### ISSUE TITLE
How to config subscribed-services in version 2.7.15 of Dubbo

### ISSUE THREAD

**Issue by doge618** [apache/dubbo#10005]
As the title see, in Dubbo 2.7.15 or later version , the `dubbo.cloud.subscribed-services` property was deprecated, how to config subscribed-services in other way other property or official document can solve my problem. At the end, thanks for the answer questions people

**Comment by chickenlj** [comment]
Please use the latest 3.x release instead. The whole instance-level service discovery mechanism has already been deprecated on 2.7.x.

**Comment by doge618** [comment]
> As the title see, in Dubbo 2.7.15 or later version , the `dubbo.cloud.subscribed-services` property was deprecated, how to config subscribed-services in other way other property or official document can solve my problem. At the end, thanks for the answer questions people

in <spring-cloud-starter-dubbo> dependency have `dubbo.cloud.subscribed-services` properties
