### ISSUE TITLE
org.apache.dubbo.common.logger.LoggerFactory default is log4j

### ISSUE THREAD

**Issue by ldkjdk** [apache/dubbo#10001]
org.apache.dubbo.common.logger.LoggerFactory default is log4j, will don't match with the log4j2 logback etc . . .
 the slf4j is default  , perhap is more best.

issue code:

static {
        String logger = System.getProperty("dubbo.application.logger", "");
        switch (logger) {
            case "slf4j":
                setLoggerAdapter(new Slf4jLoggerAdapter());
                break;
            case "jcl":
                setLoggerAdapter(new JclLoggerAdapter());
                break;
            case "log4j":
                setLoggerAdapter(new Log4jLoggerAdapter());
                break;
            case "jdk":
                setLoggerAdapter(new JdkLoggerAdapter());
                break;
            case "log4j2":
                setLoggerAdapter(new Log4j2LoggerAdapter());
                break;
            default:
                List<Class<? extends LoggerAdapter>> candidates = Arrays.asList(
                        Log4jLoggerAdapter.class,
                        Slf4jLoggerAdapter.class,
                        Log4j2LoggerAdapter.class,
                        JclLoggerAdapter.class,
                        JdkLoggerAdapter.class
                );
                for (Class<? extends LoggerAdapter> clazz : candidates) {
                    try {
                        setLoggerAdapter(clazz.newInstance());
                        break;
                    } catch (Throwable ignored) {
                    }
                }
        }
    }

**Comment by wangchengming666** [comment]
@ldkjdk 这里如果设置slf4j为默认的话，可能会影响很多的老用户

**Comment by chickenlj** [comment]
Let's just keep the default behavior not changed for now and consider changing it in the next breaking major release.
