### ISSUE TITLE
谁替代了RpcContext.getContext()

### ISSUE THREAD

**Issue by fantasylion** [apache/dubbo#10030]
dubbo 我从2.X 版本升级到了3.0.2.1 版本看到 RpcContext.getContext() 已经弃用了。请问下现在隐式参数应该怎么传，我看文档上也没有更新

**Comment by wangchengming666** [comment]
看下这个是不是你需要的 RpcContextAttachment

**Comment by fantasylion** [comment]
> 看下这个是不是你需要的 RpcContextAttachment

是不是消费者用：RpcContextAttachment.getClientAttachment().setAttachment() 传，生产者用:RpcContextAttachment.getServerAttachment().getAttachment() 取数据

**Comment by EarthChen** [comment]
> 

可以在https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-triple/ 中找一下相关样例

**Comment by chickenlj** [comment]
> > 看下这个是不是你需要的 RpcContextAttachment
> 
> 是不是消费者用：RpcContextAttachment.getClientAttachment().setAttachment() 传，生产者用:RpcContextAttachment.getServerAttachment().getAttachment() 取数据

3.0 文档我们正在完善文档中

**Comment by chickenlj** [comment]
https://dubbo.apache.org/zh/docs3-building/java-sdk/advanced-features-and-usage/rpc/context/

https://www.yuque.com/apache-dubbo/dubbo3/sw5s6w
