### ISSUE TITLE
jar冲突

### ISSUE THREAD

**Issue by gyfigher** [apache/dubbo#10032]
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>2.7.15</version>
        </dependency>

与
<dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-client</artifactId>
            <version>4.0.1</version>
        </dependency>
jar包冲突

**Comment by lianlianyi** [comment]
我也发现这个问题,先exclusion,再加进来
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
           <version>2.0.4</version>
        </dependency>

**Comment by lianlianyi** [comment]
```
       先exclusion ,再把client加进来
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.0.4</version>
        </dependency>
```

**Comment by gyfigher** [comment]
您好，非常感谢您的指导，但是我这个依赖加到pom里面了，还是报的这个错误。


| |
关颖
|
|
Tel：18438622880
***@***.***
Address: 上海浦东新区
QQ: 34513775
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年05月14日 10:53 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [apache/dubbo] jar冲突 (Issue #10032) |

       先exclusion ,再把client加进来

        <dependency>

            <groupId>org.apache.dubbo</groupId>

            <artifactId>dubbo-registry-nacos</artifactId>

            <exclusions>

                <exclusion>

                    <groupId>com.alibaba.nacos</groupId>

                    <artifactId>nacos-client</artifactId>

                </exclusion>

            </exclusions>

        </dependency>



        <dependency>

            <groupId>com.alibaba.nacos</groupId>

            <artifactId>nacos-client</artifactId>

            <version>2.0.4</version>

        </dependency>
