### ISSUE TITLE
In DubboService.java loadbalance does not have a correct default value

### ISSUE THREAD

**Issue by zeegates** [apache/dubbo#10035]
### Environment

* Dubbo version: 3.0.6
* Operating System version: windows10
* Java version: jdk1.8

### Steps to reproduce this issue

String loadbalance() default ClusterRules.EMPTY;

**Comment by zeegates** [comment]
Maybe LoadbalanceRules.EMPTY?

**Comment by yswdqz** [comment]
感觉确实是个疏忽，虽然结果上都一样。
