### ISSUE TITLE
why is dubbo-registry-redis not included in dubbo 3.x version

### ISSUE THREAD

**Issue by GreatBareBear** [apache/dubbo#10061]
Why is dubbo-registry-redis not included in dubbo 3.x version, 3.x uses redis, only dubbo-registry-redis of 2.x version can be used, and why is the db.index parameter moved after version 2.7.9 removed.

**Comment by CrazyHZM** [comment]
These extensions will be migrated to the project: https://github.com/apache/dubbo-spi-extensions
