### ISSUE TITLE
fix reproducible build issue

### ISSUE THREAD

**Issue by hboutemy** [apache/dubbo#10066]
Dubbo still has some reproducible builds issues: see https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/dubbo/README.md
and more in-depth https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/dubbo/dubbo-parent-3.0.5.diffoscope

**Comment by CrazyHZM** [comment]
Resolved in #10067
