### ISSUE TITLE
How can dubbo dynamically choose a provider using group?

### ISSUE THREAD

**Issue by a13707331174** [apache/dubbo#1007]
把接口的不同实现注册到同一个zk里,然后对不同的实现进行分组, 消费者端不想配死group,想通过传过来的一些参数,动态的选择分组的不同接口实现, 这种该如何实现呢

**Comment by chickenlj** [comment]
You should not use group, in theory, this goal should be achieved by routing. But is that dubbo do not support argument routing at this moment.  The good news is that this feature will be supported in the near future.
