### ISSUE TITLE
dubbo 2.7.15 LFUCache  Memory leak problem

### ISSUE THREAD

**Issue by zhaoguhong** [apache/dubbo#10085]
### Environment

* Dubbo version: 2.7.15
* Operating System version: mac os 10.15.7
* Java version: java8

### Description

dubbo 2.7.15 [LFUCache](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/utils/LFUCache.java) 存在严重的内存泄露问题，在触发缓存上限之前，不会清除频率表中空的队列

产生原因：这个 pr [7967]( https://github.com/apache/dubbo/pull/7967)  导致了该问题 @iiweniiang

### Test
可以看到缓存中只有一个元素，但在不断 get 的情况下，频率表却会无限制增大

![image](https://user-images.githubusercontent.com/28058794/170210418-7b326ac6-7a1d-445e-badf-fc2c9793e0f4.png)

**Comment by jk-tonycui** [comment]
I will help to check.
