### ISSUE TITLE
Is Dubbo affected by fastjson new security issue

### ISSUE THREAD

**Issue by kinkwok117** [apache/dubbo#10081]
please refer to：
https://github.com/alibaba/fastjson/wiki/security_update_20220523

**Comment by kimmking** [comment]
I found  `<fastjson_version>1.2.70</fastjson_version>` in pom.
So it does. @kinkwok117 can you submit a pr to fix it?

**Comment by chickenlj** [comment]
Already upgraded to `1.2.83`
