### ISSUE TITLE
Confusion about multiple connections

### ISSUE THREAD

**Issue by KamenRiderKuuga** [apache/dubbo#10092]
Since Nagel has been closed as @manzhizhen said, the 40ms delay should not exist, why do we still need this feature

https://github.com/apache/dubbo/blob/d42b93dfda471b448cf6ccea364ba402e58615ce/dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyClient.java#L69

https://github.com/apache/dubbo/blob/d42b93dfda471b448cf6ccea364ba402e58615ce/dubbo-remoting/dubbo-remoting-netty/src/main/java/org/apache/dubbo/remoting/transport/netty/NettyServer.java#L83

_Originally posted by @KamenRiderKuuga in https://github.com/apache/dubbo/issues/2457#issuecomment-1136918800_

**Comment by kimmking** [comment]
Generally, nagle cause a client spent 200ms delay to send data to a server. 
And delay ACK cause a server spent 40ms delay to ack client's request data, then following packets will be blocked at least 40ms.
BTW, sometimes TCP Retransmission cause 200ms and then double it in next time.
