### ISSUE TITLE
dubbo 3.x 可以生产环境用了吗？Is dubbo 3.x ready for production use?

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#10108]
Is dubbo 3.x ready for production use? it seems that dubbo has not been updated for several days, I'm worried that no one will maintain it in the future

**Comment by luger1990** [comment]
Why is there no one answer?no one maintains it~

**Comment by chickenlj** [comment]
Please check this 3.0 user case list https://github.com/apache/dubbo/issues/9436 for details.

We have a relatively regular time of releasing new versions, currently the interval between 2 versions is around 1 month.
