### ISSUE TITLE
dubbo源码mvn install 阶段多处报MojoExecutionException

### ISSUE THREAD

**Issue by Seanid** [apache/dubbo#10100]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

时间：2022-05-29
描述：通过github 获取dubbo最新源码，在本地```mvn install -Dmaven.test.skip=true```多次出现MojoExecutionException异常

首次出现是在编译dubbo-remoting-zookeeper-curator5阶段，该项目代码不多，但是是少数几个的zookeeper版本使用3.7.0，随后在
dubbo-dependencies-bom下看到配置，当Java版本>=17的时候使用3.7.0。

尝试1:将dubbo-remoting-zookeeper-curator5的zookeeper降低后，mvn install 成功

尝试2:将jdk升级到17，dubbo-remoting-zookeeper-curator5，然鹅，却会遇到proto代码生成失败，这个问题大部分出现在demo中，同样是报MojoExecutionException

最后，在本地测试的时候，本人采用的是第一种方案

**Comment by yswdqz** [comment]
请问最早使用的是jdk的什么版本？我用jdk1.8没有复现出这个错误...
