### ISSUE TITLE
给fastjson增加个扩展把

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#10107]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

给fastjson增加个扩展吧，fastjson1之前很多版本出现了安全漏洞，我们也一直建议去fastjson1 但是Dubbo强依赖了这个，无法处理，建议将json库放到扩展里面，默认可以是fastjson，后续我们提供gson jackson或者fastjson2都会方便一些

**Comment by AlbumenJ** [comment]
json 相关的重构社区最近正在推进中，预计下周机会有更详细的方案出来

**Comment by hujun-w-2** [comment]
这个已经完成了吗，有同学在生产验证吗

**Comment by AlbumenJ** [comment]
JSON 作为内部工具的通过 `-Ddubbo.json-framework.prefer=fastjson/gson` 已经是支持的了，Fastjson2 作为传输序列化方式的 3.1.0 版本中已经提供。

**Comment by hujun-w-2** [comment]
@AlbumenJ -Ddubbo.json-framework.prefer=gson这种在生产进行验证过吗，我看json工具的逻辑是如果排除掉fastjson依赖之后会自动切换到gson，我们现在是公司不建议使用fastjson，然后想直接通过排除fastjson依赖的方式来使用gson，但是不知道有没有人在生产验证过这种方式，会不会有坑

**Comment by AlbumenJ** [comment]
> @AlbumenJ -Ddubbo.json-framework.prefer=gson这种在生产进行验证过吗，我看json工具的逻辑是如果排除掉fastjson依赖之后会自动切换到gson，我们现在是公司不建议使用fastjson，然后想直接通过排除fastjson依赖的方式来使用gson，但是不知道有没有人在生产验证过这种方式，会不会有坑

 切换的逻辑应该是没问题的，至于 gson 版本不能 cover 所有使用场景的这个应该是 gson 版本的问题，Dubbo 只是简单使用了其 json 的方式
