### ISSUE TITLE
broadcast cannot apply to group

### ISSUE THREAD

**Issue by huangpang** [apache/dubbo#1010]
服务端存在： 分组1,2,3
客户端配置： group="*"

无法调用到任何服务，dubbo admin 中显示无任何提供者
调用不会报错，但无法调用到服务
通过调试源码发现，只要是group="*"都会使用MergeableCluster，而不是BroadCastCluster

如果客户端group=null，则调用报错，提示没有提供者

**Comment by beiwei30** [comment]
@huangpang pls. attach your demo application here for further investigation. thanks.

**Comment by chickenlj** [comment]
1. You should first figure out the difference of `[Broadcast](http://dubbo.io/books/dubbo-user-book/demos/fault-tolerent-strategy.html)` and `[Group Merge](http://dubbo.io/books/dubbo-user-book/demos/group-merger.html)`
2. No provider can be invoked using `group="*"`(Group Merge)
* Check again `调用不会报错，但无法调用到服务`
* I remember there's a bug in MergeableCluster, but not sure at this moment.
3. Dubbo use group/interface:version for service identification, you can never use `group=null` while all providers have a group.

**Comment by huangpang** [comment]
测试了几种配置方式，发现了以下问题：

1. 最开始无法调用到服务，是因为 group 是配置在provider标签上
<dubbo:provider group="jcj"/>
将其改到  service  之后就可以访问到(  使用的是 MergeableCluster )
与实际设想有差异

2. 客户端只要使用 gourp="*" 就会使用 MergeableCluster 调用，而且只会调用一个分组。
与实际设想有差异

3. 客户端使用指定的分组 gourp="jcj" 可以正确的调用到分组的信息。
但如果使用 goup="jcj,jcj1,jcj2" 就会变成第二条一样的效果
-----------------------------------------------------------------
配置大概如下：
服务端：
    app1():
	<dubbo:service interface="com.XXService" id="xxService" group="app1" check="false"  />
        <dubbo:service interface="com.XXService" id="xxService" group="app1" check="false"  />
    app2:
	<dubbo:reference interface="com.XXService" id="xxService" group="app2" check="false"  />
        <dubbo:reference interface="com.XXService" id="xxService" group="app2" check="false"  />

消费端：
    <dubbo:service interface="com.XXService" id="xxService" group="*" check="false"  />

   <dubbo:service interface="com.XXService" id="xxService" group="app1,app2" check="false"  />
