### ISSUE TITLE
kryo序列化引包问题

### ISSUE THREAD

**Issue by a4363220** [apache/dubbo#10105]
dubbo：3.0.8
dubbo-serialization-kryo：1.0.0
在序列化拓展包中没有排除dubbo-common模块导致项目启动报错
<dependency>
    <groupId>org.apache.dubbo.extensions</groupId>
    <artifactId>dubbo-serialization-kryo</artifactId>
    <exclusions>
        
        <exclusion>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-common</artifactId>
        </exclusion>
    </exclusions>
</dependency>

经过上面的方式排除依赖后，项目才正常启动。

还有一个疑问，我采取dubbo协议时，optimizer指定的类被加载了，但是换成tri协议却不加载请问这是什么原因？
  # 协议名称
  name: tri
  # 序列化配置
  serialization: kryo
  # 序列化对象配置实现
  optimizer: com.grain.pay.service.api.serialization.SerializationOptimizerImpl

**Comment by AlbumenJ** [comment]
> 在序列化拓展包中没有排除dubbo-common模块导致项目启动报错

这个我尝试在下一个 dubbo-serialization-kryo 版本中修复一下

> 采取dubbo协议时，optimizer指定的类被加载了，但是换成tri协议却不加载请问这是什么原因？

@guohao @EarthChen 麻烦帮忙看一下

**Comment by EarthChen** [comment]
`Triple` 协议没有注册`optimizer`, 我这边最近 fix 一下
