### ISSUE TITLE
AbstractRegistry构造函数中调用notify方法是不是没什么用？

### ISSUE THREAD

**Issue by liwanghonggc** [apache/dubbo#10114]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Dubbo AbstractRegistry构造函数中最后会调用notify(url.getBackupUrls())方法，但是感觉这个方法好像没做什么东西，有大佬指导下么。

**Comment by chickenlj** [comment]
主要用于注册中心连不上之时通知缓存在本地的地址快照
