### ISSUE TITLE
springcloud alibaba 现在可以集成dubbo3吗？

### ISSUE THREAD

**Issue by multiLJT** [apache/dubbo#10116]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by multiLJT** [comment]
springcloud-alibaba-dubbo没看到集成dubbo3的例子

**Comment by simonally** [comment]
还没有，现在还在改BUG吧，没稳定下来

**Comment by JavaLionLi** [comment]
springcloud-alibaba 社区已经宣布移除dubbo了

**Comment by chickenlj** [comment]
目前基于 Dubbo3 的应用级服务发现模型和 rest 协议，Dubbo 和 Spring Cloud 在服务发现和通信层面已经是打通的

**Comment by chickenlj** [comment]
我们稍后可在 samples 通过提供 Dubbo 和 Spring Cloud 互调的 demo 来进一步解释
