### ISSUE TITLE
Critical bug: Consistency loadbalance cause the CPU usage is 100%.

### ISSUE THREAD

**Issue by xiaotongwang1** [apache/dubbo#10111]
### Environment

* Dubbo version: 2.7.15

### Steps to reproduce this issue

Dubbo一致性Hash loadbalance存在缺陷，会导致CPU100%

Due to a defect in the hash load balance of Dubbo consistency, the CPU usage is 100%.

**Comment by xiaotongwang1** [comment]
@AlbumenJ 
![image](https://user-images.githubusercontent.com/6071261/173525457-a26d75cb-19b3-4bb0-a988-e258a6552a72.png)

**Comment by xiaotongwang1** [comment]
@[laddcn](https://github.com/laddcn)
can you recheck you pr :https://github.com/apache/dubbo/pull/8948

**Comment by xiaotongwang1** [comment]
![image](https://user-images.githubusercontent.com/6071261/173722032-557b9d68-5ab1-4962-9df4-1d9152ff629d.png)

**Comment by xiaotongwang1** [comment]
@[laddcn](https://github.com/laddcn) @AlbumenJ @[chickenlj](https://github.com/chickenlj)
当前这块代码存在死循环的BUG，这个代码能否回滚？

**Comment by edhn3000** [comment]
问一下这个问题在2.7.x中修复了吗

**Comment by edhn3000** [comment]
我这里使用的是version 2.7.18，遇到一致性hash负载占用cpu高的问题，请问这个问题在2.7.x有修复吗
dump看线程都是在执行org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalance.ConsistentHashSelector#selectForKey
看了下火焰图在getHigherEntry中比较应该是比较占用cpu的
![fire_1](https://user-images.githubusercontent.com/7310121/212655741-7b6775a5-6388-4e14-828a-284b54bbac2d.png)

![fire_2](https://user-images.githubusercontent.com/7310121/212655774-3c2444ef-10ec-4de8-b2b5-a635907e3de9.png)

![fire_3](https://user-images.githubusercontent.com/7310121/212655799-fe1516d1-a824-49c6-a2c5-1d53caf9fb92.png)

**Comment by AlbumenJ** [comment]
> 我这里使用的是version 2.7.18，遇到一致性hash负载占用cpu高的问题，请问这个问题在2.7.x有修复吗 dump看线程都是在执行org.apache.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalance.ConsistentHashSelector#selectForKey 看了下火焰图在getHigherEntry中比较应该是比较占用cpu的 ![fire_1](https://user-images.githubusercontent.com/7310121/212655741-7b6775a5-6388-4e14-828a-284b54bbac2d.png)
> 
> ![fire_2](https://user-images.githubusercontent.com/7310121/212655774-3c2444ef-10ec-4de8-b2b5-a635907e3de9.png)
> 
> ![fire_3](https://user-images.githubusercontent.com/7310121/212655799-fe1516d1-a824-49c6-a2c5-1d53caf9fb92.png)

Fix in 3.x. 2.7.x is only for security maintian now.
