### ISSUE TITLE
demo中缺少了这两个类

### ISSUE THREAD

**Issue by xmgh1024** [apache/dubbo#10122]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
![image](https://user-images.githubusercontent.com/50412181/172131274-09599a6b-e624-43b6-b179-2be2400c4483.png)

**Comment by CrazyHZM** [comment]
This is generated by IDL, and it can be generated by compiling.
