### ISSUE TITLE
 Dubbo3.0.5 Consumer端自定义线程池参数失效

### ISSUE THREAD

**Issue by lx20091901** [apache/dubbo#10120]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment
Dubbo version: 3.0.5
Operating System version: macOS
Java version: 8

### Steps to reproduce this issue

1.Provider端设置-Ddubbo.application.register-mode=instance 仅启用应用级注册并启动
2.Consumer端设置自定义线程池参数
    dubbo.consumer.threadpool=cached
    dubbo.consumer.corethreads=5
    dubbo.consumer.threads=100
    dubbo.consumer.queues=1000
3.Consumer端启动并查看DefaultExecutorRepository.createExecutorIfAbsent()方法中查看consumer端共享的线程池配置

### Expected Behavior

Cousumer端共享的线程池按照自定义的参数生成。

### Actual Behavior

实际生成的线程池参数是默认的，自定义的参数未生效。
如下图所示，第一个初始化的接口为MetadataService，url在StandardMetadataServiceURLBuilder#build构造过程中缺失可自定义的参数的处理逻辑，导致consumer端共享的portKey为2147483647的线程池为默认的线程池，无法支持自定义参数。
![image](https://user-images.githubusercontent.com/6487236/172113124-4005689d-e0f1-4eb2-a1d2-64181e807758.png)
为了证明不是配置的错误，贴上provider双注册的情况下consumer线程池的url信息
![image](https://user-images.githubusercontent.com/6487236/172114061-edc45cd1-20f9-4cd8-819a-68930f0af5d1.png)

3.0.8版本中instance中多加了一个side字段，在3.0.8版本中此问题不会复现，但应该只是凑巧不是修复的思路吧
![image](https://user-images.githubusercontent.com/6487236/172114678-2a356303-8498-4d06-b627-2cbe3cf62ab1.png)

**Comment by AlbumenJ** [comment]
这个失效是只有 MetadataService 服务还是所有消费端服务都失效了

**Comment by lx20091901** [comment]
> 这个失效是只有 MetadataService 服务还是所有消费端服务都失效了

所有的都失效了，只要side是consumer都会复用这个共享的线程池，不会根据URL中的参数再去初始化了

**Comment by AlbumenJ** [comment]
@lx20091901 麻烦可以提供个 demo 吗，我最近尝试修复下～

**Comment by lx20091901** [comment]
@AlbumenJ 就拿3.0.5源码里面spring-boot的demo就行，按照上述的配置步骤

**Comment by AlbumenJ** [comment]
Fix in #10148
