### ISSUE TITLE
dubbo官方【中文】文档三天两头的打不开

### ISSUE THREAD

**Issue by hoset** [apache/dubbo#10130]
最近再学习dubbo，目前遇到的最大障碍就是，官网文档三天两头打不开，好不容易文档可以看了，部分目录下面的内容又打不开，一开始以为是网络的问题，后面发现，用5G也是一样的。

[文档地址](https://dubbo.apache.org/zh/)

**Comment by chickenlj** [comment]
我们看一下是哪里的问题，可能是资源文件影响了加载速度
