### ISSUE TITLE
Dubbo3.0.8 应用级发现Group通配符失效

### ISSUE THREAD

**Issue by lx20091901** [apache/dubbo#10163]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.8
* Operating System version: macOS
* Java version: 8

### Steps to reproduce this issue

1. 服务提供者中有同一接口不同Group的两个实现
2. 服务提供者仅开启应用级注册并启动
3. 消费者中引用中设置@DubboReference(group = "*") 
4. 启动消费者

### Expected Behavior

消费者能引用到服务提供者

### Actual Behavior

启动报错，找不到服务提供者

![image](https://user-images.githubusercontent.com/6487236/173790033-645cae28-922d-4318-90de-249a5d8e6d34.png)

在org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.getAddresses方法中，没有特殊处理通配符*

![image](https://user-images.githubusercontent.com/6487236/173790621-a521fedd-43cd-4701-b8d8-40e2722049f7.png)

**Comment by MichaelDeSteven** [comment]
![image](https://user-images.githubusercontent.com/51652084/173989463-2c09d9de-f01e-45cf-9b0f-ea871bc74c8d.png)
应该是这里缺少了通配符处理

**Comment by chickenlj** [comment]
这个是已知问题，3.0 应用级服务发现版本中暂时没有兑现这个功能。我们争取在接下来的 3.0.10 版本中支持
