### ISSUE TITLE
dubbo3.0.6之后当服务内没有需要暴露的dubbo服务，nacos就没法注册上去

### ISSUE THREAD

**Issue by a937282042** [apache/dubbo#10172]
` <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>3.0.8</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>3.0.8</version>
            <exclusions>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo-remoting-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

用3.0.6的版本空服务也能够注册到nacos去，用3.0.6以后的版本必须要有service暴露在dubbo才能够nacos注册成功

**Comment by chickenlj** [comment]
对于应用级服务发现，现在的行为是：至少有一个服务（Interface）暴露，才会往注册中心注册地址。

**Comment by misaya98** [comment]
> 对于应用级服务发现，现在的行为是：至少有一个服务（Interface）暴露，才会往注册中心注册地址。

如果一个服务是单纯的dubbo consumer 则不会出现在nacos 的服务列表内吗？ 
也不会出现在订阅者列表内？（3.0.9目前的表现是这样的）。
