### ISSUE TITLE
dubbo启动服务会自动注册一个DEFAULT_GROUP的服务，这个分组各种自定义均无效，所以重启这个issue，下图已试过，无效告终

### ISSUE THREAD

**Issue by DspringL** [apache/dubbo#10174]
环境版本：

Dubbo Version: 3.0.8
Nacos Server：2.1.0
Nacos Client：2.0.2
Operating System version: mac
Java version: 11

dubbo启动服务会自动注册一个DEFAULT_GROUP的服务，这个分组各种自定义均无效，所以重启这个issue，下图已试过，无效告终

<img width="621" alt="image" src="https://user-images.githubusercontent.com/29829184/174410689-53d6e562-8e0d-4568-9a49-85ed87145db4.png">

**Comment by DspringL** [comment]
经过验证，在dubbo-registry-nacos:2.7.7解决了该问题，之后的3.x版本均存在该问题

**Comment by liuwawa** [comment]
同样遇到该问题，Dubbo Version: 3.0.8设置group无效，dubbo在nacos中都显示DEFAULT_GROUP

**Comment by chickenlj** [comment]
> 同样遇到该问题，Dubbo Version: 3.0.8设置group无效，dubbo在nacos中都显示DEFAULT_GROUP

使用的应用级服务发现还是接口级服务发现？

1. 应用级服务发现中，注册中心被设计使用固定的 DEFAULT_GROUP；
2. 接口级服务发现中，注册中心group配置应该是没有问题的；

**Comment by chickenlj** [comment]
![image](https://user-images.githubusercontent.com/18097545/174722102-9700c26e-6c7c-42ec-8a8b-d1a862e2e55d.png)
这个图里显示的 “服务名” 都是应用名么？如果是的话，那 Dubbo3 目前是只支持注册到 DEFAULT_GROUP 的。

**Comment by DspringL** [comment]
@chickenlj 2.7.15的版本支持自定义group，是否可以考虑合并2.7.15的自定义group到3.x的版本中来呢

**Comment by AlbumenJ** [comment]
> @chickenlj 2.7.15的版本支持自定义group，是否可以考虑合并2.7.15的自定义group到3.x的版本中来呢

Related pr https://github.com/apache/dubbo/pull/10253

**Comment by TOP-LH** [comment]
> > @chickenlj 2.7.15的版本支持自定义group，是否可以考虑合并2.7.15的自定义group到3.x的版本中来呢
> 
> Related pr https://github.com/apache/dubbo/pull/10253

请问这个发布到maven仓库了吗，不然没办法用呀

**Comment by AlbumenJ** [comment]
> > > @chickenlj 2.7.15的版本支持自定义group，是否可以考虑合并2.7.15的自定义group到3.x的版本中来呢
> > 
> > 
> > Related pr #10253
> 
> 请问这个发布到maven仓库了吗，不然没办法用呀

由于改动面偏大，社区决定在 3.1 版本中再正式修复这个问题。3.1.0 版本预计在下个月中正式发布，支持 3.0.x 平滑迁移
