### ISSUE TITLE
关于fastjson 1.2.80及以下存在新的风险

### ISSUE THREAD

**Issue by ormor** [apache/dubbo#10186]
如下链接，请问有fastjson的升级计划么

https://github.com/alibaba/fastjson/wiki/security_update_20220523

**Comment by wangchengming666** [comment]
目前dubbo已经升级到1.2.83，并且在支持fastjson2, https://github.com/apache/dubbo/pull/10166

**Comment by ormor** [comment]
> 目前dubbo已经升级到1.2.83，并且在支持fastjson2, #10166

谢谢，2.7.x版本的有升级么，看release是3.x版本的有更新至1.2.83版本。

**Comment by wangchengming666** [comment]
> > 目前dubbo已经升级到1.2.83，并且在支持fastjson2, #10166
> 
> 谢谢，2.7.x版本的有升级么，看release是3.x版本的有更新至1.2.83版本。

https://github.com/apache/dubbo/pull/10189
