### ISSUE TITLE
Unable to consume multi-group correctly

### ISSUE THREAD

**Issue by xxxcrel** [apache/dubbo#10196]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.x
* Operating System version: Mac os
* Java version: 1.8.0_301

### Steps to reproduce this issue

precondition:
1. 接口级别注册(经查看相关issue, 3.x的应用级别注册暂不支持分组聚合)
2. nacos为注册中心

setp:
1. start [merge-sample](https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-merge)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
The results merge correctly

### Actual Behavior
only call providerA 

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
nacos 上的 group 和服务的 group 的定义应该是不一样的

**Comment by xxxcrel** [comment]
在修复应用级注册分组聚合时尝试更改过以下代码来支持泛匹配:(似乎能够成功获取正确的group并创建Invoker, 但是在rpc call时传到provider的attachment:group为consumer端配置的group(如"providerA,providerB"或“*”), 而provider端getInvoker时会出现错误)
https://github.com/apache/dubbo/blob/7a33ddf93c43f9de8e45e7bc80a22a04beecf654/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java#L375-L377
https://github.com/apache/dubbo/blob/7a33ddf93c43f9de8e45e7bc80a22a04beecf654/dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java#L232-L241

**Comment by xxxcrel** [comment]
> 在修复应用级注册分组聚合时尝试更改过以下代码来支持泛匹配:(似乎能够成功获取正确的group并创建Invoker, 但是在rpc call时传到provider的attachment:group为consumer端配置的group(如"providerA,providerB"或“*”), 而provider端getInvoker时会出现错误)
> 
> https://github.com/apache/dubbo/blob/7a33ddf93c43f9de8e45e7bc80a22a04beecf654/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/event/listener/ServiceInstancesChangedListener.java#L375-L377
> 
> 
> https://github.com/apache/dubbo/blob/7a33ddf93c43f9de8e45e7bc80a22a04beecf654/dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/MetadataInfo.java#L232-L241

```Java
    protected List<URL> getAddresses(String serviceProtocolKey, URL consumerURL) {
        if (serviceProtocolKey.contains("/")) {
            int groupDelimiterIndex = serviceProtocolKey.indexOf("/");
            String groupKey = serviceProtocolKey.substring(0, groupDelimiterIndex);
            String withoutGroupServiceKey = serviceProtocolKey.substring(groupDelimiterIndex);
            List<URL> urls = new ArrayList<>();
            if ("*".equals(groupKey)) {
                for (String s : serviceUrls.keySet()) {
                    if (s.endsWith(withoutGroupServiceKey)) {
                        urls.addAll((List<URL>) serviceUrls.get(s));
                    }
                }
            } else if (COMMA_SPLIT_PATTERN.split(groupKey).length > 1) {
                String[] groups = groupKey.split(",");
                for (String group : groups) {
                    if (serviceUrls.containsKey(group + withoutGroupServiceKey)) {
                        urls.addAll((List<URL>) serviceUrls.get(group + withoutGroupServiceKey));
                    }
                }
            }
            if (!CollectionUtils.isEmpty(urls)) {
                return urls;
            }
        }
        return (List<URL>) serviceUrls.get(serviceProtocolKey);
    }
```

**Comment by liuyz60** [comment]
这个是Nacos的问题，不管哪个版本的dubbo都会出现这种情况。
Nacos服务注册时，url中不支持逗号和星号，但在分组聚合的服务路径中，具有逗号或星号，所以注册失败。
[这个问题我提到过，但没人理会](https://github.com/apache/dubbo/issues/10043)

**Comment by xxxcrel** [comment]
> 这个是Nacos的问题，不管哪个版本的dubbo都会出现这种情况。 Nacos服务注册时，url中不支持逗号和星号，但在分组聚合的服务路径中，具有逗号或星号，所以注册失败。 [这个问题我提到过，但没人理会](https://github.com/apache/dubbo/issues/10043)

似乎不太一样, 而且consumer是订阅服务, 为什么要注册, 是不是你把provider的group设为多个分组或*了

**Comment by AlbumenJ** [comment]
可以考虑把 getAddresses 改成支持批量获取的，然后遍历 serviceUrls 按照类似前缀树进行匹配

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/10256
