### ISSUE TITLE
不同timeout时间的引用service导致不能正常关闭&无限重连报错

### ISSUE THREAD

**Issue by dlmu-lq** [apache/dubbo#10206]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: mac/linux
* Java version: 1.8

### Steps to reproduce this issue

1. 分别创建一个provider、一个consumer项目，其中provider中的同一个service被consumer中两次引用，但是在注解中使用不同的timeout，如下：

        @DubboReference
        SayRpcService sayRpcService;

        @DubboReference(timeout = 2000)
        SayRpcService sayRpcService2;

2. 启动两个provider，一个consumer
3. 正常关闭其中一个provider，debug发现consumer没有正常关闭与已关闭provider之间的连接，并且ReconnectTaskTimer继续不停的每1分钟尝试连接，进行error报错

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

provider关闭后，consumer正常关闭对应资源，不再重连

### Actual Behavior

provider关闭后，consumer不能正常关闭对应资源，无限重连

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
以下是我debug发现的问题所在：

服务启动时，进行服务的refer，由于DubboReference的timeout参数不同，这里url重复了一个，可以发现，进行去重后，urls少了一半，所以后面refer服务时，refer了两次，但是ServiceDiscoveryRegistryDirectory.urlInvokerMap中只保存了一个，provider关闭时，只关闭了一个，导致ReferenceCountExchangeClient的count值increment2次，decrement1次，不能进行实际的close，不确定把这里的urls进行去重后会不会产生别的问题，如果能解决，可提交pr。如果大佬们有更好的解决方法，辛苦帮忙解决下！

![image](https://user-images.githubusercontent.com/29395234/175456978-805ec746-8c7d-4cc7-83f2-d2e911d57b10.png)

**Comment by AlbumenJ** [comment]
你可以试下 3.0.9 版本，我这边 3.0.9 版本是正常的，3.0.7 版本复现了

**Comment by dlmu-lq** [comment]
> 你可以试下 3.0.9 版本，我这边 3.0.9 版本是正常的，3.0.7 版本复现了

验证了，3.0.9正常
