### ISSUE TITLE
[Feature] The server interface supports specifying thread pools

### ISSUE THREAD

**Issue by EarthChen** [apache/dubbo#10201]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

Related issue #10154

I have a service with two interfaces, and I want to be able to assign separate thread pools to the interfaces.

```
interface 1 ---> thread pool 1
interface 2 ---> thread pool 2
```

## Background

In the same service, if an interface is full of thread pools for some reason, the entire service will be unavailable at this time. This is unacceptable.

Currently dubbo uses ports to determine the thread pool, so it will cause the entire server to share the thread pool.

**Comment by guohao** [comment]
Thread pool Isolation is a crucial feature for QoS, anyone can help to support it?

**Comment by wangchengming666** [comment]
pls assign to me
