### ISSUE TITLE
杀死provider后 metadata下有遗留数据，看着不正常

### ISSUE THREAD

**Issue by TXYan** [apache/dubbo#10204]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo 3.0.8，zk注册中心，杀死进程后metadata下还有被杀死进程的数据，这个是正常的吗？

**Comment by AlbumenJ** [comment]
这部分metadata数据是缓存在元数据中心中的，所以进程退出后是不会清理的。

**Comment by TXYan** [comment]
interface/version/side/application   这样的路径存储的数据  是监听变更用的吗？新数据会覆盖老数据 理解的对吗

**Comment by AlbumenJ** [comment]
有新数据会覆盖老数据的
