### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by linqiny** [apache/dubbo#10219]
利用dubbo进行小文件二进制byte[]传输时，在提供方端byte[]对象无法被回收导致内存溢出

版本        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-dubbo</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>
![图片](https://user-images.githubusercontent.com/42114432/176071761-8926b11b-cc4f-4735-bcdd-d5e8a521f838.png)

![图片](https://user-images.githubusercontent.com/42114432/176077119-75268e4e-1193-4d8a-aefa-40d1d454c9fb.png)

![图片](https://user-images.githubusercontent.com/42114432/176077148-53198b95-70e4-4866-92f2-e95c03b3da24.png)

**Comment by AlbumenJ** [comment]
能看下那个 threadlocal 是被哪个类所持有的吗

**Comment by icodening** [comment]
该问题可以必现，在``Hessian2ObjectInput``中的ThreadLocal，关联了``Hessian2Input``, 而该对象又关联了一个``UnsafeByteArrayInputStream``，该流会引用一个完整的byte[]数组

**Comment by AlbumenJ** [comment]
> 该问题可以必现，在`Hessian2ObjectInput`中的ThreadLocal，关联了`Hessian2Input`, 而该对象又关联了一个`UnsafeByteArrayInputStream`，该流会引用一个完整的byte[]数组

这个 ThreadLocal 是可以删掉的，在 3.0 分支已经移除了，你方便帮忙提个 pr 在 2.7 的分支修复下吗

**Comment by icodening** [comment]
> > 该问题可以必现，在`Hessian2ObjectInput`中的ThreadLocal，关联了`Hessian2Input`, 而该对象又关联了一个`UnsafeByteArrayInputStream`，该流会引用一个完整的byte[]数组
> 
> 这个 ThreadLocal 是可以删掉的，在 3.0 分支已经移除了，你方便帮忙提个 pr 在 2.7 的分支修复下吗

嗯嗯 可以的

**Comment by xishian** [comment]
> 该问题可以必现，在`Hessian2ObjectInput`中的ThreadLocal，关联了`Hessian2Input`, 而该对象又关联了一个`UnsafeByteArrayInputStream`，该流会引用一个完整的byte[]数组

观察到的现象就是堆外内存不断升高，直到OOM？
