### ISSUE TITLE
[3.0-Triple] Support server reflection

### ISSUE THREAD

**Issue by guohao** [apache/dubbo#10235]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

Provide reflection API to simplify test and interoperation with gateway.

For test, users can adopt [grpcui](https://github.com/fullstorydev/grpcui) or [grpcurl](https://github.com/fullstorydev/grpcurl).

**Comment by mark4z** [comment]
how to use it?

**Comment by mark4z** [comment]
Upgrade dubbo dependency to 3.0.10
Dubbo compiler also upgrade to 3.0.10
then mvn clean package, try it.

**Comment by fffguo** [comment]
当前版本3.2.0，使用tri
配置 dubbo.tri.builtin.service.init 为true，即可使用


<img width="1117" alt="image" src="https://github.com/apache/dubbo/assets/27751972/1da52bbc-e9bf-46a4-ba33-d0a4ea17b10f">
