### ISSUE TITLE
What is the minimum version of Nacos required for Dubbo 3 and above？

### ISSUE THREAD

**Issue by xiongwu1** [apache/dubbo#10232]
We tried to upgrade from version 2.7 to version 3 x. It is found that the application has registered with Nacos, but the interface called by the consumer has timed out all the time.  The consumer has not been upgraded

Nacos version: 2.0.3
Dubbo version: 3.0.9

**Comment by AlbumenJ** [comment]
Nacos 2.x supports Dubbo 3.x

**Comment by xiongwu1** [comment]
However, after upgrading the provider,  the consumer request timed out. The consumer not upgrade.
Nacos content:
![image](https://user-images.githubusercontent.com/15642586/176362053-c20a1787-5062-4b65-89e1-2e595e156067.png)

Error message:
![image](https://user-images.githubusercontent.com/15642586/176362386-63aef4b5-b080-44f4-845f-b91821b8d091.png)

**Comment by AlbumenJ** [comment]
This is not the problem of registry. Please check if network is available from 10.0.0.0/8 to 172.0.0.0/8

**Comment by AlbumenJ** [comment]
The exception is means 10.0.1.30 unable to connect to 172.18.0.16.

**Comment by xiongwu1** [comment]
Looks like question #9737

**Comment by xiongwu1** [comment]
So what is the final solution?  
the DUBBO_IP_TO_BIND way fixed IP is not realistic
Our solution is start parameter addition: -Ddubbo.network.interface.preferred=eth0
