### ISSUE TITLE
应用级注册下单协议多端口的支持

### ISSUE THREAD

**Issue by dadadadudu** [apache/dubbo#10238]
### Environment
* Dubbo version: 3.0.7
* Java version: 1.8

### Steps to reproduce this issue
一个实例下，一个协议，对应多个端口的情况下，在进行应用级注册时，只会取其中一个端口，另外一个端口会失效

![1656485774830_988CBFE5-8DE3-41ef-B309-12E07BE400C1](https://user-images.githubusercontent.com/8710756/176374844-440fde59-66fd-4318-9c55-3c1a711d9271.png)

### Expected Behavior
对于服务消费端者来说多个端口都要能使用，目前只能用其中一个

### Actual Behavior
代码里有个todo，解释的就是这个问题
![1656485787347_6A73BE4F-7625-417f-9784-8E8873A4297C](https://user-images.githubusercontent.com/8710756/176375326-5eb00788-2d78-4e43-8187-8607a94ded15.png)

### 初步解决方案
可以在endpoints中记录一下其他端口信息，比如新加一个multi-endpoints

**Comment by chickenlj** [comment]
此使用方式已在 3.0.11 或 3.1.0 版本中实现支持使用， 参见 https://github.com/apache/dubbo/pull/10256
