### ISSUE TITLE
配置文件超时时间设置失败

### ISSUE THREAD

**Issue by LINnil00** [apache/dubbo#10254]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: win 10
* Java version: 1.8

### Steps to reproduce this issue

1. 设置yml 配置文件如下 添加ZK超时时间
2. `dubbo:
  application:
    name: user-service-provider
  registry:
    address: 192.168.229.130:2181
    protocol: zookeeper
    timeout: 8000`
3. 运行dubbo
4. Debug 发现ZK超时时间默认为3000毫秒，设置失败
![企业微信截图_16566604094775](https://user-images.githubusercontent.com/37575483/176848545-e7d46412-a305-4eaa-9e29-474b83c64bc3.png)
可能是这里缺失对timeout的get、set方法
而timeout在此处被写死了
![企业微信截图_1656661419201](https://user-images.githubusercontent.com/37575483/176848801-5c705a47-0ddb-4165-903a-2d43ed960da8.png)

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by LINnil00** [comment]
@AlbumenJ please take a look, thanks!

**Comment by jk-tonycui** [comment]
<img width="1440" alt="截屏2022-07-03 下午6 05 48" src="https://user-images.githubusercontent.com/57054315/177034923-67f26fbb-38b5-40b3-9f65-539b94916ab8.png">

The config seem to be loaded correctly.

**Comment by AlbumenJ** [comment]
@LINnil00 看起来是低版本的问题，升级到最新版本试下呢

**Comment by LINnil00** [comment]
升级后问题解决了，谢大佬！
