### ISSUE TITLE
dubbo3.0 provider调用别的provider接口失败

### ISSUE THREAD

**Issue by fangg2021** [apache/dubbo#10265]
spring boot 2.6.4
dubbo3.0.9
zookeeper3.8.0/nacos2.1

问题如下：
    有两个provider项目A和B，一个consumer项目C，目前三个项目能正常启动，C单独调用A或者B服务的接口时都没有问题，但C调B，而B的接口中又调用A时，此时报异常（org.apache.dubbo.rpc.RpcException: Failed to invoke the method providerTestA in the service...），其中B的dubbo配置如下：

spring.application.name=dubbo-test-provider
dubbo.application.name=${spring.application.name}
#dubbo.registry.address=zookeeper://192.168.31.131:2181
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=20886
dubbo.cloud.subscribedServices=dubbo-test-rpc-provider
dubbo.consumer.check=false
dubbo.registry.check=false

demo.service.version=1.0.0
dubbo.consumer.filter=consumerFilter
dubbo.provider.filter=providerFilter

![image](https://user-images.githubusercontent.com/80429579/177072573-c6b9cde9-69a2-4047-aa8d-b63218ae22bf.png)
![image](https://user-images.githubusercontent.com/80429579/177072699-b424555d-79e0-43cf-bd32-9320403215cd.png)

其中包括check=false、version、group等都测试过，但全部失败了，哎，这个不知道是什么BUG，有谁知道或好建议的请不吝占用楼下，非常感谢！！！
我现在先使用以前的版本测试去了。

**Comment by AlbumenJ** [comment]
这个看起来是服务端没有发布这个服务却调用进去了

**Comment by fangg2021** [comment]
> 这个看起来是服务端没有发布这个服务却调用进去了

看起来的确是这样子，事实是服务已经发布了，用nacos作注册中心时在nacos 后台会看到相应的服务（RpcCoreService），所以这个BUG很诡异……另外，看到最后那个UserConfigService with version 1.0.0 not found没有？（本身就是在UserConfigService服务里面调用别的接口，但它说自己迷路了，我也没办法）

**Comment by AlbumenJ** [comment]
这个拆一个简单的测试demo出来嘛，我来跑下看看

**Comment by fangg2021** [comment]
> 这个拆一个简单的测试demo出来嘛，我来跑下看看

想搞个DEMO给你的，想不到顺便把问题搞定了（算是吧）……
问题出现在我使用了dubbo filter，而其中在使用context.getObjectAttachments()传递参数时（COPY了 org.apache.dubbo.rpc.filter.ContextFilter源码的部分内容）可能覆盖了一些重要的参数，要是只传自己想传的参数就没有问题。

嗯，需要说明的是，如果没有使用dubbo filter，直接provider服务接口之间调用的话是没有任何问题的，这个我写的标题可能有点不合适，非常感谢你的支持。
