### ISSUE TITLE
How about using guard clause to refactor nested if else clause?

### ISSUE THREAD

**Issue by cheese8** [apache/dubbo#10267]
The guard clause:
1、usually means less code and simpler code flow with less if/else nesting.
2、it clearly indicates that current method is not interested in certain cases.

**Comment by cheese8** [comment]
> would you please provide a example?

For example : 

using guard clause to refactor the 4 depth nesting if else in CacheFilter #10274

**Comment by AlbumenJ** [comment]
> > would you please provide a example?
> 
> For example : @AlbumenJ
> 
> using guard clause to refactor the 4 depth nesting if else in CacheFilter #10274

This seems good!
