### ISSUE TITLE
JSON序列化时有必要换行吗

### ISSUE THREAD

**Issue by lanicc** [apache/dubbo#10296]
[FastJsonObjectOutput.writeObject](https://github.com/apache/dubbo/blob/3ec1bee643d9c52808a970b64f206cd24f9b14e5/dubbo-serialization/dubbo-serialization-fastjson/src/main/java/org/apache/dubbo/common/serialize/fastjson/FastJsonObjectOutput.java#L104)
没有必须要在后面追加个换行符吧，`writer.println()`这行应该是多余的
GsonJsonObjectOutput 也一样

**Comment by AlbumenJ** [comment]
这里主要是读取的时候要分隔开来

**Comment by lanicc** [comment]
谢谢，前面粗心了没看到这一块
