### ISSUE TITLE
Dubbo3.0.9 执行InstanceAddressURL.getServiceNumbers时可能会空指针

### ISSUE THREAD

**Issue by xiangzz159** [apache/dubbo#10303]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.9
* Operating System version: MacOS 10.15.7
* Java version: 1.8.0_231

### Steps to reproduce this issue

1. InstanceAddressURL.getValidServiceInfo(String serviceKey)可能返回为null
2. 执行方法InstanceAddressURL.getServiceNumbers(String protocolServiceKey)时会报空指针异常

![image](https://user-images.githubusercontent.com/16982273/178272297-cc1bac0f-16a9-497d-83eb-7152023c9df3.png)

![image](https://user-images.githubusercontent.com/16982273/178272080-c959a9ed-d43e-4d12-b7b3-f1c316b259e0.png)

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by cheese8** [comment]
什么场景下报的NPE？

**Comment by chenziqiang666** [comment]
@i will solve it@

**Comment by xiangzz159** [comment]
> 

我是使用dubbo-admin时候发现服务启动一段时间后会异常报错，排查后发现是url.getParameter(String key, int defaultValue)的时候空指针异常，所以做了如下修改
![image](https://user-images.githubusercontent.com/16982273/178395634-5eba69bb-da40-45d7-be7b-6495c989eea5.png)

**Comment by wangchengming666** [comment]
fixed by https://github.com/apache/dubbo/pull/10306, so closed
