### ISSUE TITLE
How to implement Canary release base on dubbo architecture？

### ISSUE THREAD

**Issue by sungy2014** [apache/dubbo#1030]
dubbo version: 2.5.3

**Comment by chickenlj** [comment]
Usually, developers use route rule to achieve canary release, `arguments` and `attachments` can be important factors.  In theory, you can add script route rules to achieve argument routing.

**Comment by ralf0131** [comment]
@chickenlj What should we do in this issue?

**Comment by AlbumenJ** [comment]
You can implement Canary release with tag router or argument router.
