### ISSUE TITLE
您好，最近升级到2.7.15，发现tomcat启动异常时会触发ReferenceAnnotationBeanPostProcessor  was destroying 

### ISSUE THREAD

**Issue by sq-young2** [apache/dubbo#10322]
此时提供者为无法使用的状态，如果此时启动消费者，消费者无法消费服务，哪怕后续提供者完全恢复后，还是报错om.alibaba.dubbo.rpc.RpcException: Rpc cluster invoker for interface xxx on consumer 10.2.4.63 use dubbo version 2.7.15 is now destroyed! Can not invoke any more.
暂时未排查出原因

**Comment by sq-young2** [comment]
问题比较棘手，大佬看到后指导一下哦，谢谢了

**Comment by neighbor-uncleWang** [comment]
版本号：2.6.0.2；是不是有个地方的包没有升级成功呢

**Comment by sq-young2** [comment]
应该不会，因为其他功能都是正常的

**Comment by sq-young2** [comment]
2.6.0.2 是dubbo的版本吗

**Comment by sq-young2** [comment]
我刚刚测试了把ReferenceAnnotationBeanPostProcessor 的destroy注释，还是一样的情况

**Comment by sq-young2** [comment]
不好意思，因为代码在内网，问题描述是拷贝的，版本没有修改，已经修改正常

**Comment by neighbor-uncleWang** [comment]
可以提供一个简易的demo，以供测试吗？

**Comment by sq-young2** [comment]
因为项目比较复杂，框架基础上面做的，能提供写排查思路吗，从现象看，应该是提供者没有通知到消费者

**Comment by sq-young2** [comment]
我在消费者dubbo配置里面，设置了<dubbo:consumer check="false" > 貌似问题解决了，提供者恢复后，消费者会刷新服务，是不是新版本的启动检查做了什么严格性的校验，我以前的版本是当当的2.8.4，版本比较老

**Comment by AlbumenJ** [comment]
排查下是不是消费端启动的时候服务端还没启动，或者注册中心有没有对应推送

**Comment by mz0113** [comment]
理论上 check=true时候，提供方不在线，消费方不是直接就起不来吗。

**Comment by AlbumenJ** [comment]
> 理论上 check=true时候，提供方不在线，消费方不是直接就起不来吗。

是的，check 就是为了检查服务端是否已经发布了

**Comment by sq-young2** [comment]
您好， 有关之前的问题，我大致说明一下，底层初始化时候会触发getBean的操作，并且做了异常捕获，所以check=true的情况虽然获取不到消费者bean，还是不影响应用启动的。但是为何check设置为fasle我的问题解决暂时未查明原因，不管怎么样目前已经解决我的问题，有时间再继续研究下，感谢各位大佬的回复。

**Comment by sq-young2** [comment]
或许是因为在custom:check=true 的情况下，初始化时候，已经标记提供者为destroy状态，并不会再进行更新状态，表现是强依赖的；然后check=false情况下，会根据后续提供者状态进行刷新变更
