### ISSUE TITLE
triple怎么保活长连接

### ISSUE THREAD

**Issue by qtechjin** [apache/dubbo#10321]
如题，triple协议怎么保活长连接

**Comment by EarthChen** [comment]
现在不是长连接吗？  你是有什么疑问呢？

**Comment by qtechjin** [comment]
现在是长连接，但是防火墙检测不活跃连接会自动断掉，我看在这个问题里面https://github.com/apache/dubbo/pull/9968 处理了保活，好像是4月份改的，目前版本不行吗

**Comment by EarthChen** [comment]
> 现在是长连接，但是防火墙检测不活跃连接会自动断掉，我看在这个问题里面#9968 处理了保活，好像是4月份改的，目前版本不行吗

这个 pr 实现的是 http2的 keep alive，实现的有一些问题，所以关闭了。但是目前还是有 tcp 的 idle handler  有 tcp 的心跳的，理论上不应该出现不活跃。而且  就算实现了 http2的 keep alive，在idle 一段时间后，他会认为连接无用了也会自己关闭连接的。
