### ISSUE TITLE
Using Nacos cause group merger unable to work normally

### ISSUE THREAD

**Issue by sunyanghah** [apache/dubbo#10334]
####Version information

dubbo ：3.0.9

nacos : 2.1.0

dubbo-registry-nacos: 3.0.9

spring boot : 2.3.1. RELEASE

####Problem description

When I use Nacos as the registration center of Dubbo, I test the 'group merger' function of Dubbo. The request will only be processed by a certain group and cannot be merger.

When I use zookeeper, group merger works normally.

I'm not sure whether it's Dubbo's problem or Nacos' problem

**Comment by AlbumenJ** [comment]
Would you please try use `3.1.0-SNAPSHOT` for test? This may fixed in https://github.com/apache/dubbo/pull/10256

**Comment by sunyanghah** [comment]
> Would you please try use `3.1.0-SNAPSHOT` for test? This may fixed in #10256

thanks
Will version 3.1.0 be released in August?

**Comment by sunyanghah** [comment]
> Would you please try use `3.1.0-SNAPSHOT` for test? This may fixed in #10256

i'll wait for the new version,thanks

**Comment by AlbumenJ** [comment]
Will be released in the mid of August
