### ISSUE TITLE
请问triple协议该如何处理异常呢？都被RpcException包裹了，没办法拿到业务异常里的信息。

### ISSUE THREAD

**Issue by zhaokjun** [apache/dubbo#10353]
### provider的真实异常如何才能被consumer捕获？我在consumer层使用了全局异常处理器，但是拿不到具体的业务异常code和message等，还有其他异常没办法拿到其具体类型（一种感觉不怎么靠谱的解决方法是从RpcException的message里找报错的类名……）。
但是dubbo协议的话就不存在这个问题，可以直接获取到。

**Comment by AlbumenJ** [comment]
@EarthChen @guohao PTAL

**Comment by EarthChen** [comment]
这个问题已经回答过很多遍了，由于 triple 协议的状态码和信息是通过 http2 header 进行传输的(有大小限制)，不适合将整个异常进行序列化放入 header 中进行传输，建议通过自定义 filter 将异常转为 code 和 msg 通过 attachment 进行传输，然后对端在通过 filter 转为对应异常进行处理。这样的做法只是丢失了堆栈信息，但一般 rpc 场景知道对端的堆栈意义也是不大的

**Comment by yucw01** [comment]
see #9310 #8363
