### ISSUE TITLE
指定IP调用与tag冲突

### ISSUE THREAD

**Issue by LovingCoder** [apache/dubbo#10387]
dubbo 版本 2.7.15
我开启了三个服务，comsumerA（192.168.0.10：20880），providerB1（192.168.0.10：20881），providerB2（192.168.0.10：20882），providerC1（192.168.0.10：20883），providerC2（192.168.0.10：20884）；
其中 
providerB1 与 providerB2 指定了 tag （tag：providerB），
providerC1 与 providerC2 指定了 tag （tag：providerC），
我通过如下方式指定了服务提供方IP与端口
``` java
Address address = new Address(“192.168.0.10”, 20881);
RpcContext.getContext().setObjectAttachment(AddressRouterFactory.NAME, address);
```
没有指定tag，异常提示 no provider，既然直接指定了ip与端口，为什么还需要进入tag路由过滤tag呢？我需要怎么处理这个问题

**Comment by hdyztmdqd** [comment]
mark

**Comment by AlbumenJ** [comment]
https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/specify-ip/ 参考使用下这个方案看看

**Comment by LovingCoder** [comment]
很感谢
