### ISSUE TITLE
Dubbo-Spring version mapping guide

### ISSUE THREAD

**Issue by holtenko** [apache/dubbo#10385]
Hi team,

Apache-Dubbo is really an awesome project, but for newbies, it's hard to choose the version of Spring Framework(including Spring, SpringBoot...), we will have troubles of dependency conflicts, and so on.

Is there any plan to supply a guide of Dubbo-Spring version mapping?

Thanks.

**Comment by AlbumenJ** [comment]
We need to clarify the Dubbo's compatibility. In fact, Dubbo supports most versions of Spring Framework (including Spring 3.x, 4.x, 5.x, Spring Boot 1.x 2.x, etc.).

**Comment by holtenko** [comment]
> We need to clarify the Dubbo's compatibility. In fact, Dubbo supports most versions of Spring Framework (including Spring 3.x, 4.x, 5.x, Spring Boot 1.x 2.x, etc.).

Thanks @AlbumenJ 
Let me dive deep and have a try again.
