### ISSUE TITLE
为什么Dubbo3.0之后移除了http协议的实现? org.apache.dubbo.rpc.protocol.http.HttpProtocol 

### ISSUE THREAD

**Issue by BrooksWoo** [apache/dubbo#10384]
为什么Dubbo3.0之后移除了http协议的实现?

**Comment by dadadadudu** [comment]
因为有了Triple协议，是基于HTTP2的，还有Rest协议，也是基于HTTP的

**Comment by AlbumenJ** [comment]
HttpProtocol 独立发版了，使用方式参考 https://dubbo.apache.org/zh/release/dubbo-spi-extensions/#dubbo-rpc
