### ISSUE TITLE
NullPointerException could be Thrown at line 124 of org.apache.dubbo.rpc.cluster.loadbalance.RoundRobinLoadBalance

### ISSUE THREAD

**Issue by zhaoyangyingmu** [apache/dubbo#10403]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0
* Operating System version: Any
* Java version: 1.8

### Steps to reproduce this issue
An NPE could be thrown at line 124 of `org.apache.dubbo.rpc.cluster.loadbalance.RoundRobinLoadBalance`. `selectedWRR` could be null because the condition `cur > maxCurrent` may not be true. 
```java
    protected <T> Invoker<T> doSelect(List<Invoker<T>> invokers, URL url, Invocation invocation) {
        WeightedRoundRobin selectedWRR = null;
        // other codes
        for (Invoker<T> invoker : invokers) {
            // other codes
            if (cur > maxCurrent) {
                selectedWRR = weightedRoundRobin;
            }
        }
        if (selectedInvoker != null) {
            selectedWRR.sel(totalWeight); // selectedWRR could be null.
            return selectedInvoker;
        }
```
### Actual Behavior
An NPE could be thrown at line 124 because no defensive null check is provided.

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/182756373-a02fee2e-75a9-4e95-8cfe-16932590bd96.png)
`selectedWRR` and `selectedInvoker` are being set in the same time. It is impossible that `selectedWRR` is null and `selectedInvoker` is not null.
