### ISSUE TITLE
将同一服务发布在同一zk集群的不同节点下，服务关闭时会发生异常：Failed to unregister..

### ISSUE THREAD

**Issue by 1158974574** [apache/dubbo#10408]
- [ ✔️] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

1. 使用同一个zk集群，将一个服务同时发布在该zk的不同节点下，比如发布在  /dubbo1 和 /dubbo2  节点下，这时会有两个registry。
2. 服务正常关闭时，会调用 registry.destroy()方法，当第一个registry关闭后，对应的zk连接也会被关闭，这时第二个registry关闭时，由于共用了zk连接，这里就会抛出异常：Failed to unregister.....

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
升级到 2.7.15 或者 3.0.10 测试下看看

**Comment by 1158974574** [comment]
ok，升级版本后已解决
