### ISSUE TITLE
dubbo有计划支持nacos跨ns和group的访问吗

### ISSUE THREAD

**Issue by hujun-w-2** [apache/dubbo#10407]
如题，如果使用dubbo框架，nacos作为注册中心，跨namespace和group的访问这块是否有支持呢，或者最佳的实践有相关文档吗？

**Comment by chickenlj** [comment]
> 跨namespace和group的访问这块是否有支持呢

这里问题比较模糊一些，能具体描述下么？namespace group 是可以任意配置的。

可以参考下这里的文档 

https://dubbo.apache.org/zh/docs3-v2/java-sdk/reference-manual/registry/nacos/#32-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E5%90%8D%E7%A9%BA%E9%97%B4

https://dubbo.apache.org/zh/docs3-v2/java-sdk/reference-manual/registry/multiple-registry/

**Comment by chickenlj** [comment]
你想要的是多注册中心（namespace）还是单注册中心只是指定 namespace

**Comment by hujun-w-2** [comment]
> 你想要的是多注册中心（namespace）还是单注册中心只是指定 namespace

多注册中心看起来可以满足需求，但是否是最佳实践呢，我的场景是两个不同的部门，使用不同的namespace，但是这两个部门的服务希望能互相发现

**Comment by chickenlj** [comment]
建议用多注册中心。因为从nacos的角度不同namespace实质上已经是多注册中心了，逻辑隔离，所以你们这个部署架构和物理两个注册中心集群没多大区别了。

**Comment by chickenlj** [comment]
请问 dubbo 什么版本？

**Comment by hujun-w-2** [comment]
> 请问 dubbo 什么版本？
多注册中心是什么版本支持的呢，我们目前的版本是2.7.15

**Comment by hujun-w-2** [comment]
![image](https://user-images.githubusercontent.com/39894911/182992633-c9fd7f6f-f069-4f64-beec-6a927bf13280.png)

**Comment by chickenlj** [comment]
> > 请问 dubbo 什么版本？
> > 多注册中心是什么版本支持的呢，我们目前的版本是2.7.15

2.7.15 是没问题，但3.0 完全兼容并且已经稳定，建议升级到 3.0.9 以上版本

**Comment by hujun-w-2** [comment]
> > > 请问 dubbo 什么版本？
> > > 多注册中心是什么版本支持的呢，我们目前的版本是2.7.15
> 
> 2.7.15 是没问题，但3.0 完全兼容并且已经稳定，建议升级到 3.0.9 以上版本

已经稳定是指在生产验证过了吗？

**Comment by AlbumenJ** [comment]
3.0 已经在生产环境大规模落地了
