### ISSUE TITLE
在Nacos Cofnig配置dubbo:consumer:timeout无效

### ISSUE THREAD

**Issue by skyjilygao** [apache/dubbo#10422]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment
* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: 1.8
* Nacos version: 2.0.2

### Steps to reproduce this issue

1. 在nacos中的provider.yml配置超时属性：dubbo:consumer:timeout:2000
2. 测试发现配置无效，超时错误提示时间为默认值：1000

**Comment by AlbumenJ** [comment]
dubbo.consumer.timeout: 2000

**Comment by skyjilygao** [comment]
> 
应该是这样吧：
```yaml
dubbo:
  consumer:
    timeout: 2000
```
在项目provider模块中bootstrap.yml配置后生效，但是通过nacos配置就不生效。

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos/dubbo-samples-nacos-configcenter 参考这个用例进行配置，只能通过 dubbo 可以读取的方式配置

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos/dubbo-samples-nacos-configcenter

**Comment by skyjilygao** [comment]
> https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos/dubbo-samples-nacos-configcenter 参考这个用例进行配置，只能通过 dubbo 可以读取的方式配置

谢谢，根据这个示例，以及文档已经能从nacos配置中心读取到timeout了。
但是又遇到一个新的问题，不会自动刷新。虽然应用程序日志显示读取到nacos配置，但测试时发现timeout并没有刷新为最新配置，而是使用的程序启动时读取的配置。我还没找到自动刷新的参数，能告诉下吗？

**Comment by AlbumenJ** [comment]
通过这种方式i配置的不支持动态更新，如果需要动态更新的可以参考 https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/traffic/config-rule/
