### ISSUE TITLE
dubbo3自称完全兼容dubbo2，然而直接升级版本号能成功运行的有几个？

### ISSUE THREAD

**Issue by xishian** [apache/dubbo#10438]
```
在 3.0 版本的设计与开发之初，我们就定下了兼容老版本 Dubbo 用户（2.5、2.6、2.7）的目标。
因此，往 3.0 版本的升级过程将会是完全透明的，用户无需做任何业务改造，升级 3.x 后的框架行为将保持与 2.x 版本完全一致。
```
欢迎大家列一下dubbo2.7 升dubbo3.0遇到的各种不兼容问题
> No such extension ls for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler

**Comment by AlbumenJ** [comment]
由于安全问题，org.apache.dubbo.remoting.telnet.TelnetHandler 在 Dubbo 2.7 的高版本中大多数实现已经被禁用，Dubbo 3 中已经移动到 qos 模块中。

**Comment by CrazyHZM** [comment]
暂时先关闭这个issue，如果还有别的不兼容的疑惑，随时可以重新打开这个issue进行交流。

**Comment by zhimengxu** [comment]
dubbo2.7 升dubbo3.0遇到的这个问题

No such extension ls for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler

**Comment by alcoveWander** [comment]
现在用的dubbo版本 3.2.8，还是有这个问题：No such extension ls for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler

**Comment by AlbumenJ** [comment]
> 现在用的dubbo版本 3.2.8，还是有这个问题：No such extension ls for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler

Remove the configuration like `telnet=ls`

**Comment by mltneal** [comment]
dubbo2.7.20 升dubbo3.0.9 也遇到同样问题java.lang.IllegalStateException: No such extension cd for telnet/org.apache.dubbo.remoting.telnet.TelnetHandler
应用本身并没有用到cd或者ls

**Comment by mltneal** [comment]
请问咋解决呢
