### ISSUE TITLE
hessian协议在dubbo3中被删除了吗

### ISSUE THREAD

**Issue by mobile664042** [apache/dubbo#10437]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

dubbo3中不再支持hessian协议了吗？dubbo2中还支持的，因为漏洞的问题升级到dubbo3，发现用不了，查看源码，发现已删除相关协议，我这需要怎么处理啊

![image](https://user-images.githubusercontent.com/1433479/183800286-298dc6e9-a478-4828-9388-483803dd686f.png)

**Comment by yangzhongj** [comment]
需要单独引入hessian 模块

**Comment by yangzhongj** [comment]
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-serialization-hessian2</artifactId>
    <version>3.0.10</version>
    <scope>test</scope>
</dependency>

**Comment by yangzhongj** [comment]
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-serialization-hessian2</artifactId>
    <version>3.0.10</version>
</dependency>

**Comment by AlbumenJ** [comment]
<dependency>
  <groupId>org.apache.dubbo.extensions</groupId>
  <artifactId>dubbo-rpc-hessian</artifactId>
  <version>1.0.0</version>
</dependency>

**Comment by mobile664042** [comment]
> 1.0.0

这个可以了，这是在哪里有说明？

**Comment by mobile664042** [comment]
感觉有点坑，看到下面这个链接。
https://dubbo.apache.org/zh/docs/v3.0/references/protocols/hessian/

硬是没有把关键的依赖给补上。

**Comment by AlbumenJ** [comment]
官网上面关于 spi-extensions 的确实需要补一下，我这几天会弄下

**Comment by AlbumenJ** [comment]
> 感觉有点坑，看到下面这个链接。 https://dubbo.apache.org/zh/docs/v3.0/references/protocols/hessian/
> 
> 硬是没有把关键的依赖给补上。

https://github.com/apache/dubbo-website/pull/1368 已经补充
