### ISSUE TITLE
 有没有 dubbo 的 api 网关

### ISSUE THREAD

**Issue by amyson** [apache/dubbo#10449]
多活场景下，dubbo 调用本地服务时，若本地的实例全部不可用，就需要通过 api 网关把请求转发到其它机房。
dubbo api网关要做以下几件事：
1、本地网关接收 dubbo 协议的调用请求，分析出调用的微服务名称（或接口名称）及参数等信息，之后 api网关按照请求信息找到位于其它机房的 api 网关，转发消息（应该需要转成HTTP 协议，还没深入考虑）
2、dubbo api 网关接收到其它api网关的请求，识别出请求的微服务名称，发送到该微服务的本地实例
……

**Comment by AlbumenJ** [comment]
[可以看下apisix](https://apisix.apache.org/zh/docs/apisix/plugins/dubbo-proxy/)

**Comment by chickenlj** [comment]
There are pretty some choices [APISIX](https://dubbo.apache.org/zh/blog/2022/01/18/%E4%BB%8E%E5%8E%9F%E7%90%86%E5%88%B0%E6%93%8D%E4%BD%9C%E8%AE%A9%E4%BD%A0%E5%9C%A8-apache-apisix-%E4%B8%AD%E4%BB%A3%E7%90%86-dubbo-%E6%9C%8D%E5%8A%A1%E6%9B%B4%E4%BE%BF%E6%8D%B7/). [ShenYu](https://dubbo.apache.org/zh/blog/2022/05/04/%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87-apache-shenyu-%E7%BD%91%E5%85%B3%E4%BB%A3%E7%90%86-dubbo-%E6%9C%8D%E5%8A%A1/) and [Pixiu](https://dubbo.apache.org/zh/docs3-v2/dubbo-go-pixiu/user/quickstart/)

**Comment by amyson** [comment]
谢谢，在研究 ShenYu
