### ISSUE TITLE
spi扫描不到当前项目的org.apache.dubbo.remoting.Transporter文件

### ISSUE THREAD

**Issue by SampsonJava** [apache/dubbo#10450]
dubbo版本:dubbo2.7.16
在resources/META-INF/dubbo/internal下新建的org.apache.dubbo.remoting.Transporter文件
启动的时候dubbo的ExtensionLoader#loadDirectory方法扫描的fileName是对的,但是就是扫描不到当前项目下的这个文件,只能扫描到dubbo源码jar里面的org.apache.dubbo.remoting.Transporter文件,导致自定义spi实现无法加载

但是在dubbo源码项目的demo里面使用同样姿势,新建的同样路径的同样文件, 启动的时候可以扫描到自定义的Transporter实现

想请问下是姿势不对吗, 还是说有什么依赖缺少

添加了下面2个依赖和dubbo基础依赖,目前项目可以正常提供和调用,仅仅不能扫描到当前路径的spi实现
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-remoting-netty4</artifactId>
            <version>2.7.16</version>
 </dependency>
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-rpc-dubbo</artifactId>
    <version>2.7.16</version>
</dependency>

**Comment by liufeiyu1002** [comment]
`META-INF`

**Comment by SampsonJava** [comment]
> `META-INF`

我写错了, 项目中是META-INF

**Comment by SampsonJava** [comment]
```
boolean netty = ExtensionLoader.getExtensionLoader(Transporter.class).hasExtension("netty4");
```
即便是用main方法这样调用,也扫描不到当前项目下的扩展文件

**Comment by liufeiyu1002** [comment]
你项目的 `resources ` 是资源目录么？
![image](https://user-images.githubusercontent.com/32605119/184479543-9b72a4f3-0ee1-4e05-8218-26ac4c3ddd8a.png)
  idea下  `resources  ` 目录右键  `mark directory as ` 选择 `resource root`    或者提供一个可以复现的 demo

**Comment by SampsonJava** [comment]
> 

是这个资源, 我弄个demo试一试

**Comment by SampsonJava** [comment]
解决了,是因为没有项目没有生成targe文件导致扫描不到META-INF下面的文件
