### ISSUE TITLE
DubboService注解场景下version和group单独配置，且配置值一样，启动会报错

### ISSUE THREAD

**Issue by xiaomiusa87** [apache/dubbo#10454]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.10/2.7.16
* Operating System version: Windows 10
* Java version: 1.8.0_221

### Steps to reproduce this issue

1. 使用dubbo-spring-boot-starter + @DubboService注解
2. 单独配置version或group，并且version和group值一样
3. 3.0.10启动报错，2.7.16 启动后只能注册一个dubbo url到zk（期望注册2个）
![image](https://user-images.githubusercontent.com/72253502/184521500-18f94041-4ddd-4cd6-af87-fec56a6cdf04.png)
![image](https://user-images.githubusercontent.com/72253502/184521508-4760d78b-fc74-4176-ac94-2174d431f5f0.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

期望启动不报错，并且正常注册两个接口的url到注册中心

### Actual Behavior

3.0.10启动报错，2.7.16启动后只会注册一个url到zk

If there is an exception, please attach the exception trace:

报错如下：
```
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'ServiceBean:com.dubbo.demo.demo.HelloFacade:1.0.0' defined in null: Found duplicated BeanDefinition of service interface [com.dubbo.demo.demo.HelloFacade] with bean name [ServiceBean:com.dubbo.demo.demo.HelloFacade:1.0.0]
```

**Comment by chickenlj** [comment]
This is an extreme corner case that makes no meaning most of the time, same interface name, same version/group. 

Dubbo3 does not allow the same service(interface, group, version all the same) to be declared more than once. Seems like it failed to distinguish the corner case of only the version or group is set, it wrongly treats them as the same.

We can consider to fix that but it's not a priority.

**Comment by xiaomiusa87** [comment]
> 

yes. this issue has been fixed.
