### ISSUE TITLE
Already exists another bean definition with the same bean name

### ISSUE THREAD

**Issue by ms20hj** [apache/dubbo#10485]
Dubbo version: 3.0.10
 springboot：2.7.2
 Java version: java8

![image](https://user-images.githubusercontent.com/23376892/185596598-7f6ffbff-fd01-43aa-bc51-f14dd04e3112.png)

代码里面有IUserService 对应的实现类是UserServiceIpml，由于业务拓展，新增了IV3UserService对应的实现类是V3UserServiceImpl
在springboot：2.1.16.RELEASE， dubbo 2.6.5环境下是正常的。
现在对版本做了升级， Dubbo version: 3.0.10  springboot：2.7.2 出现service重复注册问题。
![image](https://user-images.githubusercontent.com/23376892/185602150-c03b8d97-f01e-40de-ad7b-12c30535664f.png)

IUserService 和 IV3UserService是两个不同的service，如何解决

**Comment by liufeiyu1002** [comment]
试一下` 3.0.11` 或者 `3.1.0` 的 `Pre-release`版本， 或者 `3.0.11-SNAPSHOT` 版本   参考这个 pr 
 https://github.com/apache/dubbo/pull/10359

**Comment by ms20hj** [comment]
@liufeiyu1002 3.0.11目前还没发布吧，maven仓库里面都没有。还未发布？
![image](https://user-images.githubusercontent.com/23376892/186051657-579184e2-de63-489d-9d6e-960e5faabdfd.png)

**Comment by liufeiyu1002** [comment]
> @liufeiyu1002 3.0.11目前还没发布吧，maven仓库里面都没有。还未发布？ ![image](https://user-images.githubusercontent.com/23376892/186051657-579184e2-de63-489d-9d6e-960e5faabdfd.png)

https://github.com/apache/dubbo/releases   `3.0.11` 还是 `pre-release` 版本的， 你可以试试 `3.1.0` 这个应该是正式发布了

**Comment by AlbumenJ** [comment]
3.1.0 中央仓已经同步，3.0.11 大概半个小时后同步完毕

**Comment by ms20hj** [comment]
@AlbumenJ 升级到3.0.11，之后把原先的@Resource 改成 @Autowired 问题解决。
但是遇到了一个奇怪的问题，换了个名字就启动起来了。
![image](https://user-images.githubusercontent.com/23376892/186371891-d907a8d6-60de-4ad5-89a0-49b63a0c9a6c.png)

**Comment by liufeiyu1002** [comment]
> 

启动不起来是因为你的代码中 有其他 `service` 使用了 `userService`这个属性名称 例如 `@Resource IUserService userService`;  
spring中 `@Resource` 是按照属性名称注入` 在getBean 时 是通过属性名称从容器中查找，找不到才会按照类型去找
 @Autowired `是按照类型注入 查找按照类型从容器中获取
当你使用时 `@Resource IUserService userService`;  `@DubboReference IV3UserService userService`;   俩个属性名称相同时，容器创建bean时 在注入 `@Resource IUserService userService` 时 从容器中 getBean("userService") 拿到的是 `IV3UserService`  这个类型的实例 类型不匹配所以启动不了

**Comment by ms20hj** [comment]
再去检查了一遍代码，确认已经把代码里面的@Resource都移除，换成了@Autowired来注入。其它所有的 service 都正常，就是这个@DubboReference IV3UserService userService 不行，换成@DubboReference IV3UserService iV3UserService 就可以了。

**Comment by liufeiyu1002** [comment]
> 再去检查了一遍代码，确认已经把代码里面的@resource都移除，换成了@Autowired来注入。其它所有的 service 都正常，就是这个@DubboReference IV3UserService userService 不行，换成@DubboReference IV3UserService iV3UserService 就可以了。

你可以贴一下 `@DubboReference IV3UserService userService` 使用这个时候的启动错误信息，或者就是改下它属性名称那样用也可以

**Comment by ms20hj** [comment]
修改了下属性，目前一切正常。就这么着吧O(∩_∩)O哈哈~
