### ISSUE TITLE
dubbo3消费者的zk注册地址对dubbo2的提供者version和group不匹配过滤的问题

### ISSUE THREAD

**Issue by xiaoni2009** [apache/dubbo#10483]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 1.0版本服务提供者dubbo3.0.5，2.0版本服务提供者dubbo2.7.8
* Java version: 11

### Steps to reproduce this issue

1. A应用暴露AService的1.0版本，A应用启动2个节点A1，A2
2. B应用暴露AService的2.0版本，B应用启动1个节点B1
3. A应用AService的1.0版本的内部的去调用AService的2.0版本接口

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

预期结果，调用A1节点的AService1.0版本，内部去调用AService的2.0，能正常走到B应用暴露AService的2.0版本

### Actual Behavior

实际结果，调用A1节点的AService1.0版本，内部去调用AService的2.0时，有可能会走到A2节点的ip（注意A2节点只暴露了1.0版本的接口），此时就会报错version2.0 not found。

而使用dubbo2是正常的。

If there is an exception, please attach the exception trace:

```
org.apache.dubbo.rpc.RpcException: Failed to invoke the method test in the service com.test.AService. Tried 1 times of the providers [A2节点的ip:20012] (1/3) from the registry zk的ip:端口 on the consumer A1节点的ip using the dubbo version 3.0.5. Last error is: Failed to invoke remote method: test, provider: dubbo://A2节点的ip:20012/com.test.ASearch?application=aTest&background=false&category=providers,configurators,routers&check=false&deprecated=false&dubbo=2.0.2&interface=com.test.AService&metadata-type=remote&pid=33&release=3.0.5.&revision=2.0&side=provider&sticky=false&threads=10&version=2.0, cause: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.io.IOException: Service com.test.AService with version 2.0 not found, invocation rejected.
java.io.IOException: Service com.test.AService with version 2.0 not found, invocation rejected.
	at org.apache.dubbo.remoting.transport.CodecSupport.checkSerialization(CodecSupport.java:166)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:138)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:93)
	at org.apache.dubbo.remoting.transport.DecodeHandler.decode(DecodeHandler.java:57)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:44)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

# 查看dubbo2和3的核心代码区别：

org.apache.dubbo.common.utils.UrlUtils#isMatch 核心比较方法，两个版本几乎一致。

﻿

## dubbo3.0
创建url时，调用了这个比较方法

org.apache.dubbo.registry.zookeeper.ZookeeperRegistry#lookup ->

org.apache.dubbo.registry.support.CacheableFailbackRegistry#toUrlsWithoutEmpty ->

org.apache.dubbo.registry.support.CacheableFailbackRegistry#createURL 根据?(%3F)从provider拆出address和param，加上consumerURL，注意version_key是从urlParam里面取的->

org.apache.dubbo.registry.support.CacheableFailbackRegistry#createServiceURL ->

org.apache.dubbo.registry.zookeeper.ZookeeperRegistry#isMatch

```
protected ServiceAddressURL createURL(String rawProvider, URL consumerURL, Map<String, String> extraParameters) {
        ...
        //这个param有点看不懂，似乎没有根据分隔符&拆开version和group
        URLParam param = stringParam.computeIfAbsent(rawParams, k -> URLParam.parse(k, isEncoded, extraParameters));
        param.setTimestamp(System.currentTimeMillis());

        ServiceAddressURL cachedURL = createServiceURL(address, param, consumerURL);
        //这里比较的chachedURL应该是providerURL，但是创建cachedURL的时候param里面没有version
        if (isMatch(consumerURL, cachedURL)) {
            return cachedURL;
        }
        return null;
}
```

## dubbo2.0
org.apache.dubbo.registry.zookeeper.ZookeeperRegistry#toUrlsWithoutEmpty ->

org.apache.dubbo.common.URLStrParser#parseEncodedStr 解析provider的url，同样根据?(%3F)拆分 ->

org.apache.dubbo.common.URLStrParser#parseEncodedParams 解析参数，根据&，所以version可以正确放入。

```
    private List<URL> toUrlsWithoutEmpty(URL consumer, List<String> providers) {
        List<URL> urls = new ArrayList<>();
        if (CollectionUtils.isNotEmpty(providers)) {
            for (String provider : providers) {
                if (provider.contains(PROTOCOL_SEPARATOR_ENCODED)) {
                    URL url = URLStrParser.parseEncodedStr(provider);
                    if (UrlUtils.isMatch(consumer, url)) {
                        urls.add(url);
                    }
                }
            }
        }
        return urls;
    }

private static Map<String, String> parseEncodedParams(String str, int from) {
...
                  case '&':
                    addParam(str, true, nameStart, valueStart, i - 2, params, tempBuf);
...
}
```

很明显3.0版本比较时，使用的是一个奇怪的param(没有version和group参数) + consumerURL去创建的cachedURL，然后跟consumerURL对比，当然就没法比较version和group了，也就是dubbo3.0的version和group的zk地址过滤无效

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-version
这个用例是每次发版都跑的，你可以升级下最新版本试试

**Comment by xiaoni2009** [comment]
这个issue里面已经解决这个问题，升级dubbo3的版本可以解决
https://github.com/apache/dubbo/issues/9557
