### ISSUE TITLE
ThreadPoolExhaustedListener 在最新版本中未发现用户配置的入口在哪

### ISSUE THREAD

**Issue by stoneapple** [apache/dubbo#10490]
ThreadPoolExhaustedListener 在最新版本中未发现用户配置的入口，这个功能的设计初衷我理解，是发生线程池耗尽通知给应用，目前没看到应用如何添加监听的地方。

**Comment by AlbumenJ** [comment]
看了下应该是之前改 EventDispatcher 的时候把入口给搞没了，目前看起来是需要有一个重新配置的入口

**Comment by stoneapple** [comment]
> 看了下应该是之前改 EventDispatcher 的时候把入口给搞没了，目前看起来是需要有一个重新配置的入口
那这个我回头整理下，提个PR修复掉

**Comment by CrazyHZM** [comment]
@stoneapple 
any progress on this?
