### ISSUE TITLE
Dubbo-2.7.9版本为什么NacosMetadataReport没有实现getAppMetadata方法

### ISSUE THREAD

**Issue by herrykings** [apache/dubbo#10509]
使用dubbo-2.7.9版本使用应用级别服务发现时候(注册中心和元数据中心都是用的nacos)，当根据应用名进行服务原数据拉取的时候，发现NacosMetadataReport 没有实现 org.apache.dubbo.metadata.report.MetadataReport#getAppMetadata(定义成default方法) 方法，导致每次都获取空值.

default MetadataInfo getAppMetadata(SubscriberMetadataIdentifier identifier, Map<String, String> instanceMetadata) {
        return null;
}

**Comment by AlbumenJ** [comment]
Dubbo 2.7 版本不建议使用应用级服务发现，升级到 3.0 或者 3.1。应用级服务发现在 3.0 版本中已经有大量的生产实践了

**Comment by JamesKings** [comment]
好嘞，感谢

**Comment by JamesKings** [comment]
> Dubbo 2.7 版本不建议使用应用级服务发现，升级到 3.0 或者 3.1。应用级服务发现在 3.0 版本中已经有大量的生产实践了

好嘞，感谢
