### ISSUE TITLE
Nacos注册中心无法使用分组聚合调用

### ISSUE THREAD

**Issue by pengsuwei** [apache/dubbo#10506]
### Environment

* Dubbo version: 3.0.7
* nacos client version: 2.1.0 
* Operating System version: windows10
* Java version: 11

### Steps to reproduce this issue
断点跟踪了一下nacos registry源码，Consumer端在初始化Provider Invoker时，没有对指定聚合分组（consumer group = merge,merge2）打包聚合初始化，而是分开进行了初始化。
org.apache.dubbo.registry.nacos.NacosRegistry#doSubscribe(org.apache.dubbo.common.URL, org.apache.dubbo.registry.NotifyListener, java.util.Set<java.lang.String>)

相同代码切换ZK为注册中心，分组聚合调用工作正常。通过跟踪zookeeper registry源码，Consumer端在初始化Provider Invoker时，对指定聚合分组（consumer group = merge,merge2）进行了打包聚合初始化。
org.apache.dubbo.registry.zookeeper.ZookeeperRegistry#doSubscribe

Consumer端均采用Dubbo API初始化方式
内网网络原因，无法上传图片。麻烦帮确认下该问题，多谢

**Comment by AlbumenJ** [comment]
升级到 3.1.0 版本后支持
