### ISSUE TITLE
dubbo.application.hostname配置不生效

### ISSUE THREAD

**Issue by alfredodiego** [apache/dubbo#10520]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

根据文档配置dubbo.application.hostname，但是这个配置一直为空，程序还是通过InetAddress.getLocalHost().getHostName() 获取hostname
排查发现ApplicationBuilder 并没有对hostname这个属性进行build

**Comment by AlbumenJ** [comment]
`dubbo.application.hostname` 这个配置是哪里看到的，文档中应该没这个配置吧

**Comment by chickenlj** [comment]
配置 hostname 的意图是什么，能否详细描述一下？ 另外，建议使用最新稳定版本 3.0.11

**Comment by alfredodiego** [comment]
> 配置 hostname 的意图是什么，能否详细描述一下？ 另外，建议使用最新稳定版本 3.0.11

项目是docker 容器部署得，在不同容器内部想配置宿主机的hostname去获取对应得ip。如果不设置对应的hostname的ip，dubbo就会抛出unkonwhost的异常，导致首次调用服务的过程比较慢

**Comment by alfredodiego** [comment]
> `dubbo.application.hostname` 这个配置是哪里看到的，文档中应该没这个配置吧

https://dubbo.apache.org/zh/docs3-v2/java-sdk/reference-manual/config/properties/
application的配置项手册

**Comment by chickenlj** [comment]
> https://dubbo.apache.org/zh/docs3-v2/java-sdk/reference-manual/config/properties/
> application的配置项手册

不是hostname这个属性，可以参照下面的文档

https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/others/set-host/#%E5%9C%A8%E4%BD%BF%E7%94%A8-docker-%E6%97%B6%E6%9C%89%E6%97%B6%E9%9C%80%E8%A6%81%E8%AE%BE%E7%BD%AE%E7%AB%AF%E5%8F%A3%E6%98%A0%E5%B0%84%E6%AD%A4%E6%97%B6%E5%90%AF%E5%8A%A8-server-%E6%97%B6%E7%BB%91%E5%AE%9A%E7%9A%84-socket-%E5%92%8C%E5%90%91%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%BF%83%E6%B3%A8%E5%86%8C%E7%9A%84-socket-%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84%E7%AB%AF%E5%8F%A3%E5%8F%B7%E6%AD%A4%E6%97%B6%E5%8F%88%E8%AF%A5%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE
