### ISSUE TITLE
dubbo 2.5 版本观察到负载不均

### ISSUE THREAD

**Issue by goudai** [apache/dubbo#10532]
dubbo版本：2.5.4
业务跑在k8s中，pod数量20台，负载算法没有指定使用默认，发现其中一个节点承接的流量远远大于其他节点，下图是dubboderverhandler线程池的监控数据
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/16605628/188050796-ed3ded5c-bcec-4b2d-8a87-2872c12df93c.png">

**Comment by AlbumenJ** [comment]
2.5.4 版本已经不在维护了，请升级到最新版本试下

**Comment by goudai** [comment]
请问这是已知问题吗

**Comment by chickenlj** [comment]
用的什么负载均衡算法？

**Comment by goudai** [comment]
没有配置负载算法，默认应该是RoundRobinLoadBalance吧

**Comment by goudai** [comment]
我找到一个pr https://github.com/apache/dubbo/pull/14 是否是修复这个问题
