### ISSUE TITLE
3.0.10 triple 协议 自定义异常抛出时,DEBUG栈信息获取有问题

### ISSUE THREAD

**Issue by mz0113** [apache/dubbo#10545]
![image](https://user-images.githubusercontent.com/42512469/188382557-fb95265c-73fc-42b2-a63c-1e3617cfa1b7.png)

org.apache.dubbo.rpc.protocol.tri.ExceptionUtils#getStackFrameList(java.lang.Throwable, int)

如图 , 如果我的异常是这样的 RuntimeException ex = new RuntimeException(" 第一行 \n 第二行") 这样带有换行符的多行文本 , 获取栈的时候会把这个文本也作为栈的一层,导致我的异常信息一直不完整(因为输出的错误信息行数多于6行)

另外想咨询一下, tri协议现在无法抛自定义异常了,以后会支持吗 我现在做法是把我的异常json以后放到ex的message里面,到了client端我再手动反序列化回来 以后会有官方支持吗?

**Comment by EarthChen** [comment]
请问一下，你的异常为什么是个 json 呢？如果是自定义的字符串 这边建议用 attachment 进行传输，走 filter 进行抛出

**Comment by mz0113** [comment]
> 请问一下，你的异常为什么是个 json 呢？如果是自定义的字符串 这边建议用 attachment 进行传输，走 filter 进行抛出
按照你的建议 , 我在服务端的filter里面将appResponse值改写 , 将exception放到了value里面 , 然后exception字段置空, 消费端filter再将value放到exceotion字段中,目前可以正常工作了
