### ISSUE TITLE
Observability MetricsFilter implements BaseFilter.Listener to replace try catch

### ISSUE THREAD

**Issue by Henrik-Yao** [apache/dubbo#10554]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

The MetricsFilter class uses try catch to collect rt information. This mode is not allowed under asynchronous conditions and needs to be replaced.

MetricsFilter 类使用 try catch 来收集 rt 信息。这种模式在异步条件下是不准确的，需要更换。

Related pr : https://github.com/apache/dubbo/pull/10331

Related issues : https://github.com/apache/dubbo/issues/9886

Related Documentation : https://qnac8r4ct8.feishu.cn/docx/doxcncmY1gYiRGX9ccX264W6JJd

**Comment by jojocodeX** [comment]
收到

**Comment by jojocodeX** [comment]
1:异常统计分类，区分框架异常，业务异常
2:正常返回结果统计，正常返回不包括throw异常数据
3:对DefaultMetricsCollector内部方法进行整理
4:添加相应的单元测试

**Comment by AlbumenJ** [comment]
Finished with #10589
