### ISSUE TITLE
dubbo-grpc协议 vs triple协议

### ISSUE THREAD

**Issue by wangyy2113** [apache/dubbo#10564]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

请问dubbo-grpc协议 与 triple协议在应用层面大概有哪些不同？ 例如dubbo-grpc支持 框架带来的服务治理能力(如标签路由，条件路由等高级特性)吗？如果支持的话，为什么要选择triple协议而不选择dubbo-grpc呢？

**Comment by chickenlj** [comment]
从spec的角度，triple和grpc协议是完全兼容的。从实现层面，triple是完全自己实现的，和Dubbo的编程模型、服务治理能力结合更好。dubbo-grpc 集成模块社区已不再继续维护，建议使用triple协议。

性能测试的指标，可以参考以下文档：
https://dubbo.apache.org/zh/docs3-v2/java-sdk/reference-manual/performance/rpc-benchmarking/
