### ISSUE TITLE
Decoupling dubbo-remoting-api with netty

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10578]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by conghuhu** [comment]
任务：完成Client相关的解耦。
目标：将Connection相关做一层抽象，在remoting-netty中做具体实现。
预期效果：dubbo-remoting-api中client相关不再直接依赖netty

**Comment by shanuo0312** [comment]
任务：完成ssl相关的解耦。
目标：抽象ssl相关的实现，下沉到reomoteing-netty的实现层当中
预期效果：api与netty解耦

**Comment by The-Gamer-01** [comment]
这个issue现在完成了吗，还需要帮助吗

**Comment by conghuhu** [comment]
> 

client已经完成了，ssl的pr在review中

**Comment by conghuhu** [comment]
这个是不是可以关闭了 @AlbumenJ
