### ISSUE TITLE
Enable consumers to request service providers by priority using the appropriate serialization type

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10574]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by tonycody** [comment]
The service provider will configure a set of serialization types with priority rules for consumers to parse according to the actual business scenario.
Consumers try the available serialization types in the current SDK version one by one according to the serialization type configured by the service provider, and request the service provider if there is a related serialization type.

E.g:
The service provider is configured as: fastjson, hessian2
Parse the serialization priority configuration before the consumer requests, try fastjson first, if the fastjson serializer is included, the request uses the fastjson serialization type to request the service provider. If fastjson is not included, try again whether hessian2 supports it. And so on!

**Comment by dkisser** [comment]
The explanation of serialization upgrade see here .[https://github.com/apache/dubbo-website/pull/1487](url)
