### ISSUE TITLE
3.1.0集成istio后，调用报错 UNAVAILABLE : upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed

### ISSUE THREAD

**Issue by niejian** [apache/dubbo#10595]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue
使用nacos注册中心，在接入k8s并集成istio后，由消费端调用提供者，提示报错如下：

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```java


SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke the method getEmpInfo in the service cn.com.bluemoon.istio.demo.dubbo.service.CustEmpService. Tried 3 times of the providers [istio-demo-dubbo-producer.istio-demo.svc.cluster.local:20885] (1/1) from the registry istio-demo-dubbo-producer.istio-demo.svc.cluster.local:20885 on the consumer 10.233.78.134 using the dubbo version 3.1.0. Last error is: Fail to invoke remote method: getEmpInfo, provider: tri://istio-demo-dubbo-producer.istio-demo.svc.cluster.local:20885/cn.com.bluemoon.istio.demo.dubbo.service.CustEmpService?application=istio-demo-consumer&background=false&check=false&interface=cn.com.bluemoon.istio.demo.dubbo.service.CustEmpService&lazy=true&mesh-enable=true&pid=11&provided-by=istio-demo-dubbo-producer&provider-port=20885&qos.accept.foreign.ip=true&qos.enable=false&register-mode=instance&register.ip=10.233.78.134&revision=1.0-SNAPSHOT&side=consumer&sticky=false, cause: org.apache.dubbo.rpc.StatusRpcException: UNAVAILABLE : upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111
--
2022-09-09 14:28:52 | RemoteAddress:istio-demo-dubbo-producer.istio-demo.svc.cluster.local:20885] with root cause


```

**Comment by AlbumenJ** [comment]
这个看起来是使用 proxy 模式的？走的 envoy 透明拦截的模式？

**Comment by niejian** [comment]
> 这个看起来是使用 proxy 模式的？走的 envoy 透明拦截的模式？

是的，使用proxy模式，走的 envoy 透明拦截的模式；
尝试在消费端pod内直接使用 telnet ip 20885 命令，发现一直telnet不通。而在生产者端使用telnet ip 20885 没问题

**Comment by niejian** [comment]
> 这个看起来是 envoy 拦截导致问题，Dubbo 绑定端口的时候默认是使用 AnyHost 0.0.0.0 的

那这个问题要怎么去解决呢

**Comment by niejian** [comment]
> 这个看起来是 envoy 拦截导致问题，Dubbo 绑定端口的时候默认是使用 AnyHost 0.0.0.0 的

对于有需要对dubbo服务做 AB、蓝绿的需求，官方这边有实际的案例可以参考下吗

**Comment by AlbumenJ** [comment]
https://dubbo.apache.org/zh/overview/tasks/mesh/dubbo-mesh/#35-%E6%B5%81%E9%87%8F%E6%B2%BB%E7%90%86---virtualservice-%E5%AE%9E%E7%8E%B0%E6%8C%89%E6%AF%94%E4%BE%8B%E6%B5%81%E9%87%8F%E8%BD%AC%E5%8F%91

**Comment by niejian** [comment]
> https://dubbo.apache.org/zh/overview/tasks/mesh/dubbo-mesh/#35-%E6%B5%81%E9%87%8F%E6%B2%BB%E7%90%86---virtualservice-%E5%AE%9E%E7%8E%B0%E6%8C%89%E6%AF%94%E4%BE%8B%E6%B5%81%E9%87%8F%E8%BD%AC%E5%8F%91

现在到这一步就进行不下去了，服务端和消费端无法通信；报错信息就如标题所示

![image](https://user-images.githubusercontent.com/7080323/190336047-5e2d7fc9-ce84-4040-9547-f80ffac8628c.png)

**Comment by AlbumenJ** [comment]
> > https://dubbo.apache.org/zh/overview/tasks/mesh/dubbo-mesh/#35-%E6%B5%81%E9%87%8F%E6%B2%BB%E7%90%86---virtualservice-%E5%AE%9E%E7%8E%B0%E6%8C%89%E6%AF%94%E4%BE%8B%E6%B5%81%E9%87%8F%E8%BD%AC%E5%8F%91
> 
> 现在到这一步就进行不下去了，服务端和消费端无法通信；报错信息就如标题所示
> 
> ![image](https://user-images.githubusercontent.com/7080323/190336047-5e2d7fc9-ce84-4040-9547-f80ffac8628c.png)

用的示例的项目部署的？

**Comment by niejian** [comment]
> > > https://dubbo.apache.org/zh/overview/tasks/mesh/dubbo-mesh/#35-%E6%B5%81%E9%87%8F%E6%B2%BB%E7%90%86---virtualservice-%E5%AE%9E%E7%8E%B0%E6%8C%89%E6%AF%94%E4%BE%8B%E6%B5%81%E9%87%8F%E8%BD%AC%E5%8F%91
> > 
> > 
> > 现在到这一步就进行不下去了，服务端和消费端无法通信；报错信息就如标题所示
> > ![image](https://user-images.githubusercontent.com/7080323/190336047-5e2d7fc9-ce84-4040-9547-f80ffac8628c.png)
> 
> 用的示例的项目部署的？

不是，参照示例改的。注册中心用的是nacos

**Comment by AlbumenJ** [comment]
修改后的示例可以发一下吗，包括具体的部署方式

**Comment by niejian** [comment]
> 修改后的示例可以发一下吗，包括具体的部署方式

问题解决了。**`服务名`没有跟`k8s service`名字一致**导致在开启mesh的时候，一直提示没有提供者。感谢答疑！
