### ISSUE TITLE
Can not accquire remote.application from url of invoker

### ISSUE THREAD

**Issue by justforstudy-A** [apache/dubbo#10594]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Operating System version: windows
* Java version: 11

### Steps to reproduce this issue

1. Started the application A、B、C
2. Then debug the method MonitorFilter#invoke of application B for remote.application of invoker

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior
I expected the value of remote.application is C, but it is null actually.
Although I get it from attachments, but value of it is B which is wrong.

If there is an exception, please attach the exception trace:
uninvolved
```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
MonitorFilter is a provider filter, which can only obtain application A's information in application B.

**Comment by justforstudy-A** [comment]
> MonitorFilter is a provider filter, which can only obtain application A's information in application B.

Thanks for reply, but MonitorFilter is both provider and consumer filter, can I ask the reason why change it only for provider?

**Comment by AlbumenJ** [comment]
MonitorFilter in consumer side for 3.x is `org.apache.dubbo.monitor.support.MonitorClusterFilter`
