### ISSUE TITLE
dubbo服务第一次启动正常调用 重启之后无论如何也调用不通了 Service com.ruoyi.system.api.RemoteUserService with version 0.0.0 not found, invocation rejected.

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#10593]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. 第一次 启动三个服务 互相调用正常
2. 重启 BC 两个服务后重新访问 A服务找不到 B服务了 实际B服务再nacos上是存在的
3. 看报错调用的端口是第一次的端口 第二次的端口变更了
![image](https://user-images.githubusercontent.com/31852897/189287489-ce3ca058-b5ed-41ca-9448-8f2b91c6c01c.png)
![image](https://user-images.githubusercontent.com/31852897/189287562-c3e67773-6e70-49e5-9b44-c63ab9b5633a.png)
![image](https://user-images.githubusercontent.com/31852897/189287751-4610508e-aa7e-46f1-9217-1aa271e4ff5b.png)
![image](https://user-images.githubusercontent.com/31852897/189287787-d9769ce3-6867-4011-a522-4e701b0dd758.png)
![image](https://user-images.githubusercontent.com/31852897/189287949-f97bf5e8-6409-4b95-9721-c360e5d3ec00.png)
![image](https://user-images.githubusercontent.com/31852897/189287981-f2254928-ee67-460a-bdad-0aefb630a6ac.png)

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JavaLionLi** [comment]
BC服务重启之后 这两个服务的端口互换了 但是元数据没有更新导致互相找不到对应的接口

**Comment by AlbumenJ** [comment]
> BC服务重启之后 这两个服务的端口互换了 但是元数据没有更新导致互相找不到对应的接口

报错后可以 debug 看下 NacosServiceDiscovery 有没有收到地址变更推送吗

**Comment by JavaLionLi** [comment]
> > BC服务重启之后 这两个服务的端口互换了 但是元数据没有更新导致互相找不到对应的接口
> 
> 报错后可以 debug 看下 NacosServiceDiscovery 有没有收到地址变更推送吗

回退到3.0.9无此问题 升级到3.1.0就有这个问题了

**Comment by AlbumenJ** [comment]
Might fixed in https://github.com/apache/dubbo/pull/10606

可以等 PR 合并后用 snapshot 版本再测试下吗
