### ISSUE TITLE
3.0.10 tri协议 broadcast广播调用失效 只能调到一个provider

### ISSUE THREAD

**Issue by mz0113** [apache/dubbo#10617]
1.  启动了3个provider , 然后consumer端pi配置为广播调用
![image](https://user-images.githubusercontent.com/42512469/190076093-477e5e50-f870-4928-ac9a-38abbb487cb1.png)

执行用例后并未发现有报错信息输出 , 但是只会有一个provider收到消息且固定为这一个, 当把这个provider下线后,就会从剩余的2个provider中再选一个进行调用,provider会输出内容,另一个还是调不到.然后再把这个下线,剩余的那一个也可以被调到了.
我看代码是进入了BroadcastClusterInvoker了,拿到的invokers列表size=3,进入了for循环3次 但是就是没啥效果 不报错 也调不到全部provider.

2.   另外问一下,broadcast2 这种模式被移除了吗 ,我配broadcast2提示我找不到扩展 can`t find extentions xxx

![image](https://user-images.githubusercontent.com/42512469/190076654-1ed16d04-937d-45c2-8b65-e7f7b335d2fe.png)

打一下断点,输出的信息可以表明是识别到了3个provider了
![image](https://user-images.githubusercontent.com/42512469/190077753-64238317-aff3-4918-8d96-9fee6b82a15b.png)

**Comment by CrazyHZM** [comment]
Fixed by #10619
