### ISSUE TITLE
accessLog can not parse tiple  pb  idl request

### ISSUE THREAD

**Issue by yangzhongj** [apache/dubbo#10627]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. accesslog = true

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

normal print accessLog 

### Actual Behavior

![image](https://user-images.githubusercontent.com/6899065/190348129-8e643f02-dff8-438e-b413-b8c2a25e8110.png)
![image](https://user-images.githubusercontent.com/6899065/190348179-c10cfab8-90c0-4309-8967-b4523bfced21.png)

**Comment by yangzhongj** [comment]
![image](https://user-images.githubusercontent.com/6899065/190348361-7805e005-6c11-4cfd-9bca-ea3ba37c8ddf.png)

**Comment by AlbumenJ** [comment]
This is a bug of fastjson. See https://github.com/alibaba/fastjson/issues/2366 

Try configure `-Ddubbo.json-framework.prefer=gson` to bypass this.

In Dubbo 3.2, Dubbo will use fastjson2 as default and no longer depend on fastjson. Fastjson2 has fix this in 2.0.16.
