### ISSUE TITLE
dubbo 是否能去掉fastjson依赖呢

### ISSUE THREAD

**Issue by hujun-w-2** [apache/dubbo#10621]
fastjson依赖目前漏洞较多，是否可以换成gson呢

**Comment by hujun-w-2** [comment]
@chickenlj 大佬，能否帮忙解答一下？

**Comment by AlbumenJ** [comment]
> ![TU5MaWooYS](https://user-images.githubusercontent.com/39894911/190173490-7d7130bc-aeb1-4c9a-943b-d21f1dcbcbbb.jpg) fa发现一个自动切换json框架的依赖，是否意味着3.0.10版本已经可以完全不依赖fastjson了

是的，但是由于兼容目的，目前 fastjson 还是会传递依赖出去。在未来合适的版本上会去掉这个传递依赖

**Comment by hujun-w-2** [comment]
出于兼容目的是什么意思呢，如果我以前老版本的dubbo服务使用的是fastjson，升级到3.0.10切换成gson会有什么问题吗？

**Comment by AlbumenJ** [comment]
> 出于兼容目的是什么意思呢，如果我以前老版本的dubbo服务使用的是fastjson，升级到3.0.10切换成gson会有什么问题吗？

有的应用因为 dubbo 传递依赖了 fastjson 就直接使用了 fastjson，如果 dubbo 不再传递以来会导致这些应用报错

**Comment by JavaLionLi** [comment]
建议使用jackson 通用spring自带 安全性可靠性都高

**Comment by JavaLionLi** [comment]
> 出于兼容目的是什么意思呢，如果我以前老版本的dubbo服务使用的是fastjson，升级到3.0.10切换成gson会有什么问题吗？

gson性能和可靠性还有功能强度都没有jackson好 相信spring最好了
