### ISSUE TITLE
由于 NettyServer、NettyClient，doOpen 只会执行一次，导致 NettyCodecAdapter 持有 url 不变，从而影响 接口粒度 SPI扩展配置参数 作用失效或异常。(2.5x、2.6.x、2.7.x、3.x版本)

### ISSUE THREAD

**Issue by daixiansuo** [apache/dubbo#10620]
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/41660452/190147781-7fbad7b9-0fbd-4bf4-abfb-c4fccf9caf53.png">
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/41660452/190147883-dbb22e0e-920a-44f6-a45f-ed180436aca3.png">
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/41660452/190148494-79211415-92e1-4b9e-849c-f9e390f7a124.png">

服务暴露 export ，createServer 只会创建一次，但是传入的 url 始终是第一个。 NettyClient 同理。

问题：

NettyServer 接收到请求时，netty pipeline 首先就是 编码解码， 而 NettyCodecAdapter 创建一次，持有的url不变。

如果指定某个 interface 的 序列化方式、timeout等 其它扩展参数， 则不起作用，除非 interface 是第一个对外暴露，如果特殊化配置的 interface 对外暴露，则全局都是这种配置。

**Comment by daixiansuo** [comment]
查看了 2.5.x、2.6.x、2.7.x、3.0.x 版本源码，NettyCodecAdapter 持有的 url 不变，目前只会影响接口粒度 serialization 执定不同SPI扩展。

**Comment by daixiansuo** [comment]
@chickenlj

**Comment by AlbumenJ** [comment]
现在高版本 serialization 会在请求的时候先配置好，不会落到通过 channel 获取的，channel 只是一个兜底策略

**Comment by AlbumenJ** [comment]
`org.apache.dubbo.rpc.protocol.dubbo.DubboCodecSupport#getRequestSerialization`
`org.apache.dubbo.rpc.protocol.dubbo.DubboCodecSupport#getResponseSerialization`

**Comment by daixiansuo** [comment]
高版本 是指 从哪个版本开始 ？

**Comment by AlbumenJ** [comment]
2.7.8 版本

**Comment by daixiansuo** [comment]
好的，感谢。 哪也就是说 2.7.8 以下的版本都会有这个问题？

**Comment by AlbumenJ** [comment]
> 好的，感谢。 哪也就是说 2.7.8 以下的版本都会有这个问题？

是的
