### ISSUE TITLE
dubbo调用拦截扩展和SkyWalkingTID集成问题

### ISSUE THREAD

**Issue by ilovedumplings** [apache/dubbo#10633]
https://dubbo.apache.org/zh/docs/v2.7/dev/impls/filter/

在这里面实现了调用拦截扩展DubboLogFilter,目的是用于打印一些参数，然后日志里继承了skywalking的TID组件,但是在DubboLogFilter里打印日志无法打印TID参数,在正常方法参数里可以。这个是不是和skywalking的机制有什么关系呢

**Comment by AlbumenJ** [comment]
得看下和 skywalking 的顺序问题

**Comment by shelltea** [comment]
可以尝试通过`@Activate`控制Filter的顺序。
```
@Activate(group = CommonConstants.PROVIDER, order = 1)
```

**Comment by ilovedumplings** [comment]
> 可以尝试通过`@Activate`控制Filter的顺序。
> 
> ```
> @Activate(group = CommonConstants.PROVIDER, order = 1)
> ```
> 
> 如果是用`TraceIdMDCPatternLogbackLayout`打印TID，也可以尝试在Filter中通过`TraceContext.traceId()`获取TID然后设置到MDC

我试了试,是可以的,但是这个原理是什么啊?感觉不可能的事,但缺成了可能,因为我感觉调用链是一个的,skywalking这么叼?

**Comment by JavaLionLi** [comment]
> > 可以尝试通过`@Activate`控制Filter的顺序。
> > ```
> > @Activate(group = CommonConstants.PROVIDER, order = 1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果是用`TraceIdMDCPatternLogbackLayout`打印TID，也可以尝试在Filter中通过`TraceContext.traceId()`获取TID然后设置到MDC
> 
> 我试了试,是可以的,但是这个原理是什么啊?感觉不可能的事,但缺成了可能,因为我感觉调用链是一个的,skywalking这么叼?

你的处理优先级比他搞 还没等到他呢 你就打印了 就是这个原理
