### ISSUE TITLE
Start two provider,but only get one on Router

### ISSUE THREAD

**Issue by shihaojun** [apache/dubbo#10659]
version:3.1.0
on org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener#getServiceUrlsCache

            for (ServiceInstance i : revisionToInstances.get(r)) {
                if (port > 0) {
                    if (i.getPort() == port) {
                        urls.add(i.toURL(protocol).setScopeModel(i.getApplicationModel()));
                    } else {
                        urls.add(((DefaultServiceInstance) i).copyFrom(port).toURL(protocol).setScopeModel(i.getApplicationModel()));
                    }
                    continue;
                }
this code change another provider's port, so this two url has the same ip:port
It's a bug or I use dubbo on the wrong way?
By the way It would't happen on version 2.7.5

provider like this:
_public static <T, P extends T> void export(Class<T> interfaceClass, P implClass, int port) {
        ServiceConfig<T> serviceConfig = new ServiceConfig<>();
        serviceConfig.setInterface(interfaceClass);
        serviceConfig.setRef(implClass);
        serviceConfig.setProtocol(new ProtocolConfig("dubbo", port));
        DubboBootstrap.getInstance().service(serviceConfig);
        DubboBootstrap.getInstance().start().await();
    }_

consumer like this:
public static <T> T refer(Class<T> interfaceClass) {
        ReferenceConfig<T> referenceConfig = new ReferenceConfig<>();
        referenceConfig.setInterface(interfaceClass);
        referenceConfig.setCheck(false);
        referenceConfig.setLazy(true);
        referenceConfig.setSticky(false);
        referenceConfig.setLoadbalance(router);
        referenceConfig.setRouter(router);
        return referenceConfig.get();
    }

**Comment by AlbumenJ** [comment]
Two url with same ip:port will be regarded as one url. In some cases, the registry may push duplicate urls.
If you want to change the weight of provider, try use `weight` param.

**Comment by shihaojun** [comment]
I did what you say, and it works. Thanks
has init route and size is:2
A hello0
has init route and size is:2
B hello 1

But it's that a BUG? or dubbo has been design like this?
before
![image](https://user-images.githubusercontent.com/17853775/192145750-be49533a-2fb5-4e37-be7e-5c4b2f1977a1.png)
after
![image](https://user-images.githubusercontent.com/17853775/192145503-690c9124-0989-4aef-a2e6-75960fc78692.png)

If those provider has same weight it still got one
has init route and size is:1
B hello 0
has init route and size is:1
B hello 1

**Comment by AlbumenJ** [comment]
May fixed in https://github.com/apache/dubbo/pull/10606

Please try 3.1.1-SNAPSHOT, or 3.1.1 ( will be formal release in three days)

**Comment by shihaojun** [comment]
Thank you

**Comment by AlbumenJ** [comment]
3.1.1 has been released. Please feel free to reopen this issue if you have any question.
