### ISSUE TITLE
【NacosRegistryFactory】org.apache.dubbo:dubbo-registry-nacos:2.7.3 doRegistry properties没有设置进username,password属性值

### ISSUE THREAD

**Issue by topsuder** [apache/dubbo#10654]
- [🤙] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. 使用 org.apache.dubbo:dubbo-registry-nacos:2.7.3
2. 配置文件registry设置为nacos:// spi
3. 注册时unknown user! 

### Expected Behavior

提供新的NacosRegistryFactory

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Caused by: com.alibaba.nacos.api.exception.NacosException: unknown user!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:282) ~[nacos-client-2.0.4.jar:na]
	... 36 common frames omitted
```

**Comment by AlbumenJ** [comment]
2.7.3 不支持，请升级到 2.7 最新版本
