### ISSUE TITLE
2.7.3.1 升级至 3.0.10 DubboShutdownHook

### ISSUE THREAD

**Issue by songzhiying** [apache/dubbo#10657]
原来在2.7.3.1 中存在DubboShutdownHook与spring 重复的问题，3.0.10中是怎么处理的？？

**Comment by AlbumenJ** [comment]
related with https://github.com/apache/dubbo/issues/10652

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo/pull/10730
