### ISSUE TITLE
dubbo 3.1.0 密码不支持 特殊字符

### ISSUE THREAD

**Issue by haroldyong** [apache/dubbo#10650]
ERROR | main | TID: N/A | o.apache.dubbo.config.utils.ConfigValidationUtils 734 |  [DUBBO] Invalid password="nacos@852146970" contains illegal character, only digit, letter, '-', '_' or '.' is legal., dubbo version: 3.1.0, current host: 192.168.0.21

**Comment by haroldyong** [comment]
在使用nacos作为注册中心，如果nacos的用户密码包含特殊字符，在代码中会报告如上错误。
请项目组考虑一下，是否需要放开这种限制，谢谢

**Comment by AlbumenJ** [comment]
Dubbo 3.1 目前在遇到非法字符之后应该只是打日志而已，数据还是正常使用的

**Comment by KeJemas** [comment]
这问题3.2.8一样存在

**Comment by xiohuchi** [comment]
这问题3.2.10 还是存在
