### ISSUE TITLE
provider 抛出自定义异常问题

### ISSUE THREAD

**Issue by a4363220** [apache/dubbo#10679]
### Environment

* Dubbo version: 3.1.0
* Operating System version: windows
* Java version: jdk8
* protocol：tri
* serialization：kryo

问题描述：consumer将provider端抛出的自定义异常转换成了RpcException

目的：
参考了多种解决方案，有些方案中使用的dubbo版本已经落后于我当前的dubbo版本了，我想咨询一下目前官方
有针对provider统一异常的方案吗？或者就近的版本会更新解决这个问题
 
目前采取过的方案：
1.在provider端拓展ExceptionFilter，使其抛出BizException，但是客户端还是用RpcException进行了转换
2.在provider回传异常的code和msg，但是在consumer的clusterFilter中却拿不到provider回传的code和msg
3.在api接口声明BizException，无效，还是RpcException

**Comment by a4363220** [comment]
> 方案三无问题一直都是这么用的 可以自己看源码 自己声明的异常不进行包装处理

public void hello()throws BizException , 这种形式还需要将异常包装？

**Comment by AlbumenJ** [comment]
tri 协议目前暂不支持抛出异常，下个版本将正式支持抛自定义异常。

**Comment by a4363220** [comment]
> tri 协议目前暂不支持抛出异常，下个版本将正式支持抛自定义异常。

您好 下个版本大概预计什么时间上线呀？

**Comment by AlbumenJ** [comment]
> > tri 协议目前暂不支持抛出异常，下个版本将正式支持抛自定义异常。
> 
> 您好 下个版本大概预计什么时间上线呀？

下个月底会正式发布

**Comment by a4363220** [comment]
> > > tri 协议目前暂不支持抛出异常，下个版本将正式支持抛自定义异常。
> > 
> > 
> > 您好 下个版本大概预计什么时间上线呀？
> 
> 下个月底会正式发布

好的

**Comment by yanan-wyze** [comment]
> > > tri 当前协议暂不支持抛出异常，下个版本将正式支持抛自定义异常。
> > 
> > 
> > 您好下个版本预计什么时间上线呀？
> 
> 下个月底会正式发布

请问dubbo 3.1.1 支持自定义抛出异常了吗？

**Comment by AlbumenJ** [comment]
Enhanced in #10667
