### ISSUE TITLE
有考虑使用kryo5.X么 4.X最后更新时间是2018年 5.X目前已经更新到5.3.0了 更新的很活跃 功能也更好一些

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#10687]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by EarthChen** [comment]
欢迎提个 pr来支持一下 https://github.com/apache/dubbo-spi-extensions

**Comment by JavaLionLi** [comment]
> 欢迎提个 pr来支持一下 https://github.com/apache/dubbo-spi-extensions

我自己也尝试搞了 但是差异太大 找不到对应的升级后的写法 官网也没有升级指南 能力有限了

**Comment by JavaLionLi** [comment]
> 欢迎提个 pr来支持一下 https://github.com/apache/dubbo-spi-extensions

https://github.com/apache/dubbo-spi-extensions/pull/141 已经提交了pr 简单做了一下适配 应该还有可以优化的地方

**Comment by JavaLionLi** [comment]
https://github.com/apache/dubbo-spi-extensions/pull/142

**Comment by JavaLionLi** [comment]
已完成pr合并
