### ISSUE TITLE
3.1.0 使用kryo报错找不到实现类 文档里只说标注序列化配置为kryo即可 还需要加什么依赖么 我看源码里也没有关于kryo的依赖包啊

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#10684]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JavaLionLi** [comment]
3.X目前是还没有提供kryo的依赖么

**Comment by JavaLionLi** [comment]
> https://dubbo.apache.org/zh/release/dubbo-spi-extensions/#dubbo-serialization
> 
> 加一下这个依赖：
> 
> ```
> <dependency>
>   <groupId>org.apache.dubbo.extensions</groupId>
>   <artifactId>dubbo-serialization-kryo</artifactId>
>   <version>1.0.0</version>
> </dependency>
> ```

可以了 sdk文档里这个章节一点关于这个依赖的痕迹都没有 建议文档优化一下 根本不知所踪啊

**Comment by AlbumenJ** [comment]
> > https://dubbo.apache.org/zh/release/dubbo-spi-extensions/#dubbo-serialization
> > 加一下这个依赖：
> > ```
> > <dependency>
> >   <groupId>org.apache.dubbo.extensions</groupId>
> >   <artifactId>dubbo-serialization-kryo</artifactId>
> >   <version>1.0.0</version>
> > </dependency>
> > ```
> 
> 可以了 sdk文档里这个章节一点关于这个依赖的痕迹都没有 建议文档优化一下 根本不知所踪啊

可以的，要不你来帮忙搞一下，提交到 dubbo-website

**Comment by JavaLionLi** [comment]
> > > https://dubbo.apache.org/zh/release/dubbo-spi-extensions/#dubbo-serialization
> > > 加一下这个依赖：
> > > ```
> > > <dependency>
> > >   <groupId>org.apache.dubbo.extensions</groupId>
> > >   <artifactId>dubbo-serialization-kryo</artifactId>
> > >   <version>1.0.0</version>
> > > </dependency>
> > > ```
> > 
> > 
> > 可以了 sdk文档里这个章节一点关于这个依赖的痕迹都没有 建议文档优化一下 根本不知所踪啊
> 
> 可以的，要不你来帮忙搞一下，提交到 dubbo-website

已经提交 https://github.com/apache/dubbo-website/pull/1525
