### ISSUE TITLE
3.1.1 国庆之前是不打算发布了么

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#10689]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by JavaLionLi** [comment]
@AlbumenJ 有几个挺严重的bug 公司希望可以尽快更新到3.1.1 请问什么时候可以正式发布啊

**Comment by AlbumenJ** [comment]
今天或明天会发完
