### ISSUE TITLE
Triple协议是否可以在2.7.x中支持

### ISSUE THREAD

**Issue by jybjobs** [apache/dubbo#10696]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
在Dubbo 3.x中只支持了部分2.x中的协议；这样的话我们之前使用到其它协议的项目升级3.0就需要先切换协议，后升级框架，最后按照推荐还需要再切换为triple协议，然后变更注册方式为application，这样是不是走了很多弯路？
如果2.x能直接支持Triple协议的话，就简单很多了。

**Comment by liufeiyu1002** [comment]
3.x 应该都支持吧。https://github.com/apache/dubbo-spi-extensions  你看这个项目里的 spi扩展应该有你用到的 协议适配吧

**Comment by jybjobs** [comment]
好的，多谢
