### ISSUE TITLE
isConsumerSide 报  null 问题

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#10704]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.1
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/31852897/194680205-3f01cc95-7cef-42e3-b784-acac97e37c28.png)
![image](https://user-images.githubusercontent.com/31852897/194680478-f890d46d-eb53-42a3-90c8-24325d42b741.png)

不应该报null的地方 却报null了 好多原先好使的 现在都不好使了 3.0.9无问题

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JavaLionLi** [comment]
![image](https://user-images.githubusercontent.com/31852897/194681426-28dcb7e2-d176-472a-8bb0-ddeeeda8f74e.png)
只要是injvm 获取url全都是null 导致后续所有操作全都报null

**Comment by JavaLionLi** [comment]
![image](https://user-images.githubusercontent.com/31852897/194681608-5beb2b6e-9085-4c00-8d8e-f722131f7b7b.png)

**Comment by AlbumenJ** [comment]
org/apache/dubbo/rpc/filter/ContextFilter.java:95 看一下这个地方有没有设置进去

**Comment by JavaLionLi** [comment]
> org/apache/dubbo/rpc/filter/ContextFilter.java:95 看一下这个地方有没有设置进去

![image](https://user-images.githubusercontent.com/31852897/194682666-9b05c3bf-829c-431a-813c-280870ee4a31.png)
这个只有PROVIDER有效 我现在想在CONSUMER打日志 拿不到数据

**Comment by AlbumenJ** [comment]
org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66
consumer 应该是这个

**Comment by JavaLionLi** [comment]
> org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个

还没等执行到这个类的时候 就已经执行上面的方法并报错了

**Comment by AlbumenJ** [comment]
> > org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个
> 
> 还没等执行到这个类的时候 就已经执行上面的方法并报错了

你的 order 是不是 min-value

**Comment by JavaLionLi** [comment]
> > > org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个
> > 
> > 
> > 还没等执行到这个类的时候 就已经执行上面的方法并报错了
> 
> 你的 order 是不是 min-value

并不是 没有设置order用的默认的

**Comment by AlbumenJ** [comment]
> > > > org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个
> > > 
> > > 
> > > 还没等执行到这个类的时候 就已经执行上面的方法并报错了
> > 
> > 
> > 你的 order 是不是 min-value
> 
> 并不是 没有设置order用的默认的

Filter 整个定义脱敏后发一下

**Comment by JavaLionLi** [comment]
> > > > > org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个
> > > > 
> > > > 
> > > > 还没等执行到这个类的时候 就已经执行上面的方法并报错了
> > > 
> > > 
> > > 你的 order 是不是 min-value
> > 
> > 
> > 并不是 没有设置order用的默认的
> 
> Filter 整个定义脱敏后发一下

`/**
 * dubbo日志过滤器
 *
 * @author Lion Li
 */
@Slf4j
@Activate(group = {CommonConstants.PROVIDER, CommonConstants.CONSUMER})
public class DubboRequestFilter implements Filter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        String client = CommonConstants.PROVIDER;
        if (RpcContext.getServiceContext().isConsumerSide()) {
            client = CommonConstants.CONSUMER;
        }
        String baselog = "Client[" + client + "],InterfaceName=[" + invocation.getInvoker().getInterface().getSimpleName() + "],MethodName=[" + invocation.getMethodName() + "]";
        log.info("DUBBO - 服务调用: {},Parameter={}", baselog, invocation.getArguments());

        long startTime = System.currentTimeMillis();
        // 执行接口调用逻辑
        Result result = invoker.invoke(invocation);
        // 调用耗时
        long elapsed = System.currentTimeMillis() - startTime;
        // 如果发生异常 则打印异常日志
        if (result.hasException() && invoker.getInterface().equals(GenericService.class)) {
            log.error("DUBBO - 服务异常: {},Exception={}", baselog, result.getException());
        } else {
            log.info("DUBBO - 服务响应: {},SpendTime=[{}ms]", baselog, elapsed);
        }
        return result;
    }

}`

**Comment by JavaLionLi** [comment]
> > > > > org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个
> > > > 
> > > > 
> > > > 还没等执行到这个类的时候 就已经执行上面的方法并报错了
> > > 
> > > 
> > > 你的 order 是不是 min-value
> > 
> > 
> > 并不是 没有设置order用的默认的
> 
> Filter 整个定义脱敏后发一下

就拦截打印了一下日志 很简单的 filter

**Comment by JavaLionLi** [comment]
> > > > > > org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:66 consumer 应该是这个
> > > > > 
> > > > > 
> > > > > 还没等执行到这个类的时候 就已经执行上面的方法并报错了
> > > > 
> > > > 
> > > > 你的 order 是不是 min-value
> > > 
> > > 
> > > 并不是 没有设置order用的默认的
> > 
> > 
> > Filter 整个定义脱敏后发一下
> 
> ```/**
 * dubbo日志过滤器
 *
 * @author Lion Li
 */
@Slf4j
@Activate(group = {CommonConstants.PROVIDER, CommonConstants.CONSUMER})
public class DubboRequestFilter implements Filter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        String client = CommonConstants.PROVIDER;
        if (RpcContext.getServiceContext().isConsumerSide()) {
            client = CommonConstants.CONSUMER;
        }
        String baselog = "Client[" + client + "],InterfaceName=[" + invocation.getInvoker().getInterface().getSimpleName() + "],MethodName=[" + invocation.getMethodName() + "]";
        log.info("DUBBO - 服务调用: {},Parameter={}", baselog, invocation.getArguments());

        long startTime = System.currentTimeMillis();
        // 执行接口调用逻辑
        Result result = invoker.invoke(invocation);
        // 调用耗时
        long elapsed = System.currentTimeMillis() - startTime;
        // 如果发生异常 则打印异常日志
        if (result.hasException() && invoker.getInterface().equals(GenericService.class)) {
            log.error("DUBBO - 服务异常: {},Exception={}", baselog, result.getException());
        } else {
            log.info("DUBBO - 服务响应: {},SpendTime=[{}ms]", baselog, elapsed);
        }
        return result;
    }

}```

**Comment by AlbumenJ** [comment]
应该和 https://github.com/apache/dubbo/pull/9645 这个 PR 有关系，导致 Dubbo Cluster Filter 没生效，我看下是哪里导致的

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/pull/10707 这个我先 revert 了

**Comment by AlbumenJ** [comment]
Will be fixed in 3.0.13, 3.1.2

**Comment by pzl-1995** [comment]
请问下最后是用什么方式解决的，我是在切换成非admin用户使用时，debug发现这里报错，麻烦告知一下

**Comment by JavaLionLi** [comment]
@AlbumenJ

**Comment by AlbumenJ** [comment]
之前修复是在 3.0 分支做的，发版的时候没有合并到新分支。
这个已经修复 https://github.com/apache/dubbo/commit/ae0a371690546ce859f2041814f76dad2c710fd9

对应的集成测试用例已经完善，https://github.com/apache/dubbo-samples/pull/586。
