### ISSUE TITLE
dubbo2.7.15版本中，是不是移除了Config-Center的支持

### ISSUE THREAD

**Issue by 2227324689** [apache/dubbo#10706]
今天使用2.7.15版本，增加配置中心的支持时，发现配置中心没有被识别。并且zookeeper上也没有生成dubbo.properties节点。
我记得在早期版本里面是支持的。
我刚刚是了下Dubbo3.x版本，它是支持配置中心的。

**Comment by AlbumenJ** [comment]
2.7.15 应该是支持配置中心的，可以看下是不是配置没生效导致的

**Comment by 2227324689** [comment]
嗯，我后来测试了一下是可以的。
