### ISSUE TITLE
Micrometer Observation Support

### ISSUE THREAD

**Issue by marcingrzejszczak** [apache/dubbo#10742]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

I'm a co-maintainer of Spring Cloud Sleuth and Micrometer projects (together with @shakuzen and @jonatan-ivanov). 

Spring Cloud Sleuth 3.1.x is the last line of Spring Cloud Sleuth. There will be no Spring Cloud Sleuth 3.2 nor 4.0 (you can read more [here]( https://github.com/spring-cloud/spring-cloud-sleuth/tree/main#spring-cloud-sleuth)). There will be no Spring Boot 3 compatible version of Spring Cloud Sleuth. Sleuth will be replaced by Micrometer Observation and Micrometer Tracing.

[Micrometer Observation](https://micrometer.io/docs/observation) is coming as part of the Micrometer 1.10 release and [Micrometer Tracing](https://micrometer.io/docs/tracing) is a new project. The idea of Micrometer Observation is that you instrument code once but you get multiple benefits out of it - e.g. you can get tracing, metrics, logging or whatever you see fit). In terms of deadlines - Micrometer 1.10.0 GA is planned for 7.11 at the moment (https://github.com/micrometer-metrics/micrometer/milestone/177). 

Since Dubbo already support Micrometer I was curious if there's interest in adding Micrometer Observation support so that automatically (when on classpath) except for metrics, spans could be created and tracing context propagation could happen too. If there's such interest we could provide a PR to add support for that.

**Comment by AlbumenJ** [comment]
Sounds great! Please go ahead.

**Comment by marcingrzejszczak** [comment]
Hey I've created a PR (https://github.com/apache/dubbo/pull/11021) and I did my best there ;) unfortunately I had no luck in running any samples to start 2 dubbo apps to perform some end to end tests so I guess I'll need some help there.
