### ISSUE TITLE
JsonUtils Support Fastjson2

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10790]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by yuchu01** [comment]
fastjson2 2.0.15, 2.0.16改动未兼容好fastjson1, 遇到rocketmq-client连接 rocketmq server异常问题。待后续社区版本修复升级依赖。(记录一下)

**Comment by AlbumenJ** [comment]
> fastjson2 2.0.15, 2.0.16改动未兼容好fastjson1, 遇到rocketmq-client连接 rocketmq server异常问题。待后续社区版本修复升级依赖。(记录一下)

@wenshao PTAL

**Comment by yuchu01** [comment]
>  fastjson2 2.0.15, 2.0.16改动未兼容好fastjson1, 遇到rocketmq-client连接 rocketmq server异常问题。待后续社区版本修复升级依赖。(记录一下)

fixed fastjson2  version 2.0.17

**Comment by wenshao** [comment]
https://github.com/alibaba/fastjson2/releases/tag/2.0.17
问题已修复，请用新版本

**Comment by CrazyHZM** [comment]
Resolved at https://github.com/apache/dubbo/pull/10791
