### ISSUE TITLE
Support netty3 and other transporters in port unification

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10812]
> I wonder if user configure `netty 3` in properties what will happen?

`No such extension org.apache.dubbo.remoting.api.pu.PortUnificationTransporter by name netty3`
current version does not support `netty3`.  change `netty4` to be compatible with lower version

_Originally posted by @icodening in https://github.com/apache/dubbo/issues/10797#issuecomment-1288370452_

**Comment by asa3311** [comment]
hi
