### ISSUE TITLE
Add deprecated method usage check in unit test

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#10849]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal
Check if deprecated method being used in unit test and fail the test. 
A possible way is to work with jacoco.

**Comment by etcZYP** [comment]
assign to me

**Comment by erdengk** [comment]
Can this task be assigned to me? The last contributor doesn't seem to have time for this.
I already have some ideas to do this.Through the code review function of the idea, I can quickly complete this task.
@AlbumenJ

**Comment by AlbumenJ** [comment]
Related with https://github.com/apache/dubbo/pull/11513

**Comment by AlbumenJ** [comment]
> I already have some ideas to do this.Through the code review function of the idea, I can quickly complete this task.

@etcZYP Any detailed proposal about this?

**Comment by AlbumenJ** [comment]
Track in https://github.com/apache/dubbo/issues/10850
