### ISSUE TITLE
Dubbo 升级 2.7.18 后，导致 Dubbo-admin 无法反解析！

### ISSUE THREAD

**Issue by Suremotoo** [apache/dubbo#10845]
之前将反馈发布在了 Dubbo-admin 仓库中，完整请移步:  https://github.com/apache/dubbo-admin/issues/936

**Comment by AlbumenJ** [comment]
这一块 Dubbo 3.x 的高版本中已经解决了，可以用下 3.1.1 或者 3.0.12 看看

对于 2.7.x 的兼容可以在的 dubbo-admin 进行解析的时候通过 gson 和 fastjson 都尝试解析（或者直接使用 fastjson 去解析），这块需要 dubbo-admin 发版看下

**Comment by Suremotoo** [comment]
> 

由于已经用于生产环境，升级大版本可能影响多，我们尽量想升至 2.7.18 版本，您那边可以在 Dubbo 2.7.18 版本环境下，尝试 在 Dubbo-admin 中解决此问题吗？

**Comment by Suremotoo** [comment]
最终还是调整源码后重新打包得以使用，还是感谢耐心反馈！
