### ISSUE TITLE
provider Filter 内 如何获得这个属性 org.apache.dubbo.rpc.proxy.AbstractProxyInvoker#proxy

### ISSUE THREAD

**Issue by gMan1990** [apache/dubbo#10866]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
比如 `public interface DemoService`
`public class DemoServiceImpl implements DemoService {`

调用 DemoService，在provider Filter里可以获得 `getInterface` `getMethodName`  但我想获得 `DemoServiceImpl实例` 或者`DemoServiceImpl.class`

**Comment by AlbumenJ** [comment]
> * [ ]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> 
> ## Ask your question here
> 比如 `public interface DemoService` `public class DemoServiceImpl implements DemoService {`
> 
> 调用 DemoService，在provider Filter里可以获得 `getInterface` `getMethodName` 但我想获得 `DemoServiceImpl实例` 或者`DemoServiceImpl.class`

在 3.x 版本可以这样获取 `invocation.getServiceModel().getProxyObject()`
