### ISSUE TITLE
自2.7.5版本后 dubbo泛化实现存在问题不能正常反序列化的情形

### ISSUE THREAD

**Issue by iloveoovo** [apache/dubbo#10868]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.18
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. 服务端采用dubbo泛化实现方式，服务端直接返回map类型的响应对象，响应对象中有list集合，list中返回的数据为map结构
2. 客户端正常调用，收到的响应数据list中的map结构没有转换为接口定义的实际java对象，导致程序做进一步处理报错
3. 经验证3.1.1 版本仍然存在该问题
4. 经排查后出问题的类为DecodeableRpcResult，代码段如下：
<img width="768" alt="image" src="https://user-images.githubusercontent.com/12338948/199507015-8b9ca5ed-17c6-475f-9190-6cf021f2dbea.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/12338948/199507116-9adc85b7-14c9-47c9-9b53-f94eec2f33c2.png">

Pls. provide [GitHub address] to reproduce this issue.
https://github.com/iloveoovo/dubbo-genericimpl-issue

### Expected Behavior

consumer端能正常反序列化

### Actual Behavior
consumer 端对于响应参数字段中List 字段的泛型处理错误

**Comment by AlbumenJ** [comment]
泛化掉用实际反序列化是在 `org.apache.dubbo.rpc.filter.GenericFilter` 中进行的。需要看服务端返回的格式是怎么样的，以及对应类是否真的存在。

**Comment by iloveoovo** [comment]
是泛化实现不正确，如下图所示：标志1是接口定义，标注2是实际返回的数据
<img width="845" alt="image" src="https://user-images.githubusercontent.com/12338948/199627272-1330359a-3b8d-425b-b909-e55fc2702d6a.png">

针对泛化实现这个场景, 由于DecodeableRpcResult 没有进入图1中的位置，导致后续通过PojoUtils进行map转bean的分支进入不了：
<img width="767" alt="image" src="https://user-images.githubusercontent.com/12338948/199628252-c6ce5bf3-6c49-4896-8ac7-68a59424e6ea.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/12338948/199628335-964dd314-bed3-4586-82af-c2ad192db20e.png">
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/12338948/199628410-b138523b-1f38-47c8-938f-be29c235538e.png">

**Comment by iloveoovo** [comment]
> 泛化掉用实际反序列化是在 `org.apache.dubbo.rpc.filter.GenericFilter` 中进行的。需要看服务端返回的格式是怎么样的，以及对应类是否真的存在。

2.7.4.1以前都能正常处理的

**Comment by AlbumenJ** [comment]
可以提供一个 Demo 吗，泛化实现和 dubbo 协议本身是解耦的，如果有行为差异应该还是在别的地方。

**Comment by iloveoovo** [comment]
demo地址： https://github.com/iloveoovo/dubbo-genericimpl-issue

**Comment by iloveoovo** [comment]
> 可以提供一个 Demo 吗，泛化实现和 dubbo 协议本身是解耦的，如果有行为差异应该还是在别的地方。

demo地址： https://github.com/iloveoovo/dubbo-genericimpl-issue

**Comment by AlbumenJ** [comment]
问题已定位，是在 GenericImplFilter 中重建 Invocation 时 returnType 没有覆盖，导致 hessian 尝试通过对应类提前反序列化

**Comment by creabob** [comment]
When Dubbo version from 2.7.5 to 2.7.23, How to solve this problem in generic implement?
because this solution only commit in version 3.1.2.

在2.7.5至2.7.23版本，如何解决该场景下泛化实现问题？
该解决方案只在3.1.x版本修复，2.7.x版本如何处理
