### ISSUE TITLE
官网总是打不开

### ISSUE THREAD

**Issue by zfovikqdev928** [apache/dubbo#10878]
官网地址总是打不开，是什么原因呢？
![image](https://user-images.githubusercontent.com/66060529/199905283-b28c18b9-0ee7-409b-997a-4c63276f9989.png)

**Comment by AlbumenJ** [comment]
这个是因为 apache.org 域是没有备案的，只能连接在 jp 或者 sg 的节点。

**Comment by kimmking** [comment]
VPN is better.

**Comment by zfovikqdev928** [comment]
VPN was not accessible before, but now it is possible. Thanks !
