### ISSUE TITLE
整合 skywalking 有问题 sky社区让我来dubbo社区问

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#10879]
https://github.com/apache/skywalking/issues/9905
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.0
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JavaLionLi** [comment]
https://github.com/apache/skywalking/issues/9905

**Comment by yuchu01** [comment]
我有在用skywalking，在3.1.0版本没遇到这个问题。你看看是不是skywalking哪里配置错了

**Comment by JavaLionLi** [comment]
> 我有在用skywalking，在3.1.0/3.1.1版本没遇到这个问题。你看看是不是skywalking哪里配置错了
> 
> * apache/skywalking-java-agent:8.10.0-alpine
> * dubbo 3.1.0 / 3.1.1

啥也没有配置 默认的依赖 默认的插件 A服务有B服务没有 单指logback

**Comment by JavaLionLi** [comment]
> > 我有在用skywalking，在3.1.0/3.1.1版本没遇到这个问题。你看看是不是skywalking哪里配置错了
> > 
> > * apache/skywalking-java-agent:8.10.0-alpine
> > * dubbo 3.1.0 / 3.1.1
> 
> 啥也没有配置 默认的依赖 默认的插件 A服务有B服务没有 单指logback



> 我有在用skywalking，在3.1.0/3.1.1版本没遇到这个问题。你看看是不是skywalking哪里配置错了
> 
> * apache/skywalking-java-agent:8.10.0-alpine
> * dubbo 3.1.0 / 3.1.1

我也是求证了好几个人 反馈都是有问题 agent-8.12.0 dubbo 3.1.0

**Comment by EarthChen** [comment]
dubbo 侧的配置可以发一下嘛  最好能给的 demo

**Comment by JavaLionLi** [comment]
应该跟dubbo关系不大 ui界面是有链路的 只有logback不输出
