### ISSUE TITLE
ApplicationConfig的enableFileCache属性默认null，导致无本地缓存

### ISSUE THREAD

**Issue by lx-maker** [apache/dubbo#10880]
![image](https://user-images.githubusercontent.com/54169514/199922630-ba1b1417-e124-40b1-bac7-49158e2adbca.png)

文档上ApplicationConfig的enableFileCache属性默认true，但是在Dubbo3.1版本中，该属性似乎默认为null，导致mapping和元数据无法在本地缓存。

![image](https://user-images.githubusercontent.com/54169514/199923129-c99ea29b-45c5-40d1-bc21-1fbb44830fc7.png)

**Comment by AlbumenJ** [comment]
Would you please submit a PR to fix this?

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo/pull/11008
