### ISSUE TITLE
使用Triple协议，调用端如何捕获服务端抛出的自定义异常

### ISSUE THREAD

**Issue by veerdone** [apache/dubbo#10908]
在服务端抛出自定义异常后，调用端捕获的是RpcException，并不是我自定义的异常，我要怎样才能捕获到这个自定义异常
如果使用的是 dubbo 协议是可以正确捕获，切换为 Triple 协议后就无法正确捕获了

**Comment by aamingaa** [comment]
你的Dubbo是什么版本，现在3.2是支持自定义异常的

**Comment by veerdone** [comment]
> 你的Dubbo是什么版本，现在3.2是支持自定义异常的

3.1版本的

**Comment by aamingaa** [comment]
> 

升级下版本试试？triple自定义异常是新特性，dubbo 3.2 才支持这个功能

**Comment by aamingaa** [comment]
> 3.1


升级下版本试试？triple自定义异常是新特性，dubbo 3.2 才支持这个功能

**Comment by veerdone** [comment]
> > 3.1
> 
> 升级下版本试试？triple自定义异常是新特性，dubbo 3.2 才支持这个功能

ok,我等会试试
