### ISSUE TITLE
Why is ScheduledExecutorService used in MemoryLimitCalculator

### ISSUE THREAD

**Issue by Y-evil** [apache/dubbo#10905]
field maxAvailable is not necessary.
and 
`public static long maxAvailable() {
        return Runtime.getRuntime().freeMemory();
}`

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/blob/cc1162feb8fc613c9529d86f996b934d480ac77b/dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/MemoryLimitCalculator.java#L69-L72

It is a cached data
