### ISSUE TITLE
Dubbo有支持Rest Reactive Programming API吗？

### ISSUE THREAD

**Issue by JamesPeng88** [apache/dubbo#10913]
- [ X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ X] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

Dubbo有支持REST Reactive Programming API吗？

**Comment by AlbumenJ** [comment]
https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/reactive/

**Comment by pengsuwei** [comment]
> https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/reactive/

Dubbo 3.x 的Rest协议支持 Reactive API吗？

**Comment by AlbumenJ** [comment]
> > https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/service/reactive/
> 
> Dubbo 3.x 的Rest协议支持 Reactive API吗？

目前只有 triple 协议支持
