### ISSUE TITLE
泛化调用时，传入map对象，在消费端反序列化类型错误

### ISSUE THREAD

**Issue by fangxueshun** [apache/dubbo#10911]
客户端发起泛化调用，使用map包装参数，客户端定义的类继承自map，此时调用就会异常

### Environment

* Dubbo version: 2.7.15
* Operating System version: mac,linux
* Java version: 1.8.0_29

### Steps to reproduce this issue

1. 客户端发起泛化调用，使用map包装参数，给出
2. 消费端反序列化时，会提示强转失败
3. ClassCastException: xxx cannot be cast to xxx

这个问题在版本2.7.0中时不存在的，经过初步定位是因为2.7.15中更新了org.apache.dubbo.common.utils.PojoUtils#realize(java.lang.Object[], java.lang.Class<?>[], java.lang.reflect.Type[])方法的实现导致。

  问题复现代码
  

     public class TestDemo extends JSONObject {
      private String name;
  
      public String getName() {
          return name;
      }
  
      public void setName(String name) {
          this.name = name;
      }
    } 

    public static void main(String[] args) {
        Object[] objects = new Object[1];
        Map<String,Object> map = new HashMap<>();
        map.put("name", "名称");
        map.put("class", TestDemo.class.getName());
        objects[0] = map;

        Object[] realize = PojoUtils.realize(objects, new Class[] {TestDemo.class},
                new Class[] {TestDemo.class});
        System.out.println(realize[0].getClass().getName());
    }

2.7.15输出：java.util.HashMap
2.7.0输出：xxx.TestDemo

相关代码
2.7.15中的实现
![image](https://user-images.githubusercontent.com/10718674/201060879-d4196275-ea41-4618-aedf-a2e0d29a4bb3.png)

2.7.0的实现
![image](https://user-images.githubusercontent.com/10718674/201060949-90a061a6-48b8-404f-8a0a-3a2ffd5e4668.png)

经验证，2.71.5-2.7.18都有改问题，在3.0.0以及以上版本中，改代码已剔除，不会有该问题

**Comment by fangxueshun** [comment]
我这边可以稳定复现的，你那边的如何测试的可以说明下么
![image](https://user-images.githubusercontent.com/10718674/204477811-3c241579-e7eb-4b43-9ff6-c8e93382d96a.png)
![image](https://user-images.githubusercontent.com/10718674/204478004-b9d91d25-065d-4d0f-a96f-57a3d0952af5.png)

**Comment by aamingaa** [comment]
这个问题在3.1已经修复了呢，可以升级到3.1试试
