### ISSUE TITLE
Service co.xx.service.TradeService with version 0.0.0 not found, invocation rejected.

### ISSUE THREAD

**Issue by leron-x** [apache/dubbo#10918]
dubbo版本:3.1.0

nacos版本：2.1.0

spring cloud alibaba版本 2021.0.1.0

运行环境: macOS Ventura 13.0

场景：服务 A 订阅 服务 B、服务C，当服务 B、服务 C 同时重启之后，通信端口发生互换，服务A收到BC服务上线通知，如下图debug所示，但是在获取 MetadataInfo 的时候，subInstances 中的ServiceMetadata 为null，导致这个表达式进入 orElseGet中的逻辑 ，先从本地缓存(/Users/leron/.dubbo/.metadata.trade.nacos.192.168.31.15%003a30848.dubbo.cache)获取服务列表并返回，但是本地的缓存仍然是以前的端口，导致调用失败

异常:Service co.xx.service.TradeService with version 0.0.0 not found, invocation rejected.

现在暂时以删除本地缓存来解决此问题 rm -rf /Users/leron/.dubbo/.*

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/69708227/201288105-8c0c0025-3662-4257-836f-1a53054bae35.png">

**Comment by AlbumenJ** [comment]
升级到 3.1.1 或者 3.1.2 版本，已经修复

**Comment by leron-x** [comment]
> 升级到 3.1.1 或者 3.1.2 版本，已经修复

好的 感谢
