### ISSUE TITLE
Dubbo3下扫描接口注册服务（zookeeper注册中）时告警问题

### ISSUE THREAD

**Issue by haoxz11** [apache/dubbo#10934]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.2
* Operating System version: mac m1
* Java version: 17

### Steps to reproduce this issue

Dubbo3下扫描接口注册服务时，由于会扫描（providers,configurators,routers）三个节点的服务，通常providers排在最后，这个时候

![image](https://user-images.githubusercontent.com/16596043/201563609-9a94904b-3651-4b41-b48f-b0652e57f950.png)

这段代码下会由于前面已经有缓存，会导致告警出现：

2022-11-14 10:26:51.161 WARN  [main]                org.apache.dubbo.registry.integration.RegistryDirectory:?   - XXXX received empty address list with no EMPTY protocol set, trigger empty protection., dubbo version: 3.1.2, current host: 172.16.11.12, error code: 1-4. This may be caused by configuration , go to https://dubbo.apache.org/faq/1/4 to find instructions. 

建议

![image](https://user-images.githubusercontent.com/16596043/201563758-181bfd93-2ec8-4028-935e-61d77dee8736.png)

将判断条件拆分这样就可以避免告警，不然当该服务有大量的消费者服务时，有非常多的告警出现；

**Comment by liufeiyu1002** [comment]
你这和不拆有啥区别么  不都是这俩个条件
![image](https://user-images.githubusercontent.com/32605119/201567414-bdb2e3a4-ec81-4462-8e84-fc1c95018ca7.png)

**Comment by haoxz11** [comment]
> 你这和不拆有啥区别么 不都是这俩个条件 ![image](https://user-images.githubusercontent.com/32605119/201567414-bdb2e3a4-ec81-4462-8e84-fc1c95018ca7.png)

不一样的，localCached只有在invokerUrls有值得时候才会赋值，而之前是为空也会赋值

**Comment by liufeiyu1002** [comment]
![image](https://user-images.githubusercontent.com/32605119/201569368-8e2362b2-e6e1-444c-b539-a74d8fcf81a6.png)
![image](https://user-images.githubusercontent.com/32605119/201569383-719fd544-f388-49f5-b197-dbecd3a4c817.png)
这俩个有区别么？  都为true 才会进去 拆的有什么意义

**Comment by haoxz11** [comment]
> ![image](https://user-images.githubusercontent.com/32605119/201569368-8e2362b2-e6e1-444c-b539-a74d8fcf81a6.png) ![image](https://user-images.githubusercontent.com/32605119/201569383-719fd544-f388-49f5-b197-dbecd3a4c817.png) 这俩个有区别么？ 都为true 才会进去 拆的有什么意义

应为providers,configurators,routers，三个节点，正常情况下只会有一个有值，前面的条件判断，而就算invokerUrls为空也会对localCached赋值，现在只要调整一下条件，只有invokerUrls有值才会赋值，这样启动就不会触发告警；

**Comment by AlbumenJ** [comment]
可以提交个 PR

**Comment by haoxz11** [comment]
> 可以提交个 PR

#10937
