### ISSUE TITLE
Dubbo从2.5.3升级到2.7.18启动报错org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /dubbo/metadata/xxx 

### ISSUE THREAD

**Issue by Qinying233** [apache/dubbo#10944]
### Environment
- dubbo version:2.7.18
- curator version:2.12.0
- zookeeper version：3.4.6
- Java version: 1.8
#### 测试环境可以正常启动，部署到另外一个环境突然就报错了，两套环境是一样的，请问这个是什么地方出了问题？

**Comment by Qinying233** [comment]
下面是异常
`2022-11-16 10:13:49,355|DubboSaveMetadataReport-thread-1|||ERROR|o.a.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport:?| [DUBBO] Failed to put provider metadata org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@18a913f8 in  FullServiceDefinition{parameters={owner=XXX, side=provider, service.name=ServiceBean:/XXXXX, release=2.7.18, methods=invokeTrans, deprecated=false, dubbo=2.0.2, interface=XXXX, timeout=100000, generic=false, revision=0.16.0-SNAPSHOT, retries=0, metadata-type=remote, application=AAA, dynamic=true, anyhost=true}} ServiceDefinition [canonicalName=XXXXX, codeSource=XXXXX.jar, methods=[MethodDefinition [name=invokeTrans, parameterTypes=[], returnType=void]]], cause: KeeperErrorCode = NoNode for /dubbo/metadata/XXXXX, dubbo version: 2.7.18, current host: 10.249.100.243 java.lang.IllegalStateException: KeeperErrorCode = NoNode for /dubbo/metadata/`

**Comment by AlbumenJ** [comment]
升级到 3.1.2 看下还有报错没有，如果还有的话麻烦提供一个 demo

**Comment by Qinying233** [comment]
好的，已经解决了

**Comment by 1994syc** [comment]
> 好的，已经解决了

是什么问题，怎么解决的

**Comment by Qinying233** [comment]
> > 好的，已经解决了
> 
> 是什么问题，怎么解决的

运维说他们那边有一个脚本错误的把zk的node文件删掉了
