### ISSUE TITLE
dubbo 使用 nacos 注册中心多协议注册问题

### ISSUE THREAD

**Issue by bobtthp** [apache/dubbo#10961]
# 在使用 dubbo、triple 协议不同端口在 nacos 上注册， 只有一种协议可以注册成功

dubbo version: 3.0.12
nacos sdk version： 2.x

![image](https://user-images.githubusercontent.com/23113152/202855322-57fbe133-ecd8-4062-9ed1-f745044f1c6f.png)
![image](https://user-images.githubusercontent.com/23113152/202855093-a1a66836-abdc-4d8d-8bd0-40e13a03d150.png)

- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/10942
