### ISSUE TITLE
Dubbo 3.1.x & 3.2.x are not compatible with Spring Boot 3

### ISSUE THREAD

**Issue by gitchenjh** [apache/dubbo#10966]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0-bata.1 & 3.1.2
* Operating System version: Windows10  22H2
* Java version: 17.0.4

### Steps to reproduce this issue

1. Pull https://github.com/gitchenjh/dubbo-spring-boot-test
2. Run ProviderApplication
3. The Application started and then stoped

Pls. provide [GitHub address] to reproduce this issue.

https://github.com/gitchenjh/dubbo-spring-boot-test

### Expected Behavior

The application run started await  
print log 
```
[Dubbo] Current Spring Boot Application is await...
```

### Actual Behavior

The Application started and then stoped

`org.apache.dubbo.spring.boot.autoconfigure.DubboListenerAutoConfiguration`  not work on Spring Boot 3,  Then `org.apache.dubbo.spring.boot.context.event.AwaitingNonWebApplicationListener` bean could not be initialized 

The reason is that Spring Boot 2.7 [Changes to Auto-configuration](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#changes-to-auto-configuration) , Spring Boot 3.0 removed `spring.factories` support

**Comment by CrazyHZM** [comment]
We will support springboot 3.0 and spring 6.0 in dubbo 3.2.
duplicate：https://github.com/apache/dubbo/issues/10565
