### ISSUE TITLE
[3.x] hessian upgrade infactor

### ISSUE THREAD

**Issue by YoungHu** [apache/dubbo#10975]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.12
* Operating System version: Mac OS
* Java version: JDK8

### Steps to reproduce this issue

1. POJO which name `com.xxx.dto.response.RowResponse` without implement java.io.Serializable
2. invoke provider which return this POJO
3. get warning log with  below message and invoke result return HashMap class type.
```
com.alibaba.com.caucho.hessian.io.SerializerFactory.getDeserializer 679: Hessian/Burlap: 'com.xxx.dto.response.RowResponse' is an unknown class in sun.misc.Launcher$AppClassLoader@18b4aac2:
java.lang.IllegalStateException: Serialized class com.xxx.dto.response.RowResponse must implement java.io.Serializable
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

invoke result return type is `com.xxx.dto.response.RowResponse`

### Actual Behavior

return HashMap

### Cause By
this problem cause by hessian version upgrade from 3.2.12 to 3.2.13.
this is the change log link: https://github.com/apache/dubbo-hessian-lite/compare/v3.2.12...v3.2.13
new version hessian add limitation for deserializer method, it require POJO implement java.io.Serializable
it seems not reasonable for this block upgrade, can we remove this limitation?
![image](https://user-images.githubusercontent.com/7418602/203039987-5a13f0b1-6e6f-490b-bcf6-13419f8193fa.png)
![image](https://user-images.githubusercontent.com/7418602/203039918-f549e019-ab36-4668-8e5f-fcf6344c5382.png)

**Comment by AlbumenJ** [comment]
Object pass in Dubbo should implement java.io.Serializable interface. This should be a programming specification, and this can prevent send unexpected object to remote, which may cause a lot of serious leaks.
If you want to send the object, which not implement java.io.Serializable interface, please add `-Ddubbo.hessian.allowNonSerializable=true` to jvm arguments.
