### ISSUE TITLE
Support optional opening of some qos commands to the external network

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#11015]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

Related with https://github.com/apache/dubbo/issues/11014

Background: Dubbo QoS supports docking with kubernetes probes, but foreignIp needs to be enabled. Due to the high-risk instructions in qos, this will lead to a series of security problems.

We should distinguish those commands with low-risk and high-risk, and support all client to request low-risk command for healthy check or metrics collection purpose.

**Comment by Koooooo-7** [comment]
I think we may have something like risk/sensitive level (e.g. `@RiskLevel`) marks on command/command group level.
For now,  dubbo could distinguish the level groups of cmd  by itself and user can config which level(s) cmd the foreign ip could access. and user could custom the level groups (if dubbo expose those command group function) in the future.

**Comment by AlbumenJ** [comment]
@Koooooo-7 would you please help to impl it?
