### ISSUE TITLE
Fix ConcurrentModificationException in application DeployListener

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#11027]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

Related with https://github.com/apache/dubbo/issues/11002

### Steps to reproduce this issue

Use API and to init a service/reference config parallel. 

![image](https://user-images.githubusercontent.com/9292748/203936457-3b01b7b1-d85a-4cf9-814c-c030f7dcf15f.png)

![image](https://user-images.githubusercontent.com/9292748/203936401-9feae085-cdb6-4188-a389-42a0973b3654.png)

![image](https://user-images.githubusercontent.com/9292748/203936536-9738cd9b-ea40-45c8-a97c-1b4c5deccd83.png)

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by IncrementalRefinement** [comment]
I think the main issue of https://github.com/apache/dubbo/issues/11002 is that the concurrent access of the Deployer is happed both within the Spring framework and the user code. In other words, the IOC container hasn't prepared the bean yet but the user code tries to access the bean already. This way of access the bean violates the principal is against the principal of IOC. So I don't think we should consider to fix this issue in Dubbo.

If we really want to fix this problem, maybe we can make the DefaultModuleDeployer implements ApplicationListener interface and add the Anonymous DeployListenerAdapter to the AbstractDeployer#listeners in its constructor?(I personally don't recommend that)

**Comment by AlbumenJ** [comment]
> I think the main issue of https://github.com/apache/dubbo/issues/11002 is that the concurrent access of the Deployer is happed both within the Spring framework and the user code. In other words, the IOC container hasn't prepared the bean yet but the user code tries to access the bean already. This way of access the bean violates the principal of IcC. So I don't think we should consider to fix this issue in Dubbo.

The API usage of Dubbo is not a bean of Spring. The API usage and Spring usage are the two basic usage of Dubbo.

So, the core issue is API usage and Spring usage are conflict when init.

**Comment by IncrementalRefinement** [comment]
> > I think the main issue of #11002 is that the concurrent access of the Deployer is happed both within the Spring framework and the user code. In other words, the IOC container hasn't prepared the bean yet but the user code tries to access the bean already. This way of access the bean violates the principal of IcC. So I don't think we should consider to fix this issue in Dubbo.
> 
> The API usage of Dubbo is not a bean of Spring. The API usage and Spring usage are the two basic usage of Dubbo.
> 
> So, the core issue is API usage and Spring usage are conflict when init.

But the API usage is concurrently accessed the AbstractDeployer(which is eventually complete after DubboDeployApplicationListener add DeployListener) together with the Spring usage. Would't this be a dangerous and not-recommended operation?

**Comment by AlbumenJ** [comment]
> > > I think the main issue of #11002 is that the concurrent access of the Deployer is happed both within the Spring framework and the user code. In other words, the IOC container hasn't prepared the bean yet but the user code tries to access the bean already. This way of access the bean violates the principal of IcC. So I don't think we should consider to fix this issue in Dubbo.
> > 
> > 
> > The API usage of Dubbo is not a bean of Spring. The API usage and Spring usage are the two basic usage of Dubbo.
> > So, the core issue is API usage and Spring usage are conflict when init.
> 
> But the API usage is concurrently accessed the AbstractDeployer(which is eventually complete after DubboDeployApplicationListener add DeployListener) together with the Spring usage. Would't this be a dangerous and not-recommended operation?

We should find out a proper opportunity to make them synchronized.
