### ISSUE TITLE
Remove direct dependency of `protobuf-java`

### ISSUE THREAD

**Issue by guohao** [apache/dubbo#11047]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal
**Goal:** Remove compile logic of `dubbo-rpc/dubbo-rpc-triple/src/main/proto/triple_wrapper.proto` to avoid version-locked of `protobuf-java`

**Changes:** 
1. Rewrite `org.apache.dubbo.rpc.protocol.tri.call.ReflectionAbstractServerCall`, replace generated code with custom encoding.
2. Check gRPC `ReflectionService` and `HealthCheck` API to avoid starting failure without `protobuf-java`
3. Set `protobuf-java` scope to `provided`

**Comment by wlazjr** [comment]
please assign to me
