### ISSUE TITLE
注册中心有服务，但是消费端调用No provider

### ISSUE THREAD

**Issue by tiancaipei** [apache/dubbo#11053]
dubbo版本2.7.17
nacos版本2.1.0
问题描述，消费者服务重启后，调用不到服务提供者，报错No provider，但是可以再注册中心看看到服务信息，重启服务提供者后，可暂时解决，但过一会，又会报同样的错误
![企业微信截图_16697154339130](https://user-images.githubusercontent.com/41528403/204496535-13babc48-6431-4f7d-9622-c7f03dfdfae6.png)
![企业微信截图_16697154095682](https://user-images.githubusercontent.com/41528403/204496548-bf552515-88fe-4b3b-b621-d4dd03fad25a.png)

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo/pull/11038. 2.7.19 is in voting.

**Comment by yl-qm** [comment]
i have this problem either, so i need level to version 2.7.19 or 3.0+ ?

**Comment by tiancaipei** [comment]
2.7.19 There is no official version yet, there may be other issues ? I'm currently using a synchronization service to synchronize the new version of the path format to the old one

**Comment by yl-qm** [comment]
> 2.7.19 There is no official version yet, there may be other issues ? I'm currently using a synchronization service to synchronize the new version of the path format to the old one

好的，我可以等他发布新版

**Comment by AlbumenJ** [comment]
> > 2.7.19 There is no official version yet, there may be other issues ? I'm currently using a synchronization service to synchronize the new version of the path format to the old one
> 
> 好的，我可以等他发布新版

2.7.19 is not officially released

**Comment by tiancaipei** [comment]
> > > 2.7.19 There is no official version yet, there may be other issues ? I'm currently using a synchronization service to synchronize the new version of the path format to the old one
> > 
> > 
> > 好的，我可以等他发布新版
> 
> 2.7.19 is not officially released

这个意思是2.7.19正式版还没有发布？还是2.7.19没有正式的版本？
![image](https://user-images.githubusercontent.com/41528403/207217283-70c4356d-a6ee-4231-8d85-893f30a6adab.png)

**Comment by AlbumenJ** [comment]
> > > > 2.7.19 There is no official version yet, there may be other issues ? I'm currently using a synchronization service to synchronize the new version of the path format to the old one
> > > 
> > > 
> > > 好的，我可以等他发布新版
> > 
> > 
> > 2.7.19 is not officially released
> 
> 这个意思是2.7.19正式版还没有发布？还是2.7.19没有正式的版本？ ![image](https://user-images.githubusercontent.com/41528403/207217283-70c4356d-a6ee-4231-8d85-893f30a6adab.png)

typo issue :)

**Comment by tiancaipei** [comment]
@AlbumenJ 我升级到了2.7.19，同步的旧路径都调用不到了
![企业微信截图_16709797949471](https://user-images.githubusercontent.com/41528403/207479527-d186bd22-4032-4584-a921-2e676a80896e.png)
![企业微信截图_16709798342183](https://user-images.githubusercontent.com/41528403/207479561-1a17d262-8b76-4151-b726-512f0935abeb.png)

**Comment by AlbumenJ** [comment]
另外默认应该是不会注册老的节点的，你们是做了独立的解析嘛

**Comment by tiancaipei** [comment]
> > @AlbumenJ 我升级到了2.7.19，同步的旧路径都调用不到了，服务消费者升级到了2.7.19，提供者还是2.7.17 ![企业微信截图_16709797949471](https://user-images.githubusercontent.com/41528403/207479527-d186bd22-4032-4584-a921-2e676a80896e.png) ![企业微信截图_16709798342183](https://user-images.githubusercontent.com/41528403/207479561-1a17d262-8b76-4151-b726-512f0935abeb.png)
> 
> 这个是怎么复现的，我这边测试是没问题的

就是和之前一样的操作顺序，消费端升级到2.7.19，然后服务端还是2.7.17，然后重新发布消费端和服务端，就还是会有这样的问题。

**Comment by tiancaipei** [comment]
> 另外默认应该是不会注册老的节点的，你们是做了独立的解析嘛

之前调用不到的时候，我调查发现是因为去调用了旧的路径，所以我开了个同步服务，把新的路径同步了一份换成了旧的路径的格式到注册中心上面

**Comment by tiancaipei** [comment]
> > > @AlbumenJ 我升级到了2.7.19，同步的旧路径都调用不到了，服务消费者升级到了2.7.19，提供者还是2.7.17 ![企业微信截图_16709797949471](https://user-images.githubusercontent.com/41528403/207479527-d186bd22-4032-4584-a921-2e676a80896e.png) ![企业微信截图_16709798342183](https://user-images.githubusercontent.com/41528403/207479561-1a17d262-8b76-4151-b726-512f0935abeb.png)
> > 
> > 
> > 这个是怎么复现的，我这边测试是没问题的
> 
> 就是和之前一样的操作顺序，消费端升级到2.7.19，然后服务端还是2.7.17，然后重新发布消费端和服务端，过一段时间，就还是会有这样的问题。

我刚做了一下完整的测试，配置如下：服务提供者（2个）版本2.7.17，服务消费者（1个）版本2.7.19；在保证服务能调用到之后，重启所有的服务提供者，就出现了调用不到的问题，我测了几次都是必现这个问题的，就连我同步的旧的路径也是没法调用到了

**Comment by chuawei** [comment]
服务提供者（2个）版本一个27.16、一个2.7.18，服务消费者（1个）版本2.7.19，存在问题。

**Comment by wxbty** [comment]
2.7.x is no longer maintained, please upgrade to the latest version. If you still have problems, please reopen the issue
