### ISSUE TITLE
Is it unnecessary for the service provider to use the built-in tomcat in spring boot？

### ISSUE THREAD

**Issue by lamb007** [apache/dubbo#11085]
When dubbo is used in spring boot, the service provider does not need to use the web function, that is, it does not need the built-in tomcat of spring boot. However, when the spring boot project starts, the built-in Tomcat will be used. How do you start the service provider without using the built-in Tomcat of spring boot, just like using pure spring.

**Comment by AlbumenJ** [comment]
Dubbo does not use tomcat as server by default. Dubbo is a server based on netty.

**Comment by lamb007** [comment]
> Dubbo does not use tomcat as server by default. Dubbo is a server based on netty.

But why do I have port conflicts when I start multiple providers at the same time? The spring boot log will also be printed using tomcat
run the first provider
`2022-12-06 18:57:19.437  INFO 22688 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)`
run the second provider
`Web server failed to start. Port 8080 was already in use.`

Only when I specify different server.port in application.xml can I succeed

**Comment by AlbumenJ** [comment]
> > Dubbo does not use tomcat as server by default. Dubbo is a server based on netty.
> 
> But why do I have port conflicts when I start multiple providers at the same time? The spring boot log will also be printed using tomcat run the first provider `2022-12-06 18:57:19.437 INFO 22688 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 8080 (http)` run the second provider `Web server failed to start. Port 8080 was already in use.`
> 
> Only when I specify different server.port in application.xml can I succeed

`o.s.b.w.embedded.tomcat` is not dubbo`s package. Please check if you have import spring-boot-web-starter. If you import it, spring will launch the web server by default. (Please check spring boot`s configuration.)

**Comment by lamb007** [comment]
> > > Dubbo does not use tomcat as server by default. Dubbo is a server based on netty.
> > 
> > 
> > But why do I have port conflicts when I start multiple providers at the same time? The spring boot log will also be printed using tomcat run the first provider `2022-12-06 18:57:19.437 INFO 22688 --- [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat initialized with port(s): 8080 (http)` run the second provider `Web server failed to start. Port 8080 was already in use.`
> > Only when I specify different server.port in application.xml can I succeed
> 
> `o.s.b.w.embedded.tomcat` is not dubbo's package. Please check if you have import spring-boot-web-starter. If you import it, spring will launch the web server by default. (Please check spring boot`s configuration.)

My question may be very childish. Thank you for your patient reply. I am new to this knowledge.
this the pom.xml
`  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-dependencies-zookeeper</artifactId>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
    </dependency>
  </dependencies>`

Do you mean to remove the spring boot web starter, but how do I start the spring boot application in my ProviderApplication after removing it.
`@SpringBootApplication
@EnableDubbo
public class ProviderApplication {
    public static void main(String[] args) {
        SpringApplication.run(ProviderApplication.class);
    }
}`

**Comment by AlbumenJ** [comment]
Please see https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-spring-boot

**Comment by AlbumenJ** [comment]
```xml
    <dependencies>
        <!-- dubbo starter -->
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
        </dependency>

        <!-- spring starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>

    </dependencies>
```

**Comment by lamb007** [comment]
> Please see https://github.com/apache/dubbo-samples/tree/master/1-basic/dubbo-samples-spring-boot

My problem has been solved. Thank you for your patience.
