### ISSUE TITLE
when throw ExceedPayloadLimitException and consumer timeout,  payload may exists memory Leak 

### ISSUE THREAD

**Issue by xieshouyu** [apache/dubbo#11089]
### Environment

* Dubbo version: 2.7.18
* Operating System version: mac
* Java version: jdk1.8

### Steps to reproduce this issue

1. 建立服务 app-provider，app-consumer 。provider端构造response数据超过payload 默认大小8M。
2. 启动provider 和 consumer服务，provider端，在ExchangeCodec对象的279行（protected encodeResponse方法第一行），打断点，断点的condition：res.getResult() != null
3. consumer 端发起请求，provider断点等超时。当consumer端，报 Waiting server-side response timeout by scan timer后，放开provider端的断点。
4. dump 内存信息，可以看到内存对象会看到多一个大对象char[]，就是你放到response内放的对象。
5. char[]的reference为GC root JNI global。
6. GC root JNI global 持有了 org.apache.dubbo.remoting.transport.ExceedPayloadLimitException、org.apache.dubbo.remoting.exchange.Response（包含了你返回的response对象）、org.apache.dubbo.remoting.transport.netty4.NettyChannel 三个对象。

Pls. provide [GitHub address] to reproduce this issue.

demo地址：https://github.com/xieshouyu/app-provider.git ，https://github.com/xieshouyu/app-consumer.git
请求 http://127.0.0.1:8082/send

### Expected Behavior

请求完成后，response被回收c

### Actual Behavior

请求完成后，response对象未被回收

**Comment by FoghostCn** [comment]
gc一次应该就没了吧

**Comment by xieshouyu** [comment]
> gc一次应该就没了吧
那必须还在，这么容易就被gc了，也不写demo去验证，你可以下demo试一下。

**Comment by FoghostCn** [comment]
复现不了，你可以吧GC root引用关系的图贴一下吗

**Comment by xieshouyu** [comment]
> 3\. der断点

有按照我的要求的位置断点等超时吗？如果你在刚进入的位置断点，那就不会有问题，必须要找我步骤，包括断点的位置。

**Comment by xieshouyu** [comment]
![image](https://user-images.githubusercontent.com/29672850/206945718-6ed3c7b1-930a-42ca-8506-cf19da50c39e.png)
![image](https://user-images.githubusercontent.com/29672850/206945872-8fe1b4c8-f8ce-4111-ad12-2f79849765c0.png)

**Comment by xieshouyu** [comment]
之前有点问题，重装了mac m1的jdk和工具，现在无法复现，先关闭。
