### ISSUE TITLE
dubbo 3.x not support zipkin with spring cloud starter sleuth

### ISSUE THREAD

**Issue by yuchang01** [apache/dubbo#11081]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: dubbo 3.1.3
* Operating System version: Spring Cloud 2021.x
* Java version: jdk 11

### Steps to reproduce this issue

docs here: https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-rpc-dubbo-integration

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

traceId can transfer between serviceA to serviceB to serviceC ……

### Actual Behavior

traceId not transfer between services!

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by yuchang01** [comment]
@AlbumenJ

**Comment by makoto4423** [comment]
So, does the problem have solved? And i run the demo in the [offical project](https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-spring-boot3-tracing), it does not worked, too.

**Comment by AlbumenJ** [comment]
> https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/integrations.html#sleuth-rpc-dubbo-integration

What's the problem?

**Comment by yuchang01** [comment]
see https://github.com/apache/dubbo/issues/11650
