### ISSUE TITLE
java.lang.IndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by lphu** [apache/dubbo#11083]
dubbo版本: 3.0.12

现象: 多注册中心的情况下, 走到ZoneAwareClusterInvoker时未挑选出符合策略的注册中心，默认选取第一个。 如果没有注册中心可用, 看到已经在之前被修复了[#11046 ](https://github.com/apache/dubbo/pull/11046)。 但是此时注册中心是正常的且只有一个Reference会出现此问题，其他机器以及其他Reference均正常， 重启或者切换订阅级别至 FORCE_INTERFACE 即可恢复正常

初步排查结果:  该Reference下游从dubbo3.x 回退版本至dubbo2.x

<img width="780" alt="image" src="https://user-images.githubusercontent.com/33591744/205871769-3dd6de9b-fe62-4fe0-b020-85e07210c9fd.png">

此时两个注册中心均在invokersToReconnect内
且 MigrationInvoker内 CurrentAvailableInvoker(即ServiceDiscoveryRegistryDirectory为 UnAvailable状态)， Invoker为Avaliable状态.

请问该问题是否和 #10925 此commit有关系?

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/pull/10925 这个只是 3.2 中一个新功能的修复，和这个问题没关系。
这个问题应该和 https://github.com/apache/dubbo/pull/11046 有关，会在 3.1.4 版本中发布。

**Comment by lphu** [comment]
> #10925 这个只是 3.2 中一个新功能的修复，和这个问题没关系。 这个问题应该和 #11046 有关，会在 3.1.4 版本中发布。

#11046 只是修复了不抛出数组越界的异常，改为抛出无服务提供者.

问题是什么原因会造成该现象, 小概率事件,本地暂时也无法复现。 推测是应用级服务变更时的问题， 只有一个Reference是不正常的, 注册中心(zk)上的值也是正常的，重启之后就正常了

**Comment by AlbumenJ** [comment]
> > #10925 这个只是 3.2 中一个新功能的修复，和这个问题没关系。 这个问题应该和 #11046 有关，会在 3.1.4 版本中发布。
> 
> #11046 只是修复了不抛出数组越界的异常，改为抛出无服务提供者.
> 
> 问题是什么原因会造成该现象, 小概率事件,本地暂时也无法复现。 推测是应用级服务变更时的问题， 只有一个Reference是不正常的, 注册中心(zk)上的值也是正常的，重启之后就正常了

注册中心中没有地址，available 检查为失败，被从服务目录中剔除

**Comment by lphu** [comment]
可以通过此方式复现该问题.  dubbo版本 3.0.12。上游使用双注册中心,  下游正常单注册,  订阅注册策略均为默认.

1. 上下游正常启动,  此时服务正常调用
2. 关闭下游, 此时在这期间调用某一下游服务, 实际上是No provider, 但是会出现 ZoneAwareClusterInvoker数组越界问题,  同时再进行select 和 reselect时, 会把 StaticDirectroy内的 invoker 移到 toBeReconnet内, 启动一个定时任务check.
3. 此时下游回滚版本至 2.7.x版本并且换一个ip启动,  启动完成后再请求 2) 同一服务,  此时仍旧报数组越界. 选择 2) 中未请求过的另一服务, 该服务能够正常通过.

Dubbo 内认为注册中心不可用是在请求过程中判断的，如果 avaliable检查失败则移动到toBeReconnect列表内， 而接受到新的地址通知时，只修改了RegistryDirectroy内的列表, 并没有把StaticDirectroy内的列表变动

**Comment by lphu** [comment]
> > 而接受到新的地址通知时，只修改了RegistryDirectroy内的列表, 并没有把StaticDirectroy内的列表变动
> 
> 这个应该是没问题的，StaticDirectroy 会及时恢复的。

你可以根据步骤测试一下, 说的StaticDirectroy未恢复可能有点问题。
实际是MigrationInvoker 判断CurrentInvoker有误， org.apache.dubbo.registry.client.migration.DefaultMigrationAddressComparator#shouldMigrate 这里即使回滚成Dubbo2.x依旧会选择到serviceDiscoveryInvoker， 导致StaticDirectroy中的定时任务去校验avaliable时，是使用的CurrentInvoker, 导致StaticDirectroy内未恢复.

**Comment by lphu** [comment]
@AlbumenJ 麻烦帮忙确认一下

**Comment by AlbumenJ** [comment]
> @AlbumenJ 麻烦帮忙确认一下


这个我测试了 3.1.4 版本是没问题的，在几秒后会自动恢复
