### ISSUE TITLE
How to customize metadata in nacos

### ISSUE THREAD

**Issue by DspringL** [apache/dubbo#11105]
![image](https://user-images.githubusercontent.com/29829184/206653559-8721eb88-2ea1-44b7-990c-11b7216a6210.png)

how to add custom metadata

**Comment by AlbumenJ** [comment]
Impl `org.apache.dubbo.registry.client.ServiceInstanceCustomizer` SPI

See `org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataCustomizer`. Add your customized metadata into `serviceInstance.getMetadata()`

**Comment by DspringL** [comment]
Thank you very mush!
