### ISSUE TITLE
有Dubbo3 mesh的调试文档吗，官网只有简单的部署文档，具体bebug调试的文档没有，自己尝试没有成功

### ISSUE THREAD

**Issue by spurstong** [apache/dubbo#11111]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by aamingaa** [comment]
https://cn.dubbo.apache.org/zh/docs3-v2/java-sdk/reference-manual/mesh/mesh/

**Comment by goto456** [comment]
@spurstong  后来你按照上面的文档成功了吗？
