### ISSUE TITLE
dubbo3.0.8 泛化调用时无法进行protobuf-json类型的反序列化

### ISSUE THREAD

**Issue by AdamsShen** [apache/dubbo#11129]
dubbo3.0.8 怎么去除了protobuf-json的Serialization解析器，目前只有
![image](https://user-images.githubusercontent.com/42172222/207499049-695378f6-801a-49b4-aead-b0e44cec09f0.png)

而dubbo2.7.8中有这个解析器
![image](https://user-images.githubusercontent.com/42172222/207499185-10f2c460-575a-4544-ae99-4593d376ad03.png)
现在我使用dubbo3.0.8 triple协议的IDL方式生成的接口，进行泛化调用的时候
服务端无法进行反序列化，直接报错no such extension org.apache.dubbo.common.serialize.serialization by name protobuf-json

**Comment by AlbumenJ** [comment]
1. org.apache.dubbo.common.serialize.Serialization 这个接口是给普通调用用的，不是给泛化调用用的
2. triple 协议不需要指定 serialization，默认底层就会去识别使用 protobuf

**Comment by AdamsShen** [comment]
> 1. org.apache.dubbo.common.serialize.Serialization 这个接口是给普通调用用的，不是给泛化调用用的
> 2. triple 协议不需要指定 serialization，默认底层就会去识别使用 protobuf

现在不是triple协议问题，是序列化方式，dubbo3.0.8不存在protobuf-json对应的Serialization处理类
目前我这边泛化调用设置是这样的
![image](https://user-images.githubusercontent.com/42172222/207530562-01837e5a-2c73-479f-bab1-47129198467f.png)

然后走到解码的GenericFilter中会直接报错no such extension org.apache.dubbo.common.serialize.serialization by name protobuf-json

**Comment by AlbumenJ** [comment]
protobuf serialization 在 3.x 里面移到这里了 https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions/dubbo-serialization-protobuf

加下依赖就可以
```xml
<dependency>
    <groupId>org.apache.dubbo.extensions</groupId>
    <artifactId>dubbo-serialization-protobuf</artifactId>
    <version>1.0.1</version>
</dependency>
```

**Comment by AdamsShen** [comment]
已经可以了，感谢~ 感谢~

**Comment by heyxhh** [comment]
> 已经可以了，感谢~ 感谢~

hello 请问使用triple+protobuf时，泛化调用是怎么做的，我泛化调用时一直报：Cannot invoke "java.lang.reflect.Method.getParameterTypes()" because "method" is null

**Comment by wxbty** [comment]
> > 已经可以了，感谢~ 感谢~
> 
> hello 请问使用triple+protobuf时，泛化调用是怎么做的，我泛化调用时一直报：Cannot invoke "java.lang.reflect.Method.getParameterTypes()" because "method" is null

Please open another issue to introduce this issue
