### ISSUE TITLE
运行mvn clean install报错了

### ISSUE THREAD

**Issue by linxun1209** [apache/dubbo#11124]
![QQ截图20221212221312](https://user-images.githubusercontent.com/103026428/207067396-42959257-7b8d-47ba-b178-f232aedd5e1d.png)

**Comment by AlbumenJ** [comment]
`org.apache.dubbo:tri-stub-demo` 这个是在 samples 里面拉的吗

**Comment by ningboliu** [comment]
之前也出现这个问题，我把所有protobuf的版本改为本地安装的一样，就成功了，你可以试试

**Comment by linxun1209** [comment]
非常感谢,谢谢你&nbsp;


666666
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月14日(星期三) 晚上7:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dubbo] 运行mvn clean install报错了 (Issue #11124)





 
之前也出现这个问题，我把所有protobuf的版本改为本地安装的一样，就成功了，你可以试试
