### ISSUE TITLE
maven 测试 多线程问题

### ISSUE THREAD

**Issue by ShenFeng312** [apache/dubbo#11134]
目前框架的单测多线程运行会报错，单个运行又太慢了。

**Comment by ShenFeng312** [comment]
![image](https://user-images.githubusercontent.com/49786112/207626625-34c8dd0d-2abf-47cb-9424-514685be2879.png)
单线程跑完需要12分钟

**Comment by ShenFeng312** [comment]
> 可以尝试下 mvnd

问题点是现在的单侧有些用到的端口是写死的或者是有些强依赖zookeeper 多线程运行下来很多用例不一定能过

**Comment by ShenFeng312** [comment]
![image](https://user-images.githubusercontent.com/49786112/207757929-a47d8e25-d40c-42b8-89c2-a1c28877c92c.png)

**Comment by ShenFeng312** [comment]
> 可以尝试下 mvnd

我认为解决的根本要从单测入手

**Comment by EarthChen** [comment]
> > 可以尝试下 mvnd
> 
> 问题点是现在的单测有些用到的端口是写死的或者是有些强依赖zookeeper 多线程运行下来很多用例不一定能过

因为 ut 并没有从整体的视角去看待整个项目，而且也不是一个人去编写所有的 ut，再加上多线程下去实现会带来不少的复杂度
