### ISSUE TITLE
Observability task:provider responds to data buried point improvement investigation and improvement(可观测性任务提供者响应数据埋点完善调研与完善)

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11145]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

En: At present, there are already some buried point data for the provider, and now it is necessary to sort out these existing buried point data into documents, and at the same time investigate what indicators the provider has not sorted out, such as the QPS RT request times provider request time-consuming histogram Figures, etc. After the research, a plan can be provided and then developed according to the plan.

中文：目前针对提供者已经存在了一些埋点数据，现在需要将这些已经存在的埋点数据梳理为文档，同时调研下提供者还有哪些未梳理的指标，比如QPS RT 请求次数  提供者请求耗时直方图等等 ，调研后可以提供方案然后针对方案进行开发。

**Comment by fomeiherz** [comment]
assign to me, thanks

**Comment by songxiaosheng** [comment]
> assign to me, thanks

ok

**Comment by songxiaosheng** [comment]
> assign to me, thanks

以留下钉钉号吗，方便我们联系

**Comment by fomeiherz** [comment]
> 

钉钉号：fomeiherz
