### ISSUE TITLE
Observability task: registration center related index data improvement investigation and improvement（可观测性任务注册中心相关指标数据完善调研与完善)

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11146]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

En:This is mainly to deal with the interaction between Dubbo and the registration center. For users, they can understand the interaction time between the current system and the registration center, registration mode, connection status and other indicators, so that developers can keep track of the health status of the application and the registration center to assist in troubleshooting. and optimize performance.

中文：这里主要是处理Dubbo内部与注册中心的交互，对于用户来说了解当前系统内部与注册中心的交互时间，注册模式，连接状况等指标，方便开发者随时掌握应用与注册中心的健康状况协助排查问题与优化性能。

**Comment by wxbty** [comment]
pls assign to me

**Comment by wxbty** [comment]
Referring to Google's 4 golden indicators, for the registration center, I think the following indicators are needed.

- dubbo_registry_duration_seconds
  Interaction delay, interaction behavior includes service register, subscription, heartbeat, indicating the network connection status of the application and registry center

- dubbo_registry_notify_total

  The change notification push received by the consumer side indicating the frequency of the service provider online or offline

- dubbo_registry_connect_total

  The number of times to reconnect with the registry center, indicating the available time of the registry center

  
In addition, a large change in the number of application instances will lead to an increase in received push traffic, which may cause a huge change in 【memory usage】 and have a greater impact on the 【gc】 of the current application.
  These two indicators belong to the system indicators and are not included for the time being.

中文：参考google四大黄金指标，我认为注册中心应该需要的指标如下：
- dubbo_registry_duration_seconds
  交互延迟，交互行为包含注册、订阅、心跳，反映应用和注册中心的网络连接状况
- dubbo_registry_notify_total
  consumer端接收到的变更通知推送，反映服务提供者上下线的频率
- dubbo_registry_connect_total
  与注册中心重连的次数，反映注册中心的可用时间

另外，应用实例数的大量变化会导致接收的推送流量增大，可能会造成内存使用的巨大变化，并且对当前应用的gc造成较大影响。
这两个指标属于系统指标，暂时不列入。

Anyone have suggestions?

**Comment by songxiaosheng** [comment]
可以的，正常的服务订阅，服务注册，接收通知，查询服务几个场景
指标类型可以处理下次数，耗时，错误次数
另外可以还有服务迁移过程显示的服务注册类型看看是否可以显示出来当前接口的服务注册类型比如当前是应用级别注册还是接口级别，订阅者当前是接口级别还是应用级别比较有利于观察dubbo升级迁移过程
