### ISSUE TITLE
Observability task metadata center related index data investigation and improvement（可观测性任务元数据中心相关指标数据调研与完善）

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11148]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

En: The metadata center is a data center registered at the dubbo3 application level, which is used to store interface data. The application-level registration center is used to store application granular data, and the metadata center is used to store interface configuration finer-grained data. The acquisition of metadata is mainly It is obtained by the consumer selecting a provider according to the load balancing algorithm and then initiating an internal RPC request to the provider. Metadata is also relatively easy to change. Some interactions between dubbo and the metadata center are displayed through index burying points, so that developers can better understand the internal situation of their own systems.

中文：元数据中心是dubbo3应用级注册的一个数据中心，用来存储接口数据，应用级注册注册中心用来存储应用粒度数据，元数据中心则来存储接口配置更细粒度的数据，元数据的获取主要是消费者根据负载均衡算法选择一个提供者然后向提供者发起一个内部的RPC请求来获取的。元数据也是比较容易发生变更的，通过指标埋点来将dubbo与元数据中心的一些交互展示出来方便开发者更了解自己的系统内部情况。

**Comment by LXPWing** [comment]
Has anyone claimed this one yet? If not, I would like to try

**Comment by LXPWing** [comment]
<div class="lake-content" typography="classic">
名称 | 描述
-- | --
元数据中心连接最大耗时 |  
元数据中心连接最小耗时 |  
元数据中心连接总耗时 |  
元数据中心连接平均耗时 |  
元数据中心连接耗时P95 |  
元数据中心连接耗时P99 |  
元数据中心连接成功次数 |  
元数据中心连接失败次数 |  
元数据中心连接总次数 |  
元数据中心数据命中成功次数 |  
元数据中心数据命中失败次数 |  
元数据中心数据命中率 |  
</div>
@songxiaosheng 宋老师 麻烦您帮忙看下“元数据中心相关指标数据”哪里需要修改

**Comment by songxiaosheng** [comment]
> | 名称 | 描述 |
> | --- |----|
> |元数据中心连接最大耗时 |    |
> |元数据中心连接最小耗时 |    |
> |元数据中心连接总耗时 |    |
> |元数据中心连接平均耗时 |    |
> |元数据中心连接耗时P95 |    |
> |元数据中心连接耗时P99 |    |
> |元数据中心连接成功次数 |    |
> |元数据中心连接失败次数 |    |
> |元数据中心连接总次数 |    |
> |元数据中心数据命中成功次数 |    |
> |元数据中心数据命中失败次数 |    |
> |元数据中心数据命中率 |    |
> 
> @songxiaosheng 宋老师 麻烦您帮忙看下“元数据中心相关指标数据”哪里需要修改

可以的 初步可以做这些 先处理一个版本，后续再细化比如根据失败的异常错误类型分类，元数据本地缓存文件大小等
