### ISSUE TITLE
Observability Task:consumer request buried point data document sorting and research improvement(可观测性任务消费者请求埋点数据文档整理与调研完善)

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11143]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

En:At present, what is lacking in request tracking is the documentation of indicators and the refinement of indicators. Here, we need to consider the tracking items needed by consumers from the perspective of consumers, such as requested QPS, RT, request count, and histogram display. execution time, etc. The main goal of consumer index tracking is to help Dubbo users optimize consumer performance, troubleshoot and other needs.

中文：目前对于请求的埋点比较欠缺的是指标的文档和指标的细化，这里需要站在消费者的维度来考虑消费者需要的埋点项，比如请求的QPS，RT，请求计数，直方图展示的执行时间等。消费者的指标埋点主要的目标是帮助Dubbo用户优化消费者性能、问题排查等需求。

**Comment by lcb11** [comment]
assign to me, thanks

**Comment by lcb11** [comment]
assign to me, thanks

**Comment by songxiaosheng** [comment]
> assign to me, thanks

ok

**Comment by songxiaosheng** [comment]
> assign to me, thanks

以留下钉钉号吗，方便我们联系

**Comment by lcb11** [comment]
> > assign to me, thanks
> 
> 以留下钉钉号吗，方便我们联系

buring123
