### ISSUE TITLE
dubbo 元数据序列化gson与fastjson不一致的问题

### ISSUE THREAD

**Issue by 315661538** [apache/dubbo#11166]
### Environment

* Dubbo version: 3.0.9
* Operating System version: Linux
* Java version: jdk1.8

### Steps to reproduce this issue

1. 应用启动参数设置 -Ddubbo.json-framework.prefer=gson，同时设置 report-metadata 配置为true
![image](https://user-images.githubusercontent.com/48381743/208357620-be6595c7-6619-4663-831f-911bbbd19daa.png)
2. 此时元数据中心中的元数据格式如下：
![image](https://user-images.githubusercontent.com/48381743/208357695-0d97fb8e-1fb2-4d39-a887-923d67a55c97.png)
3. 应用启动参数设置 -Ddubbo.json-framework.prefer=fastjson，同时设置 report-metadata 配置为true
4. 此时元数据中心中的元数据格式如下：
![image](https://user-images.githubusercontent.com/48381743/208357820-138c231d-70ad-4267-89fd-6ac31039f6dd.png)

### Expected Behavior
使用gson和使用fastjson元数据数据格式应当一致

### Actual Behavior
目前使用fastjson序列化方式，同时设置metadata-type为remote方式时，会导致服务标签丢失，出现找不到服务的情况。

**Comment by AlbumenJ** [comment]
Fixed in #10447

**Comment by AlbumenJ** [comment]
Please try 3.0.12 or 3.1.3.
