### ISSUE TITLE
Proto IDL管控平台设计

### ISSUE THREAD

**Issue by shihuili1218** [apache/dubbo#11167]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature
在Dubbo Admin中提供Proto管控平台。管控dubbo服务的proto，提供自动编译、版本管理功能。

这里有关于IDL平台内容，其中包括了需要实现的功能以及架构图。
https://cloud.fynote.com/share/d/ITHjTPAeF

**Comment by complone** [comment]
This looks very interesting. It's a bit like kafka-schema-registry. Mind to discuss something together
