### ISSUE TITLE
Observability tasks: provider and consumer tracing data buried points(可观测性任务：提供者与消费者tracing 数据埋点)

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11171]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

En:In link tracking, traceid is used to represent the global link id, and spanid is used to represent the id of the local area. There are producers and consumers in dubbo across system calls, and the consumer may be the initial link without traceid spanid and other data that needs to be reset. Generated, consumers need to pass their own traceid to the downstream when they call the provider, and Spanid can be regenerated inside their own application. Of course, in order to track the context relationship, there will also be some self-defined ids such as parent id and custom parameters. Transit should also be taken into account.

中文：在链路追踪中使用traceid来代表全局的链路id，使用spanid代表局部区域的id，dubbo中跨系统调用存在生产者和消费者，消费者可能是起始链路没有traceid spanid等数据需要重新生成，消费者调用提供者的时候需要将自身的traceid传递到下游, 而Spanid可以再自己的应用内部重新生成，当然为了追踪上下文关系也会存在一些自定的id比如父id，自定义参数的传递也应该考虑在内。

**Comment by seriouszyx** [comment]
plz assign to me, thanks

**Comment by songxiaosheng** [comment]
> plz assign to me, thanks

ok

**Comment by seriouszyx** [comment]
> > plz assign to me, thanks
> 
> Could you tell me your dingding ID to convenient contact?

private message has been sent

**Comment by seriouszyx** [comment]
This issue should have been solved by https://github.com/apache/dubbo/pull/11021, I will choose other tasks to contribute.
