### ISSUE TITLE
dubb2.6.12消费不到dubbo2.7.18的提供的服务

### ISSUE THREAD

**Issue by robin977** [apache/dubbo#11174]
问题:
dubb2.6.12消费不到dubbo2.7.18的提供的服务
Failed to check the status of the service com.aaa.bbb.boot.api.service.IUserQueryService. No provider available for the service

1，新项目采用dubbo2.7.18,作为提供者,注册中心采用nacos2.0.3
采用xml配置
    <dubbo:registry id="nacosregistry" protocol="${dubbo.registry.protocol:nacos}" address="${dubbo.registry.address}"   >
        <dubbo:parameter key="namespace" value="${dubbo.registry.namespace}" />
    </dubbo:registry>

    <dubbo:protocol name="dubbo" port="${dubbo.provider.port:20880}"   />

    <dubbo:provider timeout="10000" threadpool="fixed" threads="100" accepts="1000"  registry="nacosregistry" />

    <dubbo:service interface="com.aaa.xx.boot.api.service.IUserQueryService"
                    ref="boot.userQueryService" retries="0" version="2.0.0" registry="nacosregistry"  />

注册时，服务名如下
![wecom-temp-af6f471c9355fe905a96199d60e847fd](https://user-images.githubusercontent.com/8486672/208600374-5b62197b-95f4-4e98-bf6a-62883148ed83.png)

注册中心内容如下:
![wecom-temp-e39d0b268564f1134c08d57503f594c6](https://user-images.githubusercontent.com/8486672/208600342-ea407f42-5954-4438-91a0-39fb0068b30e.png)

2，消费端采用dubbo2.6.12,注册中心为nacos2.0.3
服务订阅时如下：服务名称没有":"
![wecom-temp-c48c092b93a1ace7711c6c3ec4317701](https://user-images.githubusercontent.com/8486672/208600235-9937d4f7-ad3b-4a1f-a99a-fc2f1754bf81.png)
，获取不到实例，如果加上":"
![image](https://user-images.githubusercontent.com/8486672/208600486-f1b8b0fb-7941-4b6f-af9a-598183768a61.png)
是可以获取实例的
建议在做服务暴露时，如果没有对应的参数，不要添加":"
![image](https://user-images.githubusercontent.com/8486672/208600666-6513a105-f1f3-406b-a719-2c5adc367b7a.png)

**Comment by AlbumenJ** [comment]
由于 2.7.4 以前的 Nacos 注册存在设计缺陷，在 2.7.4 之前的版本在 version 或者 group 为 null 的时候，会忽略中间的 `:` 注册。导致可能出现多个服务在 nacos 上面的服务名一样的情况。在 2.7.4 以后强制所有 `:` 都会注册，监听的时候两个版本的都会监听以保持兼容。

因此，2.7.4 及以后的客户端支持所有版本的 provider，2.7.4 及以后的服务端仅支持 2.7.4 以后的服务端。

**注：如果 version 和 group 都不为 null 时，所有版本互通都无问题。**

**Comment by robin977** [comment]
那基于dubbo2.6.12的服务，都是没有group的，大部分只有version属性，但是安全部门要求，必须要升级到dubbo2.7.18，处理掉漏洞
