### ISSUE TITLE
This serialization only support google protobuf object, the object class is: java.lang.String

### ISSUE THREAD

**Issue by zhangqingyango** [apache/dubbo#11189]
### Environment

* Dubbo version: 3.1.3
* Java version: 8

![image](https://user-images.githubusercontent.com/37824124/209034256-7e0983a1-8148-43c6-bf28-429165cf1aea.png)

泛化调用异常，PB 文件泛化调用

**Comment by zhangqingyango** [comment]
![image](https://user-images.githubusercontent.com/37824124/209034391-4e36f188-08c5-4155-a87d-327e24fc59cb.png)

**Comment by zhangqingyango** [comment]
@AlbumenJ 求教

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/blob/master/3-extensions/serialization/dubbo-samples-protobuf-json/protobuf-json-serialization-demo/src/main/java/org/apache/dubbo/sample/protobuf/genericCall/GenericClient.java
基于这个用例修改了下，我这边是可以正常使用的

Dubbo 3.1.4， Triple 协议

**Comment by zhangqingyango** [comment]
https://github.com/apache/dubbo-samples/blob/master/3-extensions/serialization/dubbo-samples-protobuf-json/protobuf-json-serialization-demo/src/main/java/org/apache/dubbo/sample/protobuf/genericCall/GenericClient.java

**Comment by zhangqingyango** [comment]
我把代码拉了下来，改了下注册中心，还是跑不通
![image](https://user-images.githubusercontent.com/37824124/210713239-893aef39-2771-40ce-b7c5-5e38db99623a.png)
这个是nacos 提供者信息
![image](https://user-images.githubusercontent.com/37824124/210713290-5ff18b46-d973-4bb5-a301-acd8993b544d.png)

**Comment by AlbumenJ** [comment]
> 我把代码拉了下来，改了下注册中心，还是跑不通 ![image](https://user-images.githubusercontent.com/37824124/210713239-893aef39-2771-40ce-b7c5-5e38db99623a.png) 这个是nacos 提供者信息 ![image](https://user-images.githubusercontent.com/37824124/210713290-5ff18b46-d973-4bb5-a301-acd8993b544d.png)

你修改的内容可以提个 patch 吗，我复现下

**Comment by zhangqingyango** [comment]
附件的
protobuf-json-provider-generic-demo 新建了一个demo ，注册到nacos。引用了，3-extensions 中protobuf-json-serialization-api模块


3-extensions 中修改了以下内容
1、dubbo.version 3.1.4




2. 加了一个nacos、一个protobuf 序列化依赖


3、修改了GenericClient&nbsp; 改了注册中心







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月5日(星期四) 晚上8:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] This serialization only support google protobuf object, the object class is: java.lang.String (Issue #11189)





  
我把代码拉了下来，改了下注册中心，还是跑不通  这个是nacos 提供者信息 
  
你修改的内容可以提个 patch 吗，我复现下

**Comment by zhangqingyango** [comment]
我在邮件中修改的内容，回复了你，请注意查收

**Comment by AlbumenJ** [comment]
> 我在邮件中修改的内容，回复了你，请注意查收

可以在 github 上面直接上传吗，没看到附件

**Comment by zhangqingyango** [comment]
https://github.com/zhangqingyango/dubbo-protobuf-json-demo.git

**Comment by zhangqingyango** [comment]
上传了，看下这个地址能不能看到

**Comment by aamingaa** [comment]
我来看看

**Comment by zhangqingyango** [comment]
请问这个问题是已经处理好了吗@aamingaa

**Comment by aamingaa** [comment]
> 

这个问题社区已经讨论过了，protobuf其实不适合泛化，它在设计之初就希望两端通信是有确定的实体存在，dubbo侧不应该帮用户兜这个底，将选择权交由用户。建议尝试下用prefer-serialization配置下其他序列化方式进行泛化调用呢。 https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/upgrades-and-compatibility/serialization-upgrade/#%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

**Comment by zhangqingyango** [comment]
好的，了解

**Comment by zhangqingyango** [comment]
使用了一种取巧的方式，利用dubbo-compiler 项目将proto文件打包成java service 文件时，增加一个新的方法如下：
![image](https://user-images.githubusercontent.com/37824124/224982504-cb21b7fe-fb0c-461b-9482-e7c6bc930bd1.png)
通过dubbo 默认序列化进行json 泛化调用
