### ISSUE TITLE
dubbo-2.5 时代的 dubbo-monitor-simple, 现在是改到哪去了？

### ISSUE THREAD

**Issue by gMan1990** [apache/dubbo#11195]
现在应该用哪个来监控 qps，调用链（以及每个调用的响应时间）？

**Comment by AlbumenJ** [comment]
目前可以使用 skywalking 接入监控去观测调用信息。在 Dubbo 3.2 中我们也在建设 Dubbo 自己的可观测体系，包括了 promethus、grafana 的监控。

**Comment by gMan1990** [comment]
@AlbumenJ 我记得 dubbo-admin-2 时可以`上线/下线`服务, admin-3里在哪?
