### ISSUE TITLE
3.0.12 Triple does not support non-lowercase attachments

### ISSUE THREAD

**Issue by YuWan1117** [apache/dubbo#11205]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

目前业务在使用dubbo 3.0.7版本发现使用triple协议时不能传递Key1这样的header信息，了解到3.1版本已经支持（[#10761链接](https://github.com/apache/dubbo/pull/10761)）。
但由于目前我们暂时不计划升级到3.1版本，继续在3.0版本上尝试，因此希望社区可以在3.0系列上fix此问题，我们来进行小版本升级。

期待社区的回复，感谢

**Comment by AlbumenJ** [comment]
目前 3.0 分支已经是安全维护阶段了，所有的 bugfix 社区只会在 3.1 分支进行维护。为了获得更好的支持，我们建议您升级到 3.1.4 版本。

3.0 和 3.1 版本在绝大多数使用场景下是兼容的，兼容性高于 2.7 到 3.x。https://cn.dubbo.apache.org/zh/docs3-v2/java-sdk/upgrades-and-compatibility/3.0-to-3.1-compatibility-guide/

**Comment by YuWan1117** [comment]
好的。感谢回复
