### ISSUE TITLE
dubbo3.x是否可以动态配置服务降级策略

### ISSUE THREAD

**Issue by ai-log** [apache/dubbo#11209]
1. dubbo3.x是否可以动态配置服务降级策略，文档中的方法貌似并不可行

<img width="1220" alt="截屏2022-12-27 下午6 10 13" src="https://user-images.githubusercontent.com/55009961/209650980-8969bc50-6eb6-448b-b17a-134d95814e10.png">

2. 采用protobuf时，dubbo服务降级并没有做适配，导致生成参数时会报错
<img width="864" alt="截屏2022-12-27 下午6 14 18" src="https://user-images.githubusercontent.com/55009961/209651504-d11c0a24-7674-4e37-99ee-478799addaa1.png">

**Comment by AlbumenJ** [comment]
目前只支持普通pojo返回类型的，还不支持 protobuf 类型
