### ISSUE TITLE
Observability tasks: verify how skywalking connects to the micrometer

### ISSUE THREAD

**Issue by conghuhu** [apache/dubbo#11246]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

中文：
需验证下micrometer怎么和skywalking集成。

en:
Verify how the micrometer integrates with skywalking.

**Comment by mufiye** [comment]
I'm interested in this task, and I think it is relevant to the [issue](https://github.com/apache/dubbo/issues/11150)?

**Comment by conghuhu** [comment]
cc @AlbumenJ

**Comment by conghuhu** [comment]
@mufiye  You can refer to this [article](https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/application-toolkit-micrometer-1.10/) about current issue.

When verifying, you can refer to use [samples](https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-spring-boot3-tracing).

The target is to report dubbo trace information to skywalking.

**Comment by mufiye** [comment]
> @mufiye You can refer to this [article](https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/application-toolkit-micrometer-1.10/) about current issue.
> 
> When verifying, you can refer to use [samples](https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-spring-boot3-tracing).
> 
> The target is to report dubbo trace information to skywalking.

I think I get it, I will learn and do it. So if I have done the verification, should I do a pull request to the dubbo-samples repository?

**Comment by conghuhu** [comment]
ok, You can create a new module.

**Comment by mufiye** [comment]
> ok, You can create a new module.

And one more question is should I consider the "metrics" data? I see this task is below "链路追踪" in [#issue11113](https://github.com/apache/dubbo/issues/11113) which I think is about "trace".

**Comment by conghuhu** [comment]
You can do tracing first. When need metrics later, you can add.

**Comment by mufiye** [comment]
> You can do tracing first. When need metrics later, you can add.

Ok.

**Comment by mufiye** [comment]
Do we have to use otel bridge to integrate with skywalking? I think to integrate skywalking, we just use the skywalking agent API the [article](https://skywalking.apache.org/docs/skywalking-java/next/en/setup/service-agent/java-agent/application-toolkit-micrometer-1.10/) you send to me with micrometer. And when we start the dubbo application, we should do the instrument with skywalking-java-agent jar. Then we can use the skywalking oap to get trace data.

**Comment by conghuhu** [comment]
You're right. This issue has forgotten to update. Micrometer can directly connect with skywalking

**Comment by mufiye** [comment]
> You're right. This issue has forgotten to update. Micrometer can directly connect with skywalking

I get it.

**Comment by mufiye** [comment]
I have done the verification. As a result, the micrometer trace data can integrate with skywalking and I call [pull request #724](https://github.com/apache/dubbo-samples/pull/724) to submit the sample codes.

**Comment by mufiye** [comment]
> I have done the verification. As a result, the micrometer trace data can integrate with skywalking and I call [pull request #724](https://github.com/apache/dubbo-samples/pull/724) to submit the sample codes. @conghuhu
