### ISSUE TITLE
我改如何在不禁用网卡的情况下,防止特定的网卡地址被注册到注册中心?

### ISSUE THREAD

**Issue by JocelynFloresz** [apache/dubbo#11243]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## 项目启动时会把Docker容器的所有网卡地址都注册上去
项目和ZK都是Docker部署并且在同一网段, 项目由于额外加入了另一网段所以有两个虚拟网卡.
启动时会把位于两个网段的网卡都注册上去, 导致没有和ZK在同一网段的网卡无法与ZK通信.
我如何才能在不改变网络结构的情况下, 禁用另一网段的网卡呢??

**Comment by AlbumenJ** [comment]
`-Ddubbo.network.interface.ignored=ens99`
