### ISSUE TITLE
 [DUBBO] Creating global shared handler ..., dubbo version: 3.1.4, current host: 1xxxx

### ISSUE THREAD

**Issue by jackli0909** [apache/dubbo#11273]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/86995835/211707329-ffb697d8-fd15-45a6-b2d2-a8b25f1876ca.png">

dubbo 3.1.4 
springboot 2.6.11

when start application,it happended every time.
i think, it should be ' logger.info("Creating global shared handler ...");'

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo/pull/11165
