### ISSUE TITLE
Observability task: add histogram embedding points for response time

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11278]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

EN:At present, there are response times rt p95 and p99 in the built-in burying point in dubbo3.2 branch, which can effectively solve the long tail effect, but can not solve the problem of uneven average value. For example, if the time spent in 1 second and 10 seconds are 100 average values, it should be around 5.5. If you want to know the time spent in each time period more clearly, you need to use the histogram to count the time spent in each segment to diagnose the problem
Refer to the following figure:

中文：目前在dubbo3.2分支中内置埋点中存在响应时间rt  p95和p99已经有了 可以有效的解决长尾效果，但是无法解决平均值不均衡的问题比如耗时1秒和耗时10秒都是100个平均值的话应该是在5.5左右 ，如果需要比较清晰的知道每个时间段内的耗时就需要使用到直方图来统计每个分段内的耗时的次数来诊断问题
参考图如下：
![image](https://user-images.githubusercontent.com/81170548/211722461-bad8b99f-4b03-415e-9a12-bf2ed6a4f368.png)

**Comment by gsralex** [comment]
plz assign to me, thanks
