### ISSUE TITLE
ThreadPoolStatusChecker 获取线程池信息

### ISSUE THREAD

**Issue by sq-young2** [apache/dubbo#11287]
ThreadPoolStatusChecker 获取线程池信息，得到的结果是level unkown 
获取方式是通过代理：Class<?> clazz = Class.forName("com.apache.dubbo.rpc.protocol.dubbo.status.ThreadPoolStatusChecker");

**Comment by AlbumenJ** [comment]
```java
ApplicationModel.defaultModel().getApplicationExecutorRepository()
```
