### ISSUE TITLE
How can i inject a bean to my own Validator implementation?

### ISSUE THREAD

**Issue by liuruinl** [apache/dubbo#11293]
Hello community,

I'm facing a problem when i trying to implement my own validator.

I needed inject a spring-managed bean to my own Validator impl, tried the setter-way like what i did with custom filter but no luck.

Thanks.

openjdk 11
dubbo 3.0.7

**Comment by AlbumenJ** [comment]
Is your application run with dubbo-config-spring or dubbo-spring-boot-starter? If so, Dubbo will try to inject field from spring context.

org.apache.dubbo.config.spring.extension.SpringExtensionInjector
