### ISSUE TITLE
Add Dependabot Config to Repo

### ISSUE THREAD

**Issue by sconvent** [apache/dubbo#11308]
There is no Dependabot configuration file in the repo, yet apparently Dependabot runs regularly. (See #11284 for example).

However, there are some dependencies for which Dependabot does not create PRs. There might be good reasons, but it should at least be documented somewhere which dependencies are excluded or what the strategy of the dependabot with regards to major/minor/patch upgrades is.

Otherwise some important dependency upgrades might be missed while for other dependencies, the reason for not upgrading is unknown and may cause pointless efforts to do it by hand.

So I propose to add a `dependabot.yaml` file to the `.github` folder that will contain the config for Dependabot.
Any other (unseen) config of the Dependabot would have to be removed then.

What do you think?
I can certainly help with setting it up - just wanted to ask for opinions first.

**Comment by AlbumenJ** [comment]
Sounds great. I think we can track the latest depencencies version in the main branch and keep verify the compatibility in integration test from dubbo-samples.

**Comment by AlbumenJ** [comment]
Finished in https://github.com/apache/dubbo/pull/11328
