### ISSUE TITLE
使用自定义protocol发起rpc调用会导致oom

### ISSUE THREAD

**Issue by QingJuBaiTang** [apache/dubbo#11424]
### Environment

* Dubbo version: 3.1.3
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. 通过继承AbstractProxyProtocol实现一个自定义protocol
2. 不断的发起rpc调用（rpc调用需要抛出异常）

### Expected Behavior
正常调用，正常处理异常

### Actual Behavior
跑了一段时间以后应用会oom

**Comment by aamingaa** [comment]
请问能提供一个demo吗

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/215931480-1dd37879-742b-40b5-b0e6-4a951545c7be.png)

**Comment by QingJuBaiTang** [comment]
这边是一个简单的复现工程： https://github.com/QingJuBaiTang/dubbo-learn
@aamingaa  @AlbumenJ
