### ISSUE TITLE
Click next steps in the README file to enter the 404 page.

### ISSUE THREAD

**Issue by MieAh** [apache/dubbo#11426]
I found that the links of next steps in the README file in the three active branches are all expired links, and the click-in will be a 404 page, and the links need to be updated.
![image](https://user-images.githubusercontent.com/100568933/215723925-27e31035-038d-41d7-bb44-410bebd0cf6b.png)

**Comment by MieAh** [comment]
Can I fix it?

**Comment by songxiaosheng** [comment]
> Can I fix it?
> 

of course  you  can
