### ISSUE TITLE
When there is a # sign in the password, the URL cannot be parsed normally if the password is configured in the URL

### ISSUE THREAD

**Issue by hzhufa** [apache/dubbo#11422]
### Environment

* Dubbo version: 3.1.1
* Operating System version: xxx
* Java version: xxx

### Expected Behavior

            # can be supported when configuring password with URL

### Actual Behavior

config demo: 
 
     zookeeper://test:test#1223@10.301.216.302:2181

     This url is cant`t cannot be normally  parsed

     
![06@O}T1~%PJSE}S@)9Q2 FP](https://user-images.githubusercontent.com/46232940/215923549-0e0e1fff-158b-4c88-b3fe-31724bc42a5a.png)

**Comment by schneiderlin** [comment]
please assign to me

**Comment by Shruti042003** [comment]
Please assign to me

**Comment by hzhufa** [comment]
How to assign?

**Comment by chickenlj** [comment]
> 

You cannot self-assign, please go ahead and file a pull request directly.

**Comment by CrazyHZM** [comment]
@Shruti042003 
Is there any progress?
