### ISSUE TITLE
Proxyless 模式下，可以提供一个springboot集成dubbo3 的demo吗？

### ISSUE THREAD

**Issue by wxfVeryGood** [apache/dubbo#11425]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Proxyless 模式下，可以提供一个springboot集成dubbo3 的demo吗？

**Comment by aamingaa** [comment]
一直都有的，看看dubbo-samples-xds这个module，debug文档在这：

**Comment by wxfVeryGood** [comment]
@aamingaa 你们提供的demo 是基于spring启动的，不是基于springboot启动的，我需要基于springboot启动的demo，我改了一下用springboot启动有bug
![image](https://user-images.githubusercontent.com/43227440/215738026-07120d0a-011e-4c1c-be83-8a8f28d30655.png)

**Comment by aamingaa** [comment]
> @aamingaa 你们提供的demo 是基于spring启动的，不是基于springboot启动的，我需要基于springboot启动的demo，我改了一下用springboot启动有bug ![image](https://user-images.githubusercontent.com/43227440/215738026-07120d0a-011e-4c1c-be83-8a8f28d30655.png)

mesh不支持在本地运行的

**Comment by wxfVeryGood** [comment]
那请问一下其他springboot应用如何调用mesh Proxyless模式下的dubbo微服务应用了

**Comment by aamingaa** [comment]
> 

"其他springboot应用"你指的是非dubbo应用吗

**Comment by wxfVeryGood** [comment]
> 

指的是springboot运行的dubbo应用

**Comment by goto456** [comment]
> 

那应该也调不通，只要是放入网格内的应用都没法在本地启动，必须打镜像部署到k8s上
