### ISSUE TITLE
dubbo-metrics-default miss in dubbo-bom-3.2.0-beta.5-SNAPSHOT

### ISSUE THREAD

**Issue by KamToHung** [apache/dubbo#11438]
## dubbo-metrics-default miss
I see move metrics from common to dubbo-metrics [11386](https://github.com/apache/dubbo/pull/11386), but I can't see that it's  in dubbo-bom-3.2.0-beta.5-SNAPSHOT

**Comment by wxbty** [comment]
Which pom.xml lacks the default package information? Or are you having any specific issues?

**Comment by KamToHung** [comment]
> Which pom.xml lacks the default package information? Or are you having any specific issues?

Could not find artifact org.apache.dubbo:dubbo-metrics-default:pom:unknown in alimaven (http://maven.aliyun.com/nexus/content/repositories/central/)

**Comment by wxbty** [comment]
The 3.2.0-beta.5-SNAPSHOT version of dubbo has not been pushed to the central warehouse, you can try to use the master branch to install to the local rep.
![image](https://user-images.githubusercontent.com/38374721/216242812-ca2880f8-309c-4bcf-a7fc-09b8025bac20.png)

**Comment by KamToHung** [comment]
> The 3.2.0-beta.5-SNAPSHOT version of dubbo has not been deployed to the central rep, you can try to use the master branch to install to the local rep. ![image](https://user-images.githubusercontent.com/38374721/216242812-ca2880f8-309c-4bcf-a7fc-09b8025bac20.png)

My question is dubbo
