### ISSUE TITLE
provider泛型类型为Float时返回Double类型

### ISSUE THREAD

**Issue by natsumm** [apache/dubbo#11442]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: Linux Ubuntu-20.04
* Java version: 1.8

### Steps to reproduce this issue

1. provider返回泛型为Float
2. consumer以Float接收返回参数

Demo地址: https://github.com/natsumm/dubbo-generic-float-issue

### Expected Behavior

返回Float类型参数

### Actual Behavior

返回了Double类型参数，并抛出java.lang.ClassCastException

### Detail

1. provider端代码
```
@DubboService
public class DemoServiceImpl implements DemoService {

    @Override
    public String sayHello(String name) {
        return "Hello " + name;
    }

    //此处定义为Float类型
    @Override
    public List<Float> getFloats() {
        List<Float> floats = new ArrayList<>();
        floats.add(35.3F);
        floats.add(45.1F);
        return floats;
    }
}
```
2. consumer端代码
```
@SpringBootApplication
@Service
@EnableDubbo
public class ConsumerApplication {

    @DubboReference
    private DemoService demoService;

    public static void main(String[] args) {

        ConfigurableApplicationContext context = SpringApplication.run(ConsumerApplication.class, args);
        ConsumerApplication application = context.getBean(ConsumerApplication.class);
        String result = application.doSayHello("world");
        System.out.println("result: " + result);

        //此处返回了Double类型
        List<Float> floats = application.getFloats();
        System.out.println("floats = " + floats);
        Float aFloat = floats.get(0);
    }

    public String doSayHello(String name) {
        return demoService.sayHello(name);
    }

    public List<Float> getFloats() {
        return demoService.getFloats();
    }
}
```
3. 预期返回Float类型实际Double
![image](https://user-images.githubusercontent.com/75228668/216214559-64b8b85a-c0c9-4d79-9b26-e37e938696aa.png)

**Comment by natsumm** [comment]
经验证，dubbo 3.0.0~3.1.5均存在此问题

**Comment by mytang0** [comment]
Yes, the problem is caused by serialization of float by hessian.

**Comment by natsumm** [comment]
However, when I used other serialization protocols(like `kryo` and `sft`), it still returned **Double** type except `nativejava`.

**Comment by mytang0** [comment]
> However, when I used other serialization protocols(like `kryo` and `sft`), it still returned **Double** type except `nativejava`.

Thank you for your feedback.  Let's wait for the fix.

**Comment by natsumm** [comment]
我目前是这么处理的
dubbo.version = 3.1.5
# 1 application.yml
```yaml
dubbo:
  protocols:
    dubbo:
      name: dubbo
      serialization: fst
```
# 2 pom.xml
```xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-serialization-fst</artifactId>
</dependency>
```

**Comment by natsumm** [comment]
> 我目前是这么处理的 dubbo.version = 3.1.5
> 
> # 1 application.yml
> ```yaml
> dubbo:
>   protocols:
>     dubbo:
>       name: dubbo
>       serialization: fst
> ```
> 
> # 2 pom.xml
> ```
> <dependency>
>     <groupId>org.apache.dubbo</groupId>
>     <artifactId>dubbo-serialization-fst</artifactId>
> </dependency>
> ```

使用`fst`插件的版本为 2.7.22
