### ISSUE TITLE
初始化执行顺序问题

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#11445]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.5
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/31852897/216251306-1c2617aa-0b51-4de6-bd59-fcb31872e3e1.png)
这块的执行顺序是不是有问题啊
先去连接生产者 然后生产者没启动 所以报错了
然后接下来 收到了空协议 清空所有可用地址

是不是应该先收到空协议 然后清除掉可用地址 之后也就不会去连接不会报错了

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
这个是收到 nacos 地址通知后，因为连不上把地址给剔除了，所以出现了 empty 地址

**Comment by JavaLionLi** [comment]
> 这个是收到 nacos 地址通知后，因为连不上把地址给剔除了，所以出现了 empty 地址

emmm 可是初始化先连的生产者 然后报错了 之后才收到nacos的通知删除了地址
如果先订阅收到通知把无效的生产者删除 是不是就不会报错了呢

**Comment by AlbumenJ** [comment]
> 如果先订阅收到通知把无效的生产者删除 是不是就不会报错了呢

最终结果是一样的，3.1.6 版本中已经关闭了 nacos 的本地缓存

**Comment by JavaLionLi** [comment]
> > 如果先订阅收到通知把无效的生产者删除 是不是就不会报错了呢
> 
> 最终结果是一样的，3.1.6 版本中已经关闭了 nacos 的本地缓存

那就是说 升级到3.1.6应该就不会有这个报错问题了吧

**Comment by JavaLionLi** [comment]
升级到3.1.6后解决报错问题
