### ISSUE TITLE
错误的警告

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#11446]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.5
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/31852897/216253050-1c5c0ec7-c79a-4147-bb8d-3ebefc072447.png)

警告说的是相同的协议在不同的端口 然而端口是相同的 这就令人很诧异 每个服务都会报 应该是新版本的bug

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
Already fix in https://github.com/apache/dubbo/pull/11202
