### ISSUE TITLE
I can't inject Spring @Bean into dubbo service.

### ISSUE THREAD

**Issue by wjzmr** [apache/dubbo#1145]
请教，最近遇到了dubbo和spring 依赖注入问题，想在@Bean的配置类中注入dubbo服务怎么办，因为dubbo 注解是依赖spring注解的，所以在@Bean的时候是取不到dubbo服务的

**Comment by chickenlj** [comment]
Can you describe your question in more detail? or with some demo code?

**Comment by iamrenpeng** [comment]
@Lazy(true)行不行

**Comment by chickenlj** [comment]
Dubbo should support specify id of ServiceBean registered to Spring.

**Comment by AlbumenJ** [comment]
Please check in the latest version. If you have any question, please submit a new issue.
