### ISSUE TITLE
MetadataService version 被覆盖

### ISSUE THREAD

**Issue by web1992** [apache/dubbo#11490]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.4
* Operating System version: mac os
* Java version: 1.8

### Steps to reproduce this issue

1. 在使用 dubbo 3.x 的时候，如果设置了 类似 `System.setProperty("dubbo.service.version", "TEST");` 的系统属性，那么就会覆盖(因为dubbo 只能中引入了属性覆盖机制)`org.apache.dubbo.metadata.MetadataService` 的版本，如下图：
<img width="710" alt="image" src="https://user-images.githubusercontent.com/6828647/216927841-87f218e4-2dd1-4eab-b5c3-56c75454a6fb.png">
默认版本是1.0.0

2. 那么在进行MetadataService服务调用的时候就会找不到1.0.0 的版本，导致出错。出错代码在`org.apache.dubbo.remoting.transport.CodecSupport#checkSerialization` 中

如果这个是一个问题。
我想到的解决方案，在进行服务版本的覆写的时候，跳过 MetadataService 服务。如果 MetadataService 的本版被修改了，如果后续对MetadataService进行一版本的升级，可能存在问题。

复现的项目地址 https://github.com/web1992/demo-dubbo-3x

error.log

```
java.io.IOException: Service org.apache.dubbo.metadata.MetadataService with version 1.0.0 not found, invocation rejected.
Caused by: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.io.IOException: Service org.apache.dubbo.metadata.MetadataService with version 1.0.0 not found, invocation rejected.
```

在 中 DecodeableRpcInvocation#decode 方法中 try catch 的处理不对，应该改成 `ClassNotFoundException | IOException`

```java
 catch (ClassNotFoundException e) {
            throw new IOException(StringUtils.toString("Read invocation data failed.", e));
}
```

如果没捕获，异常就没了。

**Comment by mytang0** [comment]
It depends on whether the services provided by Dubbo should be distinguished from the normal services provided by business applications. If there is no need to distinguish, then the current coverage is OK; if it needs to be distinguished, you can add an interface or an identifier to determine whether it is an internal service of Dubbo. I observed that the MetricsService of 3.2 also has coverage problems. 

@AlbumenJ

**Comment by AlbumenJ** [comment]
This should be a bug. `ConfigurableMetadataServiceExporter` has set version property and should not be override. The reason why being refreshed is `AbstractConfig` only get declared method (without inherited methods) and ignore `getVersion` method.
