### ISSUE TITLE
use @DubboService protocol not support tri 

### ISSUE THREAD

**Issue by SpringDay6** [apache/dubbo#11509]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.1
* Operating System version:win10
* Java version: java8

### Steps to reproduce this issue

@DubboService(protocol = "dubbo,tri") start spring boot 
it will generate a error,java.lang.IllegalStateException: Protocol not found: tri

**Comment by aamingaa** [comment]
试试这个？protocol = {"dubbo","tri"}

**Comment by MieAh** [comment]
你需要在配置文件中进行配置，如下
![image](https://user-images.githubusercontent.com/100568933/225373072-154b8d3c-7a6a-454f-8bf2-668df072f043.png)
