### ISSUE TITLE
Compile failed.

### ISSUE THREAD

**Issue by YunWZ** [apache/dubbo#11519]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2
* Operating System version: macOS13
* Java version: 11.0.17

### Steps to reproduce this issue

1. clone dubbo repo.(the lateset 3.2 branch)
2. exec `mvn clean install -DskipTests`

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

compile success.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
[INFO] dubbo-registry-nacos 3.2.0-beta.5-SNAPSHOT ......... FAILURE [  1.010 s]

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2023-02-10T16:02:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project dubbo-registry-nacos: Compilation failure: Compilation failure: 
[ERROR] /Users/yunye/code/apache/dubbo-group/dubbo/dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/function/NacosConsumer.java:[21,38] 错误: 程序包com.alibaba.nacos.apiption不存在
```

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/218038845-ec2fc476-5170-4f8b-9cf0-20872f1c9294.png)

Please check if you have chenge the source code.
The origin source here is 
```java
import com.alibaba.nacos.api.exception.NacosException;
```

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/218043692-aabaaef6-f685-4789-bad8-9a2c0ce65984.png)
`nacos-client` has shade this class
