### ISSUE TITLE
consumer use filer,@Reference service is null

### ISSUE THREAD

**Issue by l343765828** [apache/dubbo#11539]
public class DubboLogFilter implements Filter {
@reference(version = "1.0.1",check = false)
private GetId getid;

@OverRide
public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
try {
System.out.println("did：" + getid.getUidTest("a"));
} catch (Exception e) {
e.printStackTrace();
}
finally {
return invoker.invoke(invocation);
}
}

GetId is null

dubbo version is 2.7.5, How to solve？

**Comment by l343765828** [comment]
@AlbumenJ

**Comment by KamToHung** [comment]
miss @Activate

**Comment by aamingaa** [comment]
It is not supported and should not be supported. The logic of resending requests during request processing is problematic.

**Comment by AlbumenJ** [comment]
Inject `Reference` into `Filter` is not permitted.
