### ISSUE TITLE
Enhance the way to get dubbo version

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#11559]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

`org.apache.dubbo.common.Version` try get dubbo version from jar file name. The better way is to define a resource file in `dubbo-common` and override it when maven compile which can get the proper `revision` and `git commit hash`(Add a new method in `Version` to get `hash` and log out in logger).

**Comment by mytang0** [comment]
Please assign me.
