### ISSUE TITLE
dubbo-2.7.18针对nacos 2.1.1版本的压测问题

### ISSUE THREAD

**Issue by anuserin** [apache/dubbo#11563]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
因目前在做dubbo2.7.6->2.7.18 + nacos-client +nacos-server-2.1.1 的整体升级进行压测
报告显示在服务实例数均为一万的情况下
     dubbo-2.7.6+nacos*-2.1.1 的cpu使用率为47%，9848端口建链数为4000左右
     dubbo-2.7.18+nacos*-2.1.1 的cpu使用率为6%， 9848端口建链数为135左右
     8848为注册中心端口，偏移量为9848
在相同服务器上，配置一样，想问题为何会有如此大的差别，是做什么对nacos的优化了吗？在报告上并没发现相关处理。

**Comment by AlbumenJ** [comment]
May related with https://github.com/apache/dubbo/pull/6571

**Comment by anuserin** [comment]
请认真下看疑问点，我认为与此项修改并无关联

**Comment by anuserin** [comment]
> May related with #6571
请认真下看疑问点，我认为与此项修改并无关联

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/pull/6571 修改了注册中心的缓存，在这个提交之前，客户端发布了 n 个服务，就会建立 n 条连接，在这之后才会合并到同一个连接使用
