### ISSUE TITLE
Tag route

### ISSUE THREAD

**Issue by zonghaishang** [apache/dubbo#11585]
我走读了一下路由逻辑，有一个场景，如果请求没有带tag,  有可能请求 其他tag的服务（ 被routerule 规则排除的tag ）上，这个是符合预期的吗？

Consume A ->  Provider A1 (tag=grey，address=10.1),  Provider A2 (tag=grey，address=10.2),   Provider A3 (tag= blue，address=10.3)

下发的规则，tag=grey, address=[10.1, 10.2] 不包含address=10.3的实例。

看代码，会返回10.3 tag=blue的地址？

![image](https://user-images.githubusercontent.com/15549777/219304098-14b96906-6672-4807-93cd-484715043821.png)

code line: https://github.com/apache/dubbo/blob/master/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagRouter.java#L143

印象中，没有tag的客户端 不应该请求到tag的机器，希望我理解是错的

![image](https://user-images.githubusercontent.com/15549777/219306311-80879050-1054-412e-be55-d92a8185a01c.png)

**Comment by zonghaishang** [comment]
应当删除 `|| !tagRouterRuleCopy.getTagNames().contains(localTag)` , 这样保证 没有tag的请求，不会调用到有tag的机器

**Comment by mytang0** [comment]
我翻了一下提交记录。发现，第一版是你描述的那样，没有这个条件的。commit 927a7e5a 重构的时候被加上了这个逻辑。
