### ISSUE TITLE
为 Metrics 示例增加 kubernetes 部署支持

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#11604]
https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-metrics-spring-boot

**Comment by ShenFeng312** [comment]
assign to me, thanks

**Comment by ShenFeng312** [comment]
Added in https://github.com/apache/dubbo-samples/pull/745

**Comment by ShenFeng312** [comment]
需要等  https://github.com/apache/dubbo/pull/11630 merge 后重新添加demo
