### ISSUE TITLE
RestProtocol doRefer consistency bug

### ISSUE THREAD

**Issue by mytang0** [apache/dubbo#11618]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2
* Operating System version: Darwin
* Java version: 1.8

### Steps to reproduce this issue
When referenceCountedClient.isDestroyed(), createReferenceCountedClient has no constraints.

```
        ReferenceCountedClient referenceCountedClient = ConcurrentHashMapUtils.computeIfAbsent(clients, url.getAddress(), _key -> {
            // TODO more configs to add
            return createReferenceCountedClient(url);
        });

        if (referenceCountedClient.isDestroyed()) {
            referenceCountedClient = createReferenceCountedClient(url);
            clients.put(url.getAddress(), referenceCountedClient);
        }
```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL
