### ISSUE TITLE
[BUG]Service Name Mapping 

### ISSUE THREAD

**Issue by mark4z** [apache/dubbo#11639]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

boolean contains = StringUtils.isContains(oldConfigContent, appName) has problem.
oldConfigContentis a list of service names. If strings.Contains(oldVal, appName), then the SNP registration will be skipped, e.g. if oldConfigContentis = dubbo.io-2 and appName= dubbo.io, then newServiceName will be skipped.

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

```java
    MetadataServiceNameMapping.java
    public boolean map(URL url) {
        boolean result = true;
        for (Map.Entry<String, MetadataReport> entry : metadataReportInstance.getMetadataReports(true).entrySet()) {
                do {
                    ConfigItem configItem = metadataReport.getConfigItem(serviceInterface, DEFAULT_MAPPING_GROUP);
                    String oldConfigContent = configItem.getContent();
                    if (StringUtils.isNotEmpty(oldConfigContent)) {
                        boolean contains = StringUtils.isContains(oldConfigContent, appName);
                        if (contains) {
                            // From the user's perspective, it means successful when the oldConfigContent has contained the current appName. So we should not throw an Exception to user, it will confuse the user.
                            succeeded = true;
                            break;
                        }
    }
```

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by mark4z** [comment]
@AlbumenJ

**Comment by aamingaa** [comment]
https://github.com/apache/dubbo/pull/11643/files
