### ISSUE TITLE
dubbo 2.7.x 不支持泛型接口的注入吗

### ISSUE THREAD

**Issue by qinzhewudao** [apache/dubbo#11636]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
报错信息:org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xxxxx': Injection of @DubboReference dependencies is failed; nested exception is java.lang.IllegalArgumentException: @Service interfaceClass() or interfaceName() or interface class must be present!

接口定义如下:
```
public interface GeneralPunishService<P extends AbstractRequest> {
	Response<SinResponse> actionOnUser(P request);
}
```
注入方式如下:
```
@DubboReference
private GeneralPunishService<AbstractRequest> addLimitConsumeService;
```
debug发现是注入的时候去获取interface类型因为泛型的信息而失败了
com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.AnnotatedFieldElement#resolveInjectedType
获取到的 injectedType = null

**Comment by AlbumenJ** [comment]
Dubbo 链路中服务发现的整体模型都是直接基于服务名去定义的，不支持泛型

**Comment by qinzhewudao** [comment]
> Dubbo 链路中服务发现的整体模型都是直接基于服务名去定义的，不支持泛型

在2.6中是可以正常注入的,虽然并没有带上泛型信息.

**Comment by AlbumenJ** [comment]
> 在2.6中是可以正常注入的,虽然并没有带上泛型信息.

如果预期就是不带上泛型信息的，可以尝试升级到 3.1.7，Spring 注入的逻辑在 3.x 完整重构了，上面的信息看起来是 2.7 的 Spring 适配问题
