### ISSUE TITLE
2.7.x not compatible of 2.6.x LoadBalance

### ISSUE THREAD

**Issue by wegod** [apache/dubbo#11644]
### Environment

* Dubbo version: 2.7.20
* Java version: 1.8

### Steps to reproduce this issue

1. 在2.6.x的基础服务中创建一个LoadBalance
2. 在2.7.x的服务中引用这个LoadBalance
3. 如在2.7.20中，com.alibaba.dubbo.rpc.cluster.LoadBalance会转成compatible的类去寻找Invoker
```java
return select(invs, new com.alibaba.dubbo.common.URL(url),
                new com.alibaba.dubbo.rpc.Invocation.CompatibleInvocation(invocation));
```
4. 但是在FailoverClusterInvoker的invoker.invoke(invocation)时，没有对invocation进行compatible转换，导致调用了com.alibaba.dubbo.rpc.Invoker的default invoke方法return了null
5. 导致AbstractCluster的asyncResult为null，asyncResult.whenCompleteWithContext调用时抛了空指针
### Expected Behavior

既然兼容了2.6.x版本的LoadBalance寻找Invoker，就应该兼容invoker去执行invoke操作，然后返回结果
如在2.7.x的CompatibleInvoker中增加兼容Invocation处理

**Comment by wegod** [comment]
translate by chatGPT

**Comment by wegod** [comment]
but whenCompleteWithContext in com.alibaba.dubbo.rpc.Result always return null.
So it's better to throw an Exception about 2.7.x not compatible of 2.6.x LoadBalance

**Comment by wegod** [comment]
I add two compatible method implements and it works. 
CompatibleInvoker add method:
`        @Override
        public org.apache.dubbo.rpc.Result invoke(org.apache.dubbo.rpc.Invocation invocation) throws org.apache.dubbo.rpc.RpcException {
            return new Result.CompatibleResult(invoker.invoke(invocation));
        }`

CompatibleResult add method:
`        @Override
        public org.apache.dubbo.rpc.Result whenCompleteWithContext(BiConsumer<org.apache.dubbo.rpc.Result, Throwable> fn) {
            return delegate.whenCompleteWithContext(fn);
        }`

**Comment by AlbumenJ** [comment]
Would you please submit a PR to fix?

**Comment by wegod** [comment]
OK, but I don't test other cases 😂
