### ISSUE TITLE
Observability task: Reuse Meter port to QOS port

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11649]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Describe the proposal

EN:
Observability task: Reuse Meter port to QOS port. With more and more built-in functions of dubbo, more and more ports are exposed. Many ports can be used. At the same time, it can also reduce the creation of HttpServer objects. Ports targeted at the observability index buried point can serve the current QOS service ports, which can be distinguished by path。

中文：
可观测性任务：复用Meter端口到QOS端口，随着dubbo内置功能越来越多对外暴漏的端口也越来越多，很多端口是可以服用，同时也可以减少HttpServer对象的创建，针对可观测性指标埋点的端口可以服用当前QOS服务的端口，通过路径来区分。

**Comment by wxbty** [comment]
pls assign me

**Comment by songxiaosheng** [comment]
> pls assign me

ok
