### ISSUE TITLE
使用Triple协议 传参有空值会报错

### ISSUE THREAD

**Issue by HelloToGithub** [apache/dubbo#11648]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
![image](https://user-images.githubusercontent.com/15622677/221121735-39571dc2-d771-493a-9d3c-14f8a8ee239f.png)
ReflectionPackableMethod类中 argument.getClass().getName()报空指针
            for (Object argument : arguments) {
                builder.addArgTypes(argument.getClass().getName());
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                multipleSerialization.serialize(url, serialize, argument.getClass(), argument, bos);
                builder.addArgs(bos.toByteArray());
            }

**Comment by EarthChen** [comment]
升级一个版本或者降级一个版本即可，中间修复一个其他问题引入的

**Comment by HelloToGithub** [comment]
感谢回复。我现在的版本是3.1.5 我在官网的版本记录看3.1.5是最新的稳定版 之后就是3.2.0的beta版本 请问升级可以升级到哪个版本



在 2023-02-24 20:34:12，"earthchen" ***@***.***> 写道：

升级一个版本或者降级一个版本即可，中间修复一个其他问题引入的

**Comment by AlbumenJ** [comment]
> 感谢回复。我现在的版本是3.1.5 我在官网的版本记录看3.1.5是最新的稳定版 之后就是3.2.0的beta版本 请问升级可以升级到哪个版本 在 2023-02-24 20:34:12，"earthchen" ***@***.***> 写道： 升级一个版本或者降级一个版本即可，中间修复一个其他问题引入的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

3.1.7 版本

**Comment by HelloToGithub** [comment]
![image](https://user-images.githubusercontent.com/15622677/221463407-8c1a8f10-a38f-49af-a44d-4088705c95d3.png)
尝试升级3.1.7 依然有问题

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/11656

**Comment by xiehongji** [comment]
> 

您好。这个问题是在哪个版本被修复了

**Comment by HelloToGithub** [comment]
> 

我暂时使用dubbo协议。具体修复版本应该要社区发布下一个3.1.x版本

**Comment by AlbumenJ** [comment]
> > 
> 
> 您好。这个问题是在哪个版本被修复了

3.1.8

**Comment by HelloToGithub** [comment]
> > > 
> > 
> > 
> > 您好。这个问题是在哪个版本被修复了
> 
> 3.1.8

您好 3.1.8版本阿里Maven云仓是不是还没上传

**Comment by AlbumenJ** [comment]
> > > > 
> > > 
> > > 
> > > 您好。这个问题是在哪个版本被修复了
> > 
> > 
> > 3.1.8
> 
> 您好 3.1.8版本阿里Maven云仓是不是还没上传

正在投票中，预计周四正式同步
