### ISSUE TITLE
dubbo2.7.4.1版本容器化后存在No Provider异常问题

### ISSUE THREAD

**Issue by gulang12** [apache/dubbo#11654]
目前项目采用的是dubbo2.7.4.1+nacos-client2.0.3 注册配置中心部署到k8s上，但是服务提供者重新部署后，服务消费者还是会调用旧的容器IP，导致出现No provider available from registry异常问题？

### Environment
* Dubbo version: 2.7.4.1
* Java version: jdk1.8
* nacos-client:2.0.3
想问下这个问题是dubbo原因造成的还是nacos造成的。
1.如果是dubbo造成的，那dubbo2.7.X一系列版本是不是都存在这个问题，目前有哪个版本已经解决了这个问题？
2.如果是nacos造成的，那目前有哪个nacos-client版本已经解决了这个问题？

**Comment by AlbumenJ** [comment]
请升级到最新的 3.1.7 版本，如果还有问题再提交相关的报错及日志
