### ISSUE TITLE
metadata-type=local local - Provider怎么配置

### ISSUE THREAD

**Issue by helloy0920** [apache/dubbo#11722]
Consumer 从注册中心获取local - Provider 把 metadata 放在本地，Consumer 从 Provider 处直接获取 使用方式

**Comment by kazetyan** [comment]
`dubbo.application.metadataType=local`
默认就是local,可以不用改
![image](https://user-images.githubusercontent.com/50894526/222884980-9bdfb5d4-6eae-48e7-b39e-c5a048a370a3.png)

**Comment by helloy0920** [comment]
配置如下：
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    metadata-type: remote
    register-consumer: true
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    qosEnable: true
    qosPort: 33334
  registry:
    address: nacos://127.0.0.1:8848
    group: dubbo-${spring.profiles.active}
    use-as-config-center: false
    use-as-metadata-center: false
    register-mode: instance
    register: true
    subscribe: true
    parameters:
      registry-type: service
=========================

 我把   use-as-metadata-center 设置为false，不把注册中心当元数据中心，也不配元数据中心， consumer 就 直接NoProvider 了，我理解应该是去注册中心找的订阅的服务地址，然后调用MetaDataService获取元数据， 是我理解有问题还是配置有问题 dubbo版本3.1.7

**Comment by helloy0920** [comment]
配置如下：
dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
    metadata-type: remote
    register-consumer: true
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    qosEnable: true
    qosPort: 33334
  registry:
    address: nacos://127.0.0.1:8848
    group: dubbo-${spring.profiles.active}
    use-as-config-center: false
    use-as-metadata-center: false
    register-mode: instance
    register: true
    subscribe: true
    parameters:
      registry-type: service
=========================

 我把   use-as-metadata-center 设置为false，不把注册中心当元数据中心，也不配元数据中心， consumer 就 直接NoProvider 了，我理解应该是去注册中心找的订阅的服务地址，然后调用MetaDataService获取元数据， 是我理解有问题还是配置有问题 dubbo版本3.1.7

**Comment by helloy0920** [comment]
> `dubbo.application.metadataType=local` 默认就是local,可以不用改 ![image](https://user-images.githubusercontent.com/50894526/222884980-9bdfb5d4-6eae-48e7-b39e-c5a048a370a3.png) https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/#application

配置如下
![image](https://user-images.githubusercontent.com/45870181/222890483-83e0f80e-4e27-46bf-8bf2-7047a970a996.png)
我把 use-as-metadata-center 设置为false，不把注册中心当元数据中心，也不配元数据中心， consumer 就 直接NoProvider 了，我理解应该是去注册中心找的订阅的服务地址，然后调用MetaDataService获取元数据， 是我理解有问题还是配置有问题 dubbo版本3.1.7

**Comment by helloy0920** [comment]
配置如下：
![image](https://user-images.githubusercontent.com/45870181/222890587-39255bd9-ae29-4b43-a116-cb2a16e312ba.png)
我把 use-as-metadata-center 设置为false，不把注册中心当元数据中心，也不配元数据中心， consumer 就 直接NoProvider 了，我理解应该是去注册中心找的订阅的服务地址，然后调用MetaDataService获取元数据， 是我理解有问题还是配置有问题 dubbo版本3.1.7

**Comment by yuchang01** [comment]
consumer 的@DubboReference指定一下providerBy试试，通过服务名匹配到注册中心的服务instance，然后拿provider的local metadata

**Comment by helloy0920** [comment]
好的，感谢 🙏，已经解决
