### ISSUE TITLE
In the future, whether dubbo-monitor will cooperate with Prometheus and use Grafana to display monitoring data？

### ISSUE THREAD

**Issue by zhaojigang** [apache/dubbo#1172]

**Comment by chickenlj** [comment]
I think that's a good suggestion, we can search the possibilities of integration. This combination is good at of collecting and displaying monitor data.
Do you have any resources of integrating with Prometheus and Grafana?

**Comment by zhaojigang** [comment]
I had previously integrated Prometheus and Grafana with springboot-actuator. I will try to integrate them with dubbo recently.

**Comment by yinwerhong** [comment]
I added the feature, starting with spring boot, into version dubbox of dubbo-monitor. For more information, https://gitee.com/yinwerhong/dubbo-monitor

**Comment by ralf0131** [comment]
@yinwerhong I cannot access  https://gitee.com/yinwerhong/dubbo-monitor  

It says it does not exist.

Have you moved this repo to somewhere else?

**Comment by DatPhanTien** [comment]
@zhaojigang @yinwerhong, do you have any update on the progress of Prometheus integration into Dubbo repo?

**Comment by ralf0131** [comment]
Hi, there is an ongoing pull request which aims to provide Prometheus support for metrics, https://github.com/alibaba/metrics/pull/42. Once it get merged, Dubbo can use that feature to expose metrics data in Prometheus format.

**Comment by realcaiying** [comment]
> Hi, there is an ongoing pull request which aims to provide Prometheus support for metrics, [alibaba/metrics#42](https://github.com/alibaba/metrics/pull/42). Once it get merged, Dubbo can use that feature to expose metrics data in Prometheus format.


i noticed https://github.com/alibaba/metrics/pull/42 had been merged, any documents show how does it work with prometheus?
