### ISSUE TITLE
关于ReferenceConfig的get()方法调用init()方法的疑问

### ISSUE THREAD

**Issue by kang-hl** [apache/dubbo#11768]
init()方法已经被synchronized关键字所修饰，get()方法调用init()方法所进行的同步操作是否多余？

**Comment by MieAh** [comment]
这确实会出现两次同步操作，在init上加synchornized是没必要的

**Comment by MieAh** [comment]
但DCL是必要的，避免多次初始化

**Comment by kang-hl** [comment]
> 但DCL是必要的，避免多次初始化

保留init上的synchornized，删除DCL，不会多次初始化吧
