### ISSUE TITLE
3.2.0 多会出release版本？

### ISSUE THREAD

**Issue by sadlay** [apache/dubbo#11779]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

dubbo3.1.x 版本条件路由不支持从attachment中获取参数，看3.2.0已经支持，请问release版本有大概的发布时间吗？
同时，该功能未来是否会在3.1版本中支持？

**Comment by sadlay** [comment]
@AlbumenJ

**Comment by C20171008S** [comment]
快点出3.2.0-release吧，等不及了别的组件早都支持sb3 jdk17了

**Comment by liuwawa** [comment]
特别期待3.2.0-release版本的metrics功能，每天都过来刷动态

**Comment by AlbumenJ** [comment]
本月底会发布哈，这两天会再发布一个beta版本，可以先在beta版本上测试功能，最终 release 版本就可以直接上了

**Comment by 1076718373** [comment]
3.1.1可以用3.2的metrics吗？

**Comment by AlbumenJ** [comment]
> 3.1.1可以用3.2的metrics吗？

需要版本升级哈
