### ISSUE TITLE
The remote address could not be obtained from the context after the request

### ISSUE THREAD

**Issue by chaoyoung** [apache/dubbo#11790]
### Environment

* Dubbo version: 3.1.6
* Operating System version: macOS 13.2
* Java version: 1.8.0_362

### Steps to reproduce this issue

1. add a filter in consumer
    ```java
    @Slf4j
    public class RpcContextFilter implements Filter {
        @Override
        public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
            log.info("invoker url: {}:{}", invoker.getUrl().getHost(), invoker.getUrl().getPort());
            Result result = invoker.invoke(invocation);
            log.info("remote address: {}", RpcContext.getContext().getRemoteAddress());
            return result;
        }
    }
    ```
2. `resources/META-INF/dubbo/org.apache.dubbo.rpc.Filter` content
    ```properties
    rpcContextFilter=org.example.dubbo.filter.RpcContextFilter
    ```
3. dubbo consumer dependency
    ```java
    @DubboReference(filter = "rpcContextFilter")
    ```
4. After a request, the filter prints the log as follows:
    ```
    2023-03-10 19:08:45.667  INFO 77228 --- [nio-8081-exec-1] o.example.dubbo.filter.RpcContextFilter  : invoker url: 10.9.0.162:50051
    2023-03-10 19:08:45.817  INFO 77228 --- [nio-8081-exec-1] o.example.dubbo.filter.RpcContextFilter  : remote address: null
    ```

### Expected Behavior

The remote address can be obtained.

### Actual Behavior

The remote address is empty

If there is an exception, please attach the exception trace:

```

```

**Comment by songxiaosheng** [comment]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/81170548/229042380-38bcc3fe-d0ce-4493-aa95-a01f6ce4e0ba.png">
You can temporarily retrieve it from the invoker object

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo/pull/11824
