### ISSUE TITLE
Can the Blacklist Mechanism be Re-enabled for Generic Invoke?

### ISSUE THREAD

**Issue by BfeiC** [apache/dubbo#11792]
We have noticed that the latest version of the software has changed the generic invoke mechanism to default to a whitelist. However, this is too strict for our needs. Is it possible to re-enable the blacklist mechanism? If so, could you please provide instructions on how to do it? Thank you for your assistance in resolving this issue.

**Comment by AlbumenJ** [comment]
Which version do you use?

**Comment by BfeiC** [comment]
> Which version do you use?

I just updated to the latest version 3.2.0-beta.5.

**Comment by BfeiC** [comment]
> > > Which version do you use?
> > 
> > 
> > I just updated to the latest version 3.2.0-beta.5.
> 
> Please see https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/security/class-check/

Thank you for your reply! I have successfully resolved the issue!
