### ISSUE TITLE
Is there official document to introduce how Deployer lifecycle changes? 

### ISSUE THREAD

**Issue by OrezzerO** [apache/dubbo#11799]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Is there official document to introduce how Deployer lifecycle changes?  

I am researching how dubbo starts. There are many state in DeployState. It is hard to understand how they change by reading the source code.  So I want to know if there is official document to introduce it.

**Comment by AlbumenJ** [comment]
I am afraid that there may not documents related to this. 🤧🤧

**Comment by OrezzerO** [comment]
OK, I will try to write something about it.
