### ISSUE TITLE
请问现在3.2.0-beta.5支持的jdk和spring boot/spring cloud最高是到多少版本？？

### ISSUE THREAD

**Issue by soiz-tor** [apache/dubbo#11791]
我现在jdk：19，spring boot：3.0.4
就总是会出现报错，有序列化的，有provider连不上的

**Comment by AlbumenJ** [comment]
3.2.0-beta.5 支持 jdk 19 和 Spring Boot 3。
关于序列化的需要 provider consumer 两端都升级到 3.2，否则还是会出于兼容性原因继续使用 hessian 2。

**Comment by AlbumenJ** [comment]
> > 3.2.0-beta.5 支持 jdk 19 和 Spring Boot 3。 关于序列化的需要 provider consumer 两端都升级到 3.2，否则还是会出于兼容性原因继续使用 hessian 2。
> 
> 请问下 3.2.0-beta.5支持spring native么

支持的

**Comment by shiloliao** [comment]
> > > 3.2.0-beta.5 支持 jdk 19 和 Spring Boot 3。 关于序列化的需要 provider consumer 两端都升级到 3.2，否则还是会出于兼容性原因继续使用 hessian 2。
> > 
> > 
> > 请问下 3.2.0-beta.5支持spring native么
> 
> 支持的
但是我在编译的时候也遇到了这个问题 https://github.com/apache/dubbo/issues/11048 不知道该怎么解决

**Comment by AlbumenJ** [comment]
> > > > 3.2.0-beta.5 支持 jdk 19 和 Spring Boot 3。 关于序列化的需要 provider consumer 两端都升级到 3.2，否则还是会出于兼容性原因继续使用 hessian 2。
> > > 
> > > 
> > > 请问下 3.2.0-beta.5支持spring native么
> > 
> > 
> > 支持的
> > 但是我在编译的时候也遇到了这个问题 #11048 不知道该怎么解决

@CrazyHZM PTAL

**Comment by lukelongcn** [comment]
JDK17 都不支持，还是 beta 版本，JDK19就不要想了。

**Comment by AlbumenJ** [comment]
> JDK17 都不支持，2023年4月份还是 beta 版本，JDK19就不要想了。

3.2 本周就会正式发布，原生支持 JDK17。年底发布的 JDK21 也会及时跟进。JDK17 主要是因为 JDK 内部类限制导致有兼容性问题。
