### ISSUE TITLE
Question about distributed trace

### ISSUE THREAD

**Issue by dylan-tao** [apache/dubbo#1180]
slf4j的MDC的put、get可以方便分布式环境日志的链路跟踪，将生成的唯一key在日志里进行打印，建议dubbo的RPC传输数据时在consume -> provider之间默认将MDC的唯一key进行传输（如果多方传递时要考虑上游是否为空，为空则生成；不为空则继续传递），方便问题追踪，当然也可以通过配置开关来决定是否开启。这样一条请求打到机器上，可以很清晰的从web->consumer->provider排查问题,甚至更复杂的consumer->provider嵌套。

**Comment by zuohl** [comment]
你可以自己写拦截器扩展..

**Comment by jww0924** [comment]
建议考虑下和motan一样在框架层面增加[对opentracing的支持](https://github.com/weibocom/motan/wiki/zh_quickstart#%E4%BD%BF%E7%94%A8opentracing)，方便和APM系统对接

**Comment by caijunjun** [comment]
实现了com.alibaba.dubbo.rpc.Filter，将上游的参数往下传递，就是硬编码了，有点不雅，不知道有什么更好的方式

**Comment by chickenlj** [comment]
@jww0924 We have adapted with opentracing recently, not too much work for dubbo. We can release this feature in the next version.

**Comment by dylan-tao** [comment]
做好其实不容易，还要考虑异步线程嵌套MDC丢失的问题，所以建议还是加上并支持多线程和异步线程的场景，slf4j应该是相对比较好的日志系统了，本身logback就可以自动将日志头打印traceId。能加个开关控制并能可扩展的适配监控系统，才算相对优雅。

**Comment by dylan-tao** [comment]
It's not easy to do this, but you have to consider the loss of nested MDC for asyn threads, so it's recommended that you add and support multithreading and asyn threads，slf4j is a good logging system. Logback itself can automatically print the log header  -> traceId. can add a switch control and scalable adaptive monitoring system, is relatively elegant.
 ps: 
 for logback: <pattern>%d{MM-dd HH:mm:ss} [%X{jtraceId}] %2p %logger{0}:%L - %msg%n</pattern>

**Comment by nobodyiam** [comment]
@chickenlj 

Would love to see how you guys adapted with open tracing, we just worked out a solution that works, yet not elegantly.

The major challenge is how to pass the trace data between different threads, e.g. the i/o worker which handles decode, the dubbo thread which handles execution and encode, etc. 

As we need to present the whole process of decoding request, execution, encoding response in one message tree for the service side, and the whole process of encoding request, sending to server, decoding response for the client side. Which means we have to gather the data from different threads and merge them together.
