### ISSUE TITLE
How to set ReferenceBean with ip, port, interface, group, and payload

### ISSUE THREAD

**Issue by 11huangxing** [apache/dubbo#11805]
I used to use version 2.7.14. Because of the serialization problem, I need to upgrade to version 3.1.7. But I don't know how to get the ReferenceBean through ip, port, interface, group, and payload in version 3.1.7; Here is my previous code:

ReferenceBean<T> referenceBean = new ReferenceBean<>();
            referenceBean.setApplicationContext(applicationContext);
            referenceBean.setInterface(serviceClass);
            if (timeout != null)
            {
                referenceBean.setTimeout(timeout);
            }

            if (StringUtils.isNotBlank(group))
            {
                referenceBean.setGroup(group);
            }
            if (StringUtils.isNotBlank(ip) && port > 0)
            {
                referenceBean.setUrl("dubbo://" + ip + ":" + port);
            }
            ProtocolConfig protocolConfig = getBean(ProtocolConfig.class);
            if (protocolConfig.getPayload() != null)
            {
                Map<String, String> refParams = referenceBean.getParameters();
                if (null == refParams)
                {
                    refParams = new HashMap<>();
                }

                refParams.put(Constants.PAYLOAD_KEY, protocolConfig.getPayload().toString());
                log.debug("magic set reference config parameters: {}", refParams);
                referenceBean.setParameters(refParams);

**Comment by MieAh** [comment]
You can create a ReferenceBean by chaining through ReferenceBeanBuilder, which can meet your needs of taking me with you.
