### ISSUE TITLE
Dubbo3+springboot(or spring) needs to support "consumer+application-level"service discovery,Please give CONSUL a way to survive

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#11818]
dubbo 3 is not friendly to the support of consul .

(1) Non-application-level registration with consul, unable to support application-level registration, error: Value is too long (limit: 512 characters) '). This error is a problem of consul.

(2) Application-level registration with consul. but the latest version of dubbo-spi-extensions [dubbo-spi-extensions](https://github.com/apache/dubbo-spi-extensions)  does not implement application-level registration

Please give CONSUL a way to survive

**Comment by AlbumenJ** [comment]
Duplicate with https://github.com/apache/dubbo/issues/11817. Track in https://github.com/apache/dubbo/issues/11817.
