### ISSUE TITLE
@DubboReference(version="*")功能是否与官网描述一致？

### ISSUE THREAD

**Issue by guipengfei** [apache/dubbo#11826]
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/service/multi-versions/ 根据官网的描述：
---------------------------------------------------------------------------------------
老版本服务提供者配置
<dubbo:service interface="com.foo.BarService" version="1.0.0" />

新版本服务提供者配置
<dubbo:service interface="com.foo.BarService" version="2.0.0" />

消费者如果不需要区分版本，可以按照以下的方式配置
<dubbo:reference id="barService" interface="com.foo.BarService" version="*" />
--------------------------------------------------------------------------------------------------

测试代码：
消费者
@DubboReference(group="dubbo", version="*", check = false)
    private HelloService helloService;

2个服务提供者
@DubboService(group="dubbo", version="v1.0.0")
public class HelloServiceImpl implements HelloService {
 ...
}

@DubboService(group="dubbo", version="v2.0.0")
public class HelloServiceImplV2 implements HelloService {
 ...
}

**控制台日志：**
org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service com.shiguang.platform.provider.common.HelloService. No provider available for the service dubbo/com.shiguang.platform.provider.common.HelloService:* from registry 127.0.0.1:8848 on the consumer 192.168.0.107 using the dubbo version 3.0.8. Please check if the providers have been started and registered.

dubbo 3.0.8 + Nacos 2.1.0 + SpringBoot 2.6.4
无论是@DubboReference注解方式还是泛化调用都试了，都是No provider错误，请问不区分版本调用功能是否已支持，还是我的demo使用问题？

**Comment by MieAh** [comment]
我在我这边dubbo3.0.8+nacos2.1.2+springboot2.6.4是没有问题的，你应该检查一下你的服务是否已经注册上注册中心了，建议在你的配置上面加一下dubbo.scan.base-package。

**Comment by guipengfei** [comment]
> 我在我这边dubbo3.0.8+nacos2.1.2+springboot2.6.4是没有问题的，你应该检查一下你的服务是否已经注册上注册中心了，建议在你的配置上面加一下dubbo.scan.base-package。

项目某些代码可能影响到了这块功能，请问对于version=*的处理，源码在哪个类呢

**Comment by MieAh** [comment]
在AbstractRegistry#noifty中调用了UrlUtils#isMatch，在如下进行处理
![image](https://user-images.githubusercontent.com/100568933/225361544-57edbb8d-eaba-44b6-b860-22ffb09c5707.png)
