### ISSUE TITLE
JValidator应该如何配置才能自定义ValidationProvider呢

### ISSUE THREAD

**Issue by lanicc** [apache/dubbo#11828]
https://github.com/apache/dubbo/blob/eeab34eb6780a332ead4d48c9b9932e07effd3e0/dubbo-filter/dubbo-filter-validation/src/main/java/org/apache/dubbo/validation/support/jvalidation/JValidator.java?_pjax=%23js-repo-pjax-container#L91
```
    public JValidator(URL url) {
        this.clazz = ReflectUtils.forName(url.getServiceInterface());
        String jvalidation = url.getParameter("jvalidation");
        ValidatorFactory factory;
        if (jvalidation != null && jvalidation.length() > 0) {
            factory = Validation.byProvider((Class) ReflectUtils.forName(jvalidation)).configure().buildValidatorFactory();
        } else {
            factory = Validation.buildDefaultValidatorFactory();
        }
        this.validator = factory.getValidator();
        this.methodClassMap = new ConcurrentHashMap<>();
    }
```
看这个参数是从url中取的

**Comment by liuruinl** [comment]
刚好之前遇到。
1, 自己实现Validator; 
2, 加入dubbo SPI扩展;
3  配置provider/consumer.validation=

**Comment by lanicc** [comment]
> 刚好之前遇到。 1, 自己实现Validator; 2, 加入dubbo SPI扩展; 3 配置provider/consumer.validation=

我不想自己去通过SPI拓展，
看上面这段代码，JValidator里面是可以从url中取参数，然后实现自定义的ValidatorFactory

**Comment by liuruinl** [comment]
> > 刚好之前遇到。 1, 自己实现Validator; 2, 加入dubbo SPI扩展; 3 配置provider/consumer.validation=
> 
> 我不想自己去通过SPI拓展， 看上面这段代码，JValidator里面是可以从url中取参数，然后实现自定义的ValidatorFactory，不明白的是这个参数怎么配置才行 ![image](https://user-images.githubusercontent.com/48583080/225807701-15a8d95e-40bf-427e-ba93-99ee9534bf30.png)

  provider:
    parameters:
      jvalidation: xxx
