### ISSUE TITLE
shade-plugin 配置中缺少关于 BuiltinServiceDetector 的配置，导致 jar 中相应的SPI配置文件中 丢失了其扩展实现配置。

### ISSUE THREAD

**Issue by daixiansuo** [apache/dubbo#11835]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.22
* Operating System version: mac/windows
* Java version: 1.8

### Steps to reproduce this issue

1. [maven 仓库](https://mvnrepository.com/artifact/org.apache.dubbo/dubbo/2.7.22)下载 2.7.22 版本 dubbo jar 包。
2. 反编译或者解压后，找到 /META-INF/dubbo/internal/org.apache.dubbo.rpc.model.BuiltinServiceDetector 配置文件。
3. 打开查看即可发现，当中只有两个SPI扩展实现类的配置，如下图所示：
4. 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/41660452/225246081-1e61dddd-36c0-44d6-8282-f7f241213d9f.png">

5. 打开源码，查找BuiltinServiceDetector类，即可发现该类有四个扩展实现，具体如下图所示：
<img width="1888" alt="image" src="https://user-images.githubusercontent.com/41660452/225244745-62d21413-5b65-45bf-b256-78bbd149055d.png">

**Comment by daixiansuo** [comment]
关于这个问题，我已经提交了一个[PR](https://github.com/apache/dubbo/pull/11836)

**Comment by AlbumenJ** [comment]
Please check if the issue still exist in 3.1. 2.7.x is only for security fix now.

**Comment by daixiansuo** [comment]
已经确认，3.1.x 分支没有这个问题。那这个issue关闭吧。
