### ISSUE TITLE
dubbo3.0.12 xml配置方式，多注册中心，address地址紊乱的问题

### ISSUE THREAD

**Issue by MrZbb** [apache/dubbo#11849]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
![image](https://user-images.githubusercontent.com/31841743/225493560-16fce006-86ee-40e3-b914-7492766f72cc.png)
如图dubbo版本是3.0.12，我在xml文件中定义了2个注册中心，zk这个设置的default为true，nacos的设置不为true,启动应用打印configManager加载的注册中心信息，可以发现nacos这个address莫名其妙被替换成zk的地址了

**Comment by KamToHung** [comment]
Do you use 'System.setProperty("dubbo.registry.address", "zookeeper://127.0.0.1:2181");' or another Configuration?
