### ISSUE TITLE
容器环境注册端口和绑定端口不一致问题，2.7.x版本未修复

### ISSUE THREAD

**Issue by jojocookx** [apache/dubbo#11870]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

原始问题链接： https://github.com/apache/dubbo/issues/9156

问题说明：  
此bug在v3 已被修复，pull链接：https://github.com/apache/dubbo/pull/9298 

希望在2.7.x里也能得到修复，Thanks♪(･ω･)ﾉ

**Comment by AlbumenJ** [comment]
由于目前 Dubbo 版本太多了（2.7.x, 3.0.x, 3.1.x, 3.2.x, ...），因此 2.7.x 和 3.0.x 版本目前只能仅保证安全维护（在最近一两周也将宣布 EOL 了）。

**Comment by jojocookx** [comment]
了解。
