### ISSUE TITLE
自定义ValidationFilter拦截异常不能捕获ConstraintViolationException

### ISSUE THREAD

**Issue by 936968629** [apache/dubbo#11878]
我自定义了一个校验的拦截器，不能捕获ConstraintViolationException，只能捕获ValidationException，但是message是没有格式化的String数据，看源码如下：
`
public void validate(String methodName, Class<?>[] parameterTypes, Object[] arguments) throws Exception {
        try {
            List<Class<?>> groups = new ArrayList<>();
            Class<?> methodClass = methodClass(methodName);
            if (methodClass != null) {
                groups.add(methodClass);
            }
            Set<ConstraintViolation<?>> violations = new HashSet<>();
            Method method = clazz.getMethod(methodName, parameterTypes);
            Class<?>[] methodClasses;
            if (method.isAnnotationPresent(MethodValidated.class)){
                methodClasses = method.getAnnotation(MethodValidated.class).value();
                groups.addAll(Arrays.asList(methodClasses));
            }
            // add into default group
            groups.add(0, Default.class);
            groups.add(1, clazz);

            // convert list to array
            Class<?>[] classgroups = groups.toArray(new Class[groups.size()]);

            Object parameterBean = getMethodParameterBean(clazz, method, arguments);
            if (parameterBean != null) {
                violations.addAll(validator.validate(parameterBean, classgroups ));
            }

            for (Object arg : arguments) {
                validate(violations, arg, classgroups);
            }

            if (!violations.isEmpty()) {
                logger.error("Failed to validate service: " + clazz.getName() + ", method: " + methodName + ", cause: " + violations);
                throw new ConstraintViolationException("Failed to validate service: " + clazz.getName() + ", method: " + methodName + ", cause: " + violations, violations);
            }
        } catch (ValidationException e) {
            // only use exception's message to avoid potential serialization issue
            throw new ValidationException(e.getMessage());
        }
    }
`
发现ConstraintViolationException被转换成ValidationException了，我如果取具体的错误内容应该怎么操作呢

**Comment by liuruinl** [comment]
我是在filter里用正则直接匹配的，因为注释里面写着 "only use exception's message to avoid potential serialization issue", 怕引入风险就没重写了。

**Comment by 936968629** [comment]
> 我是在filter里用正则直接匹配的，因为注释里面写着 "only use exception's message to avoid potential serialization issue", 怕引入风险就没重写了。

有代码吗？我参考下

**Comment by mytang0** [comment]
我觉得这个简化操作可以去掉，所以我提了一个 PR

**Comment by lwj-java** [comment]
+1

**Comment by lwj-java** [comment]
https://github.com/apache/dubbo/issues/10415
