### ISSUE TITLE
Dubbo3.2 序列化bug

### ISSUE THREAD

**Issue by sniper-xx** [apache/dubbo#11910]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0-beta5 , beta6
* Operating System version:  Docker Linux
* Java version:  Jdk17

### Steps to reproduce this issue

1.  provider返回函数执行结果为Map<String, Object>
2. consumer端能接收返回结果，并且类型同样为Map<String,Object>

目前问题：
  1、如果Map中的value为String，并且字符串简单无'-'，结果正常；
  2、如果Map的value为String，字符有‘-’，如： bb65c1ea-a151-4bfe-9058-a254960a65dc，则将value转换为 byte[]类型，并且在consumer端还无法通过 new String(byte[])进行还原。

provider数据：
 
![image](https://user-images.githubusercontent.com/70681/227440887-4c3dfc01-8fa5-4082-b6d2-e426ac535db8.png)

consumer所接收到的数据：
 
![image](https://user-images.githubusercontent.com/70681/227441002-da9d6960-018e-48a8-8df7-4f5f98f196ce.png)

请问，这种问题该如何解决？ 是因为bug所致，还是配置问题？

**Comment by AlbumenJ** [comment]
我这边测试是正常的，可以提供一个可以复现的demo嘛

**Comment by wxbty** [comment]
我看日期也被转了格式，正常hessian应该不会，是不是有什么自定义格式转换的filter

**Comment by sniper-xx** [comment]
> 我这边测试是正常的，可以提供一个可以复现的demo嘛

 目前已经修改为直接返回JSON String，我今天再测试一下，看是否能复现？
