### ISSUE TITLE
bug/When we use the new features of Idea2022.3 Maven importing, it causes unresolved issues

### ISSUE THREAD

**Issue by PhoenixBackendon** [apache/dubbo#11926]
Some programmers, like me, downloaded the 2022.3 version of Idea in pursuit of Idea's new features and UI. However, the new features imported by Maven in the 2022.3 version of idea cause all packages under org.apache.dubbo to fail to resolve. And I have encountered the same problem many times in daily communication programmers. At present, it is solved by unchecking this new feature, and duplicate MVN clean installs cannot solve the problem. I would like to use this issue to remind programmers who are also experiencing this problem.

一些程序员，像我一样，下载了 Idea 的 2022.3 版本，以追求 Idea 的新功能和新 UI。但是 2022.3 版 idea 中 Maven 导入的新功能会导致 org.apache.dubbo 下的所有包都无法解析。而我在日常沟通中多次遇到相同问题的同学。目前都是通过取消勾选这个新特性来解决，重复的mvn clean install无法解决问题。在此用这个issue来提醒同样遇到这个问题的同学。
![image](https://user-images.githubusercontent.com/100568933/227727507-d222b3f4-e84f-4a7f-853a-dad3a2a66713.png)

**Comment by walterhoson** [comment]
it works, thx
