### ISSUE TITLE
fail to gracefully shutdown java dubbo app

### ISSUE THREAD

**Issue by szhengli** [apache/dubbo#11946]
To whom it may concern:

According to  the link, https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/others/graceful-shutdown/,  adjusting  wait parameter,   can ensure the jar app to wait until the running tasks  complete normally, after receiving the TERM (sent by the command of kill PID ).    The reality is IT IS NOT WORKING as expected.     Even I increase the wait value to VERY VERY large, the running tasks still  FAIL  to  complete normally.   This bug has been verified on the version of 3.2.0-beta.4,  and should apply to other dubbo 3 version, even dubbo 2.      pls help, many thanks

**Comment by AlbumenJ** [comment]
What's the actual behavior?

**Comment by szhengli** [comment]
false
