### ISSUE TITLE
3.2.0-beta.6消费者端启动报错

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#11942]
环境：
jdk17，springboot3.0.5，dubbo3.2.0-beta.6
目的：
想要完全应用级的服务注册和发现微服务，不需要维护元数据
服务提供者配置：application.properties
dubbo.registry.address=nacos://localhost:8848?namespace=develop
dubbo.application.metadataServiceProtocol=tri
dubbo.application.register-mode=instance
dubbo.protocol.port=-1
dubbo.protocol.name=tri
dubbo.protocol.serialization=fastjson2
dubbo.registry.useAsMetadataCenter=false
dubbo.application.qosEnable=false

消费者配置：application.properties
dubbo.registry.address=nacos://localhost:8848?namespace=develop
dubbo.application.metadataServiceProtocol=tri
dubbo.registry.register-mode=instance
dubbo.protocol.port=-1
dubbo.protocol.name=tri
dubbo.application.service-discovery.migration=FORCE_APPLICATION
dubbo.registry.useAsMetadataCenter=false
dubbo.registry.useAsConfigCenter=false
dubbo.application.qosEnable=false

结果：
服务提供者启动成功，但是有error日志，消费者启动失败，截图分别如下：
![1679969608359](https://user-images.githubusercontent.com/33255974/228109746-cc8713b1-0527-46f5-b9d2-fab32718ea29.png)
![1679969709179](https://user-images.githubusercontent.com/33255974/228109767-efc7bdd8-caff-42cd-a601-768264952f7b.png)

**Comment by AlbumenJ** [comment]
这就是连接超时了，看一下网络是不是通的

**Comment by AlbumenJ** [comment]
> > 这就是连接超时了，看一下网络是不是通的
> > 我是本机起的服务提供者和服务消费者，网络是没问题的，我把dubbo版本降到3.1.8，springboot降到2.5.4，jdk降到11其他配置都没变就不报错了

3.2.0-beta.6 + springboot 2.5.4 呢

**Comment by zzps** [comment]
> > > 这就是连接超时了，看一下网络是不是通的
> > > 我是本机起的服务提供者和服务消费者，网络是没问题的，我把dubbo版本降到3.1.8，springboot降到2.5.4，jdk降到11其他配置都没变就不报错了
> 
> 3.2.0-beta.6 + springboot 2.5.4 呢
 3.2.0-beta.6 + springboot 2.5.4 + jdk11 还是一样的报错的

**Comment by EarthChen** [comment]
能提供个 demo 吗

**Comment by EarthChen** [comment]
看 error日志是应用级注册失败

**Comment by zzps** [comment]
> 能提供个 demo 吗
项目代码我放这里了
https://gitee.com/755157298/dubbo-tree

**Comment by EarthChen** [comment]
> > 能提供个 demo 吗
> > 项目代码我放这里了
> > https://gitee.com/755157298/dubbo-tree

没有权限。。。

**Comment by zzps** [comment]
> > > 能提供个 demo 吗
> > > 项目代码我放这里了
> > > https://gitee.com/755157298/dubbo-tree
> 
> 没有权限。。。
不好意思，我现在开放了，你试试

**Comment by zzps** [comment]
> > > 能提供个 demo 吗
> > > 项目代码我放这里了
> > > https://gitee.com/755157298/dubbo-tree
> 
> 没有权限。。。

我放的demo能重现问题吗

**Comment by EarthChen** [comment]
> > > > 能提供个 demo 吗
> > > > 项目代码我放这里了
> > > > https://gitee.com/755157298/dubbo-tree
> > 
> > 
> > 没有权限。。。
> 
> 我放的demo能重现问题吗

已经 fix

**Comment by zzps** [comment]
> > > > > 能提供个 demo 吗
> > > > > 项目代码我放这里了
> > > > > https://gitee.com/755157298/dubbo-tree
> > > 
> > > 
> > > 没有权限。。。
> > 
> > 
> > 我放的demo能重现问题吗
> 
> 已经 fix

好的多谢，大概下一个版本什么时候发布

**Comment by AlbumenJ** [comment]
@EarthChen 帮忙把这个 case 在集成测试那边加一个验证

**Comment by AlbumenJ** [comment]
> > > > > > 能提供个 demo 吗
> > > > > > 项目代码我放这里了
> > > > > > https://gitee.com/755157298/dubbo-tree
> > > > 
> > > > 
> > > > 没有权限。。。
> > > 
> > > 
> > > 我放的demo能重现问题吗
> > 
> > 
> > 已经 fix
> 
> 好的多谢，大概下一个版本什么时候发布

下周发布
