### ISSUE TITLE
[Observable Tasks] Display indicator data in KEY, VALUE format

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#11954]
[Observable Tasks] Display indicator data in KEY, VALUE format
In order to facilitate the user's viewing of indicator data without installing Prometheus, refer to the four word command of Zookeepr to implement the output of indicator data KEY and VALUE structures

【可观测任务】KEY，VALUE格式展示指标数据

在没有安装普罗米修斯的情况下为了方便用户查看指标数据，参考zookeepr的四字命令实现指标数据KEY，VALUE结构输出
<img width="747" alt="image" src="https://user-images.githubusercontent.com/81170548/228262952-c795d894-ca85-46bd-91c0-dd5c9ca8af17.png">

**Comment by AlbumenJ** [comment]
agree

**Comment by hujun-w-2** [comment]
我尝试一下
