### ISSUE TITLE
metrics need to merge old and new implementations

### ISSUE THREAD

**Issue by wxbty** [apache/dubbo#11953]
Before 3.2, if the config did not set the Prometheus protocol, MetricsFilter would be used to count requests and thread pools, and the observation format would be customized. After 3.2, a relatively complete observability has been provided, whether the new and old implementations should be integrated. My idea is to migrate the old protocol spi extension to the new implementation, while providing a simple custom metrics format output (if it is a custom protocol).

    /**
     * @deprecated After metrics config is refactored.
     * This filter should no longer use and will be deleted in the future.
     */
    @Deprecated
    public class MetricsFilter implements Filter, ExtensionAccessorAware, ScopeModelAware {
    }

**Comment by songxiaosheng** [comment]
yes，some metrics config such as Metrics port need be remove too.

**Comment by wcy666103** [comment]
I'm willing to do that ，May you give me more detail for this task？

**Comment by wxbty** [comment]
> Prometheus protocol

It turns out that the MetricsFilter of the Dubbo-Monitor module includes the data export function of the custom Protocol. It has been removed in version 3.3. You can refer to the implementation of dubbo-2.7.23 branch to migrate this function to the metrics module of 3.3. The background of this feature is that some users want to be compatible with private indicator formats instead of using the existing general Prometheus protocol.

**Comment by Shivam1-123** [comment]
I am intrested in working on it. May you give me details?

**Comment by linhexu** [comment]
give me some simple task，please

**Comment by wxbty** [comment]
This task is quite old, so it is temporarily closed and may be reopened in the future
