### ISSUE TITLE
dubbo框架中DubboClientReconnectTimer一直重连已经下线的提供方

### ISSUE THREAD

**Issue by nannanfighting** [apache/dubbo#11976]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.9
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. 一个提供方一个消费方运行。可以手动改一下DubboClientReconnectTimer定时任务的间隔时间，便于观察报错
2. 下掉提供方
3. 手动更新下注册中心的configure或者route目录，触发一次refresh，便可稳定复现。

经过初步分析，是因为cachedInvokerUrls这个缓存在提供方全部下线后没有清理，后续configure或者route目录如果有推送会再次触发重新建连，并开启定时任务一直处理，无法销毁。

![代码](https://user-images.githubusercontent.com/19549643/229062033-9a770781-6cd6-4eab-8928-942e402dfd5e.jpeg)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

configure或者route目录的刷新不应该再次触发去连接已经下线的定时任务。
### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!

![Uploading 报错.jpg…]()

**Comment by AlbumenJ** [comment]
2.5.9 已经不维护很多年了，请升级到最新的 3.1.8 版本

**Comment by nannanfighting** [comment]
我看了下，社区在2.7.1之后（包括最新的3.1.9），就不再启动这个定时任务了；但是cachedInvokerUrls的缓存在提供方全下线后还是不清理的，这个设计是有什么考虑吗？另外去掉这个定时任务是为了解决我上面提到的问题吗？ @AlbumenJ

**Comment by AlbumenJ** [comment]
> cachedInvokerUrls的缓存在提供方全下线后还是不清理的

这个会异步清理

> 去掉这个定时任务

定时任务应该还是有的，是 org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask

**Comment by iwangjie** [comment]
Maybe close, push-out protection can solve this problem? dubbo.application.enable-empty-protection=false
