### ISSUE TITLE
ConcurrentHashMapUtils无法解决jdk8的循环bug

### ISSUE THREAD

**Issue by looly** [apache/dubbo#11986]
### Environment

* Dubbo version: 3.2, 3.3
* Operating System version: Windows11
* Java version: jdk8

### Steps to reproduce this issue

[ConcurrentHashMapUtils](https://github.com/apache/dubbo/blob/3.2/dubbo-common/src/main/java/org/apache/dubbo/common/utils/ConcurrentHashMapUtils.java) 中提供的`computeIfAbsent`方法没有解决jdk8的循环问题，复现代码如下：

```java
final ConcurrentHashMap<String,Integer> map=new ConcurrentHashMap<>();
// // map.computeIfAbsent("AaAa", key->map.computeIfAbsent("BBBB",key2->42));
ConcurrentHashMapUtils.computeIfAbsent(map, "AaAa", key->map.computeIfAbsent("BBBB",key2->42));
```

[Hutool](https://github.com/dromara/hutool) 中的解决方案是：

```java
V value = map.get(key);
if (null == value) {
	map.putIfAbsent(key, mappingFunction.apply(key));
	value = map.get(key);
}
return value;
```

**Comment by looly** [comment]
但是有issue反馈说这种方式获取的value有可能为null，我不确定这种写法是否存在问题。

issue中提出的替代方案是：

```java
V value = map.get(key);
if (null == value) {
	value = mappingFunction.apply(key);
	final V res = map.putIfAbsent(key, mappingFunction.apply(key));
	if(null != res){
		// issues#I6RVMY
		// 如果旧值存在，说明其他线程已经赋值成功，putIfAbsent没有执行，返回旧值
		return res;
	}
	// 如果旧值不存在，说明赋值成功，返回当前值
}
return value;
```

**Comment by AlbumenJ** [comment]
ConcurrentHashMapUtils 这个主要是解决性能的问题

**Comment by AlbumenJ** [comment]
死锁这个问题可以提个 PR 改下

**Comment by looly** [comment]
看到原来的issue和PR：

https://github.com/apache/dubbo/pull/11326

https://github.com/apache/dubbo/issues/11294

这个PR是为了解决 https://bugs.openjdk.org/browse/JDK-8161372 这个问题，但这本质上是个死锁问题。

@AlbumenJ 没有提PR就是因为两个解决方案我都不能保证逻辑是正确的，需要review验证，这也是困扰我的地方。

稍后提个PR。

**Comment by looly** [comment]
PR see: https://github.com/apache/dubbo/issues/11986
