### ISSUE TITLE
优雅停机：无法保证Dubbo 的 ShutdownHook 会在 SpringBoot 的 ShutdownHook 之前执行，导致spring bean先于dubbo销毁

### ISSUE THREAD

**Issue by QuentinYo** [apache/dubbo#11990]
3.0.7 版本

![image](https://user-images.githubusercontent.com/7312478/229679742-6c9a0da0-8999-4e0e-b813-628fddc3d36f.png)
上图：spring启动的时候注册了DubboShutdownHook到Jvm的Shutdown hook

![image](https://user-images.githubusercontent.com/7312478/229680063-ed64e2a5-5422-426f-8d8f-6e1ba081c513.png)
上图：spring的关闭事件也会处理dubbo的停机逻辑

由于dubbo的停机逻辑只会执行一遍，DubboShutdownHook执行过后，spring关闭事件所在的线程就不会再执行，也不会被阻塞，直接跳过，执行后续的bean销毁动作。如下：
![image](https://user-images.githubusercontent.com/7312478/229682915-39798b22-45b9-405f-927c-57f509260ffa.png)

这应该会导致spring bean先于dubbo销毁吧

**Comment by AlbumenJ** [comment]
最新的 Dubbo 3.2 版本已经做了 Spring 状态的对齐
