### ISSUE TITLE
消费者和提供者在同一个服务时负载均衡失效

### ISSUE THREAD

**Issue by HeZhanfeng** [apache/dubbo#11991]
消费者和提供者在同一个服务，请求总是打在本地的提供者上，跟源码发现我注册中心有多个提供者，但AbstractClusterInvoker.doSelect()方法的invokers参数值永远只有一个导致请求总是在本地的提供者上

**Comment by MieAh** [comment]
跟如下特性相关[本地调用](https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/advanced-features-and-usage/service/local-call/)
每个服务默认都会在本地暴露。在引用服务的时候，默认优先引用本地服务。如果希望引用远程服务可以使用一下配置（推荐Scope）强制引用远程服务。

**Comment by HeZhanfeng** [comment]
官方文档-配置项手册里没有找到这个配置，
@DubboReference(scope = "remote", loadbalance = LoadbalanceRules.ROUND_ROBIN) 这样可以解决我的问题
感谢！
