### ISSUE TITLE
Dubbo多spring容器导致部分dubbo provider无法注册

### ISSUE THREAD

**Issue by a408665321** [apache/dubbo#12024]
版本： dubbo 2.7.9
问题： 应用A中 包含@DubboService的provider类（暂时命名未ServiceA），通过springboot初始化。 应用A应用了模块B。模块B的某个类的init方法中，通过ClassPathXmlApplicationContext 加载了其他的dubbo reference 和provider。
目前由于初始化顺序的问题，模块B中的dubbo privider被通过单例对象DubboBootstrap先注册到注册中心，org.apache.dubbo.config.bootstrap.DubboBootstrap#started被设置未true。
当应用A中的dubbo provider需要被初始化时，org.apache.dubbo.config.bootstrap.DubboBootstrap#started已经为true了，跳过了初始化，导致ServcieA无法被注册到注册中心。
下图分别是第一次与第二次进入DubboBootstram的栈信息
![image](https://user-images.githubusercontent.com/12618834/230292231-b8fa757a-1b57-4551-839c-199ea7098d8a.png)
![image](https://user-images.githubusercontent.com/12618834/230292658-911fadbb-0a85-4427-b71e-a8d5752e39fb.png)

**Comment by AlbumenJ** [comment]
Please upgrade to 3.1.9

**Comment by a408665321** [comment]
> Please upgrade to 3.1.9

2.7.x能否支持，目前全链路没有统一升级Dubbo3的计划。如果2.7.x能够修复再好不过了。

**Comment by AlbumenJ** [comment]
> > Please upgrade to 3.1.9
> 
> 2.7.x能否支持，目前全链路没有统一升级Dubbo3的计划。如果2.7.x能够修复再好不过了。

2.7.x 即将在近几天宣布生命周期的 EOL，届时安全维护周期也将结束。目前最新版本是即将发布的 3.2.0 版本，我们建议所有用户都升级到最新版本。
