### ISSUE TITLE
dubbo升级到3.0之后默认多级注册，影响gateway的路由如何解决

### ISSUE THREAD

**Issue by xiaohaoni** [apache/dubbo#12037]
我们dubbo升级到了3.0，然后默认是多级注册的，这样微服务（nacos
）就会注册上dubbo的端口，网关我们使用的是gateway，路由的时候负载均衡就会路由到dubbo的端口上，正常的接口就会调不了，请问这个怎么解决

**Comment by xiaohaoni** [comment]
@chickenlj  
之前是2.7.15版本的，dubbo的端口是包到spring 的端口里面的，
![ba814cebae2ec7699f17602b20fcf34](https://user-images.githubusercontent.com/59159779/230711632-f3b85ba6-2d4a-490d-9c49-6ed0934fc1ce.png)
升级到3.0后，dubbo就会单独注册一个端口
![14b2173c5e7fbb0188ce809521adb74](https://user-images.githubusercontent.com/59159779/230711677-dfd50799-4d1f-4ebe-ab33-6101ff3b60e1.png)
导致在gateway路由负载均衡的时候有机率会路由到dubbo的端口里去，路由到spring 的端口是正常调用接口的，但是路由到dubbo的端口就会接口调用失败

**Comment by falcon-jin** [comment]
![image](https://user-images.githubusercontent.com/48880836/230722181-8d7a3808-a1f4-4730-8535-2b1b0cabf4e3.png)我这样指定单独的命名空间是可以的 看起来也舒服 不影响其它服务

**Comment by kaizen84** [comment]
可以使用命名空间进行隔离

**Comment by xiaohaoni** [comment]
感谢，这样设置确实可以
