### ISSUE TITLE
dubbo由3.1.4升级3.1.6报错dubbo注册失败

### ISSUE THREAD

**Issue by F9nc** [apache/dubbo#12032]
这是依赖库的版本信息
<curator.recipes.version>4.2.0</curator.recipes.version>
<zookeeper.version>3.4.10</zookeeper.version>
[dubbo-.3.1.6.txt](https://github.com/apache/dubbo/files/11177448/dubbo-.3.1.6.txt)
有没有大佬帮忙看下什么问题导致，万分感谢！！！

**Comment by AlbumenJ** [comment]
这个应该是 ZK 注册时序的问题，register 的时候为空

**Comment by AlbumenJ** [comment]
Related with https://github.com/apache/dubbo/pull/12033

**Comment by F9nc** [comment]
> 这个应该是 ZK 注册时序的问题，register 的时候为空
您好，您这有具体的解决方案吗 我重启了zk集群，再启动服务没有效果

**Comment by AlbumenJ** [comment]
> > 这个应该是 ZK 注册时序的问题，register 的时候为空
> > 您好，您这有具体的解决方案吗 我重启了zk集群，再启动服务没有效果

需要等 3.1 打包，更新高版本

**Comment by F9nc** [comment]
> > > 这个应该是ZK注册时间的问题，注册的时候为空
> > > 您好，您有具体的解决方案吗 我重新启动了zk群，再启动服务没有效果
> 
> 需要等 3.1 打包，更新高版本

升级到dubbo 3.1.7版本吗 还是别的？

**Comment by AlbumenJ** [comment]
> > > > 这个应该是ZK注册时间的问题，注册的时候为空
> > > > 您好，您有具体的解决方案吗 我重新启动了zk群，再启动服务没有效果
> > 
> > 
> > 需要等 3.1 打包，更新高版本
> 
> 升级到dubbo 3.1.7版本吗 还是别的？

3.1.10 版本，目前还没发布

**Comment by F9nc** [comment]
> > > > > 这个应该是ZK注册时间的问题，注册的时候为空
> > > > > 您好，您有具体的解决方案吗 我重新启动了zk群，再启动服务没有效果
> > > 
> > > 
> > > 需要等 3.1 打包，更新高版本
> > 
> > 
> > 升级到dubbo 3.1.7版本吗 还是别的？
> 
> 3.1.10 版本，目前还没发布
您好，3.1.10版本大概啥时候发布您知道不？
