### ISSUE TITLE
Triple协议中的HeaderFilter将无法生效

### ISSUE THREAD

**Issue by finefuture** [apache/dubbo#12035]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.8
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue
1. 只有是ApplicationModule模式才能设置filtersLoader SPI加载器
![image](https://user-images.githubusercontent.com/18413695/230619073-3458a2a3-d01b-4821-97ef-330dec75cb66.png)
2. 未设置加载器时headerFilter列表默认设置成空
![image](https://user-images.githubusercontent.com/18413695/230619283-a044ffdc-3187-4c58-98ae-ec6261b19a68.png)
3. 在初始化NettyPortUnificationServer时却使用的FrameworkModel，因此无法加载HeaderFilter
![image](https://user-images.githubusercontent.com/18413695/230619345-d9d17e25-ff44-46e0-974d-05b4ea589380.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

让HeaderFilter变成Framework级别 或者 默认加载filterLoader

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
@EarthChen PTAL

**Comment by EarthChen** [comment]
https://github.com/apache/dubbo/pull/12058
