### ISSUE TITLE
【扩展点】针对DataFrame的DataFilter

### ISSUE THREAD

**Issue by finefuture** [apache/dubbo#12042]
## Describe the feature

Triple协议中提供了针对HeaderFrame的过滤器HeaderFilter，希望再添加一个扩展点：针对DataFrame的DataFilter

**Comment by AlbumenJ** [comment]
@EarthChen PTAL

**Comment by EarthChen** [comment]
你是想实现什么样的需求呢？

**Comment by finefuture** [comment]
@EarthChen 在序列化之前放入上下文，序列化时使用

**Comment by EarthChen** [comment]
> @EarthChen 在序列化之前放入上下文，序列化时使用

没有理解到，你想实现什么功能，当前序列化也是框架是做的，获取到了上下文能够做什么呢？

**Comment by finefuture** [comment]
@EarthChen 我们扩展了Thrift序列化，想拿到调用的方法名
