### ISSUE TITLE
消费者IP和端口注册

### ISSUE THREAD

**Issue by pmupkin** [apache/dubbo#12056]
## Ask your question here
Dubbo消费者的IP和端口号会注册到注册中心吗？如果会的话，是在什么时机注册的呢

**Comment by AlbumenJ** [comment]
因为要降低注册中心的负载，3.x 版本应该默认不会注册了

**Comment by pmupkin** [comment]
如果需要在3.x版本中注册端口和IP，Dubbo提供了可选的注册方式吗？

**Comment by AlbumenJ** [comment]
你用的是什么注册中心

**Comment by pmupkin** [comment]
> 你用的是什么注册中心

zookeeper，我想在Dubbo3.x中实现消费者IP和端口的注册

**Comment by MieAh** [comment]
可以通过dubbo.consumer.registry配置项向指定注册中心注册。当在多个注册中心时使用，值为<dubbo:registry>的id属性，多个注册中心ID用逗号分隔，如果不想将该服务注册到任何registry，可以不进行配置

**Comment by pmupkin** [comment]
> 可以通过dubbo.consumer.registry配置项向指定注册中心注册。当在多个注册中心时使用，值为dubbo:registry的id属性，多个注册中心ID用逗号分隔，如果不想将该服务注册到任何registry，可以不进行配置

你确定这样可以？

**Comment by MieAh** [comment]
刚试验过是可以的
