### ISSUE TITLE
provider端的序列化协议强校验策略在停机时可能导致部分请求失败

### ISSUE THREAD

**Issue by QuentinYo** [apache/dubbo#12064]
背景：
dubbo版本：3.0.12
dubbo.shutdownHook.listenIgnore：设置为true，禁用dubbo的停机机制，使用spring停机事件

问题描述：
使用spring停机事件停机时，会执行下图的过程：
（org.apache.dubbo.config.ServiceConfig#unexport）
![image](https://user-images.githubusercontent.com/7312478/231090972-21d11e9c-a1a9-4b47-b5db-60c670aeb466.png)
![image](https://user-images.githubusercontent.com/7312478/231091146-b88017af-4cb7-43cf-851e-ec50e4edee55.png)
![image](https://user-images.githubusercontent.com/7312478/231091225-2664a708-3b1d-4bc7-b328-ceceb107133d.png)
服务对应的urls被从providerUrlsWithoutGroup中移除了

而停机初期，provider处理残余任务时，会有如下过程：
org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation#decode(org.apache.dubbo.remoting.Channel, java.io.InputStream) （红框中为序列化协议强校验策略）
![image](https://user-images.githubusercontent.com/7312478/231089882-6d2738b7-88d7-4f88-95b9-966012c3a242.png)

org.apache.dubbo.remoting.transport.CodecSupport#checkSerialization
![image](https://user-images.githubusercontent.com/7312478/231092601-78e4520b-feef-4c57-a140-f02f5c1c5ea1.png)
校验序列化协议时需要通过serviceRepository.lookupRegisteredProviderUrlsWithoutGroup获取服务对应的urls（实际最终是从providerUrlsWithoutGroup中读取），但是这时providerUrlsWithoutGroup中的数据已经被删掉了，导致校验失败，该请求无法被继续执行。

通过List<URL> urls = serviceRepository.lookupRegisteredProviderUrlsWithoutGroup(keyWithoutGroup(path, version)); 获取到的urls为空时是否可以直接返回，而不是抛出异常？

**Comment by AlbumenJ** [comment]
这个停机的是时序需要调整下，优先反注册，然后等待到没请求关闭协议

**Comment by QuentinYo** [comment]
目前大的顺序确实是先进行反注册，再等待到没请求关闭协议。但是在细节上有点问题，反注册时删除了请求处理过程中需要的数据（上面提到的providerUrlsWithoutGroup中的数据），导致校验序列化协议时报错

**Comment by QuentinYo** [comment]
有啥解决办法吗

**Comment by QuentinYo** [comment]
![image](https://user-images.githubusercontent.com/7312478/231934405-ccdfb70a-611e-4fbd-a3a0-76b48b3e92be.png)

帮忙看看这个思路可行吗 @AlbumenJ
