### ISSUE TITLE
gRPC 调用tri 不通

### ISSUE THREAD

**Issue by shicuining** [apache/dubbo#12107]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
注册中心nacos
a服务，使用triple协议提供服务
b服务，使用dubbo gRPC调用a服务

无法调通，提示：
Failed to check the status of the service foo.DubboFooServiceGrpc$IFooService. No provider available for the service foo.DubboFooServiceGrpc$IFooService from the url consumer://10.168.12.10...

**Comment by aamingaa** [comment]
看看注册中心服务是否注册上了

**Comment by shicuining** [comment]
> 看看注册中心服务是否注册上了

注册中心有，而且用tri调用a，也是可以通的

**Comment by AlbumenJ** [comment]
@EarthChen PTAL 这个应该是 grpc 注册格式的差异

**Comment by EarthChen** [comment]
3.1 版本 grpc 的服务注册的 interface 不太对，直接升级到3.2把
