### ISSUE TITLE
can't be found when the subscribed service [name : xxx], and then try to initialize it The metadata of Dubbo service [name : xxx] is about to be initialized

### ISSUE THREAD

**Issue by sunxiatao** [apache/dubbo#12127]
### Environment

* Dubbo version: 2.7.3
* Operating System version: Centos7
* Java version: 1.8

### Steps to reproduce this issue

Occasional occurrence in production environment and can be automatically restored in a short period of time, Here is the error log

Tried 1 times of providers [172.0.10.18.29912] (1/1) from the registry 172.0.10.18:9090 on the consumer 172.18.0.1 using the dubbo version 2.7.3 

java.nio.channels.ClosedChannelException

**Comment by AlbumenJ** [comment]
Please try upgrade to the latest version

**Comment by sunxiatao** [comment]
I will try upgrading the version, thank you
