### ISSUE TITLE
3.2.0 是要怎样打开 /metrics 接口？

### ISSUE THREAD

**Issue by wuzhuoquan** [apache/dubbo#12141]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
从 dubbo-samples 里面看到说 3.2.0 的 beta 版本开始可以搞
```
https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-metrics-prometheus
```
里面写的配置方法是
![image](https://user-images.githubusercontent.com/49891988/233246871-eb09f29a-d005-4cf9-bcee-3a8acaae2a88.png)

可是从这个仓库里面看到的配置是
![image](https://user-images.githubusercontent.com/49891988/233247049-960e4b78-dc5d-4db0-ad77-4dfc5fc37261.png)

自己试了一下，不写 qos-port 压根不就生效，而且访问 /metrics 的接口和 metrics-port 却没有任何关系
但是从 dubbo 官网的文档上说是要在 dubbo.metrics 里面去配置，看源码也看到有 metricsPort 之类的参数解析

所以我想问一下，正确打开 /metrics 的姿势到底是怎样的？

**Comment by songxiaosheng** [comment]
the documents and cases in your screenshot are not the latest. You can check the latest documents and cases，as follow:
https://cn.dubbo.apache.org/zh-cn/overview/tasks/observability/metrics-start/

**Comment by wuzhuoquan** [comment]
> the documents and cases in your screenshot are not the latest. You can check the latest documents and cases，as follow: https://cn.dubbo.apache.org/zh-cn/overview/tasks/observability/metrics-start/

OK
