### ISSUE TITLE
Dubbo 版本不一致导致调用有问题

### ISSUE THREAD

**Issue by Zhuqi95** [apache/dubbo#12148]
调用方版本：2.7.3   提供方版本：3.0.21
ZK上也能看到这个 Service, 但是调用方调用就会出提示：No provider available from registry zookeeper. 。并且没有指定 接口版本。

**Comment by hujun-w-2** [comment]
> 2.7这种低版本调用3.x高版本问题很多，尤其是用应用级发现的情况，两个版本元数据差别很大，2.7的使用还存在部分选择cloud-dubbo的干扰，个人感觉还是按服务依赖关系从下到上逐步进行3版本的切换

你们走过迁移流程吗,从下到上不会有兼容问题?或者高版本调低版本存在兼容问题吗

**Comment by liudaac** [comment]
我这边之前升级到3版本是先依次做的镜像集群，然后从流量入口逐步进行环境切换。只是这种方式在切换过程中有点资源浪费。另外，高版本调用低版本，如果低版本没用cloud-dubbo，直接以原生的接口级协议进行注册的话是兼容的。但如果用了cloud-dubbo基本没戏了，需要拷贝出新版的服务镜像。

**Comment by Zhuqi95** [comment]
> 提供方register mode看看是什么，改为all或者interface，zk目录截图看看

已经解决了谢谢，一个很小的问题，提供者消费者不在同一个分组。但是员工反馈了一个新问题，在nacos配置文件中配置了消费者的分组和提供者的分组居然不生效。非要在@DubboReference（group ="sit"） 来进行指定。
