### ISSUE TITLE
升级了dubbo3.1.8后的问题，就有问题，之前2.7.22没有

### ISSUE THREAD

**Issue by yqxqls** [apache/dubbo#12166]
本地消费端启动服务后，没法获取到元数据，之前2.7.22没有此问题，就是升级dubo3.1.8后就出现此问题
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://182.11.112.31:21883/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&corethreads=2&dubbo=2.0.2&group=tisson-open-rpc-service&heartbeat=60000&port=20883&protocol=dubbo&release=3.1.8&retries=0&side=provider&threadpool=cached&threads=100&timeout=60000&version=1.0.0) failed to connect to server /182.11.112.31:21883 client-side timeout 3000ms (elapsed: 3003ms) from netty client 192.168.239.1 using dubbo version 3.1.8

182.11.112.31 是远端服务

**Comment by yqxqls** [comment]
请问这个问题如何解决，除了回退旧版本外

**Comment by baozi-2019** [comment]
我的改成从远端获取就崩了，再改回来也不好用😀

**Comment by songxiaosheng** [comment]
确认下这个ip 端口可以telent通么
182.11.112.31 21883

**Comment by yqxqls** [comment]
> 这个是获取元数据的RPC调用，确认下这个ip 端口可以telnet通么 182.11.112.31 21883

通

**Comment by liudaac** [comment]
消费端版本是3.x么？

**Comment by yqxqls** [comment]
> 提供者与消费者都是统一使用3.1.8的，不会搞个版本不一致

**Comment by songxiaosheng** [comment]
> > 提供者与消费者都是统一使用3.1.8的，不会搞个版本不一致

是否可以直接尝试debug看下
MetadataUtils 类型的 getRemoteMetadata 方法查看下RPC请求是否发送成功

**Comment by AlbumenJ** [comment]
> 182.11.112.31

是在 192.168.239.1 这个机器 telnet 的吗，这个端口不是默认端口，另外这 IP 是公网 ip，需要检查 ACL
