### ISSUE TITLE
Dubbo 3.2.0版本REST是部分是重写了吗？有很多功能都不能用了

### ISSUE THREAD

**Issue by tell1014** [apache/dubbo#12165]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
使用3.2.0版本后，从参考[rest协议文档](https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/protocol/rest/)配置，有很多功能都不能正常使用了。
1、REST Server只支持netty，配置成其他最后实例化都是使用NettyHttpRestServer，看了源码好像确实是只支持netty。
2、不能设置response stutus。
3、不能使用JAX-RS标准的@Context annotation值得获取的上下文信息了。
4、不能使用JAX-RS标准的ExceptionMapper。
5、不能输出HTTP日志。
6、dubbo-rpc-rest包依赖了JAX-RS的实现RESTEasy，但不能处理javax.ws.rs.core.Response。

在3.1.9版本就没有出现上述几个问题，使用相同的xml配置信息在3.2.0版本只有上述问题，不是说升级到3.2.0是完全平滑的吗？
不知道是我配置有问题还是不再支持了。
配置信息：
`<dubbo:application name="test-demo-provider" logger="slf4j"/>

    <dubbo:registry address="nacos://nacos:nacos@127.0.0.1:8848"/>

    <dubbo:protocol name="rest" server="tomcat" port="8080"/>

    <bean id="userService" class="com.mydomain.test.service.impl.UserServiceImpl"/>

    <dubbo:service interface="com.mydomain.test.service.UserService" ref="userService"/>`

**Comment by songxiaosheng** [comment]
@suncairong163

**Comment by suncairong163** [comment]
3.2重写了server，仅使用netty,作为server,,原本的servlet web容器实现全部去除了。jaxrs目前只是依赖它的rest 注解，response,这块不再依赖，后面会做适配处理，exceptionMapper,duubo内部自己实现了，

**Comment by suncairong163** [comment]
https://github.com/apache/dubbo/pull/12183 这个是最新新rest使用demo可以参考一下

**Comment by tell1014** [comment]
> #12183 这个是最新新rest使用demo可以参考一下

thanks

**Comment by uzong** [comment]
3.2.0 后面的版本，还能继续使用 servlet 相关的API吗，比如 HttpServletRequest 接口吗； 上层应用大量引用了HttpServletRequest， 升级后不能再继续使用了，如何能兼容，需要改代码吗

**Comment by AlbumenJ** [comment]
> 3.2.0 后面的版本，还能继续使用 servlet 相关的API吗，比如 HttpServletRequest 接口吗； 上层应用大量引用了HttpServletRequest， 升级后不能再继续使用了，如何能兼容，需要改代码吗

可以尝试使用下 3.3
