### ISSUE TITLE
ReferenceCountManagedChannel shoule add reference count when create

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo#12164]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.23-SNAPSHOT
* Operating System version: Windows7
* Java version: jdk8

### Steps to reproduce this issue

1. tow dubbo service in one instance
3. client refre two service 
4. when pull out one service the other client throw exception

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
```

预期另外一个接口是没有报错的。
对比两个相似的类 他们初始化的逻辑不对

`org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient#ReferenceCountExchangeClient`

```java
  public ReferenceCountExchangeClient(ExchangeClient client) {
        this.client = client;
        referenceCount.incrementAndGet();
        this.url = client.getUrl();
    }
```

`org.apache.dubbo.rpc.protocol.grpc.ReferenceCountManagedChannel ` 初始化的时候少算了一个referenceCount

```java
public ReferenceCountManagedChannel(ManagedChannel delegated) {
        this.grpcChannel = delegated;
    }
```

**Comment by AlbumenJ** [comment]
Please try use triple in Dubbo 3.2.

**Comment by AlbumenJ** [comment]
2.7.x is no longer supported now.

**Comment by vio-lin** [comment]
> Please try use triple in Dubbo 3.2.

Some applications prefer to use old version. Work for update is in progress.
As the code is in old version, prefer to fix.

**Comment by vio-lin** [comment]
> From the perspective of the community, there are currently many versions maintained, which have a relatively large impact on the development of the community itself. So currently we don't consider fixing it on the 2.7.x version.

可以的。我们初衷也是后面升级时，尽量找对旧应用使用问题少的版本。
