### ISSUE TITLE
mesh模式mock无效问题

### ISSUE THREAD

**Issue by owen200008** [apache/dubbo#12173]
版本3.1.8
version：3.1.8

跟了下代码 staticDirectory 没有 routeChain，最终没有选用mock的invoke
mesh mode use staticDirectory and the routeChain is null， so mock fail

跟云大沟通有一个独立的建链逻辑，后面我再看看，先建一个issue

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/blob/2ca687ff30c9b92aec4b5fe5d94068ec59b36a0e/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java#L336

**Comment by owen200008** [comment]
验证3.2.2版本已经修复 mesh模式下可以mock
