### ISSUE TITLE
Dubbo version: 3.2.0 使用分组聚合，group配置* , 注册nacos报错，NacosException：dataId invalid

### ISSUE THREAD

**Issue by tb8367085** [apache/dubbo#12198]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* nacos 服务端版本2.2.2
* Operating System version: windows11
* Java version: 17/19 都报错

### Steps to reproduce this issue

1. 只要使用group配置*必报错，必现的，因为*是nacos的节点关键字*和，等服务都会报错。

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/18565542/235046435-df693f6b-1ee7-4069-a8a3-47f83a95d720.png)

```
Just put your stack trace here!
```

**Comment by goto456** [comment]
是不是跟你的Nacos版本有关？我之前遇到过，nacos1.x不支持*，升级到nacos 2.x就可以了

**Comment by AlbumenJ** [comment]
注册中心地址配的 group * 还是 ServiceConfig 还是 ReferenceConfig

**Comment by tb8367085** [comment]
ReferenceConfig配置成* 或者,   @AlbumenJ 
@DubboReference(group = "*", merger = "true")
这样配置的，我用了xml或者泛化，都报错。

**Comment by tb8367085** [comment]
> 是不是跟你的Nacos版本有关？我之前遇到过，nacos1.x不支持*，升级到nacos 2.x就可以了

我也是nacos2.2.2,都是最新版本的。你是用的分组聚合调用吗？@DubboReference(group = "*", merger = "true")

**Comment by AlbumenJ** [comment]
> > 是不是跟你的Nacos版本有关？我之前遇到过，nacos1.x不支持*，升级到nacos 2.x就可以了
> 
> 我也是nacos2.2.2,都是最新版本的。你是用的分组聚合调用吗？@DubboReference(group = "*", merger = "true")

试了下，应该是订阅规则的时候报错的，影响的是治理的规则，对于服务调用本身没有影响的

**Comment by flybh521** [comment]
这个问题解决了吗

**Comment by AlbumenJ** [comment]
> 这个问题解决了吗

Dubbo support wildcard group now.

**Comment by flybh521** [comment]
> > 这个问题解决了吗
> 
> Dubbo support wildcard group now.

但是现在我使用  dubbo 最新稳定版本  以及  nacos的最新稳定版本   还是会报这个问题    使用 group 配置*     分组聚合  一直报这个错

**Comment by AlbumenJ** [comment]
> > > 这个问题解决了吗
> > 
> > 
> > Dubbo support wildcard group now.
> 
> 但是现在我使用 dubbo 最新稳定版本 以及 nacos的最新稳定版本 还是会报这个问题 使用 group 配置* 分组聚合 一直报这个错

Which version

**Comment by flybh521** [comment]
> > > > 这个问题解决了吗
> > > 
> > > 
> > > Dubbo support wildcard group now.
> > 
> > 
> > 但是现在我使用 dubbo 最新稳定版本 以及 nacos的最新稳定版本 还是会报这个问题 使用 group 配置* 分组聚合 一直报这个错
> 
> Which version

dubbo 3.2.10     nacos  2.3.0    

另外  我还想问一下    分组聚合时  如果自己即使消费方也是提供方   也是无法使用分组聚合的  这个怎么解决

**Comment by AlbumenJ** [comment]
> > > > > 这个问题解决了吗
> > > > 
> > > > 
> > > > Dubbo support wildcard group now.
> > > 
> > > 
> > > 但是现在我使用 dubbo 最新稳定版本 以及 nacos的最新稳定版本 还是会报这个问题 使用 group 配置* 分组聚合 一直报这个错
> > 
> > 
> > Which version
> 
> dubbo 3.2.10 nacos 2.3.0
> 
> 另外 我还想问一下 分组聚合时 如果自己即使消费方也是提供方 也是无法使用分组聚合的 这个怎么解决

Can you please submit a demo?

**Comment by changeAtLater** [comment]
> > > > > > 这个问题解决了吗
> > > > > 
> > > > > 
> > > > > Dubbo support wildcard group now.
> > > > 
> > > > 
> > > > 但是现在我使用 dubbo 最新稳定版本 以及 nacos的最新稳定版本 还是会报这个问题 使用 group 配置* 分组聚合 一直报这个错
> > > 
> > > 
> > > Which version
> > 
> > 
> > dubbo 3.2.10 nacos 2.3.0
> > 另外 我还想问一下 分组聚合时 如果自己即使消费方也是提供方 也是无法使用分组聚合的 这个怎么解决
> 
> Can you please submit a demo?

https://github.com/alibaba/nacos/issues/5466
