### ISSUE TITLE
alibaba dubbo切换为apache dubbo，ReferenceConfig对象setApplication方法及setRegistry方法异常

### ISSUE THREAD

**Issue by jxs-nv** [apache/dubbo#12208]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.x ; 3.2.x
* Operating System version: ubuntu 22.04
* Java version: 1.8;17

### Steps to reproduce this issue

1. 使用alibaba dubbo时的代码
   com.alibaba.dubbo.config.ReferenceConfig<ISksService> referenceConfig = new com.alibaba.dubbo.config.ReferenceConfig<>();
        String appName = "sks-client";
        referenceConfig.setApplication(new com.alibaba.dubbo.config.ApplicationConfig(appName));
        referenceConfig.setInterface(ISksService.class);
        String registryConfigList = "nacos://nacos.dev.com:8848";
        com.alibaba.dubbo.config.RegistryConfig dubboRegistry = new com.alibaba.dubbo.config.RegistryConfig();
        dubboRegistry.setAddress(registryConfigList);
        referenceConfig.setRegistry(dubboRegistry);
        ISksService service = referenceConfig.get();
        Result<String> encoder = service.encode("test");
        System.out.println(encoder.getValue());
2. 切换为apache dubbo 依赖后 在referenceConfig.setApplication(new com.alibaba.dubbo.config.ApplicationConfig(appName)); 和 referenceConfig.setRegistry(dubboRegistry); 两处存在异常 java.lang.NoSuchMethodError: com.alibaba.dubbo.config.ReferenceConfig.setApplication(Lcom/alibaba/dubbo/config/ApplicationConfig;)V 及 java.lang.NoSuchMethodError: com.alibaba.dubbo.config.ReferenceConfig.setRegistry(Lcom/alibaba/dubbo/config/RegistryConfig;)V
3.

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
java.lang.NoSuchMethodError: com.alibaba.dubbo.config.ReferenceConfig.setApplication(Lcom/alibaba/dubbo/config/ApplicationConfig;)V
 java.lang.NoSuchMethodError: com.alibaba.dubbo.config.ReferenceConfig.setRegistry(Lcom/alibaba/dubbo/config/RegistryConfig;)V
```

**Comment by November22** [comment]
可以看下是不是包冲突，同时存在alibaba dubbo和apache dubbo包

**Comment by AlbumenJ** [comment]
应该是目前 ReferenceConfig 没有提供 alibaba 包的重载实现，导致如果 jar 包不重新编译会找不到老签名的方法

**Comment by jxs-nv** [comment]
> 应该是目前 ReferenceConfig 没有提供 alibaba 包的重载实现，导致如果 jar 包不重新编译会找不到老签名的方法
嗯,是的,通过fork,修改了源码重写了两个方法, 打包制品的确解决了此问题,但为以后的项目升级带来了不便. 虽然我们的社区在考虑了由alibaba dubbo 用户切换apache dubbo 中提供了一些支持,但也局限于使用了注解式的方式,有一些场景需要动态的编程式生成代理类, 就会出现此问题.

**Comment by AlbumenJ** [comment]
> > 应该是目前 ReferenceConfig 没有提供 alibaba 包的重载实现，导致如果 jar 包不重新编译会找不到老签名的方法
> > 嗯,是的,通过fork,修改了源码重载了两个方法, 打包制品的确解决了此问题,但为以后的项目升级带来了不便. 虽然我们的社区在考虑了由alibaba dubbo 用户切换apache dubbo 中提供了一些支持,但也局限于使用了注解式的方式,有一些场景需要动态的编程式生成代理类, 就会出现此问题.

这个需要修复下的，我来改下

**Comment by AlbumenJ** [comment]
> > > 应该是目前 ReferenceConfig 没有提供 alibaba 包的重载实现，导致如果 jar 包不重新编译会找不到老签名的方法
> > > 嗯,是的,通过fork,修改了源码重载了两个方法, 打包制品的确解决了此问题,但为以后的项目升级带来了不便. 虽然我们的社区在考虑了由alibaba dubbo 用户切换apache dubbo 中提供了一些支持,但也局限于使用了注解式的方式,有一些场景需要动态的编程式生成代理类, 就会出现此问题.
> 
> 这个需要修复下的，我来改下

https://github.com/apache/dubbo/pull/12220 已经提交，3.2.1 版本会修复

**Comment by AlbumenJ** [comment]
Integration test cases: https://github.com/apache/dubbo-samples/pull/834
