### ISSUE TITLE
dubbo2.7.x升级到3.2.x后 应用跑两三天后就发生内存泄漏

### ISSUE THREAD

**Issue by braveCS** [apache/dubbo#12202]
dubbo2.7.x升级到3.2.x后 应用跑两三天后就发生内存泄漏。

在 org.apache.dubbo.remoting.transport.netty4.NettyChannel的劝酒的私有的静态成员变量CHANNEL_MAP里的。
里面55多万个元素，1.1G的大小。 

到后面AbstractInvoker.waitForResultIfSync(底层是threadlessExecutor.waitAndDrain)会卡住，比如： 某个服务正常调用不到100ms就返回了，应用跑两三天后就开始 那个正常的服务调用开始20%的概率出现一次两三秒的卡顿。

**Comment by AlbumenJ** [comment]
> 在 org.apache.dubbo.remoting.transport.netty4.NettyChannel的劝酒的私有的静态成员变量CHANNEL_MAP里的。
> 里面55多万个元素，1.1G的大小。

这个是有服务频繁上下线嘛，对应的内存 dump 可以私发下我吗

> 到后面AbstractInvoker.waitForResultIfSync(底层是threadlessExecutor.waitAndDrain)会卡住，比如： 某个服务正常调用不到100ms就返回了，应用跑两三天后就开始 那个正常的服务调用开始20%的概率出现一次两三秒的卡顿。

这个是所有的请求都慢还是部分请求而已
