### ISSUE TITLE
服务端重试次数配置不生效

### ISSUE THREAD

**Issue by mywsp** [apache/dubbo#12225]
您好，
  我仅在服务端全局配置重试次数，但重试仍默认为3次，由于消费者端未配置重试次数默认为0次即不进行重试，而且会按照服务端配置的重试次数进行重试，但实际情况并非如此。
  如下图消费者端远程调用服务端时所的方法及配置参数信息，但未看到retries重试次数等配置，因此导致默认3次重试。经过发现nacos会把全部属性信息设置到EXTRA_PARAMS里面，但只要调用的时候就是拿到下图的EXTRA_PARAMS属性。

目前解决方法：
  只能在消费者端设置重试次数

![屏幕截图 2023-05-03 222028](https://user-images.githubusercontent.com/40262608/235964643-00b6aaf9-4cd7-40c0-abe5-1ca84521a379.png)

**Comment by songxiaosheng** [comment]
默认配置消费者也是重试3次不是重试0次文档如下：
https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/config/properties/#consumer

**Comment by AlbumenJ** [comment]
> 您好， 我仅在服务端全局配置重试次数，但重试仍默认为3次，由于消费者端未配置重试次数默认为0次即不进行重试，而且会按照服务端配置的重试次数进行重试，但实际情况并非如此。 如下图消费者端远程调用服务端时所的方法及配置参数信息，但未看到retries重试次数等配置，因此导致默认3次重试。经过发现nacos会把全部属性信息设置到EXTRA_PARAMS里面，但只要调用的时候就是拿到下图的EXTRA_PARAMS属性。
> 
> 目前解决方法： 只能在消费者端设置重试次数
> 
> ![屏幕截图 2023-05-03 222028](https://user-images.githubusercontent.com/40262608/235964643-00b6aaf9-4cd7-40c0-abe5-1ca84521a379.png)

不同服务重试次数无法生效的 3.1 版本已经修复了，可以升级下版本看看

**Comment by mywsp** [comment]
多谢
