### ISSUE TITLE
有PrometheusConfig类则自动开启metrics不够友好，11955问题的提交里可以换一种方式实现？

### ISSUE THREAD

**Issue by braveCS** [apache/dubbo#12222]
提交的代码里，是直接判断是否有io.micrometer.prometheus.PrometheusConfig这个类，有的话就去读取配置。 这样直接判断不够友好：工程里有这个类，但是不希望开启metrics时 就犯难了，要关闭不好关。

**Comment by AlbumenJ** [comment]
> 工程里有这个类，但是不希望开启metrics时 就犯难了，要关闭不好关。

是什么原因不开启 metrics 呢

**Comment by braveCS** [comment]
配套的资源还不够完善，我想想其他办法。
