### ISSUE TITLE
[metrics]在Dubbo3.2的provider里该如何暴露业务自定义指标

### ISSUE THREAD

**Issue by kevin-cao** [apache/dubbo#12227]
**Environment**

- Dubbo version: 3.2.0
- SpringBoot version: 2.7.11
- Prometheus version: 2.37.7
- JDK version: 8

Provider已接入dubbo-metrics，现需要通过micrometer api上报业务相关的自定义指标到Prometheus。由于provider中没有暴露用于业务指标的HTTPServer Endpoint，无法直接使用io.micrometer.core.instrument.Metrics。如何暴露业务指标的Endpoint，目前想到两种办法：
1. 复用Dubbo自身框架指标的Endpoin，也就是QOS http server
2. 创建一个新的业务指标HTTPSever对象，暴露新端口

比较倾向1(避免创建httpserver)。不过1的话该如何复用qos端口，自定义指标直接上报到/metrics路径？还是扩展BaseCommand使用新路径上报？官方有没有推荐做法或这方面的支持？

**Comment by wxbty** [comment]
使用自带org.apache.dubbo.metrics.collector.MetricsCollector的spi，可以加载第三方收集器，参考RegistryMetricsCollector实现

**Comment by songxiaosheng** [comment]
@kevin-cao 需要dubbo提供micrometer的注册表么还是提供一套指标采集标准

**Comment by kevin-cao** [comment]
> @kevin-cao 需要dubbo提供micrometer的注册表么还是提供一套指标采集标准

@songxiaosheng 需要dubbo提供micrometer的注册表，可以直接调用MeterRegistry.counter()、MeterRegistry.gauge()等方法，并且能够让prometheus通过qos端口抓取到

**Comment by songxiaosheng** [comment]
> > @kevin-cao 需要dubbo提供micrometer的注册表么还是提供一套指标采集标准
> 
> @songxiaosheng 需要dubbo提供micrometer的注册表，可以直接调用MeterRegistry.counter()、MeterRegistry.gauge()等方法，并且能够让prometheus通过qos端口抓取到

最近看下提供给你

**Comment by songxiaosheng** [comment]
![e0728ad358dc4af983cd1f954cf1d8f2.png](https://user-images.githubusercontent.com/81170548/236799277-30e6e3df-b932-4ef0-adbb-1f8185d5aa89.png)

这个版本你先用这个方法，后面我们文档出一下如何让用户使用的文档

**Comment by kevin-cao** [comment]
好的👍 试了下可以了
