### ISSUE TITLE
Dubbo3.1.9 线程池大小默认100（非文档的200） 且自定义threads不生效

### ISSUE THREAD

**Issue by HelloToGithub** [apache/dubbo#12230]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Dubbo：3.1.9

Dubbo3.1.9 线程池大小默认100（非文档的200） 且自定义threads不生效
启动服务 通过调试发现

首先执行了AbstractServer构造函数 此时参数为配置的threads参数
![image](https://user-images.githubusercontent.com/15622677/236124448-af45aef5-c479-42c8-9361-28aa7e189020.png)
![image](https://user-images.githubusercontent.com/15622677/236124530-b8084bd5-27b2-446d-89e5-2f11c1e616d3.png)

DefaultExecutorRepository.updateThreadpool
![image](https://user-images.githubusercontent.com/15622677/236125288-40c319e8-d165-4ccf-884a-9e060d1f8786.png)

然后执行了ConfigurableMetadataServiceExporter类的buildServiceConfig和export方法 又被覆盖为100
![image](https://user-images.githubusercontent.com/15622677/236132471-a0a8ff1a-5158-45b9-8de0-9756ea00c040.png)
DefaultExecutorRepository.updateThreadpool
![image](https://user-images.githubusercontent.com/15622677/236132306-9bf2ab5d-dd46-471d-9fcc-ac52ded078f6.png)
![image](https://user-images.githubusercontent.com/15622677/236125394-cb2d3c9e-46cb-46a7-add4-adb1d318d12f.png)

**Comment by ilaotan** [comment]
3.1.10都pre-release俩周了 还没发出来

**Comment by AlbumenJ** [comment]
> 3.1.10都pre-release俩周了 还没发出来

今天晚些会发布
