### ISSUE TITLE
负载均衡-roundrobin ， dubbo集群中的机器（2台）偶然同时收到了同一个请求，是负载有问题吗？接口 retries="0"

### ISSUE THREAD

**Issue by BestBigLiu** [apache/dubbo#12269]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by songxiaosheng** [comment]
权重轮训只是一种负载均衡策略不会导致多个机器被调用到，多个机器同时收到的有可能出现了RPC请求失败触发了容错机制，或者客户端自身的重试。

**Comment by BestBigLiu** [comment]
> 权重轮训只是一种负载均衡策略不会导致多个机器被调用到，多个机器同时收到的有可能出现了RPC请求失败触发了容错机制，或者客户端自身的重试。接口retries=“0” 看下dubbo控制台或者注册中心上面配置是否生效

我看看去

**Comment by ms20hj** [comment]
loadbalance: roundrobin
    cluster: failfast
    retries: 0
@DubboService(cluster = "failfast")
@DubboReference(cluster = "failfast")

**Comment by ms20hj** [comment]
loadbalance: roundrobin
cluster: failfast
retries: 0
@DubboService(cluster = "failfast")

@DubboReference(cluster = "failfast")

我在这种配置下，故意在程序上打个断点，让provider超时，释放断点后consumer又会调用一次provider，导致数据重复新增
