### ISSUE TITLE
A服务调用B服务大部分的接口都是正常的，其中有一个接口用着用着就报错：Please check if the providers have been started and registered.

### ISSUE THREAD

**Issue by chaozai0304** [apache/dubbo#12301]

**Comment by songxiaosheng** [comment]
对应接口的提供者找不到时候会报这个错误，看下为新接口，状态是否正常

**Comment by chaozai0304** [comment]
> 对应接口的提供者找不到时候会报这个错误，看下为新接口，状态是否正常

请问这个org/apache/dubbo/common/Version在dubbo和dubbo-common中出现了冲突，有没有可能导致这个问题
具体报错： ERROR  Version -  [DUBBO] Duplicate class org/apache/dubbo/common/Version.class in 2 jar

**Comment by AlbumenJ** [comment]
> ERROR Version - [DUBBO] Duplicate class org/apache/dubbo/common/Version.class in 2 jar

这个报错不影响使用，在 3.2.0 版本中已经优化
