### ISSUE TITLE
Apache Dubbo 开源之夏 2023 正式启动，贡献社区赢取 12000 奖金！

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#12300]
欢迎在校同学们参与Apache Dubbo开源之夏，社区导师手把手让**你的代码被社会广泛复用，来赚取最高12000奖金，可**推荐入职/实习你心意公司，**又拿钱又成长又有价值**，你还等什么呢？报名马上截止，快来参与Apache Dubbo开源之夏。

## OSPP 开源之夏是什么？

开源之夏是由“开源软件供应链点亮计划”发起并长期支持的一项暑期开源活动，旨在鼓励**在校学生**积极参与开源软件的开发维护，促进优秀开源软件社区的蓬勃发展，培养和发掘更多优秀的开发者。
活动联合国内外各大开源社区，针对重要开源软件的开发与维护提供项目任务，并面向全球高校学生开放报名。
学生可在本活动中自主选择感兴趣的项目任务进行申请，并在中选后获得该开源项目资深维护者（社区导师）亲自指导的机会，完成项目并贡献给社区后，参与学生还将获得开源之夏**活动奖金**和**结项证书**。

# Apache Dubbo 项目简介

Apache Dubbo 是国内最具影响力的开源软件项目之一，由阿里巴巴贡献开源，是支撑阿里双十一百万集群、万亿次服务调用的核心框架，目前 Dubbo 已捐献给享誉世界的 Apache 软件基金会 (ASF)。

## 参与Apache Dubbo开源之夏条件

- 本活动面向年满 18 周岁在校学生。
- 暑期即将毕业的学生，只要在申请时学生证处在有效期内，就可以提交申请。
- 海外学生可提供录取通知书、学生卡、在读证明等文件用于证明学生身份。

## 参与Apache Dubbo开源之夏，你能获得什么？

1. **【你的代码被社会广泛复用】**你的代码可能会运行在上万家企业核心业务逻辑中，帮助企业解决问题。
2. **【赢得最高12000奖金】**奖金总额根据项目难度分为进阶 12000 元、基础 8000 元（注：奖金数额为税前人民币金额）
3. **【社区核心人员辅导快速成长】**只要你报名被选中，每个题目的导师会精心手把手教你融入社区，帮助你完成题目的设计以及最终的落地。
4. **【推荐入职/实习】**在本次编程之夏项目中表现优秀同学，可推荐入职/实习 你心意的公司工作。
5. **【额外获得社区礼包】**所有参与本次编程之夏项目的同学，均可获得Apache Dubbo社区大礼包。

**百分百有奖品拿哦**，现在唯一的问题是时间不多了，赶紧上车报名，截止报名时间是6月4日，6个核心题目，快点来报名参与Apache Dubbo编程之夏吧。

## 课题&报名方式

点开Apache Dubbo开源之夏的[链接](https://summer-ospp.ac.cn/org/orgdetail/ab188e59-fab8-468f-bc89-bdc2bd8b5e64?lang=zh) 选择你喜欢的题目：

- [IDL 管理平台](https://summer-ospp.ac.cn/org/prodetail/23a7f0282?list=org&navpage=org)
- [API 管理平台](https://summer-ospp.ac.cn/org/prodetail/23a7f0286?list=org&navpage=org)
- [基于 Kubernetes 的集成测试体系建设](https://summer-ospp.ac.cn/org/prodetail/23a7f0284?list=org&navpage=org)
- [服务 JSON 序列化兼容性校验](https://summer-ospp.ac.cn/org/prodetail/23a7f0287?list=org&navpage=org)
- [将 Dubbo 工程结构重构为 Gradle 项目](https://summer-ospp.ac.cn/org/prodetail/23a7f0289?list=org&navpage=org)
- [自动化性能测试方案](https://summer-ospp.ac.cn/org/prodetail/23a7f0292?list=org&navpage=org)
- [移除对 jprotoc 的依赖](https://summer-ospp.ac.cn/org/prodetail/23a7f0294?list=org&navpage=org)
- [Node.js HTTP/2 协议实现](https://summer-ospp.ac.cn/org/prodetail/23a7f0520?list=org&navpage=org)
- [实现 Dubbo Rust 的路由模块](https://summer-ospp.ac.cn/org/prodetail/23a7f0553?list=org&navpage=org)

具体流程请参考 [学生指南](https://summer-ospp.ac.cn/help/student/)。

请注意找导师沟通截止流程时间，优先更导师沟通，能帮助你更好的了解题目。

为了方便大家报名，我们有以下咨询通道开放，如果对报名、题目、如何撰写 Proposal 有任何疑问，都可以前往咨询：

1. 扫码关注回复 "Apache Dubbo" 官网微信公众号，回复 “编程之夏” 加入微信沟通群

 
![apache-dubbo-wechat](https://github.com/apache/dubbo/assets/18097545/993664dc-ef08-4ced-b6f2-b02d0b0d78d8)

2. 钉钉群：22895027434（Dubbo 2023 编程之夏群），搜索并加入咨询问题
3. 发送邮件到 Apache Dubbo 邮件组：dev[@dubbo.apache.org ](/dubbo.apache.org ) 

# 参考资料

- Apache Dubbo Github 仓库：
   - [Java](http://github.com/apache/dubbo)
   - [Go](http://github.com/apache/dubbo-go)
   - [Node.js](http://github.com/apache/dubbo-js)
   - [Rust](http://github.com/apache/dubbo-rust)
   - [Admin](http://github.com/apache/dubbo-admin)
   - [更多生态](http://github.com/dubbo/)
- [Apache Dubbo 官网 ](https://dubbo.apache.org/)
- [开源之夏官网](https://summer-ospp.ac.cn/org/orgdetail/a7f6e2ad-4acc-47f8-9471-4e54b9a166a6?lang=zh)

为了让同学们更好地了解Apache Dubbo，我们还在观望提供了电子书供大家阅读学习。

- [Apache Dubbo 微服务开发从入门到精通](https://cn.dubbo.apache.org/zh-cn/contact/books/)
- [Apache Dubbo3 源码深度解析](https://cn.dubbo.apache.org/zh-cn/contact/books/)

同时如果同学们对其他领域项目感兴趣，也可以尝试申请，例如：

- 对于**微服务注册发现和配置管理**有兴趣的同学，可以尝试填报 [Nacos 开源之夏](https://summer-ospp.ac.cn/org/orgdetail/ab188e59-fab8-468f-bc89-bdc2bd8b5e64?lang=zh)；
- 对于**微服务分布式事务**有兴趣的同学，可以尝试填报[Seata](https://summer-ospp.ac.cn/org/orgdetail/064c15df-705c-483a-8fc8-02831370db14?lang=zh)开源之夏；
- 对于**微服务框架和RPC框架**有兴趣的同学，可以尝试填报[Spring Cloud Alibaba](https://summer-ospp.ac.cn/org/orgdetail/41d68399-ed48-4d6d-9d4d-3ff4128dc132?lang=zh) 和 [Dubbo](https://summer-ospp.ac.cn/org/orgdetail/a7f6e2ad-4acc-47f8-9471-4e54b9a166a6?lang=zh) 开源之夏；
- 对于**云原生网关**有兴趣的同学，可以尝试填报[Higress](https://higress.io/zh-cn/blog/ospp-2023) 开源之夏；
- 对于**分布式高可用防护**有兴趣的同学，可以尝试填报[Sentinel](https://summer-ospp.ac.cn/org/orgdetail/5e879522-bd90-4a8b-bf8b-b11aea48626b?lang=zh) 开源之夏；
- 对于**微服务治理**有兴趣的同学，可以尝试填报[OpenSergo](https://summer-ospp.ac.cn/org/orgdetail/aaff4eec-11b1-4375-997d-5eea8f51762b?lang=zh) 开源之夏。

**Comment by icankeep** [comment]
不是高校学生可以参加吗

**Comment by AlbumenJ** [comment]
> 不是高校学生可以参加吗

OSPP 活动需要学信网学生认证
