### ISSUE TITLE
Dubbo3 生成Triple协议代码时，.Dubbo3TripleGenerator不支持getSingleTemplateFileName的问题

### ISSUE THREAD

**Issue by zhangbiaoyg** [apache/dubbo#12317]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
目前正在尝试使用Dubbo 3.2.0版本，根据Protobuffer 的IDL文件生成Java源代码。

我的配置如下：
![16841400431489](https://github.com/apache/dubbo/assets/133645679/2fcd5019-5751-4043-8b5b-ba2945376ca4)

产生的问题如下：
![16841395939493](https://github.com/apache/dubbo/assets/133645679/89ca1876-b38c-4fee-a97f-f255bb2e2b0c)

我看Dubbo3TripleGenerator的源代码如下：
![image](https://github.com/apache/dubbo/assets/133645679/163b0d90-7404-4d62-98d5-ab2e4a63f814)

目前我该怎么做才能正确生成Java源代码？

**Comment by icodening** [comment]
@zhangbiaoyg 
proto文件中需要指定`option java_multiple_files = true;`

**Comment by zhangbiaoyg** [comment]
谢了，可以这个问题解决了。
不过我基于上面的那个pom 做mvn clean compile 的时候，会报下面的错误。
这个protoc-gen-triple-java是我们要先安装的吗？没找到相关的一些资料。。
![企业微信截图_16841538316447](https://github.com/apache/dubbo/assets/133645679/7208248d-70cc-4217-8da1-fe988254a8a9)

**Comment by icodening** [comment]
你去掉 `<pluginId>triple-java</pluginId>` 应该就好了

**Comment by zhangbiaoyg** [comment]
改成<pluginId>grpc-java</pluginId>可以了
