### ISSUE TITLE
Dubbo 3.2.0 broadcast + injvm not work as expected

### ISSUE THREAD

**Issue by CodePlayer** [apache/dubbo#12334]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0 / 3.2.1
* Operating System version: Windows 10
* Java version: OpenJDK 17.0.6

### Steps to reproduce this issue

```java
public interface RemoteCacheSyncService {

  void flushCache();

}

@DubboService
public class RemoteCacheSyncServiceImpl implements RemoteCacheSyncService {

  @Override
  public void flushCache() {
	  // some code			
  }

}
```

We have 3 microservices, referred to as `A`, `B`, and `C`.
Each service contains the above code.

But, just `C` has a `@DubboReference` to the interface only.

```java
@DubboReference(cluster = ClusterRules.BROADCAST)
RemoteCacheSyncService remoteCacheSyncService;
```

### Expected Behavior

Call **ALL** implementations in **ALL** microservices.

### Actual Behavior

However, since there is a service implementation of the interface in the **same application** ( `C` ),
Dubbo will use the `injvm` protocol. Only the service implementation located in `C` will be invoked.

Same issue with https://github.com/apache/dubbo/issues/6842 , however, it came back again.

**Comment by AlbumenJ** [comment]
@PhoenixBackendon PTAL

**Comment by PhoenixBackendon** [comment]
I see what you mean. The current solution is configured as forced remote in the settings, which should be able to solve it, or we can provide a rule to adapt to the requirements based on this broadcasting mechanism, and I will finish it later.

**Comment by CodePlayer** [comment]
> I see what you mean. The current solution is configured as forced remote in the settings, which should be able to solve it, or we can provide a rule to adapt to the requirements based on this broadcasting mechanism, and I will finish it later.

https://github.com/PhoenixBackendon/dubbo/blob/35da167f6a921f9c0c0799b807442f72d0fefaff/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/wrapper/ScopeClusterInvoker.java#L132
`logger.debug()` should consider use placeholder `{}` ?
