### ISSUE TITLE
请教一个provider复用ip导致的问题

### ISSUE THREAD

**Issue by ljwhx2002** [apache/dubbo#12338]
原本系统APP1 作为provider 有3个节点，ip1，ip2，ip3，提供了接口interface1的服务

consumer去调用interface1刚开始线上一直正常的，直到有一天因为是k8s部署 系统APP1 重启后 ip列表变成了 ip4 5 6，consumer调用也还是正常的，consumer一直没动过 ，过了几天有个一个系统APP2  部署 k8s复用了 ip1， 因为 APP2 并没有interface1的provider，导致consumer报错，提示：
Failed to invoke the method x in the service xxx. Tried 3 times of the providers [172.16.8.237:20880] (1/1) from the registry nacos-headless:8848 on the consumer 172.16.8.240 using the dubbo version 3.0.9. Last error is: Failed to invoke remote method: x, provider: DefaultServiceInstance{serviceName='x', host='172.16.8.237', port=20880, enabled=true, healthy=true, metadata={dubbo.metadata-service.url-params={"connections":"1","version":"1.0.0","dubbo":"2.0.2","release":"3.0.9","side":"provider","port":"20880","protocol":"dubbo"}, dubbo.endpoints=[{"port":20880,"protocol":"dubbo"}], dubbo.metadata.revision=56bbdfc8bf3cc092ab97a1eff5e8b8f9, dubbo.metadata.storage-type=local, timestamp=1683625542448}}, service{name='x',group='null',version='1.0.0',protocol='dubbo',params={side=provider, release=3.0.9, methods=x,x, deprecated=false, dubbo=2.0.2, interface=xx, service-name-mapping=true, version=1.0.0, generic=false, revision=0.1.15, application=x, background=false, dynamic=true, service.filter=dubboProviderFilter, anyhost=true},}, cause: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.io.IOException: Service x  with version 1.0.0 not found, invocation rejected.

最疑惑的问题是 Tried 3 times of the providers [172.16.8.237:20880] (1/1) ， app2复用了app1历史的ip为什么导致原本可用的provider变成1了 ，而且是这个错误的ip ，这个provider其实并不存在，它只是复用了 曾经服务过的app1的ip ，client端目前什么机制，看上去一定用了缓存，为什么这种错的情况 会把provider变成1了？ 

### Environment
nacos 2.0.2
* Dubbo version: 3.0.9
* Operating System version: xxx
* Java version: 17

**Comment by AlbumenJ** [comment]
应用级服务发现请升级到 3.2.1 版本再看是否还有问题

**Comment by zhoujinsy** [comment]
麻烦问一下是什么原因导致的呢, 我们也遇到了相同问题, dubbo版本是3.0.12, nacos版本是2.2.4, 查看了consumer端的推送日志, 接口级的和应用级的ip变更也都正常推送了
