### ISSUE TITLE
 rest service Path no found,

### ISSUE THREAD

**Issue by songlongkuan** [apache/dubbo#12330]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* Operating System version: Mac os 13
* Java version: openjdk 1.8

### Steps to reproduce this issue

1. 提供者定义接口
@Path("person")
public interface PersonService {

    @GET // #3
    @Path("{id: \\d+}")
    String getUser(@PathParam("id") Long id);

    @GET
    @Path("getPerson")
    String getPerson(@QueryParam("source") String source);
}

2.提供者实现类
@DubboService(interfaceClass = PersonService.class, protocol = {"rest", "dubbo"},version = "1.0.0",group = "dubbo-provider")
public class DubboPersonServiceImpl implements PersonService {

    @Override
    public String getUser(Long id) {
        return String.valueOf(id);
    }

    @Override
    public String getPerson(String source) {
        return source;
    }
}
3. 配置文件
dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    rest:
      name: rest
      port: 9001
    dubbo:
      name: dubbo
      port: 8001
  consumer:
    version: 1.0.0
    timeout: 10000
    retries: 0
    check: false
  provider:
    version: 1.0.0
    group: dubbo-provider
    validation: false
  application:
    name: dubbo-provider

4.. 发起curl请求

curl --location --request GET 'localhost:9001/person/getPerson' \
--header 'rest-service-version: 1.0.0' \
--header 'rest-service-group: dubbo-provider' \
--header 'version: 1.0.0' \
--header 'group: dubbo-provider' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'source=postman' \
--data-urlencode 'version=1.0.0'

响应结果是错误的：
rest service Path no found, current path info:PathMatcher{path='/person/getPerson', version='null', group='null', port=null, hasPathVariable=false, contextPath='null'}

他应该调用到getPerson接口的，但是一直调用不到

### Actual Behavior

If there is an exception, please attach the exception trace:

```
rest service Path no found, current path info:PathMatcher{path='/person/getPerson', version='null', group='null', port=null, hasPathVariable=false, contextPath='null'}
```

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

**Comment by suncairong163** [comment]
org.apache.dubbo.rpc.protocol.rest.constans.RestConstant#REST_HEADER_PREFIX  可以看一下这个字段的值吗， 最近把之前的
#rest#前缀改成了  rest-service-  
这个pr https://github.com/apache/dubbo/pull/12275

**Comment by songlongkuan** [comment]
这段代码已经删掉了，最后我把postman请求头groupId，version 都删掉反而好了，dubbo提供者也把groupId、version删掉
