### ISSUE TITLE
tirple服务启动的时候，报Http2FrameCodecBuilder的init找不到

### ISSUE THREAD

**Issue by zhangbiaoyg** [apache/dubbo#12331]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo 版本 3.2.0
我在启动triple 协议的服务时，一直报这个错，这个是啥原因呢？
![image](https://github.com/apache/dubbo/assets/133645679/917623fc-a3df-4e79-82d6-9c7c81541ffa)

**Comment by songxiaosheng** [comment]
看着像Netty版本不太兼容，检查下项目中是否多个地方引入了Netty

**Comment by zhangbiaoyg** [comment]
已解决

**Comment by jzcccc** [comment]
> 已解决

怎么解决的呢？
