### ISSUE TITLE
远程调用HttpServlet相关问题

### ISSUE THREAD

**Issue by xorange1997** [apache/dubbo#12348]
您好，目前有个需求就是我请求通过servlet进入到前置服务，然后在前置服务里面调用dubbo服务提供方，我想知道，在服务提供方我能通过RpcContext.getContext().getRequest获得HttpServlet信息吗？因为这是一个上传文件的请求，我需要获取servlet的流，然后进行写操作。
<img width="1059" alt="image" src="https://github.com/apache/dubbo/assets/38392442/2ab7f367-6283-4595-be7a-3e83e193b471">

**Comment by AlbumenJ** [comment]
serlvet 流有很多属性是不能序列化的，建议是在请求之前转换成自己的 dto，然后通过 RpcContext 传递

**Comment by xorange1997** [comment]
> serlvet 流有很多属性是不能序列化的，建议是在请求之前转换成自己的 dto，然后通过 RpcContext 传递

但是对于传文件来说这样感觉不大友好，使用dubbo的rest能不能达到这种效果勒

**Comment by AlbumenJ** [comment]
> > serlvet 流有很多属性是不能序列化的，建议是在请求之前转换成自己的 dto，然后通过 RpcContext 传递
> 
> 但是对于传文件来说这样感觉不大友好，使用dubbo的rest能不能达到这种效果勒

通过 RPC 传递文件本身就不是一个最佳实践，建议在 RPC 中仅传递文件标识符。

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
