### ISSUE TITLE
优雅停机相关问题

### ISSUE THREAD

**Issue by xorange1997** [apache/dubbo#12341]
您好，目前使用的是dubbo3.1版本，框架使用api形式启动的dubbo，请问一下，我们使用DubboBootstrap.getInstance().stop();能够实现dubbo优雅停机吗？

**Comment by xorange1997** [comment]
因为还有个DubboBootstrap getInstance(ApplicationModel applicationModel)方法，我不清楚这个方法是做什么用的

**Comment by AlbumenJ** [comment]
> 您好，目前使用的是dubbo3.1版本，框架使用api形式启动的dubbo，请问一下，我们使用DubboBootstrap.getInstance().stop();能够实现dubbo优雅停机吗？

请升级到 3.2 版本，这一块已经进行了完善。
预期 stop 的时候会提前反注册，然后等待一段时间流量是否摘除。但是由于 stop 本身是一个同步的操作，等待的时间不会很长。如果需要保证稳定的话最好使用 offline 的 qos api 提前摘除。

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
