### ISSUE TITLE
dubbo3.2 不支持kryo序列化了吗

### ISSUE THREAD

**Issue by chenbug2** [apache/dubbo#12342]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo3.2 不支持kryo序列化了吗
我看3.2的源码里，dubbo-serialization目录下，都没有kryo的工程了，之前3.1的是有的，是不准备支持了吗

**Comment by EarthChen** [comment]
在这个仓库中 https://github.com/apache/dubbo-spi-extensions

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
