### ISSUE TITLE
MonitorFilter#createStatisticsUrl作为消费方调用获取的IP不是提供方IP是消费方的ip

### ISSUE THREAD

**Issue by shaonianxingzhong** [apache/dubbo#12340]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
<img width="920" alt="1684319651177" src="https://github.com/apache/dubbo/assets/126050530/9821bbc9-604e-44d1-a47b-6feb7260c358">

### Environment

* Dubbo version: 3.1.6
* Java version: 1.8

**Comment by CrazyHZM** [comment]
The IP of the peer is collected here, so this is not a problem.
