### ISSUE TITLE
Improve the flexibility and readability of Dubbo logging

### ISSUE THREAD

**Issue by PhoenixBackendon** [apache/dubbo#12356]
## Abstract: 
As a mature micro-service framework, Dubbo has made great achievements in logging. However, the logger implemented by Dubbo only supports the configuration-based method at present, which can't make full use of the placeholder value assignment function provided by the underlying logger. As a result, developers can only use logger.debug(String message) for logging, instead of using more elegant placeholder log printing methods like Spring, Netty, Kubernetes and other projects. In order to improve the flexibility and readability of Dubbo logging, it is suggested to add a conversion layer in the middle of the logger to support placeholder logging.

## Suggestion:
1.Add a conversion layer in the middle of Dubbo's loggers to convert placeholder loggers into formats acceptable to the underlying loggers.
2.Provide an API or configuration item that allows developers to log by using placeholders and parameters, such as logger. debug (string message, object ... params).
3.The logic of formatting and replacing parameter values is realized in the conversion layer to ensure the correctness and readability of log records.

## Example:
The following code snippets demonstrate the difference between the current logging approach and the proposed placeholder-based logging approach after incorporating the conversion layer:

### Current approach:
`logger.debug("Processing request: " + request.getPath() + " from IP: " + request.getRemoteIP());`

### Placeholder-based approach (with conversion layer):
`logger.debug("Processing request: {} from IP: {}", request.getPath(), request.getRemoteIP());`

The placeholder-based logging approach improves code readability and offers greater flexibility for log output. It allows developers to separate the log message template from the parameter values, resulting in more concise and maintainable code.

## Expected Benefits:
Developers can log messages using placeholders and parameters, enabling more flexible and maintainable logging.
Through the conversion layer, Dubbo can adapt to various underlying logging frameworks, providing a consistent logging experience.
Enhance Dubbo's competitiveness in logging capabilities, attracting more developers and organizations to choose Dubbo as a distributed service framework.
This proposal aims to improve the logging functionality of Dubbo, enhancing development experience and code quality. I look forward to discussing and implementing this improvement together with the community.

**Comment by PhoenixBackendon** [comment]
related comment #12334 https://github.com/apache/dubbo/issues/12334#issuecomment-1554546614

**Comment by AlbumenJ** [comment]
> I am willing to contribute , please guide me further

Worked in https://github.com/apache/dubbo/pull/12365
