### ISSUE TITLE
集成dubbo后，dubbo检测机制会一直提示invalid version format: UNSUPPORTED

### ISSUE THREAD

**Issue by seaLordsLiu** [apache/dubbo#12363]
dubbo version：3.1.10
spring boot：2.7.6
spring cloud：2021.0.5

**Comment by 18279435013** [comment]
补充相关内容信息：1.错误提示信息![上传图像.png...]()
2. 配置信息
![image](https://github.com/apache/dubbo/assets/86147435/b997a212-3965-4786-a7ec-187bdca935dd)

**Comment by AlbumenJ** [comment]
报错的端口是哪一个

**Comment by syltr** [comment]
我遇到相同的报错，端口如下：
![image](https://github.com/apache/dubbo/assets/37098694/e82e9aa5-f638-42ce-9f3c-fd6d4502091a)

**Comment by syltr** [comment]
参考issue:12145已解决（https://github.com/apache/dubbo/issues/121450)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.

**Comment by YuanJie2001** [comment]
> 参考issue:12145已解决（https://github.com/apache/dubbo/issues/121450)

oh my gay! it's not found!

**Comment by wcy666103** [comment]
> > 参考issue:12145已解决（https://github.com/apache/dubbo/issues/121450)
> 
> oh my gay! it's not found!

What does **My gay** mean?

Refer to this link 
https://github.com/apache/dubbo/issues/12145
