### ISSUE TITLE
文件上传

### ISSUE THREAD

**Issue by xorange1997** [apache/dubbo#12360]
作者，您好，目前有个java文件上传接口问题请教一下：请求是从A服务的servlet进入的，进入到A之后需要远程调用B服务完成文件上传，因为文件上传的逻辑在B服务，目前很多方式都是将文件读成byte[]，然后进行远程调用，但是对于文件上传，这样感觉不大好。请问一下有相关demo或者建议的处理方式吗？

**Comment by AlbumenJ** [comment]
为什么不能在 A 直接进行文件处理，或者是说用户的请求直接进入到 B。

**Comment by AlbumenJ** [comment]
通常这种情况下是建议通过 RPC 生成上传的临时 token，然后通过一个独立的文件上传功能直接上传。

**Comment by xorange1997** [comment]
> 为什么不能在 A 直接进行文件处理，或者是说用户的请求直接进入到 B。

因为想要一个统一的入口，A就类似于一个网关的作用。

**Comment by Alleninggx** [comment]
可以考虑分片上传，S3规范的对象存储都支持合并文件

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.

**Comment by Alleninggx** [comment]
邮件已收到！
