### ISSUE TITLE
对prefer-serialization=fastjson2,hessian2 的理解

### ISSUE THREAD

**Issue by zhangbiaoyg** [apache/dubbo#12375]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

我在Dubbo3.2.0 版本中，使用了triple协议，并通过定义protobuf IDL 方式来生产相关文件。但是注册信息中显示prefer-serialization=fastjson2,hessian2。
![image](https://github.com/apache/dubbo/assets/133645679/ca38a5c8-b5f1-4307-a358-18682f529ba6)

这里使用的序列化不应该是protobuf吗？该如何理解这里prefer-serialization=fastjson2,hessian2代表的意思？

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
