### ISSUE TITLE
RpcServiceContext.isConsumerSide return false in consumer side

### ISSUE THREAD

**Issue by wegod** [apache/dubbo#12376]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.10
* Java version: 1.8
### Steps to reproduce this issue

1. A is consumer, B is provider, B has a 2.6.x Filter F using RpcServiceContext.isConsumerSide
2. A call B's method, in A's env and in Filter F, RpcServiceContext consumerUrl is A, url is B. 

The reason is when change Invoker to CompatibleInvoker, consumerUrl is missed in url

### Expected Behavior

isConsumerSide in Filter F return true in A's env when A calling B

### Actual Behavior

isConsumerSide method in Filter F always use url param to check and return false in A's env

![image](https://github.com/apache/dubbo/assets/3276231/bac40f63-08f6-411d-a073-640445a86fe6)

**Comment by songxiaosheng** [comment]
你这个版本有点低了，建议升级最新版本，，或者debug看下url中是否可以获取到相关信息兼容一下

**Comment by wegod** [comment]
> 你这个版本有点低了，建议升级最新版本，，或者debug看下url中是否可以获取到相关信息兼容一下

要升3.2.1么，明天我试下，不过我大概看了下3.2的代码isConsumerSide的逻辑是一样的，难道设置url和consumerUrl不一样么

**Comment by songxiaosheng** [comment]
你试试3.2版本我用这个方法判断是可以的

**Comment by wegod** [comment]
> 你试试3.2版本我用这个方法判断是可以的

或者能不能根据是否有consumerUrl判断是否是consumerSide？
另外我那个case还有个条件，B接口有个Filter F，在A调用B时，在F中isConsumerSide返回了false，url是provider的

**Comment by wegod** [comment]
> 你试试3.2版本我用这个方法判断是可以的

3.2.1 也有同样的问题
isConsumerSide的判断逻辑是在B服务的Filter里，虽然是在A consumer机器上判断的Filter，但还是被认为是provider

大概看了下url和consumerUrl的逻辑，既然拆成了两个url，感觉看着是url只表示provider的url了，为啥只用url的side来判断是否是consumer? 

可以不可以直接判断是否有consumerUrl之类的逻辑来判断isConsumerSide

**Comment by wegod** [comment]
定位到问题了，看下怎么解决比较好，感觉直接使用consumerUrl判断是不是更好一些
ConsumerContextFilter先设置RpcServiceContext的url为consumer的，AbstractClusterInvoker中invokeWithContext执行setContext会覆盖RpcServiceContext的url为provider的

**Comment by wegod** [comment]
还有个复现条件，这个Filter是2.6.x的，在转URL的时候丢失了consumerUrl，所以直接判定为provider了，明天这块再搞下兼容应该也可以

**Comment by AlbumenJ** [comment]
> > 你试试3.2版本我用这个方法判断是可以的
> 
> 3.2.1 也有同样的问题 isConsumerSide的判断逻辑是在B服务的Filter里，虽然是在A consumer机器上判断的Filter，但还是被认为是provider
> 
> 大概看了下url和consumerUrl的逻辑，既然拆成了两个url，感觉看着是url只表示provider的url了，为啥只用url的side来判断是否是consumer?
> 
> 可以不可以直接判断是否有consumerUrl之类的逻辑来判断isConsumerSide

org/apache/dubbo/rpc/cluster/filter/support/ConsumerContextFilter.java:68 这里应该是会填充 url 的才对

**Comment by AlbumenJ** [comment]
> 还有个复现条件，这个Filter是2.6.x的，在转URL的时候丢失了consumerUrl，所以直接判定为provider了，明天这块再搞下兼容应该也可以

转 2.6.x 的 Filter 的时候 RpcContext 也是会从 apache 的 RpcContext 获取的

**Comment by wegod** [comment]
> AbstractClusterInvoker中invokeWithContext执行setContext会覆盖RpcServiceContext的url为provider的

是的，但是后边就被覆盖了，AbstractClusterInvoker中invokeWithContext执行setContext会invoker的provider url覆盖为ConsumerContextFilter设置的url

在alibaba的LoadBalance中，url会转成new com.alibaba.dubbo.common.URL(url)，由于consumerURL是ServiceAddressURL的属性，这里转的时候consumerURL就丢失了，所以在apache的RpcContext判断consumerSide的时候就直接使用了invoker的provider url了

**Comment by AlbumenJ** [comment]
那这个应该是 AbstractClusterInvoker 覆盖的时候的问题，应该修在 AbstractClusterInvoker 的逻辑上

**Comment by wegod** [comment]
> 那这个应该是 AbstractClusterInvoker 覆盖的时候的问题，应该修在 AbstractClusterInvoker 的逻辑上

那这样可能在filter里使用RpcContext判断isConsumerSide可能就有问题了

我在new com.alibaba.dubbo.common.URL(url)的时候把url原信息都带上测试OK了，或者在RpcContext里判断isConsumerSide的时候判断RpcContext里的consumerUrl不为空则认定为consumerSide？

**Comment by wegod** [comment]
> [apache/dubbo-samples#853](https://github.com/apache/dubbo-samples/pull/853)
> 
> 我加了个测试用例，本地测试几种 Filter 都是可以正常获取的

ConsumerFilter继承alibaba的Filter应该就复现了，问题是出在com.alibaba.dubbo.rpc.cluster.Loadbalance里，41行转new com.alibaba.dubbo.common.URL(url)的时候，丢失了url里的consumerUrl信息

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/22642a27-7ffc-435b-86fc-6eac8045a9cd)

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/2a51ab26-95ad-4951-9c3d-7f6f38c85850)

**Comment by wegod** [comment]
晚上我再复现下截图
DubboServiceAddressURL继承了URL，里边的getSide方法实际是拿的consumerURL的SIDE_KEY，如果转alibaba的URL时候丢了consumerURL并且直接继承apache的URL实现的话，就走不到DubboServiceAddressURL的getSide方法了

**Comment by wegod** [comment]
还有个触发条件是使用2.6版本的loadbalance，这样就触发了com.alibaba.dubbo.rpc.cluster.Loadbalance里，41行转new com.alibaba.dubbo.common.URL(url)的时候，丢失了url里的consumerUrl信息的问题了

**Comment by AlbumenJ** [comment]
可以给一段具体的代码吗，Loadbalance 我理解都是 Consumer 了呀

**Comment by wegod** [comment]
> 可以给一段具体的代码吗，Loadbalance 我理解都是 Consumer 了呀

![image](https://github.com/apache/dubbo/assets/3276231/2aaf6c3f-deb2-4490-81cb-e5276136feb5)
![image](https://github.com/apache/dubbo/assets/3276231/4b797b68-8947-4469-81b2-4fa58d233632)

是的，就是在consumer端出的问题，在consumer触发Loadbalance选完invoker后，转url的时候丢失了consumerURL信息，然后在invokeWithContext的setContext方法执行时候，就会把这个provider的invoker和url放到RpcContext里，这时候filter里再调用isConsumerSide就出错了

**Comment by wegod** [comment]
![image](https://github.com/apache/dubbo/assets/3276231/9ffedf93-6f75-4c57-9eba-869d9e4b6d82)
补充个loadbalance之后调用invokeWithContext的代码

**Comment by AlbumenJ** [comment]
懂了，那应该改成加一个单独的 URL Delegator 吧，这样不会侵入到原来的 URL

**Comment by AlbumenJ** [comment]
兼容点应该在 com.alibaba.dubbo.rpc.Invoker.CompatibleInvoker#getUrl

**Comment by AlbumenJ** [comment]
另外最好 Alibaba LoadBalance 处理完以后把 CompatibleInvoker 解开来，恢复原来的 apache invoker

**Comment by wegod** [comment]
> 另外最好 Alibaba LoadBalance 处理完以后把 CompatibleInvoker 解开来，恢复原来的 apache invoker

是的，这样最好。看URL里的代码感觉是后来加的子类里加了一些属性和方法，在alibaba的兼容里丢失了。

我之前改的只是加了个Delegator https://github.com/apache/dubbo/pull/12397

回头我看下com.alibaba.dubbo.rpc.cluster.Router的再改改

**Comment by AlbumenJ** [comment]
> > 另外最好 Alibaba LoadBalance 处理完以后把 CompatibleInvoker 解开来，恢复原来的 apache invoker
> 
> 是的，这样最好。看URL里的代码感觉是后来加的子类里加了一些属性和方法，在alibaba的兼容里丢失了。
> 
> 我之前改的只是加了个Delegator #12397
> 
> 回头我看下com.alibaba.dubbo.rpc.cluster.Router的再改改

https://github.com/apache/dubbo/pull/12449 帮看下这个修改可以不

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/pull/853 补充了 LoadBalance 的 case，看起来还是没报错

**Comment by AlbumenJ** [comment]
> [apache/dubbo-samples#853](https://github.com/apache/dubbo-samples/pull/853) 补充了 LoadBalance 的 case，看起来还是没报错

验证了，在接口级服务发现模式下有问题

**Comment by wegod** [comment]
@AlbumenJ 看代码没啥问题。接口级服务发现模式下具体问题是啥？

**Comment by AlbumenJ** [comment]
> @AlbumenJ 看代码没啥问题。接口级服务发现模式下具体问题是啥？

接口级服务发现的 URL 应该是强依赖 consumerURL 的，应用级服务发现的 URL 在获取 parameters 的时候会把当前 consumerURL的数据直接覆盖进新 URL。简单来说就是接口级的会丢数据，应用级的不会

**Comment by wegod** [comment]
> > @AlbumenJ 看代码没啥问题。接口级服务发现模式下具体问题是啥？
> 
> 接口级服务发现的 URL 应该是强依赖 consumerURL 的，应用级服务发现的 URL 在获取 parameters 的时候会把当前 consumerURL的数据直接覆盖进新 URL。简单来说就是接口级的会丢数据，应用级的不会

明白了，就是这个只在接口级服务发现模式下有问题。https://github.com/apache/dubbo/pull/12449 fix了这个问题

**Comment by wegod** [comment]
@AlbumenJ https://github.com/apache/dubbo/pull/12449 还会解决一个性能问题
之前的new  URL(org.apache.dubbo.common.URL url)会造成Eden区大量的垃圾，频繁的young gc让机器load升高很多
![image](https://github.com/apache/dubbo/assets/3276231/4129db30-945a-4665-9cfd-b6dede980706)
![image](https://github.com/apache/dubbo/assets/3276231/de328642-33da-44c3-8c61-2debf93d65e0)

**Comment by sadeychai** [comment]
这个问题会在3.1.x修复吗？还是只能升级到3.2.x?

**Comment by wegod** [comment]
> 这个问题会在3.1.x修复吗？还是只能升级到3.2.x?

这个提交到了3.2.3里了，按AlbumenJ之前的说法，目前3.1.x只解决安全问题了

**Comment by LoveleeKay** [comment]
> > 这个问题会在3.1.x修复吗？还是只能升级到3.2.x?
> 
> 这个提交到了3.2.3里了，按AlbumenJ之前的说法，目前3.1.x只解决安全问题了

我用的3.2.9 版本判断依旧不准确，也是使用到了alibaba的filter
![image](https://github.com/apache/dubbo/assets/35088017/26192582-6b7b-485b-902e-51b84fa7d1c0)
