### ISSUE TITLE
triple协议序列化失败

### ISSUE THREAD

**Issue by Alleninggx** [apache/dubbo#12377]
### Environment

* Dubbo version: 3.2.1
* fastjson version: 2.0.32
* Operating System version: win
* Java version: 17

### Steps to reproduce this issue

1. 创建一个使用streaming通信模式的triple协议的Server
![image](https://github.com/apache/dubbo/assets/40049392/afbfb82b-8898-443c-b6f5-7e274feed5ac)
3. 在Provider同一个微服务中编写Client调用
4. 在新创建的Consumer微服务中编写Client调用
5. 对比

### 现象
在Provider中调用，会InjvmInvoker#doInvoke方法中，并调用recreateInvocation方法，具体在InjvmInvoker.java:232行的时候拷贝一份请求参数。问题就在这里，paramDeepCopyUtil#copy返回的是一个只是初始化过的对象，值是没有的。

url==>injvm://127.0.0.1/com.**.resource.api.dubbo.IExcelFileResourceDubboGrpcService?anyhost=true&application=psi-resource-server&background=false&bind.ip=192.168.0.192&bind.port=50051&check.serializable=false&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&exporter.listener=injvm&file-cache=true&generic=false&interface=com.**.resource.api.dubbo.IExcelFileResourceDubboGrpcService&methods=read&pid=28668&prefer.serialization=fastjson2,hessian2&qos.enable=false&release=3.2.1&retries=0&serialize.check.status=WARN&side=provider&timeout=60000&timestamp=1684749252678&token=50e3601b-f25c-4bfb-983a-a326e8386ca7&trust.serialize.class.level=4&validation=jvalidationNew

![uTools_1684753967348](https://github.com/apache/dubbo/assets/40049392/af842fb5-0aa9-4802-860a-25d7184ee2fc)

而我再Consumer中调用，它不会进去这个InjvmInvoker，最终Server能获取正确的数据。

**Comment by Alleninggx** [comment]
![image](https://github.com/apache/dubbo/assets/40049392/6f5411a2-4137-40bf-b230-b60de911d9bb)

我了解到如果是本地服务，则意味着仅在当前JVM中搜索。那么应该就是grpc 消息对象序列化和反序列的问题了。那么要怎么解决呢？

**Comment by AlbumenJ** [comment]
Injvm 协议不支持  Streaming，需要配置 scope 为 remote

**Comment by Alleninggx** [comment]
邮件已收到！
