### ISSUE TITLE
关于协议端口复用的序列化问题

### ISSUE THREAD

**Issue by mlkt** [apache/dubbo#12395]
假如有这样的协议配置：
`<dubbo:protocol name="tri" port="5678" ext-protocol="rest"/>`

1、这时参数和返回值的序列化用的是什么格式？是默认的fastjson2？ 
但是tri是用二进制的JSONB，那暴露出的rest协议参数和返回值会自动用文本的JSON吗？

2、假如是反过来这样呢？结果和上面一样吗？
`<dubbo:protocol name="rest" port="5678" ext-protocol="tri"/>`

3、还有就是如果我指定了二进制的方式又会如何？两种情况都是用二进制的来序列化吗？
`<dubbo:protocol name="rest" port="5678" ext-protocol="tri" serialization="hessian2"/>`

4、在第3个写法这里指定了二进制的情况下，假如用了注解 `@Produces({MediaType.APPLICATION_JSON})` 又会如何？

[https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/protocol/rest/](https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/protocol/rest/)
![image](https://github.com/apache/dubbo/assets/10374085/522a1aab-0d40-4821-8322-7bcb9de038bc)

**Comment by AlbumenJ** [comment]
JSONB 序列化只在 dubbo、triple 协议生效，rest 协议使用的是原生的 json
