### ISSUE TITLE
AbstractStateRouter类第120行invokers.and(routeResult)导致正确的Invoker被过滤

### ISSUE THREAD

**Issue by JagdtigerI** [apache/dubbo#12407]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.1/3.2.2
* Operating System version: windows/liunix
* Java version: 1.8

### Steps to reproduce this issue

1. AbstractStateRouter 类中，类过滤的Invokers有7个
2. 使用自定义的StateRouter进行过滤，命中5,6,7，共3个Invoker
3. 返回AbstractStateRouter 类的第120行，执行
      if (routeResult != invokers) {
            routeResult = invokers.and(routeResult);
        }
5.  invokers.and(routeResult)方法，只会在原有的7个Invokers按顺序选出3个结果，结果为第1,2,3个
6. 由于正确的invoker没被选中，导致dubbo路由错误，调用失败
![AgAACAhmkOunI206P-hOX6v_ohId1u9Q](https://github.com/apache/dubbo/assets/25842839/642c41e0-38a3-49f1-82a1-08d6d13166bc)

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
> 使用自定义的StateRouter进行过滤，命中5,6,7，共3个Invoker


这个怎么处理的

**Comment by JagdtigerI** [comment]
我们在dubbo接口上还有一层产品码注解，有ProductRouter<T> extends AbstractStateRouter<T> 进行产品码筛选。

**Comment by JagdtigerI** [comment]
一个接口会有多种产品码实现，ProductRouter 通过产品码进行过滤 命中5,6,7

**Comment by JagdtigerI** [comment]
在在3.0.X版本此功能都正常运行，升级到3.2.1之后，业务方反馈调用服务异常

**Comment by JagdtigerI** [comment]
通过修改了自定义的StateRouter中的BitList的用法，问题解决了
正确的BitList用法为在自定义的StateRouter中克隆doRouter方法传递过来的BitList
BitList<Invoker<T>> result = invokers.clone();
使用remove方法来进行过滤
result.removeIf(index);

**Comment by JagdtigerI** [comment]
此问题为自定义StateRouter中的BitList的用法错误

**Comment by sheiy** [comment]
@AlbumenJ @JagdtigerI 麻烦帮忙看看像下面这样写有问题吗？需求是通过HTTP请求里带的参数如果和dubbo provider配置的参数一样就优先使用那些provider
<img width="781" alt="image" src="https://github.com/apache/dubbo/assets/12210038/ddedf1a7-ffcd-4508-8804-11bf393040a6">

**Comment by AlbumenJ** [comment]
> @AlbumenJ @JagdtigerI 麻烦帮忙看看像下面这样写有问题吗？需求是通过HTTP请求里带的参数如果和dubbo provider配置的参数一样就优先使用那些provider <img alt="image" width="781" src="https://user-images.githubusercontent.com/12210038/258976065-ddedf1a7-ffcd-4508-8804-11bf393040a6.png">

代码上看是没问题的

**Comment by sheiy** [comment]
> > @AlbumenJ @JagdtigerI 麻烦帮忙看看像下面这样写有问题吗？需求是通过HTTP请求里带的参数如果和dubbo provider配置的参数一样就优先使用那些provider <img alt="image" width="781" src="https://user-images.githubusercontent.com/12210038/258976065-ddedf1a7-ffcd-4508-8804-11bf393040a6.png">
> 
> 代码上看是没问题的

多谢
