### ISSUE TITLE
扩展依赖注入器(ExtensionInjector)集合无法自定义排序规则

### ISSUE THREAD

**Issue by dhyly** [apache/dubbo#12402]
### Environment

* Dubbo version: 3.0.7
* Operating System version: win 10
* Java version: 1.8

### Issue1

默认的自适应扩展点AdaptiveExtensionInjector,其初始化方法initialize中获取到ExtensionInjector所有扩展实现，但是默认通过TreeSet进行排序，即按照SPI文件中指定的扩展别名进行的排序:

**initialize方法:**

![image](https://github.com/apache/dubbo/assets/86190302/b34eeee4-5064-4e27-83ef-a328e4118ba9)

**getSupportedExtensions方法:**

![image](https://github.com/apache/dubbo/assets/86190302/92aa26ca-58fa-4a8e-a13e-ce49abdc70e6)

如果我自定义一个CustomSpiExtensionInjector，我无法像Spring中继承Order接口一样，实现对自定义的扩展依赖注入器执行顺序的控制，为了防止自定义的扩展依赖注入器影响到dubbo内部的依赖注入逻辑，需要借助与自定义注解限制其处理范围:

![image](https://github.com/apache/dubbo/assets/86190302/a1ee05d7-023a-4037-a12a-2c2eb22a1494)

### thinking

能否提供对扩展依赖注入器(ExtensionInjector)的排序支持

****

### issue2 

默认提供的扩展依赖注入器实现之一: SpiExtensionInjector , 默认是获取当前扩展类型的自适应扩展点:
![image](https://github.com/apache/dubbo/assets/86190302/f0a67afe-9fad-4c3d-913a-a88005534b9e)

我有点疑惑，为什么不对获取普通扩展点的操作进行支持呢？ 比如下面这样:
![image](https://github.com/apache/dubbo/assets/86190302/a6065ffe-83e1-43ba-ab50-992084ab3842)

**Comment by AYue-94** [comment]
我的想法是。
第一个问题，你可能可以尝试ExtensionPostProcessor这个扩展点在dubbo依赖注入前后自己判断。
第二个问题，这个肯定是返回自适应扩展，这是dubbo框架从2.x开始的老逻辑，所有扩展点通过setter注入的地方都是自适应的。可能是为了让你遵循在运行时通过url来动态选择扩展点，而不是在一开始就决定注入一个死的扩展点。

**Comment by dhyly** [comment]
> 我的想法是。 第一个问题，你可能可以尝试ExtensionPostProcessor这个扩展点在dubbo依赖注入前后自己判断。 第二个问题，这个肯定是返回自适应扩展，这是dubbo框架从2.x开始的老逻辑，所有扩展点通过setter注入的地方都是自适应的。可能是为了让你遵循在运行时通过url来动态选择扩展点，而不是在一开始就决定注入一个死的扩展点。

好的
