### ISSUE TITLE
trile protocol config accesslog="true" lead to StackOverflowError

### ISSUE THREAD

**Issue by ZYB-J** [apache/dubbo#12415]
* Dubbo version: 3.1.5
* Operating System version: xxx
* Java version: jdk8

go client invoke java,Exception not print on java side,only go client side , AccessLogFilter convert request param (proto generated java class) to json,it lead to cycle invoke:
![image](https://github.com/apache/dubbo/assets/5662648/2a6edb13-fdb8-460d-bac7-1c2927e8c88f)

**Comment by EarthChen** [comment]
pb 对象无法fastjson tojson，可能需要考虑一下这块如何打印更合适，当然也可以让 fastjson 那边支持一下打印
