### ISSUE TITLE
DUBBO2升级到DUBBO3, use-as-config-center和use-as-metadata-center是否必须为true

### ISSUE THREAD

**Issue by TOP-LH** [apache/dubbo#12424]
# DUBBO2升级到DUBBO3, use-as-config-center和use-as-metadata-center是否必须为true?

如题所问, 今天从DUBBO2.7.9升级到了3.1.4, 发现之前dubbo2.7.9的时候, 这两个参数一直为false(use-as-config-center和use-as-metadata-center), 然后升级dubbo3的时候就总是报错, 说找不到服务提供者, 最后把这两个参数调整为了true就可以了

因为文档上没有说这个必须为true, 比较不理解, 过来询问一下, 谢谢

**Comment by songxiaosheng** [comment]
这两个配置是判断是否使用注册中心来作为配置中心和元数据中心的，这个只要注册中心扩展存在默认是支持的，无需单独配置，你们报错信息有不

**Comment by TOP-LH** [comment]
> 这两个配置是判断是否使用注册中心来作为配置中心和元数据中心的，这个只要注册中心扩展存在默认是支持的，无需单独配置，你们报错信息有不

那我可以关闭吗, 我看现在已经往配置中心中写入大概一百多个配置文件了, 有点冗余啊

**Comment by AlbumenJ** [comment]
如果没有开启应用级服务发现是可以关闭的

**Comment by TOP-LH** [comment]
> 如果没有开启应用级服务发现是可以关闭的

谢谢, 能否在哪里说明一下这两个参数在应用级服务发现是需要开启的, 我因为这个耽误了好久的时间

**Comment by AlbumenJ** [comment]
https://cn.dubbo.apache.org/zh-cn/overview/reference/proposals/service-discovery/

**Comment by TOP-LH** [comment]
> https://cn.dubbo.apache.org/zh-cn/overview/reference/proposals/service-discovery/

嗯. 我也是看了这个才明白需要开启注册中心和元数据配合, 那我把iss关了
