### ISSUE TITLE
dubbo2 连接zk失败重试产生死锁

### ISSUE THREAD

**Issue by xc19950304** [apache/dubbo#12428]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.18
* Operating System version: linux
* Java version: jdk8

### Steps to reproduce this issue

dubbo2 连接zk失败重试产生死锁

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

dubbo创建代理失败后，自身重试机制，会无限重试，阻塞后续业务线程重新创建代理的逻辑，请问有什么办法避免或者解决这个问题
![image](https://github.com/apache/dubbo/assets/30997509/b505f0d1-93e6-433b-b4a0-1f4f915be415)
![image](https://github.com/apache/dubbo/assets/30997509/aa36bee8-b207-408a-8b17-5ec0ec050f70)

**Comment by songxiaosheng** [comment]
curator和zookeeper客户端和服务端版本是什么

**Comment by xc19950304** [comment]
> curator和zookeeper客户端和服务端版本是什么

我们没有显示的去指定，应该用的是dubbo2.7.18默认的版本

**Comment by AlbumenJ** [comment]
你们的 zk 是连不上了吗

**Comment by xc19950304** [comment]
zk目前是能连上的，应用重启之后都没问题，但是根据线程堆栈分析，看上去是产生死锁了，具体触发原因不清楚，就现象来看是创建代理一直失败，即使zk可用正常，也没法儿访问

**Comment by AlbumenJ** [comment]
> zk目前是能连上的，应用重启之后都没问题，但是根据线程堆栈分析，看上去是产生死锁了，具体触发原因不清楚，就现象来看是创建代理一直失败，即使zk可用正常，也没法儿访问

这个看最好在 zk 那边提个 issue 问下

**Comment by xc19950304** [comment]
但是应用重启后，恢复正常了，很奇怪，dubbo和zk相关的三方包，是zk那边提供的吗

**Comment by AlbumenJ** [comment]
> 但是应用重启后，恢复正常了，很奇怪，dubbo和zk相关的三方包，是zk那边提供的吗

有两个部分，一个是 curator，一个是 zk 官方的
