### ISSUE TITLE
No such extension tomcat for server/org.apache.dubbo.remoting.Transporter

### ISSUE THREAD

**Issue by keylihai** [apache/dubbo#12430]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo版本：2.7.15
问题：启动报错No such extension tomcat for server/org.apache.dubbo.remoting.Transporter
![821685441533_ pic](https://github.com/apache/dubbo/assets/11571589/6e566ecb-adb6-46e5-a925-6febe9664639)

![831685441580_ pic](https://github.com/apache/dubbo/assets/11571589/28d3d8a5-2dec-4fbd-a6ce-a5297af65c05)
![841685441599_ pic](https://github.com/apache/dubbo/assets/11571589/44f90e75-eb02-4921-ad4c-5440dca68823)

**Comment by keylihai** [comment]
dubbo 从 2.7.8升级至 2.7.15时遇到的问题，dubbo 协议配置如下：
![image](https://github.com/apache/dubbo/assets/11571589/e44ea3b4-08ff-4d35-b848-dac2ef374033)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
