### ISSUE TITLE
设置dubbo注册模式为instance,配置中心和服务中心都是nacos,为什么nacos服务列表有两个实例,元数据中心是要抽离出来重新配置吗?

### ISSUE THREAD

**Issue by xiaojinrong** [apache/dubbo#12447]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
![image](https://github.com/apache/dubbo/assets/38065506/9f76759f-868e-4fd0-9fe8-11655b4b2d66)
![image](https://github.com/apache/dubbo/assets/38065506/9b35d3a7-94e7-418d-9bcc-e555f52cbbd5)
![image](https://github.com/apache/dubbo/assets/38065506/4e94c8de-39ae-42a8-bed5-3c272f2dd8eb)

**Comment by AlbumenJ** [comment]
是不是依赖了 Spring Cloud Nacos 组件，另外一个节点是 Spring Cloud 注册的

**Comment by kaizen84** [comment]
使用namespace做隔离

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
