### ISSUE TITLE
dubbo泛化调用过多，导致FGC无法正常回收

### ISSUE THREAD

**Issue by just-right** [apache/dubbo#12471]
- dubbo泛化调用过多，导致FGC无法正常回收

![image](https://github.com/apache/dubbo/assets/24411889/8fafa20c-8f28-430c-ac12-ff5042bc6c8b)

- mat工具分析为 org.apache.dubbo.common.threadlocal.InternalThread对象引用

![image](https://github.com/apache/dubbo/assets/24411889/4a105032-60bc-4b13-98e1-42c2657844dc)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
