### ISSUE TITLE
关于dubbo3.2默认使用fastjson2中的一个疑问，涉及@JSONField(serialize = false) 注解

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#12478]
dubbo3.2默认使用fastjson2作为默认序列化的工具，我有个疑问，如果一个传输DTO对象有个字段使用了 @JSONField(serialize = false)注解，既然用fastjson2作为序列化，那这个注解的含义就是序列化的时候忽略这个字段。那么这是不是代表这个字段对消费者不可见？也就是获取不到这个字段的值？

但是我测了测加上这个注解消费者依然可以获取到这个字段。所以有些疑惑麻烦帮忙解答。

20230612更新: 我又测试了一下传输DTO对象用了这个注解确实会忽略这个字段。。

**Comment by AlbumenJ** [comment]
> 但是我测了测加上这个注解消费者依然可以获取到这个字段。所以有些疑惑麻烦帮忙解答。
> 
> 20230612更新: 我又测试了一下传输DTO对象用了这个注解确实会忽略这个字段。。

没太清楚现在的问题是什么

**Comment by twogoods** [comment]
@AlbumenJ 为什么现在默认选json啊，性能不是不如hessian2吗

**Comment by luger1990** [comment]
> > 但是我测了测加上这个注解消费者依然可以获取到这个字段。所以有些疑惑麻烦帮忙解答。
> > 20230612更新: 我又测试了一下传输DTO对象用了这个注解确实会忽略这个字段。。
> 
> 没太清楚现在的问题是什么

就是provider中的DTO 一个属性加了@JSONField(serialize = false)注解，就会导致consumer获取不到这个字段，因为用的是fastjson2序列化，fastjson2根据注解忽略这个字段了。

**Comment by EarthChen** [comment]
> > > 但是我测了测加上这个注解消费者依然可以获取到这个字段。所以有些疑惑麻烦帮忙解答。
> > > 20230612更新: 我又测试了一下传输DTO对象用了这个注解确实会忽略这个字段。。
> > 
> > 
> > 没太清楚现在的问题是什么
> 
> 就是provider中的DTO 一个属性加了@JSONField(serialize = false)注解，就会导致consumer获取不到这个字段，因为用的是fastjson2序列化，fastjson2根据注解忽略这个字段了。

这是合理的阿 fastjson那边的处理逻辑
