### ISSUE TITLE
为什么 dubbo 的netty workerGroup 线程数默认是 Math.min(Runtime.getRuntime().availableProcessors() + 1, 32)

### ISSUE THREAD

**Issue by mxh-kkk** [apache/dubbo#12481]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## 为什么 dubbo 的netty workerGroup 线程数默认是 Math.min(Runtime.getRuntime().availableProcessors() + 1, 32)
对于IO密集型的应用，默认线程数设置成Runtime.getRuntime().availableProcessors()*2，不是通用的做法吗？

**Comment by wxbty** [comment]
大部分应用是IO密集。Runtime.getRuntime().availableProcessors()*2 这个一般是boss线程吧，work线程会比较多，比如tomcat默认200+

**Comment by mxh-kkk** [comment]
> 大部分应用是IO密集。Runtime.getRuntime().availableProcessors()*2 这个一般是boss线程吧，work线程会比较多，比如tomcat默认200+

我不太理解您说的，boss线程数不是1吗？Runtime.getRuntime().availableProcessors()*2 比 Runtime.getRuntime().availableProcessors() + 1 数量多吧？

**Comment by wxbty** [comment]
建议深入理解下netty的reactor线程模型

**Comment by mxh-kkk** [comment]
> 建议深入理解下nio的reactor线程模型

我懵了，您说的跟源码好像不太匹配
![image](https://github.com/apache/dubbo/assets/60031481/b7bc2c7a-7dc3-4cf4-9f3f-fa27e3196ff6)

**Comment by wxbty** [comment]
我说的有问题，我试着这样解释一下。
NIO模型中，有三组线程池，netty的boss线程池、work线程池，dubbo的任务处理线程池。
netty的boss线程池负责创建、接收连接（socket、connection、session这种对象），轻量动作，非常快，一般一个线程就够，但是大并发情况下，也会发生阻塞，所以，实际设置2或者处理器核心数量会比较好。
work线程是IO线程，即输入输出，负责把数据从连接中取出或发出（比如socket.read/write），一般也不需要太多，因为不涉及业务Db、远程调用等耗时操作。work线程可以处理业务，但是为了防止阻塞，有耗时操作，会再开业务线程池(一般说的Dubbo线程池自定义就是这个)来处理。
业务线程池负责处理业务，这个数量会多一些，这样IO密集应用吞吐更高一些。
-----------------------------------

tomcat和dubbo 线程池稍有区别。
tomcat内置两级 :  boss + work，work 会比较多，一般我们不需要单独开线程池，直接在servlet上（work线程）写业务就行
dubbo内置三级：boss+work+内置业务线程池 ，这样work就不用太多（<32），dubbo接口代码在内置provider线程池处理

**Comment by mxh-kkk** [comment]
> 

谢谢您解答了我的疑惑，但我对您说的还是有点疑问，我理解的netty boss只会用到一个线程吧，即使是设置了多个线程

**Comment by wxbty** [comment]
netty的boss和work都是封装了线程池的EventLoopGroup，是可以设置多个线程的。boss设置多个线程的场景，我理解一种是异常互备，还有一种是绑定多端口，单个端口正常情况下，一个boss线程管理连接是够了
