### ISSUE TITLE
反馈一下flattenMode改为oss后发布的版本（3.2.1，3.2.2）在升级时遇到的问题

### ISSUE THREAD

**Issue by SingKS8** [apache/dubbo#12487]
原有demo项目大致结构如下：
```
jdk: 17
spring boot: 3.0
dubbo: 3.2.0
```

在parent 模块使用dependencyManagement 方式引入dubbo-bom
```xml
<dependencyManagement>
....
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-bom</artifactId>
      <version>${dubbo.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
...
</dependencyManagement>
```
### 1
从3.2.0升级到3.2.2后发现

dubbo-bom 无法将 dubbo-dependencies-bom 下的依賴帶入，
例如demo项目下module-a 引入 dubbo-dependencies-bom 所控制的io.protostuff组件
```xml
 ....
   <dependency>
      <groupId>io.protostuff</groupId>
      <artifactId>protostuff-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.protostuff</groupId>
      <artifactId>protostuff-runtime</artifactId>
    </dependency>
...
```
在编译时候都是 jar is missing 相关的错误，需要将dubbo-dependencies-bom 额外增加到dependencyManagement

### 2

增加dubbo-dependencies-bom 后，zookeeper的demo一直在报错:
```
java.lang.NoClassDefFoundError: org/apache/zookeeper/admin/ZooKeeperAdmin
```
发现demo中zookeeper 只是3.4.14而非之前的3.7.0，对比发布的dubbo-dependencies-bom.pom文件和源码发现，flatten插件在oss模式下将profile全部删除，源码以下profile失效；
```xml
<profile>
  <id>curator5</id>
  <activation>
      <jdk>[17,)</jdk>
  </activation>
  <properties>
      <zookeeper_version>3.7.0</zookeeper_version>
      <curator_version>5.1.0</curator_version>
  </properties>
</profile>
```
需要额外地将zookeeper，curator组件加入项目中。

### 问题
自从有dubbo-bom模块后，现有项目大部份都以dependencyManagement的import方式引入dubbo，目前发现只有3.2.x版本系列的flattenMode改为oss。
问题1: dubbo团队是否会全线版本更改flattenMode为oss？
问题2: 对于已更改版本，dubbo-bom未来是否会调整结构，还是建议使用者import多个bom模块？

**Comment by AlbumenJ** [comment]
> dubbo团队是否会全线版本更改flattenMode为oss？

新版本采用

> dubbo-bom未来是否会调整结构

目前几个 bom 的模块采用的是 bom 的模式（两个 zk 的在 https://github.com/apache/dubbo/pull/12508 中会修改掉）。关于 zk 版本这个 case 后面的版本应该是需要全线升级 curator 5 的，curator 4 只是兼容性存在。

**Comment by AlbumenJ** [comment]
profile 不透传这个可以使 Dubbo 的依赖变得干净，否则对用户的影响很不可控。

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
