### ISSUE TITLE
Dubbo2.7.7 ReferenceBean导致的严重性能问题，影响应用启动

### ISSUE THREAD

**Issue by spilledyear** [apache/dubbo#12498]
* Dubbo version: 2.7.7
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue
基于日志调试，最终定位到耗时代码在: AnnotatedInterfaceConfigBeanBuilder#configureBean 方法中，那就针对这个方法采集一下火焰图，如下：
<img width="1549" alt="image" src="https://github.com/apache/dubbo/assets/24663965/1063e59b-801a-4c2d-ad4b-d527d5c2726c">

![image](https://github.com/apache/dubbo/assets/24663965/300dedd0-03b0-46c5-8733-1a293fbee566)

每个ReferenceBean在初始化的完成后都要执行这个方法。通过日志，项目中220ReferenceBean的时候，执行了8400多万次。而如果ReferenceBean#prepareDubboConfigBeans只执行一次，isFactoryBean之会执行5000万次。 这种情况下， 启动耗时最少可以提升10s

# 优化
我们的想法是改成只执行一次，例如：
<img width="700" alt="image" src="https://github.com/apache/dubbo/assets/24663965/90982d3d-4e1b-474e-9834-09ab4aaf654d">

这目前测试下来没发现什么问题，但不确定这样是否会产生什么副作用呢

**Comment by spilledyear** [comment]
> 



> 2.7.x version has been EOL. Please try upgrade to 3.x
短时间内很难直接升级到3.0啊。针对这个问题，大佬能否先帮忙看看，这种优化方案是否可行

**Comment by AlbumenJ** [comment]
> > 
> 
> > 2.7.x version has been EOL. Please try upgrade to 3.x
> > 短时间内很难直接升级到3.0啊。针对这个问题，大佬能否先帮忙看看，这种优化方案是否可行

看起来是没啥问题，你可以验证下

**Comment by songxiaosheng** [comment]
3.x优化过了  
<img width="1195" alt="image" src="https://github.com/apache/dubbo/assets/81170548/785b3c1e-24c1-470c-ab4a-824cd57d47ab">
