### ISSUE TITLE
OpenTelemetry Observation Support

### ISSUE THREAD

**Issue by Zod-Li** [apache/dubbo#12497]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

I'm working on using OpenTelemetry to solve observable problems in my team, and I'm having trouble trying to get dubbo(2.7.3) metrics and traces. 
The main reasons for the problem as follows.
1. It does not work well with Otel-Collector which uses push mode, and Dubbo Monitor uses pull mode.
2. The dubbo metrics obtained through the Collector adapter cannot be correlated with traces & logs

I would like to know if dubbo can natively support OpenTelemtry Metrics & Tracing API in version 2.7.x ?
If wanted, we can provide a PR to add support for it by use SPI. 

Tks.

**Comment by chickenlj** [comment]
This feature is now been supported in the 3.2.x branch.

**Comment by Zod-Li** [comment]
> 

Great~  
I have checked the 3.2.x code, But I can't find a metrics implement of otlp-exporter, nor any implement that bridges micrometer metrics to opentelemetry, am I missing something?

**Comment by Zod-Li** [comment]
> This feature is now been supported in the 3.2.x branch.

Great~
I have checked the 3.2.x code, But I can't find a metrics implement of otlp-exporter, nor any implement that bridges micrometer metrics to opentelemetry, am I missing something?

**Comment by chickenlj** [comment]
Please check the starters we have just added here:

https://github.com/apache/dubbo/tree/3.2/dubbo-spring-boot/dubbo-spring-boot-starters/observability

**Comment by conghuhu** [comment]
This is Otlp sample: [https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-tracing/dubbo-samples-spring-boot-tracing-otel-otlp](https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-tracing/dubbo-samples-spring-boot-tracing-otel-otlp)

This is Zipkin sample: [https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-tracing/dubbo-samples-spring-boot-tracing-zipkin](https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-tracing/dubbo-samples-spring-boot-tracing-zipkin)

These are all OpenTelemetry tracers.

@Zod-Li

**Comment by Zod-Li** [comment]
> This is Otlp sample: https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-tracing/dubbo-samples-spring-boot-tracing-otel-otlp
> 
> This is Zipkin sample: https://github.com/apache/dubbo-samples/tree/master/4-governance/dubbo-samples-tracing/dubbo-samples-spring-boot-tracing-zipkin
> 
> These are all OpenTelemetry tracers.
> 
> @Zod-Li

Thanks a lot~  Is there an sample of exporting dubbo metrics via the otlp protocol ?

**Comment by Zod-Li** [comment]
> @Zod-Li Thank you for your suggestion. Currently, only OTlp of Tracing is supported, and Metrics is not yet supported. We will consider implementing it in a later version.

I'm doing on this, can provide PR after completion
