### ISSUE TITLE
dubbo 3.2.0 如何通过浏览器访问Dubbo 服务端一个 Triple 协议服务

### ISSUE THREAD

**Issue by zhuhongqiang01** [apache/dubbo#12496]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo版本：3.2.0
jdk版本：1.8

官方文档描述可以直接使用 curl、浏览器访问后端 Dubbo Triple 协议服务
实际上启动dubbo triple服务
通过浏览器get访问（类似http://local host:8080/org.apache.dubbo.sample.GreetService/sayHello）
报错
org.apache.dubbo.qos.command.exception.NoSuchCommandException :NoSuchCommandException :org.apache.dubbo.sample.GreetService

禁用qos报错：
org.apache.dubbo.remoting.transport.netty4.NettyPortUnificationServerHandler: Cant not recognize protocol from downstream=/xx.xx.xx.xx:xx

请问有完整的通过浏览器访问triple协议的示例吗？

官方文档描述：
[通信协议--HTTP/2 (Triple)](https://cn.dubbo.apache.org/zh-cn/overview/core-features/protocols/#http2-triple)
Triple 可同时运行在 HTTP/1 和 HTTP/2 传输协议之上，让你可以直接使用 curl、浏览器访问后端 Dubbo 服务。

Triple 协议设计理念与规范--原生多协议支持
https://cn.dubbo.apache.org/zh-cn/overview/reference/protocols/triple/#%E5%8E%9F%E7%94%9F%E5%A4%9A%E5%8D%8F%E8%AE%AE%E6%94%AF%E6%8C%81

以下是使用 curl 客户端访问 Dubbo 服务端一个 Triple 协议服务的示例：

curl \
    --header "Content-Type: application/json" \
    --data '{"sentence": "Hello Dubbo."}' \
    https://host:port/org.apache.dubbo.sample.GreetService/sayHello

**Comment by EarthChen** [comment]
开发中，当前还没完全兑现

**Comment by zhuhongqiang01** [comment]
> 开发中，当前还没完全兑现


@EarthChen
好的，最近我在公众号、官网、各种技术文章都看到关于直接浏览器访问triple的描述，以为功能已经就绪了
请问这个功能大概哪个版本会上线

**Comment by chickenlj** [comment]
> > 开发中，当前还没完全兑现
> 
> @EarthChen 好的，最近我在公众号、官网、各种技术文章都看到关于直接浏览器访问triple的描述，以为功能已经就绪了 请问这个功能大概哪个版本会上线

Java 侧预计会在未来1-2个月就绪。同时社区规划了 Go、Node.js、Web 侧响应实现，期望在未来形成 Triple 完整的前后端互通体系。
