### ISSUE TITLE
消费者在拿到nacos的最新配置后，dubbo的服务治理规则并没有生效（重试次数）

### ISSUE THREAD

**Issue by liamashes** [apache/dubbo#12529]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
按照[官方文档](https://cn.dubbo.apache.org/zh-cn/overview/tasks/traffic-management/retry/)，调整了重试次数后，依然没有生效，配置已经成功地推送到了相应的微服务。

相关工具的版本
* dubbo-admin：0.5.0
* dubbo: 3.0.8
* nacos: 2.2.3

*dubbo-admin的动态配置*：
![image](https://github.com/apache/dubbo/assets/65932272/1de52630-3cb2-472f-bc67-3542e4033cc0)

*Nacos中查看到该配置*：
![image](https://github.com/apache/dubbo/assets/65932272/c83013a6-9561-4877-93fb-2d891767b261)

*shop-frontend容器中也找到了该配置文件*：
![image](https://github.com/apache/dubbo/assets/65932272/0a4b1991-a29a-47ae-9aa7-73295c2a4445)

*但是访问demo页面时，其重试规则仍未生效*：
![image](https://github.com/apache/dubbo/assets/65932272/8e0a4525-f528-4be8-9ca3-cbb576961d75)

*debug时，发现该对象的相应参数确实没有变化*：
![image](https://github.com/apache/dubbo/assets/65932272/c5a68c2a-20e4-458a-8d99-d2a636611410)

**而奇怪的是，这个超时时间尽管显示为null，但是在测试超时时间场景时，却发现生效了**。

***求解***

**Comment by AlbumenJ** [comment]
Dubbo 版本请升级到 3.2.2 版本

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
