### ISSUE TITLE
not support ClassForName : com.support.vo.ConfigClassVO, you can config 'JSONReader.Feature.SupportClassForName', offset 47

### ISSUE THREAD

**Issue by opjklu** [apache/dubbo#12538]
not support ClassForName : com.support.vo.ConfigClassVO, you can config 'JSONReader.Feature.SupportClassForName', offset 47

**Comment by AlbumenJ** [comment]
https://dubbo.apache.org/en/docs3-v2/java-sdk/advanced-features-and-usage/security/class-check/

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
