### ISSUE TITLE
使用的dubbo3.1.1版本，服务运行一段时间后，内存溢出

### ISSUE THREAD

**Issue by lianzhichang** [apache/dubbo#12537]
# 服务运行一段时间后，CHANNEL_MAP对象过大，导致内存溢出
```java
org.apache.dubbo.remoting.transport.netty4.NettyChannel#CHANNEL_MAP
```
![image](https://github.com/apache/dubbo/assets/128453380/20ed151d-edc4-45d8-9eaa-956d41cdbea6)

**Comment by EarthChen** [comment]
请升级到最新版本，已经进行过修复

**Comment by icodening** [comment]
ref #12202
