### ISSUE TITLE
dubbo 2.7.16版本，引入dubbo-spring-boot-starter后，dubbo.provider.parameters配置被覆盖

### ISSUE THREAD

**Issue by xinchengzezhi** [apache/dubbo#12533]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.16
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. springBoot项目，引入dubbo-spring-boot-starter后，-Ddubbo.provider.parameters[dubbo.saas.group]=saas配置无法注册到nacos,@DubboService注解的形式可以生效，项目中去掉dubbo-spring-boot-starter后也可以生效，猜测应该是dubbo本身的机制与starter包互相有覆盖
2.不确定这算不算bug

```

**Comment by AlbumenJ** [comment]
2.7.x is EOL. Please try upgrade to 3.x to see if there are still any question.

**Comment by xinchengzezhi** [comment]
升级为3.x问题依然存在，最后发现可能是dubbo跟feign包那里有冲突，把项目中所有的feign包都去掉之后，问题得到解决，具体原因不详
