### ISSUE TITLE
dubbo2.6.4消费端调用接口完成后，jvm没有退出

### ISSUE THREAD

**Issue by simonaries** [apache/dubbo#12541]
![image](https://github.com/apache/dubbo/assets/42372497/33899321-fac0-4468-bf0f-7cfb682c2ace)
dubbo2.6.4消费端调用接口完成后，jvm没有退出
如图，通过JProfiler发现还有dubbo的线程在等待，但是奇怪的是我再另外一台电脑上运行相同的代码时，不会出现这样的问题。

**Comment by AlbumenJ** [comment]
看一下这些线程的状态，如果是守护线程是不会阻塞 jvm 退出的

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
