### ISSUE TITLE
dubbo配置的问题

### ISSUE THREAD

**Issue by wzkris** [apache/dubbo#12549]
![](https://user-images.githubusercontent.com/90759163/245652510-154dde65-07bf-49c0-bf70-cb0341ceed98.png)
这里所说的读不到的配置是指全局外部化配置吗？
![](https://user-images.githubusercontent.com/90759163/245653586-52987ec8-75ee-4c6f-ba70-6a90adb2bf32.png)
标签路由应该在哪里配置？

**Comment by AlbumenJ** [comment]
这个是日志级别的问题，第一个问题在 https://github.com/apache/dubbo/pull/12555 中修复，第二个在 https://github.com/apache/dubbo/pull/12554 中修复
