### ISSUE TITLE
关于accesslog的相关配置

### ISSUE THREAD

**Issue by liamashes** [apache/dubbo#12546]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
这里的 dubbo.accesslog 如果需要调整位置，应该怎样配置呢，试了几种方案都不太行
<img width="963" alt="image" src="https://github.com/apache/dubbo/assets/65932272/f57a8ca2-c976-4417-a906-f0ce0fdf5141">

**Comment by chickenlj** [comment]
accesslog 配置在过往有安全漏洞问题，进行了限制，必须要用 3.2.x 版本才能动态修改位置。并且在使用之前要通过 `accesslog.fixed.path=false` 主动打开允许更改文件位置才行，这个配置可以通过 application 的扩展参数等进行设置，比如：

```yaml
dubbo
  application
    parameters.accesslog.fixed.path: false
```

xml 等其他配置形式类似。

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
