### ISSUE TITLE
dubbo 3.2.2 生产者启动后 会包一大堆警告 This may be caused by condition router get providerApplication is empty

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#12540]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

![image](https://github.com/apache/dubbo/assets/31852897/6ee9e08e-aad3-48e0-a16c-39393c20d8b2)
100%复现 每次启动都有 

* Dubbo version: 3.2.2
* Operating System version: xxx
* Java version: 17
* nacos 2.2.1
* springcloud alibaba 2022-RC2

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JavaLionLi** [comment]
不清楚哪来的 是什么问题导致的 用springcloud alibaba 2021版本就没有这个警告日志

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/6e7e4fc9-8a0b-4664-9eaa-c7e232abb3de)
从注册中心拿到的地址获取不到应用名或者应用名和当前应用一样

**Comment by JavaLionLi** [comment]
> ![image](https://user-images.githubusercontent.com/9292748/246647254-6e7e4fc9-8a0b-4664-9eaa-c7e232abb3de.png) 从注册中心拿到的地址获取不到应用名或者应用名和当前应用一样

可是程序都是和 dubbo 3.1.8 版本一样的啊 升级到 3.2.2 就报这个错了回退到 3.1.8 没有任何问题

**Comment by AlbumenJ** [comment]
在 https://github.com/apache/dubbo/pull/12554 中调整了日志级别，这个是个新功能

**Comment by JavaLionLi** [comment]
> 在 #12554 中调整了日志级别，这个是个新功能

那要如何避免这个问题呢 并不清楚为啥会报这个 nacos上所有的数据都是dubbo自动推送上去的 没有做更改啊

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo/pull/12572 应该和这个有关

**Comment by AlbumenJ** [comment]
看一下Nacos 注册中心上面的数据有没有 `application` 这个 key

**Comment by JavaLionLi** [comment]
> 看一下Nacos 注册中心上面的数据有没有 `application` 这个 key

每个服务一个key都是独立的 并没有在nacos上配置
![image](https://github.com/apache/dubbo/assets/31852897/15ccb352-e9ee-48f7-be9a-868f6537af9d)

**Comment by JavaLionLi** [comment]
nacos上没有其他 application的配置了

dubbo下的application如下
![image](https://github.com/apache/dubbo/assets/31852897/003fff25-fd90-4ef1-865b-d8d2e74d32c2)

**Comment by JavaLionLi** [comment]
@AlbumenJ 我发现了问题所在 system服务对外提供了rpc实现  然后自己内部也会做rpc调用来走injvm调用  
就会出现这个警告 但是我觉得这个不应该警告吧 既然提供了injvm调用 而且有些方法是公共的 自己调用自己也无可厚非 
这样就会导致 提供了多少接口 就会报多少个警告 非常不友好 这个判断在3.1.8是没有的

**Comment by JavaLionLi** [comment]
所有的injvm调用都会导致报这个警告 那是不是意味着  injvm这种调用方式 是不可以使用的

**Comment by AlbumenJ** [comment]
@chickenlj PTAL

**Comment by AlbumenJ** [comment]
> @AlbumenJ 我发现了问题所在 system服务对外提供了rpc实现 然后自己内部也会做rpc调用来走injvm调用 就会出现这个警告 但是我觉得这个不应该警告吧 既然提供了injvm调用 而且有些方法是公共的 自己调用自己也无可厚非 这样就会导致 提供了多少接口 就会报多少个警告 非常不友好 这个判断在3.1.8是没有的

如果是这样的话，这个日志是需要优化下

**Comment by JavaLionLi** [comment]
这个优化了嘛
