### ISSUE TITLE
Serialization can be negotiated using id to improve performance.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#1256]
When user set `serialization="hessian2"`, use corresponding id internally.

**Comment by diecui1202** [comment]
@chickenlj Could u pls. describe it with more details?

**Comment by chickenlj** [comment]
Firstly, this is a performance tuning task.
Dubbo internally have a name-id mapping for each serialization implementation, for example, hessian - 2
fastjson - 6

What I suggest is, use serialization id instead of name whenever we need to negotiate serialization between Provider and Consumer.
1. the URL registered to the registry.
2. payload on the wire during an RPC.

**Comment by chickenlj** [comment]
At present, I think it's no big deal whether we are using serialization name or id. Considering the tasks we have on hand, we can tune it later.
