### ISSUE TITLE
dubbo Prometheus配置问题

### ISSUE THREAD

**Issue by zixiaolu** [apache/dubbo#12573]
## dubbo Prometheus如何正确配置Prometheus的http自动发现以及暴露对应的metrics
工程中使用API形式配置的Metrics
![image](https://github.com/apache/dubbo/assets/66407243/0dcc79f7-7664-4c68-a473-76f8fdb0e3f8)
地址是按照官方文档中设定的使用dubbo-admin作为中间件
注入的Prometheus应该是读取了对应的配置，但是dubbo-admin那边也没有发现有对应的服务发现部分的代码，Prometheus端请求dubbo-admin也没有正常读取。
![image](https://github.com/apache/dubbo/assets/66407243/45a15a5c-82ec-4f3e-92fa-22056f0f1b1a)

这边请教一下如何正确的进行配置调通

**Comment by songxiaosheng** [comment]
@sjmshsh

**Comment by sjmshsh** [comment]
目前dubbo-admin的Golang版本还有很多需要完善，不过针对您的问题，您可以看看这个路径下的代码。pkg/admin/router/router.go，里面有一个路由:	router.GET("/api/:env/metrics/prometheus", handlers.PromDiscovery)，这个路由就是用来暴露http_sd的。目前我们暂时没有提供让用户灵活配置端口的功能。监控端口写死成了22222，在这个包下您可以看到相关的程序：pkg/admin/util/monitor_utils.go。也就是说您需要保证您的应用暴露给Prometheus的端口是22222，如果不是这个端口，那么暂时无法获取到您需要的。

**Comment by zixiaolu** [comment]
> 指标端口复用了QOS端口，你那边能直接借助普罗米修斯发现指标地址即可，端口和path可以目前需要先固定 ，dubbo admin是有个接口可以用 @sjmshsh 帮看下，感谢

固定的Prometheus通过QOS调通了，辛苦

**Comment by zixiaolu** [comment]
> monitor_utils.go。也就是说您需要保证您的应用暴露给Prometheus的端口是22222，如果不是这个端口，那么暂时无法获取到您需

辛苦，我这边根据tips查看develop分支下的dubbo-admin是Java版本的，develop分支下的是还没有实现这个自动发现的功能吗

**Comment by sjmshsh** [comment]
> > monitor_utils.go。也就是说您需要保证您的应用暴露给Prometheus的端口是22222，如果不是这个端口，那么暂时无法获取到您需
> 
> 辛苦，我这边根据tips查看develop分支下的dubbo-admin是Java版本的，develop分支下的是还没有实现这个自动发现的功能吗

Java版本的dubbo-admin没有提供http_sd服务发现的功能，Golang版本的提供了，但是Golang版本的dubbo-admin现在还在建设中，很多功能不稳定。

**Comment by zixiaolu** [comment]
> > > monitor_utils.go。也就是说您需要保证您的应用暴露给Prometheus的端口是22222，如果不是这个端口，那么暂时无法获取到您需
> > 
> > 
> > 辛苦，我这边根据tips查看develop分支下的dubbo-admin是Java版本的，develop分支下的是还没有实现这个自动发现的功能吗
> 
> Java版本的dubbo-admin没有提供http_sd服务发现的功能，Golang版本的提供了，但是Golang版本的dubbo-admin现在还在建设中，很多功能不稳定。

好的了解了，感谢
