### ISSUE TITLE
Dubbo3架构中涉及到很多Modle，但是像FrameworkModel中的internalApplicationModel，ApplicationModel中的internalModuleModel的用途是啥，为什么不和defaultXXModel合并呢？

### ISSUE THREAD

**Issue by shaonianxingzhong** [apache/dubbo#12603]
Dubbo3架构中涉及到很多Modle，但是像FrameworkModel中的internalApplicationModel，ApplicationModel中的internalModuleModel的用途是啥，为什么不和defaultXXModel合并呢？

**Comment by shaonianxingzhong** [comment]
求大佬们解答~~

**Comment by songxiaosheng** [comment]
我的理解是框架内部用的可以与外部的应用程序模模型隔离开，相当于两个互不干扰的容器(不知道对不)

**Comment by liufeiyu1002** [comment]
`internalApplicationModel`供 `dubbo`内置的服务使用 ， 如 `MetadataService`等   与外部程序模型应用级别的隔离

**Comment by AlbumenJ** [comment]
internal 是给框架内部用的，default 是给用户用的
