### ISSUE TITLE
关于GenericService 泛化调用 接口有多个接口实现类     应该如何指定接口实现类的问题

### ISSUE THREAD

**Issue by xwq111222** [apache/dubbo#12609]
测试环境：
jdk：18
dubbo：2.7.5
这是我的方法：
  public GenericService getGenericService(String serverName, Class<?> clazz) {
        ApplicationConfig application = new ApplicationConfig();
        ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
        application.setName(serverName);
        // 弱类型接口名
        reference.setInterface(clazz);
        RegistryConfig registry = new RegistryConfig();
        registry.setAddress(dubboConfig.getRegistryAddress());
        // 注册
        application.setRegistry(registry);
        // 声明为泛化接口
        reference.setGeneric("true");
        reference.setApplication(application);
        return reference.get();
  }
问题：clazz有多个实现类，想通过application指定对应的接口实现类，但是失效，请问应该怎么调用指定的接口实现类

**Comment by xwq111222** [comment]
有多个消费者，可以通过什么来指定消费者

**Comment by AlbumenJ** [comment]
ApplicationConfig 和调用是没有关系的呀

**Comment by AlbumenJ** [comment]
Dubbo 服务调用只会按照 接口 + 版本号 + 分组 去唯一区分服务

**Comment by xwq111222** [comment]
好的明白了谢谢
