### ISSUE TITLE
J2oVisitor throws inconsistent exceptions

### ISSUE THREAD

**Issue by tohidemyname** [apache/dubbo#12615]
end() throws IllegalStateException although its header declares ParseException.  The other methods like objectItemValue and arrayItemValue throw ParseException. objectBegin throw both exceptions:

 public void objectBegin() throws ParseException {
     ...
try {
                    mValue = mType.newInstance();
                } catch (Exception e) {
                    throw new IllegalStateException(e.getMessage(), e);
                }
    ...
ry {
                mValue = mType.newInstance();
                mWrapper = Wrapper.getWrapper(mType);
            } catch (IllegalAccessException | InstantiationException e) {
                throw new ParseException(StringUtils.toString(e));
            }
}

It is quite confusing.

**Comment by AlbumenJ** [comment]
Would you pls submit a PR to fix?

**Comment by tohidemyname** [comment]
Here is the pull request:https://github.com/apache/dubbo/pull/12676

As the methods declare that they can throw ParseException, I revised all thrown IllegalStateExceptions to ParseExceptions.

**Comment by CrazyHZM** [comment]
@tohidemyname 
Is there any progress?

**Comment by tohidemyname** [comment]
I am sorry, but I am catching several paper deadlines. I can work on these bugs next month.

**Comment by CrazyHZM** [comment]
This issue should not exist in version 3.x.

**Comment by tohidemyname** [comment]
I have submitted a pull request to the master branch. 
https://github.com/apache/dubbo/pull/12676/commits/13efd64708902bd9ef56071dd8de6ef6cee17187

I also checked 3.2, but this version does not have J2oVisitor.java. This issue does not affect 3.x.
