### ISSUE TITLE
why apache FilterNode use alibba Filter

### ISSUE THREAD

**Issue by vacuityv** [apache/dubbo#12616]
I met an error when i use dubbo 2.7.15:
<img width="970" alt="image" src="https://github.com/apache/dubbo/assets/13598237/a053dd30-4763-4ed1-a25c-55358481c18f">

why this happened, it should use apache filter

**Comment by songxiaosheng** [comment]
兼容低版本的逻辑，新版本应该都有优化完善

**Comment by AlbumenJ** [comment]
因为 DubboSofaTracerFilter 实现的是 alibaba 的 Filter 接口

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
