### ISSUE TITLE
consumer 端 RpcContext.getServiceContext().getRemoteAddressString()  返回 null

### ISSUE THREAD

**Issue by WangXiaoJin** [apache/dubbo#12631]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.2
* Operating System version: Win10
* Java version: 1.8

### Steps to reproduce this issue

consumer端的Filter中执行 `RpcContext.getServiceContext().getRemoteAddressString()` 返回null，**2.5.7**版本中是可以通过
`com.alibaba.dubbo.rpc.RpcContext#getRemoteAddressString()` 获取 provider 地址的。在**3.2.2**版本中设置`RemoteAddress`逻辑比较滞后

### Expected Behavior

期望在consumer端可以通过`RpcContext.getServiceContext().getRemoteAddressString()` 、`RpcContext.getServiceContext().getRemoteApplicationName()` 获取 对端服务信息

### Actual Behavior

实际现象是consumer端获取信息返回null，在provider端可以成功获取

**Comment by xixingya** [comment]
hello, RpcContext.getServiceContext().getRemoteAddressString()是可以正常获取值的，RpcContext.getServiceContext().getRemoteApplicationName()这个确实拿不到
