### ISSUE TITLE
metrics API returen without metric dubbo_provider_requests_failed_total

### ISSUE THREAD

**Issue by wuzhuoquan** [apache/dubbo#12634]
dubbo version: 3.2.2
In my application using dubbo 3.2.2, I curl /metrics api, return without metric ```dubbo_provider_requests_failed_total```.
![image](https://github.com/apache/dubbo/assets/49891988/05366707-fc31-4729-a648-bd8e064a1c23)

But I  found the this metric description in this webside
```
https://cn.dubbo.apache.org/zh-cn/overview/reference/metrics/standard_metrics/
```

**Comment by songxiaosheng** [comment]
部分指标数据存在时候才会有，后续会提前初始化为0
