### ISSUE TITLE
Reference Level MigrationStep Logic 

### ISSUE THREAD

**Issue by iJIAJIA** [apache/dubbo#12630]
从[官方文档](https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/upgrades-and-compatibility/service-discovery/service-discovery-samples/)来看, 是支持Reference级别的MigrationStep配置的. 
![image](https://github.com/apache/dubbo/assets/10057108/19a1e68c-00c1-47e2-8bda-d41eb5aafa3e)

但MigrationRule会缓存首次从ConsumerURL里解析出来的migration.step. 第二个ConsumerURL进来时, 支持取的上次的解析结果. 这块有点疑惑, 是逻辑BUG 还是设计如此.

``` java
public MigrationStep getStep(URL consumerURL) {
        MigrationStep value = getValue(consumerURL, SubMigrationRule::getStep);
        if (value != null) {
            return value;
        }

        /**
         * FIXME, it's really hard to follow setting default values here.
         */
        if (step == null) {
            // initial step : APPLICATION_FIRST
            step = MigrationStep.APPLICATION_FIRST;
           // 这里会缓存上次解析结果
            step = Enum.valueOf(MigrationStep.class,
                consumerURL.getParameter(MIGRATION_STEP_KEY, getDefaultStep(consumerURL, step.name())));
        }

        return step;
    }
```

**Comment by AlbumenJ** [comment]
下面这块是为了设置一个默认值呀

**Comment by iJIAJIA** [comment]
step = Enum.valueOf(MigrationStep.class,
                consumerURL.getParameter(MIGRATION_STEP_KEY, getDefaultStep(consumerURL, step.name())));
看逻辑这里才会去ReferenceConfig里获取migration.step这个参数值, 缓存之后下一个ReferenceConfig里获取的就是上个ReferenceConfig里的值了. 目前这边有个场景是部分Reference需要声明FORCE_APPLICATION, 不使用默认的APPLICATION_FIRST.

**Comment by AlbumenJ** [comment]
Fix in https://github.com/apache/dubbo/pull/13237
