### ISSUE TITLE
Dubbo Proxy Mesh模式下，负载均衡能力是istio实现的，还是Dubbo自身实现的

### ISSUE THREAD

**Issue by spurstong** [apache/dubbo#12645]
是否会调用Dubbo本身的loadbalance.select方法进行负载均衡

**Comment by AlbumenJ** [comment]
thinsdk 会使用dubbo 的，sidecar 会使用 envoy 的

**Comment by spurstong** [comment]
Dubbo-Sample项目的dubbo-samples-mesh-k8s中的thinsdk.png的内容是这个，
![image](https://github.com/apache/dubbo/assets/17487735/b01ab98b-41b3-4a98-a4dd-21ba8b812c1c)
这个不是sidecar模式吗，那thinsdk模式是哪个，是proxyless mesh模式吗

**Comment by AlbumenJ** [comment]
thinsdk 就是 sidecar 模式

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
