### ISSUE TITLE
application-first 时，reference 上指定的参数失效

### ISSUE THREAD

**Issue by stonelion** [apache/dubbo#12640]
当配置 application-first 时，reference 上指定的参数失效。

<img width="747" alt="image" src="https://github.com/apache/dubbo/assets/5867317/9c6699bb-6778-4d05-a151-74c9e0a08cc5">

如上图，method 内指定的 cache 不生效。

dubbo 版本: 3.1.8

**Comment by AlbumenJ** [comment]
cache、timeout 这些在 provider 都有指定了吗

**Comment by stonelion** [comment]
> cache、timeout 这些在 provider 都有指定了吗

没有指定。配置在方法级别内的 timeout，retry，同样也是无法生效的。

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/7a66451e-371c-42ac-bc66-e7c8695937c6)
![image](https://github.com/apache/dubbo/assets/9292748/89924781-9cc1-4487-9c50-bd9179abab1d)
![image](https://github.com/apache/dubbo/assets/9292748/63702c4a-133c-40b3-979a-634946705be0)

我试着配了下超时是生效的

**Comment by stonelion** [comment]
@AlbumenJ 超时和 retry、timeout  是使用 getMethodParameter()，这个方法是有转换读取 consumer url 上的配置。主要是 getAnyMethodParameter 没有读取 consumer url 上的配置，导致使用这个方法的 filter 都不可用。

**Comment by AlbumenJ** [comment]
getAnyMethodParameter 哪个参数会通过这个获取呢

**Comment by stonelion** [comment]
<img width="1195" alt="image" src="https://github.com/apache/dubbo/assets/5867317/fb76eee5-94b3-4c75-b434-43c5aaa1bd9b">
@AlbumenJ
