### ISSUE TITLE
Metircs: I think the requestBeforeEvent in metrics may be redundant and needs to be optimized.

### ISSUE THREAD

**Issue by RapperCL** [apache/dubbo#12654]
"RequestBeforeEvent" is a type of "RequestEvent" (FORBIDDEN_EXCEPTION) and should not be created as a new class as it is redundant and difficult to maintain. 
我认为requestBeforeEvent属于requestEvent的一种场景， 不应该单独创建一个类，有点多余

If it is necessary to separately monitor this type of event,  it is recommended to add the constant "INVOCATION_REQUEST_BEFORE" and provide the "isRequestBeforeEvent" method.

RequestBeforeEvent属于RequestEvent的一种（访问限制），不应该新建一个类，过于冗余且不易维护，如果需要单独监听这种类型的事情，建议通过添加常量INVOCATION_REQUEST_BEFORE，并提供isRequestBeforeEvent方法即可，

forexample: 
 add constant: 
新增常量：
![image](https://github.com/apache/dubbo/assets/44110731/a1e22fa1-c1e8-4894-9a1b-29cb1c918953)
Add the toRequestBeforeEvent method：
新增RequestBeforeEvent结构体方法：
![image](https://github.com/apache/dubbo/assets/44110731/1b21520e-afd1-4250-9b14-439481f30ae2)
新增判断方法：
Add  the isRequestBeforeEvent method:
![image](https://github.com/apache/dubbo/assets/44110731/9494af6e-b6c9-4be9-ab21-cc8f4b8c6229)

**Comment by songxiaosheng** [comment]
多个类型 vs 多个常量
