### ISSUE TITLE
dubbo provider cannot reconnect service without registry center since 3.2.1

### ISSUE THREAD

**Issue by yinqingzhun** [apache/dubbo#12658]
Description:
a dubbo provider project with springboot invokes dubbo service, defining referenced service like this:
```
 @DubboReference( check = false,url = "tri://localhost:50051")
 private HelloService helloService;
```

The consumer repeatedly calls the service with a delay of one second after each call.
```
 @Scheduled(fixedDelay = 1000)
    public void run() {
        String message = helloService.sayHello("lucky");
        System.out.println(message);
    }
```
key config items in  application.properties like this :
```
 dubbo.registry.address: N/A
```

Question:
The above code can run normally in dubbo-3.1.7, when starting the service consumer first, and then starting the service provider. At 3.2.1, the service consumer could not successfully reconnect to the service provider. 
According to the source code, the implementation of the ConnectionListener class, which is responsible for reconnecting, has changed. The number of connection references in the code changed from positive to 0, causing the logic to terminate early. Why is that？

Partial Code of Reconnection:

**Comment by yinqingzhun** [comment]
dubbo-3.2.1
NettyConnectionClient.ConnectionListener
 if (connectionClient.isClosed() || connectionClient.getCounter() == 0) {
    return;
}

dubbo-3.1.7
org.apache.dubbo.remoting.api.Connection.ConnectionListener
 if (conn.isClosed() || conn.refCnt() == 0) {
return;
}

**Comment by AlbumenJ** [comment]
@icodening @EarthChen PTAL
