### ISSUE TITLE
add metrics collect judgment  

### ISSUE THREAD

**Issue by RapperCL** [apache/dubbo#12665]
AggregateMetricsCollector need add  metrics collect judgment  
(org.apache.dubbo.metrics.collector.AggregateMetricsCollector#collect)
![image](https://github.com/apache/dubbo/assets/44110731/35596a43-e2dc-46d2-8e4b-e7897c6db47a)

**Comment by songxiaosheng** [comment]
入口处是有开关的，这里不加会报错不

**Comment by RapperCL** [comment]
> 入口处是有开关的，这里不加会报错不

不会报错，只是这个类在收集方法collect中没有加这个开关判断（其他指标采集器在collect方法中，都添加了此开关判断）， 导致如果设置了false，还是会收集到数据。
例如DefaultMetricsService或AbstractMetricsReporter 调用此类的collect。
![image](https://github.com/apache/dubbo/assets/44110731/dd3ae23d-f57c-4c00-8b7f-ca229a4cb363)
**
![image](https://github.com/apache/dubbo/assets/44110731/a6a0311e-1793-493e-9ec1-4d24dfdb3451)
