### ISSUE TITLE
support IntelliJ IDEA use icon which we can click to navigate to the corresponding autowired dependency

### ISSUE THREAD

**Issue by yuhaowin** [apache/dubbo#12662]
Support IntelliJ IDEA use ![The autowired dependencies icon](https://resources.jetbrains.com/help/img/idea/2023.1/spring.icons.gutter.showAutowiredDependencies.svg) in the gutter, which we can click to navigate to the corresponding autowired dependency.

<img width="1035" alt="Xnip2023-07-04_13-39-57" src="https://github.com/apache/dubbo/assets/34699768/b1adee5a-70f1-4ca1-97c6-15d576ddf826">

**Comment by chickenlj** [comment]
Recommend using install this plugin which supports recognition of Dubbo Beans if you are using IntelliJ IDEA: https://plugins.jetbrains.com/plugin/20938-apache-dubbo-in-spring-framework/

FYI, the IDEA team is working on adding more features to this plugin, https://plugins.jetbrains.com/plugin/20938-apache-dubbo-in-spring-framework/
