### ISSUE TITLE
3.2.3 @Cacheable 获取不到方法参数名

### ISSUE THREAD

**Issue by HelloToGithub** [apache/dubbo#12691]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.3
* Java version: 8

3.2.3 版本 MethodBasedEvaluationContext 获取到的method是Dubbo代理 导致@Cacheable 获取不到方法参数名 从而获取不到key名称 
![image](https://github.com/apache/dubbo/assets/15622677/66ef4484-dd7d-4bdb-b944-cf5e62c3fe80)

3.1.10 版本正常
![image](https://github.com/apache/dubbo/assets/15622677/2283efe4-c181-4c30-9528-cf2a6b440878)

**Comment by AlbumenJ** [comment]
这个只是完整代理了一层吧，方法名应该是一样的

**Comment by AlbumenJ** [comment]
This is just a complete proxy layer, the method name should be the same
