### ISSUE TITLE
[OSPP 2023] JSON Compatibility Check

### ISSUE THREAD

**Issue by Tomoko-hjf** [apache/dubbo#12699]
## Overview
Dubbo currently supports a large number of Java language features through the Hessian protocol in its Java SDK, such as generics and interfaces. However, these capabilities may not be compatible when making cross-system calls. Therefore, Dubbo needs to provide the ability to check interface definitions and determine whether the interfaces published by users can be described using native JSON.

## Project Deliverables
* A built-in class analysis tool in Dubbo that can automatically determine whether a class can be serialized using JSON.
* Creation of corresponding unit tests and integration tests.
* Writing of relevant design and usage documentation.

## Timeline
- [x] July 9-15: Organize all types and JSON representations for JDK 8, 11, and 17.
- [x] July 16-23: Obtain all service definitions and interface parameter objects and preliminarily complete the logic for determining whether they contain interfaces and abstract classes.
- [ ] July 24-30: Improve the determination logic, consider more incompatible situations.
- [ ] July 31-August 9: Complete the logic for displaying the results of checking whether an interface can be serialized using JSON.
- [ ] August 10-20: Address any remaining details and issues.
- [ ] August 21-30: Complete the corresponding unit tests, design principles, and usage documentation.

**Comment by AlbumenJ** [comment]
Please translate to English~ :)
