### ISSUE TITLE
dubbo2.7 调用下游的dubbo3.1.5版本找不到服务提供者？？？

### ISSUE THREAD

**Issue by gulang12** [apache/dubbo#12692]
消费者服务 dubbo2.7版本调用 下游服务提供者服务 dubbo3.1.5版本提示找不到服务提供者，但是我在注册中心已经有了服务提供者的注册中心，而且采用的是双注册的模式，这个是什么问题？？缺少什么依赖吗

Caused by: org.apache.dubbo.rpc.RpcException: No provider available from registry

**Comment by AlbumenJ** [comment]
1. check if provider has been registered into registry
2. check network is available

**Comment by hujun-w-2** [comment]
配置贴出来看看

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
