### ISSUE TITLE
metadataservice调用链路无法传递隐式参数

### ISSUE THREAD

**Issue by benko233** [apache/dubbo#12701]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
#11769 中修改为metadata proxy不加载filter，消费者无法传递隐式参数。当前我们项目通过在dubbo filter中设置attachment来传递认证token，metadataservice的调用都会认证失败。想问一下metadata proxy加载filter能否改为可配置的？

**Comment by AlbumenJ** [comment]
可以看一下改造 MetadataServiceURLBuilder 来支持

**Comment by AlbumenJ** [comment]
> > 可以看一下改造 MetadataServiceURLBuilder 来支持
> 
> 目前我们的解决方案是扩展DubboProtocol，重写refer方法，构造完整的调用链路。想问一下MetadataService走所有框架默认filter是否会存在问题？ ` @Override public <T> Invoker<T> refer(Class<T> serviceType, URL url) throws RpcException { FilterChainBuilder builder = ScopeModelUtil.getExtensionLoader(FilterChainBuilder.class, url.getScopeModel()).getDefaultExtension(); return builder.buildInvokerChain(super.refer(serviceType, url), REFERENCE_FILTER_KEY, CommonConstants.CONSUMER); }`

有一些 FIlter 是不期望加载到 `MetadataService` 的，所以才禁止加载默认 Filter 的
