### ISSUE TITLE
关于 dubbo-serialization-fastjson 几个依赖的区别疑问？

### ISSUE THREAD

**Issue by houkunlin** [apache/dubbo#12711]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

在 central.sonatype.com 上搜索 dubbo-serialization-fastjson 发现有四个 groupId 的依赖 https://central.sonatype.com/search?q=dubbo-serialization-fastjson&smo=true 想问一下这几个依赖的区别。Dubbo 3 应该用哪个依赖？

- `pkg:maven/com.alibaba/dubbo-serialization-fastjson`
- `pkg:maven/org.apache.dubbo/dubbo-serialization-fastjson`
- `pkg:maven/org.apache.dubbo/dubbo-serialization-fastjson2`
- `pkg:maven/org.apache.dubbo.extensions/dubbo-serialization-fastjson`

![image](https://github.com/apache/dubbo/assets/12333292/4fbc0efb-3b3a-486e-b7ec-4f1099fb8b28)

**Comment by xm101** [comment]
如果是dubbo3 建议pkg:maven/org.apache.dubbo/dubbo-serialization-fastjson2

com.alibaba 是阿里的坐标，org.apache.dubbo是apache开源的坐标，社区版本取org.apache.dubbo
fastjson2和fastjson几乎可以算是不同的2个框架，大版本，差异较大，dubbo3支持的是fastjson2
extensions顾名思义是扩展
