### ISSUE TITLE
zookeeper dubbo.registry.session 设置无用  无法设置zk的session 超时时间

### ISSUE THREAD

**Issue by qijun4tian** [apache/dubbo#12718]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.2
* Operating System version: windows&linux
* Java version: 8

### Steps to reproduce this issue

1. 启动程序
2. AbstractZookeeperTransporter  会设置ConfigCenterConfig 的 的zkclient
```
        if ((zookeeperClient = fetchAndUpdateZookeeperClientCache(addressList)) != null && zookeeperClient.isConnected()) {
            logger.info("find valid zookeeper client from the cache for address: " + url);
            return zookeeperClient;
        }
      
```
之后MetadataReport 会设置zk
zookeeper://xxx:2181/org.apache.dubbo.metadata.report.MetadataReport?application=aaa&client=&file-cache=true&port=2181&protocol=zookeeper&timeout=300000

之后RegistryService 会设置zk 
zookeeper://xxx:2181/org.apache.dubbo.registry.RegistryService?application=aaa&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=org.apache.dubbo.registry.RegistryService&pid=16296&register-mode=interface&release=3.2.2&session=180000&timeout=300000

由于上面的代码 xxx:2181 已经存在zkclient 无法设置session 超时时间

**Comment by qijun4tian** [comment]
dubbo.registry.address = zookeeper://172.16.9.102:2181?timeout=300000&session=180000 
只能这么设置

**Comment by AlbumenJ** [comment]
I don't quite understand it. Now it means that the configuration of the session is invalid. Can you provide a complete demo?

**Comment by ilaotan** [comment]
大家有没有遇到过用zk当注册中心，启动巨慢的情况？ 用127.0.0.1:2181倒是挺快，linux布的zk 3.8  慢的一批，非要加timeout才能启动成功
