### ISSUE TITLE
dubbo3.0自定义拦截器报错 No such extension xxx  filter/org.apache.dubbo.rpc.Filter,org.apache.dubbo.rpc.cluster.filter.ClusterFilter

### ISSUE THREAD

**Issue by mumuyuanbao** [apache/dubbo#12755]
在融合dubbo3.0项目
自定义拦截器filter的时候，META-INF.dubbo.internal已经配置org.apache.dubbo.rpc.Filter
定义
<img width="679" alt="image" src="https://github.com/apache/dubbo/assets/48817421/5df17f48-bfcc-4a97-8e80-5d42f2ebd011">
启动的时候会报错 No such extension 
追踪了一下报错代码
<img width="973" alt="image" src="https://github.com/apache/dubbo/assets/48817421/9cba66e7-e453-477b-8698-338f94c1dc76">

而 Arrays.asList(Filter.class, ClusterFilter.class)，自己在本包下定义的拦截器无法注入了
<img width="1095" alt="image" src="https://github.com/apache/dubbo/assets/48817421/ae91c79c-e17c-4558-a7d4-7e7e7697a753">

**Comment by AlbumenJ** [comment]
1. Check whether META-INF/dubbo/internal is a standard third-level directory. Under idea, the first level may become the folder META-INF.dubbo/
2. Check whether the corresponding interface implements the Filter interface
3. It still doesn’t work. Provide a demo after desensitization

**Comment by flanet88** [comment]
![filter](https://github.com/apache/dubbo/assets/40165957/059e1588-047c-4744-bb55-96e5d3a98d5d)

![filter1](https://github.com/apache/dubbo/assets/40165957/4966eb55-bc0e-4e25-b1d8-3b9c97a0a580)
I don't know why

**Comment by flanet88** [comment]
![Uploading filter2.png…]()

**Comment by flanet88** [comment]
![filter2](https://github.com/apache/dubbo/assets/40165957/5f116fc1-1ac2-4b93-9751-83aa46777e05)
filter

**Comment by zcmm1314** [comment]
遇到相同的问题请问这个问题解决了吗
