### ISSUE TITLE
服务暴露时为什么都要添加这个Deployer.start逻辑呢？

### ISSUE THREAD

**Issue by shaonianxingzhong** [apache/dubbo#12753]
ServiceConfig->export()中为什么要加 getScopeModule().getDeployer().start()这句呢？
<img width="490" alt="1689666678430" src="https://github.com/apache/dubbo/assets/126050530/f45a3910-e007-4fae-a618-8a03efcbb08c">
请大佬帮忙解答下这句解决的问题场景？

**Comment by shaonianxingzhong** [comment]
> 

@songxiaosheng 发布器的初始逻辑，为什么要放在serviceConfig里？是不是因为DubboBootstrap的启动逻辑的原因

**Comment by shaonianxingzhong** [comment]
> 发布器是Dubbo初始化的逻辑，比如初始化三大中心的连接数据交互，启动时的服务发现等初始化操作

@songxiaosheng 启动逻辑已经在Module start触发，不明白为什么还在ServcieConfig-服务暴露时再次触发？ 有其他场景需要吗？

**Comment by songxiaosheng** [comment]
这个pr 你可以研究下,应该是有人提前调用了export未初始化会有问题:
https://github.com/apache/dubbo/pull/9083
