### ISSUE TITLE
JVM cannot exit when Spring Boot Application Start Fail

### ISSUE THREAD

**Issue by caimofei** [apache/dubbo#12758]
### Environment

* Dubbo version: 2.7.13
* Operating System version: MAC OS(arm)
* Java version: JDK 11

### Steps to reproduce this issue

1. Create a Spring Boot Application With Dubbo Spring Boot Starter 
2. Change application config to make the application can not start successfully.such as delete the datasource.url config
3. start the application . then log will report the application start fail, but the JVM cannot exit.

**Comment by caimofei** [comment]
I have test 2.7.8--2.7.23. Having the same problem.

**Comment by caimofei** [comment]
I have test 2.7.8--2.7.23. Having the same problem.

**Comment by caimofei** [comment]
I have test 2.7.8--2.7.23. Having the same problem.<br/>2.7.7 is ok.

**Comment by EarthChen** [comment]
2.7x is eol. pls upgrade 3.x
