### ISSUE TITLE
when uses annotations to expose service, Dubbo3's component scanning processes are inconsistent with dubbo2, resulting in an incompatibility issue when upgrade it

### ISSUE THREAD

**Issue by LCFeng666** [apache/dubbo#12762]
the core Java class using to expose annotation service is ServiceAnnotationBeanPostProcessor in dubbo2，but it turns to ServiceAnnotationPostProcessor in dubbo3.  our programs has heavy use of ServiceAnnotationBeanPostProcessor in dubbo2, so it is very troublesome to upgrade.

**Comment by AlbumenJ** [comment]
Not sure how the differences between the two affect you

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
