### ISSUE TITLE
关于 @Service 注解日志警告的问题

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#12765]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

![6MJU8B7(S{ID~1IHN}U(@ W](https://github.com/apache/dubbo/assets/31852897/c424399e-b890-427d-acd0-e8f839a0f57e)
现在都用 @DubboService 注解了 然而每次启动还会报 @Service 扫描不到的警告 这是不是有点非必要啊

**Comment by AlbumenJ** [comment]
Could you pls submit a PR to fix it?

**Comment by JavaLionLi** [comment]
> Could you pls submit a PR to fix it?

不知该如何修复 老注解如果兼容的话 扫描还是得做的 但是确实目前没有使用这个注解了 都已经换成新注解了
可是如果使用新注解 就会报老注解扫描不到 有点矛盾啊

**Comment by JavaLionLi** [comment]
目前已经都3.2.X版本了 是否有考虑将老注解的相关实现处理都删除掉呢
