### ISSUE TITLE
服务升级到dubbo3版本后，代码使用 CompletableFuture报空指针？？

### ISSUE THREAD

**Issue by gulang12** [apache/dubbo#12760]
![image](https://github.com/apache/dubbo/assets/26455814/4d147238-494a-4123-a4fe-0c1f47117150)

![image](https://github.com/apache/dubbo/assets/26455814/6bd60945-5c53-4dc5-8370-547f1bacc5b8)

**Comment by AlbumenJ** [comment]
这个 NullPointer 是 Provider 端抛出来的，需要找下对应的堆栈

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
