### ISSUE TITLE
通过外部配置文件的“dubbo.application.qos-enable=false”配置来关闭QOS不生效

### ISSUE THREAD

**Issue by ldcsaa** [apache/dubbo#12779]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.4
* Operating System version: win10
* Java version: 17

### Steps to reproduce this issue

1. 启动dubbo服务时加入JVM参数：-Ddubbo.properties.file=/data/dubbo/dubbo.properties
2. /data/dubbo/dubbo.properties 中配置：dubbo.application.qos-enable=false
3. 检查 QOS端口是否打开（已打开）
4. 通过监控地址：http://localhost:9002/actuator/dubbo/properties
 查看 qos-enable 属性（true）
```
{
	"dubbo.application.name": "hp-demo-infra-service",
	"dubbo.application.organization": "HP-Socket",
	"dubbo.application.owner": "Kingfisher",
	"dubbo.application.qos-enable": "true",
	"dubbo.application.qos-port": "7002",
	"dubbo.application.version": "0.0.1-SNAPSHOT",
	"dubbo.config.multiple": "true",
	"dubbo.properties.file": "/data/dubbo/dubbo.properties",
	"dubbo.protocol.name": "dubbo",
	"dubbo.protocol.port": "6002",
	"dubbo.registry.file": "/data/dubbo/.cache/dubbo-registry_hp-demo-infra-service.properties",
	"dubbo.resolve.file": "/data/dubbo/dubbo-resolve.properties",
	"dubbo.scan.base-packages": "com.github.hpsocket.demo"
}
```

而通过JVM参数：“-Ddubbo.application.qos-enable=false”，或在 application.yml 中定义 ”dubbo.application.qos-enable: false”，配置是生效的。

**Comment by ldcsaa** [comment]
进过多次尝试，得出结论，dubbo.properties 配置文件中，以下定义可以关闭QOS：
```
dubbo.application.qosEnable=false
```

但以下定义不能关闭QOS：
```
dubbo.application.qos-enable=false
```

两个定义本质上应该是一样的，最好能修复一下。

**Comment by AlbumenJ** [comment]
Would you pls submit a PR to fix it?
