### ISSUE TITLE
dubbo3.0.9并发发起RPC调用，Hessian2ObjectInput.readObject  空指针异常

### ISSUE THREAD

**Issue by gulang12** [apache/dubbo#12775]
![image](https://github.com/apache/dubbo/assets/26455814/65a07c17-0167-4a6f-938e-3ca95dadc76d)
![image](https://github.com/apache/dubbo/assets/26455814/469cde37-b032-42cb-af82-8affd2b947ac)

**Comment by AlbumenJ** [comment]
可以提供一个独立的 demo 我们验证下吗

**Comment by gulang12** [comment]
> 可以提供一个独立的 demo 我们验证下吗

CompletableFuture<List<MinutesData>> futureBf = CompletableFuture.completedFuture(new ArrayList<>());
CompletableFuture<List<MinutesData>> futureAf = CompletableFuture.completedFuture(new ArrayList<>());


futureBf = CompletableFuture.supplyAsync(() -> {
	return queryBfMinuteKline();
});

futureAf = CompletableFuture.supplyAsync(() -> {
	return queryAfMinuteKline();
});

 public List<MinutesData> queryBfMinuteKline() {
     // RPC调用
     List<MinutesData>  list = serviceA.getBfMinuteKline();
     return list;
 }

 public List<MinutesData> queryAfMinuteKline() {
     // RPC调用
     List<MinutesData>  list = serviceA.getAfMinuteKline();
     return list;

 }

 CompletableFuture.allOf(futureBf, futureAf).join();  // 报序列化异常错误

@AlbumenJ   看以试一下上面的列子

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/95bccdc4-dd89-4183-bf88-84ea4f8390cb)
我测试了下是没问题的

**Comment by gulang12** [comment]
> ![image](https://user-images.githubusercontent.com/9292748/259322519-95bccdc4-dd89-4183-bf88-84ea4f8390cb.png) 我测试了下是没问题的

接口返回的实体类是实现了这些接口的，实体类  implements Serializable, Cloneable, Comparable<T>
会不会是这个原因 @AlbumenJ

**Comment by AlbumenJ** [comment]
> > ![image](https://user-images.githubusercontent.com/9292748/259322519-95bccdc4-dd89-4183-bf88-84ea4f8390cb.png) 我测试了下是没问题的
> 
> 接口返回的实体类是实现了这些接口的，实体类 implements Serializable, Cloneable, Comparable 会不会是这个原因 @AlbumenJ

这几个接口没问题的
