### ISSUE TITLE
dubbo3.0.9服务启动错误信息Failed to save service store file,cause:null什么原因？？

### ISSUE THREAD

**Issue by gulang12** [apache/dubbo#12807]
![image](https://github.com/apache/dubbo/assets/26455814/63481333-8867-4619-9c20-a74ff51bc823)

**Comment by songxiaosheng** [comment]
用的3.1.0好像没遇到这个问题，用之前的版本启动时候遇过

**Comment by AlbumenJ** [comment]
This may caused by file is already locked. Please check if other dubbo process is running.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
