### ISSUE TITLE
Dubbo-version : 3.2.2   KeeperErrorCode = NodeExists

### ISSUE THREAD

**Issue by QinHao12138** [apache/dubbo#12808]
* similiar problem url:  https://github.com/apache/dubbo/issues/11077;
 * exception stack:
 org.apache.zookeeper.KeeperException.create(KeeperExcep...2023-07-28 08:35:48.092 WARN  [DubboRegistryRetryTimer-thread-1]                   org.apache.dubbo.registry.retry.FailedRegisteredTask:?   - traceId:[]  [DUBBO] Failed to execute task retry register, url: consumer:///com.*.*RpcService?application=*-*&category=consumers&check=false&dubbo=2.0.2&release=3.2.2&version=1.0.0, waiting for again, cause:Failed to register consumer://*.*.*.*/com.perRpcService?application=*&category=consumers&check=false&dubbo=2.0.2&release=3.2.2&version=1.0.0 to zookeeper zookeeper://&dubbo=2.0.2&executor-management-mode=isolation&extra-keys=ocean_tag&file-cache=true&interface=org.apache.dubbo.registry.RegistryService&pid=1&qos.enable=true&release=3.2.2&serialize.check.status=WARN&simplified=true, cause: KeeperErrorCode = NodeExists f...2023-07-28 08:35:58.091 WARN  [DubboRegistryRetryTimer-thread-1]     org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient:?   - traceId:[]  [DUBBO] ZNode /dubbo/c/consumers/consumer%3A%2F%%2Fcom.pingpongx.meta.localuser.v2.rpc.UserRpcService%3Fapplication%3Dmeta-api%26category%3Dconsumers%26check%3Dfalse%26dubbo%3D2.0.2%26release%3D3.2.2%26version%3D1.0.0 already exists., dubbo version: 3.2.2, current host:, error code: 1-35. This may be caused by , go to https://dubbo.apache.org/faq/1/35 to find instructions.

**Comment by AlbumenJ** [comment]
May fixed in #12740
