### ISSUE TITLE
dubbo3 不再支持sofaRegistry了吗？

### ISSUE THREAD

**Issue by fsx379** [apache/dubbo#12810]
问题1：dubbo3 不再支持sofaRegistry了吗？
问题2：dubbo2.7 使用注册中心 sofaRegistry，有适配的管理后台吗，用于做服务治理，例如调整权重等

**Comment by liufeiyu1002** [comment]
[https://github.com/apache/dubbo-spi-extensions](https://github.com/apache/dubbo-spi-extensions)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
