### ISSUE TITLE
Nacos is the registration center, the configured 【dubbo.config-center.group】 property is invalid

### ISSUE THREAD

**Issue by guangweifan** [apache/dubbo#12829]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2
* Operating System version: windows 11
* Java version: temium-17

### Steps to reproduce this issue

1. Use nacos as the configuration center.【Spring Boot 2.7.8 + Nacos 2.2.2】
2. Modifily application.properties 
    ```
    dubbo.application.name=NmsApplication
    dubbo.config-center.address=nacos://192.168.123.197:8848
    dubbo.config-center.namespace=dubbo3
    dubbo.config-center.group=dubbo3
    dubbo.config-center.app-config-file=nacos-config-example.properties
    ```
3.The 'group' attribute used in the configuration refers to the application name. which results in the 'group' value for the configuration with 'dubbo3' being empty
![image](https://github.com/apache/dubbo/assets/25050623/7c64067b-4bf9-4090-9ec0-6c27d898a979)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
configService.getConfig("dubbo3", "dubbo3", nacosTimeout)

### Actual Behavior
configService.getConfig("dubbo3", "NmsApplication", nacosTimeout)

**Comment by AlbumenJ** [comment]
Same with https://github.com/apache/dubbo/issues/12824.

Recommend to use `namespace`

**Comment by guangweifan** [comment]
疑惑点是使用nacos作为配置中心的前提下， 应用特有外部化配置。配置了namespace和group，但是实际情况group并没有使用配置的group值，而是读取了namespace下group值默认为dubbo.application.name的相关配置文件。
