### ISSUE TITLE
使用dubbo-3.2.4时，使用rest时，不能使用多个path相同而method不同的方法

### ISSUE THREAD

**Issue by tell1014** [apache/dubbo#12831]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.4
* Operating System version: win11
* Java version: java 8

### Steps to reproduce this issue

代码：
`@Path("users")
@Consumes({ContentType.APPLICATION_JSON_UTF_8})
@Produces({MediaType.APPLICATION_JSON})
public interface UserService {

    @GET
    Response getUsers();

    @POST
    Response createUser(Object user);

}`

比如：GET /users时，返回service require request method is : POST, but current request method is: GET

看了一下源码，org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper.getRestMethodMetadata()和PathMatcher.equals()。。。

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL
