### ISSUE TITLE
dubbo 3.24 not support none serializable class org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper

### ISSUE THREAD

**Issue by mnshun** [apache/dubbo#12840]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

Dubbo version: 3.2.4
Operating System version: Linux 4.19.91-685c634.al7.x86_64
Java version: 17.0.3

### Steps to reproduce this issue

1. A服务提供dubbo rest AInterface接口
2. B服务提供 dubbo 接口 BInterface接口
3. AInterface 中调用 BInterface
4. 通过rest调用AInterface 接口，会提示not support none serializable class org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper

原因是：
<img width="1895" alt="image" src="https://github.com/apache/dubbo/assets/12005228/adfd35f4-b10f-442e-8c37-89a6fe09292e">

<img width="1799" alt="image" src="https://github.com/apache/dubbo/assets/12005228/36a1e00c-0d27-4f74-ac98-ac8866a254fb">

org.apache.dubbo.rpc.protocol.rest.handler.NettyHttpHandler#handle 
org.apache.dubbo.rpc.protocol.rest.PathAndInvokerMapper

1、需要将PathAndInvokerMapper实现序列化
2、为什么要把PathAndInvokerMapper添加到ServerAttachment中，目前debug看这些信息和请求上下文都是无关的，是否可以不传递
<img width="1772" alt="image" src="https://github.com/apache/dubbo/assets/12005228/6df6d815-add8-4cbe-8dcd-b1c7b122b573">

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL
