### ISSUE TITLE
升级到3.2.5之后 启动速度变慢 

### ISSUE THREAD

**Issue by HelloToGithub** [apache/dubbo#12875]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
升级到3.2.5之后 启动速度变慢 
这是3.2.4启动的时间 52s
![image](https://github.com/apache/dubbo/assets/15622677/615ad449-cffd-4359-acef-c766b5842998)

修改为3.2.5之后的时间 93s
![image](https://github.com/apache/dubbo/assets/15622677/d94176da-0aad-44d2-b3a4-4cdf82a5b0d1)

**Comment by AlbumenJ** [comment]
可以用 Arthas 从启动开始到结束打一下 profiler 热点图吗

**Comment by HelloToGithub** [comment]
通过对比发现 3.2.5下 在应用要启动完成的时候 再次调用了 DefaultModuleDeployer.onModuleStarting
具体调用链信息如下
![image](https://github.com/apache/dubbo/assets/15622677/5fbeb9d0-2c4d-4c1a-9ef8-8cfc85e45381)

**Comment by AlbumenJ** [comment]
> 通过对比发现 3.2.5下 在应用要启动完成的时候 再次调用了 DefaultModuleDeployer.onModuleStarting


这个如果启动过了，应该再次启动会很快的呀

**Comment by HelloToGithub** [comment]
看着应该是把之前onModuleStarting走过的 再次走了一遍 时间差不多

![image](https://github.com/apache/dubbo/assets/15622677/26fd6aec-7153-42c9-b152-260d3e3d7453)

**Comment by AlbumenJ** [comment]
> 看着应该是把之前onModuleStarting走过的 再次走了一遍 时间差不多
> 
> ![image](https://user-images.githubusercontent.com/15622677/259685979-26fd6aec-7153-42c9-b152-260d3e3d7453.png)

日志里面的好事还是毫秒级的呀

**Comment by HelloToGithub** [comment]
嗯 虽然每一条都是毫秒级 但是registry多的话 也是耗时的 请问为何3.2.5在应用要启动完成的时候 再次调用了 DefaultModuleDeployer.onModuleStarting 而3.2.4貌似不会

**Comment by AlbumenJ** [comment]
> 嗯 虽然每一条都是毫秒级 但是registry多的话 也是耗时的 请问为何3.2.5在应用要启动完成的时候 再次调用了 DefaultModuleDeployer.onModuleStarting 而3.2.4貌似不会

你可以退回下老版本执行 curl http://127.0.0.1:22222/ls 看下是不是对比新版本少了一些接口

**Comment by AlbumenJ** [comment]
如果是少了的话那就是老版本存在一些 ReferenceBean 没有加载，这些 Bean 会延迟到具体调用之前才初始化（就影响调用速度），现在 3.2.5 切换成启动的时候就全部加载了

关联 PR #12697

**Comment by HelloToGithub** [comment]
> 如果是少了的话那就是老版本存在一些 ReferenceBean 没有加载，这些 Bean 会延迟到具体调用之前才初始化（就影响调用速度），现在 3.2.5 切换成启动的时候就全部加载了
> 
> 关联 PR #12697

明白 经过验证 确实如您所说
