### ISSUE TITLE
triple自定义异常被统一封装成StateRpcException

### ISSUE THREAD

**Issue by james-ok** [apache/dubbo#12884]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
同样的接口，使用dubbo协议发布和triple协议发布，当调用到triple协议接口时，自定义异常被封装成了StateRpcException，而调用dubbo协议接口时，一切正常

**Comment by AlbumenJ** [comment]
使用的什么版本

**Comment by james-ok** [comment]
版本：3.1.8，这个问题我换3.2.5已解决
