### ISSUE TITLE
[3.x] offline instance can't removed from invoker list

### ISSUE THREAD

**Issue by YoungHu** [apache/dubbo#12887]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Bug description
3.0.12版本为修复一些问题，接口级订阅的时候增加一个带冒号和不带冒号实例合并的逻辑。
![image](https://github.com/apache/dubbo/assets/7418602/c25bdd07-4967-468c-807f-d567d96f6134)
如果不带冒号的服务订阅事件通知下来，即使实例为0，按照下面的逻辑，会错误的更新实例信息和带冒号的一样。这个时候因为后面会做ip合并不会有问题，但是在容器环境下，所有节点重启后ip变了，不带冒号的又不会有通知就一直老的实例信息，最后合并出来的就是带有新+老的所有实例，然后导致失败的情况出现。
![image](https://github.com/apache/dubbo/assets/7418602/f46a935f-015b-42ed-bcb5-294eb0cc7a3b)
这是一个偶发问题，主要的原因是消费者订阅是先拉取实例信息，这个时候nacos异步产生的事件会在下面截图这里return掉，因为还没有执行registerLisenter，map为空。但是有个例外情况就是如果异步事件执行的非常慢，registerLisenter是会先执行完的，顺序点到后异步事件就能顺利的往下执行。引发我们上面说的问题。
![image](https://github.com/apache/dubbo/assets/7418602/d4e47b19-07a6-458f-bfda-b978b9b23f39)
![image](https://github.com/apache/dubbo/assets/7418602/7147d439-de63-489f-8099-bc597c1a1247)

### Environment

* Dubbo version: 3.0.12
* Operating System version: mac os, linux
* Java version: JDK8

### Steps to reproduce this issue
复现也比较简单
1. 提供者启动3个pod节点
2. 在onevent这里打线程级断点
3. 本地启动消费者的应用
4. 断点进来以后不用管，等待应用启动完成
5. 释放断点继续执行完事件通知
6. 销毁提供者的3个pod，重新新建3个，ip地址要求全换掉
7. 看应用的日志，发现interface url size显示有6个。其中3个无法正常使用

**Comment by AlbumenJ** [comment]
这个应该修复过了，可以升级到 3.1.x 的最新版本试一下

**Comment by AlbumenJ** [comment]
Fix in #10949

**Comment by AlbumenJ** [comment]
> > Fix in #10949
> 
> 我看#10949标记里程碑里面有3.0.13，但是我在3.0.13里面没有看到这个修复的版本，麻烦把这个fix合并到3.0分支打个release出来

合并这个 PR 的时候 3.0.x 版本已经不维护 bugfix 了，所以不会在 3.0.x 版本上发 bugfix 版本了

**Comment by YoungHu** [comment]
> > > Fix in #10949
> > 
> > 
> > 我看#10949标记里程碑里面有3.0.13，但是我在3.0.13里面没有看到这个修复的版本，麻烦把这个fix合并到3.0分支打个release出来
> 
> 合并这个 PR 的时候 3.0.x 版本已经不维护 bugfix 了，所以不会在 3.0.x 版本上发 bugfix 版本了

我看在这之后还有3.0.14和3.0.15的版本出来啊，另外看release记录3.1.x每次release都有较多的bugfix，不敢升啊。

**Comment by AlbumenJ** [comment]
> > > > Fix in #10949
> > > 
> > > 
> > > 我看#10949标记里程碑里面有3.0.13，但是我在3.0.13里面没有看到这个修复的版本，麻烦把这个fix合并到3.0分支打个release出来
> > 
> > 
> > 合并这个 PR 的时候 3.0.x 版本已经不维护 bugfix 了，所以不会在 3.0.x 版本上发 bugfix 版本了
> 
> 我看在这之后还有3.0.14和3.0.15的版本出来啊，另外看release记录3.1.x每次release都有较多的bugfix，不敢升啊。

3.0.14、3.0.15 都是安全修复。至于 release note 里面的 bugfix 是取决于社区活跃度和发版周期的，作为一个软件存在问题是不可避免的，如果一个版本发布以后没有新的修复很可能是本身没有活跃度了
至于担心迭代中引入的新问题，目前社区已经在尽可能地控制在小版本迭代中不引入有风险的修改，feature 都会往最新的 beta 分支合并，因此每个大版本的最新小版本是可以比较稳定的使用的

**Comment by YoungHu** [comment]
> > > > > Fix in #10949
> > > > 
> > > > 
> > > > 我看#10949标记里程碑里面有3.0.13，但是我在3.0.13里面没有看到这个修复的版本，麻烦把这个fix合并到3.0分支打个release出来
> > > 
> > > 
> > > 合并这个 PR 的时候 3.0.x 版本已经不维护 bugfix 了，所以不会在 3.0.x 版本上发 bugfix 版本了
> > 
> > 
> > 我看在这之后还有3.0.14和3.0.15的版本出来啊，另外看release记录3.1.x每次release都有较多的bugfix，不敢升啊。
> 
> 3.0.14、3.0.15 都是安全修复。至于 release note 里面的 bugfix 是取决于社区活跃度和发版周期的，作为一个软件存在问题是不可避免的，如果一个版本发布以后没有新的修复很可能是本身没有活跃度了 至于担心迭代中引入的新问题，目前社区已经在尽可能地控制在小版本迭代中不引入有风险的修改，feature 都会往最新的 beta 分支合并，因此每个大版本的最新小版本是可以比较稳定的使用的

既然社区不愿意在3.0基础上做bugfix，短期我们自己使用patch的方式解决遇到的问题并反馈社区，待3.1趋于稳定再决定是否升级吧。实话实说使用3.0一年多来升级一个小版本解决A问题，引入新的B问题，3.0.3->3.0.5->3.0.7->3.0.10->3.0.12历经5次升级，社区已经意识到控制小版本迭代风险是一个很好的开始，希望且也坚信后续会越来越稳定。
