### ISSUE TITLE
No provider available from registry问题咨询

### ISSUE THREAD

**Issue by a108843035** [apache/dubbo#12893]
dubbo 版本：3.2.2
nacos版本：阿里云mse 2.1.2.2
在我们测试环境中从dubbo2.7.0版本升级至3.2.2版本后，业务服务经常出现No provider available from registry。
再和阿里云mse相关人员交涉以及跟踪nacos日志以后，nacos推送日志都很正常。
后续发现应用服务有oom重启的问题，但是服务重启以后为什么会出现找不到消费者的情况。
相关nacos日志如下：
2023-08-14 12:56:56,907 首次注册10.168.8.166 
2023-08-14 12:56:57.698 客户端收到10.168.8.166 
2023-08-14 13:08:39,639 注销 
2023-08-14 13:08:40.472 客户端收到注销
2023-08-14 13:09:41,505 再次注册
2023-08-14 13:09:42.109 客户端收到
其中13:09再次注册时后还是有报错，并且没有将新的节点注册上来
org.apache.dubbo.rpc.RpcException: No provider available from registry XXXXXX for service com.wuuxiang.ic.output.interfaces.item.IItemReadRpc:1.0.0 on consumer 10.168.9.160 use dubbo version 3.2.2, please check status of providers(disabled, not registered or in blacklist).

[naming.log](https://github.com/apache/dubbo/files/12332092/naming.log)
[config.log](https://github.com/apache/dubbo/files/12332093/config.log)
[remote.log](https://github.com/apache/dubbo/files/12332096/remote.log)

**Comment by AlbumenJ** [comment]
在 No Provider 的时候 curl http://127.0.0.1:22222/ls 查看对应服务存在地址，另外最好提供下 Dubbo 的日志，以便排查 Dubbo 的推送处理的情况

**Comment by a108843035** [comment]
> 在 No Provider 的时候 curl http://127.0.0.1:22222/ls 查看对应服务存在地址，另外最好提供下 Dubbo 的日志，以便排查 Dubbo 的推送处理的情况
好,我们这边增加以下qos以及dubbo日志的输出。复现后在沟通

**Comment by a108843035** [comment]
@AlbumenJ 这是调用方的dubbo日志,并且出现了no provider的问题
[wuuxiang-ic-insideapi_DUBBO_2023-08-14.0.log](https://github.com/apache/dubbo/files/12333231/wuuxiang-ic-insideapi_DUBBO_2023-08-14.0.log)

**Comment by a108843035** [comment]
我这边又复现了一下，日志都在附件内，这个时候一直是找不到服务
[QOS.txt](https://github.com/apa
[ERROR.txt](https://github.com/apache/dubbo/files/12334131/ERROR.txt)
che/dubbo/files/12334130/QOS.txt)
[wuuxiang-ic-insideapi_DUBBO_2023-08-14.0.log](https://github.com/apache/dubbo/files/12334133/wuuxiang-ic-insideapi_DUBBO_2023-08-14.0.log)

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/c86ed4c3-8a69-441a-a20b-99574d1e839b)
这个服务的 1.0.0 版本看起来就是没有地址的，有地址的是 2.0.0 的

检查下 1.0.0 的是哪个机器发布的，2.0.0 的是哪个机器发布的

**Comment by a108843035** [comment]
> ![image](https://user-images.githubusercontent.com/9292748/260955905-c86ed4c3-8a69-441a-a20b-99574d1e839b.png) 这个服务的 1.0.0 版本看起来就是没有地址的，有地址的是 2.0.0 的
> 
> 检查下 1.0.0 的是哪个机器发布的，2.0.0 的是哪个机器发布的
现在现象是这样的。测试环境服务分配内存不大，触发了k8s的oom killer，这时候我们的服务相当于强制重启了，所以这时候nacos通过心跳检测到服务下线，推送给了调用方。这时候的没有服务是正常，但是后续这台机器在不改变地址端口的情况下又启动起来并且通知到nacos上线。我在观察调用方日志来看也收到了这个服务上线的推送，但是后续调用还是无提供方

**Comment by a108843035** [comment]
这边把dubbo版本升级到3.2.5就没在复现这个问题了

**Comment by trust-freedom** [comment]
https://github.com/apache/dubbo/pull/12484 应该是这个问题导致的，我们遇到了一样的no provider available的情况。

当consumer请求provider1时，由于ThreadlessExecutor的问题导致请求线程被hang住，在ReferenceCountInvokerWrapper#invoke时会有读锁，当provider1下线时，consumer收到通知做destroy操作，ReferenceCountInvokerWrapper#destroy需要写锁，由于请求线程的读锁无法释放导致refresh操作线程也被卡死，这样当任何和当前dubbo service相关的provider2、3等等上下线时，都无法被consumer感知到，因为refresh线程还被卡着。

这个问题在 3.2.3版本被修复。
