### ISSUE TITLE
dubbo提供简单的注册中心实现

### ISSUE THREAD

**Issue by Eason-YC-Huang** [apache/dubbo#12919]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature
dubbo提供简单的注册中心实现

优点:
 - 新手更友好, 更容易写Demo, 无需了解什么例如nacos, zookeeper
 - 有时候有些个人项目, 功能比较简单, 但是想用到dubbo, 就需要额外维护一个注册中心, 比较麻烦

例如可以让服务提供者或者消费者也作为注册中心
```
// 启动注册中心
DubboBootstrap.getInstance().simpleRegistryCentry().start(8090);

// 定义所有的服务
ServiceConfig<GreetingsService> service = new ServiceConfig<>();
service.setInterface(GreetingsService.class);
service.setRef(new GreetingsServiceImpl());

// 启动 Dubbo
DubboBootstrap.getInstance()
        .application("first-dubbo-provider")
        .registry(new RegistryConfig("localhost:8090"))
        .protocol(new ProtocolConfig("dubbo", -1))
        .service(service)
        .start();
```

**Comment by EarthChen** [comment]
demo 的话建议用直连，dubbo 提供注册中心是不合适的

**Comment by songxiaosheng** [comment]
是想要基于局域网自动服务发现的模型？

**Comment by icodening** [comment]
直连或dns或许能满足你的需求。
https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-registry-extensions/dubbo-registry-dns

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
