### ISSUE TITLE
triple 协议不兼容 grpc 

### ISSUE THREAD

**Issue by s5364733** [apache/dubbo#12915]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.7
* Operating System version:  windows 11
* Java version: 1.8

### Steps to reproduce this issue

1. 服务端启动报错,使用GRPC协议
```java
Caused by: java.lang.ClassNotFoundException: io.grpc.HandlerRegistry
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 20 more


```
2. 使用triple协议启动 java 服务端，客户端go-grpc 调用报错
```java
2023/08/16 16:39:59 could not msg: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:50052: connectex: No connection could be made because the target machine actively refused it."

```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

按照官网的说法triple 协议完全兼容grpc 协议，期望可以用grpc协议和dubbo-triple协议互通，

>如果我想强行互通的话，是不是需要使用老版本的dubbo?
这样的话是不是后面没有社区支持了

**Comment by songxiaosheng** [comment]
会不会是你那边grpc版本太低了，我看grpc-api中1.57.1是有你那边缺失的类型的
<img width="844" alt="image" src="https://github.com/apache/dubbo/assets/81170548/a5da038a-a0af-4e06-b522-c7b89f866fb8">

**Comment by s5364733** [comment]
> ```java
> HandlerRegistry
> ```

请问要用什么版本，我grpc版本是1.44.1，这是sample里边的版本

**Comment by s5364733** [comment]
![image](https://github.com/apache/dubbo/assets/24503935/72bd50b8-058d-4de3-b644-9254d79ae963)
>里边已经没有GRPC的协议常量了

**Comment by AlbumenJ** [comment]
@EarthChen PTAL

**Comment by EarthChen** [comment]
triple 的 server 为什么会有 grpc 的 class 呢？  检查一下自己的依赖

**Comment by s5364733** [comment]
> triple 的 server 为什么会有 grpc 的 class 呢？ 检查一下自己的依赖

放在一个项目里边的，成功启动之后，GRPC调用 直接超时

**Comment by s5364733** [comment]
请问有没有一个案例(原生GRPC可以直接调用DUBBO triple 协议)？

**Comment by s5364733** [comment]
dubbo server 启动如下 ：<br/>

<img width="511" alt="image" src="https://github.com/apache/dubbo/assets/24503935/8783c11d-7e2b-4e26-b971-f4045cb2acc4">

grpc client 如下 ：<br/>

<img width="756" alt="image" src="https://github.com/apache/dubbo/assets/24503935/f5d15bab-b431-4f88-8c34-4d0398241f7c">

我看了sample 貌似现在都是直接用的tri 协议，没有GRPC 的案例

<img width="813" alt="image" src="https://github.com/apache/dubbo/assets/24503935/66a13271-3983-4deb-954f-98edcade47e2">

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-triple-grpc

**Comment by s5364733** [comment]
> https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-triple-grpc

我需要的是跨语言的 sample ,例如我现在使用rust 或者golang 能不能和dubbo 的tri 协议互通？

**Comment by luckybins** [comment]
尝试引用grpc的bom，然后看项目实际引用的grpc的每个包的版本是否接近。我今天遇到了相同的ClassNotFound，是这么解决的

**Comment by s5364733** [comment]
> 尝试引用grpc的bom，然后看项目实际引用的grpc的每个包的版本是否接近。我今天遇到了相同的ClassNotFound，是这么解决的

能否列一下您GRPC 版本

**Comment by s5364733** [comment]
我弄好了， 这个单可以关了，感谢各位

**Comment by s5364733** [comment]
GRPC原生互通 JAVA服务端必须以stream的定义，我改了下，貌似可以了
