### ISSUE TITLE
when try a Generic invoke in triple Protocol, I got a error like this：Triple Server received remote reset errorCode=8

### ISSUE THREAD

**Issue by zhanghan810810** [apache/dubbo#12925]
when try a Generic invoke in triple Protocol, I got a error like this：Triple Server received remote reset errorCode=8，I not konw the
 mean and how to resolve it

  I am sure my provider is running and I can use dubbo-go invoke it ,but java can't work

		ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
		reference.setApplication(applicationConfig);
		reference.setInterface(iface);
		reference.setVersion(version);
		reference.setGeneric(true);
		reference.setTimeout(30000);
		reference.setGroup(group);
		reference.setProxy("jdk");
		reference.setUrl("tri://localhost:8889");
//		reference.setProtocol("tri");
		reference.setRetries(0);

**Comment by icodening** [comment]
@zhanghan810810 请问请求参数是不是pb类型呢？

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.

**Comment by yunweiguo** [comment]
> @zhanghan810810 请问请求参数是不是pb类型呢？

PB类型有什么问题？ 我这边也遇到了相同的错误
