### ISSUE TITLE
Through 808 acquisition platform (netty long-term connection), after parsing, call the service through dubbo, do the business logic processing of the instruction, strange that the service exists, but it reports No provider available for the service

### ISSUE THREAD

**Issue by 1728581964** [apache/dubbo#12920]
jdk version: 1.8
协议： GRPC

问题复现：
使用dubbo 3.1.6, grpc 1.54.1,protobuf version 3.21.7,启动服务端成功之后，启动consumer报错：
Failed to check the status of the service com.bh.dubbo.model.DubboDemoServiceGrpc___IDemoService. No provider available for the service com.bh.dubbo.model.DubboDemoServiceGrpc___IDemoService from the url consumer://192.168.31.163/com.bh.dubbo.model.DubboDemoServiceGrpc___IDemoService?application=dubbo-admin&background=false&dubbo=2.0.2&generic=true&interface=com.bh.dubbo.model.DubboDemoServiceGrpc___IDemoService&logger=slf4j&pid=26004&qos.port=32222&register.ip=192.168.31.163&release=3.1.6&side=consumer&sticky=false&timestamp=1691290215726&unloadClusterRelated=false to the consumer 192.168.31.163 use dubbo version 3.1.6

**Comment by CrazyHZM** [comment]
@1728581964 
Try it in the latest 3.2.x version.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
