### ISSUE TITLE
生产者，消费者调用问题

### ISSUE THREAD

**Issue by qq948702703** [apache/dubbo#12944]
请问 我生产者和消费者 dubbo:registry 配置的不同组，但是生产者调用消费者还是能调用成功，是什么原因呢

**Comment by AlbumenJ** [comment]
是否使用的 Nacos 注册中心，尽量不要用 group 隔离，可以使用 namespace 参数隔离

**Comment by goto456** [comment]
> 请问 我生产者和消费者 dubbo:registry 配置的不同组，但是生产者调用消费者还是能调用成功，是什么原因呢

是使用的Dubbo 3.0.x版本吧，这个版本中nacos的regist.group不生效，到3.1.x版本才修复这个bug。

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
