### ISSUE TITLE
服务端突然断网、断电，客户端无法进行故障转移

### ISSUE THREAD

**Issue by flying-2077** [apache/dubbo#12945]
dubbo 版本 3.2.4

实验过程：服务端关闭网络，节点在15min内不会从nacos平台消失。导致consumer仍然能够拿到invoder，此时客户端如果能判断服务端invoker不能连接，就会从全局的invoker列表中剔除该invoker，执行故障转移。但是dubbo consumer 在服务端突然断网后，判断连接仍然存在，导致无法剔除invoker，无法进行故障转移。

问题：针对服务端突然断电、断网，是否是应为tcp链接无法正常断开，导致consumer判断连接失效？

<img width="916" alt="image" src="https://github.com/apache/dubbo/assets/139483558/38486a89-695a-4792-83a6-51f783f5abf2">

**Comment by AlbumenJ** [comment]
目前 Dubbo 是基于心跳的模式测试与 Provider 的连接性，默认是 1 分钟一个心跳，如果 3 次失败就会摘连接。如果需要缩短摘除时间可以配置 dubbo.protocol.heartbeat=10000 缩短到 10s 心跳，预期 30s 就能恢复

**Comment by flying-2077** [comment]
如果心跳检测的时间是10s，那么我理解在服务端A突然断电10s后，invoker.isAvailable = false，从而将服务A的invoker移除，但是经过测试，从断网到节点从nacos上彻底消失，期间持续15min，经过debug发现，在这15min内，invoker.isAvailable = true，导致客户端无法移除invoker，不清楚这是什么情况？
强调下，这个测试是突然断网和断电下测试的，nacos上服务居然停留了15min

**Comment by AlbumenJ** [comment]
> 如果心跳检测的时间是10s，那么我理解在服务端A突然断电10s后，invoker.isAvailable = false，从而将服务A的invoker移除，但是经过测试，从断网到节点从nacos上彻底消失，期间持续15min，经过debug发现，在这15min内，invoker.isAvailable = true，导致客户端无法移除invoker，不清楚这是什么情况？ 强调下，这个测试是突然断网和断电下测试的，nacos上服务居然停留了15min @AlbumenJ

1. Nacos 摘除是 Nacos 本身的心跳配置的，这个需要修改 Nacos 的长连接的配置

**Comment by AlbumenJ** [comment]
1. Nacos 的配置需要问下 Nacos 社区了
2. Triple 协议目前确实不支持，需要 #12955 完善，Dubbo 协议是可以的

**Comment by flying-2077** [comment]
多谢了，等待修复后，我们会再次验证

**Comment by flying-2077** [comment]
@icodening @AlbumenJ 2018年8月博客提出的dubbo协议心跳改进点，在2023年8月的triple协议上实现了https://cn.dubbo.apache.org/zh-cn/blog/2018/08/19/dubbo-%e7%8e%b0%e6%9c%89%e5%bf%83%e8%b7%b3%e6%96%b9%e6%a1%88%e6%80%bb%e7%bb%93%e4%bb%a5%e5%8f%8a%e6%94%b9%e8%bf%9b%e5%bb%ba%e8%ae%ae/
