### ISSUE TITLE
dubbo 2.7.22 + nacos 2.1.0 使用zone不生效

### ISSUE THREAD

**Issue by Meedly** [apache/dubbo#12940]
参考了 #9679 #9673

调用链路：

consumer双发现，注册2个nacos地址

dubbo:
  registries:
    nacosA:
      address: nacosA
      zone: nacosA
      group: nacosA
      cluster: failsafe

    nacosB:
      address: nacosB
      zone: nacosB
      group: nacosB
      cluster: failsafe

现象：
启用cluster: failsafe时，会进行AbstractClusterInvoker.doSelect进行二选一，后续无法进入ZoneAwareClusterInvoker使用zone过滤

当不使用cluster: failsafe时，会进入ZoneAwareClusterInvoker，但是clusterInovker.isAvailable均为false

**Comment by AlbumenJ** [comment]
Please try on 3.2.5. 2.7.x is no longer maintained.

**Comment by Meedly** [comment]
经过排查，目前发现是多注册中心情况下
invoker-> cachedInvoker会被覆盖，导致实际该注册中心下的节点不属于自己，截止到2.7.22未修复

**Comment by CrazyHZM** [comment]
@Meedly 
Does it still exist in 3.2.x?

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
