### ISSUE TITLE
dubbo3.2.1默认使用fastjson2序列化，序列化报错UnsupportedOperationException

### ISSUE THREAD

**Issue by 237chenhao** [apache/dubbo#12942]
### Environment

* Dubbo version: 3.2.1
* Operating System version: mac
* Java version: 17
* nacos: 2.2.1

参数对象中有泛型和枚举，泛型实际传递的是Map：
![image](https://github.com/apache/dubbo/assets/12470925/7bbd8dfa-52d3-41a9-b4f9-cc5144389236)
进行RPC调用时报序列化错误：
![image](https://github.com/apache/dubbo/assets/12470925/d0cbff1e-3f61-438b-be7f-69773481c4eb)

**Comment by AlbumenJ** [comment]
手动指定下 fastjson2 版本试试看 https://github.com/alibaba/fastjson2/releases/tag/2.0.39

如果还不行的话在 https://github.com/alibaba/fastjson2/issues/new/choose 提交 issue

**Comment by 237chenhao** [comment]
debug调试看了1个小时的源码，深不见底呀，问题应该是出在com.alibaba.fastjson2.writer.ObjectWriterCreatorASM类
![image](https://github.com/apache/dubbo/assets/12470925/1968acba-b9f6-4dea-83fa-ab18dd495006)
最终返回的是FieldWriterObject类，FieldWriterObject并没有实现方法writeEnumJSONB
![image](https://github.com/apache/dubbo/assets/12470925/01fe3c6e-7e69-46cb-afa7-27fcc1b7d00e)

**Comment by 237chenhao** [comment]
> 手动指定下 fastjson2 版本试试看 https://github.com/alibaba/fastjson2/releases/tag/2.0.39
> 
> 如果还不行的话在 https://github.com/alibaba/fastjson2/issues/new/choose 提交 issue

跑隔壁fastjson2提了issue，问题已解决，https://github.com/alibaba/fastjson2/issues/1805
