### ISSUE TITLE
一致性hash的预热

### ISSUE THREAD

**Issue by axin3892** [apache/dubbo#12946]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
负载均衡策略里random等策略可以根据权重来预热，一致性hash不受权重影响，它有预热的方案吗，不然采用一致性hash的服务每次启动流量都直接打满了；是否能够根据虚拟节点个数来调节呢

**Comment by AlbumenJ** [comment]
预热本身就是需要基于多机器来分配流量的，而一致性哈希的这个和预热是冲突的，所以无法使用权重模式

**Comment by axin3892** [comment]
预热和一致性hash两者能够兼得吗； 比如服务稳定运行时虚拟节点设置为160个，启动预热阶段的虚拟节点则是从1逐渐增加到160个，这种思路是否有可行性呢，绕过权重值转而以虚拟节点数来实现

**Comment by AlbumenJ** [comment]
> 预热和一致性hash两者能够兼得吗； 比如服务稳定运行时虚拟节点设置为160个，启动预热阶段的虚拟节点则是从1逐渐增加到160个，这种思路是否有可行性呢，绕过权重值转而以虚拟节点数来实现

这样会导致一致性哈希的效果劣化的，甚至可能导致缓存失效的

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
