### ISSUE TITLE
2.6.7version调用3.0.12version每隔三分钟关闭连接重新建连

### ISSUE THREAD

**Issue by cainiaork** [apache/dubbo#12957]
* Dubbo version: consume：2.6.7  provide：3.0.12
* Operating System version: centos
* Java version: 1.8.0

consumer：c.a.dubbo.remoting.transport.netty4.NettyClient:103 -  [DUBBO] Close old netty channel [id: 0x1cfa9d9a, L:/*.*.*.*:63702 ! R:/*.*.*.*:20886] on create new netty channel [id: 0xb822e703, L:/*.*.*.*:63970 - R:/*.*.*.*:20886], dubbo version: 2.6.7, current host: *.*.*.*

provier: o.a.d.r.t.n.NettyServerHandler -  [DUBBO] IdleStateEvent triggered, close channel NettyChannel [channel=[id: 0x4e50b0ee, L:/*.*.*.*:port - R:/*.*.*.*:port]], dubbo version: 3.0.12, current host: *.*.*.*

ip用*替代了

**Comment by AlbumenJ** [comment]
Check if you have configure `heartbeat` in consumer side.

**Comment by AlbumenJ** [comment]
Please check if provider is already shutdown.

**Comment by dngzs** [comment]
这个问题没有后续吗，我也遇到了
