### ISSUE TITLE
security/serialize.allowlist is not include 'java.util.Collections$SingletonMap'

### ISSUE THREAD

**Issue by iarrived** [apache/dubbo#12959]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

资源文件security/serialize.allowlist 中包含了

java.util.Collections$SingletonSet
java.util.Collections$SingletonList

等等。唯独没有'java.util.Collections$SingletonMap‘，这是有什么特殊的安全考虑吗？

**Comment by Sherry-lsr** [comment]
give me

**Comment by CrazyHZM** [comment]
It has been added in https://github.com/apache/dubbo/pull/12962
