### ISSUE TITLE
java.lang.UnsupportedOperationException: com.alibaba.com.caucho.hessian.io.MapDeserializer

### ISSUE THREAD

**Issue by s5364733** [apache/dubbo#12958]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

消费者请求服务提供者，报错 ，版本均为2.7.7 ，两边PO均实现序列化接口，并且没有不可序列化的字段

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

正常

### Actual Behavior

Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.lang.UnsupportedOperationException: com.alibaba.com.caucho.hessian.io.MapDeserializer@31cf246f
java.lang.UnsupportedOperationException: com.alibaba.com.caucho.hessian.io.MapDeserializer@31cf246f

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by s5364733** [comment]
传输对象里边如果有枚举，枚举的名字不能带下划线分割 否则报错

**Comment by AlbumenJ** [comment]
Could you pls provide a demo?
