### ISSUE TITLE
multiple注册中心 应用级发现异常

### ISSUE THREAD

**Issue by zhengkaifor** [apache/dubbo#12975]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.10
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo接口使用@DubboReference(registrry={multiple}）
2. 增加配置dubbo.registries.multiple.address= multiple://127.0.0.1:2181?reference-registry=xxx:2181?enableEmptyProtection=false&child.a1=xxx:2181
3. 启动服务报错
<img width="754" alt="image" src="https://github.com/apache/dubbo/assets/20293800/ed203f9e-85f6-4ef1-9a64-46b5b38fdbc4">

原因：
![image](https://github.com/apache/dubbo/assets/20293800/95a838ca-0f94-4756-a78c-4f40937c70aa)
![image](https://github.com/apache/dubbo/assets/20293800/633a8c06-4497-4381-904b-5c909f8f79e9)
![image](https://github.com/apache/dubbo/assets/20293800/0da9e47d-213f-4551-b12c-8410c3c9276c)

**Comment by AlbumenJ** [comment]
Could u pls submit a PR to fix it?
