### ISSUE TITLE
Common practices of using proto in Dubbo3

### ISSUE THREAD

**Issue by Eason-YC-Huang** [apache/dubbo#12999]
In Dubbo 2, the service provider typically provides a client jar that only contains some POJOs and service interfaces. However, in Dubbo 3, we have the option to use a proto file to define services. This raises the question of whether the provider still needs to provide a client jar, or if sharing the proto file would suffice. There might be situations where the consumer either doesn't want to or cannot use the proto file and requires a client jar instead. I understand that we can place files generated from the proto file into the client jar. However, to do this, the client would need to import protobuf-java and Dubbo, which seems somewhat unusual to have these dependencies in a client jar.

**Comment by aomsir** [comment]
You cloud use proro file define services in a module named api,then dependecy the dubbo and protobuf-java.Then you can let your client module and provider module dependecy this api module，should be able to solve your doubts

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
