### ISSUE TITLE
元数据如果存放在zk，什么时候会触发清理呢

### ISSUE THREAD

**Issue by zhengkaifor** [apache/dubbo#12995]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
版本号：3.1.10
jdk：1.8
元数据如果存放在zk，什么时候会触发清理呢
我看目前存放上去的都是持久类型节点，并且在代码中未找到清理的入口

**Comment by songxiaosheng** [comment]
ZookeeperMetadataReport类 publishAppMetadata方法，不存在则创建，存在则更新，无需删除

**Comment by zhengkaifor** [comment]
> ZookeeperMetadataReport类 publishAppMetadata方法，不存在则创建，存在则更新，无需删除

那假如我的接口版本号多次变更，则zk上会遗留历史版本的元数据信息  可以这么理解吧？

**Comment by songxiaosheng** [comment]
元数据变更时集中式存储确实会有这个问题（默认配置是分布式存储），销毁时暂未清理导致多个版本元数据遗留
<img width="795" alt="image" src="https://github.com/apache/dubbo/assets/81170548/8ae245fc-7517-4eff-9922-e96774354649">
<img width="813" alt="image" src="https://github.com/apache/dubbo/assets/81170548/414689cc-bd9f-42df-83b7-896a5dbc1347">

**Comment by zhengkaifor** [comment]
> 元数据变更时集中式存储确实会有这个问题（默认配置是分布式存储），销毁时暂未清理导致多个版本元数据遗留 <img alt="image" width="795" src="https://user-images.githubusercontent.com/81170548/265402558-8ae245fc-7517-4eff-9922-e96774354649.png"> <img alt="image" width="813" src="https://user-images.githubusercontent.com/81170548/265402764-414689cc-bd9f-42df-83b7-896a5dbc1347.png">

分布式存储是否有碰到过滚动重启过程中，因为新版本的机器量少 导致拉取元数据异常日志大量出现的情况，是否有合理的参数可以规避呢
