### ISSUE TITLE
metadata目录下这两个数据节点有什么区别，分别用途是啥

### ISSUE THREAD

**Issue by shaonianxingzhong** [apache/dubbo#13008]
Dubbo3.0.9  zookeeper作为注册中心
<img width="374" alt="1693829379675" src="https://github.com/apache/dubbo/assets/126050530/22cb2bcf-2b04-4db0-abf2-ea113dffed50">
绿色目录节点数据用途是啥
红色目录节点数据是元数据

@songxiaosheng 大佬求解答

**Comment by aomsir** [comment]
- 绿色目录节点是接口级，不用理会
- 红色目录节点是当前注册的应用的元数据中心，键为元数据唯一标识，值为具体的元数据信息。元数据中心与注册中心之间的联动就是通过这个唯一标识进行的

**Comment by shaonianxingzhong** [comment]
> * 接口级

大佬，接口级那个目录用途是啥；怎么关闭它

**Comment by shaonianxingzhong** [comment]
> * 绿色目录节点是接口级，不用理会
> * 红色目录节点是当前注册的应用的元数据中心，键为元数据唯一标识，值为具体的元数据信息。元数据中心与注册中心之间的联动就是通过这个唯一标识进行的

接口级目录具体用途是啥，可以关闭它吗

**Comment by AlbumenJ** [comment]
配置 `reportDefinition=false`

**Comment by AlbumenJ** [comment]
org.apache.dubbo.config.MetadataReportConfig#reportDefinition

**Comment by aomsir** [comment]
> > * 绿色目录节点是接口级，不用理会
> > * 红色目录节点是当前注册的应用的元数据中心，键为元数据唯一标识，值为具体的元数据信息。元数据中心与注册中心之间的联动就是通过这个唯一标识进行的
> 
> 接口级目录具体用途是啥，可以关闭它吗

https://github.com/apache/dubbo/issues/13008#issuecomment-1706019135
