### ISSUE TITLE
为什么PathMatcher的getInvokeCreatePathMatcher要返回一个noNeeHttpMethodComapre(）

### ISSUE THREAD

**Issue by xhhong211** [apache/dubbo#13018]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.5
* Operating System version: Windows 11
* Java version: 1.8

### Steps to reproduce this issue

```java
 public static PathMatcher getInvokeCreatePathMatcher(String path, String version, String group, Integer port, String method) {
        return new PathMatcher(path, version, group, port, method).noNeedHttpMethodCompare();
    }
```
返回一个noNeedHttpMethodCompare的PathMatcher，造成无法通过METHOD区分不同的REST接口。

**Comment by xhhong211** [comment]
> 可以依据Method进行区分，它还有一个方法重载是要求区分的。使用这个方法不区分方法类型只是为了判断是否存在请求路径相同的接口。
---
ServiceInvokeRestFilter中的doHandler调用的是这个方法，造成现在不能通过METHOD区分请求，有什么解决方法？
```java
    private void doHandler(HttpRequest nettyHttpRequest,
                           NettyHttpResponse nettyHttpResponse,
                           RequestFacade request,
                           URL url,
                           ServiceDeployer serviceDeployer) throws Exception {
        //  acquire metadata by request
        InvokerAndRestMethodMetadataPair restMethodMetadataPair = RestRPCInvocationUtil.getRestMethodMetadataAndInvokerPair(request);

```

**Comment by CrazyHZM** [comment]
@xhhong211 
Could you try it in the latest version?

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
