### ISSUE TITLE
springboot + dubbo 启动时调用其他服务报错

### ISSUE THREAD

**Issue by xugflz2011** [apache/dubbo#13013]
## 背景:
数据库连接信息在另一个dubbo服务中,启动时初始化datasource时调用dubbo服务,报如下错误:
ReferenceBean is not ready yet, please make sure to call reference interface method after dubbo is started.

请问该如何解决呢?

**Comment by aomsir** [comment]
提个想法：能否延迟初始化，等Dubbo服务起了以后再初始化datasource

**Comment by AlbumenJ** [comment]
You can try 3.2.6 after it released.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
