### ISSUE TITLE
dubbo url update parameter but stream method parameter can not be update cause splite

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo#13022]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2 and 3.2.6-SNAPSHOT
* Operating System version:  windows 10
* Java version: jdk17

### Steps to reproduce this issue

1. set callback parameter In service url suchas  streamCallback.1.callback "methodA.1.callback = true"
2. remove another parameterkey “threadPool”
3. getmethoParameter "methodA"
4. check callbackparameter

### Expected Behavior

url can get parameter  1.callback = true  but it can not be obtain

### Actual Behavior

URL.addParameter use  limit to splite paramter 
![image](https://github.com/apache/dubbo/assets/12695349/8650334d-26c9-4f4e-ade2-90df4e3b0aa8)

but in doAddParameters()
org.apache.dubbo.common.url.component.URLParam#removeParameters

```java
\\ process without limit cause stream paramter can not be parsed
 String[] methodSplit = key.split("\\.");
                if (methodSplit.length == 2) {
                    if (newMethodParams == null) {
                        newMethodParams = new HashMap<>(METHOD_PARAMETERS);
                    }
```

If there is an exception, please attach the exception trace:

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
