### ISSUE TITLE
dubbo的ReferenceConfigCache能增加维度吗

### ISSUE THREAD

**Issue by caochengxiang** [apache/dubbo#13031]
dubbo的ReferenceCache看着只有interfaceName、group、version三个维度，这是基于哪些背景考虑，能增加多一些维度吗，比如registry等

**Comment by veenter** [comment]
一般的远程调用框架都只有interfaceName、version  group都没有。更何况registry了

通常环境下，所有的消费者和生产者都在一个注册中心内。

请描述下你的具体场景是啥

**Comment by caochengxiang** [comment]
比如有的业务用户场景是，会连两个注册中心，group和version还一样，通过页面手动触发接口调哪个nacos的provider，由于referenceCache的原因，会有一些问题。
提这个issue主要是咨询设计者当时设计Cache只用interfaceName、group、version三个维度是否有特殊考虑，没有特殊考虑的话，我可以提一个pr把更多维度加进去

**Comment by AlbumenJ** [comment]
> 比如有的业务用户场景是，会连两个注册中心，group和version还一样，通过页面手动触发接口调哪个nacos的provider，由于referenceCache的原因，会有一些问题。 提这个issue主要是咨询设计者当时设计Cache只用interfaceName、group、version三个维度是否有特殊考虑，没有特殊考虑的话，我可以提一个pr把更多维度加进去

对于有特殊需求的可以自己设计一个 ReferenceConfig 的 cache 即可

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
