### ISSUE TITLE
拦截扩展的类加载器疑问

### ISSUE THREAD

**Issue by houkunlin** [apache/dubbo#13047]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Dubbo版本：`org.apache.dubbo:dubbo-bom:3.2.5`
SpringBoot：3.1.2

根据 https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/spi/description/filter/ 文档，在使用拦截器时，无法获取 AopAspect 类中 ThreadLocal 数据，经过调试发现：

在 Controller 中 与在 Filter 中，两个 `AopAspect.class` 不是一个对象，两个 `AopAspect.LISTS` 不是同一个 ThreadLocal 对象，导致在 Filter 中无法获取到数据。

```java
@Slf4j
@Aspect
@Component
@RequiredArgsConstructor
public class AopAspect {
    /**
     * 当前请求的某个数据列表
     */
    public static final ThreadLocal<List<?>> LISTS = new ThreadLocal<>();
}

@Slf4j
@Activate(group = CommonConstants.CONSUMER, order = -10000, onClass = {OBJECT_MAPPER_CLASS_NAME})
public class MyConsumerFilter implements Filter {
    public static final String KEY = DataScope.class.getName() + "#Dubbo";

    private final ObjectMapperCodec mapper;

    public MyConsumerFilter(ApplicationModel applicationModel) {
        this.mapper = applicationModel.getBeanFactory().getBean(ObjectMapperCodec.class);
    }

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        log.info("消费者");
        Result result;
        try {
            initContext(invocation);
            result = invoker.invoke(invocation);
        } finally {
            invocation.getObjectAttachments().remove(KEY);
        }
        return result;
    }

    private void initContext(Invocation invocation) {
        // 在 Controller 中，这个是有数据的，但是在 Filter 中无法获取数据
        List<?> lists = AopAspect.LISTS.get();
        if (lists == null || lists.isEmpty()) {
            return;
        }

        String context = mapper.serialize(new MyContext(lists));

        log.info("消费者：{}", context);
        invocation.setObjectAttachment(KEY, context);
    }
}
```

在 `META-INF/dubbo/org.apache.dubbo.rpc.Filter` 文本文件中增加
```txt
MyConsumerFilter=com.houkunlin.MyConsumerFilter
```

**Comment by songxiaosheng** [comment]
说明不是一个线程，同一个线程内是一样的，可以贴一下你的线程名字么

**Comment by MingJunDuan** [comment]
threadlocal有跨线程池上下文丢失情况，查看是否存在跨线程池的情况

**Comment by houkunlin** [comment]
调试执行 `Thread.currentThread()` 看到都是同一个线程对象

下图，在 Filter 里面调试的内容
![image](https://github.com/apache/dubbo/assets/12333292/26d53078-8cd1-45f3-916e-415bc27ec0b5)

下图，在 Controller 里面调试的内容
![image](https://github.com/apache/dubbo/assets/12333292/a8e71733-b2cd-4df8-adf7-785ca6e7bb97)

**Comment by AlbumenJ** [comment]
是不是环境里面存在多个 `AopAspect.class`，对应的 class loader 是不一样的

**Comment by AlbumenJ** [comment]
Dubbo 的 Filter 默认是使用 Dubbo 的 classloader 加载的

**Comment by houkunlin** [comment]
有且只有一个 `AopAspect.class`

**Comment by AlbumenJ** [comment]
在两边分别执行 `System.identityHashCode(AopAspect.LISTS)` 看下结果是不是一样呢

**Comment by houkunlin** [comment]
`log.warn("调试 Dubbo 问题 HashCode: {}", System.identityHashCode(DataScopeAop.DATA_SCOPE_LIST));` 执行打印日志截图

![image](https://github.com/apache/dubbo/assets/12333292/a3fd94d4-ce2a-43b8-ad78-a15dbd04fc11)

**Comment by AlbumenJ** [comment]
> `log.warn("调试 Dubbo 问题 HashCode: {}", System.identityHashCode(DataScopeAop.DATA_SCOPE_LIST));` 执行打印日志截图
> 
> ![image](https://user-images.githubusercontent.com/12333292/267517449-a3fd94d4-ce2a-43b8-ad78-a15dbd04fc11.png)

如果这两个对象不一样就意味着环境里面有两个 DataScopeAop 类

**Comment by kimmking** [comment]
最开始的截图就能看出来，两个类的id不一样，一个是22718，一个是7773，说明不是一个类，存在两个不同cl加载的Aop类，导致LISTS静态对象也不是一个。

**Comment by houkunlin** [comment]
在 Controller 获取 AOP 的 classloader
![image](https://github.com/apache/dubbo/assets/12333292/2cb1cb25-0c00-432a-a5b4-99497f6f9aff)

在过滤器中获取 AOP 的 classloader
![image](https://github.com/apache/dubbo/assets/12333292/031ac8e9-e9e1-44b1-b0ff-4565f95c65a6)

**Comment by AlbumenJ** [comment]
那这个应该需要你去处理类加载器的差异，Dubbo 只能通过 TCCL 去加载你的类

**Comment by CuriousRookie** [comment]
RestartClassLoader...
把 spring-boot-devtools 去掉，或者参考[官方文档](https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.devtools.restart.customizing-the-classload)进行一些自定义？

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
