### ISSUE TITLE
使用了dubbo spring boot starter 3.2.5之后，Spring boot默认json序列化工具被设为了fastjson，请问改如何修改

### ISSUE THREAD

**Issue by JiangZhou1** [apache/dubbo#13046]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
使用了dubbo spring boot starter 3.2.5之后，Spring boot默认json序列化工具被设为了fastjson，我现在想将json序列化工具修改回Jackson，但我并没有找到相关配置，请问改如何修改
spirng boot 版本：2.6.4
dubbo spring boot starter: 3.2.5
fastjson: 2.0.40

**Comment by aomsir** [comment]
dubbo在3.2.x后将默认序列化由hessian2替换为了Fastjson2
你可以引入依赖，在dubbo配置文件中进行修改即可


https://blog.csdn.net/qq_43266723/article/details/132794546

**Comment by JiangZhou1** [comment]
> dubbo在3.2.x后将默认序列化由hessian2替换为了Fastjson2 你可以引入依赖，在dubbo配置文件中进行修改即可
> 
> https://blog.csdn.net/qq_43266723/article/details/132794546

我使用3.2.0的版本是正常的，我也去看了一下启动日志里边包含fastjson2，并且@JsonFormat注解可以正常起作用，但是当我把版本替换到3.2.0之后的任一个版本，@JsonFormat注解就失效了。

**Comment by AlbumenJ** [comment]
> > dubbo在3.2.x后将默认序列化由hessian2替换为了Fastjson2 你可以引入依赖，在dubbo配置文件中进行修改即可
> > https://blog.csdn.net/qq_43266723/article/details/132794546
> 
> 我使用3.2.0的版本是正常的，我也去看了一下启动日志里边包含fastjson2，并且@JsonFormat注解可以正常起作用，但是当我把版本替换到3.2.0之后的任一个版本，@JsonFormat注解就失效了。

`@JsonFormat` 是加在 Spring Controller 的参数里面还是 Dubbo 请求的参数里面

**Comment by JiangZhou1** [comment]
谢谢各位，我已经找到原因，由于类的泛型层级过深，在方法的返回类型上没有给出完整的泛型类型，类似这样：A<B<C>>，我是这样的A<>，在传递过程中C这一层变成了HashMap格式，也就丢失了@JsonFormat注解。在dubbo 3.2.0和之前的版本是没有这个问题的，可能是因为使用的是hessian2，而fastjson2并没有处理那么深的层级。
