### ISSUE TITLE
wireshark支持解析dubbo协议

### ISSUE THREAD

**Issue by Goddywu** [apache/dubbo#13044]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature

wireshark支持解析dubbo协议，可以快速找到一个请求的所有数据包

目前有一些难找，得找大批的数据

<img width="684" alt="image" src="https://github.com/apache/dubbo/assets/29056050/6a91fee6-872e-4bb3-84d0-b1b0b285514e">

**Comment by icodening** [comment]
当前dubbo社区没有提供这类插件，临时解决方案可以是参考着[Wireshark](https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Tvb.html)手册写一个lua插件, 协议spec可以参考[这里](https://dubbo.apache.org/zh-cn/overview/reference/protocols/tcp/).
<img width="1465" alt="image" src="https://github.com/apache/dubbo/assets/42876375/86cc9dbd-69aa-43c9-8988-2c5231482c2b">

**Comment by Goddywu** [comment]
> 当前dubbo社区没有提供这类插件，临时解决方案可以是参考着[Wireshark](https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Tvb.html)手册写一个lua插件, 协议spec可以参考[这里](https://dubbo.apache.org/zh-cn/overview/reference/protocols/tcp/). <img alt="image" width="1465" src="https://user-images.githubusercontent.com/42876375/267858275-86cc9dbd-69aa-43c9-8988-2c5231482c2b.png">

嗯嗯，之前我自己写了一个，不如你这个完善

老哥，你这边lua脚本能分享吗？🐷

**Comment by icodening** [comment]
@Goddywu 我这个也是不完整的  你可以参考着改改。
[dubbo.txt](https://github.com/apache/dubbo/files/12620811/dubbo.txt)
