### ISSUE TITLE
3.1.11稳定版本安全漏洞是否可以升级

### ISSUE THREAD

**Issue by luckytao** [apache/dubbo#13079]
dubbo和dubbo-dependencies-zookeeper-curator5中的安全漏洞问题能否升级下

**Comment by AlbumenJ** [comment]
> dubbo和dubbo-dependencies-zookeeper-curator5中的安全漏洞问题能否升级下

你是指哪些漏洞，传递依赖的？

**Comment by luckytao** [comment]
@AlbumenJ 是的

**Comment by andotorg** [comment]
I'll fix it
