### ISSUE TITLE
ReferenceConfig cannot be cast to Destroyable

### ISSUE THREAD

**Issue by ayz6uem** [apache/dubbo#13089]
![image](https://github.com/apache/dubbo/assets/11682279/2a0eee85-ee57-4ead-a287-624913282f92)

**Comment by AlbumenJ** [comment]
The result of `rc.get()` can be cast to `Destroyable`

**Comment by AlbumenJ** [comment]
org.apache.dubbo.rpc.proxy.AbstractProxyFactory#getProxy(org.apache.dubbo.rpc.Invoker<T>, boolean)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
