### ISSUE TITLE
dubbo spring xml 的xsd没有更新

### ISSUE THREAD

**Issue by libaoj1985** [apache/dubbo#13082]
http://dubbo.apache.org/schema/dubbo/dubbo.xsd
application 里没有 serialize-check-status 这个属，麻烦快点更新一下

**Comment by AlbumenJ** [comment]
官网的文档只是一个兜底文档而已，具体在 SDK 中是需要依赖 jar 提供的 xsd 为准的

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
