### ISSUE TITLE
dubbo cannot transfer Integer value to String value int the PojoUtils by gerneric

### ISSUE THREAD

**Issue by Charcla** [apache/dubbo#13095]
### Environment

* Dubbo version: 2.7.18
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. I have a gateway to receive the outside http request ,in the gateway, I receive the Map req ,one of the value in the map is Integer
2. the gateway invoke provider by the generic invoke,but the provide pojo filed is String
3. In the PojoUtils,this tranfer will thowe aexception
java.lang.RuntimeException: Failed to set pojo ApplyLoanInfoOut property projectCategory value class java.lang.Integer, cause: argument type mismatch
4. but PojoUtils can transfer String to Integer By the CompatibleTypeUtils.java
5. so can support this?

**Comment by kimmking** [comment]
can you make a test case?
