### ISSUE TITLE
dubbo invocation上下文参数透传问题

### ISSUE THREAD

**Issue by AmosWong1998** [apache/dubbo#13108]
背景描述：
希望基于dubbo.tag的路由能力实现环境隔离、流量转发的功能。下面分别写了面向Consumer和provider的两个filter来实现dubbo.tag属性在整个dubbo上下文的传递。

问题描述：
当调用链路较为复杂时，会出现invocation的attachments丢失dubbo.tag属性的情况，举个例子：
时刻1：A -> B，可以正确传递tag属性
时刻2：B -> C，可以正确传递tag属性
时刻3：B -> D 无法传递tag属性（tag丢失）

代码如下，EnvContext是ThreadLocal，用于暂存dubbo.tag字段：

生产者Filter：
```java
@Activate(group = CommonConstants.PROVIDER)
public class DubboProviderTagFilter implements Filter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        try {
            String tagValue = invocation.getAttachment(TagKeyConstants.TAG_KEY);
            if (StringUtils.isNotBlank(tagValue)) {
                EnvContext.setDubboTag(tagValue);
            }

            // 继续执行
            return invoker.invoke(invocation);
        } finally {
            // 清理上下文
            EnvContext.remove();
        }
    }
}
```
消费者Filter：
```java
@Activate(group = CommonConstants.CONSUMER)
public class DubboConsumerTagFilter implements ClusterFilter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        try {
            String tagValue = EnvContext.getDubboTag();
            // 设置到上下文中，在后续调用链路中传递
            if (StringUtils.isNotBlank(tagValue)) {
                invocation.setAttachment(TagKeyConstants.TAG_KEY, tagValue);
            }

            // 继续执行
            return invoker.invoke(invocation);
        } finally {
            // 清理上下文
            EnvContext.remove();
        }
    }
}
```
EnvContext的初始化时机，是在发起rest请求的时候，从请求头中获取前端传入的dubbo.tag字段，然后初始化EnvContext。过滤器如下：

```java
@Slf4j
public class RestTagFilter implements Filter {

    @Override
    public void init(FilterConfig filterConfig) throws ServletException {
        Filter.super.init(filterConfig);
        log.info("Web 过滤器：restTagFilter 初始化");
    }

    @Override
    public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
        EnvContext.remove();

        HttpServletRequest request = (HttpServletRequest) servletRequest;
        String tagValue = request.getHeader(TagKeyConstants.TAG_KEY);
        if (StringUtils.isNotBlank(tagValue)) {
            RequestAttributes requestAttributes = RequestContextHolder.currentRequestAttributes();
            requestAttributes.setAttribute(TagKeyConstants.TAG_KEY, tagValue, RequestAttributes.SCOPE_REQUEST);
            RequestContextHolder.setRequestAttributes(requestAttributes, true);
            // 设置tag
            EnvContext.setDubboTag(tagValue);
        }

        filterChain.doFilter(servletRequest, servletResponse);
    }

    @Override
    public void destroy() {
        Filter.super.destroy();
        log.info("Web 过滤器：restTagFilter 销毁");
    }
}
```

**Comment by liufeiyu1002** [comment]
时刻2：B -> C，可以正确传递tag属性
时刻3：B -> D 无法传递tag属性（tag丢失）

你在 时刻2 请求结束以后 在 filter中已经把 线程变量里的 内容都清理掉了，当然不会获取到值了

> 背景描述： 希望基于dubbo.tag的路由能力实现环境隔离、流量转发的功能。下面分别写了面向Consumer和provider的两个filter来实现dubbo.tag属性在整个dubbo上下文的传递。
> 
> 问题描述： 当调用链路较为复杂时，会出现invocation的attachments丢失dubbo.tag属性的情况，举个例子： 时刻1：A -> B，可以正确传递tag属性 时刻2：B -> C，可以正确传递tag属性 时刻3：B -> D 无法传递tag属性（tag丢失）
> 
> 代码如下，EnvContext是ThreadLocal，用于暂存dubbo.tag字段：
> 
> 生产者Filter：
> 
> ```java
> @Activate(group = CommonConstants.PROVIDER)
> public class DubboProviderTagFilter implements Filter {
> 
>     @Override
>     public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
>         try {
>             String tagValue = invocation.getAttachment(TagKeyConstants.TAG_KEY);
>             if (StringUtils.isNotBlank(tagValue)) {
>                 EnvContext.setDubboTag(tagValue);
>             }
> 
>             // 继续执行
>             return invoker.invoke(invocation);
>         } finally {
>             // 清理上下文
>             EnvContext.remove();
>         }
>     }
> }
> ```
> 
> 消费者Filter：
> 
> ```java
> @Activate(group = CommonConstants.CONSUMER)
> public class DubboConsumerTagFilter implements ClusterFilter {
> 
>     @Override
>     public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
>         try {
>             String tagValue = EnvContext.getDubboTag();
>             // 设置到上下文中，在后续调用链路中传递
>             if (StringUtils.isNotBlank(tagValue)) {
>                 invocation.setAttachment(TagKeyConstants.TAG_KEY, tagValue);
>             }
> 
>             // 继续执行
>             return invoker.invoke(invocation);
>         } finally {
>             // 清理上下文
>             EnvContext.remove();
>         }
>     }
> }
> ```
> 
> EnvContext的初始化时机，是在发起rest请求的时候，从请求头中获取前端传入的dubbo.tag字段，然后初始化EnvContext。过滤器如下：
> 
> ```java
> @Slf4j
> public class RestTagFilter implements Filter {
> 
>     @Override
>     public void init(FilterConfig filterConfig) throws ServletException {
>         Filter.super.init(filterConfig);
>         log.info("Web 过滤器：restTagFilter 初始化");
>     }
> 
>     @Override
>     public void doFilter(ServletRequest servletRequest, ServletResponse servletResponse, FilterChain filterChain) throws IOException, ServletException {
>         EnvContext.remove();
> 
>         HttpServletRequest request = (HttpServletRequest) servletRequest;
>         String tagValue = request.getHeader(TagKeyConstants.TAG_KEY);
>         if (StringUtils.isNotBlank(tagValue)) {
>             RequestAttributes requestAttributes = RequestContextHolder.currentRequestAttributes();
>             requestAttributes.setAttribute(TagKeyConstants.TAG_KEY, tagValue, RequestAttributes.SCOPE_REQUEST);
>             RequestContextHolder.setRequestAttributes(requestAttributes, true);
>             // 设置tag
>             EnvContext.setDubboTag(tagValue);
>         }
> 
>         filterChain.doFilter(servletRequest, servletResponse);
>     }
> 
>     @Override
>     public void destroy() {
>         Filter.super.destroy();
>         log.info("Web 过滤器：restTagFilter 销毁");
>     }
> }
> ```

**Comment by liufeiyu1002** [comment]
时刻2：B -> C，可以正确传递tag属性
时刻3：B -> D 无法传递tag属性（tag丢失）

你在 时刻2 请求结束以后 在 filter中已经把 线程变量里的 内容都清理掉了，当然不会获取到值了

**Comment by AmosWong1998** [comment]
> 时刻2：B -> C，可以正确传递tag属性 时刻3：B -> D 无法传递tag属性（tag丢失）
> 
> 你在 时刻2 请求结束以后 在 filter中已经把 线程变量里的 内容都清理掉了，当然不会获取到值了

我丢，B->C和B->D是一个线程执行的，B->C执行完会clear掉上下文，就导致B->D传递不下去了。有啥办法解决么

**Comment by liufeiyu1002** [comment]
> > 时刻2：B -> C，可以正确传递tag属性 时刻3：B -> D 无法传递tag属性（tag丢失）
> > 你在 时刻2 请求结束以后 在 filter中已经把 线程变量里的 内容都清理掉了，当然不会获取到值了
> 
> 我丢，B->C和B->D是一个线程执行的，B->C执行完会clear掉上下文，就导致B->D传递不下去了。有啥办法解决么

谁设置的谁来负责清理， consumerFilter 不需要清理啊 你不是只有 rest一个入口么 在RestTagFilter那个位置清理就行了呀。

**Comment by Linchen-Xu** [comment]
你这里目前的整体流程是这样的：
1. 收到dubbo调用，provider filter在收到请求时从attachment中解出tag放到envContext中；
2. consumer filter在对下游进行dubbo调用时把tag放入attachment，调用下游；
3. 收到下游回复或因某些问题抛异常，执行consumer filter的finally里的代码，将envContext清空；
4. 如果有其他dubbo调用，重复2-3步；
5. 给上游返回调用结果，再次清空envContext。

实际上你在第一次dubbo调用（第三步的finally）那里就把context清空了，之后的调用中都是从没有tag的context里取标签。provider filter那里的清空操作也等同于没有生效，除非在其他地方的代码里往上下文加了参数。

如果想达到你要的效果，即上下文参数在给上游返回结果前一直生效的话，就把consumer filter的finally那部分删掉，在provider filter里清空一次参数就行了。

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
