### ISSUE TITLE
triple+protobuf服务不支持泛化调用吗？泛化调用时报错：Cannot invoke "java.lang.reflect.Method.getParameterTypes()" because "method" is null

### ISSUE THREAD

**Issue by heyxhh** [apache/dubbo#13106]
定义的triple+protobuf服务，在使用泛化调用时报错：Cannot invoke "java.lang.reflect.Method.getParameterTypes()" because "method" is null；但是如果不用protobuf编码，直接使用triple协议泛化定义没问题。debug看了下，在使用Protobuf时，泛化调用取method的时候会直接返回null，代码路径：org.apache.dubbo.rpc.model.StubMethodDescriptor::getMethod.
获取method的时候直接返回null
public Method getMethod() {
        return null;
    }

**Comment by AlbumenJ** [comment]
使用的什么版本的 Dubbo

**Comment by heyxhh** [comment]
> 使用的什么版本的 Dubbo

3.2.6版本的

**Comment by AlbumenJ** [comment]
> > 使用的什么版本的 Dubbo
> 
> 3.2.6版本的

可以测试下 3.2.7 版本（准备投票，可以用 3.2 或者 3.2.7-release 分支本地 install 先），这个问题应该是修复了的

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
