### ISSUE TITLE
dubbo 3.2  branch source code dubbo-cluster build fail

### ISSUE THREAD

**Issue by andotorg** [apache/dubbo#13135]
### Environment

* Dubbo version: 3.2
* Operating System version: mac 10.15
* Java version: JDK8  or JDK 15  or JDK 17

### Steps to reproduce this issue

1. mvn clean install
2. show build error
dubbo-cluster build fail

### Actual Behavior

If there is an exception, please attach the exception trace:
error log 
```
Please refer to /Users/lucas/github/dubbo/dubbo-cluster/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.�
```
�

**Comment by AlbumenJ** [comment]
Try use `./mvnw clean install -Dmaven.test.skip=true`.

Unit test cases are very very complexed and easy to fail on local env(due to network and so on). :)

**Comment by andotorg** [comment]
Skipping tests is certainly possible, but is there any other way to fix it? Unit tests can be executed normally

**Comment by AlbumenJ** [comment]
Which case failed?

**Comment by andotorg** [comment]
I'm checking it too, and I'll fix it after I find it.

**Comment by andotorg** [comment]
`public static String getInterfaceName(Invocation invocation) {
        if (invocation.getServiceModel() != null && invocation.getServiceModel().getServiceMetadata() != null) {
            return invocation.getServiceModel().getServiceMetadata().getServiceInterfaceName();
        } else {
            String serviceUniqueName = invocation.getTargetServiceUniqueName();
            String interfaceAndVersion;
            String[] arr = serviceUniqueName.split(PATH_SEPARATOR);
            if (arr.length == 2) {
                interfaceAndVersion = arr[1];
            } else {
                interfaceAndVersion = arr[0];
            }
            String[] ivArr = interfaceAndVersion.split(GROUP_CHAR_SEPARATOR);
            return ivArr[0];
        }
    }`


Cannot invoke "String.split(String)" because "serviceUniqueName" is null

**Comment by andotorg** [comment]
fix method
```java
if (StringUtils.isBlank(serviceUniqueName)) {
                return "";
            }
            String[] arr = serviceUniqueName.split(PATH_SEPARATOR);
```

**Comment by andotorg** [comment]
[ERROR]   ScriptStateRouterTest.testRouteHostFilter:121 » IllegalState unsupported route engine type: javascript
[ERROR]   ScriptStateRouterTest.testRoutePickInvokers:80 » IllegalState unsupported route engine type: javascript
[ERROR]   ScriptStateRouterTest.testRouteReturnAll:59 » IllegalState unsupported route engine type: javascript
[ERROR]   ScriptStateRouterTest.testRoute_throwException:139 » IllegalState unsupported route engine type: javascript

**Comment by andotorg** [comment]
@AlbumenJ   Can you help me see if it can be merged?

**Comment by andotorg** [comment]
> fix method
> 
> ```java
> if (StringUtils.isBlank(serviceUniqueName)) {
>                 return "";
>             }
>             String[] arr = serviceUniqueName.split(PATH_SEPARATOR);
> ```

The measurement NPE has also been fixed, and judgment conditions have been added.
