### ISSUE TITLE
在没有使用 SpringBoot 的情况下如何使用 Metrics

### ISSUE THREAD

**Issue by T-baby** [apache/dubbo#13146]
看了下没有 MeterBinder 这类，没法像 Micrometer 官方提供的，使用类似 `JvmGcMetrics().bindTo(prometheusMeterRegistry)` 的方式注册。有什么其它方式在没有使用 Spring Boot 的情况下使用吗，如在 Vert.x 中使用？

**Comment by T-baby** [comment]
http://127.0.0.1:22222/metrics/ 这个地址的 metrics 可以直接给 Prometheus 采集吗？

**Comment by AlbumenJ** [comment]
> http://127.0.0.1:22222/metrics/ 这个地址的 metrics 可以直接给 Prometheus 采集吗？

可以的，这个就是标准的 prometheus 输出

**Comment by T-baby** [comment]
> > http://127.0.0.1:22222/metrics/ 这个地址的 metrics 可以直接给 Prometheus 采集吗？
> 
> 可以的，这个就是标准的 prometheus 输出

谢谢，国庆快乐。
