### ISSUE TITLE
使用triple协议，提供方provider方法重载，consumer方消费报错，provider方空指针

### ISSUE THREAD

**Issue by SpringStudent** [apache/dubbo#13142]
### Environment

* Dubbo version: 3.2
* Operating System version: windows 10
* Java version:1.8

### Steps to reproduce this issue

1. 在provider侧提供重载方法如下
![1695871853510](https://github.com/apache/dubbo/assets/14833956/b5a8a389-cb75-49e7-8150-63147065e75f)
2. 在consumer侧分别调用两个重载方法
3. provider报错NPE
![1695871935061](https://github.com/apache/dubbo/assets/14833956/44dde66c-2a5d-4904-afb5-9b709c74b059)

### Expected Behavior

期望能正常调用

### Actual Behavior
consumer
![image](https://github.com/apache/dubbo/assets/14833956/740c67c1-fde1-4106-b066-0fa257804441)
provider
![1695871991526](https://github.com/apache/dubbo/assets/14833956/537c0413-0e82-467e-9838-fe33fe45dbed)

```
Just put your stack trace here!
```

**Comment by SpringStudent** [comment]
![image](https://github.com/apache/dubbo/assets/14833956/dbc3f9ef-f58c-4074-8831-73deba751223)
是否

**Comment by AlbumenJ** [comment]
@EarthChen PTAL

**Comment by andotorg** [comment]
I'm fix it.

**Comment by namelessssssssssss** [comment]
能否提供完整的代码？个人测试服务端的简单重载在3.3下可以跑通 :)

**Comment by SpringStudent** [comment]
3.3是指分支吗，并没看到该分支？代码用的是dubbo-demo/dubbo-demo-triple，只是简单的在GreeterService.java类中新增了一个重载方法
`public interface GreeterService {

    /**
     * Sends a greeting
     */
    HelloReply sayHello(HelloRequest request);

    String sayHello(String name);


    CompletableFuture<String> sayHelloAsync(String request);

}`

**Comment by SpringStudent** [comment]
> 能否提供完整的代码？个人测试服务端的简单重载在3.3下可以跑通 :)
![image](https://github.com/apache/dubbo/assets/14833956/18ae2a39-4576-4ae4-8e65-0576faa5fcac)
3.3分支调用也是一样的错误

**Comment by namelessssssssssss** [comment]
看上去是个bug，我们看下如何修复

**Comment by EarthChen** [comment]
有 pb存在时不建议使用重载，wrapper模式的 md 是在 data 响应时填充的，而 pb (stub)模式下不支持重载，他会基于 header 中的元数据就找到md

**Comment by SpringStudent** [comment]
> 有 pb存在时不建议使用重载，wrapper模式的 md 是在 data 响应时填充的，而 pb (stub)模式下不支持重载，他会基于 header 中的元数据就找到md

那是否应该在程序启动时检测下provider重载行为并提前报错，否则在程序运行中框架报错空指针报错也并不是非常友好的行为

**Comment by EarthChen** [comment]
> > 有 pb存在时不建议使用重载，wrapper模式的 md 是在 data 响应时填充的，而 pb (stub)模式下不支持重载，他会基于 header 中的元数据就找到md
> 
> 那是否应该在程序启动时检测下provider重载行为并提前报错，否则在程序运行中框架报错空指针报错也并不是非常友好的行为

这个可以的，欢迎你提个 pr 来 check 一下

**Comment by SpringStudent** [comment]
> pb



> > > 有 pb存在时不建议使用重载，wrapper模式的 md 是在 data 响应时填充的，而 pb (stub)模式下不支持重载，他会基于 header 中的元数据就找到md
> > 
> > 
> > 那是否应该在程序启动时检测下provider重载行为并提前报错，否则在程序运行中框架报错空指针报错也并不是非常友好的行为
> 
> 这个可以的，欢迎你提个 pr 来 check 一下

你提到的pb，是指什么。好的我稍后会提个pr

**Comment by EarthChen** [comment]
> > pb
> 
> > > > 有 pb存在时不建议使用重载，wrapper模式的 md 是在 data 响应时填充的，而 pb (stub)模式下不支持重载，他会基于 header 中的元数据就找到md
> > > 
> > > 
> > > 那是否应该在程序启动时检测下provider重载行为并提前报错，否则在程序运行中框架报错空指针报错也并不是非常友好的行为
> > 
> > 
> > 这个可以的，欢迎你提个 pr 来 check 一下
> 
> 你提到的pb，是指什么。好的我稍后会提个pr

protobuf 的类，用proto 文件生成的 class

**Comment by SpringStudent** [comment]
> r



> > > pb
> > 
> > 
> > > > > 有 pb存在时不建议使用重载，wrapper模式的 md 是在 data 响应时填充的，而 pb (stub)模式下不支持重载，他会基于 header 中的元数据就找到md
> > > > 
> > > > 
> > > > 那是否应该在程序启动时检测下provider重载行为并提前报错，否则在程序运行中框架报错空指针报错也并不是非常友好的行为
> > > 
> > > 
> > > 这个可以的，欢迎你提个 pr 来 check 一下
> > 
> > 
> > 你提到的pb，是指什么。好的我稍后会提个pr
> 
> protobuf 的类，用proto 文件生成的 class

ok
