### ISSUE TITLE
Question about nacos multi-subscribe

### ISSUE THREAD

**Issue by tiancaipei** [apache/dubbo#13156]
版本:
org.apache.dubbo
2.7.20、2.7.23

注册中心：
nacos

问题：
从2.7.X的低版本升级到高版本时，为了兼容低版本的服务名称，高版本会同时订阅两个格式路径名称；但是当所有服务都升级到2.7.X的高版本之后，旧的路径已经没有了服务的提供者，但是依旧在被订阅，会触发nacos的推空保护，打印出大量的问题日志。请问是否有一个字段可以开始或关闭旧路径的订阅

**Comment by AlbumenJ** [comment]
2.7.x has been EOL, and the latest version that supports turning off nacos multi-mode subscription is 3.2.x. This can be achieved by configuring `nacos.subscribe.legacy-name=false`, for example `nacos://127.0.0.1:8848?nacos.subscribe.legacy-name=false`

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
