### ISSUE TITLE
我看支持了jdk21但是并没有使用虚拟线程进行改造 后续是否考虑提供一个使用虚拟线程的开关

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#13151]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by AlbumenJ** [comment]
3.3.0-beta.1 开始支持协程

**Comment by l1141806406** [comment]
国庆都过完了，还没发布3.3GA

**Comment by AlbumenJ** [comment]
> 国庆都过完了，还没发布3.3GA

目前 3.3 还是在 beta 状态，需要一段时间稳定才能达到 GA

**Comment by l1141806406** [comment]
https://cn.dubbo.apache.org/zh-cn/blog/2022/10/22/%E8%81%9A%E7%84%A6%E7%A8%B3%E5%AE%9A%E6%80%A7dubbo-java-%E5%8F%91%E7%89%88%E8%A7%84%E5%88%92%E5%85%AC%E5%B8%83/

对于 Dubbo 3.3 版本，将在 2023 年 3 月紧随着 3.2 版本结束新功能合入阶段后正式开始开发。因此，Dubbo 3.3 版本的第一个 beta release 也将会在 2023 年 3 月发布。同样的，经过 6 个月的新功能合入阶段之后，Dubbo 3.3 版本将会在 2023 年 9 月正式发布生产可用 GA 版本，同时进入稳定性维护阶段

就算迟一点，我理解10月份应该能发布吧

**Comment by AlbumenJ** [comment]
> https://cn.dubbo.apache.org/zh-cn/blog/2022/10/22/%E8%81%9A%E7%84%A6%E7%A8%B3%E5%AE%9A%E6%80%A7dubbo-java-%E5%8F%91%E7%89%88%E8%A7%84%E5%88%92%E5%85%AC%E5%B8%83/
> 
> 对于 Dubbo 3.3 版本，将在 2023 年 3 月紧随着 3.2 版本结束新功能合入阶段后正式开始开发。因此，Dubbo 3.3 版本的第一个 beta release 也将会在 2023 年 3 月发布。同样的，经过 6 个月的新功能合入阶段之后，Dubbo 3.3 版本将会在 2023 年 9 月正式发布生产可用 GA 版本，同时进入稳定性维护阶段
> 
> 就算迟一点，我理解10月份应该能发布吧

出于目前功能稳定性收敛的考虑，3.3 的 GA 需要延后发布

**Comment by l1141806406** [comment]
好的，感谢🙏

**Comment by l1141806406** [comment]
3.3预估大概什么时候GA？

**Comment by JoyfulAndSpeedyMan** [comment]
11月了。3.3大概什么时候GA
