### ISSUE TITLE
泛化GenericService实例创建问题

### ISSUE THREAD

**Issue by yeohx** [apache/dubbo#13152]
版本:
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>3.2.6</version>
        </dependency>
代码用例:
 ApplicationConfig application = new ApplicationConfig();
        application.setName("Test-" + UUID.randomUUID().toString());
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("nacos://localhost:8848");
        application.setRegistry(registryConfig);

        ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
        reference.setGeneric("true");
        reference.setApplication(application);
        reference.setInterface(interfaceName);
        reference.setVersion(version);
        SimpleReferenceCache referenceConfigCache = SimpleReferenceCache.getCache();
        GenericService genericService = referenceConfigCache.get(reference);
        return genericService;
问题:
reference.setApplication(application); 方法已经弃用.
建议使用:org.apache.dubbo.config.AbstractConfig#setScopeModel(ScopeModel)代替
说明里为了支持多应用
但是ScopeModel需要如何创建呢?
是否可以提供一个完整的3.*.*版本的泛型调用的例子.如何支持多应用的例子.
我看了demo里面的泛型例子,是通过DubboBootstrap设置的.没有通过ScopeModel配置
最好能在demo里面增加一下ScopeModel支持多应用泛化的例子

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/blob/master/1-basic/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/client/Application.java

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
