### ISSUE TITLE
[Serialization] Add Fury serialization support for dubbo

### ISSUE THREAD

**Issue by chaokunyang** [apache/dubbo#13160]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have searched the [release notes](https://github.com/apache/dubbo/releases) of this repository and believe that this is not a duplicate.

## Describe the feature
Hi, I'm the author of [Fury](https://github.com/alipay/fury) serialization framework, it's a fast multi-language serialization framework powered by jit and zero-copy. The complete introduction are published as a [blog in  medium](https://medium.com/@shawn.ck.yang/fury-a-blazing-fast-multi-language-serialization-framework-powered-by-jit-and-zero-copy-fdd16f3215cb).

Now it's the fastest java serialization framework in https://github.com/eishay/jvm-serializers, see the[wiki](https://github.com/eishay/jvm-serializers/wiki) for detailed benchmark data : 
![image](https://github.com/apache/dubbo/assets/12445254/df84965e-d4df-4205-abde-5b518531ad5a)

I want to know whether we can integrate fury into dubbo? I implemented the integration in the https://github.com/fury-project/dubbo-serialization-fury , it has been used by some users in production env. Can we make this official?

**Comment by EarthChen** [comment]
You can first contribute a spi to https://github.com/apache/dubbo-spi-extensions.

**Comment by chaokunyang** [comment]
> You can first contribute a spi to https://github.com/apache/dubbo-spi-extensions.

Added PR in https://github.com/apache/dubbo-spi-extensions/pull/226, coud you please review it?
