### ISSUE TITLE
How to achieve graceful shutdown after integrating Rocketmq and Dubbo?

### ISSUE THREAD

**Issue by lpcy** [apache/dubbo#13185]
I have a complex application scenario that includes both Dubbo and Rocketmq consumers, based on the Spring environment. Dubbo has both services and references. At present, when the program is stopped, the Rocketmq consumer will report an error due to the Dubbo being stopped. Can it be implemented to stop the dubbo service and rocketmq consumer first when the program is stopped, and then stop the dubbo reference after both are executed? I know Spring has a SmartLifecycle tool, but it seems that Dubbo does not support it. My environment:
Dubbo: 3.2.5
Spring: 4.3

**Comment by AlbumenJ** [comment]
1. We should only offline provider.
2. You can call `http://127.0.0.1:22222/offline` or `http://127.0.0.1:22222/gracefulShutdown` to offline all the service provided on Dubbo.

**Comment by lpcy** [comment]
> 1. We should only offline provider.
> 2. You can call `http://127.0.0.1:22222/offline` or `http://127.0.0.1:22222/gracefulShutdown` to offline all the service provided on Dubbo.

Thank you. How can I close all providers in the code?

**Comment by AlbumenJ** [comment]
> > 1. We should only offline provider.
> > 2. You can call `http://127.0.0.1:22222/offline` or `http://127.0.0.1:22222/gracefulShutdown` to offline all the service provided on Dubbo.
> 
> Thank you. How can I close all providers in the code?

1. The most easily way is to request `http://127.0.0.1:22222/gracefulShutdown` via URLConnection or HttpUtils in your code.
2. Using the following code (But this is not ensure in the future. The API may be changed in the future.)
```java
@Autowired
private ModuleModel moduleModel;

...

new GracefulShutdown(ScopeModelUtil.getFrameworkModel(moduleModel)).execute(null, null);
```

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
