### ISSUE TITLE
How to disable telnet invoke command?

### ISSUE THREAD

**Issue by Aaronlong31** [apache/dubbo#13197]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
If I turn on QOS, I can execute the invoke command through telnet. 
I want to turn off the invoke command when QOS is turned on. 
Because the invoke command can bypass dubbo's security check mechanism(such as TokenFilter), the dubbo service method is directly called, and there is a security problem.

**Comment by iJIAJIA** [comment]
在spring-boot环境
dubbo 3.2.x里的org.apache.dubbo.spring.boot.env.DubboDefaultPropertiesEnvironmentPostProcessor#setDubboApplicationQosEnableProperty
会默认启用qos.
并且在我这边实践测试下来(可能有误), 无法通过在 在spring配置里添加dubbo.application.qos-enable 去禁用.
所以我自己实现了个 Custom EnvironmentPostProcessor 来禁用qos.

**Comment by AlbumenJ** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> 
> ## Ask your question here
> If I turn on QOS, I can execute the invoke command through telnet. I want to turn off the invoke command when QOS is turned on. Because the invoke command can bypass dubbo's security check mechanism(such as TokenFilter), the dubbo service method is directly called, and there is a security problem.

QoS command can only be called in localhost by default. If you think localhost is also dangerous, pls disable qos.

**Comment by AlbumenJ** [comment]
> 在spring-boot环境 dubbo 3.2.x里的org.apache.dubbo.spring.boot.env.DubboDefaultPropertiesEnvironmentPostProcessor#setDubboApplicationQosEnableProperty 会默认启用qos. 并且在我这边实践测试下来(可能有误), 无法通过在 在spring配置里添加dubbo.application.qos-enable 去禁用. 所以我自己实现了个 Custom EnvironmentPostProcessor 来禁用qos.

Try the latest version. This has been fixed.
