### ISSUE TITLE
Dubbo 的参数支持netty的ByteBuf类型么？

### ISSUE THREAD

**Issue by xiandafu** [apache/dubbo#13239]
我在用Netty做一个代理服务器，调用后端dubbo服务。为了避免IO COPY消耗，我想把netty收到的IO 请求直接转发到dubbo服务，因此想定义如下接口

public void sendRequest(Header header,ByteBuf buf）

这里的buf是堆外buf。包含了代理服务接收的请求内容。

我的问题是
Dubbo 的参数支持netty的ByteBuf类型么，以及能及时释放ByteBuf么？我需要怎么做才能实现这个功能？

**Comment by ShenFeng312** [comment]
不可以。dubbo是peer to peer的长链接调用。你如果不decode。你根本不知道包是否完整顺序是否正确。并且你不会知道你需要访问哪个服务。如果要做网关可以考虑泛化调用。如果是客户端的代理。可能可以使用socket代理
