### ISSUE TITLE
dubbo、nacos、spring boot集成，怎么获取当前服务注册的ip？

### ISSUE THREAD

**Issue by offSwitch** [apache/dubbo#13248]
使用了dubbo-registry-nacos这个包，要怎么获取当前服务注册到nacos上的ip呢？

**Comment by AlbumenJ** [comment]
`NetUtils.getLocalAddress()`

**Comment by offSwitch** [comment]
> `NetUtils.getLocalAddress()`

这个在多网卡情况下不行，我已经用其他方式解决了
