### ISSUE TITLE
大佬好，请问整合prometheus，http_sd service discovery的请求地址是什么

### ISSUE THREAD

**Issue by benjijun** [apache/dubbo#13262]
关于dubbo 整合promethus 在pull模式下，官方描述如下：
目前 Dubbo Admin 内置了 prometheus http_sd service discovery 实例地址发现机制，Admin 默认会使用 qos 端口、 /metrics 作为这样 Admin 就能够将所有示例地址汇聚后以标准 http_sd 的方式同步给 Prometheus Server。

问题：这个实例地址是啥，很疑惑，我在admin的源码中只发现了个MetricsCollectController,这个接口会向prometheus同步指标？我的理解是promethus会定时请求dubbo-admin的这个实例地址， 然后dubbo-admin会从注册中心拉取所有的服务实例，然后对于每一个服务实例请求他的指标接口获取指标，最后再返回给promethus，但是我看MetricsCollectController这个类很疑惑，好像不是干这个是的

**Comment by songxiaosheng** [comment]
duubo admin那边你看下你当前的部署版本，应该还没此接口，可以考虑基于k8s或者自己实现的你们机器列表的服务发现接口配置下

**Comment by benjijun** [comment]
我看了应该是没有，自己写吧，谢了
