### ISSUE TITLE
Hutool的JSONArray反序列化错误

### ISSUE THREAD

**Issue by markr512** [apache/dubbo#13268]
dubbo3.2.7版本问题
传输对象中有JSONArray字段的属性,在反序列化后得到的对象不是原有对象,变成了config和raw
3.1.11没有这个问题

**Comment by EarthChen** [comment]
使用的默认序列化吗？3.2默认序列化切换为了 fastjson2 ，相关问题可以提给那边

**Comment by markr512** [comment]
是默认序列化

**Comment by AlbumenJ** [comment]
> 是默认序列化

Please submit a issue to https://github.com/alibaba/fastjson2
