### ISSUE TITLE
Dubbo3.3 tag routing rule is invalid

### ISSUE THREAD

**Issue by chenrenhang** [apache/dubbo#13264]
### Environment

* Dubbo version: 3.3
* Java version: jdk8

### Steps to reproduce this issue

1. Start provider service A with tag="ruochen"
2. Start consumer service B and request service A with tag="ruochen1"

### Expected Behavior
Failed to invoke service A

### Actual Behavior
Successfully called and returned the result

Tag routing rule is invalid !!!

**Comment by wxbty** [comment]
It has not reappeared after testing. If there are still problems, please open another issue.
