### ISSUE TITLE
dubbo直连模式下，如何能在不重启服务情况下更新invoke地址

### ISSUE THREAD

**Issue by fungoddd** [apache/dubbo#13270]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## 请教各位大佬一个问题
我通过dubbo直连模式部署应用服务，配置如下：
```
dubbo.registry.address=N/A
dubbo.provider.register=false
dubbo.consumer.check=false
dubbo.application.qos-enable=false
```

并配置了dubbo.resolve.file配置项，指定了dubbo-resolve.properties配置文件：

```
com.xxx.sys.api.SysElasticSearchRpcService=dubbo://127.0.0.1:20991
com.xxx.sys.api.SysUserRpcService=dubbo://127.0.0.1:20991
com.xxx.oss.api.OssFileRecordRpcService=dubbo://127.0.0.1:20010
```
我监视了该文件，想在修改提供者地址时，来更新dubbo远程调用的地址。
我通过 ReferenceBeanManager 获取到了全部ReferenceBean，
并调用了referenceBean.getReferenceConfig().refresh()方法来刷新配置，
但是调用接口时还是原来的旧地址，请问有什么方法可以做到吗? 或是可以重新注册dubbo reference bean。

##
Java Version：1.8.0_341
SpringBoot Version：2.7.14
Dubbo version：3.1.11

**Comment by AlbumenJ** [comment]
Two ways:
1. Implement your own Directory to handle push
2. Re-create ReferenceConfig to subscribe after the address changes

**Comment by fungoddd** [comment]
非常感谢，我通过ReferenceBean的refresh方法更新了ReferenceConfig，并通过ReferenceBean的init方法更新可invoker对象，再使用自定义的动态代理类，将里面invoker引用为刷新后的ReferenceBean中的invoker对象实现了此功能。
