### ISSUE TITLE
qos online 无法注册配置registry=false的服务

### ISSUE THREAD

**Issue by arsenalzjx** [apache/dubbo#13276]
想使用qos进行优雅启停，应用启动后我需要做好一系列检查，最后再对dubbo接口进行注册，这样就要求启动时不自动注册dubbo服务，配置dubbo.registry.register=false后，使用qos的online接口无法注册服务到配置中心上

**Comment by arsenalzjx** [comment]
version 2.7.15

**Comment by AlbumenJ** [comment]
Please try on the latest version.

**Comment by AlbumenJ** [comment]
2.7.x is EOL now
