### ISSUE TITLE
在Dubbo 3.2.7使用rest无法自定义HTTP响应status

### ISSUE THREAD

**Issue by tell1014** [apache/dubbo#13287]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Operating System version: win10
* Java version: java8

### Steps to reproduce this issue

    @DELETE
    @Path("{uid}")
    public Response deleteUserById(@PathParam("uid") String uid) {
        return Response.status(300).build();
    }
  无法设置自定义响应码，无论怎么设置所有响应都为200。

**Comment by AlbumenJ** [comment]
@CrazyHZM @suncairong163 PTAL
