### ISSUE TITLE
采用应用级别注册时的InstanceRequest没有dubbo.tag

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#13293]
版本：
1.dubbo：3.2.7
2. nacos： 2.3.0-BETA
应用配置：
dubbo.provider.tag=XXX  # 我们基于dubbo.tag进行路由
dubbo.application.register-mode : instance    #  只采用应用级别注册方式

问题：
1. nacos注册中心的服务实例各个instance里并没有dubbo.tag：因为InstanceRequest注册请求对象里面并没有包含dubbo.tag；
2. nacos注册中心的配置列表里的相关接口方法元数据里只有最后一个注册服务实例的dubbo.tag，因为ConfigPublishRequest发布dubbo元数据是覆盖配置内容的方式。

建议：
InstanceRequest里包含dubbo.tag

**Comment by zrlw** [comment]
服务A的配置文件（片段）:
![0880c6ed041095c9a707](https://github.com/apache/dubbo/assets/40652892/f6102701-fd91-499c-a341-eed726df3c29)

nacos注册中心服务详情显示的Instance实例元数据：
![0880c6ed041095c9e706](https://github.com/apache/dubbo/assets/40652892/1a908777-061d-491b-a9d1-1f0edd7234cf)

nacos注册中心配置列表接口方法元数据（只有最后注册服务实例的dubbo.tag)：
![0880c6ed041095c98707](https://github.com/apache/dubbo/assets/40652892/923fb1b3-f7f2-4fe2-9815-b61ecba4ebed)

**Comment by zrlw** [comment]
翻到之前提过的一个issue：
https://github.com/apache/dubbo/issues/8307
当时给出的解决办法是应用配置dubbo.application.metadata-type=remote
这样注册中心就会记录各个instance的元数据（里面有dubbo.tag）：
![0880c6ed041095c9b707](https://github.com/apache/dubbo/assets/40652892/663e2b5b-9042-4de5-939b-81eddd33ed78)
注册中心metadata-type元数据的DataId是应用名、Group是各个instance的dubbo.metadata.revision：
![0880c6ed041095c99707](https://github.com/apache/dubbo/assets/40652892/47561beb-6cb7-4c62-95cb-23c65410ee03)
注册中心该服务的实例明细情况：

对于没有nacos-sync同步跨集群同步注册实例的应用场景，这种方法是可行的。

但是我们需要通过nacos-sync（自己修订的0.4.9，适配nacos2批量同步临时实例）把A机房注册中心的dubbo服务实例复制到B机房的nacos注册中心，nacos-sync现在只有同步服务实例明细的功能，配置数据同步并不在它最初的功能设计范畴。

如果只是接口名到应用名的映射关系，还可以手工汇总导入到B机房的nacos注册中心存储元数据的config_info表，但是dubbo的metadata-type这种元数据是服务注册时动态生成的，除非在nacos-sync基础上再搞一套dubbo的metadata-type元数据同步（深度捆定dubbo，从A机房获取instance对象的dubbo.metadata.revision，然后从A机房注册中心拉取相关的metadata-type元数据，再将其发布到B机房的nacos注册中心）。否则没办法搞应用级别实例的跨机房同步。

这种方式有点复杂，所以能否直接在InstanceRequest请求数据加个dubbo.tag呢？或者增加个配置选项，把实例元数据都留在InstanceRequest里？

**Comment by AlbumenJ** [comment]
简单来说你是希望这个 Key 可以注册到 Instance 实例上面是吗

**Comment by zrlw** [comment]
> 可以实现 org.apache.dubbo.registry.client.ServiceInstanceCustomizer 这个接口，把 `dubbo.tag` 给拼接到 ServiceInstance 上面

我还是想办法改nacos-sync同步dubbo元数据吧
