### ISSUE TITLE
dubbo filter 中如何判断当前 invoker 是consumer 还是 provider

### ISSUE THREAD

**Issue by lossend** [apache/dubbo#13292]
之前 dubbo 2.7 版本的时候通过 RpcContext.isProviderSide判断，换了 3.0.9之后就不行了，报空指针，请问怎么判断才能同时兼容 dubbo3.0.9 和dubbo 2.7 版本

**Comment by lossend** [comment]
我现在这么判读，是否能兼容两种版本
![image](https://github.com/apache/dubbo/assets/49791601/3624153c-d546-4d21-bb43-6f4e8c3f9f70)

**Comment by AlbumenJ** [comment]
最简单的方式是实现两个 Filter，通过 Activate 去隔离

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
