### ISSUE TITLE
请教下：Dubbo3 在适配时，DubboService 注解应该怎么注册？

### ISSUE THREAD

**Issue by noear** [apache/dubbo#13290]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
之前 `@Service` 注解，有个对应的配置类 `ServiceConfig`，可以通过 DubboBootstrap::service 注册服务。。。。但是，`@DubboService` 没看到有对应的 Config 类，DubboBootstrap 上也没看到相应的注册？？？

**Comment by oxsean** [comment]
这几个注解的处理逻辑是一样的:
https://github.com/apache/dubbo/blob/3.2/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationPostProcessor.java#L103
因此你提到的注册逻辑也是一样的.

**Comment by noear** [comment]
@oxsean 你发的是 spring 里的实现。。。并非 dubbo 自己的接口注册。就像 DubboBootstrap 通过 ServiceConfig 对 `@Service` 注解提供注册支持。这个现在没有！

**Comment by oxsean** [comment]
哦哦，没太理解你的意思，Config内都是ServiceConfig只不过只有Service有Constructor支持，你可以自己写个子类继承ServiceConfig然后调用appendAnnotation方法来解析元数据，我也没试过，仅供参考
https://github.com/apache/dubbo/blob/af566233dbb9673c9da18b545133bfaca0bd5bf5/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java#L486

**Comment by noear** [comment]
@oxsean 你的意思是，把注解转换一下。然后再用 ServiceConfig 进行注册是吗？？？

**Comment by oxsean** [comment]
直接塞 DubboService 进去，这个是反射调用的，不case是哪个注解，字段名字在对的上就可以。

**Comment by noear** [comment]
@oxsean 我的意思是：把 DubboService 换成 Service 主解；然后用 ServiceConfig ，再注册到 DubboBootstrap 。。。是这个意思吗？

**Comment by oxsean** [comment]
`
public class ServiceConfig extend AbstractConfig  {
    public ServiceConfig(DubboService service) {
        super();
        appendAnnotation(DubboService.class, service);
    }
}
`

**Comment by noear** [comment]
@oxsean 谢谢！！！不过，有另一个疑问哦。Service 注解老旧就弃用了，为什么框架里不直接出一个 DubboServiceConfig 类？

**Comment by oxsean** [comment]
我猜是很少有人这么用

**Comment by noear** [comment]
@oxsean 那，如果不是基于 spring 应该怎么用？

**Comment by oxsean** [comment]
Api方式
https://dubbo.apache.org/en/docs3-v2/java-sdk/quick-start/api/

**Comment by noear** [comment]
@oxsean 你是用户，还是作者啊？这么熟！

**Comment by noear** [comment]
@oxsean 我看这个说明了。。。不过一般用，还是会加注解的。。。做申明，注解提供了便利。。。还是要给 DubboService 和 Service 相同的待遇：）

**Comment by noear** [comment]
我是在核对： https://github.com/noear/solon  这个项目关于 dubbo3 的适配。所以来此一问

**Comment by oxsean** [comment]
用的比较久的用户，正在尝试做点贡献，一般做framework开发才有这种需求，如果是服务开发的话，没有必要混合这两种方式，觉得有必要可以尝试提个PR加下
@noear 令人佩服的活跃度

**Comment by noear** [comment]
@oxsean 看来你是高手啊：）。。。最近在写个通讯协议（。https://github.com/noear/socketd ），一个人写得有点心慌。有没有兴趣帮忙检查检查代码：）

**Comment by oxsean** [comment]
> @oxsean 看来你是高手啊：）。。。最近在写个通讯协议（。https://github.com/noear/socketd ），一个人写得有点心慌。有没有兴趣帮忙检查检查代码：）

玩得久而已，网络通讯方面不熟，不敢随便评价，空了看看~
