### ISSUE TITLE
当实体类字段存在Jackson的@JsonIgnore注解时dubbo调用获取的该字段值为null

### ISSUE THREAD

**Issue by fungoddd** [apache/dubbo#13325]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Operating System version: MacOS 13.5
* Java version: 1.8.0_341

### Steps to reproduce this issue

1. 我在实体类的字段上添加了Jackson的@JsonIgnore注解
```
    @JsonIgnore
    @TableField("authentication_string")
    @ApiModelProperty(value = "密码")
    protected String password;
```
2. 通过dubbo调用接口查询，得到的该字段值为null，我默认用的是fastjson2序列化，@JsonIgnore是jackson的注解，为什么会受影响？当我去除@JsonIgnore注解或设置序列化为hession时就好了
```
dubbo.provider.prefer-serialization=hessian2
```

**Comment by AlbumenJ** [comment]
这个是符合预期的，因为 3.2 默认使用 fastjson2，而 fastjson2 默认支持 Jackson 的注解

**Comment by fungoddd** [comment]
非常感谢，之前没有了解过fastjson2的特性，已解决
