### ISSUE TITLE
Streaming 通信服务提供者报超时警告

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#13339]
* Dubbo version: 3.2.5
* Operating System version: windows
* Java version: jdk17

需要用Streaming 通信来解决服务提供者处理耗时很长的业务场景，按照官方文档写了一个样例，
在服务提供者处理完的时候会报一个警告，消费者端正常。按道理来说Streaming 通信是没有超时时间限制的，所以这个警告很多余
[参照的官网demo链接](https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/protocol/triple/streaming/#%E8%B0%83%E7%94%A8%E6%96%B9%E5%BC%8F)
警告截图：
![1699517747241](https://github.com/apache/dubbo/assets/33255974/ed558728-16e8-4e81-9de9-28d00919bb2b)

**Comment by kazetyan** [comment]
![image](https://github.com/apache/dubbo/assets/50894526/af415e21-c51c-4295-9fba-6851a0f41aa5)

先获取consumer的timeout,再获取provider的timeout,没有就取默认值1000

实测provider的`dubbo.provider.timeout`是有效的,设置值大于实际值就不会打印
consumer的配置试了几个都没有生效,不清楚是不是bug

由于ProfilerServerFilter是共用的,所以不管是不是stream,只要超时就会打性能warn日志,要不要区分得看官方怎么考虑了

**Comment by zzps** [comment]
> ![image](https://user-images.githubusercontent.com/50894526/284860494-af415e21-c51c-4295-9fba-6851a0f41aa5.png)
> 
> 先获取consumer的timeout,再获取provider的timeout,没有就取默认值1000
> 
> 实测provider的`dubbo.provider.timeout`是有效的,设置值大于实际值就不会打印 consumer的配置试了几个都没有生效,不清楚是不是bug
> 
> 由于ProfilerServerFilter是共用的,所以不管是不是stream,只要超时就会打性能warn日志,要不要区分得看官方怎么考虑了

确实问题的根本就是产品设计成需不需要区分，在我看来肯定是要区分的，stream场景百分百都是超过一般请求的设置的timeout的
，如果还和一般混合那为什么不直接报错了呢，当然如果这样就是更严重的产品bug问题了

**Comment by kazetyan** [comment]
> > ![image](https://user-images.githubusercontent.com/50894526/284860494-af415e21-c51c-4295-9fba-6851a0f41aa5.png)
> > 先获取consumer的timeout,再获取provider的timeout,没有就取默认值1000
> > 实测provider的`dubbo.provider.timeout`是有效的,设置值大于实际值就不会打印 consumer的配置试了几个都没有生效,不清楚是不是bug
> > 由于ProfilerServerFilter是共用的,所以不管是不是stream,只要超时就会打性能warn日志,要不要区分得看官方怎么考虑了
> 
> 确实问题的根本就是产品设计成需不需要区分，在我看来肯定是要区分的，stream场景百分百都是超过一般请求的设置的timeout的 ，如果还和一般混合那为什么不直接报错了呢，当然如果这样就是更严重的产品bug问题了

嗯嗯,等官方回复

**Comment by EarthChen** [comment]
请问，目前除了打印一条 warn 日志还有其他影响吗？

**Comment by zzps** [comment]
> 请问，目前除了打印一条 warn 日志还有其他影响吗？

这个除了日志其他没有影响，有影响的是这个问题[https://github.com/apache/dubbo/issues/13363](url)
