### ISSUE TITLE
Can @DubboReference support obtaining service providers based on the spring.application.name registered in the registration center like Feign?

### ISSUE THREAD

**Issue by X1aoHei** [apache/dubbo#13346]
Now the direct connection method must provide host + port. Obtaining the host is relatively simple. The port exposed by dubbo is not of special concern to developers. If the port number is occupied, dubbo will automatically replace it. In this case, you must go to the log. Check;
In addition, for dubbo, since it supports the registration center, the registration center replaces the host and port with the application name. Why does dubbo still retain this design?

---

现在直联方式必须要提供host+端口，host获取还比较简单，dubbo暴露的端口对于开发者来说不会特别关注，如果端口号被占用，dubbo也会自动替换，这种情况就必须去日志里面查看；
另外对于dubbo来说，既然支持注册中心，注册中心把host、端口用application name来替代，为什么dubbo还保留这种设计呢？

**Comment by AlbumenJ** [comment]
> Now the direct connection method must provide host + port. Obtaining the host is relatively simple. The port exposed by dubbo is not of special concern to developers. If the port number is occupied, dubbo will automatically replace it. In this case, you must go to the log. Check;

You can specify the port on the provider side. But if the port is occupied, there may not be a good solution.

> In addition, for dubbo, since it supports the registration center, the registration center replaces the host and port with the application name. Why does dubbo still retain this design?

Not sure what design?

**Comment by zrlw** [comment]
if add ```String providerApplication() default "";``` to ```@DubboReference```,  the consumers will not need interfaceName-applicationName mapping metadata anymore.

**Comment by AlbumenJ** [comment]
Can't `providedBy` satisfy?

**Comment by X1aoHei** [comment]
> Can't `providedBy` satisfy?
可以的，`providedBy`满足我的需求，是我没找到注解各个字段的详细解释

Yes, `providedBy` meets my needs, but I couldn't find a detailed explanation for each field in the annotation

**Comment by AlbumenJ** [comment]
> > Can't `providedBy` satisfy?
> 
> 可以的，`providedBy`满足我的需求，是我没找到注解各个字段的详细解释
> 
> Yes, `providedBy` meets my needs, but I couldn't find a detailed explanation for each field in the annotation

I think we need to update the website in the next several months. 
Currently we are working on https://dubbo-next.staged.apache.org/

**Comment by zrlw** [comment]
> Can't `providedBy` satisfy?

naming it as providerAppname or providerApplication might be better to be consistent with the other two similar attributes providerPort and providerNamespace.
