### ISSUE TITLE
Reactor programming works in oneToOne mode, but the server reports an error in other modes

### ISSUE THREAD

**Issue by wiscloud** [apache/dubbo#13348]
![image](https://github.com/apache/dubbo/assets/52514676/d3015b27-c3dc-4c8d-b86e-2e6416053b6a)

**Comment by AlbumenJ** [comment]
@wiscloud Can you please provide a demo?

**Comment by wiscloud** [comment]
[demo-bug.zip](https://github.com/apache/dubbo/files/13428450/demo-bug.zip)
这是一个 springboot3 的示例，本机是M1芯片的 MacStudio，OneToOne 模式是可以的，其它模式不行

**Comment by chickenlj** [comment]
You are missing `package` in your proto file.

**Comment by chickenlj** [comment]
Please provide both `package` and `java_package`, or only provide `package`
