### ISSUE TITLE
建议检查ApplicationConfig的Name属性

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#13341]
## Describe the feature
现在org.apache.dubbo.config.ApplicationConfig#isValid方法只检查name是否为空，应用名称可以随便写，比如配成```providers:a.b.c:1.0:GroupA``` 这样的也可以。建议采用下列正则表达式对应用名称做一下检查，避免出现不必要的混乱。
```^[_a-zA-Z][_a-zA-Z0-9\-\.]*$``` ： 和java类名规则类似，只是禁用了```$```字符，除了首字符外允许使用连字符```-```和小数点```.```。

**Comment by AlbumenJ** [comment]
org.apache.dubbo.config.utils.ConfigValidationUtils#PATTERN_NAME

    private static final Pattern PATTERN_NAME = Pattern.compile("[\\-._0-9a-zA-Z]+");

**Comment by AlbumenJ** [comment]
> i see. the application using error format name should not be started, but `org.apache.dubbo.config.utils.ConfigValidationUtils` only log error messages.

We can make it into expcetion on 3.3.x. For 3.2.x, this may change users' expectations.
