### ISSUE TITLE
URL encoding is performed when passing URL parameters under the rest protocol

### ISSUE THREAD

**Issue by wiscloud** [apache/dubbo#13349]
![image](https://github.com/apache/dubbo/assets/52514676/9cc70020-a5f9-451b-94eb-09074ba7c986)

When requesting, the sayHello method uses URL parameters and performs URL encoding, and the server directly returns a String that is also URL encoded. The second method say does not have such a problem.

--- 
请求时，sayHello方法采用了 URL 传参，进行了 URL 编码，且服务端直接返回 String 也进行了 URL 编码，第二个方法say并没有这样的问题。

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

**Comment by kazetyan** [comment]
![image](https://github.com/apache/dubbo/assets/50894526/4c562d3e-db6e-4b0e-a0fc-83874c319a98)

![image](https://github.com/apache/dubbo/assets/50894526/9542a458-1ce0-480f-bc1a-823f22d5cccc)

`ParamProviderParamParser` 获取到参数时是否应该进行url decode 处理

![image](https://github.com/apache/dubbo/assets/50894526/cc42c151-4841-4c82-9369-f96f3826c357)

或者在创建`NettyRequestFacade` 的时候进行?

![image](https://github.com/apache/dubbo/assets/50894526/60b921f7-445d-4a49-b51d-fb7aa22e53c6)

排查的时候顺便看了下`BodyProviderParamParser`的实现,解码时编码要么是取系统默认的,要么是写死的utf-8(或许是个隐藏bug?)
![image](https://github.com/apache/dubbo/assets/50894526/4d73ff25-cdf4-46f7-8261-f47471a7f29b)
![image](https://github.com/apache/dubbo/assets/50894526/d60c8aa0-e045-4b13-8a0d-bd4cfac02bea)

**Comment by wiscloud** [comment]
[demo-bug.zip](https://github.com/apache/dubbo/files/13428227/demo-bug.zip)
这是写的一个示例压缩包，采用了三个子模块的形式，然后也测试过将所有的代码放到一个模块中，在一个模块中并没有出现乱码问题，但在三个子模块中就出现了乱码问题

**Comment by kazetyan** [comment]
> [demo-bug.zip](https://github.com/apache/dubbo/files/13428227/demo-bug.zip) 这是写的一个示例压缩包，采用了三个子模块的形式，然后也测试过将所有的代码放到一个模块中，在一个模块中并没有出现乱码问题，但在三个子模块中就出现了乱码问题

![image](https://github.com/apache/dubbo/assets/50894526/6ce02c78-9868-44b1-a0e1-1665e804433d)

@wiscloud 这个代码我试过了,问题还是这个,至于放到一个模块的情况,dubbo直接走了injvmInvoker,相当于本地调用了

![image](https://github.com/apache/dubbo/assets/50894526/b51304fa-bb9d-41f4-9b90-b117af1546b8)

![image](https://github.com/apache/dubbo/assets/50894526/3603f9d2-627f-4c8a-950a-59588fd2378f)

**Comment by MajaChen** [comment]
我也遇到了同样的问题，这个issue我先认领了，我尝试解决一下

**Comment by CrazyHZM** [comment]
@MajaChen 
Is there any progress?

**Comment by MajaChen** [comment]
我正在努力修复，麻烦再给我两周时间，看到2024年1月7号能否搞定，或者考虑放弃。谢谢！

**Comment by MajaChen** [comment]
In English, I've read the code very carefully, I think I've come up a proper way to fix the problem, see the [pr](https://github.com/apache/dubbo/pull/13617), it also contains necessary unit test.

## cause: 
In consumer side, parameters in RequestTemplate will be encoded with UTF-8 and will be appended to http request uri. Chinese character like '李强' in parameters will be transformed to '%E6%9D%8E%E5%BC%BA'
(The problem occur when using subclass of RestClient like OkhttpClient or HttpClientRestClient but not URLConnectionRestClient as demonstrated in unit test in RestClientTest)

Then the request is sent to provider.

In provider side, ReuqeFascade will parse the http request and extract the parameters from the uri, but forget to decode paramters with UTF-8, so Chinese character remains undecoded state, like '%E6%9D%8E%E5%BC%BA'

## solution:
 We need to decode the parameters with UTF-8 in RequestFascade.initParameters. For simplicity, I decode the whole uri and I'm pretty sure is safe even the uri is not encoded with UTF-8 at all in consumer side. You can refer the unit test in NettyRequestFacadeTest.

## demonstration:
![tGBBeWues4](https://github.com/apache/dubbo/assets/53480612/2de97c02-e889-4ae0-bdbd-54c7e26203b4)
![img_v2_2f58fbac-41b0-42d8-87aa-fb32282425al](https://github.com/apache/dubbo/assets/53480612/f82a8e93-7c0d-495a-abbe-c48ef9f8da5f)
![BX5Jf8ALdE](https://github.com/apache/dubbo/assets/53480612/79f880af-a075-4b4e-b37e-c302f4b49b23)

**Comment by MajaChen** [comment]
supplement: if you use @QueryParam to annotate the parameter，the parameter will be trated as request parameter in RequestTemplate, and it can cause problmes; But if you don't, the parameter will be trated as  request body, the problem won't occur.
Besides, if you use URLConnectionRestClient instead of OkhttpClient, the problem won't occur eigther.

**Comment by MajaChen** [comment]
@CrazyHZM I've launch a pull request, can you review the code
