### ISSUE TITLE
Building the project fails with "Failure to find log4j:log4j:jar:1.2.12"

### ISSUE THREAD

**Issue by berndgoetz** [apache/dubbo#13350]
### Environment

* Dubbo version: 3.2.7
* Operating System version: Windows 11
* Java version: openjdk 11.0.18 2023-01-17, OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10), OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)
* Special setup: I am running behind a Enterprise firewall, and we are using a artifact proxy as maven repository. This proxy blocks old and vulnerable versions of different libraries, in this case log4j version 1.2.12

### Steps to reproduce this issue

Run "mvn clean package -DskipTests" fails with the following error:

### Expected Behavior

Project resolves all dependencies and compiles successfully.

### Actual Behavior

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dubbo-build-tools: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.1 or one of its dependencies could not be resolved: Failure to find log4j:log4j:jar:1.2.12 in https://artifact.swissre.com/internal was cached in the local repository, resolution will not be reattempted until the update interval of internal-plugin has elapsed or updates are forced -> [Help 1]

**Comment by AlbumenJ** [comment]
Which repo are you builded for? Dubbo SDK itself, Dubbo Samples or your project?

**Comment by berndgoetz** [comment]
The Dubbo SDK itself.

**Comment by AlbumenJ** [comment]
> The Dubbo SDK itself.

Oops. This might be hard to resolve. Dubbo needs to support to log with log4j1 even though this is not a strong dependency. I think it is possible to remove the log4j1 dependency in 3.3.x or even 3.4.x in the future. But for now, there are still a lot of users still depends on it.

**Comment by oxsean** [comment]
It appears that your private Maven server(https://artifact.swissre.com/internal) is unable to download log4j. Since dubbo requires support for log4j's logging implementation, it is not possible to completely remove the log4j dependency. The suggested solutions are:

1. Switch to maven central server, compile and download log4j once, and then switch back to your private server.
2. Manually download the specified version of the jar and pom files from https://mvnrepository.com/, and then use the command 
```
mvn install:install-file -Dfile=D:/xxx.jar -DgroupId=log4j -DartifactId=log4j -Dversion=1.2.12 -Dpackaging=jar
```
to install them locally.

**Comment by berndgoetz** [comment]
Thanks. Case closed. It was initially indeed our internal repository not serving that log4j library version, but that works now.
