### ISSUE TITLE
Consumer don't inherit the stub config in the provider

### ISSUE THREAD

**Issue by WangXiaoJin** [apache/dubbo#13354]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.3
* Operating System version: Win11
* Java version: 1.8

### Steps to reproduce this issue

Provider service config `stub="true"`. Consumer don't inherit the stub config, and must manually set up the `stub="true"` config.

**Comment by AlbumenJ** [comment]
`stub` config is design for consumer and not support configure in the provider side.

**Comment by WangXiaoJin** [comment]
@AlbumenJ Okay, thank you for your reply.
