### ISSUE TITLE
triple+rest support custom uri like "proto annotations"

### ISSUE THREAD

**Issue by huntkalio** [apache/dubbo#13369]
I use curl to send  rest request in triple port ，the command like 
```
curl http:/xxxxxxx/org.apache.dubbo.samples.tri.grpc.Greeter/greet  -H "Content-Type: application/json" -X POST -d '{"name":"test"}'
```
But I can't change the uri, can dubbo support change the uri.May like this: https://cloud.google.com/endpoints/docs/grpc/transcoding,  use  "proto annotations" . 

So the dubbo framework user  can custom the uri.

**Comment by AlbumenJ** [comment]
@icodening @EarthChen @suncairong163 PTAL

We can support this feature when merging rest protocol into triple protocol.

**Comment by EarthChen** [comment]
@xiaoyuuuuuupeng

**Comment by xiaoyuuuuuupeng** [comment]
ok will try it

**Comment by oxsean** [comment]
No update for a longer time.

**Comment by oxsean** [comment]
There are two things that need to be done: one is to add the Mapping annotation to the generated stub, and the other is to support filling path variable parameters into the pb object when parsing parameters.
