### ISSUE TITLE
INTERNAL exception occurred when sending generic parameter in streaming

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#13363]
* Dubbo version: 3.2.5
* Operating System version: windows11
* Java version: 17

If the streaming communication mode StreamObserver generic parameter is also generic, an error "INTERNAL: Call aborted cause client exception" will be reported during runtime.

---

streaming通信模式StreamObserver泛型参数如果也是泛型的话在运行的时候会报错“INTERNAL : Call aborted cause client exception”
具体看代码截图
![1700016850144](https://github.com/apache/dubbo/assets/33255974/f9c5dd27-e718-4080-ac75-c5d88ee0e79e)
![1700016959488](https://github.com/apache/dubbo/assets/33255974/6475ea78-1006-4c39-9f34-cf9bc465c1f2)

**Comment by AlbumenJ** [comment]
Can you please provide a demo?

**Comment by zzps** [comment]
> Can you please provide a demo?
[https://gitee.com/755157298/dubbo-tree.git](url)

项目启动后
请求： 127.0.0.1:8080/ping/serverStream   不会报错
请求：127.0.0.1:8080/ping/serverStreamGeneric   会报错

[另外顺便帮我看一下这个问题](https://github.com/apache/dubbo/issues/13339)

**Comment by AlbumenJ** [comment]
@XiaoyuPeng Can you please help check it?

**Comment by kazetyan** [comment]
## 问题
![image](https://github.com/apache/dubbo/assets/50894526/b29e393e-09e7-4140-848b-6c55e13545c8)
![image](https://github.com/apache/dubbo/assets/50894526/e0af6028-9f9f-45de-a5b0-116fe9d8a5c7)
![image](https://github.com/apache/dubbo/assets/50894526/57a4953d-461a-472b-96c5-9c86ea93a538)
`ParameterizedTypeImpl`和`Class` 并没有继承关系,强转报错了
## 改动+验证
### 单元测试
![image](https://github.com/apache/dubbo/assets/50894526/6176e558-8758-40e6-801c-bbb1429d44aa)
看这的逻辑似乎是想获取`StreamObserver<X>`里的X的类型,加个判断,如果X也带泛型,获取X本身的类型
### 集成测试
改动前
![image](https://github.com/apache/dubbo/assets/50894526/3c12b9f0-79a2-4114-aa13-e070b6ad6701)
改动后
![image](https://github.com/apache/dubbo/assets/50894526/fdc0f5d1-614c-4fff-9b89-9b2baa7c6f31)

**Comment by zzps** [comment]
> ## 问题
> 
> ![image](https://private-user-images.githubusercontent.com/50894526/286463499-b29e393e-09e7-4140-848b-6c55e13545c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDM4NzUsIm5iZiI6MTcwMTMwMzU3NSwicGF0aCI6Ii81MDg5NDUyNi8yODY0NjM0OTktYjI5ZTM5M2UtMDllNy00MTQwLTg0OGItNmM1NWUxMzU0NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAwMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZWJmZjk2YjdiNDQwMDY2NjA4MTQwNzc0ZmIxNDc2OWFhM2Y5OWFlNWQyNjgxY2EwNWI4ODU3OWMwMzMxNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tlyMbSF9QwYZiR7dydIpY6diWbDKL_aiZ1cOaFM3AGc) ![image](https://private-user-images.githubusercontent.com/50894526/286463755-e0af6028-9f9f-45de-a5b0-116fe9d8a5c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDM4NzUsIm5iZiI6MTcwMTMwMzU3NSwicGF0aCI6Ii81MDg5NDUyNi8yODY0NjM3NTUtZTBhZjYwMjgtOWY5Zi00NWRlLWE1YjAtMTE2ZmU5ZDhhNWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAwMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MGI0OWNmM2RmMDE5ZTg4YmY2NTQyOTZkNTdhNjk0ZGY3N2EwMDk0MmQ0OWVjYThhZGRhZTk0MDM1MmM1MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zocT6RgHHJMNP30ppwbgKd06E7nxLbT2gZSJm58m5zc) ![image](https://private-user-images.githubusercontent.com/50894526/286464019-57a4953d-461a-472b-96c5-9c86ea93a538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDM4NzUsIm5iZiI6MTcwMTMwMzU3NSwicGF0aCI6Ii81MDg5NDUyNi8yODY0NjQwMTktNTdhNDk1M2QtNDYxYS00NzJiLTk2YzUtOWM4NmVhOTNhNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAwMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYjQ5NGUyOTllMjFjNTc2MTY3OWExZGI2NGM5Y2Y5YjgyMWY3MzE2N2M0NmVlYzhhN2ViYjUxODY1NzhjMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1W2sTzaz3OEAhDIamJ3KhwPTNBDWjemuWVik9s_3Gbs) `ParameterizedTypeImpl`和`Class` 并没有继承关系,强转报错了
> ## 改动+验证
> ### 单元测试
> 
> ![image](https://private-user-images.githubusercontent.com/50894526/286529563-6176e558-8758-40e6-801c-bbb1429d44aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDM4NzUsIm5iZiI6MTcwMTMwMzU3NSwicGF0aCI6Ii81MDg5NDUyNi8yODY1Mjk1NjMtNjE3NmU1NTgtODc1OC00MGU2LTgwMWMtYmJiMTQyOWQ0NGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAwMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2M2ZkNmI2MTVmNTM3YjEyMDViZWZmMTg3ZjU1NmI5ZjUzNmM4M2Y2MDA1OTQ5ZTg4NjljZTJlZjgyNGIyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.by13T8sNnbjPie0XYTOZ0NIIxCu3Zp3VbblSGsOCEfM) 看这的逻辑似乎是想获取`StreamObserver<X>`里的X的类型,加个判断,如果X也带泛型,获取X本身的类型
> ### 集成测试
> 
> 改动前 ![image](https://private-user-images.githubusercontent.com/50894526/286541614-3c12b9f0-79a2-4114-aa13-e070b6ad6701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDM4NzUsIm5iZiI6MTcwMTMwMzU3NSwicGF0aCI6Ii81MDg5NDUyNi8yODY1NDE2MTQtM2MxMmI5ZjAtNzlhMi00MTE0LWFhMTMtZTA3MGI2YWQ2NzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAwMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNjBhODdjNDVjYWNjMjU3MjdiNGZkOTFlMDAzOGVlMjJiZmMwYThlZGE2MTAwNGE4OTA2MzFhYjRhYjhjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xcXBDl8zzWpHMbRDCT7NHYM50sKyLWo1pr63ZWrRYDk) 改动后 ![image](https://private-user-images.githubusercontent.com/50894526/286555670-fdc0f5d1-614c-4fff-9b89-9b2baa7c6f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDM4NzUsIm5iZiI6MTcwMTMwMzU3NSwicGF0aCI6Ii81MDg5NDUyNi8yODY1NTU2NzAtZmRjMGY1ZDEtNjE0Yy00ZmZmLTliODktOWIyYmFhN2M2ZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAwMTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2N2VkMzUyOGI4NTU2YTllZjA5YzVkMDA2NmJlYzJjYmI1YzliNzFhYWU4ZGY4ZDI2YjRhYjQ4ZjhhYmQzZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vW4vsa1ipOX3bDXCVhtIwCmr7mk4PB9dd0557qtMZcQ)
有心了

**Comment by kazetyan** [comment]
> > ## 问题
> > ![image](https://private-user-images.githubusercontent.com/50894526/286463499-b29e393e-09e7-4140-848b-6c55e13545c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjUwMTQsIm5iZiI6MTcwMTMyNDcxNCwicGF0aCI6Ii81MDg5NDUyNi8yODY0NjM0OTktYjI5ZTM5M2UtMDllNy00MTQwLTg0OGItNmM1NWUxMzU0NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMmE2ZDhhNmY1ZTc2NWU1ZjdlMWE2ODczOWI2MzFkNDI4OTdjMjczMDdlOWI5MGMzYWY4ZTBiYjFkZGJjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LfTyi9ocp_NHy3He7_5LFVAnNrPyrVFlPTE7KXOAa8A) ![image](https://private-user-images.githubusercontent.com/50894526/286463755-e0af6028-9f9f-45de-a5b0-116fe9d8a5c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjUwMTQsIm5iZiI6MTcwMTMyNDcxNCwicGF0aCI6Ii81MDg5NDUyNi8yODY0NjM3NTUtZTBhZjYwMjgtOWY5Zi00NWRlLWE1YjAtMTE2ZmU5ZDhhNWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhOTJlNmI5OTVhYTUxNmY4YjI4NzkwNzkyNjgyYmZjY2ZjNDExZGM0YzU2NzVjYmU3Yjk1OTA2Y2RiZDRjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ssr65lkDb4n1hVNeZkTuCXxwZ4kY_Ys1g5dTRHL22cM) ![image](https://private-user-images.githubusercontent.com/50894526/286464019-57a4953d-461a-472b-96c5-9c86ea93a538.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjUwMTQsIm5iZiI6MTcwMTMyNDcxNCwicGF0aCI6Ii81MDg5NDUyNi8yODY0NjQwMTktNTdhNDk1M2QtNDYxYS00NzJiLTk2YzUtOWM4NmVhOTNhNTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjY2U2ZmU3NzljNGRlMTU0NDQ3YjE3MDAwOGQwNGIwODEzNjMxODAwZGEyZDQ4OTE1OGRjYmRjNzNhOTgyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jhr3ud0wmgW6IaC4npYtEIC3UivG6YYX02khKp34n_c) `ParameterizedTypeImpl`和`Class` 并没有继承关系,强转报错了
> > ## 改动+验证
> > ### 单元测试
> > ![image](https://private-user-images.githubusercontent.com/50894526/286529563-6176e558-8758-40e6-801c-bbb1429d44aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjUwMTQsIm5iZiI6MTcwMTMyNDcxNCwicGF0aCI6Ii81MDg5NDUyNi8yODY1Mjk1NjMtNjE3NmU1NTgtODc1OC00MGU2LTgwMWMtYmJiMTQyOWQ0NGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMjY0MWYwMTExMTY0MTNkOWEyMmIxNDA5NjU1Mzk1YWVkM2FkMjRiNTBjNDZjYjY3YzVlNTg3MGIzYTY5YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TswTaCJRrulkh2K0GDbwbbnEuE0ZPFQ8uXEy3Re9wDg) 看这的逻辑似乎是想获取`StreamObserver<X>`里的X的类型,加个判断,如果X也带泛型,获取X本身的类型
> > ### 集成测试
> > 改动前 ![image](https://private-user-images.githubusercontent.com/50894526/286541614-3c12b9f0-79a2-4114-aa13-e070b6ad6701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjUwMTQsIm5iZiI6MTcwMTMyNDcxNCwicGF0aCI6Ii81MDg5NDUyNi8yODY1NDE2MTQtM2MxMmI5ZjAtNzlhMi00MTE0LWFhMTMtZTA3MGI2YWQ2NzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOGU4MTJhZGM0ZjcwYzQyOTVjZjZiZmY2ZmVjMTk1YWVhMWEyNzY2OThhZDEyMDU0MTk5NjdkMTE5NjI1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4dSZWVPXiXoopEpyvpwTP0CH467pqBfPyb3UlunFNno) 改动后 ![image](https://private-user-images.githubusercontent.com/50894526/286555670-fdc0f5d1-614c-4fff-9b89-9b2baa7c6f31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjUwMTQsIm5iZiI6MTcwMTMyNDcxNCwicGF0aCI6Ii81MDg5NDUyNi8yODY1NTU2NzAtZmRjMGY1ZDEtNjE0Yy00ZmZmLTliODktOWIyYmFhN2M2ZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA2MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MmNlNjE5MWU3ZWQyM2YxZDYxMzVkNzJiYjI0OGU5Njg4MWEzYWJiNmEyNWYwYjYyZDU0ZjlmNTI2MGQ2MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7qvHLmBCWGPNLzdx2LWZQBpniZV2sdoYQgRRBolFk9U)
> 
> Can you task a PR to fix it?

非常乐意！我之前没提过PR，我尝试提一个，要是有什么问题还请多多指教。
