### ISSUE TITLE
从Dubbo 2.7.x升级到Dubbo 3.2.x，使用triple协议出现一些问题

### ISSUE THREAD

**Issue by haopangang** [apache/dubbo#13374]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
If I only configure the tri protocol，The following error will be reported
如果我仅仅配置tri协议，就会报以下错误。
<img width="1281" alt="image" src="https://github.com/apache/dubbo/assets/24272650/c233a8b5-3344-410c-918f-f03b1451fe10">
But I added ext-protocol.Is ok!
但是我加上ext-protocol,就不会有这个问题。
配置如下：
```
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    register-mode: instance
  protocol:
    name: tri
    port: -1
   #ext-protocol: dubbo,
```

**Comment by leohao6762** [comment]
使用tri协议需要添加依赖：
`<dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>`
