### ISSUE TITLE
Imcompact rule configuration between dubbo2.7.7 and dubbo-admin v0.6.0

### ISSUE THREAD

**Issue by dxc-danny** [apache/dubbo#13380]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: win/linux
* Java version: 1.8

ps:低版本,2.6.x 条件路由没问题

### Steps to reproduce this issue

1. 自启dubbo-admin并且新建/修改条件路由
![1700048059951](https://github.com/apache/dubbo/assets/36264224/69977303-91bf-42df-a00e-b4b1a73c9efc)

2. 自己本地写了个demo调用本地dubbo服务,发现条件路由不生效(根本没有发现有条件路由当然失效了..)
![企业微信截图_17000330892062](https://github.com/apache/dubbo/assets/36264224/b2259dae-3885-43ff-b8dd-6345eba4d09a)

3. 然后从dubbo-admin中创建/修改路由 进入路由通知监听中
org.apache.dubbo.registry.integration.RegistryDirectory#notify  发现只有empty://开头的协议,并没有routers路由更改通知,怀疑admin那边订阅和通知的key,listener可能没对齐

4.zk中确实有自己新增的条件路由
![企业微信截图_17001901146404](https://github.com/apache/dubbo/assets/36264224/b77f9441-d44c-4413-a99c-78ecf0ce6d99)

大佬们麻烦看看

**Comment by ilaotan** [comment]
路过。。。 有没有试过2.7最新版 有没有可能是个bug且修复了
