### ISSUE TITLE
升级到3.2.8后序列化错误

### ISSUE THREAD

**Issue by huanyang001** [apache/dubbo#13381]
升级到3.2.8后报如下错误
[DUBBO] [Serialization Security] Serialized class xx.xx.xx. is not in allow list. Current mode is `STRICT`, will disallow to deserialize it by default. Please add it into security/serialize.allowlist or follow FAQ to configure it., dubbo version: 3.2.8, current host: xxx.xxx.xxx.xxx, error code: 4-21. This may be caused by , go to https://dubbo.apache.org/faq/4/21 to find instructions.

**Comment by HelloNewWorld33** [comment]
哥们你怎么解决的

**Comment by penghcn** [comment]
-Ddubbo.application.serialize-check-status=WARN

**Comment by penghcn** [comment]
或者加入 resources/security/serialize.allowlist中。参考官方文档https://dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/serialization/serialization/ 和https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/faq/4/21/
