### ISSUE TITLE
dubbo version 3.2.5 customer serialization failure

### ISSUE THREAD

**Issue by HXinPeng** [apache/dubbo#13399]
![image](https://github.com/apache/dubbo/assets/73336018/8f823732-4e0f-4cf5-93e5-6c753b507e5f)

**I have already set the detection level to "off," but there is still an exception during parsing.**
我已经设置好了检测级别为关闭，但是在解析时还是异常

**versions：
java：17
dubbo：3.2.5
springboot : 3.0.10
spring-data-jpa：3.0.10**

**Transferring data from customer  to Provider  is fine; however, there are abnormal when transferring data from Provider to customer ！！**
Provider 中处理好后返回信息至 customer 时就有这个问题。最终异常抛出是在customer

**ErrMsg**：[DUBBO] Decode rpc result failed: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: autoType not support input org.hibernate.collection.spi.PersistentBag, offset 207, dubbo version: 3.2.5, current host: xxxxxx

**Comment by AlbumenJ** [comment]
Have you configure this in both consumer and provider sides?

**Comment by HXinPeng** [comment]
> Have you configure this in both consumer and provider sides?

yes，I have configured both ends. I have identified the problem in more detail: When using Spring Data JPA, after adding the @OneToMany annotation to the entity, the address of the List parameter in the retrieved entity becomes PersistentBag. Is there any way to resolve this?

是的，两端都配置好了。我更详细地确定了这个问题:在使用Spring Data JPA时，在向实体添加@OneToMany注释后，查询出来的实体中的List参数的地址变成了PersistentBag。有办法解决这个问题吗?

**Comment by HXinPeng** [comment]
@AlbumenJ

**Comment by AlbumenJ** [comment]
Is `PersistentBag` exist in your consumer side?

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
