### ISSUE TITLE
Dubbo 3.2.0 使用 ContextHolderAuthenticationResolverFilter 报错

### ISSUE THREAD

**Issue by Xyk859852** [apache/dubbo#13405]
### Environment

* Dubbo version: 3.2.0
* Operating System version: Mac   
* Java version: jdk 1.8
* SpringCloud Alibaba 2021.0.1.0
* SpringCloud 2021.0.1
* SpringBoot 2.6.8

### Steps to reproduce this issue

1. 在使用dubbo 3.2.0 版本时，customer调用provider接口，报错，org.apache.dubbo.spring.security.filter.ContextHolderAuthenticationResolverFilter 这个Filter在做Json转化时报错，我在dubbo官网上面看这个filter是用于 Istio ，但是我这边的应用就只是虚拟机部署而已。

<img width="1225" alt="image" src="https://github.com/apache/dubbo/assets/39120949/81b1f610-0a7e-406c-82c6-ce9f7fff47a2">

**Comment by ShenFeng312** [comment]
看起来是你依赖了dubbo-spring-security 的原因

**Comment by Xyk859852** [comment]
这个问题我这边修复好了哈，忘记关掉了。
