### ISSUE TITLE
Direct exception delivery problem when Dubbo is upgraded to 3.2.7

### ISSUE THREAD

**Issue by liudaac** [apache/dubbo#13403]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
After Dubbo was upgraded to 3.2.7, spring was also upgraded to 6.0.13. Discover the exception delivery mechanism in the new version. Exceptions thrown at each layer are wrapped with ExecutionException and then passed upward. This causes the previous logic of using spring aspects to capture specified exceptions and return exception content to fail.

For example, for three-layer calls, the result is that the structure captured by the top layer is
```
java.lang.RuntimeException(
   java.util.concurrent.ExecutionException(
           org.apache.dubbo.rpc.RpcException(
                        java.util.concurrent.ExecutionException(
                                   cn.aradin.sdk.base.exception.CustomizedSdkException: ERRMSG
                        )
          )
   )
)
```
Similar to this multi-level structure wrapped by ExecutionException. Among them, CustomizedSdkException inherits from RpcException, and can be caught in the uppermost aspect in the old version.
Is there a solution to this?

## Ask your question here
Dubbo升级至3.2.7之后，spring也一起升级至6.0.13。发现新版中异常的传递机制，在每一层抛出的异常都使用ExecutionException包装，然后再向上传递。这就导致之前的使用spring切面抓取指定异常并返回异常内容的逻辑失效。

比如对于三层调用，造成的结果就是最上层抓到的结构为
```
java.lang.RuntimeException(
  java.util.concurrent.ExecutionException(
          org.apache.dubbo.rpc.RpcException(
                       java.util.concurrent.ExecutionException(
                                  cn.aradin.sdk.base.exception.CustomizedSdkException: ERRMSG
                       ) 
         ）
  ）
)
```
类似这种被ExecutionException包裹的多级结构。其中CustomizedSdkException继承自RpcException，在旧版中最上层的切面是可以抓到。
这个有办法解决么？

**Comment by AlbumenJ** [comment]
CustomizedSdkException is a checked exception or un-checked exception?

**Comment by liudaac** [comment]
As org.apache.dubbo.rpc.RpcException extends from RuntimeException, the CustomizedSdkException which extends from RpcException should be also a child-exception of RuntimeException. So, an un-checked exception?
