### ISSUE TITLE
`Owner` key being overrided when routing

### ISSUE THREAD

**Issue by QzLijian1** [apache/dubbo#13414]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
### Environment
* Dubbo version: 2.6X
* Operating System version: IDEA
* Java version: 1.8

### Steps to reproduce this issue
1. Provider configuration
Configure in application.properties
dubbo.applications.provider.owner=PROVIDER
Provider starts normally
2. Consumer configuration
Configure in application.properties
dubbo.applications.consumer.owner=CONSUMER
3. When the consumer obtains the application name of a provider Invoker in the provider list through List<Invoker<T>>, the data obtained is the consumer application name instead of the provider application name.

Pls. provide [GitHub address] to reproduce this issue.
### Expected Behavior
When the consumer obtains the application name of a provider Invoker in the provider list through List<Invoker<T>>, it is the provider application name PROVIDER

### Actual Behavior

When the consumer obtains the application name of a provider Invoker in the provider list through List<Invoker<T>>, it is the consumer application name CONSUMER.
If there is an exception, please attach the exception trace:

Just put your stack trace here!
Debug found that the ClusterUtils.mergeUrl() method will overwrite the provider parameters with the consumer parameters. Personal understanding and application-related parameters cannot overwrite the consumer configuration with the provider configuration, that is, do not overwrite the relevant configurations under the application.

---

### Steps to reproduce this issue
1. 提供方配置
在application.properties中配置
dubbo.applications.provider.owner=PROVIDER
提供方正常启动
2. 消费方配置
在application.properties中配置
dubbo.applications.consumer.owner=CONSUMER
3. 消费方通过List<Invoker<T>>获取提供方列表中某个提供方Invoker应用名时，取得的数据为消费方应用名而非提供方应用名

Pls. provide [GitHub address] to reproduce this issue.
### Expected Behavior
消费方通过List<Invoker<T>>获取提供方列表中某个提供方Invoker应用名时为提供方应用名PROVIDER

### Actual Behavior

消费方通过List<Invoker<T>>获取提供方列表中某个提供方Invoker应用名时为消费方应用名CONSUMER
If there is an exception, please attach the exception trace:

Just put your stack trace here!
debug发现ClusterUtils.mergeUrl()方法会将消费方参数覆盖提供方参数，个人理解与应用相关参数不能将消费方配置覆盖提供方配置，即application下相关配置不要覆盖。

**Comment by AlbumenJ** [comment]
1. `owner` is not design for routing.
2. If you want to route with properties, try specify another key
3. 2.6.x is EOL now, please upgrade to 3.2.x

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
