### ISSUE TITLE
RestProtocol convergence to TripleProtocol

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#13427]
# 中文

## 背景

在dubbo3中，rest协议和triple协议是各自独立的http实现，为了能够享受http/2的红利，同时简化http相关协议使用成本，计划将rest协议融合到triple中

## 主体思路

1. 同grpc的支持，将在triple协议中默认支持rest，当service满足rest激活条件时，注册对应rest处理handler
2. 迁移思路
   1. 保证融合后的tri能够支持原rest所有能力，直接将rest改成triple即可
   2. 对于原有调用方调用方式不变
   3. 待功能稳定后，直接将rest client call切换到triple http方式，也就是用户配置了rest，实际调用到的是triple http rpc
3. 当前triple具备完整的http/1, http/2协议栈，但是在path匹配上是固定的{service}/{method}, 因此需要增加一个`PathHandlerRouter`接口，包含一下两个实现：
   1. TriplePathHandlerRouter
      负责 triple http的路由解析
   2. RestPathHandlerRouter
      负责rest http的路由解析，优先级低于TriplePathHandlerRouter
4. 增加`PathHandlerRegistry`接口，在TripleProtocol export时，将需要的service解析并注册到`Registry`，供route时使用
5. 为了支持rest，需要有一套filter机制，来让用户能够定制一些调用行为，比如做权限校验，cors支持等，考虑在`AbstractServerTransportListener`和`AbstractServerHttpChannelObserver`中增加逻辑来支持

# English

## Background

In Dubbo 3, RestProtocol and TripleProtocol are independent HTTP implementations. To leverage the benefits of HTTP/2 and simplify the usage of HTTP-related protocols, we plan to convergence RestProtocol into TripleProtocol.

## Core Concept

1. Similar to gRPC support, Triple protocol will natively support REST. When a service meets the REST activation criteria, it will register the corresponding REST handler.
2. Migration Strategy:
   1. Ensure the merged Triple supports all existing REST capabilities; transition from REST to Triple directly.
   2. Maintain the existing call methods for current users.
   3. Once stabilized, switch REST client calls to Triple HTTP RPC. This means even if users configure REST, the actual call will be through Triple HTTP RPC.
3. While Triple currently supports complete HTTP/1 and HTTP/2 stacks, its path matching is fixed to `{service}/{method}`. Therefore, it's necessary to introduce a `PathHandlerRouter` interface with two implementations:
   1. `TriplePathHandlerRouter` for Triple HTTP routing.
   2. `RestPathHandlerRouter` for REST HTTP routing, with lower priority than TriplePathHandlerRouter.
4. Add a `PathHandlerRegistry` interface. During TripleProtocol export, parse and register necessary services to `Registry` for routing use.
5. To support REST, a filter mechanism is needed for custom call behaviors like authorization checks, CORS support, etc. Plan to add this logic in `AbstractServerTransportListener` and `AbstractServerHttpChannelObserver`.

## Pending Issues

* Whether to drop the RestProtocol client call support.
* Custom array-based argument codec parsing may be necessary due to REST's use of path variables in URLs.
* The existing `RestRequestFilter` and `RestResponseFilter`, as well as `org.apache.dubbo.rpc.protocol.rest.extension.resteasy`, might be phased out, primarily to accommodate HTTP/2 request model differences.

**Comment by AlbumenJ** [comment]
Can you pls submit a proposal to dubbo-website?

**Comment by AlbumenJ** [comment]
- Whether to drop the RestProtocol client call support.

I think we should support it in the future.

- Custom array-based argument codec parsing may be necessary due to REST's use of path variables in URLs.

Yes, we should support it

- The existing RestRequestFilter and RestResponseFilter, as well as org.apache.dubbo.rpc.protocol.rest.extension.resteasy, might be phased out, primarily to accommodate HTTP/2 request model differences.

We can implement the normal rest invoke first and see if some users request for this.
