### ISSUE TITLE
Is there any place where I can check for Dubbo security vulnerabilities? And do you have a list of the currently patched vulnerabilities?

### ISSUE THREAD

**Issue by shaonianxingzhong** [apache/dubbo#13430]
Dubbo安全漏洞有地方可以查看吗？以及目前修复的漏洞列表有吗？
Is there any place where I can check for Dubbo security vulnerabilities? And do you have a list of the currently patched vulnerabilities?

**Comment by AlbumenJ** [comment]
You can check in https://www.cvedetails.com/vulnerability-list/vendor_id-45/product_id-76651/Apache-Dubbo.html
