### ISSUE TITLE
Dead lock in Dubbo3.1.9

### ISSUE THREAD

**Issue by jybjobs** [apache/dubbo#13438]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.1.9
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue
高并发场景下偶发出现服务启动线程死锁问题，现象和[12620](https://github.com/apache/dubbo/issues/12620)类似，但项目中并未使用@scheduled之类的注解。
<img width="1363" alt="bug" src="https://github.com/apache/dubbo/assets/15391009/bb287c39-2727-4780-9c5e-e09ebd331871">

**Comment by finefuture** [comment]
Please update to the latest version and try again.
