### ISSUE TITLE
Generic type miss when injvm invoke

### ISSUE THREAD

**Issue by YAGAMIL** [apache/dubbo#13448]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.6
* Operating System version: linux or windows
* Java version: 17
* dubbo-serialization-fastjson：2.7.23

dubbo.protocol.serialization=fastjson

### Steps to reproduce this issue

1. 使用上述配置
2. 本地调用注入接口
3. 泛型返回值类型丢失，成为JSONObject导致后续操作出问题

injvm本地通过dubbo调用出现泛型丢失情况

![7891b14b68469a9a00161603ab5bf60c](https://github.com/apache/dubbo/assets/16757285/839a9c37-fb48-47eb-9725-fbb22ff4e012)

![877765f7e0dc14bbe07c020a973458ff](https://github.com/apache/dubbo/assets/16757285/fe67b35c-e93f-474b-894a-e07db01cae36)

**Comment by AlbumenJ** [comment]
Fix in https://github.com/apache/dubbo/pull/13351
