### ISSUE TITLE
The ReferenceCountExchangeClient is closed repeatedly, triggering warning logs.

### ISSUE THREAD

**Issue by XIACYBING** [apache/dubbo#13450]
1. When DubboProtocol shuts down, it destroys the held SharedClientsProvider.
2. However, afterwards, DubboProtocol calls its superclass AbstractProtocol to destroy the current protocol's Invoker, and within the DubboInvoker specific to the dubbo protocol, it destroys the held ClientsProvider (which can be a SharedClientsProvider) again. 

Is this situation reasonable? It's similar logic in both versions 2.7.15 and 3.3. This issue leads to the close method of ReferenceCountExchangeClient and the related underlying classes being called twice. 

Here is the relevant code: 

Destruction of DubboProtocol: 
![54103440bf6b69a6b8573ad6cbc03a7b](https://github.com/apache/dubbo/assets/39894036/f66e5235-6448-483e-831a-75513a283f9c)

Destruction of AbstractProtocol: 
![8ac68de90077ccc0f91898656fdef753](https://github.com/apache/dubbo/assets/39894036/b195cde2-619e-48b1-9dd0-6b4cda06eb48)

Destruction of DubboInvoker: 
![c25521f43dd264d4d2ebb352513d83a7](https://github.com/apache/dubbo/assets/39894036/b0004419-41cb-4274-b670-476c8720ad69)
 
Closing of ReferenceCountExchangeClient: 
![76ac22d651a4f1dd562045bb824e2547](https://github.com/apache/dubbo/assets/39894036/8825546d-0c61-47cb-bf4e-f20343f43d18)

---

1. DubboProtocol在关闭的时候，会对持有的SharedClientsProvider进行销毁；
2. 但是在这之后，DubboProtocol会调用父类AbstractProtocol对当前协议下的Invoker进行销毁，而在dubbo协议对应的DubboInvoker中，又会对持有的ClientsProvider（可以是SharedClientsProvider）再次进行销毁；

这个情况是合理的吗？在2.7.15版本和3.3版本都对比过，是类似的逻辑；

而这个问题会导致ReferenceCountExchangeClient内部，及相关底层类的close被二次调用

附上相关代码：
DubboProtocol的销毁：
![54103440bf6b69a6b8573ad6cbc03a7b](https://github.com/apache/dubbo/assets/39894036/f66e5235-6448-483e-831a-75513a283f9c)

AbstractProtocol的销毁：
![8ac68de90077ccc0f91898656fdef753](https://github.com/apache/dubbo/assets/39894036/b195cde2-619e-48b1-9dd0-6b4cda06eb48)

DubboInvoker的销毁：
![c25521f43dd264d4d2ebb352513d83a7](https://github.com/apache/dubbo/assets/39894036/b0004419-41cb-4274-b670-476c8720ad69)

ReferenceCountExchangeClient的关闭：
![76ac22d651a4f1dd562045bb824e2547](https://github.com/apache/dubbo/assets/39894036/8825546d-0c61-47cb-bf4e-f20343f43d18)

**Comment by AlbumenJ** [comment]
I think we can destroy all the clients before destroy DubboProtocol to prevent this error.

**Comment by XIACYBING** [comment]
> I think we can destroy all the clients before destroy DubboProtocol to prevent this error.

Will closing the SharedClientsProvider before the DubboProtocol cause any call issues? Because the DubboInvoker are still providing services to the consumer.

Can we should check the type of ClientsProvider before destroy in DubboInvoker, and all SharedClientsProvider should manage by DubboProtocol

**Comment by AlbumenJ** [comment]
> > I think we can destroy all the clients before destroy DubboProtocol to prevent this error.
> 
> Will closing the SharedClientsProvider before the DubboProtocol cause any call issues? Because the DubboInvoker are still providing services to the consumer.
> 
> Can we should check the type of ClientsProvider before destroy in DubboInvoker, and all SharedClientsProvider should manage by DubboProtocol.

Before DubboProtocol destroyed, all the DubboInvoker should have been destroyed. So, we can make sure all the DubboInvokers being destroyed and DubboProtocol will not print error message.

**Comment by AlbumenJ** [comment]
> The current situation is to destroy the DubboProtocol first and then the DubboInvokers. Should we modify it to destroy the DubboInvokers first and then the DubboProtocol?

Yes

> And when destroying the DubboProtocol, should we continue to destroy the SharedClientsProvider?

Yes, for clean up

**Comment by XIACYBING** [comment]
When we destroyed DubboInvoker, we had already destroyed the relevant ClientsProvider. If it was only for cleaning purposes, should we add a closed identifier to the AbstractClientsProvider to identify those that were not destroyed

**Comment by XIACYBING** [comment]
> > The current situation is to destroy the DubboProtocol first and then the DubboInvokers. Should we modify it to destroy the DubboInvokers first and then the DubboProtocol?
> 
> Yes
> 
> > And when destroying the DubboProtocol, should we continue to destroy the SharedClientsProvider?
> 
> Yes, for cleaning up

When we destroyed DubboInvoker, we had already destroyed the relevant ClientsProvider. If it was only for cleaning purposes, should we add a closed identifier to the AbstractClientsProvider to identify those that were not destroyed

**Comment by AlbumenJ** [comment]
> > > The current situation is to destroy the DubboProtocol first and then the DubboInvokers. Should we modify it to destroy the DubboInvokers first and then the DubboProtocol?
> > 
> > 
> > Yes
> > > And when destroying the DubboProtocol, should we continue to destroy the SharedClientsProvider?
> > 
> > 
> > Yes, for cleaning up
> 
> When we destroyed DubboInvoker, we had already destroyed the relevant ClientsProvider. If it was only for cleaning purposes, should we add a closed identifier to the AbstractClientsProvider to identify those that were not destroyed

That's ok, but only for preventing exceptions.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
