### ISSUE TITLE
Failed register interface application mapping for service xxx

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#13451]
* Dubbo version: 3.2.5
* Java version: 17

Dubbo service startup error Failed register interface application mapping for service xxxx.....
![1701481770260](https://github.com/apache/dubbo/assets/33255974/a14d1fd4-92c3-41f0-b417-692be6517e49)
Find the relevant logic in the source code in ServiceConfig
![1701481869609](https://github.com/apache/dubbo/assets/33255974/591c069d-3e23-4715-8474-b090f8afe90a)
![1701481928540](https://github.com/apache/dubbo/assets/33255974/8b2d9a94-4fc0-497f-a227-74f27d294158)
I found that there is no place to set the switch to turn off. My project is registered by application, and there is no need for interface mapping to solve these problems of transitioning to old versions.

---

dubbo服务启动报错 Failed register interface application mapping for service xxxx.....
![1701481770260](https://github.com/apache/dubbo/assets/33255974/a14d1fd4-92c3-41f0-b417-692be6517e49)
在源码中找到相关逻辑地方在ServiceConfig
![1701481869609](https://github.com/apache/dubbo/assets/33255974/591c069d-3e23-4715-8474-b090f8afe90a)
![1701481928540](https://github.com/apache/dubbo/assets/33255974/8b2d9a94-4fc0-497f-a227-74f27d294158)
发现没有地方可以设置关掉的开关，我的项目是按应用注册，不需要接口映射这些过渡老版本的问题

**Comment by AlbumenJ** [comment]
Service name mapping is a required option for app level service discovery even though you do not want to compact with 2.7.x or interface level service discovery.

**Comment by AlbumenJ** [comment]
> > Service name mapping is a required option for app level service discovery even though you do not want to compact with 2.7.x or interface level service discovery.
> 
> 在我的项目里是完完全全的应用级服务发现，不需要接口级的。我觉得还是有必要有开关可以关掉，即使为了兼容老用户让这个开关默认开启，但也不能让没有历史负担的新项目承担这个兼容问题

This is the **requirement** of application level service discovery.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
