### ISSUE TITLE
No response on http protocol

### ISSUE THREAD

**Issue by cookiejoo** [apache/dubbo#13503]
如题：
由于某些原因没有ZK部署只能把之前的dubbo接口全部改成http方式调用，客户端使用dubbo的Reference bean指定了http地址

@Bean(name = "testFacade")
    public SensitiveDataSecretKeyFacade sensitiveDataSecretKeyFacade() {
        ReferenceConfig<TestFacade> reference = new ReferenceConfig<>();
        reference.setApplication(applicationConfig);
        reference.setRegistry(defaultRegistryConfig);
        reference.setProtocol(HTTP_PROTOCOL);
        reference.setUrl("http://localhost:8080/");
        reference.setInterface(TestFacade.class);
        reference.setTimeout(3000);
        reference.setCheck(false);
        return reference.get();
    }

 Response<List<TestDomain>> response = testFacade.getAllSecretKeys();
 没次调用这个都是为null，但是服务端都已经进去了，服务端的返回代码如下：

服务端无dubbo依赖，纯SpringBoot web模块，用什么方式返回数据，客户端才能收到？

`
@Controller
@RequestMapping
public class DubboController {

    // {"id":"-1653306013559333894","jsonrpc":"2.0","method":"getAllSecretKeys"}
    @RequestMapping(value = "/xxx.facade.TestFacade")
    public Response<List<TestDomain>> testFacade(HttpServletRequest request,
                                                             HttpServletResponse response) throws IOException {
        System.out.println(request);
        try {
            ServletInputStream inputStream = request.getInputStream();
            if (inputStream != null) {
                String[] list = IOUtils.readLines(inputStream);
                StringBuffer stringBuffer = new StringBuffer();
                for (String s : list) {
                    stringBuffer.append(s);
                }

                String objString = stringBuffer.toString();
                System.out.println(objString);
            }
        } catch (IOException e) {
            log.error("agent info error:", e);
        }
        Response<List<TestDomain>> r = new Response<>();
        List<TestDomain> l = Lists.newArrayList();
        TestDomain d = new TestDomain();
        d.setVersion(1);
        l.add(d);
        r.success(l);
        String json = new Gson().toJson(r);
        response.getOutputStream().write(json.getBytes(StandardCharsets.UTF_8));
        response.flushBuffer();
        return r;
    }
`
我尝试了四种方式
1：直接返回Response<List<TestDomain>> 无效
2：用ResponseEntity<Response<List<TestDomain>>>  包装返回也无效
3：用response.getOutputStream().write(json) 也无效
4：用@ResponseBody 也无效

求助各位大能，帮帮我。

**Comment by AlbumenJ** [comment]
What version do you use?
Http protocol is not well useful. 3.3.x is improving it now.

**Comment by cookiejoo** [comment]
> What version do you use? Http protocol is not well useful. 3.3.x is improving it now.

is dubbo 2.7.4

**Comment by AlbumenJ** [comment]
> > What version do you use? Http protocol is not well useful. 3.3.x is improving it now.
> 
> is dubbo 2.7.4

Please try using the latest version. BTW, http protocol is not well deveploed now :)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
