### ISSUE TITLE
MetricsDispatcher  should initial after  org.apache.dubbo.config.spring.context.DubboInfraBeanRegisterPostProcessor

### ISSUE THREAD

**Issue by focuse8** [apache/dubbo#13501]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.5
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

In 3.2.5, MetricsDispatcher initials before org.apache.dubbo.config.spring.context.DubboInfraBeanRegisterPostProcessor registers.  When objects of MetricsCollector  are created, they won't be set properties from spring context

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
no jstack

**Comment by AlbumenJ** [comment]
@conghuhu PTAL

**Comment by wxbty** [comment]
@focuse8   MetricsCollectors are loaded by spi and can be injected into springbean using setter, refer to https://cn.dubbo.apache.org/zh-cn/docsv2.7/dev/source/adaptive-extension/

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
