### ISSUE TITLE
Dubbo 2.7.12 LFUCache Memory leak  bug

### ISSUE THREAD

**Issue by GuanghuiCong** [apache/dubbo#13500]
Environment
Dubbo version: 2.7.12
Operating System version: linux
Java version: 1.8

Description
使用dubbo2.7.12版本出现内存泄漏Bug，gc也无法回收，在本地通过有感网关桥调用服务，发现有感在请求时会附带generic=true的参数，在服务端generic=true会先进入GenericFilter的invoke函数(104行，PojoUtils.realize(args, params, method.getGenericParameterTypes()))，做class的序列化，在SerializeClassChecker的validateClass中使用到lfuCache，但是LFUcache存在bug，最终导致内存泄漏。
产生原因：这个 pr [7967 ](https://github.com/apache/dubbo/pull/7967) 导致了该问题

![3f03e2b089d67633744f3237c1bc4be9](https://github.com/apache/dubbo/assets/79358121/01e4b57f-83b9-4db2-bdf0-9641cad313e7)
 抓包发现：
![image](https://github.com/apache/dubbo/assets/79358121/c8bab51c-8368-42e5-9dcf-49d266d35c69)

**Comment by AlbumenJ** [comment]
Fixed in https://github.com/apache/dubbo/pull/10086

**Comment by AlbumenJ** [comment]
Please upgrade to the latest version
