### ISSUE TITLE
hessian2 performance issue

### ISSUE THREAD

**Issue by xuwangxin** [apache/dubbo#13516]
Reflection is used extensively in the class constructors in the com.alibaba.com.caucho.hessian.io.java8 package. From the source code, we already know the data type of the object currently passed in. Can we directly obtain the real object through forced transfer? Attributes?
![image](https://github.com/apache/dubbo/assets/142288246/820e9243-0397-4983-b5b2-299023e800cd)

When using jmh for benchmark testing, monitoring the CPU usage through pyroscope is actually relatively high.
![image](https://github.com/apache/dubbo/assets/142288246/fa01a09d-1f3e-4b90-a9ea-120395c0e542)

---
com.alibaba.com.caucho.hessian.io.java8包里类构造函数里大量用到了反射，从源码看其实已经知道当前传进来的对象的数据类型，是否可以直接通过强转拿到真实对象获取属性？
![image](https://github.com/apache/dubbo/assets/142288246/820e9243-0397-4983-b5b2-299023e800cd)

用jmh做基准测试时通过pyroscope监控cpu占用其实是比较高的
![image](https://github.com/apache/dubbo/assets/142288246/fa01a09d-1f3e-4b90-a9ea-120395c0e542)

**Comment by AlbumenJ** [comment]
Please try switch to jsonb serialziation if you want better performance cause hessian2 is hard to maintain now which is very different from the branch of caucho.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
