### ISSUE TITLE
If the server interface is abnormal, the exception stack information will be serialized to the client.

### ISSUE THREAD

**Issue by zhangxqianger** [apache/dubbo#13512]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.5
* Operating System version: linux
* Java version: 1.8

### Actual Behavior

<img width="1295" alt="图片" src="https://github.com/apache/dubbo/assets/9571520/96252668-9239-44d3-b0f0-575a8d26827c">

![WeChate65b93d84a638c9d27f3883acaa8d1ba](https://github.com/apache/dubbo/assets/9571520/1691e842-daac-4650-bc41-56017bee21f6)

![WeChat2120d15e65c73429b977298e4d60add4](https://github.com/apache/dubbo/assets/9571520/8ce142c7-63f0-4102-8ce6-cf3bb29936ae)

If an exception occurs in the interface, AsyncRpcResult#newDefaultAsyncResult will encapsulate the exception into an AppResponse object. future.complete(result) will cause the HeaderExchangeHandler to not recognize the future exception, and will give the AppResponse class sequence with the exception stack to the client, and the client will deserialize the exception information. It is because the exception stack class information on the server cannot be loaded, causing the metaspace to grow infinitely.

如果接口出现异常，AsyncRpcResult#newDefaultAsyncResult会把异常封装成AppResponse对象，future.complete(result)导致HeaderExchangeHandler无法识别future异常，会把带有异常堆栈的AppResponse类序列给客户端，客户端反序列化异常信息是因为无法加载服务端的异常堆栈class信息导致metaspace无限增长。

**Comment by AlbumenJ** [comment]
1. Transmit stack trace to client is **by design** and is a important message to locate the real problem.
2. Metaspace is not depended on the stack trace length or the expcetion itself will not effect the metaspace.
