### ISSUE TITLE
RemotingException failed to connect to server xxx.xx.xx.xx:20880 client-side timeout 3000ms

### ISSUE THREAD

**Issue by aillamsun** [apache/dubbo#13511]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* Operating System version: k8s pod container
* Java version: 1.8
* Registration center: nacos2.x (Huawei Cloud instance)

### Steps to reproduce this issue

A -> B

1. There is nothing in the code. Click pod (number > 1) to restart (service B)
2. Then there is an RPC request for service A and service B fails.
3. Then restart service B, and service A requests service B normally.

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

#### The warning log found in the startup log is as follows:

```java
dubbo version: 3.2.0, current host: 10.95.19.65, error code: 2-12. This may be caused by condition router get providerApplication is empty, will not subscribe to provider app rules., go to https://dubbo. apache.org/faq/2/12 to find instructions.
```
#### The request call error log is as follows:
```java
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.95.14.154:20880/com.sinr.business.facade.BizMerchantCustomConfigFacadeService?anyhost=true&application=dubbo-mobile-consumer&background=false&category=providers,configurators, routers&check=false&codec=dubbo&delay=-1&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&file-cache=true&generic=false&group=usercenter-k8s&heartbeat=60000&interface=com.sinoiov.usercenter.business.facade.BizMerchantCustomConfigroundFacadeService&loadbalance=rob in&logger=log4j2&methods =queryMerchantCustomConfigByCode,queryMerchantCustomConfigByCodeAndKey&path=com.si.business.facade.BizMerchantCustomConfigFacadeService&pid=20&prefer.serialization=fastjson2,hessian2&protocol=dubbo&qos.enable=true&release=3.2.0&retries=0&revision=2.0.1& service-name-mapping=true&service.filter=traceFilter&side=consumer&sticky =false&timeout=30000&timestamp=1702460530573&unloadClusterRelated=false) failed to connect to server /10.95.14.154:20880 client-side timeout 3000ms (elapsed: 3000ms) from netty client 10.95.9.125 using dubbo version 3.2.0
```

---

- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.0
* Operating System version: k8s pod容器
* Java version: 1.8
* 注册中心: nacos2.x （华为云实例）

### Steps to reproduce this issue

A -> B 

1. 代码无任何，点击pod（个数>1）重启（服务B）
2. 然后出现A服务RPC请求B 服务失败
3. 然后在重启服务B，服务A请求服务B正常

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

#### 启动日志发现警告log如下:

```java
dubbo version: 3.2.0, current host: 10.95.19.65, error code: 2-12. This may be caused by condition router get providerApplication is empty, will not subscribe to provider app rules., go to https://dubbo.apache.org/faq/2/12 to find instructions. 
```
#### 请求调用错误日志如下：
```java
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.95.14.154:20880/com.sinr.business.facade.BizMerchantCustomConfigFacadeService?anyhost=true&application=dubbo-mobile-consumer&background=false&category=providers,configurators,routers&check=false&codec=dubbo&delay=-1&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&file-cache=true&generic=false&group=usercenter-k8s&heartbeat=60000&interface=com.sinoiov.usercenter.business.facade.BizMerchantCustomConfigFacadeService&loadbalance=roundrobin&logger=log4j2&methods=queryMerchantCustomConfigByCode,queryMerchantCustomConfigByCodeAndKey&path=com.si.business.facade.BizMerchantCustomConfigFacadeService&pid=20&prefer.serialization=fastjson2,hessian2&protocol=dubbo&qos.enable=true&release=3.2.0&retries=0&revision=2.0.1&service-name-mapping=true&service.filter=traceFilter&side=consumer&sticky=false&timeout=30000&timestamp=1702460530573&unloadClusterRelated=false) failed to connect to server /10.95.14.154:20880 client-side timeout 3000ms (elapsed: 3000ms) from netty client 10.95.9.125 using dubbo version 3.2.0
```

**Comment by aillamsun** [comment]
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.95.0.166:20880/com.sinoiov.usercenter.business.facade.syncdata.BizSyncDataFacadeService?anyhost=true&application=dubbo-mobile-consumer&background=false&category=providers,configurators,routers&check=false&codec=dubbo&delay=-1&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&file-cache=true&generic=false&group=usercenter-k8s&heartbeat=60000&interface=com.sinoiov.usercenter.business.facade.syncdata.BizSyncDataFacadeService&loadbalance=roundrobin&logger=log4j2&methods=companyAuthFromDaka,realNameFromDaka,vehicleAuthFromDaka&path=com.sinoiov.usercenter.business.facade.syncdata.BizSyncDataFacadeService&pid=20&prefer.serialization=fastjson2,hessian2&protocol=dubbo&qos.enable=true&release=3.2.0&retries=0&revision=2.0.1&service-name-mapping=true&service.filter=traceFilter&side=consumer&sticky=false&timeout=30000&timestamp=1702460540044&unloadClusterRelated=false) failed to connect to server /10.95.0.166:20880 client-side timeout 3000ms (elapsed: 3000ms) from netty client 10.95.9.125 using dubbo version 3.2.0


从日志看 请求failed to connect to server /10.95.0.166:20880 失败了 实际注册中心 已经不是这个地址了

<img width="151" alt="image" src="https://github.com/apache/dubbo/assets/8295963/710434b4-bf98-4048-a587-fd1be944d824">

**Comment by AlbumenJ** [comment]
1. Please take a memory dump when request failed
2. Please feel free to upgrade to the latest version

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.

**Comment by lihuagang03** [comment]
我们今天下午也遇到了这个问题，还没去深究原因。
和运维沟通，没有阿里云Pod容器实例之间的网络监控，不好查看确认。提供者IP是有效且存在的
`dubbo-3.2.10`和`triple`协议

完整的异常调用栈

```
timestamp:2024-08-12T18:06:18.441 
message: [DUBBO] Fail to connect to null, dubbo version: 3.2.10, current host: 192.168.108.87, error code: 6-16. This may be caused by , go to https://dubbo.apache.org/faq/6/16 to find instructions. 
thread:NettyClientWorker-10-2 
logger:org.apache.dubbo.remoting.transport.netty4.NettyConnectionHandler 
level:ERROR 
exception:org.apache.dubbo.remoting.RemotingException: client(url: tri://192.168.119.252:8506/com.lefit.dubbo.push.api.dubbo.ums.IPushService?application=lefit-push&background=false&category=providers,configurators,routers&check=false&check.serializable=false&cluster=failfast&deprecated=false&dubbo=2.0.2&dynamic=true&executor-management-mode=isolation&file-cache=true&generic=false&interface=com.lefit.dubbo.push.api.dubbo.ums.IPushService&logger=slf4j&metadata-service-port=8502&metadata-service-protocol=dubbo&methods=send&owner=***&pid=8&prefer.serialization=hessian2&qos.accept.foreign.ip=true&qos.enable=true&qos.port=22222&release=3.2.10&retries=2&revision=1.1.27&serialization=hessian2&serialize.check.status=DISABLE&service-name-mapping=true&service.filter=dubboAccessFilter&side=provider&sticky=false&timeout=3000&unloadClusterRelated=false) 
failed to connect to server /192.168.119.252:8506 client-side timeout 3000ms (elapsed: 3001ms) from netty client 192.168.108.87 using dubbo version 3.2.10
 at org.apache.dubbo.remoting.transport.netty4.NettyConnectionClient.doConnect(NettyConnectionClient.java:204)
 at org.apache.dubbo.remoting.transport.netty4.NettyConnectionHandler.lambda$reconnect$0(NettyConnectionHandler.java:87)
 at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
 at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
 at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:750)
```

6-16 - 重连时发生异常
可能的原因
每次发生重连时提示，网络不稳定造成的延迟重连。

排查和解决步骤
检查是否有网络丢包情况。

**Comment by qiubyte** [comment]
same problem, dubbo3.3.0

**Comment by tokamaky** [comment]
same problem, dubbo3.3.0

**Comment by tradeshark** [comment]
same problem ,dubbo 3.3.1
