### ISSUE TITLE
Dubbo 3.2.9 Config DUBBO_REGISTRY_ADDRESS invalid

### ISSUE THREAD

**Issue by jsbxyyx** [apache/dubbo#13543]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.9
* Operating System version: k8s
* Java version: 17

### Steps to reproduce this issue

use dubbo-spring-boot-starter 3.2.9 config `DUBBO_REGISTRY_ADDRESS: nacos://nacos-svc:8848` on k8s environment invalid.
config properties on nacos console, normal run.

使用dubbo-spring-boot-starter 3.2.9 在k8s中配置 `DUBBO_REGISTRY_ADDRESS: nacos://nacos-svc:8848`不生效
配置属性到nacos控制台正常运行

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
This is not available in 3.2.x and expected to being fixed in 3.3.x by @chickenlj
