### ISSUE TITLE
Does Dubbo support the interoperability between dubbo2 and proxyless dubbo3 or dubbo3 sidecar?

### ISSUE THREAD

**Issue by HEIBAIJIE** [apache/dubbo#13547]
- [ √] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo2升级到dubbo3可以通过双注册的方式实现平滑升级，相互访问。
dubbo3到dubbo mesh由于服务发现都是基于K8S Service，应该也可以相互访问。
但是dubbo2到dubbo mesh是否支持互通，以保证平滑演进呢？

**Comment by AlbumenJ** [comment]
You should register all the upgraded providers to registry.

**Comment by maglna1** [comment]
> You should register all the upgraded providers to registry.
请问是这个意思吗？即仅支持单向调用：
![image](https://github.com/apache/dubbo/assets/54428342/0bcd803d-35a5-4c70-bb75-eec22e0ca210)
![image](https://github.com/apache/dubbo/assets/54428342/bf18fed3-5183-4135-a77c-8ac49d4d8a0f)
![image](https://github.com/apache/dubbo/assets/54428342/73885a43-369f-43cf-9be0-2d3904bdce87)
![image](https://github.com/apache/dubbo/assets/54428342/6d686740-a04e-46eb-bdc5-299538097171)

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
