### ISSUE TITLE
metrics version doesn't change when receiving event in AggregateMetricsCollector

### ISSUE THREAD

**Issue by focuse8** [apache/dubbo#13544]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

```
public void onEvent(RequestEvent event) {
        if (enableQps) {
            MethodMetric metric = calcWindowCounter(event, MetricsKey.METRIC_REQUESTS);
            TimeWindowCounter qpsCounter = qps.get(metric);
            if (qpsCounter == null) {
                qpsCounter = ConcurrentHashMapUtils.computeIfAbsent(
                        qps,
                        metric,
                        methodMetric -> new TimeWindowCounter(
                                bucketNum, TimeUnit.MILLISECONDS.toSeconds(qpsTimeWindowMillSeconds)));
                samplesChanged.set(true);
            }
            qpsCounter.increment();
        }
    }
```

the source above in AggregateMetricsCollector.class shows that the field "samplesChanged" changed only if  there is a new TimeWindowCounter.   
A event causing  qps to change  won't be collected.  Is that expected?

**Comment by AlbumenJ** [comment]
`samplesChanged` is design to notify micrometer that any metric collectors are changed, which we need to register a new metrics to micrometer. If metrics value it self changed, micrometer can perceive it.

**Comment by AlbumenJ** [comment]
You can check in `org.apache.dubbo.metrics.report.AbstractMetricsReporter#registerSample`

**Comment by focuse8** [comment]
Got it!  Thank you!  I thought  the value of GaugeMetricSample was a number . it is the Object of TimeWindowQuantile.
