### ISSUE TITLE
Get all addresses from registry

### ISSUE THREAD

**Issue by flybh521** [apache/dubbo#13542]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
如何 使用dubbo本身的框架获取 注册中心上的所有服务的地址

**Comment by chrissun951** [comment]
<img width="711" alt="image" src="https://github.com/apache/dubbo/assets/29780304/26cf7308-7251-4da6-b12a-9a3d2f224ed3">


org.apache.dubbo.registry.RegistryService#subscribe

**Comment by flybh521** [comment]
嗯嗯  我的意思时  我使用了 dubbo起了一个 消费者，  如何通过dubbo 获取到我订阅的所有服务，也就是所有的服务存在框架的哪个地方， 我想取出来所有的服务  做点自己的逻辑。   看框架源码 看蒙圈了。 特来问问。

**Comment by chrissun951** [comment]
先要能手动订阅一个服务,

**Comment by AlbumenJ** [comment]
What is the purpose? Maybe you can use `Router`.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
