### ISSUE TITLE
Introduce bytebuddy proxy in apache/dubbo-spi-extensions.

### ISSUE THREAD

**Issue by CrazyHZM** [apache/dubbo#13555]
Dubbo's default proxy is javassist. It has been tested by the practice of mass production.
Bytebuddy proxy can be chosen from dubbo-spi-exntensions. It still needs to be tested over time.

**Comment by kimmking** [comment]
ByteBuddy is better for maintaining.

**Comment by AlbumenJ** [comment]
Track in https://github.com/apache/dubbo/issues/13867
