### ISSUE TITLE
Native memory leak question

### ISSUE THREAD

**Issue by DaiChaoLi** [apache/dubbo#13561]
Environment:
jdk version: jdk17 (this is the key point)
Dubbo version: Basically all the current versions, I haven’t tried them all, but if you try 2.7-the latest version, they basically have them.

Steps to reproduce (required):
1.@Reference(parameters = {"sent", "true"}), that is, sent is set to true
2. It is best to set up a timer and then call it in a for loop, so that you can easily observe the growth of memory.

Phenomenon:
After turning on -XX:NativeMemoryTracking, through the above reproduction steps, it is found that the Internal area memory continues to increase. It can be seen from the code that it is basically netty's future.await(timeout) line of code that affects the jdk17 environment. After testing, it was found that jdk21 does not have this problem. Strictly speaking, this is a problem with Netty, but from the perspective of the phenomenon, this can be reproduced by dubbo's sent configuration, so I came here to ask.

---

环境：
jdk版本：jdk17（这个是重点）
Dubbo版本：基本目前全部版本，没全部试过，但是你把2.7-最新版本都试一下，基本都有

重现步骤（必现）：
1.@Reference(parameters = {"sent", "true"}),即sent设置成true
2.最好搞个定时器，然后for循环调用，这样方便观察内存的增长

现象：
开启-XX:NativeMemoryTracking后，通过上述重现步骤，发现Internal区域内存不断增加。从代码可知，基本是netty的future.await(timeout)这行代码在jdk17的环境下影响到了，经测试，发现jdk21没有这个问题。严格来说这个是netty的问题，但是从现象而言，这个由dubbo的sent配置可以重现，因此也过来一起问问。

**Comment by AlbumenJ** [comment]
1. Pls test on JDK 8 and 11
2. Have you submit a issue to netty?
3. `sent` means not care about the result which is also means that will return immediately and request might not have written successfully.
