### ISSUE TITLE
Unexpected bind.ip in nacos registry

### ISSUE THREAD

**Issue by geekerzhou** [apache/dubbo#13579]
In the case of docker + nacos
DUBBO_IP_TO_REGISTRY,DUBBO_PORT_TO_REGISTRY are configured. The purpose is to register to nacos the host machine, not the virtual IP of docker.
The service can be registered normally and the consumer can be called normally, but the bind.ip attribute of the parameter registered on nacos is still the docker ip. As a result, the consume end keeps reporting the error Not found exported service: xx/org.apache.dubbo.metadata.MetadataService:1.0.0:20880

---

docker + nacos 情况下
配置了DUBBO_IP_TO_REGISTRY,DUBBO_PORT_TO_REGISTRY。目的是注册到 nacos 的是宿主机，而不是 docker 的虚拟 ip。
服务可以正常注册，consumer 也可以正常调用，但是注册到 nacos 上的 parameter 的 bind.ip 属性仍然为 docker 的 ip。导致 consume 端一直报错Not found exported service: xx/org.apache.dubbo.metadata.MetadataService:1.0.0:20880

**Comment by AlbumenJ** [comment]
Please submit a demo to verify this

**Comment by CrazyHZM** [comment]
Similar to the problem description: https://github.com/apache/dubbo/issues/9617

**Comment by kimmking** [comment]
Use the latest codes, I find the ip registered to Nacos, sometimes 127.xxx, and sometimes 192.xxx.

**Comment by rtry** [comment]
目前关于注册的IP，能用的方式
1.通过配置参数 DUBBO_IP_TO_BIND 指定IP
2.通过配置参数 dubbo.network.interface.preferred=eth0 指定网卡偏好
3.改host
4.自行扩展部分代码，通过代码注入需要的IP

不知道还有其他方式么？ 

集群的部署，Ip本来就是漂移的，Dubbo 在容器内获取IP进行注册的时候，现在的NetUtils 这个类，完全有可能拿不到想要的IP，为什么不提供一个 IP段的配置？

集群之间网络是通的，但是容器可以有多个网卡，获取IP很有可能也会获取到其他IP，也会出现不通的情况

**Comment by kimmking** [comment]
> 目前关于注册的IP，能用的方式 1.通过配置参数 DUBBO_IP_TO_BIND 指定IP 2.通过配置参数 dubbo.network.interface.preferred=eth0 指定网卡偏好 3.改host 4.自行扩展部分代码，通过代码注入需要的IP
> 
> 不知道还有其他方式么？
> 
> 集群的部署，Ip本来就是漂移的，Dubbo 在容器内获取IP进行注册的时候，现在的NetUtils 这个类，完全有可能拿不到想要的IP，为什么不提供一个 IP段的配置？
> 
> 集群之间网络是通的，但是容器可以有多个网卡，获取IP很有可能也会获取到其他IP，也会出现不通的情况

一个好的实践是实现容器的In-place重启，IP不变

**Comment by onceMisery** [comment]
> 目前关于注册的IP，能用的方式 1.通过配置参数 DUBBO_IP_TO_BIND 指定IP 2.通过配置参数 dubbo.network.interface.preferred=eth0 指定网卡偏好 3.改host 4.自行扩展部分代码，通过代码注入需要的IP
> 
> 不知道还有其他方式么？
> 
> 集群的部署，Ip本来就是漂移的，Dubbo 在容器内获取IP进行注册的时候，现在的NetUtils 这个类，完全有可能拿不到想要的IP，为什么不提供一个 IP段的配置？
> 
> 集群之间网络是通的，但是容器可以有多个网卡，获取IP很有可能也会获取到其他IP，也会出现不通的情况

不知这个配置dubbo.network.interface.ignored=docker0是否可行

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
