### ISSUE TITLE
code

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo#13589]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.x 
* Operating System version: windows
* Java version: jdk8

### Steps to reproduce this issue

1. new DubboService
2. add debug break point and add condition
3. run dubboService

![image](https://github.com/apache/dubbo/assets/12695349/ae811a9d-0acd-4761-b2bd-fe18638b80c8)

`org.apache.dubbo.common.extension.ExtensionLoader#injectExtension`

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

there is a test method but execute by `org.apache.dubbo.common.extension.ExtensionLoader#injectExtension`

org.apache.dubbo.rpc.filter.ExceptionFilter#setLogger

![image](https://github.com/apache/dubbo/assets/12695349/7a548b59-be97-4532-b12f-5b9c834c191d)

### Actual Behavior

test code will be invoke by execute，and logger be replaced.

**Comment by AlbumenJ** [comment]
Already fixed
