### ISSUE TITLE
OkHttpClient should use connection pool

### ISSUE THREAD

**Issue by icodening** [apache/dubbo#13596]
It seems that HTTP connection pooling is not used and can be optimized

<img width="678" alt="image" src="https://github.com/apache/dubbo/assets/42876375/439ed760-d3dd-4007-9af5-5b97feb785c8">

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

**Comment by kimmking** [comment]
I think we should add .connectionPool(xxxx) to resolve this issue.

**Comment by conghuhu** [comment]
closed by #14079
