### ISSUE TITLE
serialization format error

### ISSUE THREAD

**Issue by xm101** [apache/dubbo#13602]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

provider:
* **Dubbo version: 2.6.7**
* **Fastjson version: 1.2.71**
* Java version: 1.8

consumer:
* **Dubbo version: 3.2.9**
* **Fastjson version: 2.0.43**
* Java version: 1.8

### Steps to reproduce this issue

1. 提供方返回对象Map<BigInteger,Date> ，filter打印返回值日志：{\"526\":\"2023-10-19\"}
2. 调用方获取结果，打印返回值：{\"526\":{\"value\":\"2023-10-19 00:00:00\"}}

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

得到返回值类型Map<BigInteger,Date>

### Actual Behavior

得到返回值类型Map<BigInteger,Map<String, Date>>

**Comment by AlbumenJ** [comment]
Have you configured with `fastjson` serialization?

**Comment by xm101** [comment]
> Have you configured with `fastjson` serialization?

Not configured,it should be serialized by hession2 and deserialized by fastjson2

**Comment by xm101** [comment]
![image](https://github.com/apache/dubbo/assets/20034630/7b1655e3-ce26-4a58-9467-49784a7f77ee)
hessian-lite-3.2.13，无法解析Date类型？

**Comment by xm101** [comment]
已解决，增加serialize.allowlist
