### ISSUE TITLE
Has dubbo released a version that supports jdk21?

### ISSUE THREAD

**Issue by yuyu1025** [apache/dubbo#13608]
As we all know, jdk21 introduced virtual threads, and this will bring a big performance boost to IO-frequent frameworks. Therefore, I would like to know
- Does dubbo support jdk21?
- Will dubbo support virtual threads?
- Does dubbo still need netty and is it possible to use a simpler BIO socket framework?

**Comment by AlbumenJ** [comment]
1. The latest Dubbo 3.2.x version support jdk 21.
2. Virtual threads will be supported in Dubbo 3.3.x. 3.3.0-beta.1 has supported it.
3. We have no ideas about BIO socket cause it may change a lot for Dubbo framework. Do you have any ideas? It would be welcome if you submit a propose for it.

**Comment by kimmking** [comment]
Another way is rebuilding dubbo in a reactive fx.
