### ISSUE TITLE
dubbo2.7.22 BroadcastCluster2Invoker When the service provider returns a void value, an NPE exception occurs.

### ISSUE THREAD

**Issue by November22** [apache/dubbo#13606]
### Environment

* Dubbo version: 2.7.22 

### Steps to reproduce this issue

1. privoder returns a void value
2. use BroadcastCluster2Invoker 

![image](https://github.com/apache/dubbo/assets/26109828/47470e58-f232-4caf-9622-4aa3687506d0)

**Comment by November22** [comment]
can be modified to `Object value = res.resultList.stream().map(it->it.getData()).filter(Objects::nonNull).findFirst().orElse(null);`

**Comment by AlbumenJ** [comment]
Please check on 3.2.x branch.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.

**Comment by yellowsand1** [comment]
I also encounter this problem. And I see broadcast2 was removed in later version ? Plz can u explain y ? Its really costy to infvoke in loop in my case , but I'm afraid boardcast2 may cause other problem since u guys decide to remove XD.
