### ISSUE TITLE
Error name about registry cache

### ISSUE THREAD

**Issue by shaowYe** [apache/dubbo#13603]
MultipleRegistry 的initReferenceRegistry方法中
 final URL registryUrl = URL.valueOf(tmpUrl).addParameterIfAbsent(CHECK_KEY, url.getParameter(CHECK_KEY, "true"));

没有把 tmpUrl 中的 application 参数放到 registryUrl中，导致创建 registry 缓存的文件名中的 application 取到的是 null
![image](https://github.com/apache/dubbo/assets/19586802/4fc29059-250a-48fc-a6cb-5899070ed6a8)

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/13633
