### ISSUE TITLE
Why enter ServiceAnnotationPostProcessor twice

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#13623]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Operating System version: win
* Java version: 17

### Steps to reproduce this issue

First time entering
![image](https://github.com/apache/dubbo/assets/31852897/0e22beed-5414-432c-86f6-8bc9c1271809)

second time entry
![image](https://github.com/apache/dubbo/assets/31852897/fbc457e1-aaed-4ba6-adac-5fd647b80672)

Then the second time you enter, the implementation class cannot be scanned, resulting in a warning report. The services are all one service.
![image](https://github.com/apache/dubbo/assets/31852897/27d3b3b8-4e1d-4f38-870d-b90dd93aff31)

There are implementation classes under the package and corresponding annotations.
![image](https://github.com/apache/dubbo/assets/31852897/53e94412-f347-4c88-9d0b-68da2739ae08)
![image](https://github.com/apache/dubbo/assets/31852897/ab610b73-c729-4323-8526-7f1457050493)
![image](https://github.com/apache/dubbo/assets/31852897/f958c1ad-444a-4f0f-accd-9804a299b252)

I don’t understand why it can’t be scanned. Did I understand something wrong or is there something wrong with which part I’m using?

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

---

- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Operating System version: win
* Java version: 17

### Steps to reproduce this issue

第一次进入
![image](https://github.com/apache/dubbo/assets/31852897/0e22beed-5414-432c-86f6-8bc9c1271809)

第二次进入
![image](https://github.com/apache/dubbo/assets/31852897/fbc457e1-aaed-4ba6-adac-5fd647b80672)

然后第二次进入就扫描不到实现类了 导致报warn  服务都是一个服务
![image](https://github.com/apache/dubbo/assets/31852897/27d3b3b8-4e1d-4f38-870d-b90dd93aff31)

包下都是有实现类的 也有对应的注解
![image](https://github.com/apache/dubbo/assets/31852897/53e94412-f347-4c88-9d0b-68da2739ae08)
![image](https://github.com/apache/dubbo/assets/31852897/ab610b73-c729-4323-8526-7f1457050493)
![image](https://github.com/apache/dubbo/assets/31852897/f958c1ad-444a-4f0f-accd-9804a299b252)

不理解为啥扫描不到 是不是我理解错什么了 或者哪块用的有问题

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by liufeiyu1002** [comment]
首先说为啥会扫描2次， 他是由不同的俩个 `ServiceAnnotationPostProcessor` 类实例扫描的 第一个`ServiceAnnotationPostProcessor` 实例创建的时机是 通过 enabledubbo 注解注入的 从 `DubboComponentScanRegistrar` 类中，第二个实例是 springboot autoconfig 的spring.factories 文件扫描注入的 当配置了 属性  `dubbo.scan.base-packages` 以后会注入一个 `ServiceAnnotationPostProcessor` 新的实例对象

**Comment by AlbumenJ** [comment]
Please translate the content to English:)

**Comment by JavaLionLi** [comment]
> 首先说为啥会扫描2次， 他是由不同的俩个 `ServiceAnnotationPostProcessor` 类实例扫描的 第一个`ServiceAnnotationPostProcessor` 实例创建的时机是 通过 enabledubbo 注解注入的 从 `DubboComponentScanRegistrar` 类中， 第二个实例是 springboot autoconfig 的spring.factories 文件扫描注入的 当配置了 属性 `dubbo.scan.base-packages` 以后会注入一个 `ServiceAnnotationPostProcessor` 新的实例对象 (查看 DubboAutoConfiguration )
> 
> 为啥第二次会扫描不到 因为 用了容器中的 `servicePackagesHolder` 来校验了 扫描路径是否被扫描过 以及类是否已经被扫描过，如果被扫描过是不会再次被扫描的 所以你的第二次进入是一个空的返回， 你第一次的扫描路径是 `org.dromara.system`(EnableDubbo 的scanBasePackages 属性) 第二个为 `org.dromara.**.dubbo` (properties中 dubbo.scan.base-packages) 第二个路径的所有类都在第一个路径中扫描过时 第二个路径就不会扫描返回到任何类

那是否配了 `dubbo.scan.base-packages` 就不需要 `EnableDubbo ` 注解了, 或者`EnableDubbo `标注后 就不需要 `dubbo.scan.base-packages` 配置了
