### ISSUE TITLE
base-packages：Configurated error path while can still scan packets

### ISSUE THREAD

**Issue by xiaoyibuchitang** [apache/dubbo#13624]
base-packages：Configurated error path while can still scan packets
![6D~E2JSFY HD U~UY`W61I](https://github.com/apache/dubbo/assets/92422287/0eaed3b3-9c28-4da8-8a8b-7ebad5d643f2)

![}6AHPY`X_HG%VWY4K6E$N)7](https://github.com/apache/dubbo/assets/92422287/aa93c2aa-4765-44d1-ad24-aa3d609d3ee6)

![XIH}BM5LVDX}7_W{ XMK6FI](https://github.com/apache/dubbo/assets/92422287/8eb762e5-7249-4db4-a03b-d547b179dc9a)

with no base-packages:
![R}3%%XKWY9R}}V2_W$FTG7](https://github.com/apache/dubbo/assets/92422287/36e9b592-fcb5-4b93-9766-9e961d957366)
![J6@T)IG@X@SHAUMT$7`Y6ZV](https://github.com/apache/dubbo/assets/92422287/12ab090e-b4f4-434b-847c-256deaa5fd51)
why ?

**Comment by xiaoyibuchitang** [comment]
> You cannot configure with `dubbo.scan=`. Please try remove it

![I6B%0R_K2_2SB$ZG47DFO(B](https://github.com/apache/dubbo/assets/92422287/cb048261-0e30-4c19-a0c2-0e83f9db2cdf)
![{LQ_}IP8KMWUIX_$%X(IR6J](https://github.com/apache/dubbo/assets/92422287/26395346-adee-4a12-acb6-3dcf886638cd)
provider cannot register the service as well as cannot support

**Comment by xiaoyibuchitang** [comment]
> You cannot configure with `dubbo.scan=`. Please try remove it

provider cannot register the service as well as cannot support

![1](https://github.com/apache/dubbo/assets/92422287/7352871a-c3cd-4e69-b524-569ca2db9e74)

**Comment by xiaoyibuchitang** [comment]
> You cannot configure with `dubbo.scan=`. Please try remove it

the key problem is that why it needs labels which even could be empty like scan: base-packaging:         ,it's empty while it could work.

**Comment by AlbumenJ** [comment]
> > You cannot configure with `dubbo.scan=`. Please try remove it
> 
> the key problem is that why it needs labels which even could be empty like scan: base-packaging: ,it's empty while it could work.

That is the limitation of `SpringBoot`.

For class scanning, if your class can be scan by `SpringBoot`, Dubbo will proxy it.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
