### ISSUE TITLE
provider registration :It need attribute“scan: base-packages: ”label but do not need value.Because it always scan the package and its children-packages where start-up class in, no matter what value you attribute

### ISSUE THREAD

**Issue by xiaoyibuchitang** [apache/dubbo#13629]
[Summary.docx](https://github.com/apache/dubbo/files/13868438/Summary.docx)

So  can a business-level project  attribute "scan: basepackages: " without values?

**Comment by liufeiyu1002** [comment]
Whether the `@DubboService` annotation takes effect depends on whether the `ServiceAnnotationPostProcessor` exists

**`ServiceAnnotationPostProcessor` has 2 functions**

1. Scan all classes under the given path to find classes with `DubboService` related annotation types. Create BeanDefinition and register it in the spring container (ServiceBean instance)
2. Traverse all BeanDefinition objects in the container, process the `DubboService` related annotation on the `@Bean` method, create a BeanDefinition and register it in the spring container (ServiceBean instance)

In the springboot dubbo project, there are two conditions for whether `ServiceAnnotationPostProcessor` is created (either one can be met). If it exists at the same time, multiple `ServiceAnnotationPostProcessor` instances will be created.

1. Using the `@EnableDubbo` annotation will create a `ServiceAnnotationPostProcessor` instance. The corresponding scanpackage path is the `scanBasePackages` attribute. When the attribute `scanBasePackages` is not set, the package path of the startup class is used by default.
2. Configuring `dubbo.scan.base-packages` (regardless of whether it has a value) will create a ServiceAnnotationPostProcessor instance

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
