### ISSUE TITLE
what's the best practice for tag-router in multi zookeeper registry scene?

### ISSUE THREAD

**Issue by zth9** [apache/dubbo#13636]
Dubbo Version 2.7.x

1.Spread tag-router config in all zks.

2.Set the tag-router config in the specified zk, and all dubbo app specify this zk as the config-center.

3.Set tag-router config in the zk that exported dubbo service, dubbo consumer load config from calling service' zk registry.

Or other better way？

**Comment by finefuture** [comment]
I think the second way is better. Dubbo supports the isolation of the registry center and the config center.

**Comment by zth9** [comment]
> I think the second way is better. Dubbo supports the isolation of the registry center and the config center.

Agree. but in my case, the first way is more suitable considering the cost of refactor. Because we don't know how many dubbo app use which one registry as config center. Maybe i will use first one way now, and switch to the second way one by one app after.

How about the third way？I think this is the most suitable way, but currently dubbo has not implemented it this way. What is the reason for this?

**Comment by shaowYe** [comment]
> > I think the second way is better. Dubbo supports the isolation of the registry center and the config center.
> 
> Agree. but in my case, the first way is more suitable considering the cost of refactor. Because we don't know how many dubbo app use which one registry as config center. Maybe i will use first one way now, and switch to the second way one by one app after.
> 
> How about the third way？I think this is the most suitable way, but currently dubbo has not implemented it this way. What is the reason for this?

since dubbo 3.1.0, you can set attachments on registry, may suit your third way
