### ISSUE TITLE
How to configure namespace for nacos registry

### ISSUE THREAD

**Issue by yyang3920347** [apache/dubbo#13632]
1. Start the consumer service. Dubbo consumers can only register to the public namespace of nacos and need to register to the namespace I specify.

2. Producers can register to the specified namespace normally
3. Version
Dubbo 2.7.15
nacos 2.2.0

picture

<img width="1775" alt="image" src="https://github.com/apache/dubbo/assets/45329233/40584528-4c0c-4bf8-b73b-afa19e0d0bd1">

<img width="1810" alt="image" src="https://github.com/apache/dubbo/assets/45329233/235bed3d-c8cb-4c52-87a4-481fea747977">
<img width="872" alt="image" src="https://github.com/apache/dubbo/assets/45329233/60a5d0c6-1353-47a4-9d85-a177e44caf45">

<img width="1760" alt="image" src="https://github.com/apache/dubbo/assets/45329233/ef5b45e3-2895-4546-a203-ca965f4d4cd4">

<img width="1463" alt="image" src="https://github.com/apache/dubbo/assets/45329233/37b4ef3b-046c-40ed-9d2c-19cba9c2968e">

---
1. 启动消费者服务，dubbo消费者只能注册到nacos的public这个namespace，需要注册到我指定的namespace

2. 生产者可以正常注册到指定的namespace
3.版本
dubbo 2.7.15
nacos 2.2.0

图片

<img width="1775" alt="image" src="https://github.com/apache/dubbo/assets/45329233/40584528-4c0c-4bf8-b73b-afa19e0d0bd1">

<img width="1810" alt="image" src="https://github.com/apache/dubbo/assets/45329233/235bed3d-c8cb-4c52-87a4-481fea747977">
<img width="872" alt="image" src="https://github.com/apache/dubbo/assets/45329233/60a5d0c6-1353-47a4-9d85-a177e44caf45">

<img width="1760" alt="image" src="https://github.com/apache/dubbo/assets/45329233/ef5b45e3-2895-4546-a203-ca965f4d4cd4">

<img width="1463" alt="image" src="https://github.com/apache/dubbo/assets/45329233/37b4ef3b-046c-40ed-9d2c-19cba9c2968e">

**Comment by AlbumenJ** [comment]
```
dubbo:
  registry:
    parameters:
      namespace: xxx-xxx-xxx
```

**Comment by AlbumenJ** [comment]
or dubbo.registry.address=nacos://127.0.0.1:8848?namespace=xxx-xxx-xxx

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
