### ISSUE TITLE
Transmit message by gateway

### ISSUE THREAD

**Issue by bringwu** [apache/dubbo#13638]
有这样一个场景，client->gateway->bizSever,  gateway只负责通过dubbo中转二进制参数到bizServer的dubbo接口，dubbo接口执行完后返回二进制响应结果到gateway，gateway再回应给客户端。

bizServer的面向客户端的接口只有一个参数（可能是pb对象，也可能是其他自定义编解码协议）：public XXXRsp cmd1（xxxReq）

在这个流程中，，gateway只有二进制格式的请求参数、interfaceName、methodName，没有接口类型与参数类型，这种场景貌似泛化调用也不支持？看着泛化调用都需要gateway有dubbo接口的class。

dubbo目前能支持这种场景吗？有案例吗

**Comment by zhangyungen** [comment]
你们用的gateway 是哪一套呀？shenyu网关完全支持的，小公司推荐。

**Comment by bringwu** [comment]
> 你们用的gateway 是哪一套呀？shenyu网关完全支持的，小公司推荐。

自己通过netty实现的网关

**Comment by bringwu** [comment]
@zhangyungen 大佬，目前dubbo支持我的需求不？（开源网关暂不适用，不考虑）

**Comment by kimmking** [comment]
感觉你这不是一个网关，而是一个网络代理？

**Comment by bringwu** [comment]
> 感觉你这不是一个网关，而是一个网络代理？

是一个网关，消息透传只是其中一个功能。跟一般的web应用不一样。现在纠结的应该是dubbo支不支持这个能力

**Comment by bringwu** [comment]
> 感觉你这不是一个网关，而是一个网络代理？

这个网关的一个功能是将客户端的请求处理封装后投递给后面的业务服务，同样的也将响应信息、推送信息等加工处理后回应给客户端

**Comment by kimmking** [comment]
那就不是dubbo支持不支持这个网关，而是这个网关支不支持dubbo。思路反了。

**Comment by chickenlj** [comment]
Please check the features and best practices we are working on with the upcoming dubbo 3.3 release.

https://dubbo-next.staged.apache.org/zh-cn/overview/mannual/java-sdk/tasks/gateway/triple/

> Please notice that contents in the above link are all in experimental or developing phase.
