### ISSUE TITLE
gernericService.invoke return unexpected result

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/dubbo#13641]
Dear，

below is my code，

`@DubboReference(interfaceName="com.saic.iov.cloud.sp.support.api.ITbAppversionApi", version = "1.1", generic=true, check = false)
    private GenericService gernericService;

 public void filter(HttpRequest request, HttpResponse response, PluginFilterChain chain) {
         Object object1 = gernericService.$invoke("fingVersionInfoV2",   new String[]{"java.lang.String","java.lang.Integer","java.lang.Integer"}, new Object[]{"1.0.1",1,1});    //调用泛化接口
        log.info(JSON.toJSONString(object1));
        response.setBody(JSON.toJSONString(object1));
    }`

**I use  curl   to  access   it return  the below**

{"class":"com.cloud.sp.support.api.dto.AppVersionDto"}

**it just  return the  return object‘s description . But how to get real value of the interface's call result. Thanks**

**Comment by kimmking** [comment]
can you show the result details in the provider side?
