### ISSUE TITLE
Incompatible with spring 3.2.0 and dubbo 2.7.11

### ISSUE THREAD

**Issue by zhangtingshu** [apache/dubbo#13643]
环境：
jdk：21
springboot版本：3.2.0
dubbo版本：2.7.11

使用xml文件注入bean，启动报错，报错内容：
java.lang.ClassNotFoundException: org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter

**Comment by kimmking** [comment]
I suggest upgrade to 3.2 version.

**Comment by AlbumenJ** [comment]
Please upgrade to 3.2.x.
