### ISSUE TITLE
如何手动从注册中心移除当前节点

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#13668]
我是通过instance注册到nacos注册中心的。dubbo提供了方法ApplicationModel.defaultModel().destroy();来实现优雅停机，我如果仅仅想把当前实例从nacos获取其他注册中心移除有没有单独的方法？

**Comment by liudaac** [comment]
可以参考 https://github.com/liudaac/aradin/blob/main/aradin-spring/aradin-spring-actuator-starter/src/main/java/cn/aradin/spring/actuator/starter/actuate/OfflineEndpoint.java performDeregistry的实现

**Comment by luger1990** [comment]
> 可以参考 https://github.com/liudaac/aradin/blob/main/aradin-spring/aradin-spring-actuator-starter/src/main/java/cn/aradin/spring/actuator/starter/actuate/OfflineEndpoint.java performDeregistry的实现

牛逼 可以了，附上代码
```
ApplicationModel applicationModel = ApplicationModel.defaultModel();
ServiceInstanceMetadataUtils.unregisterMetadataAndInstance(applicationModel);
```
