### ISSUE TITLE
Incorrect response header for rest protocol

### ISSUE THREAD

**Issue by imjyz** [apache/dubbo#13665]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2
* Java version: 1.8

### Steps to reproduce this issue

1.  使用 rest 协议暴露一个dubbo接口，get / post 均可。
2.  使用postman访问接口，得到预期外的 Content-Type：
    * [[application/json, application/json]]
    * [[text/plain, application/json]]

按照 RFC-2616 规范，响应格式应该是 `Content-Type: text/html; charset=ISO-8859-4` 这种格式。

**Comment by imjyz** [comment]
debug发现应该是 `org.apache.dubbo.rpc.protocol.rest.extension.resteasy.ResteasyContext#addResponseHeaders` 引起的错误

```java
for (Map.Entry<String, List<Object>> entry : headers.entrySet()) {
        String key = entry.getKey();
        if (entry.getValue() == null) {
              continue;
        }
        response.addOutputHeaders(key, entry.getValue().toString());
}
```

**Comment by bruce0312** [comment]
same problem too. i have to write new customized spi to fix this problem..

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

**Comment by suncairong163** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 3.2
> * Java version: 1.8
> 
> ### Steps to reproduce this issue
> 1. 使用 rest 协议暴露一个dubbo接口，get / post 均可。
> 2. 使用postman访问接口，得到预期外的 Content-Type：
>    
>    * [[application/json, application/json]]
>    * [[text/plain, application/json]]
> 
> 按照 RFC-2616 规范，响应格式应该是 `Content-Type: text/html; charset=ISO-8859-4` 这种格式。

Can you provide case code?
