### ISSUE TITLE
Not publish after register ServiceConfig as spring bean

### ISSUE THREAD

**Issue by ichenkaihua** [apache/dubbo#13678]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: win10
* Java version: 8/21
* springboot: 2.2.9/3.1.x
* nacos: 2.2.3/2.2.4

### Steps to reproduce this issue

This is a problem when dubbo2 is upgraded to dubbo3.
In dubbo2, as the official documentation says, you can expose `ServiceConfig` as a spring bean, and then the provider will be registered in the registration center.
But in dubbo3, this method is invalid. The nacos configuration center does not generate the mapping file, causing the consumer to report no provider.

```java
@Configuration
public class ProviderConfiguration {
     @Bean
     public ServiceConfig demoService() {
         ServiceConfig service = new ServiceConfig();
         service.setInterface(DemoService.class);
         service.setRef(new DemoServiceImpl());
         service.setGroup("dev");
         service.setVersion("1.0.0");
         Map<String, String> parameters = new HashMap<>();
         service.setParameters(parameters);
         return service;
     }
}
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

You can register to the registration center

### Actual Behavior

unregistered

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: win10
* Java version: 8/21
* springboot: 2.2.9/3.1.x
* nacos: 2.2.3/2.2.4

### Steps to reproduce this issue

这是dubbo2升级到dubbo3的问题。
在dubbo2中，可以像官方文档所说的，暴露`ServiceConfig`作为spring bean，然后就会注册provider到注册中心。
但在dubbo3中，这种方式无效，nacos配置中心没有生成mapping文件，导致消费端报no provider。

```java
@Configuration
public class ProviderConfiguration {
    @Bean
    public ServiceConfig demoService() {
        ServiceConfig service = new ServiceConfig();
        service.setInterface(DemoService.class);
        service.setRef(new DemoServiceImpl());
        service.setGroup("dev");
        service.setVersion("1.0.0");
        Map<String, String> parameters = new HashMap<>();
        service.setParameters(parameters);
        return service;
    }
}
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

可以注册到注册中心

### Actual Behavior

没有注册

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by liufeiyu1002** [comment]
using `ServiceBean` , Register in init method

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
