### ISSUE TITLE
Chore: Update the comment content in pom.xml to be consistent

### ISSUE THREAD

**Issue by yuluo-yx** [apache/dubbo#13686]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
There are currently two license annotations in pom.xml.

such as:
https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-spring-boot/pom.xml#L3

https://github.com/apache/dubbo/blob/2cf54f7947596abbf92f907853a2df7cbfc8b7fb/dubbo-spring-boot/dubbo-spring-boot-starters/pom.xml#L3

They should need to be unified, if it needs to be updated please assign me and I will complete.

**Comment by heliang666s** [comment]
hello,I am interested in it,please assign me.

**Comment by AlbumenJ** [comment]
> hello,I am interested in it,please assign me.

done

**Comment by yuluo-yx** [comment]
fiexd in #14039,  closed.
