### ISSUE TITLE
dubbo 3.2.10 reports an exception `All clients has disconnected from /192.168.0.5:20880. You can graceful shutdown now.`

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#13693]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: xxx
* Java version: 17

### Steps to reproduce this issue

![image](https://github.com/apache/dubbo/assets/31852897/cfcdd21e-97cf-4aca-9d9d-4181e4847c83)
What is the significance of this report? My service has just been started. How can someone connect? And why should I use the warn level? I think warn is the log level that should be used when there is an abnormal situation. If no one connects, it is an abnormal situation. I hope it can be optimized. one time

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

---

- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: xxx
* Java version: 17

### Steps to reproduce this issue

![image](https://github.com/apache/dubbo/assets/31852897/cfcdd21e-97cf-4aca-9d9d-4181e4847c83)
报的这个东西有什么意义么 我服务才刚启动啊 怎么可能会有人连接? 而且为什么要用warn这种级别 我认为warn是异常情况才应该用的日志级别 没有人连接算是异常情况的嘛 希望可以优化一下

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
Can you please submit a PR to enhance it?

**Comment by wlngo** [comment]
I want to enhance it @AlbumenJ

**Comment by wlngo** [comment]
Can you provide a demo? I can't reproduce it.
The warning only appears when I force close all consumers. @JavaLionLi  
![image](https://github.com/apache/dubbo/assets/85060647/9c4c3c6e-1772-4f65-be01-c3c47faa4aed)

**Comment by JavaLionLi** [comment]
> Can you provide a demo? I can't reproduce it. The warning only appears when I force close all consumers. @JavaLionLi ![image](https://private-user-images.githubusercontent.com/85060647/301373941-9c4c3c6e-1772-4f65-be01-c3c47faa4aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTEwODAsIm5iZiI6MTcwNjc5MDc4MCwicGF0aCI6Ii84NTA2MDY0Ny8zMDEzNzM5NDEtOWM0YzNjNmUtMTc3Mi00ZjY1LWJlMDEtYzNjNDdmYWE0YWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTYyOTJjNDM5NTg0OWE5NDNlNWU4NWQ5ZDBhMzE0ODI0OWY5MDhkOGFhODY2MDlkZGIxMzZlNzg4NzIzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nXB1h22ePgVVKSS5S_P-rcTwRp8y46xXdF2LeD1QYU)

很奇怪这个问题复现不了了 先关闭了 有问题在打卡

**Comment by eduosi** [comment]
> > Can you provide a demo? I can't reproduce it. The warning only appears when I force close all consumers. @JavaLionLi ![image](https://private-user-images.githubusercontent.com/85060647/301373941-9c4c3c6e-1772-4f65-be01-c3c47faa4aed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTEwODAsIm5iZiI6MTcwNjc5MDc4MCwicGF0aCI6Ii84NTA2MDY0Ny8zMDEzNzM5NDEtOWM0YzNjNmUtMTc3Mi00ZjY1LWJlMDEtYzNjNDdmYWE0YWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTYyOTJjNDM5NTg0OWE5NDNlNWU4NWQ5ZDBhMzE0ODI0OWY5MDhkOGFhODY2MDlkZGIxMzZlNzg4NzIzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5nXB1h22ePgVVKSS5S_P-rcTwRp8y46xXdF2LeD1QYU)
> 
> 很奇怪这个问题复现不了了 先关闭了 有问题在打卡
部署在 k8s 上，且开启健康检查（TCP模式），就会出现，dubbo 使用的 dubbo 协议。
