### ISSUE TITLE
Dubbo 3.2.10 使用@Autowired注入时报红

### ISSUE THREAD

**Issue by spq666** [apache/dubbo#13699]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
![image](https://github.com/apache/dubbo/assets/32086265/0adb41b3-7850-444e-adf5-0188fa9fcc49)
![image](https://github.com/apache/dubbo/assets/32086265/12544e52-e78e-4134-ad51-97a4b75ff424)
![image](https://github.com/apache/dubbo/assets/32086265/c3dec917-a154-4d16-8f98-3e701bfcd99b)
![image](https://github.com/apache/dubbo/assets/32086265/ed25abba-a705-430e-8b14-635112deee3b)
![image](https://github.com/apache/dubbo/assets/32086265/cd3b1b5b-1d1d-488b-9ee8-9f5edae1f693)

在CTestService中引用ATestService会报红，显示有多个实现类需要指定一个，但另一个实现类指向的是BTestService中的ATestService，在CTestService中使用@Resource或者@DubboReference引用ATestService则没有问题，麻烦问下这个是什么原因

**Comment by spq666** [comment]
![image](https://github.com/apache/dubbo/assets/32086265/01d072b5-6e33-49f0-bc7a-9f834ba25dd7)

**Comment by spq666** [comment]
![image](https://github.com/apache/dubbo/assets/32086265/d398251e-b7ce-40e0-a402-0a432fbbf572)

**Comment by liufeiyu1002** [comment]
在 `ATestServiceImpl` 中 使用了 `@DubboReference `会在容器中生成一个 类型为 `ATestService` 的代理类  所以你用 `Autowired` 注解时会提示 (Autowired是byType的)  @resource 是通过 名称注入的idea 不会提示告警
想验证 你可以通过 `applicationContext` 查看bean 容器中的类

**Comment by spq666** [comment]
> 在 `ATestServiceImpl` 中 使用了 `@DubboReference `会在容器中生成一个 类型为 `ATestService` 的代理类 所以你用 `Autowired` 注解时会提示 (Autowired是byType的) @resource 是通过 名称注入的idea 不会提示告警 想验证 你可以通过 `applicationContext` 查看bean 容器中的类

好的，明白怎么回事了，非常感谢！
