### ISSUE TITLE
bug in FastJson2ObjectInput.readBytes and FastJson2ObjectOutput.writeBytes

### ISSUE THREAD

**Issue by bringwu** [apache/dubbo#13697]
The type of length is int, but only a single byte is being read and written.

![企业微信截图_17065021082675](https://github.com/apache/dubbo/assets/15963748/5b4f8986-a009-4eaf-b065-5061d5e39574)

![企业微信截图_17065021626847](https://github.com/apache/dubbo/assets/15963748/d68a6df4-d478-4b93-968e-3af458eb885e)

**Comment by AlbumenJ** [comment]
It should be changed to `readLength` and `writeLength`.
BTW, `org.apache.dubbo.common.serialize.DataInput#readBytes` has no usage now.

**Comment by tritone-l** [comment]
> It should be changed to `readLength` and `writeLength`. BTW, `org.apache.dubbo.common.serialize.DataInput#readBytes` has no usage now.

org.apache.dubbo.common.serialize.DataInput#writeBytes ，It doesn't seem to have been used either

**Comment by finefuture** [comment]
Fixed in #13968
