### ISSUE TITLE
dubbo 3.2.10 local metadata center not effective

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#13692]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: xxx
* Java version: 17

### Steps to reproduce this issue

![image](https://github.com/apache/dubbo/assets/31852897/7e9896bc-5ca5-4698-93a3-b6728dc7a683)
The metadata center type has been configured as local
Debug also shows that it is local
But an error will still be reported. The remote metadata center is unavailable.
![image](https://github.com/apache/dubbo/assets/31852897/69e4a922-7b32-4f45-8dc4-c9c23be85205)

![image](https://github.com/apache/dubbo/assets/31852897/f3244a31-891f-4d96-a3f9-8571fc9927f5)
According to the documentation, local stores metadata locally. Why does it need to be pushed to the remote metadata center?
![image](https://github.com/apache/dubbo/assets/31852897/ca1ec3d7-88a6-413e-a4f0-0b936571188a)
I also changed the push configuration that may be relevant to false.

When the consumer starts, it does not go to the producer to obtain metadata.
After testing, the producer is not started and the consumer can be started normally. dubbo.metadata-report.check=true has no effect.

After the above series of questions, we concluded that metadataType=local has no effect.

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

---

- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: xxx
* Java version: 17

### Steps to reproduce this issue

![image](https://github.com/apache/dubbo/assets/31852897/7e9896bc-5ca5-4698-93a3-b6728dc7a683)
元数据中心类型已经配置为了local
debug看也是local
但是依旧会报错 远程元数据中心不可用
![image](https://github.com/apache/dubbo/assets/31852897/69e4a922-7b32-4f45-8dc4-c9c23be85205)

![image](https://github.com/apache/dubbo/assets/31852897/f3244a31-891f-4d96-a3f9-8571fc9927f5)
按照文档的说法 local 是把元数据存储到本地 为啥还要往远程元数据中心推送?
![image](https://github.com/apache/dubbo/assets/31852897/ca1ec3d7-88a6-413e-a4f0-0b936571188a)
可能有关的推送配置我也都改成了false

消费者启动的时候也并没有去生产者获取元数据
经测试 不启动生产者 消费者可以正常启动 dubbo.metadata-report.check=true 无作用

经上述一系列问题得出结论 metadataType=local 无作用

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: xxx
* Java version: 17

### Steps to reproduce this issue

![image](https://github.com/apache/dubbo/assets/31852897/7e9896bc-5ca5-4698-93a3-b6728dc7a683)
元数据中心类型已经配置为了local
debug看也是local
但是依旧会报错 远程元数据中心不可用
![image](https://github.com/apache/dubbo/assets/31852897/69e4a922-7b32-4f45-8dc4-c9c23be85205)

![image](https://github.com/apache/dubbo/assets/31852897/f3244a31-891f-4d96-a3f9-8571fc9927f5)
按照文档的说法 local 是把元数据存储到本地 为啥还要往远程元数据中心推送?
![image](https://github.com/apache/dubbo/assets/31852897/ca1ec3d7-88a6-413e-a4f0-0b936571188a)
可能有关的推送配置我也都改成了false

消费者启动的时候也并没有去生产者获取元数据
经测试 不启动生产者 消费者可以正常启动 dubbo.metadata-report.check=true 无作用

经上述一系列问题得出结论 metadataType=local 无作用

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JavaLionLi** [comment]
完整配置如下

```
dubbo:
  application:
    logger: slf4j
    metadataType: local
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
  # 注册中心配置
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
    group: DUBBO_GROUP
    parameters:
      namespace: ${spring.profiles.active}
  metadata-report:
    check: true
    reportMetadata: false
    reportDefinition: false
  # 消费者相关配置
  protocol:
    name: dubbo
    port: -1
  consumer:
    cache: false
    # 支持校验注解
    validation: jvalidationNew
    # 调用重试 不包括第一次 0为不需要重试
    retries: 0
    # 初始化检查
    check: false```

**Comment by AlbumenJ** [comment]
`dubbo.application.metadataType` is only for application level service discovery. Beside this, some definition metadata are also need to report to metadata center which is enabled by default.

**Comment by JavaLionLi** [comment]
> `dubbo.application.metadataType` is only for application level service discovery. Beside this, some definition metadata are also need to report to metadata center which is enabled by default.

我就是应用级服务发现啊 FORCE_APPLICATION 我已经关闭了 reportDefinition 应该是不会推送了才对啊

**Comment by JavaLionLi** [comment]
主要问题是 消费者根本没有来本地取元数据 而是去了远程中心取数据 远程中心里也有一大堆元数据 并没有把元数据存到本地

**Comment by JavaLionLi** [comment]
所以我觉得这块是有问题的 希望官方可以测一测 以前用local不启动生产者是无法启动消费者的 
消费者启动的时候会去调用生产者的接口  现在升级了3.2.X以后 就再也不会请求生产者的接口了

**Comment by AlbumenJ** [comment]
> 主要问题是 消费者根本没有来本地取元数据 而是去了远程中心取数据 远程中心里也有一大堆元数据 并没有把元数据存到本地

1. Please comment in English because we want all the users know what we are talking about.
2. Using of local or remote metadata or not is depend on provider side. If a provider only export in remote mode, consumer should use it.
3. Except these, application level serivce discovery also require metadata center of save and read the mapping of interface name and application name.

**Comment by JavaLionLi** [comment]
> > 主要问题是 消费者根本没有来本地取元数据 而是去了远程中心取数据 远程中心里也有一大堆元数据 并没有把元数据存到本地
> 
> 1. Please comment in English because we want all the users know what we are talking about.
> 2. Using of local or remote metadata or not is depend on provider side. If a provider only export in remote mode, consumer should use it.
> 3. Except these, application level serivce discovery also require metadata center of save and read the mapping of interface name and application name.

I have set local globally

There is no data in the metadata center, and consumers can still start successfully.

According to the description of 3, that is to say, local storage cannot be used in any case, and remote storage is required. Is there a problem with this understanding?

**Comment by AlbumenJ** [comment]
> According to the description of 3, that is to say, local storage cannot be used in any case, and remote storage is required. Is there a problem with this understanding?

You are right
