### ISSUE TITLE
NPE for ServiceKey

### ISSUE THREAD

**Issue by lihuagang03** [apache/dubbo#13714]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: Linux 4.19.91-26.al7.x86_64
* Java version: openjdk-8 1.8.0_333

### Steps to reproduce this issue

Based on the dubbo source code of the complete exception call stack below, it is suspected that the ServiceKey is null and causes NPE. The inference is that the path in the URL is empty.
Why is the path of the URL empty? What is the specific URL? Because of the production environment, it is difficult to debug online through arthas. I haven’t reached the level of Filter interceptor either.
The pre-release environment did not appear or reappear.

error code: 4-20, the company currently uses `dubbo-3.1.1` and `dubbo-3.2.10` internally.

<img width="677" alt="image" src="https://github.com/apache/dubbo/assets/1811851/03f9dd0a-432e-4092-8200-b8de287351a4">

Complete exception call stack
```
message: [DUBBO] Decode rpc invocation failed: null, dubbo version: 3.2.10, current host: xxx.xxx.xxx.xxx, error code: 4-20. This may be caused by , go to https://dubbo .apache.org/faq/4/20 to find instructions.
thread:NettyServerWorker-9-1
logger:org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation
exception:
java.lang.NullPointerException: null
   at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
   at org.apache.dubbo.rpc.support.GroupServiceKeyCache.getServiceKey(GroupServiceKeyCache.java:37)
   at org.apache.dubbo.rpc.support.ProtocolUtils.serviceKey(ProtocolUtils.java:50)
   at org.apache.dubbo.rpc.protocol.AbstractProtocol.serviceKey(AbstractProtocol.java:85)
   at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:308)
   at org.apache.dubbo.rpc.protocol.dubbo.CallbackServiceCodec.decodeInvocationArgument(CallbackServiceCodec.java:386)
   at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decodeArgument(DecodeableRpcInvocation.java:197)
   at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:182)
   at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:105)
   at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:199)
   at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:137)
   at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:92)
   at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:59)
   at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:103)
   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.lang.Thread.run(Thread.java:750)

```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

---

- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.10
* Operating System version: Linux  4.19.91-26.al7.x86_64
* Java version: openjdk-8  1.8.0_333

### Steps to reproduce this issue

结合下面完整的异常调用栈的dubbo源代码走读看，怀疑ServiceKey为null引起NPE，反推是URL中的path为空。
为何URL的path为空，具体URL是什么？因为生产环境，不好通过arthas在线调试。也没走到Filter拦截器这一层
预发环境，没有出现和复现。

error code: 4-20，公司内部目前使用`dubbo-3.1.1`和`dubbo-3.2.10`。

<img width="677" alt="image" src="https://github.com/apache/dubbo/assets/1811851/03f9dd0a-432e-4092-8200-b8de287351a4">

完整的异常调用栈
```
message: [DUBBO] Decode rpc invocation failed: null, dubbo version: 3.2.10, current host: xxx.xxx.xxx.xxx, error code: 4-20. This may be caused by , go to https://dubbo.apache.org/faq/4/20 to find instructions.
thread:NettyServerWorker-9-1
logger:org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation
exception:
java.lang.NullPointerException: null 
  at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) 
  at org.apache.dubbo.rpc.support.GroupServiceKeyCache.getServiceKey(GroupServiceKeyCache.java:37) 
  at org.apache.dubbo.rpc.support.ProtocolUtils.serviceKey(ProtocolUtils.java:50) 
  at org.apache.dubbo.rpc.protocol.AbstractProtocol.serviceKey(AbstractProtocol.java:85) 
  at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:308) 
  at org.apache.dubbo.rpc.protocol.dubbo.CallbackServiceCodec.decodeInvocationArgument(CallbackServiceCodec.java:386) 
  at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decodeArgument(DecodeableRpcInvocation.java:197) 
  at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:182) 
  at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:105) 
  at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:199) 
  at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:137) 
  at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:92) 
  at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:59) 
  at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:103) 
  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) 
  at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) 
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) 
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) 
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) 
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) 
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) 
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) 
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) 
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) 
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) 
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) 
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) 
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
  at java.lang.Thread.run(Thread.java:750)

```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
![image](https://github.com/apache/dubbo/assets/9292748/ed85c016-7a61-4438-802e-c510ff35eab2)
It seems that `path` here is null. And this value is set in `org/apache/dubbo/rpc/protocol/dubbo/DubboInvoker.java:92`.
Can you please provide some other logs from consumer and provider side?

**Comment by lihuagang03** [comment]
Q: It seems that `path` here is null. 
Yes, I agree with you.

Q: Can you please provide some other logs from consumer and provider side?
No, sorry. I don't know which consumer application it is. What exactly does the URL look like?
I'll go find the context log in K8s Docker, for production environment.

**Comment by lihuagang03** [comment]
> Q: It seems that `path` here is null. Yes, I agree with you.
> 
> Q: Can you please provide some other logs from consumer and provider side? No, sorry. I don't know which consumer application it is. What exactly does the URL look like? I'll go find the context log in K8s Docker, for production environment.

I can't find any relevant logs in the context log.

**Comment by AlbumenJ** [comment]
> > Q: It seems that `path` here is null. Yes, I agree with you.
> > Q: Can you please provide some other logs from consumer and provider side? No, sorry. I don't know which consumer application it is. What exactly does the URL look like? I'll go find the context log in K8s Docker, for production environment.
> 
> I can't find any relevant logs in the context log.

Some logs end with `dubbo version`

**Comment by lihuagang03** [comment]
> > > Q: It seems that `path` here is null. Yes, I agree with you.
> > > Q: Can you please provide some other logs from consumer and provider side? No, sorry. I don't know which consumer application it is. What exactly does the URL look like? I'll go find the context log in K8s Docker, for production environment.
> > 
> > 
> > I can't find any relevant logs in the context log.
> 
> Some logs end with `dubbo version`

No, just the above complete exception call stack.

**Comment by AlbumenJ** [comment]
1. Can you please the stuff registered to registry?
2. You may need to java debug with `DubboInvoker` to check if `path` has been set or not.

**Comment by lihuagang03** [comment]
> 1. Can you please the stuff registered to registry?
> 2. You may need to java debug with `DubboInvoker` to check if `path` has been set or not.

1. I don't even know what the URL looks like. 😂
2. This problem occurs in the production environment, If we could debug, we would have known the root cause of the problem long ago.
3. At the framework level, can we capture this exception?  Of course, we also want to do it ourselves, and we can only do it this way. Use Arthas or BTrace tool to enhance the bytecode.
4.

**Comment by AlbumenJ** [comment]
> > 1. Can you please the stuff registered to registry?
> > 2. You may need to java debug with `DubboInvoker` to check if `path` has been set or not.
> 
> 1. I don't even know what the URL looks like. 😂
> 2. This problem occurs in the production environment, If we could debug, we would have known the root cause of the problem long ago.
> 3. At the framework level, can we capture this exception?  Of course, we also want to do it ourselves, and we can only do it this way. Use Arthas or BTrace tool to enhance the bytecode.

1. Please ignore the typo 😭 . What I mean is to provide the stuff in registry.
2. `tt -t org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker doInvoke` and get the `target object` and `args[0]`

**Comment by lihuagang03** [comment]
> > > 1. Can you please the stuff registered to registry?
> > > 2. You may need to java debug with `DubboInvoker` to check if `path` has been set or not.
> > 
> > 
> > 
> > 1. I don't even know what the URL looks like. 😂
> > 2. This problem occurs in the production environment, If we could debug, we would have known the root cause of the problem long ago.
> > 3. At the framework level, can we capture this exception?  Of course, we also want to do it ourselves, and we can only do it this way. Use Arthas or BTrace tool to enhance the bytecode.
> 
> 1. Please ignore the typo 😭 . What I mean is to provide the stuff in registry.
> 2. `tt -t org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker doInvoke` and get the `target object` and `args[0]`

2. Good way, but we can't use arthas because the volume of request calls is high in production environment. We're going to use the SkyWalking plugin to enhance the bytecode and print out those URLs through conditional debugging or try catch exception.

**Comment by lihuagang03** [comment]
Other colleagues discovered the cause of the problem through online debugging in the pre-release environment. @AlbumenJ
1. `context` is set in the filter configured by the consumer. The configuration is wrong, but it takes effect. It seems that the dubbo framework does not check the configuration validity of Filter `@Activate(group = PROVIDER)`?
     * `consumerConfig.setFilter("context,dubboExceptionFilter");`
2. The request call executes `ContextFilter.removeContext()`, which will clean up the request call context. When retrying after a timeout, there is no `path` parameter in the retry call, causing this NPE.

`dubbo-3.2.10.jar!/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter`
```
context=org.apache.dubbo.rpc.filter.ContextFilter
```

<img width="873" alt="image" src="https://github.com/apache/dubbo/assets/1811851/b6d3508d-6632-4f3b-b5f0-aa42f2ed128b">

<img width="1019" alt="image" src="https://github.com/apache/dubbo/assets/1811851/65b69bf1-7608-40a8-bc6e-1da274f6f830">

---

其他同事通过在预发环境在线调试，发现了问题原因。 @AlbumenJ 
1. 在消费者配置的过滤器中设置了`context`，配置错了，但生效了。dubbo框架层面好像没有对 Filter `@Activate(group = PROVIDER)`做配置有效性校验？
    * `consumerConfig.setFilter("context,dubboExceptionFilter");`
2. 请求调用执行了`ContextFilter.removeContext()`，会执行清理请求调用上下文。超时重试时，引起重试调用时没有`path`参数，引起这个NPE。

`dubbo-3.2.10.jar!/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter`
```
context=org.apache.dubbo.rpc.filter.ContextFilter
```

<img width="873" alt="image" src="https://github.com/apache/dubbo/assets/1811851/b6d3508d-6632-4f3b-b5f0-aa42f2ed128b">

<img width="1019" alt="image" src="https://github.com/apache/dubbo/assets/1811851/65b69bf1-7608-40a8-bc6e-1da274f6f830">

**Comment by AlbumenJ** [comment]
> Other colleagues discovered the cause of the problem through online debugging in the pre-release environment. @AlbumenJ
> 
> 1. `context` is set in the filter configured by the consumer. The configuration is wrong, but it takes effect. It seems that the dubbo framework does not check the configuration validity of Filter `@Activate(group = PROVIDER)`?
>    
>    * `consumerConfig.setFilter("context,dubboExceptionFilter");`
> 2. The request call executes `ContextFilter.removeContext()`, which will clean up the request call context. When retrying after a timeout, there is no `path` parameter in the retry call, causing this NPE.
> 
> `dubbo-3.2.10.jar!/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter`
> 
> ```
> context=org.apache.dubbo.rpc.filter.ContextFilter
> ```
> 
> <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/1811851/308072310-b6d3508d-6632-4f3b-b5f0-aa42f2ed128b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjMxMC1iNmQzNTA4ZC02NjMyLTRmM2ItYjVmMC1hYTQyZjJlZDEyOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0NjRlOWJjODlmMDQyYjcwOTFhOGI2NjZiMjk5YWE0MTYxZmY3ZWExY2FkMWYxYjk4OTNjOWMxZTdlMTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6NfA9J5nce_pDwXbJDqEeydStG2v3YKFd2OLfzIF5mQ"> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/1811851/308072536-65b69bf1-7608-40a8-bc6e-1da274f6f830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjUzNi02NWI2OWJmMS03NjA4LTQwYTgtYmM2ZS0xZGEyNzRmNmY4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVkNDMxNjFlZjU3MzZhZjZmNTE4ODhjYWQ5NTY2YzBiMTlhNmViM2NmMDg4OWRlMTI5Mjk5ZDg5YjY3ZDhmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cGnbn6w7y5ktqLhxhKigp1odBDTcXcsjVsdEjoA3ILA">
> 其他同事通过在预发环境在线调试，发现了问题原因。 @AlbumenJ
> 
> 1. 在消费者配置的过滤器中设置了`context`，配置错了，但生效了。dubbo框架层面好像没有对 Filter `@Activate(group = PROVIDER)`做配置有效性校验？
>    
>    * `consumerConfig.setFilter("context,dubboExceptionFilter");`
> 2. 请求调用执行了`ContextFilter.removeContext()`，会执行清理请求调用上下文。超时重试时，引起重试调用时没有`path`参数，引起这个NPE。
> 
> `dubbo-3.2.10.jar!/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter`
> 
> ```
> context=org.apache.dubbo.rpc.filter.ContextFilter
> ```
> 
> <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/1811851/308072310-b6d3508d-6632-4f3b-b5f0-aa42f2ed128b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjMxMC1iNmQzNTA4ZC02NjMyLTRmM2ItYjVmMC1hYTQyZjJlZDEyOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0NjRlOWJjODlmMDQyYjcwOTFhOGI2NjZiMjk5YWE0MTYxZmY3ZWExY2FkMWYxYjk4OTNjOWMxZTdlMTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6NfA9J5nce_pDwXbJDqEeydStG2v3YKFd2OLfzIF5mQ"> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/1811851/308072536-65b69bf1-7608-40a8-bc6e-1da274f6f830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjUzNi02NWI2OWJmMS03NjA4LTQwYTgtYmM2ZS0xZGEyNzRmNmY4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVkNDMxNjFlZjU3MzZhZjZmNTE4ODhjYWQ5NTY2YzBiMTlhNmViM2NmMDg4OWRlMTI5Mjk5ZDg5YjY3ZDhmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cGnbn6w7y5ktqLhxhKigp1odBDTcXcsjVsdEjoA3ILA">

> 1. `context` is set in the filter configured by the consumer. The configuration is wrong, but it takes effect. It seems that the dubbo framework does not check the configuration validity of Filter `@Activate(group = PROVIDER)`?
>     * `consumerConfig.setFilter("context,dubboExceptionFilter");`

Dubbo will load your filter if you specify the filter name to `ReferenceConfig` or `ConsumerConfig`.
`@Activate(group = PROVIDER)` is only for automatically enable, and is not a strict limit.

**Comment by lihuagang03** [comment]
> > Other colleagues discovered the cause of the problem through online debugging in the pre-release environment. @AlbumenJ
> > 
> > 1. `context` is set in the filter configured by the consumer. The configuration is wrong, but it takes effect. It seems that the dubbo framework does not check the configuration validity of Filter `@Activate(group = PROVIDER)`?
> >    
> >    * `consumerConfig.setFilter("context,dubboExceptionFilter");`
> > 2. The request call executes `ContextFilter.removeContext()`, which will clean up the request call context. When retrying after a timeout, there is no `path` parameter in the retry call, causing this NPE.
> > 
> > `dubbo-3.2.10.jar!/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter`
> > ```
> > context=org.apache.dubbo.rpc.filter.ContextFilter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/1811851/308072310-b6d3508d-6632-4f3b-b5f0-aa42f2ed128b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjMxMC1iNmQzNTA4ZC02NjMyLTRmM2ItYjVmMC1hYTQyZjJlZDEyOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0NjRlOWJjODlmMDQyYjcwOTFhOGI2NjZiMjk5YWE0MTYxZmY3ZWExY2FkMWYxYjk4OTNjOWMxZTdlMTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6NfA9J5nce_pDwXbJDqEeydStG2v3YKFd2OLfzIF5mQ"> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/1811851/308072536-65b69bf1-7608-40a8-bc6e-1da274f6f830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjUzNi02NWI2OWJmMS03NjA4LTQwYTgtYmM2ZS0xZGEyNzRmNmY4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVkNDMxNjFlZjU3MzZhZjZmNTE4ODhjYWQ5NTY2YzBiMTlhNmViM2NmMDg4OWRlMTI5Mjk5ZDg5YjY3ZDhmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cGnbn6w7y5ktqLhxhKigp1odBDTcXcsjVsdEjoA3ILA">
> > 其他同事通过在预发环境在线调试，发现了问题原因。 @AlbumenJ
> > 
> > 1. 在消费者配置的过滤器中设置了`context`，配置错了，但生效了。dubbo框架层面好像没有对 Filter `@Activate(group = PROVIDER)`做配置有效性校验？
> >    
> >    * `consumerConfig.setFilter("context,dubboExceptionFilter");`
> > 2. 请求调用执行了`ContextFilter.removeContext()`，会执行清理请求调用上下文。超时重试时，引起重试调用时没有`path`参数，引起这个NPE。
> > 
> > `dubbo-3.2.10.jar!/META-INF/dubbo/internal/org.apache.dubbo.rpc.Filter`
> > ```
> > context=org.apache.dubbo.rpc.filter.ContextFilter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/1811851/308072310-b6d3508d-6632-4f3b-b5f0-aa42f2ed128b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjMxMC1iNmQzNTA4ZC02NjMyLTRmM2ItYjVmMC1hYTQyZjJlZDEyOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0NjRlOWJjODlmMDQyYjcwOTFhOGI2NjZiMjk5YWE0MTYxZmY3ZWExY2FkMWYxYjk4OTNjOWMxZTdlMTliNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6NfA9J5nce_pDwXbJDqEeydStG2v3YKFd2OLfzIF5mQ"> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/1811851/308072536-65b69bf1-7608-40a8-bc6e-1da274f6f830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTI5NzgsIm5iZiI6MTcwOTExMjY3OCwicGF0aCI6Ii8xODExODUxLzMwODA3MjUzNi02NWI2OWJmMS03NjA4LTQwYTgtYmM2ZS0xZGEyNzRmNmY4MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjhUMDkzMTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWVkNDMxNjFlZjU3MzZhZjZmNTE4ODhjYWQ5NTY2YzBiMTlhNmViM2NmMDg4OWRlMTI5Mjk5ZDg5YjY3ZDhmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cGnbn6w7y5ktqLhxhKigp1odBDTcXcsjVsdEjoA3ILA">
> 
> > 1. `context` is set in the filter configured by the consumer. The configuration is wrong, but it takes effect. It seems that the dubbo framework does not check the configuration validity of Filter `@Activate(group = PROVIDER)`?
> >    
> >    * `consumerConfig.setFilter("context,dubboExceptionFilter");`
> 
> Dubbo will load your filter if you specify the filter name to `ReferenceConfig` or `ConsumerConfig`. `@Activate(group = PROVIDER)` is only for automatically enable, and is not a strict limit.

ok, thx!   ღ( ´･ᴗ･` )比心
