### ISSUE TITLE
Concurrent issue of Nacos Registry

### ISSUE THREAD

**Issue by ShenFeng312** [apache/dubbo#13719]
![image](https://github.com/apache/dubbo/assets/49786112/69eb7f26-578e-4281-a1da-f05ae61e1409)
此处的代码是否应该更正为先subscribeEventListener再获取实例呢？ 看起来再并发情况下会导致变更事件丢失

**Comment by AlbumenJ** [comment]
If change it, some unexpected things may happen.
1. Dubbo subscribe
2. Nacos server notify with version A
3. Dubbo get services and nacos server neturn version B
4. Dubbo refresh invokers with version B
5. subscribe thread notify with version A
6. Dubbo refresh invokers with version A

In last, only version A exist.

**Comment by ShenFeng312** [comment]
@AlbumenJ 

I think nacos will notify version B latter too. And we just use last notify version .We may not need to get services.
