### ISSUE TITLE
Service Mesh support question

### ISSUE THREAD

**Issue by maglna1** [apache/dubbo#13712]
Dubbo3 supports service grid and supplements the old system migration solution: How to solve the problem of data synchronization in the registration center?

https://cn.dubbo.apache.org/zh-cn/overview/core-features/service-mesh/

**Comment by AlbumenJ** [comment]
As for now, you may need to register all the provider as the K8S service.
In the future, we may provide a tool to help you do that.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
