### ISSUE TITLE
一种更简洁的编码风格

### ISSUE THREAD

**Issue by Aresxue** [apache/dubbo#13711]
## 背景
在20~21年间我曾多次使用hsf，其推荐把多个提供者/消费者统一维护在一个配置类中，业务中使用原生spring的编程方式即可（消费者Autowired，提供者使用spring的@Service），彻底解耦了spring和hsf，当我转向2.7.x的dubbo时发现其并没有这个机制，所以在公司内部框架中独立实现过相关功能，如今在3.x中我看到了dubbo和hsf的融合，dubbo终于也实现了在配置类中配置提供者和消费者这种编程风格，但我觉得仍然不够简洁，所以在这里想讨论一下是否有可能更加简洁一些。

## Describe the feature
一、消费者在配置类中使用field模式
```java
@RpcConsumerCollector
public class RpcConsumerConfig {

  @RpcConsumer(group = "demo", version = "${dubbo.provider.version:1.0.0}")
  private UserRpcService userRpcService;

}
``` 
此类方式等价于现在dubbo3.x的使用ReferenceBean方法的模式，但field的方式要相对更简洁一些
二、提供者在配置类中使用field模式
```java
@RpcProviderCollector
public class RpcProviderConfig {

  // UserRpcService可省略
  @RpcProvider(group = "demo", version = "1.0.0", interfaceClass = UserRpcService.class)
  private UserRpcService userService;

}
``` 
此类方式等价于现在dubbo3.x的使用DubboService方法的模式，但field的方式要相对更简洁一些，避免了new UserRpcServiceImpl此类代码，值得注意的是对于提供者而言可能会存在同个接口有多个实现（对于rpc服务的不同版本）的情况，此类可以直接将field的类型设为UserRpcServiceImpl，指定interfaceClass为UserRpcService.class（实现类只实现一个接口时可省略interfaceClass）
三、收集器
```java
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Inherited
@Documented
@Component
public @interface RpcProviderCollector {

  String version() default "";

  String group() default "";

}

@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Inherited
@Component
public @interface RpcConsumerCollector {

  String version() default "";

  String group() default "";

}
``` 
上面提到把消费者和提供者集中管理起来，但有时候又不想把所有的提供者/消费者都放在一起，这时候就可以使用收集器，比如把A应用的消费者放到ARpcConsumerConfig，B应用的消费者放到BRpcConsumerConfig，然后使用可以直接在类上加上@RpcConsumerCollector指定group和version，其内的field默认会继承@RpcConsumerCollector的group和version，在理想情况下达到一个非常简洁的程序
```java
@RpcConsumerCollector(group = "demo", version = "${dubb.consumer.version:1.0.0}")
public class RpcConsumerConfig {
  
  private UserRpcService userRpcService;
  
  private UserRpcService1 userRpcService1;
  
  private UserRpcService2 userRpcService2;

}
```

**Comment by AlbumenJ** [comment]
@Aresxue Can you please translate this proposal into English :)

**Comment by AlbumenJ** [comment]
This suggestion is very useful and I think we can continue discussing how to design it in more detail and how to implement it more elegantly.

BTW, a fluent API like gRPC is also a good choice for Dubbo.

**Comment by Aresxue** [comment]
> @Aresxue Can you please translate this proposal into English :)

Of course, certainly.I will submit a new proposal in English.

**Comment by Aresxue** [comment]
a new proposal #13718

**Comment by Aresxue** [comment]
a new proposal #13718
