### ISSUE TITLE
Memory leak when running integration case dubbo-samples-memory-tri-server

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#13723]
### Environment

* Dubbo version: 3.2.6
* Operating System version: windows11
* Java version: jdk 1.8

### Steps to reproduce this issue
Executing integration tests on dubbo-samples-memory-tri-server failed. Through dumping, it was found that some resources have issues with incomplete destroy.
<img width="552" alt="1" src="https://github.com/apache/dubbo/assets/716461/2492ea90-d3a9-49c0-a634-e9bed6d5590f">
<img width="543" alt="2" src="https://github.com/apache/dubbo/assets/716461/321bef6f-f151-4ee1-b400-e23492e6de6a">

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by FoghostCn** [comment]
Dubbo version 3.3.0-beta.2-SNAPSHOT also have this problem

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-integration-cases/pull/13
