### ISSUE TITLE
In nacos registration, dubbo interface level service registration and discovery, whether there is redundant metadata information in the configuration center

### ISSUE THREAD

**Issue by wallfacers** [apache/dubbo#13725]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

Check whether the meta information records in the configuration center are redundant when the service registration is already discovered at the interface granularity

Interface service list：
![image](https://github.com/apache/dubbo/assets/26599681/404d30a5-12df-4f91-bc13-cc861ae475f1)

Meta information configuration:
![image](https://github.com/apache/dubbo/assets/26599681/1a8d4eec-0329-4ac7-a60a-aa32f2e727f9)

properties:
![image](https://github.com/apache/dubbo/assets/26599681/48e5e967-b667-46a0-853b-782904a7cf9e)

### Environment

* Dubbo version: 3.2.0-beta.4
* Naocs version: 2.3.0
* Operating System version: mac
* Java version: 1.8

**Comment by AlbumenJ** [comment]
The content in configuration center is the metadata of dubbo, which is useful for service govermance and not for service discovery.

**Comment by AlbumenJ** [comment]
They have the same name but different content

**Comment by wallfacers** [comment]
I don't need service governance, can I turn off the write of this configuration @AlbumenJ A

**Comment by AlbumenJ** [comment]
```
dubbo.registry.useAsConfigCenter = false
dubbo.registry.useAsMetadataCenter = false
```

**Comment by wallfacers** [comment]
@AlbumenJ  thanks
