### ISSUE TITLE
use injvm protocol   request loss value

### ISSUE THREAD

**Issue by huaPeti** [apache/dubbo#13720]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

Dubbo 3.2.4:  When using the injvm protocol, when the Default ParamDeepCopyUtil executes the copy method, the Protobuf type input serialization fails, resulting in parameter loss. Is there a corresponding solution?

**Comment by namelessssssssssss** [comment]
It have been fixed in https://github.com/apache/dubbo/pull/13597

**Comment by huaPeti** [comment]
thanks ,I find it.

Will this issue be resolved in version 3.2.11? Approximately when will 3.2.11 be released?

**Comment by AlbumenJ** [comment]
> thanks ,I find it.
> 
> Will this issue be resolved in version 3.2.11? Approximately when will 3.2.11 be released?

Already released
