### ISSUE TITLE
Same zone prefer configuration

### ISSUE THREAD

**Issue by Floweryu** [apache/dubbo#13734]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
I want to give priority to configuring the same region in the project, but the dubbo-admin platform has not yet been built. Is there any other place to configure it?

---

- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
我想项目中配置同区域优先，但dubbo-admin平台目前还未搭建，有别的地方进行配置吗？

**Comment by AlbumenJ** [comment]
You can configure with the raw rules base on tag router.
