### ISSUE TITLE
求Dubbo协议 + Protobuf序列化的使用文档或者demo!!!

### ISSUE THREAD

**Issue by duyang416** [apache/dubbo#13736]
环境：
```
dubbo 3.2.10
jdk 1.8
spring-cloud-alibaba 2021.0.5.0
nacos 2.2.3
```

项目需要使用Dubbo协议 + Protobuf序列化的方式，目前按照官方文档，再配置文件中加入了：
``` yaml
dubbo:
  protocol:
    name: dubbo
    port: -1
    serialization: protobuf
```
但是在启动时会有如下报错：
```java
java.lang.IllegalStateException: No such extension protobuf for serialization/org.apache.dubbo.common.serialize.Serialization
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:712)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:689)
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateProtocolConfig(ConfigValidationUtils.java:603)
	at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:38)
	at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:620)
	at org.apache.dubbo.config.context.ConfigManager.checkConfigs(ConfigManager.java:302)
	at org.apache.dubbo.config.context.ConfigManager.loadConfigs(ConfigManager.java:282)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.loadApplicationConfigs(DefaultApplicationDeployer.java:255)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:222)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:635)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:85)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.init(DubboConfigApplicationListener.java:68)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59)
	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:38)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:892)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at org.XXXApplication.main(JeecgOmsCloudApplication.java:26)
```

刚开始接触dubbo，希望能解答一下!

**Comment by namelessssssssssss** [comment]
Maybe you can try this extension&nbsp;


https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions%2Fdubbo-serialization-protobuf



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月5日(周一) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [apache/dubbo] 求Dubbo协议 + Protobuf序列化的使用文档或者demo!!! (Issue #13736)




 
环境：
 dubbo 3.2.10 jdk 1.8 spring-cloud-alibaba 2021.0.5.0 nacos 2.2.3  
项目需要使用Dubbo协议 + Protobuf序列化的方式，目前按照官方文档，再配置文件中加入了：
 dubbo:   protocol:     name: dubbo     port: -1     serialization: protobuf
 
但是在启动时会有如下报错：
 java.lang.IllegalStateException: No such extension protobuf for serialization/org.apache.dubbo.common.serialize.Serialization 	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:712) 	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:689) 	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateProtocolConfig(ConfigValidationUtils.java:603) 	at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:38) 	at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:620) 	at org.apache.dubbo.config.context.ConfigManager.checkConfigs(ConfigManager.java:302) 	at org.apache.dubbo.config.context.ConfigManager.loadConfigs(ConfigManager.java:282) 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.loadApplicationConfigs(DefaultApplicationDeployer.java:255) 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:222) 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:635) 	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:85) 	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.init(DubboConfigApplicationListener.java:68) 	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59) 	at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:38) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133) 	at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:892) 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) 	at org.XXXApplication.main(JeecgOmsCloudApplication.java:26)
 
刚开始接触dubbo，希望能解答一下!

**Comment by duyang416** [comment]
> Maybe you can try this extension&nbsp; https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions%2Fdubbo-serialization-protobuf
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年2月5日(周一) 下午3:50 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [apache/dubbo] 求Dubbo协议 + Protobuf序列化的使用文档或者demo!!! (Issue #13736) 环境： dubbo 3.2.10 jdk 1.8 spring-cloud-alibaba 2021.0.5.0 nacos 2.2.3 项目需要使用Dubbo协议 + Protobuf序列化的方式，目前按照官方文档，再配置文件中加入了： dubbo: protocol: name: dubbo port: -1 serialization: protobuf 但是在启动时会有如下报错： java.lang.IllegalStateException: No such extension protobuf for serialization/org.apache.dubbo.common.serialize.Serialization at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:712) at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:689) at org.apache.dubbo.config.utils.ConfigValidationUtils.validateProtocolConfig(ConfigValidationUtils.java:603) at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:38) at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:620) at org.apache.dubbo.config.context.ConfigManager.checkConfigs(ConfigManager.java:302) at org.apache.dubbo.config.context.ConfigManager.loadConfigs(ConfigManager.java:282) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.loadApplicationConfigs(DefaultApplicationDeployer.java:255) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:222) at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:635) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:85) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.init(DubboConfigApplicationListener.java:68) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:38) at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133) at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:892) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) at org.XXXApplication.main(JeecgOmsCloudApplication.java:26) 刚开始接触dubbo，希望能解答一下! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

想要采用Protobuf序列化，是不是必须写 .proto 文件然后编译？

**Comment by AlbumenJ** [comment]
> > Maybe you can try this extension  https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions%2Fdubbo-serialization-protobuf
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年2月5日(周一) 下午3:50 收件人: _**@**_.**_>; 抄送: _**@**_._**>; 主题: [apache/dubbo] 求Dubbo协议 + Protobuf序列化的使用文档或者demo!!! (Issue #13736) 环境： dubbo 3.2.10 jdk 1.8 spring-cloud-alibaba 2021.0.5.0 nacos 2.2.3 项目需要使用Dubbo协议 + Protobuf序列化的方式，目前按照官方文档，再配置文件中加入了： dubbo: protocol: name: dubbo port: -1 serialization: protobuf 但是在启动时会有如下报错： java.lang.IllegalStateException: No such extension protobuf for serialization/org.apache.dubbo.common.serialize.Serialization at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:712) at org.apache.dubbo.config.utils.ConfigValidationUtils.checkMultiExtension(ConfigValidationUtils.java:689) at org.apache.dubbo.config.utils.ConfigValidationUtils.validateProtocolConfig(ConfigValidationUtils.java:603) at org.apache.dubbo.config.utils.DefaultConfigValidator.validate(DefaultConfigValidator.java:38) at org.apache.dubbo.config.context.AbstractConfigManager.checkDefaultAndValidateConfigs(AbstractConfigManager.java:620) at org.apache.dubbo.config.context.ConfigManager.checkConfigs(ConfigManager.java:302) at org.apache.dubbo.config.context.ConfigManager.loadConfigs(ConfigManager.java:282) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.loadApplicationConfigs(DefaultApplicationDeployer.java:255) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:222) at org.apache.dubbo.config.deploy.DefaultModuleDeployer.prepare(DefaultModuleDeployer.java:635) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.initDubboConfigBeans(DubboConfigApplicationListener.java:85) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.init(DubboConfigApplicationListener.java:68) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:59) at org.apache.dubbo.config.spring.context.DubboConfigApplicationListener.onApplicationEvent(DubboConfigApplicationListener.java:38) at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133) at org.springframework.context.support.AbstractApplicationContext.registerListeners(AbstractApplicationContext.java:892) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) at org.XXXApplication.main(JeecgOmsCloudApplication.java:26) 刚开始接触dubbo，希望能解答一下! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 想要采用Protobuf序列化，是不是必须写 .proto 文件然后编译？

Yes
