### ISSUE TITLE
ConsistentHashLoadBalance issue

### ISSUE THREAD

**Issue by goto456** [apache/dubbo#13750]
- [√ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.x
* Java version: 1.8

### dubbo 3.2.x 版本的修改记录中删除了以请求参数作为hash key的代码，导致仅仅只使用method name 作为hash key

相关代码在ConsistentHashLoadBalance类中的select方法中，如下图所示：
![](https://raw.githubusercontent.com/goto456/markdown-pictures/master/wengeblog/dubbo-hash-bug.jpeg)

不知道是不是当时修改的同学手误改错了？

**Comment by goto456** [comment]
上图中的修改是在2023年6月的 https://github.com/apache/dubbo/pull/12519 里面修改的。

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/13753
