### ISSUE TITLE
Can not deserialize map correctly.

### ISSUE THREAD

**Issue by piaolinzhi** [apache/dubbo#13757]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.11 & 3.3.0-beta.1
* Operating System version: win11 
* Java version: Azul Zulu version 1.8.0_362

### Steps to reproduce this issue

just use dubbo sample simply

1. provider  

configs 

```
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: tri
    port: 50052
  registry:
      address: nacos://nacos:nacos@192.168.0.xx:8848
```

``` java
    @Override
    public Map<Integer, List<Integer>> testSerialization(List<Integer> params) {
        Map<Integer, List<Integer>> result =new HashMap<>();
        result.put(1, Arrays.asList(-1));
        result.put(2, Arrays.asList(-1));
        return result;
    }
```
3. consumer  
```
    @Override
    public void run(String... args) throws Exception {
        String result = demoService.sayHello("world");
        System.out.println("Receive result ======> " + result);

        new Thread(()-> {
            while (true) {
                try {
                    Thread.sleep(1000);
                    System.out.println(new Date() + " Receive result ======> " + demoService.testSerialization(Arrays.asList(1)));
                } catch (InterruptedException e) {
                    e.printStackTrace();
                    Thread.currentThread().interrupt();
                }
            }
        }).start();
    }
````

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

got  like    {1=[-1], 2=[-1]}

### Actual Behavior

```
Sun Feb 18 16:31:28 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:29 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:30 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:31 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:32 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:33 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:34 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:35 CST 2024 Receive result ======> {1=[-1], 2=[null]}
Sun Feb 18 16:31:36 CST 2024 Receive result ======> {1=[-1], 2=[null]}
```

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by icodening** [comment]
can you provide a demo? I failed to reproduce.
<img width="1698" alt="image" src="https://github.com/apache/dubbo/assets/42876375/18c44d98-ab4b-48e9-b759-80a29b9bd6b9">

**Comment by piaolinzhi** [comment]
https://github.com/piaolinzhi/dubbo-issue-demo @icodening

**Comment by kazetyan** [comment]
序列化的问题,你的代码上都备注了
![image](https://github.com/apache/dubbo/assets/50894526/7c1136b3-5ec1-46a2-bff9-67e90c5469a2)

## 默认序列化
![image](https://github.com/apache/dubbo/assets/50894526/79fc2b71-5022-4356-9460-266390561068)
![image](https://github.com/apache/dubbo/assets/50894526/30c4575f-110a-409f-949e-45c6b0e96970)
## gson
![image](https://github.com/apache/dubbo/assets/50894526/a3c64c25-e41d-4716-9a15-3812cafe9629)
![image](https://github.com/apache/dubbo/assets/50894526/a098c07a-5ce4-437f-a4bc-0893a27a42d8)

**Comment by piaolinzhi** [comment]
> 序列化的问题,你的代码上都备注了 ![image](https://private-user-images.githubusercontent.com/50894526/307720086-7c1136b3-5ec1-46a2-bff9-67e90c5469a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODQyOTEsIm5iZiI6MTcwOTA4Mzk5MSwicGF0aCI6Ii81MDg5NDUyNi8zMDc3MjAwODYtN2MxMTM2YjMtNWVjMS00NmEyLWJmZjktNjdlOTBjNTQ2OWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzU5YWZlNzJiZjEyY2Q4MGNiYTU3ZmFkOTVjMTVhNWVlMGYzMWZmZWUxODYxZDEzZTRmYmY1MGY1NzdlYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eBdmwonYltHXu4pQYCAUDb0MKYLfL8IZaVzyu2Fw3-0)
> 
> ## 默认序列化
> ![image](https://private-user-images.githubusercontent.com/50894526/307719435-79fc2b71-5022-4356-9460-266390561068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODQyOTEsIm5iZiI6MTcwOTA4Mzk5MSwicGF0aCI6Ii81MDg5NDUyNi8zMDc3MTk0MzUtNzlmYzJiNzEtNTAyMi00MzU2LTk0NjAtMjY2MzkwNTYxMDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZTQ5NDJmMTgxNDYzNWY3ZGUyZWZkMTkxNWFjNjliZDk5ZTYyYjIyZWY5YzJkNTE4OGM4YmFhNjNmNmIyNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qzvcoL90X6DBZCatnYiqZQAHSesMu5e98zOJ6SLXa-g) ![image](https://private-user-images.githubusercontent.com/50894526/307719515-30c4575f-110a-409f-949e-45c6b0e96970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODQyOTEsIm5iZiI6MTcwOTA4Mzk5MSwicGF0aCI6Ii81MDg5NDUyNi8zMDc3MTk1MTUtMzBjNDU3NWYtMTEwYS00MDlmLTk0OWUtNDVjNmIwZTk2OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZWU1YmM3MGUyMThhNzBjZDhmYTkzNTRkNjJjYWZkMWVlNzg2NWY2NzRhMjljZDdiNWFhNTJiM2UyYTc5MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GoHLUKaaKPvIm182yqg3ooHAqYlPkwnnTK1UScVGA9U)
> 
> ## gson
> ![image](https://private-user-images.githubusercontent.com/50894526/307719696-a3c64c25-e41d-4716-9a15-3812cafe9629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODQyOTEsIm5iZiI6MTcwOTA4Mzk5MSwicGF0aCI6Ii81MDg5NDUyNi8zMDc3MTk2OTYtYTNjNjRjMjUtZTQxZC00NzE2LTlhMTUtMzgxMmNhZmU5NjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMDZmZjNmYzVlMWZlYjFjOTBiYzdlNTU2NGNkMTE1OWQwOWNhZDQzNGYxOThmOTdlZWNkYzIyMWQwN2ViY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7QkpeZ1xf6nRLN4mboAPJTfDpD5YmOygS69eFmTJGBk) ![image](https://private-user-images.githubusercontent.com/50894526/307718258-a098c07a-5ce4-437f-a4bc-0893a27a42d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODQyOTEsIm5iZiI6MTcwOTA4Mzk5MSwicGF0aCI6Ii81MDg5NDUyNi8zMDc3MTgyNTgtYTA5OGMwN2EtNWNlNC00MzdmLWE0YmMtMDg5M2EyN2E0MmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDAxMzMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjk0MzViOTdjZTA4ZjU5MzNlN2FmYWU1NGRhOGY4YzBkYWVhZmYxN2FkNzJjNTFjZjVlNzViMjJkNzY0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a4Otpa00ZMLJmD2T5mFNmUhVmeDjAqAG6I7BGpU91cA)

我觉得是个问题所以提出来了，fastjson2 是默认的，问题很隐蔽。

**Comment by ShenFeng312** [comment]
确实有问题 先给issue 加上bug 标签吧

**Comment by ShenFeng312** [comment]
看起来是fastjson2的使用有问题

**Comment by ShenFeng312** [comment]
BUG 触发自  fastjson的JSONWriter.Feature.ReferenceDetection

**Comment by ShenFeng312** [comment]
失败情况
```java
    public static void main(String[] args) {
        Map<Integer, List<Integer>> result =new HashMap<>();
        result.put(1, Arrays.asList(-1));
        result.put(2, Arrays.asList(-1));

        byte[] bytes = JSONB.toBytes(result, JSONWriter.Feature.WriteClassName, JSONWriter.Feature.FieldBased, JSONWriter.Feature.ErrorOnNoneSerializable, JSONWriter.Feature.ReferenceDetection, JSONWriter.Feature.WriteNulls, JSONWriter.Feature.NotWriteDefaultValue, JSONWriter.Feature.NotWriteHashMapArrayListClassName, JSONWriter.Feature.WriteNameAsSymbol);
        ParameterizedTypeImpl parameterizedType = new ParameterizedTypeImpl(Map.class, Integer.class, new ParameterizedTypeImpl(List.class, Integer.class));
        Object o = JSONB.parseObject(bytes, parameterizedType);
        System.out.println(JSONObject.toJSONString(o));

    }
```
成功情况
```java
 public static void main(String[] args) {
        Map<Integer, List<Integer>> result =new HashMap<>();
        result.put(1, Arrays.asList(-1));
        result.put(2, Arrays.asList(-1));

        byte[] bytes = JSONB.toBytes(result, JSONWriter.Feature.WriteClassName, JSONWriter.Feature.FieldBased, JSONWriter.Feature.ErrorOnNoneSerializable, JSONWriter.Feature.WriteNulls, JSONWriter.Feature.NotWriteDefaultValue, JSONWriter.Feature.NotWriteHashMapArrayListClassName, JSONWriter.Feature.WriteNameAsSymbol);
        ParameterizedTypeImpl parameterizedType = new ParameterizedTypeImpl(Map.class, Integer.class, new ParameterizedTypeImpl(List.class, Integer.class));
        Object o = JSONB.parseObject(bytes, parameterizedType);
        System.out.println(JSONObject.toJSONString(o));

    }
```

**Comment by ShenFeng312** [comment]
@AlbumenJ  PTAL

**Comment by ShenFeng312** [comment]
会在 https://github.com/alibaba/fastjson2/pull/2280 中修复
