### ISSUE TITLE
Default allow serialize list question

### ISSUE THREAD

**Issue by stupidboytt** [apache/dubbo#13752]
What is the default whitelist of dubbo 3.2's class inspection mechanism? If I put a list<Map<String,Object>> in the object, it can be deserialized, but if I put an object-shaped array like List<T>, it will prompt is not in allow list

---

dubbo 3.2的类检查机制默认的白名单是哪些，我在对象中放一个list<Map<String,Object>>是可以反序列化的，但是用放List<T> 这种对象形数组就提示is not in allow list，请大神简答

**Comment by AlbumenJ** [comment]
You can get the default allow list in https://github.com/apache/dubbo/blob/3.2/dubbo-common/src/main/resources/security/serialize.allowlist

**Comment by stupidboytt** [comment]
I have two classes, PageVo and DetailVo, but PageVo passes parameters to dubbo and then places the query results in pageVo. setDetailVo(deatilVo), which can be serialized and returned. However, when using detailVo directly, it prompts that serialization is not possible

**Comment by AlbumenJ** [comment]
Dubbo only allow serialize the class declared on method signature. Sub-class is not allowed by default. You need to specify the class you want to serialize in serialize allow list.

**Comment by AlbumenJ** [comment]
No news is good news. Please feel free to create a new issue if you have any question.
