### ISSUE TITLE
Error port in service discovery

### ISSUE THREAD

**Issue by lironghai** [apache/dubbo#13779]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

![image](https://github.com/apache/dubbo/assets/34302941/fe320e14-2e85-49a5-b120-c426c14f8887)

Nacos2.0.3 is used as the registration center. In nacos, the configuration reported by the service provider is 20880, but the port is indeed inconsistent when the consumer makes the call, but the information seen later is that the interface has been pulled from nacos. metadata information

使用的nacos2.0.3作为注册中心，在nacos中服务提供方上报的配置是20880，但是在消费方进行调用时端口确不一致了，但从后面看到的信息是已经从nacos中拉取到了接口的元数据信息

**Comment by AlbumenJ** [comment]
Please try upgrade to 3.2.11

**Comment by lironghai** [comment]
> Please try upgrade to 3.2.11

thank you
