### ISSUE TITLE
Usage question of QoS invoke

### ISSUE THREAD

**Issue by gMan1990** [apache/dubbo#13772]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

`接口+分组+版本号才能唯一确定一个服务`
那QoS里invoke，的语法是什么？

`invoke 类.方法()` (里面没 分组和版本)

**Comment by AlbumenJ** [comment]
If you only pulish one service for one interface, just use `invoke className.methodName()`

If there are more than one service for one interface, use `cd serviceKey` first.

**Comment by gMan1990** [comment]
@AlbumenJ `dubbo version "3.0.5"`
假设现在`ls`出来 `group-a/org.Service:1.0.0` `group-a/org.Service:2.0.0` `group-b/org.Service:1.0.0`

```text
dubbo>cd aaaa/bbb:1.0.0
No such service
```

**Comment by AlbumenJ** [comment]
> @AlbumenJ `dubbo version "3.0.5"` 假设现在`ls`出来 `group-a/org.Service:1.0.0` `group-a/org.Service:2.0.0` `group-b/org.Service:1.0.0`
> 
> ```
> dubbo>cd aaaa/bbb:1.0.0
> No such service
> ```

`cd group-a/org.Service:1.0.0`

**Comment by gMan1990** [comment]
@AlbumenJ 提示`No such service `

**Comment by AlbumenJ** [comment]
确认了下这里确实不支持按照版本号隔离
dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/impl/ChangeTelnet.java:59
你有兴趣完善下这一块吗

**Comment by kazetyan** [comment]
@AlbumenJ 我可以,看了下其他地方的用法,增加一个`exporter.getInvoker().getUrl().getServiceKey()` 应该就可以了

`org/apache/dubbo/qos/command/impl/CountTelnet.java:86` 也得同步修改一下

**Comment by AlbumenJ** [comment]
> @AlbumenJ 我可以,看了下其他地方的用法,增加一个`exporter.getInvoker().getUrl().getServiceKey()` 应该就可以了
> 
> `org/apache/dubbo/qos/command/impl/CountTelnet.java:86` 也得同步修改一下

Yes, pls go ahead
