### ISSUE TITLE
CodeStyleNotSupportException，only support [jax-rs, spring-webmvc] annotation

### ISSUE THREAD

**Issue by yx-Yaoxaing** [apache/dubbo#13801]
@Service
@Slf4j
public class ProcedureGuideServiceImpl implements ProcedureGuideService {

}

@DubboService
public class RpcProcedureGuideService extends ProcedureGuideServiceImpl {
}

org.apache.dubbo.rpc.protocol.rest.exception.CodeStyleNotSupportException: service is: interface com.cqnews.xindian.api.service.gov.ProcedureGuideService, only support [jax-rs, spring-webmvc] annotation

 <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>3.2.11</version>
</dependency>

**Comment by yx-Yaoxaing** [comment]
是不应该这样使用继承的方式去使用@DubboService

**Comment by yx-Yaoxaing** [comment]
消费端的代码：
 
@DubboReference(check = false)
  public ProcedureGuideService procedureGuideService;
  
  然后消费端就报错：only support [jax-rs, spring-webmvc] annotation 
  但是不影响调用 能正常调用。

**Comment by AlbumenJ** [comment]
@suncairong163 PTAL

**Comment by suncairong163** [comment]
> @suncairong163 PTAL

This case has been supported in the PR of  #12700 ,But i can not find relative code aboute  #12700 PR,Need merge or PR again?

**Comment by suncairong163** [comment]
> 消费端的代码：
> 
> @DubboReference(check = false) public ProcedureGuideService procedureGuideService;
> 
> 然后消费端就报错：only support [jax-rs, spring-webmvc] annotation 但是不影响调用 能正常调用。

Dubbo code style is not support at 3.2

**Comment by wangqing-github** [comment]
最后解决了吗，是不是版本的问题
