### ISSUE TITLE
No available executors, this is not expected, framework should call createExecutorIfAbsent first  before coming to here.

### ISSUE THREAD

**Issue by jxguosuspectx** [apache/dubbo#13829]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Dubbo Version

2.7.23

### Steps to reproduce this issue

Environment:
Dubbo version 2.7.23
JDK 11
servce provider side

Question:
when I start my spring dubbo service,  below logs occur:

[WARN] [o.a.d.c.threadpool.manager.DefaultExecutorRepository] [] [] []  [DUBBO] No available executors, this is not expected, framework should call createExecutorIfAbsent first before coming to here., dubbo version: 2.7.23, current host: xxx

After a few seconds,  this log no longer occurs.

I am eager to known whether here problems happened, or whether my dubbo service configuration has errors.

Thanks.

### What you expected to happen

no this warn log when start dubbo service.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Have you tried test on 3.2.x?

**Comment by jxguosuspectx** [comment]
> Have you tried test on 3.2.x?

Do I have to update dubbo version to 3.2.x ? Due to environmental restrictions, the upgrade cannot be completed in a short time. I want to know if this is a known problem in the 2.7.x version. Can this problem be solved or circumvented in the  2.7.x version?

**Comment by AlbumenJ** [comment]
> > Have you tried test on 3.2.x?
> 
> Do I have to update dubbo version to 3.2.x ? Due to environmental restrictions, the upgrade cannot be completed in a short time. I want to know if this is a known problem in the 2.7.x version. Can this problem be solved or circumvented in the 2.7.x version?

> I want to know if this is a known problem in the 2.7.x version.

Yes

> Can this problem be solved or circumvented in the 2.7.x version?

No, 2.7.x is EOL now
