### ISSUE TITLE
[Bug] 泛化调用后，范型信息丢失，导致消费者端无法重建对象

### ISSUE THREAD

**Issue by lwj-java** [apache/dubbo#13837]
### Pre-check

- [ ] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Dubbo Version

2.7.6

### Steps to reproduce this issue

例如服务B以泛化的形式提供一个接口，接口返回值为：PoJoA<PoJoB>
当A服务 调用 服务B时，得到的返回值会变成 PoJoA<HashMap>这样的结构

### What you expected to happen

期望返回结果为PoJoA<PoJoB>

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EarthChen** [comment]
2.x is eol,pls use latest version.

**Comment by AlbumenJ** [comment]
Pls translate this issue in English

**Comment by AlbumenJ** [comment]
English only on GitHub.
Please recreate a issue in English if you still have questions.
