### ISSUE TITLE
[Task] Introduce bytebuddy proxy in apache/dubbo-spi-extensions

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#13867]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SPI Extensions (apache/dubbo-spi-extensions)

### Descriptions

Dubbo's default proxy is javassist. It has been tested by the practice of mass production.
Bytebuddy proxy can be chosen from dubbo-spi-exntensions. It still needs to be tested over time.
ref #13555

Task: Move bytebuddy implementation in apache/dubbo to apache/dubbo-spi-extensions

### Related issues

https://github.com/apache/dubbo/discussions/13831

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by finefuture** [comment]
I'm interested. Please assign it to me.

**Comment by AlbumenJ** [comment]
> I'm interested. Please assign it to me.

done
