### ISSUE TITLE
about "The parameters of execution method of dubbo service are organized by 'Object[]'.will bring 2 problems"

### ISSUE THREAD

**Issue by scanry** [apache/dubbo#1390]
目前dubbo的requst的方法参数通过Object[]组织的，然后被序列化传输到服务端，服务端再反序列化，这样会涉及到几个问题:
1.基本类型会自动装箱拆箱带来性能影响。
1.基本类型和引用类型参数都被序列化框架一起处理带来性能影响。
代码简写例子:
rpc服务方法

```java
public String say(String name) {
	return "hi:" + name;
}
```

rpc服务方法参数封装

```java
class TestServiceSayParam$Generate{
		private String name;
		public String getParam1() {
			return name;
		}
		public byte[] serialize() {
			return name.getBytes();
		}
		public TestServiceSayParam$Generate unSerialize(byte[] data) {
			TestServiceSayParam$Generate param = new TestServiceSayParam$Generate();
			param.name = new String(data);
			return param;
		}
	}
```

以上代码分别在服务端和客户端初始化时动态生成，带来的作用:
1.避免基本类型装箱拆箱。
2.基本来下和引用类型分别序列化。

**Comment by ralf0131** [comment]
Hi, welcome to Dubbo community!

If it is a feature request, please use English to submit. Dubbo is a global community, and all the issues may be viewed and discussed by people all over the world.

**Comment by scanry** [comment]
Ok,thanks for your advice.
The parameters of execution method of dubbo service are organized by 'Object[]'.such will bring 2 problems:
1.The primitive type are packing and unpacking.
2.Both the primitive  type and the reference type are serialized in the same way.
Code examples:
//method of dubbo sercice
public String say(String name) {
return "hi:" + name;
}
//class of parameters  of  dubbo sercice's method,
//it was generated at the time of initialization.
class TestServiceSayParam$Generate{
         private String name;
         public String getParam1() {
                   return name;
         }
        public byte[] serialize() {
                   return name.getBytes();
         }
         public TestServiceSayParam$Generate unSerialize(byte[] data) {
                    TestServiceSayParam$Generate param = new TestServiceSayParam$Generate();
                    param.name = new String(data);
                    return param;
          }
}
The changes brought about：
1.To avoid the primitive type are packing and unpacking.
2.The primitive type and the reference type are respectively serialized.

**Comment by chickenlj** [comment]
```java
@Override
    protected void encodeRequestData(Channel channel, ObjectOutput out, Object data) throws IOException {
        RpcInvocation inv = (RpcInvocation) data;

        out.writeUTF(inv.getAttachment(Constants.DUBBO_VERSION_KEY, DUBBO_VERSION));
        out.writeUTF(inv.getAttachment(Constants.PATH_KEY));
        out.writeUTF(inv.getAttachment(Constants.VERSION_KEY));

        out.writeUTF(inv.getMethodName());
        out.writeUTF(ReflectUtils.getDesc(inv.getParameterTypes()));
        Object[] args = inv.getArguments();
        if (args != null)
        for (int i = 0; i < args.length; i++){
            out.writeObject(encodeInvocationArgument(channel, inv, i));
        }
        out.writeObject(inv.getAttachments());
    }
```
Do you mean in here, we should serialize according to parameter type?

**Comment by beiwei30** [comment]
this sounds interesting, we should consider it when we tune performance.
