### ISSUE TITLE
[Feature] 目前元数据中心推送的元数据都没有过期时间 使用nacos当元数据中心还有数量限制 改用redis当元数据中心之后 发现也没有过期ttl设置

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#13919]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

目前元数据中心推送的元数据都没有过期时间 使用nacos当元数据中心还有数量限制 改用redis当元数据中心之后 发现也没有过期ttl设置

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JavaLionLi** [comment]
还有就是jedis版本太低了 spring都默认 5.0.X的jedis了 咱们这还是3.X 是否可以升级一下

**Comment by AlbumenJ** [comment]
Please re-submit the issue in English. We want all the content in GitHub are in English.
