### ISSUE TITLE
[Bug] Dubbo项目重启更新过几次，Nacos配置中心生成相同dataId的配置

### ISSUE THREAD

**Issue by ivendear** [apache/dubbo#13912]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.2.11

### Steps to reproduce this issue

![ee3ab560a833cbbdee4f657af21404c](https://github.com/apache/dubbo/assets/30311140/7ba92d91-a8b0-4e7c-ae5a-a931c471bf24)
![80423ecd882c26e2632f816aca87f0c](https://github.com/apache/dubbo/assets/30311140/f671cea2-8974-4269-b1d3-d793243efebb)
如上两图，自动生成的file-center配置有3个，只有其中一个是被用到的，另外两个难道要手动清理？

### What you expected to happen

期望是只保留一个被用到的配置文件

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please re-submit the issue in English.
