### ISSUE TITLE
[Feature] Merge CommonConfigPostProcessor and ConfigPostProcessor 

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#13959]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Merge `CommonConfigPostProcessor` and `ConfigPostProcessor` in `dubbo-common`

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
hello,I am new there,I want to try this,thank you!

**Comment by AlbumenJ** [comment]
> hello,I am new there,I want to try this,thank you!

Please go ahead

**Comment by heliang666s** [comment]
Could  you assign it to me? Thanks~

**Comment by CrazyHZM** [comment]
> Could you assign it to me? Thanks~

Done. @heliang666s

**Comment by heliang666s** [comment]
I have some questions, ask for help
there is my modifylog:
* create src/main/java/org/apache/dubbo/config/CommonConfigPostProcessor.java;(because there is no CommonConfigPostProcessor but need to merge)
* move ConfigPostProcessor to src/main/java/org/apache/dubbo/config/CommonConfigPostProcessor.java;
* Modify dependencies
![图片](https://github.com/apache/dubbo/assets/147408835/43f070fe-dff0-41cf-b36d-1945f480f924)
![图片](https://github.com/apache/dubbo/assets/147408835/9e091aa8-a73e-42d5-b059-54ce79fffa33)
This creates a dependency loop, I don't know how to fix it, please give a suggestion, thanks

**Comment by AlbumenJ** [comment]
1. `CommonConfigPostProcessor` is in `3.3` branch
2. Because `dubbo-rpc-rest` is going to be moved to `dubbo-spi-extensions` in https://github.com/apache/dubbo/issues/13958, we can prevent the dependency loop

**Comment by heliang666s** [comment]
![图片](https://github.com/apache/dubbo/assets/147408835/efc44278-aa04-49bd-966c-7c0b6d6c054e)
Firstly,The pr is always error at the this check point.I don`t know how to fix it.

![图片](https://github.com/apache/dubbo/assets/147408835/1b406883-f927-4021-ab2a-a04454606a9c)

Secondly, I find https://github.com/apache/dubbo/issues/13958 has merged into apache/dubbo-spi-extensions,but did not  merge into apache/dubbo 3.3,the dependency loop is still there.I try to change the vision in pom.xml.But I think it`s  not a good solution.Please give a suggestion, thanks~

**Comment by AlbumenJ** [comment]
> ![图片](https://private-user-images.githubusercontent.com/147408835/320292276-efc44278-aa04-49bd-966c-7c0b6d6c054e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjQzNzIsIm5iZiI6MTcxMjU2NDA3MiwicGF0aCI6Ii8xNDc0MDg4MzUvMzIwMjkyMjc2LWVmYzQ0Mjc4LWFhMDQtNDliZC05NjZjLTdjMGI2ZDZjMDU0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwODE0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNjdkY2JkZTNkNTUzYTJkOWIzMDE0NDU1M2I5YmMxMzAzMjE5ODJkMTQxNGE1NjcwZWNlMTExNGE5YTY1ZjdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vAW8AI-DCp5G2DDtvub-A-5iZTlcVrhWg6s38_9SIIg) Firstly,The pr is always error at the this check point.I don`t know how to fix it.
> 
> ![图片](https://private-user-images.githubusercontent.com/147408835/320292349-1b406883-f927-4021-ab2a-a04454606a9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjQzNzIsIm5iZiI6MTcxMjU2NDA3MiwicGF0aCI6Ii8xNDc0MDg4MzUvMzIwMjkyMzQ5LTFiNDA2ODgzLWY5MjctNDAyMS1hYjJhLWEwNDQ1NDYwNmE5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwODE0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTNhYjYwMjA3YTBjNGUwOTdhYThhNWM3NDM4NzU4YTczNDA4NDVmNzVhNmU1ZTI1ZTE4YzQ4MDYwZjZkMWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wpio0Dwh8xxGMQWViNzP0TWZQjh8nkX0CM2TaVYMxEI)
> 
> Secondly, I find #13958 has merged into apache/dubbo-spi-extensions,but did not merge into apache/dubbo 3.3,the dependency loop is still there.I try to change the vision in pom.xml.But I think it`s not a good solution.Please give a suggestion, thanks~

After https://github.com/apache/dubbo-spi-extensions/pull/306 merge, we can remove all the implementation of `REST protocol` in 3.3 branch

**Comment by anukraticodes** [comment]
Hey, I want to work on this issue.
