### ISSUE TITLE
[Feature] Move Rest Protocol to SPI Extensions

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#13958]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Move Rest Protocol(`dubbo-rpc/dubbo-rpc-rest`, `dubbo-remoting/dubbo-remoting-http`, `dubbo-metadata/dubbo-metadata-processor/src/main/java/org/apache/dubbo/metadata/annotation/processing/rest` and `dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/rest`) to SPI Extensions

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by walkinggo** [comment]
i am willing to do it.could you show more details?Do i need to move the file and make sure it can works?or something else?

**Comment by AlbumenJ** [comment]
> i am willing to do it.could you show more details?Do i need to move the file and make sure it can works?or something else?

1. Copy all the related files to apache/dubbo-spi-extensions repo.
2. test it work proper or not
3. Remove the origin code in apache/dubbo

**Comment by chi3316** [comment]
hello,I am also interested in this issue and i wanna try to solve it .Could you please assign it to me

**Comment by CrazyHZM** [comment]
@chi3316 Go ahead! We will choose and merge better PR.

**Comment by wcy666103** [comment]
hello,I am also interested in this issue and i wanna try to solve it .Could you please assign it to me

**Comment by chi3316** [comment]
@wcy666103 Hi, can you give me your email or other contact details, I would like to ask you some questions about this issue.thanks

**Comment by wcy666103** [comment]
> @wcy666103 Hi, can you give me your email or other contact details, I would like to ask you some questions about this issue.thanks

my DingTalk 1qn_sgsgvles4i

**Comment by wcy666103** [comment]
> @wcy666103 Hi, can you give me your email or other contact details, I would like to ask you some questions about this issue.thanks

my DingTalk 1qn_sgsgvles4i

**Comment by wcy666103** [comment]
PTAL @AlbumenJ 
[Move Rest Protocol to SPI Extensions PR#306](https://github.com/apache/dubbo-spi-extensions/pull/306)

**Comment by wcy666103** [comment]
Due to the use of rest protocol in `dubbo-plugin/dubbo-rest-jaxrs` and `dubbo-rest-spring` modules to test various functions of tri, some problems occurred during my migration. For `SpringMvcRestProtocolTest` classes and class `JaxrsRestProtocolTest` rewriting, can someone help me

**Comment by songxiaosheng** [comment]
> Due to the use of rest protocol in `dubbo-plugin/dubbo-rest-jaxrs` and `dubbo-rest-spring` modules to test various functions of tri, some problems occurred during my migration. For `SpringMvcRestProtocolTest` classes and class `JaxrsRestProtocolTest` rewriting, can someone help me

@EarthChen @suncairong163 PATL

**Comment by oxsean** [comment]
@wcy666103 You can contact me, but these two modules are for tri, what do they have to do with migration?

**Comment by wcy666103** [comment]
> @wcy666103 You can contact me, but these two modules are for tri, what do they have to do with migration?

Please help me change the test cases to Mockito or another protocol,here can talk in DingTalk： 1qn_sgsgvles4i

**Comment by wcy666103** [comment]
The task has been completed and pr has been merged into dubbo branch 3.3 in https://github.com/apache/dubbo/pull/14061 and spi-extension master branch in https://github.com/apache/dubbo-spi-extensions/pull/306
