### ISSUE TITLE
[Feature] Move Mesh Rule Router to SPI Extensions

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#13957]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Move Mesh Rule Router(dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh) to SPI Extensions

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AmmyHaber** [comment]
I send a pull request about this issue,please check it.[#13977](https://github.com/apache/dubbo/pull/13977/commits/0accf5445238553d263dcebb19e0d6f70d160bda)

**Comment by heliang666s** [comment]
hello,I want to solve it,please assign it to me,thanks ~

**Comment by AlbumenJ** [comment]
> hello,I want to solve it,please assign it to me,thanks ~

done

**Comment by heliang666s** [comment]
Hi, I don't know how to do, can you give some details or advice,thanks

**Comment by heliang666s** [comment]
![图片](https://github.com/apache/dubbo/assets/147408835/10fe2987-eab8-40df-9761-13332de5ce5b)
hi,I don't know how to implement the interface,can you give some details or advice,thanks

**Comment by AlbumenJ** [comment]
Just copy all the related code to `dubbo-spi-extensions` and then remove them in `apache/dubbo`

**Comment by heliang666s** [comment]
PTAL @AlbumenJ  https://github.com/apache/dubbo-spi-extensions/pull/307

**Comment by heliang666s** [comment]
@AlbumenJ I remove dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh ,but other code depend on the file.How I can solve it?add dependency in pom.xml? 
![图片](https://github.com/apache/dubbo/assets/147408835/0cf6b7b6-422c-4fdb-9150-a57cd6781876)

**Comment by AlbumenJ** [comment]
> @AlbumenJ I remove dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/mesh ,but other code depend on the file.How I can solve it?add dependency in pom.xml? ![图片](https://private-user-images.githubusercontent.com/147408835/320498313-0cf6b7b6-422c-4fdb-9150-a57cd6781876.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTkzNTcsIm5iZiI6MTcxMjcxOTA1NywicGF0aCI6Ii8xNDc0MDg4MzUvMzIwNDk4MzEzLTBjZjZiN2I2LTQyMmMtNGZkYi05MTUwLWE1N2NkNjc4MTg3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwMzE3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzM4NWJhNGMwZTNhZGE4OGZmNWI0MTRmOGViMGI3MjQzODFkMWEzN2NkNWI2ZjQ0YmUxNjViM2U2ZDYyNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n3V5u-4MpTnj0Ln0TMzeRriT9wgZ0Mlgba8SCXm0wjA)

How about copy all the related classes to `org.apache.dubbo.rpc.cluster.configurator.parser.model`

**Comment by walkinggo** [comment]
Is this issue completed? Is there any progress? I am very interested in this and want to join. @heliang666s

**Comment by wcy666103** [comment]
Is this issue completed? Is there any progress? I am very interested in this and want to join. @heliang666s

**Comment by heliang666s** [comment]
This issue is basically done, I've filed it at apache/dubbo-spi-extensions#307 and the merge was successful. I was a bit busy a while ago and had a little problem left in the msater branch, and I'll fix it recently. Thank you for your concern @wcy666103 @walkinggo

**Comment by songxiaosheng** [comment]
ref https://github.com/apache/dubbo-spi-extensions/pull/307
