### ISSUE TITLE
[Feature][3.3] Triple rest path match support case insensitive

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#13967]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Same as spring mvc, we need to support path case insensitive, as well as can be enabled by configuration

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by qyi71** [comment]
hello,I'm new , I want try this. but  i don't know more detail. can you describe it in more detail?  that kind of paths?

**Comment by oxsean** [comment]
@qyi71 Sorry, I'm already working on it.
The url match of triple rest is case-sensitive by default and needs to support case-insensitive.
