### ISSUE TITLE
[Feature][3.3] Triple protocol http1 upgrade support

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#13966]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Documents and netty demo:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism
- https://github.com/abhijitparkhi1983/netty/blob/b2dc54c8c672c325e1056c62f7ca84406e28fb91/example/src/main/java/io/netty/example/http2/helloworld/server/HelloWorldHttp2Handler.java

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by walklown** [comment]
Could you please add some details, such as the usage scenarios of this function in the Tripple protocol?

**Comment by oxsean** [comment]
If using non-gRPC, clients usually don't default to HTTP/2. Therefore, after supporting http1 upgrade, clients can be guided to upgrade to HTTP/2, leverage the benefits of Http/2

**Comment by oxsean** [comment]
@walklown please take a look this PR:
https://github.com/apache/dubbo/pull/14223
