### ISSUE TITLE
[Feature] Update FileTest in 3.3

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#13961]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Update `org.apache.dubbo.dependency.FileTest` in 3.3 to support check `dubbo-all-shaded` and `dubbo-core-spi`

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RainYuY** [comment]
I would like to try to do this. Can you assign it to me? Thanks~
I think I should remove them from the ignored list and add them to the dependencies pom, which will check them.

**Comment by CrazyHZM** [comment]
@AlbumenJ This can describe the content of the specific need to check what it is. 
This PR (https://github.com/apache/dubbo/pull/13978) does not understand what needs to be done.

**Comment by RainYuY** [comment]
> I would like to try to do this. Can you assign it to me? Thanks~ I think I should remove them from the ignored list and add them to the dependencies pom, which will check them.


> @AlbumenJ This can describe the content of the specific need to check what it is. This PR (#13978) does not understand what needs to be done.

Sorry for that. I think I actually didn't understand. As I said, I think `dubbo-all-shaded` and `dubbo-core-spi` are new modules that need to be checked. Now, when @CrazyHZM reninded it, I think they should have their own checks like `dubbo-all` and `dubbo-bom`. This time, do I understand correctly?

**Comment by RainYuY** [comment]
Another question, what is the positioning of `core-spi` and `all-shaded`? Are they gradually replacing the SPI and includes in `dubbo-all` using the Maven Shade Plugin? I think `dubbo-all-shaded` should imply this, but `dubbo-core-spi` hasn't been updated for a long time. I'm not sure whether it should only check the included SPI or all SPI. Should I also update the SPI dependencies in pom?

**Comment by AlbumenJ** [comment]
Update `checkDubboAllTransform` in `FileTest` to check `dubbo-all-shaded` and `dubbo-core-spi`
