### ISSUE TITLE
dubbo 3.1.7 

### ISSUE THREAD

**Issue by LuoHpeng** [apache/dubbo#13972]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.1.7,jdk 1.8

### Steps to reproduce this issue

When the dubbo interface is registered with kubernetes, it is normal in the early stage, but the dubbo interface is added later, resulting in the application status always down. After investigation, the following is an exception

![image](https://github.com/apache/dubbo/assets/35796450/785a96bc-9806-4603-8a09-69b1d9754090)

The source code involved

![image](https://github.com/apache/dubbo/assets/35796450/5453de5a-242d-42dc-a471-e3dede4d1ee2)

Upgrade kubernetes-client to 6.4.1 Solution, kubernetes-client code changes greatly

![image](https://github.com/apache/dubbo/assets/35796450/109993b4-1b11-408b-bcbf-c8a8ab188f23)

### What you expected to happen

The kubernetes-client version in dubbo 3.1.7 was upgraded to 6.4.1

<img width="526" alt="image" src="https://github.com/apache/dubbo/assets/35796450/a370fe89-e131-40d6-a683-aa6d03c1a6db">

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
`dubbo-kubernetes` has been moved to https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-kubernetes. You can submit a PR to fix it.

**Comment by wcy666103** [comment]
The latest dependency version has been upgraded to 6.12.0 https://github.com/apache/dubbo-spi-extensions/pull/321
 please close this issue as complete
