### ISSUE TITLE
[Bug] 同等条件下，压测效果(QPS/RT)dubbo3不如dubbo2表现好

### ISSUE THREAD

**Issue by roadToit** [apache/dubbo#14013]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.1.11
Dubbo 2.6.12
OpenJdk 11
Linux

### Steps to reproduce this issue

1、空dubbo接口（里面无任何逻辑）
2、dubbo接口返回一个pojo对象
3、dubbo接口返回pojo的list
分别基于dubbo2和dubbo3对以上三种接口进行压测，
压测结果：
1、基于dubbo3的接口比基于dubbo2的接口的QPS下降了相当数值；
2、基于dubbo3的接口比基于dubbo2的接口RT（Max/TP9999/TP999/TP99/avg）都有不同程度的上升，接口变慢了。
基于上面的压测结果，请问还有必要进行dubbo2到dubbo3的升级吗

### What you expected to happen

期望dubbo3的QPS和RT相较于dubbo2能够有提升，但是压测结果并不是这样，很困惑

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please submit the issue in English.
