### ISSUE TITLE
[Feature][3.3] Triple rest useTrailingSlashMatch useSuffixPatternMatch support

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14036]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

Supports useTrailingSlashMatch useSuffixPatternMatch in triple rest similar to Spring MVC.
https://docs.spring.io/spring-framework/docs/5.3.9/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.html#setUseSuffixPatternMatch-boolean-

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
hello，I think I can solve it, can it be assigned to me, thanks~

**Comment by heliang666s** [comment]
Please tell me which file you want to change. And tell me more details of the modification, thanks~@oxsean

**Comment by oxsean** [comment]
> Please tell me which file you want to change. And tell me more details of the modification, thanks~@oxsean

My dingding id: oxsean
We can discussion on dingding.
