### ISSUE TITLE
[Bug] why it default use 【dubbo】

### ISSUE THREAD

**Issue by vhypnus** [apache/dubbo#14063]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.2.5
java 1.8

### Steps to reproduce this issue

code in org.apache.dubbo.registry.client.metadata.StandardMetadataServiceURLBuilder.generateUrlWithoutMetadata 

        URLBuilder urlBuilder = new URLBuilder()
                .setHost(host)
                .setPort(port)
                .setProtocol(DUBBO_PROTOCOL)
                .setPath(MetadataService.class.getName())
                .addParameter(TIMEOUT_KEY, ConfigurationUtils.get(applicationModel, METADATA_PROXY_TIMEOUT_KEY, DEFAULT_METADATA_TIMEOUT_VALUE))
                .addParameter(Constants.RECONNECT_KEY, false)
                .addParameter(SIDE_KEY, CONSUMER)
                .addParameter(GROUP_KEY, serviceName)
                .addParameter(VERSION_KEY, MetadataService.VERSION)
                .addParameter(RETRIES_KEY, 0);

### What you expected to happen

why don not use protocol from 【dubbo.endpoints】property it has the right protocol.

### Anything else
online properties
```dubbo.application.name=dubbo-sample
dubbo.protocol.name=tri
dubbo.protocol.port=-1
dubbo.registries.idRegistry.group=finepay-id
dubbo.registries.idRegistry.address=nacos://xxxx:8848?username=xxx&password=xxxxx
#dubbo.registries.idRegistry.address=nacos://xxxxxx:8848
dubbo.registries.idRegistry.register-mode=instance
dubbo.registries.idRegistry.parameters.namespace=788986be-5d7b-42ed-a542-xxxxxxx
```

### Are you willing to submit a pull request to fix on your own

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
I think you can refer to org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java @vhypnus

**Comment by vhypnus** [comment]
> I think you can refer to org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java @vhypnus

**Comment by AlbumenJ** [comment]
`generateUrlWithoutMetadata` is only for **Not-Dubbo** framework
Such as `Spring Cloud`
