### ISSUE TITLE
[Feature][3.3] Triple http limiting the size of the HTTP request and response

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14068]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

If the client provides a body input that is too large or the response output is too large, it could make server OOM. Therefore, it is necessary to limit their sizes to prevent DOS attacks.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by finefuture** [comment]
I'm working on it, please assign it to me.

**Comment by Chenjp** [comment]
@finefuture  

Pls consider adding support for following scope level "max-body-size":
1. Application;
2. Protocol;
3. Service;

Priority : Service>Protocol>Application.

Example:
1. Nginx:
```
Syntax: client_max_body_size size;
Context: http, server, location
```
2. Another Example: [Kong request-size-limiting](https://docs.konghq.com/hub/kong-inc/request-size-limiting/configuration/)

**Comment by finefuture** [comment]
> @finefuture
> 
> Pls consider adding support for following scope level "max-body-size":
> 
> 1. Application;
> 2. Protocol;
> 3. Service;
> 
> Priority : Service>Protocol>Application.
> 
> Example:
> 
> 1. Nginx:
> 
> ```
> Syntax: client_max_body_size size;
> Context: http, server, location
> ```
> 
> 2. Another Example: [Kong request-size-limiting](https://docs.konghq.com/hub/kong-inc/request-size-limiting/configuration/)

Good idea, but cross-protocol may involve relatively large changes. Maybe we can implement it in triple protocol first.
