### ISSUE TITLE
[Bug] The hyperlink to the document is broken

### ISSUE THREAD

**Issue by heliang666s** [apache/dubbo#14062]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java Samples (apache/dubbo-samples)

### Dubbo Version

No

### Steps to reproduce this issue

![图片](https://github.com/apache/dubbo/assets/147408835/8100103c-e225-4eba-b9c1-74bacb9d8045)
![图片](https://github.com/apache/dubbo/assets/147408835/aee96c9d-b826-4055-a718-9d29d8a7854c)

### What you expected to happen

Restore the normal use of the hyperlink

### Anything else

Please assign to me if possible,thanks~

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Can you please help fix it?

**Comment by heliang666s** [comment]
Yes,I am.I will find other broken  hyperlink to fix.Please assign me ~

**Comment by wcy666103** [comment]
Please close this issue as completed @heliang666s
