### ISSUE TITLE
[Bug] rmi protocol doesnot work for threads ，iothreads  etc.. 

### ISSUE THREAD

**Issue by hhfdna** [apache/dubbo#14089]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 2.6.2

### Steps to reproduce this issue

write a dubbo service with rmi protocol, set iothreads, threads etc. attributes,

### What you expected to happen

protocol attribute dispather,threadpool,threads doesnot work for rmi

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Dubbo 2.6.x is EOL now. Please check in the latest version.
BTW, rmi is now moved to dubbo-spi-extensions
