### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by wcy666103** [apache/dubbo#14083]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SPI Extensions (apache/dubbo-spi-extensions)

### Descriptions

`MinaClientToServerTest` in spi-extensions project The local test will pass, but not the ci. Currently, it is annotated with disabled.Related commits can be viewed here https://github.com/apache/dubbo-spi-extensions/pull/310

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by songxiaosheng** [comment]
please add title
