### ISSUE TITLE
[Bug] Dubbo-samples test start error

### ISSUE THREAD

**Issue by heliang666s** [apache/dubbo#14085]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java Samples (apache/dubbo-samples)

### Dubbo Version

OpenJDK 17.0.10,Ubuntu 22.04

### Steps to reproduce this issue

* When I solve the issue:https://github.com/apache/dubbo/issues/13861,I add the test ,however,it maybe have bug.I do not konw how to fix it.This test is edit by myself.
![图片](https://github.com/apache/dubbo/assets/147408835/f67670db-8538-42f8-bb67-a73d6d6a95b4)
![图片](https://github.com/apache/dubbo/assets/147408835/56b50925-dff1-4214-aeae-9297d27bbca7)

### What you expected to happen

everything is ok.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FoghostCn** [comment]
Have you start provider first?

**Comment by wcy666103** [comment]
It looks like the provider is not started,If there are no other problem, we can close this issue @heliang666s
