### ISSUE TITLE
[Feature] maven中央仓库还没有3.2.12版本的dubbo

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#14107]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

see the issue title

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zrlw** [comment]
![image](https://github.com/apache/dubbo/assets/40652892/2ec50ddc-dee5-4ac8-9a46-74c3f34e7a59)

**Comment by bert82503** [comment]
这里也木有，估计安装到阿里的仓库

https://mvnrepository.com/artifact/org.apache.dubbo/dubbo

<img width="932" alt="image" src="https://github.com/apache/dubbo/assets/1811851/a3fccf48-d00a-4cf8-8484-0550ed0e211c">

**Comment by aofall** [comment]
目前是 Pre-release 状态，估计投票还没有通过所以没发布吧

**Comment by lihuagang03** [comment]
> 目前是 Pre-release 状态，估计投票还没有通过所以没发布吧

不是吧，版本Tag都打出来了，这个版本Tag名称好像没有`dubbo-`前缀，命名方式没有保持一致
https://github.com/apache/dubbo/releases/tag/3.2.12

**Comment by aofall** [comment]
> > 目前是 Pre-release 状态，估计投票还没有通过所以没发布吧
> 
> 不是吧，版本Tag都打出来了，这个版本Tag名称好像没有`dubbo-`前缀，命名方式没有保持一致 https://github.com/apache/dubbo/releases/tag/3.2.12

GitHub release 只是发布的第一步（Pre-release），要发布到maven中央仓库后续还有审核投票流程

**Comment by FoghostCn** [comment]
https://central.sonatype.com/artifact/org.apache.dubbo/dubbo/3.2.12
