### ISSUE TITLE
[Bug]org.apache.dubbo.config.spring.util.AnnotationUtils 派生注解的属性无法merge

### ISSUE THREAD

**Issue by luoning810** [apache/dubbo#14104]
### Pre-check

- [ ] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.2.11

### Steps to reproduce this issue

org.springframework.core.annotation.AnnotatedElementUtils#tryGetMergedAnnotation  注解属性merge未生效

### What you expected to happen

<img width="1324" alt="image" src="https://github.com/apache/dubbo/assets/22349611/79763ae3-277c-4c8c-a41f-e56a359a4b82">
问题：findMethod 结果为null

推测原因：通过反射获取 org.springframework.core.annotation.AnnotatedElementUtils#getMergedAnnotation方法时入参错误。
spring 版本：5.3.x
<img width="1443" alt="image" src="https://github.com/apache/dubbo/assets/22349611/7b4af4a6-3b50-4f14-be2f-d4a9923ee220">

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luoning810** [comment]
@songxiaosheng  Please help confirm

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)
