### ISSUE TITLE
Dubbo 小流量预热 失效的[Bug] 

### ISSUE THREAD

**Issue by smalltalkhyb** [apache/dubbo#14123]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo-spring-boot-starter     <version>3.2.6</version>

### Steps to reproduce this issue

调试 Dubbo小流量预热的时候

Dubbo 通过集中默认的负载均衡策略实现⼩流量预热

### What you expected to happen

Dubbo 小流量预热 失效的[Bug] 
Dubbo 通过集中默认的负载均衡策略实现⼩流量预热
AbstractLoadBalance 中的getWeight 方法获取 timestamp的时候，错误的获取的是consumerURL 参数里面的 timestamp

![image](https://github.com/apache/dubbo/assets/3281621/012cd83b-d910-4595-8be6-9feb31975333)

![image](https://github.com/apache/dubbo/assets/3281621/8124c736-5ddf-448f-8a38-8f556c1ecab2)

consumer://192.168.8.70/xxx.service.FlowTestService?application=dubbo-provider-xxx&background=false&category=providers,configurators,routers&check=false&dubbo=2.0.2&executor-management-mode=isolation&file-cache=true&interface=xxx.service.FlowTestService&methods=test&mse.project.name=j1h07oev3e@2df24465468817c&opensergo.io/canary-huyanbing=huyanbing&pid=61978&qos.enable=true&release=3.2.6&retries=2&side=consumer&sticky=false&timeout=10000&timestamp=1713848191305&unloadClusterRelated=false

### Anything else

Every times 

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by luoning810** [comment]
the same problem in v3.2.11

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)
