### ISSUE TITLE
[Bug] Multiple Logging Implementations Detected in Dubbo-Samples

### ISSUE THREAD

**Issue by chi3316** [apache/dubbo#14120]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java Samples (apache/dubbo-samples)

### Dubbo Version

Dubbo 3.3.0-beta.1
jdk21

### Steps to reproduce this issue

1. Clone the dubbo samples repository:
     ```java
       git clone https://github.com/apache/dubbo-samples.git
    ````
2. Open the project in IntelliJ IDEA and navigate to the 2-advanced/dubbo-samples-cache Module.
3. Run `src/main/java/org/apache/dubbo/samples/cache/CacheProvider.java`, located in dubbo-samples-cache-provider.
4. It will appear a warning from SLF4J
![image](https://github.com/apache/dubbo/assets/110283895/6dae8ea7-f7b8-4ef9-80a2-20fa5e471f1a)

### What you expected to happen

I expected the test cases to execute successfully without encountering any warnings related to multiple logging implementations.

### Anything else

**The identified problematic modules in the 2-advanced module  include :** 
- dubbo-samples-cache
- dubbo-samples-group
- dubbo-samples-mock
- dubbo-samples-notify
- dubbo-samples-rpccontext
- dubbo-samples-service-discovery
- dubbo-samples-spring-security
- dubbo-samples-validation

**Root Cause:**

The issue arises due to the inclusion of dubbo-zookeeper-curator5-spring-boot-starter without excluding the logging implementation dependencies, leading to conflicts with existing logging implementations in the classpath.

**Solution:**
1. Option 1: manually Exclude Logging Implementations related logback
    ![image](https://github.com/apache/dubbo/assets/110283895/17aaae80-5c8e-40d2-a666-a2caf8724b4c)
2. Option 2: upgrade to Dubbo 3.3.0-beta.2 or higher
   Starting from Dubbo version 3.3.0-beta.2, adding dubbo-zookeeper-curator5-spring-boot-starter will no longer include logging implementation dependencies by default. Therefore, updating the Dubbo version to 3.3.0-beta.2 or higher can resolve the issue without the need for manual exclusions.
![image](https://github.com/apache/dubbo/assets/110283895/5e8cc748-61f4-4b2f-82c2-6a01003c7b55)

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by oxsean** [comment]
The issue was indeed present in the previous versions, but it has been resolved in the latest beta. 
[GitHub - Apache Dubbo Issue #13188](https://github.com/apache/dubbo/issues/13188).

For more details, you can refer to the documentation here: [Apache Dubbo Documentation](https://dubbo.apache.org/en/docs3-v2/java-sdk/advanced-features-and-usage/others/logger-howto/).

**Comment by oxsean** [comment]
The issue was indeed present in the previous versions, but it has been resolved in the latest beta. 
[GitHub - Apache Dubbo Issue #13188](https://github.com/apache/dubbo/issues/13188).

For more details, you can refer to the documentation here: [Apache Dubbo Documentation](https://dubbo.apache.org/en/docs3-v2/java-sdk/advanced-features-and-usage/others/logger-howto/).

**Comment by chi3316** [comment]
> The issue was indeed present in the previous versions, but it has been resolved in the latest beta. [GitHub - Apache Dubbo Issue #13188](https://github.com/apache/dubbo/issues/13188).
> 
> For more details, you can refer to the documentation here: [Apache Dubbo Documentation](https://dubbo.apache.org/en/docs3-v2/java-sdk/advanced-features-and-usage/others/logger-howto/).

Got it. Thanks for the answer.
