### ISSUE TITLE
[Bug] Dubbo 版本 3.2.2 JDK 版本 17 使用 tolist 报错

### ISSUE THREAD

**Issue by LinQi0777** [apache/dubbo#14144]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java version : 3.2.2 
JDK version : 17
OS version：Windows 11

### Steps to reproduce this issue

When Dubbo version 3.2.2 is used, when JDK version 17 is used, the Java native API tolist will report an error, but the collon(Cortrolltion.tolist) will release the error and will not report an error.
当使用 Dubbo 版本 3.2.2 的时候，当 JDK 版本为 17 的时候，使用 Java 本地的 API  tolist 会发生报错，但是使用 collon(Cortrolltion.tolist) 报错则解除，不会发生报错

### What you expected to happen

I think it may be due to the difference between the way Java native serialization is used and the way collon serialization is used. It may be due to the fact that Dubbo 3.2.2 is incompatible with Java native serialization, but compatible with collon serialization.
我认为可能是 Java 本地序列化的方式与 collon 序列化的方式有所差别导致的，可能是 Dubbo 3.2.2 版本针对 Java 原生序列化方式不兼容导致，但是对 collon 序列化的方式兼容。

### Anything else

I hope I can improve after I know the bug, thank you!
希望在得知 bug 之后可以改进吧，谢谢！

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)
