### ISSUE TITLE
[Bug] nacos tests timeout and dubbo-samples-test-13787 caseSpecificVersion led to the failure of the integration tests

### ISSUE THREAD

**Issue by jkoChen** [apache/dubbo#14158]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java Integration Cases (apache/dubbo-integration-cases)

### Dubbo Version

dubbo.version=3.2.13-SNAPSHOT spring.version=5.3.30 java.version=8 

### Steps to reproduce this issue

The "integration-test" step of Dubbo's GitHub workflow cannot be executed successfully.
<img width="1332" alt="image" src="https://github.com/apache/dubbo/assets/37362859/172fde66-fcb5-4912-86b0-20862fa0cc23">

<img width="1215" alt="image" src="https://github.com/apache/dubbo/assets/37362859/6297aee5-44c3-4528-85d8-fe9d2e916fc6">

### What you expected to happen

<img width="1215" alt="image" src="https://github.com/apache/dubbo/assets/37362859/6297aee5-44c3-4528-85d8-fe9d2e916fc6">
The five tests have consistently failed and have not been successful. Among them, the tests related to Nacos could not be conducted because I was unable to build the Docker image locally for testing.
The reason for the failure of the test dubbo-samples-test-13787 is that it uses a specific version number of Dubbo, which leads to the test not utilizing the version of Dubbo that was built during the CI (Continuous Integration) process, resulting in the failure.
<img width="1217" alt="image" src="https://github.com/apache/dubbo/assets/37362859/024db92f-27b6-40f1-b384-57e6acf396d6">

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by FoghostCn** [comment]
The case-versions.conf configuration file describes the dubbo version that is expected to run. It will not run when your version does not match.

so if you use dubbo.version=3.2.13-SNAPSHOT it should not run,please check you env DUBBO_VERSION

**Comment by jkoChen** [comment]
> The case-versions.conf configuration file describes the dubbo version that is expected to run. It will not run when your version does not match.
> 
> so if you use dubbo.version=3.2.13-SNAPSHOT it should not run,please check you env DUBBO_VERSION


@FoghostCn 
As shown in the following code:
<img width="852" alt="image" src="https://github.com/apache/dubbo/assets/37362859/8f6a1cf6-6035-43bb-a7e1-fe9109620c91">
When there is no match and it is not an inequality (!=), the test case will be executed with this specific version number. I am uncertain whether this is the intended logic or a bug.

**Comment by AlbumenJ** [comment]
Fix in https://github.com/apache/dubbo-integration-cases/pull/23
