### ISSUE TITLE
[Bug] Dubbo 3.2.11 dubbo-metadata-report-etcd作为元数据中心报错

### ISSUE THREAD

**Issue by glynnwei** [apache/dubbo#14160]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SPI Extensions (apache/dubbo-spi-extensions)

### Dubbo Version

Dubbo：3.2.11
JDK：1.8

### Steps to reproduce this issue

dubbo-metadata-report-etcd作为元数据中心接入
```
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-metadata-report-etcd</artifactId>
    <version>2.7.23</version>
</dependency>
```

### What you expected to happen

EtcdMetadataReport unrealized registerServiceAppMapping method returns false by default.

### Anything else

nacos and zookeeper implement this method

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)
