### ISSUE TITLE
[Bug] triple远程调用，连接异常重连，导致客户端阻塞直到超时

### ISSUE THREAD

**Issue by jybjobs** [apache/dubbo#14167]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version
3.2.11

### Steps to reproduce this issue
 triple远程调用，等待响应阶段，如果出现连接异常重连，之后客户端会阻塞直到timeout。
------

写一接口，内部可以sleep 30s，设置客户端超时时间为60s.
发起客户端调用后，迅速 kill 或restart 服务端。客户端没有立即失败，而是会等到60s timeout。

### What you expected to happen

连接出现异常时客户端可以快速失败

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)
