### ISSUE TITLE
The matching wildcard is strict, but no declaration can be found for element 'dubbo:consumer'.

### ISSUE THREAD

**Issue by walnut-tom** [apache/dubbo#14187]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo: 2.7.15
openjdk version "1.8.0_252"
CentOS release 6.10 (Final)

### Steps to reproduce this issue

spring 配置文件中写 https://dubbo.apache.org/schema/dubbo/dubbo.xsd 在访问dubbo.apache.org网络不畅的情况下会导致服务启动失败
`Offending resource: class path resource [applicationContext.xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 10 in XML document from class path resource [dubbo-consumer.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 10; columnNumber: 52; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'dubbo:consumer'.
`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
       http://dubbo.apache.org/schema/dubbo https://dubbo.apache.org/schema/dubbo/dubbo.xsd">

    <dubbo:consumer timeout="5000" check="false" />
</beans>
```

### What you expected to happen

配置文件中可以写
   xmlns:dubbo="http://dubbo.apache.org/schema/dubbo" 
或者
   xmlns:dubbo="https://dubbo.apache.org/schema/dubbo"

http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd
https://dubbo.apache.org/schema/dubbo https://dubbo.apache.org/schema/dubbo/dubbo.xsd

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Duplicated with https://github.com/apache/dubbo/discussions/14186
