### ISSUE TITLE
[Bug] enable-empty-protection default value is different between doc and code

### ISSUE THREAD

**Issue by neal-wyz** [apache/dubbo#14190]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo java 3.2.12, Openjdk 1.8, idea 2024

### Steps to reproduce this issue

![微信截图_20240514181741](https://github.com/apache/dubbo/assets/18344122/c89f8737-d52e-4207-905d-c69d2bb81ecd)
![微信截图_20240514181757](https://github.com/apache/dubbo/assets/18344122/3c418a0c-de85-4f2d-82ac-839a5ee41f82)
![微信图片_20240514181611](https://github.com/apache/dubbo/assets/18344122/e2083752-87d9-4428-af7f-8831ff8628a9)
![微信图片_20240514181703](https://github.com/apache/dubbo/assets/18344122/7b0d37e3-2a53-4adc-902a-85969e1e2791)

### What you expected to happen

I get some WARN info in console window, if the default value is true, the WARN info is unexpected.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
This has been changed. Please help update the documents.

**Comment by neal-wyz** [comment]
> This has been changed. Please help update the documents.

OK, thanks, I am glad to do that.
