### ISSUE TITLE
No such extension org.apache.dubbo.rpc.Filter

### ISSUE THREAD

**Issue by flanet88** [apache/dubbo#14205]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo:3.2.9  jdk:1.8

### Steps to reproduce this issue

![filter](https://github.com/apache/dubbo/assets/40165957/885d4dab-0101-4be1-a1a6-2d71dd4a7cbf)
![filter1](https://github.com/apache/dubbo/assets/40165957/776761bc-aaba-4211-8c28-129b2fbcbb49)
![filter2](https://github.com/apache/dubbo/assets/40165957/74921754-9d1f-43cd-b4ea-340e6e11f4fa)
如图这个是自定义filter

### What you expected to happen

![filter](https://github.com/apache/dubbo/assets/40165957/027f008c-0866-4676-bd8d-aa65fc3a8387)
![filter1](https://github.com/apache/dubbo/assets/40165957/741f77be-b8fa-49b7-b6fe-01b48ae3197f)
![filter2](https://github.com/apache/dubbo/assets/40165957/d88fbb5a-54cc-493c-9283-30ca5f88d19c)

获取不到自定义过滤器

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please submit the issue all in English:)
