### ISSUE TITLE
[Bug] Example dubbo-samples-triple-rest-jaxrs runing failed in 3.3

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14236]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java Samples (apache/dubbo-samples)

### Dubbo Version

3.3.0-beta.3-SNAPSHOT

### Steps to reproduce this issue

Run example dubbo-samples-triple-rest-jaxrs

### What you expected to happen

Run succeed. but failed
https://github.com/apache/dubbo-samples/pull/1150#issuecomment-2132594889

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
The specific version number is 3.3.0-beta.3-SNAPSHOT
