### ISSUE TITLE
[Bug] spring boot 3.2.5  ConfigurationClassPostProcessor WRAN log

### ISSUE THREAD

**Issue by firmianaQ** [apache/dubbo#14253]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.2.11, Graalvm-ce 17.0.9, Windows 11

### Steps to reproduce this issue

After upgrading to Spring Boot 3.2.5 our services that use now log a new warning on startup

> 2024-05-29 10:09:24 [main] WARN  o.s.c.a.ConfigurationClassPostProcessor - Cannot enhance @Configuration bean definition 'org.apache.dubbo.spring.boot.autoconfigure.DubboRelaxedBinding2AutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static' and/or marking the containing configuration class as 'proxyBeanMethods=false'.

> 2024-05-29 10:09:24 [main] WARN  o.s.c.a.ConfigurationClassPostProcessor - Cannot enhance @Configuration bean definition 'org.apache.dubbo.spring.boot.autoconfigure.DubboAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static' and/or marking the containing configuration class as 'proxyBeanMethods=false'.

### What you expected to happen

no warning

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xixingya** [comment]
@firmianaQ  if you want to use graalvm with native please use dubbo 3.3, thank you

**Comment by wcy666103** [comment]
The problem in the 3.3 branch has been solved, see: https://github.com/apache/dubbo/pull/13461
If you want to use native, use 3.3, as 3.2 will not provide support for this.
Please close this pr as complete
