### ISSUE TITLE
[Bug] In Dubbo 3, when configuring multiple registries, one registry will be overwritten by another one.

### ISSUE THREAD

**Issue by goto456** [apache/dubbo#14258]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.2.9, JDK 1.8, MacOS

### Steps to reproduce this issue

In an application, it is both a provider and a consumer.
When it as a provider, use spring boot properties like this:
```
dubbo.registry.address=nacos://nacos-mba.qiyi.domain:8848
```
and when it as a consumer to invoker other provider, the registry is like this:
```
RegistryConfig registryConfig = new RegistryConfig("nacos://nacos-test.qiyi.domain:8848");
referenceConfig.setRegistry(registryConfig);
```
and then run the project.

When running to `ConfigValidationUtils.loadRegistries()`, the registry for the consumer will be overwrittern by the registry for the provider.

The relevant screenshots are as follows：

![Before refresh](https://raw.githubusercontent.com/goto456/markdown-pictures/master/wengeblog/dubbo-bug-1.jpg)

![After refresh](https://raw.githubusercontent.com/goto456/markdown-pictures/master/wengeblog/dubbo-bug-2.jpeg)

### What you expected to happen

The registry for the consumer should not be overwrittern by the registry for the provider.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
`dubbo.registry.address` is a global key to override configuration. 
If you want to use `-D` properies, try use `dubbo.registries.xxx.address=nacos://xxx`

**Comment by heliang666s** [comment]
I think it's best for you to have two XML configuration files for one service, one for consumers and one for producers, as detailed in the link below：https://blog.csdn.net/weixin_43932472/article/details/113887427

**Comment by goto456** [comment]
> `dubbo.registry.address` is a global key to override configuration. If you want to use `-D` properies, try use `dubbo.registries.xxx.address=nacos://xxx`

But in dubbo 2.x it will not be overrided.

**Comment by AlbumenJ** [comment]
> > `dubbo.registry.address` is a global key to override configuration. If you want to use `-D` properies, try use `dubbo.registries.xxx.address=nacos://xxx`
> 
> But in dubbo 2.x it will not be overrided.

This is not by design
