### ISSUE TITLE
[Bug] 关于dubbo广播【BROADCAST】2.6.X 2.7.X 3.X问题

### ISSUE THREAD

**Issue by nuoqin** [apache/dubbo#14266]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

2.7.X/3.X

### Steps to reproduce this issue

我们系统从alibaba dubbo 2.6.X升级到2.7.X/3.X时，在使用ReferenceConfig，发现registryConfig.setCluster(ClusterRules.BROADCAST)时，发现在2.6.X版本是支持广播
到其他服务器上的服务。但升级到2.7.X/3.X时，服务无法进行广播。

2.6.X代码如下
```
ReferenceConfig<CacheService> reference = new ReferenceConfig<>();
RegistryConfig registryConfig = new RegistryConfig("zookeeper地址");
**registryConfig.setCluster(ClusterRules.BROADCAST);**
reference.setRegistry(registryConfig); 
//设置ApplicationConfig
reference.setApplication(application);
reference.setInterface(CacheSyncService.class);

CacheService service = reference.get();

service.update();
```
2.7.X/3.X代码确要
```
ReferenceConfig<CacheService> reference = new ReferenceConfig<>();
RegistryConfig registryConfig = new RegistryConfig("zookeeper地址");
reference.setRegistry(registryConfig); 
//设置ApplicationConfig
reference.setApplication(application);
reference.setInterface(CacheSyncService.class);
**reference.setCluster(ClusterRules.BROADCAST);**

CacheService service = reference.get();

service.update();
```

### What you expected to happen

服务不可用

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please submit the issue in English :)

**Comment by nuoqin** [comment]
When our system is upgraded from alibaba dubbo 2.6.X to 2.7.X/3.X, when we use ReferenceConfig and find registryConfig.setCluster(ClusterRules.BROADCAST), we find that broadcast is supported in version 2.6.X
to services on other servers. However, when upgrading to 2.7.X/3.X, the service cannot broadcast.


2.6.X code is as follows

```
ReferenceConfig<CacheService> reference = new ReferenceConfig<>();
RegistryConfig registryConfig = new RegistryConfig("zookeeper地址");
**registryConfig.setCluster(ClusterRules.BROADCAST);**
reference.setRegistry(registryConfig); 
//设置ApplicationConfig
reference.setApplication(application);
reference.setInterface(CacheSyncService.class);

CacheService service = reference.get();

service.update();
```
2.7.X/3.X code is as follows
```
ReferenceConfig<CacheService> reference = new ReferenceConfig<>();
RegistryConfig registryConfig = new RegistryConfig("zookeeper地址");
reference.setRegistry(registryConfig); 
//设置ApplicationConfig
reference.setApplication(application);
reference.setInterface(CacheSyncService.class);
**reference.setCluster(ClusterRules.BROADCAST);**

CacheService service = reference.get();

service.update();
```
But in the official documentation, there is no hint,I wonder if users should be informed of this change，Thanks

**Comment by AlbumenJ** [comment]
> When our system is upgraded from alibaba dubbo 2.6.X to 2.7.X/3.X, when we use ReferenceConfig and find registryConfig.setCluster(ClusterRules.BROADCAST), we find that broadcast is supported in version 2.6.X to services on other servers. However, when upgrading to 2.7.X/3.X, the service cannot broadcast.
> 
> 2.6.X code is as follows
> 
> ```
> ReferenceConfig<CacheService> reference = new ReferenceConfig<>();
> RegistryConfig registryConfig = new RegistryConfig("zookeeper地址");
> **registryConfig.setCluster(ClusterRules.BROADCAST);**
> reference.setRegistry(registryConfig); 
> //设置ApplicationConfig
> reference.setApplication(application);
> reference.setInterface(CacheSyncService.class);
> 
> CacheService service = reference.get();
> 
> service.update();
> ```
> 
> 2.7.X/3.X code is as follows
> 
> ```
> ReferenceConfig<CacheService> reference = new ReferenceConfig<>();
> RegistryConfig registryConfig = new RegistryConfig("zookeeper地址");
> reference.setRegistry(registryConfig); 
> //设置ApplicationConfig
> reference.setApplication(application);
> reference.setInterface(CacheSyncService.class);
> **reference.setCluster(ClusterRules.BROADCAST);**
> 
> CacheService service = reference.get();
> 
> service.update();
> ```
> 
> But in the official documentation, there is no hint,I wonder if users should be informed of this change，Thanks

Please re-submit a new one

**Comment by wcy666103** [comment]
I experimented in the way you said, and the results of 2.x and 3.x were correct. I will add some test cases about cluster to the samples repository

**Comment by nuoqin** [comment]
Sorry I resubmitted this issue to a new one, it has the test code I just wrote, the problem is from version 2.7.6 to version 2.7.23 3.0.X, the code has not changed in any way, there are detailed screenshots in it, if you have time, you can take a look, thank you。
https://github.com/apache/dubbo/issues/14280
