### ISSUE TITLE
[Feature] Websocket Support For Triple Protocol

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14298]
### Background

The Triple protocol is based on HTTP/2 and implements bidirectional communication using streams. WebSocket's long connection and event features are very suitable for RPC scenarios, so we consider using WebSocket as the communication layer for Triple, giving users more options.

In terms of specific implementation, we do not want to change the existing Triple protocol but rather adapt the Triple frame model to WebSocket frames. This can be done by referencing the approach used in HTTP/3.

### Next Step
high-level design

**Comment by oxsean** [comment]
If you are interested in this, please leave a message to participate. However, implementing a new communication layer is quite challenging, so it is best if you have extensive experience with Netty

**Comment by finefuture** [comment]
I'm interested. Please assign it to me.

**Comment by blueuuufish** [comment]
I am also very interested in this, but I see that it has already been assigned to someone else. May I have a try?

**Comment by finefuture** [comment]
Adapt the websocket frames model to the http2 frames, reuse the request processing flow of http2.
![websocket on triple—Netty](https://github.com/apache/dubbo/assets/18413695/7031133d-a232-4258-86e8-d209c71b3f45)

Extend the Endpoint and MessageHandler of javax.websocket, adapt the websocket on netty request processing model.
![websocket on triple—javax websocket](https://github.com/apache/dubbo/assets/18413695/08a655e3-044a-4f00-b75f-cc9d9e801d84)
