### ISSUE TITLE
[Feature] Why RedisMetaDataReport not reuse JedisCluster

### ISSUE THREAD

**Issue by CycleMaker** [apache/dubbo#14316]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

https://github.com/apache/dubbo/blob/7cf5fe42f2c92a33cf5d0f973fcb021f21fe7f05/dubbo-metadata/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java#L212-L221
I wonder why not reuse JedisCluster,Is there anything I haven't considered？

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Metadata related opetations are in low frequency and we are no need to maintain a connection with redis.

**Comment by CycleMaker** [comment]
i see
