### ISSUE TITLE
[Bug] Dubbo 3.2.11 , use dual registries（ZK+Nacos），provider defined timeout expires（consumer no timeout specified）

### ISSUE THREAD

**Issue by mrwangyin** [apache/dubbo#14335]
### consumer configuration：
spring.application.name=dubbo-springboot-demo-consumer
server.port=9999
dubbo.application.name=${spring.application.name}
dubbo.protocol.name=dubbo
dubbo.protocol.host=172.16.1.16
dubbo.protocol.port=20888

dubbo.registries.nacos-registry.address=nacos://10.10.10.203:8848?username=nacos&password=nacos
dubbo.registries.nacos-registry.default=true
dubbo.registries.nacos-registry.timeout=11000
dubbo.registries.nacos-registry.use-as-config-center=false
dubbo.registries.nacos-registry.use-as-metadata-center=false
dubbo.registries.nacos-registry.parameters.namespace=dubbo_timeout
#dubbo.registries.nacos.parameters.group=registry-center
dubbo.registries.nacos-registry.register-mode=instance
dubbo.registries.nacos-registry.parameters.register-consumer-url=true
dubbo.registries.zk-registry.preferred=true

dubbo.registries.zk-registry.address=zookeeper://127.0.0.1:2181
dubbo.registries.zk-registry.default=true
dubbo.registries.zk-registry.timeout=8000
dubbo.registries.zk-registry.use-as-config-center=false
dubbo.registries.zk-registry.use-as-metadata-center=false
dubbo.registries.zk-registry.register-mode=instance

dubbo.config-centers.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.config-centers.zk-registry.timeout=13000

dubbo.config-centers.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.config-centers.nacos-registry.timeout=14000
dubbo.config-centers.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.config-centers.nacos-registry.parameters.group=config-center

dubbo.metadata-reports.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.metadata-reports.zk-registry.timeout=15000

dubbo.metadata-reports.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.metadata-reports.nacos-registry.timeout=16000
dubbo.metadata-reports.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.metadata-reports.nacos-registry.parameters.group=metadata-center

### provider configuration：
spring.application.name=dubbo-springboot-demo-provider
server.port=8888
dubbo.application.name=${spring.application.name}
dubbo.protocol.name=dubbo
dubbo.protocol.host=172.16.1.16
dubbo.protocol.port=20889

dubbo.registries.nacos-registry.address=nacos://10.10.10.203:8848?username=nacos&password=nacos
dubbo.registries.nacos-registry.default=true
dubbo.registries.nacos-registry.timeout=11000
dubbo.registries.nacos-registry.use-as-config-center=false
dubbo.registries.nacos-registry.use-as-metadata-center=false
dubbo.registries.nacos-registry.parameters.namespace=dubbo_timeout
#dubbo.registries.nacos.parameters.group=registry-center
dubbo.registries.nacos-registry.register-mode=instance
dubbo.registries.nacos-registry.parameters.register-consumer-url=true
dubbo.registries.zk-registry.preferred=true

dubbo.registries.zk-registry.address=zookeeper://127.0.0.1:2181
dubbo.registries.zk-registry.default=true
dubbo.registries.zk-registry.timeout=9000
dubbo.registries.zk-registry.use-as-config-center=false
dubbo.registries.zk-registry.use-as-metadata-center=false
dubbo.registries.zk-registry.register-mode=instance

dubbo.config-centers.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.config-centers.zk-registry.timeout=13000

dubbo.config-centers.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.config-centers.nacos-registry.timeout=14000
dubbo.config-centers.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.config-centers.nacos-registry.parameters.group=config-center

dubbo.metadata-reports.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.metadata-reports.zk-registry.timeout=15000

dubbo.metadata-reports.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.metadata-reports.nacos-registry.timeout=16000
dubbo.metadata-reports.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.metadata-reports.nacos-registry.parameters.group=metadata-center

## When the app initializes invoker，DEBUG will enter the code block below：
![image](https://github.com/apache/dubbo/assets/44059656/38121efe-287a-402a-90e4-64b63956098e)

### provider timeout for configuration：
![image](https://github.com/apache/dubbo/assets/44059656/904b5afa-687a-44a0-a48a-863b30e8c9c6)

### consumer no timeout configured
![image](https://github.com/apache/dubbo/assets/44059656/eb185d16-7cdb-40d3-9a9b-a2104cf1693a)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by mrwangyin** [comment]
consumer侧配置：

spring.application.name=dubbo-springboot-demo-consumer
server.port=9999
dubbo.application.name=${spring.application.name}
dubbo.protocol.name=dubbo
dubbo.protocol.host=172.16.1.16
dubbo.protocol.port=20888

dubbo.registries.nacos-registry.address=nacos://10.10.10.203:8848?username=nacos&password=nacos
dubbo.registries.nacos-registry.default=true
dubbo.registries.nacos-registry.timeout=11000
dubbo.registries.nacos-registry.use-as-config-center=false
dubbo.registries.nacos-registry.use-as-metadata-center=false
dubbo.registries.nacos-registry.parameters.namespace=dubbo_timeout
#dubbo.registries.nacos.parameters.group=registry-center
dubbo.registries.nacos-registry.register-mode=instance

dubbo.registries.nacos-registry.parameters.register-consumer-url=true

dubbo.registries.zk-registry.preferred=true

dubbo.registries.zk-registry.address=zookeeper://127.0.0.1:2181
dubbo.registries.zk-registry.default=true
dubbo.registries.zk-registry.timeout=8000
dubbo.registries.zk-registry.use-as-config-center=false
dubbo.registries.zk-registry.use-as-metadata-center=false
dubbo.registries.zk-registry.register-mode=instance

dubbo.config-centers.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.config-centers.zk-registry.timeout=13000

dubbo.config-centers.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.config-centers.nacos-registry.timeout=14000
dubbo.config-centers.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.config-centers.nacos-registry.parameters.group=config-center

dubbo.metadata-reports.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.metadata-reports.zk-registry.timeout=15000

dubbo.metadata-reports.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.metadata-reports.nacos-registry.timeout=16000
dubbo.metadata-reports.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.metadata-reports.nacos-registry.parameters.group=metadata-center

**Comment by mrwangyin** [comment]
provider侧配置：
spring.application.name=dubbo-springboot-demo-provider
server.port=9999
dubbo.application.name=${spring.application.name}
dubbo.protocol.name=dubbo
dubbo.protocol.host=172.16.1.16
dubbo.protocol.port=20889


dubbo.registries.nacos-registry.address=nacos://10.10.10.203:8848?username=nacos&password=nacos
dubbo.registries.nacos-registry.default=true
dubbo.registries.nacos-registry.timeout=11000
dubbo.registries.nacos-registry.use-as-config-center=false
dubbo.registries.nacos-registry.use-as-metadata-center=false
dubbo.registries.nacos-registry.parameters.namespace=dubbo_timeout
dubbo.registries.nacos-registry.register-mode=instance
dubbo.registries.nacos-registry.parameters.register-consumer-url=true
dubbo.registries.zk-registry.preferred=true

dubbo.registries.zk-registry.address=zookeeper://127.0.0.1:2181
dubbo.registries.zk-registry.default=true
dubbo.registries.zk-registry.timeout=9000
dubbo.registries.zk-registry.use-as-config-center=false
dubbo.registries.zk-registry.use-as-metadata-center=false
dubbo.registries.zk-registry.register-mode=instance


dubbo.config-centers.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.config-centers.zk-registry.timeout=13000

dubbo.config-centers.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.config-centers.nacos-registry.timeout=14000
dubbo.config-centers.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.config-centers.nacos-registry.parameters.group=config-center

dubbo.metadata-reports.zk-registry.address=${dubbo.registries.zk-registry.address}
dubbo.metadata-reports.zk-registry.timeout=15000

dubbo.metadata-reports.nacos-registry.address=${dubbo.registries.nacos-registry.address}
dubbo.metadata-reports.nacos-registry.timeout=16000
dubbo.metadata-reports.nacos-registry.parameters.namespace=${dubbo.registries.nacos-registry.parameters.namespace}
dubbo.metadata-reports.nacos-registry.parameters.group=metadata-center

**Comment by mrwangyin** [comment]
![image](https://github.com/apache/dubbo/assets/44059656/77810db2-a931-4f19-b181-95fa3cd2d5dc)

**Comment by AlbumenJ** [comment]
Please submit the issue in English only:)

**Comment by mrwangyin** [comment]
> Please submit the issue in English only:)

翻译了一下，请谅解 :)

**Comment by AlbumenJ** [comment]
Please submit a new one
