### ISSUE TITLE
[Feature] HTTP version negotiation on the consumer side for HTTP/3

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14353]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

In order to support HTTP/2 transparent upgrade to HTTP/3, we need to then client version negotiation,

### approximate proposal:
The client can first create a HTTP/2 client, and then try to send a HEAD request, if the server responds Alt-Svc support for HTTP/3 HTTP/3 client will be created, the new stream request sent to the new client.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by blueuuufish** [comment]
I am interested in it,Could you assgin me please?

**Comment by wcy666103** [comment]
> I am interested in it,Could you assgin me please?

Just go ahead
