### ISSUE TITLE
[Feature] Integration testing and Example for HTTP/3

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14354]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

It is recommended that the original HTTP/2 triple related Integration testing and Example be modified to add support for HTTP/3.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
I am interested in it,Could you assgin me please?

**Comment by oxsean** [comment]
Example done
https://github.com/apache/dubbo-samples/pull/1177
