### ISSUE TITLE
[Bug] Fastjson2:2.0.51中JSONB存在漏洞

### ISSUE THREAD

**Issue by ywzou** [apache/dubbo#14378]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.2.14

### Steps to reproduce this issue

Fastjson2:2.0.51中JSONB在自定义一下字段序列化、反序列化规则，自定义时间格式的情况均失败

### What you expected to happen

Fastjson2:2.0.51中JSONB在自定义一下字段序列化、反序列化规则，自定义时间格式的情况反序列化异常均失败

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
please use English and re-submit issue

**Comment by wcy666103** [comment]
Notice that you've filed an issue in fastjson https://github.com/alibaba/fastjson2/issues/2752
