### ISSUE TITLE
[Bug] dubbo 3.2.10反序列问题

### ISSUE THREAD

**Issue by huanyang001** [apache/dubbo#14425]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dobbo 版本 3.2.10
jdk版本 1.8

### Steps to reproduce this issue

参数丢失

### What you expected to happen

序列化方式为fastjson2,provider端参数反序列化会导致参数类型为ArrayList的数据丢失
消费者调用服务,入参为
[{"boost":1.0,"commonTerm":false,"existTerm":false,"firstValue":0,"includeLower":true,"includeUpper":false,"isNested":false,"must":true,"name":"supplierLevel","nested":false,"rangeTerm":true,"secondValue":6,"termEnum":"RANGE","value":0,"values":[0,6]},{"boost":1.0,"commonTerm":false,"existTerm":false,"firstValue":0,"includeLower":true,"includeUpper":false,"isNested":false,"must":true,"name":"supplierLevel","nested":false,"rangeTerm":true,"secondValue":5,"termEnum":"RANGE","value":0,"values":[0,5]}]
提供者接收到的参数
[{"boost":1.0,"commonTerm":false,"existTerm":false,"firstValue":0,"includeLower":true,"includeUpper":false,"isNested":false,"must":true,"name":"supplierLevel","nested":false,"rangeTerm":true,"secondValue":6,"termEnum":"RANGE","value":0,"values":[0,6]},{"boost":1.0,"commonTerm":false,"existTerm":false,"firstValue":0,"includeLower":true,"includeUpper":false,"isNested":false,"must":true,"name":"supplierLevel","nested":false,"rangeTerm":true,"termEnum":"RANGE","value":0,"values":[0]}],

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please re-submit in english only.

**Comment by wcy666103** [comment]
Have you ever tried using the fastjson2 package to serialize your arguments directly?

If this is also the case with direct use, please file an issue directly in the fastjson2 repository https://github.com/alibaba/fastjson2

**Comment by AlbumenJ** [comment]
Please submit the issue in English only:)
