### ISSUE TITLE
[Feature] execute dubbo-compiler plugin failed

### ISSUE THREAD

**Issue by 2277509846** [apache/dubbo#14453]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

I followed https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/quick-start/idl/ The provided method is to configure the protobuf Maven plugin, but when I execute "mvn install", an error message "PROTOC FAILED: -- dubbo_ot: protoc gen dubbo: Plugin failed with status code 1" appears without specifying the reason. There is no problem with the proto file

<build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.6.2</version>
      </extension>
    </extensions>
    <plugins>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <version>0.6.1</version>
        <configuration>
          <protocArtifact>com.google.protobuf:protoc:3.12.0:exe:${os.detected.classifier}</protocArtifact>
          <pluginId>grpc-java</pluginId>
          <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.32.1:exe:${os.detected.classifier}</pluginArtifact>
          <clearOutputDirectory>false</clearOutputDirectory>
          <protocPlugins>
            <protocPlugin>
              <id>dubbo</id>
              <groupId>org.apache.dubbo</groupId>
              <artifactId>dubbo-compiler</artifactId>
              <version>3.0.9</version>
              <mainClass>org.apache.dubbo.gen.tri.Dubbo3TripleGenerator</mainClass>
            </protocPlugin>
          </protocPlugins>
          <protoSourceRoot>src/main/proto</protoSourceRoot>
          <outputDirectory>src/main/java</outputDirectory>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
You can follow the link in the doc directly to the official example.

**Comment by 2277509846** [comment]
I cloned the project "git@github.com:apache/dubbo-samples.git", but when I execute the "mvn package" command in protocol sub, an error occurs when I run the dubbo-samples-triple or dubbo-samples-triple-reactor modules. Simply remove these two modules from pom.xml to build success. Built successfully on Linux operating system, but failed on Windows operating system. Here are the errors prompted by the idea tool:

```
[INFO] 
[INFO] --- protobuf:0.6.1:compile (default) @ dubbo-samples-triple ---
[INFO] Building protoc plugin: dubbo
[INFO] Compiling 1 proto file(s) to D:\dubbo-samples\3-extensions\protocol\dubbo-samples-triple\target\generated-sources\protobuf\java
[ERROR] PROTOC FAILED: --dubbo_out: protoc-gen-dubbo: Plugin failed with status code 1.
[ERROR] D:\dubbo-samples\3-extensions\protocol\dubbo-samples-triple\src\main\proto\greeter.proto [0:0]: --dubbo_out: protoc-gen-dubbo: Plugin failed with status code 1.
protoc did not exit cleanly. Review output for more information.
```
