### ISSUE TITLE
[Feature] Move excludeAttachmentsSet to ContextFilter

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo#14481]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

![image](https://github.com/user-attachments/assets/49b332c1-9bb7-426b-a4a6-8629b42d4fea)

Support get these header in attachment

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please assign it to me

**Comment by oxsean** [comment]
The global configuration above needs to be keeping.

**Comment by oxsean** [comment]
Done in  https://github.com/apache/dubbo/pull/14644
