### ISSUE TITLE
[Feature] Document Defects Difficult to Get Started

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#14486]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

The documents are all tutorials written from an xml perspective, but now they are basically configured with springboot integration using annotations. Beginners are developed with annotations. As a result, the documents are all written in xml, which is difficult to start.

It is hoped that the official documents can provide usage methods from the perspective of annotations.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
The new documentation design is already in the works and should accompany the official release of dubbo3.3.

**Comment by JavaLionLi** [comment]
> The new documentation design is already in the works and should accompany the official release of dubbo3.3.

Thank you. I'm looking forward to it

**Comment by JavaLionLi** [comment]
> The new documentation design is already in the works and should accompany the official release of dubbo3.3.

I hope to help everyone get started faster and integrate with practical use

**Comment by wcy666103** [comment]
> > The new documentation design is already in the works and should accompany the official release of dubbo3.3.
> 
> I hope to help everyone get started faster and integrate with practical use

We also look forward to your participation to help us improve the documentation.

**Comment by JavaLionLi** [comment]
> > > The new documentation design is already in the works and should accompany the official release of dubbo3.3.
> > 
> > 
> > I hope to help everyone get started faster and integrate with practical use
> 
> We also look forward to your participation to help us improve the documentation.

Is there a place to preview the new version of the document?

**Comment by oxsean** [comment]
It's good to google before asking questions, or at least look up the official website
https://dubbo.apache.org/en/docs3-v2/java-sdk/quick-start/spring-boot/
https://dubbo.apache.org/zh-cn/overview/quickstart/java/spring-boot/

**Comment by wcy666103** [comment]
> > > > The new documentation design is already in the works and should accompany the official release of dubbo3.3.
> > > 
> > > 
> > > I hope to help everyone get started faster and integrate with practical use
> > 
> > 
> > We also look forward to your participation to help us improve the documentation.
> 
> Is there a place to preview the new version of the document?

https://dubbo-next.staged.apache.org
