### ISSUE TITLE
Consumer和Provider为同一服务时，seata的xid丢失问题

### ISSUE THREAD

**Issue by Alleninggx** [apache/dubbo#14485]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.2
seata 2.0..0
dubbo-filter-seata 1.0.2

seata and dubbo-filter-seata relies on spring-cloud-alibaba-bom

### Steps to reproduce this issue

```java
@Override
@GlobalTransactional
public boolean edit() throws BizException {
    System.err.println("xid " + RootContext.getXID());  // xid = 123
    Dept dept = deptDubbo.getById(id);                      // deptDubbo and the current class are in the same service
    System.err.println("xid " + RootContext.getXID());  // xid = null
}
```
当在全局事务中，调用一个来自本服务的一个Dubbo接口时，会使RootContext中的xid丢失（仅RootContext的xid丢失了，DefaultGlobalTransaction中并没有）

When a Dubbo interface from this service is called in a global transaction, the xid in the RootContext is lost (only the xid of the RootContext is lost, not DefaultGlobalTransaction).

---

我在Dubbo Filter中，结合多个Consumer验证了这个结论：
I tested this conclusion in the Dubbo Filter with multiple consumers:

```
@Activate(group = CommonConstants.CONSUMER)
public class DubboConsumerContextFilter implements Filter {

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        System.out.println(RootContext.getXID());   // xid = 123
        Result result = invoker.invoke(invocation);
        System.out.println(RootContext.getXID());   // xid = null
        return result;
    }

}
```

### What you expected to happen

我觉得应该是`SeataTransactionPropagationProviderFilter`的问题，它的作用是把消费端的xid设置到服务端的RootContext中，结束后它有一步是在结束调用后解绑，但是因为Consumer和Provider都是同一个服务，所以RootContext也是同一个，导致了解绑时把Consumer的xid解绑了。

I think should be `SeataTransactionPropagationProviderFilter` problem, its role is to set in the server RootContext xid on the consumption side, after the end of it is a step in the end the call after the unbundling, However, since both Consumer and Provider are the same service, the RootContext is also the same, resulting in the untying of the xid of the Consumer.

![image](https://github.com/user-attachments/assets/5a2ca346-1b91-46f5-b588-cc32f51de9bf)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please re-submit this pr in english only.

**Comment by Alleninggx** [comment]
![image](https://github.com/user-attachments/assets/1b5ad264-ae89-441d-a1d5-b882fad8fad3)

@laywin 据我所知  [scope=Injvm不支持 Streaming](https://github.com/apache/dubbo/issues/12377)，所以trip协议必须设置scope=romote，那么这样修改，是不是不会对trip协议起作用呢？

**Comment by laywin** [comment]
> ![image](https://private-user-images.githubusercontent.com/40049392/354519004-1b5ad264-ae89-441d-a1d5-b882fad8fad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODc2MDIsIm5iZiI6MTcyMjU4NzMwMiwicGF0aCI6Ii80MDA0OTM5Mi8zNTQ1MTkwMDQtMWI1YWQyNjQtYWU4OS00NDFkLWExZDUtYjg4MmZhZDhmYWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxYTMyMjI1ZWIyZmE3MTNlMDgyMjVjMjFkNGVkMDZhMTVkNzY1MTZkY2I0NjQ3YWYyYjRlZDdkYTkwYjViMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xwBtIj02pmiiED-0kW73M6wa6M4_Jp-s6w-QCOnehDY)
> 
> @laywin 据我所知 [scope=Injvm不支持 Streaming](https://github.com/apache/dubbo/issues/12377)，所以trip协议必须设置scope=romote，那么这样修改，是不是不会对trip协议起作用呢？

i think the key is to judge whether the invoke happens in same thread, if so, keep the xid, otherwise remove it,  when in remote scope, it will not in same thread, remove it in provider thread. when call returned client, xid is also there.

**Comment by Alleninggx** [comment]
> i think the key is to judge whether the invoke happens in same thread, if so, keep the xid, otherwise remove it, when in remote scope, it will not in same thread, remove it in provider thread. when call returned client, xid is also there.

Oh, it dawned on me. Thank you
