### ISSUE TITLE
[Bug] When using the RedisMetadataReport, the subscription fails when the producer is not started and there is no metadata. As a result, after the subsequent producer is started, the consumer cannot find the metadata information corresponding to the producer and report an error.

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#14501]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.2.14

### Steps to reproduce this issue

When using the RedisMetadataReport, the subscription fails when the producer is not started and there is no metadata. As a result, after the subsequent producer is started, the consumer cannot find the metadata information corresponding to the producer and report an error.

```
"Failed to invoke the method queryByClientId in the service org.dromara.system.api.RemoteClientService. No provider available for the service org.dromara.system.api.RemoteClientService from registry ServiceDiscoveryRegistryDirectory(registry: 192.168.3.9:8848, subscribed key: org.dromara.system.api.RemoteClientService)-Directory(invokers: 0[], validInvokers: 0[], invokersToReconnect: 0[]) on the consumer 192.168.3.9 using the dubbo version 3.2.14. Please check if the providers have been started and registered.
```

If the producer is started first and the consumer is started later, there will be no such problem.

### What you expected to happen

You can re-subscribe to metadata after the producer goes online, or you can simply report an error to prevent the startup, depending on the community's choice.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JavaLionLi** [comment]
In the nacos metadata plug-in, I remember that if there is no metadata, it will report a warning and then subscribe repeatedly until it succeeds.

**Comment by wcy666103** [comment]
The latest implementation (dubbo 3.3) has moved here https://github.com/apache/dubbo-spi-extensions

**Comment by JavaLionLi** [comment]
> The latest implementation (dubbo 3.3) has moved here https://github.com/apache/dubbo-spi-extensions

I copied it from here.
What I want to say is that he has a problem. Please look at my description carefully.

**Comment by JavaLionLi** [comment]
At present, a problem has also been found, that is, producer metadata has ttl
Once the ttl expires, the data will expire, resulting in the loss of metadata, resulting in the consumer can not find the producer metadata to report an error.

**Comment by JavaLionLi** [comment]
At present, what I can do is to change ttl to -1 to solve this problem.

**Comment by JavaLionLi** [comment]
![image](https://github.com/user-attachments/assets/6976d251-5fea-4d4b-a450-2025d1d68f04)
Consumers subscribe to producer metadata, which will report an error once it expires.
