### ISSUE TITLE
[Feature] Remove invalid parameters <org.apache.dubbo.rpc.protocol.tri.stream>

### ISSUE THREAD

**Issue by cnzakii** [apache/dubbo#14506]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

The `eos` parameter in the `sendMessage` method of the `org.apache.dubbo.rpc.protocol.tri.stream.ClientStream` interface is not used in any implementation of the method, and its intended functionality is entirely replaced by the `halfClose` method of the same interface. Therefore, this parameter is redundant and can be removed.

![2024-08-09_16 30 53](https://github.com/user-attachments/assets/05262b06-17fa-4501-ac6d-42ae5cf4957a)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
If it has been resolved, please close the issue~
