### ISSUE TITLE
Getting exception - Caused by: java.lang.IllegalStateException: fail to create adaptive instance: java.lang.IllegalStateException: 

### ISSUE THREAD

**Issue by milindk740** [apache/dubbo#1452]
I am trying to integrate dubbo into the application. I have written a simple client class 

`

import com.alibaba.dubbo.config.ApplicationConfig;
import com.alibaba.dubbo.config.ReferenceConfig;
import com.alibaba.dubbo.config.RegistryConfig;
import org.apache.log4j.Logger;

public class DubboFactory {

  private static final Logger logger = Logger.getLogger(DubboFactory.class);
  public DubboCry createInstance () {
    ApplicationConfig application = new ApplicationConfig();
    application.setName("demo-consumer");
    application.setVersion("1.0.0");
    RegistryConfig registryConfig = new RegistryConfig();
    registryConfig.setAddress("zookeeper://XXX.XX.me:2181");
    ReferenceConfig<DubboCry> reference = new ReferenceConfig<>();
    reference.setApplication(application);
    reference.setRegistry(registryConfig);
    reference.setVersion("1.0.0");
    reference.setInterface(DubboCry.class);
    return reference.get();
  }

`

Following is the pom.xml 
`

    
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-log4j12</artifactId>
        <version>1.7.25</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>dubbo</artifactId>
        <version>2.5.9</version>
    </dependency>

    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-core</artifactId>
        <version>2.6.4</version>
    </dependency>

</dependencies>
`

I am getting following exception. 

> Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.demo.cry.DubboCryFactory.createInstance(DubboCryFactory.java:55)
	at com.demo.cry.DubboRPCTest.main(DubboRPCTest.java:26)
Caused by: java.lang.IllegalStateException: fail to create adaptive instance: java.lang.IllegalStateException: Can not create adaptive extension interface com.alibaba.dubbo.common.extension.ExtensionFactory, cause: No adaptive method on extension com.alibaba.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:447)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.<init>(ExtensionLoader.java:98)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtensionLoader(ExtensionLoader.java:119)
	at com.alibaba.dubbo.config.ReferenceConfig.<clinit>(ReferenceConfig.java:67)

I am unable to understand what is going wrong. Can anyone guide me through this.

**Comment by chickenlj** [comment]
> ava.lang.IllegalStateException: Can not create adaptive extension interface com.alibaba.dubbo.common.extension.ExtensionFactory, cause: No adaptive method on extension com.alibaba.dubbo.common.extension.ExtensionFactory, refuse to create the adaptive class!

By default, dubbo provides a default adaptive implementation `AdaptiveExtensionFactory`, so adaptive implementation should be created at runtime. Maybe `AdaptiveExtensionFactory` can not be loaded properly, do you use a customized classloader hierarchy in you project? Or you can show me your example.

**Comment by chickenlj** [comment]
Would you please send an email to dev@dubbo.apache.org? I think we can get more in-depth and more valuable advices there.

**Comment by weijianghui** [comment]
Has this problem been solved? Give me some ideas.
