### ISSUE TITLE
protocol线程池参数配置无效

### ISSUE THREAD

**Issue by jiang017** [apache/dubbo#14531]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo version: 3.1.8
Operating System version:Windows 10
Java version: 1.8
Spring Boot: 2.1.18

### Steps to reproduce this issue

如下图所示：
当添加如下线程池配置时，均未生效，线程池依旧是CachedThreadPool。

dubbo.protocol.threadpool: fixed
dubbo.protocol.threads: 102
dubbo.protocol.corethreads: 11
![image](https://github.com/user-attachments/assets/f358b277-c2e2-4788-8a25-da57a1336603)

跟踪参数链路发现，在ConfigurableMetadataServiceExporter#buildServiceConfig进行了默认参数设置，最终导致配置失效。

为了使得上述配置生效，项目当前路径导入ConfigurableMetadataServiceExporter并重写buildServiceConfig方法。

对以下代码进行注释，线程池参数 及 类型，均正确，达到预期。

位置：ConfigurableMetadataServiceExporter#buildServiceConfig

``` java
threadParams.put(THREADPOOL_KEY, "cached");
threadParams.put(THREADS_KEY, "100");
threadParams.put(CORE_THREADS_KEY, "2");
```
![image](https://github.com/user-attachments/assets/98b84259-6c94-4f35-aee4-f419b4c40782)

### What you expected to happen

希望通过其它方式让线程池配置dubbo.protocol.threadpool 及 dubbo.protocol.threads 生效，而非以上代码重写（注释）的方式。

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
Hello, welcome to the dubbo community, please describe your problem in English

**Comment by funky-eyes** [comment]
Did you create a `ProtocolConfig` bean yourself, or are you not using `dubbo-spring-boot-starter` at all?

**Comment by jiang017** [comment]
> 你是自己创造了一个豆子，还是你根本没有使用？`ProtocolConfig``dubbo-spring-boot-starter`
> 
> 你是自己创造了一个豆子，还是你根本没有使用？`ProtocolConfig``dubbo-spring-boot-starter`

I used dubbo spring boot starter with version 3.1.8 and have not made any custom beans for ProtocolConfig

**Comment by jiang017** [comment]
> Did you create a `ProtocolConfig` bean yourself, or are you not using `dubbo-spring-boot-starter` at all?

I used dubbo spring boot starter with version 3.1.8 and have not made any custom beans for ProtocolConfig

**Comment by jiang017** [comment]
> > Did you create a `ProtocolConfig` bean yourself, or are you not using `dubbo-spring-boot-starter` at all?
> 
> I used dubbo spring boot starter with version 3.1.8 and have not made any custom beans for ProtocolConfig

I feel it's strange. As long as I delete the configuration of ConfigurableMetadataServiceExporter#buildServiceConfig-threadParams, everything will become normal and parameter dubbo.protocol.threads will take effect

**Comment by laywin** [comment]
In version 3.1.8, metadata export uses the internal cached thread pool configuration. Application-level service export uses your own thread pool configuration.

**Comment by AlbumenJ** [comment]
1. Please try on the latest version (3.2.x)
2. Please re-submit the issue in English if you still have any question.
