### ISSUE TITLE
[Bug] Using a higher version of fury in dubbo-serialization-fury will result in an error 'Fail to decode request due to RpcInvocation'. Currently, it is known that fury versions 0.4.1 and above will experience this issue

### ISSUE THREAD

**Issue by yunshen-Lee** [apache/dubbo#14536]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SPI Extensions (apache/dubbo-spi-extensions)

### Dubbo Version

Dubbo Java 3.2.9,OpenJDK 1.8

### Steps to reproduce this issue

Reproduce with a simple RPC call

### What you expected to happen

error:Fail to decode request due to: RpcInvocation

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
Some time ago, we upgraded fury to version 0.6.0 in dubbo-spi-extensions, does this kind of problem still happen? If so, can you describe it in more detail? If nothing else, I'll be tracking this issue.

**Comment by yunshen-Lee** [comment]
> Some time ago, we upgraded fury to version 0.6.0 in dubbo-spi-extensions, does this kind of problem still happen? If so, can you describe it in more detail? If nothing else, I'll be tracking this issue.

At first, I used the latest official version of Dubbo-serialization-fury, which is 3.3.0 and relies on the 0.2.0 version of Fury, which works properly. Later, I found out that you submitted the latest code to Dubbo-serialization-fury and updated the Fury version to 0.6.0, so I directly used your latest code and reported the above error.

**Comment by heliang666s** [comment]
> > Some time ago, we upgraded fury to version 0.6.0 in dubbo-spi-extensions, does this kind of problem still happen? If so, can you describe it in more detail? If nothing else, I'll be tracking this issue.
> 
> At first, I used the latest official version of Dubbo-serialization-fury, which is 3.3.0 and relies on the 0.2.0 version of Fury, which works properly. Later, I found out that you submitted the latest code to Dubbo-serialization-fury and updated the Fury version to 0.6.0, so I directly used your latest code and reported the above error.

Okay, I'll try to fix this and the bug in the next few days and upgrade the fury to the latest version 0.7.0

**Comment by yunshen-Lee** [comment]
> > > Some time ago, we upgraded fury to version 0.6.0 in dubbo-spi-extensions, does this kind of problem still happen? If so, can you describe it in more detail? If nothing else, I'll be tracking this issue.
> > 
> > 
> > At first, I used the latest official version of Dubbo-serialization-fury, which is 3.3.0 and relies on the 0.2.0 version of Fury, which works properly. Later, I found out that you submitted the latest code to Dubbo-serialization-fury and updated the Fury version to 0.6.0, so I directly used your latest code and reported the above error.
> 
> Okay, I'll try to fix this and the bug in the next few days and upgrade the fury to the latest version 0.7.0

Thank you, I will continue to pay attention.
