### ISSUE TITLE
[Bug] Dubbo 3.3-beta6 NoClassDefFoundError: com/google/protobuf/ProtocolMessageEnum

### ISSUE THREAD

**Issue by heliang666s** [apache/dubbo#14535]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.3-beta6
ubutnu 24.04

### Steps to reproduce this issue

Dubbo 3.3 beta6 now gives the error NoClassDefFoundError: com/google/protobuf/ProtocolMessageAnum when running the sample library, and the protobuf dependency needs to be introduced separately to work properly, but this is not the case in beta 5. In addition, only the Triple protocol is affected, and the Dubbo and Injvm protocols are normal. I'm guessing it's a bit of a problem with the beta6 dependency
![图片](https://github.com/user-attachments/assets/58a1cb67-e3f5-41b7-b361-46afd38ea20b)
![图片](https://github.com/user-attachments/assets/3a21181e-bf90-4980-9afe-74642e4d5c01)

### What you expected to happen

It should be like the beta 5 version, without introducing a protobuf dependency to start normally

### Anything else

No

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by oxsean** [comment]
Fixed in https://github.com/apache/dubbo/pull/14537
