### ISSUE TITLE
[Bug] The QoS command cannot be accessed through telnet

### ISSUE THREAD

**Issue by JinQian1024** [apache/dubbo#14574]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.3.0-beta.6

### Steps to reproduce this issue

I get an error when I use telnet to connect to the qos port and use the command, there was no problem when 3.3.0-beta.4（maybe one or two earlier versions） was used, there was an error when updating the code to beta.6
![image](https://github.com/user-attachments/assets/54897276-cf54-45f3-b1ac-845b7a0fb811)

### What you expected to happen

When I added the refCnt here it worked fine, I wasn't sure if it was due to an incorrect release
![image](https://github.com/user-attachments/assets/875a2aa3-b4e6-46fb-bc5a-dc8974394fce)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
What command do you use?

**Comment by AlbumenJ** [comment]
![image](https://github.com/user-attachments/assets/4946e486-a4e9-48c9-920c-0c3ae525e975)

**Comment by wcy666103** [comment]
@JinQian1024 PTAL

**Comment by AlbumenJ** [comment]
Caused by #13921
