### ISSUE TITLE
[Bug] dubbo springboot项目启动完成后立马调用其他dubbo服务报错

### ISSUE THREAD

**Issue by 949808802** [apache/dubbo#14600]
### Pre-check

- [ ] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

2.7.13

### Steps to reproduce this issue

都是springboot项目
1.b服务正常启动提供服务。
2.a服务启动后在spring的启动完成事件ApplicationReadyEvent中调用b服务，抱错，通过controller 调用，可以调用。

### What you expected to happen

期望在程序启动成功后立马调用其他服务，可以调通

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please re-submit this pr in English Only!

**Comment by wcy666103** [comment]
Can you post the corresponding code in detail?
