### ISSUE TITLE
[Bug] A bean with that name has already been defined and overriding is disabled

### ISSUE THREAD

**Issue by he-jialin2** [apache/dubbo#14617]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.2.15, JDK17, dubbo-spring-boot-observability-starter:3.2.15

### Steps to reproduce this issue

Problems may arise when using two dependency packages at the same time，when tracing mode is turned on, a bug will appear.
dubbo.tracing.enabled=true
implementation("org.apache.dubbo:dubbo-spring-boot-observability-starter:3.2.15")
implementation("org.springframework.boot:spring-boot-actuator-autoconfigure:${springBootVersion}")

spring.main.allow-bean-definition-overriding=true

If the configuration supports bean override injection, no error will be reported.

### What you expected to happen

I hope that the application can be started normally without additional configuration

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
You can submit a pr to try and fix this.

**Comment by he-jialin2** [comment]
#14631
