### ISSUE TITLE
Can it be integrated with Spring Boot Admin, or can it be excluded from monitoring by Spring Boot Admin?

### ISSUE THREAD

**Issue by stoneLee81** [apache/dubbo#14624]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

jdk 21
dubbo 3.2.15
spring boot 3.3.0
spring boot admin 3.3.0

### Steps to reproduce this issue

My project uses Spring Boot Admin to monitor some basic parameters. The project also uses Dubbo, and after starting the project, Spring Boot Admin is monitoring both the project parameters and Dubbo parameters. As a result, in the Spring Boot Admin interface, there are two monitoring instances for the project: one for the project parameters and one for Dubbo monitoring. However, the actuator for Dubbo monitoring is not accessible, which leads to the project not being displayed correctly in the Spring Boot Admin interface.

### What you expected to happen

Does Dubbo support integration with Spring Boot Admin, or can Dubbo be excluded from monitoring in Spring Boot Admin?

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
you can try dubbo-admin,maybe it can work.

**Comment by wcy666103** [comment]
> you can try dubbo-admin,maybe it can work.

dubbo-k8s
