### ISSUE TITLE
[Bug] 3.2.12 The consumer does not automatically reconnect to the triple stream after the provider restarts

### ISSUE THREAD

**Issue by lindonglin** [apache/dubbo#14629]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.2.12,  OpenJDK 17.0.11, MacOS 14.4.1 /  Centos 7.9

### Steps to reproduce this issue

1. Refer to the document ([dubbo triple stream](https://cn.dubbo.apache.org/zh-cn/overview/what/ecosystem/protocol/triple/#stream-%E6%96%B9%E5%BC%8F)) to implement triple stream provider and consumer
2. Start the provider first and then the consumer. Both the provider and the consumer can receive and send messages normally.
3. Restart the provider, and the consumer calls onNext to send a message without any error, but in fact the provider does not receive the corresponding message, and the consumer also does not receive the provider message

### What you expected to happen

When the provider is restarted, the consumer is disconnected from the provider, the channel becomes inactive, and then there is no callback notification (grpc stream will trigger the onError method) to allow the consumer to reconnect manually, and there is no automatic reconnection.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by cnzakii** [comment]
Could you provide your test code along with a description of your specific steps? If possible, it would be helpful to include some logs of any exceptions as well.

**Comment by lindonglin** [comment]
@cnzakii  Hello, the following code can reproduce the phenomenon I described。 After the provider is restarted, the consumer runs normally without error, but the provider does not actually receive the message.

```proto
syntax = "proto3";
option java_multiple_files = true;
option java_package = "com.test.someutil.tri";
option java_outer_classname = "HelloWorldProto";
option objc_class_prefix = "HLW";
package helloworld;
// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}
// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```


```java
public interface IStreamGreeter {

    StreamObserver<HelloRequest> sayHello(StreamObserver<HelloReply> replyObserver);
}
```

```java
public class IStreamGreeterImpl implements IStreamGreeter {

    @Override
    public StreamObserver<HelloRequest> sayHello(StreamObserver<HelloReply> replyObserver) {
        return new StreamObserver<>() {
            @Override
            public void onNext(HelloRequest helloRequest) {
                System.out.println("onNext receive request name:" + helloRequest.getName());
                replyObserver.onNext(HelloReply.newBuilder().setMessage("ok").build());
            }

            @Override
            public void onError(Throwable cause) {
                System.out.println("onError");
                replyObserver.onError(cause);
            }

            @Override
            public void onCompleted() {
                System.out.println("onComplete");
                replyObserver.onCompleted();
            }
        };
    }
}
```

**provider main**
```java
public class DubboTripleStreamProvider {

    public static void main(String[] args) throws InterruptedException {
        ServiceConfig<IStreamGreeter> service = new ServiceConfig<>();
        service.setInterface(IStreamGreeter.class);
        service.setRef(new IStreamGreeterImpl());
        service.setProtocol(new ProtocolConfig(CommonConstants.TRIPLE, 9002));
        service.setApplication(new ApplicationConfig("stream-provider"));
        service.setRegistry(new RegistryConfig("zookeeper://127.0.0.1:2181"));
        service.export();
        System.out.println("dubbo service started");
        new CountDownLatch(1).await();
    }
}
```

**consumer main**
```java
public class DubboTripleStreamConsumer {

    public static void main(String[] args) throws InterruptedException, IOException {
        ReferenceConfig<IStreamGreeter> ref = new ReferenceConfig<>();
        ref.setInterface(IStreamGreeter.class);
        ref.setCheck(false);
        ref.setProtocol(CommonConstants.TRIPLE);
        ref.setLazy(true);
        ref.setTimeout(100000);
        ref.setApplication(new ApplicationConfig("stream-consumer"));
        ref.setUrl("tri://127.0.0.1:9002");
        final IStreamGreeter iStreamGreeter = ref.get();
        System.out.println("dubbo ref started");
        try {
            StreamObserver<HelloRequest> streamObserver = iStreamGreeter.sayHello(new StreamObserver<>() {
                @Override
                public void onNext(HelloReply reply) {
                    System.out.println(reply.getMessage());
                }

                @Override
                public void onError(Throwable throwable) {
                    System.out.println("onError:" + throwable.getMessage());
                }

                @Override
                public void onCompleted() {
                    System.out.println("onCompleted");
                }
            });
            int i = 0;
            while (true) {
                streamObserver.onNext(HelloRequest.newBuilder()
                        .setName("hello " + i++)
                        .build());
                Thread.sleep(5000L);
            }
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
```

**Comment by cnzakii** [comment]
![2024-09-05_22 53 26](https://github.com/user-attachments/assets/e6da4dff-4131-420a-a9a0-909c2e7c00a9)

@lindonglin I can display the exception information here, but I am indeed unable to pass the error information through `onError`. I will consult with relevant experts to further investigate this issue.



Here is my initial assessment for reference:

In version 3.2, `ServerTransportObserver` does not check whether the corresponding header is received in `onData`, meaning it does not verify if it is a valid request.

In the latest version, 3.3.0-beta.5, although this part of the code has been refactored, the corresponding exception handling is still missing.

However, in the latest code of the 3.3 branch, this type of exception handling has been implemented in `AbstractServerTransportListener.onData`. Still, it is currently uncertain whether a correct "error message" is returned to the client (since this is a quick assessment, the issue might not lie here).

![2024-09-05_23 49 59](https://github.com/user-attachments/assets/206e78de-0beb-4d1d-9869-04e3c22faf84)

**Comment by lindonglin** [comment]
@cnzakii Thanks for your help. Here are some of my thoughts:

It seems that TripleClientStream only gets the active channel through CreateStreamQueueCommand the first time.

After the provider is restarted, the original channel becomes inactive. The underlying netty reconnects and generates a new channel, but TripleClientStream still holds the old channel.

Should the streamChannelFuture in TripleClientStream be updated to the latest channel to achieve automatic reconnection of triple stream?

When the consumer starts
![image](https://github.com/user-attachments/assets/51644edf-ff6b-45ca-9a12-0fc54a0aed40)

When the provider restarts
![image](https://github.com/user-attachments/assets/e026604b-d5cb-49f8-a746-d0b06fafbc3b)

After the provider restarts
![20240906-120203](https://github.com/user-attachments/assets/27795dff-5c03-44d8-881c-3adc899dda9e)

**Comment by cnzakii** [comment]
@lindonglin 
That's right, I also identified this issue. Here, it should be replaced with `this.promise.tryFailure(new IllegalStateException("Channel is not active"));`, but this is still a passive response. Currently, a proactive response may be needed to notify the user.

**Comment by lindonglin** [comment]
@cnzakii 
I'll solve this problem temporarily: use provider to actively send heartbeats to consumers through `org.apache.dubbo.common.stream.StreamObserver#onNext`. If consumers don't receive heartbeats for a long time, they think the connection is disconnected and actively initiate reconnection. 

Do you have any plans to fix this or add a proactive response to notify the user.
