### ISSUE TITLE
[Feature] Replacement of WinRun4J and Removal of protobuf-maven-plugin in Dubbo

### ISSUE THREAD

**Issue by oxsean** [apache/dubbo#14623]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

## Requirement Description

The current implementation of the Dubbo Maven Plugin for Windows uses WinRun4J to handle protobuf code generation and JVM startup for request processing. Additionally, Due to licensing constraints, we need to replace WinRun4J functionality with a BAT script solution and remove the dependency on protobuf-maven-plugin(also unfriendly-licensed).

Key points of the requirement:

1. Remove all dependencies and references to WinRun4J from the project.

2. Remove all dependencies and references to protobuf-maven-plugin from the project and example project.

3. Develop a BAT script generator that will:
   - Call by proto.exe  to generate code 
   - Start a JVM to process requests
   - Replicate the functionality currently provided by WinRun4J
   - See https://stackoverflow.com/questions/42444090/how-to-run-a-protobuf-python-plugin-on-windows

4. Modify the `WinDubboProtocPluginWrapper` class to:
   - Generate the BAT script instead of creating a WinRun4J configuration
   - Execute the BAT script instead of the WinRun4J executable

5. Ensure that the new implementation maintains all current functionalities, including:
   - Proper classpath setup
   - Passing of JVM arguments
   - Handling of main class execution
   - Error logging

6. Ensure that the new implementation is compatible with existing Dubbo Maven Plugin configurations and minimizes the need for users to modify their existing setups.

9. Provide clear migration guidelines for users who were previously relying on protobuf-maven-plugin functionality.

These changes will allow us to remove dependencies on both the CPL-licensed WinRun4J and the unfriendly-licensed protobuf-maven-plugin while maintaining the functionality of the Dubbo Maven Plugin for Windows users. The solution should aim to be self-contained within the Dubbo project, reducing external dependencies with licensing issues.

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
I want to solve it.Please assign to me.
