### ISSUE TITLE
[Bug] 多注册中心下，一个注册中心挂了 导致客户端无法调用服务端，报cannot invoker Registry.getUrl Because this.url is null

### ISSUE THREAD

**Issue by huangqy17** [apache/dubbo#14674]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.2.10 jdk21
![单注册多订阅 drawio](https://github.com/user-attachments/assets/6172a651-dc27-495e-8847-095dccc0361a)

### Steps to reproduce this issue

[Bug] 多注册中心下，一个注册中心挂了 导致客户端无法调用服务端，报cannot invoker Registry.getUrl Because this.url is null

### What you expected to happen

[Bug] 多注册中心下，一个注册中心挂了 应正常调用

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please re-submit this pr in English Only.

**Comment by wcy666103** [comment]
Would you be willing to submit a pr to help fix this ?

**Comment by AlbumenJ** [comment]
Please re-submit the issue in English
