### ISSUE TITLE
[Bug] future.sync.set default value error   

### ISSUE THREAD

**Issue by bigbird-0101** [apache/dubbo#14727]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo:latest 

### Steps to reproduce this issue

except: future.sync.set  default value=false
why code default set true ?
this code want to set false ,why? RpcContext.getServiceContext().setFuture(new FutureAdapter<>(asyncResult.getResponseFuture()));  this code  async to do when InvokeMode.ASYNC
```java
if (setFutureWhenSync || invocation.getInvokeMode() != InvokeMode.SYNC) {
            // set server context
            RpcContext.getServiceContext().setFuture(new FutureAdapter<>(asyncResult.getResponseFuture()));
}
```

### What you expected to happen

except:future.sync.set  default value=false
why code default set true ?
this code want to set false ,why? RpcContext.getServiceContext().setFuture(new FutureAdapter<>(asyncResult.getResponseFuture()));  this code  async to do when InvokeMode.ASYNC
```java
 if (setFutureWhenSync || invocation.getInvokeMode() != InvokeMode.SYNC) {
      // set server context
      RpcContext.getServiceContext().setFuture(new FutureAdapter<>(asyncResult.getResponseFuture()));
  }
```

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
To compact to previous version

**Comment by bigbird-0101** [comment]
I see  previous version, it  is also default value = true, but  I understand the default value here should be false

**Comment by AlbumenJ** [comment]
> I see previous version, it is also default value = true, but I understand the default value here should be false

In Dubbo 2.7 or 3.0, there is no way to disable set future by default. In order to prevent memory leak in some scenarios, we support a way to disable it.

**Comment by bigbird-0101** [comment]
Yes, I encountered a memory leak scenario, so I paid attention to this problem. However, the current solution provided by versions after 3.0 is not very good. The future is still set by default. The expectation is that the future is not set, and I saw that paragraph.

The default value expected by the code is false, which means that future is not set to prevent memory leaks.

**Comment by bigbird-0101** [comment]
> > I see previous version, it is also default value = true, but I understand the default value here should be false
> 
> In Dubbo 2.7 or 3.0, there is no way to disable set future by default. In order to prevent memory leak in some scenarios, we support a way to disable it.


Yes, I encountered a memory leak scenario, so I paid attention to this problem. However, the current solution provided by versions after 3.0 is not very good. The future is still set by default. The expectation is that the future is not set, and I saw that paragraph.

The default value expected by the code is false, which means that future is not set to prevent memory leaks.

**Comment by bigbird-0101** [comment]
> > I see previous version, it is also default value = true, but I understand the default value here should be false
> 
> In Dubbo 2.7 or 3.0, there is no way to disable set future by default. In order to prevent memory leak in some scenarios, we support a way to disable it.

this is old code:
```java
    private static final boolean setFutureWhenSync = Boolean.parseBoolean(System.getProperty(CommonConstants.SET_FUTURE_IN_SYNC_MODE, "true"));
```

Except code:
```java
    private static final boolean setFutureWhenSync = Boolean.parseBoolean(System.getProperty(CommonConstants.SET_FUTURE_IN_SYNC_MODE, "false"));
```

**Comment by AlbumenJ** [comment]
We can change it in the next major release and this is a breaking change.

**Comment by bigbird-0101** [comment]
> We can change it in the next major release and this is a breaking change.

Do you need me to submit a PR?

**Comment by AlbumenJ** [comment]
I have created a new branch for `3.4`. You can submit a PR to that~

**Comment by bigbird-0101** [comment]
> I have created a new branch for `3.4`. You can submit a PR to that~

ok

**Comment by bigbird-0101** [comment]
> I have created a new branch for `3.4`. You can submit a PR to that~
PR is commited   [https://github.com/apache/dubbo/pull/14785](https://github.com/apache/dubbo/pull/14785)
