### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by deyongTang** [apache/dubbo#14746]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

java.io.IOException: Len error. A message from /192.168.0.102:2449 with advertised length of 1195725856 is either a malformed message or too large to process (length is greater than jute.maxbuffer=1048575)

	at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:567)

	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:352)

	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508)

	at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:153)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source).

When using Dubbo to register services to Zookeeper, an exception occurred in the Zookeeper logs indicating that the data packet size was too large.

Dubbo should normally register services to Zookeeper, and the size of the data packets sent should be within a reasonable range (usually not exceeding 1MB).

However, Dubbo is sending exceptionally large data packets (over 1GB), which causes Zookeeper to fail to process them and results in service registration failure.

Dubbo version: 3.3.0

### Steps to reproduce this issue

When using Dubbo to register services to Zookeeper, an exception occurred in the Zookeeper logs indicating that the data packet size was too large.

### What you expected to happen

Dubbo should normally register services to Zookeeper, and the size of the data packets sent should be within a reasonable range (usually not exceeding 1MB).

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Can you submit a complete reproduction? Can you help us improve by submitting a pr?
