### ISSUE TITLE
[Bug] dubbo3.2.11 direct connection for test caused error!

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#14758]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.2.11, openjdk17,windows11, instance discovery, tripple protocol

### Steps to reproduce this issue

when i do test direct connect to the provider whith dubbo 3.2.11,and it lead to a error! follow is the screenshot
![图片](https://github.com/user-attachments/assets/6b055ba1-f66b-4fd0-9b9c-cc2275f6cc07)

### What you expected to happen

expect consumer direct connect to the provider help me convenience to test 

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Can you provide a full demo address?

**Comment by zzps** [comment]
> Can you provide a full demo address?

https://gitee.com/755157298/dubbo-tree.git
after clone ,start invoker and servant ,then request by url "http://127.0.0.1:9090/ping/api" and method GET,and you will see 
both in invoker and servant
![图片](https://github.com/user-attachments/assets/ad3cdd6a-b3f3-442f-af30-91e7f0024f7a)

**Comment by AlbumenJ** [comment]
@zzps You can use `@DubboReference(url = "tri://localhost:50051?serialization=fastjson2")` or use `hessian2` instead.

In Dubbo 3.3, we have improved the compability between hessian and JDK17

**Comment by zzps** [comment]
> ?serialization=fastjson2

thank you, it works
