### ISSUE TITLE
[Bug] upgrade to 3.3.1 and start error

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#14762]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo  3.3.1 ,openjdk17,windows11

### Steps to reproduce this issue

here is the demo ,https://gitee.com/755157298/dubbo-tree.git ,  after clone edit the root pom dubbo dependency version to 3.3.1
and  start you will see 
![图片](https://github.com/user-attachments/assets/fd9f06aa-663d-42af-b7d5-b506539d135e)

### What you expected to happen

start success

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo/pull/14763
