### ISSUE TITLE
[Bug] Failed register interface application mapping for service

### ISSUE THREAD

**Issue by eduosi** [apache/dubbo#14764]
### Pre-check

- [ ] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.3.x

### Steps to reproduce this issue

When the registry and metadata center use consul and dubbo.registry.register-mode is instance, the ServiceConfig always prompts: ’Failed register interface application mapping for service'.

### What you expected to happen

org.apache.dubbo.metadata.report.MetadataReport method ` registerServiceAppMapping (String the serviceKey, String application, The URL URL) ` and ` registerServiceAppMapping (String serviceInterface, String defaultMappingGroup, String newConfigContent, Object ticket) 'returns false by default; And the org.apache.dubbo.metadata.store.consul.ConsulMetadataReport does not override the method. Cause MetadataServiceNameMapping. Map URL (URL) will always return false. Eventually, the org.apache.dubbo.config.ServiceConfig mapServiceName will always print this error.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
Please re-submit this pr in english only.
