### ISSUE TITLE
[Bug] sendRedirect 302    failure

### ISSUE THREAD

**Issue by smalltalkhyb** [apache/dubbo#14772]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.3.1

### code
```
    @Override
    public String locationTest(String url) {
//
//        org.apache.dubbo.remoting.http12.message.DefaultHttpResponse httpResponse = (org.apache.dubbo.remoting.http12.message.DefaultHttpResponse)RpcContext.getServiceContext().getResponse();
//
//        httpResponse.setBody("locationTest");
//
//        httpResponse.sendRedirect(url);
//
//        return "locationTest";


        HttpResultPayloadException httpResultPayloadException = new HttpResultPayloadException(HttpResponseStatus.FOUND.code(), "");
        throw new org.apache.dubbo.remoting.http12.exception.HttpResultPayloadException(httpResultPayloadException);

    }
```

### error

http://localhost:8080/http/response/test?url=https://baidu.com

![image](https://github.com/user-attachments/assets/0c66585a-009c-4039-a54f-09b395e8197e)

### What you expected to happen

sendRedirect to    custom  url 

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by oxsean** [comment]
```java
// work fine
throw HttpResult.found("http://www.apache.org").toPayload();

// work fine
throw new HttpResultPayloadException(302, "http://www.apache.org");

// not work, fixed
HttpResponse response = RpcContext.getServiceContext().getResponse(HttpResponse.class);
response.sendRedirect("http://www.apache.org");
```
