### ISSUE TITLE
[Bug] tripple-rest global CORS not support

### ISSUE THREAD

**Issue by stdiogo** [apache/dubbo#14779]
### Pre-check

- [x] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.3.0, OpenJDK17 , Windows 10

### Steps to reproduce this issue

https://cn.dubbo.apache.org/zh-cn/overview/mannual/java-sdk/reference-manual/protocol/tripe-rest-manual/#cors%E9%85%8D%E7%BD%AE-2 

According to the configuration mentioned in the documentation above

![image](https://github.com/user-attachments/assets/8de775e5-47f6-43fa-9795-5a9737b8ea28)
allowed-origins、allowed-methods field in org.apache.dubbo.config.nested.CorsConfig Which are java type of String[] do not take effect, so the dubbo service can not get the corresponding CorsConfig value. But allow-credentials、max-age can take effect。

I reviewed the code of org.apache.dubbo.config.AbstractConfig(the red rectangle)，none of condition can match. So no value will return when class field type is String[] .
![image](https://github.com/user-attachments/assets/6e868afe-1d88-466c-92dd-d99cf46a774c)

Even fix problem above, I think it is not work. Http1UnaryServerChannelObserver rebuild the metadata(Header),so whatever the header is set in Filter, are not send to client.
![image](https://github.com/user-attachments/assets/8c101088-0757-4289-97a9-2f989217aee2)

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
Please translate all the content to English

**Comment by stdiogo** [comment]
> Please translate all the content to English

done
