### ISSUE TITLE
[Bug] in package dubbo-demo，where is the HelloReply and HelloRequest？

### ISSUE THREAD

**Issue by zhangcunli** [apache/dubbo#14782]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.3

### Steps to reproduce this issue

1.see the screenshot:
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/a8a30c0a-c341-40bc-9c92-b3cd59520ce1">

### What you expected to happen

1. I want run the demo: `dubbo-demo/dubbo-demo-triple`
2. But I can't find the package: `org.apache.dubbo.demo.hello.HelloReply` and `org.apache.dubbo.demo.hello.HelloRequest`

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
This is defined in the proto file, and you need to pull the code down to compile it for it to appear, and you can't browse it directly on GitHub. @zhangcunli

**Comment by heliang666s** [comment]
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/e68f8fe2-4761-4100-a023-6309df25c114">
By the way, you can close the issue if you feel your issue has been solved
