### ISSUE TITLE
[Bug]   The Nacos console[serviceManagement] does not display the Dubbo service list

### ISSUE THREAD

**Issue by rickiehsu** [apache/dubbo#14784]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

 Environment:  Dubbo 3.2.16 , Java 17, Centos 7

### Steps to reproduce this issue

1. dubbo.properties

> dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.registry.parameters.namespace=abc
dubbo.registry.group=dubbo
dubbo.registry.username=nacos
dubbo.registry.password=nacos

2. applicationContext.xml
> <dubbo:registry id="dubboRegistryService" address="${dubbo.registry.address}" timeout="${dubbo.registry.timeout}"
                    group="${dubbo.registry.group:dubbo}"
                    username="${dubbo.registry.username:#{null}}"
                    password="${dubbo.registry.password:#{null}}">
        <dubbo:parameter key="max.active" value="50"/>
        <dubbo:parameter key="namespace" value="${dubbo.registry.parameters.namespace}"/>
        <dubbo:parameter key="init.timeout" value="${dubbo.registry.timeout}"/>
    </dubbo:registry>

3. nacos console  Service List
> 
![image](https://github.com/user-attachments/assets/4c8ec534-8db7-455b-837f-f114637a896f)

4.  nacos console  Configuration Management
> 
![image](https://github.com/user-attachments/assets/7b6e7077-66aa-4c65-9e9a-67383f2e5abf)

### What you expected to happen

The Nacos console displays the list of registered services.

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
It looks like you're only configuring registry without explicitly configcenter.

nacos versions are not compatible with each other, make sure the version is correct

Is there a log about registry in the console of dubbo app?

**Comment by rickiehsu** [comment]
namespace is wrong.
