### ISSUE TITLE
[Question] Any body can tell me how to run the demo: dubbo-demo-triple?

### ISSUE THREAD

**Issue by zhangcunli** [apache/dubbo#14783]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo Java 3.3

### Steps to reproduce this issue

1. I have build the dubbo-demo with the command: mvn clean package;

2. But the demo "dubbo-demo-triple" not look like the "dubbo-demo-api-provider",  there is no "dubbo-demo-triple-provider-3.3.2.jar" and "dubbo-demo-triple-consumer-3.3.2.jar" generated.

3.look the sreenshot:
<img width="627" alt="image" src="https://github.com/user-attachments/assets/704d7976-8b75-4767-918c-df6f076b5c29">

### What you expected to happen

Question: 
1. I want to know how to run the demo "dubbo-demo-triple", Thanks!

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
Do you want to start in IDEA？ then run provider and then consumer.If you want to run a jar, because the consumer and provider are packages and not modules, only one jar package will be generated. You can use the Maven Exec plugin pom.xml and use the corresponding command at startup.@zhangcunli
