### ISSUE TITLE
The same Dubbo service cannot be registered under multiple namespaces of one NACOS, but can be registered under different NACOS namespaces

### ISSUE THREAD

**Issue by zhangjunjie007** [apache/dubbo#14790]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Descriptions

This is my configuration:
dubbo:
  registries:
    nacos1:
      id: nacos-dubbo
      address: nacos://192.168.1.11:8848?namespace=dubbo
      register: true
      username: nacos
      password: nacos
    nacos2:
      id: nacos-plm
      address: nacos://192.168.1.11:8848?namespace=plm
      register: true
      username: nacos
      password: nacos

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhangjunjie007** [comment]
My Dubbo version is 3.1.10

**Comment by wcy666103** [comment]
I have tried 3.3.1, 3.2.10 versions and they all work. Can you provide a repository address where this problem can be reproduced?

**Comment by zhangjunjie007** [comment]
> 我试过 3.3.1、3.2.10 版本，都可以。你能提供一个可以重现这个问题的仓库地址吗？



> I have tried 3.3.1, 3.2.10 versions and they all work. Can you provide a repository address where this problem can be reproduced?

Sorry, I read it wrong. My version is 3.1.10  Does this version have this issue？

**Comment by wcy666103** [comment]
> > 我试过 3.3.1、3.2.10 版本，都可以。你能提供一个可以重现这个问题的仓库地址吗？
> 
> > I have tried 3.3.1, 3.2.10 versions and they all work. Can you provide a repository address where this problem can be reproduced?
> 
> Sorry, I read it wrong. My version is 3.1.10 Does this version have this issue？

This problem does exist in versions below 3.2.x, but it is only resolved in versions above 3.2.x, please refer to this pr for details https://github.com/apache/dubbo/pull/12731
https://github.com/apache/dubbo/issues/12629

**Comment by zhangjunjie007** [comment]
> > > 我试过 3.3.1、3.2.10 版本，都可以。你能提供一个可以重现这个问题的仓库地址吗？
> > 
> > 
> > > I have tried 3.3.1, 3.2.10 versions and they all work. Can you provide a repository address where this problem can be reproduced?
> > 
> > 
> > Sorry, I read it wrong. My version is 3.1.10 Does this version have this issue？
> 
> This problem does exist in versions below 3.2.x, but it is only resolved in versions above 3.2.x, please refer to this pr for details #12731 #12629

ok，thankyou
