### ISSUE TITLE
[Feature] GLCC project conclusion assessment

### ISSUE THREAD

**Issue by wcy666103** [apache/dubbo#14823]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar feature requirement.

### Apache Dubbo Component

Java SPI Extensions (apache/dubbo-spi-extensions)

### Descriptions

CCF GitLink Programming Summer Camp (GitLink Code Camp, referred to as GLCC), is sponsored by the China Computer Society (CCF), GitLink community and CCF Open Source Development Committee (CCF ODC) jointly held for the summer open source project internship program for college students across the country.

The title of my project is **Dubbo Kernel traffic rules Improvement & Complete Example writing **. The following link is some of the work I did for the project in dubbo related repositories:

`I will close this issue after the review is completed`

## dubbo-samples repositorie：

broadcast samples：[Add broadcast test by wcy666103](https://github.com/apache/dubbo-samples/pull/1157)

newrouter samples： [Add Condition rule v3.1 test case by wcy666103](https://github.com/apache/dubbo-samples/pull/1186)

## dubbo repositorie

ConditionRouterRulev3.1 : [New condition router v3.1 by wcy666103 ](https://github.com/apache/dubbo/pull/14456)

other： [Condition route v3.1 by wcy666103 ](https://github.com/apache/dubbo/pull/14356)

affinityRouter : [Add Affinity Router by wcy666103 ](https://github.com/apache/dubbo/pull/14787)

xds resource： [Define XDS resources by wcy666103 ](https://github.com/apache/dubbo/pull/14449)

## dubbo-extensions repositorie：

fix broadcast test： [fix-broadcast-test-unit by wcy666103](https://github.com/apache/dubbo-spi-extensions/pull/539)

add broadcast test：[Add cluster-broadcast1 unit test by wcy666103 ](https://github.com/apache/dubbo-spi-extensions/pull/444)

## dubbo-go repositorie:

https://github.com/apache/dubbo-go/pull/2738

## issue

v3.1design：[[Feature\] New Condition route v3.1](https://github.com/apache/dubbo/issues/14455)

design2： [[Feature\] Design and implement new conditional rules V3.1](https://github.com/apache/dubbo/issues/14344)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
