### ISSUE TITLE
[Bug] Cannot be found in the maven central repository org.apache.dubbo.extensions:dubbo-metadata-report-redis

### ISSUE THREAD

**Issue by eduosi** [apache/dubbo#14867]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo SPI Extensions JAVA 3.3.0

### Steps to reproduce this issue

Cannot be found in the maven central repository `<dependency>
<groupId>org.apache.dubbo.extensions</groupId>
<artifactId>dubbo-metadata-report-redis</artifactId>
`

![图片](https://github.com/user-attachments/assets/f1af4309-b9d1-4342-b37f-1b04af375137)

### What you expected to happen

Need to upload org.apache.dubbo.extensions:dubbo-metadata-report-redis to maven central 

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
Hello and thanks for the feedback. But this is not a bug, this is because the latest version of `dubbo-spi-extensions` has not been released yet, and the current version 3.3 has not integrated the redis extension. Our latest version is coming soon, so you can wait. If you need to use it urgently, you can manually compile and package the master branch of `dubbo-spi-extensions` and then use it.@eduosi

**Comment by eduosi** [comment]
> Hello and thanks for the feedback. But this is not a bug, this is because the latest version of `dubbo-spi-extensions` has not been released yet, and the current version 3.3 has not integrated the redis extension. Our latest version is coming soon, so you can wait. If you need to use it urgently, you can manually compile and package the master branch of `dubbo-spi-extensions` and then use it.@eduosi

OK, I understand.
