### ISSUE TITLE
[Bug] consumer invoke provider by http3 start fail

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#14885]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.3.2 , openjdk17, windows11

### Steps to reproduce this issue

refer to [https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-triple-http3/README.md](url)
provider service config like that and use curl test, and it works http3 success.  but use consumer invoke the provider by rpc use http3 the consumer start failed. follow is the image
![1731304976386](https://github.com/user-attachments/assets/1a14c724-185f-425c-8c87-243c16d069ec)
both provider and consumer config as th image
![1731305040854](https://github.com/user-attachments/assets/e5317244-494c-48ea-8341-0a906bdad086)
consumer start failed with the error

### What you expected to happen

consumer invoke provider by rpc use http3 success

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by oxsean** [comment]
Could you please provider a demo?

**Comment by zzps** [comment]
> Could you please provider a demo?

[https://gitee.com/755157298/dubbo-tree.git](url)

**Comment by zzps** [comment]
> Could you please provider a demo?
here is the demo,you can test [[https://gitee.com/755157298/dubbo-tree.git](https://github.com/apache/dubbo/issues/url)](url)

**Comment by oxsean** [comment]
Sorry, this is an http3 negotiation bug that needs to be fixed, you run your demo by modifying the configuration:
```
dubbo.protocol.triple.http3.negotiation=false
```
 to turn off the http3 negotiation, after modified I can run your demo locally.

**Comment by oxsean** [comment]
Fixed in https://github.com/apache/dubbo/pull/14901

**Comment by zzps** [comment]
> Sorry, this is an http3 negotiation bug that needs to be fixed, you run your demo by modifying the configuration:
> 
> ```
> dubbo.protocol.triple.http3.negotiation=false
> ```
> 
> to turn off the http3 negotiation, after modified I can run your demo locally.

so  modify the word 'negotiate' to 'negotiation' ,then run ok?

**Comment by zzps** [comment]
> Sorry, this is an http3 negotiation bug that needs to be fixed, you run your demo by modifying the configuration:
> 
> ```
> dubbo.protocol.triple.http3.negotiation=false
> ```
> 
> to turn off the http3 negotiation, after modified I can run your demo locally.

after i modify the configuration 
dubbo.protocol.triple.http3.negotiate=false
to 
dubbo.protocol.triple.http3.negotiation=false
and  start success,alse i can see the http3 establish.
but the consumer print a schedule error as below image
![1731903235474](https://github.com/user-attachments/assets/69a771c7-3f73-4861-a858-30a7034f17f9)

**Comment by oxsean** [comment]
> > Sorry, this is an http3 negotiation bug that needs to be fixed, you run your demo by modifying the configuration:
> > ```
> > dubbo.protocol.triple.http3.negotiation=false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to turn off the http3 negotiation, after modified I can run your demo locally.
> 
> after i modify the configuration dubbo.protocol.triple.http3.negotiate=false to dubbo.protocol.triple.http3.negotiation=false and start success,alse i can see the http3 establish. but the consumer print a schedule error as below image ![1731903235474](https://private-user-images.githubusercontent.com/33255974/387061224-69a771c7-3f73-4861-a858-30a7034f17f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDQ5MDYsIm5iZiI6MTczMTkwNDYwNiwicGF0aCI6Ii8zMzI1NTk3NC8zODcwNjEyMjQtNjlhNzcxYzctM2Y3My00ODYxLWE4NTgtMzBhNzAzNGYxN2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MzY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwODMyNzY0NGI0NjUzYmQzM2I2NDY3NjRhMTMyNGFiYTg0ZDUwMjg2YTE0ZmRiZjhlYzYwY2ZiMGFiOGZjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G5oyerol4bbCZSHqLDFXp3D8ZJc3mSHqZaQFeukgDF4)

Check provider runing properly.

**Comment by zzps** [comment]
> > > Sorry, this is an http3 negotiation bug that needs to be fixed, you run your demo by modifying the configuration:
> > > ```
> > > dubbo.protocol.triple.http3.negotiation=false
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to turn off the http3 negotiation, after modified I can run your demo locally.
> > 
> > 
> > after i modify the configuration dubbo.protocol.triple.http3.negotiate=false to dubbo.protocol.triple.http3.negotiation=false and start success,alse i can see the http3 establish. but the consumer print a schedule error as below image ![1731903235474](https://private-user-images.githubusercontent.com/33255974/387061224-69a771c7-3f73-4861-a858-30a7034f17f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDQ5MDYsIm5iZiI6MTczMTkwNDYwNiwicGF0aCI6Ii8zMzI1NTk3NC8zODcwNjEyMjQtNjlhNzcxYzctM2Y3My00ODYxLWE4NTgtMzBhNzAzNGYxN2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MzY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwODMyNzY0NGI0NjUzYmQzM2I2NDY3NjRhMTMyNGFiYTg0ZDUwMjg2YTE0ZmRiZjhlYzYwY2ZiMGFiOGZjZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G5oyerol4bbCZSHqLDFXp3D8ZJc3mSHqZaQFeukgDF4)
> 
> Check provider runing properly.

the provider runing properly, the cunsumer runing properly first,and wait about 5 minutes.the consumer will print the error period

**Comment by oxsean** [comment]
Seem h3 Idle process has some problem, need further investigation.

**Comment by zzps** [comment]
> Seem h3 Idle process has some problem, need further investigation.
you can use up demo to see it ,just start and wait few minutes

**Comment by oxsean** [comment]
Fixed in https://github.com/apache/dubbo/pull/14955
