### ISSUE TITLE
[Bug] register-mode parameter in ApplicationConfig is not effective

### ISSUE THREAD

**Issue by aruato** [apache/dubbo#14883]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo 3.3.2

### Steps to reproduce this issue

When configuring **dubbo.application.register-mode=instance** and **dubbo.registry.register-mode=all**, the expected behavior is for the **application** configuration to take precedence. However, the actual behavior is that the **registry** configuration is applied instead

### What you expected to happen

The priority of ApplicationConfig should be higher than that of RegistryConfig

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
The priority of **RegistryConfig** is higher than **ApplicationConfig**
