### ISSUE TITLE
[Bug] The menu on the left side of the new document is compressed too tightly, which is very inconvenient to see, and I hope it can be optimized

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#14894]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.3.3

### Steps to reproduce this issue

The menu on the left side of the new document is compressed too tightly, which is very inconvenient to see, and I hope it can be optimized

![image](https://github.com/user-attachments/assets/f2335fd7-20bb-46ac-95bc-d9a582eb573d)

### What you expected to happen

6

### Anything else

6

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-website/pull/3071
