### ISSUE TITLE
[Bug] 新文档左边菜单能不能优化一下 这个样子也没法看啊

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#14890]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

3.3.0

### Steps to reproduce this issue

![image](https://github.com/user-attachments/assets/aa550ab1-50dc-4cb2-88dd-d0c50782fd43)

### What you expected to happen

6

### Anything else

6

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by heliang666s** [comment]
Hello, please use English thank you. We've received your feedback.@JavaLionLi

**Comment by AlbumenJ** [comment]
Please re-submit the issue in English only :)

**Comment by songxiaosheng** [comment]
I remember I made some changes before, but the latest version has been reverted back. I'll optimize this for you
