### ISSUE TITLE
[Bug] the dependency missing of dubbo-spring-boot.

### ISSUE THREAD

**Issue by lanxi0** [apache/dubbo#14947]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

apache/dubbo 3.3
When running the dubbo-demo-spring-boot-project, it was found that there were missing dependencies, and the IDEA compilation did not pass

### Steps to reproduce this issue

Pull project TAG 3.3.
When running the dubbo-demo-spring-boot-project, it was found that there were missing dependencies, and the IDEA compilation did not pass

### What you expected to happen

I hope the demo project can be successfully executed

### Anything else

![image](https://github.com/user-attachments/assets/dc1de733-0fb7-44cc-9194-32ae95c1c5c4)

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
It looks like a problem with idea, not all maven projects were identified.

**Comment by lanxi0** [comment]
I searched for dependency relationships and it seems that adding a dependency would be better
In order not to affect other dependencies, I set the newly added dependencies not to

**Comment by lanxi0** [comment]
Maven install was successful, but there will be an error when running the demo project directly

**Comment by oxsean** [comment]
I also encountered this issue, thank you for fixing it. The reason the CI passed is because of the shaded jar dubbo.jar, but this is not available during development.
