### ISSUE TITLE
[Bug] loadbalance cannot be modified on the consumer side

### ISSUE THREAD

**Issue by eye-gu** [apache/dubbo#14968]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo: 3.2.14 jdk:17

### Steps to reproduce this issue

Config loadbalance as roundrobin, but attempting to change it to random on the consumer side,  did not take effect

consumer:
```
RpcContext.getClientAttachment().setAttachment(CommonConstants.LOADBALANCE_KEY, "random");
```

### What you expected to happen

Can dynamically modify the loadbalance  on the consumer side? If there is a problem with my usage, please let me know the correct method. Thank you

### Anything else

`org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker#initLoadBalance`

Check the code of this method, does it not support dynamic modification loadbalance?

### Are you willing to submit a pull request to fix on your own?

- [x] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by laywin** [comment]
```java
    protected LoadBalance initLoadBalance(List<Invoker<T>> invokers, Invocation invocation) {
        ApplicationModel applicationModel = ScopeModelUtil.getApplicationModel(invocation.getModuleModel());
        if (CollectionUtils.isNotEmpty(invokers)) {
            return applicationModel
                    .getExtensionLoader(LoadBalance.class)
                    .getExtension(invokers.get(0)
                            .getUrl()
                            .getMethodParameter(
                                    RpcUtils.getMethodName(invocation), LOADBALANCE_KEY, DEFAULT_LOADBALANCE));
        } else {
            return applicationModel.getExtensionLoader(LoadBalance.class).getExtension(DEFAULT_LOADBALANCE);
        }
    }
```
i think you can override url by config on dubbo admin.

**Comment by AlbumenJ** [comment]
`loadbalance` cannot be modified by invocation
