### ISSUE TITLE
Dubbo 2.7.22 No provider，重新触发通知后又正常

### ISSUE THREAD

**Issue by kangzhaok** [apache/dubbo#15004]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

2.7.22

### Steps to reproduce this issue

1. consumer可以看到nacos注册中心通知的url实例数是正确的。
2. 但是consumer调用的时候就会报no provider。
3. 通过nacos重新上下线一个实例时，consumer看到通知的url实例数也正确。
4. 再次调用就正常了。

### What you expected to happen

有老师遇到过吗？

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by kangzhaok** [comment]
同一台机器，调用多次，有几次是no provider，其他是正常的

**Comment by wcy666103** [comment]
Please re-submit in English Only.

**Comment by AlbumenJ** [comment]
Please re-submit in English Only :) Or you can upgrade to the latest version
