### ISSUE TITLE
Our company has developed CircuitBreaker, on the consumer side,can we open source?

### ISSUE THREAD

**Issue by wanhuhou** [apache/dubbo#1505]

**Comment by ralf0131** [comment]
You are always welcome for any kind of contribution to Dubbo community if you would like to open source your work. Could you please briefly describe what you have done so that we can discuss how the contribution is going to happen?

**Comment by kimmking** [comment]
I think you could create a subproject for this and submit a PR to dubbo-ops repo.

**Comment by justinmclean** [comment]
Hi,

Depending on the amount of code it may need to come in as a software grant. [1]

Thanks,
Justin

1. http://apache.org/foundation/how-it-works/legal.html#incoming-code

**Comment by chickenlj** [comment]
Welcome @wanhuhou, would you please give a brief introduction of your design principles here? So we can figure the amount of code this feature may contains and discuss of a way to properly accepting it into the community.

**Comment by wanhuhou** [comment]
yes  I'm tidying up. Please wait a minute.

**Comment by wanhuhou** [comment]
Our  circuitBreaker is done in the filter, and the basic principle is to record QPS, error rate and so on with the ip- interface to judge whether or not it is circuitBreaker.
The main solution is to solve the problem of continuous request for the machine when the single service machine has access abnormity.

1, CircuitBreaker operate on the consumer side. When the server fails to provide services normally, the consumption terminal will automatically drop the abnormal service address.

      For example, the HelloService service has three server servers, A, server B, and server C.
The consumer side access the HelloService.sayHi () method, each consumer will record the address, service name, and method name of the specific access service.
In the first step, when the server A HelloService.sayHi () method is abnormal and reaches the threshold, the consumption end's fusing mechanism removes the access address of the server A.
The subsequent access can only be the server - side B, the server - side C. At this point, the state of the CircuitBreaker is open;
The second step is the window period, which is configured freely, such as configuring 5000ms, that is, when the server A is removed for 5 seconds, the A access address of the server is re placed into the address list.
At this time, the state is half-open, which is used to try to access the service side A. The 6 consecutive visits indicate that the service A of the server is recovered, and the state changes to closed at this time.
If you try to access the server - side A failure, then the half-open state changes to open, retries it, and waits after 5 seconds to retry.
2, after the CircuitBreaker, it reduces the access pressure to the exception service machine and makes the client no longer access the exception machine to improve the probability of successful return.


Configurable parameters:
 circuitBreakerRequestVolumeThreshold=20 //与circuitBreakerRollingStatisticalWindowBuckets配合使用，默认15秒内的访问量是10，才有可能开启熔断
 circuitBreakerSleepWindowInMilliseconds=60000//60秒之后重试，单位是ms
 circuitBreakerErrorThresholdPercentage=80//错误率80% 
 circuitBreakerOpenweight=1 //熔断打开之后重试关闭时的权重 
 circuitBreakerCloseweight=1000 //存在熔断服务且过了熔断窗口可重试时没有被熔断的服务。
 circuitBreakerRollingStatisticalWindowBuckets //环境变量中配置

**Comment by wanhuhou** [comment]
Hystrix circuit breakers by test, open and close the influence on the performance of the machine is relatively small in high performance environment (local development machine 16g delay less than 1ms), is mainly the influence of time delay, if the machine configuration is relatively low, for example: 2 nuclear 4G (about 2ms), the performance difference
It's more obvious. The delay in our machine is unacceptable.
our circuit breakers the following is the realization:
The properties of the circuit breakers:
1, the corresponding qps. can be obtained according to key
2, the error rate can be obtained according to key.
3, fuses have taken place.
4, the circuit breakers has three kinds of state open half-open closed.
5, the circuit breakers supports high concurrency (a small impact on the performance when the amount of concurrency is increased).
The same key holds the same breaker object and holds the circuit breakers information of the key. Each breaker holds a bucket array (10), and the bucket object contains simple attributes, such as the upper figure, access volume, failure volume, start time and end time. Point points to the current bucket index,
When the current bucket reaches a certain amount, the next bucket is switched, and the last bucket end time is set, so the failure rate, QPS can be calculated. The same way moves down to the last bucket[9] to automatically switch to the first bucket[0].
Calculate the average value of the QPS, the failure rate, and the bucket before the pointer is taken.
The statistics of the total amount of requests and the total amount of failure are LongAdder.
Synchronization of bucket switching

**Comment by zonghaishang** [comment]
I think this strategy is relatively simple, if you can detect the performance of the server to automatically adjust the fuse will be better.

**Comment by wanhuhou** [comment]
Welcome everyone to make an improvement

**Comment by zonghaishang** [comment]
circuitBreakerRequestVolumeThreshold=20 //与circuitBreakerRollingStatisticalWindowBuckets配合使用，默认15秒内的访问量是10，才有可能开启熔断
circuitBreakerSleepWindowInMilliseconds=60000//60秒之后重试，单位是ms
circuitBreakerErrorThresholdPercentage=80//错误率80%
circuitBreakerOpenweight=1 //熔断打开之后重试关闭时的权重
circuitBreakerCloseweight=1000 //存在熔断服务且过了熔断窗口可重试时没有被熔断的服务。
circuitBreakerRollingStatisticalWindowBuckets //环境变量中配置

Can you provide a flowchart to explain the relationship between these parameters? Thanks.

**Comment by ningyu1** [comment]
@zonghaishang 
Parameter configuration can be viewed: [Hystrix-Configuration](https://github.com/Netflix/Hystrix/wiki/Configuration)

@wanhuhou 
Parameter configuration is best left to the user to choose their own scene to choose.
There are a lot of configurable items. 
It’s not an easy thing to integrate well.

**Comment by beiwei30** [comment]
@wanhuhou, you may consider to submit a pull request, thanks.
