### ISSUE TITLE
Dubbo multi-protocol， dubbo & webservice protocol to publish service，when startup fail to init webservice bean

### ISSUE THREAD

**Issue by lawplus** [apache/dubbo#1560]
because of dubbo2.5.3 webservice RPC is very old dev@2013?，so it replied on cxf2.6.1，but cxf 2.6.1 integriting with dubbo using spring 4.0，is not compatible， when the spring container starting, it raise  NoSuchMethod at some spring aop framwork classes。i judge it means cxf2 & spring4 is not compatible。
when cxf upgrade to 3.x above，the dubbo error： NoSuchMethod  at some cxf related class，it means cxf3 & dubbo rpc webservice is not compatible,  WebServiceProtocol.java

--
refer to https://github.com/apache/incubator-dubbo/blob/master/dubbo-rpc/dubbo-rpc-webservice/src/main/java/com/alibaba/dubbo/rpc/protocol/webservice/WebServiceProtocol.java
error happends @ line 88
--

so I ask here any plan to upgrade to support cxf3?

**Comment by lovepoem** [comment]
Please paste some error logs and your test code, if we can fix the bug ,we'll upgrade the  cxf as soon as possible.

**Comment by lovepoem** [comment]
Hi, Welcome!

Would you please consider ask in English? Since this project is moved to ASF repo, we hope it is understandable by people all over the world so that everyone can join to discuss.

Also, please try to ask by sending an email to dev@dubbo.incubator.apache.org-->[Subscribe guide](https://github.com/ApacheInfra/dubbo/issues/1393) , issues is used to track bugs.

**Comment by rongmin** [comment]
@lovepoem  thanks to remind. pls help to look at this problem.

**Comment by kimmking** [comment]
@rongmin you can use the latest version by packaging from the master code.
1. then you can add ws protocol to a xml file just like:
 incubator-dubbo\dubbo-test\dubbo-test-`examples\src\main\java\com\alibaba\dubbo\examples\generic\generic-provider.xml`

`
<dubbo:application name="generic-generic"/>

    <dubbo:registry address="multicast://224.5.6.7:1234"/>

    <dubbo:protocol name="dubbo" port="20880"/>
    <dubbo:protocol name="webservice" port="10880"/>

    <bean id="userserviceimpl" class="com.alibaba.dubbo.examples.generic.impl.UserServiceImpl"/>

    <dubbo:service interface="com.alibaba.dubbo.examples.generic.api.IUserService" ref="userserviceimpl" protocol="dubbo,webservice">
    </dubbo:service>
`
2. run  `git\incubator-dubbo\dubbo-test\dubbo-test-examples\src\main\java\com\alibaba\dubbo\examples\generic\GenericProvider.java`  as an application in your IDE.
3. and then visit a WSDL from URL:
http://192.168.123.102:10880/com.alibaba.dubbo.examples.generic.api.IUserService?WSDL
4. you will find WS work well, the ref CXF version is 3.0.4 now.

**Comment by kimmking** [comment]
generic test case is not a good demo,
I update CXF to 3.2.4 and add a demo for it.
#1564
