### ISSUE TITLE
http2 support?

### ISSUE THREAD

**Issue by eonezhang** [apache/dubbo#1563]
as netty 4.1.x add default support for http2, and dubbo also support protocol extension, is any plan to support http1/2 transport without containers such as jetty.

**Comment by beiwei30** [comment]
yes, that's in the plan.

**Comment by EdwardLee03** [comment]
Can share the detailed plan or milestone? thx @beiwei30

**Comment by carryxyh** [comment]
Hi, this is in plan.
The rep is here:
https://github.com/zonghaishang/dubbo-rpc-http2

**Comment by zonghaishang** [comment]
@eonezhang  http2 example: https://github.com/zonghaishang/dubbo-example-http2
I will provide more detailed documentation later.

**Comment by cvictory** [comment]
We should add a demo in dubbo-sample project.  I have new a issue : https://github.com/dubbo/dubbo-samples/issues/38 .

This issue can be closed. 

&READY-TO-CLOSE&

**Comment by carryxyh** [comment]
@cvictory 
Hi,
Since the part of HTTP2 has not been merged into the master, can this problem be closed?

**Comment by spilledyear** [comment]
2018年，为啥没合并呢？
