### ISSUE TITLE
dubbo protocol can support TLS？ 

### ISSUE THREAD

**Issue by the3rd** [apache/dubbo#1605]

**Comment by lovepoem** [comment]
What's TLS? Can you explain it ?

**Comment by kimmking** [comment]
The latest version of SSL.
It required that dubbo support HTTPS protocol.

**Comment by the3rd** [comment]
Yes. The latest version of SSL. [Transport Layer Security](https://en.wikipedia.org/wiki/Transport_Layer_Security)

But it does not mean HTTPS. Dubbo's default protocol 'dubbo' should support 'over TLS/SSL'.

**Comment by ywww** [comment]
@the3rd     how to use

**Comment by Warkeeper** [comment]
I'm recently working on supporting SSL/TLS for Dubbo on Netty4 transporter,in fact,it's pretty easy to achieve cause netty4 has a good support on ssl/tls. If someone's interested in it,you could check my repo(I think my code quality is not good enough to merge into the official branch).

我最近在做一个关于加强dubbo安全性的毕业设计，主要工作是为dubbo增加ssl/tls支持，目前我实现了为dubbo的netty4传输层增加ssl/tls支持。事实上，这个实现还是挺简单的，因为netty4对ssl/tls的支持很棒（我还参考了gRpc相关的实现）。如果有人有兴趣可以来看看我的repo，我将会在近期持续的做tls支持相关的内容（比如在dubbo-admin中增加签发证书、生成CA证书的功能）。PS：我觉得我的代码质量实在比不上dubbo的源码质量，都不好意思提PR，所以还待有相关需求的大佬来做吧

**Comment by TotalForgot** [comment]
Dear experts
We are also interested in this feature of Dubbo.
Is there any update regarding this aspect?

Best
TotalForgot
