### ISSUE TITLE
server=“servlet" 并指定 contextpath 时，发布的webservice ，dubbo无法访问

### ISSUE THREAD

**Issue by codingboyli** [apache/dubbo#163]
server=“servlet" 并指定 contextpath 时，发布的webservice ，dubbo无法访问。

 final ServerFactoryBean serverFactoryBean = new ServerFactoryBean();
  serverFactoryBean.setAddress(url.getAbsolutePath());

url.getAbsolutePath() 获得的结果将 contextpath也加进去了。 导致webservice发布的url多了 contextpath  .

解决方法：

 修改 ： ServiceConfig.doExportUrlsFor1Protocol 方法：

// 导出服务
        String contextPath = protocolConfig.getContextpath();
        if ((contextPath == null || contextPath.length() == 0) && provider != null) {
            contextPath = provider.getContextpath();
        }

增加：
        map.put("contextpath", contextPath);

修改 WebServiceProtocol.doExport 方法：

```
protected <T> Runnable doExport(T impl, Class<T> type, URL url)
        throws RpcException {
    String addr = url.getIp() + ":" + url.getPort();
    HttpServer httpServer = serverMap.get(addr);
    if (httpServer == null) {
        httpServer = httpBinder.bind(url, new WebServiceHandler());
        serverMap.put(addr, httpServer);
    }
    String contextpath = url.getParameter("contextpath");
    String address = url.getAbsolutePath();
    if (contextpath != null && contextpath.length() > 0) {
        address = address.substring(contextpath.length() + 1);
    }
    final ServerFactoryBean serverFactoryBean = new ServerFactoryBean();
    serverFactoryBean.setAddress(address);
    serverFactoryBean.setServiceClass(type);
    serverFactoryBean.setServiceBean(impl);
    serverFactoryBean.setBus(bus);
    serverFactoryBean.setDestinationFactory(transportFactory);
    serverFactoryBean.create();
    return new Runnable() {
        public void run() {
            serverFactoryBean.destroy();
        }
    };
}
```

**Comment by CrazyHZM** [comment]
Duplicate #86

**Comment by beiwei30** [comment]
需要注意的是，这个问题不单单在 webservice 的时候有，应该是所有依赖 server 是 servlet 的情况下都有。

> server=“servlet" 并指定 contextpath 时
