### ISSUE TITLE
[BUG]Endpoint address is missing in WSDL with webserivce protocol

### ISSUE THREAD

**Issue by kimmking** [apache/dubbo#1655]
When we export a webservice with webserivce protocol, we will find Endpoint address is missing in WSDL, then we use wsdl to generate codes and call ws method, it will be failing.

See also #1585

**Comment by schdai** [comment]
if you use dubbo 2.5.3 and cxf 2.7.7 , it's ok.

**Comment by AlbumenJ** [comment]
Close this issue, will be tracked with #1655
