### ISSUE TITLE
How can I know where I am called in a Router

### ISSUE THREAD

**Issue by gougouzcm** [apache/dubbo#1669]
I write a router.

```java
@Override
    public <T> List<Invoker<T>> route(List<Invoker<T>> list, URL url, Invocation invocation) throws RpcException {


        // TODO 不能这么决定是 zkSubscribe 的触发的route
        if (StringUtils.isBlank(invocation.getMethodName())){

            logger.info("zkRefresh notify invokes " + list);
            // 代表是 zk监听的触发的 refresh
            return list;

        }

        // 从ThreadLocal中拿到 当前的灰度分组
        String grayGroup = RpcGrayContext.getGrayGroup();
        if (StringUtils.isNotEmpty(grayGroup)){
            logger.info("current rpc request is  greyGroup " + grayGroup);
            invocation.getAttachments().put(Constant.GRAY_GROUP_KEY, grayGroup);

        }else {
            logger.info("current rpc request is  normalGroup " );
        }



        List<Invoker<T>> invokerList = new ArrayList<>();

        List<Invoker<T>> normalInvokerList = new ArrayList<>();


        if ( list != null ){

            for ( Invoker invoker : list ){

                URL providerUrl = invoker.getUrl();
                String providerGroup = providerUrl.getParameter(com.alibaba.dubbo.common.utils.StringUtils.camelToSplitName("dynamicGroup","."));

                if (StringUtils.isBlank(providerGroup) ){

                    normalInvokerList.add(invoker);
                    System.out.println(providerUrl.getHost() + " is not AB test");

                    if (StringUtils.isBlank(grayGroup)) {

                        invokerList.add(invoker);
                    }
                }else {
                    System.out.println(providerUrl.getHost() + " is  AB test , group is " + providerGroup );
                    if ( providerGroup.equals(grayGroup) ){
                        invokerList.add(invoker);
                    }

                }


            }
        }
        if (StringUtils.isNotBlank(grayGroup) && CollectionUtils.isEmpty(invokerList)){
            // 如果当前请求是灰度请求，但是没有任何灰度机器，那么按照正常的机器请求
            return normalInvokerList;
        }else {
            return invokerList;

        }

    }
```

In this router , I want every rpc request route by  the  threadLocal `RpcGrayContext.getGrayGroup();` content.
If current rpc is a GrayGroup rpc ,I will found all the providers in this group.

The question is that [RegistyDirctory](https://github.com/apache/incubator-dubbo/blob/master/dubbo-registry/dubbo-registry-api/src/main/java/com/alibaba/dubbo/registry/integration/RegistryDirectory.java)  will cache a map `Map<String, List<Invoker<T>>> methodInvokerMap`.
It will call the method I Override 
```
private List<Invoker<T>> route(List<Invoker<T>> invokers, String method) {
            Invocation invocation = new RpcInvocation(method, new Class<?>[0], new Object[0]);
            List<Router> routers = getRouters();
            if (routers != null) {
                for (Router router : routers) {
                    if (router.getUrl() != null) {
                        invokers = router.route(invokers, getConsumerUrl(), invocation);
                    }
                }
            }
            return invokers;
        }
```
But when registry refresh the router or providers , the content from `RpcGrayContext.getGrayGroup()` will be empty.
It will cause the cachemap `methodInvokerMap` lost some InvokeUrl .

So , If I know the my router was called by the ZkNotifyThread , I will return all the invokers.
If my router was call by the rpc request , I will allocate the right grayGroup providersfrom ThreadLocal  for this request .

I don't want to use the `new Throwable().getStackTrace()` . 

can any one help me ,thk

**Comment by beiwei30** [comment]
route method will only be called by refreshInvoker method, I am wondering when your thread local variable `RpcGrayContext.getGrayGroup()` can be kicked in.

**Comment by beiwei30** [comment]
you should consider to use [conditional routing](http://dubbo.apache.org/books/dubbo-user-book/demos/routing-rule.html) to achieve your purpose, something like:

```
group=grey => ip list separated with comma
```

**Comment by gougouzcm** [comment]
@beiwei30 

```
public List<Invoker<T>> list(Invocation invocation) throws RpcException {
        if (destroyed) {
            throw new RpcException("Directory already destroyed .url: " + getUrl());
        }
        List<Invoker<T>> invokers = doList(invocation);
        List<Router> localRouters = this.routers; // local reference
        if (localRouters != null && localRouters.size() > 0) {
            for (Router router : localRouters) {
                try {
                    if (router.getUrl() == null || router.getUrl().getParameter(Constants.RUNTIME_KEY, false)) {
                        invokers = router.route(invokers, getConsumerUrl(), invocation);
                    }
                } catch (Throwable t) {
                    logger.error("Failed to execute router: " + getUrl() + ", cause: " + t.getMessage(), t);
                }
            }
        }
        return invokers;
    }
```
I put the param Constants.RUNTIME_KEY true in url， so the  router will be called every rpc request。

`RpcGrayContext.getGrayGroup()`  was put in a web filter / or the `<dubbo:provider filter=grayFilter>` , It will be clean and set  at that time  。

First , In my test , if ` router.getUrl().getParameter(Constants.RUNTIME_KEY, false) == true` , the router will be called every time.
I had got a idea how to add grayRouter in [1622](https://github.com/apache/incubator-dubbo/issues/1622)。

The  [conditional routing](http://dubbo.apache.org/books/dubbo-user-book/demos/routing-rule.html) is too complex for deal with gray request.  many interface, many  configures, and can't dynamic route gray request in One application.

**Comment by beiwei30** [comment]
I will take a look at this issue later.

**Comment by CrazyHZM** [comment]
If this issue still exists, please reopen this issue and close it for now.
