### ISSUE TITLE
The Random of loadbalance  unaverage Load

### ISSUE THREAD

**Issue by jieyisoft** [apache/dubbo#1711]
Using virtualization cluster, using 5 nodes, each node host configuration and application are consistent, each node has three Dubbo services.

1000 concurrent stress tests are carried out through JMeter, and the configuration (loadbalance=random, dispatcher=message, threadpool=fixed services are accessed asynchronously).

In theory, loadbalance=random has 300 performance per service configuration and is fully satisfied with consumption calls.

But it is found that Dubbo service must be configured with 1000 threads, otherwise it will output dump information wrongly.

LeastActiveLoadBalance can not solve the problems.

What is the reason for this?

**Comment by beiwei30** [comment]
this should not happen, not sure if it's caused by wrongly configured jmeter, which route all traffic to one single provider.
