### ISSUE TITLE
performance testing，at single thread test scene, thread sleep is slower than no sleep in response time，why？？

### ISSUE THREAD

**Issue by zackhu135** [apache/dubbo#1719]
sleep scene:
public static void main(String[] args) {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[]{"META-INF/spring/dubbo-demo-consumer.xml"});
        context.start();
        DemoService demoService = (DemoService) context.getBean("demoService"); // get remote service proxy
        for(int i=0;i<10000;i++) {
            try {
                Thread.sleep(100);
                String hello = demoService.sayHello("world"); // call remote method
            } catch (Throwable throwable) {
                throwable.printStackTrace();
            }
        }
    }

no sleep scene:
public static void main(String[] args) {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[]{"META-INF/spring/dubbo-demo-consumer.xml"});
        context.start();
        DemoService demoService = (DemoService) context.getBean("demoService"); // get remote service proxy
        for(int i=0;i<10000;i++) {
            try {
                String hello = demoService.sayHello("world"); // call remote method
            } catch (Throwable throwable) {
                throwable.printStackTrace();
            }
        }
    }

**Comment by kimmking** [comment]
can you show your test result ?

**Comment by AlbumenJ** [comment]
Close for long time no response. Please feel free to reopen if you have any question.
