### ISSUE TITLE
System property dubbo.service.delay invalid

### ISSUE THREAD

**Issue by feelwing1314** [apache/dubbo#1728]
根据dubbo参数的映射关系<dubbo:service delay="5000">也可以通过-Ddubbo.service.delay=5000配置，但是发现-Ddubbo.service.delay=5000不起作用；

debug下面这段代码（ServiceConfig.java）发现：

```java
public synchronized void export() {
    ... ...
    if (delay != null && delay > 0) {
        delayExportExecutor.schedule(new Runnable() {
            @Override
            public void run() {
                doExport();
            }
        }, delay, TimeUnit.MILLISECONDS);
    } else {
        doExport();
    }
}
```

如果有delay，先delay再doExport()，而解析JVM参数的逻辑（appendProperties(this);）是在doExport()方法中调用；所以导致 if (delay != null && delay > 0)判断时，还没有解析JVM参数-Ddubbo.service.delay=5000，从而导致这种配置不起作用；

**Comment by ralf0131** [comment]
Would you please send a pull request?

**Comment by chickenlj** [comment]
http://dubbo.apache.org/#!/docs/user/demos/delay-publish.md?lang=zh-cn

http://dubbo.apache.org/#!/docs/user/configuration/properties.md?lang=zh-cn
