### ISSUE TITLE
Dubbo用户手册(中文) 一些内容链接无法打开

### ISSUE THREAD

**Issue by weichengpei** [apache/dubbo#1783]
Dubbo用户手册(中文) ， 2快速启动， “ API 的方式” 无法点开。

**Comment by ralf0131** [comment]
It is already fixed, the link points to http://dubbo.apache.org/books/dubbo-user-book/configuration/api.html

**Comment by ralf0131** [comment]
Hi, 

Would you please update the title and description using English? Dubbo is a global community and we would like the issue to be seen by people all over the world.
