### ISSUE TITLE
graceful shutdown time shoud could be configured in xml file

### ISSUE THREAD

**Issue by qinliujie** [apache/dubbo#1814]
see #465 ,dubbo.service.shutdown.wait / dubbo.service.shutdown.wait.seconds can only be configured in dubbo.properties file or jvm arguments, we should  also support in xml format and put this config into ApplicationConfig.what do you think? @chickenlj

**Comment by caneo** [comment]
[Dubbo-1814][Baiji-4] configure "provider.XML" 
add a tag named Wait <dubbo:registry>: set timeout time for graceful downtime configuration in the registry.
<dubbo:registry address="multicast://224.5.6.7:1234" wait="100000"/>

**Comment by lisirrx** [comment]
In dubbo.properties, `dubbo.service.shutdown.wait` is used for config wait timeout of graceful shutdown. So we can use `dubbo:parameter` of `dubbo:service` to pass a timeout value to `DubboProtocal` to overide the value of `dubbo.service.shutdown.wait`

However a static field `wait` is added into `DubboProtocal`, I can't find a more elegance way to implement it.
#2375
