### ISSUE TITLE
When using the restfull protocol transaction rollback failed

### ISSUE THREAD

**Issue by jqncc** [apache/dubbo#1815]
dubbo+mybatis
使用rest协议时,方法内调用其他spring service的方法,发生异常时事务回滚失败,使用dubbo协议时正常
Using rest protocol, method calls within other spring service, the method of transaction rollback failed, when an exception occurs when using the dubbo protocol is normal

**Comment by pan289091315** [comment]
i found is ok, Could you please submit one demo project so I can try reproducing this issue?

**Comment by AlbumenJ** [comment]
Close for long time no response. Please check in the latest master branch or you can submit a new issue.
