### ISSUE TITLE
生产者、消费者、注册中心不在同一个工程时，@reference调用远程接口无法识别

### ISSUE THREAD

**Issue by mengxiaofei007** [apache/dubbo#1864]
![image](https://user-images.githubusercontent.com/36765750/40667599-24036ff4-6395-11e8-92e8-b131f41df811.png)
![image](https://user-images.githubusercontent.com/36765750/40668454-2555af8c-6397-11e8-8e81-77f9a75435df.png)
生产者可以正常发布
dubbo监控中心也可以看到生产者 
![image](https://user-images.githubusercontent.com/36765750/40667971-fa343892-6395-11e8-8b42-d594ffe80b4c.png)
就是在消费者引入远程生产者接口的时候本地不识别，编译不通过，请问这个问题该如何解决？如何让dubbo调用远程主机的接口服务呢？？能否讲解一下 翻了一下官网文档  没有发现相关解释~谢谢了~

**Comment by yythlj** [comment]
+1

**Comment by diecui1202** [comment]
Hi, you need to add the dependency which contains the class `Crm` to your consumer side project.
