### ISSUE TITLE
有没有将服务注册中心从zk迁移到Eureka的计划

### ISSUE THREAD

**Issue by kevinwong0211** [apache/dubbo#1893]
Eureka更适合

**Comment by AlbumenJ** [comment]
could you please describe why you want to move to eureka?

**Comment by cliffcw** [comment]
> could you please describe why you want to move to eureka?
most of company is Spring Cloud feign of http ...  and want to replace with dubbo

**Comment by AlbumenJ** [comment]
> > could you please describe why you want to move to eureka?
> > most of company is Spring Cloud feign of http and the registry is eureka ... they want to replace with dubbo

Dubbo support eureka currently.
