### ISSUE TITLE
dubbo-admin cache issue.

### ISSUE THREAD

**Issue by zyong2004** [apache/dubbo#1933]
在首次 使用一个分组服务时，可以发现服务，可以在dubbo-admin看到，然后关闭服务，刷新admin，服务还在，变更分组组名时，重启服务时，老的分组和新的分组同时存在，老的分组显示正常提供提供服务，调用时出现服务不可用。

**Comment by dengjiexiao** [comment]
我想问下dubbo admin 怎么看不到消费者了？

**Comment by diecui1202** [comment]
@dengjiexiao You could provide more information here, maybe you need to check the consumer is exist.

**Comment by dengjiexiao** [comment]
@diecui1202  https://github.com/apache/incubator-dubbo/issues/663

**Comment by dengjiexiao** [comment]
![image](https://user-images.githubusercontent.com/26115736/44328045-17b9cb00-a493-11e8-97fe-cb493a8d6a9b.png) 提供者服务启动成功和消费者也是启动成功，但是只能看到服务者，但是看不到消费者

**Comment by diecui1202** [comment]
@dengjiexiao Make sure the process of the consumer is still alive.

**Comment by dengjiexiao** [comment]
消费者是存活的。
![image](https://user-images.githubusercontent.com/26115736/44328351-e55c9d80-a493-11e8-9a34-52c1ab7904d8.png)

**Comment by diecui1202** [comment]
@nzomkxia check this problem in the dubbo ops if necessary.

@dengjiexiao Is your dubbo ops the lastest version?

**Comment by dengjiexiao** [comment]
@diecui1202   从你们incubator-dubbo-ops项目下载的打包，是最新的

**Comment by nzomkxia** [comment]
@dengjiexiao 试一下当前版本的dubbo ops: https://github.com/apache/incubator-dubbo-ops
