### ISSUE TITLE
可伸缩的线程池写法可能存在一定问题

### ISSUE THREAD

**Issue by wu560130911** [apache/dubbo#1954]
dubbo默认实现的CachedThreadPool，当queue大写不为0时，尤其为-1时，将永远加入队列，直到队列满，才会新创建线程去处理（未达到最大线程数）。
https://github.com/apache/incubator-dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/threadpool/support/cached/CachedThreadPool.java#L46

**Comment by lnyu** [comment]
这不正是 CachedThreadPool 吗？

**Comment by wu560130911** [comment]
但是针对queues小于零时，就可能出现问题了，所以建议对此参数进行校验，防止出现误用

**Comment by chickenlj** [comment]
It follows the convention of the standard CachedThreadPool provided by JDK. I think there's no need for a further check.

**Comment by wu560130911** [comment]
@chickenlj  are you sure? jdk only provide use SynchronousQueue, not LinkedBlockingQueue

**Comment by qq925716471** [comment]
The default value of the corethreads is 0. When set queues to -1, the task will be added to the queue until the capacity of the queue is reached.The capacity bound, or Integer.MAX_VALUE if none

**Comment by edwardlee03** [comment]
> The default value of the corethreads is 0. When set queues to -1, the task will be added to the queue until the capacity of the queue is reached. The capacity bound, or Integer.MAX_VALUE if none

是存在这个问题，尤其在高并发且提供者响应很慢时，会同时把消费者也一起拖垮。我们内部设置为`threads`
```
int threads = url.getParameter(Constants.THREADS_KEY, Constants.DEFAULT_THREADS);
```

**Comment by AlbumenJ** [comment]
> @chickenlj are you sure? jdk only provide use SynchronousQueue, not LinkedBlockingQueue

In JDK     

```java
    public static ExecutorService newFixedThreadPool(int nThreads, ThreadFactory threadFactory) {
        return new ThreadPoolExecutor(nThreads, nThreads,
                                      0L, TimeUnit.MILLISECONDS,
                                      new LinkedBlockingQueue<Runnable>(),
                                      threadFactory);
    }

    public static ExecutorService newCachedThreadPool(ThreadFactory threadFactory) {
        return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                                      60L, TimeUnit.SECONDS,
                                      new SynchronousQueue<Runnable>(),
                                      threadFactory);
    }
```

CachedThreadPool is more like a extend for `newCachedThreadPool`, support customize queue.
