### ISSUE TITLE
It is recommended to delete group and version in RegistryConfig

### ISSUE THREAD

**Issue by ningyu1** [apache/dubbo#1977]
In the document, there is no description of the use of the group and version of RegistryConfig, so as to avoid misuse and suggestion deletion.

RegistryConfig's group is currently used to affect the UrlPath of service registration.
I don't think it's useful.

**Comment by kimmking** [comment]
see also https://github.com/apache/incubator-dubbo/issues/1955

**Comment by ningyu1** [comment]
@kimmking thinks .
What is the role of groups designed to be isolated clusters?  Distinguish the environment?
It seems that the service details for adding the group cannot be seen in dubbo admin.

There is also the `version` attribute of the `RegistryConfig` class,  From a code standpoint, it doesn't seem to work.

**Comment by kimmking** [comment]
@ningyu1  you are right.
1.  dubbo admin doesn't support more than 1 groups.
2. the version of Registry is no use until now.

**Comment by chickenlj** [comment]
As far as I know, some users rely on Registry group to isolate clusters belongs to the different business area.

So instead of deleting this feature, we may need to further enhance it, supplement docs, enhance functionality.
