### ISSUE TITLE
Dubbo序列化多个 CopyOnWriteArrayList 对象, 反序列化后得到的对象变成同一个!

### ISSUE THREAD

**Issue by DC-ET** [apache/dubbo#2132]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.10
* Operating System version: win10
* Java version: 1.8

### Step to reproduce this issue

        `public class Entity implements Serializable {

         private static final long serialVersionUID = 187648346954430294L;

         private List<Integer> list1 = new CopyOnWriteArrayList<>();
         private List<Integer> list2 = new CopyOnWriteArrayList<>();

         public List<Integer> getList1() {
             return list1;
         }

         public List<Integer> getList2() {
             return list2;
         }
     }`

        `public static void main(String[] args) throws IOException {
        Entity entity = new Entity();
        // 此时两个 CopyOnWriteArrayList 不同
        System.out.println(entity.getList1() == entity.getList2());

        // 序列化
        OutputStream outputStream = new FileOutputStream("dubboSerializer");
        GenericObjectOutput objectOutput = new GenericObjectOutput(outputStream);
        objectOutput.writeObject(entity);
        objectOutput.flushBuffer();

        // 反序列化
        GenericObjectInput input = new GenericObjectInput(new FileInputStream("dubboSerializer"));
        Entity obj1 = (Entity) input.readObject();
        // 此时两个 CopyOnWriteArrayList 相同????????????????????????
        System.out.println(obj1.getList1() == obj1.getList2());
        }`

说明: 将 CopyOnWriteArrayList 换成 ArrayList 时 没有此问题.

**Comment by beiwei30** [comment]
where's GenericObjectInput introduced?

**Comment by lovepoem** [comment]
Now the dubbo use hessian serialize component  by default
```java

@Test
public void testListSerializer() throws Exception {

    List<Integer> list = new CopyOnWriteArrayList<>();
    list.add(1111);
    list.add(2222);
    List<Integer> list2 = new CopyOnWriteArrayList<>();
    list2.add(1111);
    list2.add(2222);
   // Assert.assertTrue(list==list2);
    List deserialize = baseHessianSerialize(list);
    List deserialize2 = baseHessianSerialize(list2);
    Assert.assertTrue(deserialize.equals(list));
    Assert.assertTrue(deserialize==deserialize2);
}

/**
 * hessian serialize util
 *
 * @param data
 * @param <T>
 * @return
 * @throws IOException
 */
provite <T> T baseHessianSerialize(T data) throws IOException {
    ByteArrayOutputStream bout = new ByteArrayOutputStream();
    HessianOutput out = new HessianOutput(bout);

    out.writeObject(data);
    out.flush();

    ByteArrayInputStream bin = new ByteArrayInputStream(bout.toByteArray());
    HessianInput input = new HessianInput(bin);
    return (T) input.readObject();
}


```
Your problem can't be reproduced

Ian Luo <notifications@github.com> 于2018年7月27日周五 下午12:36写道：

**Comment by 15058126273** [comment]
GenericObjectInput was imported from com.alibaba.dubbo.common.serialize.support.dubbo.GenericObjectInput; (dubbo:2.5.10)

I'm using dubbo serialization not hessian. config like this: 

ProtocolConfig config = new ProtocolConfig();
config.setSerialization("dubbo");

should i change the serialization to solve this problem?

note: 

I use com.alibaba.dubbo.common.serialize.support.hessian.Hessian2ObjectInput  -> test ok;
I use GenericObjectInput with ArrayList -> test ok;
I use GenericObjectInput with CopyOnWriteArrayList -> test not ok;

**Comment by kimmking** [comment]
I think it's a bug on dubbox branch.
When dubbox rest and kryo+fst functionalities transferred to dubbo master repo, GenericObjectInput is not contained.
So we suggest you use hessian serialization or update your dubbo version to 2.6.x.

**Comment by complone** [comment]
Why not wrap this object with Collections. synchronized List? This allows you to rewrite hashcode and store it as a different address

**Comment by CrazyHZM** [comment]
2.5.x is no longer maintained, try to upgrade to 2.7.x or 3.x to solve the problem.
