### ISSUE TITLE
Add profile for quickly check files meet ASF standards: enable rat and style plugin.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#2416]
mvn clean test \# This will run all unit tests
\# you can also open rat and style plugin to check if every file meets
requirements.
mvn clean test -Drat.skip=false -Dcheckstyle.skip=false

I suggest to use a dedicate profile for release, which will including
all the checks, rat, checkstyle, etc, so that we can run

**Comment by diecui1202** [comment]
IMO, we just remove the following two properties in the pom:

```
        <checkstyle.skip>true</checkstyle.skip>
        <rat.skip>true</rat.skip>
```

so that we can run them each time except you absolutely do not want then to run.

**Comment by CrazyHZM** [comment]
Already integrated.
