### ISSUE TITLE
[Performance optimization] Dubbo performance improvement

### ISSUE THREAD

**Issue by zonghaishang** [apache/dubbo#2508]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0+
* Java version: 1.8

### Optimize the scene

```
1.  Performance improvement scenario description
2.  Unoptimized benchmark performance
3.  Optimized benchmark performance
4.  Benchmarking tool： https://github.com/dubbo/dubbo-benchmark
```

No        | issues           | description     |  status     | pull request|
-----------|-----------|------------------|----------------|------------|
 | 1  | https://github.com/apache/incubator-dubbo/issues/2737   |  epoll  | done  | https://github.com/apache/incubator-dubbo/pull/2738 |
 | 2  |    |    |   |   |
 | 3  |    |    |   |   |
 | 4  |    |    |   |   |

**Comment by carryxyh** [comment]
Very meaningful thing. :)

**Comment by zonghaishang** [comment]
Performance optimization is a long-term process, I will collect mail optimization points and I will mention optimization points, listed here.

**Comment by carryxyh** [comment]
Related issue:https://github.com/apache/incubator-dubbo/issues/2295

**Comment by lovepoem** [comment]
add https://lists.apache.org/thread.html/3f5ee8f06308d9c0b58716380a2d15e0f55c362b67c6023fbc147bfa@%3Cdev.dubbo.apache.org%3E

**Comment by imsunv** [comment]
http://jm.taobao.org/2018/01/16/post180116/
How about this performance optimization for hessian
