### ISSUE TITLE
dubbo服务provider启动多个分组时，禁用不生效

### ISSUE THREAD

**Issue by crazyStar00** [apache/dubbo#2550]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: window 7
* Java version: java7

### Steps to reproduce this issue

1. 启动一个服务provider，分组为sg
2. 启动相同的服务provider，分组为cf
3. 启动consumer，分组设置为*，无限循环调用服务。
4.consumer调用时，从provider列表会取第一个provider进行调用。
5.当用admin控制台将第一个provider禁用后，仍然调用第一个consumer

**Comment by Super4You** [comment]
你好:
      1、不同分组是被标识为不同的服务，相当于 两个不同的服务你各自启动了一个
      2、Dubbo控制逻辑是必须保证有一个的可能的服务，也就是如果一种服务只有一个示例，控制台是无法 
            禁用的
      3、分组后的服务被识别为不同的服务，因此你无论你怎么禁用别的分组，调用的只能是跟你客户端配置 
            相同的分组服务
       不知道解释的对不对，希望能帮到你

**Comment by 653945222** [comment]
1. 可以理解了。
2. 当有启动一个服务没有group分组时，在admin页面禁止服务，consumer调用失败
3. 当启动一个服务有group分组时，在admin页面禁止服务，consumer调用成功。

**Comment by diecui1202** [comment]
@653945222 You can start 2 providers per group. Then disable one provider on ops, and check the invocation.

**Comment by 653945222** [comment]
@diecui1202 
1. 启动两个不同分组的provider，然后在ops里面禁用一个provider，consumer调用成功。
2. 启动两个不同分组的provider，然后在ops里面禁用两个provider，consumer调用成功。
