### ISSUE TITLE
The problem described below has occured two times in our product enviroment

### ISSUE THREAD

**Issue by runfriends** [apache/dubbo#2569]
the problem has occured two times, however the program could resume after restarting. 
- [ X ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ X ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: CentOS 6.9 kernel 2.6.32
* Java version:  1.8.0_51-b16

### *HEAP DUMP ANALYSIS*
The classloader/component "sun.misc.Launcher$AppClassLoader @ 0xc00009e0" occupies 218,169,664 (20.50%) bytes. The memory is accumulated in one instance of "java.lang.Object[]" loaded by "<system class loader>".

Class Name | Shallow Heap | Retained Heap
-- | -- | --
java.util.concurrent.ConcurrentHashMap$Node[65536] @ 0xef72bd20 | 262,160 | 206,175,368
table java.util.concurrent.ConcurrentHashMap @ 0xc1caa0f0 | 64 | 206,175,432
notified com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry @ 0xc0e90f00 | 104 | 287,488,568
this$0 com.alibaba.dubbo.registry.support.FailbackRegistry$1 @ 0xc0e91130 | 16 | 16
task java.util.concurrent.Executors$RunnableAdapter @ 0xc0e91118 | 24 | 40
<Java Local> java.lang.Thread @ 0xc0737418 DubboRegistryFailedRetryTimer-thread-1 Thread | 120 | 472
callable java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask @ 0xc0e910d0 » | 72 | 72
Total: 2 entries |   |  
registry com.alibaba.dubbo.registry.integration.RegistryDirectory @ 0xc1961620 » | 80 | 3,328
val$registry com.alibaba.dubbo.registry.integration.RegistryProtocol$1 @ 0xc1498860 » | 40 | 40
val$registry com.alibaba.dubbo.registry.integration.RegistryProtocol$1 @ 0xc165e460 » | 40 | 40
val$registry com.alibaba.dubbo.registry.integration.RegistryProtocol$1 @ 0xc1d449b8 » | 40 | 40
val$registry com.alibaba.dubbo.registry.integration.RegistryProtocol$1 @ 0xc25720b8 » | 40 | 40
Total: 6 entries |   |  

### *SOME THREAD STACK*
```
com.alibaba.dubbo.rpc.RpcException: No provider available from registry 172.16.0.128:2181 for service **SERVICE NAME HERE** on consumer 172.16.0.128 use dubbo version 2.6.0, may be providers disabled or not registered ?
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:572) ~[dubbo-2.6.0.jar:2.6.0]
	at com.alibaba.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:73) ~[dubbo-2.6.0.jar:2.6.0]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:265) ~[dubbo-2.6.0.jar:2.6.0]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:224) ~[dubbo-2.6.0.jar:2.6.0]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70) ~[dubbo-2.6.0.jar:2.6.0]
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51) ~[dubbo-2.6.0.jar:2.6.0]
	at com.alibaba.dubbo.common.bytecode.proxy7.queryId(proxy7.java) ~[dubbo-2.6.0.jar:2.6.0]

```

**Comment by Geker** [comment]
No provider 的情况下，ReferenceConfig创建失败，但是destory()时，dubbo没有清理已经注册到AbstractRegistry的属性notified属性的URL。导致内存泄漏。
private final ConcurrentMap<URL, Map<String, List<URL>>> notified = new ConcurrentHashMap<>();
可以失败时，反射主动进行清理。
