### ISSUE TITLE
the Test Case(org.apache.dubbo.test.Spring3CompatibilityTest）go wrong

### ISSUE THREAD

**Issue by SuperDubbo** [apache/dubbo#2576]
the Test Case(org.apache.dubbo.test.Spring3CompatibilityTest）go wrong,but i can't find the problem.
please solve it.

**Comment by carryxyh** [comment]
There are some unstable ut, I will look at it.
Can you provide a link to ci?

**Comment by amsqcsq** [comment]
你好，请问开发是拉去哪个版本

**Comment by diecui1202** [comment]
2.6.x is a maintained branch, master is the new branch holds new features.
3.x is new dubbo 3.0 branch.

**Comment by carryxyh** [comment]
@SuperDubbo 
I tried to run it and it did throw an exception.

I have already done this on the mailing list about the use of this type of information. You can post your opinion on the mailing list and keep track of the latest news:
https://lists.apache.org/thread.html/38d6303e5b1d0bf4311cf819705455690c6dff7bddfa260b069a8165@%3Cdev.dubbo.apache.org%3E

**Comment by carryxyh** [comment]
Of course, if you are willing to submit pr to fix it, it is also very welcome.
If you are interested, please reply to the email to let the community know and start working.
:)

**Comment by SuperDubbo** [comment]
I tried to fix it,but can not find the right way.:smile:
And I hope to keep it,do not delete it.
Do you have time to fix it?
@carryxyh

**Comment by carryxyh** [comment]
I will check it.

**Comment by SuperDubbo** [comment]
ok,I am doubt that the @DubboComponentScan annotataion seem take no effet to the provider,but take effet to the consumer.
I hope you can fix it soon. Thank You !@carryxyh
