### ISSUE TITLE
When Dubbo is measured with large load, the consumer spends much more time than the provider.

### ISSUE THREAD

**Issue by stoneapple** [apache/dubbo#2674]
不知道各位Dubbo的用户及官方的朋友，有没有遇到或者听过这样的例子。
提供方执行很快，但是消费方却需要很长的时间，有时候就直接超时了，提供方可能1s不到，消费方需要等到几十秒然后超时了，这个场景下gc，cpu看了都还好，之前有抓包提供方返回的报文在交换机上就很迟发出来了。
       有没有遇到相似的，或者有分析思路。

Translated from Google:

I don't know if you and Dubbo's users and official friends have encountered or heard such an example.
The provider performs very quickly, but the consumer takes a long time, sometimes it will time out directly, the provider may not be 1s, the consumer needs to wait for tens of seconds and then time out. In this scenario, gc, cpu read Fortunately, the packets returned by the packet capture provider were sent out late on the switch.
        Have you encountered similar, or have analytical ideas.

**Comment by cvictory** [comment]
I think you can give us a demo that can reproduce this issue.
That will be help us large time to reproduce this issue.

**Comment by jasonjoo2010** [comment]
Do you have the actually QPS for each method invocation?

If you have some `hot service` considering to separate it to a new connection with "connection".
Dubbo's single connection model is designed for small consumers compared with less providers. But if you suffered much heavy traffic on it you should try increasing the number of connections.

**Comment by beiwei30** [comment]
> 之前有抓包提供方返回的报文在交换机上就很迟发出来了。
这种情况优先看下两端的网卡，是不是已经打满，重传率高不高，等等

**Comment by zonghaishang** [comment]
1. 看抓包`sudo tcpdump -i any -vvvnnttttSs0 port 20880(端口) -w dump.pcap`
然后用wireshark分析报文，可以看到时间

2. 用arthas看下服务调用耗时，https://github.com/alibaba/arthas/blob/master/README_CN.md 和 https://alibaba.github.io/arthas/trace.html
