### ISSUE TITLE
可以实现动态添加和删除filter吗

### ISSUE THREAD

**Issue by shuohao** [apache/dubbo#2789]
目前添加和去掉自定义Filter需要项目启动前代码上设置filter或者"-"去掉，问下能否实现动态的添加和删除

**Comment by carryxyh** [comment]
应该是可以的。
通过修改zk上的url。

**Comment by bee06** [comment]
> 应该是可以的。
> 通过修改zk上的url。

不可以吧

**Comment by carryxyh** [comment]
这个我也不是很清楚。
我看了一下代码，修改url后会重新走一遍创建invoker的流程，当然也会重新用filter包装一遍invoker。这个有试过的可以在这边留言说一下到底是可以还是不可以。

**Comment by carryxyh** [comment]
@zonghaishang

**Comment by beiwei30** [comment]
我觉得可以的，不过也没试验。

**Comment by wuwu955** [comment]
原来那些自带的filter 可以不让他执行吗

**Comment by wuwu955** [comment]
扩展 telnet  命令看看 能不能实现

**Comment by qixiaobo** [comment]
Maybe you can extend a super filter to control your logic?

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
