### ISSUE TITLE
dubbo的扩展机制依赖注入使用的是按名称注入，而且还不支持spring的@Autowired注解

### ISSUE THREAD

**Issue by kinglcc** [apache/dubbo#285]
dubbo的扩展机制依赖注入使用的是按名称注入，而且还不支持spring的@Autowired注解。
这样使得扩展引入spring容器中的bean比较困难

**Comment by mercyblitz** [comment]
An interesting issue 👍

**Comment by mercyblitz** [comment]
It has been supported since 2.7.3
