### ISSUE TITLE
Questions can I controls the routing rules of overload methods?

### ISSUE THREAD

**Issue by violetgo** [apache/dubbo#2866]
can I controls the routing rules of overload methods? I wonder if Dubbo can support it. The details are as follows:

I have a hotspot service A, like this:

```
Interface A{

   public void hotMethod ();
   public void hotMethod (Object someParams);
   //other method
}
```

Then I need to refactor the Interface A,
Then it may have two different service versions until refactor is completed. (An old version will provide a method `hotMethod()` , and a new version will provide a method `hotMethod (Object someParams)`.)

Then I want all requests that call `hotMethod'(Object someParams)' to call the new version, and other requests to go to the old version. Can I implement this ?

**Comment by tswstarplanet** [comment]
Does it can route request based on parameters if the names of method are identical ?

**Comment by AlbumenJ** [comment]
Currently, this might not supported fully. Methods with the same name is not a good idea in traffic routing.

Close for long time no response. Please feel free to reopen if you have any question.
