### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.alibaba.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor

### ISSUE THREAD

**Issue by zfvipgit** [apache/dubbo#2869]
版本:2.6.5
采用注解的方式进行配置,提示找不到com.alibaba.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor
这个类,

原因:
ReferenceAnnotationBeanPostProcessor这个类继承了AnnotationInjectedBeanPostProcessor
但是AnnotationInjectedBeanPostProcessor这个类根本不存在

**Comment by vio-lin** [comment]
add this dependency
 
        <dependency>
            <groupId>com.alibaba.spring</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>1.0.2</version>
        </dependency>

**Comment by ted005** [comment]
helps a lot.

**Comment by Gaara13562** [comment]
express my heartfelt gratitude...

**Comment by kebukeyi** [comment]
oh.thanks to you very much

**Comment by jian1106** [comment]
springboot 3.0 does not have class `org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter`.

**Comment by jian1106** [comment]
Springboot 3.0 does not have class `org.springframework.beans.factory.config.InstantiationAwareBeanPostProcessorAdapter`.
