### ISSUE TITLE
Add daily average number of invocations to 'Who is using Dubbo' template

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo#2870]
Add daily average number of invocations to [Who is using Dubbo](https://github.com/apache/incubator-dubbo/issues/1012) template. 

This metric can help us learn more about how extensible our user is using Dubbo.

Of course, they can skip this if they want to.

**Comment by edwardlee03** [comment]
组织：挖财网络技术有限公司
地点：中国浙江杭州
联系方式：bert825_work@163.com
场景：服务管控与治理，单元化改造，动态链路/环境隔离
调用量：10亿级别
