### ISSUE TITLE
dubbo 消费者报错: cannot invoke any more

### ISSUE THREAD

**Issue by Knight-Wu** [apache/dubbo#2955]
你好, 想问下, 这个问题可能的原因是啥, 因为提供者服务正常, 而且消费者重启了仍然报这个错, 异常见截图
![11](https://user-images.githubusercontent.com/20329409/49926356-55d17380-fef6-11e8-92e5-85bb7caf0191.png)

**Comment by Knight-Wu** [comment]
指的报错的应用的日志吗，都是些业务日志呢，还是要应用启动的日志？

**Comment by Knight-Wu** [comment]
你好，是需要提供什么类型的日志呢

**Comment by tswstarplanet** [comment]
就是异常的日志，还有把jdk版本，dubbo版本这些环境信息也说一下

**Comment by wuhulala** [comment]
consumer  是在做单元测试吗？

**Comment by Knight-Wu** [comment]
@tswstarplanet jdk: 1.7.60, dubbo版本: 2.5.4, 但是在原生dubbo 上面做了一些集群容错的改动,只是新增了一些实现类和插件, 并没有改动dubbo 的代码,

**Comment by Knight-Wu** [comment]
@tswstarplanet 这个问题有遇到过吗, 想问下你们的思路, 有可能是什么触发了 destroy 的方法, 导致consumer 认为服务已经不可用了

**Comment by Knight-Wu** [comment]
@tswstarplanet 上面那个就是完整的异常栈了, 其他都是应用日志, 你是想看什么样的信息

**Comment by Knight-Wu** [comment]
@wuhulala  就是比如a b c 三台机器提供者, a 机器出现系统异常无法处理请求后, 剔除, 只重试 b c机器, 然后发请求包到a 的业务线程池, 直到a 正常才恢复调用

**Comment by AlbumenJ** [comment]
应该是剔除的时候将 invoker 关闭了

**Comment by AlbumenJ** [comment]
Please check if it still in the latest version.
