### ISSUE TITLE
config item in application-qa.properties cannot override config item in application.properties

### ISSUE THREAD

**Issue by fuhongwei041** [apache/dubbo#2985]
### Environment

* Dubbo version: 2.6.4
* Operating System version: linux
* Java version: 8
* Starter:0.1.1

### Steps to reproduce this issue

1. default config application.properties
2. add config application-qa.properties
3. java -jar xx.jar --spring.profiles.active=qa

config item in application-qa.properties cannot override config item in application.properties

**Comment by Bricks-Man** [comment]
Could you please update a demo on github?
