### ISSUE TITLE
Enhance the java doc of dubbo-cluster module

### ISSUE THREAD

**Issue by carryxyh** [apache/dubbo#2991]
Enhance the java doc of dubbo-cluster module.

Related project: https://github.com/apache/incubator-dubbo/projects/2

**Comment by carryxyh** [comment]
https://github.com/apache/incubator-dubbo/issues/2884

**Comment by carryxyh** [comment]
Seems like I can't assign to u because u are not a committer or a PMC.
I can't find u at the assignees list.
But u can direct do this and send pr. I will take a look. :)

**Comment by khanimteyaz** [comment]
No worries, I mark myself in this issue in comment secntion, so that we can avoid double spend.

**Comment by khanimteyaz** [comment]
@khanimteyaz working on it.

**Comment by danielamorais** [comment]
I'm not sure if this issue is been fixed but I can work on it if @khanimteyaz is not available. Let me know if I should try to work on other issues

**Comment by khanimteyaz** [comment]
Hi,
Please you start working on this.  Due to time crunch I am not able work on
this.  thanks for your cooperation.

**Comment by danielamorais** [comment]
I'll work on this

**Comment by carryxyh** [comment]
Very nice of u. @danielamorais 
Looking forward to your pr.
