### ISSUE TITLE
Enhance the java doc of dubbo-config module.

### ISSUE THREAD

**Issue by carryxyh** [apache/dubbo#2993]
Enhance the java doc of dubbo-config module.

Related project: https://github.com/apache/incubator-dubbo/projects/2

**Comment by carryxyh** [comment]
https://github.com/apache/incubator-dubbo/issues/2884

**Comment by lixiaojiee** [comment]
I can do this module

**Comment by carryxyh** [comment]
Ok, looking forward to your contribution.
