### ISSUE TITLE
Enhance the java doc of dubbo-plugin module.

### ISSUE THREAD

**Issue by carryxyh** [apache/dubbo#2998]
Enhance the java doc of dubbo-plugin module.

Related project: https://github.com/apache/incubator-dubbo/projects/2

**Comment by carryxyh** [comment]
https://github.com/apache/incubator-dubbo/issues/2884

**Comment by sfyumi** [comment]
I will work on this.

**Comment by carryxyh** [comment]
@sfyumi 
nice work! looking forward to it.
