### ISSUE TITLE
Enhance the java doc of dubbo-registry module.

### ISSUE THREAD

**Issue by carryxyh** [apache/dubbo#2999]
Enhance the java doc of dubbo-registry module.

Related project: https://github.com/apache/incubator-dubbo/projects/2

**Comment by carryxyh** [comment]
https://github.com/apache/incubator-dubbo/issues/2884

**Comment by Leishunyu** [comment]
I am learning this piece recently, I will gradually improve this comment.

**Comment by carryxyh** [comment]
Nice work.
Looking forward to it.

**Comment by Leishunyu** [comment]
you are good boy
