### ISSUE TITLE
Enhance the java doc of dubbo-rpc module.

### ISSUE THREAD

**Issue by carryxyh** [apache/dubbo#3001]
Enhance the java doc of dubbo-rpc module.

Related project: https://github.com/apache/incubator-dubbo/projects/2

**Comment by carryxyh** [comment]
https://github.com/apache/incubator-dubbo/issues/2884

**Comment by wangweiufofly** [comment]
I will try to enhance the java doc for the dubbo-rpc-api sub-module

**Comment by carryxyh** [comment]
@wangchangbing sure, looking forward to your contribution!
