### ISSUE TITLE
The official document has not been updated

### ISSUE THREAD

**Issue by liugdxd** [apache/dubbo#3012]
The official document has not been updated

**Comment by carryxyh** [comment]
Can u give some details?

**Comment by liugdxd** [comment]
for example
http://dubbo.apache.org/en-us/docs/user/demos/result-cache.html  
http://dubbo.apache.org/zh-cn/docs/user/demos/concurrency-control.html
http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html
http://dubbo.apache.org/zh-cn/docs/user/demos/logger-strategy.html
http://dubbo.apache.org/zh-cn/docs/user/demos/service-container.html 
...
Hyperlinks inside

**Comment by liugdxd** [comment]
http://dubbo.apache.org/zh-cn/docs/dev/principals/general-knowledge.html

**Comment by lovepoem** [comment]
Would you please send a pr ?

liugdxd <notifications@github.com> 于 2018年12月20日周四 下午9:10写道：
