### ISSUE TITLE
applcation.yml multi profile

### ISSUE THREAD

**Issue by smallAttr** [apache/dubbo#3014]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: Mac 10.14
* Java version: 1.8.0_172

### Steps to reproduce this issue
run my project and let's spring.profiles.active=prod. I find the address of zooKeeper is default value(zookeeper://127.0.0.1:2181) in application.yml. but I expected result is zookeeper://127.0.0.1:2182. about detail configuration. please see provider/src/main/resources/application.yml

github address: https://github.com/smallAttr/zk-dubbo-demo/tree/multi_profile

and printf load dubbo configuration as same as expected result:
dubbo configuration:CoreConfiguration(address=zookeeper://127.0.0.1:2182, client=zkclient)

![image](https://user-images.githubusercontent.com/17873796/50206590-d4bb2600-03a6-11e9-91df-977690f3f8fc.png)

**Comment by icankeep** [comment]
@smallAttr hello, there's not anything wrong when I run your demo project
![image](https://user-images.githubusercontent.com/39434627/120059792-3870cf80-c086-11eb-9404-c732e1a30e10.png)

**Comment by icankeep** [comment]
maybe you don't set active profile, just like this
![image](https://user-images.githubusercontent.com/39434627/120059816-6b1ac800-c086-11eb-9666-88ba3aebc154.png)

**Comment by icankeep** [comment]
this issue ha

**Comment by icankeep** [comment]
READY_TO_CLOSE
