### ISSUE TITLE
Invocation performance on consumer side turns bad under presure

### ISSUE THREAD

**Issue by jasonjoo2010** [apache/dubbo#3024]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: Centos 7
* Java version: 1.8

### Steps to reproduce this issue

For some time we found some performance jitter under some high loads points. Generally like the chart below (Figure 1) showing the latency on provider side didn't change much but latency on consumer side had a big deterioration.

> <img width="982" alt="Figure 1" src="https://user-images.githubusercontent.com/17573073/50273714-575ee680-0476-11e9-8559-bd54b4cbf08d.png">
> Figure 1

The count of providers in the figure 1 is 3 in three nodes. Each nodes has 4 cores and 16G.

We have tried:

* Check the nat gateway band width and connections monitor  
30MB/s max and less then 3000 connections. They don't hit the limit.
* Try to separate to a new connection for one service to see whether the problem is in ONE connection model.  
The chart is capture after that and issue continues.
* Check the tomcat thread pool usage  
Though i think it's irrelevant to the issue but i have integrated Sentinel to make sure the tomcat thread pool will not be full.
* Doubt if it's a vpc's performance problem (They are deployed in Aliyun.com) but we found similar issue in our IDC cluster as Figure 2.  
6 Providers deployed.

> <img width="976" alt="screen shot 2018-12-20 at 16 57 09" src="https://user-images.githubusercontent.com/17573073/50274475-516a0500-0478-11e9-8bb4-4b54929fc1c7.png">
> Figure 2

Now we are continue figuring out what the problem is. Did anyone hit this issue and kindly gives some advices?

Thanks

**Comment by beiwei30** [comment]
any update, any finding? @jasonjoo2010

**Comment by jasonjoo2010** [comment]
> any update, any finding? @jasonjoo2010

It's complicated and several factors affect this. For example TCP congestion in OS layer and link layer take a role here. It still a continuous optimizing thing now. I will pay back a new issue if i find something that can be optimized in dubbo.
