### ISSUE TITLE
The Document about dubbo consumer  setting   not updated

### ISSUE THREAD

**Issue by 9526xu** [apache/dubbo#3025]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

When I browse this issue [Dubbo-2013 ](https://github.com/apache/incubator-dubbo/pull/2114),I found 「dubbo:consume」 more attributes。But in the official documentation [dubbo-consume](https://dubbo.incubator.apache.org/zh-cn/docs/user/references/xml/dubbo-consumer.html), it is not updated

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by carryxyh** [comment]
Hi, @9526xu 
Would u like send a pull request to fix them?

**Comment by 9526xu** [comment]
Yes，I will fix it and send it。 @carryxyh

**Comment by CrazyHZM** [comment]
The address has expired, please refer to the latest address：https://dubbo.apache.org/zh/docs/
