### ISSUE TITLE
2.6.5  For input string: "" BUG

### ISSUE THREAD

**Issue by gfj7817** [apache/dubbo#3033]
if i have a jar name = test.jar
when java -jar test.jar , this service (test.jar) cannot invoking other Provider（2.6.5）
but java -jar test-2.5.10.jar , this service (test.jar) can invoking other Provider（2.6.5）
because 
![655ccadb-f7d2-4a4f-a986-76ad5ad13cf2](https://user-images.githubusercontent.com/33675358/50306763-59a25e80-04d1-11e9-9e8b-9c569b69dc51.png)

please next version fix.

**Comment by hemanshu070** [comment]
I I'm new but I think I can fix this if you walk me through the issue.

**Comment by beiwei30** [comment]
I have no idea on reporter's point, @chickenlj could you pls. take a look?

**Comment by AlbumenJ** [comment]
Please check if it still exist in the latest version.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
