### ISSUE TITLE
Annotation can not work with multi-registries circumstances when using Config Center in 2.7.0.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#3047]
For example, there are two registries configured in remote Config Center:
```properties
dubbo.registries.registry1.address=zookeeper://127.0.0.1:2181
dubbo.registries.registry2.address=zookeeper://127.0.0.1:2182
```

If we want to use `registry1` as the registry for one service `DemoService`,  we can easily figure out  how to achieve that without Config Center, that is, explictly specify the registry that should be used in @Service, like this:
```java
@Service(registry="registry1")
public class DemoServiceImpl implements DemoService{
}
```
However, it just failed to work, simply because there's no Spring Bean named `registry1`.

**Comment by tswstarplanet** [comment]
I will try to fix it

**Comment by khanimteyaz** [comment]
@chickenlj if you fine then I would like to work on this. do let me know your thought?

**Comment by chickenlj** [comment]
@khanimteyaz Sorry, are you still on this? It would be great if you'd like to look at it.

I know @mercyblitz is an expert on this kind of issue, and he helped did most of the works on Spring integration.

**Comment by khanimteyaz** [comment]
@chickenlj thanks for your reply. I was planning to work on this, once I have completed my UT for dubbo-config-sprint BeanService. Due to some urgent work on I might be less involve this and next week. So I would suggest if some one can take this one would be better otherwise once I am free will take it up.
What do you say?

**Comment by chickenlj** [comment]
Thanks, please feel free to deal with your work first.

Let's see what @mercyblitz say about this issue.

**Comment by chickenlj** [comment]
You can try to see the problem I am describing here by running this sample: https://github.com/chickenlj/dubbo-samples/tree/multi-registries-annotation/dubbo-samples-configcenter/dubbo-samples-configcenter-multi-registries

https://github.com/chickenlj/dubbo-samples/blob/e5dcf0f378b3b2dd32eee89b54993af66534262d/dubbo-samples-configcenter/dubbo-samples-configcenter-multi-registries/src/main/java/org/apache/dubbo/samples/configcenter/multiregistries/impl/AnnotationServiceImpl.java#L28

**Comment by mercyblitz** [comment]
It has been supported
