### ISSUE TITLE
Handling timeouts and network timeouts separately

### ISSUE THREAD

**Issue by HouZhiHouJue** [apache/dubbo#3060]
There is a difference between timeout and network timeout. In FailoverClusterInvoker, whether it is timeout or network timeout, it is ignored. If it is a business timeout, then two retry attempts will cause an avalanche effect. In FailfastClusterInvoker, there is no fault tolerance for network timeouts. If it is a network partition, the SLA will inevitably fall. I think the implementation of these two Invokers must include the processing of the network timeout, otherwise the implementation is not correct.

- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: centos 7.2
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by lexburner** [comment]
A nice suggestion to me.

**Comment by Kiddinglife** [comment]
@HouZhiHouJue  I think you are right. I posted another issue which looks similar to your one. the dubbo has provided the upper user the exact error code for different failing reasons. you can go there and check if there is the one you are looking forward to.
[issue](https://github.com/apache/incubator-dubbo/issues/3215)
regards.
