### ISSUE TITLE
serialization argument error with kryo , then nothing output~

### ISSUE THREAD

**Issue by gMan1990** [apache/dubbo#3079]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: xxx
* Java version: xxx
* netty 4.1.23

### Steps to reproduce this issue

0. protocol=dubbo, server=netty4
1. mock a exception at (like serialization argument error with kryo)
https://github.com/apache/incubator-dubbo/blob/6ce7b11f982c5f7beb2ac5897fb33d48da357ada/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboCodec.java#L189
2. throw up at
https://github.com/netty/netty/blob/8c549bad3821f9b63f2313b83a15c531e94dfaf0/codec/src/main/java/io/netty/handler/codec/MessageToByteEncoder.java#L107
3. catch then throw EncoderException at
https://github.com/netty/netty/blob/8c549bad3821f9b63f2313b83a15c531e94dfaf0/codec/src/main/java/io/netty/handler/codec/MessageToByteEncoder.java#L125

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

logger the exception

### Actual Result

nothing output

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
---
中文吧，英文写不下去了🤣，这里说加ChannelFutureListener就可以，但我不会（ChannelFutureListener类里有一些常量不知道可用不
https://github.com/netty/netty/issues/8688

**Comment by beiwei30** [comment]
@gMan1990 didn't catch your point, would you mind to provide a reproducer ((a simple app to reproduce this issue)) on github?

**Comment by gMan1990** [comment]
@beiwei30 中文来一遍
1. 消费端配置protocol=dubbo, server=netty4
2. 运行起来，就会发送请求，执行到这句
https://github.com/apache/incubator-dubbo/blob/6ce7b11f982c5f7beb2ac5897fb33d48da357ada/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DubboCodec.java#L189
会调用具体的serialization来序列化，特别的情况会产生异常的，比如请求参数是一个HibernateProxy，然后用kryo，就会异常 https://github.com/magro/kryo-serializers/issues/104
3. 然后会throw到
https://github.com/netty/netty/blob/8c549bad3821f9b63f2313b83a15c531e94dfaf0/codec/src/main/java/io/netty/handler/codec/MessageToByteEncoder.java#L107
4. 然后被catch然后throw EncoderException
https://github.com/netty/netty/blob/8c549bad3821f9b63f2313b83a15c531e94dfaf0/codec/src/main/java/io/netty/handler/codec/MessageToByteEncoder.java#L125

---
3, 4多余的，自己调试就可以了。就是说序列化可能会出现异常，但是dubbo创建的netty4的实例把异常吞掉了，没有报错，控制台一点信息没有，一直到timeout.
netty4那边说https://github.com/netty/netty/issues/8688 ，加个ChannelFutureListener？你来看看

**Comment by xiaoheng1** [comment]
Personal opinion, the probability of abnormal serialization components is small.
If this happens, it would be better for us to fix the corresponding serialization component to solve this problem.

**Comment by goodjava** [comment]
Can you push the demo project to git?

**Comment by AlbumenJ** [comment]
Close for long time no response. You can try verify this in Dubbo 2.7
