### ISSUE TITLE
[suggestion] Seperate Constants.java into some SubConstants Class

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#3137]
Currently we manage out constants values in org.apache.dubbo.common.Constants.java.  

This class is very bloated and this structure is not well enough.  Maybe we should categorize such constants into groups. In this way , we can add some XxxConstants, such as RegistryConstants,ConfigCenterConstants etc.   It'd be better if it is split by module of dubbo-core.

**Comment by CrazyHZM** [comment]
@cvictory  
Is there a plan for this suggestion? If there is no plan, I plan to start doing this in the near future.

**Comment by beiwei30** [comment]
@CrazyHZM pls. take a look at #4017. I've finished step1.

- step2, we need to create multiple **Constants** in dubbo-common module.
- step3, start to reference new **Constatns** one by one.
- step4, delete old **Constants**
- step5, examine each new **Constants** and evaluate if they are more suitable to move out from dubbo-common into its delegated module, say: org.apache.dubbo.common.serialize.Constants to dubbo-serialization-api

**Comment by CrazyHZM** [comment]
@beiwei30 
I think this step is good, I am responsible for doing the remoting, rpc, config parts, I will start with remoting

**Comment by beiwei30** [comment]
will you do it based on the current pull request, or wait until it's merged?

**Comment by CrazyHZM** [comment]
Wait until after being merged

**Comment by beiwei30** [comment]
@CrazyHZM #4017 is merged. pls. start to move constants into **constants** sub package first. In this step, let's don't touch org.apache.dubbo.common.Constants **untouched**.

**Comment by beiwei30** [comment]
FYI, the first new constant class I created is: org.apache.dubbo.common.constants.CommonConstants

**Comment by CrazyHZM** [comment]
I created 
org.apache.dubbo.common.constants.RemotingConstants、
org.apache.dubbo.common.constants.RpcConstants and org.apache.dubbo.common.constants.ConfigConstants.

**Comment by beiwei30** [comment]
@CrazyHZM see #4019 4020

**Comment by CrazyHZM** [comment]
@beiwei30 
step2 #4021

**Comment by beiwei30** [comment]
> @beiwei30
> step2 #4021

I left my comment. Would you mind to review mine too?

**Comment by CrazyHZM** [comment]
> @CrazyHZM see #4020

I will merge it when I pass ci

**Comment by beiwei30** [comment]
I think we can now move to step3.

**Comment by CrazyHZM** [comment]
I will start modifying the remoting later.

**Comment by beiwei30** [comment]
so, now we should move to step4, start to review any constants suitable to move back to its own module.

**Comment by CrazyHZM** [comment]
Add comments first or move directly

**Comment by beiwei30** [comment]
if you are pretty sure it should be move into individual module, just do it, and let's review :)

**Comment by CrazyHZM** [comment]
ok,I will start to review remoting part.

**Comment by beiwei30** [comment]
@CrazyHZM FYI, I am on remoting.

**Comment by CrazyHZM** [comment]
@beiwei30 
I will start the fourth step of config.

**Comment by cvictory** [comment]
You can continue to work at this in dubbo-2.7.3
