### ISSUE TITLE
CompletableFuture<T> support for GenericService.

### ISSUE THREAD

**Issue by xcorpio** [apache/dubbo#3163]
泛化调用中
```java
public interface GenericService {

    Object $invoke(String method, String[] parameterTypes, Object[] args) throws GenericException;

}
```
这里可不可以异步调用返回个Future。我的工具实现会有多个 `ReferenceConfig` 缓存，我可以单独再用一个线程池来作为 `$invoke` 的执行上下文。但每个 `ReferenceConfig` 好像都有一组线程来维持，这个本身能不能异步调用？

**Comment by xcorpio** [comment]
OK，期待...

**Comment by manzhizhen** [comment]
I was suddenly more curious at the time that the GenericService did not implement asynchronous calls? Haha

**Comment by xiangxiuhui** [comment]
> 应该是可以的，不过我需要验证一下效果，但是需要改造一下GenericService接口。
> 可能将来会长这样：
> 
> ```
> public interface GenericService {
> 
>     Object $invoke(String method, String[] parameterTypes, Object[] args) throws GenericException;
> 
>     CompletableFuture<Object> $invokeAsync(String method, String[] parameterTypes, Object[] args) throws GenericException;
> }
> ```
 
 oninvoke、onreturn、onthrow 也要支持下 GenericService
例如下面判断：
        final Method onInvokeMethod = (Method) StaticContext.getSystemContext().get(StaticContext.getKey(invoker.getUrl(), invocation.getMethodName(), Constants.ON_INVOKE_METHOD_KEY));
        final Object onInvokeInst = StaticContext.getSystemContext().get(StaticContext.getKey(invoker.getUrl(), invocation.getMethodName(), Constants.ON_INVOKE_INSTANCE_KEY));

**Comment by chickenlj** [comment]
> public interface GenericService {
> 
>     Object $invoke(String method, String[] parameterTypes, Object[] args) throws GenericException;
> 
>     CompletableFuture<Object> $invokeAsync(String method, String[] parameterTypes, Object[] args) throws GenericException;
> }

Is there any progress on this feature?

**Comment by carryxyh** [comment]
@chickenlj 
Hi, I am very sorry that I have been procrastinating for a long time. 
I will try to solve this problem this week. If it's more complicated, I'll discuss a scenario on the mailing list.

**Comment by chickenlj** [comment]
@carryxyh No hurry, if you don't get enough time maybe I can give it a try. Just make sure we don't spend too much time repeating this issue.

**Comment by carryxyh** [comment]
Simple pr for this issue: 
https://github.com/apache/incubator-dubbo/pull/3637

Would u pls have a review?

**Comment by chickenlj** [comment]
I am on it.
