### ISSUE TITLE
about the ls command of Qos and telnet,do we need to show the methods and thire parameter types？

### ISSUE THREAD

**Issue by kexianjun** [apache/dubbo#3172]
I have noticed that current ls command of Qos and Telnet.there is currently no way to get all the methods and their parameter types of the services,do we need this functionality? as shown below.
![image](https://user-images.githubusercontent.com/12162539/50871193-e025ce00-13f5-11e9-99dc-9feb8fef2ad6.png)

**Comment by CrazyHZM** [comment]
`ls -l XxxService`  This command can find the parameter type
