### ISSUE TITLE
dubbo线上运行服务端java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ylylc** [apache/dubbo#3176]
1、项目运行过程中，网络无变化突然出现，导致所以请求都收不到。错误信息

com.nbs.agent.plugin.dubbo20.NettyChannelUtil.reportAsExternal(Ljava/lang/Object;Z)V

2、trace:

com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send | (NettyChannel.java)
-- | --
com.alibaba.dubbo.remoting.transport.AbstractPeer.send | (AbstractPeer.java:51)
com.alibaba.dubbo.remoting.exchange.support.header.HeartbeatHandler.received | (HeartbeatHandler.java:68)
com.alibaba.dubbo.remoting.transport.MultiMessageHandler.received | (MultiMessageHandler.java:28)
com.alibaba.dubbo.remoting.transport.AbstractPeer.received | (AbstractPeer.java:123)
com.alibaba.dubbo.remoting.transport.netty.NettyHandler.messageReceived | (NettyHandler.java:91)
org.jboss.netty.channel.Channels.fireMessageReceived | (Channels.java:302)
com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived | (NettyCodecAdapter.java:148)
org.jboss.netty.bootstrap.NettyDispatcher.upstreamDispatcher | (SourceFile:51)
org.jboss.netty.bootstrap.NettyDispatcher.handleUpstream | (SourceFile:32)
org.jboss.netty.channel.Channels.fireMessageReceived | (Channels.java:274)
org.jboss.netty.channel.Channels.fireMessageReceived | (Channels.java:261)
org.jboss.netty.channel.socket.nio.NioWorker.read | (NioWorker.java:349)
org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys | (NioWorker.java:280)
org.jboss.netty.channel.socket.nio.NioWorker.run | (NioWorker.java:200)
java.util.concurrent.ThreadPoolExecutor.runWorker | (ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run | (ThreadPoolExecutor.java:617)
java.lang.Thread.run | (Thread.java:745)

**Comment by ylylc** [comment]
看着像jar冲突！项目运行中怎么会突然出现这个。在前一分钟还能调用的

**Comment by xishian** [comment]
dubbo 的传递依赖还是netty3 :-(

**Comment by AlbumenJ** [comment]
Close for long time no response. Please feel free to reopen if you have any question.
