### ISSUE TITLE
zk宕机一段时间后，dubboAdmin显示服务被禁用了

### ISSUE THREAD

**Issue by rayjie** [apache/dubbo#3200]
zk宕机一段时间，大约15分钟，去dubboAdmin看到服务被禁用了，在重启zk后仍然是禁用状态，导致服务不可用。

### 环境
- dubbo版本
`		
			<groupId>com.alibaba.boot</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>0.2.0</version>
		`
- spring boot版本 
2.0.4.RELEASE

**Comment by Kiddinglife** [comment]
> i found my dubbo admin did not work 15 minutes later my zk dead. i quickly restart zk but dubbo admin still did not work.
dubbo version
<groupId>com.alibaba.boot</groupId> <artifactId>dubbo-spring-boot-starter</artifactId> <version>0.2.0</version>
spring boot version
2.0.4.RELEASE

Hi @rayjie,
I think it is a quite natural thing that dubbo admin becomes unavailable after zk dead.
Try to setup zk cluster to avoid such issue in the future.

let me know how you think about it.
regards.

**Comment by manzhizhen** [comment]
"It is still disabled after restarting zk, causing the service to be unavailable." Is it normal to check the communication after restarting zk? How long is the service or disabled after the restart is successful? In general, dubbo and the registration center have the reconnection function. After the zk is restored, it will be re-registered.

“在重启zk后仍然是禁用状态，导致服务不可用。” 重启zk后检查了通讯方面是正常的吗？重启成功后多长时间服务还是禁用状态？一般来说dubbo和注册中心有重连功能，发现zk恢复后，会进行重新注册。

**Comment by Kiddinglife** [comment]
Hi @manzhizhen,
I suspect @rayjie did not setup zk cluster. And after the leader zk node was down, the zk client reconnects several times and finally gives it up with returning an exception to dubbo framework.

hi @rayjie , plz setup zk cluster and let us know how it is going on.
regards.

**Comment by rayjie** [comment]
> "It is still disabled after restarting zk, causing the service to be unavailable." Is it normal to check the communication after restarting zk? How long is the service or disabled after the restart is successful? In general, dubbo and the registration center have the reconnection function. After the zk is restored, it will be re-registered.
> 
> “在重启zk后仍然是禁用状态，导致服务不可用。” 重启zk后检查了通讯方面是正常的吗？重启成功后多长时间服务还是禁用状态？一般来说dubbo和注册中心有重连功能，发现zk恢复后，会进行重新注册。

谢谢你的回复，zk是集群的，当时运维操作是”轮流重启zk修改zookeeper连接数限制，增加对每个ip限制的数量“。事后我查看了应用的日志，在zk恢复后是有重新建立连接的。还有一点，此次受影响的服务只有是用了这个版本的受影响，使用dubbox2.8.4（当当网的一个版本）的服务未受影响。我在本地搭建了一套这个服务模拟zk宕机并未重现该情况，目前正在跟运维商量在开发环境重复当时线上的操作，待后续有结果我再同步。
