### ISSUE TITLE
关于用注解方式  @Reference注入，dubbo服务对象为null的问题

### ISSUE THREAD

**Issue by yaodongfei** [apache/dubbo#3201]
@Reference(version = "1.0.0", check = false, lazy = true,mock = "")
在此方式启用了mock参数注入，dubbo服务就会为null。去掉，是可以正常注入的。

**Comment by yaodongfei** [comment]
依赖dubbo版本  <dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>0.2.0</version>
		</dependency>

**Comment by Kiddinglife** [comment]
Hi @yaodongfei,
Can you give more details about your source codes?
regards.

**Comment by AlbumenJ** [comment]
This has been fix in the latest version.

Close for long time no response. Please feel free to reopen if you have any question.
