### ISSUE TITLE
will dubbo support opentracing? when?

### ISSUE THREAD

**Issue by limfriend** [apache/dubbo#3209]
open tracing become more and more popular.  we can find a lot of framework which is support  opentracing, e.g  grpc, thrift, okhttp, kafka, redis, jdbc, spring boot..
https://github.com/opentracing-contrib?utf8=%E2%9C%93&q=&type=&language=java

**Comment by ralf0131** [comment]
Hi,

Thanks for raising this issue, for now Dubbo support tracing framework like Zipkin, Skywalking and  Spring Cloud Sleuth, I think supporting opentracing should be as straight-forward as they are. 

The principal here for Dubbo is that we should embrace the standards. If you or someone would like to contribute, we will be very happy.

**Comment by Kiddinglife** [comment]
@limfriend  
Hi mate, 
the current tracing of dubbo is good enough in most of cases. 
Can you please highlight the reason why you desire to move to opentracing? Does it have some features that overwheel others?
regards.

**Comment by maxiaoguang64** [comment]
I have some experience in opentracing.
I want to try it.

**Comment by ralf0131** [comment]
@maxiaoguang64 Great, please feel feel to go ahead.

**Comment by maxiaoguang64** [comment]
@ralf0131 I want to add a sub project dubbo-filter-opentracing in dubbo-filter.
if user want to use trace implement opentracing, only need to call GlobalTracer.register(tracer).

**Comment by ralf0131** [comment]
@maxiaoguang64 Please ahead with your implementation, about where should the code go, I am not quite sure we should put that in the core Dubbo repository in external repository, would you please subscribe and send email to dev@dubbo.apache.org to discuss with the community? 
You can refer to this [guide](http://dubbo.apache.org/zh-cn/docs/developers/contributor-guide/mailing-list-subscription-guide_dev.html) to subscribe the mailing list.

**Comment by maxiaoguang64** [comment]
@ralf0131 It's only a filter that implement org.apache.dubbo.rpc.Filter and use opentracing api.

**Comment by Kiddinglife** [comment]
@maxiaoguang I believe so, mate. I will try it when you are done. Lol.

**Comment by maxiaoguang64** [comment]
@ralf0131 I send a mail to discuss with this, but i didn't get any reply.
can we disscus with github?

**Comment by ralf0131** [comment]
@maxiaoguang64 I've replied your email. I think you can go ahead with your implementation. What need to be discussed is where should the code be placed.

**Comment by ralf0131** [comment]
Hi @maxiaoguang64 Any update on this issue?
