### ISSUE TITLE
Can dubbo provide api to change underlying component after the application has launched ?

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#3214]
Dubbo provider its own spi  mechanism to let user configure and extend it. But it works during the application is launching. Can the framework provider api to change them after launching. 
For example, we can change registry of some services by api when the environment changes.

**Comment by Kiddinglife** [comment]
Hi @tswstarplanet,
Are you expecting something like dynamic loading of the extended component at runtime?
regards.

**Comment by tswstarplanet** [comment]
@Kiddinglife Thanks for the response, I think it is like that you said. I think if the underlying component like registry can be replace after the starting up of an application, it can be more flexible.
