### ISSUE TITLE
Why not convert dubbo's futrue to callback

### ISSUE THREAD

**Issue by complone** [apache/dubbo#3314]
Since dubbo's ```futrue``` is to determine which provider is forwarded to the``` Comnsumer```, the dubbo ```callback``` function exists to solve the request to send the corresponding service, so why not directly translate``` furtrue``` into a callback?

Refernce: https://blog.csdn.net/u010317829/article/details/52151896

Doc: http://dubbo.apache.org/zh-cn/docs/dev/design.html

**Comment by complone** [comment]
Since the underlying dubbo is also based on netty, I think we should make full use of the futrue/promise mode to give network performance optimization problems to netty.

The reason why dubbo uses futrue for asynchronous calls, isn't it because of the NIO mechanism?

**Comment by complone** [comment]
> Since the underlying dubbo is also based on netty, I think we should make full use of the futrue/promise mode to give network performance optimization problems to netty.
> 
> The reason why dubbo uses futrue for asynchronous calls, isn't it because of the NIO mechanism?

https://www.cnblogs.com/tiancai/p/9573912.html

**Comment by complone** [comment]
I have seen that the return value of callback is handled in Dubbo 2.7 using the JDK native interface.

**Comment by CrazyHZM** [comment]
CompletedFuture is supported in the new version.
