### ISSUE TITLE
是否在服务注册处提供spi扩展机制用于自定义注册信息如一些权限信息等

### ISSUE THREAD

**Issue by fireflyhoo** [apache/dubbo#3343]
### Environment

* Dubbo version: 任意版本
* Operating System version: 任意操作系统
* Java version:  1.5+

### Steps to reproduce this issue
当前dubbo没有提供针对服务注册的spi扩展机制,如果想针对服务注册进行自定义特性实现非常不方便,比如,我们针对部分dubbo服务加调用权限,这些需求, 比如我们想把服务方法的参数签名加到注册信息上.

希望官方对此进行支持.

**Comment by LiZhenNet** [comment]
目前可以通过Filter 来实现权限控制

**Comment by fireflyhoo** [comment]
> 目前可以通过Filter 来实现权限控制

我想要的是在注册信息上附加我自定义的一些参数.

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it
