### ISSUE TITLE
[Cond optimization]Behavior of annotations and xml config should keep consistent

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#3357]
**I found some corresponding annotation and xml config have inconsistent behavior.**
**What I mean is that some required properties in xml config are not required in comparable annotation configs.** For example, the interface property is required in <dubbo:service /> config. But interfaceClass or interfaceName of @Service annotation is not required. 
**I think it is not a good design. We should make them have consistent behavior because it can make processing of config clearer and simpler.**

**Comment by mercyblitz** [comment]
Fixed.
