### ISSUE TITLE
泛化调用生成的ReferenceConfig，在服务提供者异常的时候调用destory并不能释放zk链接等资源

### ISSUE THREAD

**Issue by FancyKong** [apache/dubbo#3369]
复现步骤：
1. 将服务提供者全部实例禁用
2. 触发该服务提供者的链接建立
3. 建立失败
4. 尝试回收该链接的资源
5. 回收失败

**Comment by FancyKong** [comment]
/**
     * 连接消费服务
     *
     * @param config
     * @return
     */
    public GenericService genericService(GenericServiceConfig config) {
        ReferenceConfig<GenericService> referenceConfig = buildReferenceConfig(config);
        GenericService genericService = getServiceFromCache(referenceConfig);
        if (genericService != null) {
            return genericService;
        } else {
            log.info("该config对应的泛化服务不存在， config = {}", config);
            closeConsumer(config);
            return null;
        }
    }

/**
     * 关闭消费某个服务
     *
     * @param config 泛化服务配置
     */
    public void closeConsumer(GenericServiceConfig config) {
        ReferenceConfigCache cache = ReferenceConfigCache.getCache();
        cache.destroy(buildReferenceConfig(config));
    }

**Comment by xiaoheng1** [comment]
can you provider a demo?

**Comment by AlbumenJ** [comment]
Close for long time no response. Please try check in the latest version.
