### ISSUE TITLE
class comment error in OverrideConfigurator 

### ISSUE THREAD

**Issue by hjq2016** [apache/dubbo#3385]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1.open dubbo-cluster project；
2.go into package (com.alibaba.dubbo.rpc.cluster.configurator.override)
3.see class comments.
4. the content is "AbsentConfigurator",error.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

/**
 * OverrideConfigurator
 *
 */
public class OverrideConfigurator extends AbstractConfigurator {

    public OverrideConfigurator(URL url) {
        super(url);
    }

    @Override
    public URL doConfigure(URL currentUrl, URL configUrl) {
        return currentUrl.addParameters(configUrl.getParameters());
    }

}

### Actual Result

/**
 * AbsentConfigurator
 *
 */
public class OverrideConfigurator extends AbstractConfigurator {

    public OverrideConfigurator(URL url) {
        super(url);
    }

    @Override
    public URL doConfigure(URL currentUrl, URL configUrl) {
        return currentUrl.addParameters(configUrl.getParameters());
    }

}

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
Can you submit a PR to fix it?

**Comment by hjq2016** [comment]
> Can you submit a PR to fix it?

Do you have tutorial link that guide me how to sumbim a PR?

**Comment by CrazyHZM** [comment]
> > 你能提交公关来解决它吗？
> 
> 你有教程链接，指导我如何总结公关？


You can refer to this connected tutorial
https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md

**Comment by CrazyHZM** [comment]
> > Can you submit a PR to fix it?
> 
> Do you have tutorial link that guide me how to sumbim a PR?

You can refer to this connected tutorial
https://github.com/apache/incubator-dubbo/blob/master/CONTRIBUTING.md

**Comment by Moriadry** [comment]
@CrazyHZM hi, this issue can be closed now.
