### ISSUE TITLE
dubbbo 2.6.5 & Webservice

### ISSUE THREAD

**Issue by schdai** [apache/dubbo#3411]
I use dubbo 2.6.5 and cxf 3.2.5, when I pubish a serivce like this 
<dubbo:protocol name="webservice" port="8080"	server="servlet" />

there is lost code in the generated wsdl when I browse the wsdl in IE or  Firefox using url like http://..../demoservice?wsdl.
so calling the webmethod in soap will result in failure because of loss of <soap:address bind=...> in wsdl
but in buddo 2.5.3 + cxf  2.7.7 , it's ok.

**Comment by CrazyHZM** [comment]
refer #1655
Is it the same as yours?

**Comment by schdai** [comment]
thank you for your reply.
the sourcecode url is https://github.com/schdai/dubbo-webservice.git

the wsdl address:   http://localhost:8080/dubbo-webservice/services/DubboService?wsdl

and there is noting under port element, it should exists if you use dubbo 2.5.3 & cxf 2.7.7
<wsdl:service name="DubboService">
<wsdl:port binding="tns:DubboServiceSoapBinding" name="DubboServicePort">
    </wsdl:port>
</wsdl:service>

**Comment by schdai** [comment]
refer #1655    is the same result with mine.  but under dubbo 2.5.3 + cxf 2.7.7, everything is ok.
