### ISSUE TITLE
Fluent -style builder API support.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#3431]
I am thinking of providing a fluent -style builder API built on ServiceConfig, ReferenceConfig, ...
It may work like this:
```java
ApplicationConfig applicationConfig = ApplicationBuilder.name("demo").build();

ServiceConfig serviceConfig = ServiceBuilder.ref(ref).timeout(1000).build();
ReferenceConfig referenceConfig = ReferenceBuilder.interface("interface name").timeout(2000).build();

DubboBuilder dubboBuilder = DubboBuilder.application(applicationConfig).registry(registryConfig).protocol(protocol);

// To trigger the export/refer process, you can just start dubboBuilder
dubboBuilder.services(Arrays.asList(serviceConfig)).references(Arrays.asList(referenceConfig)).start();
// Or, you can export/refer one specific Service or Reference
dubboBuilder.export(serviceConfig);
dubboBuilder.refer(referenceConfig);
```

At present, one of the problems of using ServiceConfig and ReferenceConfig directly is that some application-level configurations need to be set to each ServiceConfig or ReferenceConfig, which is redundant, unnecessary and inconvenient for users
```java
ApplicationConfig application = new ApplicationConfig();

ServiceConfig serviceConfig1 = new ServiceConfig();
serviceConfig1.setApplication(application);
serviceConfig1.export();

ServiceConfig serviceConfig2 = new ServiceConfig();
serviceConfig2.setApplication(application);
serviceConfig2.export();
```

**Comment by chickenlj** [comment]
ConfigManager can work as the basis for the Builder: https://github.com/apache/incubator-dubbo/blob/master/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/context/ConfigManager.java

**Comment by xxlv** [comment]
Cool,I love it

**Comment by Kiddinglife** [comment]
nice

**Comment by tswstarplanet** [comment]
I think the export and refer method of DubboBuilder can provider overload methods such as
```java
DubboBuilder.export(ServiceConfig service,  ProviderConfig provider, RegistryConfig registry)
java
if users would like to refer specific config to a service or a reference. They can config by themselves.

**Comment by chickenlj** [comment]
>DubboBuilder.export(ServiceConfig service,  ProviderConfig provider, RegistryConfig registry)
java
if users would like to refer specific config to a service or a reference. They can config by themselves.

I would suggest providing the service-restricted configs using ServiceConfig:
`ServiceConfigBuilder.provider(The ProviderConfig).registry(The RegistryConfig).build()`

What do you think? @tswstarplanet

**Comment by chickenlj** [comment]
Is there anyone who's interested and want to give it a try?

**Comment by tswstarplanet** [comment]
Yes, it looks good. We should also limit reproduction of global configs, such as application.

**Comment by Bricks-Man** [comment]
I want to try this issue.And I will commit a pr after serveral days

**Comment by chickenlj** [comment]
> Yes, it looks good. We should also limit reproduction of global configs, such as application.
Yes, the `ConfigManager` introduced in 2.7.0 can achieve that, but it may have some room for improvement.

**Comment by chickenlj** [comment]
@Bricks-Man Awesome, please let me know if you have any problem.

**Comment by chickenlj** [comment]
Further thought on this topic. 
A unified entry like `DubboBuilder.start()` can help us with:
1. Application level rules. You may have noticed of some application level rules introduced in 2.7.0.  The rules are fetched and watched inside each Service, I think it would be better if we can have an application level place to do that.
2. Adapting to microservice architecture. The microservice model is one microservice per process which is different from Dubbo's interface level service model. A unified entry would make the application level service discovery model more easily achieved.

**Comment by Bricks-Man** [comment]
@chickenlj I have finished this issue.Could you have time to do a review for it?Please tell me if you have any question.

**Comment by wuhulala** [comment]
so cool

**Comment by cvictory** [comment]
#3661
