### ISSUE TITLE
Method config should be checked when using generic invoke

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#3436]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1-SNAPSHOT
* Operating System version: all
* Java version: all

### Steps to reproduce this issue

1.config a reference using generic invoke
2.config method of the reference with a name that is not contained by the interface(not the GenericService, but the real service that is invoked)

Pls. provide [GitHub address] to reproduce this issue.

What do you expected from the above steps？

report error of no such method

What actually happens?

no error reported

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by changfubai** [comment]
![image](https://user-images.githubusercontent.com/20989201/134809687-c2908615-b97b-444e-87f4-25171e526e95.png)
I did not reproduce, I think it has been fixed.
call method which is not exist will throw exception: notSuchMethodException. I think it is ok.
@CrazyHZM
