### ISSUE TITLE
ProtocolConfig配置不生效

### ISSUE THREAD

**Issue by haozi000005** [apache/dubbo#3535]
### Environment

* Dubbo version: 2.7.0
* Operating System version: Windows
* Java version: 1.8

我从dubbo2.6.5升级到2.7.0之后，通过ProtocolConfig配置，如下：
```java
        @Bean
	public ProtocolConfig protocolConfig() {
		ProtocolConfig config = new ProtocolConfig();
		config.setName("dubbo");
		config.setServer("netty4");
		config.setPort(10003);
		config.setHost("192.168.1.11");
		config.setSerialization("hessian2");
		config.setThreads(500);
		return config;
	}
```
来配置我要暴露的地址，结果通过zk客户端工具查看到providers下面注册的内容value是127.0.0.1，我的consumer也一直都连不上这个服务，consumer在另外的局域网地址上。请问如何解决此问题，在dubbo2.6.5的时候是192.168.1.11

**Comment by limng06** [comment]
我从dubbo2.6.5升级到2.7.0之后 xml中的 rest protocol配置也失效了

**Comment by chickenlj** [comment]
@haozi000005 有问题原因的进展么？我来尝试复现一下问题

**Comment by AlbumenJ** [comment]
可以使用指定绑定网卡的方式
