### ISSUE TITLE
Why AdaptiveClassCodeGenerator instead of generating class directly

### ISSUE THREAD

**Issue by kezhenxu94** [apache/dubbo#3539]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

At the moment we create the adaptive extension class by `org.apache.dubbo.common.extension.ExtensionLoader#createAdaptiveExtensionClass`, which generates a Java class source `String` and compiles it. 

So I'm wondering why is this strategy chosen and can we generate a proxy class directly (for example using cglib) of the adaptive extension class, it would save the time to compile and reduce the complexity when manipulating `String` to generate the source code, thus less errors may occur and more performant(I think).

Thanks

**Comment by carryxyh** [comment]
Hi,
Since each extension will only be loaded once, performance is not the focus of consideration.
