### ISSUE TITLE
dubbo Http协议<metodName>.timeout参数配置不生效

### ISSUE THREAD

**Issue by core1942** [apache/dubbo#3546]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo 2.6.3
* spring-integration-httpinvoker 2.0.6.RELEASE
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue
```java
protocol.refer(DemoService.class, URL.valueOf("http://127.0.0.1:20880/com.wg.dubbo.service.DemoService?sayHello.timeout=60000"))
```
或
```xml
<dubbo:reference id="demoService" interface="com.wg.dubbo.service.DemoService" url="http://localhost:20880">
        <dubbo:method name="sayHello" timeout="6000" retries="2"/>
    </dubbo:reference>
```

provider超时的sayHello执行sleep 5秒，会报超时。

设置为
```java
protocol.refer(DemoService.class, URL.valueOf("http://127.0.0.1:20880/com.wg.dubbo.service.DemoService?timeout=60000"))
```
或
```xml
<dubbo:reference id="demoService" interface="com.wg.dubbo.service.DemoService" url="http://localhost:20880" timeout="6000" retries="2">
        <dubbo:method name="sayHello" />
    </dubbo:reference>
```
会timeout会生效

**Comment by CrazyHZM** [comment]
2.6.x currently only focuses on security issues, try to upgrade to 2.7.x or 3.x to solve the problem.
