### ISSUE TITLE
[DISCUSS] Dubbo service authorization

### ISSUE THREAD

**Issue by liuxinggang** [apache/dubbo#3560]
dubbo⽬前的安全策略有两个：
 1.令牌验证
 2. 路由规则
他们的作⽤分别是：
1.防⽌Consumer绕过注册中⼼
2.保护Provider，只允许被某些IP上的Consumer访问

在云的环境下，机器ip多变，配置复杂维护成本⾼，不能有效保护敏感服务。

所以我们需要提供⼀种机制，来对consumer进⾏认证和授权，保护敏感服务。

**Comment by ralf0131** [comment]
Hi, 

+1 to support authorization. 
Do you have any detailed proposal?

**Comment by Fuyao-JIANG** [comment]
We plan to use JWT(json web token) to implement authorization.We provide a auth service taking auth information from registry center. And user can set auth rules in a dashboard for auth service. We provide also a filter for consumer to get token from auth service and a provider check token with a filter.
Proceed as follow:
a.Consumer get token from Auth Service when it has no token or token is expire;
b.Auth Service check consumer information and provide token. Token is encrypted by provider's secret;
c.Consumer add token in attachment and send to provider;
d.Provider check token and return response.

**Comment by beiwei30** [comment]
Great, we really need a ACL mechanism for dubbo services. Looking forward to your pull request :)

**Comment by beiwei30** [comment]
@Fuyao-JIANG any update on this?

**Comment by Fuyao-JIANG** [comment]
I am sorry that I quit this issue for personal reason.

**Comment by zhaixiaoxiang** [comment]
I will solve it.
