### ISSUE TITLE
在上下文中如何可以获取当前活跃的服务提供者？

### ISSUE THREAD

**Issue by haozi000005** [apache/dubbo#3586]
如题，请教下在上下文中如何可以获取当前活跃的服务提供者？如果没有是否能提供一个工具类来获取，这样在实际开发过程中也是有意义的~

**Comment by kexianjun** [comment]
what's information you want to get about the provider?

**Comment by haozi000005** [comment]
provider  instance list

**Comment by lexburner** [comment]
Can you provide some scenes that the provider instance list is needed?
