### ISSUE TITLE
Many properties of ApplicationConfig are not defined in the official documentation

### ISSUE THREAD

**Issue by JerryChin** [apache/dubbo#3612]
There're some **undocumented** (NOT appear in the official documentation) properties of `ApplicationConfig`, like `registries`, `registryIds`, `shutwait`, `qosAcceptForeignIp`, `qosPort`, `qosEnable`, `dumpDirectory`, `isDefault`, just to name a few.

Please help elaborate the official documentation.

**Comment by kexianjun** [comment]
these are new properties, feel free to fix this in https://github.com/apache/incubator-dubbo-website
