### ISSUE TITLE
Provide SSL encryption over underlying socket choice

### ISSUE THREAD

**Issue by JerryChin** [apache/dubbo#3613]
Hey,

Is possible to encrypt the communication between provider and consumer? our RPC traffic will be on the Internet, so in our case It's extremely insecure to use Dubbo without any encryption.

Anyone can help me a bit.

**Comment by zonghaishang** [comment]
The dubbo protocol does not currently support encryption. Welcome to submit pr support for this feature.
ssl: 
`https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java`

**Comment by AlbumenJ** [comment]
Currently, the lastest version support SSL encryption. Please check.
