### ISSUE TITLE
Describe org.apache.dubbo.registry.ZKTools

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo#3627]
The code is just for testing purpose.

I found that when using zkcli to write node value with new line character, the "\n" will be treated as "\\" and "n" by zkcli. 

The work around is to use the Java API provided by curator, this is why the ZKTools class is written.

**Comment by JerryChin** [comment]
I'm a bit confused, `org.apache.dubbo.registry.ZKTools` has resided in the test directory of `dubbo-registr-api` in `master` branch since its creation, as observed from its version history, am I missing something?

**Comment by ralf0131** [comment]
You are right, my bad... Maybe it is better add some description to the class.
