### ISSUE TITLE
hessian2 反序列化bug

### ISSUE THREAD

**Issue by jiaZengShen** [apache/dubbo#3640]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

1. 定义类：
public class JZSVo implements Serializable{
    List<Double> arr = new ArrayList<>();
    //get方法
    //set方法。
}
2. 在producer端赋值
public JZSVo get() {
        List<Double> list = new ArrayList<>();
        list.add(null);
        list.add(null);
        list.add(3.0);

        JZSVo jzsVo = new JZSVo();
        jzsVo.setArr(list);
        return jzsVo;
    }
3. 在service端接收返回的数据 jzsVo中的arr的第一个、第二个数据应该为null实际为0.0
4.经过测试所有的基础类型：Double/Float/Integer等都会出现这种问题。

**Comment by tswstarplanet** [comment]
I try to reproduce the problem, but it fails. Can you provide a demo project ?

**Comment by CrazyHZM** [comment]
> I try to reproduce the problem, but it fails. Can you provide a demo project ?


I looked at this problem. It really exists. It should be a bug in hessian-lite. Let me fix it.

**Comment by fingthinking** [comment]
> > I try to reproduce the problem, but it fails. Can you provide a demo project ?
> 
> I looked at this problem. It really exists. It should be a bug in hessian-lite. Let me fix it.

哥们，你之前的修复思路不太对啊~~~，麻烦帮忙看看这个？[https://github.com/dubbo/hessian-lite/pull/11](https://github.com/dubbo/hessian-lite/pull/11)
