### ISSUE TITLE
本地直连，消费端能正常请求到服务端，服务端也能在1s内完成业务返回数据，但是消费端无法接收到数据，并且50s后出现超时异常。

### ISSUE THREAD

**Issue by itsql** [apache/dubbo#3691]
dubbo.registry.id=ssj-dubbo-registry
dubbo.registry.address=N/A
dubbo.protocol.serialization=java
dubbo.consumer.timeout=50000
#/**注意这里的注解是dubbo的注解，这里没有使用注册中心，为直连方式，各自本地开发可以放开 （dubbo://ip:服务端口）
 dubbo.reference.url = dubbo://127.0.0.1:12345

以上为我的点对点的配置

**Comment by xiaoheng1** [comment]
can you provider some system info?
for example: dubbo version, jdk version, Operating system version and a demo

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
