### ISSUE TITLE
Why don't some PRs trigger codecov-io ?

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#3696]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Recently I have found that some PRs do not trigger codecov-io. But it seemed all PRs could trigger codecov-io previously. Does someone know why ?

**Comment by CrazyHZM** [comment]
For example?

**Comment by tswstarplanet** [comment]
3688

**Comment by CrazyHZM** [comment]
> #3688
There is a trigger ci, what do you think?
https://travis-ci.org/apache/incubator-dubbo/builds/507714081?utm_source=github_status&utm_medium=notification

**Comment by tswstarplanet** [comment]
But there is no code coverage presented in this pr. In other prs, there may be code coverage.

**Comment by CrazyHZM** [comment]
> But there is no code coverage presented in this pr. In other prs, there may be code coverage.


Because you just modified the annotations, I guess there should be no other code affected.
