### ISSUE TITLE
win10下 meta-report缓存文件保存出错

### ISSUE THREAD

**Issue by liulang203** [apache/dubbo#3700]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. meta-report address "zookeeper://192.168.1.10:2081,192.168.1.11:2081"
2. run dubbo project

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

在org.apache.dubbo.metadata.support.AbstractMetadataReport类中
```java
        // Start file save timer
        String filename = reportServerURL.getParameter(Constants.FILE_KEY, System.getProperty("user.home") + "/.dubbo/dubbo-metadata-" + reportServerURL.getParameter(Constants.APPLICATION_KEY) + "-" + reportServerURL.getAddress() + ".cache");
```
其中reportServerURL.getAddress() 的内容是：“192.168.1.10:2081,192.168.1.11:2081”在win10下“:"是非法文件名字符，从而造成文件名错误。

```
 WARN  org.apache.dubbo.metadata.store.zookeeper.ZookeeperMetadataReport-  [DUBBO] Failed to save service store file, cause: 文件名、目录名或卷标语法不正确。, dubbo version: 2.7.0, current host: 10.0.75.1
java.io.IOException: 文件名、目录名或卷标语法不正确。
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.apache.dubbo.metadata.support.AbstractMetadataReport.doSaveProperties(AbstractMetadataReport.java:134)
	at org.apache.dubbo.metadata.support.AbstractMetadataReport.access$100(AbstractMetadataReport.java:56)
	at org.apache.dubbo.metadata.support.AbstractMetadataReport$SaveProperties.run(AbstractMetadataReport.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by xia-fei** [comment]
`public void doSaveProperties(long version) {
        if (version < lastCacheChanged.get()) {
            return;
        }
        if (file == null) {
            return;
        }
        // Save
        try {
            File lockfile = new File(file.getAbsolutePath() + ".lock");
            if (!lockfile.exists()) {
                lockfile.createNewFile();
            }
            RandomAccessFile raf = new RandomAccessFile(lockfile, "rw");
            try {
                FileChannel channel = raf.getChannel();
                try {
                    FileLock lock = channel.tryLock();
                    if (lock == null) {
                        throw new IOException("Can not lock the registry cache file " + file.getAbsolutePath() + ", ignore and retry later, maybe multi java process use the file, please config: dubbo.registry.file=xxx.properties");
                    }
                    // Save
                    try {
                        if (!file.exists()) {
                            file.createNewFile();
                        }
                        FileOutputStream outputFile = new FileOutputStream(file);
                        try {
                            properties.store(outputFile, "Dubbo Registry Cache");
                        } finally {
                            outputFile.close();
                        }
                    } finally {
                        lock.release();
                    }
                } finally {
                    channel.close();
                }
            } finally {
                raf.close();
            }
        } catch (Throwable e) {
            if (version < lastCacheChanged.get()) {
                return;
            } else {
                registryCacheExecutor.execute(new SaveProperties(lastCacheChanged.incrementAndGet()));
            }
            logger.warn("Failed to save registry store file, cause: " + e.getMessage(), e);
        }
    }`
` private class SaveProperties implements Runnable {
        private long version;

        private SaveProperties(long version) {
            this.version = version;
        }

        @Override
        public void run() {
            doSaveProperties(version);
        }
    }`
如果创建文件失败
每次lastCacheChanged值都一样  还递归创建线程运行。GG

**Comment by icom2014** [comment]
文件名中有 ：不能创建文件，文件名还有可能过长。

**Comment by CodingSinger** [comment]
好像还没修复

**Comment by slankka** [comment]
已经找到解决方法：
提供一个metadata-report配置，或者通过注解提供。
```
<dubbo:metadata-report address=
```
就可以骗过AbstractMetadataReport 去创建这个文件了。

**Comment by kelylm** [comment]
win10 如果本机测试，zk地址配置一个，win10文件名称过长不能创建
