### ISSUE TITLE
examine backward compatibility for Zipkin and Skywalking on 2.7.2

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#3728]
see more from https://github.com/openzipkin/brave/issues/867, also see https://github.com/apache/incubator-dubbo/issues/3576

**Comment by cvictory** [comment]
skywalking暂时不用做兼容：
![image](https://user-images.githubusercontent.com/4089452/59676559-6989c980-91fa-11e9-98e0-084373f9a12f.png)
