### ISSUE TITLE
关于服务打标动态路由

### ISSUE THREAD

**Issue by sturdypine** [apache/dubbo#3736]
服务提供方通过<dubbo:provider tag="xxx-A"/>和<dubbo:provider tag="xxx-B"/>可以静态设置一组服务不同打标信息，
服务消费方通过使用RpcContext.getContext().setAttachment(Constants.REQUEST_TAG_KEY,"xxx-A");可以指定服务族进行访问。
希望新版本提供RpcContext.getContext().setAttachment(Constants.REQUEST_TAG_KEY,"xxx-A,xxx-B");
用分隔符隔开，用于访问一组指定的服务族均可以。理由是在蓝绿发布场景，一组静态的vm上发布的均是A组服务，另外一组静态的vm上发布B组服务。正常情况AB组可以同时对外提供服务，在特殊发布场景只有A组提供服务，B组等待发布。整个管控信息不希望通过现有服务控制台完成，因为结合单元化流量分配等，有独立的控制台完成，只需框架客户端辅助支持即可。
如果可以带比例更赞：
RpcContext.getContext().setAttachment(Constants.REQUEST_TAG_KEY,"{'xxx-A':99,'xxx-B':1}");

**Comment by CrazyHZM** [comment]
Are you still paying attention to this issue?

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
