### ISSUE TITLE
希望封装得再好一点

### ISSUE THREAD

**Issue by huqilong** [apache/dubbo#3740]
按照文档配置的时候报错，缺少org.apache.curator包依赖

<dependency> <groupId>org.apache.curator</groupId> <artifactId>curator-framework</artifactId> <version>4.0.1</version> </dependency>

期望能直接引用一个starter就可以搞定，不要显式引用dependencies了

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
