### ISSUE TITLE
Dubbox and dubbo versions are compatible with each other

### ISSUE THREAD

**Issue by zonghaishang** [apache/dubbo#3751]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by zonghaishang** [comment]
https://github.com/dangdangdotcom/dubbox/commit/39c56bbfab80f012b78517c47eab0c71c92c9520#diff-011c6205e08b39119616bb17910fc8be

**Comment by chickenlj** [comment]
I and zonghaishang are still working on this issue, we will see if we can catch up with this release.
