### ISSUE TITLE
connected、disconnected not fire on 2.6.6-release

### ISSUE THREAD

**Issue by HiFangfangXu** [apache/dubbo#3753]
i have implements ChannelHandler
then start server by Exchangers.bind(url,the implements ChannelHandler, receiver);
and start client Exchangers.connect(url, the implements ChannelHandler,null);
the public void connected(Channel channel)  desn't fire on client connected to server,
and public void disconnected(Channel channel) desn't fire on client when the server force shutdown .

on 2.7.2-snapshot i tests can be fired.

**Comment by CrazyHZM** [comment]
2.6 no longer maintained,try it with the latest version, if you still have problems, you can reopen the issues
