### ISSUE TITLE
README some links “page 404”

### ISSUE THREAD

**Issue by PansonPanson** [apache/dubbo#3761]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

```
![image](https://user-images.githubusercontent.com/16064908/55133199-cdeb3e80-515f-11e9-8434-7fe364b1187b.png)
links are 404 in README

```

**Comment by CrazyHZM** [comment]
Can you describe it in detail? Because I checked the README.md file of the project, there is no such image.

**Comment by PansonPanson** [comment]
![image](https://user-images.githubusercontent.com/16064908/55145168-385ea780-517d-11e9-9b6d-20f64aecddec.png)

**Comment by CrazyHZM** [comment]
Could you pull request to fix it?
