### ISSUE TITLE
 consumer 端配置的filter无效

### ISSUE THREAD

**Issue by penweizgx** [apache/dubbo#3814]
### Environment

* Dubbo version: 2.7
* Operating System version: macos 10.13.6 
* Java version: 1.8

### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/6983487/55667776-73ef2500-5893-11e9-87f9-7b19d40167c3.png)
![image](https://user-images.githubusercontent.com/6983487/55667785-8e290300-5893-11e9-97f1-e6cd187f9c66.png)

1. consumer 端配置的filter无效，provider端配置的filter正常有效，服务可以正常调用

**Comment by sicw** [comment]
更改日志级别为Debug
在consumer时观察日志有没有default.reference.filter=traceDubboFilter字样
如果没有说明配置没有生效

**Comment by xiaoheng1** [comment]
I checked the new version and found that the consumer specified filter is valid, please upgrade the dubbo version and try it.

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
