### ISSUE TITLE
AnnotationBean 中ClassPathBeanDefinitionScanner应该设置useDefaultFilters为false

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo#3858]
AnnotationBean 中ClassPathBeanDefinitionScanner的useDefaultFilters被设置为true,当使用spring.factories配置bean时候,导致Spring中的@Configuration 注解类也被扫描, 从而IOC中出现两个Bean对象

**Comment by chenlushun** [comment]
```java
    public DubboClassPathBeanDefinitionScanner(BeanDefinitionRegistry registry, Environment environment,
                                               ResourceLoader resourceLoader) {

        this(registry, false, environment, resourceLoader);

    }
```

dubbo这里设置为false，即使扫描了也不会出问题吧？IOC不会出现2个同名称的bean

**Comment by brucelwl** [comment]
> ```java
>     public DubboClassPathBeanDefinitionScanner(BeanDefinitionRegistry registry, Environment environment,
>                                                ResourceLoader resourceLoader) {
> 
>         this(registry, false, environment, resourceLoader);
> 
>     }
> ```
> 
> dubbo这里设置为false，即使扫描了也不会出问题吧？IOC不会出现2个同名称的bean
你说的不会出问题是不出现明显的bug,但是显然这样多保存一个永远不使用的bean在IOC中是不合理的

**Comment by brucelwl** [comment]
@chenlushun  你说的不会出问题是不出现明显的bug,但是显然这样多保存一个永远不使用的bean在IOC中是不合理的

**Comment by brucelwl** [comment]
@chenlushun  我想确认下AnnotationBean中目的应该只是为了扫描dubbo 的 @service 类吧?,如果我将AnnotationBean中useDefaultFilters true改为false会不会有什么坑

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it
