### ISSUE TITLE
dubbo泛化调用，float类型数据结果不正确

### ISSUE THREAD

**Issue by crazyMonkey1995** [apache/dubbo#3861]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.8.5
* Operating System version: mac os 10.14
* Java version: 1.8.0_191

### Steps to reproduce this issue

1. dubbo provider返回类型为Float或者带有float的时候：
```
Float test();
```
implements为：
```
@Override
    public Float test() {
        return 99.8F;
    }
```
2. 消费者为泛化调用：
```
    Object result = genericService.$invoke(methodName, parameterTypes, params); //泛化调用刚刚的方法
```

### Expected Result

结果不出意料的化应当是99.8

### Actual Result

实际得到的是99.80000305175781
![image](https://user-images.githubusercontent.com/21658981/56009427-4df1d680-5d12-11e9-90ec-f905a65cfbe1.png)

**Comment by CrazyHZM** [comment]
使用的是什么协议的泛化调用，我来复现一下看看

**Comment by ab91963931372** [comment]
> 使用的是什么协议的泛化调用，我来复现一下看看

就dubbo协议，指定了本地url跳过注册中心： dubbo://localhost:20880，注册中心是zookeeper

**Comment by tswstarplanet** [comment]
2.8.5，你用的是dubbox吧？

**Comment by CrazyHZM** [comment]
的确存在这个问题，我来看看怎么解决这个问题吧

**Comment by ab91963931372** [comment]
> 2.8.5，你用的是dubbox吧？

**Comment by CrazyHZM** [comment]
它其实不是泛化的问题，而是序列化的问题，你应该用的是hessian序列化吧，hessian序列化会在把float类型按照double来进行序列化，所以会导致反序列化后是double类型的，才出现你的问题

**Comment by ab91963931372** [comment]
> 它其实不是泛化的问题，而是序列化的问题，你应该用的是hessian序列化吧，hessian序列化会在把float类型按照double来进行序列化，所以会导致反序列化后是double类型的，才出现你的问题

那意思是说在不修改provider序列化的前提下，这个问题是一定会出现的吗？

**Comment by ab91963931372** [comment]
> 它其实不是泛化的问题，而是序列化的问题，你应该用的是hessian序列化吧，hessian序列化会在把float类型按照double来进行序列化，所以会导致反序列化后是double类型的，才出现你的问题

那为什么如果是通过Reference注入的形式调用就不会出现这个问题，而通过泛化调用就会出现呢

**Comment by CrazyHZM** [comment]
也是一个Float类型吗，如果是放在数组里面的，例如float[]类型的，是不会出现这个问题的
