### ISSUE TITLE
Plans for swagger-dubbo?

### ISSUE THREAD

**Issue by huangxfchn** [apache/dubbo#3871]
- [ ] Currently there is no official swagger-dubbo plugin, so it is inconvenient to test the dubbo interface.
- [ ] Unofficial swagger-dubbo plugin: https://github.com/Sayi/swagger-dubbo
- [ ] I established an official development swagger-dubbo plugin.

Thanks for dubbo team.

**Comment by chickenlj** [comment]
Good to know that you are working on this feature, please keep the community posted.

**Comment by chickenlj** [comment]
Would you mind send an email to dev@dubbo.apache.org to discuss this feature first?

**Comment by huangxfchn** [comment]
I'm sorry that I haven't paid attention to this issue due to my busy schedule recently.

For example, when we develop web applications, we provide swagger interface documentation for the caller to use, which would be a nice feature if dubbo also supports such a feature.
