### ISSUE TITLE
dubbo2.7.x config-center的配置namespace参数与代码获取配置的变量值不一致

### ISSUE THREAD

**Issue by nevin9939** [apache/dubbo#3872]
### Environment

* Dubbo version: 2.7.1
* Dubbo Admin version: 0.2.0
* Java version: 1.8

### Steps to reproduce this issue
在dubbo-admin中添加权重设置和负载均衡设置
在zookeeper里面能看到设置的结果在config下面
<img width="1342" alt="a000" src="https://user-images.githubusercontent.com/26532831/56106546-4b8eb700-5f74-11e9-8108-ffde0fb8128b.png">
<img width="965" alt="a1111" src="https://user-images.githubusercontent.com/26532831/56106550-51849800-5f74-11e9-8ec6-a866f850206f.png">
<img width="1617" alt="a2222" src="https://user-images.githubusercontent.com/26532831/56106559-577a7900-5f74-11e9-9ece-441442a42814.png">

但是实际dubbo在调用时，并没有从config下面获取配置，仍然从服务接口下面的配置中获取，到账新的配置不生效，而且从服务接口拿配置，也没有应用级一说，仍是服务级

**Comment by nevin9939** [comment]
![aaaaa](https://user-images.githubusercontent.com/26532831/56194137-d949cf80-6064-11e9-85b9-b6a2e5573ebb.png)
```xml
<dubbo:config-center address="${dubbo.address}" namespace="yk" />
```
这应该是个bug，造成配置从错误的地方获取，导致获取不到配置，给人假象是配置未生效

**Comment by chickenlj** [comment]
请问你这里指定namespace="yk"是想达到什么目的？
`<dubbo:config-center address="${dubbo.address}" namespace="yk" />`

这样，会导致zk监听路径为：
`/yk/config/xxx`
因此这里指定的namespace需与dubbo-admin中配置保持一致，否则dubbo-admin写入的路径仍为：
`/dubbo/config/xxx`

**Comment by nevin9939** [comment]
namespace="yk"是为了做环境隔离，跟
<dubbo:registry group="yk"/>
保持一致

**Comment by chickenlj** [comment]
你目前同时使用了两个环境吗：`dubbo`、`yk`？
dubbo-admin是否配置了configcenter使用`yk`？

**Comment by nevin9939** [comment]
是的，配置都配了，实际需要区分的环境有4个

**Comment by nevin9939** [comment]
问题点不是应该在配置文件的参数key 与 实际获取参数的key不一致吗

**Comment by navychi** [comment]
遇到同样问题
