### ISSUE TITLE
拓展点的aop的顺序无法控制

### ISSUE THREAD

**Issue by githubcheng2978** [apache/dubbo#3879]
拓展点的aop执行顺序无法控制。例如ProtocolFilterWrapper和ProtocolListenerWrapper 
这两个每次重新启动项目的时候，执行顺序都不一样

**Comment by chickenlj** [comment]
这是当前的SPI机制可以增强的一点，但是从社区的角度我认为这个优先级相对要低一些，你愿意给出自己的实现吗？
