### ISSUE TITLE
自定义路由没有工作

### ISSUE THREAD

**Issue by cookiejoo** [apache/dubbo#3894]
我按照官方给我的文档例子，自己扩展了路由功能，配置也是一样的，但是路由的方法断点一直没进去，我是在consumer里面写的代码，是不是我理解错了还是什么？
这个测试怎么做？
jar包里面的ConditionRouteFactory断点也没进去，好像也不是用这个去判断条件，所以，这个Invoker是怎么得到的地址信息？

**Comment by LiZhenNet** [comment]
可以提供demo吗？

**Comment by cookiejoo** [comment]
> 可以提供demo吗？

2.7.x的可以,就是2.6.x的不行
![image](https://user-images.githubusercontent.com/3397316/60406520-d3d23f00-9be8-11e9-9061-58fc7ad1ae7f.png)
![image](https://user-images.githubusercontent.com/3397316/60406538-e3ea1e80-9be8-11e9-9938-6ee569141b78.png)
![image](https://user-images.githubusercontent.com/3397316/60406552-efd5e080-9be8-11e9-8753-2183d6228f14.png)

**Comment by web1992** [comment]
@cookiejoo  2.6.x Dubbo 的包名还是 `com.alibaba.dubbo.xxx` 因此使用2.6.x 的话，META-INF 下面的配置文件要改成 `com.alibaba.dubbo.xxx`开头。

**Comment by jinxin231** [comment]
请问这个问题有解决吗？我这2.6.X也是生效失败
