### ISSUE TITLE
多注册中心数据合并建议

### ISSUE THREAD

**Issue by stoneapple** [apache/dubbo#3918]
这样的场景：公司在异地建设多个机房，注册中心也没个机房部署了一个集群，服务在注册的时候，同城的两个机房是同时注册的，防止一个集群故障引，提升高可用（同城双活）。
       在这种场景下，消费方的内存中，同一个服务同一个提供方会同时缓存两份数据，增加了消费方的内存开销（消费方的registrydirectory是按照注册中心维度缓存服务提供方）；
       另外还有一个风险，当某个机房的注册中心集群真的故障了，在恢复初期，肯定会有很多dubbo客户端重新注册上来，然后引发zookeeper的推送，但是此时，推送到消费方的服务提供方列表很少，交易压力会集中在这几台，出现交易失败率陡增的现象。虽然提供方都是好的，并且另外一个注册中心上注册的提供方列表是全的，但是由于注册中心配置的先后，可能会引发该问题。
       所以我们建议官方团队，是否针对多注册中心场景下，能对多注册中心场景相同的服务提供方进行一个合并缓存？解决上述两个问题？

**Comment by NameHaibinZhang** [comment]
多个注册中心的问题，可以考虑通过注册中心自身的数据同步来完成

**Comment by stoneapple** [comment]
> 多个注册中心的问题，可以考虑通过注册中心自身的数据同步来完成

主要是考虑注册中心的高可用，如果同步失败了怎么处理？另外zookeeper的异地同步，有推荐的方案吗

**Comment by githublaohu** [comment]
请了解 nacos

**Comment by chickenlj** [comment]
please refer to Multi Registry solution, we will keep working there

**Comment by chickenlj** [comment]
#5399
