### ISSUE TITLE
zookeeper推送的providers列表不可信，如何解决

### ISSUE THREAD

**Issue by suichen** [apache/dubbo#3921]
由于网络或者其他原因，zookeeper跟provider之间的心跳超时，这时候zookeeper会认为所有的provider都不可用，实际上provider是可用的，但zookeeper依然会推送空列表为consumer。这样的话就可能导致服务调用失败。。。有没有比较好的解决这写问题的方法？

**Comment by haroldyong** [comment]
https://github.com/apache/incubator-dubbo/issues/3920，是不是同样的问题引起的了？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
