### ISSUE TITLE
dubbo 2.7.1 SpringStatusChecker  UNKOWN

### ISSUE THREAD

**Issue by dongdongzld** [apache/dubbo#3927]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: macbook 10.14.3
* Java version: 1.7

### Steps to reproduce this issue

这个问题依然存在，2.7.1，spring:UNKOWN
// [Issue] SpringStatusChecker execute errors on non-XML Spring configuration // issue : https://github.com/apache/incubator-dubbo/issues/3615 if(c instanceof GenericWebApplicationContext) { // ignore GenericXmlApplicationContext continue; }
c是一个GenericWebApplicationContext但被忽略了，右侧的注释是说忽略GenericXmlApplicationContext？

**Comment by CrazyHZM** [comment]
The logic is removed in the new version, try it with the latest version, if you still have problems, you can reopen the issue
