### ISSUE TITLE
dubbo注册服务IP地址总是127.0.0.1而不是内网地址

### ISSUE THREAD

**Issue by wo8335224** [apache/dubbo#3930]
Why are the IP addresses obtained by the registered services all 127.0.0.1 instead of the intranet IP? Can I specify to get the intranet address? eho0?

Tell us your environment
dubbo 2.7.1
dubbo-registry-nacos 2.7.1
nacos-client 1.0.0-RC3
![image](https://user-images.githubusercontent.com/10435131/56729984-33474500-6789-11e9-9986-644028d2e850.png)

**Comment by byronzoz** [comment]
Maybe, I also face the same problem

https://github.com/apache/incubator-dubbo/issues/3923

**Comment by boomblog** [comment]
具体的配置文件能否提供一下，我这边测试如下配置<dubbo:protocol name="dubbo"/>，发现注册中心的地址是内网地址。

**Comment by wo8335224** [comment]
@boomblog 我用的是nacos注册中心，spring boot 整合dubbo
                  <dependency>
			<groupId>com.alibaba.boot</groupId>
			<artifactId>nacos-config-spring-boot-starter</artifactId>
			<version>0.2.1</version>
		</dependency>
		
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-registry-nacos</artifactId>
			<version>2.7.1</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.0.0-RC3</version>
		</dependency>
         <dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>2.7.1</version>
		</dependency>

**Comment by wo8335224** [comment]
# Spring boot application
dubbo.registry.address=nacos://192.168.1.214:8848
dubbo.protocol.port=-1

**Comment by VanXD** [comment]
对hosts 文件进行配置
1.使用 hostname 命令取得当前的 机器名
2.将机器名和内网 ip 配置进 hosts

**Comment by wo8335224** [comment]
> 对hosts 文件进行配置
> 1.使用 hostname 命令取得当前的 机器名
> 2.将机器名和内网 ip 配置进 hosts

没用~试过的

**Comment by boomblog** [comment]
> @boomblog 我用的是nacos注册中心，spring boot 整合dubbo
> 
> com.alibaba.boot
> nacos-config-spring-boot-starter
> 0.2.1
> 
> 
> 
> org.apache.dubbo
> dubbo-registry-nacos
> 2.7.1
> 
> 
> com.alibaba.nacos
> nacos-client
> 1.0.0-RC3
> 
> 
> org.apache.dubbo
> dubbo-spring-boot-starter
> 2.7.1

private String findConfigedHosts(ProtocolConfig protocolConfig, List<URL> registryURLs, Map<String, String> map) {
        boolean anyhost = false;

        String hostToBind = getValueFromConfig(protocolConfig, Constants.DUBBO_IP_TO_BIND);

        // if bind ip is not found in environment, keep looking up
        if (StringUtils.isEmpty(hostToBind)) {
            hostToBind = protocolConfig.getHost();
            if (provider != null && StringUtils.isEmpty(hostToBind)) {
                hostToBind = provider.getHost();
            }

            if (StringUtils.isEmpty(hostToBind)) {
                anyhost = true;
                **hostToBind = getLocalHost();**

                if (StringUtils.isEmpty(hostToBind)) {
                    hostToBind = findHostToBindByConnectRegistries(registryURLs);
                }
            }
        }

        map.put(Constants.BIND_IP_KEY, hostToBind);

        // registry ip is not used for bind ip by default
        String hostToRegistry = getValueFromConfig(protocolConfig, Constants.DUBBO_IP_TO_REGISTRY);
        if (StringUtils.isEmpty(hostToRegistry)) {
            // bind ip is used as registry ip by default
            hostToRegistry = hostToBind;
        }

        map.put(Constants.ANYHOST_KEY, String.valueOf(anyhost));

        return hostToRegistry;
    }

这是获取host的源码，你可以先本地测一下调用getLocalHost()这个方法返回的是什么

**Comment by VanXD** [comment]
> > 对hosts 文件进行配置
> > 1.使用 hostname 命令取得当前的 机器名
> > 2.将机器名和内网 ip 配置进 hosts
> 
> 没用~试过的

![image](https://user-images.githubusercontent.com/9159171/58162466-ce620a80-7cb4-11e9-8ae5-01ec75dd2dfa.png)
不要重复出现 hostname

**Comment by fangQiangQiang** [comment]
seam question

**Comment by chickenlj** [comment]
> 这是获取host的源码，你可以先本地测一下调用getLocalHost()这个方法返回的是什么

可以按照这里的步骤尝试先试一下看。

**Comment by Hoxton019030** [comment]
給遇到這個問題的人
我前不久也遇到這個問題

後來發現是我電腦有裝Http Proxy或是VPN的東西
他一直嘗試把我的ip註冊到http proxy的網域

可以用nslookup來查看自己的ip位置是跑到哪裡
