### ISSUE TITLE
如果通过@Service发布服务那么代码中不可以使用@Transactional注解

### ISSUE THREAD

**Issue by danny-zhu** [apache/dubbo#394]
如题，不能同时使用@Service和@Transactional

**Comment by zscchaofan** [comment]
spring声明式事务+spring的@service 注解+dubbo xml配置式发布服务 , 为什么事务性实现不了?
junit测试不通过dubbo发布的服务可以实现事务。求解答，多谢。 @danny-zhu

**Comment by ZZMarquis** [comment]
很多人遇到这个问题，不用注解，xml配置吧

**Comment by kayuu0810** [comment]
我也遇到了。最后没办法用的xml配置的
