### ISSUE TITLE
How to set a customized Dispatcher as default?

### ISSUE THREAD

**Issue by ivyerick** [apache/dubbo#3955]
Hi
Because a special requirement, we implemented a customized  AllDispatcher(org.apache.dubbo.remoting.transport.dispatcher.all.AllDispatcher).  

* we add a customizedAll spi in the dubbo/internal dir  and setting dispatcher property to customizedAll. 
`customizedAll=xxx.CustomizedAllDispatcher`

* After deployment, we found that the dispatcher property(customizedAll) is broadcasted to dubbo registry add dubbo consumer apply the "customizedAll" dispatcher property when they started. Then all the consumers are crashed.

* Then we do some investigation. properties only related to provider's threadpool  are not broadcasted to consumer(`src/main/java/org/apache/dubbo/rpc/cluster/support/ClusterUtils.java`).

* We also do some investigation about ExtensionLoader.  We plan to override `all=xxx.CustomizedAllDispatcher` with `all=org.apache.dubbo.remoting.transport.dispatcher.all.AllDispatcher`. 

* ExtensionLoader use "urls = classLoader.getResources(fileName);" to launch spi extension. we cannot make sure `com.alibaba.dubbo.remoting.Dispatcher` file  in our module is loaded earlier than `com.alibaba.dubbo.remoting.Dispatcher` in origin dubbo module

So is there a way to add a customized dispatcher which have no influence to all its consumer?
or  is there a way to override default AllDispatcher?
or is there a way to prevent properties broadcasted to consumer?

**Comment by kexianjun** [comment]
I did not find a way to prevent the parameters configured on the provider side from propagating to the consumer side, but you can always override a parameter propagating from provider in consumer side by configuring like the following
```
<dubbo:consumer>
        <dubbo:parameter key="dispatcher" value="all"/>
</dubbo:consumer>
```

**Comment by cvictory** [comment]
As noted above,  you can add some configuration。 You just configure as following:

```
<dubbo:consumer>
        <dubbo:parameter key="dispatcher" value="customizedAll"/>
</dubbo:consumer>
```
