### ISSUE TITLE
dubbo 2.7.1 thrift doesn't work

### ISSUE THREAD

**Issue by wuhuajie** [apache/dubbo#3992]
1. provider and consumer can be built successfully.
2. the provider can receive the request from consumer, and return data successfully.
3. the consumer is hanging on to wait the data  all the time.  No timeout, no data, hanging only.

**Comment by CrazyHZM** [comment]
Can you describe the details a bit more, such as using a demo or telling a rough configuration?

**Comment by beiwei30** [comment]
pls. check https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-thrift

**Comment by wuhuajie** [comment]
> pls. check https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-thrift

Thanks.  
May I understand that we have to use protocol as "name="native-thrift"", while name=thrift won't work now and in future.
