### ISSUE TITLE
[SoC2019]Support more security choose

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#3998]
Currently the security support of Dubbo is not enough. We should provide more feature to use. Such as TLS support,  Authorization，high-level encrypt data.

Required feature

1.  TLS support 

1.1 Support TLS , maybe you can refer the netty implements.

1.2 Use the same port as the TCP port , default is 20880.  And the server should consume the invocation of simple TCP or TCP+TLS.

 

Options feature

2.  Authorization

2.1  You can add some authorization between client and server.

2.2  You should focus on client and server communication, but not on registration.

2.3  This feature is option. 

#### If you are interested in this topic, please refer to : https://github.com/apache/incubator-dubbo/issues/4001

**Comment by jievince** [comment]
I am interested in this idea.

**Comment by cvictory** [comment]
You can apply for the topic directly. If you have any question, you can leave a message here.

**Comment by Warkeeper** [comment]
What a pity! My undergraduate graduation project is all about adding security feature to Dubbo (including TLS support), but now I'm having a job to do and unable to participate in this. Hope someone could pick this up and do a better job !

**Comment by TotalForgot** [comment]
@cvictory That is such a great news for Dubbo users.
Do you have an update regarding the progress of these security support features in Dubbo code base?
Very eager to see version of Dubbo with these features integrated

Best
