### ISSUE TITLE
[SoC2019]Supporting gRPC Protocol.

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#3999]
gRPC is a very popular RPC framework built on top of the HTTP/2 protocol. We can try to integrate gRPC with Dubbo and make it one of the many third-party RPC protocols supported by Dubbo, just like Hessian (code, doc) and Thrift (code, doc).

* Make gRPC easy to use: allowing developers to program with interface directly, calling remote gRPC services like calling local services
* Leverage service governance features provided by Dubbo: Service Discovery, Load Balancing and Traffic Management.

#### If you are interested in this topic, please refer to : https://github.com/apache/incubator-dubbo/issues/4001

**Comment by arjenzhou** [comment]
Hi,
I wonder that is it available for Alibaba Summer of Code？

I am a college student from China who have experience on open source and not accepted by Google Summer of Code with other community. I have experience on using netty and spring. Could you please give me some introduction on contribute to it?

**Comment by arjenzhou** [comment]
I just saw this issue at JIRA and wonder if it is available because I found it was discussed already.

In addition, is there any communication ways like gitter,etc.  I want to talk about this sub-project.

**Comment by eonezhang** [comment]
in our org, we have implemented raw `thrift`,`unary gRPC` support on `dubbo` depend on `armeria`, looking forward to the official support.

**Comment by arjenzhou** [comment]
From the text I assume that is there code and doc's links not put. 

Also, I have writtern some demo of gRPC and dubbo and wonder should I read about the psrt of Hessian and Thirf to work out how they run or any other directions?

**Comment by arjenzhou** [comment]
Hi @cvictory

I have some questions about gRPC extenstion. 

1. When I refer to the Thirft implementation of Dubbo I found there are native-thrift and thrift, and thrift was deprecated. I wonder the differences between them, is that mean dubbo no longer support dubbo custom thrift?

2. When I use gRPC and Thrift found they have the similarity that use theirselves compiler to compile from .protobuf or .thrift file to .java not using custom encodng.
But I found the thrift codec2 implementation was customized, and what should gRPC protocol do about the protocl codec? Using native gRPC protocol of customeize a codec for gRPC.

LFYP

**Comment by cvictory** [comment]
1. If you use thrift,  use native-thrift directly. I don't know the thrift but only know native thrift.  refer to : http://dubbo.apache.org/zh-cn/docs/user/references/protocol/thrift.html.  

2. I think we have two ways to implements. 
2.1 You can introduce gRpc, and the protocl , transport and serialization are managed with gRpc. 

引入gRPC，gRPC负责了协议，通信等所有的事情。

2.2 You can refer to gRPC, and you implement the [Http/2](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).  Finally, you can invoke between the dubbo app used gRpc protocol and the gRpc app.

**Comment by arjenzhou** [comment]
@cvictory 
Thanks for your reply.

There is a draft proposal, the way to integrate gRPC (as same as native-thrift) is talked about in it. Please review and write your comments at your convenience.

https://docs.google.com/document/d/1Es3hYCeo6DlWx5iXD23QKrDx16YVKzxi9_ATLKiv0hE/edit?usp=sharing

**Comment by cvictory** [comment]
> https://docs.google.com/document/d/1Es3hYCeo6DlWx5iXD23QKrDx16YVKzxi9_ATLKiv0hE/edit?usp=sharing

ok. I will check it.  And you can prepare the proposal firstly.

**Comment by arjenzhou** [comment]
There is my commit after sorting out, please feel free to review it.

The grpc code-gen plugin is relay on https://github.com/chickenlj/grpc-java/tree/grpc-codegen-dubbo/compiler

Is it necessary to create a PR to upstream repo?

@chickenlj @cvictory

**Comment by arjenzhou** [comment]
It works well with:
https://github.com/arjenzhou/grpc-demo/blob/master/src/main/java/org/apache/dubbo/rpc/protocol/grpc/api/gRPCServer.java
and
https://github.com/arjenzhou/dubbo-demo/blob/master/src/main/java/org/apache/dubbo/samples/basic/BasicConsumer.java

**Comment by konglz** [comment]
代码bug比较多：

* 1. 超时时间完全不生效，不管在哪一端设置；
* 2. 服务端抛异常，客户端接不到。

**Comment by arjenzhou** [comment]
感谢反馈，会继续修改

konglz <notifications@github.com> 于 2019年9月10日周二 下午9:53写道：

**Comment by konglz** [comment]
另外，测过性能没有？我看核心链路上直接走反射，比如：
```java
    /**
     * 这里返回的impl必须要有所有的方法, Stub BlockingStube FutureStub
     */
    @Override
    protected <T> T doRefer(Class<T> type, URL url) throws RpcException {
        //通过 type(IGreeter)，反射获得外部类（GreeterGrpc），调用静态方法（getDubboStub()），获得并返回（T）stub
        Class<?> enclosingClass = type.getEnclosingClass();
        if (enclosingClass == null) {
            throw new IllegalArgumentException(
                    type.getName() + " must be declared inside protobuf generated classes, " +
                            "should be something like ServiceNameGrpc.IServiceName.");
        }

        final Method dubboStubMethod;
        try {
            dubboStubMethod = enclosingClass.getDeclaredMethod("getDubboStub", Channel.class, long.class);
        } catch (NoSuchMethodException e) {
            throw new IllegalArgumentException("Does not find getDubboStub in " + enclosingClass.getName()
                    + ", please use the customized protoc-gen-grpc-dubbo-java to update the generated classes.");
        }

        Channel channel = channelMap.computeIfAbsent(url.getServiceKey(),
                k -> ManagedChannelBuilder.forAddress(url.getHost(), url.getPort()).usePlaintext().build()
        );

        try {
            int timeout = url.getParameter(TIMEOUT_KEY, DEFAULT_TIMEOUT);
            @SuppressWarnings("unchecked") final T stub = (T) dubboStubMethod.invoke(null, channel, timeout);
            return stub;
        } catch (IllegalAccessException | InvocationTargetException e) {
            throw new IllegalStateException("Could not create stub through reflection.", e);
        }
    }
```

可以参考 [motan的GRPC实现](https://github.com/weibocom/motan/blob/master/motan-extension/protocol-extension/motan-protocol-grpc/src/main/java/com/weibo/api/motan/protocol/grpc/GrpcProtocol.java)
