### ISSUE TITLE
Make deciding serialization happens on I/O thread or biz thread easier.

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#4037]
`decode.in.io` 
* default value is `true`, which means decode happens on I/O thread.
* the way to change the value is not direct enough, at least there should have a document tell us how to do it.
 ```xml
  <dubbo:application name="demo-consumer">
        <dubbo:parameter key="decode.in.io" value="false"/>
    </dubbo:application>
 ```

**Comment by cvictory** [comment]
I have add a article on http://dubbo.apache.org/
