### ISSUE TITLE
Default category of Redis is different from Default Category of zookeeper

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#4042]
In zookeeper, the default category is Provider when subscription:

```
categories = url.getParameter(CATEGORY_KEY, new String[]{DEFAULT_CATEGORY});
```
https://github.com/apache/incubator-dubbo/blob/master/dubbo-registry/dubbo-registry-zookeeper/src/main/java/org/apache/dubbo/registry/zookeeper/ZookeeperRegistry.java#L251

------------

But in redis:
```
List<String> categories = Arrays.asList(url.getParameter(CATEGORY_KEY, new String[0]));
```

https://github.com/apache/incubator-dubbo/blob/master/dubbo-registry/dubbo-registry-redis/src/main/java/org/apache/dubbo/registry/redis/RedisRegistry.java#L411

**Comment by CrazyHZM** [comment]
This has been fixed.
