### ISSUE TITLE
@Service.methods 不起作用

### ISSUE THREAD

**Issue by Mark-WJQ** [apache/dubbo#4043]
@Service(methods ={@Method(name = "sayHello",retries = 2)} )，通过注解加载类时，没有将methods属性加载上。
ServiceAnnotationBeanPostProcessor.buildServiceBeanDefinition 这个方法中需要加一句，将注解对象初始化到ServiceBean的对象中 ：builder.addConstructorArgValue(service);

**Comment by kexianjun** [comment]
I have tried the @Method annotation and it work for me, can you provider a demo to reproduce this issue?

**Comment by beiwei30** [comment]
feel free to reopen it if you still can reproduce with the latest version `2.7.4-SNAPSHOT`
