### ISSUE TITLE
有计划支持k8s作为注册中心吗？

### ISSUE THREAD

**Issue by dntbeSris** [apache/dubbo#4090]
有计划支持k8s作为支持中心吗？我已经实现了一个版本。提交之前是不是得提个issue？

**Comment by chickenlj** [comment]
@dntbeSris 太棒了，我认为K8S的支持是接下来的一个重要方向，你可以将你的实现提交为pull request，社区会随时给予反馈的。

**Comment by ShenFeng312** [comment]
现在支持了吗

**Comment by rxxy** [comment]
好像是3.0开始支持?

**Comment by AlbumenJ** [comment]
3.0 support this
