### ISSUE TITLE
当dubbo端口设为-1时, 如何在代码中获取当前dubbo的端口?

### ISSUE THREAD

**Issue by goozi** [apache/dubbo#4091]
- [ x ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ x ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: windows 10
* Java version: 1.8

### Steps to reproduce this issue

1. 当dubbo端口设为-1时, 如何在代码中获取当前dubbo的端口?
```

**Comment by web1992** [comment]
为什么要设置成 -1 ？ -1 是非法的端扣。

下面的代码也许有用。

```java
int remotePort = RpcContext.getContext().getRemotePort();
int localPort = RpcContext.getContext().getLocalPort();
```

**Comment by yakecanlee** [comment]
@web1992 设置为-1时,dubbo会自动搜索和设置为可用的端口.

**Comment by evan-cai** [comment]
我也想问这个问题。

**Comment by beiwei30** [comment]
> 为什么要设置成 -1 ？ -1 是非法的端扣。
> 
> 下面的代码也许有用。
> 
> ```java
> int remotePort = RpcContext.getContext().getRemotePort();
> int localPort = RpcContext.getContext().getLocalPort();
> ```

@web1992 is correct.
