### ISSUE TITLE
听说升顶级项目了，项目名咋还没改

### ISSUE THREAD

**Issue by ilaotan** [apache/dubbo#4105]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by ralf0131** [comment]
We can't remove it by ourself, I have requested the ASF infra, here is the ticket:

[1] https://issues.apache.org/jira/browse/INFRA-18412

**Comment by ACXNX** [comment]
已经过去两天了，项目名称目前还是没有更新！

**Comment by ralf0131** [comment]
Hi, we are still waiting for ASF infra, details: https://issues.apache.org/jira/browse/INFRA-18452

**Comment by ralf0131** [comment]
This issue has been fixed.
