### ISSUE TITLE
dubbo网关选择或者说如何实现

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo#4117]
我现在已经有好几个dubbo服务了，但是前段缺少统一的调用入库，这个时候有相关网关的实现或者想法呢。

**Comment by yb1682003** [comment]
dubbo本身就是不期望中间网关层去转发

**Comment by kexianjun** [comment]
If you want to implement your own gateway, the [generic reference](http://dubbo.incubator.apache.org/en-us/docs/user/demos/generic-reference.html) is a good hitting-point

**Comment by 1076572358** [comment]
> dubbo本身就是不期望中间网关层去转发

微服务没有api网关的话 10个服务 10台机器 10个地址 前端不得调哭？肯定要有网关这个东西

**Comment by 1076572358** [comment]
> If you want to implement your own gateway, the [generic reference](http://dubbo.incubator.apache.org/en-us/docs/user/demos/generic-reference.html) is a good hitting-point
thinks，Is there a use case, or something like zuul?

**Comment by yb1682003** [comment]
可以在自己基于Spring Gateway来做个转发 但一般很少有dubbo直接对接前端的

**Comment by kexianjun** [comment]
currently, the official gateway is in development, pls refer to https://github.com/apache/dubbo-proxy

**Comment by lakehuang** [comment]
> currently, the official gateway is in development, pls refer to https://github.com/apache/dubbo-proxy

dubbo-proxy 活跃度挺低的，有没有生产上使用的案例

**Comment by AlbumenJ** [comment]
You can refer dubbo-go-pixiu.
