### ISSUE TITLE
ZookeeperDynamicConfiguration 严重 BUG

### ISSUE THREAD

**Issue by abel533** [apache/dubbo#4125]
### Environment

* Dubbo version: 2.7.1
* Operating System version: windows
* Java version: 8

当 zookeeper 地址配置错误时，`CountDownLatch` 会在下面位置锁死，**建议增加超时时间！！**
![20190521172642506](https://user-images.githubusercontent.com/1787798/58221745-3e6ca100-7d46-11e9-972d-3242ae8d6bc4.png)

**Comment by boomblog** [comment]
我感觉这里的意思是在初始化Dubbo时，需要先确保连接上配置中心了，才能继续往后执行。

**Comment by boomblog** [comment]
> 我感觉这里的意思是在初始化Dubbo时，需要先确保连接上配置中心了，才能继续往后执行。

如果设置一个超时时间，dubbo就可能不会从配置中心读取配置了，那么可能就会从其他地方去读取配置了，这个流程行不行感觉需要好好讨论一下

**Comment by dhchao11** [comment]
dubbo后续的初始化，依赖zk配置中心的数据，个人觉得，强依赖和弱依赖时应采取不同的策略。
1､ 强依赖zk配置中心时，长时间死等也许是最优的策略，在连接恢复正确同步配置后，再做后续初始化。
2､ 非强依赖zk配置中心，可以设置默认的超时时间，应用优先启动，待zk同步后再更新。

**Comment by abel533** [comment]
这里最关键的问题是，强依赖 zk 时，地址配置错误，主线程卡死在这里没有任何反应，运维看不到任何信息。

如果不增加超时时间，可以考虑增加额外线程输出这里的等待信息。至少能看到程序目前在等什么，方便运维解决问题。

**Comment by cvictory** [comment]
重现方式，启动redis，然后将原来zookeeper的配置项的端口从2181编程6379，启动就会hold。

也就是只要有端口可以连接上，但是没法通过zookeeper协议传播，就会等待。

**Comment by beiwei30** [comment]
pls.check #4134
