### ISSUE TITLE
ZookeeperDynamicConfiguration will be busy wait if zk is unavailable.

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4134]
```java
    ZookeeperDynamicConfiguration(URL url, ZookeeperTransporter zookeeperTransporter) {
        this.url = url;
        rootPath = "/" + url.getParameter(CONFIG_NAMESPACE_KEY, DEFAULT_GROUP) + "/config";

        initializedLatch = new CountDownLatch(1);
        this.cacheListener = new CacheListener(rootPath, initializedLatch);
        this.executor = Executors.newFixedThreadPool(1, new NamedThreadFactory(this.getClass().getSimpleName(), true));

        zkClient = zookeeperTransporter.connect(url);
        zkClient.addDataListener(rootPath, cacheListener, executor);
        try {
            // Wait for connection
            this.initializedLatch.await();
        } catch (InterruptedException e) {
            logger.warn("Failed to build local cache for config center (zookeeper)." + url);
        }
    }
```

Instead, should we introduce a timeout for **this.initializedLatch.await()**?

**Comment by Leishunyu** [comment]
I think it is not particularly necessary, it is not available at the time of initialization. This problem should be discovered in time. If the configuration center is used, the connection is necessary.

**Comment by beiwei30** [comment]
there are two issues in this implementation:

1. When zookeeper address is configured wrong, the latch will wait forever. This problem is also mentioned in #4125
2. Even when zookeeper address is configured correctly, there's chance that INITIALIZED event is fired before the listener is registered, which will cause latch waits forever as well.
