### ISSUE TITLE
how about change the data type of field ‘generic’ from ‘String’ to ‘Boolean’ in class AbstractReferenceConfig?

### ISSUE THREAD

**Issue by yuzhiping** [apache/dubbo#4143]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: macOS
* Java version: 1.8

### Steps to reproduce this issue

1. how about change the data type of field ‘generic’ from ‘String’ to ‘Boolean’ in class AbstractReferenceConfig?

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by yuzhiping** [comment]
practically ，the field ‘generic’ with a value true or false，but the type was defined as a String,i think,change it to Boolean more better.

**Comment by beiwei30** [comment]
we cannot change it to boolean, since we need to distinguish whether this value is set explicitly by user or not.
