### ISSUE TITLE
dubbo泛化调用怎么支持RpcContext传值?

### ISSUE THREAD

**Issue by edgelone** [apache/dubbo#4156]
Dubbo 泛化调用怎么用RpcContext传值到服务提供方呢?

我是这么写的,但是服务端接不到
```java
RpcContext.getContext().setAttachment("token", "ttttttoooo");

Object result = genericService.$invoke(method, null, new Object[]{params});
```

**Comment by l8i8n6jian** [comment]
服务端接不到是因为TagContextFilter中的invoke方法进行了attachments.remove(TOKEN_KEY); 
不使用“token”以及其他KEY不被remove调就可以了

**Comment by manzhizhen** [comment]
> 服务端接不到是因为TagContextFilter中的invoke方法进行了attachments.remove(TOKEN_KEY);
> 不使用“token”以及其他KEY不被remove调就可以了

哈哈，这其实也是dubbo的锅，理论上暴露给用户直接使用的方法，dubbo都应该尽量避免key和用户的key冲突，比如dubbo内部应该使用_dubbo_token这类不容易和用户冲突的key

**Comment by edgelone** [comment]
@l8i8n6jian @manzhizhen 非常感谢,真的纠结了半天啊   保留字这种   太容易坑了
