### ISSUE TITLE
多层次RPC服务依赖，如果给出最上游最适合的timeout时间

### ISSUE THREAD

**Issue by chixuan777** [apache/dubbo#4167]
A->B->C->D
B、C、D有各自的超时时间
如何从下到上的给出A最佳的超时时间限制呢？

**Comment by web1992** [comment]
这类问题在分布式系统中，都是会遇到的，其实和dubbo 关系不大。

合理的超时时间是很难设置的，如果网络波动，流量间隙性剧增，都会导致超时的发生。同时随着核心业务数据量越来越大，压力增大，总有一天这个超时时间会不满足性能要求的。

如果对超时时间要求特别高，可以对服务进行按照业务进行合理的拆分，拆分成子系统。同时对可以异步执行的业务引入MQ 消息等。

**Comment by CalvinKirs** [comment]
If necessary, you may need to consider current limiting fuses to ensure that your  time is within your stress test.

**Comment by IndiraFinish** [comment]
这种情况和框架关系不大，对数据要求强一致性的，以最下游系统为准。最终一致性的可以考虑使用消费端异步处理的方式。

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
