### ISSUE TITLE
怎么不使用原生的TagRouter

### ISSUE THREAD

**Issue by l8i8n6jian** [apache/dubbo#4168]
### Environment

* Dubbo version: 2.7.1
* Operating System version: CentOS6
* Java version:1.8

### Steps to reproduce this issue

1. 如果我不想使用原生的TagRouter，想使用定制的，该怎么配置

**Comment by kexianjun** [comment]
you just need to implement your own Router, pls refer http://dubbo.incubator.apache.org/zh-cn/docs/dev/impls/router.html
