### ISSUE TITLE
[Used by]  maven GAV has made a mistake

### ISSUE THREAD

**Issue by menng** [apache/dubbo#4173]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: dubbo-2.7.1
* Operating System version: win10 edge/chrome
* Java version: 1.8

### Steps to reproduce this issue
1. [Used by]  maven GAV has made a mistake
```xml
<dependency>
  <groupId>org.apache.dubbo</groupId>
  <artifactId>dubbo</artifactId>
  <version>ubbo-2.7.1</version>
</dependency>
```

### Expected Result
```xml
<dependency>
  <groupId>org.apache.dubbo</groupId>
  <artifactId>dubbo</artifactId>
  <version>2.7.1</version>
</dependency>
```
**ubbo-2.7.1** -> **2.7.1**
### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by ralf0131** [comment]
Yes, I notice that as well. But I don't know how Github is getting that.

**Comment by CrazyHZM** [comment]
Used by is temporarily closed.
