### ISSUE TITLE
Dubbo2.7.1 Provider注册的时候没有优先读Hostname的IP地址

### ISSUE THREAD

**Issue by evancyz** [apache/dubbo#4176]
以前默认都是读hostname的内网IP地址的

升级到2.7.1 的时候发现ip变成了公网ip

切回2.7.0 正常

**Comment by web1992** [comment]
You can change you config like this, to bind.
```xml
<dubbo:protocol name="dubbo" host="www.github.com"/>
```

**Comment by evancyz** [comment]
> You can change you config like this, to bind.
> 
> ```
> <dubbo:protocol name="dubbo" host="www.github.com"/>
> ```

6666

**Comment by manzhizhen** [comment]
> > You can change you config like this, to bind.
> > ```
> > <dubbo:protocol name="dubbo" host="www.github.com"/>
> > ```
> 
> 6666

What if you have multiple services? This is not the fundamental solution

**Comment by beiwei30** [comment]
this issue has already been addressed in `2.7.3`
