### ISSUE TITLE
Add JMH Performance Benchmarks for DUBBO

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dubbo#4184]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
yes
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
yes

JMH is a Java harness for building, running, and analysing nano/micro/milli/macro benchmarks written in Java and other languages targetting the JVM.
use JMH, some of our code changes will be more convincing

**Comment by htynkn** [comment]
I think this one can help: https://github.com/apache/dubbo-benchmark but changes must apply to make it more easy to use

**Comment by CalvinKirs** [comment]
> I think this one can help: https://github.com/apache/dubbo-benchmark but changes must apply to make it more easy to use

thank for your help.
