### ISSUE TITLE
请问，2.7.0以上admin后台哪里去了？找不到war包，是剥离了吗？请提供获取地址

### ISSUE THREAD

**Issue by wanghuan578** [apache/dubbo#4191]

**Comment by nzomkxia** [comment]
https://github.com/apache/dubbo-admin  默认的分支是Develop，采用spring boot，没有war包了

**Comment by wanghuan578** [comment]
哦，那后台是哪个jar包啊，我想拉起来学习学习

**Comment by htynkn** [comment]
可以参考README的启动说明：https://github.com/apache/dubbo-admin/blob/develop/README_ZH.md
或者尝试使用docker镜像 https://hub.docker.com/r/apache/dubbo-admin。

建议根据README的指引直接使用源代码构建启动。

**Comment by htynkn** [comment]
可以参考README的启动说明：https://github.com/apache/dubbo-admin/blob/develop/README_ZH.md
或者尝试使用docker镜像 https://hub.docker.com/r/apache/dubbo-admin。

建议根据README的指引直接使用源代码构建启动。
