### ISSUE TITLE
Compatibility problem with MonitorService interface

### ISSUE THREAD

**Issue by jasonjoo2010** [apache/dubbo#4199]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: ANY
* Java version: ANY

### Steps to reproduce this issue
Duboo 2.7.x changes package to org.apache.dubbo.
So when collecting monitor data through `MonitorService` interface instances under `2.7` use new interface subscription while old ones still use old one. Dubbo 2.7 keep some interfaces ensuring backward compatibility including `Service`/`Reference`/etc. . But `MonitorService` is not included.

Is that an issue?

I copy the old interface into my receiver project to collect data from old dubbo clients.

### Expected Result
Old MonitorService should be kept.

And there is another error log i don't know whether it's a bug.

```
ERROR o.a.d.r.t.CodecSupport [NettyServerWorker-3-8]  [DUBBO] Serialization extension org.apache.dubbo.common.serialize.protostuff.ProtostuffSerialization has duplicate id to Serialization extension org.apache.dubbo.serialize.hessian.Hessian2Serialization, ignore this Serialization extension
```

**Comment by tswstarplanet** [comment]
you can submit a pr to fix it

**Comment by jasonjoo2010** [comment]
Hey, Taosheng

Which one do you refer to, the missing deprecated interface or the duplicated serialization id?


best regards,

Jason

**Comment by beiwei30** [comment]
> ERROR o.a.d.r.t.CodecSupport [NettyServerWorker-3-8]  [DUBBO] Serialization extension org.apache.dubbo.common.serialize.protostuff.ProtostuffSerialization has duplicate id to Serialization extension org.apache.dubbo.serialize.hessian.Hessian2Serialization, ignore this Serialization extension

This issue has already been addressed.

**Comment by beiwei30** [comment]
and I am not sure if we really need to keep the old `MonitorService` in the newer release, after all the `MonitorService` is used for exposing the monitor service for the current version. The monitor center should take care of the compatibility.

**Comment by jasonjoo2010** [comment]
Close for the low priority. But we'd better describe it in document for those which have mixed versions deployed in environment and also have implemented MonitorService. (The simple solution is just copying the legacy interface into project and public them together).
