### ISSUE TITLE
Will dubbo-registry-nacos support register to the differenct namspaces with Nacos?

### ISSUE THREAD

**Issue by fofohi** [apache/dubbo#4207]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: mac osx
* Java version: 1.8

### Steps to reproduce this issue

I am using the newest dubbo and nacos,but when register to the nacos the service only show in the [public] namespace,even if I assign the namesapce name.

Will dubbo support this feature ? Nacos >= 0.8.0 has supported the namespace params.

Thank you

**Comment by ralf0131** [comment]
Hi,

Thanks for reporting. Since code has been freezed in 2.7.2, I think the support will be added in 2.7.3.

**Comment by mercyblitz** [comment]
You could try to add the parameter named "namespace" into the registry URL
