### ISSUE TITLE
NPE when the TagRouterRule addresses config is null

### ISSUE THREAD

**Issue by web1992** [apache/dubbo#4218]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: Windows
* Java version: 1.8

### Steps to reproduce this issue

When I config `TagRouter` like this (in Dubbo admin):

```YAML
enabled: true
force: false
runtime: false
tags:
  - name: tag1
    addresses: null
  - name: tag2
    addresses: null
```

### Actual Result

Then the `java.lang.NullPointerException` was caused

```
java.lang.NullPointerException
	at org.apache.dubbo.rpc.cluster.router.tag.model.TagRouterRule.lambda$init$2(TagRouterRule.java:55)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.apache.dubbo.rpc.cluster.router.tag.model.TagRouterRule.init(TagRouterRule.java:53)
	at org.apache.dubbo.rpc.cluster.router.tag.model.TagRuleParser.parse(TagRuleParser.java:42)
```

I think we should add NPE check in `TagRouterRule` or check `addresses ` in Dubbo admin

```java
tags.forEach(tag -> {
    tagnameToAddresses.put(tag.getName(), tag.getAddresses());
   // check  tag.getAddresses() not null
    tag.getAddresses().forEach(addr -> {
        List<String> tagNames = addressToTagnames.computeIfAbsent(addr, k -> new ArrayList<>());
        tagNames.add(tag.getName());
    });
});
```

**Comment by CrazyHZM** [comment]
Can you submit a PR to fix it?

**Comment by web1992** [comment]
@CrazyHZM  I have send one PR

**Comment by CrazyHZM** [comment]
Thank you, I have already dealt with it.
