### ISSUE TITLE
maven project compile error 

### ISSUE THREAD

**Issue by xiqicode** [apache/dubbo#4227]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project  dubbo-rpc-xml: Compilation failure 

dubbo\dubbo-rpc\dubbo-rpc-xml\src\main\java\org\apache\dubbo\xml\rpc\protocol\xmlrpc\XmlRpcProtocol.java:[154,4] 错误: Override 不是可重复的注释类型

**Comment by wanghbxxxx** [comment]
there are duplicate Override annotations.
