### ISSUE TITLE
netty 不进行水位控制导致应用OOM

### ISSUE THREAD

**Issue by yiyanghua** [apache/dubbo#4241]
使用netty传输的时候，没有进行水位控制导致应用OOM

**Comment by carryxyh** [comment]
一般情况下不会产生这种问题，是有背压现象么？

**Comment by yiyanghua** [comment]
netty write到channel buffer里面，尤其是在provider 异步的情况下，很容易导致oom

**Comment by lexburner** [comment]
Dubbo 没配置 Netty 的水位控制，因为业务报文的大小是没法估计的，不配置的话，使用的是默认配置：
水位低水位32K，高水位64K
这些应该不是导致 OOM 的直接原因吧？是否可以详细描述下你们测试的场景？
