### ISSUE TITLE
dubbo2.7.1-AbstractConfig.java-getMetaData set default depend on getmethod sequence

### ISSUE THREAD

**Issue by owen200008** [apache/dubbo#4248]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: centos, windows
* Java version: 
centos : openjdk version "1.8.0_212"
windows: oracle jdk  java version "1.8.0_201"

### Steps to reproduce this issue

just run no set generic

1.  register generic service like:

```java
        ServiceConfig<GenericService> service = new ServiceConfig<GenericService>();
        service.setInterface(registerServiceConfInterface.getInterfaceName());
        service.setVersion(registerServiceConfInterface.getVersion());
        service.setGroup("test");
        service.setGeneric("true");
        service.setRef();//just implement GenericService is ok return null
       service.export();
```

2. use @Reference define like follow

```java
  @Reference(version = "1.0.0", timeout = 5000, group = "test", check = false)
  private DubboVersionFacade dubboVersionFacade;
```

3. result:
(1) start on windows the generic is null
(2) start on centos generic is false
reason:
AbstractReferenceConfig have two function to set generic 
(1) isgeneric 
(2) setgeneric 
get methods sequence isgeneric first it will be null
get methods sequence setgeneric first it will be false

can i add the Parameter parameter to exclude the isgeneric ?

**Comment by owen200008** [comment]
add the code 
if(parameter.excluded())
   continue;

**Comment by owen200008** [comment]
centos update the jdk version to oracle jdk java version "1.8.0_211" it is same to openjdk。
maybe different platform compile is different，methods sequence different.
it is ok run with dubbo-2.6.2

**Comment by cvictory** [comment]
https://github.com/apache/dubbo/pull/4678
