### ISSUE TITLE
清除一下NacosDynamicConfiguration 177行的 System.out.println("1");

### ISSUE THREAD

**Issue by naturezhm** [apache/dubbo#4252]
### Environment

* Dubbo version: 2.7.2

### 问题描述
如题，在NacosDynamicConfiguration的177行有一行System.out.println("1"); 在启动时，会一直在控制台输出，看着很不专业。

类路径如下： 
https://github.com/apache/dubbo/blob/master/dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java

**Comment by CrazyHZM** [comment]
sorry，can you submit a PR to remove it?

**Comment by naturezhm** [comment]
https://github.com/apache/dubbo/pull/4261

Already submitted. PLZ confirm and pass it.

**Comment by beiwei30** [comment]
it's already fixed.
