### ISSUE TITLE
 2.7.2还不能从maven仓库中下载

### ISSUE THREAD

**Issue by zjw2011** [apache/dubbo#4253]
dubbo2.7.2 还没有上传到maven仓库中，什么时间上传上去？

**Comment by logan2013** [comment]
+1
when can we use 2.7.2 from maven

**Comment by dhchao11** [comment]
http://repo1.maven.org/maven2/org/apache/dubbo/dubbo/2.7.2/

**Comment by kexianjun** [comment]
It's now available
