### ISSUE TITLE
dubbo 2.7.2配置zookeeper，提示不支持

### ISSUE THREAD

**Issue by zhangkangyue** [apache/dubbo#4263]
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.configcenter.DynamicConfigurationFactory by name zookeeper

**Comment by zhangkangyue** [comment]
<dubbo:registry address="zookeeper://127.0.0.1:2181"/>

**Comment by CrazyHZM** [comment]
在pom文件里面加入configcenter的依赖例如加入dubbo-configcenter-zookeeper依赖你就可以跑demo了

**Comment by arjenzhou** [comment]
@zhangkangyue 
You can refer to https://github.com/arjenzhou/dubbo-demo, there are some my experience about it.

**Comment by zhangkangyue** [comment]
> @zhangkangyue
> You can refer to https://github.com/arjenzhou/dubbo-demo, there are some my experience about it.

provider端：
<dubbo:application name="dubbo-provider"/>
    <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
    <dubbo:registry address="zookeeper://127.0.0.1:2181" simplified="true"/>
    <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>
    <bean id="greetingService" class="cn.jcorn.dubbo.provider.GreetingServiceImpl"/>
    <dubbo:service interface="cn.jcorn.dubbo.api.GreetingService" ref="greetingService"/>

consumer端：<dubbo:application name="dubbo-consumer"/>
    <dubbo:registry address="zookeeper://127.0.0.1:2181"/>
    <dubbo:reference id="greetingService" check="false" interface="cn.jcorn.dubbo.api.GreetingService"/>

启动dubbo-demo consumer报错：
Exception in thread "main" org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service cn.jcorn.dubbo.api.GreetingService. No provider available for the service cn.jcorn.dubbo.api.GreetingService from registry 127.0.0.1:2181 on the consumer 30.16.96.186 using the dubbo version 2.7.1. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:265)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:57)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:242)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:76)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at cn.jcorn.dubbo.consumer.Consumer.main(Consumer.java:11)

**Comment by arjenzhou** [comment]
@zhangkangyue
Please refer to README, I met the same issue and solve it by that way.

**Comment by arjenzhou** [comment]
Also, is 30.16.96.186 your ip address? 

Provide your environment will be a good way for help.

**Comment by zhangkangyue** [comment]
> Also, is 30.16.96.186 your ip address?
> 
> Provide your environment will be a good way for help.

是的

**Comment by zhangkangyue** [comment]
> @zhangkangyue
> You can take a look at zookeeper client whether provider is properly resgisted to zookeeper or not.

我把zk  节点/dubbo删除，consumer消费正常了。是脏数据导致的吗？

**Comment by arjenzhou** [comment]
https://github.com/apache/dubbo/issues/4213
https://github.com/apache/dubbo/issues/3785

You can refer to these two issues.

**Comment by wallacefw1987** [comment]
> > @zhangkangyue
> > You can refer to https://github.com/arjenzhou/dubbo-demo, there are some my experience about it.
> 
> provider端：
> <dubbo:application name="dubbo-provider"/>
> <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
> <dubbo:registry address="zookeeper://127.0.0.1:2181" simplified="true"/>
> <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>
> 
> <dubbo:service interface="cn.jcorn.dubbo.api.GreetingService" ref="greetingService"/>
> 
> consumer端：<dubbo:application name="dubbo-consumer"/>
> <dubbo:registry address="zookeeper://127.0.0.1:2181"/>
> <dubbo:reference id="greetingService" check="false" interface="cn.jcorn.dubbo.api.GreetingService"/>
> 
> 启动dubbo-demo consumer报错：
> Exception in thread "main" org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service cn.jcorn.dubbo.api.GreetingService. No provider available for the service cn.jcorn.dubbo.api.GreetingService from registry 127.0.0.1:2181 on the consumer 30.16.96.186 using the dubbo version 2.7.1. Please check if the providers have been started and registered.
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:265)
> at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:57)
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:242)
> at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:76)
> at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57)
> at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
> at cn.jcorn.dubbo.consumer.Consumer.main(Consumer.java:11)



> > @zhangkangyue
> > You can refer to https://github.com/arjenzhou/dubbo-demo, there are some my experience about it.
> 
> provider端：
> <dubbo:application name="dubbo-provider"/>
> <dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
> <dubbo:registry address="zookeeper://127.0.0.1:2181" simplified="true"/>
> <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"/>
> 
> <dubbo:service interface="cn.jcorn.dubbo.api.GreetingService" ref="greetingService"/>
> 
> consumer端：<dubbo:application name="dubbo-consumer"/>
> <dubbo:registry address="zookeeper://127.0.0.1:2181"/>
> <dubbo:reference id="greetingService" check="false" interface="cn.jcorn.dubbo.api.GreetingService"/>
> 
> 启动dubbo-demo consumer报错：
> Exception in thread "main" org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service cn.jcorn.dubbo.api.GreetingService. No provider available for the service cn.jcorn.dubbo.api.GreetingService from registry 127.0.0.1:2181 on the consumer 30.16.96.186 using the dubbo version 2.7.1. Please check if the providers have been started and registered.
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:265)
> at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:57)
> at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:242)
> at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:76)
> at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57)
> at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
> at cn.jcorn.dubbo.consumer.Consumer.main(Consumer.java:11)
-----------------------------------------------------------------------------------------------------------
我也遇到这个问题 ， 不过我跟着这个 demo `https://github.com/arjenzhou/dubbo-demo.git` 去覆盖（dubbo-demo-xml）项目后，问题解决了
