### ISSUE TITLE
consistentHash loadbalance has multi-thread problem 

### ISSUE THREAD

**Issue by wzc903011** [apache/dubbo#4270]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: mac os 10.13.4
* Java version:  jdk8

### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/9124779/59173853-66029c80-8b81-11e9-9bd6-912f55432544.png)
I have 300 provider instance; so i set 2000 virutal nodes; 
when the quantity of provider changed,  consumer need to refresh the "ConsistentHashSelector";  if the qps is 200,  consumer will create 200 "ConsistentHashSelector" ; 
it cost 300ms to create a "ConsistentHashSelector"  with 2000 virtual nodes and 300 providers；

1. com.alibaba.dubbo.rpc.cluster.loadbalance.ConsistentHashLoadBalance
set hash.nodes = 2000；
2.   deploy 3 providers,  every provider use consistentHash loadbalance
3. consumer set timeout as 100ms ，test qps is 100， deploy the forth provider,  the thread in cusumer will be blocked。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by web1992** [comment]
Please past some java stack dump info.
use `jstack pid` to dump

**Comment by wzc903011** [comment]
![image](https://user-images.githubusercontent.com/9124779/59187285-b7258700-8ba7-11e9-92c8-02c82be004b7.png)
![image](https://user-images.githubusercontent.com/9124779/59187752-b7725200-8ba8-11e9-9842-c28b3685116a.png)
jstack的结果可能不是你想要的，因为---》
我是在本地（1个consumer + 3个provider ==》1000个virtualnode）；
consumer里创建了线程池，100个线程并行请求provider； 很明显在初始化和扩容缩容的时候，创建的对象很大（我自己复制了一个一致性hash，通过打日志，发现创建了100个ConsistentHashSelector）

**Comment by web1992** [comment]
Please give a demo in Githu. So that I can run the demo by myself.

**Comment by wzc903011** [comment]
> Please give a demo in Githu. So that I can run the demo by myself.
git@github.com:wzc903011/ex-dubbo.git

**Comment by wzc903011** [comment]
> Please give a demo in Githu. So that I can run the demo by myself.
git@github.com:wzc903011/ex-dubbo.git
run two UserServiceApplication and one UserWebApplication;  the invoke http://localhost:8080/uidrequest；

**Comment by web1992** [comment]
I can't find  `loadbalance` config in `appcontext-consumer.xml` ,it's some config error?

```xml
<dubbo:reference id="userQueryRemoteService" interface="com.mingqi.local.userservice.UserQueryRemoteService"
    timeout="50"/>
```

**Comment by wzc903011** [comment]
> I can't find `loadbalance` config in `appcontext-consumer.xml` ,it's some config error?
> 
> ```
> <dubbo:reference id="userQueryRemoteService" interface="com.mingqi.local.userservice.UserQueryRemoteService"
>     timeout="50"/>
> ```
config in provider

**Comment by web1992** [comment]
Dubbo 的集群和负载均衡策略应该配置在 consumer 方的。如果有多个 provider ,consumer 会通过负载均衡策略去选择一个合适的 provider .

**Comment by wzc903011** [comment]
> Dubbo 的集群和负载均衡策略应该配置在 consumer 方的。如果有多个 provider ,consumer 会通过负载均衡策略去选择一个合适的 provider .

问题是一样的，我把配在consumer上的代码传上来了。

**Comment by wzc903011** [comment]
> Dubbo 的集群和负载均衡策略应该配置在 consumer 方的。如果有多个 provider ,consumer 会通过负载均衡策略去选择一个合适的 provider .

并发和耗时的问题，辛苦帮忙看下是不是支持下，不然要在consumer端建线程池去异步初始化一致性hash的map

**Comment by web1992** [comment]
1. 50ms 的超时时间实在是太短了吧。你什么业务能保证在50ms 内完成？这个时间不符合实际。
2. consumer 第一次在调用的时候，肯定是要对 loadbalance 进行初始化的，如果设置了几千个 `hash.codes` 和 provider 有几千的时候，第一次耗时肯定会需要比较久的时间的。可以自定义一个loadbalance 同时用一个标记来标记 virtualInvokers 是否初始化完成(初始化过程可设置成异步的，用一个线程来处理)如果没有初始化完成，就随机一个 invoker.如果初始化完成了，那么走select 逻辑去进行hash 选择。这样可以避免第一次耗时过久的问题。
3. Dubbo 原始的 ConsistentHashLoadBalance 没发现有并非的问题呐。。

**Comment by wavesZh** [comment]
i cannot find the problem that you said by your demo, maybe i do not call right. And `timeout` work on `DefaultFuture#get()` that invoked after `LoadBalance.select(...)`, so initialization/refresh time of  `ConsistentHashSelector` do not  be include in 'timeout'.

**Comment by wzc903011** [comment]
> 1. 50ms 的超时时间实在是太短了吧。你什么业务能保证在50ms 内完成？这个时间不符合实际。
> 2. consumer 第一次在调用的时候，肯定是要对 loadbalance 进行初始化的，如果设置了几千个 `hash.codes` 和 provider 有几千的时候，第一次耗时肯定会需要比较久的时间的。可以自定义一个loadbalance 同时用一个标记来标记 virtualInvokers 是否初始化完成(初始化过程可设置成异步的，用一个线程来处理)如果没有初始化完成，就随机一个 invoker.如果初始化完成了，那么走select 逻辑去进行hash 选择。这样可以避免第一次耗时过久的问题。
> 3. Dubbo 原始的 ConsistentHashLoadBalance 没发现有并非的问题呐。。
1. 是系统要求，就不讨论了。  
2. provider在部署、扩缩容的时候，consumer都需要重新初始化virtualInvokers；loadbalance是在consumer实例里完成，要异步初始化，需要在consumer里创建线程池，能不能使用dubbo的线程池完成，这样consumer出问题的时候，也好定位。
3. 并发不会导致逻辑问题，会导致同一个method的ConsistentHashSelector被初始化多次。

**Comment by web1992** [comment]
我自己写了一个，提供下我自己的思路，看是否有帮助 [CustConsistentHashLoadBalance](https://github.com/web1992/dubbos/blob/master/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/java/cn/web1992/dubbo/demo/loadbance/CustConsistentHashLoadBalance.java)

上面的第三点 `ConsistentHashSelector`  被初始化多次确实会发生，因为`System.identityHashCode(invokers)`  在 `invokers` ，没有发生变化的时候，确发生了变化,因此会导致 `ConsistentHashSelector` 被实例化多次 ，可以用 `invokers.hashCode()` 代替 ,`invokers.hashCode()` 方法来自`AbstractList`,从下面的实现可以看出 `invokers` 发生变化的时候，hascode 会发生变化。会重新生成虚拟节点。
```java
    // from AbstractList
    public int hashCode() {
        int hashCode = 1;
        for (E e : this)
            hashCode = 31*hashCode + (e==null ? 0 : e.hashCode());
        return hashCode;
    }
```

**Comment by wzc903011** [comment]
> 我自己写了一个，提供下我自己的思路，看是否有帮助 [CustConsistentHashLoadBalance](https://github.com/web1992/dubbos/blob/master/dubbo-demo-xml/dubbo-demo-xml-consumer/src/main/java/cn/web1992/dubbo/demo/loadbance/CustConsistentHashLoadBalance.java)
> 
> 上面的第三点 `ConsistentHashSelector` 被初始化多次确实会发生，因为`System.identityHashCode(invokers)` 在 `invokers` ，没有发生变化的时候，确发生了变化,因此会导致 `ConsistentHashSelector` 被实例化多次 ，可以用 `invokers.hashCode()` 代替 ,`invokers.hashCode()` 方法来自`AbstractList`,从下面的实现可以看出 `invokers` 发生变化的时候，hascode 会发生变化。会重新生成虚拟节点。(当invokers 没有变化，每次方法调用（频繁）都生成大量的虚拟节点的时候，确实会浪费内存和降低性能)
> 
> ```java
>     // from AbstractList
>     public int hashCode() {
>         int hashCode = 1;
>         for (E e : this)
>             hashCode = 31*hashCode + (e==null ? 0 : e.hashCode());
>         return hashCode;
>     }
> ```

嗯 这个写法和我上传的样例类似，使用dubbo的其中一个consumer线程去完成初始化，而dubbo是在 LoadBalance.select(...)执行完成后再去调用DefaultFuture#get()，我最开始没注意到这个，所以担心会阻塞其中一个线程。 谢谢了
