### ISSUE TITLE
Why there is `clazz.getConstructor();` in `ExtensionLoader.loadClass` method ?

### ISSUE THREAD

**Issue by anLA7856** [apache/dubbo#4273]
I found there is a line code `clazz.getConstructor();` in ` ExtensionLoader.loadClass` method. 
getConstructor just return it's constructor but there is't a variable to accept it.
Therefore, if it is useless, why not remove it?
[ExtensionLoader](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java)

**Comment by web1992** [comment]
When we use `clazz.newInstance()` to new instance. Default we must have a no-arguments constructor.

I think Dubbo use `clazz.getConstructor()` to check wheater if a no-arguments constructor in you customer extension. If no exception will cause.
