### ISSUE TITLE
泛化调用时，float类型精度会丢失

### ISSUE THREAD

**Issue by Sakuramaomao** [apache/dubbo#4275]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by Sakuramaomao** [comment]
dubbo版本：2.7.2
springboot版本：2.1.3

**Comment by CrazyHZM** [comment]
repeated #3861 
I will close this issue first. If it is a different phenomenon, please re-open this issue.
