### ISSUE TITLE
提供者禁用无效

### ISSUE THREAD

**Issue by caiqien** [apache/dubbo#428]
列表界面将提供者禁用，点击进去看到的状态还是启动状态，消费端依然能调用该服务。这是什么情况？

**Comment by justein** [comment]
bug，这个admin是阉割版，有不少bug。建议看源码根据需求自己实现，或者可以试下：dubbokeeper

**Comment by yunhaibin** [comment]
@caiqien 推荐看一下[dubbokeeper](https://github.com/dubboclub/dubbokeeper)

**Comment by caiqien** [comment]
@yunhaibin 谢谢

**Comment by david1228** [comment]
@yunhaibin  @justein
我也遇到类似问题，不过我在列表界面将一个服务禁用后能生效。然后，再启用，状态还是已禁用，手动编辑页面修改disabled=false显示已启用，但是服务不可用，再次进入编辑界面仍然显示：disabled=true
想问下如何恢复这个服务？将disabled=true去掉呢，thanks

**Comment by david1228** [comment]
@yunhaibin 谢谢，我看看。

**Comment by zylele** [comment]
欢迎试用我集成的[dubbokeeperMySQL快速启动版](https://github.com/zylele/dubbokeeper-mqs)，集成监控与展示，节省服务器资源，提供一键编译部署。新增服务预警接口、权限登录功能
