### ISSUE TITLE
do not know `(name.startsWith("get") || name.length() > 3)` in `AdaptiveClassCodeGenerator.generateUrlAssignmentIndirectly` method to find URL getter method ?

### ISSUE THREAD

**Issue by huanlekkx** [apache/dubbo#4281]
do not know `(name.startsWith("get") || name.length() > 3)` in `AdaptiveClassCodeGenerator.generateUrlAssignmentIndirectly` method to find URL getter method ?

**Comment by RussXia** [comment]
I can't understand why this is an `||` operation too.[code here](https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/extension/AdaptiveClassCodeGenerator.java)
