### ISSUE TITLE
dubbo泛化调用时支持给属性加别名，例如对象属性里order_id转换成orderId？

### ISSUE THREAD

**Issue by superstarchenxin** [apache/dubbo#4286]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.4
* Operating System version: CentOS 6.7
* Java version: 1.8

### Steps to reproduce this issue
```java
@Getter
@Setter
public class BaseResponse {
    @JSONField(name = "order_id")
    private int orderId;
}
```

### Expected Result
BaseResponse {
   private int order_id;
}

### Actual Result
BaseResponse {
   private int orderId;
}

**Comment by chickenlj** [comment]
please work on this ticket https://github.com/apache/dubbo/pull/4296
