### ISSUE TITLE
Unable to locate Method of ExceedPayloadLimitException

### ISSUE THREAD

**Issue by Arugal** [apache/dubbo#4287]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: Linux 3.10.0-957.5.1.el7.x86_64
* Java version: 1.8

### Steps to reproduce this issue

Data length too large

### Expected Result

Locate the exception method based on the log

### Actual Result

java.io.IOException: Data length too large: 18463787, max payload: 8388608, channel: NettyChannel [channel=[id: 0x57203c57, /127.0.0.1:43554 => /127.0.0.1:20890]]

**Comment by wanghbxxxx** [comment]
they run in different threads:
caller method in user thread
payload checker in netty's thread
