### ISSUE TITLE
dubbo-admin服务治理没有对接口的方法参数说明

### ISSUE THREAD

**Issue by caiqien** [apache/dubbo#430]
只能看到服务接口，而没有列表对每个接口的方法以及需要传的参数进行说明。API管理太粗糙。点击禁用服务还报了404.

**Comment by yunhaibin** [comment]
@caiqien dubbo的admin和monitor本身就是瘦身阉割后的示例，除非你有能力有精力在基础上去改造和优化，不然不建议生产使用admin和monitor，建议你看看这个项目[dubbokeeper](https://github.com/dubboclub/dubbokeeper)可以考虑生产上直接使用

**Comment by caiqien** [comment]
@yunhaibin dubbokeeper我发现禁用服务（已经注册多个服务）之后消费端也还是能够调用查询数据的，而且路由添加似乎也不起作用。

**Comment by yunhaibin** [comment]
@caiqien 不会有这么严重的bug吧，是不是哪里配置有点问题，我没在项目中用dubbokeeper，只是看过这个项目，好像项目是从15年就开始做了，按道理应该已经比较完善了，怎么还会有这种低级问题，抽空我搭个测试环境试一下，或者你在issue里面看看是不是确实有同样的问题存在。

**Comment by yunhaibin** [comment]
#428 同样的问题

**Comment by caiqien** [comment]
@yunhaibin 是啊，dubbo-admin和dubbokeeper似乎都有同样的问题。禁用这种功能应该是不需要专门配置什么地方的吧，应该是控制台跑起来就应有的功能。人家都是dubbo本身的机制是如果是一个提供者禁用是无效的，我试了多个，也是无效。

**Comment by nzomkxia** [comment]
请试一下目前新版本的dubbo ops是否有这个问题：https://github.com/apache/incubator-dubbo-ops
