### ISSUE TITLE
dubbo 2.7.2 一台服务器启动多个报qos-server can not bind localhost:22222, dubbo version: 2.7.2

### ISSUE THREAD

**Issue by lwjsw2320214** [apache/dubbo#4307]
dubbo 版本：2.7.2 

![image](https://user-images.githubusercontent.com/5327274/59481144-bafe2580-8e95-11e9-8aa7-92554e4eeec6.png)
更改后无效还是继续报错，但是服务能启动
![image](https://user-images.githubusercontent.com/5327274/59481184-dbc67b00-8e95-11e9-9b00-fbf48cda01a0.png)

![image](https://user-images.githubusercontent.com/5327274/59481270-25af6100-8e96-11e9-870b-8422afc315ab.png)

**Comment by dai19470** [comment]
请修改服务端口

**Comment by web1992** [comment]
你需要把 dubbo.properties 的配置注释了,dubbo.properties  的优先级要高

```properties
dubbo.application.qos.port=22222
```
把上面的配置删掉

配置文件的优先级文章 [http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html](http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html)

**Comment by lwjsw2320214** [comment]
> 你需要把 dubbo.properties 的配置注释了,dubbo.properties 的优先级要高
> 
> ```ini
> dubbo.application.qos.port=22222
> ```
> 
> 把上面的配置删掉
> 
> 配置文件的优先级文章 http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html
我直接用的xml 配置，没有用properties方式

**Comment by xiaofeiahaha** [comment]
dubbo2.7.2版本的qos配置参数被改过了，取的是qos-enable
![image](https://user-images.githubusercontent.com/11786784/60635391-3cb5f300-9e45-11e9-8916-0e47af8e6305.png)

**Comment by xiaofeiahaha** [comment]
qos 2.7.2版本参数改过了，取的是qos-enable,qos-port

**Comment by zenochen** [comment]
why not release one version for the qos related bug fix?
all the qos settings cannot be take effect.
so I must rollback to 2.7.1

**Comment by morningcat2018** [comment]
> why not release one version for the qos related bug fix?
> all the qos settings cannot be take effect.
> so I must rollback to 2.7.1

I had the same problem.

**Comment by linxiaobai** [comment]
> 你需要把 dubbo.properties 的配置注释了,dubbo.properties 的优先级要高
> 
> ```ini
> dubbo.application.qos.port=22222
> ```
> 
> 把上面的配置删掉
> 
> 配置文件的优先级文章 http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html

没用，我的版本2.7.3，试了没效果

**Comment by AlbumenJ** [comment]
> > 你需要把 dubbo.properties 的配置注释了,dubbo.properties 的优先级要高
> > ```ini
> > dubbo.application.qos.port=22222
> > ```
> > 
> > 
> > 把上面的配置删掉
> > 配置文件的优先级文章 http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html
> 
> 没用，我的版本2.7.3，试了没效果

你可以考虑指定为其他端口，因为22222是默认绑定端口
