### ISSUE TITLE
Dubbo服务版本修改

### ISSUE THREAD

**Issue by jiafuweiJava** [apache/dubbo#4313]
![image](https://user-images.githubusercontent.com/20169094/59496009-24e0f400-8ec3-11e9-9164-0f3c19457a95.png)
如何修改生产者的dubbo版本？通过dubbo-admin，查看到的版本不一样！怎么把2.4.9的这个应用版本改成2.0.2

**Comment by web1992** [comment]
这个版本号应该是通过 MANIFEST.MF 文件读取的。
具体的实现逻辑 在`org.apache.dubbo.common.Version` 中。
如果你想修改这个版本号需要所有的Dubbo服务使用相同的 jar 包版本，可以通过maven 修改。

希望能有帮助。

**Comment by jiafuweiJava** [comment]
> 这个版本号应该是通过 MANIFEST.MF 文件读取的。
> 具体的实现逻辑 在`org.apache.dubbo.common.Version` 中。
> 如果你想修改这个版本号需要所有的Dubbo服务使用相同的 jar 包版本，可以通过maven 修改。
> 
> 希望能有帮助。

好的   谢谢！  你说的 “所有的Dubbo服务使用相同的 jar 包” 指的是dubbo的jar吗

**Comment by web1992** [comment]
@jiafuweiJava  是的

比如这个：
![image](https://user-images.githubusercontent.com/6828647/59582550-34527e00-910b-11e9-814c-fb1215b878fe.png)

**Comment by cvictory** [comment]
dubbo之前版本，没有区分协议和dubbo的包版本。 
在2.6的部分版本中，已经统一将这个版本声明为2.0.2，就是协议版本。没有提供包的版本。
在2.7中，除了协议版本之外，增加了release-key，作为包的版本。 
无论怎么样，老的admin估计都不识别。

**Comment by qixiaobo** [comment]
可以参考当时的issue https://github.com/apache/dubbo/pull/1843

**Comment by qixiaobo** [comment]
https://github.com/apache/dubbo/issues/1466

**Comment by qixiaobo** [comment]
因为这个改动导致和低版本不兼容 新的修复pr 在这 https://github.com/apache/dubbo/pull/2117
