### ISSUE TITLE
export服务，applicationEventPublisher为null

### ISSUE THREAD

**Issue by niejian** [apache/dubbo#4314]
### Environment

* Dubbo version:  2.6.6
* Operating System version: mac
* Java version:  1.8

### Steps to reproduce this issue

在spring boot 1.5.3的环境中，使用注解@Service方式注册相关的服务，在启动项目的时候爆出 ` Initialization of bean failed; nested exception is java.lang.NullPointerException` 错误。经过调试发现**dubbo在export服务的发布通知的时候时候, `applicationEventPublisher` 是空**，请问如何解决
![](https://s2.ax1x.com/2019/06/14/V5nLnA.md.jpg)

**Comment by web1992** [comment]
检查一下自己的 spring-boot 的配置吧。我自己搭建的spring boot + Dubbo 没有问题

[dubbo-spring-boot](https://github.com/web1992/dubbos/tree/master/dubbo-spring-boot)

**Comment by niejian** [comment]
> 检查一下自己的 spring-boot 的配置吧。我自己搭建的spring boot + Dubbo 没有问题
> 
> [dubbo-spring-boot](https://github.com/web1992/dubbos/tree/master/dubbo-spring-boot)
> 
> 我用的是 Spring boot starter. Spring boot 版本改成 `1.5.3.RELEASE` 也没错误

你确定？？？？

**Comment by niejian** [comment]
是spring版本的问题。spring版本改变为5+之后就可以了。springboot1.5.3使用的spring4.3.8的版本
