### ISSUE TITLE
In concurrent environment, should use AtomicXXX instead of volatile to increase

### ISSUE THREAD

**Issue by slievrly** [apache/dubbo#4323]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/8758457/59562427-2e06c800-905f-11e9-9bff-9ea54d87fc6d.png)
![image](https://user-images.githubusercontent.com/8758457/59562435-51317780-905f-11e9-930b-a66bc866ccf1.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by kexianjun** [comment]
how about to make the org.apache.dubbo.cache.support.AbstractCacheFactory#createCache synchronized like the following:
```java
@Override
    public Cache getCache(URL url, Invocation invocation) {
        url = url.addParameter(METHOD_KEY, invocation.getMethodName());
        String key = url.toFullString();
        Cache cache = caches.get(key);
        if (cache == null) {
            cacheLock.lock();
            if (null == caches.get(key)) {
                try {
                    caches.put(key, createCache(url));
                }finally {
                    cacheLock.unlock();
                }
            }
            cache = caches.get(key);
        }
        return cache;
    }
```
