### ISSUE TITLE
RegistryConfig equals issue

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4337]
```java
RegistryConfig registry1 = new RegistryConfig();
RegistryConfig registry2 = new RegistryConfig();
registry1.setAddress("zookeeper://127.0.0.1:2182");
registry2.setAddress("zookeeper://127.0.0.1:2183");
```

In fact registry1.equals(registry2) will return **true**. This may lead issue in org.apache.dubbo.config.context.ConfigManager#addRegistry

**Comment by cvictory** [comment]
The get method is annotated @Parameter(excluded = true),  so that it will ignore in equals method.

```
 @Parameter(excluded = true)
    public String getAddress() {
        return address;
    }
```

![image](https://user-images.githubusercontent.com/4089452/59742487-61846500-92a0-11e9-9999-4ede505a13f1.png)

But this `exclude` parameter is also used somewhere else, such as appendParameters.

**Comment by Leishunyu** [comment]
You can solve the equals problem by modifying the setAddress method of registryConfig.
