### ISSUE TITLE
parameters config  in properties will not take effect

### ISSUE THREAD

**Issue by imsunv** [apache/dubbo#4342]
in the doc:

http://dubbo.apache.org/zh-cn/docs/user/configuration/configuration-load-process.html

```
dubbo.application.parameters.item1=value1
dubbo.application.parameters.item2=value2
dubbo.registry.parameters.item3=value3
dubbo.reference.org.apache.dubbo.samples.api.DemoService.parameters.item4=value4
```

this config seems, will not take effect.

**Comment by chickenlj** [comment]
> dubbo.reference.org.apache.dubbo.samples.api.DemoService.parameters.item4=value4

Yes, this is a known issue, we are planning to solve this problem in 2.7.4, which is expected to be released in 1 month.

**Comment by chickenlj** [comment]
related https://github.com/apache/dubbo/issues/4882

**Comment by chickenlj** [comment]
pull request https://github.com/apache/dubbo/pull/4899
