### ISSUE TITLE
[ISSUE] Dubbo+nacos throw classNotFound

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#4347]
Dubbo 2.7.2 + Nacos 1.0.0 works well, but Nacos 1.0.1 failed as following: 

![image](https://user-images.githubusercontent.com/4089452/59749456-9ba93300-92af-11e9-9bf9-330d8e8482fc.png)

**Comment by JerryChin** [comment]
I'd like to create a PR for this issue. 

Should I simply remove the reference to `om.alibaba.nacos.client.naming.utils.StringUtils` ?

**Comment by IanCao** [comment]
https://github.com/apache/dubbo/pull/4308

**Comment by IanCao** [comment]
#4308
