### ISSUE TITLE
实现dubbo灰度，消费端有对应路由实现吗？

### ISSUE THREAD

**Issue by zhangkangyue** [apache/dubbo#4366]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by web1992** [comment]
可以在消费端实现自己的 Filter,通过 Filter 对customer的请求标记tag,如下：
```java
RpcContext.getContext().setAttachment("tag1","test-tag");
```
同时通过配置中心对 provider 进行tag 标记。

**Comment by chickenlj** [comment]
具体请参考文档中的标签路由部分 http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html

**Comment by chickenlj** [comment]
`RpcContext.getContext().setAttachment("tag1","test-tag");`

除了在代码中做以上设置外，Dubbo也可以读取特定位置的环境变量，也就是说只要机器被划分好环境，部署在其中的Dubbo应用即可自动被流量划分
