### ISSUE TITLE
关于dubbo 无故超时调用的问题

### ISSUE THREAD

**Issue by myhzy** [apache/dubbo#4367]
应用服务信息:
项目拆分为七个服务，每台服务器上都会部署这七个服务
其中一个服务(简称api服务)作为用户请求入口，通过dubbo对另外六个服务进行调用
注册中心：单机zookeeper

问题:
项目常态下接口平均响应时间90ms左右, 运行一段时间后(目前是约一天左右),  会出现部分机器上的api服务调用dubbo服务耗时增长, 直至无法在超时时间内响应（超时时间配置的是30秒）, 引起崩溃。（注：不是四台机器上的api调用dubbo服务都会超时, 其中1～2台, 每次崩溃的机器也不一样）
崩溃时服务器cpu, 内存, 带宽出入均正常。
数据库cpu, 内存, 连接数正常，没有慢查询。
dubbo监控图显示provider耗时正常, consumer耗时很高
用了无数种办法，依旧不能确定.

**Comment by web1992** [comment]
请提供下 Dubbo 的版本信息。

**Comment by chickenlj** [comment]
请提供一些更详细的信息再reopen，以方便社区用户帮助定位问题。目前已有信息我们很难帮助定位。
