### ISSUE TITLE
2.7.2 AccessLogFilter

### ISSUE THREAD

**Issue by gioxiao** [apache/dubbo#4374]
String accessLogKey = invoker.getUrl().getParameter(ACCESS_LOG_KEY);
是不是应该改成
String accessLogKey = invoker.getUrl().getParameter(Constants.ACCESS_LOG_KEY);
url里面没有dubbo.accesslog参数

**Comment by kexianjun** [comment]
no, pls see the import statement
```java
import static org.apache.dubbo.rpc.Constants.ACCESS_LOG_KEY;

```
