### ISSUE TITLE
Why Dubbo and RPC?

### ISSUE THREAD

**Issue by Lrcezimbra** [apache/dubbo#4382]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

I searched in FAQ and docs and I didn't find an answer.

Why and when use Dubbo?
Given that REST APIs are increasingly common, why use RPC instead of web services?
What's the advantages to use RPC instead REST web services?
What's the point that I'm don't catching? 
I talk with people that have the same doubt. I think that this point could be answered in FAQ.

Thanks.

**Comment by tswstarplanet** [comment]
You can have a look the official website.
https://dubbo.apache.org
