### ISSUE TITLE
[bug] RpcContext.getContext().getUrl().toFullString();  throw NPE

### ISSUE THREAD

**Issue by yintiefu** [apache/dubbo#4390]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Java version: 1.8

### Steps to reproduce this issue
```` java
           //泛化调用，异步
            ref.$invoke(callMethod, typeArrays, objectArrays);

            //2.7.1正常，2.7.2出现npe
            String uri = RpcContext.getContext().getUrl().toFullString();
            event.setTotalUri(uri);

            Future<Object> result = RpcContext.getContext().getFuture();

````
上面同一段代码，2.7.1的时候没有问题， 2.7.2 RpcContext.getContext().getUrl().toFullString();会出现npe

![image](https://user-images.githubusercontent.com/2860398/60083357-2a162c80-9768-11e9-8c70-3f2c00560598.png)

**Comment by jimgreat** [comment]
ContextFilter 中有说明  
异步情况下Context从当前线程上清除了
 try {
            return invoker.invoke(invocation);
        } finally {
            // IMPORTANT! For async scenario, we must remove context from current thread, so we always create a new RpcContext for the next invoke for the same thread.
            RpcContext.removeContext();
            RpcContext.removeServerContext();
        }

**Comment by yintiefu** [comment]
> 2.7.2 的 ConsumerContextFilter 中
> Context从当前线程上清除了
> 
> ```
>         try {
>             RpcContext.removeServerContext();
>             return invoker.invoke(invocation);
>         } finally {
>             RpcContext.removeContext();
>         }
> ```
> 
> 之前的只是clearAttachments()

关键是异步调用，调用之后马上返回，然后finally块里面执行了RpcContext.removeContext(); 调用之后的线程什么也没了

**Comment by chickenlj** [comment]
@yintiefu 如你所描述的，2.7.2版本确实和2.7.1存在以上差异。

2.7.2开始会在每次调用后清空RpcContext，对于不清空context的场景我们也收到了一些用户上报的问题，如造成不同thread/调用间互相影响等，最终经过论我们决定采用清空context的策略。
抱歉给你带来以上不兼容性问题，你可以尝试用以下代码：

```java
CompletableFuture<Object> future = ref.$invokeAsync(callMethod, typeArrays, objectArrays);
future.whenComplete(() -> {
   String uri = RpcContext.getContext().getUrl().toFullString();
   event.setTotalUri(uri);
});

// 或者
ref.$invokeAsync(callMethod, typeArrays, objectArrays);
CompletableFuture<Object> future = RpcContext.getContext().getFuture();
future.whenComplete(() -> {
   String uri = RpcContext.getContext().getUrl().toFullString();
   event.setTotalUri(uri);
});
```

**Comment by yintiefu** [comment]
> @yintiefu 如你所描述的，2.7.2版本确实和2.7.1存在以上差异。
> 
> 2.7.2开始会在每次调用后清空RpcContext，对于不清空context的场景我们也收到了一些用户上报的问题，如造成不同thread/调用间互相影响等，最终经过论我们决定采用清空context的策略。
> 抱歉给你带来以上不兼容性问题，你可以尝试用以下代码：
> 
> ```java
> CompletableFuture<Object> future = ref.$invokeAsync(callMethod, typeArrays, objectArrays);
> future.whenComplete(() -> {
>    String uri = RpcContext.getContext().getUrl().toFullString();
>    event.setTotalUri(uri);
> });
> 
> // 或者
> ref.$invokeAsync(callMethod, typeArrays, objectArrays);
> CompletableFuture<Object> future = RpcContext.getContext().getFuture();
> future.whenComplete(() -> {
>    String uri = RpcContext.getContext().getUrl().toFullString();
>    event.setTotalUri(uri);
> });
> ```

尝试这个方式无效，会先执行RpcContext.removeContext(),然后才是future.whenComplete

**Comment by jimgreat** [comment]
好像要使用whenCompleteWithContext，  异步调用的RpcContext会在AsyncRpcResult保留下来，调用whenCompleteWithContext时会把保留的RpcContext会恢复到当前线程上
