### ISSUE TITLE
dependency issue in dubbo bom

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4400]
In org.apache.dubbo:dubbo-dependencies-bom, there's no 8.5.31 for tomcat-embed-logging-juli in central repo:

```xml
      <dependency>
        <groupId>org.apache.tomcat.embed</groupId>
        <artifactId>tomcat-embed-logging-juli</artifactId>
        <version>${tomcat_embed_version}</version>
      </dependency>
```

**Comment by cvictory** [comment]
<dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>${tomcat_embed_version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-logging-juli</artifactId>
                <version>${tomcat_embed_version}</version>
            </dependency>

what are they used ?

**Comment by cvictory** [comment]
I will try to delete this in next release
