### ISSUE TITLE
paas云环境下服务启用、禁用等治理操作留下大量的垃圾数据

### ISSUE THREAD

**Issue by stoneapple** [apache/dubbo#4410]
不知道各位团队有没有留意到这个问题，早先都是虚拟机IP一般固定的，我理解这个设计是没问题的。现在越来越多的服务器都运行在docker里面，重启一次IP就变了，那些存储在zookeeper上的动态治理配置数据都变成僵尸数据了。
        希望Dubbo团队能思考下这个问题，给一个方案。

**Comment by chickenlj** [comment]
我们最近正在着手重构服务治理规则，关注点是去除规则中的直接ip依赖，我想这个任务应该能覆盖你这里提出的问题吧？

**Comment by stoneapple** [comment]
> 我们最近正在着手重构服务治理规则，关注点是去除规则中的直接ip依赖，我想这个任务应该能覆盖你这里提出的问题吧？

这个会发布到哪个版本，2.6.x分支会处理吗？还是重构服务治理平台Admin

**Comment by chickenlj** [comment]
2.6.x没有计划发布，计划最终是会发布到2.7版本。会先从Dubbo框架上做改造予以支持，然后再支持Admin

**Comment by chickenlj** [comment]
预计提供支持的时间点大概在9月底吧

**Comment by cvictory** [comment]
我们预计会在后面的分支里支持，预计时间点要到11月或者12月。

**Comment by cvictory** [comment]
这个整体的工作量比较庞大，估计很难在这个版本完成。
针对路由规则相关的，我们期望通过标签的方式进行路由。标签可以直接和k8s的pod label对应上，或者或docker环境中的-D参数（-D参数写到provider url中，再写入注册中心）对应上。
针对其他一些动态配置，可以选用类似的方案。
