### ISSUE TITLE
ExtensionLoader.loadClass方法代码错误

### ISSUE THREAD

**Issue by jianhh** [apache/dubbo#4416]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: win7
* Java version: Java1.8

### Steps to reproduce this issue
ExtensionLoader类中loadClass(Map<String, Class<?>> extensionClasses, java.net.URL resourceURL, Class<?> clazz, String name)方法

....
String[] names = NAME_SEPARATOR.split(name);
            if (ArrayUtils.isNotEmpty(names)) {
                cacheActivateClass(clazz, names[0]);
                for (String n : names) {
                    cacheName(clazz, n);
                    saveInExtensionClass(extensionClasses, clazz, name);
                }
            }
....

### Expected Result

最后一行代码saveInExtensionClass(extensionClasses, clazz, name);中的name应该改成n？
由于dubbo中的name都是一个（没有逗号分隔），所以不会发生问题
例如：
![image](https://user-images.githubusercontent.com/12593175/60316014-844b0380-999b-11e9-95c3-7e51ff19fe3d.png)

**Comment by Leishunyu** [comment]
https://github.com/apache/dubbo/pull/4346
