### ISSUE TITLE
dubbo2.6.4升级到2.7.2调用失败，解码错误

### ISSUE THREAD

**Issue by crossdawn** [apache/dubbo#4418]
目前dubbo使用2.6.4版本，想进行升级到新版2.7.x。
用消费者版本2.6.4，服务提供者版本2.7.2，进行测试
调用一个方法后，报错
Failed to invoke remote method.monitorKey:null method
Caused by: com.alibaba.dubbo.remoting.RemotingException: java.io.IOException: Unknown result flag, expect '0' '1' '2', get 4
java.io.IOException: Unknown result flag, expect '0' '1' '2', get 4

**Comment by web1992** [comment]
应该是你的 2.6.4 jar 包不是最新的导致的，你下检查下你的 2.6.4 的jar 包 `DubboCodec` 代码中是否有下面 3,4,5 几个值。如果没有更新下最新的jar 试试。

```java
public class DubboCodec extends ExchangeCodec implements Codec2 {

    public static final String NAME = "dubbo";
    public static final String DUBBO_VERSION = Version.getProtocolVersion();
    public static final byte RESPONSE_WITH_EXCEPTION = 0;
    public static final byte RESPONSE_VALUE = 1;
    public static final byte RESPONSE_NULL_VALUE = 2;
    // 下面的几个 RESPONSE_xxx 是新增的
    public static final byte RESPONSE_WITH_EXCEPTION_WITH_ATTACHMENTS = 3;
    public static final byte RESPONSE_VALUE_WITH_ATTACHMENTS = 4;
    public static final byte RESPONSE_NULL_VALUE_WITH_ATTACHMENTS = 5;
    public static final Object[] EMPTY_OBJECT_ARRAY = new Object[0];
    public static final Class<?>[] EMPTY_CLASS_ARRAY = new Class<?>[0];
    private static final Logger log = LoggerFactory.getLogger(DubboCodec.class);
}
```

**Comment by crossdawn** [comment]
目前项目中使用的是基于2.6.4-SNAPSHOT打打一个包，DubboCodec确实没有345，这种情况的升级有没有什么好的建议呢？
Manifest-Version: 1.0
Implementation-Vendor: Alibaba
Implementation-Title: dubbo
Implementation-Version: 2.6.4-SNAPSHOT
Implementation-Vendor-Id: com.alibaba
Built-By: apple
Build-Jdk: 1.7.0_79
Specification-Vendor: Alibaba
Specification-Title: dubbo
Created-By: Apache Maven 3.2.5
Specification-Version: 2.6.4-SNAPSHOT
Archiver-Version: Plexus Archiver

**Comment by web1992** [comment]
不使用 2.6.4-SNAPSHOT 快照版本。把 SNAPSHOT 去掉。快照版本一般是用来版本过度的，本身不是稳定的，不建议使用。

**Comment by nisiyong** [comment]
@web1992 我这边也遇到这个问题，消费者2.6.2，提供者2.7.2。
解决这个问题只能升级消费端？
