### ISSUE TITLE
rest服务 列表怎么获取

### ISSUE THREAD

**Issue by wanhuhou** [apache/dubbo#4422]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment
发布了dubbo rest服务，dubbo消费端用jar接口访问没有问题，如果非dubbo的客户端，怎么知道路径信息，zk上注册相关信息，？？？

**Comment by web1992** [comment]
可以参考这个文章
[dubbox reset](https://dangdangdotcom.github.io/dubbox/rest.html)

如果reset 服务发布成功，通过浏览器是可以访问的，需要使用web容器，如tomcat ，并且tomcat 的端口要和dubbo reset 中的配置的端口一样。
