### ISSUE TITLE
Version  Duplicate. 

### ISSUE THREAD

**Issue by mininight** [apache/dubbo#4427]
### Environment

* Dubbo version: 2.7.2
* Operating System version: win10
* Java version: 1.8

### this issue
[DUBBO] Duplicate class org/apache/dubbo/common/Version.class in 2 jar [file:/E:/maven/repository/default/org/apache/dubbo/dubbo/2.7.2/
dubbo-2.7.2.jar
!/org/apache/dubbo/common/Version.class, file:/E:/maven/repository/default/org/apache/dubbo/dubbo-common/2.7.2/
dubbo-common-2.7.2.jar
!/org/apache/dubbo/common/Version.class], dubbo version: 2.7.2

**Comment by cvictory** [comment]
In dubbo-2.7.2.jar, it contain all of dubbo jar.  It is repackaged as inner class in a jar.

**Comment by mininight** [comment]
> In dubbo-2.7.2.jar, it contain all of dubbo jar. It is repackaged as inner class in a jar.

I added a new serialization module 'dubbo-serialization-protostuff ', and this problem arises.  Y^.^Y

**Comment by mininight** [comment]
It's okay like this : 
<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-protostuff</artifactId>
            <version>${dubbo.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo-common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by mininight** [comment]
It's okay like this  :
`<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-protostuff</artifactId>
            <version>${dubbo.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo-common</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`
