### ISSUE TITLE
Does Dubbo's annotation parameters support spel?

### ISSUE THREAD

**Issue by Billzaifei** [apache/dubbo#4433]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. @Service(interfaceClass = xxx.class, timeout = 3000, version = "1.0.7", group="#{config.group}")

What do you expected from the above steps？
register a provider service with the group name given by the spel

**Comment by cvictory** [comment]
Firstly you should define a variable in spring properties source , such as : `v.tt.service=1.0.0.pub`

Then you can add annotation:
```
@Service(version = "${v.tt.service}")
```

**Comment by Billzaifei** [comment]
Hey dude.

I've tried and debugged. Obviously dubbo doesn't support properties placeholder or spel.

For example, when I set the annotation parameters as below.

      @service(interfaceClass = xxx.class, timeout = 3000, version = "1.0.7", group="#{config.group}")

It would throw exception as below when DubboProviderAutoConfiguration was running.

      Invalid group="${config.group}" contain illegal charactor, only digit, letter, '-', '_' and '.' is legal.

The exception is thrown from the 'setGroup' method of AbstractServiceConfig. Codes as below:

        public void setGroup(String group) {
        checkKey("group", group);
        this.group = group;
        }

        protected static void checkKey(String property, String value) {
        checkProperty(property, value, MAX_LENGTH, PATTERN_KEY);
        }

    protected static void checkProperty(String property, String value, int maxlength, Pattern pattern) {
        if (value == null || value.length() == 0) {
            return;
        }
        if (value.length() > maxlength) {
            throw new IllegalStateException("Invalid " + property + "=\"" + value + "\" is longer than " + maxlength);
        }
        if (pattern != null) {
            Matcher matcher = pattern.matcher(value);
            if (!matcher.matches()) {
                throw new IllegalStateException("Invalid " + property + "=\"" + value + "\" contain illegal charactor, only digit, letter, '-', '_' and '.' is legal.");
            }
        }
    }
