### ISSUE TITLE
Use StringUtils.isNotEmpty() method in DubboBeanDefinitionParser

### ISSUE THREAD

**Issue by zhenxianyimeng** [apache/dubbo#4437]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: mac os 10.14.3
* Java version: 1.8.0_201

### Steps to reproduce this issue

1. use   StringUtils.isNotEmpty(id)  instead of   id != null && id.length() in DubboBeanDefinitionParser.JAVA at line 97

What do you expected from the above steps？
 make code clear and unity as other StringUtils method used in this class

**Comment by ralf0131** [comment]
It has been fixed from 2.7.4 onwards.
