### ISSUE TITLE
2.7.2的dubbo如何使用dubbo-monitor

### ISSUE THREAD

**Issue by guangshuowang** [apache/dubbo#4444]
如题2.7.2的dubbo如何使用dubbo-monitor？我按照md文件中的说明从incubator-dubbo-ops下载打包的monitor没有org.apache.dubbo.monitor.MonitorService服务提供者，只有com.alibaba.dubbo.monitor.MonitorService，项目跑起来提示找不到org.apache.dubbo.monitor.MonitorService报错，2.7.2版本的dubbo是没有monitor了还是我没有找对地方？

**Comment by web1992** [comment]
用这个 [dubbo-admin](https://github.com/apache/dubbo-admin)

**Comment by cvictory** [comment]
monitor在2.7中，虽然还是启用了，但是在 dubbo-admin中，从monitor迁移到了metrics。

所以使用dubbo-admin吧，如果有需求，可以到dubbo-admin里去提。

**Comment by rongmin** [comment]
> monitor在2.7中，虽然还是启用了，但是在 dubbo-admin中，从monitor迁移到了metrics。
> 
> 所以使用dubbo-admin吧，如果有需求，可以到dubbo-admin里去提。

dubbo admin启动server后， 0.2 版本的， 没看到注册这个provider： org.apache.dubbo.monitor.MonitorService
估计dubbo admin还没计划迭代吧？
