### ISSUE TITLE
native-thrift cannot run within docker instance

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4445]
native-thrift cannot run within docker instance since its impl *org.apache.dubbo.rpc.protocol.nativethrift.ThriftProtocol* doesn't honor *bind.host* and *bind.port*.

This limitation should apply to all *org.apache.dubbo.rpc.protocol.AbstractProxyProtocol*.

Pls. use https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-thrift to verify.

**Comment by guohao** [comment]
I will try it 😄
