### ISSUE TITLE
RPCContext doesn't work with native-thrift

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4446]
It looks like RPCContext doesn't work when native-thrift is enabled. Need to look into further. The corresponding example is: https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-thrift

**Comment by CrazyHZM** [comment]
Because `RpcContext.removeContext();` operation is done in ConsumerContextFilter

**Comment by cvictory** [comment]
@beiwei30  native thrift don't support attachment transmission.
