### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [apache/dubbo#4449]
Hi
The following lines have cryptographic API misuses. <br> File name => dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java: Line number => 875: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java: Line number => 797: API name => MessageDigest:<BR> File name => dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java: Line number => 868: API name => MessageDigest:<BR> File name => dubbo-common/src/main/java/org/apache/dubbo/common/io/Bytes.java: Line number => 797: API name => MessageDigest:<BR>

**Comment by cvictory** [comment]
The code is not readable, Can you format this code ? Please tell us how to produce this issue also.

**Comment by mhp0rtal** [comment]
Hi,
Thanks for your attention.
I reported the cryptographic misuses due to my recent research on how developers employ Java Cryptography Architecture (JCA) APIs in Java applications. I utilized some static analysis tools intended for checking cryptographic practices. The aforementioned misuses in those files were obtained from the results of the tools. The severity of the bug is relative. For instance, Even though MD5 is listed on Java documentation, MD5 is not recommended to use in any language anymore as it is considered insecure. An attacker can try billions of candidate passwords per second on a single GPU. Nevertheless, depending on the scenario the same hash algorithm may not be a problem for file integrity purpose.
There are several instances of cryptographic misuses which could lead to a security vulnerability:
*Do not use ECB mode for encryption.
*Do not use a non-random IV for CBC encryption
*Do not use constant encryption keys.
*Do not use constant salts for PBE.
*Do not use fewer than 1,000 iterations for PBE.
*Do not use static seeds to seed SecureRandom(·)
You can try using either CryptoLint or CogniCrypt to check your code from a cryptographic point of view
