### ISSUE TITLE
doRefer in RestProtocol may cause OOM

### ISSUE THREAD

**Issue by HzjNeverStop** [apache/dubbo#4458]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3-SNAPSHOT
* Operating System version: mac os 10.13.6
* Java version: 1.8.0_171

### Steps to reproduce this issue

1.  run the code in unit test: 

```java
   @Test
    public void testRestProtocol() {
        protocol = ExtensionLoader.getExtensionLoader(Protocol.class).getExtension("rest");
        URL url = URL.valueOf("rest://127.0.0.1:5342/rest/say?version=1.0.0&interface=org.apache.dubbo.rpc.protocol.rest.DemoService");
        while (true) {
            Invoker<DemoService> invoker = protocol.refer(DemoService.class, url);
            invoker.destroy();
        }
    }
```

Pls. provide [GitHub address] to reproduce this issue.

### Actual Result

What actually happens?
the size of LinkedList [clients] will keep growing, the ResteasyClient hold by it will not release, which will cause OOM easily.

```java
 ResteasyClient client = new ResteasyClientBuilder().httpEngine(engine).build();
clients.add(client);
```

the clients in the linkedList will not release when invoker destroyed, they will only be released when the rest protocol destroyed.
I think the protocol layer should not hold the object's such like client, it should be hold by the invoker and has the same lifecycle with invoker

**Comment by kaojunsong** [comment]
@chickenlj hello,we have met the same issues.Is this a bug of dubbo,and how to fixed it?

**Comment by beiwei30** [comment]
I believe this issue has been addressed by #4614. @kaojunsong @HzjNeverStop would you mind to verify?

**Comment by cvictory** [comment]
@HzjNeverStop  should you check this issue now ?  
If you don't reply , i will close this issue firstly.

**Comment by HzjNeverStop** [comment]
> @HzjNeverStop should you check this issue now ?
> If you don't reply , i will close this issue firstly.

it's ok, please close this issue, thanks
