### ISSUE TITLE
ipv6的支持（使用zookeeper）

### ISSUE THREAD

**Issue by chiyupei** [apache/dubbo#4459]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: windows
* Java version: 1.8
* zookeeper version: 3.4.6

### Steps to reproduce this issue

使用zookeeper作为注册中心，开启ipv6的情况下，服务消费者始终找不到服务提供者，能帮忙给解决一下吗？

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by cvictory** [comment]
You can confige the zookeeper address like this :

```
<dubbo:registry address="zookeeper://[fe80::1c23:653e:65a1:6014%en0]:2181"/>
```
`fe80::1c23:653e:65a1:6014%en0` is my ipv6 in my mac.

**Comment by chiyupei** [comment]
@cvictory 一直是按照您提供的方式配置的，如果服务提供者和消费者在一台服务器上是可以的，分别在两台服务器上就提示找不到服务提供者了，我本地调试感觉和ipv6的scope_id有关。您能再看看吗？
