### ISSUE TITLE
dubbo2.7.2 qos 配置参数替换后，无法禁用qos

### ISSUE THREAD

**Issue by xiaofeiahaha** [apache/dubbo#4461]
### Environment

* Dubbo version: 2.7.2
* Operating System version: mac
* Java version: jdk 1.8

### Steps to reproduce this issue
1. 配置qos-enable 新参数为false
![image](https://user-images.githubusercontent.com/11786784/60637359-bd2c2200-9e4c-11e9-9377-4f4751be25ba.png)
2. 启动的时候发现参数被替换成老参数
![image](https://user-images.githubusercontent.com/11786784/60636231-3d03bd80-9e48-11e9-9fc7-1c33e20666cb.png)
3. 看2.7.2的源码，取参数取的是新参数，url里没有qos-enable只有qos.enable导致默认还是启动qos
![image](https://user-images.githubusercontent.com/11786784/60636256-50af2400-9e48-11e9-83f3-754dd97a4c27.png)
![image](https://user-images.githubusercontent.com/11786784/60636262-573d9b80-9e48-11e9-9fed-35f1e8b06fd5.png)
4. 看了下参数读取这里，是否是这里被替换掉了呢？
![image](https://user-images.githubusercontent.com/11786784/60636381-d337e380-9e48-11e9-979e-86420e4d11f8.png)

请问下是bug还是我的使用姿势有误？

**Comment by cvictory** [comment]
we will fix this issue in next verison.  https://github.com/apache/dubbo/issues/4377
