### ISSUE TITLE
【BUG】泛化调用时通过MethodConfig设置重试次数不生效

### ISSUE THREAD

**Issue by liu844869663** [apache/dubbo#4466]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: Windows10
* Java version: 1.8.0

### Steps to reproduce this issue
1. 设置一个接口的响应时间为999999999ms；
2. 进行泛化调用；
3. 通过MethodConfig类设置方法的相关参数（方法名称、超时时间、重试次数）；
4. 通过MethodConfig类中setRetries方法设置方法的重试次数为0；

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
只会调用一次，在第一次调用失败后不会重试。
### Actual Result

What actually happens?
在第一次调用失败后进行重试，总共会调用3次。

What is the cause?
在FailoverClusterInvoker的doInvoke方法中获取获取重试次数时：
int len = this.getUrl().getMethodParameter(invocation.getMethodName(), "retries", 2) + 1;
由于invocation.getMethodName()为$invoke，在URL中重试次数为methodName.retries，而从URL中获取$invoke.retries，获取结果为空，然后采用默认值2，从而导致上述情况。
注：这里应该通过RpcUtil工具类中的getMethodName方法获取方法名称。

**Comment by kexianjun** [comment]
already fix in #2145

**Comment by wind-clothes** [comment]
@liu844869663 您好，你这这边在泛化调用的时候如何动态的修改服务方法的配置的，比如：重试次数，超时时间，服务的直连地址？

**Comment by liu844869663** [comment]
> @liu844869663 您好，你这这边在泛化调用的时候如何动态的修改服务方法的配置的，比如：重试次数，超时时间，服务的直连地址？

不清楚，我是在发起泛化调用前设置好

**Comment by wind-clothes** [comment]
@liu844869663 好的，了解了，感谢。

**Comment by wind-clothes** [comment]
@kexianjun 您好，你这这边在泛化调用的时候如何动态的修改服务方法的配置的，比如：重试次数，超时时间，服务的直连地址？ 这个功能是否有相关的文档。

**Comment by qixiaobo** [comment]
How about set the timeout  parameter with different timeout?
