### ISSUE TITLE
同一个dubbo服务一个微服务内多个类引用时,有些类的此dubbo服务reference注解属性不起作用

### ISSUE THREAD

**Issue by jufeng98** [apache/dubbo#4470]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version:Windows10
* Java version: 1.8

### Steps to reproduce this issue

1. 同一个微服务多个类引用同样的dubbo服务
2. 每个类的reference除了version和group一样之外,其它属性均有不一样的配置
3. 项目运行起来后有些类的此dubbo服务reference注解属性不起作用

我看了源码,是这里的问题:
    /**
     * Generate a cache key of {@link ReferenceBean}
     *
     * @param reference {@link Reference}
     * @param beanClass {@link Class}
     * @return
     */
    private String generateReferenceBeanCacheKey(Reference reference, Class<?> beanClass) {

        String interfaceName = resolveInterfaceName(reference, beanClass);

        String key = reference.url() + "/" + interfaceName +
                "/" + reference.version() +
                "/" + reference.group();

        Environment environment = applicationContext.getEnvironment();

        key = environment.resolvePlaceholders(key);

        return key;

    }
这里会缓存dubbo service,但是key应该由所有reference属性组成才对

**Comment by chickenlj** [comment]
Maybe we should count `reference id` as part of the key. 

```java
String key = reference.id() + "/" + interfaceName +
            "/" + reference.version() +
            "/" + reference.group();
```

**Comment by jufeng98** [comment]
那是极好的，可以解决这个问题

**Comment by mercyblitz** [comment]
This issue has been fixed, please update 2.6.6~ or refer https://github.com/apache/dubbo/blob/f9325699388f653ebbcd921cbdd0baf02d838715/dubbo-config/dubbo-config-spring/src/main/java/com/alibaba/dubbo/config/spring/beans/factory/annotation/ReferenceAnnotationBeanPostProcessor.java#L178

**Comment by jufeng98** [comment]
我看了2.6.6版本，问题并得到没有解决
![image](https://user-images.githubusercontent.com/26024578/60815841-0b358280-a1cb-11e9-83b4-2ddcc8dabbf2.png)
timeout和retries属性完全被忽略
![image](https://user-images.githubusercontent.com/26024578/60815967-3cae4e00-a1cb-11e9-90c0-e1e46ada8369.png)
![image](https://user-images.githubusercontent.com/26024578/60816083-7a12db80-a1cb-11e9-8140-077ea6727264.png)
仍然未考虑到其它Reference属性

**Comment by mercyblitz** [comment]
Please wait for 2.6.7

**Comment by mercyblitz** [comment]
It's still an issue for local `@Servnce`  that was referenced by multiple `@Reference` with different attributes. If the service annotated `@Servnce` is remote, it works.

**Comment by tswstarplanet** [comment]
duplicate to #4674
