### ISSUE TITLE
dubbo admin使用问题

### ISSUE THREAD

**Issue by Hypocresy** [apache/dubbo#4477]
我的dubbo服务已经停了一周了，但我还是能在dubbo admin管理界面看到 我的服务信息，另外我更改接口的 信息时 admin界面并不会更新接口信息而是新增一条信息

**Comment by web1992** [comment]
你用的dubbo 版本是多少？是用的zk 作为注册中心么？dubbo 2.7.1  有过 provider 注册中心相关的Bug

**Comment by Hypocresy** [comment]
dubbo使用的2.7.1 使用的zookeeper作注册中心，请问这里需要什么注意的呢

**Comment by web1992** [comment]
建议升级到2.7.2 
解决办法:

2.7.1版本增加配置：<dubbo:provider dynamic="true"/> 或<dubbo:service dynamic="true"/>

2.7.1 的bug 
https://github.com/apache/dubbo/issues/4213
