### ISSUE TITLE
Delete unused code, defaultPort can not be null.

### ISSUE THREAD

**Issue by TingSky** [apache/dubbo#4479]
Delete unused code. 
DefaultPort can not be null.
The code can never reached.
![image](https://user-images.githubusercontent.com/3785051/60713095-f64abc00-9f4a-11e9-9c0f-81b299dff2da.png)

**Comment by TingSky** [comment]
submit PR, TBR
https://github.com/apache/dubbo/pull/4480

**Comment by CrazyHZM** [comment]
It has been merged, thank you.
