### ISSUE TITLE
你好如果zookpeer连接需要授权的话dubbo应该怎么配置？

### ISSUE THREAD

**Issue by z2468091508** [apache/dubbo#4484]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by web1992** [comment]
你使用的 dubbo 版本是多少？dubbo 使用的 curator 客户端，默认只支持 digest 的授权方式。
具体的代码在 `CuratorZookeeperClient` 中。

可通过下面的配置来指定digest 需要的配置信息：

```xml
<dubbo:registry username="123" password="456" address="zookeeper://127.0.0.1:2181" />
```
如果 digest 的授权方式无法满足你的需求，可以通过 `SPI` 自定义 `ZookeeperTransporter`
并封装自己的 `ZookeeperClient`(或者简单的修改dubbo的实现) 实现类通过xml 加载自定义的 zk client实现。

配置如下:
```xml
 <dubbo:registry client="自定义 ZookeeperTransporter 实现类的名字" username="123" password="456" address="zookeeper://127.0.0.1:2181" />
```
