### ISSUE TITLE
remove code duplicate in AbstractConfig.java

### ISSUE THREAD

**Issue by zhenxianyimeng** [apache/dubbo#4491]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: mac os 10.14.3
* Java version: 1.8.0_201

### Steps to reproduce this issue

1. remove code ClassUtils.isPrimitive(method1.getReturnType()) in AbstractConfig.java at line 653
2. ClassUtils.isPrimitive(method1.getReturnType()) is already judge in method MethodUtils.isGetter 
3. no need to do this any more

What actually happens?
make code brief and clean

**Comment by cvictory** [comment]
Can you post a pr?

**Comment by zhenxianyimeng** [comment]
I have made a pr #4492, need review

**Comment by zhenxianyimeng** [comment]
> Can you post a pr?

I have made a pr #4492, need review

**Comment by htynkn** [comment]
Close via #4492. Thanks for your contribution.
