### ISSUE TITLE
设置属性dubbo.provider.metrics.，里面的值无法放入url参数列表里

### ISSUE THREAD

**Issue by WhaleCloud-platform** [apache/dubbo#4497]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: Mac
* Java version: 8

#### 设置属性值
- Provider
> dubbo.provider.filter=metrics
dubbo.provider.metrics.protocol=dubbo
dubbo.provider.metrics.port=20880

- Consumer
> dubbo.consumer.filter=metrics
dubbo.consumer.metrics.protocol=dubbo
dubbo.consumer.metrics.port=20880

 dubbo.provider会映射到`ProviderConfig`里的metrics，dubbo.consumer会映射到`ConsumerConfig`里的metrics。但是在`AbstractConfig`里解析时方法类型只能是`Primitive `，所以导致里面的值无法放入url 参数列表里。导致dubbo-admin里无法获取到protocol和port

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

> 为什么不跟xml`<dubbo:metrics`一样提供`dubbo.metrics`，然后在`DubboConfigConfiguration`映射进去
```java
    @EnableDubboConfigBindings({
            @EnableDubboConfigBinding(prefix = "dubbo.application", type = ApplicationConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.module", type = ModuleConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.registry", type = RegistryConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.protocol", type = ProtocolConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.monitor", type = MonitorConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.provider", type = ProviderConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.consumer", type = ConsumerConfig.class),
            @EnableDubboConfigBinding(prefix = "dubbo.config-center", type = ConfigCenterBean.class),
            @EnableDubboConfigBinding(prefix = "dubbo.metadata-report", type = MetadataReportConfig.class)
    })
```

**Comment by cvictory** [comment]
Hello, can you post a pull request for this issue ?

**Comment by WhaleCloud-platform** [comment]
已提：https://github.com/apache/dubbo/pull/4505。dubbo-spring-boot-project也需要修改
