### ISSUE TITLE
客户端连接zk  时好时坏  Will not attempt to authenticate using SASL (unknown error)

### ISSUE THREAD

**Issue by WorkAccounthjj** [apache/dubbo#4506]
目前这个问题困扰了我三天了 具体报错如下

`07-09 13:53:45.813 INFO  o.a.z.ClientCnxn - Opening socket connection to server 172.30.30.126/172.30.30.126:2181. Will not attempt to authenticate using SASL (unknown error)
07-09 13:53:52.813 WARN  o.a.z.ClientCnxn - Session 0x26b2ad901c6009c for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection timed out
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:712)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
07-09 13:53:53.883 INFO  o.a.z.ClientCnxn - Opening socket connection to server 172.30.30.127/172.30.30.127:2181. Will not attempt to authenticate using SASL (unknown error)
07-09 13:54:00.883 WARN  o.a.z.ClientCnxn - Session 0x26b2ad901c6009c for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection timed out
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:712)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
07-09 13:54:01.369 INFO  o.a.z.ClientCnxn - Opening socket connection to server 172.30.30.125/172.30.30.125:2181. Will not attempt to authenticate using SASL (unknown error)
07-09 13:54:08.369 WARN  o.a.z.ClientCnxn - Session 0x26b2ad901c6009c for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection timed out
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:712)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1068)
07-09 13:54:10.016 INFO  o.a.z.ClientCnxn - Opening socket connection to server 172.30.30.126/172.30.30.126:2181. Will not attempt to authenticate using SASL (unknown error)
07-09 13:54:10.219 INFO  o.a.z.ClientCnxn - Socket connection established to 172.30.30.126/172.30.30.126:2181, initiating session
07-09 13:54:10.441 INFO  o.a.z.ClientCnxn - Unable to reconnect to ZooKeeper service, session 0x26b2ad901c6009c has expired, closing socket connection
07-09 13:54:10.441 INFO  o.a.z.ZooKeeper - Initiating client connection, connectString=172.30.30.125:2181,172.30.30.126:2181,172.30.30.127:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@5fb96f79
07-09 13:54:10.442 INFO  o.a.z.ClientCnxn - EventThread shut down
07-09 13:54:11.120 INFO  o.a.z.ClientCnxn - Opening socket connection to server 172.30.30.126/172.30.30.126:2181. Will not attempt to authenticate using SASL (unknown error)
07-09 13:54:11.423 INFO  o.a.z.ClientCnxn - Socket connection established to 172.30.30.126/172.30.30.126:2181, initiating session
07-09 13:54:11.833 INFO  o.a.z.ClientCnxn - Session establishment complete on server 172.30.30.126/172.30.30.126:2181, sessionid = 0x26b2ad901c600a0, negotiated timeout = 30000
`

**Comment by web1992** [comment]
从  `Connection timed out` 日志分析,可能是链接zk 之后 session 断开连接了，后续进行重新连接的时候超时了 ，先检查下你们机器之间的网络问题吧，如果是线上的机器，最好看下系统监控，看下网络带宽的占用情况。
