### ISSUE TITLE
如何扩展元数据的自定义维度？

### ISSUE THREAD

**Issue by yu120** [apache/dubbo#4520]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

目前元数据上报至元数据中心的参数维度不能够满足我的业务，所以想扩展元数据来实现一些个性化参数的上报，以便于其他消费者或网关更好的使用一些特殊场景？

**Comment by chickenlj** [comment]
可以直接扩展MetadataReport扩展点，覆盖已有实现或提供新实现

```java
public interface MetadataReport {

    void storeProviderMetadata(MetadataIdentifier providerMetadataIdentifier, FullServiceDefinition serviceDefinition);

    void storeConsumerMetadata(MetadataIdentifier consumerMetadataIdentifier, Map<String, String> serviceParameterMap);

}
```
