### ISSUE TITLE
@Service我把timeout时间从原来的3秒改到30秒，我发现重启启动服务后没有生效，跟踪源码调试发现服务消费者调用的url里面还是3秒

### ISSUE THREAD

**Issue by lmzhizhe** [apache/dubbo#4527]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

@Service我把timeout时间从原来的3秒改到30秒，我发现重启启动服务后没有生效，跟踪源码调试发现服务消费者调用的url里面还是3秒

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
请先检查确认注册中心中的数值是否是timeout=30s
