### ISSUE TITLE
path和contextpath长度超过200报错

### ISSUE THREAD

**Issue by Eric1995** [apache/dubbo#4536]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Windows 10
* Java version: 1.8

### Steps to reproduce this issue

正常运行demo

### Expected Result

不会发生报错

### Actual Result

报path和contextpath长度超过200错误。分析代码得知这两个值是系统的环境变量，windows上环境变量通常设置很多，长度很容易超过200。不知道为啥要设置长度不超过200。

**Comment by chickenlj** [comment]
> 分析代码得知这两个值是系统的环境变量，windows上环境变量通常设置很多

Windows上的环境变量不应该被读取到，请问你是用的哪个代码分支，master还是2.7.3-release?

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/pull/4522
