### ISSUE TITLE
Bug form Dubbo with REST Protocol

### ISSUE THREAD

**Issue by 2227324689** [apache/dubbo#4543]
### Environment

* Dubbo version: 2.7.2
* Operating System version: window
* Java version: 1.8

### Steps to reproduce this issue

I'm use REST protocol Publish Service .  
The Service start failed but I get noting error from log. 
so,  I'm trying to debug the source code. 

I'm get an error when dubbo use ExtensionLoader.getExtensionLoader  load RestProtocol。 

ServiceConfig.java line 751.  
```java
final int defaultPort = ExtensionLoader.getExtensionLoader(Protocol.class).getExtension(name).getDefaultPort();
```
detailMessage is `NoClassDefFoundError`.  

My question  is that the error message was not thrown out.    is that a mistake?

**Comment by CrazyHZM** [comment]
Can you provide configuration or related exceptions?

**Comment by 2227324689** [comment]
I think Dubbo have  many  Problems with exception handling . 
for example : 
  I  use Dubbo spi , if  i write an error class in this package:  `META-INF/dubbo/org.apache.dubbo.rpc.protocol` .    
> actually , the right class name shoud be `org.apache.dubbo.rcp.Protocol`. 

I will get an error message .   
```
Caused by: java.lang.ClassNotFoundException: org.apache.cxf.Bus
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by beiwei30** [comment]
it should be a maven dependency issue in your project. Pls. refer to https://github.com/beiwei30/dubbo-rest-samples/tree/master/basic for the details.
