### ISSUE TITLE
dubbo如何更好的测试?

### ISSUE THREAD

**Issue by objectboy2016** [apache/dubbo#4547]
编写一个dubbo服务, 如何更优雅,更直观的测试?   比如我们平时开发一个接口就在postman或者利用浏览器就能测试,  dubbo呢 ?  用什么工具测试优雅直观?  谢谢

**Comment by web1992** [comment]
推荐个插件 [https://github.com/thubbo/jmeter-plugins-for-apache-dubbo](https://github.com/thubbo/jmeter-plugins-for-apache-dubbo)

**Comment by beiwei30** [comment]
@objectboy2016 可以看下 [dubbo-admin](https://github.com/apache/dubbo-admin) 上的服务测试功能
