### ISSUE TITLE
dubbo2.7.2调用dubbox2.8.4接口异常

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo#4555]
公司打算升级到Apache dubbo，但是公司原有服务都是dubbox2.8.4，
新的系统使用2.7.2的Apache dubbo调用老系统dubbox2.8.4系统的接口，报错，提示：
Decode rpc invocation failed: expected integer at 0x12 java.lang.String (Ljava/lang/String;)

查看原码dubbo2.8.4的DecodeableRpcInvocation里的decode()方法和最新的Apache dubbo2.7.2的实现不一样，造成调用没法互通，这个有办法解决么？

**Comment by web1992** [comment]
这个问题是 dubbox 中修改了 `com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec` 类中 `encodeRequestData`方法的编码实现和`DecodeableRpcInvocation`的解码操作，但是没有考虑到协议的兼容性问题。

代码片段如下：

> dubbo encodeRequestData

```java
        RpcInvocation inv = (RpcInvocation) data;

        out.writeUTF(version);
        out.writeUTF(inv.getAttachment(Constants.PATH_KEY));
        out.writeUTF(inv.getAttachment(Constants.VERSION_KEY));

        out.writeUTF(inv.getMethodName());
        out.writeUTF(ReflectUtils.getDesc(inv.getParameterTypes()));
        Object[] args = inv.getArguments();
        if (args != null)
            for (int i = 0; i < args.length; i++) {
                out.writeObject(encodeInvocationArgument(channel, inv, i));
            }
        out.writeObject(inv.getAttachments());
```

> dubbox encodeRequestData

```java
        RpcInvocation inv = (RpcInvocation) data;

        out.writeUTF(inv.getAttachment(Constants.DUBBO_VERSION_KEY, DUBBO_VERSION));
        out.writeUTF(inv.getAttachment(Constants.PATH_KEY));
        out.writeUTF(inv.getAttachment(Constants.VERSION_KEY));

        out.writeUTF(inv.getMethodName());

        // NOTICE modified by lishen
        // TODO
        if (getSerialization(channel) instanceof OptimizedSerialization && !containComplexArguments(inv)) {
            out.writeInt(inv.getParameterTypes().length);
        } else {
            out.writeInt(-1);
            out.writeUTF(ReflectUtils.getDesc(inv.getParameterTypes()));
        }

        Object[] args = inv.getArguments();
        if (args != null)
            for (int i = 0; i < args.length; i++){
                out.writeObject(encodeInvocationArgument(channel, inv, i));
            }
        out.writeObject(inv.getAttachments());
```

建议去修改 Dubbox 的 DubboCodec 和 DecodeableRpcInvocation 的实现，并且与新版中的dubbo 2.7.x 的`编码`和`解码`操作保持一致。

可以写自己的 DecodeableRpcInvocation 和 DubboCodec 类放在 Dubbox 项目中，修改相关的实现，与2.7.x 保持一致。
（利用类加载机制加载自己修改后的 DecodeableRpcInvocation 和 DubboCodec ）

**Comment by jimiyi** [comment]
@web1992 或者是否可以利用spi机制，扩展Apache dubbo的协议解析部分，兼容原来dubbox的？

**Comment by web1992** [comment]
@jimiyi 可以的，需要实现自己的 `com.alibaba.dubbo.remoting.Codec2`
进行配置
```xml
<dubbo:protocol  codec="自定义的codec实现类名称" />
```

**Comment by jimiyi** [comment]
试了下，不行，因为codec替换的是codec接口，并不是codec2的接口

**Comment by chickenlj** [comment]
@jimiyi 理论上实现Codec2扩展是会被加载的，能否提供你的部分扩展方式

```java
 protected static Codec2 getChannelCodec(URL url) {
        String codecName = url.getParameter(Constants.CODEC_KEY, "telnet");
        if (ExtensionLoader.getExtensionLoader(Codec2.class).hasExtension(codecName)) {
            return ExtensionLoader.getExtensionLoader(Codec2.class).getExtension(codecName);
        } else {
            return new CodecAdapter(ExtensionLoader.getExtensionLoader(Codec.class)
                    .getExtension(codecName));
        }
    }
```

**Comment by chickenlj** [comment]
请注意2.7.2之后，需要扩展`org.apache.dubbo.xxx.Codec2`而不是`com.alibaba.xxx.Codec2`

**Comment by jimiyi** [comment]
昨天又试了下，是扩展了，但是必须放在META-INF/dubbo/internal下面才生效，放在META-INF/dubbo下不行，很奇怪啊

**Comment by krirto** [comment]
能否在encodeRequestData和decode的时候，判断当前的协议进行兼容？
![image](https://user-images.githubusercontent.com/37257070/61842252-1d513980-aeca-11e9-93ee-61a637eec90f.png)

**Comment by krirto** [comment]
encodeRequestData方法
![image](https://user-images.githubusercontent.com/37257070/61842283-34902700-aeca-11e9-831e-68b91f6e43be.png)

**Comment by jimiyi** [comment]
> 能否在encodeRequestData和decode的时候，判断当前的协议进行兼容？
> ![image](https://user-images.githubusercontent.com/37257070/61842252-1d513980-aeca-11e9-93ee-61a637eec90f.png)

是的，就是改这段让dubbox和Apache dubbo可以互调

**Comment by krirto** [comment]
> > 能否在encodeRequestData和decode的时候，判断当前的协议进行兼容？
> > ![image](https://user-images.githubusercontent.com/37257070/61842252-1d513980-aeca-11e9-93ee-61a637eec90f.png)
> 
> 是的，就是改这段让dubbox和Apache dubbo可以互调

但是我遇到另一个问题，在兼容dubbox调用dubbo服务时consumer进行encode时没办法获取到provider的协议，我想到的是根据协议的不通进行判断是否writeInt对dubbo正常版本进行兼容
![image](https://user-images.githubusercontent.com/37257070/61920425-27d40780-af8c-11e9-86a4-ea7c83fc3299.png)
请问您是如何处理的呢？

**Comment by jimiyi** [comment]
url里面获取key为"dubbo"的值，2.8.4就是dubbox，2.0.2就是Apache dubbo，然后你根据不同的版本号，做不同的处理

**Comment by edwardlee03** [comment]
我们又在生产环境遇到这个问题，坑啊😭，直接回滚了。消费者使用`dubbox-2.8.4`，提供者`dubbo-2.6.3`。
