### ISSUE TITLE
configcenter bug for zookeeper

### ISSUE THREAD

**Issue by cifaz** [apache/dubbo#4557]
### Environment
* Dubbo version: 2.7.2
* Operating System version:  window10 1903
* Java version: jdk1.8

### Steps to reproduce this issue
1. create app router in dubbo admin
2. request my url
3. no response the app router

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
No response or listner for the app condition router

### Actual Result
We add the app condition router, it should be invoke in routerChain.route, 
The reason is ZookeeperDynamicConfiguration
```

rootPath = "/" + url.getParameter(CONFIG_NAMESPACE_KEY, DEFAULT_GROUP) + "/config";

Tips: 
CONFIG_NAMESPACE_KEY = org.apache.dubbo.configcenter.Constants.CONFIG_NAMESPACE_KEY = config.namespace (dubbo-configcenter-api)
```

But the zookeeper config is dubbo.config-center.namespace = dubbo, If I change to my own config, em, dubbo.config-center.namespace = dev, It cannot work

**Comment by WhaleCloud-platform** [comment]
2.7.3已修复

**Comment by chickenlj** [comment]
Fxied in 2.7.3, and will be released in few days.
