### ISSUE TITLE
springboot2.1.6+dubbo2.6.2，加载外部资源占位符无法被替换

### ISSUE THREAD

**Issue by yuyu414** [apache/dubbo#4564]
springboot2.1.6+dubbo2.6.2，加载外部资源占位符无法被替换

我的项目是springboot2.6.2，通过@PropertySource("file:${config.root.local}/app.properties")这个注解加载我的外部资源文件，然后在springboot的application.propertiesl配置文件中替换掉占位符，发现无法替换掉这个占位符的值，导致系统启动失败，就是dubbo不行，其中还有数据库相关的占位符￥{ }是可以替换掉的？可能原因是什么怎么处理一下？

**Comment by yuyu414** [comment]
2019-07-13 12:58:30.894  INFO 3476 --- [           main] e.OverrideDubboConfigApplicationListener : Dubbo Config was overridden by externalized configuration {dubbo.application.name=taskcenter-provider, dubbo.port=10002, dubbo.protocol.name=dubbo, dubbo.protocol.port=20880, dubbo.registry.address=${zookeeper.url}}

**Comment by yuyu414** [comment]
`"C:\Program Files\Java\jdk1.8.0_211\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58732,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:C:\Users\10415\.IntelliJIdea2019.1\system\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_211\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_211\jre\lib\rt.jar;C:\Users\10415\Desktop\dsp-v2.0\code\trunk\taskcenter-boot\web\target\classes;C:\Users\10415\Desktop\dsp-v2.0\code\trunk\taskcenter-boot\manager\target\classes;C:\Users\10415\Desktop\dsp-v2.0\code\trunk\taskcenter-boot\dal\target\classes;E:\maven-repository\org\mybatis\spring\boot\mybatis-spring-boot-starter\2.0.1\mybatis-spring-boot-starter-2.0.1.jar;E:\maven-repository\org\springframework\boot\spring-boot-starter\2.1.6.RELEASE\spring-boot-starter-2.1.6.RELEASE.jar;E:\maven-repository\org\springframework\boot\spring-boot\2.1.6.RELEASE\spring-boot-2.1.6.RELEASE.jar;E:\maven-repository\org\springframework\boot\spring-boot-starter-logging\2.1.6.RELEASE\spring-boot-starter-logging-2.1.6.RELEASE.jar;E:\maven-repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;E:\maven-repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;E:\maven-repository\org\apache\logging\log4j\log4j-to-slf4j\2.11.2\log4j-to-slf4j-2.11.2.jar;E:\maven-repository\org\apache\logging\log4j\log4j-api\2.11.2\log4j-api-2.11.2.jar;E:\maven-repository\org\slf4j\jul-to-slf4j\1.7.26\jul-to-slf4j-1.7.26.jar;E:\maven-repository\javax\annotation\javax.annotation-api\1.3.2\javax.annotation-api-1.3.2.jar;E:\maven-repository\org\springframework\spring-core\5.1.8.RELEASE\spring-core-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\spring-jcl\5.1.8.RELEASE\spring-jcl-5.1.8.RELEASE.jar;E:\maven-repository\org\yaml\snakeyaml\1.23\snakeyaml-1.23.jar;E:\maven-repository\org\mybatis\spring\boot\mybatis-spring-boot-autoconfigure\2.0.1\mybatis-spring-boot-autoconfigure-2.0.1.jar;E:\maven-repository\org\mybatis\mybatis\3.5.1\mybatis-3.5.1.jar;E:\maven-repository\org\mybatis\mybatis-spring\2.0.1\mybatis-spring-2.0.1.jar;E:\maven-repository\mysql\mysql-connector-java\5.1.47\mysql-connector-java-5.1.47.jar;E:\maven-repository\com\alibaba\druid-spring-boot-starter\1.1.10\druid-spring-boot-starter-1.1.10.jar;E:\maven-repository\com\alibaba\druid\1.1.10\druid-1.1.10.jar;E:\maven-repository\org\springframework\boot\spring-boot-autoconfigure\2.1.6.RELEASE\spring-boot-autoconfigure-2.1.6.RELEASE.jar;E:\maven-repository\com\google\code\gson\gson\2.6.2\gson-2.6.2.jar;E:\maven-repository\com\huihe\common\huihe-common-lang\2.0.0\huihe-common-lang-2.0.0.jar;E:\maven-repository\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;E:\maven-repository\commons-net\commons-net\3.3\commons-net-3.3.jar;E:\maven-repository\commons-codec\commons-codec\1.11\commons-codec-1.11.jar;E:\maven-repository\axis\axis\1.4\axis-1.4.jar;E:\maven-repository\org\apache\axis\axis-jaxrpc\1.4\axis-jaxrpc-1.4.jar;E:\maven-repository\org\apache\axis\axis-saaj\1.4\axis-saaj-1.4.jar;E:\maven-repository\axis\axis-wsdl4j\1.5.1\axis-wsdl4j-1.5.1.jar;E:\maven-repository\commons-discovery\commons-discovery\0.2\commons-discovery-0.2.jar;E:\maven-repository\org\codehaus\jackson\jackson-mapper-asl\1.9.13\jackson-mapper-asl-1.9.13.jar;E:\maven-repository\org\codehaus\jackson\jackson-core-asl\1.9.13\jackson-core-asl-1.9.13.jar;E:\maven-repository\com\fasterxml\jackson\core\jackson-annotations\2.9.0\jackson-annotations-2.9.0.jar;E:\maven-repository\com\fasterxml\jackson\core\jackson-databind\2.9.9\jackson-databind-2.9.9.jar;E:\maven-repository\com\fasterxml\jackson\core\jackson-core\2.9.9\jackson-core-2.9.9.jar;E:\maven-repository\commons-collections\commons-collections\3.2\commons-collections-3.2.jar;E:\maven-repository\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;E:\maven-repository\org\apache\httpcomponents\httpclient\4.5.9\httpclient-4.5.9.jar;E:\maven-repository\org\apache\httpcomponents\httpcore\4.4.11\httpcore-4.4.11.jar;E:\maven-repository\net\sourceforge\javacsv\javacsv\2.0\javacsv-2.0.jar;E:\maven-repository\com\thoughtworks\xstream\xstream\1.4.7\xstream-1.4.7.jar;E:\maven-repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;E:\maven-repository\xpp3\xpp3_min\1.1.4c\xpp3_min-1.1.4c.jar;E:\maven-repository\commons-io\commons-io\2.5\commons-io-2.5.jar;E:\maven-repository\org\apache\poi\poi-ooxml\3.14\poi-ooxml-3.14.jar;E:\maven-repository\org\apache\poi\poi\3.14\poi-3.14.jar;E:\maven-repository\org\apache\poi\poi-scratchpad\3.14\poi-scratchpad-3.14.jar;E:\maven-repository\fr\opensagres\xdocreport\xdocreport\1.0.6\xdocreport-1.0.6.jar;E:\maven-repository\org\apache\poi\poi-ooxml-schemas\3.14\poi-ooxml-schemas-3.14.jar;E:\maven-repository\org\apache\poi\ooxml-schemas\1.3\ooxml-schemas-1.3.jar;E:\maven-repository\org\apache\xmlbeans\xmlbeans\2.6.0\xmlbeans-2.6.0.jar;E:\maven-repository\stax\stax-api\1.0.1\stax-api-1.0.1.jar;E:\maven-repository\javax\mail\mail\1.4.7\mail-1.4.7.jar;E:\maven-repository\javax\activation\activation\1.1\activation-1.1.jar;E:\maven-repository\com\aliyun\oss\aliyun-sdk-oss\2.6.0\aliyun-sdk-oss-2.6.0.jar;E:\maven-repository\org\jdom\jdom\1.1\jdom-1.1.jar;E:\maven-repository\net\sf\json-lib\json-lib\2.4\json-lib-2.4-jdk15.jar;E:\maven-repository\commons-beanutils\commons-beanutils\1.8.0\commons-beanutils-1.8.0.jar;E:\maven-repository\net\sf\ezmorph\ezmorph\1.0.6\ezmorph-1.0.6.jar;E:\maven-repository\com\aliyun\aliyun-java-sdk-vod\2.15.1\aliyun-java-sdk-vod-2.15.1.jar;E:\maven-repository\com\aliyun\aliyun-java-sdk-sts\2.1.6\aliyun-java-sdk-sts-2.1.6.jar;E:\maven-repository\com\aliyun\aliyun-java-sdk-core\3.7.1\aliyun-java-sdk-core-3.7.1.jar;E:\maven-repository\org\json\json\20170516\json-20170516.jar;E:\maven-repository\com\aliyun\aliyun-java-sdk-dysmsapi\1.1.0\aliyun-java-sdk-dysmsapi-1.1.0.jar;E:\maven-repository\com\aliyun\aliyun-java-sdk-dyvmsapi\1.0.0\aliyun-java-sdk-dyvmsapi-1.0.0.jar;E:\maven-repository\com\taobao\dayu\taobao-sdk-java\20160607\taobao-sdk-java-20160607.jar;E:\maven-repository\com\qcloud\cos_api\5.2.4\cos_api-5.2.4.jar;E:\maven-repository\joda-time\joda-time\2.10.2\joda-time-2.10.2.jar;E:\maven-repository\com\tencentcloudapi\tencentcloud-sdk-java\3.0.1\tencentcloud-sdk-java-3.0.1.jar;E:\maven-repository\com\squareup\okhttp\okhttp\2.5.0\okhttp-2.5.0.jar;E:\maven-repository\com\squareup\okio\okio\1.6.0\okio-1.6.0.jar;E:\maven-repository\com\qcloud\vod_api\1.1.1\vod_api-1.1.1.jar;E:\maven-repository\com\qcloud\qcloud-java-sdk\2.0.1\qcloud-java-sdk-2.0.1.jar;E:\maven-repository\org\springframework\spring-context-support\5.1.8.RELEASE\spring-context-support-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\spring-beans\5.1.8.RELEASE\spring-beans-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\spring-context\5.1.8.RELEASE\spring-context-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\spring-expression\5.1.8.RELEASE\spring-expression-5.1.8.RELEASE.jar;E:\maven-repository\org\quartz-scheduler\quartz\2.3.1\quartz-2.3.1.jar;E:\maven-repository\com\mchange\mchange-commons-java\0.2.15\mchange-commons-java-0.2.15.jar;E:\maven-repository\net\sourceforge\pinyin4j\pinyin4j\2.5.0\pinyin4j-2.5.0.jar;E:\maven-repository\io\swagger\swagger-annotations\1.5.20\swagger-annotations-1.5.20.jar;E:\maven-repository\org\springframework\boot\spring-boot-starter-jdbc\2.1.6.RELEASE\spring-boot-starter-jdbc-2.1.6.RELEASE.jar;E:\maven-repository\com\zaxxer\HikariCP\3.2.0\HikariCP-3.2.0.jar;E:\maven-repository\org\springframework\spring-jdbc\5.1.8.RELEASE\spring-jdbc-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\spring-tx\5.1.8.RELEASE\spring-tx-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\boot\spring-boot-starter-data-redis\2.1.6.RELEASE\spring-boot-starter-data-redis-2.1.6.RELEASE.jar;E:\maven-repository\org\springframework\data\spring-data-redis\2.1.9.RELEASE\spring-data-redis-2.1.9.RELEASE.jar;E:\maven-repository\org\springframework\data\spring-data-keyvalue\2.1.9.RELEASE\spring-data-keyvalue-2.1.9.RELEASE.jar;E:\maven-repository\org\springframework\data\spring-data-commons\2.1.9.RELEASE\spring-data-commons-2.1.9.RELEASE.jar;E:\maven-repository\org\springframework\spring-oxm\5.1.8.RELEASE\spring-oxm-5.1.8.RELEASE.jar;E:\maven-repository\org\springframework\spring-aop\5.1.8.RELEASE\spring-aop-5.1.8.RELEASE.jar;E:\maven-repository\io\lettuce\lettuce-core\5.1.7.RELEASE\lettuce-core-5.1.7.RELEASE.jar;E:\maven-repository\io\netty\netty-common\4.1.36.Final\netty-common-4.1.36.Final.jar;E:\maven-repository\io\netty\netty-handler\4.1.36.Final\netty-handler-4.1.36.Final.jar;E:\maven-repository\io\netty\netty-buffer\4.1.36.Final\netty-buffer-4.1.36.Final.jar;E:\maven-repository\io\netty\netty-codec\4.1.36.Final\netty-codec-4.1.36.Final.jar;E:\maven-repository\io\netty\netty-transport\4.1.36.Final\netty-transport-4.1.36.Final.jar;E:\maven-repository\io\netty\netty-resolver\4.1.36.Final\netty-resolver-4.1.36.Final.jar;E:\maven-repository\io\projectreactor\reactor-core\3.2.10.RELEASE\reactor-core-3.2.10.RELEASE.jar;E:\maven-repository\org\reactivestreams\reactive-streams\1.0.2\reactive-streams-1.0.2.jar;E:\maven-repository\org\apache\commons\commons-pool2\2.5.0\commons-pool2-2.5.0.jar;C:\Users\10415\Desktop\dsp-v2.0\code\trunk\taskcenter-boot\facade\target\classes;E:\maven-repository\com\alibaba\boot\dubbo-spring-boot-starter\0.1.0\dubbo-spring-boot-starter-0.1.0.jar;E:\maven-repository\com\alibaba\dubbo\2.5.10\dubbo-2.5.10.jar;E:\maven-repository\org\springframework\spring-web\5.1.8.RELEASE\spring-web-5.1.8.RELEASE.jar;E:\maven-repository\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;E:\maven-repository\org\jboss\netty\netty\3.2.5.Final\netty-3.2.5.Final.jar;E:\maven-repository\org\apache\zookeeper\zookeeper\3.4.9\zookeeper-3.4.9.jar;E:\maven-repository\log4j\log4j\1.2.16\log4j-1.2.16.jar;E:\maven-repository\jline\jline\0.9.94\jline-0.9.94.jar;E:\maven-repository\io\netty\netty\3.10.5.Final\netty-3.10.5.Final.jar;E:\maven-repository\org\apache\curator\curator-framework\2.12.0\curator-framework-2.12.0.jar;E:\maven-repository\org\apache\curator\curator-client\2.12.0\curator-client-2.12.0.jar;E:\maven-repository\com\google\guava\guava\16.0.1\guava-16.0.1.jar;E:\maven-repository\com\alibaba\boot\dubbo-spring-boot-autoconfigure\0.1.0\dubbo-spring-boot-autoconfigure-0.1.0.jar;E:\maven-repository\com\alibaba\boot\dubbo-spring-boot-actuator\0.1.0\dubbo-spring-boot-actuator-0.1.0.jar;C:\Users\10415\Desktop\dsp-v2.0\code\trunk\taskcenter-boot\model\target\classes;E:\maven-repository\com\aliyun\openservices\ons-client\1.7.9.Final\ons-client-1.7.9.Final.jar;E:\maven-repository\org\slf4j\slf4j-api\1.7.26\slf4j-api-1.7.26.jar;E:\maven-repository\org\hibernate\validator\hibernate-validator\6.0.17.Final\hibernate-validator-6.0.17.Final.jar;E:\maven-repository\javax\validation\validation-api\2.0.1.Final\validation-api-2.0.1.Final.jar;E:\maven-repository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;E:\maven-repository\com\fasterxml\classmate\1.4.0\classmate-1.4.0.jar;E:\maven-repository\com\github\ulisesbocchio\jasypt-spring-boot-starter\2.1.0\jasypt-spring-boot-starter-2.1.0.jar;E:\maven-repository\com\github\ulisesbocchio\jasypt-spring-boot\2.1.0\jasypt-spring-boot-2.1.0.jar;E:\maven-repository\org\jasypt\jasypt\1.9.2\jasypt-1.9.2.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\lib\idea_rt.jar" com.huihe.taskcenter.TaskCenterApplication
Connected to the target VM, address: '127.0.0.1:58732', transport: 'socket'
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2019-07-13 13:24:58.293  INFO 5048 --- [           main] a.b.d.c.e.WelcomeLogoApplicationListener : 

  ████████▄  ███    █▄  ▀█████████▄  ▀█████████▄   ▄██████▄  
  ███   ▀███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ███    ███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ███    ███ ███    ███  ▄███▄▄▄██▀   ▄███▄▄▄██▀  ███    ███ 
  ███    ███ ███    ███ ▀▀███▀▀▀██▄  ▀▀███▀▀▀██▄  ███    ███ 
  ███    ███ ███    ███   ███    ██▄   ███    ██▄ ███    ███ 
  ███   ▄███ ███    ███   ███    ███   ███    ███ ███    ███ 
  ████████▀  ████████▀  ▄█████████▀  ▄█████████▀   ▀██████▀  
                                                             

 :: Dubbo Spring Boot (v0.1.0) : https://github.com/dubbo/dubbo-spring-boot-project
 :: Dubbo (v2.0.1) : https://github.com/alibaba/dubbo
 :: Google group : http://groups.google.com/group/dubbo

2019-07-13 13:24:58.310  INFO 5048 --- [           main] e.OverrideDubboConfigApplicationListener : Dubbo Config was overridden by externalized configuration {dubbo.application.name=taskcenter-provider, dubbo.protocol.name=dubbo, dubbo.protocol.port=10018, dubbo.registry.address=${zookeeper.url}}

`

**Comment by cvictory** [comment]
@mercyblitz  can you check this issue ?

**Comment by yuyu414** [comment]
> @mercyblitz can you check this issue ?

我的这个issue提出的有问题，源码中没有获取到配置文件之后，如果value是占位符的话没有做出处理，等我有空的时候 试着去加上去，目前工作比较忙

**Comment by ryuhi** [comment]
将${xxxx}改成@xxx@试试看

**Comment by mercyblitz** [comment]
Did you mean the property "config.root.local" is configured from `application.properties`,
or 
the location of `@PropertySource("file:${config.root.local}/app.properties")` can not be parsed
