### ISSUE TITLE
使用protostuff 序列化时候 心跳 WrapperUtils出错

### ISSUE THREAD

**Issue by chenyu2016** [apache/dubbo#4568]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. protocol设置为dubbo 序列化设置为 protosubff
2. 等待心跳

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

WrapperUtils.needWrapper(Object obj){
return needWrapper(obj.getClass());  //这里obj 是null报错
}
因为NettyClientHandler.userEventTriggered() 
方法创建Request对象时候  mData 属性没有null
请问是不是我使用protosubff 姿势不对

```
Just put your stack trace here!
```

**Comment by cvictory** [comment]
I find there is no sample in https://github.com/apache/dubbo-samples.  
Can you supply a protostuff sample and post a pull request in https://github.com/apache/dubbo-samples.

**Comment by chenyu2016** [comment]
> 我发现[https://github.com/apache/dubbo-samples中](https://github.com/apache/dubbo-samples)没有样本。
> 您可以在[https://github.com/apache/dubbo-samples中](https://github.com/apache/dubbo-samples)提供protostuff示例并发布拉取请求。

好的 一会我提交一个 请求 
并且 我还发现 @Reference注解创建消费者时  MethodConfig 对@method标签和使用xml创建 对 onreturn 
onthrow  oninvoke 这三个属性的即使不一致

**Comment by beiwei30** [comment]
https://github.com/apache/dubbo-samples/pull/104

**Comment by beiwei30** [comment]
https://github.com/apache/dubbo/pull/4645

**Comment by hanlukk** [comment]
这个问题解决了吗？哪个版本解决了？
