### ISSUE TITLE
ExtensionLoader.getActivateExtension 一个小的优化

### ISSUE THREAD

**Issue by sin-ning** [apache/dubbo#4569]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ -] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3

### ExtensionLoader.getActivateExtension

```java

                if (isMatchGroup(group, activateGroup)) {
                    // 这个应该放到 if 里面，会更合适
                    T ext = getExtension(name);
                    if (!names.contains(name)
                            && !names.contains(Constants.REMOVE_VALUE_PREFIX + name)
                            && isActive(activateValue, url)) {
                        exts.add(ext);
                    }


```

**Comment by cvictory** [comment]
Can you optimize the code and post pull request?
