### ISSUE TITLE
RegistryProtocol.DestroyableExporter 格式优化

### ISSUE THREAD

**Issue by sin-ning** [apache/dubbo#4570]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ -] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3

### Steps to reproduce this issue

-

### Expected Result
-

### Actual Result

-

``` java
    // private 应该改为  private static 保持统一
    static private class DestroyableExporter<T> implements Exporter<T> {
          // 省略
    }
```

**Comment by cvictory** [comment]
Can you post pull request for this issue?

**Comment by AnthonyKot** [comment]
Do you mean something like this:
https://github.com/apache/dubbo/pull/4583

**Comment by sin-ning** [comment]
No.

```java
static private class DestroyableExporter<T> implements Exporter<T> {
}
```

The following should be changed.

```java
private static class DestroyableExporter<T> implements Exporter<T> {
}
```

**Comment by beiwei30** [comment]
@sin-ning would you mind to submit a pull request to enhance it?

**Comment by Moriadry** [comment]
This issue has been solved, can be closed now. @beiwei30
