### ISSUE TITLE
dubbo2.7.2 提供者接口级别超时时间会覆盖方法级别超时时间

### ISSUE THREAD

**Issue by 18702524676** [apache/dubbo#4571]
`
@Service(timeout = 2000,retries = 3,methods = {
        @Method(name = "getNewUserAllMap",timeout = 50000,retries = 2),
        @Method(name = "getUserProfilesMap",timeout = 10000,retries = 3)
})
`
消费端没有配置超时时间，通过上述配置，getNewUserAllMap，getUserProfilesMap的超时时间都以Service配置的超时时间为准，与官方描述的超时时间优先级不符，dubbo版本2.7.2，求解决

**Comment by cvictory** [comment]
我觉得这个方式是对的，consumer端没有配置超时时间，本就应该以服务端为准，不然服务端的配置根本没有用了？

**Comment by 18702524676** [comment]
> 我觉得这个方式是对的，消费者端没有配置超时时间，本就应该以服务端为准，不然服务端的配置根本没有用了？

我在服务端给方法配置了超时时间，但是方法的超时时间没有生效，应该是服务端的方法级优先与服务端的类级

**Comment by beiwei30** [comment]
pls. verify, it should have been fixed on the main trunk.

**Comment by lizhuquan0769** [comment]
我使用的spring cloud alibaba 2.2.7，dubbo版本是2.7.13， 也出现这个问题，请问怎么解决了，method级别设置根本无效
