### ISSUE TITLE
Consider to upgrade to use fastjson 1.2.58

### ISSUE THREAD

**Issue by biyuhao** [apache/dubbo#4575]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master branch
* Operating System version: all
* Java version: all

### Steps to reproduce this issue

fastjson <= 1.2.48 considers vulnerable, see https://www.anquanke.com/post/id/181874
we are using 1.2.46, I think it's better to use the latest version [fastjson-1.2.58](https://github.com/alibaba/fastjson/releases/tag/1.2.58) if possible.

**Comment by cvictory** [comment]
Can you fire a pull request?
