### ISSUE TITLE
使用nacos作为注册中心，下线服务不生效问题

### ISSUE THREAD

**Issue by leshalv** [apache/dubbo#4577]
使用nacos作为注册中心，下线服务不生效问题

**Comment by leshalv** [comment]
DUBBO版本2.7.1，nacos从RC3到1.1.0都不好用

**Comment by kexianjun** [comment]
看下是不是 #4013 造成的

**Comment by leshalv** [comment]
我的意思是，我想通过nacos的下线按钮操作对dubbo服务的下线和上线，但是发现不生效

**Comment by leshalv** [comment]
nacos控制台版本号1.1.0
dubbo版本2.7.2

**Comment by chickenlj** [comment]
有以下2.7.2已知问题，同时在2.7.3已经修复，不知和你遇到的场景是否相符：
nacos由于没有遵循EMPTY协议，Nacos无法完成下线所有服务。

**Comment by leshalv** [comment]
我更新了2.7.3版本，下线还是不可以，难道是我只有一个消费者服务的问题吗？

**Comment by leshalv** [comment]
然后我升级了nacos1.1.1 客户端版本，然后还是点击下线还是不可以

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/61768002-9f812580-ae18-11e9-8efe-b7a6a2212372.png)
点击下线，我看控制台爆出了WRAN异常

**Comment by heixiaoma** [comment]
大佬，有联系方式吗？我也和你遇到同样问题，我现在就是用最新的dubbo还是不行，dubbo2.7.3和nacos 1.1.3

**Comment by leshalv** [comment]
> 大佬，有联系方式吗？我也和你遇到同样问题，我现在就是用最新的dubbo还是不行，dubbo2.7.3和nacos 1.1.3

给个邮箱

**Comment by mercyblitz** [comment]
It works.
