### ISSUE TITLE
wrapper 类无序，是否可以改为有序

### ISSUE THREAD

**Issue by zhaojigang** [apache/dubbo#4578]
hi，由于 Dubbo SPI AOP 的 wrapper 类使用 ConcurrentHashSet 来存储的，导致无法确定 wrapper 类的顺序，建议改为 TreeSet 或者 List 来存储
![image](https://user-images.githubusercontent.com/14085645/61259745-20537800-a7ae-11e9-9150-c3699308fbda.png)

### Environment
* Dubbo version: 2.6.6 2.7.3-SNAPSHOT也有这个问题
* Operating System version: mac
* Java version: jdk8

**Comment by beiwei30** [comment]
这样做没有意义，因为 classloader 加载的顺序也是未知的。应当确保 wrapper class 本身的实现与顺序无关。

**Comment by anLA7856** [comment]
可否给出更详细说明一下？从 代码外层中加载 SPI 对应类名文件来看，是按行从上往下读取，单个加载。是有顺序行的。
