### ISSUE TITLE
Consumer onconnect, ondisconnect is not working

### ISSUE THREAD

**Issue by codeimport** [apache/dubbo#4580]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows10
* Java version: JDK1.8

### Steps to reproduce this issue

1. set onconnect,ondisconnect parameter on @Reference
2. write onconnect,ondisconnect callback on consumer

code:

    @Reference(onconnect = "onconnect")
    private HelloDubboService helloDubboService;

    public void onconnect(){
        System.out.println(">>>>>>>>>>>>>>>>>onconnect()");
    }

### Expected Result

it should invoke onconnect ,ondisconnect callback when the consumer connect the provider 

### Actual Result

it does not work

is it a bug?or these callback only be used on provider side?

**Comment by chickenlj** [comment]
> is it a bug?or these callback only be used on provider side?

At present, it only works on the provider side.  But it would be a good complement if we can add support on the Consumer side.

**Comment by beiwei30** [comment]
I will verify. I believe it starts working now after https://github.com/apache/dubbo/pull/4598 is merged.

**Comment by beiwei30** [comment]
confirmed, it doesn't work. We need something like org.apache.dubbo.config.spring.schema.DubboBeanDefinitionParser#parseMethods when process `@Method`

**Comment by tswstarplanet** [comment]
> > is it a bug?or these callback only be used on provider side?
> 
> At present, it only works on the provider side. But it would be a good complement if we can add support on the Consumer side.

In fact the consumer side can also trigger the connected and disconnected methods of ChannelHandler interface of dubbo.

**Comment by cvictory** [comment]
从实现角度来看，provider和consumer的连接断开都应该可以增加一定的事件。
但是现在onconnect的配置是和接口绑定在一起，在后续的链路中会去找这个接口的对应实现。 consumer端是没有实现的，所以功能上暂时不能支持。

如果要在consumer端支持，应该需要调用一个独立的类和方法来完成。 暂时不建议增加。

----

From an implementation perspective, the disconnection between the provider and the consumer should be able to increase certain events.
But now the configuration of onconnect is bound to the interface, and the corresponding implementation of this interface will be found in subsequent links. The consumer side is not implemented, so it cannot be supported temporarily.

If you want to support it on the consumer side, you should call a separate class and method to complete it. It is not recommended to increase for the time being.
