### ISSUE TITLE
dubbo2.6.6 后应该删除对netty3的依赖

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo#4581]
dubbo2.6.6默认使用netty4,那么对netty3的依赖应该删除,应该讲netty4的依赖添加上

**Comment by chickenlj** [comment]
2.7中netty4已经是默认依赖。

**Comment by brucelwl** [comment]
> 2.7中netty4已经是默认依赖。

2.6.6 默认使用是netty4，但是依赖的jar 是 netty3， 启动时报错，请看清我的问题再关闭issue
