### ISSUE TITLE
Provider throw RpcException but Consumer do not invoke mock

### ISSUE THREAD

**Issue by codeimport** [apache/dubbo#4585]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: windowns10
* Java version: jdk1.8

### Steps to reproduce this issue

1. consumer set paramert mock = true
2. consumer add XxxServiceMock class
3. when provider receive connection more than executes provider throw RpcException

### Expected Result

when provider throw RpcException，consumer side will invoke XxxServiceMock

### Actual Result

provider return RpcResult，But not throw RpcException，so MockClusterInvoker can not catch
the RpcException and do not invoke XxxServiceMock

can i create a pr for it?

**Comment by cvictory** [comment]
@chickenlj  I review a pr about exception. It is the same as this one?
