### ISSUE TITLE
[Feature] @Reference auto-wires the instance of

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo#4594]
好像现在没这个实现，但是感觉如下方案可以实现？

```java
@Reference(interfaceName="com.xxx.xxx.DemoService",generic="true")
GenericService genericService;
```

解析的时候如果指定了是泛化，则设置interfacename为注解中interfaceName的值，如果没指定泛化为true，则走原来的步骤。

`GenericService` also can be auto-wired by `@Reference`

The correlative issue : https://github.com/apache/dubbo-spring-boot-project/issues/552

**Comment by CodingSinger** [comment]
can i commit a pr for this?
