### ISSUE TITLE
dubbo protocal host cannot support ipv6 format

### ISSUE THREAD

**Issue by ljywit** [apache/dubbo#4597]
I use IPV6 to configure protocal's host, like :
<dubbo:protocal host="**:**:**:**" port="22660"/>
I startup application, system will validate the host and throw "IllegalStateException" by name's pattern. I think the host cannot be used by name pattern when use ipv6.

ProtocolConfig.java
public void setHost(String host) {
        checkName(HOST_KEY, host);
        this.host = host;
    }

AbstractConfig.java.
protected static void checkName(String property, String value) {
        checkProperty(property, value, MAX_LENGTH, PATTERN_NAME);
    }

**Comment by chickenlj** [comment]
I think IPV6 support should be considered as a whole.

**Comment by KeRan213539** [comment]
遇到同样问题, 1年多了还没解决吗?
