### ISSUE TITLE
@Reference annotation ignore the @Method annotation

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#4607]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-SNAPSHOT
* Operating System version: MacOS
* Java version: java11

### Steps to reproduce this issue

1. Config reference like
```java
    @Reference(id = "referenceId1" , methods = {@Method(name = METHOD, timeout = 7000, arguments = @Argument(index = 0))})
    private DemoService demoService;
```
2. debug the application, observe if the methods config works

### Expected Result

the methods config works

### Actual Result

the methods config doesn't work

If there is an exception, please attach the exception trace:

I find that it seems the code following generate the effect
```java
package org.apache.dubbo.config.spring.util;

public class AnnotationUtils {
```

in the method public static Map<String, Object> getAttributes(Annotation annotation, PropertyResolver propertyResolver, boolean ignoreDefaultValue, String... ignoreAttributeNames)

```java
            if (attributeValue.getClass().isAnnotation()) {
                continue;
            }
            if (attributeValue.getClass().isArray() && attributeValue.getClass().getComponentType().isAnnotation()) {
                continue;
            }
```

Should we delete these code ?

**Comment by Leishunyu** [comment]
has remove it https://github.com/apache/dubbo/pull/4598

**Comment by beiwei30** [comment]
fixed
