### ISSUE TITLE
在 registry.simplified=true 时getColonSeparatedKey() 结果不完整

### ISSUE THREAD

**Issue by jimgreat** [apache/dubbo#4621]
- [ *] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ *] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: MAC_OS
* Java version: 1.8.0_181

### Steps to reproduce this issue

URL.getColonSeparatedKey() 正常结果应该是{interface}:[version]:[group]
在获取{interface}时，是直接通过INTERFACE_KEY从parameters中获取的，在registry.simplified=true 时：

final URL registeredProviderUrl = getRegisteredProviderUrl(providerUrl, registryUrl);

registeredProviderUrl 的 parameters中是没有INTERFACE_KEY的。
导致NacosRegistry在获取serviceName时不完整。

在append时对INTERFACE_KEY进行特殊处理可以解决
 **String parameterValue = INTERFACE_KEY.equals(parameterName)?getServiceInterface():this.getParameter(parameterName);**
`

    public String getColonSeparatedKey() {
        StringBuilder serviceNameBuilder = new StringBuilder();
        append(serviceNameBuilder, INTERFACE_KEY, true);
        append(serviceNameBuilder, VERSION_KEY, false);
        append(serviceNameBuilder, GROUP_KEY, false);
        return serviceNameBuilder.toString();
    }

    private void append(StringBuilder target, String parameterName, boolean first) {
        String parameterValue = INTERFACE_KEY.equals(parameterName)?getServiceInterface():this.getParameter(parameterName);
        if (!StringUtils.isBlank(parameterValue)) {
            if (!first) {
                target.append(":");
            }
            target.append(parameterValue);
        } else {
            target.append(":");
        }
    }`

**Comment by chickenlj** [comment]
> registry.simplified=true 时：
> 
> final URL registeredProviderUrl = getRegisteredProviderUrl(providerUrl, registryUrl);
> 
> registeredProviderUrl 的 parameters中是没有INTERFACE_KEY的

I find the same problem, I think we can solve it by adding `interface` key back to url: 

`dubbo.registry.extra-keys=interface`.
or
```xml
<dubbo:registry extra-keys="interface" />
```


This issue should be fixed in the next release.

**Comment by jimgreat** [comment]
dubbo.registry.extra-keys=interface 这个配置对 getRegisteredConsumerUrl 不生效

**Comment by chickenlj** [comment]
下一个版本这部分的实现可能会有一些重构，会把这个增强考虑在内的

**Comment by cvictory** [comment]
@jimgreat  can you post a pr?
