### ISSUE TITLE
nacos作为注册中心，如何指定namespace

### ISSUE THREAD

**Issue by lion000** [apache/dubbo#4627]
在使用nacos作为注册中心时，我希望dubbo的服务注册到nacos中心的时，能配置指定的namespace
### Environment

* Dubbo version: 2.7.1
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
理论上需要通过现有的<dubbo:registry group="xxx" /> 来配置，但是现在的版本还不支持，会考虑在下一个版本提供支持

**Comment by lion000** [comment]
好的，希望也可以使用dubbo.registry.namespace来配置
