### ISSUE TITLE
如果扩展codec2 接口？

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo#4628]
### Environment

* Dubbo version: 2.7.2
* Operating System version: win10
* Java version: 1.8

codec2 接口虽然被标注为spi，但是没有办法扩展，<dubbo:protocol >标签里只能设置codec，但是这个已经被标注成废弃，如何对codec2接口扩展呢？

**Comment by chickenlj** [comment]
虽然外围暴露的设置入口是codec，但是最终使用的是codec2扩展点，所以直接扩展codec2扩展点就可以了。

**Comment by chickenlj** [comment]
如有必要，请重新打开

**Comment by jimiyi** [comment]
我有一个疑问，为什么只有把org.apache.dubbo.remoting.Codec2文件放在META-INF.dubbo.internal下面才可以被替换，而放在META-INF.dubbo是无效的。另外我看到在dubbo-rpc/dubbo-rpc-dubbo/META-INF.dubbo.internal下面已经包含了Codec2的spi扩展文件，是不是因为这个原因？internal下面的优先级比较高？

**Comment by morisenmen** [comment]
There is another bug in here
in[DubboProtocol#createServer()] 
the code `url = url.addParameter(Constants.CODEC_KEY, DubboCodec.NAME);` should be
```
if (Objects.isNull(url.getParameter(Constants.CODEC_KEY)) {
    url = url.addParameter(Constants.CODEC_KEY, DubboCodec.NAME);
}
```

Another way is at the `AbstractEndpoint#getChannelCodec` 
have  priority
`String codecName = url.getParameter("default.codec", "telnet");`
than 
`String codecName = url.getParameter(Constants.CODEC_KEY, "telnet");`

But it is so dirty here.
