### ISSUE TITLE
Validate base642bytes(String) input.

### ISSUE THREAD

**Issue by Maxi17** [apache/dubbo#4631]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2
* Operating System version: Ubuntu 18.04
* Java version: 1.8

### Steps to reproduce this issue

Method `base642bytes(String)` and other overloaded methods only check the length of the input `String`, not its content. Currently, passing an invalid `String` to this method causes it to return an unpredictble result. For example:

```
import org.apache.dubbo.common.io.Bytes;

public class Testing {

    public static void main(String[] args) {
        System.out.println(Bytes.bytes2base64(Bytes.base642bytes("d=u=b=bo")));
	System.out.println(Bytes.bytes2base64(Bytes.base642bytes("invalid")));
    }
}

```

### Expected Result

`IllegalArgumentException` for the first call.

### Actual Result

Prints `//v///bo` for the first call and throws an `IllegalArgumentException` for the second call, even though both calls pass an invalid `String`.

Ideally, `base642bytes(String)` throws an `IllegalArgumentException` whenever an invalid input `String` is passed. This can be achieved by checking each character individually, which is highly inefficient, or by updating the documentation explaining under what conditions an `IllegalArgumentException` is thrown.

**Comment by chickenlj** [comment]
The length of a `Base64 encoded string` should be divided by 4 with no remainer.

**Comment by chickenlj** [comment]
Isn't that a requirement from the Base64 encoding algorithm?
