### ISSUE TITLE
when provider throw RpcException consumer do not retry correct times

### ISSUE THREAD

**Issue by codeimport** [apache/dubbo#4635]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: windows10
* Java version: jdk1.8

### Steps to reproduce this issue

1. consumer set retries 5
2. connection over executes on provider
3. provider throw RpcException

### Expected Result

consumer will retry 5 times

### Actual Result

when provider throw RpcException，FailoverClusterInvoker  receive a AppReponse with a RpcException in it，and FailoverClusterInvoker can not catch the RpcException and do not retry；

**Comment by beiwei30** [comment]
do you mean RpcException is explicitly thrown from business code on the provider side? If this is the case, then we should not fix anything.

**Comment by cvictory** [comment]
I think
