### ISSUE TITLE
dubbo的默认限流器存在线程安全问题

### ISSUE THREAD

**Issue by FanHuaRan** [apache/dubbo#4639]
dubbo的默认限流器是依靠org.apache.dubbo.rpc.filter.tps.StatItem做计数的，这个实现有线程安全问题：
1.滑动窗口移动的时候，有线程安全问题，可能造成误差，这儿可以使用CAS或者double check lock来改善。
2.计数器token没有加volatile关键字，多线程当中不具备可见性。

**Comment by kexianjun** [comment]
duplicate with #4280
