### ISSUE TITLE
Annotation based service with 'callback parameter' method not works correctly

### ISSUE THREAD

**Issue by dyachkovD** [apache/dubbo#4643]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
### Environment

* Dubbo version: 2.7.1
* Operating System version: Fedora 29
* Java version: SE 11 (18.9)

### Steps to reproduce this issue

1. Make service like this

```java
@Service(interfaceClass = MessagingService.class, methods = {
        @Method(name = "addMessageListener", arguments = {
                @Argument(index = 0, callback = true)
        })
})
public class MessagingServiceImpl implements MessagingService {

    @Override
    public void addMessageListener(MessageListener listener) {
        //...
    }
}
```

2. Call method **addMessageListener** on consumer side

### Expected Result

No exceptions thrown

### Actual Result

Throws **IllegalStateException**

*Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: addMessageListener, provider: dubbo://127.0.0.1:20880/com.example.api.service.MessagingService?application=dubbo-spring-boot-starter&default.generic=false&default.lazy=false&default.sticky=false&dubbo=2.0.2&generic=false&interface=com.example.api.service.MessagingService&lazy=false&methods=addMessageListener&pid=5389&register.ip=192.168.1.103&revision=0.0.1-SNAPSHOT&side=consumer&sticky=false&timestamp=1563276164135, cause: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Serialized class com.example.client.controller.MainController$1 must implement java.io.Serializable
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Serialized class com.example.client.controller.MainController$1 must implement java.io.Serializable*

**Comment by beiwei30** [comment]
It looks like a serialization issue, check this:

```
Serialized class com.example.client.controller.MainController$1 must implement java.io.Serializable
```

**Comment by dyachkovD** [comment]
@beiwei30 When I use the XML service configuration, everything works well. Сallback parameter should not implements java.io.Serializable. Check docs https://dubbo.apache.org/en-us/docs/user/demos/callback-parameter.html

**Comment by dyachkovD** [comment]
@beiwei30 No, com.example.client.controller.MainController$1 is simple closure. If i use XML configuration, works fine. The `@Argument` annotation seems to be ignored.
