### ISSUE TITLE
dubbo2.7.3 @Method 注解设置重试无效

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo#4644]
dubbo2.7.3 @Method 注解设置重试无效

**Comment by CrazyHZM** [comment]
repeated：#4635

**Comment by brucelwl** [comment]
> repeated：#4635
@CrazyHZM  未必是同一个问题, 我使用的是 @method 注解设置的重试, 但是dubbo2.7.2 版本正常, 通过其他方式设置的重试也正常,唯独@method 设置设置重试无效

**Comment by CrazyHZM** [comment]
是否可以提供相关配置，我试了method配置是正常的，或者你可以看一下dubbo-samples项目中关于注解的示例

**Comment by brucelwl** [comment]
@CrazyHZM   示例代，https://github.com/brucelwl/dubbo_integration_bug
先启动 服务提供端
再执行消费端的 单元测试
看服务提供端控制台打印的日志
相关类：
`com.bruce.rpc.provider.ProviderApplication`
`com.bruce.rpc.consumer.ConsumerNewTests`
`com.bruce.rpc.consumer.service.ConsumerNewDubbo`

**Comment by Leishunyu** [comment]
https://github.com/apache/dubbo/pull/4598 will fixed it in 2.7.4

**Comment by complone** [comment]
I saw this time retry 2 times by default, should I change to retry 1 time?

![problem](https://user-images.githubusercontent.com/20021404/63092155-60676f80-bf93-11e9-956c-04ec8711b8e1.png)

**Comment by Hansanshi** [comment]
我试了一下，不光是重试，其他参数也不生效

**Comment by beiwei30** [comment]
reopen, @brucelwl confirmed it still exist, let's target it to 2.7.7

**Comment by cvictory** [comment]
@brucelwl  I run with your demo, and it work will. 
I modified it to 5 times,  it worked well.

please check it again , I used dubbo and dubbo-spring-boot at 2.7.6

**Comment by cvictory** [comment]
@brucelwl  please check it again,  If you have some problem, let us know as soon as possible.
