### ISSUE TITLE
springboot 集成dubbo项目，@EnableDubbo需放到@SpringBootApplication注解类下面才生效，放到子包中得其他@Configuration中不生效

### ISSUE THREAD

**Issue by core1942** [apache/dubbo#4651]
version:2.7.1

```java
@SpringBootApplication
@EnableDubbo(scanBasePackages = "com.zm.crm.service.dubbo")
public class Application { }
```

生效

```java
@Configuration
@EnableDubbo(scanBasePackages = "com.zm.crm.service.dubbo")
public class DubboConfig { }
```

不生效

**Comment by ll2lxl** [comment]
I also encountered a similar problem that EnableDubbo's alisfor did not work on the configuration of the subpackage, but I did not try to put it into SpringbootApplication

**Comment by fibbery** [comment]
应该是注解AliasFor没生效吧，spring版本过低了。
不升级spring的话直接用DubboComponentScan吧

**Comment by beiwei30** [comment]
> 应该是注解AliasFor没生效吧，spring版本过低了。
> 不升级spring的话直接用DubboComponentScan吧

I agree with @fibbery's analysis, close it for now.

**Comment by core1942** [comment]
用的当前最新的spring boot版本 2.1.6.RELEASE

**Comment by jasonjoo2010** [comment]
related to #4693
