### ISSUE TITLE
dubbo 泛化调用采用API方式时consumer无法获取provider端抛出的异常信息

### ISSUE THREAD

**Issue by skiof007** [apache/dubbo#4654]
### Environment

* Dubbo version: 2.6.2
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo 泛化调用采用API方式时，consumer无法获取provider端抛出的异常信息,但采用<dubbo:reference  id="genericService" interface="hbec.app.dubbo.test.interfaces.IDubboService"   generic="true" />这种方式是可以获取到provider抛出的异常信息.

consumer端代码:
    
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName("generic-call-consumer");
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress("zookeeper://echqlm2:2181?backup=echqlm0:2181");
        ReferenceConfig<GenericService> referenceConfig = new ReferenceConfig<>();
        referenceConfig.setInterface("hbec.app.dubbo.test.interfaces.IDubboService");
        applicationConfig.setRegistry(registryConfig);
        referenceConfig.setApplication(applicationConfig);
        referenceConfig.setGeneric(true);
        referenceConfig.setAsync(true);
        referenceConfig.setTimeout(7000);
        genericService = referenceConfig.get();
        invokeSayHello();

    public static void invokeSayHello() throws Exception {

        Object result = genericService.$invoke("tt", null, new Object[]{"wfwfwf","152","323","52"});
     }

provider端代码:
              ApplicationConfig applicationConfig = new ApplicationConfig();
	        applicationConfig.setName("generic-impl-provider");
	        RegistryConfig registryConfig = new RegistryConfig();
            registryConfig.setAddress("zookeeper://echqlm2:2181?backup=echqlm0:2181");

	        GenericService helloService = new GenericImplOfHelloService();
	        ServiceConfig<GenericService> service = new ServiceConfig<>();
	        service.setApplication(applicationConfig);
	        service.setRegistry(registryConfig);
	        service.setInterface("hbec.app.dubbo.test.interfaces.IDubboService");
	        service.setRef(helloService);
	        service.export();

	        System.out.println("dubbo service started");
	        new CountDownLatch(1).await();

public class GenericImplOfHelloService implements GenericService {
    @Override
    public Object $invoke(String method, String[] parameterTypes, Object[] args) throws GenericException {
        if (method.equals("tt")) {
            System.out.print("executing sayHello.");
            throw new RuntimeException("sayHello: throws exception");
        } else if (method.equals("sayHelloAsync")) {
            System.out.print("executing sayHelloAsync.");
            return CompletableFuture.completedFuture("sayHelloAsync: hello " + args[0]);
        }

        GenericException genericException = new GenericException();
        genericException.setExceptionMessage("method does not exist.");
        throw genericException;
    }
}

**Comment by skiof007** [comment]
genericService.$invoke("tt", null, new Object[]{"wfwfwf","152","323","52"});//该方法在调用时无法获取provider端返回的异常信息

**Comment by skiof007** [comment]
新版不存在该问题!

**Comment by HongJinFeng** [comment]
新版本返回的GenericException是属于Apache的包的，而2.6.X版本GenericException是在alibaba包下的，hession进行反序列化的时候，低版本无法反序列化高版本的GenericExcetion，因为找不到这个类。
![441585025515_ pic](https://user-images.githubusercontent.com/33616750/77389799-0fdcae00-6dcf-11ea-8fbf-31368a52b969.jpg)
低版本consumer最后就序列化为返回一个map类
![471585025572_ pic](https://user-images.githubusercontent.com/33616750/77389803-12d79e80-6dcf-11ea-9c54-bb4ed3a613c4.jpg)
但是返回的流把Result标记为Exception（com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult#decode(com.alibaba.dubbo.remoting.Channel, java.io.InputStream），但是序列化结果不是GenericException。
![image](https://user-images.githubusercontent.com/33616750/77389899-5d591b00-6dcf-11ea-9e35-1131e649af39.png)
这个问题可以解决吗？

**Comment by qixiaobo** [comment]
https://github.com/apache/dubbo/issues/4675
