### ISSUE TITLE
Invalid name="com.alibaba.dubbo.config.ProtocolConfig#0" 

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo#4657]
`dubbo 2.6.7 `
`springBoot2.1.6`
使用@EnableDubbo启用dubbo, 配置dubbo.protocol.xxx相关属性,不设置dubbo.protocol.id,启动应用将会抛出异常. **java.lang.IllegalStateException: Invalid name="com.alibaba.dubbo.config.ProtocolConfig#0" contains illegal character, only digit, letter, '-', '_' or '.' is legal**
原因: 如果没有指定id属性,dubbo采用Spring 工具类BeanDefinitionReaderUtils.generateBeanName(builder.getRawBeanDefinition(), registry) 生成的bean名称带有`#0` , **见com.alibaba.dubbo.config.spring.context.annotation.DubboConfigBindingRegistrar resolveSingleBeanName 方法**,而 AbstractConfig中的正则会对该名称验证, `Pattern.compile("[\\-._0-9a-zA-Z]+")` 导致程序启动失败

**Comment by brucelwl** [comment]
@mercyblitz  本质原因竟然是因为com.alibaba.dubbo.config.spring.context.config.NamePropertyDefaultValueDubboConfigBeanCustomizer 会给name属性没有赋值的属性赋值

**Comment by icc99** [comment]
这个要咋解决 我现在dubbo2.7.5 和dubbo-spring-boot-starter 2.7.5 也出现这个问题. 之前都用2.7.4.1没有这个问题

**Comment by brucelwl** [comment]
> 这个要咋解决 我现在dubbo2.7.5 和dubbo-spring-boot-starter 2.7.5 也出现这个问题. 之前都用2.7.4.1没有这个问题

自己指定一下ID就行

**Comment by icc99** [comment]
> > 这个要咋解决 我现在dubbo2.7.5 和dubbo-spring-boot-starter 2.7.5 也出现这个问题. 之前都用2.7.4.1没有这个问题
> 
> 自己指定一下ID就行

在application.properties写入
dubbo.protocol.id=han

会报另一个错
java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name han

**Comment by brucelwl** [comment]
dubbo.protocol.name=dubbo

**Comment by icc99** [comment]
> dubbo.protocol.name=dubbo

还真是这样.. 谢谢

**Comment by wuuJiawei** [comment]
添加如下配置：

dubbo:
  application:
    name: this-is-consumer

**Comment by joviqiao** [comment]
我是apollo配置的，还是他妈提示这个，这项目捐出去来跟坨屎一样

**Comment by kabengka** [comment]
我吐了，dubbo.application.name、dubbo.application.id、dubbo.protocol.id、dubbo.protocol.name全都设置了，但是我消费者启动起来还是报这个错误，而我的提供者可以正常启动，就是一个小demo，一共才6个文件，我快要疯了。

**Comment by yisitmxk** [comment]
apache版本的dubbo有无数个bug, 代码质量非常差，建议大家不要升级到2.7以上，现在的开发人员质量太差了

**Comment by Jason274Zhao** [comment]
还行吧 , 阿里现在不怎么重视了
