### ISSUE TITLE
dubbo multi config Exception

### ISSUE THREAD

**Issue by liqing201104** [apache/dubbo#4658]
### Environment

* Dubbo version: 2.7.3
* Dubbo-spring-boot-starter: 2.7.1
* Spring-boot: 2.1.6.RELEASE

[示例代码参考](https://github.com/liqing201104/simple-demo/tree/master/dubbo-demo/dubbo-multi-config)

使用zookeeper和nacos双注册中心时，注册失败，异常信息如下 

*org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ServiceBean:org.apache.dubbo.samples.api.DemoService': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Multiple MetadataReport configs: {zookeeper=<dubbo:metadata-report address="zookeeper://192.168.124.254:2181" prefix="dubbo.metadata-report" valid="true" />, nacos=<dubbo:metadata-report address="nacos://nacos.didispace.com:80" prefix="dubbo.metadata-report" valid="true" />}*

**Comment by beiwei30** [comment]
You cannot specify multiple metadata report center [here](https://github.com/liqing201104/simple-demo/blob/master/dubbo-demo/dubbo-multi-config/src/main/resources/application.properties#L13)
