### ISSUE TITLE
@Reference annotation register in spring too late

### ISSUE THREAD

**Issue by asukaonly** [apache/dubbo#4661]
Reference annotation register in spring BeanPostProcessor
when @Reference annotation use param like timeout or check, i need copy reference again and again,  i can't just use @Resource to visit the reference. 
like this:
```
public class Demo1 {
    @Reference(url = "dubbo://127.0.0.1:7100", timeout = 5000, check = false)
    private UserService userService;
}
```

```
public class Demo2 {
    @Reference(url = "dubbo://127.0.0.1:7100", timeout = 5000, check = false)
    private UserService userService;
}
```
can we scan @Reference annotation in beanDefinition stage?

```
public class Demo1 {
    @Reference(url = "dubbo://127.0.0.1:7100", timeout = 5000, check = false)
    private UserService userService;
}
```

```
public class Demo2 {
    @Resource
    private UserService userService;
}
```

**Comment by beiwei30** [comment]
pls. try this:

```java
public class Demo1 {
    @Reference(id="user1", url = "dubbo://127.0.0.1:7100", timeout = 5000, check = false)
    private UserService userService;
}


public class Demo2 {
    @Autowired
    @Qualifier("user1")
    private UserService userService;
}
```

**Comment by asukaonly** [comment]
> pls. try this:
> 
> ```java
> public class Demo1 {
>     @Reference(id="user1", url = "dubbo://127.0.0.1:7100", timeout = 5000, check = false)
>     private UserService userService;
> }
> 
> 
> public class Demo2 {
>     @Autowired
>     @Qualifier("user1")
>     private UserService userService;
> }
> ```

it not work
@Autowired effect in AnnotationInjectedBeanPostProcessor
@Reference register reference to spring in ReferenceAnnotationBeanPostProcessor
when Demo2 init first, AnnotationInjectedBeanPostProcessor can't find reference in spring
