### ISSUE TITLE
关于netty4线程模型问题

### ISSUE THREAD

**Issue by wangx1949** [apache/dubbo#4662]
dubbo引入netty4之后, 有没有处理线程模型的问题?
业务线程执行以下代码, name字段不是volatile, 根据happens-before原则, 在序列化层可能看不到name值.

User user = new User(); //business thread
user.setName("admin");
channel.write(user); 
...
encoder.encode(user); //io thread
...

**Comment by beiwei30** [comment]
这个问题不可能出现的。

**Comment by wangx1949** [comment]
Indeed, according to this principle.
