### ISSUE TITLE
dubbo服务无法刷新拒绝服务

### ISSUE THREAD

**Issue by god8816** [apache/dubbo#4664]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.4
* Operating System version: 2.6.32-504.el6.x86_64
* Java version: 1.8.0_45

### Steps to reproduce this issue

1.偶然发现，无法重现

### Expected Result

What do you expected from the above steps？

### Actual Result
1: 偶然发现，我重启dubbo项目，有个dubbo服务没有刷新，其时间戳tamp没有刷新，其节点
值都正常。
2: 调用这个dubbo服务，发现其报拒绝服务错误。
3: 解决办法：在zookeeper删除这个节点，然后重启项目，项目恢复。
4: 我无法判断，这个bug是zookeeper还是dubbo？
<img width="1152" alt="企业微信截图_08dd1ecd-6588-4f40-94e4-04b01a9ee02e(1)" src="https://user-images.githubusercontent.com/13092208/61849008-847ae800-aee2-11e9-91a7-6c903e81acb3.png">

**Comment by cvictory** [comment]
dubbo2.5已经处于停止更新状态，能否使用2.6.x或者2.7.x的版本。 如果在上述两个版本中，还出现问题，我们会及时处理的。
