### ISSUE TITLE
xml和注解混合配置，系统启动报异常

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo#4667]
#4408 # Environment

* Dubbo version: 2.7.2
* Operating System version: win10
* Java version: 1.8

由于涉及老的系统升级，老的dubbo系统使用了com.alibaba.dubbo.config.annotation.Service的注解，同时还在xml文件中配置了部分dubbo相关的属性，spring boot系统在启动类上增加了@EnableDubbo(scanBasePackages = "XXX")，后启动报错：
Caused by: java.lang.IllegalStateException: Invalid name="org.apache.dubbo.config.ProtocolConfig#0" contains illegal character, only digit, letter, '-', '_' or '.' is legal.

**Comment by cvictory** [comment]
Can you raise dubbo to 2.7.3?   I remember it have been fixed in recently version.

After doing this, if you still have problem, I will check with you.

**Comment by beiwei30** [comment]
@jimiyi pls. provide a sample app to reproduce this issue on github. Thanks.

**Comment by cvictory** [comment]
duplicate https://github.com/apache/dubbo/issues/4657
