### ISSUE TITLE
dubbo服务自定义参数中文问题

### ISSUE THREAD

**Issue by lion000** [apache/dubbo#4668]
使用nacos注册中心
dubbo.protocol.name=dubbo
dubbo.protocol.port=19499
dubbo.protocol.host=127.0.0.1
dubbo.protocol.parameters.serviceLabel=测试服务
dubbo.protocol.charset=utf-8
例如上面的配置，parameters.serviceLabel会写入到nacos元数据里面，但是显示是???
已经指定了编码格式，请问怎样可以解决？

### Environment

* Dubbo version: 2.7.1
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by cvictory** [comment]
@mercyblitz  is it valid for chinese word?

**Comment by mercyblitz** [comment]
I am confused, Did you use Nacos as the registry or config center?

**Comment by mercyblitz** [comment]
It's not a Nacos or Dubbo issue, you have to handle the Chinese charset in your properties file, default, it uses ISO-8895-1
