### ISSUE TITLE
dubbo 配置问题

### ISSUE THREAD

**Issue by linchuyao** [apache/dubbo#4669]
目前provider 配置的是kryo序列化 现更改配置为hessian2并且重启provider 消费端不做重启在消费时还是使用kryo协议这是什么原因

**Comment by cvictory** [comment]
哪个版本的dubbo？  

提issue的时候，麻烦给下基础信息。

**Comment by linchuyao** [comment]
2.8.4

**Comment by beiwei30** [comment]
2.8.4 is dubbox, pls. verify it on 2.7 or 2.6. thanks.
