### ISSUE TITLE
关于模块调用之间的问题

### ISSUE THREAD

**Issue by fei1025** [apache/dubbo#4684]
### Environment

* Dubbo version: 2.5.3
* Operating System version: liunx 7
* Java version: 1.8
### 问题描述
        我们有A,B两个模块
        A模块通过Dubbo调用B模块的查询数据,如果B模块的查询的数据量小于10条的话,B模块就返回给A模块null,如果数据量大的话反而没有这个问题.
       现在这个问题是线上频繁发生,线上的服务器是阿里云上,部署了两台服务器,通过内网访问的.
但是在测试环境是基本没有发生,测试环境的服务器是本地的,并且两个模块是部署到一个服务器的.
      请指教下这个问题的原因,和解决办法
#### A 模板的
       	// 气费账单 
		mapCondition.put("billType", BillConstant.BILL_TYPE_GAS);

		String lang = LocaleContextHolder.getLocale().getLanguage();
		mapCondition.put("lang", lang);
		Map<String,String>  unnormalTypeView = viewDictEnumDataService.getEnumMap("BU0001", users.getMainDeptCode());
		Map<String,String>   billStatusView = viewDictEnumDataService.getEnumMap("BS0001", users.getMainDeptCode());

		String result = billForFeeService.searchBillInfoListYHNoPage(mapCondition,page,unnormalTypeView,billStatusView);

		return result;
#### B 模块的
          @Override
    public String searchBillInfoListYHNoPage(Map<String, Object> mapCondition,Page page,Map<String,String>  unnormalTypeView,
                                                           Map<String,String>   billStatusView) {
        page.startPageOrderBy();
        List<CustBillEntity> custBillList =  billMapper.searchBillInfoYH(mapCondition);
        PageInfo<CustBillEntity> pageInfo = new PageInfo<CustBillEntity>(custBillList);
        disposeGetBillGasInfo(pageInfo,unnormalTypeView,billStatusView);
        return page.toPageInfoJSONString(pageInfo);
    }

    public void disposeGetBillGasInfo(PageInfo<CustBillEntity> searchBillInfoList,Map<String,String>  unnormalTypeView,
                                      Map<String,String>   billStatusView){
        List<CustBillEntity> listMap = new ArrayList<CustBillEntity>();
        for (CustBillEntity billEntity : searchBillInfoList.getList()) {
            billEntity.setGasDetailList(billForFeeService.getBillGasInfo(billEntity.getBillCode()));
            billEntity.setMeterBillDetailList(billForFeeService.getBillMeterInfo(billEntity.getBillCode()));
            if(billEntity.getUnnormalTypeBf()!=null){
                billEntity.setUnnormalTypeBf(unnormalTypeView.get(billEntity.getUnnormalTypeBf()));

            }
            if(billEntity.getBillStatusBf()!=null){
                billEntity.setBillStatusBf(billStatusView.get(billEntity.getBillStatusBf()));
            }
            //应收金额要加上其他金额
            billEntity.setRcvblAmount(billEntity.getRcvblAmount().add(billEntity.getOtherFee()));
            listMap.add(billEntity);
        }
        searchBillInfoList.setList(listMap);

    }

**Comment by dai19470** [comment]
自己业务有问题吧

**Comment by fei1025** [comment]
> 问题

应该不是,代码上逻辑并不复杂

**Comment by dai19470** [comment]
debug,查看有没有调用到B模块的服务, 如果调用到查看一下B模块服务返回的数据.是否序列化

**Comment by it-huitailang** [comment]
在dai19470 的基础上，再做一个猜测，可能跟分页limit有关系。

**Comment by fei1025** [comment]
> debug,查看有没有调用到B模块的服务, 如果调用到查看一下B模块服务返回的数据.是否序列化

现在的问题是,本地没办法重现这个问题,只有线上有这个问题,而且还是偶然的

**Comment by fei1025** [comment]
> debug,查看有没有调用到B模块的服务, 如果调用到查看一下B模块服务返回的数据.是否序列化

正因为本地没办法重现,而且是因为线上模板是划分两个服务器,所有我才怀疑是Dubbo 之间的网络通信问题

**Comment by it-huitailang** [comment]
那现在的首要问题是想办法重现问题，否则无法判定是哪里的问题。

**Comment by beiwei30** [comment]
not a dubbo bug, feel free to reopen it if you confirm it is indeed a dubbo bug.
