### ISSUE TITLE
代码if判断 true，false问题

### ISSUE THREAD

**Issue by smipo** [apache/dubbo#4685]
分支:master
MyInvoker类63行 if (hasException == false)  是否可以改成 if (!hasException) 
BlockMyInvoker类43行 if (hasException == false)  是否可以改成 if (!hasException) 
LegacyInvoker类62行if (hasException == false)  是否可以改成 if (!hasException) 
PerformanceClientFixedTest类83行 if (client != null && client.isConnected() == false)
是否可以改成 if (client != null && !client.isConnected() )
第一次提交issue，如有错误，请指正，感谢

**Comment by CrazyHZM** [comment]
Can you submit a PR to clean this part.
