### ISSUE TITLE
When the provider interrupts abnormally, the consumer cannot return quickly and still waits for the timeout to end

### ISSUE THREAD

**Issue by zhaozhiwei2017** [apache/dubbo#4694]
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Windows 10
* Java version: Oracle JDK 1.8

### Steps to reproduce this issue

1. set @Reference(timeout = 10000)
2. kill -9 provider

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

fast return when timeout is not reached

### Actual Result

What actually happens?

the consumer returns until the timeout ends

detail see #1968

**Comment by zhaozhiwei2017** [comment]
#1968

**Comment by beiwei30** [comment]
dup of #4699
