### ISSUE TITLE
EchoFilter has no effect with Generic Call

### ISSUE THREAD

**Issue by seishuchen** [apache/dubbo#4703]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2~2.7.3
* Operating System version: Mac
* Java version: JDK1.8

### Steps to reproduce this issue

1. Use GenericService to call $echo

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

Echo what you send.

### Actual Result

Consumer：
```
Failed to check the status of the service com.alibaba.dubbo.monitor.MonitorService. No provider available for the service hesc/com.alibaba.dubbo.monitor.MonitorService from the url zookeeper://192.168.99.51:2183/com.alibaba.dubbo.registry.RegistryService?application=dime-test&dubbo=2.6.2&generic=true&group=hesc&interface=com.alibaba.dubbo.monitor.MonitorService&pid=92150&register.ip=172.28.58.146&side=consumer&timestamp=1564539016305 to the consumer 172.28.58.146 use dubbo version 2.6.2
```

Producer: no $echo method error

If there is an exception, please attach the exception trace:

*Method method = ReflectUtils.findMethodByMethodSignature(invoker.getInterface(), name, types);*

```
java.lang.NoSuchMethodException: com.alibaba.dubbo.monitor.MonitorService.$echo(java.lang.String)
```

Code:

```
@GetMapping("/test")
        public Result<String> test() {
            try {

                ReferenceConfig<GenericService> reference = new ReferenceConfig<GenericService>();
                // 弱类型接口名
                reference.setInterface("com.alibaba.dubbo.monitor.MonitorService");
                //                reference.setInterface("com.alibaba.dubbo.rpc.service.EchoService");
                // 声明为泛化接口 
                reference.setGeneric(true);

                ApplicationConfig applicationConfig = new ApplicationConfig();
                applicationConfig.setName("dime-test");
                reference.setApplication(applicationConfig);

                reference.setGroup("hesc");
                RegistryConfig registryConfig = new RegistryConfig();
                registryConfig.setAddress("zookeeper://192.168.99.51:2183?backup=192.168.99.37:2183");
                
                reference.setRegistry(registryConfig);

                // 用org.apache.dubbo.rpc.service.GenericService可以替代所有接口引用  
                GenericService genericService = reference.get();

                EchoService echoService = (EchoService) genericService;
                // 基本类型以及Date,List,Map等不需要转换，直接调用 
                Object result = genericService
                    .$invoke("$echo", new String[] { "java.lang.String" }, new Object[] { "Haha" });
                //                Object result = echoService.$echo("Haha");

                return Results.success(result.toString());
            } catch (Exception e) {
                return Results.error(e);
            }
        }
```

**Comment by qixiaobo** [comment]
I remember we should invoke code like this
```java
assertEqauls(“OK”, (echoService).$echo(“OK”))
```

**Comment by qixiaobo** [comment]
I think dubbo can only know this interface class is your business interface nor EchoService.
So it can  only find your interface defined methods.
But in fact your impl would be enhanced by dubbo proxy. It will add echoService interface to your impl.

**Comment by seishuchen** [comment]
> I remember we should invoke code like this
> 
> ```java
> assertEqauls(“OK”, echoService.$echo(“OK”))
> ```

GenericService genericService = reference.get();
EchoService echoService = (EchoService) genericService;
Object result = echoService.$echo("Hello");

**Comment by seishuchen** [comment]
GenericService genericService = reference.get();
            EchoService echoService = (EchoService) genericService;
            Object result = echoService.$echo("Hello");

**Comment by qixiaobo** [comment]
> > I remember we should invoke code like this
> > ```java
> > assertEqauls(“OK”, echoService.$echo(“OK”))
> > ```
> 
> Even this is useless.
> 
> ```
> GenericService genericService = reference.get();
> EchoService echoService = (EchoService) genericService;
> Object result = echoService.$echo("Hello");
> ```

I think you should call like this
```java
BusinessService businessService = reference.get();
EchoService echoService = (EchoService) businessService;
Object result = echoService.$echo("Hello");
```
Just as I say, the genericService not exists in fact.

You may have a try~

**Comment by beiwei30** [comment]
I am confused. Are you saying generic invocation doesn't work?

Feel free to reopen this issue after you try https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-generic/dubbo-samples-generic-call.

**Comment by qixiaobo** [comment]
> I am confused. Are you saying generic invocation doesn't work?
> 
> Feel free to reopen this issue after you try https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-generic/dubbo-samples-generic-call.

I can understand~ I think @seishuchen should hava a try like I said before

**Comment by seishuchen** [comment]
I mean that when you use generic call a service's $echo method to check whether this service is health, although the provider received the call, but the method name is $invoke, not $echo, then the condition does not match  in EchoFilter, the continue to excute until throw a NoSuchMethodException.

**Comment by qixiaobo** [comment]
> I mean that when you use generic call a service's $echo method to check whether this service is health, although the provider received the call, but the method name is $invoke, not $echo, then the condition does not match in EchoFilter, the continue to excute until throw a NoSuchMethodException.

You are right.  I think dubbo never support this feature before.
