### ISSUE TITLE
dubbo源码 换成zk注册中心就报错

### ISSUE THREAD

**Issue by PrayForZx** [apache/dubbo#4707]
![image](https://user-images.githubusercontent.com/24647693/62204781-80f2cf80-b3c0-11e9-811e-c80aa65ac19a.png) ，麻烦尽快修复，现在看源码还得看2.5.x的源码，不太方便

**Comment by zhaozhiwei2017** [comment]
提issue请标明dubbo版本，jdk版本，系统版本等基础信息，谢谢

**Comment by tswstarplanet** [comment]
是不是pom文件里没有添加依赖？

**Comment by finalcola** [comment]
应该是没有依赖
```
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-configcenter-zookeeper</artifactId>
        </dependency>
```

**Comment by beiwei30** [comment]
it should not happen on main trunk. feel free to reopen it if you still experience this issue.
