### ISSUE TITLE
在debug dubbo代码过程中initialized变量初始化就一直为true

### ISSUE THREAD

**Issue by HuaZohar** [apache/dubbo#4711]
在debug dubbo代码过程中initialized变量初始化一直为true
在类com.alibaba.dubbo.config.ReferenceConfig中
private transient volatile boolean initialized;
initialized变量一直为true;

idea无法打断点调试

**Comment by cvictory** [comment]
我测试是ok的，确认下自己环境。 或者在自己的github上提供一个demo。

**Comment by beiwei30** [comment]
this issue should have been fixed, pls. try against the latest version 2.7.3
