### ISSUE TITLE
高频交易下，优雅停机偶发调用失败逻辑问题

### ISSUE THREAD

**Issue by LYC-CLamDown** [apache/dubbo#4714]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.9目前使用/2.7.2也检查了确实还是有此逻辑bug  
* Operating System version: suse
* Java version: 1.8

### Steps to reproduce this issue
注册中心 zookeeper  。protocol ：dubbo
1. 优雅停机逻辑为首先断开所有注册中心连接，然后断开所有protocol连接
        // destroy all the registries
        AbstractRegistryFactory.destroyAll();
        // destroy all the protocols
        destroyProtocols();
2. zk收到provider下线请求会通知consumer一个event，让其对invokersList进行操作，更新（删除）下线的provider。在此更新完成前，如果仍旧有请求持续进入，有可能选中此provider，从而导致交易失败
3. 是否可以把Dubboprotocol.close中sendreadonlyEvnent提前到AbstractRegistryFactory.destroyAll();前，先把channel状态置为readonly，这样invoker.isavailable（）=false，就不会被选中了。

ps：还有个小问题，在只有一个提供者的情况下，为何不判断invoker.isavailable（）？在分批停机升级的时候，最后一台不论invoker.isavailable（）状态必然被选中，还是会有隐患。

**Comment by LYC-CLamDown** [comment]
是我提问方式不对么，怎么没人答复额

**Comment by tswstarplanet** [comment]
你说的优雅停机是指telnet之后用offline停机吗？

**Comment by tswstarplanet** [comment]
我看了代码，优雅关机的过程是先将服务向注册中心unregister，然后再关闭本地的网络连接（你所说的channel.readonly.send事件也是这个时候触发）

**Comment by wavesZh** [comment]
也许你可以通过增长`provider.shutdown.min.wait`来解决你的问题.优雅关机会等待一段时间（`provider.shutdown.min.wait`）以处理已到达的请求然后再关闭channel.

**Comment by LYC-CLamDown** [comment]
> 也许你可以通过增长`dubbo.service.shutdown.wait`来解决你的问题.优雅关机会等待一段时间（`dubbo.service.shutdown.wait`）以处理已到达的请求然后再关闭channel.

这个时间是用来等待在途交易完成，功能不一样。而且没办法从根本解决这个问题，通过sendreadonly事件可以等价于关闭业务channel， 不会再有业务进入。
目前我是加了一个在registryprotocol加了beforeDestory接口发送事件，但感觉不够优雅

**Comment by tswstarplanet** [comment]
先关channel也会有问题吧，我先关了，但是registry里还有，这期间你那边也可能会有请求过来

**Comment by LYC-CLamDown** [comment]
> 先关channel也会有问题吧，我先关了，但是registry里还有，这期间你那边也可能会有请求过来

再有多个invoker的时候，doselect（）会判断invoker.isavailable（）的，通过client.isconnect()和channel状态是否不为readonly，在dubboinvoker这个类

但是单个invoker的时候没这个判断，所以有我上面最后的那个小疑问

**Comment by tswstarplanet** [comment]
嗯嗯，忘了这个了，不过你看多个invoker的时候，其实也是会重新选择，一个的时候没有其他选择，所以不判断了吧

**Comment by LYC-CLamDown** [comment]
> 嗯嗯，忘了这个了，不过你看多个invoker的时候，其实也是会重新选择，一个的时候没有其他选择，所以不判断了吧

嗯呐，但是也有个情况，如果只有一个invoke的时候但不校验isavialable（），这个provider在优雅停机过程中，就不能第一时间发现没有提供者了~最差情况要等 dubbo.service.shutdown.wait 这个时间了。

回到一开始那个问题哈，因为我们对业务成功率要求比较高，出现过这个问题，很偶发。目前改法也在上面说了，但感觉不够优雅~还请指点谢谢

**Comment by wavesZh** [comment]
按你的解决方案，先`sendChannelReadOnlyEvent`给consumer以禁用channel，这个过程是有时间差的，仍是会有请求发出，在`dubbo.service.shutdown.wait`内，provider是可以正常处理的。如果时间差大于这个（可能性小），请求会失败。按照目前dubbo的做法：provider先`AbstractRegistryFactory.destroyAll`会触发consumer更新invoker list，然后`sendChannelReadOnlyEvent`后等待`dubbo.service.shutdown.wait` ，关闭channel。如果发生你那种请求处理失败的情况，只有当超过了`dubbo.service.shutdown.wait`，consumer仍没有禁用channel或更新invoker list或请求在路上漂了太久了。这种可能性也比较小吧。我感觉这个无法根本解决，`sendChannelReadOnlyEvent`和 禁用channel 本就不是原子性的。
