### ISSUE TITLE
org.apache.dubbo.registry.multicast.MulticastRegistry#checkMulticastAddress

### ISSUE THREAD

**Issue by long181170** [apache/dubbo#4716]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-SNAPSHOT
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. 这个地方的判断是不是写反了，ipv4的地址要提示ipv6的报错。
![bug](https://user-images.githubusercontent.com/31816029/62285052-73ece380-b487-11e9-9617-c1c4ef2fb31d.jpg)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by tswstarplanet** [comment]
Has been fixed
