### ISSUE TITLE
dubbo 2.7.1版本里，当client连接不上zookeeper时，ctrl + c 退出不了进程，只能kill -9

### ISSUE THREAD

**Issue by hengyunabc** [apache/dubbo#4719]
Demo: [demo3.zip](https://github.com/apache/dubbo/files/3456605/demo3.zip)

直接运行：

```
mvn spring-boot:run -DskipTests
```

**Comment by cvictory** [comment]
专业，最喜欢demo.

**Comment by finalcola** [comment]
在最新的dubbo版本中已经修复了。是因为在ZookeeperDynamicConfiguration中，会将zk作为配置中心，在初始化时会连接zk并拉取配置，2.7.1中做法是一直阻塞，最新版本会带有超时时间。
