### ISSUE TITLE
Thread pool is EXHAUSTED while active is 0

### ISSUE THREAD

**Issue by shiluotang** [apache/dubbo#4723]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: centos-6
* Java version: 1.7.0_71
### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

[DUBBO] Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-xxxx, Pool Size: 100 (active: 0, core: 100, max: 100, largest: 100), Task: 8960329 (completed: 8960329), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://xxxxxxx:xxxx!, dubbo version: 2.5.3, current host: xxxxxxxxxx

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by complone** [comment]
You set up 100 threads, and active represents the number of connections currently available. So I think that active 0 is normal.

**Comment by shiluotang** [comment]
> represents

How could that be normal? The whole thread pool is idle but log says no thread could be spared for new job?

**Comment by complone** [comment]
> > represents
> 
> How could that be normal? The whole thread pool is idle but log says no thread could be spared for new job?

Sorry, I didn't look at it at the time. Can you use jstack to observe the current state of the thread?

**Comment by web1992** [comment]
Which thread poll you use it? In Duboo has `CachedThreadPool`,`EagerThreadPool`,`FixedThreadPool`,`LimitedThreadPool`

**Comment by shiluotang** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 2.5.3
> * Operating System version: centos-6
> * Java version: 1.7.0_71
> 
> ### Steps to reproduce this issue
> 1. xxx
> 2. xxx
> 3. xxx
> 
> Pls. provide [GitHub address] to reproduce this issue.
> 
> ### Expected Result
> What do you expected from the above steps？
> 
> ### Actual Result
> What actually happens?
> 
> [DUBBO] Thread pool is EXHAUSTED! Thread Name: DubboServerHandler-xxxx, Pool Size: 100 (active: 0, core: 100, max: 100, largest: 100), Task: 8960329 (completed: 8960329), Executor status:(isShutdown:false, isTerminated:false, isTerminating:false), in dubbo://xxxxxxx:xxxx!, dubbo version: 2.5.3, current host: xxxxxxxxxx
> 
> If there is an exception, please attach the exception trace:
> 
> ```
> Just put your stack trace here!
> ```

Dubbo can't get the state of thread pool when it's exhausted, so the situation describe above is very likely to happen in heavy threading.

**Comment by h2562961224** [comment]
I had this issue too while high concurrency happened. I solve it by using a size of TaskQueue which larger than the maxPoolSize .It seem like a 1-sized(default config) TaskQueue cant perform well in high concurrency case

**Comment by shiluotang** [comment]
> I had this issue too while high concurrency happened. I solve it by using a size of TaskQueue which larger than the maxPoolSize .It seem like a 1-sized(default config) TaskQueue cant perform well in high concurrency case

Thanks for your suggestion!
