### ISSUE TITLE
[ISSUE] Is it right that the program return directly when it is the consumer url?

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#4724]
In https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java#L99~L102,  it will be reture directly if it is consumer url.    

How do the ops collect consumer info?

```
@Override
    public void register(URL url) {
        if (isConsumerSide(url)) {
            return;
        }

        super.register(url);
    }
```

**Comment by tswstarplanet** [comment]
I think this method can be deleted because other concrete registry class like ZookeeperRegistry doesn't have the method.

**Comment by AnthonyKot** [comment]
Actually some of concrete registry still has same check:
https://github.com/apache/dubbo/blob/956d28b11ecda2b4aa3c76481c95f06fc3833210/dubbo-registry/dubbo-registry-sofa/src/main/java/org/apache/dubbo/registry/sofa/SofaRegistry.java#L200~L204

**Comment by cvictory** [comment]
I will close the issue at present.
