### ISSUE TITLE
dubbo泛化调用 返回值首字母小写问题

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo#4737]
通过泛化调用方式 返回了一个对象，对象里面参数首字母小写了。这种如何解决呢。
比如生产者返回：:{"code":101,"msg":"WMS_发票号已回传","result":{"ERDAT":"20190804","TYPE":"E","MESSAGE":"发票号已回传"},"success":false}

泛化调用返回：{"code":101,"msg":"WMS_发票号已回传","result":{"mESSAGE":"发票号已回传","tYPE":"E","class":"com.xxx.xxx.xxx.xxxx","eRDAT":"20190804"},"success":false}

里面的result 首字母小写了

**Comment by CrazyHZM** [comment]
用的是什么协议，什么序列化方式

**Comment by 1076572358** [comment]
> 用的是什么协议，什么序列化方式

协议dubbo  默认序列化方式

**Comment by sumlight** [comment]
这大写的成员变量不符合规范啊，都按规范取名就完全避免这个问题了。阿里的相关规范：【强制】方法名、参数名、成员变量、局部变量都统一使用lowerCamelCase风格，必须遵从驼峰形式。

**Comment by 1076572358** [comment]
> 这大写的成员变量不符合规范啊，都按规范取名就完全避免这个问题了。阿里的相关规范：【强制】方法名、参数名、成员变量、局部变量都统一使用lowerCamelCase风格，必须遵从驼峰形式。

我也知道不符合规范 ，但是很多时候偏偏有这么个情况。而且问题是 提供者返回值通过泛化接口调用后 里面对象首字母小写了。

**Comment by qixiaobo** [comment]
啥版本dubbo

**Comment by qixiaobo** [comment]
看起来目前是这么处理的
```java
 if (ProtocolUtils.isJavaGenericSerialization(generic)) {
                    try {
                        UnsafeByteArrayOutputStream os = new UnsafeByteArrayOutputStream(512);
                        ExtensionLoader.getExtensionLoader(Serialization.class)
                                .getExtension(Constants.GENERIC_SERIALIZATION_NATIVE_JAVA)
                                .serialize(null, os).writeObject(result.getValue());
                        return new RpcResult(os.toByteArray());
                    } catch (IOException e) {
                        throw new RpcException("Serialize result failed.", e);
                    }
                } else if (ProtocolUtils.isBeanGenericSerialization(generic)) {
                    return new RpcResult(JavaBeanSerializeUtil.serialize(result.getValue(), JavaBeanAccessor.METHOD));
                } else {
                    return new RpcResult(PojoUtils.generalize(result.getValue()));
                }
```
默认情况下都是PojoUtils.generalize

```java
  map.put("class", pojo.getClass().getName());
        for (Method method : pojo.getClass().getMethods()) {
            if (ReflectUtils.isBeanPropertyReadMethod(method)) {
                try {
                    map.put(ReflectUtils.getPropertyNameFromBeanReadMethod(method), generalize(method.invoke(pojo), history));
                } catch (Exception e) {
                    throw new RuntimeException(e.getMessage(), e);
                }
            }
        }
        // public field
        for (Field field : pojo.getClass().getFields()) {
            if (ReflectUtils.isPublicInstanceField(field)) {
                try {
                    Object fieldValue = field.get(pojo);
                    if (history.containsKey(pojo)) {
                        Object pojoGenerilizedValue = history.get(pojo);
                        if (pojoGenerilizedValue instanceof Map
                                && ((Map) pojoGenerilizedValue).containsKey(field.getName())) {
                            continue;
                        }
                    }
                    if (fieldValue != null) {
                        map.put(field.getName(), generalize(fieldValue, history));
                    }
                } catch (Exception e) {
                    throw new RuntimeException(e.getMessage(), e);
                }
            }
        }
```
即均是使用readmethod放到map中&public field
其中对于方法转属性如下处理
```java
    public static String getPropertyNameFromBeanReadMethod(Method method) {
        if (isBeanPropertyReadMethod(method)) {
            if (method.getName().startsWith("get")) {
                return method.getName().substring(3, 4).toLowerCase()
                        + method.getName().substring(4);
            }
            if (method.getName().startsWith("is")) {
                return method.getName().substring(2, 3).toLowerCase()
                        + method.getName().substring(3);
            }
        }
        return null;
    }

```
因此会出现首字母大写的属性会被默认小写

**Comment by 1076572358** [comment]
> 看起来目前是这么处理的
> 
> ```java
>  if (ProtocolUtils.isJavaGenericSerialization(generic)) {
>                     try {
>                         UnsafeByteArrayOutputStream os = new UnsafeByteArrayOutputStream(512);
>                         ExtensionLoader.getExtensionLoader(Serialization.class)
>                                 .getExtension(Constants.GENERIC_SERIALIZATION_NATIVE_JAVA)
>                                 .serialize(null, os).writeObject(result.getValue());
>                         return new RpcResult(os.toByteArray());
>                     } catch (IOException e) {
>                         throw new RpcException("Serialize result failed.", e);
>                     }
>                 } else if (ProtocolUtils.isBeanGenericSerialization(generic)) {
>                     return new RpcResult(JavaBeanSerializeUtil.serialize(result.getValue(), JavaBeanAccessor.METHOD));
>                 } else {
>                     return new RpcResult(PojoUtils.generalize(result.getValue()));
>                 }
> ```
> 
> 默认情况下都是PojoUtils.generalize
> 
> ```java
>   map.put("class", pojo.getClass().getName());
>         for (Method method : pojo.getClass().getMethods()) {
>             if (ReflectUtils.isBeanPropertyReadMethod(method)) {
>                 try {
>                     map.put(ReflectUtils.getPropertyNameFromBeanReadMethod(method), generalize(method.invoke(pojo), history));
>                 } catch (Exception e) {
>                     throw new RuntimeException(e.getMessage(), e);
>                 }
>             }
>         }
>         // public field
>         for (Field field : pojo.getClass().getFields()) {
>             if (ReflectUtils.isPublicInstanceField(field)) {
>                 try {
>                     Object fieldValue = field.get(pojo);
>                     if (history.containsKey(pojo)) {
>                         Object pojoGenerilizedValue = history.get(pojo);
>                         if (pojoGenerilizedValue instanceof Map
>                                 && ((Map) pojoGenerilizedValue).containsKey(field.getName())) {
>                             continue;
>                         }
>                     }
>                     if (fieldValue != null) {
>                         map.put(field.getName(), generalize(fieldValue, history));
>                     }
>                 } catch (Exception e) {
>                     throw new RuntimeException(e.getMessage(), e);
>                 }
>             }
>         }
> ```
> 
> 即均是使用readmethod放到map中&public field
> 其中对于方法转属性如下处理
> 
> ```java
>     public static String getPropertyNameFromBeanReadMethod(Method method) {
>         if (isBeanPropertyReadMethod(method)) {
>             if (method.getName().startsWith("get")) {
>                 return method.getName().substring(3, 4).toLowerCase()
>                         + method.getName().substring(4);
>             }
>             if (method.getName().startsWith("is")) {
>                 return method.getName().substring(2, 3).toLowerCase()
>                         + method.getName().substring(3);
>             }
>         }
>         return null;
>     }
> ```
> 
> 因此会出现首字母大写的属性会被默认小写

这波源码分析给满分，也就是说底层给熟悉强制设置成首字母小写了。那这估计没法子改了吧。

**Comment by qixiaobo** [comment]
看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】

**Comment by 1076572358** [comment]
> 看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】

对的 返回bean的class在泛化调用端不存在。

**Comment by qixiaobo** [comment]
> > 看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】
> 
> 对的 返回bean的class在泛化调用端不存在。

所以 几乎无解了 除非你加新的泛化方式
当然了还有你的java bean 可以把field改成public【馊主意】如果只是一个类的话

**Comment by 1076572358** [comment]
> > > 看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】
> > 
> > 
> > 对的 返回bean的class在泛化调用端不存在。
> 
> 所以 几乎无解了 除非你加新的泛化方式
> 当然了还有你的java bean 可以把field改成public【馊主意】如果只是一个类的话

遗憾的是我把field改成public仍然首字母小写，首字母小写是否还有其他原因呢

**Comment by 1076572358** [comment]
> > > > 看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】
> > > 
> > > 
> > > 对的 返回bean的class在泛化调用端不存在。
> > 
> > 
> > 所以 几乎无解了 除非你加新的泛化方式
> > 当然了还有你的java bean 可以把field改成public【馊主意】如果只是一个类的话
> 
> 遗憾的是我把field改成public仍然首字母小写，首字母小写是否还有其他原因呢

我使用dubbo版本为2.7.0

**Comment by qixiaobo** [comment]
> > > > > 看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】
> > > > 
> > > > 
> > > > 对的 返回bean的class在泛化调用端不存在。
> > > 
> > > 
> > > 所以 几乎无解了 除非你加新的泛化方式
> > > 当然了还有你的java bean 可以把field改成public【馊主意】如果只是一个类的话
> > 
> > 
> > 遗憾的是我把field改成public仍然首字母小写，首字母小写是否还有其他原因呢
> 
> 我使用dubbo版本为2.7.0

注意field不要是final以及static

**Comment by 1076572358** [comment]
> > > > > > 看上去generic 支持nativejava 应当是无损的【不过这个和泛化调用不符合 毕竟这个返回bean的class在返回调用侧可能不存在】
> > > > > 
> > > > > 
> > > > > 对的 返回bean的class在泛化调用端不存在。
> > > > 
> > > > 
> > > > 所以 几乎无解了 除非你加新的泛化方式
> > > > 当然了还有你的java bean 可以把field改成public【馊主意】如果只是一个类的话
> > > 
> > > 
> > > 遗憾的是我把field改成public仍然首字母小写，首字母小写是否还有其他原因呢
> > 
> > 
> > 我使用dubbo版本为2.7.0
> 
> 注意field不要是final以及static

我的只是一个普通实体类，原本是private，后来改成了public

**Comment by qixiaobo** [comment]
sorry 目前我说的都是2.6.x版本代码 2.7.x代码我没有看

**Comment by 1076572358** [comment]
> sorry 目前我说的都是2.6.x版本代码 2.7.x代码我没有看

已经很感谢了 🙏

**Comment by CrazyHZM** [comment]
2.7.x的实现也是上述所说，还是希望你可以从代码规范来解决该问题，我先关闭该issues，如果有问题可以随时重新开启。

**Comment by 98DE9E1F** [comment]
> 2.7.x的实现也是上述所说，还是希望你可以从代码规范来解决该问题，我先关闭该issues，如果有问题可以随时重新开启。

一般使用泛化 调用的场景 网关居多，如果涉及到已有的业务，遵循规范让业务方进行改造，考虑到影响面和成本，业务方几乎不会配合
