### ISSUE TITLE
活捉ConfigCenterConfig配置变动导致timeout判断无效的问题

### ISSUE THREAD

**Issue by richie696** [apache/dubbo#4760]
首先声明此问题从2.7.0版本~2.7.3版本全部都受到影响，ConfigCenter的配置键是以config.开头，比如config.timeout，而org.apache.dubbo.common.constants.CommonConstants.TIMEOUT常量的定义则是String TIMEOUT_KEY = "timeout"; 在配置初始化的时候，初始化时长如果不超过预设的5秒则不会出问题，如果超出的话则会抛出如下异常
`RROR CuratorFrameworkImpl:694 - Background operation retry gave up
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss`
经过我的排查发现只有使用apache curator的版本在2.x的时候才不会有该异常，使用3.x和4.x都会出现，虽然此异常并不会有什么其他的影响，但是每次启动工程的时候都会抛出，非常难受，希望可以解决一下，具体的几个关键处代码我已经放到截图中。
![1](https://user-images.githubusercontent.com/7754030/62594507-7af37600-b90d-11e9-9482-18775849c786.png)
![2](https://user-images.githubusercontent.com/7754030/62594508-7b8c0c80-b90d-11e9-9c30-da16091c622e.png)
![3](https://user-images.githubusercontent.com/7754030/62594511-7c24a300-b90d-11e9-8d93-c84b4dac29d7.png)
![4](https://user-images.githubusercontent.com/7754030/62594512-7c24a300-b90d-11e9-93b5-157d79433b12.png)
![5](https://user-images.githubusercontent.com/7754030/62594513-7cbd3980-b90d-11e9-88f5-ae631dd437ae.png)
![6](https://user-images.githubusercontent.com/7754030/62594514-7d55d000-b90d-11e9-9150-d0e5f2890d53.png)

**Comment by tswstarplanet** [comment]
@complone I think your solution is not right, because the zookeeper transporter is not only used by config-center. It will not use "config.timeout" as timeout key when it is used by Zookeeper Registry.

**Comment by richie696** [comment]
> @complone I think your solution is not right, because the zookeeper transporter is not only used by config-center. It will not use "config.timeout" as timeout key when it is used by Zookeeper Registry.

So what do I do right?I followed the ‘dubbo-samples/dubbo-samples-annotation’ and reported the error. My configuration file is as follows:
![10](https://user-images.githubusercontent.com/7754030/62614894-dd189f00-b93e-11e9-97ea-bf3c10398478.png)
![11](https://user-images.githubusercontent.com/7754030/62614896-ddb13580-b93e-11e9-96bf-7d15ad31299e.png)
![12](https://user-images.githubusercontent.com/7754030/62614897-de49cc00-b93e-11e9-8a58-b5f9ed759952.png)

**Comment by complone** [comment]
> @complone I think your solution is not right, because the zookeeper transporter is not only used by config-center. It will not use "config.timeout" as timeout key when it is used by Zookeeper Registry.


Thank you for your correction.I saw your [Dubbo-4760](https://github.com/apache/dubbo/pull/4763)
