### ISSUE TITLE
一致性hash负载均衡为啥要四个节点分一个摘要

### ISSUE THREAD

**Issue by typooooohj** [apache/dubbo#4762]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7
* Operating System version: win64
* Java version: 1.8

### Steps to reproduce this issue

        ConsistentHashSelector(List<Invoker<T>> invokers, String methodName, int identityHashCode) {
            this.virtualInvokers = new TreeMap<Long, Invoker<T>>();
            this.identityHashCode = identityHashCode;
            URL url = invokers.get(0).getUrl();
            this.replicaNumber = url.getMethodParameter(methodName, HASH_NODES, 160);
            String[] index = COMMA_SPLIT_PATTERN.split(url.getMethodParameter(methodName, HASH_ARGUMENTS, "0"));
            argumentIndex = new int[index.length];
            for (int i = 0; i < index.length; i++) {
                argumentIndex[i] = Integer.parseInt(index[i]);
            }
            for (Invoker<T> invoker : invokers) {
                String address = invoker.getUrl().getAddress();
                for (int i = 0; i < replicaNumber / 4; i++) {
                   //这里生成的16字节摘要为啥要分在四个节点
                    byte[] digest = md5(address + i);
                    for (int h = 0; h < 4; h++) {
                        long m = hash(digest, h);
                        virtualInvokers.put(m, invoker);
                    }
                }
            }
        }

**Comment by typooooohj** [comment]
hash环是0~2^(32)次方所以，要把16字节除以4，但是这样，如果一个进来的hash值顺时针扫面最近的一个hash环上的节点，这个节点只有四分之一的摘要信息，无法定位带真正的invoker啊！

**Comment by typooooohj** [comment]
知道了，我猜这里的MD5生成了16字节，而hash换的key只要4个字节，所以一次md5可以用在四个节点，除非碰巧其中有两个一样。

**Comment by complone** [comment]
It is divided into the following two steps:

- Generate a message digest for every 4 nodes according to the md5 algorithm. The digest is 16 bytes and 128 bits long.
- Then divide 128 bits into 4 parts, 0-31, 32-63, 64-95, 95-128, and generate 4 32-bit numbers, stored in long, the high 32 bits of long are 0 and as the key of the virtual node.

**Comment by typooooohj** [comment]
> It is divided into the following two steps:
> 
> * Generate a message digest for every 4 nodes according to the md5 algorithm. The digest is 16 bytes and 128 bits long.
> * Then divide 128 bits into 4 parts, 0-31, 32-63, 64-95, 95-128, and generate 4 32-bit numbers, stored in long, the high 32 bits of long are 0 and as the key of the virtual node.

thanks a lot,  as a freshman ,I have forgotten long has 64bits, so the hight 32 bits should be zero.
