### ISSUE TITLE
dubbo路由规则根据应用无效

### ISSUE THREAD

**Issue by WhaleCloud-platform** [apache/dubbo#4779]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Mac
* Java version: 8

### 原因
> 使用zdubbo-admin新建条件路由，目录为`/configCenterGroup/config/demo-consumer.condition-router`这里没有namespace概念，其实整个zdubbo -admin也没这个概念

> 然后dubbo consumer启动时，需要配置`namespace="configCenterGroup"`，然后在`ListenableRouter`获取规则时，通过`namespace`+`group`来获取的，结果是`/configCenterGroup/config/dubbo/demo-consumer.condition-router`。但是group又是默认值又是dubbo。导致规则取不出来

```java
    private synchronized void init(String ruleKey) {
        if (StringUtils.isEmpty(ruleKey)) {
            return;
        }
        String routerKey = ruleKey + RULE_SUFFIX;
        configuration.addListener(routerKey, this);
        String rule = configuration.getRule(routerKey, DynamicConfiguration.DEFAULT_GROUP);
        if (StringUtils.isNotEmpty(rule)) {
            this.process(new ConfigChangeEvent(routerKey, rule));
        }
    }
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

> 是否需要修改zdubbo-admin加上namespace这个概念，然后是否需要修改dubbo代码，group不能写死成默认值

### Actual Result
> zdubbo-admin新增属性：admin.config-center.namespace=

> `String rule = configuration.getRule(routerKey, DynamicConfiguration.DEFAULT_GROUP);`group写活
What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by WhaleCloud-platform** [comment]
https://github.com/apache/dubbo/pull/4388/files/ff2bf5630279ad377d853c88edd41e4e05138fec
是不是这个改成问题了。2

**Comment by chickenlj** [comment]
@WhaleCloud-platform 
请确认一下你最终的配置是写在了哪个路径，是这个么： `/configCenterGroup/config/dubbo/demo-consumer.condition-router`

2.7.3相比2.7.2及之前版本，在zookeeper存储路径上有一些变化，变为：
`/configCenterGroup/config/dubbo/demo-consumer/condition-router`
具体链接参考：https://github.com/apache/dubbo/releases/tag/dubbo-2.7.3

**Comment by chickenlj** [comment]
如果Admin能写入这个根目录/configCenterGroup/，那应该就不是Admin的问题

**Comment by WhaleCloud-platform** [comment]
dubbo-admin写入的时候，目录是:`/configCenterGroup/config/demo-consumer.condition-router`，相比dubbo获取规则，目录是：`/configCenterGroup/config/dubbo/demo-consumer.condition-router`，多了`/dubbo`。是不是dubbo-admin需要修改下。  还有dubbo取规则的时候  为什么要用默认的GROUP。是不是应该取`dubbo.config-center.group`值。

**Comment by tswstarplanet** [comment]
@chickenlj 这里有个地方我也不太明白，就是scope为Application的配置，是group就是这个应用名吧。那如果设置为provider的应用名，那consumer的应用名不是这个，这样这个规则还会生效吗？

**Comment by tswstarplanet** [comment]
@WhaleCloud-platform 你用的配置中心是zookeeper吗？

**Comment by tswstarplanet** [comment]
我在dubbo-admin配置的应用级别标签在zookeeper的路径是
/dubbo/config/demo-provider/condition-router
跟你那个也不一样

**Comment by tswstarplanet** [comment]
感觉这里dubbo-admin和dubbo的处理确实有不一致的地方

**Comment by tswstarplanet** [comment]
@chickenlj 如果是条件路由，group只能是dubbo吗？

**Comment by chickenlj** [comment]
> 目录是:/configCenterGroup/config/demo-consumer.condition-router

Admin写入的目录应该缺少group的，需要继续确认一下

**Comment by WhaleCloud-platform** [comment]
@tswstarplanet zk。        @chickenlj 谢谢。还有group只能是默认值dubbo吗？

**Comment by chickenlj** [comment]
@WhaleCloud-platform 能留个钉钉/微信联系方式么?

**Comment by WhaleCloud-platform** [comment]
@chickenlj 钉钉号：jsismvf     正好还有几个问题需要确认下，谢谢。

**Comment by challengeof** [comment]
同样遇到了这个问题，dubbo-admin 使用master自行编译，dubbo使用是2.7.3，调试发现dubbo-admin写入没有问题，是dubbo在读取condition rule时候应用名称错误（dubbo-admin写入时使用provider application name dubbo读取时使用consumer application name）导致从zk读取结果为null，我会修复这个问题！ @chickenlj

**Comment by chickenlj** [comment]
condition router 用 consumer 应用名去订阅，我觉得是对的，应该是 admin 那边的写入需要修改才对？

**Comment by challengeof** [comment]
我们现在所有的路由规则都是基于服务也就是提供者来设置，只有应用路由需要基于consumer来设置么？

**Comment by yeahhao** [comment]
设置某个应用的黑白名单，出现同样问题，黑白名单设置肯定是对于提供者而设置的，写入的肯定是provider，而dubbo只读取consumer，规则始终无法生效。@chickenlj

**Comment by yeahhao** [comment]
条件路由，动态配置的功能都存在相同问题，2.7版的规则配置没有生效，没有被读取到。@chickenlj

**Comment by zziawan** [comment]
读取到也没有效果，我修改了dubboadmin。比如服务禁用，启动的时候会报没有provider，如果运行中禁用provider 没有任何效果。。。dubbo 2.7.3
