### ISSUE TITLE
nacos registry doesn't work if simplified registration is enabled.

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#4780]
If enable simplified registration for nacos:

```xml
<dubbo:registry address="nacos://localhost:8848" simplified="true"/>
```
Then **providers::::** is registered on nacos for the service name, which is apparently unexpected.

**Comment by beiwei30** [comment]
see https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistry.java#L457

**Comment by jimgreat** [comment]
https://github.com/apache/dubbo/issues/4621

**Comment by beiwei30** [comment]
cool, then I will close this issue. dup of #4621
