### ISSUE TITLE
Use generic invocation via API , lost "version" value

### ISSUE THREAD

**Issue by z529192557** [apache/dubbo#4784]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: MAC OX 10.14.5
* Java version: 1.8

### Steps to reproduce this issue

1. Use GenericService by API,  assign the version is 1.0.0.test.qa.st
![image](https://user-images.githubusercontent.com/9245774/62794432-aab99e00-bb06-11e9-9422-8317c64374b1.png)

2. breakpoint at DubboInvoker.doInvoke
3. check the DubboInvoker.version = 0.0.0 
![image](https://user-images.githubusercontent.com/9245774/62794513-e2284a80-bb06-11e9-878a-ab54d420d57c.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
In the instance of DubboInvoker，the version should be  1.0.0.test.qa.st
### Actual Result
In the instance of DubboInvoker，the version’s value actully is  default value,0.0.0
### Cause
this method : "ClusterUtils.mergeUrl" at line 87 ,remove the version key, so lost the version's value

**Comment by z529192557** [comment]
same as "group",  "ClusterUtils.mergeUrl" at line 84, remove the group key , so lost the group value

**Comment by tswstarplanet** [comment]
Would you please submit a pr to fix it ?

**Comment by z529192557** [comment]
> Would you please submit a pr to fix it ?
OK，I submit a pr to fix it，

**Comment by z529192557** [comment]
the modify in the issues https://github.com/apache/dubbo/issues/4525 leads to this problem，I just fix GROUP_KEY and VERSION_KEY，
- when consumer has theirs value，and provider dose not have， use the consumer's value
- when consumer does not have theirs value，and provider has value， use the provider's value

**Comment by beiwei30** [comment]
@z529192557 but I tried  it on main branch, but failed to reproduce.

**Comment by beiwei30** [comment]
> @z529192557 but I tried it on main branch, but failed to reproduce.

I didn't realize your test is direct invocation, pls. ignore my previous comment.

**Comment by z529192557** [comment]
> test

Yes，it‘s direct invocation，only in direct invocation via API， can reproduce.

**Comment by z529192557** [comment]
> > @z529192557 but I tried it on main branch, but failed to reproduce.
> 
> I didn't realize your test is direct invocation, pls. ignore my previous comment.

Yes，it‘s direct invocation，only in direct invocation via API， can reproduce.
