### ISSUE TITLE
[Problems]Conflicts in application level router

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#4791]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-SNAPSHOT
* Operating System version: MacOS
* Java version: java11

### Problems

1.When we create a application level condition router, we must set the application with the **provider application**'s name, because dubbo-admin will query if the application have exported service.

2.But the router is used by **consumer application**, so the consumer application will use its application name to query router rules. So the rules will not be queried and executed.

I think the solution can be:
When we configure config-center in consumer application, can add a parameter called '**router.apps**' or any other.
the value of router.apps should be **several provider application names**. When get different provider application router rules, we need to **split the router.apps value** add query each other's router rules.

**Comment by complone** [comment]
What do you mean by adding the rules in the` ConditionRouterRule` to a new variable in `configCenterConfig`?

**Comment by tswstarplanet** [comment]
> What do you mean by adding the rules in the` ConditionRouterRule` to a new variable in `configCenterConfig`?

No, rules are stored in config center

**Comment by beiwei30** [comment]
@tswstarplanet I am afraid I don't fully understand the problem you describe. Would you mind take a look at https://github.com/apache/dubbo-samples/blob/master/dubbo-samples-governance/dubbo-samples-configconditionrouter/src/main/java/org/apache/dubbo/samples/governance/ZKTools.java#L55?

**Comment by tswstarplanet** [comment]
@beiwei30 Yes, I have look it. 
Yes, the router rules can be set to the zookeeper config center. But the problem is that when we create **application level router rule** by **dubbo-admin**, the **specified application** is an application that acts a **provider**. But the rules will be used by applications that are **consumers**. And when consumers subscribe the application level router rules, they use **their own application names**. So they can not get the rules.
