### ISSUE TITLE
dubbo+nacos服务发现bug

### ISSUE THREAD

**Issue by supercocoa** [apache/dubbo#4793]
### Environment

* Dubbo version: 2.7.3 + nacos 1.1.0
* Operating System version: linux/mac
* Java version: 1.8

### Steps to reproduce this issue

1. 根据[文档](http://dubbo.apache.org/zh-cn/docs/user/configuration/api.html)通过代码使用dubbo
2. 在机器X启动A服务provider
3. 在机器X启动consumerA1，timeout参数为3000，目标是服务A
4. 在step3的同一进程启动consumerA2，timeout参数为8000，目标也是服务A
5. 下线机器X的A服务provider，上线机器Y的A服务provider
6. 通过consumerA2调用服务A还是去已近下线的机器X的A服务provider，连不通，即没有感知到服务上下线，没有去连机器Y的服务Aprovider

debug调试源码发现是`NacosRegistry`的`subscribeEventListener`会校验serviceName，同一serviceName只能往NamingService/EventDispatcher注册订阅一个lisnter(consumer)，虽然EventDispatcher本身可以一个key加多个listener，看看NacosRegistry是不是这块是不是有bug

```java 
//NacosRegistry.java
    private void subscribeEventListener(String serviceName, final URL url, final NotifyListener listener)
            throws NacosException {
        if (!nacosListeners.containsKey(serviceName)) {
            EventListener eventListener = event -> {
                if (event instanceof NamingEvent) {
                    NamingEvent e = (NamingEvent) event;
                    notifySubscriber(url, listener, e.getInstances());
                }
            };
            namingService.subscribe(serviceName, eventListener);
            nacosListeners.put(serviceName, eventListener);
        }
    }
```

``` java 
//EventDispatcher.java
    public void addListener(ServiceInfo serviceInfo, String clusters, EventListener listener) {

        NAMING_LOGGER.info("[LISTENER] adding " + serviceInfo.getName() + " with " + clusters + " to listener map");
        List<EventListener> observers = Collections.synchronizedList(new ArrayList<EventListener>());
        observers.add(listener);

        observers = observerMap.putIfAbsent(ServiceInfo.getKey(serviceInfo.getName(), clusters), observers);
        if (observers != null) {
            observers.add(listener);
        }

        serviceChanged(serviceInfo);
    }
```

### Expected Result

consumerA2可以连接到正确机器Y的A服务provider

### Actual Result

consumerA2可以连接到下线机器X的A服务provider

**Comment by tswstarplanet** [comment]
你下线提供者是在nacos把配置删除，还是直接把那个生产者进程关掉啊？

**Comment by supercocoa** [comment]
关掉provider进程 @tswstarplanet

**Comment by tswstarplanet** [comment]
I have found the reason. I will submit a pr to fix it.

**Comment by cvictory** [comment]
https://github.com/apache/dubbo/pull/4802

**Comment by supercocoa** [comment]
换了2.7.4.1问题依然存在  @tswstarplanet @beiwei30

**Comment by webeasymail** [comment]
dubbo 2.7.8 依然存在这个问题
