### ISSUE TITLE
GenericService genericService = ReferenceConfigCache.getCache().get(reference) 耗时26s

### ISSUE THREAD

**Issue by zlba111** [apache/dubbo#4794]

**Comment by zlba111** [comment]
GenericService genericService = ReferenceConfigCache.getCache().get(reference);
耗时26秒，时间太长了，怎么优化？

**Comment by complone** [comment]
> GenericService genericService = ReferenceConfigCache.getCache().get(reference);
> 耗时26秒，时间太长了，怎么优化？

Https://github.com/apache/dubbo/issues/1293
Please see here, the official recommendation to get ReferenceConfig, and ReferenceConfigCache is only a reference for user implementation

**Comment by zlba111** [comment]
> > GenericService genericService = ReferenceConfigCache.getCache（）。get（reference）; 
> > 耗时26秒，时间太长了，怎么优化？
> 
> [https://github.com/apache/dubbo/issues/1293](Https://github.com/apache/dubbo/issues/1293)
> 请看这里，获取ReferenceConfig的官方建议，而ReferenceConfigCache只是用户实现的参考

这并不能解决我的问题，这个性能为啥这么慢
