### ISSUE TITLE
官方博客中介绍SPI文章中存在一处英文版单词拼写错误

### ISSUE THREAD

**Issue by gloryofme** [apache/dubbo#4800]
http://dubbo.apache.org/en-us/docs/dev/SPI.html 中的一句话： "To extend Dubbo Protocol, placee a text file in the extension jar file: " ，其中的单词“placee”应该是拼写错误吧，是否应该修改为“palce”。

**Comment by CrazyHZM** [comment]
Please submit an issue or PR under this project to fix it.
https://github.com/apache/dubbo-website
