### ISSUE TITLE
如果禁用org.apache.dubbo.rpc.filter.ExceptionFilter

### ISSUE THREAD

**Issue by yyb1994** [apache/dubbo#4801]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows10
* Java version: 1.8

### Steps to reproduce this issue

1. 我想禁用org.apache.dubbo.rpc.filter.ExceptionFilter，使用自已定义的异常过滤器，以便使自定义的异常可以在customer方捕捉到，我现在的做法是修改了dubbo源码包META-INF\dubbo\internal\org.apache.dubbo.rpc.Filter下面的exception=com.seals.web.conf.DubboExceptionFilter，直接换成了自己的filter，但这样似乎不太友好，请问有其它的解决方案么

**Comment by kexianjun** [comment]
pls refer http://dubbo.apache.org/en-us/docs/dev/impls/filter.html,use - to delete the extension you want to remove.

**Comment by yyb1994** [comment]
> 请参阅http://dubbo.apache.org/en-us/docs/dev/impls/filter.html,use - 删除要删除的扩展名。

已经解决问题，非常感谢

**Comment by qixiaobo** [comment]
use -

**Comment by qixiaobo** [comment]
So never named your filter default 
-default stands for excluding all default filters
