### ISSUE TITLE
dubbo not support qos port configuration

### ISSUE THREAD

**Issue by SparkandScala** [apache/dubbo#4805]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Mac
* Java version: 1.8

### Steps to reproduce this issue

1. does the dubbo 2.7.3 version not support config qos port in the properties?
i set the configuration as follow:
dubbo.protocol.port=2345
dubbo.qos.enable=true
dubbo.qos.port=33333
dubbo.qos.accept.foreign.ip=false

it is not working, and i found the QosConstants class in the package org.apache.dubbo.qos.common; the default port is 22222, can not change.

**Comment by Moriadry** [comment]
https://github.com/apache/dubbo/issues/3958 
try to use `dubbo.application.qos-enable=true` config, if still not work, you can give a feedback here.

**Comment by lovepoem** [comment]
Please refer the doc :
http://dubbo.apache.org/en-us/blog/introduction-to-dubbo-qos.html

Create a dubbo.properties file in this directory src/main/resources in your
project, and copy the following codes into it:

dubbo.application.qos.enable=true
dubbo.application.qos.port=33333
dubbo.application.qos.accept.foreign.ip=false



myPrecious <notifications@github.com> 于2019年8月13日周二 下午7:54写道：

**Comment by SparkandScala** [comment]
hi, thank you your help, i find the configuration is working, as follows:
dubbo.application.qosEnable=true
dubbo.application.qosPort=33333
dubbo.application.qosAcceptForeignIp=false

**Comment by lovepoem** [comment]
> hi, thank you your help, i find the configuration is working, as follows:
> dubbo.application.qosEnable=true
> dubbo.application.qosPort=33333
> dubbo.application.qosAcceptForeignIp=false

ok
