### ISSUE TITLE
如何改变genericService.$invoke里面传的参数不需要传参数类型

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo#4814]
如果我想实现调用genericService.$invoke(methodName, new String[]{}, new Object[]{})
里面传的参数类型设置为null，为：genericService.$invoke(methodName, null, new Object[]{})，通过修改底层哪部分代码能够实现。目前定位到了GenericFilter这个类。

**Comment by tswstarplanet** [comment]
为什么一定要传null，空数组不就代表没有参数了吗？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
