### ISSUE TITLE
Is it appropriate about the suffix of ServiceAnnotationBeanPostProcessor class name?

### ISSUE THREAD

**Issue by FisherLea** [apache/dubbo#4816]
I find a small flaw about the name of ServiceAnnotationBeanPostProcessor. The class ServiceAnnotationBeanPostProcessor is actually an implementation of BeanFactoryPostProcessor instead of BeanPostProcessor, but the name looks like an implementation of the BeanPostProcessor interface.
Thanks.

**Comment by tswstarplanet** [comment]
I think you are right.

**Comment by CrazyHZM** [comment]
Already fixed
