### ISSUE TITLE
dubbo-admin 规则路由保存路径和dubbo读取的不一致

### ISSUE THREAD

**Issue by wml7758** [apache/dubbo#4821]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.2,  dubbo-admin最新develop分支a21b125
* Operating System version: Ubuntu18.04
* Java version: 1.8

### Steps to reproduce this issue

1. 在dubbo-admin里建应用级规则路由。填写应用名时只能写provider的应用名(如demo-provider)
2. 查看zk，生的配置路径为：/dubbo/config/demo-provider/condition-router的Data中。
3. 跟踪consumer请求时的dubbo代码，发现在创建AppRouter时查找路径为消费者(如demo-consumer)的路径/dubbo/config/demo-consumer/condition-router。造成配置不生效。
4. 如果切换到dubbo2.7.3，consumer请求时生成AppRouter时读取ZK路径变为/dubbo/config/dubbo/demo-consumer.condition-router。所以无论2.7.2, 2.7.3 都和admin中配置的路径不一样。

**Comment by tswstarplanet** [comment]
duplicate to #4791

**Comment by WhaleCloud-platform** [comment]
zdubbo-admin存取规则时没有namespace概念。但是dubbo有。/${namespace}/config/${group}/..
所以 我把zdubbo-admin这块修改了。
