### ISSUE TITLE
how to use monitor in dubbo 2.7.3

### ISSUE THREAD

**Issue by SparkandScala** [apache/dubbo#4827]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Mac
* Java version: 1.8
* Dubbo-admin version: 0.2.0

### Steps to reproduce this issue
i install the dubbo-admin-0.2.0 for dubbo 2.7.3, but i can't get the metrics in the statics page.

i want to know how to get the metrics in the page.

**Comment by WhaleCloud-platform** [comment]
if you use XML configuration mode:
```xml
    <dubbo:metrics port="20880" protocol="dubbo" />
    <dubbo:provider filter="metrics" />

    <dubbo:metrics port="20880" protocol="dubbo"/>
    <dubbo:consumer filter="metrics" />
```
if you use BOOT configuration mode(2.7.4 support):
```properties
dubbo.provider.filter=metrics
dubbo.metrics.protocol=dubbo
dubbo.metrics.port=20880

dubbo.consumer.filter=metrics
dubbo.metrics.protocol=dubbo
dubbo.metrics.port=20880

```

**Comment by SparkandScala** [comment]
why the dubbo-admin show  "Metrics will release later"?
