### ISSUE TITLE
Prometheus support

### ISSUE THREAD

**Issue by eonezhang** [apache/dubbo#483]
would you like to support prometheus in this repo?

**Comment by linux-china** [comment]
个人认为， Dubbo支持metrics输出，而和Prometheus集成可以交给后续的框架集成，如Spring-Boot-Dubbo+Micrometer，只要采集到Dubbo的metrics数据，然后交给micrometer类似框架完成和Prometheus的集成。

**Comment by ralf0131** [comment]
Hi, I am planning to implement this feature. My plan is similar to @linux-china

**Comment by eonezhang** [comment]
@ralf0131  does @linux-china  support prometheus in dubbo now?

**Comment by linux-china** [comment]
@eonezhang  已经添加好啦，请看这里 https://github.com/linux-china/spring-boot-apache-dubbo    这个是基于Spring Boot 2.0的，2.0已经通过 http://micrometer.io/  完成对prometheus的集成啦。

**Comment by diecui1202** [comment]
@linux-china Great job.

**Comment by diecui1202** [comment]
@linux-china Could you contribute this work to dubbo ? We all expect that.
