### ISSUE TITLE
Caused by: java.net.UnknownHostException: ${dubbo.registry.address.id}   dubbo的xml占位符解析失败  dubbo从2.6.2升级到2.7.3出现

### ISSUE THREAD

**Issue by fengjianjun1** [apache/dubbo#4835]
dubbo 从2.6.2 升级到2.7.3之后，出现问题，dubbo的xml中占位符配置的数据无法解析，被认定为字符串

application.yml 中配置  dubbo.registry.address.id: zookeeper://127.0.0.1:2181

@SpringBootApplication
@EnableDubbo
@ImportResource("classpath:consumer.xml")
public class Application 

consumer.xml 中配置   <dubbo:registry address="${dubbo.registry.address.id}" default="false" id="idserver" />

怀疑是spring 的初始化尚未结束，dubbo就开始读取配置文件中的信息，导致占位符失效

**Comment by tswstarplanet** [comment]
这个问题我在dubbo-spring-boot-project里提了个pr

**Comment by JsonSong89** [comment]
同样发现这个问题了 现在有解决方案吗?

**Comment by fengjianjun1** [comment]
> 这个问题我在dubbo-spring-boot-project里提了个pr

我看到了这个pr 不过这个pr审核没通过么？说明2.7.3目前确实存在这个问题是么？

**Comment by complone** [comment]
可以考虑现在这里配个环境变量试试
![index](https://user-images.githubusercontent.com/20021404/63089479-96542600-bf8a-11e9-96e8-edd9ae371873.png)

**Comment by tswstarplanet** [comment]
> > 这个问题我在dubbo-spring-boot-project里提了个pr
> 
> 我看到了这个pr 不过这个pr审核没通过么？说明2.7.3目前确实存在这个问题是么？

ci passed

**Comment by fengjianjun1** [comment]
> 可以考虑先在这里配个环境变量试试
> ![index](https://user-images.githubusercontent.com/20021404/63089479-96542600-bf8a-11e9-96e8-edd9ae371873.png)
![image](https://user-images.githubusercontent.com/16314792/63137835-59c80f00-c00a-11e9-801f-3b1074ee310c.png)


并没有生效

**Comment by fengjianjun1** [comment]
> > > 这个问题我在dubbo-spring-boot-project里提了个pr
> > 
> > 
> > 我看到了这个pr 不过这个pr审核没通过么？说明2.7.3目前确实存在这个问题是么？
> 
> ci passed

我看到你的提交记录了，按照你的修改，把源码修改了一下，然后启动项目,结果依然是失败
![image](https://user-images.githubusercontent.com/16314792/63138445-21760000-c00d-11e9-80b5-e9af446c61f8.png)

**Comment by tswstarplanet** [comment]
@fengjianjun1 你再试下，之前那个有点问题，我后来修改过了

**Comment by Dong-2017** [comment]
我也遇到这个问题，临时用apollo外部配置覆盖dubbo config

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
