### ISSUE TITLE
[求助]dubbo 消费端返回null  查询服务端有正常返回

### ISSUE THREAD

**Issue by MtBoss** [apache/dubbo#4849]
Dubbo version: 2.6.2
 Java version: 1.8
 
A服务发送MQ消息，B服务消费 B服务中调用C服务dubbo接口（同步接口） 同步null ，查询C系统dubbo接口服务端查询有结果。 

我查询了下之前的issue 有提到线程传染。上述情况是否也属于线程传绕导致的呢。望各路大神解惑。谢谢~

**Comment by kexianjun** [comment]
看下 dubbo.consumer.cluster 配置是不是 failsafe

**Comment by MtBoss** [comment]
> 看下 dubbo.consumer.cluster 配置是不是 failsafe

您好，服务端并无异常，也未超时。

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
