### ISSUE TITLE
泛化调用，返回值增加的class字段，建议增加开关。

### ISSUE THREAD

**Issue by farliu** [apache/dubbo#4863]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: centos
* Java version: 1.8

### 需求
泛化调用，返回值增加的class字段，建议增加开关。

### 举例
在PojoUtils.java中，有两处建议怎么增加该开关，如下：
1. put "class" 字段
```
Map<String, Object> map = new HashMap<String, Object>();
history.put(pojo, map);
map.put("class", pojo.getClass().getName());
```

2. 根据条件remove "class" 字段
```
// when return type is not the subclass of return type from the signature and not an interface
if (!type.isInterface() && !type.isAssignableFrom(pojo.getClass())) {
    try {
        map = (Map<Object, Object>) type.newInstance();
        Map<Object, Object> mapPojo = (Map<Object, Object>) pojo;
        map.putAll(mapPojo);
        map.remove("class");
    } catch (Exception e) {
        //ignore error
        map = (Map<Object, Object>) pojo;
    }
} else {
    map = (Map<Object, Object>) pojo;
}
```

期待修改成以下代码：
1. put "class" 字段
```
Map<String, Object> map = new HashMap<String, Object>();
history.put(pojo, map);
if (keepGenericClass){  // to increase the switch for control generics
    map.put("class", pojo.getClass().getName());
}
```

2. 根据条件remove "class" 字段
```
// when return type is not the subclass of return type from the signature and not an interface
if (!type.isInterface() && !type.isAssignableFrom(pojo.getClass())) {
    try {
        map = (Map<Object, Object>) type.newInstance();
        Map<Object, Object> mapPojo = (Map<Object, Object>) pojo;
        map.putAll(mapPojo);
            if (keepGenericClass){  // to increase the switch for control generics
                map.remove("class");
            }
    } catch (Exception e) {
        //ignore error
        map = (Map<Object, Object>) pojo;
    }
} else {
    map = (Map<Object, Object>) pojo;
}
```

**Comment by qixiaobo** [comment]
I use fastjson with class exclude

far <notifications@github.com> 于 2019年8月18日周日 10:37写道：

**Comment by farliu** [comment]
> I use fastjson with class exclude far <notifications@github.com> 于 2019年8月18日周日 10:37写道：
> […](#)

Can you give an example?

**Comment by qixiaobo** [comment]
```java
 /**
     * remove specify class field refer to dubbo generic invoke
     */
    private static final SimplePropertyPreFilter CLASS_NAME_PRE_FILTER = new SimplePropertyPreFilter(HashMap.class);

    static {
        CLASS_NAME_PRE_FILTER.getExcludes().add("class");
    }
```


```java
JSON.toJSONString(result, CLASS_NAME_PRE_FILTER
```

**Comment by qixiaobo** [comment]
I just add this code to my generic invoke application to return json

**Comment by farliu** [comment]
> I just add this code to my generic invoke application to return json

the problem is solved with your code, but it is still recommended to add a switch.

**Comment by qixiaobo** [comment]
> > I just add this code to my generic invoke application to return json
> 
> the problem is solved with your code, but it is still recommended to add a switch.

You are right. But I think the dubbo  framework wants to make it easy for someone who wants class info. You can see you can only set this var at startup other than runtime.
