### ISSUE TITLE
2.7.3 使用Nacos作为服务中心的时候，服务如果没有配置group，会导致服务发现失败

### ISSUE THREAD

**Issue by evancyz** [apache/dubbo#4864]
hello，我使用Nacos作为注册中心

我注册了一个服务，这个服务没有配置group，在Nacos后台服务列表的URL是这样

服务注册： providers:com.xxx.api.service.xxxService:1.0.0
服务消费： consumers:com.xxx..api.service.xxxService:1.0.0:

![image](https://user-images.githubusercontent.com/22286097/63220180-dbf43700-c1b4-11e9-9837-48d06c0c5949.png)

消费者后面多了一个 ：，导致服务匹配不上

看起来是由于 2.7.3  版本 配置中心 重构导致的，从dubbo的这个Test上来看，这个是符合预期的吗？

```
 org.apache.dubbo.common.URLTest

@Test
    public void testGetColonSeparatedKey() {
        URL url1 = URL.valueOf("10.20.130.230:20880/context/path?interface=org.apache.dubbo.test.interfaceName&group=group&version=1.0.0");
        Assertions.assertEquals("org.apache.dubbo.test.interfaceName:1.0.0:group", url1.getColonSeparatedKey());

        URL url2 = URL.valueOf("10.20.130.230:20880/context/path?interface=org.apache.dubbo.test.interfaceName&version=1.0.0");
        Assertions.assertEquals("org.apache.dubbo.test.interfaceName:1.0.0:", url2.getColonSeparatedKey());

        URL url3 = URL.valueOf("10.20.130.230:20880/context/path?interface=org.apache.dubbo.test.interfaceName&group=group");
        Assertions.assertEquals("org.apache.dubbo.test.interfaceName::group", url3.getColonSeparatedKey());

        URL url4 = URL.valueOf("10.20.130.230:20880/context/path?interface=org.apache.dubbo.test.interfaceName");
        Assertions.assertEquals("org.apache.dubbo.test.interfaceName::", url4.getColonSeparatedKey());
    }
```
我给 `nacos` 和 `nacos-sync`项目都提了issue，不知道是谁的锅

nacos：alibaba/nacos#1712
nacos-sync：https://github.com/nacos-group/nacos-sync/issues/100

**Comment by tswstarplanet** [comment]
我在2.7.4-SNAPSHOT上试了一下，没有问题，你可以试一下

**Comment by evancyz** [comment]
2.7.4-SNAPSHOT 没有 release 吧 ？  能在生产上用么

**Comment by tswstarplanet** [comment]
> 2.7.4-SNAPSHOT 没有 release 吧 ？ 能在生产上用么

不建议上生产

**Comment by evancyz** [comment]
。。。那如果我想上nacos，那个版本比较合适呢？ 2.7.0  ？

**Comment by evancyz** [comment]
我们线上的服务 group都是空的，
看起来  现在的dubbo release版本，都没有修复这个问题
除了魔改一把，不然nacos上不了了

**Comment by tswstarplanet** [comment]
> 我们线上的服务 group都是空的，
> 看起来 现在的dubbo release版本，都没有修复这个问题
> 除了魔改一把，不然nacos上不了了

你们2.7.3之前用的是nacos作注册中心吗？有这个问题吗

**Comment by evancyz** [comment]
我们以前注册中心用的 zk 

这不想统一迁到nacos上嘛

线上nacos  和  nacos-sync  已经搭上去了 还没用

**Comment by complone** [comment]
> > 我们线上的服务 group都是空的，
> > 看起来 现在的dubbo release版本，都没有修复这个问题
> > 除了魔改一把，不然nacos上不了了
> 
> 你们2.7.3之前用的是nacos作注册中心吗？有这个问题吗

我想在这里看起来是必须要配置的

![index](https://user-images.githubusercontent.com/20021404/63245536-04526300-c293-11e9-8ccc-b48c0d334238.png)

**Comment by evancyz** [comment]
没有吧。。之前group可以为空的 ------------------ 原始邮件 ------------------
发件人: "windWheel"<notifications@github.com>
发送时间: 2019年8月19日(星期一) 下午3:10
收件人: "apache/dubbo"<dubbo@noreply.github.com>;
抄送: "Yanzhi Cai"<124920917@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [apache/dubbo] 2.7.3 使用Nacos作为服务中心的时候，服务如果没有配置group，会导致服务发现失败 (#4864)


  
我们线上的&#x670D;务 group都是空的，
 看起来 现在的dubbo release版本，都没有修复这个问题
 除了魔改一把，不然nacos上不了了
  
你们2.7.3之前用的是nacos作注册中心吗？有这个问题吗
  
我想在这里看起来是必须要配置的
 

 
&mdash;

**Comment by evancyz** [comment]
你好请问有解决方案吗？

**Comment by evancyz** [comment]
后来想了个方案 像zk里注册了两个服务：
```
       <dubbo:service interface="com.xxx.xx.api.service.XXXService" ref="xxxx" version="1.0.0"/>
       <dubbo:service interface="com.xxx.xx.api.service.XXXService" ref="xxxx" version="1.0.0" group="test"/>
```
在 zk 的 注册那边 注册的是两个服务
```
dubbo://10.xx.218.7:20779/com.xx.xx.api.service.XXService?xxx
dubbo://10.xx.218.7:20779/com.xx.xx.api.service.XXService2?xxx&group=test

```

然后用 `nacos-sync` 做同步的时候，都是ok的
项目启动的check也是ok的


可是调用的时候，用test的那个group，就报错了。估计也是服务重了，内部名字没匹配，绝望了，感觉不是很想用nacos的注册中心了

```
com.alibaba.dubbo.remoting.RemotingException: Not found exported service: test/com.xx.api.service.XXService:1.0.0:20779 in [test/com.piaoniu.xx.api.service.XXService2:1.0.0:20779, com.xx..api.service.XXService:1.0.0:20779], may be version or group mismatch 
```

**Comment by evancyz** [comment]
没人回复嘛。。。

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosServiceName.java#L205

**Comment by fengyi1993** [comment]
我也遇到这个问题，原来dubbo版本2.6.5，升级到2.7.3，stable和sit环境都配了组名，生产环境没有组名，导致生产环境dubbo注册的时候也多了个冒号，dubbo调用失败。我是查nacos生产的日志发现了这个问题，然后找到这篇帖子，我想请教一下，这个最终结局方案是啥？

**Comment by AlbumenJ** [comment]
> 我也遇到这个问题，原来dubbo版本2.6.5，升级到2.7.3，stable和sit环境都配了组名，生产环境没有组名，导致生产环境dubbo注册的时候也多了个冒号，dubbo调用失败。我是查nacos生产的日志发现了这个问题，然后找到这篇帖子，我想请教一下，这个最终结局方案是啥？

升级到 2.7 的最新版本看下呢
