### ISSUE TITLE
在windows连接zookeeper出现文件写入异常

### ISSUE THREAD

**Issue by ZhouZiHe** [apache/dubbo#4871]
在 2.7.3 这个版本中,在windows下连接zookeeper时,会出现写入文件异常,目测是文件路径写入不对
![image](https://user-images.githubusercontent.com/20511319/63245245-429b5280-c292-11e9-986a-bf95c894d98f.png)

**Comment by ZhouZiHe** [comment]
初始化元数据缓存的时候是不是应该做一个兼容
![image](https://user-images.githubusercontent.com/20511319/63247318-585f4680-c297-11e9-92f0-6d25a80258e9.png)

**Comment by ZhouZiHe** [comment]
![image](https://user-images.githubusercontent.com/20511319/63247563-e804f500-c297-11e9-9a25-52bed7d91a70.png)

**Comment by ZhouZiHe** [comment]
![image](https://user-images.githubusercontent.com/20511319/63264010-9c187700-c2bc-11e9-9b5c-70ecc1b5f000.png)
关注这个地方

**Comment by htynkn** [comment]
Close via #5158
