### ISSUE TITLE
在使用配置中心动态更新配置的时候,无法更新多层配置

### ISSUE THREAD

**Issue by ZhouZiHe** [apache/dubbo#4882]
使用apollo 作为配置中心的时候,目前无法进行配置map属性
![image](https://user-images.githubusercontent.com/20511319/63263546-85255500-c2bb-11e9-954c-4cf24aec90f4.png)
在源码中判断set方法的时候进行自动去除这个方法
![image](https://user-images.githubusercontent.com/20511319/63263499-60c97880-c2bb-11e9-94ec-173bddee0078.png)

**Comment by ZhouZiHe** [comment]
类似于parameters这类参数应该是无法通过配置中心进行动态配置的

**Comment by mzorro** [comment]
The other day I was just considering this.
If we are gonna support overriding of `Map` properties, we should consider it's format in config center, I was thinking something like `a=1&b=2&c=3`, then we can parse it with `URL.valueOf("?"+value).getParameters()`.
I'll try to make a PR this week.
