### ISSUE TITLE
FailedSubscribedTask 是如何重试的呢？

### ISSUE THREAD

**Issue by benyVip** [apache/dubbo#4897]
版本是2.6.5的版本
FailedSubscribedTask 这个任务是会往订阅失败的refer的代码插入一个url，表示是这个订阅失败，但是如何排查到是有在retry的呢？貌似找了日志也一直没有找到，请问如何开启这个retry的日志呢？

**Comment by LiZhenNet** [comment]
在最新的版本中，retry 是没有日志的，具体还是看订阅失败(Failed to subscribe)的错误日志

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
