### ISSUE TITLE
Rest 协议的Dubbo-Attachments格式限制

### ISSUE THREAD

**Issue by SamPeng87** [apache/dubbo#4898]
We use Rest protocol more year.

最近我们尝试使用skywalking作为调用跟踪，结果发现rest协议下的Dubbo-Attachments有限制

"The attachments of RpcContext must not contain  , or = "

我认为这应该是一个bug。没有考虑传入的Attachments的格式。只是简单的用,和=进行分割。
通常在外部调用可能只是像getAttachments().put("contextData", contextDataStr);这样去调用。DataStr的格式只有在rest的时候才有限制。这是不合理的。

异常抛出在
dubbo-rpc/dubbo-rpc-rest/src/main/java/org/apache/dubbo/rpc/protocol/rest/RpcContextFilter.java

是应该修复这个问题吗？

刚和Skywalking的人讨论了一会，认为是协议层不应该有格式上面的限制。

https://github.com/apache/skywalking/issues/3294

**Comment by wu-sheng** [comment]
SkyWalking header is using BASE64 encoding, w/ leveraging the Dubbo Attachments. Recently we received the feedback about the limit in Dubbo REST. 

Would Dubbo team explain why have this limit? And is there any possibility to remove it?

**Comment by tswstarplanet** [comment]
I think it can be improved, I will submit a pr.
