### ISSUE TITLE
对于dubbo2.7.x，如果zk设置了Acl，默认配置中心设置会导致服务注册失败

### ISSUE THREAD

**Issue by childepeng** [apache/dubbo#4917]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue
场景：
1、zookeeper针对dubbo节点设置了访问控制；
2、dubbo使用curator作为zk客户端；
3、当我从2.6.3升级到2.7.3之后发现，服务无法在zookeeper里注册，异常提示： NoAuth

问题分析：
之后通过文档，发现dubbo 2.7 之后增加了配置中心和元数据中心，并默认采用服务注册中心的配置；但是对于username/password属性并没有继承使用； 导致服务注册过程中提示没有权限。

疑问？
配置中心和服务注册中心的配置是独立的， 但实际上配置中心的如果不设置zk的用户密码，却会导致服务注册失败；

**Comment by 13567436138** [comment]
最新版username password已经继承了啊

**Comment by htynkn** [comment]
similar to #5076
But code is in master branch, not release yet.

**Comment by zhaoyuguang** [comment]
@childepeng  你可以试试这种方式解决
```
<dubbo:registry
            address="zookeeper://username:pwd@ip:port"
            group="xxx"/>
```
