### ISSUE TITLE
Check deploy environment when invoke dubbo service by telnet

### ISSUE THREAD

**Issue by tswstarplanet** [apache/dubbo#4918]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

For the sake of security, invoking dubbo service by telnet should only be allowed when application is deployed in dev or test environment.

**Comment by guohao** [comment]
Pls close this issue @qinliujie
