### ISSUE TITLE
Problem of dubbo.xsd file in dubbo2.5.6.jar

### ISSUE THREAD

**Issue by alexander-wong-tech** [apache/dubbo#4928]
### Environment

* Dubbo version: 2.5.6
* Operating System version: Windows10
* Java version: 1.8.0_221

### Steps to reproduce this issue

1. Document description 2.5.6 supports netty4.
![image](https://user-images.githubusercontent.com/6479081/63580542-a17d0680-c5c7-11e9-9ec0-a3150cb3cd6e.png)

2. I can't find the parameter client from dubbo.xsd in dubbo2.5.6.jar.
![image](https://user-images.githubusercontent.com/6479081/63581082-c4f48100-c5c8-11e9-991d-11173f3ff712.png)

3. I can find the parameter client from dubbo.xsd in dobbo2.5.7.jar.
![image](https://user-images.githubusercontent.com/6479081/63581152-f2412f00-c5c8-11e9-8cd1-e4c0e9c7943e.png)

### I hope:
1. Please update the document, Describe it in more detail.
2. Modify the dubbo.xsd file in dubbo2.5.6.jar, add parameter "client".

Looking forward to official reply, Thank you very much.

**Comment by CrazyHZM** [comment]
2.5.x version is no longer supported, it is recommended to upgrade to the new version.
