### ISSUE TITLE
dubbo consume升级到2.7.3后启动报错

### ISSUE THREAD

**Issue by Tank-zhu** [apache/dubbo#4946]
### dubbo 环境：
consume 2.7.3  
provider 2.6.5 
注册中心nacos 1.1.3

### 问题说明：
consume 没有升级时 2.6.5 启动正常调用provider
当consume升级后，启动时报找不到老服务。然后我将provider升级到2.7.3
consume又能正常调用provider 。

## 求大佬讲解一下

**Comment by web1992** [comment]
配置是怎么配的？帖出来看看

**Comment by Tank-zhu** [comment]
哪一部份配置。如果是配置有问题。那为何相同版本可以调用。不同版本就不能调用呢。我认为是注册中心元数据不一致导致的。

**Comment by Tank-zhu** [comment]
而且我换成zk为注册中心后。不同版本的相互调用是没有问题的。唯独这个nacos注册中心不能相互调用。
