### ISSUE TITLE
Adaptive通过injectExtension注入set属性时,如果存在循环依赖,会创建很多对象直到栈溢出退出

### ISSUE THREAD

**Issue by ououtt** [apache/dubbo#4959]
<img width="216" alt="屏幕快照 2019-08-28 15 16 29" src="https://user-images.githubusercontent.com/20450037/63834009-e24d9480-c9a6-11e9-97cf-6ad6daea94f4.png">
<img width="215" alt="屏幕快照 2019-08-28 15 16 37" src="https://user-images.githubusercontent.com/20450037/63834023-e7aadf00-c9a6-11e9-962c-35604dec03d8.png">
像这样的两个spi接口,在获取Adaptive实现时,由于是先调用injectExtension方法注入再暴露,所以会出现循环依赖问题,在创建A时依赖B,创建B时又依赖A,但此时A对象虽已生成,但还未放到缓存中,于是又去创建,最终创建很多个对象,直到栈溢出被catch.这里修改成先暴露再通过set注入会更好.

**Comment by CrazyHZM** [comment]
Circular dependency is not a very elegant way of coding, this will remain the same for the time being.
