### ISSUE TITLE
Dubbo service grouping registered with nacos, the grouping is not valid

### ISSUE THREAD

**Issue by Python-IBM** [apache/dubbo#4965]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows7
* Java version: 1.8

### Steps to reproduce this issue

1.  Register services into two different groups
<dubbo:registry  address="nacos://localhost:8848" group="group-dev-1"/>
<dubbo:registry  address="nacos://localhost:8848" group="group-dev-2"/>
2. Groups are invalid and services are transferred to each other.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

I want the same service to be registered in different groupings, and service invocations are isolated, rather than invoking each other.

### Actual Result

Different groupings, Dubbo consumption call or the same service, did not achieve service grouping isolation

**Comment by tswstarplanet** [comment]
Even a dubbo service is registered to different group of the same registry, the service is still the identical one.

**Comment by Python-IBM** [comment]
> Even a dubbo service is registered to different group of the same registry, the service is still the identical one. So the client will invoke the same one.

If I use nacos, I want to register the same service to separate calls in different groups. How can I do that?

**Comment by 13567436138** [comment]
用zookeeper可以生效，nacos不生效<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

    <dubbo:application name="demo-provider"/>

    
    <dubbo:registry  id="group1" address="zookeeper://127.0.0.1:2181" group="group1"/>
    <dubbo:registry  id="group2" address="zookeeper://127.0.0.1:2181" group="group2"/>

    <dubbo:protocol name="dubbo" port="20887"/>

    <bean id="demoService1" class="com.mark.i4970.providor.DemoServiceImpl">
        <property name="id" value="demo1"/>
    </bean>
    <bean id="demoService2" class="com.mark.i4970.providor.DemoServiceImpl">
        <property name="id" value="demo2"/>
    </bean>
    <dubbo:service interface="com.mark.i4970.api.DemoService"  registry="group1" ref="demoService1"/>
    <dubbo:service interface="com.mark.i4970.api.DemoService" registry="group2" ref="demoService2"/>

</beans>

``
result: Hello world, response from provider: 192.168.198.1:20887demo1
result: Hello world, response from provider: 192.168.198.1:20887demo2
`<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">

    <dubbo:application name="demo-consumer"/>

   
    <dubbo:registry id="group1" address="zookeeper://127.0.0.1:2181" group="group1"/>
    <dubbo:registry  id="group2" address="zookeeper://127.0.0.1:2181" group="group2"/>


    <dubbo:reference id="demoService1" check="false" interface="com.mark.i4970.api.DemoService" registry="group1"/>
    <dubbo:reference id="demoService2" check="false" interface="com.mark.i4970.api.DemoService" registry="group2"/>

</beans>
`

**Comment by CrazyHZM** [comment]
@13567436138 I ran with your configuration, it is OK.
