### ISSUE TITLE
注册Filter的Eeception 被spring的DataBuilder默认的ErrorProcessor 吃掉了没有抛出和处理

### ISSUE THREAD

**Issue by ShenFeng312** [apache/dubbo#4967]
### Environment

* Dubbo version: 2.7.2
* Java version:1.8

注册Filter时 如果filter没有加在org.apache.dubbo.rpc.Filter 目录下回抛出 new IllegalStateException("No such extension " + v + " for " + property + "/" + type.getName()) 但是这个好像被springDataBinder 默认的ErrorProcessor 给吃掉了 导致报错没有反馈到用户应该添加一个自定义的ErrorProcessor 解决这个问题

调试时的异常
org.springframework.beans.MethodInvocationException: Property 'filter' threw exception; nested exception is java.lang.IllegalStateException: No such extension com.xiaoxinyun.answerweb.config.dubbo.filter.AddTokenFilter for file/org.apache.dubbo.rpc.Filter

**Comment by tswstarplanet** [comment]
不用侵入到dubbo的源码就可以扩展的，你在自己项目的resources目录下面添加spi文件了吗？

**Comment by ShenFeng312** [comment]
> 不用侵入到dubbo的源码就可以扩展的，你在自己项目的resources目录下面添加spi文件了吗？

谢谢~问题已经解决~我是在sesources 和注解中使用的filter不一致时发生了这个问题 但是为什么dubbo 没有给我warning 或者error希望在以后的版本中你们能添加给一个ErrorProcessor来处理这个错误让使用者能够看到而不是用默认的ErrorProcessor

**Comment by tswstarplanet** [comment]
个人觉得，你说这个似乎没有必要吧，这里并没有什么需要自定义的错误处理逻辑啊
