### ISSUE TITLE
ResponseCallback 为什么不支持多个？

### ISSUE THREAD

**Issue by glmapper** [apache/dubbo#4968]
2.6.x 版本中使用 ResponseCallback 实现异步回调的 callback ，但是发现在 ResponseCallback 在  DefaultFuture 中是非数组属性，这样也就意味着，自己扩展的 ResponseCallback 存在覆盖或者被覆盖的情况（FutureFilter 中设置到ResponseCallback ）。

**Comment by 13567436138** [comment]
能把你的代码贴出来么？

**Comment by 13567436138** [comment]
貌似只能有一个callback，是否可以用责任链模式，将多个，串起来

**Comment by chickenlj** [comment]
ResponseFuture现在是只支持注册单个ResponseCallback实例，暂无支持更多实例的计划。请使用2.7.3及以上版本的CompletableFuture.
