### ISSUE TITLE
在消费端通过dubbo:annotation加载后，通过context.getBean("demoService")无法获取到对应的代理对象

### ISSUE THREAD

**Issue by xinweishao** [apache/dubbo#4970]
Dubbo version： 2.6.7

在消费端通过dubbo:annotation加载后，在main方法中通过context.getBean("demoService")无法获取到对应的代理对象；必须通过其他的对象，在其他的对象内，通过@Reference引入后才能获取，这个地方是不是有点问题。

<dubbo:annotation package="xxx.xx.xx" />

**Comment by xinweishao** [comment]
如果在xml中，用 <dubbo:reference id="demoService" check="false" interface="com.alibaba.dubbo.demo.DemoService"/>  这种形式也可以获取，就是通过<dubbo:annotation package="xxx.xx.xx" /> 就无法获取

**Comment by 13567436138** [comment]
消费端肯定要加注解@reference获取的啊

**Comment by ouyangnengda** [comment]
Let me say my opinion.

- About your dubbo version. First,dubbo'version include:2.7.1 || 2.7.0 || 2.6.6. But that didn't exist 2.6.7. You can visit dubbo‘s download web page. https://dubbo.apache.org/zh-cn/blog/download.html

- Second, I can get Object by <dubbo:annotation package="xxx.xx.xx"/> in Version 2.7.3. But the Object always is org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationBeanPostProcessor@1e097d59. Unfortunately I do not know why.

consumer.xml
```xml
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd">
    <dubbo:application name="demo-consumer"/>
    <dubbo:registry address="zookeeper://127.0.0.1:2181"/>
    <dubbo:annotation id="demoService" package="cn.ouyangnengda.dubbo.DemoService.DemoService"/>
</beans>
```

DubboApplication.class

```java
public class DubboApplication {
    public static void main(String[] args) throws IOException {
        ApplicationContext applicationContext = SpringApplication.run(DubboApplication.class, args);
        System.out.println("Start consumer!");
        Object demoService = applicationContext.getBean("demoService");
        System.out.println(demoService.toString());
        System.in.read();
    }
}
```

Console Print out
```java 
Start consumer!
org.apache.dubbo.config.spring.beans.factory.annotation.ServiceAnnotationBeanPostProcessor@1e097d59
```

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
