### ISSUE TITLE
2.7.4预计什么时候发布

### ISSUE THREAD

**Issue by supercocoa** [apache/dubbo#4985]
RT
2.7.3的bugfix，2.7.4预计什么时候发布

**Comment by ACXNX** [comment]
可以看[这里](https://github.com/apache/dubbo-awesome/blob/master/slides/meetup/201908%40shanghai/1.%E5%88%98%E5%86%9B%20Dubbo%202.7.3_4%E7%89%88%E6%9C%AC%E6%96%B0%E7%89%B9%E6%80%A7%E5%8F%8A%E5%8F%91%E7%89%88%E8%AE%A1%E5%88%92%E4%BB%8B%E7%BB%8D.pdf)

**Comment by htynkn** [comment]
可以关注邮件列表(https://lists.apache.org/list.html?dev@dubbo.apache.org)，近期已经开始RC投票了

**Comment by CrisLi** [comment]
Any updates？
