### ISSUE TITLE
[dubbo-website] dubbo webstite(en version) have picture of Chinese tips

### ISSUE THREAD

**Issue by sonymoon** [apache/dubbo#4993]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Issue Detail
I have read [dubbo website](http://dubbo.apache.org/en-us/docs/dev/implementation.html).
And when I have reached  to `RPC details` section, I found that the picture has notes in Chinese. It is not international friendly since this page is not just for Chinese developers.

#### see the picture below
![image](https://user-images.githubusercontent.com/6781070/64228239-c8690000-cf18-11e9-83f3-b49ef834b81f.png)

BTW, If I am willing to contribute to the website, is there any way ?

**Comment by slievrly** [comment]
http://dubbo.apache.org/zh-cn/docs/developers/contributor-guide/new-contributor-guide_dev.html

**Comment by sonymoon** [comment]
> http://dubbo.apache.org/zh-cn/docs/developers/contributor-guide/new-contributor-guide_dev.html

Thanks!
