### ISSUE TITLE
ServiceBean 可以重复发布吗？（export() -> unexport() -> export()）

### ISSUE THREAD

**Issue by pinkdawn** [apache/dubbo#4994]
### Environment

* Dubbo version: 2.7.2
* Operating System version: win 10
* Java version: 1.8.0_191

### Steps to reproduce this issue

1. New a `ServiceBean`, 设置必要的其他属性
2. 调用 ServiceBean.export()
3. 调用 ServiceBean.unexport()
4. 再次调用 ServiceBean.export() 

### Expected Result

`ServiceBean`调用过 `unexport` 后，应该可以重新调用 `export` 再次发布。

### Actual Result

会报错 `The service xxxxx has already unexported!`。 
为什么 `ServiceBean` 有两个内部状态： exported  和  unexported ? 
一个 ServiceBean 只能被发布、重新发布一次？？
如果有需求，暂时停止发布某个ServiceBean，稍后再手工重新发布，这种需要要怎么处理呢？

**Comment by cdy1996** [comment]
可以通过nacos注册中心的下线和上线, 来实现对某个服务的下线和上线. 因为其实你只要注册中心不给提供对应的某个服务地址就可以了, 不需要让去调用dubbo的SerivceConfig的export和unexport去实现上下线,. 另外更简单的方式就是通过优雅的停机和重新启动也可以实现上下线.

**Comment by chickenlj** [comment]
通过 动态配置规则 或者 qos online/offline 来实现
