### ISSUE TITLE
how to config mutiple zookeeper registry？ No registry config found or it's not a valid config

### ISSUE THREAD

**Issue by huzhenpengssp** [apache/dubbo#4999]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows
* Java version: 1.8

### Steps to reproduce this issue
dubbo-spring-boot-starter: 2.7.3
application.properties
dubbo.registrys.cob1.address=zookeeper://127.0.0.1:2181
dubbo.registrys.cob2.address=zookeeper://127.0.0.1:2181

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
how to solve the problem

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
No registry config found or it's not a valid config! the registry config is<dubbo:registry valid ="false" zookeeperprotocol="false" prefix="dubbo.registry"
```

**Comment by CrazyHZM** [comment]
refer to it:
http://dubbo.apache.org/zh-cn/docs/user/demos/multi-registry.html

**Comment by chickenlj** [comment]
Try `dubbo.registries.cob1.address=xxx`

**Comment by joviqiao** [comment]
我tm不需要多注册中心！！！！妈卖批
