### ISSUE TITLE
dubbo:config-center timeout配置不生效

### ISSUE THREAD

**Issue by genvyday** [apache/dubbo#5001]
dubbo:config-center timeout在url里参数为config.timeout，转换时取的却是timeout

**Comment by CrazyHZM** [comment]
能否给个例子说明，并且说明是哪个版本。

**Comment by genvyday** [comment]
版本2.7.3
<dubbo:config-center timeout="10000" protocol="zookeeper" address="172.16.1.20"/>
timeout不生效
<dubbo:config-center protocol="zookeeper" address="172.16.1.20?timeout=10000"/>
timeout生效
