### ISSUE TITLE
service provider, netty worker线程执行效率问题

### ISSUE THREAD

**Issue by toplifangkai** [apache/dubbo#5010]
如果只有一个consumer，provider的NioEventLoopGroup中是否只有一个worker线程在处理？

**Comment by CodingSinger** [comment]
不一定吧？如果有多个连接的话，就可能会分配给多个线程管理

**Comment by gnocuohz** [comment]
NioEventLoop 注册多个channel，处理事件时就是单线程执行的。所以不推荐传大包，会阻塞 IO 线程。所以处理完 IO 后，AllChannelHandler 会分发到业务线程

**Comment by sunshujie1990** [comment]
> > NioEventLoop 注册多个channel，处理事件时就是单线程执行的。所以不推荐传大包，会阻塞 IO 线程。所以处理完 IO 后，AllChannelHandler 会分发到业务线程
> 
> 但是我看我们日志，总是只有190到200这是个线程在活跃，虽然是ALL设置的，但是其他的线程都被IO消息吃了么

基于Netty4
1.服务端io线程数可配置，默认也不是单线程的
Math.min(Runtime.getRuntime().availableProcessors() + 1, 32)
2.服务端业务线程跑不满我觉得有以下可能性
   2.1服务执行太快了，用不了这么多线程
   2.2线程池配了queue，queue不满不会创建新线程。可以把queue配置为0或者使用eager类型的ThreadPool
