### ISSUE TITLE
can dubbo provider mark more than one tag?

### ISSUE THREAD

**Issue by CodingSinger** [apache/dubbo#5014]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: 10.12.6
* Java version: 1.8

now dubbo provider can only have a tag, assuming that consumer with a tag A or Tag B can send request to provider with tagA and tagB by tag-router.

**Comment by chickenlj** [comment]
Currently, it's not supported, but we are working on this.
