### ISSUE TITLE
should revert all default values from org.apache.dubbo.config.AbstractServiceConfig

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#5015]
We should revert all default values from org.apache.dubbo.config.AbstractServiceConfig, otherwise the explicit configuration from upper level config, say protocol config, will not work.

**Comment by sonymoon** [comment]
> We should revert all default values from org.apache.dubbo.config.AbstractServiceConfig, otherwise the explicit configuration from upper level config, say protocol config, will not work.

which attribute do you mean. I noticed two: `deprecated` and `dynamic`  have default value

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
