### ISSUE TITLE
a suggust for mocking

### ISSUE THREAD

**Issue by zhoujiaping** [apache/dubbo#5016]
In our projects,it depends on dubbo framework.
then when we  were testing, we found there are some way to mock or stub.
but both of them need do a lot of work(create lots of class, and implements methods).
and they are not dynamic, when we change some code, we must restart module.
so, i create a project aim to solve this problem(in fact, not only for dubbo mock/stub).
i wish your provide a new way (refers to https://github.com/zhoujiaping/java-agent https://github.com/zhoujiaping/java-agent-web) to mock/stub.
thanks!

**Comment by chickenlj** [comment]
Looks great, would you please provide a demo of how to use this project to mock Dubbo.

**Comment by zhoujiaping** [comment]
ok，

https://github.com/zhoujiaping/java-agent




https://github.com/zhoujiaping/java-agent-web





there is a sample for dubbo


---Original---

**Comment by chickenlj** [comment]
Please provide more detailed information of how this projct works for Dubbo. Then we can decide if it suits for the community.

**Comment by chickenlj** [comment]
Reopen if necessary.
