### ISSUE TITLE
2.7.4-SNAPSHOT无法在springboot用yml写dubbo.metrics.port

### ISSUE THREAD

**Issue by Armstjoh** [apache/dubbo#5022]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-SNAPSHOT
* Operating System version: win7
* Java version: 8

### Steps to reproduce this issue

1. 使用springboot，在application.yml无法使用
dubbo:
  metircs:
    port: 20880
    protocol: dubbo

**Comment by chickenlj** [comment]
Metrics related config needs to be registered into Spring to support usage like this. It's very likely not finished yet.
