### ISSUE TITLE
不定期出现Caused by: org.apache.dubbo.remoting.RemotingException: message can not send, be cause channel is closed. 

### ISSUE THREAD

**Issue by zhangdabaowudi** [apache/dubbo#5040]
* Dubbo version: 2.7.1
* Operating System version: Windows Server 2008 虚拟机
* Java version: 1.8

不定期出现Caused by: org.apache.dubbo.remoting.RemotingException: message can not send, be cause channel is closed. 一会自己能恢复，一会又出现，没有规律

**Comment by zhangdabaowudi** [comment]
有大神能帮忙吗

**Comment by zhangdabaowudi** [comment]
anybody can help ?

**Comment by liumin666** [comment]
我也遇到了这个异常 ，当服务集群中的一个服务挂掉后 注册中心的其他服务都会抛出这个异常

**Comment by lkj41110** [comment]
```
 @Override
    public void send(Object message, boolean sent) throws RemotingException {
        if (needReconnect && !isConnected()) {
            connect();
        }
        Channel channel = getChannel();
        //TODO Can the value returned by getChannel() be null? need improvement.
        if (channel == null || !channel.isConnected()) {
            throw new RemotingException(this, "message can not send, because channel is closed . url:" + getUrl());
        }
        channel.send(message, sent);
    }
```
一般会在连接后，在校验`  if (channel == null || !channel.isConnected())`之前，发现channel关闭了会提示这个错误。

**Comment by netman525** [comment]
message can not send, be cause channel is closed  本地noitfy已经更新/root/.dubbo/文件为provider B, 而调用的地址还是provider A， 这个A的地址还会在别的地方缓存吗?

nacos 注册中心， dubbo 版本 2.7.3

**Comment by peachyy** [comment]
还有就是 更新provider的时候 ，当更新完后 要等很长一会时间 consumer才能成功调用到provider。

**Comment by yaoqi** [comment]
2.7.0 偶尔也会有同样的问题

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
