### ISSUE TITLE
通过API方式发布Dubbo服务有空指针异常

### ISSUE THREAD

**Issue by hudaming1** [apache/dubbo#5047]
### Environment

* Dubbo version: 2.7.3
* Operating System version: Max OS
* Java version: 1.8.0_181

### Steps to reproduce this issue

当我使用Main方法，通过API发布Dubbo服务时，会提示空指针异常，通过追代码发现ServiceBean第346行applicationEventPublisher为null，因为在使用Dubbo的API发布服务时，我并没有监听Spring事件的需求，因此希望能对applicationEventPublisher增加非空判断，不要影响Export主流程，或者抛出更加友好的异常，而非NullPointerException。

**代码片段如下：**
`
import org.apache.dubbo.config.ApplicationConfig;
import org.apache.dubbo.config.ProtocolConfig;
import org.apache.dubbo.config.ProviderConfig;
import org.apache.dubbo.config.RegistryConfig;
import org.apache.dubbo.config.spring.ServiceBean;
import org.hum.practise.dubbo._service.TestService;
import org.hum.practise.dubbo._service.TestServiceImpl;

public class Test2 {

	public static void main(String[] args) {
	    ServiceBean<TestService> serviceBean = new ServiceBean<TestService>();
	    RegistryConfig registryConfig = new RegistryConfig("zookeeper://127.0.0.1:2181");
	    ProviderConfig provider = new ProviderConfig();
	    provider.setTimeout(1000);
	    serviceBean.setProvider(provider);
	    serviceBean.setApplication(new ApplicationConfig("huming"));
	    serviceBean.setInterface(TestService.class);
	    serviceBean.setRef(new TestServiceImpl());
	    serviceBean.setProtocol(new ProtocolConfig("dubbo", 20880));
	    serviceBean.setRegistry(registryConfig);
	    serviceBean.export();
	    System.out.println("server start!");
	}
}
`

**异常堆栈如下：**
`
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.config.spring.ServiceBean.publishExportEvent(ServiceBean.java:346)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:338)
	at org.hum.practise.dubbo.export.Test2.main(Test2.java:27)
`

谢谢

**Comment by LiZhenNet** [comment]
ServiceBean 是在spring 环境下使用的，你应该使用的是ServiceConfig

**Comment by AlbumenJ** [comment]
@hudaming1 Please try use `ServiceConfig`. 
`ServiceBean` is designed for Spring env.
If you have any question please feel free to reopen this issue.
