### ISSUE TITLE
服务端从2.6.0升级到2.7.1后，Version.getIntVersion报错，响应失败

### ISSUE THREAD

**Issue by chozee** [apache/dubbo#5048]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.0
* Operating System version: centos 6
* Java version: jdk 1.8

### Steps to reproduce this issue

1. 服务端dubbo 2.7 客户端使用2.6.0 由于集群原因升级到2.7之后zk的curator客户端会造成任务卡住，所以无法升级
2. ause: java.lang.NumberFormatException: For input string: ""
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.dubbo.common.Version.parseInt(Version.java:128)
	at org.apache.dubbo.common.Version.getIntVersion(Version.java:113)
	at org.apache.dubbo.common.Version.isSupportResponseAttachment(Version.java:102)

**Comment by qixiaobo** [comment]
```java
public static boolean isSupportResponseAttachment(String version) {
        if (StringUtils.isEmpty(version)) {
            return false;
        }
        // for previous dubbo version(2.0.10/020010~2.6.2/020602), this version is the jar's version, so they need to
        // be ignore
        int iVersion = getIntVersion(version);
        if (iVersion >= 2001000 && iVersion <= 2060200) {
            return false;
        }

        return iVersion >= LOWEST_VERSION_FOR_RESPONSE_ATTACHMENT;
    }
```
It looks good 
https://github.com/apache/dubbo/blob/dubbo-2.7.1/dubbo-common/src/main/java/org/apache/dubbo/common/Version.java

**Comment by qixiaobo** [comment]
```java
 /**
     * get prefix digits from given version string
     */
    private static String getPrefixDigits(String v) {
        Matcher matcher = PREFIX_DIGITS_PATTERN.matcher(v);
        if (matcher.find()) {
            return matcher.group(1);
        }
        return "";
    }
```
so it may return ""

**Comment by qixiaobo** [comment]
maybe you can provide the error v parameter?

**Comment by AlbumenJ** [comment]
close for long time no response

Please feel free to reopen it
