### ISSUE TITLE
配置<dubbo:provider ... />的executes参数引发的bug

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo#5052]
### Environment

* Dubbo version: 2.7.2
* Operating System version: centos
* Java version: 1.8

### Steps to reproduce this issue
接口配置了全局的executes参数后，对并发请求接口做了限制，跟踪代码发现接口请求计数不会扣减，原因如下：
1. 是使用泛化调用的发起的请求
2. 请求经过GenericFilter后，ExecuteLimitFilter(line: 52)方法里可以拿到正确的methodName
3. 外层ProtocolFilterWrapper(line: 159)在扣减接口计数时，外层的invocation，并没有经过GenericFilter过滤，所以拿到的methodName依然是$invoke, 造成计数扣减失败

请尽快修复这个bug

**Comment by sonymoon** [comment]
我在本地debug确实发现了这个问题。泛化调用时
RpcStatus Map中会存在$invoke->RpcStatus。
ExecuteLimitListener回调中endCount方法扣减的是$invoke方法的active，实际上应该扣减真实method的active？
是设计上泛化调用$invoke就是单独统计吗  
ping @cvictory @htynkn 
如果算bug的话 我会提一个PR

**Comment by chickenlj** [comment]
你们说的是`泛化实现`吧？不是`泛化调用`

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
