### ISSUE TITLE
token and tag is ineffective when I use telnet command

### ISSUE THREAD

**Issue by YeautyYE** [apache/dubbo#5056]
![image](https://user-images.githubusercontent.com/37794518/64752612-cb847180-d552-11e9-842c-5e207e9fd836.png)
![image](https://user-images.githubusercontent.com/37794518/64752621-d212e900-d552-11e9-842b-3761c69050a7.png)

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
