### ISSUE TITLE
nacos endpoint parse error

### ISSUE THREAD

**Issue by cyejing** [apache/dubbo#5058]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: mac
* Java version: jdk8

### Steps to reproduce this issue

1. Configure the nacos endpoint address: dev.nacos.com:8080
2. The dubbo configuration resolves the port error. No port number is parsed and passed to nacos for initialization.

1. 配置nacos endpoint地址：dev.nacos.com:8080
2. dubbo 配置解析端口错误。没有有端口号解析出来传给nacos进行初始化

code：
https://github.com/apache/dubbo/blob/7d564e75fe776681e9e3c0a6f6bd1c4ad1ea51af/dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosRegistryFactory.java#L95

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
Normal resolution endpoint port
### Actual Result
Failed to parse endpoint port

**Comment by candyaaa** [comment]
@i will solve it@

**Comment by CrazyHZM** [comment]
Nacos already supports address resolution.
