### ISSUE TITLE
dubbo线程池不满，每次设置完成线程池就最后几个活跃

### ISSUE THREAD

**Issue by zxyevjgithub** [apache/dubbo#5061]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
