### ISSUE TITLE
同一服务provider层两个服务之间互相调用会导致被引用的服务启动不了

### ISSUE THREAD

**Issue by rock007** [apache/dubbo#5062]
如题，同一服务(provider)项目,一个服务引用调用另一个（其实没必要），如下图
![image](https://user-images.githubusercontent.com/2245512/64776592-1326ef80-d58b-11e9-8f6b-bbce96cd6e0a.png)

结果查出服务（redis为注册中心）

![image](https://user-images.githubusercontent.com/2245512/64777010-e3c4b280-d58b-11e9-882c-6be8f9a9162f.png)
最终结果是少了一个

**Comment by yuxiao97** [comment]
没看懂一个工程下的服务为什么还要走Dubbo呢

**Comment by kakaCat** [comment]
循环注入问题。

**Comment by rock007** [comment]
其实不是，第一次可以起动，第二次就不行了，用的redis为注册中心——这个才是原因，换成zookeeper就好了，什么都没改
