### ISSUE TITLE
I found a bug in Dubbo

### ISSUE THREAD

**Issue by pengzhengfa** [apache/dubbo#5064]
Here's how I discovered dubbo's bugs
-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->private synchronized void destroyConnectStatusCheckCommand() {
-->Look at the logic inside. There's a dead loop in it. If we add the synchronized keyword in it, then he won't have synchronization problem.
-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->protected void connect() throws RemotingException {-->connectLock.lock();-->There's also a lock here.
-->So where does the problem arise? Look at the logic of his reconnection detection.-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->protected void connect() throws RemotingException {
-->initConnectStatusCheckCommand();-->Click in-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->private synchronized void initConnectStatusCheckCommand() {
try {
	if (!isConnected()) {
		connect();
	} else {
		lastConnectedTime = System.currentTimeMillis();
	}
} catch (Throwable t) {
	String errorMsg = "client reconnect to " + getUrl().getAddress() + " find error . url: " + getUrl();
	// wait registry sync provider list
	if (System.currentTimeMillis() - lastConnectedTime > shutdown_timeout) {
		if (!reconnect_error_log_flag.get()) {
			reconnect_error_log_flag.set(true);
			logger.error(errorMsg, t);
			return;
		}
	}
	if (reconnect_count.getAndIncrement() % reconnect_warning_period == 0) {
		logger.warn(errorMsg, t);
	}
}
-->He has no locks in it.-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)
-->private synchronized void destroyConnectStatusCheckCommand() {-->If in a flash our method is implemented here, remove the connection.
-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->private synchronized void initConnectStatusCheckCommand() {
-->connect();-->And then, at the same time, it executes into this method.
-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->private synchronized void destroyConnectStatusCheckCommand() {
-->reconnectExecutorFuture.cancel(true);-->When we remove the connection, our Future is closed.
-->So at the same time, he's executing it.-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->private synchronized void initConnectStatusCheckCommand() {
-->connect();-->Click to go-->protected void connect() throws RemotingException {-->He did it again.-->initConnectStatusCheckCommand();-->This method
-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->protected void connect() throws RemotingException {
--> initConnectStatusCheckCommand();-->Click in-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)
-->private synchronized void initConnectStatusCheckCommand() {-->if (reconnect > 0 && (reconnectExecutorFuture == null || reconnectExecutorFuture.isCancelled())) {
-->If he is greater than 0 or not, reconnectExecutorFuture == null - > I don't mean null - > but | reconnectExecutorFuture. isCancelled ()--> Here is or is not cancelled
-->He's a canceller.-->So at the same time, we have entered into this logic.-->At the same time, it goes into the logic of if.-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)
-->reconnectExecutorFuture = reconnectExecutorService.scheduleWithFixedDelay(connectStatusCheckCommand, reconnect, reconnect, TimeUnit.MILLISECONDS);
-->Here he added another, and he recreated another.-->scheduleWithFixedDelay-->The task of restarting the disconnected line is executed once in two seconds.
-->Wouldn't our registry notify our client to cancel it at this time? He won't.
-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)-->private synchronized void destroyConnectStatusCheckCommand() {-->Cancellation
-->So he'll always implement the logic of disconnection and reconnection - > What's the real solution to this bug?-->com.alibaba.dubbo.remoting.transport.AbstractClient(class)
-->private synchronized void initConnectStatusCheckCommand() {-->if (reconnect > 0 && (reconnectExecutorFuture == null || reconnectExecutorFuture.isCancelled())) {
-->|| reconnectExecutorFuture.isCancelled())-->Just comment him out of this line of code.

**Comment by zhaozhiwei2017** [comment]
Can you repeat your discovery process as follows？
1. do something...
2. do something...
3. do something...

**Comment by pengzhengfa** [comment]
I have marked on it very clear, from which class began to go in, I was conducted by means of the debug mode, the probability of actually in the real environment is small, when it is at our connection time-outs have an if statement judgment, judgment of whether his connection failure, because when I debug already give he shut down the server connection, when he is the connection failure, but at the time of our if statement judge, judge if he fails, at this time is a failure, and then we inform dubbo zookeeper connect destruction may be at the same timeYes, this kind of situation may lead to the endless detection. I will help you clean up a detailed debug process when I have time next time. Thank you

**Comment by zhaozhiwei2017** [comment]
@pengzhengfa you can try upgrade your dubbo to 2.7.x, the new version of dubbo starts with com.apache.xxx package names

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
