### ISSUE TITLE
如何通过代码或者接口调用的方式获取dubbo服务的参数列表和参数类型？

### ISSUE THREAD

**Issue by zlba111** [apache/dubbo#5068]

**Comment by danke** [comment]
你的意思指的是当一个服务被调用后,在这个被调用的服务内获取其参数列表?亦或指的是在调用服务时进行外部监测?

**Comment by zlba111** [comment]
在服务没有调用前进行外部检测，获取其参数列表

**Comment by sonymoon** [comment]
我感觉你可以扩展`org.apache.dubbo.rpc.Filter` 可以参考 `org.apache.dubbo.rpc.filter.EchoFilter` 等。不知道是不是你想要的答案

**Comment by zlba111** [comment]
org.apache.dubbo.rpc.Filter 可以参考 org.apache.dubbo.rpc.filter.EchoFilter
这2种方式需要浸入业务代码，有没有不用侵入的方式？

**Comment by imsunv** [comment]
you can see [metadata-center](http://dubbo.apache.org/zh-cn/docs/user/references/metadata/introduction.html)

the method signature will register to metadata center and can find it here

**Comment by zlba111** [comment]
如何在应用外面通过接口调用方式或其他方式拿到元数据？
