### ISSUE TITLE
Use the echo test to throw a ClassCastException

### ISSUE THREAD

**Issue by kiwiflydream** [apache/dubbo#5074]
### Environment

* Dubbo version: 2.7.3
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue
```
@Service
public class DubboEchoService {

    @Reference(version="1.0.0")
    private DemoService demoService;

    public void test(){
        EchoService echoService = (EchoService) demoService;
        Object status = echoService.$echo("OK");
        System.out.println(status);
    }
}
```

```
java.lang.ClassCastException: com.sun.proxy.$Proxy55 cannot be cast to org.apache.dubbo.rpc.service.EchoService
```

I found all the examples were through  <dubbo:reference />
, but we have no XML file in spring boot and can only use the annotation, but found the error

**Comment by CodingSinger** [comment]
yes, it's a bug, because the annotation processor only use the DemoService as the proxy interface. we will fix it soon.

**Comment by kiwiflydream** [comment]
Thanks.

**Comment by Leishunyu** [comment]
I did not reproduce this problem.

**Comment by hhofchina** [comment]
reproduce: annotation config dubbo 

        Assert.assertEquals("OK", ((EchoService) yourDubboService).$echo("OK"));

class com.sun.proxy.$Proxy106 cannot be cast to class org.apache.dubbo.rpc.service.EchoService (com.sun.proxy.$Proxy106 and org.apache.dubbo.rpc.service.EchoService are in unnamed module of loader 'app')

**Comment by changfubai** [comment]
I did not reproduce on master, I guess it has been fixed.
may @CrazyHZM  close it ?
