### ISSUE TITLE
有人碰到dubbo跟rabbitmq消费者一起启动有冲突吗

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo#5081]
使用rebbitmq消费机打开后批量消费数据，dubbo消费者调用dubbo生产者就调不通了，超时。有人碰到过吗。

**Comment by 1076572358** [comment]
spring.rabbitmq.listener.simple.concurrency = 3 ,这里开启的并发concurrency大于3就调用不到服务生产者这里来了 实在是百思不得其解

**Comment by kakaCat** [comment]
建议查看一下线程，是不是线程数不够了

**Comment by htynkn** [comment]
理论上二者没有关联也不会有冲突。
是否有例子可以重现相关问题？如果可以稳定重现的话，建议附上相关例子重新开一个issue
