### ISSUE TITLE
office web site doc description is error

### ISSUE THREAD

**Issue by Jason-laosan** [apache/dubbo#5095]
![image](https://user-images.githubusercontent.com/6261668/65306689-93b3a480-dbb8-11e9-8968-9188ad6df3c9.png)
![image](https://user-images.githubusercontent.com/6261668/65306726-b0e87300-dbb8-11e9-938e-e1ac6c161770.png)
source code doc is  different from office doc(http://dubbo.apache.org/zh-cn/docs/source_code_guide/cluster.html) 3.2.3 ,please check which one is right

**Comment by superleo-cn** [comment]
Based on the comment from source code, the invoker exactly executes one time, which means if it fails, the retry strategy is not going to wok.  Ultimately, you have to catch the exception and handle it yourself. The document is out of date, you should follow the code.

**Comment by jin19910624** [comment]
source code doc is Usually used for non-idempotent write operations,but office doc is 幂等操作，

**Comment by superleo-cn** [comment]
Correct, that's why I asked you to follow the source code comment.

**Comment by CrazyHZM** [comment]
Issues have been created in the dubbo-website project
