### ISSUE TITLE
dubbo 2.7.3 版本应用,能被dubbo2.5.5版本应用正常调用吗？能正常调用dubbo2.5.5版本应用吗

### ISSUE THREAD

**Issue by zhangkangyue** [apache/dubbo#5109]
dubbo升级中，如何实现 dubbo2.5.5版本应用 平滑升级到dubbo2.7.3；
请大神支招

**Comment by kiwiflydream** [comment]
http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html

**Comment by zhangkangyue** [comment]
前提是所有的dubbo应用都升级到新版dubbo 2.7.3吗？
有部分dubbo应用用老版2.5.5版本，部分应用使用新版dubbo2.7.3的解决方案吗？

**Comment by htynkn** [comment]
2.7.x 和 2.6.x 是目前社区提供支持的版本，二者是可以兼容的。
 参考 http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html ，理论上对于低版本也是功能兼容的。

建议在测试环境先行测试，再迁移到生产环境。

**Comment by kiwiflydream** [comment]
@zhangkangyue  https://www.infoq.cn/article/kOxdaV3y9fMZ0Bzs0jb2  携程的这篇总结的很全，希望对你有用。
