### ISSUE TITLE
how to use it (dubbo:reference) config to Spring properties file?

### ISSUE THREAD

**Issue by cookiejoo** [apache/dubbo#5116]
i want to use it Spring properties file replace xml file.
like
dubbo.reference.myinterface.timeout=10000
dubbo.reference.myinterface.interface=com.demo.provider.service.IMyService
dubbo.reference.myinterface.retries=0
but it not work. can i how to do?

I refer to the following documentation
![image](https://user-images.githubusercontent.com/3397316/65654951-01dee800-e04d-11e9-8b6e-247410174f1f.png)

**Comment by cookiejoo** [comment]
我的目的是对某个接口做超时配置,我用的是spring的properties文件,没有xml的consumer配置.
但我这么用无效.请求帮助/...

**Comment by jasonjoo2010** [comment]
So what about use `@EnableDubbo` and `@Reference` for replacement?

**Comment by cookiejoo** [comment]
> So what about using `@EnableDubbo` and `@Reference` for replacement?

@Reference(version = "1.0")
private IMyService myService;

becourse i don't want update my code.
i want use other way to do it.
like config properties file.
thank you!

**Comment by sonymoon** [comment]
1. Create `dubbo.properties`.
2. Specify reference config for a certain interface. Eg, 
`dubbo.reference.org.apache.dubbo.demo.DemoService.timeout=500`.
I test locally and it worked.

**Comment by cookiejoo** [comment]
> 1. Create `dubbo.properties`.
> 2. Specify reference config for a certain interface. Eg,
>    `dubbo.reference.org.apache.dubbo.demo.DemoService.timeout=500`.
>    I test locally and it worked.

ok,i try of it,thank you
