### ISSUE TITLE
为什么payload没有限制文件传输大小?

### ISSUE THREAD

**Issue by cookiejoo** [apache/dubbo#5117]
`<dubbo:protocol name="hessian" host="${dubbo.protocol.host}" port="57994" server="jetty" payload="8388608"/>`
我设置了这个和
`<dubbo:provider registry="defaultRegistry" register="${dubbo.registry.register}" timeout="${dubbo.timeout}" filter="-exception" delay="-1" payload="8388608"/>`
都没有作用,我传输60M的文件都没异常
`uploadBytes(String systemName, String bizType, String fileSuffix, byte[] data)`
这是为啥呢?
怎么才能够限制data的大小?

**Comment by kimmking** [comment]
can you make a testcase for me?

**Comment by cookiejoo** [comment]
@Test
    public void upload() {
        File file = new File("D:\\web.jar");
        try {
            byte[] data = Files.toByteArray(file);
            for (int i = 0; i < 100; i++) {
                Response<String> response = warehouseFacade.uploadBytes("apv", "ocr", "jar", data);
}
Response<String> uploadBytes(String var1, String var2, String var3, byte[] var4);

<dubbo:protocol name="hessian" port="57994" server="jetty" payload="8388608"/>
<dubbo:provider registry="defaultRegistry" register="${dubbo.registry.register}" timeout="5000" filter="-exception" delay="-1" payload="8388608"/>
	<dubbo:service registry="defaultRegistry" interface="facade.WarehouseFacade" ref="warehouseFacade" protocol="hessian" timeout="12000"/>

**Comment by cookiejoo** [comment]
> can you make a testcase for me?

dubbo 2.6.2

**Comment by sonymoon** [comment]
You can assert the length of data that it should be equal or bigger than you expect

**Comment by cookiejoo** [comment]
> You can assert the length of data that it should be equal or bigger than you expect

![image](https://user-images.githubusercontent.com/3397316/65738522-c60f5580-e114-11e9-8f79-3ab510794105.png)
my file just 24M, i don't know how to see this Provide interface payload attribute...
![image](https://user-images.githubusercontent.com/3397316/65738559-de7f7000-e114-11e9-8905-e574d85d2aac.png)

**Comment by sonymoon** [comment]
I looked into code, hessian protocol do not check payload for now, use dubbo protocol instead.

**Comment by cookiejoo** [comment]
> I looked into code, hessian protocol do not check payload for now, use dubbo protocol instead.

But I'm transmitting big files.i need use hessian protocol,Is the Hessian protocol unsupported?Is there any other way?
thank you.

**Comment by sonymoon** [comment]
I think you better limit the file upload size in web container, not by dubbo.
Similar issue dicussed here #2813

**Comment by cookiejoo** [comment]
thank you for your time,i was find other way to limit that files size.
