### ISSUE TITLE
There are some url in testcase that should be optimized

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo#5119]
- References to internal JIRA  http://code.alibabatech.com/jira/browse/DUBBO-XXX that it cannot be accessed.
- Reference to this URL : http://b2b-doc.alibaba-inc.com/display/RC/dubbo_devguide.htm
- Reference to this URL (http://dubbo.io/logo.png) in tests. This gives a 404 so I’m not sure if those test pass. there are also there reference to http://dubbo.io.

Some url is internal url in the testcase.
One url is invalid but testcase passed, we can optimize it.

**Comment by qinliujie** [comment]
can't find any url like that ,close
