### ISSUE TITLE
使用com.alibaba.dubbo.config.annotation.Service描述的服务与springAop冲突导致服务无法暴露

### ISSUE THREAD

**Issue by spjich** [apache/dubbo#512]
# 问题代码
          @Service(owner = "jc")
           public class UserBusiness implements UserBusinessInterface {
                 @LOG
                 @Override
               public UserResponse regist(UserRegistDTO userRegistDTO) {
                          return staUserService.regist(userRegistDTO);
              }
           }

# 场景
1.用com.alibaba.dubbo.config.annotation.Service标签修饰UserBusiness 服务
2.@LOG是一个自定义标签，并且配置了spring的Aop进行了拦截,配置如下
             @Pointcut("@annotation(com.*.*.core.aop.LOG)")

# 现象
dubbo无法暴露UserBusiness  这个服务

# 原因分析
配置有Spring aop的bean生成了代理对象
com.alibaba.dubbo.config.spring.AnnotationBean 这个类的postProcessAfterInitialization方法的 
Service service = bean.getClass().getAnnotation(Service.class); 这一行获取到的是由cglib代理出来的对象，所以无法得到@Service 注解，导致服务未暴露

# 解决方法
Service service = bean.getClass().getAnnotation(Service.class); 将此方法改成如下代码

      Service service;
      if (AopUtils.isAopProxy(proxy) ){
               service =（根据代理对象获得到的cglib或者jdkproxy的原始对象）
      }else{
               service = bean.getClass().getAnnotation(Service.class);
      }

**Comment by zhangzhenhua92** [comment]
厉害

**Comment by CXL6688** [comment]
使用xml注解方式也可以避免这个问题，我已将这个模型放到我的git上。

**Comment by sxc9870** [comment]
if ("$$".contains(clazz.getName())||clazz.getSimpleName().contains("$$")) {  
            clazz =clazz. getSuperclass();     
        }
再加一段这个试试
