### ISSUE TITLE
zookeeper acl设置在dubbo中不生效

### ISSUE THREAD

**Issue by lingo169** [apache/dubbo#5120]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.7
* Operating System version: linux redhat4.8
* Java version: jdk1.8

### Steps to reproduce this issue

1. connect zookeeper with zKcli;
2. setAcl /dubbo digest:abcd:base64(sha(abcd)):cdrwa
3. ls /dubbo  权限受限
4. addauth digest abcd:abcd
5.可以访问 ls /dubbo

What actually happens?
zookeeper acl设置在dubbo中不生效
If there is an exception, please attach the exception trace:

```
配置文件dubbo.properties中配置了如下信息
dubbo.registry.protocol=zookeeper
dubbo.registry.address=zookeeper的集群地址
dubbo.registry.username=abcde(故意不正确）
dubbo.registry.password=abcde(故意不正确）
dubbo.registry.client=zkclient

question（问题）：
实际情况不是应该出现noauth的异常吗？
现状是没有出现异常，这是为什么？
```

**Comment by htynkn** [comment]
dubbo使用的是zk client连接，zookeeper acl的设置生效与否dubbo无法控制。
建议如果问题无法排除，可以使用java zk client直接连接测试，判断问题所在。
