### ISSUE TITLE
Cannot configure zookeeper cluster address after using multiple registry

### ISSUE THREAD

**Issue by yxxcoder** [apache/dubbo#5121]
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [√] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: MacOS 10
* Java version: Oracle JDK 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

Cannot configure zookeeper cluster address after using multiple registry

Only one address can be configured when using multiple:
```
 <dubbo:registry address="
    multiple://127.0.0.1?
    reference-registry=zookeeper://127.0.0.1:2182,sofa://127.0.0.1:9603&amp;
    service-registry=zookeeper://127.0.0.1:2182,sofa://127.0.0.1:9603"/>
```

If you use the backup field, could only add one more address:
```
 <dubbo:registry address="
    multiple://127.0.0.1?
    reference-registry=zookeeper://127.0.0.1:2182?backup=127.0.0.1:2181,sofa://127.0.0.1:9603&amp;
    service-registry=zookeeper://127.0.0.1:2182?backup=127.0.0.1:2181,sofa://127.0.0.1:9603"/>
```

The previous configuration is like this:
```
<dubbo:registry protocol="zookeeper" address="10.20.153.10:2181,10.20.153.11:2181,10.20.153.12:2181" />
```

Only two addresses can be configured that do not meet the needs of our production environment.

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
