### ISSUE TITLE
org.apache.dubbo.common.bytecode.Proxy cause metaspace leak

### ISSUE THREAD

**Issue by yuyijq** [apache/dubbo#5124]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: all
* Operating System version: all
* Java version: 1.8

org.apache.dubbo.common.bytecode.Proxy use WeakHashMap to cache generated dynamic proxy, but the WeakHashMap's value be gced, so if we create many ReferenceConfig(for one service interface), then org.apache.dubbo.common.bytecode.Proxy would generate many dynamic proxy class.

**Comment by xiaoheng1** [comment]
see https://github.com/apache/dubbo/pull/7374

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
