### ISSUE TITLE
dubbo-demo-provider 项目没有找到，是换地方了吗

### ISSUE THREAD

**Issue by championjing** [apache/dubbo#5128]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version:  windows 10
* Java version:  1.8

### Steps to reproduce this issue

http://dubbo.apache.org/zh-cn/docs/admin/install/provider-demo.html 说明文档中提到的dubbo-demo-provider，在clone git后并没有找到

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

希望说明文档中提供最新的dubbo-demo-provider位置，或者新的项目名

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by imsunv** [comment]
@championjing  
>  https://github.com/apache/dubbo/tree/master/dubbo-demo/dubbo-demo-xml

 the doc needs to be updated

**Comment by zhaozhiwei2017** [comment]
所有的demo项目都在dubbo-demo项目下
> https://github.com/apache/dubbo/tree/master/dubbo-demo

**Comment by htynkn** [comment]
move issue to website repo
