### ISSUE TITLE
HeaderExchangeChannel 类的 send 方法是否能直接调用 channel.send 方法？

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo#5133]
我使用的是 dubbo2.7.2

我看了下 github 上的最新源码，如下：

```
public void send(Object message, boolean sent) throws RemotingException {
        if (closed) {
            throw new RemotingException(this.getLocalAddress(), null, "Failed to send message " + message + ", cause: The channel " + this + " is closed!");
        }
        if (message instanceof Request
                || message instanceof Response
                || message instanceof String) {
            channel.send(message, sent);
        } else {
            Request request = new Request();
            request.setVersion(Version.getProtocolVersion());
            request.setTwoWay(false);
            request.setData(message);
            channel.send(request, sent);
        }
    }
```

为啥不能直接调用 channel.send(message, sent) ？这是基于什么考虑了？

**Comment by zhaozhiwei2017** [comment]
我觉得这是基于装饰者模式考虑的，HeaderExchangeChannel 的职责就是用Request对象包装请求体，但是如果之前已经有装饰器对请求体做过包装了，那就没必要再包装一层了，这是我的理解，不知道正不正确

**Comment by xiaoheng1** [comment]
@zhaozhiwei2017 您好，但是上面的 message 是字符串的时候，它也是直接调用的 channel.send 方法呀，所以在看这个方法的时候，感到很困惑

**Comment by zhaozhiwei2017** [comment]
@xiaoheng1   这是为telnet的处理做的兼容，org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#received方法中有一段代码:
![image](https://user-images.githubusercontent.com/28380264/66179109-4d6f4280-e69a-11e9-8d63-a4e394d31fc4.png)

**Comment by xiaoheng1** [comment]
@zhaozhiwei2017 明白了，感谢您的解答

**Comment by xiaoheng1** [comment]
@zhaozhiwei2017 请教下，为啥 request 方法没有上面的判断？例如对 Request, Response 的判断？

public CompletableFuture<Object> request(Object request, int timeout) throws RemotingException {
        if (closed) {
            throw new RemotingException(this.getLocalAddress(), null, "Failed to send request " + request + ", cause: The channel " + this + " is closed!");
        }
        // create request.
        Request req = new Request();
        req.setVersion(Version.getProtocolVersion());
        req.setTwoWay(true);
        req.setData(request);
        DefaultFuture future = DefaultFuture.newFuture(channel, req, timeout);
        try {
            channel.send(req);
        } catch (RemotingException e) {
            future.cancel();
            throw e;
        }
        return future;
    }
