### ISSUE TITLE
为什么Directory类不支持SPI呢

### ISSUE THREAD

**Issue by CodingSinger** [apache/dubbo#5152]
有一个需求，需要重写RegistryDirectory的某些方法，但是Direcotry并不支持SPI的做法，是写死在RegistryProtocol的doRefer方法中的，于是我想到了自己去实现RegistryProtocol，尽管Protocol支持SPI，但是RegistryProtocol却不支持覆盖...

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
