### ISSUE TITLE
telnet 运维的端口无法调通

### ISSUE THREAD

**Issue by changelzj** [apache/dubbo#5156]
:: Dubbo Spring Boot (v0.2.0) : https://github.com/apache/incubator-dubbo-spring-boot-project
 :: Dubbo (v2.6.2) : https://github.com/apache/incubator-dubbo
 :: Google group : dev@dubbo.incubator.apache.org

以下配置均试过，系统里面都检测不到qosPort端口的占用

#dubbo.application.qos-enable=true
#dubbo.application.qos-port=9856
#dubbo.application.qos.accept.foreign.ip=true

dubbo.application.qosEnable=true
dubbo.application.qosPort=33333
dubbo.application.qosAcceptForeignIp=true

**Comment by kexianjun** [comment]
Please check if the following dependency exists first
```
<dependency>
  <groupId>com.alibaba</groupId>
  <artifactId>dubbo-qos</artifactId>
  <version>2.6.2</version>
</dependency>
```

**Comment by qixiaobo** [comment]
I use dubbo 2.6.4 
This works fine
```
dubbo.application.qos.enable=true
dubbo.application.qos.port=2${server.port}
dubbo.application.qos.acceptForeignIp=false
```

**Comment by qixiaobo** [comment]
> Please check if the following dependency exists first
> 
> ```
> <dependency>
>   <groupId>com.alibaba</groupId>
>   <artifactId>dubbo-qos</artifactId>
>   <version>2.6.2</version>
> </dependency>
> ```
Not all in one?
should  check com.alibaba.dubbo.qos.server.handler.QosProcessHandler exists?

**Comment by kexianjun** [comment]
I'm quite sure that you should add dubbo-qos explicitly in dubbo version 2.6.2

**Comment by changelzj** [comment]
> I'm quite sure that you should add dubbo-qos explicitly in dubbo version 2.6.2

The problem has been solved Thanks

**Comment by changelzj** [comment]
The problem has been solved Thanks

**Comment by qixiaobo** [comment]
> I'm quite sure that you should add dubbo-qos explicitly in dubbo version 2.6.2

That means some version not provide the all-in-one jar~
