### ISSUE TITLE
The file attribute in dubbo's registry tag is not valid

### ISSUE THREAD

**Issue by Python-IBM** [apache/dubbo#5157]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows7
* Java version: 1.8

### Steps to reproduce this issue

1.<dubbo:registry file="/dubbo/cache/demo.cache">/
2. Startup application
3. No files were generated in the corresponding directory

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

I want to generate cache files in the corresponding directory after the program starts

### Actual Result

No files were generated in the corresponding directory

**Comment by CodingSinger** [comment]
is there any exception when application startup?

**Comment by CodingSinger** [comment]
maybe you need to check whether you have the permission to create dir under the root dir

**Comment by Python-IBM** [comment]
> is there any exception when application startup?

no any exception

**Comment by Python-IBM** [comment]
> maybe you need to check whether you have the permission to create dir under the root dir

Not generated in the root directory, but in the specified directory

**Comment by Python-IBM** [comment]
I tried. Why can't the directory specified in Dubbo 2.7.3 be generated? Dubbo 2.6.5 can specify directory generation

**Comment by CodingSinger** [comment]
> > maybe you need to check whether you have the permission to create dir under the root dir
> 
> Not generated in the root directory, but in the specified directory

can you post your  github repo here?

**Comment by Python-IBM** [comment]
You can try it on your own locally.

<dubbo:registry file="E:/dubbo/cache/demo.cache"/>

No files were generated in the directory corresponding to disk E.

**Comment by Python-IBM** [comment]
> > > maybe you need to check whether you have the permission to create dir under the root dir
> > 
> > 
> > Not generated in the root directory, but in the specified directory
> 
> can you post your github repo here?

You can try it on your own locally.

<dubbo:registry file="E:/dubbo/cache/demo.cache"/>

No files were generated in the directory corresponding to disk E.

**Comment by sonymoon** [comment]
I tested with latest master branch, mac os, no ex.
