### ISSUE TITLE
2.7.3 dubbo 服务治理是基于ip 不变，有方法支持容器特性吗？

### ISSUE THREAD

**Issue by zhangkangyue** [apache/dubbo#5159]
容器ip不固定，服务治理怎么实现

**Comment by nisiyong** [comment]
IP不固定并没有问题，因为有注册中心。消费者调用提供者时，是依据提供者的地址列表来调用的，消费者无需知道提供者的具体IP

**Comment by zhangkangyue** [comment]
> IP不固定并没有问题，因为有注册中心。消费者调用提供者时，是依据提供者的地址列表来调用的，消费者无需知道提供者的具体IP

考虑到dubbo服务治理，是基于ip粒度的；如条件路由、黑白名单、标签路由。
部署到容器上，怎样保持条件路由、黑白名单、标签路由等服务治理功能

**Comment by cdy1996** [comment]
１．　条件路由是有应用粒度和服务粒度的所以IP不固定是没有关系的具体可以看[条件路由](http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html)
２．　黑白名单的话, [官方文档](http://dubbo.apache.org/zh-cn/docs/admin/serviceGovernance.html)的描述是:　是条件路由的一部分，规则存储和条件路由放在一起，为了方便配置所以单独拿出来，同样可以通过**服务和应用**两个维度，指定黑名单和白名单
３．　标签路由的话我没用过,不过你也可以看官方文档

**Comment by htynkn** [comment]
也可以使用标签路由规则进行治理

**Comment by zhangkangyue** [comment]
> １．　条件路由是有应用粒度和服务粒度的所以IP不固定是没有关系的具体可以看[条件路由](http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html)
> ２．　黑白名单的话, [官方文档](http://dubbo.apache.org/zh-cn/docs/admin/serviceGovernance.html)的描述是:　是条件路由的一部分，规则存储和条件路由放在一起，为了方便配置所以单独拿出来，同样可以通过**服务和应用**两个维度，指定黑名单和白名单
> ３．　标签路由的话我没用过,不过你也可以看官方文档

1、条件路由时，需要基于ip粒度，实现黑白名单、排除预发布机
2、实现灰度时，也需要针对ip做灰度，实现灰度发布、A/BTest
3、标签路由也需要配置ip粒度。
谢谢哈

**Comment by zhangkangyue** [comment]
> 也可以使用标签路由规则进行治理

标签路由需要针对标签设置对应ip清单
