### ISSUE TITLE
dubbo2.7.4 什么时间发布正式版本？

### ISSUE THREAD

**Issue by zjw2011** [apache/dubbo#5162]

**Comment by zhaozhiwei2017** [comment]
已经发布了
>  https://github.com/apache/dubbo/releases

**Comment by zhaozhiwei2017** [comment]
应该很快就发布了，现在社区正在进行发布投票

**Comment by zjw2011** [comment]
但是还没有传到maven私服上去吗？

**Comment by htynkn** [comment]
投票之后才会正式发布到maven中央仓库，投票情况和进度参考：
https://lists.apache.org/thread.html/fa98308e777b1a1f22a6600fc1c4800525fd161c655b9f23a97714bc@%3Cdev.dubbo.apache.org%3E
