### ISSUE TITLE
dubbo spi filter save trace bug

### ISSUE THREAD

**Issue by trotyzyq** [apache/dubbo#5178]
springboot 2.1.5 release
dubbo 2.6.2

my web is consumer-> provider ->provider 
# first problem
I use dubbo spi filter do traceId,  but when I do redistemplate list , the second provider's data is ok, the consumer and first provider's data is zset And no Size . do you think is impossibile,but is true.

# second problem
when i use mysql ,the second provider can not do this method, sometimes.

**Comment by CrazyHZM** [comment]
2.6.x version will no longer be maintained, it is recommended to upgrade to the latest version
