### ISSUE TITLE
Use dubbo 2.7.4 in maven project

### ISSUE THREAD

**Issue by dangit815** [apache/dubbo#5182]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4
* Operating System version: windows10
* Java version: 1.8

### Actual Result
How can I use dubbo2.7.4 in maven project?Which repository can provider 2.7.4, and how to configure in the pom.xml and setting.xml? Thanks :)

**Comment by zishinan** [comment]
DownLoad source code and package your self , then dependence local package in pom or upload to you local maven server.

**Comment by zyna** [comment]
No Release.

**Comment by htynkn** [comment]
It's released. https://mvnrepository.com/artifact/org.apache.dubbo/dubbo/2.7.4
