### ISSUE TITLE
appear NullPointException if Parameters is null

### ISSUE THREAD

**Issue by lkj41110** [apache/dubbo#5186]
### Environment

* Dubbo version: 2.7.4-release

### Steps to reproduce this issue

```
 cc.getParameters().put(org.apache.dubbo.remoting.Constants.CLIENT_KEY, rc.getClient());
```
appear NullPointException if Parameters is null

#5185

**Comment by lkj41110** [comment]
run dubbo-demo-xml-provider dome in 2.7.4-release,produce NullPointException。

**Comment by sonymoon** [comment]
I ran into this problem too.
StackTrace:
```
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:628)
	at java.util.Optional.orElseGet(Optional.java:267)
```
How can the related commit pass the ci unit tests?

**Comment by lkj41110** [comment]
i think the ci unit tests dont cover this case.
Run `useRegistryForConfigIfNecessary` Only when the registry protocol is zookeeper and there's no config center specified explicitly.

**Comment by cvictory** [comment]
**Sorry for bringing you inconvenience.**

We have deploy dubbo 2.7.4.1-SNAPSHOT to fix this issue. I think you can depend on this version to check if this problem is still exist.

We will publish 2.7.4.1 at this weekend.
