### ISSUE TITLE
how to disable a service under one port?

### ISSUE THREAD

**Issue by StevenKin** [apache/dubbo#5188]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: Linux
* Java version: 1.8

### Steps to reproduce this issue

I have some services under one ip， every service has a random port，I want to disable some services under the port，the override url such as 
`override://ip:port/xxx.LoginService?category=configurators&disabled=true&dynamic=false&enabled=true`,How can I do this?thanks

**Comment by sonymoon** [comment]
Try `disabled=true` by dynamic config on dubbo-admin.
