### ISSUE TITLE
服务端抛运行时异常，消费端无堆栈信息打印

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo#5189]
* Dubbo version: 2.7.3
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue
服务端抛运行时异常，消费端无堆栈信息打印。服务端也无异常堆栈打印。
消费端打印日志如下：堆栈没有打印，不方便定位问题
java.lang.NullPointerException: null

**Comment by htynkn** [comment]
服务端抛出的异常是什么类型的？能否提供demo复现这个问题？

**Comment by lkj41110** [comment]
可以参考下：https://github.com/apache/dubbo/issues/619
以及这篇文章：https://www.yuque.com/fa902k/id5z6r/sr041v
```
如果服务提供端报了大量的 NPE 异常, JVM 为了性能会做优化, 会重新编译, 不再打印异常堆栈. 只会抛出预定义的NPE异常java.lang.NullPointerException: null. 见https://www.oracle.com/technetwork/java/javase/relnotes-139183.html
```
