### ISSUE TITLE
泛型server注入

### ISSUE THREAD

**Issue by sglmsn** [apache/dubbo#5194]
* Dubbo version: 2.7.3
* Operating System version: win10
* Java version:  1.8

使用这个的时候 , 会注入DetrimentServiceImpl而不是MiningMachineServiceImpl
    @Reference
    BaseServer<T1Bean> baseServer;

@Service
public class DetrimentServiceImpl extends BaseServerImpl<DetrimentDao, Detriment> implements BaseServer<Detriment> {
}

@Service()
public class MiningMachineServiceImpl extends BaseServerImpl<T1BeanDao, T1Bean> implements BaseServer<T1Bean> {
}

**Comment by chickenlj** [comment]
Please use `group` to distinguish different implementations.
