### ISSUE TITLE
dubbo home link not found

### ISSUE THREAD

**Issue by jsbxyyx** [apache/dubbo#5196]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/26616196/67084492-ad540600-f1cf-11e9-96b9-991b377b60ca.png)
![image](https://user-images.githubusercontent.com/26616196/67084510-b218ba00-f1cf-11e9-8928-7a1068ce0d5a.png)

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by luyuanwan** [comment]
It has bean fixed,It is linked to http://dubbo.apache.org/zh-cn/docs/user/configuration/api.html
