### ISSUE TITLE
Is this a bug in class URL's getAuthority()?

### ISSUE THREAD

**Issue by maslke** [apache/dubbo#5202]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

##
In master branch,code of getAuthority() is just like this:
```java
public String getAuthority() {
        if (StringUtils.isEmpty(username)
                && StringUtils.isEmpty(password)) {
            return null;
        }
        return (username == null ? "" : username)
                + ":" + (password == null ? "" : password);
    }
```
if username is 'admin' and password is null，the return value will be 'admin:'。Is it right?Also I think null check of username is unnecessary.
Is the below code is better?
```java
public String getAuthority() {
        if (StringUtils.isEmpty(username)
                && StringUtils.isEmpty(password)) {
            return null;
        }
        return username + (password == null ? "" : ":" + password);
    }
```

**Comment by kimmking** [comment]
which class？

**Comment by maslke** [comment]
> which class？

org.apache.dubbo.common.URL.getAuthority()

**Comment by htynkn** [comment]
Refer to https://www.ietf.org/rfc/rfc3986.txt

> 3.2.1.  User Information
> 
>    The userinfo subcomponent may consist of a user name and, optionally,
>    scheme-specific information about how to gain authorization to access
>    the resource.  The user information, if present, is followed by a
>    commercial at-sign ("@") that delimits it from the host.
> 
>       userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
> 
>    Use of the format "user:password" in the userinfo field is
>    deprecated.  Applications should not render as clear text any data
>    after the first colon (":") character found within a userinfo
>    subcomponent unless the data after the colon is the empty string
>    (indicating no password).  Applications may choose to ignore or
>    reject such data when it is received as part of a reference and
>    should reject the storage of such data in unencrypted form.  The
>    passing of authentication information in clear text has proven to be
>    a security risk in almost every case where it has been used.
> 
>    Applications that render a URI for the sake of user feedback, such as
>    in graphical hypertext browsing, should render userinfo in a way that
>    is distinguished from the rest of a URI, when feasible.  Such
>    rendering will assist the user in cases where the userinfo has been
>    misleadingly crafted to look like a trusted domain name
>    (Section 7.6).

**Comment by CrazyHZM** [comment]
@maslke Can you submit a request to fix it?
