### ISSUE TITLE
Question about AbstractClusterInvoker.doSelect method

### ISSUE THREAD

**Issue by zjq123456** [apache/dubbo#5210]
Why canot select the last invoker  of invokers.

### Environment

* Dubbo version: 2.7.3
* Operating System version: 
* Java version: 1.8

### Steps to reproduce this issue

1. AbstractClusterInvoker.doSelect

![image](https://user-images.githubusercontent.com/14069938/67258514-aaa12b80-f4c3-11e9-886f-295a17977821.png)

**Comment by LiosWong** [comment]
first look at the location of the first selection, if not the last, select the **index+1** position, in order to avoid collision

**Comment by zjq123456** [comment]
Thanks, the invoker and rInvoker is not the same object.
