### ISSUE TITLE
org.apache.dubbo.rpc.RpcException

### ISSUE THREAD

**Issue by yandeyu** [apache/dubbo#5218]
dubbo 2.71 jdk 1.8
Failed to invoke the method getServiceRestMetadata in the service org.apache.dubbo.rpc.service.GenericService. Tried 3 times of the providers [192.168.3.146:20880] (1/1) from the registry localhost:9090 on the consumer 192.168.3.12 using the dubbo version 2.7.3. Last error is: java.lang.NoSuchMethodError:

**Comment by luyuanwan** [comment]
Can you give us your code  please?

**Comment by qinliujie** [comment]
Just look like your business error.close
