### ISSUE TITLE
Please use the latest version 2.7.4.1 for 2.7.4 release

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#5219]
2.7.4.1 is now voting in the mailing list, please help check and vote accordingly

You may have noticed that there already have a bunch of 2.7.4 artifacts in the maven central repo. But there's a severe problem (https://github.com/apache/dubbo/issues/5216) for that version, the bug will stop you from starting up your apps, so, you will not get success trying to use 2.7.4. 

We plan to use 2.7.4.1 as the next formal release and we'll publish official release notes once the vote is finished.

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/5186

**Comment by lkj41110** [comment]
I think should to increase the unit test coverage, this is a low-level bug

**Comment by mircoteam** [comment]
this problem，we should config provider.xml、consumer.xml like this
`<dubbo:registry address="zookeeper://127.0.0.1:2181">
        <dubbo:parameter key="hash.arguments" value="0,1"/>
    </dubbo:registry>`
because a java config code read `dubbo:registry` node paramers info。we can config paramers info pass the problem code。

**Comment by chickenlj** [comment]
2.7.4.1 has been released
