### ISSUE TITLE
getInjectedObject override

### ISSUE THREAD

**Issue by hehuang139** [apache/dubbo#5221]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: ubuntu 18.04
* Java version: 1.8

### Steps to reproduce this issue

it's a suggestion, the method "org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor#getInjectedObject" is a protected method, but attr "injectedObjectsCache" is private. so when i override the method, it's very difficult, there are lots of modifitions. so can the attr be protected?

**Comment by chickenlj** [comment]
AnnotationInjectedBeanPostProcessor has been removed from Dubbo's source code repo and now exists as a third part dependency in spring-context-support. 

If u really have that need, please submit a PR there.
