### ISSUE TITLE
when i test the demo code,the console return NullPointerException 

### ISSUE THREAD

**Issue by mircoteam** [apache/dubbo#5222]
org.apache.dubbo.config.AbstractInterfaceConfig#useRegistryForConfigIfNecessary

ConfigCenterConfig cc = configManager.getConfigCenter().orElse(new ConfigCenterConfig());
                if (rc.getParameters() != null) {
                    Map<String, String> configParams = cc.getParameters() == null ? new HashMap<>() : cc.getParameters();
                    configParams.putAll(rc.getParameters());
                    cc.setParameters(configParams);
                }
                cc.getParameters().put(org.apache.dubbo.remoting.Constants.CLIENT_KEY,rc.getClient());

when rc.getParameters() is null then cc.getParameters() is null, it`s will show NullPointerException.

please check cc.getParameters() is null and init before use it.

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/5219

Thanks for reporting, please focus on this issue and help test

**Comment by ZhiQinIsZhen** [comment]
我也刚刚替换成2.7.4，也出现了同样的问题
