### ISSUE TITLE
dubbo两个提供者互相调用

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo#5223]
1:假如我有两个dubbo提供者，也就是两个服务，这两个服务如何互相调用。
我将api打包成jar调用然后  
@Reference(version = "6.6.6",timeout = 6000,check = false)
TestService2 testService2;
这样还是不行

**Comment by lkj41110** [comment]
你的意思是两个提供者都暴露了Test接口，A调用B的test，B调用A的test？

**Comment by 1076572358** [comment]
> 你的意思是两个提供者都暴露了Test接口，A调用B的test，B调用A的test？

对的 ，这应该比较正常吧，两个服务之间互相调用。两个服务都是提供者

**Comment by 1076572358** [comment]
> 你的意思是两个提供者都暴露了Test接口，A调用B的test，B调用A的test？

不好意思 弄错了 是两个不同的服务，两个服务没有相同的接口，a是提供者，b也是提供者，a需要调用b的testService2服务。

**Comment by lkj41110** [comment]
这个就常规的，
```
A服务
@service
public class Test1{
	
}
@refence
Test2 test2
```
```
B服务

@service
public class Test2{
	
}
@refence
Test1 test1
```

**Comment by 1076572358** [comment]
@Reference吧
如果a服务application是aaa
b服务application是bbb
a用b服务的b1方法
那么打印dubbo  url是什么样子呢，application是aaa还是bbb，
我碰到的奇葩问题是a用b服务的b1方法，启动报错，说找不到提供者，我看url ，b1的application显示aaa

**Comment by lkj41110** [comment]
启动报错还是调用报错?
理论上调用关系是有上下游关系，你这种相互引用要把前置检查关了`check="false" `才能启动成功。

**Comment by yangb001** [comment]
可以
