### ISSUE TITLE
如何屏蔽dubbo框架输出日志

### ISSUE THREAD

**Issue by luoye1989hzx** [apache/dubbo#5228]
019-10-24 08:58:58.152 [ERROR] [DubboServerHandler-192.168.6.17:21881-thread-5] [wechat] [1accadf3c7474147b4f8485ea275ea91] com.taobao.api.internal.util.TaobaoLogger.logApiError(TaobaoLogger.java:50) - 2019-10-24 08:58:58.152^_^23435943^_^alibaba.aliqin.fc.sms.num.send^_^192.168.6.17^_^Linux^_^83^_^http://gw.api.taobao.com/router/rest^_^method=alibaba.aliqin.fc.sms.num.send&sign=61675C8065E00AB149ABDF344371CDF4F4C2895BB02A7DD573A0CA109F0B6AE0&format=json&rec_num=13736111889&sms_template_code=SMS_66515274&extend=13736111889&app_key=23435943&partner_id=top-sdk-java-20190510&v=2.0&sms_free_sign_name=%E6%B2%83%E6%9C%B4%E4%BC%81%E4%B8%9A%E6%9C%8D%E5%8A%A1&sign_method=hmac-sha256&sms_param=%7B%22captcha%22%3A%22224260%22%7D&sms_type=normal&timestamp=2019-10-24+08%3A58%3A58^_^{"error_response":{"code":15,"msg":"Remote service error","sub_code":"isv.BUSINESS_LIMIT_CONTROL","sub_msg":"触发分钟级流控Permits:1","request_id":"y5yf5kyvr8wm"}}

DubboServerHandler线程会不断输出这类错误，而且在info、warn、error日志文件中都会输出，如何屏蔽

**Comment by RojerAlone** [comment]
直接在日志框架里设置吧，dubbo 貌似没有提供这个功能
