### ISSUE TITLE
dubbo服务自动发现

### ISSUE THREAD

**Issue by benyVip** [apache/dubbo#5229]
比如A需要调用服务B的F1接口，但是F1是新增加的接口，如果A服务先启动，启动完成后，再隔一段时间启动B服务，才有F1接口，调用进来，会报reference的错误，说找不到对应的服务

**Comment by birdynoangels** [comment]
我也遇到了这个问题

**Comment by RojerAlone** [comment]
先启动服务 B 不就行了？

**Comment by sonymoon** [comment]
或者启动服务B之前，服务A先disable也可以？
