### ISSUE TITLE
无法设置DUBBO_IP_TO_REGISTRY=127.0.0.1

### ISSUE THREAD

**Issue by redwolf2019** [apache/dubbo#5233]
### 环境

* Dubbo version: 2.7.3
* Operating System version: MacOS
* Java version: Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

### 问题
- 设置```DUBBO_IP_TO_REGISTRY=127.0.0.1```失败
- 源码里禁用里本机回环地址
```
/*org.apache.dubbo.common.utils.NetUtils */
   public static boolean isInvalidLocalHost(String host) {
        return host == null
                || host.length() == 0
                || host.equalsIgnoreCase(LOCALHOST_KEY)
                || host.equals(ANYHOST_VALUE)
                || (LOCAL_IP_PATTERN.matcher(host).matches());
    }
```

### 希望得到的帮助
- 支持设置本机回环地址,方便开发调试.

**Comment by hengyunabc** [comment]
这个的确不是很友好，但是也是可以理解的，防止出错。 开发时可以设置为本机的其它ip。
