### ISSUE TITLE
Wrapper 类的执行顺序能否指定啊

### ISSUE THREAD

**Issue by coderlongren** [apache/dubbo#5245]
```java
wrapper1=org.apache.dubbo.demo.provider.Wrapper1
wrapper2=org.apache.dubbo.demo.provider.Wrapper2
```
这样会先执行wrapper2, 再执行wrapper1，有什么特殊的注解可以指定顺序吗？

**Comment by kexianjun** [comment]
如果是 SPI 扩展可以用 order 指定顺序

**Comment by xiaoheng1** [comment]
Wrapper 类的作用是增强功能吧，那个 Wrapper 在前，那个 Wrapper 在后应该没有影响吧？

**Comment by coderlongren** [comment]
> Wrapper 类的作用是增强功能吧，那个 Wrapper 在前，那个 Wrapper 在后应该没有影响吧？

你说的对，一般自己使用Dubbo都不会主动的使用Wrapper，thanks
