### ISSUE TITLE
Does multicast also rely on zkclient?

### ISSUE THREAD

**Issue by liunancun** [apache/dubbo#5246]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4
* Operating System version: Window7
* Java version: jdk8

### Steps to reproduce this issue

1. Using the quick start example
2. https://dubbo.apache.org/en-us/docs/user/quick-start.html

Pls. provide [GitHub address] to reproduce this issue.

No dependence on zkclient test success

What do you expected from the above steps？

Test failure
Consumer cannot call provider interface

provider start log:
十月 27, 2019 6:36:21 下午 org.springframework.context.support.ClassPathXmlApplicationContext prepareRefresh
信息: Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@1e397ed7: startup date [Sun Oct 27 18:36:21 CST 2019]; root of context hierarchy
十月 27, 2019 6:36:21 下午 org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
信息: Loading XML bean definitions from class path resource [provider.xml]
十月 27, 2019 6:36:21 下午 org.apache.dubbo.common.logger.LoggerFactory info
信息: using logger: org.apache.dubbo.common.logger.jcl.JclLoggerAdapter
十月 27, 2019 6:36:22 下午 org.apache.dubbo.config.AbstractConfig info
信息:  [DUBBO] The service ready on spring started. service: com.bessky.demo.DemoService, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:22 下午 org.apache.dubbo.config.AbstractConfig warn
警告:  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:22 下午 org.apache.dubbo.config.AbstractConfig info
信息:  [DUBBO] No valid ip found from environment, try to find valid host from DNS., dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:22 下午 org.apache.dubbo.config.AbstractConfig info
信息:  [DUBBO] Export dubbo service com.bessky.demo.DemoService to local registry url : injvm://127.0.0.1/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&bind.ip=192.168.98.1&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&qos.enable=false&release=2.7.4&side=provider&timestamp=1572172582429, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:22 下午 org.apache.dubbo.config.AbstractConfig info
信息:  [DUBBO] There's no valid monitor config found, if you want to open monitor statistics for Dubbo, please make sure your monitor is configured properly., dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:22 下午 org.apache.dubbo.config.AbstractConfig info
信息:  [DUBBO] Register dubbo service com.bessky.demo.DemoService url dubbo://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&bind.ip=192.168.98.1&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&qos.enable=false&release=2.7.4&side=provider&timestamp=1572172582429 to registry registry://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?application=hello-world-app&dubbo=2.0.2&pid=8792&qos.enable=false&registry=multicast&release=2.7.4&timestamp=1572172582421, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:22 下午 org.apache.dubbo.qos.protocol.QosProtocolWrapper info
信息:  [DUBBO] qos won't be started because it is disabled. Please check dubbo.application.qos.enable is configured either in system property, dubbo.properties or XML/spring-boot configuration., dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.remoting.transport.AbstractServer info
信息:  [DUBBO] Start NettyServer bind /0.0.0.0:20880, export /192.168.98.1:20880, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.registry.multicast.MulticastRegistry info
信息:  [DUBBO] Register: dubbo://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&release=2.7.4&side=provider&timestamp=1572172582429, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.registry.multicast.MulticastRegistry info
信息:  [DUBBO] Send multicast message: register dubbo://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&release=2.7.4&side=provider&timestamp=1572172582429 to /224.5.6.7:1234, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.registry.multicast.MulticastRegistry info
信息:  [DUBBO] Subscribe: provider://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&bind.ip=192.168.98.1&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&qos.enable=false&release=2.7.4&side=provider&timestamp=1572172582429, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.registry.multicast.MulticastRegistry info
信息:  [DUBBO] Send multicast message: subscribe provider://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&bind.ip=192.168.98.1&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&qos.enable=false&release=2.7.4&side=provider&timestamp=1572172582429 to /224.5.6.7:1234, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.registry.multicast.MulticastRegistry info
信息:  [DUBBO] Receive multicast message: register dubbo://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&release=2.7.4&side=provider&timestamp=1572172582429 from /127.0.0.1:1234, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:23 下午 org.apache.dubbo.registry.multicast.MulticastRegistry info
信息:  [DUBBO] Receive multicast message: subscribe provider://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&bind.ip=192.168.98.1&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&qos.enable=false&release=2.7.4&side=provider&timestamp=1572172582429 from /127.0.0.1:1234, dubbo version: 2.7.4, current host: 192.168.98.1
十月 27, 2019 6:36:24 下午 org.apache.dubbo.registry.multicast.MulticastRegistry warn
警告:  [DUBBO] Ignore empty notify urls for subscribe url provider://192.168.98.1:20880/com.bessky.demo.DemoService?anyhost=true&application=hello-world-app&bean.name=com.bessky.demo.DemoService&bind.ip=192.168.98.1&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.bessky.demo.DemoService&methods=sayHello&pid=8792&qos.enable=false&release=2.7.4&side=provider&timestamp=1572172582429, dubbo version: 2.7.4, current host: 192.168.98.1

**Comment by chickenlj** [comment]
和 zkclient 没有关联
