### ISSUE TITLE
dubbo Endpoint 接口为啥不抽象 receive 方法了？

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo#5248]
我使用的是 dubbo2.7.1

1.在看 Endpint 接口的时候，发现只抽象了 send 方法，为啥没有抽象 receive 用于接收数据了？

2.Endpoint 接口的 send 方法和 ChannelHandler 接口中的 sent 方法的区别和联系是啥样的了？

**Comment by chickenlj** [comment]
建议升级到 2.7.3 或更新版本
