### ISSUE TITLE
if use hessian protocol，RpcContext's attachment case insensitive

### ISSUE THREAD

**Issue by slievrly** [apache/dubbo#5253]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

The result I expect is that the attachment obtained by the provider after the hession protocol is case sensitive.

** 是否可以将attachment 的HashMap 改成 CaseInsensitiveMap? **
### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:
Http11InputBuffer:

![image](https://user-images.githubusercontent.com/8758457/67666880-a7b4a800-f9a7-11e9-9b96-2199ac19bbe2.png)

![image](https://user-images.githubusercontent.com/8758457/67667209-48a36300-f9a8-11e9-89c0-737c5098f86b.png)

**Comment by chickenlj** [comment]
I think it's a convention of the HTTP specification to keep headers lowercase.

**Comment by chickenlj** [comment]
Reopen if you have diferent opinions.

**Comment by slievrly** [comment]
@chickenlj  If so, the developer should be told that the key of the Attachment is always lowercase.
