### ISSUE TITLE
why show this : Ignore empty notify urls for subscribe url

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#5258]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: win7
* Java version: 1.8

Java Code：
package com.ghy.www;

import com.ghy.www.dubbo.provider.service.ISayHello;
import com.ghy.www.dubbo.provider.service.SayHello;
import org.apache.dubbo.config.ApplicationConfig;
import org.apache.dubbo.config.RegistryConfig;
import org.apache.dubbo.config.ServiceConfig;

import java.io.IOException;

public class Application1 {
    public static void main(String[] args) throws IOException {
        SayHello helloService = new SayHello();
        // 服务配置
        ServiceConfig<ISayHello> serviceConfig = new ServiceConfig<ISayHello>();
        // 设置应用名称
        serviceConfig.setApplication(new ApplicationConfig("dubbo2-server"));
        // 设置注册中心
        serviceConfig.setRegistry(new RegistryConfig("multicast://224.5.6.7:1234?unicast=false"));
        // 设置业务接口
        serviceConfig.setInterface(ISayHello.class);
        // 设置业务实现类
        serviceConfig.setRef(helloService);
        // 发布服务
        serviceConfig.export();
        // 进程不销毁
        System.in.read();

    }

}

run after show WARN：
main  WARN multicast.MulticastRegistry:  [DUBBO] Ignore empty notify urls for subscribe url provider://192.168.61.250:20880/com.ghy.www.dubbo.provider.service.ISayHello?anyhost=true&application=dubbo2-server&bind.ip=192.168.61.250&bind.port=20880&category=configurators&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.ghy.www.dubbo.provider.service.ISayHello&methods=sayHello&pid=9900&release=2.7.4.1&side=provider&timestamp=1572321725880, dubbo version: 2.7.4.1, current host: 192.168.61.250

why ?
thank very much!

**Comment by chickenlj** [comment]
That means it's an empty notification of configuratos: `category=configurators`

**Comment by maxiaodong58** [comment]
> category

注册中心    ：nacos 
dubbo版本 : 2.7.3

心跳检测 抛这个异常。不懂什么意思！

**Comment by startjava** [comment]
你用组播了吧？？无线路由器？？？



发自我的iPhone


------------------ Original ------------------

**Comment by gMan1990** [comment]
我这启动时也显示 `2022-11-20 01:40:18,310  WARN [main] org.apache.dubbo.registry.support.AbstractRegistry.(AbstractRegistry.java:450)  [DUBBO] Ignore empty notify urls for subscribe url provider://*, dubbo version: 3.0.9, current host: *`

**Comment by gMan1990** [comment]
> That means it's an empty notification of configuratos: `category=configurators`

不懂，所以应该怎么fix it?

**Comment by AlbumenJ** [comment]
> > That means it's an empty notification of configuratos: `category=configurators`
> 
> 不懂，所以应该怎么fix it?

使用的是 zk 注册中心吗

**Comment by gMan1990** [comment]
@AlbumenJ nacos

**Comment by AlbumenJ** [comment]
@gMan1990 这个是 nacos 注册中心地址为空了，导致 Dubbo 侧触发了推空保护

**Comment by gMan1990** [comment]
@AlbumenJ 那我应该怎么调整呢？

**Comment by AlbumenJ** [comment]
> @AlbumenJ 那我应该怎么调整呢？

查下为什么 nacos 注册中心地址会为空，是否是预期的。

**Comment by gMan1990** [comment]
@AlbumenJ 应该不是`空`的问题吧，不然别人也调用不到这个服务

**Comment by AlbumenJ** [comment]
> @AlbumenJ 应该不是`空`的问题吧，不然别人也调用不到这个服务

这个日志确实就是注册中心推送地址为空的时候报的

**Comment by gMan1990** [comment]
@AlbumenJ `注册中心推送地址` 怎么配置？

**Comment by AlbumenJ** [comment]
> @AlbumenJ `注册中心推送地址` 怎么配置？

出现这个日志的时候看一下 nacos 控制台上面的记录

**Comment by gMan1990** [comment]
@AlbumenJ 不太会，求帮助 /(ㄒoㄒ)/~~

**Comment by zhouyu00** [comment]
我这边也有类似的问题，怀疑是nacos集群节点同步数据不一致，而我本地又添加了    dubbo.application.metadata-type: remote 这个配置导致的
