### ISSUE TITLE
能不能把官网的文档更新一下啊，这是坑啊！

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#5263]
<dubbo:registry protocol="multicast" address="224.5.6.7:1234">
	    <dubbo:parameter key="unicast" value="false" />
	</dubbo:registry>

官网组播注册中心使用如上配置，提供者和消费者通讯时出现异常。

但是使用如下配置就可以，
<dubbo:application name="demo-consumer">
        <dubbo:parameter key="unicast" value="false" />
</dubbo:application>

<dubbo:consumer>
        <dubbo:parameter key="unicast" value="false" />
</dubbo:consumer>
这个解决办法也是在另外一个issue中提供的：
https://github.com/apache/dubbo/issues/4136

建议尽快更新官网的文档啊，这样后来人才不会再次掉到坑里！

**Comment by jamesxuhaozhe** [comment]
如果确实是这个问题的话，楼主应该也可以向官网的github repo提交pr的吧

**Comment by luyuanwan** [comment]
我也发现，有许多功能官网上 查不到 ，比如RpcContext的使用

**Comment by xishian** [comment]
自己写文档吧，dubbo是一个意外

**Comment by chickenlj** [comment]
请往官网提交 pr
