### ISSUE TITLE
[Unit Test Failure] ServiceConfigTest.testDelayExport() and ServiceConfigTest.testExport() failing

### ISSUE THREAD

**Issue by jamesxuhaozhe** [apache/dubbo#5266]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5-SNAPSHOT
* Operating System version: Max OS 10.14.5
* Java version: Oracle jdk 1.8.0_131

### Steps to reproduce this issue

1. checkout master branch
2. checkout HEAD 15d8084
3. run command: ./mvnw clean install -DskipTests=false & ./mvnw clean test-compile failsafe:integration-test

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

The build should run successfully

### Actual Result

What actually happens?

Unit test failing 

If there is an exception, please attach the exception trace:

```
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ServiceConfigTest.testDelayExport:173 
Expected: a collection with size <1>
     but: collection size was <0>
[ERROR]   ServiceConfigTest.testExport:155 
protocol.export(
    <any org.apache.dubbo.rpc.Invoker>
);
Wanted 1 time:
-> at org.apache.dubbo.config.ServiceConfigTest.testExport(ServiceConfigTest.java:155)
But was 2 times:
-> at org.apache.dubbo.config.mock.MockProtocol2.export(MockProtocol2.java:36)
-> at org.apache.dubbo.config.mock.MockProtocol2.export(MockProtocol2.java:36)


[INFO] 
[ERROR] Tests run: 557, Failures: 2, Errors: 0, Skipped: 2

```

**Comment by qinliujie** [comment]
Had already fix that,thx~
