### ISSUE TITLE
ApplicationConfig->updateParameters method frist Parameter not used

### ISSUE THREAD

**Issue by malagebi** [apache/dubbo#5267]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue
路径：org.apache.dubbo.config.ApplicationConfig
1. 私有方法 updateParameters 第一个参数，并没有被使用
![微信截图_20191030140415](https://user-images.githubusercontent.com/10953561/67832964-4105ca80-fb1e-11e9-9f11-4efaead6fff0.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by wangkezun** [comment]
It's been resolved. Please checkout the latest code.

**Comment by chickenlj** [comment]
Thanks for reporting, it's been fixed.
