### ISSUE TITLE
Unsupported protocol http in notified url

### ISSUE THREAD

**Issue by chengxj** [apache/dubbo#5268]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.7
* Operating System version: windows7
* Java version: 1.7.0_79

### Steps to reproduce this issue

1. provider
<dubbo:service version="1.0.0" group="dubbo" protocol="http" 
   interface="dubbo.api.ApiService" ref="apiService"/>
2. consumer
<dubbo:reference id="apiService" version="1.0.0" group="dubbo" protocol="http" check="false" interface="dubbo.api.ApiService"/>
3.log
com.alibaba.dubbo.registry.integration.RegistryDirectory: Unsupported protocol http in notified url:

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by boomblog** [comment]
HTTP dependencies are not added

**Comment by chengxj** [comment]
> HTTP dependencies are not added

你具体指的是什么依赖？

**Comment by chengxj** [comment]
> HTTP dependencies are not added
谢谢，的确是因为缺少HTTP相关的JAR引发的。我已经调试好了。

**Comment by chengxj** [comment]
构建dubbo-2.6.7项目时，使用http协议通信出现报错Unsupported protocol http in notified url，是因为在项目中少引了

**Comment by chengxj** [comment]
构建dubbo-2.6.7项目时，使用http协议通信出现报错Unsupported protocol http in notified url，是因为在项目中少引了		
```
<dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>dubbo-rpc-http</artifactId>
</dependency>
<dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
</dependency>
```
