### ISSUE TITLE
dubbo设置"dubbo.registry.simplified = true"后，服务名称信息丢失

### ISSUE THREAD

**Issue by makingtime** [apache/dubbo#5274]
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [√] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: Windows 10 专业版 1809 64位
* Java version: 1.8.0.191
* Nacos version: 1.1.3
* Redis version: 5.0.6

### Steps to reproduce this issue

1.使用nacos作为注册中心 
dubbo.registry.protocol = nacos
dubbo.registry.address = 172.16.1.10:8848

2. 启用meta data report
dubbo.metadata-report.address = redis://172.16.1.11:6379

3. 设置registry simplified
dubbo.registry.simplified = true

### Expected Result

nacos的服务列表中service名称正常显示
如：consumers:com.xxx.services.DubboServiceProviderA:1.0.0:

### Actual Result

service名称丢失
consumers:::1.0.0:

Service详情中的元数据
```
path=com.xxx.services.DubboServiceProviderA
protocol=consumer
application=dubbo-consumer-a
release=2.7.4.1
dubbo=2.0.2
check=false
category=consumers
version=1.0.0
```

**Comment by jimgreat** [comment]
see https://github.com/apache/dubbo/issues/4621

**Comment by chickenlj** [comment]
duplicate as #4621
