### ISSUE TITLE
dubbo的流量复制

### ISSUE THREAD

**Issue by ywf4026** [apache/dubbo#5279]
如果想做dubbo的流量复制，有没有好的方案和建议？

谢谢了

**Comment by CodingSinger** [comment]
能详细说明下啥是流量复制以及用途吗

**Comment by ywf4026** [comment]
流量复制就是 一个请求可以变成两个一模一样的请求，可以拿其中一个请求去做别的事情，比如线上流量引到线下去做测试等用途

**Comment by LiZhenNet** [comment]
这个应该是nginx 做的事
