### ISSUE TITLE
dubbo是否允许在运行期，由客户端动态选择序列化方式？例如，A, B同时调用同一个provider的同一个方法，A选择用fastjson序列化，B选择用hessian2序列化

### ISSUE THREAD

**Issue by bedlimate** [apache/dubbo#5287]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
当前版本并不支持这么做，理论上通过双方协商能够做到，但是我们并不打算提供这种支持
