### ISSUE TITLE
java.lang.IllegalStateException: Too much registries found (dubbo:reference 并没有按照id匹配)

### ISSUE THREAD

**Issue by 17683908932** [apache/dubbo#5289]
在properties里面配置多个
dubbo.registry.address=xxxxxx
dubbo.registry.aaa.address=xxxxxx
在xml里面配置
<dubbo:reference id="xx" interface="xxxx" version="1.0.0" registry="aaa"/>
就会报错 Too much registries found
实际上配置的dubbo.registry.aaa.address=xxxxxx 并不能根据aaa来匹配
![image](https://user-images.githubusercontent.com/54841788/68372350-9d4e9700-017b-11ea-95c9-425b66cce6fe.png)

org.apache.dubbo.config.AbstractInterfaceConfig.convertRegistryIdsToRegistries()
if (((List)tmpRegistries).size() > ids.length) {
                throw new IllegalStateException("Too much registries found, the registries assigned to this service are :" + this.registryIds + ", but got " + ((List)tmpRegistries).size() + " registries!");
            }
是不是应该需要在 tmpRegistries 里面根据 id 取对应的 Registries

**Comment by chickenlj** [comment]
如果有多个 registry，请用：
```properties
dubbo.registries.aaa.address=xxxxxx
```

**Comment by 17683908932** [comment]
是的 我那样做了
dubbo.registries.product.address=xxxxxx
 但是报错了 java.lang.IllegalStateException: Too much registries found
debug 发现了一个id为zookeeper的和一个id为product的两个 [截图里面显示的]
zookeeper是默认的zk
product是特别的zk

**Comment by jasonjoo2010** [comment]
sample of dubbo.properties:

```properties
# main registry
dubbo.registry.id=registryMain
dubbo.registry.address=${dubbo.registry.url1}
dubbo.registry.file=logs/dubbo-registry-main.properties
dubbo.registry.protocol=zookeeper

# another
dubbo.registries.registryOther.id=registryOther
dubbo.registries.registryOther.address=${dubbo.other.registry.url}
dubbo.registries.registryOther.file=logs/dubbo-registry-other.properties
dubbo.registries.registryOther.protocol=zookeeper
# default not to register to it
dubbo.registries.registryOther.register=false
```

And you must specific the default registry to subscribe/publish in your <dubbo:consumer /> or <dubbo:provider /> if you don't want them working together.
