### ISSUE TITLE
在提供者不可用情况下出现的消费者无限注册问题

### ISSUE THREAD

**Issue by sourirer** [apache/dubbo#5300]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: macOS
* Java version: 1.8

### Steps to reproduce this issue

1. 使用 GenericService 进行泛化调用
2. 提供者provider不可用
3. 吞噬抛出的异常并循环继续尝试调用（不重启）

` ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
        reference.setApplication(this.applicationConfig);
        reference.setRegistry(this.registryConfig);
        // 接口名
        reference.setInterface(interfaceClass);
        // 声明为泛化接口
        reference.setGeneric(true);
        //禁用重试,避免某些场景产生重复数据调用
        reference.setRetries(0);

        ReferenceConfigCache cache = ReferenceConfigCache.getCache();
        while (true) {
            try {

                GenericService genericService = cache.get(reference);
                genericService.$invoke(methodName, paramClassPath, params);
                Thread.sleep(10);

            } catch (Exception e) {
                e.printStackTrace();
            }
        }`

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

1，消费者成功注册；
2，打印异常并继续尝试调用；
3，消费者注册节点不增加；

### Actual Result

1，消费者成功注册；
2，打印异常并且继续尝试调用；
3，消费者注册节点随着尝试次数的增加而增加并且无上限；

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by sourirer** [comment]
阅读源码后判断为，注册动作发生在invoker的可用状态判断之前。
当invoker不可用时，没有取消注册的动作。
在重复尝试获取invoker的时候，会由于refer为null再一次进行初始化。导致不断的重复注册。

**Comment by CodingSinger** [comment]
Can you provide a complete example in this issue?

**Comment by sourirer** [comment]
> Can you provide a complete example in this issue?

I have fix the problem by set check="false",so this issue only will occur while check="true" and program won't be interrupt by exception.

I don't think it's a real bug.
