### ISSUE TITLE
[UT]AbstractMetadataReportFactoryTest is not stable

### ISSUE THREAD

**Issue by jasonjoo2010** [apache/dubbo#5304]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: *
* Operating System version: *
* Java version: *

### Steps to reproduce this issue
Run it in different system having multiple network adapters.

### Expected Result
Stably successful.

### Actual Result
Fail sometimes.

**Comment by mercyblitz** [comment]
How about the different results?

**Comment by jasonjoo2010** [comment]
> How about the different results?

The root cause is due to the different logic on fetching the local hostname.

Please refer to #5303
