### ISSUE TITLE
Mistake in the document.

### ISSUE THREAD

**Issue by Billzaifei** [apache/dubbo#5305]
- [1 ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [1] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Pls. provide [GitHub address] to reproduce this issue.
http://dubbo.apache.org/en-us/docs/user/references/registry/zookeeper.html

Reference from above url as below:

Description on registration procedure:

When service provider boots up: write service URL address under directory /dubbo/com.foo.BarService/providers
When service consumer boots up: subscribe to /dubbo/com.foo.BarService/providers for provider's URL addresses. At the same time, write consumer's URL address under /dubbo/com.foo.BarService/providers.

Expect:

When service consumer boots up: subscribe to /dubbo/com.foo.BarService/providers for provider's URL addresses. At the same time, write consumer's URL address under /dubbo/com.foo.BarService/consumers.

**Comment by wangkezun** [comment]
Thanks for your feedback! This issue should be reported in https://github.com/apache/dubbo-website. And I just send a pr to fix this issue. You can find it here https://github.com/apache/dubbo-website/pull/525

**Comment by Billzaifei** [comment]
Thanks for the guiding. And the fixing checked.
