### ISSUE TITLE
dubbo-admin服务提供者列表出现相同的记录

### ISSUE THREAD

**Issue by hadesvip** [apache/dubbo#5318]
### 使用dubbo-admin的时候发现服务提供者列表出现相同的记录数
![image](https://user-images.githubusercontent.com/9640832/68739669-500f7100-0624-11ea-9c92-e7cda6fa5b3f.png)

### 环境

* Dubbo version: 2.5.3
* Operating System version: centos7
* Java version: 1.8

**Comment by guohao** [comment]
@hadesvip Try this ops https://github.com/apache/dubbo-admin
