### ISSUE TITLE
registry url  bean.name is service interface not bean id

### ISSUE THREAD

**Issue by RyouZhang** [apache/dubbo#5320]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5-SNAPSHOT
* Operating System version: macos 10.15.2
* Java version: openjdk 11.0.5

**Comment by chickenlj** [comment]
Please provide more details
