### ISSUE TITLE
2.7.4.1版本基于注解配置RegistryConfig时setPort()方法不生效

### ISSUE THREAD

**Issue by Ninwoo** [apache/dubbo#5322]
## 问题描述
使用如下方式配置RegistryConfig bean时

```java
    @Bean
    public RegistryConfig registryConfig() {
        RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setProtocol("zookeeper");
        registryConfig.setAddress("localhost");
        registryConfig.setPort(2181);
        return registryConfig;
    }
```

提示无法与zookeeper建立连接，调试代码发现，zookeeper链接为

`zookeeper://localhost:9090/ConfigCenterConfig?check=true&config-file=dubbo.properties&group=dubbo&highest-priority=false&namespace=dubbo&timeout=3000`

使用了9090端口，未使用2181端口，registryConfig.setPort()不生效。

对比测试，使用registryConfig.setAddress("localhost:2181")方式可以生效。

**Comment by lkj41110** [comment]
i think it is a bug,when using  zookeeper and using it as a default configuration center.

**Comment by lkj41110** [comment]
`ConfigCenterConfig` and `MetadataReportConfig` don't have `port` attribute as well as  RegistryConfig。
When using  zookeeper and `ConfigCenterConfig` is null,don't set port attribute.
```
                    cc.getParameters().put(CLIENT_KEY, registryConfig.getClient());
                    cc.setProtocol(registryConfig.getProtocol());
                    cc.setAddress(registryConfig.getAddress());
                    cc.setNamespace(registryConfig.getGroup());
                    cc.setUsername(registryConfig.getUsername());
                    cc.setPassword(registryConfig.getPassword());
                    cc.setHighestPriority(false);
                    configManager.addConfigCenter(cc);
```

**Comment by guohao** [comment]
@lkj41110 Could you help to fix it ?

**Comment by lkj41110** [comment]
I am willing to do it
