### ISSUE TITLE
consumer 为什么无法配置序列化方式？

### ISSUE THREAD

**Issue by ghost** [apache/dubbo#533]
我想请问下，为什么consumer无法配置序列化方式？
    
    <dubbo:consumer id="goodsServiceConsumer" registry="goodsServiceClientRegistry"
                    init="false" check="${goodsService.dubbo.consumer.check}" retries="0"/>

在provider里面是可以配置并且使用成功的
    
    <dubbo:provider registry="goodsRegistry"
                    protocol="goodsProtocol"
                    cluster="${goodsService.dubbo.provider.cluster}"
                    loadbalance="${goodsService.dubbo.provider.loadbalance}"
                    serialization="${goodsService.dubbo.provider.serialization}"
                    retries="${goodsService.dubbo.provider.retries}"
                    timeout="${goodsService.dubbo.provider.timeout}"
                    proxy="javassist"
                    delay="-1"/>

**Comment by chickenlj** [comment]
可以先配置在dubbo:protocol标签。consumer、provider存在配置的不对等，会考虑在consuemr xsd中增加配置项

**Comment by chenguizhong** [comment]
在consumer端配置感觉不合理！
个人建议：
=========================
1、序列化方式应该由服务端指定
2、通过协议传到客户端
3、当客户端不存在相应的反序列化方式时，抛序列化方式不存在异常
4、协议支持自定义序列化方式。
=========================
欢迎指正～

**Comment by cnhans** [comment]
因为client 都是由服务提供者编写的，我们采用common server client模式，并不是楼上那样，所以不存在不透明沟通难的问题。

**Comment by uglycow** [comment]
the provider is aware of what serialize protocol is  suitable for the DO. So, i also think
it's the provider's work to choose which serialization to use.
