### ISSUE TITLE
Dubbo 2.7.4.1 Generic true , metadata is null, service  Is not normal

### ISSUE THREAD

**Issue by SmileTower** [apache/dubbo#5331]
Dubbo Service  register org.apache.dubbo.rpc.service.GenericService subclass 
metadata-report is null

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue
1
dubbo.registry.simplified=true
dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
Dubbo Service  register org.apache.dubbo.rpc.service.GenericService subclass 
metadata-report is null

The service cannot be invoked normally

org.apache.dubbo.metadata.integration.MetadataReportService#publishProvider

org.apache.dubbo.metadata.integration.MetadataReportService#needStore  == false

2.
dubbo.registry.simplified=false
dubbo.registry.address=zookeeper://127.0.0.1:2181
 
This is OK

**Comment by wuzhipeng7cc** [comment]
see #4621

**Comment by chickenlj** [comment]
Fixed in #5465
