### ISSUE TITLE
@Service和@Reference注解timeout不生效问题

### ISSUE THREAD

**Issue by cyzhaotmind** [apache/dubbo#5332]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment
* Dubbo version: 2.7.3
* Operating System version: xxx
* Java version: 1.8
* Springboot: 2.1.8
* nacos: 1.1.3

### Steps to reproduce this issue

1. 在@Reference配置指定方法的超时时间2000,其他地方的超时配置全去掉
2. 测试
3. dubbo使用了超时时间1000,即@Reference的配置不生效

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
1. 关于超时时间的优先级,我的理解是@Reference>@Service>consumer的yml配置>provider的yml配置
2. 在provider和consumer的bootstrap.yml里使用dubbo.consumer.timeout和dubbo.provider.timeout配置各自的全局超时时间
3. 在@Reference和@Service注解上配置指定方法或指定类的超时时间
4. 期望通过以上方式合理的控制超时时间

### Actual Result

1. springboot+dubbo+nacos项目能够正常运行
2. 只在consumer的yml里使用dubbo.consumer.timeout配置超时时间,生效,符合预期
3. 注释掉2的配置,系统使用了dubbo的默认超时时间1000,符合预期
4. 只在 consumer使用@Reference(version = "${this.version}", timeout = 6000) 不符合预期 ,期望使用6000,测试结果显示使用了默认的1000
5. 只在consumer使用@Reference(version = "${this.version}"  ,methods = {
            @Method(name = "xxxMethod", timeout = 5000)
    })  不符合预期 期望使用配置的,测试结果显示使用了默认的1000
6. 只在provider配置@Service(version = "${this.version}", methods = {
        @Method(name = "xxxMethod", timeout = 21000)
}) 不符合预期 期望使用配置的,测试结果显示使用了默认的1000
7. 只在@Service(version = "${this.version}", timeout = 4000)配置超时时间, 符合预期
8. 在provider的yml里配置dubbo.provider.timeout=5000,并在@Service(version = "${this.version}", timeout = 4000),  不符合预期,测试结果是5000,期望是service上的能覆盖全局的

总结:  
1. 请问是我优先级理解错误,还是@Reference和@Service注解配置不生效
2. 如何实现在一个地方可以配置整体的超时时间,又可以在特定的接口或者方法上配置特殊的超时时间

注: 
1.用的是org.apache.dubbo.config.annotation.Reference和org.apache.dubbo.config.annotation.Service
2. consumer是一个springboot项目 , provider是另一个springboot项目,服务的注册发现,提供给别的项目使用,都没有问题.

**Comment by zhouyongwei** [comment]
我也碰到一个关于超时时间的问题，看dubbo的文档建议不配置customer的超时时间，配置provider的超时时间，文档中说dubbo会使用provider的超时时间。  我在项目中配置了provider全局timeout为60s，customer没配置，结果还是1s就超时。

**Comment by cyzhaotmind** [comment]
@zhouyongwei 按你说的方式测试了一下,我这边倒是没出现你的说的情况,测试结果是使用了provider的超时时间
![image](https://user-images.githubusercontent.com/43691614/69035180-fb9e3400-0a1d-11ea-9602-f3945358cef2.png)

**Comment by chickenlj** [comment]
> 请问是我优先级理解错误,还是@reference和@service注解配置不生效
优先级正如你所理解的，没有问题

> dubbo使用了超时时间1000,即@reference的配置不生效
请问你用的是 org.apache.dubbo 包下的 @Reference 么

**Comment by zhouyongwei** [comment]
嗯，我这边debug结果是使用了provider的时间，没问题，之前的测试程序有问题。

发自我的iPhone

**Comment by cyzhaotmind** [comment]
@chickenlj 用了org.apache.dubbo.config.annotation.Reference和org.apache.dubbo.config.annotation.Service

**Comment by jimgreat** [comment]
Service和Reference 是不是在一个项目是启动的？

**Comment by tonyLee1** [comment]
@Service(version = XXX,
  methods = {
	@Method(timeout = 60000,name = "XXX")
  }
)
超时不生效，是因为优先级的问题吗？（备注：provide yml 设置了timeout = 5000，结果生效时间是5000）

**Comment by cyzhaotmind** [comment]
> @service(version = XXX,
> methods = {
> @method(timeout = 60000,name = "XXX")
> }
> )
> 超时不生效，是因为优先级的问题吗？（备注：provide yml 设置了timeout = 5000，结果生效时间是5000）

**Comment by quyf** [comment]
这个在dubbo-2.7.4的版本修复了
