### ISSUE TITLE
ConsumerContextFilter类中为什么不执行removeContext和removeServerContext方法，

### ISSUE THREAD

**Issue by learninghard-lizhi** [apache/dubbo#5335]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

1. 最近我的使用Dubbo框架的Java程序长时间不发布会出现内存使用不足的情况，通过线上dump文件发现InternalThreadLocal对象很多ReferenceQueue为null,但是对象空间还存在。具体JProfile分析截图如下
![image](https://user-images.githubusercontent.com/33508425/68990122-4b4bf680-088a-11ea-8d13-fa48e718779d.png)
2.  然后查看2.6.5的Dubbo源码发现，发现ConsumerContextFilter类中，并没有调用removeContext和removeServerContext方法，以及ContextFilter类中仅仅只调用了removeContext方法并没有调用removeServerContext。
3. 但是我看dubbo 的2.7.0的版本开始这2个类的实现都调用removeContext和removeServerContext方法，那是不是说明2.6.5的版本由于没有调用removeContext和removeServerContext方法，从而会导致内存泄漏以及线程对象可能会错乱的情况呢？

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
ConsumerContextFilter和ContextFilter在2.6.5版本应该要调用removeContext和removeServerContext方法来清楚当前线程赋值的对象。另外如果不升级dubbo版本如何去解决内存的问题呢？

### Actual Result

What actually happens?
Java持续不重启，运行时间过长，会出现内存一直在上升的情况。
If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
一般情况下，ThreadLocal 中的数据每次会被不同调用覆盖，不会无限增长，即使不清理大小和线程数基本也是正相关的。
