### ISSUE TITLE
dubbo+nacos多consumer时服务发现bug（2.7.4.1），内含复现demo

### ISSUE THREAD

**Issue by supercocoa** [apache/dubbo#5336]
### Environment

* Dubbo version: 2.7.4.1 + nacos 1.1.0
* Operating System version: linux/mac
* Java version: 1.8

### Steps to reproduce this issue

使用附件中的demo，分别启动provider工程和consumer工程，其中consumer工程通过DOUBLE_CONSUMER开关开启两个consumer，然后按以下表格中四种provider重启case后consumer再发rpc调用都会有问题：

| consumer号 | provider在本机重启 | provider在本机重启且换端口号 | provider在另一台机器重启 | provider在另一台机器重启且换端口号 | 先起一个provider再起consumer工程再起另一个机器的provider然后杀掉第一个provider |
|------------|--------------------|------------------------------|--------------------------|------------------------------------|--------------------------------------------------------------------------------|
| consumer1  | rpc大约10s+不通    | rpc通                        | rpc通                    | rpc通                              | rpc通                                                                          |
| consumer2  | rpc大约10s+不通    | rpc不通                      | rpc不通                  | rpc不通                            | rpc不通                                                                        |

以上情况当consumer工程中只有一个consumer时(关闭DOUBLE_CONSUMER开关)或者不用nacos用zk(关闭USE_NACOS开关)时都没有问题，切换端口号重启可以打开RANDOM_PORT开关测试

### Expected Result

使用nacos时多个consumer也能像zk一样正常

### Actual Result

使用nacos时多个consumer没有像zk一样正常

附件demo：
[dubbo-nacos-demo.zip](https://github.com/apache/dubbo/files/3854113/dubbo-nacos-demo.zip)

**Comment by supercocoa** [comment]
类似问题：  #4793  #5207 
@beiwei30   @cvictory   @tswstarplanet

**Comment by chickenlj** [comment]
多谢反馈，我们将尝试熟悉 nacos 的开发者一同协助解决。

**Comment by jimgreat** [comment]
我们把NacosRegistry.java中的
  if (!nacosListeners.containsKey(serviceName)) 
去掉了
目前使用正常

**Comment by easyhaloo** [comment]
嗯 NacosRegistry目前是单例模式
你这个相当于相同的服务名,nacosListeners只会保留一个serviceName的监听

说白了你两个consumer是在同一个jvm里面
![image](https://user-images.githubusercontent.com/32064710/69903573-34eb8200-13d6-11ea-9fca-a6b6656bb660.png)

**Comment by LittleDW** [comment]
影响了 dubbo 的 分组聚合

**Comment by mercyblitz** [comment]
It will be fixed and release in 2.7.5
