### ISSUE TITLE
最新Spring boot集成Dubbo 报错  No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.

### ISSUE THREAD

**Issue by YellowDoing** [apache/dubbo#5338]
* dubbo-spring-boot-starter  version: 2.7.4.1
* Spring Boot version: 2.2.1.RELEASE

`application.properties`
![image](https://user-images.githubusercontent.com/20732953/69009863-b1bd3b80-0994-11ea-86c7-a430367e4de2.png)

`DemoServiceImpl`
![image](https://user-images.githubusercontent.com/20732953/69009873-ca2d5600-0994-11ea-9dd5-906f75aae71a.png)

HhhhApplication 
`
@SpringBootApplication
@EnableDubbo
public class HhhhApplication {

    public static void main(String[] args) {
        SpringApplication.run(HhhhApplication.class, args);
    }
}`

报错信息
![image](https://user-images.githubusercontent.com/20732953/69009881-de715300-0994-11ea-86fb-b490b857b323.png)

`java.lang.IllegalStateException: No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config.`

**Comment by chickenlj** [comment]
I will check this problem soon.

**Comment by mercyblitz** [comment]
There is no error in my side, how to reproduce it?
