### ISSUE TITLE
dubbo代码强依赖yaml1.20的功能，但pom中未配置强依赖1.20的yaml

### ISSUE THREAD

**Issue by yangxuqiang1111** [apache/dubbo#5345]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
dubbo应该强依赖1.20yaml

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:
![image](https://user-images.githubusercontent.com/15937567/69050498-20ee6a80-0a3d-11ea-9326-df6ae9214a72.png)
```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
It's more likely that you are using an imcompatible yaml version
