### ISSUE TITLE
Nacos group name always be 'DEFAULT_GROUP'

### ISSUE THREAD

**Issue by SoccerClub** [apache/dubbo#5349]
### Environment

* Dubbo version: 2.7.3
* Operating System version: Win 10
* Java version: 1.8
* Nacos Client version: 1.1.3

### Steps to reproduce this issue

1.  The doRegister()  function of NacosRegistry class invoke namingService.registerInstance(serviceName, instance), which passes no groupName to nacos api, so the group name always be  'DEFAULT_GROUP'

**Comment by RojerAlone** [comment]
Dubbo don't support Nacos group now, you can use Nacos namespace to split different group service.

**Comment by SoccerClub** [comment]
> Dubbo don't support Nacos group now, you can use Nacos namespace to split different group service.

I see. Thanks

**Comment by s464425024** [comment]
you can see the dubbo-registry-nacos ,  the method doRegister use namingService.registerInstance(serviceName, instance);

NacosNamingService   the method registerInstance

public void registerInstance(String serviceName, Instance instance) throws NacosException {
        registerInstance(serviceName, Constants.DEFAULT_GROUP, instance);
}
