### ISSUE TITLE
2.7.4.1 springboot nacos消费者端version单独设置，在@Reference中不起作用

### ISSUE THREAD

**Issue by mengfei31** [apache/dubbo#5350]
**只在**@Reference(group = "XXX", version = "1.0.0")设置在引用上，**不在**application.yml中设置
dubbo. consumer. version= 1.0.0 不起作用，且会生成两个消费者一个 version=0.0.0，一个version=1.0.0，调用不到生产者。

环境：
springcloud+dubbo+nacos(配置中心，注册中心)

**Comment by mercyblitz** [comment]
It works.
