### ISSUE TITLE
telnet extend return no such command

### ISSUE THREAD

**Issue by kiwiflydream** [apache/dubbo#5354]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue
![image](https://user-images.githubusercontent.com/13311001/69123200-b93b2c80-0adb-11ea-90df-89868d248893.png)
![image](https://user-images.githubusercontent.com/13311001/69123211-bcceb380-0adb-11ea-99a7-ff96313d7b1e.png)

Pls. provide [GitHub address] to reproduce this issue.
[DEMO url](https://github.com/kiwiflydream/study-example/blob/master/study-dubbo-example/study-dubbo-example-provider/src/main/java/cn/coder4j/study/example/dubbo/provider/HelloTelnetHandler.java)

**Comment by fibbery** [comment]
你应该telnent你的dubbo.protocol.port
而不是dubbo.application.qos-port

**Comment by kiwiflydream** [comment]
> 你应该telnent你的dubbo.protocol.port
> 而不是dubbo.application.qos-port

😂，原来是这样，谢谢
