### ISSUE TITLE
dubbo 2.7.4.1 版本dubbo-demo 运行报错,无法初始化配置器

### ISSUE THREAD

**Issue by hzhxxx** [apache/dubbo#5364]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4
* Operating System version: win 10
* Java version: jdk 8u22

### Steps to reproduce this issue

dubbo 2.7.4 版本dubbo-demo 运行报错,无法初始化配置器
1. 运行 dubbo-demo-api-provider,使用 zookeeper 3.5,已经确认zk 正常。
 service.setRegistry(new RegistryConfig("zookeeper://192.168.1.203:2181"));
运行报错，错误位于 AbstractInterfaceConfig::useRegistryForConfigIfNecessary 
的 628 行
cc.getParameters().put(org.apache.dubbo.remoting.Constants.CLIENT_KEY,rc.getClient());
提示 rc.getClient() 为空

2. 使用 nacos 正常,修改代码，编译运行正常 
service.setRegistry(new RegistryConfig("nacos://192.168.1.207:8848"));

3. dubbo-demo-xml-provider 也是相同的错误

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
Exception in thread "main" java.lang.NullPointerException
	at org.apache.dubbo.config.AbstractInterfaceConfig.lambda$null$7(AbstractInterfaceConfig.java:628)
	at java.util.Optional.orElseGet(Optional.java:267)

**Comment by lkj41110** [comment]
#5219 ,please use 2.7.4.1

**Comment by yangzhi666** [comment]
![image](https://user-images.githubusercontent.com/24977234/70047742-95abd200-1603-11ea-838a-34c55908128e.png)
是由于demo中没有初始化这个map造成的。
估计是nacos的模式下，会从注册中心取回信息，从而初始化。
这个被开发人员落下了。。。。。

**Comment by chickenlj** [comment]
Please try 2.7.4.1 or later version.
