### ISSUE TITLE
Apollo config center not work via XML configuration

### ISSUE THREAD

**Issue by zhangyz-hd** [apache/dubbo#5365]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: ANY
* Java version: ANY(8 or above)

### Steps to reproduce this issue

1. Apollo config center not work via XML configuration
```
# vm parameter
-Dapp.id=ABC
```
```
<!-- configuration xml -->
<dubbo:config-center protocol="apollo" address="127.0.0.1:8080" namespace="dubbo">
    <dubbo:parameter key="env" value="DEV"/>
</dubbo:config-center>
```
2. And, this configuration is not friendly

### Objective
1. Apollo config center initialized via XML like
```
<dubbo:config-center protocol="apollo" address="127.0.0.1:8080" namespace="dubbo">
    <dubbo:parameter key="env" value="DEV"/>
    <dubbo:parameter key="app.id" value="ABC"/>
</dubbo:config-center>
```
2. Or var XML with System Properties: "-Dapp.id=ABC -Denv=DEV -Dapollo.meta=http://127.0.0.1:8080"
```
<dubbo:config-center protocol="apollo" namespace="dubbo"/>
```

**Comment by zhangyz-hd** [comment]
PR #5366

**Comment by chickenlj** [comment]
Thanks, I will take a review of the pull request.
