### ISSUE TITLE
telnet  ops invoke :no such command

### ISSUE THREAD

**Issue by tiyxing** [apache/dubbo#5368]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: mac os
* Java version: jdk8

### Steps to reproduce this issue

1. telnet ip:port
2. ls
3. help found no invoke command

![image](https://user-images.githubusercontent.com/38564000/69211938-b94e3180-0b9a-11ea-8365-9ad0a0ec62c7.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by fibbery** [comment]
你这是qos端口吧😄
你需要直接telnet dubbo提供服务的端口   dubbo.protocol.port

**Comment by tiyxing** [comment]
是的，thanks
