### ISSUE TITLE
Project code compilation error

### ISSUE THREAD

**Issue by liujianbigboss** [apache/dubbo#5369]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5-SNAPSHOT
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

A compilation error occurred when cloning the latest code to local, as follows: cannot resolve com.alibaba.spring: Spring context support: 1.0.4-snapshotPls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AJunze** [comment]
master分支，import项目时缺少com.alibaba.spring:Spring context support: 1.0.4-snapshot这个依赖，maven不能自动下载，github Spring context support 项目上面也只有master分支，最新是1.0.3，怎样才能找到？

**Comment by liujianbigboss** [comment]
应该是master分支的问题，我这边暂时是使用的2.7.4正式分支的代码自己编译运行，由于2.7.4已经归档没有分支了，你可以迁tag里面的2.7.4.希望对你有帮助。

**Comment by wallacefw1987** [comment]
我已經退回到tag dubbo-2.6.7編譯通過了

**Comment by chickenlj** [comment]
Sorry, has beed fixed.
