### ISSUE TITLE
dubbo telnet UP DOWN 按键处理失效

### ISSUE THREAD

**Issue by Yangjianbin** [apache/dubbo#5382]
我看源码输入的指令必须是 
private static final byte[] UP = new byte[]{27, 91, 65};

private static final byte[] DOWN = new byte[]{27, 91, 66};

但是我在客户端输入命令时候
结果为：dubbo>^[[A

然后打断点 看到源码中收到的字符数组为：[27, 91, 65,13,0] 把我输入的回车也加进去了；这样判断就不能返回true（boolean up = endsWith(message, UP)）

**Comment by chickenlj** [comment]
Would you like to submit a patch to fix this issue?

**Comment by hengyunabc** [comment]
我觉得这个 UP/DOWN 支持可以考虑去掉，因为在不同的平台，不同的软件差异是很大的。

以 jline 为例 https://github.com/jline/jline3 ，实际上要有一些native handler的处理才生效。

我在mac下面测试 item2 和原生的 terminal 都不支持输入 UP/DOWN 。

**Comment by 9526xu** [comment]
mac 下原生终端，iterm2 telnet 进入 Dubbo 后，中文都将乱码，
![image](https://user-images.githubusercontent.com/15943801/73746477-3cd9f080-4790-11ea-9b96-ed930f3e673b.png)
如果使用 SecureCRT telnet 却不会乱码。不知道各位是否碰到该情况？有解决办法吗？

> 编码都为 utf-8

**Comment by chickenlj** [comment]
see comment at https://github.com/apache/dubbo/pull/5535
