### ISSUE TITLE
dubbo-bom缺少dubbo管理

### ISSUE THREAD

**Issue by maxiaodong58** [apache/dubbo#5383]
为什么不在
`<dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-bom</artifactId>
        <version>${dubbo.version}</version>
        <type>pom</type>
        <scope>import</scope>
</dependency>`

放入 dubbo 子包的管理。我以为自己看错了，结果看了很多遍，还是没有
`<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>${dubbo.version}</version>
 </dependency>`

**Comment by chickenlj** [comment]
Good suggestion

**Comment by chickenlj** [comment]
Please check https://github.com/apache/dubbo/pull/5492
