### ISSUE TITLE
Does dubbo support native grpc

### ISSUE THREAD

**Issue by RojerAlone** [apache/dubbo#5388]
I find there's a module named dubbo-rpc-grpc, and the `doRefer` method throw a `UnsupportedOperationException` exception in `GrpcProtocol` class, so it means dubbo only support to called by native grpc consumer and don't support to call native grpc provider from dubbo consumer? and can't call each other by grpc protocol?

And more, the official website don't hava related document.

**Comment by chickenlj** [comment]
Hi, RojerAlone

Our goal is to support both running gRPC protocol inside Dubbo and interoperability between Dubbo-gRPC and native gRPC.

From which version did you encountered the `UnsupportedOperationException `? Please check the latest in the master branch and the gRPC sample in apache/dubbo-samples project.

The formal gRPC support is expected to be released in about two weeks.

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-grpc

**Comment by RojerAlone** [comment]
Sorry, my mistake, I didn't see that `GrpcProtocol` override the `protocolBindingRefer` method, thanks a lot.
And more, which version the formal gRPC support would release?

**Comment by chickenlj** [comment]
Expect to be released in 2.7.5, a version that is almost ready to vote.

**Comment by RojerAlone** [comment]
@chickenlj  thanks a lot

**Comment by RojerAlone** [comment]
@chickenlj I notice that 2.7.5 is released, and it seems I need to generate Java code by dubbo's proto generator, is there some detail docs about using grpc on dubbo?
