### ISSUE TITLE
Dubbo 2.6.x RpcContext.getServerContext().getAttachment(key) is null when consumer use generic

### ISSUE THREAD

**Issue by shadowmind** [apache/dubbo#5389]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.x
* Operating System version: MacOS 10.12.6 
* Java version: Java 1.8

### Steps to reproduce this issue

1. Build a provider demo, add RpcContext.getServerContext().setAttachment("key","value");
2. Build a consumer demo. Call provider service by generic.
3. RpcContext.getServerContext().getAttachment("key");

What do you expected from the above steps？
Get the value which provider set in the RpcContext.getServerContext() attachment

What actually happens?
Null. Can't get the value which provider set in the RpcContext.getServerContext() attachment

Cause:
GenericFilter return a new RpcResult without setting setAttachments

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
Merged.
