### ISSUE TITLE
 @Reference(async = true) 没有效果？

### ISSUE THREAD

**Issue by Lex-gu** [apache/dubbo#5391]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

1. consumer a 设置@Reference(async = true)
2. a调用服务b

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

a应该异步调用b服务

### Actual Result

依旧是同步调用，如果是XML配置的异步调用没有问题

**Comment by dyachkovD** [comment]
Same with` @Argument(index=0, callback = true)`. In this case Dubbo ignore `callback` argument while it not defined in XML `<dubbo:argument index="0" callback="true" />`

**Comment by chickenlj** [comment]
请升级到最新版本的 Dubbo，2.6.7。
或者 2.7.4.1。

新版本应该已经修复
