### ISSUE TITLE
dubbo protobuf compiler bug

### ISSUE THREAD

**Issue by RyouZhang** [apache/dubbo#5392]
if the proto def method like xxxxAync， the protoc-gen-dubbo-java will create a same name method。

**Comment by chickenlj** [comment]
The generated name should be `xxxxAyncAsync`, not the expected result in your case?

**Comment by RyouZhang** [comment]
but it xxxAsync

**Comment by RyouZhang** [comment]
ok， I get the issus。

**Comment by chickenlj** [comment]
Emm, I get what you mean here. Right offhand, I would say that we can consider this as a name convention restriction of Dubbo-gRPC that users must follow.

If you have any other ideas in mind, please let me know.
