### ISSUE TITLE
dubbo 主分支clone下来后，进行 build（install）失败。

### ISSUE THREAD

**Issue by Lavaong** [apache/dubbo#5393]
### Environment

* Dubbo version: 2.7.4.1
* Operating System version: win10 专业版
* Java version: 1.8.0_212

### Steps to reproduce this issue

1.git clone https://github.com/apache/dubbo.git dubbo
2.mvn clean source:jar install -Dmaven.test.skip

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result
Build Failure:
         Cause: can't get dubbo-config-spring:2.7.5 from maven repo.
I serarch two maven repos include apache and aliyun,Both can't find the artifactid

Just put your stack trace here!
```

**Comment by jrrx** [comment]
I meet the same issue.

**Environment**

- Dubbo version: master branch
- Operating System version: macOS Mojave 10.14.4
- java version:  1.8.0_144

**Steps to reproduce this issue:** 
same step as the issue reporter

**Actual Result**
[ERROR] Failed to execute goal on project dubbo-config-spring: Could not resolve dependencies for project org.apache.dubbo:dubbo-config-spring:jar:2.7.5-SNAPSHOT: Failure to find com.alibaba.spring:spring-context-support:jar:1.0.4-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]

**Comment by jrrx** [comment]
Hi, Lavaong:
Here is a temporary resolution:
find this file:   dubbo-dependencies-bom/pom.xml

change the version of tag alibaba_spring_context_support_version to 1.0.5, then you will build success.

<alibaba_spring_context_support_version>1.0.4-SNAPSHOT</alibaba_spring_context_support_version>

<alibaba_spring_context_support_version>1.0.5</alibaba_spring_context_support_version>

**Comment by Lavaong** [comment]
Hi ,@jrrx 
I also solved this problem by another way, I changed the branch to dubbo-v2.6.4 and successfully build it. later,I will try to use your method, thank you very much for your suggestion，~，~。
