### ISSUE TITLE
泛化调用时 接口的参数是抽象类,使用其实现类作为参数调不通

### ISSUE THREAD

**Issue by machuxin** [apache/dubbo#5397]
接口参数为抽象类，具体调用时，为对应的实现类。使用dubbo正常调用,没有问题。而使用泛化调用的时候，提示方法不存在。如接口为 String getPerson(Person person) ，正常调用时 使用 getPerson(Chinese); 但是泛化调用的使用，参数类型 我传Chinese显示方法不存在。而Person是抽象类，无法实例化

**Comment by imsunv** [comment]
you can put "class" key with Chinese class full name for value  in your Pojo Map when generic invoke

**Comment by machuxin** [comment]
> 泛型调用时，可以在Pojo Map中将带有中文类全名的“类”键作为值
我的意思是 Chinese extends Person，泛化调用的时候，不可以传Chinese,只能传Person。泛化调用无法实现 父类对象指向子类的引用。

**Comment by qinliujie** [comment]
you can do it like that 

```
package org.apache.dubbo.samples.generic.call.api;
public abstract class A 

public class B extends A 

public interface HelloService {
    String sayHello(A a);
}


```

```
        Map parameter = new HashMap();
        parameter.put("class", "org.apache.dubbo.samples.generic.call.api.B");
        parameter.put("name", "qinliujie");


        Object result = genericService.$invoke("sayHello", new String[]{"org.apache.dubbo.samples.generic.call.api.A"}, new Object[]{parameter});

```

**Comment by 407345725** [comment]
接口定义：
`SingleResult<CalculateSalaryFeedbackDTO> getCalculateSalaryFeedback(Long customerId, String salaryType, String requestId,
            Pair<String, Long> calculateSettingPair);`
泛化调用:
`      Map<String, Object> pairMap = Maps.newHashMap();
        pairMap.put("left", 3L);
        pairMap.put("right", 4L);
        pairMap.put("class", "org.apache.commons.lang3.tuple.MutablePair");

        Object result = genericService.$invoke("getCalculateSalaryFeedback",
            new String[] { "java.lang.Long", "java.lang.String", "java.lang.String", "org.apache.commons.lang3.tuple.Pair"},
            new Object[] { 1L, "2", "3", pairMap});
        System.out.println(result);`

**Comment by machuxin** [comment]
> you can put "class" key with Chinese class full name for value in your Pojo Map when generic invoke

thanks

**Comment by machuxin** [comment]
> 接口定义：
> `SingleResult<CalculateSalaryFeedbackDTO> getCalculateSalaryFeedback(Long customerId, String salaryType, String requestId, Pair<String, Long> calculateSettingPair);`
> 泛化调用:
> ` Map<String, Object> pairMap = Maps.newHashMap();
> pairMap.put("left", 3L);
> pairMap.put("right", 4L);
> pairMap.put("class", "org.apache.commons.lang3.tuple.MutablePair");
> 
> ```
>     Object result = genericService.$invoke("getCalculateSalaryFeedback",
>         new String[] { "java.lang.Long", "java.lang.String", "java.lang.String", "org.apache.commons.lang3.tuple.Pair"},
>         new Object[] { 1L, "2", "3", pairMap});
>     System.out.println(result);`
> ```
好的 我明白了 谢谢

**Comment by machuxin** [comment]
> you can do it like that
> 
> ```
> package org.apache.dubbo.samples.generic.call.api;
> public abstract class A 
> 
> public class B extends A 
> 
> public interface HelloService {
>     String sayHello(A a);
> }
> ```
> 
> ```
>         Map parameter = new HashMap();
>         parameter.put("class", "org.apache.dubbo.samples.generic.call.api.B");
>         parameter.put("name", "qinliujie");
> 
> 
>         Object result = genericService.$invoke("sayHello", new String[]{"org.apache.dubbo.samples.generic.call.api.A"}, new Object[]{parameter});
> ```

谢谢
