### ISSUE TITLE
Optimize the configuration of  “multiple-registry”

### ISSUE THREAD

**Issue by zhangyz-hd** [apache/dubbo#5399]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: ANY
* Java version: ANY

### Description

We started using "registry-multiple" for high availability of Registry Center, but found that "multiple-registry" configuration was not beautiful enough.
We wish to transform like:
```
<dubbo:registry protocol="multiple">
    <dubbo:child-registry key="z1" protocol="zookeeper" address="12.34.56.1:2181,12.34.56.2:2181,12.34.56.3:2181"/>
    <dubbo:child-registry key="z2" protocol="zookeeper" address="12.34.56.4:2181" register="false"/><!-- subscribe only-->
    <dubbo:child-registry key="r1" protocol="redis" address="9.8.7.6:3030"/>
</dubbo:registry>
```

And we have completed code.

**Comment by zhangyz-hd** [comment]
And then, via properties file, it could configured like this:
```
dubbo.registry.protocol=multiple
dubbo.registry.parameters[child.z1]=zookeeper://12.34.56.1:2181,12.34.56.2:2181,12.34.56.3:2181
dubbo.registry.parameters[child.z2]=zookeeper://12.34.56.4:2181?register=false
dubbo.registry.parameters[child.r1]= redis://9.8.7.6:3030
```

Is this more readable?

**Comment by chickenlj** [comment]
Personally, I think the example configuration code is too complex. 
Could you please escribe your main concern of the previous mechanism?

**Comment by zhangyz-hd** [comment]
> Personally, I think the example configuration code is too complex.
> Could you please escribe your main concern of the previous mechanism?

multiple-registry的实现思路是非常ok的，但是配置方式非常不友好；
properties配置时，需要写成
```
dubbo.registry.address=multiple://127.0.0.1?application=vic&service-registry=reg1,reg2&reference-registry=reg1,reg2
```
或者
```
dubbo.registry.address=multiple://127.0.0.1?application=vic
dubbo.registry.parameters[service-registry]=reg1,reg2
dubbo.registry.parameters[reference-registry]=reg1,reg2
```
目前使用中发现这几个问题：
1. 人为拆分了service-registry和reference-registry属性，为何不参照dubbo-registry的register和subscribe属性去定义只注册/只订阅。
2. 多个注册中心用,（逗号）分割，但是zookeeper集群的多个ip地址之间默认就是,（逗号）分割，如zookeeper://ip1,ip2,ip3，这种在multiple-registry中就没法用了，也无法使用zookeper://ip1?backup=ip2,ip3的语法

如果不改变dubbo.xsd语法，比较友好的定义方式是：xml中
```
<dubbo:registry protocol="multiple">
    <dubbo:parameter key="child.z1" value="zookeeper://ip1,ip2,ip3"/>
    <dubbo:parameter key="child.z2" value="zookeeper://ip4,ip5,ip6" register="false"/><!-- 只订阅-->
    <dubbo:parameter key="child.r1"  value="redis://ip7"/>
</dubbo:registry>
```
或者properties中
```
dubbo.registry.protocol=multiple
dubbo.registry.parameters[child.z1]=zookeeper://ip1,ip2,ip3
dubbo.registry.parameters[child.z2]=zookeeper://ip4,ip5,ip6?register=false
dubbo.registry.parameters[child.r1]= redis://ip7
```

如果可以增加child-registry定义，那么也是可以做到1楼/2楼的语法描述。

**Comment by chickenlj** [comment]
@zhangyz-hd multi registry 我们这边还在想是否继续维护，感觉不论从配置还是实现上复杂度都有点高：目前是多个注册中心的数据聚合到一起，构成一个虚拟的注册中心，然后选址。

你看这个多注册中心订阅的设计是否能满足需求？
https://github.com/apache/dubbo/blob/master/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/support/registry/ZoneAwareClusterInvoker.java

**Comment by chickenlj** [comment]
如下示例：
1. 业务部署假设是双注册中心
![image](https://user-images.githubusercontent.com/18097545/70682056-8ea65300-1cd8-11ea-8e9b-cf6284e04e48.png)


2. 则对应消费端，先在注册中心间选择，再到选定的注册中心选址
<img width="758" alt="DDECDDAD-81C2-41DB-A687-BF958EE03D6D" src="https://user-images.githubusercontent.com/18097545/70682076-9cf46f00-1cd8-11ea-94d2-1a2e0dcdbe5d.png">

**Comment by chickenlj** [comment]
多注册中心间的选址策略，目前设计的有
<img width="702" alt="F7ED4F53-B47E-42E3-AB19-8480AC8B8979" src="https://user-images.githubusercontent.com/18097545/70682166-de851a00-1cd8-11ea-8e87-bac27389ca7f.png">

**Comment by zhangyz-hd** [comment]
multiple-registry相比与多个registry摊开来用，有其独特的优势：

1. RegistryDirectory数量：multiple下，RegistryDirectory的数量是服务数N，而多个registry下，RegistryDirectory的数量是N*registry数，这里就存在内存浪费问题，因为urlInvokerMap开销不小。

2. loadbalance的处理逻辑：在多个registry下，先筛选第一个registry对应的RegistryDirectory下的可用invokers做random，如果第一个registry下无invokers，再筛选第二个，当第一个注册中心短暂故障或者提供者不完整，消费者就有影响。

我们在评估验证了multiple-registry的模式后，发现很适合解决上述问题，使用场景包括：

1. 多zookeeper集群共同使用时，避免对消费者带来额外的内存压力和loadbalance异常。

2. 异构注册中心集群：一方面一个园区内部署多个异构的注册中心，如zookeeper+xxxx，用来避免单一技术栈带来的可用性问题。另一方面，新注册中心上线试点，旧注册中心逐步平滑退出，可以保证应用无业务影响。

我们使用multiple-registry，并不是把所有zone的registry合并起来，只是把一个zone内部的合并起来，所以不是ZoneAwareClusterInvoker实现的场景。

当然multiple-registry目前完成度并不是非常高，有一些细节我们可以来做进一步优化，包括开发体验以、内存开销、notify逻辑方面。

**Comment by icc99** [comment]
> 多注册中心间的选址策略，目前设计的有
> <img alt="F7ED4F53-B47E-42E3-AB19-8480AC8B8979" width="702" src="https://user-images.githubusercontent.com/18097545/70682166-de851a00-1cd8-11ea-8e87-bac27389ca7f.png">

同zone优先 客户端要怎么配置???
