### ISSUE TITLE
Compilation Fails in Mac OS

### ISSUE THREAD

**Issue by steve0801** [apache/dubbo#5404]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: MacOS Catalina 10.15.1
* Java version: 1.8.0_91

### Steps to reproduce this issue

1.  
I just forked the proj and tried to compile the whole proj: 
mvn clean install -DskipTests=true

then I got a compilation error. 

2. It runs wrong in Win 10 either.

### Expected Result

Build Success

### Actual Result

I got this error:
_Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.1:compile-custom (default) on project dubbo-serialization-protobuf: Could not transfer artifact org.apache.dubbo:protoc-gen-dubbo-java:exe:osx-x86_64:1.19.0-SNAPSHOT from/to apache.snapshots (https://repository.apache.org/snapshots): Remote host closed connection during handshake_

**Comment by steve0801** [comment]
I suppose that I should build it in Linux rather than MacOS.

<img width="1169" alt="screenshot" src="https://user-images.githubusercontent.com/17006547/69909583-e40c7580-1437-11ea-8500-87a34b0bb4f9.png">

**Comment by chickenlj** [comment]
Both the SNAPSHOT version of Linux and OSX have been released. Please update the master branch for the latest code and try again.

**Comment by steve0801** [comment]
Seems it doesn't work so I have to re-open it.

Pls look at the link, and you will see linux version only existing in Central Repository:
[https://repository.apache.org/snapshots/org/apache/dubbo/protoc-gen-dubbo-java/1.19.0-SNAPSHOT](https://repository.apache.org/snapshots/org/apache/dubbo/protoc-gen-dubbo-java/1.19.0-SNAPSHOT/)

**Comment by steve0801** [comment]
> Both the SNAPSHOT version of Linux and OSX have been released. Please update the master branch for the latest code and try again.

Seems it doesn't work.

Pls look at the link, and you will see linux version only existing in Central Repository:
[https://repository.apache.org/snapshots/org/apache/dubbo/protoc-gen-dubbo-java/1.19.0-SNAPSHOT](https://repository.apache.org/snapshots/org/apache/dubbo/protoc-gen-dubbo-java/1.19.0-SNAPSHOT)

**Comment by dreamsky888** [comment]
I follow the instruction article：https://yq.aliyun.com/articles/728009。And the problem still exist：Could not find artifact org.apache.dubbo:protoc-gen-dubbo-java:pom:1.19.0-SNAPSHOT.
