### ISSUE TITLE
MergeableCluster 无法相应

### ISSUE THREAD

**Issue by maxiaodong58** [apache/dubbo#5407]
生产者配置如下：
 `<dubbo:service` interface="com.dubbo.provider.api.MenuService" ref="menuMobileServiceImpl" cluster="mergeable" merger="true" timeout="500" group="menuMobile"/>
 <dubbo:service interface="com.dubbo.provider.api.MenuService" ref="menuFruitsServiceImpl" cluster="mergeable" merger="true" timeout="500" `group="menuFruits"/>`

当使用这种方式配置的时候，会出现一直处于请求状态，不会出现超时断开。也没有办法返回正常的结果集。

**Comment by chickenlj** [comment]
I will try to reproduce this issue later.

**Comment by guohao** [comment]
@maxiaodong58 Merageable only works at consumer side. It has no effect when configured in `Service` tag. Here's a reference link : [group-merger](http://dubbo.apache.org/en-us/docs/user/demos/group-merger.html)

**Comment by guohao** [comment]
@qinliujie Pls close this issue.
