### ISSUE TITLE
多协议会注册会把默认dubbo协议也注册上去

### ISSUE THREAD

**Issue by pan289091315** [apache/dubbo#5415]
### Environment

* Dubbo version: dubbo-2.7.3-release
* Operating System version: windows10
* Java version: jdk8

### Steps to reproduce this issue

1. 使用spring-boot 启动,dubbo注解配置
2. yaml 配置如下：
dubbo:
  registry:
      address: nacos://127.0.0.1:8848
      check: false
  protocols:
    dubbo:
      name: dubbo
      port: 2019
    rest:
      name: rest
      port:  8088
      server: tomcat

3.注册中心会发现dubbo 协议注册了两遍。总共三个实例
![image](https://user-images.githubusercontent.com/6639546/69949255-23b48980-152c-11ea-85ea-0bc3a0b439a7.png)

其中2个dubbo协议。1个rest协议

**Comment by chickenlj** [comment]
Could you please submit one demo project so I can try reproducing this issue?

**Comment by pan289091315** [comment]
ignore it, my workmates has modify the source code,the community version are not this problem
