### ISSUE TITLE
使用nacos作为注册中心时，有一个provider，2个consumer，但是nacos控制台中只显示一个consumer

### ISSUE THREAD

**Issue by lidaoyang** [apache/dubbo#5426]
### Environment

* Dubbo version: 2.7.3
* Nacos version: 1.1.3
* Java version: 1.8

### Steps to reproduce this issue

1. 注册一个provider，nacos控制台里面有1个provider
2. 再注册一个consumer，nacos控制台里面有1个consumer
3. 再注册一个consumer，nacos控制台里面还是1个consumer，但是这个consumer已经被更新了，里面的应用名变了。

![image](https://user-images.githubusercontent.com/26211950/70118432-efafa480-16a2-11ea-9d5a-d71607bfbe3a.png)
![image](https://user-images.githubusercontent.com/26211950/70118444-f6d6b280-16a2-11ea-84d1-31a4836fecf6.png)
![image](https://user-images.githubusercontent.com/26211950/70118458-ffc78400-16a2-11ea-829f-005a5ca4c5b7.png)

**Comment by chickenlj** [comment]
该问题不影响服务调用，在同一个机器启动多个 consumer 实例时可以复现，暂无方案解决
