### ISSUE TITLE
TagRouter的stream操作导致ConsistentHashLoadBalance每次都需要重新进行hash环的映射。

### ISSUE THREAD

**Issue by thisiswanghy** [apache/dubbo#5429]
### Environment

* Dubbo version: 2.7.4.1

ConsistentHashLoadBalance 用到了 System.identityHashCode(invokers); 来判断 hash 值，从而判断是否有服务端的上下线操作。
而TagRouter的org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterUsingStaticTag方法中的 stream 操作会修改 invokers 的值，所以 ConsistentHashLoadBalance 受到了影响。
导致即使在服务端没有上下线操作的时候，一致性hash负载均衡算法每次都需要重新进行hash环的映射。

**Comment by thisiswanghy** [comment]
https://github.com/apache/dubbo/issues/5424

**Comment by CodingSinger** [comment]
i think should replace `java.lang.System#identityHashCode` with `hashCode` .
@chickenlj 
what's your opinion？

**Comment by thisiswanghy** [comment]
https://mp.weixin.qq.com/s/ctBM0WO-uWNlTWHI-TPniw 
bug的详细描述

**Comment by kimmking** [comment]
@CodingSinger  I commit some comments for your bugfix.

**Comment by LinShunKang** [comment]
@beiwei30 
In Dubbo 2.6.x branch, there is the same problem，`TagRouter` always return new `List<Invoker<T>>`:

https://github.com/apache/dubbo/blob/c894e0633537139aa784948aef9e8cb36a433179/dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/loadbalance/ConsistentHashLoadBalance.java#L47

https://github.com/apache/dubbo/blob/c894e0633537139aa784948aef9e8cb36a433179/dubbo-cluster/src/main/java/com/alibaba/dubbo/rpc/cluster/router/tag/TagRouter.java#L50-L76
