### ISSUE TITLE
how to use gRPC compiler ??

### ISSUE THREAD

**Issue by RyouZhang** [apache/dubbo#5431]
I get source from master branch. then mvn package dubbo/compiler.
I got a error when run dubbo-compiler

Error: Could not find or load main class org.apache.dubbo.gen.grpc.DubboGrpcGenerator

**Comment by chickenlj** [comment]
I tried but didn't reproduce your issue. Update the latest code and try again?

**Comment by chickenlj** [comment]
Do you have `org.apache.dubbo.gen.grpc.DubboGrpcGenerator` in your classpath?

**Comment by chickenlj** [comment]
run `mvn clean package` in 'dubbo/compiler' directory

**Comment by chickenlj** [comment]
Reopen if necessary
