### ISSUE TITLE
ExecuteLimitFilter does not work on generic invoke

### ISSUE THREAD

**Issue by maxiaoguang64** [apache/dubbo#5436]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: xxx
* Java version: 1.8

because invocation.getMethodName() is $invoke

**Comment by maxiaoguang64** [comment]
fixed by 2.7.5

**Comment by sonymoon** [comment]
Is it surely fixed?
