### ISSUE TITLE
VERSION_KEY和GROUP_KEY为空时，注册到NACOS的服务名与alibaba实现不一致，导致无法消费。

### ISSUE THREAD

**Issue by sdsEnjoyLife** [apache/dubbo#5442]
### Environment

* Dubbo version: latest version
* Operating System version: LINUX & WINDOWS
* Java version: 1.8

### Steps to reproduce this issue

必现哦

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

VERSION_KEY和GROUP_KEY为空时，注册到NACOS的服务名不带双冒号后缀。

### Actual Result

What actually happens?

VERSION_KEY和GROUP_KEY为空时，注册到NACOS的服务名有双冒号后缀，与alibaba实现不一致。
alibaba实现是为空时无双冒号后缀。

**Comment by mercyblitz** [comment]
Which Dubbo version did you use?

**Comment by htynkn** [comment]
master branch can reproduce this, refer to code:
```
private String getServiceName(URL url, String category) {
        return category + SERVICE_NAME_SEPARATOR + url.getColonSeparatedKey();
    }
```

```
public String getColonSeparatedKey() {
        StringBuilder serviceNameBuilder = new StringBuilder();
        append(serviceNameBuilder, INTERFACE_KEY, true);
        append(serviceNameBuilder, VERSION_KEY, false);
        append(serviceNameBuilder, GROUP_KEY, false);
        return serviceNameBuilder.toString();
    }
```
if VERSION_KEY is empty and GROUP_KEY is empty, will append ':'
```
private void append(StringBuilder target, String parameterName, boolean first) {
        String parameterValue = this.getParameter(parameterName);
        if (!StringUtils.isBlank(parameterValue)) {
            if (!first) {
                target.append(":");
            }
            target.append(parameterValue);
        } else {
            target.append(":");
        }
    }
```

**Comment by icc99** [comment]
2.7.3 之后就有这个问题了.    搞得我现在都不能升级, 现在的dubbo兼容性太差了...

**Comment by htynkn** [comment]
@chickenlj @mercyblitz URL `getColonSeparatedKey` method also called by 
+ DynamicConfiguration
+ AccessKeyAuthenticationHelper

There may have same issue

**Comment by mercyblitz** [comment]
It can be compatible with subscribing to the service name pattern of Alibaba's implementation, however, the early Nacos registry exists some defect, please update the new version.
