### ISSUE TITLE
[dubbo-common] typo: config-centre

### ISSUE THREAD

**Issue by spawpaw** [apache/dubbo#5445]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: v2.7.3
* Java version: 1.8

### Actual Result
https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/config/ConfigurationUtils.java#L77
```java
logger.warn("You specified the config centre, but there's not even one single config item in it.");
```

### Expected Result

```java
logger.warn("You specified the config center, but there's not even one single config item in it.");
```
Although `centre` has a simmilar meaning with `center`, we usually call a config center `config center` but not `config centre`. so consider changing it to `config center`?

**Comment by mercyblitz** [comment]
You can pull a request for it :D
