### ISSUE TITLE
dubbo架构应用部署在K8S上出现长连接断开问题

### ISSUE THREAD

**Issue by sunzj1989** [apache/dubbo#5457]
dubbo架构应用部署在KubeSphere容器平台中，一段时间不操作，会出现链接断开问题，多次刷新后链接回复正常，使用短连接不会出现上述问题，请问有没有解决方法。

**Comment by cvictory** [comment]
能否说明下，dubbo的具体版本，以及出现问题之后的具体现象(包括日志或者其他结果)

**Comment by cvictory** [comment]
I will close this issue firstly. If you still have some problem, please give me some detail .
