### ISSUE TITLE
StringUtils.split(String, char) result is not expect

### ISSUE THREAD

**Issue by LinShunKang** [apache/dubbo#5458]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4
* Operating System version: Darwin Kernel Version 18.7.0
* Java version: 1.8.0_181-b13)

### Steps to reproduce this issue

1. invoke `StringUtils.split("d,1,2,4", 'a')`
2. invoke `"d,1,2,4".split("a")`

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

`StringUtils.split("d,1,2,4", 'a')` should return `["d,1,2,4"]` just like `"d,1,2,4".split("a")`.

### Actual Result

empty array.

**Comment by chickenlj** [comment]
Would you like to try to fix it?

**Comment by LinShunKang** [comment]
OK, I will try to fix it.
