### ISSUE TITLE
Using URL as key to Map is unsafe

### ISSUE THREAD

**Issue by kahing** [apache/dubbo#5462]
https://github.com/apache/dubbo/blob/3257ef48f524c748c0651e97f6a8d06ff2963c94/dubbo-remoting/dubbo-remoting-p2p/src/main/java/org/apache/dubbo/remoting/p2p/exchange/support/AbstractExchangeGroup.java#L49

https://news.ycombinator.com/item?id=21765788

**Comment by chickenlj** [comment]
Thanks.

The URL you mentioned is defined by Dubbo and it behaves differently from the one in JDK. So I think we are not facing the issue you mentioned in the link below. 

Reopen if necessary
