### ISSUE TITLE
Could Dubbo REST use same port with SpringBoot Server port or how do?

### ISSUE THREAD

**Issue by yuxiao97** [apache/dubbo#5463]

**Comment by mercyblitz** [comment]
Yes, you can do it, but you have to change a little bit.

First, you should remove the configuration of Dubbo's REST, which means the Dubbo service with REST protocol should not be exported.

Second, your Dubbo `@Service` Classes annotate the `@Component`.

Finally, you read [this article](https://dzone.com/articles/using-jax-rs-with-spring-boot-instead-of-mvc) instructing the remaining work.

**Comment by yuxiao97** [comment]
Thanks,it's worked.Surprise mercyblitz answer me self.
