### ISSUE TITLE
How to disable MonitorService

### ISSUE THREAD

**Issue by L-glory** [apache/dubbo#5472]
- [] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ 1] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. I didn't add any configuration about monitor in app;
2. Provider and consumer Startup success;
3. Call someone interface and get exception like "java.lang.NoClassDefFoundError: com/alibaba/dubbo/monitor/MonitorService".

How to disable dubbo's monitor related services if I don't want to use monitor.

**Comment by chickenlj** [comment]
配置 filter="-monitor"

**Comment by chickenlj** [comment]
dubbo.consumer.filter=-monitor
dubbo.provider.filter=-monitor
