### ISSUE TITLE
dubbo的路由规则对泛化实现的服务无法生效

### ISSUE THREAD

**Issue by maomaofeitui** [apache/dubbo#5475]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.3
* Operating System version: centos
* Java version: 1.8

### Steps to reproduce this issue

1. 泛化实现一个dubbo服务
ServiceConfig<GenericService> service = dubboServices.get(serviceId);
        this.removeService(service);
        dubboServices.remove(serviceId);
        service = this.createDubboService(serviceName, myGenericService, address, timeout,
                protocolPort, groupName, retries, applicationName);
        service.export();
2. 注册中心写入规则，
{
	"condition": " => host != 172.1.1.1",
	"service":"com.bestpay.cf.instalmentmix.api.facade.account.CustomerService"
}
3. 结果路由规则不生效
请求还是走到了172.1.1.1上的服务，没有按预期情况走到泛化实现的服务上面

### Expected Result

希望是有方式可以让路由规则可以对泛化服务生效

**Comment by qinliujie** [comment]
I have checked that it can work at  2.7.x,please upgrade to 2.7.x
