### ISSUE TITLE
Registry调用destroy为什么不清除AbstractRegistryFactory中的缓存

### ISSUE THREAD

**Issue by shenluw** [apache/dubbo#5483]
你好：
我有一个疑问，当Registry调用destroy后不会去清除AbstractRegistryFactory中的缓存，导致以同样的参数再次获取的时候得到了一个已经无法使用的Registry。这个时设计的时候就认为不该这么使用吗？

**Comment by tswstarplanet** [comment]
Would you like to submit a pr ?
