### ISSUE TITLE
[dubbo-common] duplicate class

### ISSUE THREAD

**Issue by spawpaw** [apache/dubbo#5489]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: v2.7.3
* Java version: 1.8
* Maven version: 3.6.1

### Steps to reproduce this issue
here is an project that reproduces this issue.
https://github.com/spawpaw/dubbo-duplicate-dep-demo

### Actual Result

What actually happens?

this is my error log:

```
2019-12-16 14:43:06.210 ERROR 3220 --- [  restartedMain] o.a.d.c.Version                          :  [DUBBO] Duplicate class org/apache/dubbo/common/Version.class in 2 jar [file:/C:/var/repository/org/apache/dubbo/dubbo-common/2.7.3/dubbo-common-2.7.3.jar!/org/apache/dubbo/common/Version.class, file:/C:/var/repository/org/apache/dubbo/dubbo/2.7.3/dubbo-2.7.3.jar!/org/apache/dubbo/common/Version.class], dubbo version: 2.7.3, current host: 169.254.227.5
14:43:21.307 ERROR 3220 --- [  restartedMain] o.a.d.c.Version                         :236 :  [DUBBO] Duplicate class org/apache/dubbo/remoting/exchange/Exchangers.class in 2 jar [file:/C:/var/repository/org/apache/dubbo/dubbo-remoting-api/2.7.3/dubbo-remoting-api-2.7.3.jar!/org/apache/dubbo/remoting/exchange/Exchangers.class, file:/C:/var/repository/org/apache/dubbo/dubbo/2.7.3/dubbo-2.7.3.jar!/org/apache/dubbo/remoting/exchange/Exchangers.class], dubbo version: 2.7.3, current host: 169.254.227.5
14:43:21.319 ERROR 3220 --- [  restartedMain] o.a.d.c.Version                         :236 :  [DUBBO] Duplicate class org/apache/dubbo/remoting/Transporters.class in 2 jar [file:/C:/var/repository/org/apache/dubbo/dubbo-remoting-api/2.7.3/dubbo-remoting-api-2.7.3.jar!/org/apache/dubbo/remoting/Transporters.class, file:/C:/var/repository/org/apache/dubbo/dubbo/2.7.3/dubbo-2.7.3.jar!/org/apache/dubbo/remoting/Transporters.class], dubbo version: 2.7.3, current host: 169.254.227.5
14:43:21.320 ERROR 3220 --- [  restartedMain] o.a.d.c.Version                         :236 :  [DUBBO] Duplicate class org/apache/dubbo/remoting/RemotingException.class in 2 jar [file:/C:/var/repository/org/apache/dubbo/dubbo/2.7.3/dubbo-2.7.3.jar!/org/apache/dubbo/remoting/RemotingException.class, file:/C:/var/repository/org/apache/dubbo/dubbo-remoting-api/2.7.3/dubbo-remoting-api-2.7.3.jar!/org/apache/dubbo/remoting/RemotingException.class], dubbo version: 2.7.3, current host: 169.254.227.5

```

lets inspect the artifact `org.apache.dubbo:dubbo-common ` and `org.apache.dubbo:dubbo`:

dubbo-common:
![图片](https://user-images.githubusercontent.com/18007922/70884353-c41caa80-2010-11ea-84ec-63d0cc268987.png)
![图片](https://user-images.githubusercontent.com/18007922/70884364-ce3ea900-2010-11ea-8cba-283486f12775.png)

dubbo-remoting:  
![图片](https://user-images.githubusercontent.com/18007922/70884919-478acb80-2012-11ea-855f-de523dc3ecdb.png)
![图片](https://user-images.githubusercontent.com/18007922/70884974-6f7a2f00-2012-11ea-8327-6043ebf221e7.png)

It seems that `org.apache.dubbo:dubbo ` packages all classes in all modules into one artifact, so when other framework wants to depend a single dubbo module, the duplicate class error occurs.

### Expected Result
decompose `org.apache.dubbo:dubbo`

### See also
#4427 #2314

**Comment by chickenlj** [comment]
I'm afraid that the only way to avoid this error msg is to make sure you depend only on one type of artifact, either the all-in-one jar or specify each sub artifact separately.

**Comment by spawpaw** [comment]
I'm using `dubbo-spring-boot-starter` and `dubbo-metadata-reporter-zookeeper`, so I was very very confused  when those two official artifact raise an duplicate class error.

![图片](https://user-images.githubusercontent.com/18007922/70960461-0b12aa80-20ba-11ea-9a00-1d4da7486498.png)

wishing the official articfacts won't have conflicts any more : )

@chickenlj

**Comment by hai1004** [comment]
so what's the result? the duplcate class ' RemotingException.class '  in double.jar and double-remoting-api.jar，should I exclude  double-remoting-api.jar ?
