### ISSUE TITLE
telnet invoke

### ISSUE THREAD

**Issue by xjcrb** [apache/dubbo#5505]
telnet invoke报这个错
invalid json argument cause com/alibaba/fastjson/json

**Comment by LiosWong** [comment]
把invoke参数贴出来，应该是格式有问题

**Comment by LiosWong** [comment]
> telnet invoke报这个错
> invalid json argument cause com/alibaba/fastjson/json

把invoke参数贴出来，应该是格式有问题

**Comment by xjcrb** [comment]
就算是调用不用传入参数的方法也是报这个错，参数确定是没问题

**Comment by LiZhenNet** [comment]
> 就算是调用不用传入参数的方法也是报这个错，参数确定是没问题

建议把接口方法定义跟具体的 telnet 命令发出来

**Comment by xjcrb** [comment]
已经解决，dubbo2.6.3版本会出现这个问题，替换版本就行

**Comment by hesherya** [comment]
2.7.5 又出现这个问题了

**Comment by FanHuaRan** [comment]
要命哦，快解决啊

**Comment by qianyong-2005** [comment]
dubbo>ls
PROVIDER:
org.apache.dubbo.samples.api.GreetingService:1.0.0

dubbo>invoke org.apache.dubbo.samples.api.GreetingService:1.0.0.sayHello( { "name": "zookeeper"} )
Invalid json argument, cause: com/alibaba/fastjson/JSON

**Comment by coffeehb** [comment]
2.7.7 同样出现这个问题

**Comment by codemak2r** [comment]
升级到2.7.10 可以直接解决这个问题
