### ISSUE TITLE
调用服务时，第一次失败，然后就一直成功了。

### ISSUE THREAD

**Issue by daxiong1224** [apache/dubbo#5534]
有一个服务第一次调用的时候报类型转换错误。这个问题也是最近才爆出来的，之前一直正常。

第一次点执行，结果是失败，错误信息和截图如下：

![1](https://user-images.githubusercontent.com/34907635/71433453-2d3fa480-271a-11ea-8172-3823d19b14ca.png)
再点一次执行，成功了。之后再重复点执行，都能够调通。
![2](https://user-images.githubusercontent.com/34907635/71433465-3a5c9380-271a-11ea-8268-3bc9ab15d16c.png)
服务应该没问题的，不然重复调应该一直失败才是。不知道问题出在哪里，希望大牛帮忙解决下。

补充一点：这个是A项目中服务接口。我是在项目B中的PROVIDER层建consumer调用(文中描述的失败情况)结果是失败。 但是在项目B的consumer层直接调用该服务又是一切正常的。

**Comment by OLPMO** [comment]
请问你可以提供一个重现的demo吗？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
