### ISSUE TITLE
Unused variable in EtcdServiceDiscovery

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo#5537]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6-SNAPSHOT

### Steps to reproduce this issue

https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdServiceDiscovery.java#L64

``` java
private final ConcurrentMap<URL, ConcurrentMap<NotifyListener, ChildListener>> etcdListeners = new ConcurrentHashMap<>();
```

Need check this line

**Comment by shtke** [comment]
Can I take this Issue ?

**Comment by htynkn** [comment]
close via #5548
