### ISSUE TITLE
Dubbo的2.6.5版本使用AnnotationBean扫描包时，ServiceBean的publishExportEvent方法异常

### ISSUE THREAD

**Issue by MingKaBum** [apache/dubbo#5551]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.5
* Spring boot version: 2.1.8.RELEASE
* Java version: 1.8

### Steps to reproduce this issue

1. 项目启动过程中，扫描到Service注解的类；
2. 在export()的过程中，在2.6.5版本新加了publishExportEvent();的操作；
3. 内部的方法是ServiceBeanExportedEvent的事件监听；
4.applicationEventPublisher.publishEvent(exportEvent);这个方法的applicationEventPublisher为null，抛出了空指针异常；
5.ServiceBean方法实现了ApplicationEventPublisherAware接口，但是却没有调用其中的方法setApplicationEventPublisher方法；

### Message
萌新一个，最近在学习Dubbo，遇到这个问题，自己查了很多资料没有解决，还请各位大佬帮忙看一下，感谢。

**Comment by GungnirLaevatain** [comment]
ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的

**Comment by MingKaBum** [comment]
> ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的
1.我是从2.6.4版本升级到2.6.5版本之后出现的问题；
2.使用了AnnotationBean扫描了Package，在其中注入了annotationPackage和applicationContext属性；
3.AnnotationBean里面的方法postProcessAfterInitialization在扫描到dubbo的@Service注解后，初始化一个ServiceBean之后进行export();
```java
    /**
     * @since 2.6.5
     */
    @Override
    public void export() {
        super.export();
        // Publish ServiceBeanExportedEvent
        publishExportEvent();
    }
    /**
     * @since 2.6.5
     */
    private void publishExportEvent() {
        ServiceBeanExportedEvent exportEvent = new ServiceBeanExportedEvent(this);
        applicationEventPublisher.publishEvent(exportEvent);
    }
```
4.方法里面的applicationEventPublisher这个为Null，导致抛出了空指针异常；
5.ServiceBean实现了ApplicationEventPublisherAware，但是在应用启动的时候并没有执行它的方法
```java
/**
     * @param applicationEventPublisher
     * @since 2.6.5
     */
    @Override
    public void setApplicationEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
        this.applicationEventPublisher = applicationEventPublisher;
    }
```
6.自己调试了一下代码，发现ApplicationContextAwareProcessor在初始化的时候，没有扫描到ServiceBean类型；
7.麻烦大佬帮忙看一下，这个问题已经困惑自己三四天了，目前暂时没有找到解决方案，只能降低版本到2.6.4；

**Comment by MingKaBum** [comment]
> ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的

**Comment by GungnirLaevatain** [comment]
> > ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的
> > 1.我是从2.6.4版本升级到2.6.5版本之后出现的问题；
> > 2.使用了AnnotationBean扫描了Package，在其中注入了annotationPackage和applicationContext属性；
> > 3.AnnotationBean里面的方法postProcessAfterInitialization在扫描到dubbo的@service注解后，初始化一个ServiceBean之后进行export();
> 
> ```java
>     /**
>      * @since 2.6.5
>      */
>     @Override
>     public void export() {
>         super.export();
>         // Publish ServiceBeanExportedEvent
>         publishExportEvent();
>     }
>     /**
>      * @since 2.6.5
>      */
>     private void publishExportEvent() {
>         ServiceBeanExportedEvent exportEvent = new ServiceBeanExportedEvent(this);
>         applicationEventPublisher.publishEvent(exportEvent);
>     }
> ```
> 
> 4.方法里面的applicationEventPublisher这个为Null，导致抛出了空指针异常；
> 5.ServiceBean实现了ApplicationEventPublisherAware，但是在应用启动的时候并没有执行它的方法
> 
> ```java
> /**
>      * @param applicationEventPublisher
>      * @since 2.6.5
>      */
>     @Override
>     public void setApplicationEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
>         this.applicationEventPublisher = applicationEventPublisher;
>     }
> ```
> 
> 6.自己调试了一下代码，发现ApplicationContextAwareProcessor在初始化的时候，没有扫描到ServiceBean类型；
> 7.麻烦大佬帮忙看一下，这个问题已经困惑自己三四天了，目前暂时没有找到解决方案，只能降低版本到2.6.4；



> > ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的
> > 1.我是从2.6.4版本升级到2.6.5版本之后出现的问题；
> > 2.使用了AnnotationBean扫描了Package，在其中注入了annotationPackage和applicationContext属性；
> > 3.AnnotationBean里面的方法postProcessAfterInitialization在扫描到dubbo的@service注解后，初始化一个ServiceBean之后进行export();
> 
> ```java
>     /**
>      * @since 2.6.5
>      */
>     @Override
>     public void export() {
>         super.export();
>         // Publish ServiceBeanExportedEvent
>         publishExportEvent();
>     }
>     /**
>      * @since 2.6.5
>      */
>     private void publishExportEvent() {
>         ServiceBeanExportedEvent exportEvent = new ServiceBeanExportedEvent(this);
>         applicationEventPublisher.publishEvent(exportEvent);
>     }
> ```
> 
> 4.方法里面的applicationEventPublisher这个为Null，导致抛出了空指针异常；
> 5.ServiceBean实现了ApplicationEventPublisherAware，但是在应用启动的时候并没有执行它的方法
> 
> ```java
> /**
>      * @param applicationEventPublisher
>      * @since 2.6.5
>      */
>     @Override
>     public void setApplicationEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
>         this.applicationEventPublisher = applicationEventPublisher;
>     }
> ```
> 
> 6.自己调试了一下代码，发现ApplicationContextAwareProcessor在初始化的时候，没有扫描到ServiceBean类型；
> 7.麻烦大佬帮忙看一下，这个问题已经困惑自己三四天了，目前暂时没有找到解决方案，只能降低版本到2.6.4；

AnnotationBean已经被标记为Deprecated了，且其扫描创建的ServiceBean的确不走spring的后置处理器，你可以尝试使用`EnableDubbo`注解来替换这个废弃的类

**Comment by MingKaBum** [comment]
> > > ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的
> > > 1.我是从2.6.4版本升级到2.6.5版本之后出现的问题；
> > > 2.使用了AnnotationBean扫描了Package，在其中注入了annotationPackage和applicationContext属性；
> > > 3.AnnotationBean里面的方法postProcessAfterInitialization在扫描到dubbo的@service注解后，初始化一个ServiceBean之后进行export();
> > 
> > 
> > ```java
> >     /**
> >      * @since 2.6.5
> >      */
> >     @Override
> >     public void export() {
> >         super.export();
> >         // Publish ServiceBeanExportedEvent
> >         publishExportEvent();
> >     }
> >     /**
> >      * @since 2.6.5
> >      */
> >     private void publishExportEvent() {
> >         ServiceBeanExportedEvent exportEvent = new ServiceBeanExportedEvent(this);
> >         applicationEventPublisher.publishEvent(exportEvent);
> >     }
> > ```
> > 
> > 
> > 4.方法里面的applicationEventPublisher这个为Null，导致抛出了空指针异常；
> > 5.ServiceBean实现了ApplicationEventPublisherAware，但是在应用启动的时候并没有执行它的方法
> > ```java
> > /**
> >      * @param applicationEventPublisher
> >      * @since 2.6.5
> >      */
> >     @Override
> >     public void setApplicationEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
> >         this.applicationEventPublisher = applicationEventPublisher;
> >     }
> > ```
> > 
> > 
> > 6.自己调试了一下代码，发现ApplicationContextAwareProcessor在初始化的时候，没有扫描到ServiceBean类型；
> > 7.麻烦大佬帮忙看一下，这个问题已经困惑自己三四天了，目前暂时没有找到解决方案，只能降低版本到2.6.4；
> 
> > > ApplicationEventPublisherAware接口在spring环境下会由ApplicationContextAwareProcessor进行处理的
> > > 1.我是从2.6.4版本升级到2.6.5版本之后出现的问题；
> > > 2.使用了AnnotationBean扫描了Package，在其中注入了annotationPackage和applicationContext属性；
> > > 3.AnnotationBean里面的方法postProcessAfterInitialization在扫描到dubbo的@service注解后，初始化一个ServiceBean之后进行export();
> > 
> > 
> > ```java
> >     /**
> >      * @since 2.6.5
> >      */
> >     @Override
> >     public void export() {
> >         super.export();
> >         // Publish ServiceBeanExportedEvent
> >         publishExportEvent();
> >     }
> >     /**
> >      * @since 2.6.5
> >      */
> >     private void publishExportEvent() {
> >         ServiceBeanExportedEvent exportEvent = new ServiceBeanExportedEvent(this);
> >         applicationEventPublisher.publishEvent(exportEvent);
> >     }
> > ```
> > 
> > 
> > 4.方法里面的applicationEventPublisher这个为Null，导致抛出了空指针异常；
> > 5.ServiceBean实现了ApplicationEventPublisherAware，但是在应用启动的时候并没有执行它的方法
> > ```java
> > /**
> >      * @param applicationEventPublisher
> >      * @since 2.6.5
> >      */
> >     @Override
> >     public void setApplicationEventPublisher(ApplicationEventPublisher applicationEventPublisher) {
> >         this.applicationEventPublisher = applicationEventPublisher;
> >     }
> > ```
> > 
> > 
> > 6.自己调试了一下代码，发现ApplicationContextAwareProcessor在初始化的时候，没有扫描到ServiceBean类型；
> > 7.麻烦大佬帮忙看一下，这个问题已经困惑自己三四天了，目前暂时没有找到解决方案，只能降低版本到2.6.4；
> 
> `AnnotationBean`已经被标记为Deprecated了，且其扫描创建的`ServiceBean`的确不走spring的后置处理器，你可以尝试使用`EnableDubbo`注解来替换这个废弃的类

感谢大佬的建议，我这边已经弃用了AnnotationBean扫描包的方式了，并且启动成功了。
```java
@DubboComponentScan
@Import({EnableDubboImportSelector.class})
public @interface EnableDubboConfiguration {

    String port() default "20880";

    String protocol() default "dubbo";

    @AliasFor(annotation = DubboComponentScan.class, attribute = "basePackages")
    String[] scanPackageName() default {"com.example"};
}
```
