### ISSUE TITLE
Container contents are never accessed

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo#5554]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6-SNAPSHOT

### Steps to reproduce this issue

Looks like there are some potential code issues in two files: a collection or map whose contents are never queried or accessed is useless.

https://github.com/apache/dubbo/blob/master/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java#L111
https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/compiler/support/JdkCompiler.java#L211

### Expected Result

Remove them if it can be confirmed as unless

**Comment by mayankkt9** [comment]
Can I work on this ?

**Comment by htynkn** [comment]
close via #5556
