### ISSUE TITLE
protocol.register配置不生效

### ISSUE THREAD

**Issue by crazyzh1984** [apache/dubbo#5583]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: mac 10.15
* Java version: 1.8

### Steps to reproduce this issue

1. Spring start app
```java
@SpringBootApplication
@EnableDubbo(multipleConfig = false)
public class RunApp {
}
```

2. application.yml
```yml
dubbo:
  protocol:
    register: false
```

3. start RunApp

### Expected Result
Providers don't register to  registry center

### Actual Result
Providers registered to registry center.
Checked from dubbo admin 

### Problems
http://dubbo.apache.org/en-us/docs/user/references/xml/dubbo-service.html
Attribute `register` is not required, should be null when not set.

The default value in @Service is `true` in v2.7.3.

#### v2.6.2
com.alibaba.dubbo.config.annotation.Service
```java
boolean register() default false;
```

#### v2.7.3
org.apache.dubbo.config.annotation.Service
```java
/**
 * Whether to register the service to register center, default value is true
 */
boolean register() default true;
```

org.apache.dubbo.config.AbstractServiceConfig
```java
/**
 * Whether to register
 */
 private Boolean register = true;
```
ServiceBean.register default value is true。(should be null)

org.apache.dubbo.config.ServiceConfig
```java
doExportUrlsFor1Protocol(ProtocolConfig protocolConfig, List<URL> registryURLs){
  ......
  appendParameters(map, provider);
  appendParameters(map, protocolConfig);
  appendParameters(map, this);// default: this.register=true (unset on @Service)
  ......
}
```
`this.register` has default value(from AbstractServiceConfig), can't be overrided by protocolConfig.

### fix
org.apache.dubbo.config.AbstractServiceConfig
```java
/**
 * Whether to register
 */
 private Boolean register;
```
Change to null on unset.

**Comment by tswstarplanet** [comment]
The default action is to register. I think there are some problems elsewhere.

**Comment by tswstarplanet** [comment]
2.7.4应该修复了这个问题了

**Comment by crazyzh1984** [comment]
> 2.7.4应该修复了这个问题了

看了下master，的确修复了。抱歉，我关了吧
