### ISSUE TITLE
@EnableDubbo中的scanBasePackages不生效

### ISSUE THREAD

**Issue by htyoung** [apache/dubbo#5591]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows 10
* Java version: 1.8

### Steps to reproduce this issue

1. 当将dubbo配置类不放在根包的目录时，用scanBasePackages指定要扫描的包，org.apache.dubbo.config.spring.context.annotation.DubboComponentScanRegistrar类中getPackagesToScan方法返回是dubbo配置类所在的包（即默认值）

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

返回scanBasePackages指定的包

### Actual Result

实际上返回的是默认值

**Comment by mercyblitz** [comment]
Which version of Spring Framework did you use?

**Comment by htyoung** [comment]
Spring Framework 4.3.17.RELEASE

**Comment by htyoung** [comment]
But the attribute “basePackages” of the annotation @DubboComponentScan works

**Comment by OLPMO** [comment]
你好，请问你可以提供一个可复现bug的最小demo吗？@htyoung

**Comment by htyoung** [comment]
https://github.com/htyoung/dubbo-issue-5591 here is demo project @OLPMO @mercyblitz

**Comment by liuzdcq** [comment]
[https://stackoverflow.com/questions/37120046/spring-framework-aliasfor-annotation-dilema](url) 
I think it's the problem relate to this.

**Comment by spilledyear** [comment]
解决了吗？ 我也遇到这个问题

**Comment by htyoung** [comment]
> 解决了吗？ 我也遇到这个问题
换一个注解，用@DubboComponentScan替代，@EnableDubbo这个应该是个bug，升版本试试看吧

**Comment by linxiaobai** [comment]
大概率是EnableDubbo里AliasFor的问题，将@EnableDubbo注解替换成下面这2个就行了。
```java
@EnableDubboConfig
@DubboComponentScan(basePackages = "xxx")
```

**Comment by icankeep** [comment]
&ready to close&
