### ISSUE TITLE
A bean with that name has already been defined and overriding is disabled

### ISSUE THREAD

**Issue by Huangxuny1** [apache/dubbo#5610]
in [issue 5591](https://github.com/apache/dubbo/issues/5591) , @htyoung give a reproduce demo project .
The project env is :
>  org.springframework.boot 1.5.13.RELEASE <br>
>  org.apache.dubbo 2.7.3 <br>

by my debug , it's lead by  `AbstractApplicationEventMulticaster`#getApplicationListeners(
			ApplicationEvent event, ResolvableType eventType)   donot return listeners contain `ServiceBean`
![image](https://user-images.githubusercontent.com/21981606/72119414-535a7b00-338f-11ea-8546-691d1f57a0d4.png)
![image](https://user-images.githubusercontent.com/21981606/72119423-5bb2b600-338f-11ea-9ce4-e6026c1ef932.png)

,
so when I watch master branch , it's have handled this issue [registerBeans(registry, DubboBootstrapApplicationListener.class);](https://github.com/apache/dubbo/blob/f264dac97307abe08992b71caf5912a741c21cd8/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceAnnotationBeanPostProcessor.java#L113) 
 
exactly , the issue have been solved

BUT in  `org.springframework.boot 2.2.2.RELEASE`  , 
the bean "DubboBootstrapApplicationListener" already register , once do "registerBeans(registry, DubboBootstrapApplicationListener.class);" 
it will lead a to another issue 
```
Description:
The bean 'dubboBootstrapApplicationListener' could not be registered. A bean with that name has already been defined and overriding is disabled.
Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

**Comment by htyoung** [comment]
[in issue 5591](https://github.com/apache/dubbo/issues/5591),when I use spring-boot above 2.2.0（included），this issue doesn't appear

**Comment by Huangxuny1** [comment]
> [in issue 5591](https://github.com/apache/dubbo/issues/5591),when I use spring-boot above 2.2.0（included），this issue 5591 doesn't appear

well, 
`springboot 2.2.2 RELEASE` and `dubbo 2.7.3`    ✅ it works 
`springboot 1.5.13 RELEASE` and `dubbo 2.7.5 or dubbo 2.7.6-SNAPSHOT` ✅ it works 

BUG 
`springboot 2.2.2 RELEASE` and `dubbo 2.7.5 or dubbo 2.7.6-SNAPSHOT`  ❌ 

```
The bean 'dubboBootstrapApplicationListener' could not be registered. A bean with that name has already been defined and overriding is disabled.
```
