### ISSUE TITLE
Dubbo优雅停机问题

### ISSUE THREAD

**Issue by szd1993** [apache/dubbo#5630]
DubboBootstrapApplicationListener通过监听spring容器关闭事件ContextClosedEvent，将provider从注册中心移除，并关闭应用
是不是存在以下问题：
1.当ContextClosedEvent触发时，spring容器已经销毁，此时如果外部流量进来、以及内部依旧在运行的线程，会因为bean找不到，出现异常

是否考虑先执行从注册中心移除provider的操作(在spring容器启动时，放入钩子)，然后再销毁spring容器

**Comment by mail6562** [comment]
这个一直都没有实现

**Comment by mercyblitz** [comment]
> 1.当ContextClosedEvent触发时，spring容器已经销毁，此时如果外部流量进来、以及内部依旧在运行的线程，会因为bean找不到，出现异常

the ContextClosedEvent is raised while the Spring container is closing, however, the managed Spring Beans are not destroyed yet, Please refer to the method `org.springframework.context.support.AbstractApplicationContext#doClose`. Actually, the provider will be offlined first when the method `org.apache.dubbo.config.bootstrap.DubboBootstrap#stop` is invoked.

**Comment by oaoit** [comment]
> > 1.当ContextClosedEvent触发时，spring容器已经销毁，此时如果外部流量进来、以及内部依旧在运行的线程，会因为bean找不到，出现异常
> 
> the ContextClosedEvent is raised while the Spring container is closing, however, the managed Spring Beans are not destroyed yet, Please refer to the method `org.springframework.context.support.AbstractApplicationContext#doClose`. Actually, the provider will be offlined first when the method `org.apache.dubbo.config.bootstrap.DubboBootstrap#stop` is invoked.

外部流量是没有了，但是内部没有执行完的dubbo线程还在执行。spring 发送完关机事件紧接着就要销毁所有beans没有什么停顿，所以dubbo的残留线程很有可能没执行完。
