### ISSUE TITLE
方法注解超时配置

### ISSUE THREAD

**Issue by annpeter** [apache/dubbo#5634]
### Environment

* Dubbo version: 2.7.5
* Operating System version: Centos7
* Java version: 1.8

使用注解的情况下，怎么在provider的方法级别上配置超时时间

**Comment by furaul** [comment]
同问该问题，希望有通过注解或者配置文件的方法，非xml，配置方法级别，包括超时时间、重试次数等

**Comment by CrazyHZM** [comment]
The new version supports @Method annotation
