### ISSUE TITLE
Dubbo 2.7 路由标签不能持续传递

### ISSUE THREAD

**Issue by linfeiyu** [apache/dubbo#5638]
文档对标签路由的表述：通过一行代码的设置，达到标签的持续传递
实际代码中在 ContextFilter.invoke 方法中清除了 attachments 中的标签信息，导致标签只在当前的 Invocation 有效，不能达到持续传递的效果。

**Comment by chickenlj** [comment]
We do that on purpose, you need to do some extra work to make the tag passed along the invoke chain. For example, you add a filter working before ContextFilter and save tag before it get removed.
