### ISSUE TITLE
2.7.5感觉不是太稳定，兼容也不是太好，建议退回2.7.4.1

### ISSUE THREAD

**Issue by luhouhua** [apache/dubbo#5641]
具体问题参考 #5640 #5638 #5633

**Comment by CodingSinger** [comment]
2.7.5可以认为是个实验版本，不建议升级上生产使用。

**Comment by beiwei30** [comment]
will evaluate and fix a.s.a.p

**Comment by chickenlj** [comment]
带来不便敬请谅解，请参考这里的升级建议：https://github.com/apache/dubbo/issues/5669

关于以上问题，请在每个 issue 中分别跟踪修复状态
