### ISSUE TITLE
dubbo 2.7.5使用grpc，启动程序报错

### ISSUE THREAD

**Issue by twfx7758** [apache/dubbo#5644]
* Dubbo version: 2.7.5
* Operating System version: win10
* Java version: 1.8.0_171

### Steps to reproduce this issue

配置：
# Dubbo Protocol
dubbo.protocol.name=grpc
dubbo.protocol.serialization=protobuf
dubbo.protocol.port=8808
#dubbo.protocol.server=tomcat
## Dubbo Registry
dubbo.registry.address=N/A

配置好相就文件，启用报错，请大礼帮忙解答：

Failed to set dubbo proxied service impl to stub, please make sure your stub was generated by the dubbo-protoc-compiler.

我还需要配置proto文件？还是引用protoc插件

**Comment by twfx7758** [comment]
发现项目没有io.grpc相关的包，引用dubbo 2.7.5，不是应该自动关联相应的包吗

**Comment by twfx7758** [comment]
我感觉是我使用姿势有问题，请问哪里有dubbo grpc的示例？？？急用 非常感谢

**Comment by twfx7758** [comment]
![image](https://user-images.githubusercontent.com/3370412/72244708-ced75900-3629-11ea-8252-fc0be1b55f7e.png)
看描述，接口必需定义 .proto文件吗？？

**Comment by twfx7758** [comment]
dubbo-protoc-compiler   这个是什么呢

**Comment by chickenlj** [comment]
@twfx7758 https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-grpc
gRPC 示例在这里有

**Comment by chickenlj** [comment]
> 看描述，接口必需定义 .proto文件吗？？

是的，参考示例，.proto 文件是必要的

**Comment by chickenlj** [comment]
应该是 Provider 端的业务实现类没有继承 gRP stub：
https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-grpc/dubbo-samples-original/src/main/java/org/apache/dubbo/samples/basic/impl/helloworld/GrpcGreeterImpl.java

**Comment by chickenlj** [comment]
```java
public class GrpcGreeterImpl extends DubboGreeterGrpc.GreeterImplBase {

    @Override
    public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
        System.out.println("Executing thread is " + Thread.currentThread().getName());
        HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + request.getName()).build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
    }

}
```

**Comment by twfx7758** [comment]
你好，我看了motan的grpc示例，但他们直接定义接口，没有proto文件，dubbo可以吗？

**Comment by twfx7758** [comment]
> ```java
> public class GrpcGreeterImpl extends DubboGreeterGrpc.GreeterImplBase {
> 
>     @Override
>     public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
>         System.out.println("Executing thread is " + Thread.currentThread().getName());
>         HelloReply reply = HelloReply.newBuilder().setMessage("Hello " + request.getName()).build();
>         responseObserver.onNext(reply);
>         responseObserver.onCompleted();
>     }
> 
> }
> ```

多谢，我再研究研究其它方案

**Comment by Jijun** [comment]
用grpc其实在于多语言接入，目前看dubbo的grpc实现需要依赖注册中心，例如zk，这样其他语言调用就需要连接zk去拿到grpc provider信息。不如直接用nginx或envoy直接代理grpc流量简单。
可以参考我的项目，基于dubbo泛化调用，目前在生产上运行效果很好，[grpc-dubbo-proxy](https://github.com/Jijun/grpc-dubbo-proxy)

**Comment by spilledyear** [comment]
> 你好，我看了motan的grpc示例，但他们直接定义接口，没有proto文件，dubbo可以吗？

@twfx7758 楼主解决了吗？ 我想在项目中仅仅使用 grpc协议， 序列化还是用原生的序列化方式， 这样现有项目就不需要改造了，能实现吗？
