### ISSUE TITLE
telnet invoke报错：Unsupported command: invoke

### ISSUE THREAD

**Issue by LiosWong** [apache/dubbo#5652]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: MacBook Pro
* Java version: 1.8

### Steps to reproduce this issue

1. telnet 
```
➜  ~ telnet 127.0.0.1 20880
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
dubbo>
```
2. invoke
```
dubbo>invoke org.apache.dubbo.demo.DemoService.sayHello("lios")
Unsupported command: invoke
```
3. help
```
dubbo>help
Please input "help [command]" show detail.
 status [-l]    - Show status.
 clear [lines]  - Clear screen.
 log level      - Change log level or show log 
 help [command] - Show help.
 exit           - Exit the telnet.
dubbo>
```

**Comment by LiosWong** [comment]
在本地用idea启动服务提供者,然后使用telnet，invoke失败，提示命令不支持，请问是什么原因

**Comment by MountainCui25** [comment]
> 在本地用idea启动服务提供者,然后使用telnet，invoke失败，提示命令不支持，请问是什么原因

你好，请问问题最终是怎么解决的呢？我也遇到同样问题

**Comment by AlbumenJ** [comment]
> > 在本地用idea启动服务提供者,然后使用telnet，invoke失败，提示命令不支持，请问是什么原因
> 
> 你好，请问问题最终是怎么解决的呢？我也遇到同样问题

使用 telnet 127.0.0.1 22222          invoke
