### ISSUE TITLE
revisit relationshipt between DubboBootstrap  and ServiceConfig & ReferenceConfig

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#5666]
Right now DubboBootstrap is depended by ServiceConfig and ReferenceConfig in order to make sure the necessary artifacts init-ed correct, which looks to me a severe flaw we should address as soon as possible.

In my opinion, the lack of central controller leads to today's situation. We should make sure the following scenarios works.

1. DubboBootstrap -> register  to [config manager] -> start()  to trigger [central controller]'s lifecycle to roll out.
2. ServiceConfig -> register to [config manager] -> export() to trigger [central controller]'s lifecycle to roll out.
3. ReferenceConfig -> register to [config manager] -> refer() to trigger [central controller]'s lifecycle to roll out.

**Comment by chickenlj** [comment]
Agree with the idea of sperate some logics from Bootstrap into a separate `central controller`, I will try to take a look at this later.

**Comment by chickenlj** [comment]
![image](https://user-images.githubusercontent.com/18097545/106302057-69d1be00-6293-11eb-8a98-c4fb6944e1ab.png)

最右侧是 Dubbo 提供的标准API接口，有着统一的配置管理与启动方式；
左侧是 Dubbo 的使用方式，Dubbo可以有 API、Spring（XML Annotation）等多种使用方式，但不论配置方式如何变化，最终都应该映射到右侧标准的配置与启动流程上

其他一些行为改进：
* SpringExtensionFactory 侵入到了Dubbo核心流程中
* Spring 配置装配阶段和Dubbo核心逻辑启动阶段分离，典型如ReferenceBean.getObject()
* Dubbo 多实例支持 ConfigManager？
* Dubbo 多ReferenceBean实例(如timeout配置不同)，Dubbo 运行态元数据ServiceRepository目前不支持
* 一些全局默认配置，如Monitor Registry等，要等待用户配置都扫描完成后，如确认用户未配置再生成框架默认配置
