### ISSUE TITLE
Use G1 to replace CMS configuration in start.sh

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo#5668]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: latest
* Operating System version: linux
* Java version: 9+

### Requirement

 After Java 9 ，the default JVM garbage collector is G1 , So please add G1 configuration in 

`dubbo/dubbo-container/dubbo-container-api/src/main/resources/META-INF/assembly/bin/start.sh`

when your jdk is higher then Java 8

**Comment by chickenlj** [comment]
Also see #835
