### ISSUE TITLE
why org.apache.dubbo.config.AbstractInterfaceConfig#setApplication is `@Deprecated`?

### ISSUE THREAD

**Issue by Byron4j** [apache/dubbo#5679]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: Win10
* Java version: JDK8

### Steps to reproduce this issue

1. use dubbo API show provider application
```
ServiceConfig<GreetingsService> service = new ServiceConfig<>();
        service.setApplication(new ApplicationConfig("first-dubbo-provider"));
```
3. but find this method is annotated by `@Deprecated`

If i want to show a demo with dubbo API to my students， where can i find a method which with no `@Deprecated` ？

-------

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
Please reference to DubboBootstrap. Here's the demo code of using DubboBootstrap https://github.com/apache/dubbo/blob/master/dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java

**Comment by lonre** [comment]
> Please reference to DubboBootstrap. Here's the demo code of using DubboBootstrap https://github.com/apache/dubbo/blob/master/dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java

@chickenlj demo code also invoked Deprecated method of `setApplication`

**Comment by pumzx** [comment]
@chickenlj Please explain why the setApplication() method is deprecated and what is the recommended method?thank you

**Comment by twenty-zhang** [comment]
Duplicate Config found for ApplicationConfig, you should use only one unique ApplicationConfig for one application.
