### ISSUE TITLE
获取Adaptive扩展时存在循环注入的问题

### ISSUE THREAD

**Issue by ououtt** [apache/dubbo#5683]
dubbo获取Adaptive扩展时会先调用injectExtension方法,通过set方法注入之后再返回暴露给外界使用.注入的对象来源是通过SpiExtensionFactory得到的,但是SpiExtensionFactory也是获取的Adaptive扩展.如果此时有A,B两个类,两者都有对方的set方法,那么虽然在启动时不会报错(注入时会catch到栈溢出异常退出),但其实创建了很多个A和B的对象.关键的是,获取到的A和B内部的对象不是对方,使用时会出现问题

**Comment by xylsh** [comment]
循环依赖的时候，代码抛出的stackoverflowerror会被捕获后logger打印，然后这个error就不管了，dubbo继续运行。个人认为这种情况dubbo不应该继续执行？   @chickenlj

**Comment by CrazyHZM** [comment]
The relevant logic has changed, try it with the latest version, if you still have problems, you can reopen the issue
