### ISSUE TITLE
nacos注册中心，泛化调用如何配置namespace

### ISSUE THREAD

**Issue by lixocg** [apache/dubbo#5706]
使用nacos作为dubbo注册中心，并且创建了新的namespace，在新的namespace下发布dubbo服务，泛化调用没找到如何设置新的namespace，导致泛化调用失败，找不到服务，求教如何配置？

**Comment by lixocg** [comment]
sorry,刚刚如下尝试，既然可以了：）
![image](https://user-images.githubusercontent.com/13638878/73666422-c2509880-46dd-11ea-9a4d-8f7c1b122313.png)

**Comment by zx0828** [comment]
你好，我按照图上配置，还是出现泛化调用找不到provider，请问你那边解决了吗，thanks。
