### ISSUE TITLE
tomcat9 is Incompatible with dubbo 2.7

### ISSUE THREAD

**Issue by goodliukai** [apache/dubbo#5711]
### Environment

* Dubbo version: 2.7.*
* Operating System version: xxx
* Java version: 8
* springboot: 2.2.4

### Steps to reproduce this issue

1.  I want to use dubbo with springboot 
2. Need two protocol - rest and dubbo
3. Rest server is tomcat, and I use tomcat9 in my project

### Exception
```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.apache.dubbo.remoting.http.tomcat.TomcatHttpServer.<init>(TomcatHttpServer.java:66)

The following method did not exist:

    org.apache.catalina.connector.Connector.setProtocol(Ljava/lang/String;)V

The method's class, org.apache.catalina.connector.Connector, is available from the following locations:

    jar:file:/Users/leeco/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.30/tomcat-embed-core-9.0.30.jar!/org/apache/catalina/connector/Connector.class

It was loaded from the following location:

    file:/Users/leeco/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.30/tomcat-embed-core-9.0.30.jar
```
### What`s wrong

The code is "tomcat.getConnector().setProtocol("org.apache.coyote.http11.Http11NioProtocol");"

**Comment by goodliukai** [comment]
tomcat8.5.31 is ok. but the function setProtocl is Deprecated.

**Comment by htynkn** [comment]
related doc link: https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/connector/Connector.html#setProtocol(java.lang.String)
