### ISSUE TITLE
[Enhancement] Setting the default IDs for Dubbo's Config Beans 

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo#5721]
The IDs of Dubbo's Config instances are very important metadata that will be cached into `ConfigManager` as the cache key, thus In Spring scenario, The bean names are identified and could be used as the value Of Ids.

**Comment by iamorchid** [comment]
这里的change导致了另外一个问题，config bean的id会作为property key的一部分，会导致出现这样的property key: dubbo.registry.**org.apache.dubbo.config.RegistryConfig#0**.address，其中org.apache.dubbo.config.RegistryConfig#0是bean的id。这将导致其他配置中key为dubbo.registry.address的配置失效。config prefix + id作为property key的前缀，这个是否有必要呢？多数情况下，用户更关心的是config prefix.

**Comment by iamorchid** [comment]
另外一个问题是，我将dubbo.registry相关的配置放在spring管理的PropertySource里面，这时产生的RegistryConfig有携带注入上面comment中的id。但将dubbo.registry相关的配置放置在dubbo.properties文件中，由dubbo自己加载，这是产生的RegistryConfig对象的id为null。如果将id作为property key的一部分，这种差异将导致难以理解。

**Comment by Devifish** [comment]
该修改导致在添加了`EnableDubbo`或`DubboComponentScan`等注解的情况下 `ApplicationConfig`配置的 name 参数注入并覆盖了配置文件的参数为 `org.apache.dubbo.config.ApplicationConfig#0`引发ApplicationConfig.name 名称不符合规则异常
