### ISSUE TITLE
status -l里面的load warn

### ISSUE THREAD

**Issue by zong400** [apache/dubbo#5722]
您好，我有点不明白telent 命令status -l里面出来的load代表的意义。
我们的服务跑在k8s里面，配置了cpu limit是1000m，从系统资源看，单个容器的cpu使用率还很低，但是load已经warn了

dubbo status:
| load       | WARN   | load:1.52197265625,cpu:1 

CPU           mem
155m         856Mi

**Comment by biyuhao** [comment]
你好，
在你的单个容器内，1core cpu 的 load 为 1.52 可以认为是已经比较繁忙了
相关代码如下：
```
    public Status check() {
        OperatingSystemMXBean operatingSystemMXBean = ManagementFactory.getOperatingSystemMXBean();
        double load;
        try {
            Method method = OperatingSystemMXBean.class.getMethod("getSystemLoadAverage", new Class<?>[0]);
            load = (Double) method.invoke(operatingSystemMXBean, new Object[0]);
            if (load == -1) {
                com.sun.management.OperatingSystemMXBean bean =
                        (com.sun.management.OperatingSystemMXBean) operatingSystemMXBean;
                load = bean.getSystemCpuLoad();
            }
        } catch (Throwable e) {
            load = -1;
        }
        int cpu = operatingSystemMXBean.getAvailableProcessors();
        return new Status(load < 0 ? Status.Level.UNKNOWN : (load < cpu ? Status.Level.OK : Status.Level.WARN),
                (load < 0 ? "" : "load:" + load + ",") + "cpu:" + cpu);
    }
```
调用的api：
https://docs.oracle.com/javase/8/docs/api/java/lang/management/OperatingSystemMXBean.html#getSystemLoadAverage()

Linux Load相关介绍：
https://scoutapm.com/blog/understanding-load-averages

代码出处：
https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/status/support/LoadStatusChecker.java
