### ISSUE TITLE
加载扩展类时,因为类名相同导致的error

### ISSUE THREAD

**Issue by a364176773** [apache/dubbo#5726]
```
    private void saveInExtensionClass(Map<String, Class<?>> extensionClasses, Class<?> clazz, String name) {
        Class<?> c = extensionClasses.get(name);
        if (c == null) {
            extensionClasses.put(name, clazz);
        } else if (c != clazz) {
            String duplicateMsg = "Duplicate extension " + type.getName() + " name " + name + " on " + c.getName() + " and " + clazz.getName();
            logger.error(duplicateMsg);
            throw new IllegalStateException(duplicateMsg);
        }
    }
```
seata方面最近有用户反馈出现如下错误信息
`2020-02-10 21:51:30.686 ERROR 20076 --- [           main] o.a.d.common.extension.ExtensionLoader   :  [DUBBO] Duplicate extension org.apache.dubbo.rpc.Filter name transactionpropagation on io.seata.integration.dubbo.TransactionPropagationFilter and io.seata.integration.dubbo.alibaba.TransactionPropagationFilter, dubbo version: 2.7.4.1, current host: 192.168.1.103
`
在排查时,通过源码找到2.7.3其实就存在此问题,但是dubbo代码中还未打印此错误日志
在2.7.4.1中,因为findAnnotationName(clazz);通过class获取缓存name时如果类名想同,就会导致进入else if (c != clazz) 的方法块,因为2个类名相同,路径不同导致的bug,希望能解决下,通过限定类名或者其它手段来解决这个问题.
以下是seata的源码,同个类名,而dubbo这边取得是非限定类名,导致出现上诉问题
![image](https://user-images.githubusercontent.com/19943636/74155646-e537fb00-4c4f-11ea-871b-e2e81b541096.png)

**Comment by CodingSinger** [comment]
io.seata.integration.dubbo.TransactionPropagationFilter and io.seata.integration.dubbo.alibaba.TransactionPropagationFilter 应该是用了相同的extension name导致的

**Comment by a364176773** [comment]
> io.seata.integration.dubbo.TransactionPropagationFilter and io.seata.integration.dubbo.alibaba.TransactionPropagationFilter 应该是用了相同的extension name导致的

@CodingSinger 的确是如此,所以导致了这个问题,我个人认为应该也会有不少人使用扩展类名相同的情况吧,然后用包名区分开.

**Comment by CodingSinger** [comment]
这个短期内应该不会更改，插件实现方应该自己注意这个问题，避免重名。

**Comment by a364176773** [comment]
> 这个短期内应该不会更改，插件实现方应该自己注意这个问题，避免重名。

@CodingSinger 了解,感谢解疑.我们这边目前也正在处理.
