### ISSUE TITLE
请问下dubbo没有类似spring的BeanFactory的类吗？

### ISSUE THREAD

**Issue by jaxlove** [apache/dubbo#5728]
找了很久没有找到相关问题，client端想动态获取一个dubbo的引用，不知道有没有办法

**Comment by CodingSinger** [comment]
引用是指？获取`ReferenceBean`?

**Comment by jaxlove** [comment]
> 引用是指？获取`ReferenceBean`?

就是想像spring的Service service = Application.getBean(name|class)这样的方式获取bean

**Comment by wade-zhou** [comment]
本来就已经被spring管理起来了，直接按Application.getBean(name|class)方式就能获取到

**Comment by jaxlove** [comment]
> 本来就已经被spring管理起来了，直接按Application.getBean(name|class)方式就能获取到

我擦，还真是，谢谢了

**Comment by mercyblitz** [comment]
You can also use `ConfigManager` to retrieve all Dubbo config objects, including `ReferenceBean`
