### ISSUE TITLE
当dubbo使用nacos做注册中心的时候,该如何选择namespace呢?

### ISSUE THREAD

**Issue by cielswift** [apache/dubbo#5747]
dubbo: #dubbo配置
  registry:
    address: nacos://127.0.0.1:13100?backup=127.0.0.1:13101,127.0.0.1:13102 #使用nacos注册中心

这里会导致dubbo把所有的调用都注册到public 上;

我在配置里没有找到关于namespace的配置;
网路上也找不到关于修改namespace的;

**Comment by liuhonglin** [comment]
address: nacos://127.0.0.1:13100?namespace={namespace id} 这样

**Comment by cielswift** [comment]
太感谢了

**Comment by vergilyn** [comment]
dubbo.properties:
```properties
# dubbo底层参数绑定基于 spring-bean的 org.springframework.beans.MutablePropertyValues
# 所以，spring 4 与 spring 5 的语法可能不一样
# dubbo.registry.parameters.namespace=xxx

# spring-bean 5.2.2.RELEASE 成功绑定并注册到指定的namespace
dubbo.registry.parameters[namespace]=xxx  
```

**Comment by RongXiong2016** [comment]
同时注册到多namespace的呢

**Comment by yangzhiw** [comment]
> dubbo.properties:
> 
> ```ini
> # dubbo底层参数绑定基于 spring-bean的 org.springframework.beans.MutablePropertyValues
> # 所以，spring 4 与 spring 5 的语法可能不一样
> # dubbo.registry.parameters.namespace=xxx
> 
> # spring-bean 5.2.2.RELEASE 成功绑定并注册到指定的namespace
> dubbo.registry.parameters[namespace]=xxx  
> ```

为什么我只能使用这种方式：address: nacos://127.0.0.1:13100?namespace={namespace id} 是可以的；
