### ISSUE TITLE
dubbo telnet 

### ISSUE THREAD

**Issue by vonzou** [apache/dubbo#5748]
dubbo telnet command，when in param is Map ,and the key of the map is number，will throw Exception：java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

### Environment

* Dubbo version: all
* Operating System version: all
* Java version: all

### Steps to reproduce this issue

1. TELNET 127.0.0.1 20880
2. invoke com.xxx.xxxApiService({"3":0.123})
3. exception occurred:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by biyuhao** [comment]
please try this
```
invoke com.xxx.xxxApiService({"3":0.123, "class":"java.util.HashMap"})
```
specify the class type just like the UT case `testOverriddenMethodWithSpecifyParamType`

feel free to reopen.
