### ISSUE TITLE
2.7.5 dubbo.config-center don't work

### ISSUE THREAD

**Issue by yjx1045072812** [apache/dubbo#5778]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. create a simple app with dubbo
2. create dubbo.properties file which contains `dubbo.config-center.address=zookeeper://127.0.0.1:2181`
3. start app with springContainer
4. invoke`ApplicationModel.getConfigManager().getConfigCenters()` 

### Expected Result

 `ApplicationModel.getConfigManager().getConfigCenters()`  return a non-empty list, it contains an instance of `ConfigCenterConfig`

### Actual Result

 `ApplicationModel.getConfigManager().getConfigCenters()`  return a empty list

### Other

I just want test new API `DubboBootstrap` in 2.7.5, so the app is very simple. It does not contain any services.
And `dubbo.properties`is simple too :
```
dubbo.config-center.address=zookeeper://127.0.0.1:2181
dubbo.application.name=test
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
```
After dubbo starts, `DubboBootstarp.getApplication()` a returned the correct instance of `ApplicationConfig`, should `ApplicationModel.getConfigManager().getConfigCenters()`  return a non-empty list?

**Comment by itfinally** [comment]
Because Dubbo 2.7.5 startup too soon, Dubbo 2.7.4.1 is working.
This problem has been write on my [issue](https://github.com/apache/dubbo/issues/5777).

**Comment by yjx1045072812** [comment]
> Because Dubbo 2.7.5 startup too soon, Dubbo 2.7.4.1 is working.
> This problem has been written on my [issue](https://github.com/apache/dubbo/issues/5777).

You did a great job.
But by checking the source code of dubbo, I don't have any code to create a ConfigCenterConfig instance and add it to ConfigManager, sure this is a bug caused by the startup sequence? If you find the code, please show me.
