### ISSUE TITLE
Dubbo 2.7.5 服务分组，provider服务接口提供多个group，注册中心只看到一个

### ISSUE THREAD

**Issue by gaotingwang** [apache/dubbo#5779]
### Environment

* Dubbo version: 2.7.5
* Operating System version: macOS
* Java version: 1.8

### Steps to reproduce this issue

1. 使用服务分组功能，provider提供多个group
```java
@Service(version = "1.0", group = "group1", interfaceClass = GroupService.class)
public class GroupServiceImp1 implements GroupService {

    @Override
    public List<User> getUserInfo() {
        ...
    }

}

@Service(version = "2.0", group = "group2", interfaceClass = GroupService.class)
public class GroupServiceImp2 implements GroupService {

    @Override
    public List<User> getUserInfo() {
        ...
    }

}
```
2. 使用了zk做服务注册中心
3. 在Doubbo-Admin中只能看到`group1`的服务，看不到`group2`的服务，且consumer也只能调用`group1`的接口，`group2`提示No provider。

### Actual Result
跟踪代码，在`org.apache.dubbo.config.context.ConfigManager#addIfAbsent`方法中：
```java
static <C extends AbstractConfig> void addIfAbsent(C config, Map<String, C> configsMap, boolean unique) throws IllegalStateException {
    if (config != null && configsMap != null) {       
         // 这里因为不同group的key是相同的，导致configsMap没有加入其它group的ServiceBean
        String key = getId(config);
        C existedConfig = (AbstractConfig)configsMap.get(key);
        if (existedConfig != null && !config.equals(existedConfig)) {
            if (logger.isWarnEnabled()) {
                String type = config.getClass().getSimpleName();
                logger.warn(...);
            }
        } else {
            configsMap.put(key, config);
        }

    }
}
```
而这里key是根据Interface进行setId，不同group的实现的是相同Interface，所以导致key相同。

有什么解决办法吗？还是我本身使用哪里出了问题，导致服务分组功能不可用

**Comment by mercyblitz** [comment]
This issue has been fixed, but you have to wait for the 2.7.6 release. If you'd like to fix it in the emergency, I suggest you copy the code https://github.com/apache/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/config/DubboConfigDefaultPropertyValueBeanPostProcessor.java, and define it as the Spring Bean.
