### ISSUE TITLE
Expansion of ConcurrentHashMap in ExtensionLoader

### ISSUE THREAD

**Issue by caishi13202** [apache/dubbo#5797]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: windows
* Java version: 1.8

In ExtensionLoader, EXTENSION INSTANCES is a ConcurrentHashMap with a default size, and the extension class provided in Dubbo has exceeded 16. 
Start the program, it will expand at least twice. I think it is more appropriate to add an initial size of 64 here. 
Other places where ConcurrentHashMap is used should also pay attention to a suitable initial size

**Comment by chickenlj** [comment]
Would you like to create a patch to improve it?
