### ISSUE TITLE
About the parsing process of dynamic config center

### ISSUE THREAD

**Issue by itfinally** [apache/dubbo#5817]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: MacOS
* Java version: JDK1.8

### Steps to reproduce this issue

Quote the [issue](https://github.com/apache/dubbo/issues/5777#event-3081652635) to continue question about ***Not friendly with the YAML config***.

**You can use any dynamic config center as Dubbo configuration provider( Must be use other format to write your configuration, like YAML, XML, etc... ), them you verify this issue.**

The one of example of about "Not friendly with the YAML config", you can found that code in the class `org.apache.dubbo.config.AbstractInterfaceConfig`( Version 2.7.4.1 ) , line 303 & 304 .

```java
Environment.getInstance().updateExternalConfigurationMap(parseProperties(configContent));
Environment.getInstance().updateAppExternalConfigurationMap(parseProperties(appConfigContent));
```

You can not expect everyone have to use "Properties" format to write them configurations, this code can not handling other format like YAML, so that someone use other format like me have to customize own protocol by SPI for handle the configuration parsing process. 

My suggest is, do not write that dead code like "parseProperties".

Or, also can write a document to teach everyone to handling this situation if someone use other format like me.

### Expected Result

Pull all config from remote config center ( like Nacos / Apollo ) and **parse configuration in other formats successfully**. 

### Actual Result

Parsing any format configurations as "Properties" format, and failure.

The configuration parsing process is unreasonable, that code only accept "Properties" format.

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
