### ISSUE TITLE
"payload" configuratoin doesn't work  in consumer side while setting simplified="true" 

### ISSUE THREAD

**Issue by liusf1993** [apache/dubbo#5830]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version:Linux version 4.15.0-88-generic 16.04.1-Ubuntu
* Java version: java version "1.8.0_201"

### Steps to reproduce this issue

1. server-side configuration
```
     <dubbo:registry  address="zookeeper://127.0.0.1:2181" check="false" simplified="true"
      file="${user.home}/.dubbo/${application.name}-cache.properties"/>
    <dubbo:provider timeout="60000" retries="1" payload="104857600" />
    <dubbo:metadata-report address="zookeeper://127.0.0.1:2181"  />
```
2. client-side
   invoke method, and the response' data size  is more than 8M(default payload) but less than 100M(configued payload).

### Expected Result
  there is not exception, and the result was returned as expected.
### Actual Result
  throws an ExceedPayloadLimitException
```
Caused by: org.apache.dubbo.remoting.transport.ExceedPayloadLimitException: Data length too large: 11727594, max payload: 8388608, channel: NettyChannel [channel=[id: 0x61f431d2, L:/172.18.0.1:52186 - R:/172.18.0.1:20880]]
	at org.apache.dubbo.remoting.transport.AbstractCodec.checkPayload(AbstractCodec.java:50)
```

**Comment by xiantang** [comment]
i  cannot reproduce this bug. plz show me the Minimum size demo which can reproduce this bug. @liusf1993

**Comment by liusf1993** [comment]
here is a demo to replay the question https://github.com/liusf1993/dubbo-test.git

**Comment by liusf1993** [comment]
> i cannot reproduce this bug. plz show me the Minimum size demo which can reproduce this bug. @liusf1993

here is a demo to replay the question https://github.com/liusf1993/dubbo-test.git

**Comment by Huangxuny1** [comment]
well , after debug .  I can draw a conclusion, 

when ` <dubbo:registry address="zookeeper://127.0.0.1:2181" check="false" simplified="false"/>
`
the `channel.getUrl()` is 
> dubbo://127.0.0.1:20880/IDemoService?anyhost=true&application=demo-consumer&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&init=false&interface=IDemoService&methods=sayHello&`payload=204857600`&pid=18148&qos.enable=false&register.ip=127.0.0.1&release=2.7.7-SNAPSHOT&remote.application=demo-provider&retries=1&side=consumer&sticky=false&timeout=60000&timestamp=1586184578922

the url contains a key `payload` that will be used in (`payload = channel.getUrl().getParameter(Constants.PAYLOAD_KEY, Constants.DEFAULT_PAYLOAD);
`)[https://github.com/apache/dubbo/blob/228cad5ef439b7db6fe62566dcd158ce0a127b4b/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractCodec.java#L47]

but when `<dubbo:registry address="zookeeper://127.0.0.1:2181" check="false" simplified="true"/>
` 
the `channel.getUrl()` is 
> dubbo://127.0.0.1:20880/IDemoService?application=demo-consumer&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&heartbeat=60000&init=false&interface=IDemoService&pid=18210&qos.enable=false&register.ip=127.0.0.1&release=2.7.7-SNAPSHOT&remote.application=demo-provider&side=consumer&sticky=false&timeout=60000&timestamp=1586184981868

there is no key `payload` becase of simplified

so `
> payload = channel.getUrl().getParameter(Constants.PAYLOAD_KEY, Constants.DEFAULT_PAYLOAD);` 

the `Constants.DEFAULT_PAYLOAD`  size is 8M
> int DEFAULT_PAYLOAD = 8 * 1024 * 1024;

but in this issue the size is `9437210`  

so in (AbstractCodec.java)[https://github.com/apache/dubbo/blob/228cad5ef439b7db6fe62566dcd158ce0a127b4b/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/transport/AbstractCodec.java#L49-L53]  
throw `ExceedPayloadLimitException`

**Comment by cvictory** [comment]
I think you can refer this https://github.com/apache/dubbo/pull/5974.
