### ISSUE TITLE
didn't find this package org.apache.dubbo.common.serialize.protobuf.support.wrapper

### ISSUE THREAD

**Issue by HHeyJ** [apache/dubbo#5846]

**Comment by chickenlj** [comment]
What's the problem exactly? `org.apache.dubbo.common.serialize.protobuf.support.wrapper` is generated from [proto](https://github.com/apache/dubbo/tree/master/dubbo-serialization/dubbo-serialization-protobuf/src/main/proto) by protobuf and is packaged in the released binary.

**Comment by chickenlj** [comment]
Reopen if necessary.

**Comment by TotoroOnTheTree** [comment]
I had the same problem when i ran the demo (dubbo/dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/). Have you solved it？

**Comment by HHeyJ** [comment]
> I had the same problem when i ran the demo (dubbo/dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-provider/). Have you solved it？

抱歉刚看到这条信息，现在我运行之前下的代码启动dubbo-demo-XML-Provider and Dubbo-demo-XML-Consumer是好的

**Comment by TotoroOnTheTree** [comment]
嗯，后面找到原因了，要用Protobuf的命令生成warpper文件。其实@chickenlj给出了答案，只是我当时没注意。感谢回复。
