### ISSUE TITLE
bug found in the service discovery. can be repeated

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo#5866]
### Environment

* Dubbo version: 2.7.4.1
* Operating System version: k8s(centos)
* Java version: JDK1.8

### Steps to reproduce this issue

spring cloud alibaba 2.2(dubbo 1.7.4)和nacos的程序，在k8s下测试，一个问题卡住挺久了，求教。
1.  provider先启动，consumer启动，测试服务调用，正常。
2. 把provider 的pod删除，k8s自动启动一个provider的pod,且provider的ip发生变化。nacos查看，正常。测试服务调用，正常。
3.再把provider 的pod删除（已经是第2次删除），k8s自动启动一个provider的pod,且provider的ip发生变化。测试服务调用，异常

![image](https://user-images.githubusercontent.com/27885492/76684452-22285080-6647-11ea-9776-90097a345114.png)

我试过合入(#5858) 到本地dubbo 1.7.4代码，修改后确定用改后的代码。问题依旧，无法解决。

**Comment by imgoby** [comment]
Now I have the rules：
problem will appear when execute command: kubelet delete pod xxx  
but not appear where execute  : kubectl scale --replicas=0 deployment xxx  ，kubectl scale --replicas=1 deployment xxx 。
why?
I think it is a bug.

**Comment by chickenlj** [comment]
I think it's likely to be a Registry related issue, which Registry did you use when experiencing this problem?

It seems to be that the Registry can not detect the removed pod and delete the item from its storage.

**Comment by imgoby** [comment]
It has been solved In Spring Cloud Alibaba

**Comment by mercyblitz** [comment]
Resolved in Spring Cloud Alibaba 2.2.1.RELEASE
