### ISSUE TITLE
2.7.5版本特性里增加新的SPI，有介绍使用的地方么？

### ISSUE THREAD

**Issue by haoxz11** [apache/dubbo#5882]
2.7.5版本特性里增加新的SPI，有介绍使用的地方么？

**Comment by haoxz11** [comment]
通过代码里找到了，的确是动态修改元数据，但是只有启动时生效，后面想改的话没有监听事件。

**Comment by CrazyHZM** [comment]
Issues have been created in the dubbo-website project
