### ISSUE TITLE
无法将元数据保存至dubbo.medata-report.address

### ISSUE THREAD

**Issue by ywengineer** [apache/dubbo#5887]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: macOS 10.15.3 (19D76)
* Java version: 1.8.241

### Steps to reproduce this issue

1. 启用将metadata保存至remote的方式为dubbo.application.metadata-type=remote
2. 配置dubbo.metadata-report.adress=nacos://127.0.0.1:8848
3. 无法在Nacos查看服务元数据

为导出服务的URL生成的metadata相关的参数名为metadata.type，但常量METADATA_KEY的值为metadata。因此获得的WritableMetadataService为InMemoryWritableMetadataService，导致无法将元数据保存到remote

org.apache.dubbo.config.ServiceConfig#487
```java
WritableMetadataService metadataService = WritableMetadataService.getExtension(url.getParameter(METADATA_KEY, DEFAULT_METADATA_STORAGE_TYPE));
                if (metadataService != null) {
                    metadataService.publishServiceDefinition(url);
                }
```

**Comment by ywengineer** [comment]
可以在@Service注解添加parameters={"metadata", "remote"}临时解决问题。

**Comment by yyzx428** [comment]
[(#5809)](https://github.com/apache/dubbo/pull/5809)  这个提交有修改这个问题

**Comment by ywengineer** [comment]
@yyzx428 2.7.6及之后的metadata report有调整.
