### ISSUE TITLE
depend on new hessian-lite in 2.7.7

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#5892]
hessian-lite has a performance improvement (https://github.com/apache/dubbo-hessian-lite/pull/27), we need to bump up hessian-lite and depend on the new version in the next dubbo release.

**Comment by beiwei30** [comment]
we also need to merge https://github.com/apache/dubbo/pull/5889

**Comment by chickenlj** [comment]
We will for the hessian 3.2.7 to release, it's voting now.
