### ISSUE TITLE
dubbo-registry-consul  build fail

### ISSUE THREAD

**Issue by Gibaldiqqq** [apache/dubbo#5918]
I have searched the issues of this repository and believe that this is not a duplicate.
 I have checked the FAQ of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version:CentOS 7.6
* Java version: 1.8

### Steps to reproduce this issue

1. cd dubbo-dubbo-2.7.5/dubbo-registry/dubbo-registry-consul/
2. mvn install

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

BUILD SUCCESS

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.dubbo.registry.consul.ConsulRegistryTest
log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.924 s <<< FAILURE! - in org.apache.dubbo.registry.consul.ConsulRegistryTest
[ERROR] testAvailable  Time elapsed: 0.876 s  <<< ERROR!
java.net.UnknownHostException: releases.hashicorp.com
        at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:54)

[ERROR] testRegister  Time elapsed: 0.003 s  <<< ERROR!
java.net.UnknownHostException: releases.hashicorp.com
        at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:54)

[ERROR] testStatusChecker  Time elapsed: 0.002 s  <<< ERROR!
java.net.UnknownHostException: releases.hashicorp.com
        at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:54)

[ERROR] testSubscribe  Time elapsed: 0.003 s  <<< ERROR!
java.net.UnknownHostException: releases.hashicorp.com
        at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:54)

[ERROR] testLookup  Time elapsed: 0.003 s  <<< ERROR!
java.net.UnknownHostException: releases.hashicorp.com
        at org.apache.dubbo.registry.consul.ConsulRegistryTest.setUp(ConsulRegistryTest.java:54)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   ConsulRegistryTest.setUp:54 » UnknownHost releases.hashicorp.com
[ERROR]   ConsulRegistryTest.setUp:54 » UnknownHost releases.hashicorp.com
[ERROR]   ConsulRegistryTest.setUp:54 » UnknownHost releases.hashicorp.com
[ERROR]   ConsulRegistryTest.setUp:54 » UnknownHost releases.hashicorp.com
[ERROR]   ConsulRegistryTest.setUp:54 » UnknownHost releases.hashicorp.com
[INFO]
[ERROR] Tests run: 5, Failures: 0, Errors: 5, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.487 s
[INFO] Finished at: 2020-03-28T07:34:42+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project dubbo-registry-consul: There are test failures.
[ERROR]
[ERROR] Please refer to /home/Dubbo/dubbo-dubbo-2.7.5/dubbo-registry/dubbo-registry-consul/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExceptio

**Comment by AlbumenJ** [comment]
The tests in dubbo-registry-consul requires download consol binary from releases.hashicorp.com. 
Maybe you can check your network connection to releases.hashicorp.com.

**Comment by AlbumenJ** [comment]
related codes are in `com.pszymczyk.consul`

```
        <dependency>
            <groupId>com.pszymczyk.consul</groupId>
            <artifactId>embedded-consul</artifactId>
            <scope>test</scope>
        </dependency>
```

```
package com.pszymczyk.consul.infrastructure

class HttpBinaryRepository {

    public static final String CONSUL_BINARY_CDN = "CONSUL_BINARY_CDN"
    public static final String CONSUL_DEFAULT_CDN = "https://releases.hashicorp.com/consul/"

    File getConsulBinaryArchive(String version, File file) {
        httpsProtocolsSetter.setRequiredTls(System.getProperty("java.version"), System.getProperty("https.protocols"))
        String os = OsResolver.resolve()
        String cdn = System.getenv(CONSUL_BINARY_CDN) != null ? System.getenv(CONSUL_BINARY_CDN)
                : System.getProperty(CONSUL_BINARY_CDN) != null ? System.getProperty(CONSUL_BINARY_CDN) : CONSUL_DEFAULT_CDN;
        String url = "${cdn}${version}/consul_${version}_${os}_amd64.zip"
        OutputStream outputStream = file.newOutputStream()
        outputStream << new URL(url).openStream()
        outputStream.close()
        file
    }
}
```

**Comment by htynkn** [comment]
`releases.hashicorp.com` is accessable. could you please check your network connection again?
If you only want to build jar file, you can skip tests by adding `-DskipTests`

**Comment by Gibaldiqqq** [comment]
Thank you very much! Currently I'm fixing the network
