### ISSUE TITLE
Is it better to put this code outside of the for?

### ISSUE THREAD

**Issue by qiaolin-li** [apache/dubbo#5919]
https://github.com/apache/dubbo/blob/cefe7c37e9c31d478b2fe08f323c1f9542ca1466/dubbo-common/src/main/java/org/apache/dubbo/common/extension/ExtensionLoader.java#L571-L594

Is it better to put this code outside of the for?
```java
if (i == 1) { 
             buf.append(", possible causes: "); 
         } 
```

**Comment by htynkn** [comment]
I agree this is some code smell we can optimize. Also I notice the hard coded string for newline `\r\n`.  

We are happy to accept any PR which can help to fix code smell.

**Comment by qiaolin-li** [comment]
I'll try PR for the first time

**Comment by qiaolin-li** [comment]
Which branch should I target if I initiate PR? 3. X-dev?

**Comment by htynkn** [comment]
I just confirm this code is in master branch too. Could you please try open PR to master branch?

**Comment by qiaolin-li** [comment]
ok

**Comment by htynkn** [comment]
close this issue. more detail refer to #5920
