### ISSUE TITLE
有关泛化调用的一些问题

### ISSUE THREAD

**Issue by chocotan** [apache/dubbo#5929]
1. 不管服务提供方抛出什么异常，消费方接收到的都是 RpcException 且 异常堆栈被以字符串的方式 放在 exceptionMessage中
2. 消费方传输的参数中一旦包含有数组字段，且数组中包含 null元素，服务提供方会抛NullPointerException
3. 涉及到泛型的时候，为什么需要消费方在数据中增加class字段？ 我在使用spring mvc或者其他框架时没有遇到过有需要调用方传输类型才能够正确工作的情况
4. 如果服务提供方的Dubbo Filter中抛出了异常，那么消费方接收到的RpcException的code均为 RpcException.NETWORK_EXCEPTION，给消费方的异常判断造成了困扰
5. 在早期的版本中，泛化调用时，路由规则是不生效的

以上我均可以提供相关示例代码

**Comment by powerttt** [comment]
同样遇到此类问题，重写GenericFilter拦截自定义的异常无效了,还没有找到优雅的绝决方案。泛化调用时，提供者返回的结果对象，都会加入class属性。

**Comment by chickenlj** [comment]
> 消费方传输的参数中一旦包含有数组字段，且数组中包含 null元素，服务提供方会抛NullPointerException

这一点接下来会进行修复

**Comment by chickenlj** [comment]
> 如果服务提供方的Dubbo Filter中抛出了异常，那么消费方接收到的RpcException的code均为 RpcException.NETWORK_EXCEPTION，给消费方的异常判断造成了困扰

> 在早期的版本中，泛化调用时，路由规则是不生效的

这两点会进一步予以确认

**Comment by Jijun** [comment]
> 消费方传输的参数中一旦包含有数组字段，且数组中包含 null元素，服务提供方会抛NullPointerException

我们遇到了同样的问题。同样是数组中有null元素。

**Comment by CrazyHZM** [comment]
After confirming, the above problems have not been reproduced in the new version, please provide your version number, or try it with the latest version, if you still have problems, you can reopen the issue.

**Comment by HRsGIT** [comment]
> 1. 不管服务提供方抛出什么异常，消费方接收到的都是 RpcException 且 异常堆栈被以字符串的方式 放在 exceptionMessage中
> 2. 消费方传输的参数中一旦包含有数组字段，且数组中包含 null元素，服务提供方会抛NullPointerException
> 3. 涉及到泛型的时候，为什么需要消费方在数据中增加class字段？ 我在使用spring mvc或者其他框架时没有遇到过有需要调用方传输类型才能够正确工作的情况
> 4. 如果服务提供方的Dubbo Filter中抛出了异常，那么消费方接收到的RpcException的code均为 RpcException.NETWORK_EXCEPTION，给消费方的异常判断造成了困扰
> 5. 在早期的版本中，泛化调用时，路由规则是不生效的
> 
> 以上我均可以提供相关示例代码



> 1. 不管服务提供方抛出什么异常，消费方接收到的都是 RpcException 且 异常堆栈被以字符串的方式 放在 exceptionMessage中
> 2. 消费方传输的参数中一旦包含有数组字段，且数组中包含 null元素，服务提供方会抛NullPointerException
> 3. 涉及到泛型的时候，为什么需要消费方在数据中增加class字段？ 我在使用spring mvc或者其他框架时没有遇到过有需要调用方传输类型才能够正确工作的情况
> 4. 如果服务提供方的Dubbo Filter中抛出了异常，那么消费方接收到的RpcException的code均为 RpcException.NETWORK_EXCEPTION，给消费方的异常判断造成了困扰
> 5. 在早期的版本中，泛化调用时，路由规则是不生效的
> 
> 以上我均可以提供相关示例代码

请问可以提供示例代码吗 我在复现时候好像并没有遇到2和4问题
