### ISSUE TITLE
按照路由扩展的文档自定义路由后，怎么让路由生效，是不是要往注册中心写一些东西，这部分在文档里没有说明

### ISSUE THREAD

**Issue by liunancun** [apache/dubbo#5932]
按照路由扩展的文档自定义路由后，怎么让路由生效，是不是要往注册中心写一些东西，这部分在文档里没有说明

**Comment by liunancun** [comment]
Dubbo-Admin那边也只能陪着条件路由和标签路由，没有自定义路由的配置

**Comment by bigbang555** [comment]
配置了路由的话，在对应/duubo/xxx.xxx.XxxService/routers下会有相应的节点生成的

**Comment by RojerAlone** [comment]
不需要，在你的扩展 `XxxRouterFactory` 加上 `@Activate` 注解即可。

**Comment by liunancun** [comment]
现在是加了@Activate注解，如果只想对部分服务生效可以配置吗，现在所有服务调用都经过这个路由

**Comment by RojerAlone** [comment]
@liunancun 两种办法：
1. 查找官方文档，不过我以前找过没找到，或者你直接看代码是否有相关逻辑，我在 `RouterChain` 中没找到
2. 在你的 Router 中配置，根据请求信息判断是否进行路由操作

**Comment by lishun888** [comment]
目前按照上面说的配置，还是没有生效

**Comment by lishun888** [comment]
String routerkey = url.getParameter(Constants.ROUTER_KEY);
        if (routerkey != null && routerkey.length() > 0) {
            RouterFactory routerFactory = ExtensionLoader.getExtensionLoader(RouterFactory.class).getExtension(routerkey);
            routers.add(routerFactory.getRouter(url));
        }

源码上是要求从zk url获取参数的，这块不知道要怎么处理
