### ISSUE TITLE
telnet 问题

### ISSUE THREAD

**Issue by wuwu955** [apache/dubbo#5938]
### Environment

* Dubbo version: com.alibaba.dubbo 2.8.4
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue
telnet dubbo 服务端口号能通  而输入ls 命令没有 输出服务接口列表  并且这个服务的所有接口调用超时  请问这个是什么原因？

**Comment by AlbumenJ** [comment]
In #5815 , this issue has been solved.

**Comment by wuwu955** [comment]
> In #5815 , this issue has been solved.

Thank you for answering that question. I read the issue, but the problem I encountered was not that the ls command could not be found, but that the service interface list was not output. Do you know the reason?

**Comment by AlbumenJ** [comment]
> > In #5815 , this issue has been solved.
> 
> Thank you for answering that question. I read the issue, but the problem I encountered was not that the ls command could not be found, but that the service interface list was not output. Do you know the reason?

> Dubbo version: com.alibaba.dubbo 2.8.4

The lastest dubbo version is 2.7.6, and it seems that the 2.8.4 version has not been released yet. Could you please check your dubbo version?

**Comment by wuwu955** [comment]
> > > In #5815 , this issue has been solved.
> > 
> > 
> > Thank you for answering that question. I read the issue, but the problem I encountered was not that the ls command could not be found, but that the service interface list was not output. Do you know the reason?
> 
> > Dubbo version: com.alibaba.dubbo 2.8.4
> 
> The lastest dubbo version is 2.7.6, and it seems that the 2.8.4 version has not been released yet. Could you please check your dubbo version?

My project uses alibaba dubbo 2.8.4 not apache dubbo

**Comment by AlbumenJ** [comment]
I think you may use Dubbox which is maintained by [dangdangdotcom](https://github.com/dangdangdotcom/dubbox). Dubbox has stopped updating for about three years and Dubbox has been merged  into Apache Dubbo. Maybe you can upgrade dubbo to Apache Dubbo and see whether this problem still exist.

**Comment by wuwu955** [comment]
> I think you may use Dubbox which is maintained by [dangdangdotcom](https://github.com/dangdangdotcom/dubbox). Dubbox has stopped updating for about three years and Dubbox has been merged into Apache Dubbo. Maybe you can upgrade dubbo to Apache Dubbo and see whether this problem still exist.

Okay, I closed this issue and watched it for a while.
