### ISSUE TITLE
telnet issue

### ISSUE THREAD

**Issue by infuq** [apache/dubbo#5939]
### Environment

* Dubbo version: 2.7.4.1
* Operating System version: macOS Catalina Version 10.15.3
* Java version: 1.8.0_231

### Steps to reproduce this issue

1. 通过telnet调用接口如下
方法(Method)
`public String convert7(UserInfoCondition userInfoCondition) {  }`
参数(Parameter)
`public class UserInfoCondition {
    private List<Map<Integer, UserInfo>> userList;
}`
`public class UserInfo {
    private String accountMobile;
    private String userPassword;
}`

invoke UsesrInfoFacade.convert7({"userList":[{"1":{"accountMobile":"15052234567"}}]})
or
invoke UsesrInfoFacade.convert7({"userList":[{1:{"accountMobile":"15052234567"}}]})

提示如下错误(has a problem)
![image](https://user-images.githubusercontent.com/17045745/77892951-ebd50d00-72a5-11ea-95b0-dd59a68a83cc.png)

到底如何书写这个入参呢?(How to write the parameters)

**Comment by promiss** [comment]
尝试了很多种写法, 也指定了class, 还是失败, 不知道问题出在哪里.

**Comment by DIscord010** [comment]
和#5748应该是一个问题。 `invoke DemoService.sayHello({"userList":[{"1":{"accountMobile":"15052234567"},"class":"java.util.HashMap"}]}) `这样是可行的
