### ISSUE TITLE
Zone area can not get in ZoneAwareClusterInvoker

### ISSUE THREAD

**Issue by snailbinich** [apache/dubbo#5943]
### Environment

* Dubbo version: 2.7.5
* Operating System version: max os catalina  10.15.4
* Java version:1.8
### Steps to reproduce this issue

1.  start two zookeeper as registies
2.  start tow helloService as providers , Register to two different registries

3.  start a consumer,  create a registes using the flowing code
` public RegistryConfig createRegistryConfig(String registry, String  zoneCode){

        RegistryConfig config = new RegistryConfig(registry, protocol);
        config.setCluster(LdcAwareCluster.NAME); 
        config.setZone(zoneCode); //unit
        config.setUseAsConfigCenter(Boolean.FALSE);
        config.setParameters(parmeters);
        return  config;
    }`

4. but it can't get zone in ZoneAwareClusterInvoker line 70
`invoker.getUrl().getParameter(REGISTRY_KEY + "." + ZONE_KEY)`

I look into the source code , and i found org.apache.dubbo.registry.integration.RegistryDirectory#turnRegistryUrlToConsumerUrl

`return URLBuilder.from(url)
                .setPath(url.getServiceInterface())
                .clearParameters()
                .addParameters(queryMap)
                .removeParameter(MONITOR_KEY)
                .build()`

here cleared the parameters and append map as parameters, but the querymap just has the PREFERRED_KEY ,not ZONE_KEY, so i guess in the code  org.apache.dubbo.registry.integration.RegistryDirectory#turnRegistryUrlToConsumerUrl
`String isDefault = url.getParameter(PREFERRED_KEY);
        if (StringUtils.isNotEmpty(isDefault)) {
            queryMap.put(REGISTRY_KEY + "." + PREFERRED_KEY, isDefault);
        }`

it should put ZONE_KEY into the map, so the ZoneAwareClusterInvoker can get the ZONE_KEY,
is it right? or how can i  get the ZONE_KEY in ZoneAwareClusterInvoker?

**Comment by xli1224** [comment]
This has been resolved in 2.7.6.  #5654

**Comment by snailbinich** [comment]
> This has been resolved in 2.7.6. #5654

Thanks
