### ISSUE TITLE
使用默认 protocol 配置的问题

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#5947]
![image](https://user-images.githubusercontent.com/18097545/78014651-d54cb580-737a-11ea-809c-fe5dc884ec55.png)

dubbo 2.7.3， 同时暴露rest和dubbo，com.alibaba.dubbo.samples.echo.api.EchoService这个接口是dubbo协议的，还是当做rest来暴露？

**Comment by zhouhaopeng** [comment]
2中协议会同时暴露，rest协议需要在接口上添加@path注解，添加web访问路径

**Comment by wuwenhui0917** [comment]
private void doExportUrls() {
        List<URL> registryURLs = loadRegistries(true);
        _for (ProtocolConfig protocolConfig : protocols) {_
            //服务唯一标记
            String pathKey = URL.buildKey(getContextPath(protocolConfig).map(p -> p + "/" + path).orElse(path), group, version);
            //发布的方法
            ProviderModel providerModel = new ProviderModel(pathKey, ref, interfaceClass);
            ApplicationModel.initProviderModel(pathKey, providerModel);
            doExportUrlsFor1Protocol(protocolConfig, registryURLs);
        }
    }
上面就是export服务代码，配置几个协议会发布几个协议的。
