### ISSUE TITLE
default. 导致的高版本与低版本间的服务发现问题（default.version default.group）

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#5948]
lower version, for example 2.6.8
```properties
dubbo.provider.version=1.0
```

2.7.6 failed to recognize the provider url with 'default.version=1.0' key,  it only takes 'version.1.0' into consideration.

**Comment by lkxiaolou** [comment]
我测试了2.7.7这个兼容并没有效果，看了下2.6.6的代码是这样兼容的
![image](https://user-images.githubusercontent.com/6935924/112637517-379aa200-8e79-11eb-9a2d-c45b0b3c03aa.png)
