### ISSUE TITLE
[Solution] How to integrate Apache Dubbo with Nacos authentication

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo#5956]
## Introduction
Although Apache Dubbo 2.7.6 had been released, built-in artifact `org.apache.dubbo:dubbo-registry-nacos` could not cooperate with Nacos Server 1.2.0+ enabling authentication. This issue will help you how to integrate them.

## Prerequisites
- Nacos Server 1.2.0+ enabling authentication feature [[Guide](https://nacos.io/en-us/blog/nacos%201.2.0%20guide.html)]
- Apache Dubbo 2.7.5+

### Adding the Maven dependencies

Adding following dependencies into your `pom.xml`

```xml
        <!-- Dubbo Registry Nacos -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>2.7.6</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>1.2.1</version>
        </dependency>
```

### Updating the externalized properties

> Assuming that username and password are "nacos" 

- For Spring stack applications

Assuming that your application is using Spring Framework 3.1+, and current `Properties` file is like this :

```properties
## Nacos registry address
dubbo.registry.address = nacos://127.0.0.1:8848
```

You should append the Nacos authentication username and password as the parameters, as following

```properties
dubbo.registry.address = nacos://127.0.0.1:8848/?username=nacos&password=nacos
```

- For Raw API  applications

Before:
```java
    RegistryConfig registryConfig = ...
    registryConfig.setAddress("nacos://127.0.0.1:8848");
```

After:
```java
    RegistryConfig registryConfig = ...
    registryConfig.setAddress("nacos://127.0.0.1:8848/?username=nacos&password=nacos");
```

### Bugfixs

`com.alibaba:dubbo-registry-nacos:2.7.6` also fixes some known bugs in Dubbo 2.7.6, please see 
- PR : https://github.com/apache/dubbo/pull/5902
- Issues : #5871 #5885 and #5899

### Compatibility

Being compatible with Dubbo Nacos Registry 2.6+. 

### Documents

https://github.com/mercyblitz/dubbo-registry-nacos

### Warning

`com.alibaba:dubbo-registry-nacos:2.7.6` is not a long-term maintaining module, it will be replaced by Apache Dubbo 2.7.7.

**Comment by RojerAlone** [comment]
Is this solution useful only for users who use Nacos 1.2+ and enable authentication? It seems can't resolve #5871

**Comment by liuyanghui** [comment]
dubbo 2.7.5 目前不支持，需要修改源码
