### ISSUE TITLE
the guarantee of the order of notifications

### ISSUE THREAD

**Issue by wavesZh** [apache/dubbo#5961]
How to guarantee the order of notifications？From `NotifyListener#notify`:

>The order of notifications to be guaranteed by the notifications(That is, the implementation of the registry). Such as: single thread push, queue serialization, and version comparison.

If Dubbo realize it by single thread push,  i thinks it is a bug beacause the existance of `AbstractRetryTask`.   If a action1 for A fail then submit to timer to try,  but before the retry, action2 for A happen and success,  then task retry success, maybe happen overide.

**Comment by chickenlj** [comment]
I just noticed there's one `FailedNotifiedTask`, I think what you worry is possible to happen. It needs to be fixed.

**Comment by wavesZh** [comment]
Not only `FailedNotifiedTask`, other implementations for `AbstractRetryTask` : subscribe, register  maybe have some problem.

**Comment by laddcn** [comment]
Mybe version comparison is the best method to guarantee order of notifications. Retry task will break order for single thread push in certain situations. We can tag versions(atomic incremental) all notifications(data) for the same url(type) when notifications are received, and store the newest version when nofications are processed successfully. Before notify method are processed, version comparison are processed at first.
However, other data(such as subscribe, register information) maybe have the same problem, this solution will affectted a lot of methods. Aop maybe an appropriate way for implement.

**Comment by chickenlj** [comment]
Yeah, I agree, subscribe register also has the risk, but I think it's of relatively low risk than notification.

**Comment by laddcn** [comment]
@chickenlj I have read related codes, it is not so complicated as expected. I can give a PR to resolve the problem of notifications this weekend.

**Comment by chickenlj** [comment]
@laddcn. Please go ahead. But I worry if we can achieve that without a lock being used on the main notification path.

**Comment by laddcn** [comment]
I have an idea. 
This above problem occurs under 2 conditions:
1. Wrong order of notify operation of main loop and retry task. And this problem only occurs when retry task after main loop 
2. There are two versions of data: main loop(new), retry task(old)

I is hard to break the first condition without lock. However, it is easy to break the second condition when the first condition occurs:
1. We only hold the newest data(volatile) for various category, which are used by main loop and retry task
2. We update data before notify operation in  main loop. Then when the first condition occurs, data is the newest both in main loop and retry task. Wrong order will not lead to overwrite problem.

This solution will be easy to implement and efficient.

**Comment by laddcn** [comment]
I have fixed the order problem of NotifyListener.notify yet. I will fixed the order problem of saveProperties(save urls to cache) later.

**Comment by laddcn** [comment]
I add test case to display the scenario.And new codes works fine now. Help me review this PR when have time. @chickenlj

**Comment by chickenlj** [comment]
Sure, well done. I will check this issue soon.

**Comment by chickenlj** [comment]
The patch needs further verification, let's move it to the next release.

**Comment by laddcn** [comment]
@chickenlj Please help me review the above PR.
