### ISSUE TITLE
多注册中心模式下，采用广播和并行模式调用，consumer调用一次，同一个provide触发两次

### ISSUE THREAD

**Issue by klboke** [apache/dubbo#5965]
dubbo版本：2.7.4.1
多注册中心模式下，采用广播和并行模式调用，consumer调用一次，同一个provide触发两次。这个不算bug，但是是一个可以讨论的问题，相同的URL是否需要去重

**Comment by AlbumenJ** [comment]
在2.7.5版本之后引入的 ZoneAwareCluster，在 `ZoneAwareClusterInvoker` 中会根据策略选择一个注册中心去进行调用，然后广播或并行操作是对单个的注册中心中服务提供者去操作。

调用链如下：
ZoneAwareClusterInvoker(StaticDirectory) -> XXXXClusterInvoker(RegistryDirectory, routing happens here) -> Invoker

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
