### ISSUE TITLE
@Reference注解中cluster=“failfast"失效

### ISSUE THREAD

**Issue by zhouhaopeng** [apache/dubbo#5966]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. 配置cluster=“failfast”
`@Component("demoHelloWorldComponent")
public class DemoHelloWorldComponent implements HelloWorldService {

    @Reference(cluster = "failfast")
    private HelloWorldService helloWorldService;

    @Override
    public String sayHello() {
        return helloWorldService.sayHello();
    }
}`
2. 在源代码中发现，AbstractDirectory在构造过程中会调用removeParameter(REFER_KEY)，导致Cluster$Adaptive在join的时候无法找点key=cluster对的值，返回默认failover策略
`    public AbstractDirectory(URL url, RouterChain<T> routerChain) {
        if (url == null) {
            throw new IllegalArgumentException("url == null");
        }

        this.url = url.removeParameter(REFER_KEY).removeParameter(MONITOR_KEY);
        this.consumerUrl = url.addParameters(StringUtils.parseQueryString(url.getParameterAndDecoded(REFER_KEY)))
                .removeParameter(MONITOR_KEY);

        setRouterChain(routerChain);
    }`

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by wuwenhui0917** [comment]
代码应该是如下的吧：
if (url.getProtocol().equals(REGISTRY_PROTOCOL)) {
            Map<String, String> queryMap = StringUtils.parseQueryString(url.getParameterAndDecoded(REFER_KEY));
            this.url = url.addParameters(queryMap).removeParameter(MONITOR_KEY);
        } else {
            this.url = url;
        }
1.这个代码是在RegistryDirectory 起作用
2.这个是删除的monitor这个参数吧！！

**Comment by zhouhaopeng** [comment]
![image](https://user-images.githubusercontent.com/36914462/78353231-4a6af580-75dc-11ea-9956-7421ed61bf8f.png)
master我看的这2个参数都删了

**Comment by AlbumenJ** [comment]
- 这里删除的是refer和monitor参数，并没有看到删除你前面提到的cluster参数哦
- 另外，我刚刚在自己项目上指定cluster=“failfast"也是正常使用failfast策略的（Dubbo 版本 2.7.5）

**Comment by zhouhaopeng** [comment]
refer里面包含了cluster参数




在2020年04月03日 21:54，Albumen Kevin 写道：

这里删除的是refer和monitor参数，并没有看到删除你前面提到的cluster参数哦
另外，我刚刚在自己项目上指定cluster=“failfast"也是正常使用failfast策略的（Dubbo 版本 2.7.5）

**Comment by zhouhaopeng** [comment]
![image](https://user-images.githubusercontent.com/36914462/78368520-582d7480-75f6-11ea-9b32-c35affa9d6dc.png)
我的是master分支

**Comment by AlbumenJ** [comment]
这是我的 consumerUrl `consumer://169.254.181.69/xxx.UserLoginWebService?application=xxx&category=providers,configurators,routers&check=false&cluster=failfast&dubbo=2.0.2&init=false&interface=xxxxx.UserLoginWebService&methods=xxxxx&pid=93024&qos.enable=false&release=2.7.5&side=consumer&sticky=false&timestamp=1585922098761` 

这里的 `cluster` 参数并没有因为 refer 删除而不存在哦，另外自适应拓展的调用也是直接读 url 的参数的，对于 Cluster 拓展直接读取 ` cluster` 参数的

```
@SPI(FailoverCluster.NAME)
public interface Cluster {

    /**
     * Merge the directory invokers to a virtual invoker.
     *
     * @param <T>
     * @param directory
     * @return cluster invoker
     * @throws RpcException
     */
    @Adaptive
    <T> Invoker<T> join(Directory<T> directory) throws RpcException;
}
```
这里的 Adaptive 注解没带 value 是默认直接读 `refer` 的

**Comment by zhouhaopeng** [comment]
我用的是master分支，join方法用的是directory里面的url




在2020年04月03日 22:03，Albumen Kevin 写道：

这是我的 consumerUrl consumer://169.254.181.69/xxx.UserLoginWebService?application=xxx&category=providers,configurators,routers&check=false&cluster=failfast&dubbo=2.0.2&init=false&interface=xxxxx.UserLoginWebService&methods=xxxxx&pid=93024&qos.enable=false&release=2.7.5&side=consumer&sticky=false&timestamp=1585922098761

这里的 cluster 参数并没有因为 refer 删除而不存在哦，另外自适应拓展的调用也是直接读 url 的参数的，对于 Cluster 拓展直接读取 cluster 参数的

@SPI(FailoverCluster.NAME)

public interface Cluster {



    /**

     * Merge the directory invokers to a virtual invoker.

     *

     * @param <T>

     * @param directory

     * @return cluster invoker

     * @throws RpcException

     */

    @Adaptive

    <T> Invoker<T> join(Directory<T> directory) throws RpcException;

}



这里的 Adaptive 注解没带 value 是默认直接读 refer 的

**Comment by AlbumenJ** [comment]
在 `ReferenceConfig` 中有这段代码
```
    /**
     * The {@link Cluster}'s implementation with adaptive functionality, and actually it will get a {@link Cluster}'s
     * specific implementation who is wrapped with <b>MockClusterInvoker</b>
     */
    private static final Cluster CLUSTER = ExtensionLoader.getExtensionLoader(Cluster.class).getAdaptiveExtension();

    @SuppressWarnings({"unchecked", "rawtypes", "deprecation"})
    private T createProxy(Map<String, String> map) {

    ···

                if (registryURL != null) { // registry url is available
                    // for multi-subscription scenario, use 'zone-aware' policy by default
                    URL u = registryURL.addParameterIfAbsent(CLUSTER_KEY, ZoneAwareCluster.NAME);
                    // The invoker wrap relation would be like: ZoneAwareClusterInvoker(StaticDirectory) -> FailoverClusterInvoker(RegistryDirectory, routing happens here) -> Invoker
                    invoker = CLUSTER.join(new StaticDirectory(u, invokers));
                } else { // not a registry url, must be direct invoke.
                    invoker = CLUSTER.join(new StaticDirectory(invokers));
                }
            }
        }

    ···

    }
```

这里的 CLUSTER 是一个自适应拓展对象，当调用 join 方法时会去读取 join 参数中的以 URL 为返回类型的方法的值中的 cluster 的值判断具体实现类的拓展名的（位于 `StaticDirectory` 拓展的 `AbstractDirectory` 的 `getConsumerUrl` 方法）

**Comment by zhouhaopeng** [comment]
![image](https://user-images.githubusercontent.com/36914462/78371213-3b933b80-75fa-11ea-8b06-7edbdff113e1.png)
反编译后，是直接获取directory里面的url

**Comment by AlbumenJ** [comment]
这里没问题的，从 url 读取 `cluster` 参数，如果为空则返回默认值（第二个参数 defaultValue） `failover`

**Comment by zhouhaopeng** [comment]
现在我设置的cluster=fastover，然后仍然用的是failover

**Comment by AlbumenJ** [comment]
或许可以测试开启debug模式，在具体发送远程调用的方法上 step into，就会进入到 `InvokerInvocationHandler` 中，你可以看一下 `invoker`  对象的内容（我上面第一张截图）

**Comment by zhouhaopeng** [comment]
![image](https://user-images.githubusercontent.com/36914462/78374419-67b0bb80-75fe-11ea-807a-913d17f2d41a.png)
@AlbumenJ

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/78375395-56b47a00-75ff-11ea-99d4-833a55d31a92.png)
请问你是否配置了覆盖信息，另外麻烦看一下 consumerUrl 的值，在 dictionary 中

**Comment by zhouhaopeng** [comment]
源码下 dubbo-demo/dubbo-demo-annotation 工程,consumer是HelloWorldService
Albumen Kevin <notifications@github.com> 于2020年4月3日周五 下午11:05写道：

**Comment by zhouhaopeng** [comment]
大哥，帮我看下

hp zh <haopengzhou.coke@gmail.com> 于2020年4月3日周五 下午11:26写道：

**Comment by AlbumenJ** [comment]
根据源码下 dubbo-demo/dubbo-demo-annotation 工程可以复现你说的问题，结果代码跟踪后发现 `RegistryDirectory` 在最新的 master 分支上的获取 URL 的逻辑已被修改，根据 Git 日志发现这部分逻辑在 c29bb65 版本被修改，关联PR #5856

![image](https://user-images.githubusercontent.com/9292748/78385760-f6c5cf80-760e-11ea-91d2-cc9789f39971.png)

修改后的 `getUrl` 不再被重写，导致 cluster 获取拓展实现的时候获取到的 url 的参数并没有从 `refer` 字段中解析出来，解析代码在 `RegistryDirectory` 构造方法中

```
        this.queryMap = StringUtils.parseQueryString(url.getParameterAndDecoded(REFER_KEY));
        this.overrideDirectoryUrl = this.directoryUrl = turnRegistryUrlToConsumerUrl(url);
```

c29bb65 版本之前的 `getUrl` 被覆写为获取 `this.overrideDirectoryUrl` 就可以正常获取到 `refer` 字段解析后的 URL，但 c29bb65 版本更改之后只能从 `getConsumerUrl` 中获取到，而 `cluster` 的自适应拓展仍使用  `getUrl` 读取拓展名，导致自定义 `cluster` 失效。

@chickenlj 请问在 #5856 中是因为什么才将 `getUrl` 的重写改为 `getConsumerUrl` ，是有什么特殊用意吗

**Comment by zhouhaopeng** [comment]
这个是bug是吧

Albumen Kevin <notifications@github.com> 于2020年4月4日周六 上午1:29写道：

**Comment by jianpeng957** [comment]
这个问题会在2.7.6修复吗？现在还存在相关的问题

**Comment by newweapon** [comment]
2.7.7 还存在这个问题啊

**Comment by jinghe0929** [comment]
2.7.8版本仍然存在

**Comment by AlbumenJ** [comment]
@jinghe0929 
> 2.7.8版本仍然存在

测试了一下，2.7.8 中已经没有这个问题了，请问你可以提供相关的使用代码样例吗
