### ISSUE TITLE
消费多注册中心时，provider打上tag会报错

### ISSUE THREAD

**Issue by lkxiaolou** [apache/dubbo#5979]
### Environment

* Dubbo version: 2.6.7
* Java version: 8

### Steps to reproduce this issue

1. provider起两个，其中一个带上tag（-Ddubbo.provider.tag=xx），且往两个注册中心注册（不论类型，比如两个zk）
2. consmuer消费，也配置1中的两个注册中心，会报 com.alibaba.dubbo.rpc.RpcException: No provider available in []

原因是当消费两个注册中心的服务时，调用时使用availableCluster包装，检测注册中心的可用性
![image](https://user-images.githubusercontent.com/6935924/78656136-8d3d0e00-78f9-11ea-994f-d5f542ef461d.png)

同时该invoker会合并来自provider URL的一切参数，包括tag路由的tag参数
![image](https://user-images.githubusercontent.com/6935924/78656325-cd03f580-78f9-11ea-9a1b-fc8995f5358f.png)

发起调用时通过availableCluster检测注册中心的可用性，也当成一个正常的invoker来执行，也会经过路由处理，如果请求不带tag，那么两个注册中心都不符合路由规则，从而抛出异常

![image](https://user-images.githubusercontent.com/6935924/78656489-0d637380-78fa-11ea-8bf0-5db3d94f875e.png)

不知道这是否算一个bug？
如果是的话可以在创建StaticDirectory时重新setRouters方法，指定此处不使用路由
![image](https://user-images.githubusercontent.com/6935924/78656650-4a2f6a80-78fa-11ea-9cc3-d794f8cfb359.png)

**Comment by AlbumenJ** [comment]
在 2.7.5 版本以后已使用 `ZoneAwareCluster` 代替 `AvailableCluster` ，对于多注册中心的处理逻辑做了优化，你可以尝试把 Dubbo 版本升级到 2.7.5 以后，不过要注意 2.7.x 升级带来的包名的相关问题

**Comment by lkxiaolou** [comment]
> 在 2.7.5 版本以后已使用 `ZoneAwareCluster` 代替 `AvailableCluster` ，对于多注册中心的处理逻辑做了优化，你可以尝试把 Dubbo 版本升级到 2.7.5 以后，不过要注意 2.7.x 升级带来的包名的相关问题

恩，我测试了2.7.5版本是可以的，谢谢

**Comment by qixiaobo** [comment]
So sad to use 2.6.X
