### ISSUE TITLE
protocol attribute 'default' is not working

### ISSUE THREAD

**Issue by jscene** [apache/dubbo#5982]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: windows10
* Java version: 1.8

### Steps to reproduce this issue

1. application.properties 

```
dubbo.protocols.dubbo.port=-1
dubbo.protocols.dubbo.name=dubbo
dubbo.protocols.dubbo.default=true

dubbo.protocols.rest.port=-1
dubbo.protocols.rest.name=rest
dubbo.protocols.rest.contextpath=upmRestServices
dubbo.protocols.rest.default=false
```
2. interfaces
```
public interface UserBusinessService extends Serializable {
 // methods
}
```
```
@Path("noGeneratorRestService")
@Consumes({"application/json", "text/xml"})
@Produces({"application/json; charset=UTF-8", "text/xml; charset=UTF-8"})
public interface NOGeneratorRestService {
//methods
}
```
3. implements
```
@Service
public class UserBusinessServiceImpl implements UserBusinessService {
//methods
}
```
```
@Service(protocol = "rest")
public class NOGeneratorRestServiceImpl implements NOGeneratorRestService {
//methods
}
```
4. exception result
```
java.lang.RuntimeException: RESTEASY003130: Class is not a root resource.  It, or one of its interfaces must be annotated with @Path: xxx.UserBusinessService implements:  java.io.Serializable
```
5. ConfigManager.isDefaultConfig is not working
![1586330358(1)](https://user-images.githubusercontent.com/13428489/78758056-1747ae00-79b0-11ea-9f68-b8b282e95b51.png)

My Application has two protocols, one is the default dubbo procotol, and the other is rest. And I wish the rest working when I declearing at the @Service，otherwise use the dubbo procotol. But now the dubbo.protocols.rest.default=false is not working.
应用里面有两个协议，一个是默认的dubbo协议，一个是rest协议，我希望就是注解里面有显示声明rest就用rest协议，不然就默认用dubbo协议，现在的问题就是default属性没有生效，导致不声明的接口都会同时暴露两种协议，请问是哪里配置不对吗？

**Comment by Huangxuny1** [comment]
@jscene  in latest dubbo version , it's fixed 

![image](https://user-images.githubusercontent.com/21981606/78802117-028b0a80-79f0-11ea-9764-163f554f9f25.png)

it's becase of `org.apache.dubbo.common.utils.ReflectUtils#getProperty(Object bean, String methodName)`

it's has fix in #5947

update your dubbo version will be ok
