### ISSUE TITLE
2.7.5 telnet command lose

### ISSUE THREAD

**Issue by envyer** [apache/dubbo#5986]
part telnet command lose in 2.7.5 version，cause by package error
![image](https://user-images.githubusercontent.com/11310064/78859787-0146f580-7a63-11ea-9394-3a1c0e273798.png)

**Comment by envyer** [comment]
for example ListTelnetHandler：
actual package is **org.apache.dubbo.qos.legacy.ListTelnetHandler**
not **org.apache.dubbo.rpc.protocol.dubbo.telnet.ListTelnetHandler**

**Comment by envyer** [comment]
please fix **META-INF/dubbo.internal/org.apache.dubbo.remoting.telnet.TelnetHandler**

**Comment by AlbumenJ** [comment]
In #5815 , this issue had been solved.

**Comment by unixxiaobin** [comment]
i config spring-boot project use
dubbo.application.qosEnable=true
dubbo.application.qosPort=33333
dubbo.application.qosAcceptForeignIp=false

but not effect

**Comment by AlbumenJ** [comment]
> I config spring-boot project use
> 
> dubbo.application.qosEnable=true
> dubbo.application.qosPort=33333
> dubbo.application.qosAcceptForeignIp=false
> 
> but telnet command not effect why ??
> 
> ![image](https://user-images.githubusercontent.com/23090397/78976895-bc49be80-7b49-11ea-9f1d-8b506bcb0c0f.png)

In my project, I configure qos with the following configuration and it run correctly.

```
dubbo.application.qos-enable=true
dubbo.application.qos-port=33333
dubbo.application.qos-accept-foreign-ip=false
```

**Comment by unixxiaobin** [comment]
I try use 

dubbo.application.qos-enable=true
dubbo.application.qos-port=33333

dubbo.application.qos-accept-foreign-ip=false




The Server can start up but the port 33333 not LISTENING










At 2020-04-10 16:57:27, "Albumen Kevin" <notifications@github.com> wrote:

I config spring-boot project use

dubbo.application.qosEnable=true
dubbo.application.qosPort=33333
dubbo.application.qosAcceptForeignIp=false

but telnet command not effect why ??

In my project, I configure qos with the following configuration and it run correctly.

dubbo.application.qos-enable=true
dubbo.application.qos-port=33333
dubbo.application.qos-accept-foreign-ip=false

**Comment by unixxiaobin** [comment]
#5690 has resolve this problem . I try success—
