### ISSUE TITLE
What is the advantage of this lock?

### ISSUE THREAD

**Issue by qiaolin-li** [apache/dubbo#5987]
https://github.com/apache/dubbo/blob/317e62f73fd0a9bac4b34eb8b2c31bbae591ef91/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DubboProtocol.java#L458-L494

Why not use the key to lock

```java
synchronized (key.intern()) {
 // ...... content
}
```

**Comment by qiaolin-li** [comment]
see, maybe he doesn't want to affect multiple locks because of the key string

**Comment by tangcent** [comment]
Have a look at the situation like this: 
When thread A finishes executing `locks.putIfAbsent(key, new Object())`, 
another thread B which holding the lock executes `locks.remove(key)`,
and then thread A executes `synchronized (locks.get(key))`.

**Comment by qiaolin-li** [comment]
![image](https://user-images.githubusercontent.com/32925394/79084834-9cdcac80-7d68-11ea-80b1-654612a4ead9.png)

You raise a good question, when you say this, he will have a null pointer exception.
你提出了一个好问题，当出现你说的这种情况下，他就会出现空指针异常。
