### ISSUE TITLE
consumer timeout value is not provider config

### ISSUE THREAD

**Issue by linuke** [apache/dubbo#6005]
### Environment

* Dubbo version: 2.7.x
* Operating System version: all
* Java version: 1.8

### Steps to reproduce this issue

1. provider config  dubbo.provider.timeout=2000
2. consumer timeout value is DEFAULT_TIMEOUT（1000）

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
2000
What do you expected from the above steps？

### Actual Result
1000

**Comment by linuke** [comment]
the consumer url is
dubbo://10.200.182.168:18089/xxxxx?anyhost=true&application=xx&bean.name=ServiceBean:com.demo.xx&xxxxe&default.timeout=2000&xxxxx

int timeout = getUrl().getMethodPositiveParameter(methodName, TIMEOUT_KEY, DEFAULT_TIMEOUT);

**Comment by KindHunter** [comment]
I think your problem is not a really problem, because this strategy is designed on purpose!

http://dubbo.apache.org/en-us/docs/user/recommend.html


![image](https://user-images.githubusercontent.com/25549282/79104610-830b8b80-7da1-11ea-9a4a-841cc32a1a0c.png)

**Comment by linuke** [comment]
If a attribute is configurated in provider side, not configurated in consumer side, consumer service will use the attribute in provider side. 
But now the provider configuration is not used.

**Comment by linuke** [comment]
https://github.com/apache/dubbo/issues/5948
