### ISSUE TITLE
the article in the blog of dubbo is loss

### ISSUE THREAD

**Issue by a51764579** [apache/dubbo#6009]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. the url of the article is "http://dubbo.apache.org/zh-cn/blog/grpc-http2-protobuf.html"

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
It's an issue of Dubbo-website , please trace apache/dubbo-website#581

**Comment by htynkn** [comment]
where do you get this link?
I find something similar: http://dubbo.apache.org/zh-cn/blog/Dubbo-supporting-gRPC-HTTP2-and-protobuf.html

**Comment by AlbumenJ** [comment]
> where do you get this link?
> I find something similar: http://dubbo.apache.org/zh-cn/blog/Dubbo-supporting-gRPC-HTTP2-and-protobuf.html

In the below of "http://dubbo.apache.org/zh-cn/docs/user/new-features-in-a-glance.html".

**Comment by a51764579** [comment]
> > where do you get this link?
> > I find something similar: http://dubbo.apache.org/zh-cn/blog/Dubbo-supporting-gRPC-HTTP2-and-protobuf.html
> 
> http://dubbo.apache.org/zh-cn/blog/index.html
> ![image](https://user-images.githubusercontent.com/9292748/79182616-cf0e0d00-7e41-11ea-882a-57d4b82b4d01.png)

First , open then url "http://dubbo.apache.org/zh-cn/blog/index.html" in browser,second,click the last article in the article list of the page.


> > where do you get this link?
> > I find something similar: http://dubbo.apache.org/zh-cn/blog/Dubbo-supporting-gRPC-HTTP2-and-protobuf.html
> 
> http://dubbo.apache.org/zh-cn/blog/index.html
> ![image](https://user-images.githubusercontent.com/9292748/79182616-cf0e0d00-7e41-11ea-882a-57d4b82b4d01.png)

First,open the url "http://dubbo.apache.org/zh-cn/blog/index.html" in browser,second,click the last article in the article list of the page.

**Comment by htynkn** [comment]
this link has been fixed via https://github.com/apache/dubbo-website/commit/d2c013f23ca455a8aeaed4d0aa0aba970cca0f80
Thanks very much for your feedback
