### ISSUE TITLE
NacosMetadataReport缺失username和password参数解析

### ISSUE THREAD

**Issue by cai-ti** [apache/dubbo#6010]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: win10
* Java version: java8

### Steps to reproduce this issue

NacosMetadataReport缺失username和password参数解析，导致nacos开启权限认证的情况下，dubbo元数据无法发送到nacos

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by laddcn** [comment]
It seems similar to https://github.com/apache/dubbo/issues/5956, I will try to resolve this problem tomorrow.

**Comment by cai-ti** [comment]
> It seems similar to #5956, I will try to resolve this problem tomorrow.

I currently add it to NacosMetadataReport through SPI and it can be used normally，But there may be loss of other parameters that I did not find, maybe refer to nacos to confirm that the completion will be better

**Comment by brotherlu-xcq** [comment]
I want continue the left work, please assign it to me.

**Comment by CrazyHZM** [comment]
> I want to continue the left work, please assign it to me.

Go a head！

**Comment by brotherlu-xcq** [comment]
I tried with master branch, but can not reproduce the problem. below is my registry config. Nacos enabled auth.
![image](https://user-images.githubusercontent.com/25661357/135223114-e2aa77ca-a0ec-42ad-acf7-67318d957206.png)

**Comment by CrazyHZM** [comment]
> I tried with master branch, but can not reproduce the problem. below is my registry config. Nacos enabled auth. ![image](https://user-images.githubusercontent.com/25661357/135223114-e2aa77ca-a0ec-42ad-acf7-67318d957206.png)

Then this problem should be fixed in a certain version, I will close the issues first.
