### ISSUE TITLE
nacos1.2.1 +dubbo 2.7.6.1-SNAPSHOT

### ISSUE THREAD

**Issue by liuyanghui** [apache/dubbo#6013]
nacos1.2.1 +dubbo 2.7.6.1-SNAPSHOT（因为修改了dubbo 不支持nacos 认证问题，所有新修改了一个版本）
providers 可以正常启动并在 nacos可以查看到服务正常运行
但是启动consumer 或者启动完成一段时间后再次调用接口 报错：Injection of @Reference dependencies is failed; 
跟踪源码发现：org.apache.dubbo.registry.integration.RegistryDirectory#refreshInvoker             this.forbidden = true; 导致该问题，并发现地址为： empty://
但是没有发现解决方案，为什么导致调用refreshInvoker 方法

**Comment by AlbumenJ** [comment]
This problem has been sloved by #5902 . And it would be fix in 2.7.7 version or you can checkout the newest version of master branch and install it in your computer.

The empty protocol is used to fix #5442. But it cause some problems in #5885.
