### ISSUE TITLE
[Discussion] Travis always failed

### ISSUE THREAD

**Issue by tangcent** [apache/dubbo#6019]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Travis

### Steps to reproduce this issue

1.  Create a PR.
2. See the build of travis.
see https://travis-ci.org/github/apache/dubbo/jobs/674706306

### Expected Result

Passed.

### Actual Result

Failed:
```
[ERROR] testContainer  Time elapsed: 0.127 s  <<< ERROR!
java.lang.IllegalStateException: Recursive update
	at org.apache.dubbo.container.log4j.Log4jContainerTest.testContainer(Log4jContainerTest.java:31)
```

Travis always failed.
But sometimes it will passed after force-pushed without any change.

Compare:
https://travis-ci.org/github/apache/dubbo/jobs/674706306
https://travis-ci.org/github/apache/dubbo/builds/674993938

**Comment by chickenlj** [comment]
https://bugs.openjdk.java.net/browse/JDK-8062841

**Comment by chickenlj** [comment]
It looks more like a JDK related restriction or drawback.

**Comment by tangcent** [comment]
I get it.
