### ISSUE TITLE
如何指定ip调用提供者

### ISSUE THREAD

**Issue by hweeeeeei** [apache/dubbo#6025]
不要使用注解的方法调用，  因为ip需要根据业务进行动态指定

**Comment by AlbumenJ** [comment]
动态指定推荐选择使用注册中心，点对点直连只建议用于测试环境下

**Comment by wavesZh** [comment]
@hweeeeeei 也许可以考虑自定义 LoadBalance 实现

**Comment by hweeeeeei** [comment]
我最后的采用的方法如下:
WebAilloPushService是一个接口。
`
@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes = TilloTestApplication.class)
public class DubboToIpTest {


    @Value("${spring.dubbo.appname}")
    private String appname;

    //服务提供者port
    static final String remoteDubboPort = ":20803";
    // ReferenceConfig缓存
    private static Map<String, ReferenceConfig<WebAilloPushService>> referenceCache = new ConcurrentHashMap<>();

    String reip = "127.0.0.1";

    @Value("${spring.dubbo.group}")
    private String group;
    @Value("${spring.dubbo.version}")
    private String version;
    @Value("${spring.dubbo.timeout}")
    private Integer timeout;

    public WebAilloPushService getWebAilloPushService(String ip) {

        ReferenceConfig<WebAilloPushService> webAilloPushServiceReferenceConfig = referenceCache.get(ip);
        if (null == webAilloPushServiceReferenceConfig) {

            ReferenceConfig<WebAilloPushService> referenceConfig = new ReferenceConfig<>();
            referenceConfig.setApplication(new ApplicationConfig(appname));
            referenceConfig.setInterface(WebAilloPushService.class);
            referenceConfig.setGroup(group);
            referenceConfig.setGeneric(false);
            referenceConfig.setVersion(version);
            referenceConfig.setTimeout(timeout);
            referenceConfig.setAsync(false);
            String url = ip + remoteDubboPort;
            referenceConfig.setUrl(url);
            referenceCache.put(ip, referenceConfig);

            return referenceConfig.get();
        }
        return webAilloPushServiceReferenceConfig.get();

    }


}
`

**Comment by chickenlj** [comment]
没太理解你这里描述的需求，这里有一个指定 ip 调用的一个文档，看是否满足需求：http://dubbo.apache.org/zh-cn/docs/user/demos/explicit-target.html

**Comment by Hulk904** [comment]
> 没太理解你这里描述的需求，这里有一个指定 ip 调用的一个文档，看是否满足需求：http://dubbo.apache.org/zh-cn/docs/user/demos/explicit-target.html
比如有A，B，C三个provider，客户端有的需要指定调用A机器提供的服务，有的需要调用C机器提供的服务。

**Comment by kgdngitfk** [comment]
http://dubbo.apache.org/zh-cn/docs/user/demos/explicit-target.html页面已经404了，我也想问这个问题，配置的Cluster不生效

**Comment by AlbumenJ** [comment]
@kgdngitfk 目前最新地址是这个 https://dubbo.apache.org/zh/docs/v2.7/user/examples/explicit-target/

**Comment by realoldroot** [comment]
2.7.12以后可以指定Ip Port调用Provider https://dubbo.apache.org/zh/docs/v2.7/user/examples/invoke-with-specified-ip/

**Comment by kgdngitfk** [comment]
我按照负载均衡自定义了LoadBalance，配置了
<dubbo:reference  interface="xxx.xxx.autocharge.service.AutoChargeService" loadbalance="demo"/>
注入bean
 @Reference
  AutoChargeService autoChargeService;
再调用autoChargeService的方法时发现自定义扩展的loadbalance还是没有生效通过debug发现
在org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker#initLoadBalance方法中
这一段调用
ExtensionLoader.getExtensionLoader(LoadBalance.class).getExtension(invokers.get(0).getUrl()
                    .getMethodParameter(RpcUtils.getMethodName(invocation), LOADBALANCE_KEY, DEFAULT_LOADBALANCE));
通过getMethodParameter获取到的loadbalance的值是空的所以使用了默认的RandomLoadBalance，于是我强制修改变量，将
getExtension（）的参数修改为自定义的loadbalance的名称，结果生效了
,所以我初步定位是在注册时没有把loadbalance的值放进去URL.parameters里面导致的，使用的dubbo版本是2.7.3的
这个loadbalance是需要consumer和provider两边都要配置才行吗？

**Comment by xykjlcx** [comment]
> 2.7.12以后可以指定Ip Port调用Provider https://dubbo.apache.org/zh/docs/v2.7/user/examples/invoke-with-specified-ip/

这个似乎不生效了
