### ISSUE TITLE
[Enhancement] Refactoring the parser of dubbo config BeanDefinitions in XML configuration

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo#6039]
The `org.apache.dubbo.config.spring.schema.DubboBeanDefinitionParser` is too complicated to maintain, which is used to parse  13 BeanDefinitions of Dubbo config, thus, it'd better be refactored by the small modules for every Dubbo config.

- Adding attributes
   - `id` attribute for `<dubbo:config-center />` , `<dubbo:monitor />` and `<dubbo:metadata-report />`

- Deprecated attributes
    - `<protocol keepalive="true" />` to be replaced by `<protocol keep-alive="true" />`

- Removing attributes
   - `forks` attribute of `<dubbo:registry />`

**Comment by CodeIngL** [comment]
我认为重构他不是一个好主意，这是一个稳定的代遗弃的的模块。唯一的瑕疵只是众多普通bean中，refenceBean的beanDefinition存在提前暴露的问题，修复也非常的简单

**Comment by mercyblitz** [comment]
> 我认为重构他不是一个好主意，这是一个稳定的代遗弃的的模块。唯一的瑕疵只是众多普通bean中，refenceBean的beanDefinition存在提前暴露的问题，修复也非常的简单

Thanks for your advice, a new Java System Property `dubbo.experimental.bean-definition-parser` will be introduced into Dubbo 2.7.7 to swtich it on or not.

**Comment by liaow** [comment]
@mercyblitz After upgrading dubbo to 2.7.7, this problem is not fixed, is it because the code has not been merged into the main branch?

also see [dubbo-spring-boot-project #695](https://github.com/apache/dubbo-spring-boot-project/issues/695)

**Comment by Da-Hong** [comment]
> 我认为重构他不是一个好主意，这是一个稳定的代遗弃的的模块。唯一的瑕疵只是众多普通bean中，refenceBean的beanDefinition存在提前暴露的问题，修复也非常的简单

请问怎么修复呢？小马哥的补丁并没有打到2.7.7里，目测2.7.8也没有。

**Comment by Da-Hong** [comment]
在2.7.7源码包里更新了小马哥的补丁试了还是不行，目前[这个方案](https://github.com/apache/dubbo/pull/5710)有效果，但不知道有没有其他副作用 #5710

**Comment by CodeIngL** [comment]
肯定有副作用呀，RefernceBean本质上就是FactoryBean，你给他设定tagertType，逻辑上就不是FactoryBean。完全破坏了spring的结构，现在看解决方法是加lazy。是为了解决而解决么。从根源上就错了

**Comment by Da-Hong** [comment]
> 肯定有副作用呀，RefernceBean本质上就是FactoryBean，你给他设定tagertType，逻辑上就不是FactoryBean。完全破坏了spring的结构，现在看解决方法是加lazy。是为了解决而解决么。从根源上就错了

方便讲下解决方案吗？

**Comment by CodeIngL** [comment]
![image](https://user-images.githubusercontent.com/12370508/86867935-4cc27b80-c106-11ea-9ce7-416882bc0a3e.png)
在这里应该使用decoratedDefinition来进行暴露问题，如果你快速定制dubbo，你可以参考https://github.com/open-wrapper/dubbo-wrapper

**Comment by CodeIngL** [comment]
这bug超级久了，就是 不修，我也是醉了。 不是有专门spring生态的团队么

**Comment by Da-Hong** [comment]
> ![image](https://user-images.githubusercontent.com/12370508/86867935-4cc27b80-c106-11ea-9ce7-416882bc0a3e.png)
> 在这里应该使用decoratedDefinition来进行暴露问题，如果你快速定制dubbo，你可以参考https://github.com/open-wrapper/dubbo-wrapper

这样改还是不行，DubboBootstrap->start->initialize->checkGlobalConfigs->validateApplicationConfig报错，原因是valid时new ApplicationConfig之后refresh的时候取name值（取值有个顺序，但是都没取到）是null，但是项目中是在consumer.xml中${}方式从yml文件中取值的，也就是说这个时候还没有加载到这些。有点懵了。。。求教！

**Comment by Da-Hong** [comment]
#5976 差不多事同一个问题

**Comment by furaul** [comment]
> ![image](https://user-images.githubusercontent.com/12370508/86867935-4cc27b80-c106-11ea-9ce7-416882bc0a3e.png)
> 在这里应该使用decoratedDefinition来进行暴露问题，如果你快速定制dubbo，你可以参考https://github.com/open-wrapper/dubbo-wrapper

你好，我试了下这个方法是可以使用的，可以解决我的问题。
看下下DecoratedDefinition的相关源码，对这个不太理解，有没有详细的文章或者博客介绍

**Comment by CodeIngL** [comment]
这个是spring的东西，可以参考相关api






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "furaul"<notifications@github.com&gt;; 
发送时间: 2020年12月1日(星期二) 下午5:45
收件人: "apache/dubbo"<dubbo@noreply.github.com&gt;; 
抄送: "codeL"<576579140@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/dubbo] [Enhancement] Refactoring the parser of dubbo config BeanDefinitions in XML configuration (#6039)





  

 在这里应该使用decoratedDefinition来进行暴露问题，如果你快速定制dubbo，你可以参考https://github.com/open-wrapper/dubbo-wrapper
  
你好，我试了下这个方法是可以使用的，可以解决我的问题。
 看下下DecoratedDefinition的相关源码，对这个不太理解，有没有详细的文章或者博客介绍
