### ISSUE TITLE
添加请求和响应的大小限制

### ISSUE THREAD

**Issue by conan425** [apache/dubbo#6048]
背景：我们是网关应用，如果provider返回的响应数据过大，会导致系统内存短时间被打爆
我们希望可以增加配置参数，来设置provider返回数据的大小上限，比如设置上限为10M，那么作为Consumer，可以接受把10M的数据读入到内存然后快速失败就可以了。
需求的上下文和 @陆龟 同学详细对过

**Comment by IndiraFinish** [comment]
```
AbstractCodec
protected static void checkPayload(Channel channel, long size) throws IOException {
        int payload = Constants.DEFAULT_PAYLOAD;
        if (channel != null && channel.getUrl() != null) {
            payload = channel.getUrl().getParameter(Constants.PAYLOAD_KEY, Constants.DEFAULT_PAYLOAD);
        }
        if (payload > 0 && size > payload) {
            ExceedPayloadLimitException e = new ExceedPayloadLimitException(
                "Data length too large: " + size + ", max payload: " + payload + ", channel: " + channel);
            logger.error(e);
            throw e;
        }
    }
```
在Netty解码的时候，会检查body大小，默认是8M。这个可以通过URL配置

**Comment by wuwu955** [comment]
> ```
> AbstractCodec
> protected static void checkPayload(Channel channel, long size) throws IOException {
>         int payload = Constants.DEFAULT_PAYLOAD;
>         if (channel != null && channel.getUrl() != null) {
>             payload = channel.getUrl().getParameter(Constants.PAYLOAD_KEY, Constants.DEFAULT_PAYLOAD);
>         }
>         if (payload > 0 && size > payload) {
>             ExceedPayloadLimitException e = new ExceedPayloadLimitException(
>                 "Data length too large: " + size + ", max payload: " + payload + ", channel: " + channel);
>             logger.error(e);
>             throw e;
>         }
>     }
> ```
> 
> 在Netty解码的时候，会检查body大小，默认是8M。这个可以通过URL配置

 你好 ，我看文档 是要在ProviderConfig和ProtocolConfig 中配置payload 的值 但是这个是配置的是所有接口的数据包大小限制了。针对上述的 单个接口限制 你说的是通过URL配置 请问怎么配呢？

**Comment by Jervis-Miao** [comment]
现在能支持按接口或者方法配置payload了吗

**Comment by CrazyHZM** [comment]
Payload本身不应该在接口或者方法上去配置，它是属于协议的抽象属性。
