### ISSUE TITLE
不兼容nacos 1.2.X （incompatible with nacos 1.2.X )

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#6053]
## Issue Description
*bug report* 
dubbo-registry-nacos is still incompatible with nacos 1.2.X

* dubbo-registry-nacos version:  2.7.6
* Operating System version: CentOS
* Java version: 1.8

### Steps to reproduce this issue
Upgrade nacos to 1.2.1

### Expected Result
well done

### Actual Result
calling dubbo server often fails, downgrade to 2.7.5 and every thing seemed to be OK.

**Comment by AlbumenJ** [comment]
Just now I try dubbo-registry-nacos which version is 2.7.6 with nacos 1.2.1, and it runs properly. Could you please provide a demo to reproduce this issue?

**Comment by zrlw** [comment]
https://github.com/apache/dubbo/blob/master/dubbo-dependencies-bom/pom.xml:
 <nacos_version>1.1.1</nacos_version>

**Comment by mercyblitz** [comment]
Try this one https://github.com/apache/dubbo/issues/5956

It will be fixed in the next release.

**Comment by zrlw** [comment]
thanks a lot!

**Comment by zrlw** [comment]
the 'nacos_version' should be upgraded to 1.2.1, but i don't see any change at master branch by now.
