### ISSUE TITLE
升级到2.7.6，如果Service和Reference没有使用group，将无法注入报错：Injection of @Reference dependencies is failed;

### ISSUE THREAD

**Issue by BigXin0109** [apache/dubbo#6077]
测试工程：
https://github.com/apache/dubbo-samples/tree/master/java/dubbo-samples-nacos/dubbo-samples-nacos-registry
将dubbo依赖改成2.7.6。（原有依赖是2.7.5，可以正常使用。）

具体原因如下：
nacos中服务列表内：
providers:org.apache.dubbo.samples.api.GreetingService:1.0.0:
由于 org.apache.dubbo.registry.nacos.NacosRegistry#getServiceNames0中在2.7.6多加了一行代码
` // Add the legacy service name since 2.7.6
serviceNames.add(getLegacySubscribedServiceName(url));`，
这边需要两个服务：
providers:org.apache.dubbo.samples.api.GreetingService:1.0.0:
providers:org.apache.dubbo.samples.api.GreetingService:1.0.0
注意：下面那个服务是没有最后面那个冒号的。
但是nacos中没有这个服务，这会导致下面那个服务找不到实例。

如果Service和Reference添加group，例如：
@Service(version = "1.0.0",group = "dubbo")
@Reference(version = "1.0.0",group = "dubbo")
nacos中服务列表内：
providers:org.apache.dubbo.samples.api.GreetingService:1.0.0:dubbo
此时NacosRegistry#getServiceNames0只返回一个服务名称，无冲突。

**Comment by BigXin0109** [comment]
后面看最新源码，发现已处理，不好意思
https://github.com/apache/dubbo/issues/5885

**Comment by mathcoder23** [comment]
非常感谢,这个问题困扰我4个小时,也怪我不看源码
临时增加了group来解决.

**Comment by gatspy** [comment]
duboo:2.7.6, nacos: 1.2.1还是有这个问题. 也是加group临时解决.

**Comment by BigXin0109** [comment]
> Duboo：2.7.6，NACOS：1.2.1还是有这个问题。也是加组临时解决。

现在的master分支里面最新源码上已经修复这个问题了，之前大神们已经发现了这个问题（问题#5885）你可以去看一下。

**Comment by BigXin0109** [comment]
> 非常感谢,这个问题困扰我4个小时,也怪我不看源码
> 临时增加了group来解决.

我也是被困扰了挺久的，一直以为是自己写的有问题，最后发现测试用例也会，就去跟源码了。
