### ISSUE TITLE
Dynamic config center usage is confusing

### ISSUE THREAD

**Issue by slankka** [apache/dubbo#6084]
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [√] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5 and 2.7.6
* Operating System version: windows 10
* Java version: 1.8.0_151

### Steps to reproduce this issue

1. `apollo.bootstrap.enabled=true` and make sure 'dubbo' is removed from `apollo.bootstrap.namespaces`  (I know dubbo has ability to load from Apollo's namespace 'dubbo' by default)
2. Define a bean `ConfigCenterConfig` (It will fail with 'No registry config found or it's not a valid config'). We ignore it now, so define a  `ConfigCenterBean` which is a real Spring style bean. And `configManager` in `DubboBootstrap` will find it. 

```
@Configuration
public class DubboConfig {
  @Bean
  public ConfigCenterBean configCenter() {
    ConfigCenterBean configCenterBean = new ConfigCenterBean();
    configCenterBean.setAddress("apollo.yourcompany.com");
    configCenterBean.setProtocol("apollo");
    configCenterBean.setNamespace("dubbo");
//    configCenterBean.setIncludeSpringEnv(true);
    configCenterBean .setGroup(null); // I don't want appConfigContent(DubboBootstrap.java:821)
    return configCenterBean ;
  }
}
```

3. Start application

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
I don't think DubboBootstrap should load from ConfigCenter using Application name.
`appConfigContent = dynamicConfiguration.getProperties ... ` should not be executed. 

### Actual Result
The `DubboBootstrap` just force to load from ConfigCenter, it doesn't allow property set by 
configCenterConfig, even `dubbo.application.name` is set in Apollo's dubbo namespace. 
```
String appGroup = getApplication().getName();
```

What actually happens?

If there is an exception, please attach the exception trace:

*Realtime-Compute-Server is spring.application.name*
```
WARN 17952 --- [           main] c.c.f.a.i.RemoteConfigRepository         : Load config failed, will retry in 1 SECONDS. appId: realtime-compute, cluster: default, namespaces: Realtime-Compute-Server.properties
```

soon later: 
```
java.lang.UnsupportedOperationException: No support
	at org.apache.dubbo.common.config.configcenter.DynamicConfiguration.publishConfig(DynamicConfiguration.java:155)
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.publishConfig(CompositeDynamicConfiguration.java:72)
	at org.apache.dubbo.metadata.DynamicConfigurationServiceNameMapping.lambda$map$0(DynamicConfigurationServiceNameMapping.java:59)
	at org.apache.dubbo.metadata.DynamicConfigurationServiceNameMapping.execute(DynamicConfigurationServiceNameMapping.java:92)
	at org.apache.dubbo.metadata.DynamicConfigurationServiceNameMapping.map(DynamicConfigurationServiceNameMapping.java:58)
```
***
SPLIT LINE
***
Here is my thought:
1. DubboBootstrap should using group defined in ConfigCenterBean or `configContent` from configFile to load some app individual config.
2. If my first way of using configCenter config is correct, why UnsupportedOperationException is thrown.
3. If some of maintainers approve my idea, I'm pleased to submit a PR.

**Comment by mercyblitz** [comment]
This issue will be resolved since 2.7.7,  `DynamicConfiguration#publishConfig` method will not throw an exception if not being implemented.
