### ISSUE TITLE
compatible problem with generic service

### ISSUE THREAD

**Issue by wikiwikiwiki** [apache/dubbo#6123]
### Environment

* Dubbo version: 2.7.6
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

when use generic service, lower version code (like 2.6.x) use generic service build with ReferenceConfig will receive a ClassCastException after update to 2.7.x.

从2.6.x升级到2.7.x时，低版本使用ReferencConfig初始化进行泛化调用的代码，会在获取实例时收到一个ClassCastException.

**Comment by AlbumenJ** [comment]
close #6123 via #6124
