### ISSUE TITLE
Dubbo2.7.3使用Redis作为注册中心时，配置元数据中心不支持手动指定哪个库

### ISSUE THREAD

**Issue by DongDongLi20** [apache/dubbo#6132]
Dubbo2.7.3使用Redis作为注册中心时，配置元数据中心不支持手动指定哪个库。
目前我自己的办法是把解析元数据配置的类拿出来重写，这个以后在以后的版本改进下

再提个小建议，Dubbo-Admin希望支持不同的注册中心

**Comment by DIscord010** [comment]
Fixed by #4476.
