### ISSUE TITLE
com/alibaba/nacos/client/naming/utils/StringUtils

### ISSUE THREAD

**Issue by danglibin** [apache/dubbo#6145]
<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>1.2.1</version>
		</dependency>

<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>dubbo</artifactId>
			<version>2.6.5</version>
		</dependency>

出现Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/client/naming/utils/StringUtils
依赖问题，nacos1.0.0版本的不会出现，1以上的版本就有这问题，是dubbo的依赖问题

**Comment by mercyblitz** [comment]
Please upgrade Duboo 2.6.8, this issue had been fixed.

**Comment by suruns** [comment]
帮忙看下呢，还是不得行啊
![image](https://user-images.githubusercontent.com/12554451/89367415-84274680-d70b-11ea-9cbe-30e428439ce5.png)

**Comment by suruns** [comment]
<properties>
        <java.version>1.8</java.version>
        <spring-boot.version>1.4.0.RELEASE</spring-boot.version>
        <spring.version>4.3.25.RELEASE</spring.version>
        <dubbo.version>2.6.8</dubbo.version>
        <dubbo.spring-boot.version>0.1.2.RELEASE</dubbo.spring-boot.version>
        <nacos.version>1.3.1</nacos.version>
    </properties>

**Comment by suruns** [comment]
` <properties>
        <java.version>1.8</java.version>
        <spring-boot.version>1.4.0.RELEASE</spring-boot.version>
        <spring.version>4.3.25.RELEASE</spring.version>
        <dubbo.version>2.6.8</dubbo.version>
        <dubbo.spring-boot.version>0.1.2.RELEASE</dubbo.spring-boot.version>
        <nacos.version>1.3.1</nacos.version>
    </properties>`
