### ISSUE TITLE
dubbo 2.7.6使用dubbo-registry-nacos注册服务，服务名不正常

### ISSUE THREAD

**Issue by yinjunonly** [apache/dubbo#6161]
[参考nacos区该问题](https://github.com/alibaba/nacos/issues/2787)

### Environment

* Dubbo version: 2.7.6
* Operating System version: win10
* Java version: java8

**Comment by IvanKimCN** [comment]
请问下 是只有服务名异常吗？  我在用的时候是服务可以注册上去，但是调用的时候就报no provider

**Comment by mercyblitz** [comment]
Please try this way : https://github.com/apache/dubbo/issues/5956
