### ISSUE TITLE
RpcContext Attatchment Bug in `ObjectToStringMap` for dubbo `2.7.6`

### ISSUE THREAD

**Issue by candyleer** [apache/dubbo#6162]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: any
* Java version: 1.8

### Steps to reproduce this issue
```java
public class DubboTest {

    public static void main(String[] args) {
        RpcContext.getContext().getAttachments().put("a", "b");

        System.out.println("before");
        for (Map.Entry<String, String> entry : RpcContext.getContext().getAttachments().entrySet()) {
            System.out.println(entry.getKey() + "==>" + entry.getValue());
        }

        System.out.println("after");
    }
}
```
execute result:
![image](https://user-images.githubusercontent.com/11530760/82122989-855e6c80-97c9-11ea-8333-9437b469b0e0.png)

the reason is `ObjectToStringMap` implements has serious problem.

I will make a PR to fix this

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by vergilyn** [comment]
可以用 `getObjectAttachments()` 替换的吧？
（`getAttachments()`已经被标记为 `Deprecated`）

**Comment by candyleer** [comment]
> 可以用 `getObjectAttachments()` 替换的吧？
> （`getAttachments()`已经被标记为 `Deprecated`）

可以用这个替换，老项目没法一次性替换完成，只能保持兼容

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
