### ISSUE TITLE
PojoUtils realize  not correct  for Multidimensional  primitive array

### ISSUE THREAD

**Issue by sqtds** [apache/dubbo#6177]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7-SNAPSHOT 
* Operating System version: mac
* Java version: 1.8.0_65

### Steps to reproduce this issue

1. PojoUtilsTest 下的test_PrimitiveArray新增如下测试用例
2. 
assertObject(new int[][]{{37, -39, 12456}});
        assertObject(new Integer[][][]{{{37, -39, 12456}}});
        assertArrayObject(new Integer[]{37, -39, 12456});
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

通过测试用例

### Actual Result

What actually happens?

org.opentest4j.AssertionFailedError: expected: [[I@b3d7190<[[37, -39, 12456]]> but was: [[I@10d59286<[[37, -39, 12456]]>

生成一个新的对象了。

**Comment by sqtds** [comment]
这个主要解决的是避免原生多维数组的转换，提升泛化性能。有大神能帮忙preview吗？

**Comment by AlbumenJ** [comment]
close #6177 via #6178
