### ISSUE TITLE
[Discuss] About Dubbo Docker Image

### ISSUE THREAD

**Issue by mercyblitz** [apache/dubbo#6183]
Should we need to build a docker image for Dubbo every release? 

I noticed the Spring Boot 2.3 has supported the Docker image :

> Spring Boot 2.3 adds some interesting new features that can help you package up your Spring Boot application into Docker images. [[Source](https://spring.io/blog/2020/05/15/spring-boot-2-3-0-available-now)]

**Comment by htynkn** [comment]
spring-boot will do extra work when doing package. but for dubbo, it's only a framework and works via library. also dubbo doesn't have gradle plugin or maven plugin (dubbo doesn't need too).

Could you share more detail what do you expect for this docker image? or what's the issue this image will solve?
