### ISSUE TITLE
2020 Alibaba Summer of Code

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#6203]
## 2020 Alibaba Summer of Code
Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience software development in the real world. Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summertime to participate in the open-source project and work with the core members of the project.

## What you can get?
On this exclusive developer journey, students will have the opportunity to:

Participate in the top projects of the International Open Source Foundation;
Get a scholarship from Alibaba;
Obtain an open source contributor certificate;
Get a fast pass of Alibaba Internship/recruitment;
Get your code adopted and used by the open source project！

## Our Mentor
Jun Liu (@chickenlj ), ASoC Mentor, Apache Dubbo PMC.
Deng Ming (@flycash ), ASoC Mentor, Apache Dubbo Committer.
Wang Xiang (@sxllwx ), ASoC Mentor, Apache Dubbo Committer.

## Timeline
![Timeline](https://user-images.githubusercontent.com/5254035/57433282-a8774780-726a-11e9-844c-c4f96a1d64b9.png)

## Apply Now! 
You can click on this link to apply directly:
https://github.com/apache/dubbo/issues?q=is%3Aopen+is%3Aissue+label%3AASOC2020
https://github.com/apache/dubbo-go/issues?q=is%3Aissue+is%3Aopen+label%3AASOC2020

## Contact the Organizer
Email Address: aliopensource@alibabacloud.com

**Comment by keithnull** [comment]
Maybe you need to update the timeline diagram.🤔
