### ISSUE TITLE
Springboot 整合dubbo 读不到<dubbo:application name>配置问题

### ISSUE THREAD

**Issue by LittleYoungMan** [apache/dubbo#6219]
您好：
我用的是springboot1.5.8版本 dubbo 2.8.6版本
遇到一个诡异的问题 
就是在启动项目的时候 客户端会报错  使用的是xml配置
读不到<dubbo:application name>
解决办法我有两种
1、写一个默认的dubbo.properties放到resource下，
将读不到的配置写到这里
2、写两遍读不到的配置   打印debug日志发现，两个dubbo:application:name都被读到了

不知道是dubbo自己的问题 还是和spring某个版本整合的问题。

**Comment by ZhiQinIsZhen** [comment]
有dubbo  2.8.x版本了？

**Comment by mercyblitz** [comment]
Please use the official release of Dubbo, for example, using 2.7.7.
