### ISSUE TITLE
Filter chain was not invoked with local calls since v2.7.6

### ISSUE THREAD

**Issue by jamespan** [apache/dubbo#6224]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6, 2.7.7
* Operating System version: macOS 10.14.1
* Java version: 1.8.0_222

### Steps to reproduce this issue

1. expose service with name Alice.call()
2. expose service with name Bob.call(), with an injvm @Reference field Alice
3. add a filter to Alice, which print "filter invoked"
4. invoke Alice.call()

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

"filter invoked" was print in console.

### Actual Result

"filter invoked" was not print in console.

**Comment by 634094502** [comment]
https://github.com/634094502/dubbo/tree/injvm-filter-issue/dubbo-demo
