### ISSUE TITLE
dubbo  nacos  consumers 启动后 无法获取providers   必须重启 providers 问题 。

### ISSUE THREAD

**Issue by fengzhenxin001** [apache/dubbo#6229]
consumers  ： 
![image](https://user-images.githubusercontent.com/57970765/82991582-79c43e80-a030-11ea-961f-9b4d5c83ee17.png)

**Comment by COBSNAN** [comment]
Environment
Dubbo version: 2.7.6
Operating System version: Win10
Java version: Java 11
我也遇到相同的问题，consumer新启动无法获取provider列表。 在NacosRegistry类getServiceNames0 方法，有个getLegacySubscribedServiceName，不知道这个是做什么的，如果consumer 没有group 会生成interface:version serverName，但正常的provider 生成的serverName 是 interface:version: ,这样导致获取不到提供服务列表，把RegistryDirectory 的forbidden 设置为true，必须重启一下provider 才可以，看dubbo2.7.8 好像也没对应修改
![image](https://user-images.githubusercontent.com/5803018/92694253-5c19ab80-f379-11ea-80d0-6734de353254.png)

**Comment by COBSNAN** [comment]
https://github.com/apache/dubbo/issues/5885 这个已经解决 需要升级版本
