### ISSUE TITLE
nacos + dubbo   consumer   重启后无法获取服务提供者

### ISSUE THREAD

**Issue by fengzhenxin001** [apache/dubbo#6230]
16:08:50.991 logback [http-nio-8082-exec-3] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/dubboDemo] threw exception [Request processing failed; nested exception is org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:8848 for service com.fzx.service.TestService:1.0.0 on consumer 192.168.8.131 use dubbo version 2.7.6, please check status of providers(disabled, not registered or in blacklist).] with root cause
org.apache.dubbo.rpc.RpcException: No provider available from registry 127.0.0.1:8848 for service com.fzx.service.TestService:1.0.0 on consumer 192.168.8.131 use dubbo version 2.7.6, please check status of providers(disabled, not registered or in blacklist).
	at org.apache.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:599)

**Comment by vergilyn** [comment]
参考 #5902
