### ISSUE TITLE
dubbo 2.7.7 多次注册 DubboBootstrapApplicationListener

### ISSUE THREAD

**Issue by dwhgygzt** [apache/dubbo#6231]
这个问题之前版本也发现有这个问题。

### Environment

* Dubbo version: 2.7.7
* Operating System version: window 10  springboot 2.2.6
* Java version: 1.8

### Steps to reproduce this issue

正常引入的 dubbo 2.7.7 启动报错

What actually happens?

APPLICATION FAILED TO START
***************************

Description:

The bean 'dubboBootstrapApplicationListener' could not be registered. A bean with that name has already been defined and overriding is disabled.

Action:

Debug 代码发现 DubboBootstrapApplicationListener 一共三处注册
org.apache.dubbo.config.spring.beans.factory.annotation.ServiceClassPostProcessor 中注册代码
// ------------------------------129行-----------------------------------------
 // @since 2.7.5
 registerBeans(registry, DubboBootstrapApplicationListener.class);
// -----------------------------------------------------------------------

org.apache.dubbo.config.spring.context.annotation.DubboConfigConfigurationRegistrar
// ------------------------------56行-----------------------------------------
// Since 2.7.6
 registerCommonBeans(registry);
// -----------------------------------------------------------------------

org.apache.dubbo.config.spring.context.annotation.DubboComponentScanRegistrar
// ------------------------------61行-----------------------------------------
// Since 2.7.6
 registerCommonBeans(registry);
// -----------------------------------------------------------------------

以上 registerCommonBeans 方法没啥问题 ， 该方法中注册DubboBootstrapApplicationListener的代码是
  // Since 2.7.4 Register DubboBootstrapApplicationListener as an infrastructure Bean
   registerInfrastructureBean(registry, DubboBootstrapApplicationListener.BEAN_NAME,
                DubboBootstrapApplicationListener.class);
这个registerInfrastructureBean方法里面有是否已经注册过的Bean判断，

ServiceClassPostProcessor  中的 registerBeans 没有判断是否相同的Bean是否已经注册过，导致抛出 BeanDefinitionOverrideException

建议相关代码统一全部调用 BeanRegistrar中的 registerInfrastructureBean 这个方法。

**Comment by lohcve** [comment]
这个问题这么明显，咋就不修复呢？
`2020-05-30 23:30:40.991 [main] WARN [AbstractApplicationContext:558] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'dubboBootstrapApplicationListener' defined in null: Cannot register bean definition [Generic bean: class [org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener]; scope=singleton; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'dubboBootstrapApplicationListener': There is already [Root bean: class [org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.
2020-05-30 23:30:41.005 [main] INFO [ConditionEvaluationReportLoggingListener:136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-05-30 23:30:41.009 [main] ERROR [LoggingFailureAnalysisReporter:40] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'dubboBootstrapApplicationListener' could not be registered. A bean with that name has already been defined and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

`

**Comment by kexianjun** [comment]
I have reproduce this problem,@mercyblitz can you pls take a look at this

**Comment by vergilyn** [comment]
或者是否可以考虑在`com.alibaba.spring.util.AnnotatedBeanDefinitionRegistryUtils#registerBeans(...)`中判断重复的beanName？ 

spring-context-support v1.0.6 只判断class，并未判断bean-name。

**Comment by libinglong** [comment]
Quick start always DO NOT start!LOL
