### ISSUE TITLE
ConcurrentModificationException when RpcContext.copyOf

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#6240]
in #6204. 在进行压测时发生了ConcurrentModificationException.

最终定位到该问题。
有A，B，C三个系统。B系统收到A的调用后，调用C系统。B系统在调用C系统时，是另开了一个线程去进行调用的。最终发现B系统中的Dubbo-Server线程在返回给A系统时RpcContext.copyOf的attachments和B系统调用C系统的业务线程中attachments相同。B调用C系统的业务线程中在ConsumerContextFilter返回后的finnaly中对attachments进行了clear，clear的这个attachments正是B系统返回A系统的Dubbo-Server线程中的那个attachemnts。

由于Dubbo-Server线程在copyOf的过程中，业务线程中对同一个attachments进行了clear.就导致了该HashMap的读写并发问题。

下面上图：
![image](https://user-images.githubusercontent.com/22524871/83127075-4ce55980-a10c-11ea-858a-06ba9de366d2.png)
![image](https://user-images.githubusercontent.com/22524871/83127156-6a1a2800-a10c-11ea-812b-0d174b975d38.png)

我通过 System.identityHashCode()打出了attachements对应的hashCode.可以看到，
在15:29:08 454时，Dubbo线程（DubboServerHandler-xxxxxx-thread-134）在构造AsyncRpcResult时进行copfOf操作，此时对应的attachemtns是684182654.在15:29:08 461时,Dubbo线程(DubboServerHandler-xxxxxx-thread-134)抛出了ConcurrentHashMap异常。可以推断，在这个时间段内，有其他线程对684182654这个attachement进行了修改。

继续看图，在15:29:08 461时，我们的业务线程(pool-1-thread-200)在发起对C的调用的ConsumerFilter的finnaly中，对attachments进行clear。clear的attachemtns还是684182654。
就是因为业务线程(pool-1-thread-200)的clear attachements操作，导致了（DubboServerHandler-xxxxxx-thread-134）在copyOf时发生了并发读写问题。

**Comment by horizonzy** [comment]
@chickenlj  @mercyblitz @cherishsince

**Comment by horizonzy** [comment]
![image](https://user-images.githubusercontent.com/22524871/83214507-523bb600-a197-11ea-8b60-572f055d8b73.png)
这是我在B应用的代码，很费解

**Comment by horizonzy** [comment]
如果asyncContext.signalContextSwitch.在业务线程invoke之前调用，在业务线程调用调用完成,在ConsumerContextFilter的finnaly中clear了attachemtns。在clear之前，dubbo线程已经在进行copyOf中的attachments拷贝，在进行iterator迭代。但没有操作完，这时业务线程clear已经操作完成.hashMap的modCount已经增加了，和iterator中的expectedModCount已经不一致了。这个在dubbo线程中肯定会抛出ConcurrentModificationException。这种情况在attachments中元素越多，越容易出现该情况。这个问题已经能够稳定浮现，在现在我们这边粗暴的操作是，RpcContext.copyOf的        copy.attachments.putAll(this.attachments);这行代码中，手动catch ConcurrentModificationException,会重试两次，该问题能够解决。社区看看有没有更优雅的解决方案

**Comment by horizonzy** [comment]
暂时用粗暴的方式进行修改以解决该问题:
修改点1: org.apache.dubbo.rpc.RpcContext#startAsync
如果当前线程是dubbo线程的话，打一个标识，并把当前线程的名称设置到value，为后续使用。因为只有dubbo线程和其他线程共享数据时才会有该问题，所以需要增加一个dubbo线程的标识。
```
  public static AsyncContext startAsync() throws IllegalStateException {
        RpcContext currentContext = getContext();
        if (currentContext.asyncContext == null) {
            currentContext.asyncContext = new AsyncContextImpl();
        }
        currentContext.asyncContext.start();
        appendDubboThreadInfo();
        return currentContext.asyncContext;
    }

    private static void appendDubboThreadInfo() {
        if (Thread.currentThread().getName().startsWith(AbstractServer.SERVER_THREAD_POOL_NAME)) {
            RpcContext.getContext().setAttachment(DUBBO_THREAD_SIGN, Thread.currentThread().getName());
        }
    }
```
改动点2: org.apache.dubbo.rpc.AsyncContextImpl#signalContextSwitch
在共享RpcContext时，需要判断当前线程的attachments中有无dubbo标识，没有dubbo标识的话，说明这个共享没有在dubbo线程与其他线程之前，不管。并且判断当前AsyncContextImpl的storeContext和当前线程的RpcContext是否一致，有可能在同一个线程中调用signalContextSwitch();这种情况需要排除。满足要求后，设置SHARE_CONTEXT_SIGN值，为后续ConsumerContextFilter的clearAttachments判断用。
```
 public void signalContextSwitch() {
        //add the share context sign
        if (storedContext.getAttachments().containsKey(DUBBO_THREAD_SIGN) && RpcContext.getContext() != storedContext) {
            storedContext.setAttachment(SHARE_CONTEXT_SIGN, String.valueOf(Boolean.TRUE));
        }
        RpcContext.restoreContext(storedContext);
        RpcContext.restoreServerContext(storedServerContext);
        // Restore any other contexts in here if necessary.
    }
```


改动点3: org.apache.dubbo.rpc.filter.ConsumerContextFilter#invoke
在clear attachments之后，需要判断一下SHARE_CONTEXT_SIGN有没有被Dubbo线程删除，因为clear必须要在Dubbo线程的RpcContext copyOf操作之后。所以这里重试3次，如果dubbo线程一直没有copyOf完成，这里就抛出异常，证明dubbo线程执行太慢了，本次调用失败。
 ```
public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        RpcContext.getContext()
                .setInvoker(invoker)
                .setInvocation(invocation)
                .setLocalAddress(NetUtils.getLocalHost(), 0)
                .setRemoteAddress(invoker.getUrl().getHost(),
                        invoker.getUrl().getPort());
        if (invocation instanceof RpcInvocation) {
            ((RpcInvocation) invocation).setInvoker(invoker);
        }
        try {
            // TODO should we clear server context?
            RpcContext.removeServerContext();
            return invoker.invoke(invocation);
        } finally {
            // TODO removeContext? but we need to save future for RpcContext.getFuture() API. If clear attachments here, attachments will not available when postProcessResult is invoked.
            //check attachments share context sign
            checkShareContextSign();
            RpcContext.getContext().clearAttachments();
        }
    }

     private void checkShareContextSign() {
        int retryCount = 3;
        long retry_internal = RpcContext.getContext().getAttachments().size() < 1000 ? 10 : 20;
        for (int i = 0; i < retryCount; i++) {
            boolean isShareContext = RpcContext.getContext().getAttachments().containsKey(SHARE_CONTEXT_SIGN);
            if (!isShareContext) {
                return;
            }
            try {
                Thread.sleep(retry_internal);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        throw new RpcException("Concurrent Exception, the biz Thread is faster than dubbo thread");
    }
```



改动点4: org.apache.dubbo.rpc.AsyncRpcResult#AsyncRpcResult(java.util.concurrent.CompletableFuture<java.lang.Object>, java.util.concurrent.CompletableFuture<org.apache.dubbo.rpc.Result>, boolean)
在AsyncRpcResult的RpcContext copyOf操作过后，需要清除SHARE_CONTEXT_SIGN值，这里需要判断，只有当前线程和之前设置dubbo线程的值一致时，才进行删除。因为其他线程也可能会走到这里来。

```
 public AsyncRpcResult(CompletableFuture<Object> future, final CompletableFuture<Result> rFuture, boolean registerCallback) {
        if (rFuture == null) {
            throw new IllegalArgumentException();
        }
        resultFuture = rFuture;
        if (registerCallback) {
            /**
             * We do not know whether future already completed or not, it's a future exposed or even created by end user.
             * 1. future complete before whenComplete. whenComplete fn (resultFuture.complete) will be executed in thread subscribing, in our case, it's Dubbo thread.
             * 2. future complete after whenComplete. whenComplete fn (resultFuture.complete) will be executed in thread calling complete, normally its User thread.
             */
            future.whenComplete((v, t) -> {
                RpcResult rpcResult;
                if (t != null) {
                    if (t instanceof CompletionException) {
                        rpcResult = new RpcResult(t.getCause());
                    } else {
                        rpcResult = new RpcResult(t);
                    }
                } else {
                    rpcResult = new RpcResult(v);
                }
                // instead of resultFuture we must use rFuture here, resultFuture may being changed before complete when building filter chain, but rFuture was guaranteed never changed by closure.
                rFuture.complete(rpcResult);
            });
        }
        this.valueFuture = future;
        // employ copy of context avoid the other call may modify the context content
        this.storedContext = RpcContext.getContext().copyOf();
        this.storedServerContext = RpcContext.getServerContext().copyOf();
        removeShareContextInfo();
    }

    private void removeShareContextInfo() {
        Map<String, String> attachments = RpcContext.getContext().getAttachments();
        if (attachments.containsKey(DUBBO_THREAD_SIGN) && attachments.containsKey(SHARE_CONTEXT_SIGN)) {
            if (attachments.get(DUBBO_THREAD_SIGN).equals(Thread.currentThread().getName())) {
                attachments.remove(DUBBO_THREAD_SIGN);
                attachments.remove(SHARE_CONTEXT_SIGN);
            }
        }
    }
```

**Comment by chickenlj** [comment]
> AsyncRpcResult时进行copfOf操作 

你用的是哪个版本的 Dubbo，现在 copyOf 方法已经被重构掉了

**Comment by horizonzy** [comment]
> > AsyncRpcResult时进行copfOf操作
> 
> 你用的是哪个版本的 Dubbo，现在 copyOf 方法已经被重构掉了

2.7.2版本。
