### ISSUE TITLE
Dubbo2.7.3版本 负载均衡获取权重代码REMOTE_TIMESTAMP_KEY 获取invoker启动时间,没有找到对应的key值

### ISSUE THREAD

**Issue by yexiaofei-CN** [apache/dubbo#6242]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: windows 10
* Java version: 1.8

问题描述
### Dubbo 负载均衡 consumer获取provider 设置的权重时，看下面一段代码
org.apache.dubbo.rpc.cluster.loadbalance.AbstractLoadBalance类中
` protected int getWeight(Invoker<?> invoker, Invocation invocation) {
        // 获取权重
        int weight = invoker.getUrl().getMethodParameter(invocation.getMethodName(), WEIGHT_KEY, DEFAULT_WEIGHT);

        if (weight > 0) {
            // 获取invoker的启动时间戳
            long timestamp = invoker.getUrl().getParameter(REMOTE_TIMESTAMP_KEY, 0L);
            if (timestamp > 0L) {
                // 计算当前invoker已经启动了多久
                int uptime = (int) (System.currentTimeMillis() - timestamp);
                // 获取预热时间
                int warmup = invoker.getUrl().getParameter(WARMUP_KEY, DEFAULT_WARMUP);
                // 若已经启动，且尚未到达预热时间，计算预热权重
                if (uptime > 0 && uptime < warmup) {
                    weight = calculateWarmupWeight(uptime, warmup, weight);
                }
            }
        }
        // 权重是一个非负整数
        return weight >= 0 ? weight : 0;
    }`
获取String REMOTE_TIMESTAMP_KEY = "remote.timestamp"; 这个key ，在url中是没用这个key的，会默认找 default.remote.timestamp。
引发的问题就是每次就是默认0，导致新加入的provider 也会有可能马上拿到。看到最新版本的dubbo中这个key更改为了timestamp。在2.7.3中是否是个bug。

**Comment by luoning810** [comment]
2.7.4.1 版本中已修复
