### ISSUE TITLE
dubbo rest 自定义ClientRequestFilter 不生效

### ISSUE THREAD

**Issue by benxiaohaihh** [apache/dubbo#6244]
* Dubbo version: 2.6.2

使用dubbo rest 协议暴露和消费dubbo服务，想在消费方调用服务方的时候，在消费方添加过滤器，向http header中添加一些信息传递到服务端（服务端有可能不是dubbo服务，所以这些信息塞在attachments中没用）。添加的自定义ClientRequestFilter 始终不生效。

配置如下：
spring:
  dubbo:
    application:
      name: provider-rest-test
    registry: 
      address: N/A
    protocol: 
      name: rest
      server: tomcat
      port: 8082
      extension: io.xx.test.filter.TraceHeaderOutputFilter,com.alibaba.dubbo.rpc.protocol.rest.support.LoggingFilter

看了下dubbo-rpc-rest部分的源码，
其在RestProtocol.java中，会判断url是否存在key为extension的自定义filter，debug发现此时url并无此extension，导致自定义的TraceHeaderOutputFilter无法注册到client中去。

 client.register(RpcContextFilter.class);
        for (String clazz : Constants.COMMA_SPLIT_PATTERN.split(url.getParameter(Constants.EXTENSION_KEY, ""))) {
            if (!StringUtils.isEmpty(clazz)) {
                try {
                    client.register(Thread.currentThread().getContextClassLoader().loadClass(clazz.trim()));
                } catch (ClassNotFoundException e) {
                    throw new RpcException("Error loading JAX-RS extension class: " + clazz.trim(), e);
                }
            }
        }
请问有什么办法可以注册自定义的ClientRequestFilter?或者有什么办法可以在url添加extension？

**Comment by lisll** [comment]
仔细想想

**Comment by benxiaohaihh** [comment]
> 仔细想想

我想了个招儿，扩展一下Protocol，自定义一个RestExtendProtocol，里面功能跟RestProtocol都一样，只是加上主动注册我的自定义ClientRequestFilter。
client.register(RpcContextFilter.class);
这样就可以实现我想要的效果了。但是不知道有没有更好的方法？

**Comment by CrazyHZM** [comment]
> > 仔细想想
> 
> 我想了个招儿，扩展一下Protocol，自定义一个RestExtendProtocol，里面功能跟RestProtocol都一样，只是加上主动注册我的自定义ClientRequestFilter。 client.register(TraceHeaderOutputFilter.class); 这样就可以实现我想要的效果了。但是不知道有没有更好的方法？

这个解决办法问题不大，或者可以开放一些扩展出来
