### ISSUE TITLE
README.md->Getting started->Implement service interface for the provider section class name error

### ISSUE THREAD

**Issue by DngY** [apache/dubbo#6246]
README.md->Getting started->Implement service interface for the provider 部分GreetingsServiceImpl多了一个s, 应该为GreetingServiceImpl，同样implements GreetingsService 也多了一个s, 应该为implements GreetingService.

**Comment by lebron374** [comment]
> README.md->Getting started->Implement service interface for the provider 部分GreetingsServiceImpl多了一个s, 应该为GreetingServiceImpl，同样implements GreetingsService 也多了一个s, 应该为implements GreetingService.

i create a new pr to fix this problem
