### ISSUE TITLE
dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置

### ISSUE THREAD

**Issue by lidaoyang** [apache/dubbo#6247]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: xxx
* Java version: 1.8

dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置
![image](https://user-images.githubusercontent.com/26211950/83252563-06602f80-a1de-11ea-999d-9d724ca7d606.png)
在nacos logs/config.log日志中发现发布配置的日志：
 INFO [main :config.NacosConfigService] [addr-hz-internal.edas.aliyun.com-c1d6921b-00bd-4f3f-b46e-3a44b407c036] [publish-single] ok, dataId=edas-provider, group=mapping-com.zfxf.app.dubbo.service.DemoService, tenant=c1d6921b-00bd-4f3f-b46e-3a44b407c036, config=1590738418788

把dubbo 2.7.5降到2.7.3不会出现创建配置的问题，测试了2.7.6和2.7.5都会出现创建配置的情况。
这个应该是个bug吧。

**Comment by madongbao** [comment]
困扰很久了 2.7.3之上都不行

**Comment by lidaoyang** [comment]
> 困扰很久了 2.7.3之上都不行

我这边测试2.7.3没有出现，应该跟环境有关，现在已经有2.7.8了，你可以用新版本的

**Comment by madongbao** [comment]
我用的就是最新版还是不行，

**Comment by lidaoyang** [comment]
> 我用的就是最新版还是不行，

嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象

**Comment by ORGRY** [comment]
如何解决呢

**Comment by tttmmiao** [comment]
怎么解决的, 同样遇到了这个问题

**Comment by madongbao** [comment]
> 怎么解决的, 同样遇到了这个问题

![image](https://user-images.githubusercontent.com/33247803/91688474-a38f8300-eb94-11ea-842d-5e040b86cb05.png)

**Comment by madongbao** [comment]
> 怎么解决的, 同样遇到了这个问题

![image](https://user-images.githubusercontent.com/33247803/91688480-a9856400-eb94-11ea-8fd9-18cee9fe2675.png)


> 如何解决呢

![image](https://user-images.githubusercontent.com/33247803/91688491-ad18eb00-eb94-11ea-8470-6bf1dbaffc5e.png)

**Comment by lidaoyang** [comment]
> https://mercyblitz.github.io/2020/05/11/Apache-Dubbo-%E6%9C%8D%E5%8A%A1%E8%87%AA%E7%9C%81%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/ &nbsp; dubbo2.7.3 使用的是本地元数据储存，之后提供了远程 默认是远程 设置下就好了 dubbo: application: name: ${spring.application.name} metadata-type: local
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lidaoyang"<notifications@github.com&gt;; 发送时间: 2020年8月25日(星期二) 下午4:35 收件人: "apache/dubbo"<dubbo@noreply.github.com&gt;; 抄送: "努力の往前飛"<1184156375@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [apache/dubbo] dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置 (#6247) 我用的就是最新版还是不行， 嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯，测试了一下，添加这个元数据不会存到这里了，但是还有条mapping 还在，
![image](https://user-images.githubusercontent.com/26211950/91694259-ee15fd00-eb9e-11ea-93fc-1c044c4d93c4.png)

**Comment by madongbao** [comment]
> > https://mercyblitz.github.io/2020/05/11/Apache-Dubbo-%E6%9C%8D%E5%8A%A1%E8%87%AA%E7%9C%81%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/   dubbo2.7.3 使用的是本地元数据储存，之后提供了远程 默认是远程 设置下就好了 dubbo: application: name: ${spring.application.name} metadata-type: local
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "lidaoyang"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年8月25日(星期二) 下午4:35 收件人: "apache/dubbo"<[dubbo@noreply.github.com](mailto:dubbo@noreply.github.com)>; 抄送: "努力の往前飛"<[1184156375@qq.com](mailto:1184156375@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [apache/dubbo] dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置 (#6247) 我用的就是最新版还是不行， 嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 嗯，测试了一下，添加这个元数据不会存到这里了，但是还有条mapping 还在，
> ![image](https://user-images.githubusercontent.com/26211950/91694259-ee15fd00-eb9e-11ea-93fc-1c044c4d93c4.png)

这个是必有的去除不了

**Comment by lidaoyang** [comment]
> > > https://mercyblitz.github.io/2020/05/11/Apache-Dubbo-%E6%9C%8D%E5%8A%A1%E8%87%AA%E7%9C%81%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/   dubbo2.7.3 使用的是本地元数据储存，之后提供了远程 默认是远程 设置下就好了 dubbo: application: name: ${spring.application.name} metadata-type: local
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "lidaoyang"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年8月25日(星期二) 下午4:35 收件人: "apache/dubbo"<[dubbo@noreply.github.com](mailto:dubbo@noreply.github.com)>; 抄送: "努力の往前飛"<[1184156375@qq.com](mailto:1184156375@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [apache/dubbo] dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置 (#6247) 我用的就是最新版还是不行， 嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 嗯，测试了一下，添加这个元数据不会存到这里了，但是还有条mapping 还在，
> > ![image](https://user-images.githubusercontent.com/26211950/91694259-ee15fd00-eb9e-11ea-93fc-1c044c4d93c4.png)
> 
> 这个是必有的去除不了

这个是什么原因知道吗？

**Comment by AlbumenJ** [comment]
> > > https://mercyblitz.github.io/2020/05/11/Apache-Dubbo-%E6%9C%8D%E5%8A%A1%E8%87%AA%E7%9C%81%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/   dubbo2.7.3 使用的是本地元数据储存，之后提供了远程 默认是远程 设置下就好了 dubbo: application: name: ${spring.application.name} metadata-type: local
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: "lidaoyang"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年8月25日(星期二) 下午4:35 收件人: "apache/dubbo"<[dubbo@noreply.github.com](mailto:dubbo@noreply.github.com)>; 抄送: "努力の往前飛"<[1184156375@qq.com](mailto:1184156375@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [apache/dubbo] dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置 (#6247) 我用的就是最新版还是不行， 嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 嗯，测试了一下，添加这个元数据不会存到这里了，但是还有条mapping 还在，
> > ![image](https://user-images.githubusercontent.com/26211950/91694259-ee15fd00-eb9e-11ea-93fc-1c044c4d93c4.png)
> 
> 这个是必有的去除不了

可以考虑关闭应用级服务发现模型就不会注册了

**Comment by lidaoyang** [comment]
> > > > https://mercyblitz.github.io/2020/05/11/Apache-Dubbo-%E6%9C%8D%E5%8A%A1%E8%87%AA%E7%9C%81%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/   dubbo2.7.3 使用的是本地元数据储存，之后提供了远程 默认是远程 设置下就好了 dubbo: application: name: ${spring.application.name} metadata-type: local
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: "lidaoyang"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年8月25日(星期二) 下午4:35 收件人: "apache/dubbo"<[dubbo@noreply.github.com](mailto:dubbo@noreply.github.com)>; 抄送: "努力の往前飛"<[1184156375@qq.com](mailto:1184156375@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [apache/dubbo] dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置 (#6247) 我用的就是最新版还是不行， 嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 嗯，测试了一下，添加这个元数据不会存到这里了，但是还有条mapping 还在，
> > > ![image](https://user-images.githubusercontent.com/26211950/91694259-ee15fd00-eb9e-11ea-93fc-1c044c4d93c4.png)
> > 
> > 
> > 这个是必有的去除不了
> 
> 可以考虑关闭应用级服务发现模型就不会注册了

不是很明白，具体怎么关呢？

**Comment by lidaoyang** [comment]
> > > > https://mercyblitz.github.io/2020/05/11/Apache-Dubbo-%E6%9C%8D%E5%8A%A1%E8%87%AA%E7%9C%81%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1/   dubbo2.7.3 使用的是本地元数据储存，之后提供了远程 默认是远程 设置下就好了 dubbo: application: name: ${spring.application.name} metadata-type: local
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: "lidaoyang"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年8月25日(星期二) 下午4:35 收件人: "apache/dubbo"<[dubbo@noreply.github.com](mailto:dubbo@noreply.github.com)>; 抄送: "努力の往前飛"<[1184156375@qq.com](mailto:1184156375@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [apache/dubbo] dubbo 2.7.5+nacos 1.1.4启动应用会在nacos配置列表中用服务命创建配置，一个服务会创建一个配置 (#6247) 我用的就是最新版还是不行， 嗯，刚才测试发现2.7.8确实还会出现创建配置的问题，dubbo不知道是不是故意的，不过我刚才测试了2.7.3的dubbo-spring-boot-starter 没有出现上面的现象 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 嗯，测试了一下，添加这个元数据不会存到这里了，但是还有条mapping 还在，
> > > ![image](https://user-images.githubusercontent.com/26211950/91694259-ee15fd00-eb9e-11ea-93fc-1c044c4d93c4.png)
> > 
> > 
> > 这个是必有的去除不了
> 
> 可以考虑关闭应用级服务发现模型就不会注册了

为啥默认会使用远程模式存储元数据呢，而不是本地模式呢？上面的文档中提到说建议使用本地存储模式是否正确呢？
![image](https://user-images.githubusercontent.com/26211950/91698198-e6f1ed80-eba4-11ea-952a-e2aceac7a4a0.png)

**Comment by sundong1982** [comment]
使用 dubbo.application.metadata-type=local 后依然有这个问题 只是注册到配置数据中的名称不同了，多了如：mapping-com.alibaba.cloud.dubbo.service.DubboMetadataService等

**Comment by ymingxu** [comment]
> 使用 dubbo.application.metadata-type=local 后依然有这个问题 只是注册到配置数据中的名称不同了，多了如：mapping-com.alibaba.cloud.dubbo.service.DubboMetadataService等

是的，我也遇到这个问题了

**Comment by sundong1982** [comment]
这是个大坑啊，各位怎么解决的。我目前想到的是把dubbo相关的单独放一个namespace

sca-2.2.0开始每个版本dubbo和nacos整合时都有BUG，下一个版本修复了又出现新问题，新版本根本不敢上生产。

**Comment by jasonlee529** [comment]
nacos的配置列表里面出现了这么多无用的信息，严重影响了配置管理的服务呀，要找到自己的配置文件，很不方便。

**Comment by AlbumenJ** [comment]
> nacos的配置列表里面出现了这么多无用的信息，严重影响了配置管理的服务呀，要找到自己的配置文件，很不方便。

最新版本已经不会自动写入服务映射信息了，请升级到最新版本

**Comment by zuonidelaowang** [comment]
> > nacos的配置列表里面出现了这么多无用的信息，严重影响了配置管理的服务呀，要找到自己的配置文件，很不方便。
> 
> 最新版本已经不会自动写入服务映射信息了，请升级到最新版本

我用的3.0.4 还是会生成  mapping 配置文件，是需要配置什么吗？ @AlbumenJ A

**Comment by zuonidelaowang** [comment]
> nacos的配置列表里面出现了这么多无用的信息，严重影响了配置管理的服务呀，要找到自己的配置文件，很不方便。

这个问题你解决了吗 我现在用的3.0.4会在 nacos 生成 mapping配置。

**Comment by jofei-cn** [comment]
可以加以下配置解决

dubbo:
  registry:
    use-as-metadata-center: false
