### ISSUE TITLE
How to get Spring ApplicationContext from Dubbo?

### ISSUE THREAD

**Issue by mostcool** [apache/dubbo#6248]
How to get Spring ApplicationContext from Dubbo?

**Comment by mostcool** [comment]
以前可以通过下面的方式获取
ApplicationContext context=ServiceBean.getSpringContext();
在2.7.6版本中怎么获取呢？

**Comment by mercyblitz** [comment]
You can try `org.apache.dubbo.config.spring.extension.SpringExtensionFactory` to get all instances of `ApplicationContext`.
