### ISSUE TITLE
How about consider changing default json impl to gson to replace fastjson

### ISSUE THREAD

**Issue by qixiaobo** [apache/dubbo#6256]
While fastjson has a lot of security problems.
In aliyun notice has chaimed to make a suggestion to gson.

>>>二、fastjson加固
>>>
>>>fastjson在1.2.68及之后的版本中引入了safeMode，配置safeMode后，无论白名单和黑名单，都>>>不支持autoType，可一定程度上缓解反序列化Gadgets类变种攻击（关闭autoType注意评估对业>>>务的影响）开启方法参考：https://github.com/alibaba/fastjson/wiki/fastjson_safemode
>>>
>>>
>>>
>>>三、采用其他json处理组件替换，jackson-databind漏洞也频发，建议使用Gson
>>>
>>>
>>>
>>>四、使用阿里云WAF/云防火墙紧急漏洞拦截（可申请免费试用），再升级到安全版本

https://github.com/alibaba/fastjson/wiki/security_update_20200601

**Comment by mercyblitz** [comment]
Good idea.
