### ISSUE TITLE
native-thrift,  the rpc communication is unstable, occasionally got error like: Expected protocol id ffffff82 but got.

### ISSUE THREAD

**Issue by wuhuajie** [apache/dubbo#6264]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: Linux staging 4.4.0-63-generic #84~14.04.2-Ubuntu SMP Mon Feb 13 11:04:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Java version: 1.8.0

### Steps to reproduce this issue

1.  start thrift provider with native-thrift, zookeeper is used for register
2. start thrift consumer with native-thrift, zookeeper is used for register 
3. run for while, there will be exception as below. But not happen regularly but occasionally.
  

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
no error.

### Actual Result

What actually happens?
which happens occasionally. Not every time. 

 Failed to invoke the method getInstitute in the service thrift.java.institute.InstituteService$Iface. Tried 3 times of the providers [10.28.57.152:20886, 10.28.61.123:20886] (2/2) from the registry zookeeper.config.palmdrive.cn:2181 on the consumer 59.110.53.154 using the dubbo version 2.7.6. Last error is: Failed to invoke remote service: interface thrift.java.institute.InstituteService$Iface, method: getInstitute, cause: Expected protocol id ffffff82 but got c

If there is an exception, please attach the exception trace:

Failed to invoke the method getInstitute in the service thrift.java.institute.InstituteService$Iface. Tried 3 times of the providers [10.28.57.152:20886, 10.28.61.123:20886] (2/2) from the registry zookeeper.config.palmdrive.cn:2181 on the consumer 59.110.53.154 using the dubbo version 2.7.6. Last error is: Failed to invoke remote service: interface thrift.java.institute.InstituteService$Iface, method: getInstitute, cause: Expected protocol id ffffff82 but got c
org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)

org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)

org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)

org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)

org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)

org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)

org.apache.dubbo.common.bytecode.proxy0.getInstitute(proxy0.java)

model.institute.InstituteModel.getDubboInstitute(InstituteModel.java:100)

model.institute.InstituteModel.getInstitute(InstituteModel.java:60)

controllers.institute.InstitutesCtrl.getSchool(InstitutesCtrl.java:100)

Routes$$anonfun$routes$1$$anonfun$applyOrElse$446$$anonfun$apply$446.apply(routes_routing.scala:7672)

Routes$$anonfun$routes$1$$anonfun$applyOrElse$446$$anonfun$apply$446.apply(routes_routing.scala:7672)

play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)

play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)

play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)

play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)

play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)

scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)

play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)

play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)

scala.concurrent.impl.Future$.apply(Future.scala:31)

scala.concurrent.Future$.apply(Future.scala:485)

play.core.j.JavaAction$class.apply(JavaAction.scala:82)

play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)

play.utils.Threads$.withContextClassLoader(Threads.scala:21)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)

scala.Option.map(Option.scala:145)

play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)

play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)

play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)

play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)

play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)

play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)

play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)

play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)

scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)

akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)

scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by wuhuajie** [comment]
Sometimes, below exception shows:

Failed to invoke the method getInstitutes in the service thrift.java.institute.InstituteService$Iface. Tried 3 times of the providers [10.28.57.152:20886] (1/1) from the registry zookeeper.config.palmdrive.cn:2181 on the consumer 59.110.53.154 using the dubbo version 2.7.6. Last error is: Failed to invoke remote service: interface thrift.java.institute.InstituteService$Iface, method: getInstitutes, cause: java.net.SocketException: Broken pipe (Write failed)
org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)

org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)

org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)

org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)

org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)

org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)

org.apache.dubbo.common.bytecode.proxy4.getInstitutes(proxy4.java)

model.institute.InstituteModel.getDubboInstitutes(InstituteModel.java:142)

model.institute.InstituteModel.getInstitutes(InstituteModel.java:71)

controllers.institute.InstitutesCtrl.getInstitutes(InstitutesCtrl.java:93)

Routes$$anonfun$routes$1$$anonfun$applyOrElse$407$$anonfun$apply$407.apply(routes_routing.scala:7388)

Routes$$anonfun$routes$1$$anonfun$applyOrElse$407$$anonfun$apply$407.apply(routes_routing.scala:7388)

play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)

play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)

play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)

play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)

play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)

scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)

play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)

play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)

scala.concurrent.impl.Future$.apply(Future.scala:31)

scala.concurrent.Future$.apply(Future.scala:485)

play.core.j.JavaAction$class.apply(JavaAction.scala:82)

play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)

play.utils.Threads$.withContextClassLoader(Threads.scala:21)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)

play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)

scala.Option.map(Option.scala:145)

play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)

play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)

play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)

play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)

play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)

play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)

play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)

play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)

scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)

akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)

scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)

scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)

scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)

scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by chickenlj** [comment]
Could you please help to find the root causing exception? I am not sure, but it's much likely a thrift using problem.

**Comment by wuhuajie** [comment]
Because it happens randomly,  there is no problem on retrying with the same parameters and the same return data. 

Thrift is called by dubbo, there is not direct usage of thrift on my program, only some configuration.

It seems that native-thrift is unstable on production mode.   Besides the exception below, there will oom and oom on direct memory occasionally. 


Are there any usage on production mode?

**Comment by chickenlj** [comment]
Sorry, I cannot reproduce the problem you reported. Please provide a demo so we can reproduce it.

We are also planning to move this extension to a new sub project called apache/dubbo-spi-extensions, you are welcome to continue asking there if the problem still exists.
