### ISSUE TITLE
Nacos集群 + Dubbo下provider 同时注册该集群下多个namespace

### ISSUE THREAD

**Issue by chuntaojun** [apache/dubbo#6265]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

Mac os
jdk1.8
Nacos1.1.4 集群
dubbo 2.7.6
spring boot 2.0.8

### Steps to reproduce this issue

https://github.com/alibaba/nacos/issues/2928

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by mercyblitz** [comment]
It's recommended to use the `namespace` parameter of Dubbo register URL, is like :

```
dubbo.registies.a.address = http://127.0.0.1:8888/?namespace=a

dubbo.registies.b.address = http://127.0.0.1:8888/?namespace=b
```

**Comment by RongXiong2016** [comment]
> It's recommended to use the `namespace` parameter of Dubbo register URL, is like :
> 
> ```
> dubbo.registies.a.address = http://127.0.0.1:8848/?namespace=a
> ...
> dubbo.registies.b.address = http://127.0.0.1:8848/?namespace=b
> ```

经过验证，同一地址下不同namespace还是不生效。不同address下namespace是可以的
