### ISSUE TITLE
提供者不能再被调用到

### ISSUE THREAD

**Issue by FloatingTea** [apache/dubbo#6280]
1. 环境:dubbo-admin：2.5.8;dubbo-spring-boot-starter:2.7.6
2. 3个提供者负载均衡策略采用默认（随机）。
3. 通过管控台对提供者A进行倍权操作，倍权生效，调用正常。
4. 通过管控台禁用提供者A。
5. 通过管控台启用提供者A。
6. 通过管控台修改负载均衡策略为轮询。调用异常，提供者A不再收到调用请求。

**Comment by dllen** [comment]
客户端本地有缓存？
