### ISSUE TITLE
对同个接口的不同实现通过@Service设置不同group无法生效，zk中只注册了其中一个group。

### ISSUE THREAD

**Issue by Yanyi-m** [apache/dubbo#6283]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: springboot 2.1.7，zookeeper 3.6.1
* Java version: java8

### Steps to reproduce this issue

1. 设置接口DemoDubboService。
2. 两个实现类DefaultDemoServiceImpl1，DefaultDemoServiceImpl2
3. 分别设置@Service(version = "1.0.0",group = "demo1"），@Service(version = "1.0.0",group = "demo2"）

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

demo1,demo2都在zk注册

### Actual Result

只能在zk中找到demo1

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by mercyblitz** [comment]
This issue will be resolved after Apache Dubbo 2.7.8 release.

**Comment by vergilyn** [comment]
相同的问题： #6056 , #5923
