### ISSUE TITLE
[check-update] get changed dataId error, code: 403 #2987

### ISSUE THREAD

**Issue by zhuyouzhufu** [apache/dubbo#6284]
* Dubbo version: 2.7.7
* Nacos version: 1.2.1
* Java version: 1.8

2020-06-07 22:37:14.940 ERROR [mall-message-producer,,,] 19144 --- [05-d8b36c995544] c.a.n.client.config.impl.ClientWorker : [fixed-120.0.0.1_8848-bc2f7f07-1289-4b09-8805-d8b36c995544] [check-update] get changed dataId error, code: 403

**Comment by zhuyouzhufu** [comment]
<spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
<dubbo-spring-boot.version>2.7.7</dubbo-spring-boot.version>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>${spring-cloud-alibaba.version}</version>
        </dependency>

        
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>${spring-cloud-alibaba.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo-spring-boot.version}</version>
        </dependency>

**Comment by zhuyouzhufu** [comment]
根据Dubbo2.7.7的更新文档说明已经处理了nacos的权限问题，但是我按照文档提示写完后还是会出现403的问题。是不是版本不稳定，这个权限Dubbo是不是支持的还不够完善？

**Comment by zhuyouzhufu** [comment]
dubbo:
  application:
    name: mall-message-producer
  provider:
    group: mall
    # 设置服务超时时间，默认值为1000毫秒
    timeout: 60000
  registry:
    group: mall
    username: mall
    password: mall
    # 使用哪种注册中心：apollo、zookeeper、nacos等。
    protocol: nacos
    #address: 127.0.0.1:8848?backup=127.0.0.2:8848
    address: nacos://127.0.0.1:8848/?username=mall&password=mall&namespace=bc2f7f07-1289-4b09-8805-d8b36c995544
  config-center:
    group: mall
    username: mall
    password: mall
    # 使用哪种注册中心：apollo、zookeeper、nacos等。
    protocol: nacos
#    namespace: bc2f7f07-1289-4b09-8805-d8b36c995544
    address: nacos://127.0.0.1:8848/?username=mall&password=mall&namespace=bc2f7f07-1289-4b09-8805-d8b36c995544
  metadata-report:
    group: mall
    username: mall
    password: mall
    address: nacos://127.0.0.1:8848/?username=mall&password=mall&namespace=bc2f7f07-1289-4b09-8805-d8b36c995544

**Comment by zhuyouzhufu** [comment]
说明一下我的Nacos是有mall这个组和用户并为mall分配了RW读写权限

**Comment by lidong1665** [comment]
这个是在2.7.7发布之后，我发现2.7.7还不支持nacos的鉴权，我才提交的pr，我的这个pr已经测试，是ok的。不知道2.7.8会不会合并进去：https://github.com/apache/dubbo/pull/6182。这个是支持类似nacos://127.0.0.1:8848/?username=mall&password=mall&namespace=bc2f7f07-1289-4b09-8805-d8b36c995544这种的配置方式。

**Comment by zhuyouzhufu** [comment]
> 这个是在2.7.7发布之后，我发现2.7.7还不支持nacos的鉴权，我才提交的pr，我的这个pr已经测试，是ok的。不知道2.7.8会不会合并进去：[https://github.com/apache/dubbo/pull/6182。](https://github.com/apache/dubbo/pull/6182%E3%80%82)这个是支持类似`nacos://127.0.0.1:8848/?username=mall&password=mall&namespace=bc2f7f07-1289-4b09-8805-d8b36c995544`这种的配置方式。
谢谢大哥的解答，我还以为2.7.7已经支持了。搞的我昨天死磕了一天。都在怀疑自己是不是太垃圾了，出了Demo也搞不出来
