### ISSUE TITLE
org.apache.dubbo.rpc.cluster.support.ClusterUtils#mergeUrl

### ISSUE THREAD

**Issue by pkxiuluo** [apache/dubbo#6293]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: mac
* Java version: 1.8

org.apache.dubbo.rpc.cluster.support.ClusterUtils#mergeUrl 这个里面写死了哪些provider key不可被consumer覆盖，比如TagRouter 需要的tag字段不可覆盖:copyOfLocalMap.remove(TAG_KEY);。
能否把这个能力开放出来，来定制provider url 中哪些key不可覆盖。

**Comment by finefuture** [comment]
@chickenlj 这个能力对于定制化需求还挺重要的,可以看下不

**Comment by AlbumenJ** [comment]
> @chickenlj 这个能力对于定制化需求还挺重要的,可以看下不

Welcome to submit PR, and we will review it ASAP.

**Comment by CrazyHZM** [comment]
@pkxiuluo @fakefrog 
This customization capability will be provided in the next version, just extend UrlMergeProcessor through SPI.
