### ISSUE TITLE
TypeBuilder缺失优先级，部分类型无法构建TypeDefinition

### ISSUE THREAD

**Issue by zjseu** [apache/dubbo#6306]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.x
* Operating System version: centos
* Java version: 1.8

### Steps to reproduce this issue

Dubbo在构建服务调用参数信息时，现有的TypeDefinition无法对[FastUtil](https://github.com/vigna/fastutil)中的Map进行解析。  
例如，FastUtil中的Int2ObjectMap的`getActualTypeArguments`参数长度为1，`MapTypeBuilder`会对长度进行校验，导致抛出IllegalArgumentException异常。  
TypeBuilder是支持SPI扩展的，可以自定义实现支持FastUtil的Builder，但是由于TypeBuilder中没有定义优先级顺序，因此在`TypeDefinitionBuilder`无法提升自定义TypeBuilder的优先级，导致无法构建相应参数定义信息。

异常信息：  
[ServiceDefinitionBuilder] Map type [it.unimi.dsi.fastutil.ints.Int2ObjectMap<it.unimi.dsi.fastutil.shorts.ShortList>] with unexpected amount of arguments [[Ljava.lang.reflect.Type;@38866769].[interface it.unimi.dsi.fastutil.shorts.ShortList]

![image](https://user-images.githubusercontent.com/13111067/84353556-f9860780-abf1-11ea-8730-668bcfaf7a11.png)

**Comment by cvictory** [comment]
能给个demo验证吗？
@zjseu

**Comment by cvictory** [comment]
https://github.com/apache/dubbo/pull/6365 支持排序，可以自定义了。
