### ISSUE TITLE
多注册中心 只注册了一个成功

### ISSUE THREAD

**Issue by RongXiong2016** [apache/dubbo#6326]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.7.6
* Operating System version: Mac os
* Java version: java8
nacos1.1.4 

### Steps to reproduce this issue

1. 同一个nacos下，配置了多个namespace
2. dubbo配置多注册中心后，项目启动后只注册到一个namespace下
3. 另外一个namespace没有任何provider，配置如下
dubbo:
  registries:
    test1:
      address: nacos://127.0.0.1:8848?namespace=3d064614-057d-4298-a6ce-34ed39e053e1
    test2:
      address: nacos://127.0.0.1:8848?namespace=1ca1de39-870c-497f-9ac2-f67bb3665691
      default: true
    

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
希望能分别注册到2个namespace下。另外经过实验 当两个address配置的ip:port不一样时是可以成功注册到2个namespace下，是不是dubbo注册时认为ip+port一样就是相同的注册中心

### Actual Result

What actually happens?

**Comment by tswstarplanet** [comment]
同ip同端口，应该只算一个注册中心

**Comment by RongXiong2016** [comment]
> 同ip同端口，应该只算一个注册中心

那这个能否在后续版本提供支持呢

**Comment by RongXiong2016** [comment]
请问是否未来有提供支持呢？

**Comment by RongXiong2016** [comment]
升级2.7.8后，问题解决

**Comment by TOP-LH** [comment]
> 升级2.7.8后，问题解决

请帮忙看一下我这个问题 https://github.com/apache/dubbo/discussions/14961
