### ISSUE TITLE
2.7.X是否有不带com.alibaba目录的包

### ISSUE THREAD

**Issue by jqncc** [apache/dubbo#6331]
新项目使用dubbo2.7.x不需要兼容老版本dubbo, com.alibaba显得多余了,这个目录是否能去掉,maven库有无不带这个目录的包

**Comment by qixiaobo** [comment]
No way，just  some others need to make a compatibility~ Or provide a adapter

**Comment by CodeIngL** [comment]
你想要去掉，又想极为简单跟踪社区源码，可以参考
https://github.com/open-wrapper/dubbo-wrapper

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
