### ISSUE TITLE
Method threw 'java.lang.StackOverflowError' exception. Cannot evaluate org.apache.dubbo.config.spring.ReferenceBean.toString()

### ISSUE THREAD

**Issue by 283883031** [apache/dubbo#6334]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: win10 x64
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo从2.8.4 的版本升级到2.7.6的版本，生产者启动正常，消费者调用多个应用的生产实例化dubbo的bean时抛出异常。 低版本启动正常，使用正常。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
堆栈异常如下：
[stack trace.txt](https://github.com/apache/dubbo/files/4786508/stack.trace.txt)


```

**Comment by canglang1973** [comment]
这个问题应该是你订阅了太多的服务造成的,实例化bean的时候栈深度不够导致溢出,你可以通过设置-Xss值大一点来解决,like this issue https://github.com/apache/dubbo/issues/5745

**Comment by 283883031** [comment]
是的，把-Xss设置成3M可以启动成功。消费者大概订阅了有400个服务。 跟踪源码发现有存在循环依赖，引起溢出。
