### ISSUE TITLE
Nacos上无法下线Dubbo应用

### ISSUE THREAD

**Issue by whthomas** [apache/dubbo#6335]
Nacos版本：1.3.0
Dubbo版本：2.7.7

consumer应用在Nacos(集群)中无法正常下线，在Nacos上点击下线之后还是能正常通过Dubbo调用到Provider端提供的服务。

**Comment by tswstarplanet** [comment]
你试过在单机版里面下线吗？单机版我试了没问题

**Comment by whthomas** [comment]
单机版的我没有尝试过，但是我们需要上生产的话，肯定不能是在单机版上运行的。

**Comment by tswstarplanet** [comment]
你可以在测试环境试下，如果单机没问题，可能不是dubbo的问题

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
