### ISSUE TITLE
错误日志提示——格式问题

### ISSUE THREAD

**Issue by wangkang-ARM** [apache/dubbo#6345]
- [ ] Log format error "is not subtype" plus space prefix

### Environment

* Dubbo version: 2.7.0
* Operating System version:  MAC OS
* Java version: 1.8

### Steps to reproduce this issue
class：org.apache.dubbo.common.extension.ExtensionLoader#loadClass

错误行号：691

内容：throw new IllegalStateException("Error when load extension class(interface: " + this.type + ", class line: " + clazz.getName() + "), class " + clazz.getName() + "is not subtype of interface.");

日志格式错误 "is not subtype"加空格前缀

```java
 private void loadClass(Map<String, Class<?>> extensionClasses, java.net.URL resourceURL, Class<?> clazz, String name) throws NoSuchMethodException {
        if (!type.isAssignableFrom(clazz)) {
            throw new IllegalStateException("Error when load extension class(interface: " +
                    type + ", class line: " + clazz.getName() + "), class "
                    + clazz.getName() + "is not subtype of interface.");
        }
```

```java
cause: Error when load extension class(interface: interface com.luban.dubbo_spi.api.Car, class line: com.luban.dubbo_spi.impl.BenzCar), class com.luban.dubbo_spi.impl.BenzCaris not subtype of interface.

造成误解，并不存在com.luban.dubbo_spi.impl.BenzCaris not subtype of interface. 而是com.luban.dubbo_spi.impl.BenzCar
```

**Comment by tswstarplanet** [comment]
Can you submit a pr to fix it ?

**Comment by CrazyHZM** [comment]
Has been resolved.
