### ISSUE TITLE
Dubbo服务的故障自隔离与自恢复能力方案

### ISSUE THREAD

**Issue by stoneapple** [apache/dubbo#6360]
Dubbo版本：2.5.9
问题：    基础设施层面的一些问题，如ceph故障，导致服务提供者节点无法正常工作，通过服务下线去隔离，会对注册中心造成一定的性能压力，并且时效性也不够。我们希望服务提供者端检测到此类故障（比如日志输出超时，数据库连接超时）就自己迅速进入"隔离"状态，并通过长链接通知到各个消费者，是的流量不再进入该提供方。

解决思路：增强一下dubbo协议的，在服务提供者与消费者长链接2个状态（正常、只读）之上，增加一个"隔离”状态，在这个状态下，消费者也不会筛选到该提供者。而提供者端自己实现控制逻辑，对这个"隔离”状态进行修改。请帮忙分析下这方案是否合理，多谢！服务提供方侧可自行配置检查项，可以通过日志输出探测磁盘或者业务要素的判断。

**Comment by CrazyHZM** [comment]
The 2.5.x version is no longer maintained, it is recommended to upgrade to the new version.
