### ISSUE TITLE
关于官方文档spi拓展实现

### ISSUE THREAD

**Issue by wangchongbin** [apache/dubbo#6367]
src
 |-main
    |-java
        |-com
            |-xxx
                |-XxxProtocol.java (实现Protocol接口)
                |-XxxExporter.java (实现Exporter接口)
                |-XxxInvoker.java (实现Invoker接口)
    |-resources
        |-META-INF
            |-dubbo
                |-org.apache.dubbo.rpc.Protocol (纯文本文件，内容为：xxx=com.xxx.XxxProtocol)

官网指示需要这样建立项目结构,但是,我根据这个结构建立的项目,进行拓展
报错:
Failed to bind properties under 'spring.dubbo.protocol' to com.alibaba.dubbo.config.ProtocolConfig:

    Property: spring.dubbo.protocol.serialization
    Value: CustomDubboSerialization
    Origin: class path resource [application.yml]:23:22
    Reason: No such extension CustomDubboSerialization for serialization/com.alibaba.dubbo.common.serialize.Serialization

最后解决:
src
 |-main
    |-java
        |-com
            |-xxx
                |-XxxProtocol.java (实现Protocol接口)
                |-XxxExporter.java (实现Exporter接口)
                |-XxxInvoker.java (实现Invoker接口)
    |-resources
        |-META-INF
            |-dubbo
                |-com.alibaba.dubbo.rpc.Protocol (纯文本文件，内容为：xxx=com.xxx.XxxProtocol)

注意:你家dubbo项目已经升级成了Apache的顶级项目了,也捐给了Apache,所以域名要跟着更新啊,ps:搞了半天,原来是官方错了-_-

**Comment by laddcn** [comment]
I have had the same problem before. 
1. Official document should be updted.
2. Both package name should be supportted. 

I will give a PR to resolve this problem.

**Comment by laddcn** [comment]
This problem has been resolve in https://github.com/apache/dubbo/pull/6068  since 2.7.7. Update your dubbo version to 2.7.7 and have a try.

**Comment by wangchongbin** [comment]
ok , 谢谢
