### ISSUE TITLE
bug:关于2.7.*版本调用低版本接口不通

### ISSUE THREAD

**Issue by jsjinfuming** [apache/dubbo#6377]
Dubbo版本升级，由于采用逐步替换，需同时兼容dubbo高版本(2.7.7)调用低版本(2.6.2)和低版本调用高版本，在2.7.7调用2.6.2版本时候，由于2.6.2采用全局配置版本号，重试次数，过滤器等，出现高版本无法兼容情况，发现2.7.*版本在UrlUtils中，获取参数和2.6.2不一致，以下为截图：
  2.6.2版本如下：
![图片](https://user-images.githubusercontent.com/67535872/85941012-b1d1e080-b952-11ea-99e4-a8f0a0fad043.png)
![图片](https://user-images.githubusercontent.com/67535872/85941025-c910ce00-b952-11ea-8c2d-00f075502964.png)

URL：
  public String getParameter(String key) {
        String value = parameters.get(key);
        if (value == null || value.length() == 0) {
            value = parameters.get(Constants.DEFAULT_KEY_PREFIX + key);
        }
        return value;
    }
2.7.7版本：
![图片](https://user-images.githubusercontent.com/67535872/85941030-d75eea00-b952-11ea-986b-ec9e9aca58e8.png)
![Uploading 图片.png…]()

URL类：
 public String getParameter(String key) {
        return parameters.get(key);
    }

临时解决版本：
  方案一)在低版本手动增加隐式参数，携带版本号，超时时间等
 方案二) 修改源码，增加默认参数获取，default.*

以上为自己修改方案，如有问题，麻烦及时告知，更正

**Comment by laddcn** [comment]
能把有问题的Provider（2.6.2）和Consumer（2.7.7)的参数配置贴下吗，我试了下，好像问题没有复现

**Comment by jsjinfuming** [comment]
Provider的接口参数
dubbo://172.20.20.219:20882/com.im.pps.bill.rpc.service.AccountAdminBillProtocol?anyhost=true&application=pps-bill-service-biz&default.payload=220971520&default.retries=0&default.service.filter=providerFilter&default.timeout=500000&default.version=1.0.0&dubbo=2.6.2&generic=false&gray_release=prod&interface=com.im.pps.bill.rpc.service.AccountAdminBillProtocol&methods=queryTruckOrdList,queryFormsSupplierList
其中这些：default.*这些参数，在低版本2.6.2中就无法获取，导致Consumer调用Provider出现无法forbidden 为true ,无法调用情况
下图为provider接口截图
![Uploading 图片.png…]()

**Comment by jsjinfuming** [comment]
Provider(2.6.2版本)接口：





服务端服务，采用xml方式，版本，重试次数等采用默认配置，红线标准参数，均获取不了





Consumer（2.7.7) 配置：








Consumer调用时候发现：

org.apache.dubbo.common.URL对获取参数做了调整，导致获取不到default.* 相关信息






备注：
       1)我司采用Provider 所有配置在xml方式设置，设置全局默认版本，超时时间等，没有单独针对接口逐个设置，针对未设置版本号，采用默认版本号，故导致高版本(2.7.7)升级时，兼容低版本接口无法调用情况，麻烦帮忙核实下，是配置有误，还是设置问题
      2）发现 Consumer 和 Provider 相关设置全局默认参数均丢失了，麻烦帮忙协助排查下




以上，有不对之处，麻烦及时指正，万分感谢！！！





--
金福明

技术中心
中储南京智慧物流科技有限公司
Mobile: 18013316328
邮箱：jinfuming@zczy56.com
地址：南京市鼓楼区燕江路201号数码港2期4层




发件人：Lei Jiang <notifications@github.com>
发送日期：2020-06-29 22:41:17
收件人：apache/dubbo <dubbo@noreply.github.com>
抄送人：jsjinfuming <jinfuming@zczy56.com>,Author <author@noreply.github.com>
主题：Re: [apache/dubbo] bug:关于2.7.*版本调用低版本接口不通 (#6377)

能把有问题的Provider（2.6.2）和Consumer（2.7.7)的参数配置贴下吗，我试了下，好像问题没有复现

**Comment by jsjinfuming** [comment]
麻烦有空帮忙看下，万分感谢





Provider(2.6.2版本)接口：





服务端服务，采用xml方式，版本，重试次数等采用默认配置，红线标准参数，均获取不了





Consumer（2.7.7) 配置：








Consumer调用时候发现：

org.apache.dubbo.common.URL对获取参数做了调整，导致获取不到default.* 相关信息






备注：
       1)我司采用Provider 所有配置在xml方式设置，设置全局默认版本，超时时间等，没有单独针对接口逐个设置，针对未设置版本号，采用默认版本号，故导致高版本(2.7.7)升级时，兼容低版本接口无法调用情况，麻烦帮忙核实下，是配置有误，还是设置问题
      2）发现 Consumer 和 Provider 相关设置全局默认参数均丢失了，麻烦帮忙协助排查下




以上，有不对之处，麻烦及时指正，万分感谢！！！









发件人：Lei Jiang <notifications@github.com>
发送日期：2020-06-29 22:41:17
收件人：apache/dubbo <dubbo@noreply.github.com>
抄送人：jsjinfuming <jinfuming@zczy56.com>,Author <author@noreply.github.com>
主题：Re: [apache/dubbo] bug:关于2.7.*版本调用低版本接口不通 (#6377)

能把有问题的Provider（2.6.2）和Consumer（2.7.7)的参数配置贴下吗，我试了下，好像问题没有复现

**Comment by CodeIngL** [comment]
直接升级太危险了，你可以参考我司的升级方案
https://github.com/open-wrapper/dubbo-wrapper

**Comment by JasonMing** [comment]
releated to: https://github.com/apache/dubbo/issues/6728
already fixed at https://github.com/apache/dubbo/commit/eed216b14e8c8e980e98a78ce495806a32df2b97 in 2.7.9 release
