### ISSUE TITLE
While exception happened in server side, stacktrace of consumer side can not be obtained.

### ISSUE THREAD

**Issue by liusf1993** [apache/dubbo#6379]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version:Linux version 4.15.0-88-generic 16.04.1-Ubuntu
* Java version: java version "1.8.0_201"

### Steps to reproduce this issue

1. invoke the remote method in consumer side.  
2. always throw a exception in the method implementation of server side.  
3. catch the exception in consumer side, and print stacktrace of the exception.  

### Expected Result

stacktrace of consumer side can not be obtained.

### Actual Result  
only stacktrace of server side was printed, we can not find where we invoked the remote method.  

I have read related the code, it's in `org.apache.dubbo.rpc.AppResponse#recreate`  
```` 
@Override
    public Object recreate() throws Throwable {
        if (exception != null) {
            // fix issue#619
            try {
                // get Throwable class
                Class clazz = exception.getClass();
                while (!clazz.getName().equals(Throwable.class.getName())) {
                    clazz = clazz.getSuperclass();
                }
                // get stackTrace value
                Field stackTraceField = clazz.getDeclaredField("stackTrace");
                stackTraceField.setAccessible(true);
                Object stackTrace = stackTraceField.get(exception);
                if (stackTrace == null) {
                    exception.setStackTrace(new StackTraceElement[0]);
                }
            } catch (Exception e) {
                // ignore
            }
            throw exception;
        }
        return result;
    }
````    
while recreating the result,  `AppResponse` only deserialize the exception of server side, so stacktrace of consumer side is ignored.   
maybe we can modify `throw exception` to `new RpcException(exception)`.

**Comment by KindHunter** [comment]
i also have seen this kind issue, which kind of  bother me, so i create a ConsumerExceptionFilter.java to append consumer side stackTrace to exception

**Comment by liusf1993** [comment]
> i also have seen this kind issue, which kind of bother me, so i create a ConsumerExceptionFilter.java to append consumer side stackTrace to exception

I'm a little confused on how to solve the problem.   
I have tried to use `new RpcException(exception)` to warpper the internal cause, but from the ut  failures, I realized the  side effect of wrapping exception,  exception catch may not work as expected.  
I also tried to fix merge stacktrace by using code like like this  
````
                    StackTraceElement[] localStackTrace = new RpcException().getStackTrace();
                    StackTraceElement[] responseStackTrace = exception.getStackTrace();
                    StackTraceElement[] mergedStackTraceElement = new StackTraceElement[localStackTrace.length + responseStackTrace.length];
                    System.arraycopy(localStackTrace, 0, mergedStackTraceElement, 0, localStackTrace.length);
                    System.arraycopy(responseStackTrace, 0, mergedStackTraceElement, localStackTrace.length, responseStackTrace.length);
                    exception.setStackTrace(mergedStackTraceElement);
```` 
but the error message is not elegent, and is a little confused.

**Comment by manzhizhen** [comment]
I don't know what your ultimate goal is. The server throws an exception. What's wrong with the client getting the exception stack of the server?

**Comment by liusf1993** [comment]
> I don't know what your ultimate goal is. The server throws an exception. What's wrong with the client getting the exception stack of the server?

While an exception happend in server side, I want to know where I invoke the remote method in the client. But from current stacktrace,  I can't get the message.

**Comment by choaryzhang** [comment]
`@Activate
@Slf4j
public class RpcAuthorizationFilter implements Filter {

    private static final String REQUEST_HEADER = "_REQUEST_HEADER";

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        boolean checkPass = true;
        String checkMessage = null;
        try {
            //your code
        } catch (Exception ex) {
            log.error("error:", ex);
            checkPass = false;
            checkMessage = ex.getMessage();
        }
        if (checkPass) {
            return invoker.invoke(invocation);
        } else {
            return AsyncRpcResult.newDefaultAsyncResult(new RpcException(checkMessage), invocation);
        }
    }}`

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
