### ISSUE TITLE
什么时候 可以友好支持网关类的应用啊

### ISSUE THREAD

**Issue by afei1689** [apache/dubbo#638]
1。客户端泛化异步调用服务
2。服务端可以支持异步返回结果

**Comment by chickenlj** [comment]
个人认为网关并不是dubbo这种服务框架项目本身要解决的问题，但在微服务体系中却是和dubbo等rpc框架密切相关的。未来dubbo做好模块化拆分且能完善整个生态体系的话，网关也是必不可少的一环。

**Comment by beiwei30** [comment]
我想 @afei1689 的意思是**为了更好的支持网关**，dubbo 客户端和服务端需要具备的能力。

**Comment by chickenlj** [comment]
Supported start from 2.7.3
