### ISSUE TITLE
2.7.7 <dubbo:consumer/> 不生效

### ISSUE THREAD

**Issue by CatHubChapLin** [apache/dubbo#6381]
在2.7.3版本将beansOfTypeIncludingAncestors返回的consumer放到了ReferenceBean.consumer变量中
// [2.7.3] org.apache.dubbo.config.spring.ReferenceBean 

    public void afterPropertiesSet() throws Exception {
        if (applicationContext != null) {
            BeanFactoryUtils.beansOfTypeIncludingAncestors(applicationContext, ConfigCenterBean.class, false, false);
        }

        if (getConsumer() == null) {
            Map<String, ConsumerConfig> consumerConfigMap = applicationContext == null ? null : BeanFactoryUtils.beansOfTypeIncludingAncestors(applicationContext, ConsumerConfig.class, false, false);
            if (consumerConfigMap != null && consumerConfigMap.size() > 0) {
                ConsumerConfig consumerConfig = null;
                for (ConsumerConfig config : consumerConfigMap.values()) {
                    if (config.isDefault() == null || config.isDefault()) {
                        if (consumerConfig != null) {
                            throw new IllegalStateException("Duplicate consumer configs: " + consumerConfig + " and " + config);
                        }
                        consumerConfig = config;
                    }
                }
                if (consumerConfig != null) {
                    setConsumer(consumerConfig);
                }
            }
        }
        // ... 
    }

但是在2.7.7，仅仅调用了beansOfTypeIncludingAncestors,没有将返回值放进consumer变量，导致dubbo:consumer 不生效
//[2.7.7]org.apache.dubbo.config.spring.ReferenceBean

    public void afterPropertiesSet() throws Exception {
        // Initializes Dubbo's Config Beans before @Reference bean autowiring
        prepareDubboConfigBeans();
        // ...
    }

    /**
     * Initializes there Dubbo's Config Beans before @Reference bean autowiring
     */
    private void prepareDubboConfigBeans() {
        //...
        beansOfTypeIncludingAncestors(applicationContext, ConsumerConfig.class);
        //...
    }

**Comment by manzhizhen** [comment]
mark

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
