### ISSUE TITLE
dubbo 2.7.7   org.apache.dubbo.config.RegistryConfig#setAddress  has bug，may cause the username or password to be null

### ISSUE THREAD

**Issue by fish-mirror** [apache/dubbo#6392]
### Environment

* Dubbo version: 2.7.7
* Operating System version: Linux & MacOS
* Java version: 1.8.0_101

### Steps to reproduce this issue

我们项目是通过 xml 进行配置的，这次因为序列化漏洞需要从 2.7.4.1 升级到 2.7.7，升级后发现注册中心的 username 获取不到一直报 Invalid url, password without username 错误

xml 配置如下
```xml
    <dubbo:registry id="xxx"
                    address="zk1.host.xxx:2181,zk2.host.xxx:2181,zk3.host.xxx:2181"
                    protocol="zookeeper"
                    username="${dubbo.registry.xxx.username}"
                    password="${dubbo.registry.xxx.password}"
                    client="curator"
                    group="xxx"
                    file="/var/tmp/dubbo/xxx"
                    version="1.0.0">
    </dubbo:registry>
```

### Expected Result
正确加载所有配置项

### Actual Result
username 为空，报错信息是 报 Invalid url, password without username 

### Analysis

原来 2.7.4.1 版本是
``` java
public void setAddress(String address) {
        this.address = address;
        if (address != null) {
            int i = address.indexOf("://");
            if (i > 0) {
                this.updateIdIfAbsent(address.substring(0, i));
                this.updateProtocolIfAbsent(address.substring(0, i));
                int port = address.lastIndexOf(":");
                if (port > 0) {
                    this.updatePortIfAbsent(StringUtils.parseInteger(address.substring(port + 1)));
                }
            }
        }
    }
```
而在 2.7.7 改为
``` java
public void setAddress(String address) {
        this.address = address;
        if (address != null) {
            try {
                URL url = URL.valueOf(address);
                this.setUsername(url.getUsername());
                this.setPassword(url.getPassword());
                this.updateProtocolIfAbsent(url.getProtocol());
                this.updatePortIfAbsent(url.getPort());
                this.updateParameters(url.getParameters());
            } catch (Exception var3) {
            }
        }

    }
```
这个方法会导致如果 setAddress 方法在 setUsername 和 setPassword 方法之后执行的话，会导致设置的 username 和 paswword  覆盖，我这边配置 address 没有用 `username:pwd@ip:port`的方式配置，username 和 password 为 null

我的理解是，既然可以单独设置的 username 和 password 的话，这样一个 bug 会让人遇到的时候很奇怪。
debug 的时候发现读取 xml 的 properties 顺序如下
![image](https://user-images.githubusercontent.com/12289604/86109974-8ccaa280-baf7-11ea-80de-699c0e44624a.png)

当 address 读取在 username 和 password 之前不会有这个问题，希望可以把 setAddress  setUsername setPassword 方法改成不受顺序影响的方式

**Comment by fish-mirror** [comment]
今天有空正好继续看下昨天 properties 顺序的问题，因为发现有的机器上 properties 顺序是没问题（address 在 username 和 password 前面）可以成功部署，有的顺序就有问题。


 xml 配置的情况下，RegisterConfig 这个类是在 `org.apache.dubbo.config.spring.schema.DubboBeanDefinitionParser#parse(org.w3c.dom.Element, org.springframework.beans.factory.xml.ParserContext, java.lang.Class<?>, boolean)` 这里被加载的。

其中加载 properties 是先通过反射 `beanClass.getMethods()` 获取所有公共方法，在循环中获取所有的 settter 方法，然后去 
`beanDefinition.getPropertyValues().addPropertyValue(beanProperty, reference);`

 `java.lang.Class#getMethods` 最终是通过 native 方法从 jvm 获取的，转为数组的时候，jvm 是不保证方法顺序的。

查阅资料后，简单来说就是就是，jvm 在类解析的时候，从 class 文件里挨个解析出 method，并存到 _methods字段里，并作了一次排序序，但是这个排序是根据这个方法名对应的 Symbol 对象地址进行排序的。因为存在释放内存的操作，所以分配的地址不是线性变化的。
根据地址排序应该也是为了速度，毕竟地址排序是最快的。


综上，我的建议是，要么修改 `org.apache.dubbo.config.RegistryConfig#setAddress` 方法的调用结果不受 setter 方法的调用顺序影响，要么，在 `org.apache.dubbo.config.spring.schema.DubboBeanDefinitionParser#parse(org.w3c.dom.Element, org.springframework.beans.factory.xml.ParserContext, java.lang.Class<?>, boolean)`  中加载 properties 能够控制 address 这个属性能够排序在 username 和 password 前面

**Comment by fish-mirror** [comment]
目前采用了将 address 配置改成 `usernam:pwd@zk1.host.xxx:2181,zk2.host.xxx:2181,zk3.host.xxx:2181` 的方式来解决。
但这个 bug 建议还是修复下，踩到坑还是有点难受

**Comment by chjskarl** [comment]
遇到同样问题了，但是这是zookeeper的账号密码不生效，以前旧版本的是正常了，这不敢升级呀，希望尽快解决

**Comment by chjskarl** [comment]
遇到同样问题了，希望尽快解决，旧版本的功能是正常的

**Comment by DIscord010** [comment]
我觉得在`setAddress`方法中进行判空处理比控制`propertyValues`顺序要来的方便，你可以提个pr修复这个问题。

**Comment by chjskarl** [comment]
希望下一版本可以修复这个bug。老版本的功能是正常的，不然不好升级，不知道怎么提pr？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月8日(星期三) 中午11:16
收件人:&nbsp;"apache/dubbo"<dubbo@noreply.github.com&gt;;
抄送:&nbsp;"cjs"<811591@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo] dubbo 2.7.7   org.apache.dubbo.config.RegistryConfig#setAddress  has bug，may cause the username or password to be null (#6392)





 
我觉得在setAddress方法中进行判空处理比控制propertyValues顺序要来的方便，你可以提个pr修复这个问题。

**Comment by icankeep** [comment]
#6467 has already fixed it

RegistryConfig.java
```java
// Refactor since 2.7.8
updatePropertyIfAbsent(this::getUsername, this::setUsername, url.getUsername());
updatePropertyIfAbsent(this::getPassword, this::setPassword, url.getPassword());
updatePropertyIfAbsent(this::getProtocol, this::setProtocol, url.getProtocol());
updatePropertyIfAbsent(this::getPort, this::setPort, url.getPort());
```

**Comment by icankeep** [comment]
&ready to close&
