### ISSUE TITLE
dubbo2.7.和2.5.x版本兼容问题

### ISSUE THREAD

**Issue by java-Learner-lx** [apache/dubbo#6400]
消费端泛化调用，dubbo的版本是2.7.5，服务端dubbo版本是2.5.3。消费端同步调用没问题，消费端异步调用，就会报错
`com.alibaba.dubbo.rpc.RpcException: Failed to invoke remote proxy method $invokeAsync to registry:`，求答案和解决方式

**Comment by chickenlj** [comment]
> $invokeAsync

不支持调用 2.5 低版本，请使用老的异步方式，即设置`ReferenceConfig.setAsync(true)`
