### ISSUE TITLE
元数据中心关于泛型的问题

### ISSUE THREAD

**Issue by czq080** [apache/dubbo#6405]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: xxx
* Java version: xxx

### question
 在dubbo2.7.7中，在查看元数据的过程中，发现对Collection的泛型进行了写入，但是自定义的泛型信息并没有写入，后面会有相关规划吗

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by beiwei30** [comment]
@czq080 这里的元数据，是指与服务测试相关的元信息吗？

**Comment by czq080** [comment]
> @czq080 这里的元数据，是指与服务测试相关的元信息吗？The metadata referred here, is it relevant to the helper information for service testing or generic invocation?
for example see below:
public class Example<T>{}  我目前了解到的只是对特定接口(像org.apache.dubbo.metadata.definition.builder.CollectionTypeBuilder)的做了处理，如果自定义的类信息，在元数据中是缺失的

**Comment by chickenlj** [comment]
moving to 2.7.10

**Comment by 15168326318** [comment]
> moving to 2.7.10

我2.7.12版本怎么自定义的泛型还是没有在元数据里啊

**Comment by 15168326318** [comment]
@czq080   dubbo 2.7.12版本，自定义的泛型还是没有在元数据里啊，你的可以了吗？
