### ISSUE TITLE
关于<dubbo:protocol>中的threads配置项默认数量200是经验值吗

### ISSUE THREAD

**Issue by fageiguanbing** [apache/dubbo#6410]
在 `文档的服务调用过程` 中的 `2.3.2.1 线程派发模型` 中看到对于iothreads的解释，比较清楚，我理解应算是计算密集型的线程数设置。

且两个线程池隔离开来是为了互不影响。

关于业务线程池的默认数量 `200`，我有个疑问：

对于IO密集型应用的线程数量设置为200会不会过多呢？这个是业界的经验值吗？

我的公式为：`IO密集型最佳线程数 =CPU 核数 * [ 1 +（I/O 耗时 / CPU 耗时）]`

**Comment by dongyinuo** [comment]
1. io 密集型, 200 个不多吧
2. 200 是不是业界经验值, 这个不太清楚, 比如 tomcat 默认的线程池 就是 200
3. 你的公示是如何来的?

**Comment by fageiguanbing** [comment]
> 1. io 密集型, 200 个不多吧
> 2. 200 是不是业界经验值, 这个不太清楚, 比如 tomcat 默认的线程池 就是 200
> 3. 你的公示是如何来的?

的确，tomcat的默认线程池是200，这方面有没有一个硬件标准呢？

公式是在极客时间上面看到的  https://time.geekbang.org/column/article/86666
