### ISSUE TITLE
关于针对dubbo spi扩展

### ISSUE THREAD

**Issue by SkillyZ** [apache/dubbo#6413]
我有个需求， spi扩展只想在日常预发环境加载， 不想在线上环境加载这个spi dubbo有解决方案吗？

**Comment by CodeIngL** [comment]
可以，你可以私聊我

**Comment by xiaoheng1** [comment]
可以看下 Activate 注解。

&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
You can refer in https://dubbo.apache.org/zh/docs/v2.7/dev/spi/#%E6%89%A9%E5%B1%95%E7%82%B9%E8%87%AA%E5%8A%A8%E6%BF%80%E6%B4%BB
