### ISSUE TITLE
2.7.6及后续版本中标签路由（TagRouter）行为不符合预期的问题

### ISSUE THREAD

**Issue by odirus** [apache/dubbo#6426]
- [✔ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [✔ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.  // FAT 显示404，望修正

### Environment

* Dubbo version: 2.7.6+
* Operating System version: macOS 10.14.5
* Java version: AdoptOpenJDK（1.8.0_222）

### Steps to reproduce this issue

1. 准备 consumer 和 provider 各一个服务
2. 启动 provider 的时候通过 "-Ddubbo.provider.tag=test" 指定标签
3. 启动 consumer 的时候不指定 Tag 参数，即使用默认值

### Expected Result

在官网文档 [路由规则](http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html) 最后一段是这样描述的：

`
request.tag未设置时，只会匹配tag为空的provider。即使集群中存在可用的服务，若 tag 不匹配也就无法调用，这与约定1不同，携带标签的请求可以降级访问到无标签的服务，但不携带标签/携带其他种类标签的请求永远无法访问到其他标签的服务。
`

也就是说 consumer 不指定 tag 的时候流量将不会到达 provider，因为 provider 是带了 tag 标记的

### Actual Result

实际上 consumer 是可以正常调用带tag标记的provider，这与文档中的描述不一致。在 2.7.5 中没有这个问题，根据我的排查，引入这个问题是由于增加了方法 org.apache.dubbo.registry.integration.RegistryDirectory#getConsumerUrl
```
    @Override
    public URL getConsumerUrl() {
        return this.overrideDirectoryUrl;
    }
```
2.7.5版本之前使用的是抽象类方法 org.apache.dubbo.rpc.cluster.directory#getConsumerUrl
```
    public URL getConsumerUrl() {
        return consumerUrl;
    }
```

经过 org.apache.dubbo.registry.integration.RegistryDirectory#mergeUrl 方法的处理之后，程序会把provider端的tag注入到属性 this.overrideDirectoryUrl中，因此 getConsumerUrl 方法返回的URL中就有了 tag 信息

请问这个问题是否会被修正呢？还是我们的用法不对？

**Comment by jianpeng957** [comment]
遇到的同样的问题！麻烦在新的版本修复下

**Comment by shuchaang** [comment]
同样遇到这个问题,想问一下是bug还是有意为之。

**Comment by hanlukk** [comment]
这个怎么样了， 感觉bug 每个版本都很多， 都不知道用哪个版本好咯

**Comment by zlm0125** [comment]
可以提供修复的小版本吗

**Comment by zlm0125** [comment]
2.7.7可以提供修复的小版本吗
