### ISSUE TITLE
支持直连模式下，在连接不可用时的快速失败

### ISSUE THREAD

**Issue by haiyang1985** [apache/dubbo#6443]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: macOS
* Java version: 1.8

### Steps to reproduce this issue

1. 服务端打开dubbo协议，并监听8080端口
2. 客户端通过dubbo作为代理，以直连的方式与服务端建立连接。
```
String url="dubbo://127.0.0.1:20880"
ReferenceConfig<DemoService> referenceConfig = new ReferenceConfig<>();
referenceConfig.setInterface(DemoService.class);
referenceConfig.setUrl(url);
```
3. 客户端跟服务端的网络出现问题，请求无法到达服务端。

原因：
为了避免并发请求重复创建线程，Netty在建连的时候时加锁的。
org.apache.dubbo.remoting.transport.netty.NettyClient
```
@Override
protected void doConnect() throws Throwable {
    long start = System.currentTimeMillis();
    ChannelFuture future = bootstrap.connect(getConnectAddress());
    try {
        boolean ret = future.awaitUninterruptibly(getConnectTimeout(), TimeUnit.MILLISECONDS);
        ...
    } finally {

    }
}
```

org.jboss.netty.channel.DefaultChannelFuture
```
private boolean await0(long timeoutNanos, boolean interruptable) throws InterruptedException {
    try {
        synchronized (this) {
            try {
                for (;;) {
                    try {
                        this.wait(waitTime / 1000000, (int) (waitTime % 1000000));
                    } catch (InterruptedException e) {
                       
                    }
                }
            } finally {
            }
        }
    } finally {
    }
}
```

从调用的堆栈中可以发现，在请求发送之前会检查当前连接是否可用，如果不可用就会重新建连。
假设同时进来了100个请求，第一个请求发现连接不可用需要重新建连，由于服务端不可达，就会一直持有连接的锁，直到3s超时之后才会释放锁。那么，第100个请求等待的时候就是100*3=300s，会导致线程被大量阻塞。
```
at org.apache.dubbo.remoting.transport.netty.NettyClient.doConnect(NettyClient.java:130)
at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:189)
at org.apache.dubbo.remoting.transport.AbstractClient.<init>(AbstractClient.java:71)
at org.apache.dubbo.remoting.transport.netty.NettyClient.<init>(NettyClient.java:59)
at org.apache.dubbo.remoting.transport.netty.NettyTransporter.connect(NettyTransporter.java:37)
at com.ctrip.framework.cdubbo.internal.delegate.CDubboTransporterDelegate.connect(CDubboTransporterDelegate.java:25)
at org.apache.dubbo.remoting.Transporter$Adaptive.connect(Transporter$Adaptive.java)
at org.apache.dubbo.remoting.Transporters.connect(Transporters.java:75)
at org.apache.dubbo.remoting.exchange.support.header.HeaderExchanger.connect(HeaderExchanger.java:39)
at org.apache.dubbo.remoting.exchange.Exchangers.connect(Exchangers.java:109)
at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.initClient(LazyConnectExchangeClient.java:83)
at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.request(LazyConnectExchangeClient.java:127)
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

对于直连模式，在出现服务端连接不可用的情况下，能够支持快速失败。

### Actual Result

对于直连模式，在出现服务端连接不可用的情况下，会导致线程阻塞。

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
After support send.reconnect is configurable, in lazy mode, you can do this to close and reconnect：
<dubbo:reference id="demoService" check="false"
                 interface="org.apache.dubbo.demo.DemoService"/>
                 interface="org.apache.dubbo.demo.DemoService" url="dubbo://127.0.0.1:20880" lazy="true">
    <dubbo:parameter key="send.reconnect" value="false"/>
</dubbo:reference>

**Comment by chickenlj** [comment]
我有一些疑问或需要确认的点，不论是直连或非直连模式，如果采用默认配置 `lazy="true"` `send.reconnect=true`，会发生什么行为：

第一次 request 时会执行链接建立，此时
* 如果建立链接成功。一切正常运行
* 如果建立链接失败。首先 request 调用会以 RemotingException 终止；而 LazyConnectExchangeClient 的状态如下：
```java
class LazyConnectExchangeClient {
    private boolean initialState = true;
    private Client client = null // 因为 client 创建以 RemotingException 终止了

  // 后续每次请求都会尝试 client 建连（client=null），因为 isConnected() 指示调用者可用
  private void initClient() throws RemotingException {
        if (client != null) {
            return;
        }
        if (logger.isInfoEnabled()) {
            logger.info("Lazy connect to " + url);
        }
        connectLock.lock();
        try {
            if (client != null) {
                return;
            }
            this.client = Exchangers.connect(url, requestHandler);
        } finally {
            connectLock.unlock();
        }
    }
    
  // 始终返回 initialState = true，告诉外围链接可用，实际上上一次建连失败了
   public boolean isConnected() {
        if (client == null) {
            return initialState; 
        } else {
            return client.isConnected();
        }
   }
}
```

我认为 LazyConnectExchangeClient 正常工作的情况应该是，第一次请求时尝试主动建连，后续依赖 ReconnectTask 建连，而不是一直重复建连。这意味着 LazyConnectExchangeClient 需要增加更多状态，可能的改法是：
* 第一次 request 尝试建立 client 链接，此时无论如何 client 实例都要生成，并根据client状态告知此次request结果，如决策是否抛出 RemotingException
* 后续 request。理论上来说后续 request 在 client 可用之前不会进来，因为此时 isConnected 能准确的反映 LazyClient 的连接状态。不论因为什么原因（如外围没做连接管理的高可用策略），如果 request 进入了一个当前不可用的 LazyClient，则可以依据 client 的状态快速失败（另一个选择是始终尝试建立链接，但我认为这样不太好）。

**Comment by CrazyHZM** [comment]
@chickenlj 
同意上述的改法，client不应该再通过是否为null来判断，应该根据它自身的状态来判断是否可用。
另外可以讨论一下当连接不可用时，每次请求还放进来建连的场景，也就是send.connect的应用场景。
