### ISSUE TITLE
一个 provider 上千个 consumer

### ISSUE THREAD

**Issue by lishuchao012** [apache/dubbo#6448]
请教大家一个问题， 我一个 provider 上千个 consumer 通过连 这个 provider 去操作数据可以么？ 考虑到数据库连接池数量限制，边缘侧不能直接连数据库，于是想在各个边缘侧的 consumer 连下 中心的 provider， 不知道可不可行，有没有数量限制

**Comment by cocodroid** [comment]
增加provider节点来分摊下负载
