### ISSUE TITLE
consumer parameter can not passed to provider side

### ISSUE THREAD

**Issue by Roronoa-Zoro** [apache/dubbo#6454]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: Mac
* Java version: jdk 1.8

### Steps to reproduce this issue

1. configure consumer in xml file
<dubbo:reference id="demoServieRpc" interface="com.aop.demo.demo.dubbo.DemoService" group="ceshi" retries="1">
        <dubbo:parameter key="hide" value="1" hide="true"/>
    </dubbo:reference>

public interface DemoService {
    String sayHello();
}

2. define a filter in provider side
@Activate(group = "provider")
public class HideParameterFilter implements Filter {
    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        String hide = invoker.getUrl().getParameter("hide");
        System.out.println("context" + RpcContext.getContext().getAttachment("hide"));
        System.out.println("隐式参数" + hide);
        return invoker.invoke(invocation);
    }
}
and we also create a file named "org.apache.dubbo.rpc.Filter" under META-INF/dubbo folder, and file content is
hideParameterFilter=com.aop.demo.demo.dubbo.HideParameterFilter

3. configure service in provider side
<dubbo:service interface="com.aop.demo.demo.dubbo.DemoService"
                   ref="demoService" executes="10" group="ceshi" filter="hideParameterFilter"/>

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
then consumer invode sayHello(), in provider side, hideParameterFilter should print 1.

### Actual Result

hideParameterFilter print null.

```
Just put your stack trace here!
```

**Comment by Roronoa-Zoro** [comment]
Guys, please help me figure it out, thanks a lot.

**Comment by DIscord010** [comment]
`<dubbo:parameter` is parameter configuration.
You can use `RpcContext.getContext().setAttachment("index", "1")` to implicitly pass parameters:
[http://dubbo.apache.org/en-us/docs/user/demos/attachment.html](url)

**Comment by leeey111** [comment]
I'm also confuse about the dubbo:parameter , it doesn't seem to work,
sometimes we don't want to use RpcContext explicitly, but want to configure extra-param through a configuration file.

**Comment by AlbumenJ** [comment]
> I'm also confuse about the dubbo:parameter , it doesn't seem to work,
> sometimes we don't want to use RpcContext explicitly, but want to configure extra-param through a configuration file.

Like @DIscord010  said `<dubbo:parameter>` is a parameter configuration, which is used by Dubbo to config RPC properties. It is the same like `retries` properties in `<dubbo:reference>`. The only way to pass implicit parameters is using `RpcContext.getContext().setAttachment`.

**Comment by leeey111** [comment]
> > I'm also confuse about the dubbo:parameter , it doesn't seem to work,
> > sometimes we don't want to use RpcContext explicitly, but want to configure extra-param through a configuration file.
> 
> Like @DIscord010 said `<dubbo:parameter>` is a parameter configuration, which is used by Dubbo to config RPC properties. It is the same like `retries` properties in `<dubbo:reference>`. The only way to pass implicit parameters is using `RpcContext.getContext().setAttachment`.

I get it now, thanks！👍
