### ISSUE TITLE
通配符的匹配很全面, 但无法找到元素 'dubbo:application' 的声明

### ISSUE THREAD

**Issue by hello-piper** [apache/dubbo#6468]
版本: alibaba dubbo 2.5.7

问题：dubbo-consumer.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 47; cvc-complex-type.2.4.c: 通配符的匹配很全面, 但无法找到元素 'dubbo:application' 的声明

但是我dubbo-consumer.xml是有<dubbo:application name="live-unionpay" />声明的

**Comment by c327812419** [comment]
我下午刚碰到这个问题，搞了半天，发现是pom.xml里没有引用dubbo的相关jar………………

**Comment by hello-piper** [comment]
> 我下午刚碰到这个问题，搞了半天，发现是pom.xml里没有引用dubbo的相关jar………………

我这边是因为 consumer.xml 里面 *dubbo.xsd文件访问不到导致
