### ISSUE TITLE
2.7.x的monitor监控中心如何搭建？

### ISSUE THREAD

**Issue by c327812419** [apache/dubbo#6469]
#5713 # Environment

* Dubbo version: 2.7.3
* Operating System version: win10，linux
* Java version: 1.8

2.7.x版本的monitor监控中心怎么搭建呢？2.5.x和2.6.x是在dubbo-simple\dubbo-monitor-simple目录下会生成监控中心的jar，直接运行就可以了。但是2.7.x没有dubbo-simple这个目录，网上也没有找到相应的文章。

劳烦大神告知下，谢谢！

**Comment by c327812419** [comment]
这么多天了，没有人回答。。。

**Comment by c327812419** [comment]
这么多天了，没有人回答。。。

**Comment by c327812419** [comment]
这么多天了，没有人回答。。。org.apache.dubbo.monitor.MonitorService这个类是在dubbo-monitor-api模块下面，但是这个模块下没有生成打包后的文件，真愁

**Comment by YangXueJun** [comment]
这都没人回答，不知道用dubbo-admin的master分支可不可以，可以试一下。国内开源不行啊

**Comment by IndiraFinish** [comment]
需要自己实现MonitorService，暴露这个服务。可以拿到一些简单的采集指标
