### ISSUE TITLE
dubbo-admin master 分支版本支持现在的dubbo最新版吗

### ISSUE THREAD

**Issue by YangXueJun** [apache/dubbo#6507]
dubbo-admin master 分支版本支持现在的dubbo最新版吗？
dubbo-admin 重构的develop版本有很多问题，老版dubbo-admin可以用吗
。

**Comment by oawang** [comment]
mark

**Comment by caichy** [comment]
dubbo monitor 也用不了了吧，感觉问题还很多，重构不完善不敢用在生产
