### ISSUE TITLE
Some code not follow the convention

### ISSUE THREAD

**Issue by lfzCarlosC** [apache/dubbo#6514]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue
remove the explicit type when assigning object
https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java#L532

https://github.com/apache/dubbo/blob/master/dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/RpcInvocation.java#L72

camel case:
https://github.com/apache/dubbo/blob/ba89f44f5aeddd2d06024232a15e355c2e8dc5cd/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/CallbackServiceCodec.java#L299
`callbackstatus `
Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
Would u like to help to submit a pull request to fix it.

**Comment by lfzCarlosC** [comment]
👍

**Comment by lfzCarlosC** [comment]
https://github.com/apache/dubbo/pull/6624
