### ISSUE TITLE
dubbo2.7.3 ，retries无效

### ISSUE THREAD

**Issue by gyjx** [apache/dubbo#6515]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: centos6.8
* Java version: 1.8

### Steps to reproduce this issue

@Reference(version = "${service.version}", methods = {@Method(name = "saveStuSegment", timeout = 30000, retries = -1)})

consumer配置 method 配置retries 无效

debug到下面这段代码，发现len还是3
public Result doInvoke(Invocation invocation, final List<Invoker<T>> invokers, LoadBalance loadbalance) throws RpcException {
        List<Invoker<T>> copyInvokers = invokers;
        checkInvokers(copyInvokers, invocation);
        String methodName = RpcUtils.getMethodName(invocation);
        int len = getUrl().getMethodParameter(methodName, RETRIES_KEY, DEFAULT_RETRIES) + 1;
        if (len <= 0) {
            len = 1;
        }

**Comment by gyjx** [comment]
public ReferenceBean(Reference reference) {
        super(reference);
    }


继续跟下去，发现这个构造方法没用到？

**Comment by gyjx** [comment]
@Override
    protected void postConfigureBean(AnnotationAttributes attributes, ReferenceBean bean) throws Exception {

        bean.setApplicationContext(applicationContext);

        configureInterface(attributes, bean);

        configureConsumerConfig(attributes, bean);

        configureMethodConfig(attributes, bean);

        bean.afterPropertiesSet();

    }

**Comment by gyjx** [comment]
请问这是2.7.3的bug码？

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
