### ISSUE TITLE
2.7版本rest服务在实现类指定@path时报错RESTEASY003130

### ISSUE THREAD

**Issue by jqncc** [apache/dubbo#6517]
### Environment
* Dubbo version: 2.7.6
* Java version: 1.8

### Steps to reproduce this issue
2.6版本时rest服务的路径@Path可以只在实现类指定,不需要在接口指定,这样保持接口的纯粹.

2.7必须指定在接口层否则报错:
RESTEASY003130: Class is not a root resource.  It, or one of its interfaces must be annotated with @Path

使用注解和xml配置都一样

**Comment by chickenlj** [comment]
这两种模式各有优劣吧，具体可详细阅读下原作者关于这部分设计的思考：
https://dangdangdotcom.github.io/dubbox/rest.html

**Comment by chickenlj** [comment]
如有进一步想法，可重新打开 issue

**Comment by jqncc** [comment]
问题不在谁优谁劣,而是现在根本不支持rest注解放在实现类里了. 原来低版本时是支持的, 升级后就会出现一堆错误
