### ISSUE TITLE
How to dynamically get provide for different group?

### ISSUE THREAD

**Issue by CodingFishWu** [apache/dubbo#6522]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: Mac OS
* Java version: 1.8
* Spring Boot 2.3.1.RELEASE

I'm in trouble how to dynamic find dubbo service providers.

Here is one example:

I have multiple implementations for the service, which is seperated by different group. But I don't how many groups at the begining. I want the consumer find the correct group from config center, and then I could change the config without modify any code or restart the application.

But I don't know how to use a dynamic service, or change the group of a service dynamically.

The only way I can find is using [ReferenceConfig](http://dubbo.apache.org/en-us/docs/user/demos/reference-config-cache.html) to find provider in api mode. But I prefer a configration way, which is more readable and maintainable.

**Comment by CodingFishWu** [comment]
Here is my example for API mode:
```
    /* Get Provider by group name */
        ReferenceConfig<ApiResolver> reference = new ReferenceConfig<>();
        reference.setInterface(ApiResolver.class);
        reference.setGroup(groupName);
        reference.setCheck(false);
        ReferenceConfigCache cache = ReferenceConfigCache.getCache();
        try {
            ApiResolver apiResolver = cache.get(reference);
            // Do something......
        }
        // Not Found, Or Error
        catch ( ConnectException | IllegalStateException | RpcException exception) {
        }
```

**Comment by guohao** [comment]
Instead of exporting multi-group providers, just try [Tag routing rules](http://dubbo.apache.org/en-us/docs/user/demos/routing-rule.html).

By the way, It's not a good design that one RPC interface has distinct implementations in same cluster.
