### ISSUE TITLE
设置 simplified 为true,导致服务不注册。

### ISSUE THREAD

**Issue by 15168326318** [apache/dubbo#6527]
因为simplified ,url的side参数没有。
   而服务自省需要根据这个来判断是否注册。

    protected boolean shouldRegister(URL providerURL) {
        String side = providerURL.getParameter("side");
        boolean should = "provider".equals(side);
        if (!should && this.logger.isDebugEnabled()) {
            this.logger.debug(String.format("The URL[%s] should not be registered.", providerURL.toString()));
        }

        return should;
    }
### Environment

* Dubbo version: 2.7.7
* Operating System version: xxx
* Java version: 1.8

**Comment by CrazyHZM** [comment]
shouldRegister only affect service discovery.

**Comment by CrazyHZM** [comment]
I think there is no problem. I will close the issue first. If there are other questions, I can reopen the issue.
