### ISSUE TITLE
2.7.8 默认ConfigCenter的group属性丢失

### ISSUE THREAD

**Issue by spilledyear** [apache/dubbo#6532]
# Environment
* Dubbo version: 2.7.8
* Java version: 1.8

### Steps to reproduce this issue
1. 应用使用dubbo2.7.8客户端，使用ZK作为注册中心   
<dubbo:registry protocol="zookeeper" address="localhost:2181" client="curator"/>

2. dubbo-admin 添加全局配置
dubbo.registry.simplified=true
dubbo.registry.extra-keys=isolate,zone

3. 启动应用，简化URL未生效

### Expected Result
我们期望通过外部化配置为所有客户端开启元数据中心和简化URL。因为配置中心数据比较少，所以我们使用了默认的配置中心，然后元数据中心和简化URL相关配置放在配置中心，因为每个客户端都已经配置了注册中心，这样就可以在客户端不做任何修改的前提下，为所有客户端开启元数据中心和简化URL功能

### Actual Result
配置中心未生效

自己调试时发现：在根据注册中心生成配置中心的时候，因为 RegistryConfig中的group属性默认为空，导致修改了 ConfigCenterConfig 的group属性的默认值(dubbo) ，所以读取配置的路径变成  /dubb/config/dubbo.properties， 实际上dubbo-admin 写配置的路径为  /dubb/config/dubb/dubbo.properties

### 尝试修改
在 DubboBootstrap#registryAsConfigCenter  方法中添加一个判断操作
```
        if(StringUtils.isNotEmpty(registryConfig.getGroup())){
            cc.setGroup(registryConfig.getGroup());
        }
```

经过验证，发现可以生效，是否提交一个PR？

**Comment by chickenlj** [comment]
```java
 if(StringUtils.isNotEmpty(registryConfig.getGroup())){
            cc.setGroup(registryConfig.getGroup());
        }
```

I think this patch can fix the issue you are facing, it would be great if you can submit a pull request.

**Comment by spilledyear** [comment]
> ```java
>  if(StringUtils.isNotEmpty(registryConfig.getGroup())){
>             cc.setGroup(registryConfig.getGroup());
>         }
> ```
> 
> I think this patch can fix the issue you are facing, it would be great if you can submit a pull request.

ok， i will  it
