### ISSUE TITLE
Dubbo 2.6.9 正式版Official Release计划什么时候发布？

### ISSUE THREAD

**Issue by Chenjp** [apache/dubbo#6537]
目前是Pre-Release，但现在HW形式严峻，是否可以明确2.6.9的正式发布时间？
我们现在对2.7.8和2.6.9的选择，还在犹豫中。

**Comment by qixiaobo** [comment]
2.6.9 release at 18 days ago
![image](https://user-images.githubusercontent.com/2881751/89282788-a030d680-d67e-11ea-91e5-ccf5c0b84dc8.png)

**Comment by Chenjp** [comment]
### 谢谢，已经看到没有Pre-Release标记了。

**Comment by chickenlj** [comment]
2.6.9 has just been released.
