### ISSUE TITLE
MonitorService 未能完全向下兼容

### ISSUE THREAD

**Issue by PromiseChan** [apache/dubbo#6541]
我司目前dubbo交易的监控采集，使用的是com.alibaba.dubbo.monitor.MonitorService,  URL 类采用com.alibaba.dubbo.common.URL

但迁移到2.7.8后，由于无法引入dubbo-compatible模块（dubbo-monitor-api 与 dubbo-compatible 存在循环依赖），因此只能手动把com.alibaba.dubbo.monitor.MonitorFactory 、com.alibaba.dubbo.monitor.Monitor、com.alibaba.dubbo.common.URL从dubbo-compatible 下移到dubbo-monitor-api 模块

请问官方后续能否调整位置

**Comment by CodeIngL** [comment]
用什么官方调整位置，使用https://github.com/open-wrapper/dubbo-wrapper，自己定制

**Comment by chickenlj** [comment]
能进一步解释下 `dubbo-monitor-api 与 dubbo-compatible 存在循环依赖` 循环依赖产生的原因么？

**Comment by chickenlj** [comment]
未能定位，请回复并打开
