### ISSUE TITLE
how does dubbo specific serialization type in annotation base on dubbo 2.7.7 

### ISSUE THREAD

**Issue by taojintianxia** [apache/dubbo#6545]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: macOS
* Java version: 1.8u251

as I use dubbo spring boot ,  just wonder how to specify the serialization type like kryo or protobuff in `@DubboService` annotation ?

**Comment by MessianicZZQ** [comment]
@DubboService annotations may really don't support serialization，it this ok?

@Bean
    public ProtocolConfig protocolConfig(){
        ProtocolConfig protocolConfig = new ProtocolConfig();
        protocolConfig.setSerialization("kryo");
        // ...other config 
        return protocolConfig;
    }

**Comment by taojintianxia** [comment]
> @DubboService annotations may really don't support serialization，it this ok?
> 
> @bean
> public ProtocolConfig protocolConfig(){
> ProtocolConfig protocolConfig = new ProtocolConfig();
> protocolConfig.setSerialization("kryo");
> // ...other config
> return protocolConfig;
> }

thx for your reply , I see this usage , but how do we set serialization type for a specific service？
for example , I have to services , serviceA, service B . 
I want serviceA use protobuf  and service B use json as serilization.
