### ISSUE TITLE
hessian协议回声测试报错，提示Not found method "$echo" in class com.example.service.HkService.

### ISSUE THREAD

**Issue by 15168326318** [apache/dubbo#6552]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue
1.
    @DubboReference(check = false, protocol = "hessian")
    private HkService hkService;
2.
        EchoService echoService = (EchoService) hkService;
        Object oj = echoService.$echo("成立");

### Expected Result

 ok

### Actual Result
org.apache.dubbo.common.bytecode.NoSuchMethodException: Not found method "$echo" in class com.example.service.HkService.
	at org.apache.dubbo.common.bytecode.Wrapper2.invokeMethod(Wrapper2.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	at org.apache.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:113)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:163)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:52)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at com.alibaba.dubbo.rpc.Invoker$CompatibleInvoker.invoke(Invoker.java:55)
	at io.seata.integration.dubbo.alibaba.AlibabaDubboTransactionPropagationFilter.invoke(AlibabaDubboTransactionPropagationFilter.java:43)
	at com.alibaba.dubbo.rpc.Filter.invoke(Filter.java:29)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at io.seata.integration.dubbo.ApacheDubboTransactionPropagationFilter.invoke(ApacheDubboTransactionPropagationFilter.java:65)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at co.faao.plugin.filter.ConsumerExceptionFilter.invoke(ConsumerExceptionFilter.java:28)

**Comment by iochenlei** [comment]
假设我们有一个DemoService接口，该接口定义如下：

```java

public interface DemoService {
    String sayHello(String name);

    long timestamp();

    String getThreadName();

    int getSize(String[] strs);

    int getSize(Object[] os);

    Object invoke(String service, String method) throws Exception;

    int stringLength(String str);

    Type enumlength(Type... types);

//	Type enumlength(Type type);

    String get(CustomArgument arg1);

    byte getbyte(byte arg);

    String complexCompute(String input, ComplexObject co);

    ComplexObject findComplexObject(String var1, int var2, long l, String[] var3, List<Integer> var4, ComplexObject.TestEnum testEnum);
}
```

当使用Hessian协议时，给消费者使用的Invoker会通过org.apache.dubbo.rpc.protocol.AbstractProxyProtocol#protocolBindingRefer方法创建。

protocolBindingRefer方法的默认实现会通过ProxyFactory动态创建Invoker：

```java
final Invoker<T> target = proxyFactory.getInvoker(doRefer(type, url), type, url);
```

上面的代码会：

1. 调用org.apache.dubbo.rpc.protocol.hessian.HessianProtocol#doRefer方法，返回的结果是DemoService接口的一个代理(功能是把该实例上发生的方法调用通过RPC发送给服务提供者)。

2. 把1的结果传给proxyFactory.getInvoker()方法，下面主要看这个方法是怎么实现的。

ProxyFactory的默认使用的实现类是JavassistProxyFactory，这个类通过Javassist为Invoker生成的代码如下：

````java
    public Object invokeMethod(Object o, String n, Class[] p, Object[] v) throws java.lang.reflect.InvocationTargetException {
        org.apache.dubbo.service.DemoService w;
        try {
            w = ((org.apache.dubbo.service.DemoService) $1);
        } catch (Throwable e) {
            throw new IllegalArgumentException(e);
        }
        try {
            if ("invoke".equals($2) && $3.length == 2) {
                return ($w) w.invoke((java.lang.String) $4[0], (java.lang.String) $4[1]);
            }
            if ("get".equals($2) && $3.length == 1) {
                return ($w) w.get((org.apache.dubbo.service.CustomArgument) $4[0]);
            }
            if ("timestamp".equals($2) && $3.length == 0) {
                return ($w) w.timestamp();
            }
            if ("getSize".equals($2) && $3.length == 1 && $3[0].getName().equals("[Ljava.lang.Object;")) {
                return ($w) w.getSize((java.lang.Object[]) $4[0]);
            }
            if ("getSize".equals($2) && $3.length == 1 && $3[0].getName().equals("[Ljava.lang.String;")) {
                return ($w) w.getSize((java.lang.String[]) $4[0]);
            }
            if ("getbyte".equals($2) && $3.length == 1) {
                return ($w) w.getbyte(((Byte) $4[0]).byteValue());
            }
            if ("sayHello".equals($2) && $3.length == 1) {
                return ($w) w.sayHello((java.lang.String) $4[0]);
            }
            if ("getThreadName".equals($2) && $3.length == 0) {
                return ($w) w.getThreadName();
            }
            if ("enumlength".equals($2) && $3.length == 1) {
                return ($w) w.enumlength((org.apache.dubbo.service.Type[]) $4[0]);
            }
            if ("stringLength".equals($2) && $3.length == 1) {
                return ($w) w.stringLength((java.lang.String) $4[0]);
            }
            if ("complexCompute".equals($2) && $3.length == 2) {
                return ($w) w.complexCompute((java.lang.String) $4[0], (org.apache.dubbo.service.ComplexObject) $4[1]);
            }
            if ("findComplexObject".equals($2) && $3.length == 6) {
                return ($w) w.findComplexObject((java.lang.String) $4[0], ((Number) $4[1]).intValue(), ((Number) $4[2]).longValue(), (java.lang.String[]) $4[3], (java.util.List) $4[4], (org.apache.dubbo.service.ComplexObject$TestEnum) $4[5]);
            }
        } catch (Throwable e) {
            throw new java.lang.reflect.InvocationTargetException(e);
        }
        throw new org.apache.dubbo.common.bytecode.NoSuchMethodException("Not found method \"" + $2 + "\" in class org.apache.dubbo.service.DemoService.");
    }
```

可以看出，凡是在DemoService接口中声明的方法都被转发给了w（上面调用HessianProtocol#doRefer方法锁返回的结果)，对于DemoService接口中没声明的方法就抛出NoSuchMethodException异常(比如EchoService接口的$echo方法)。

还可以看出，抛出NoSuchMethodException异常是消费者自己的行为。在异常发生时未发生RPC请求。

另外有趣的是AbstractProtocol的一些子类重载了protocolBindingRefer方法，使用自定义的逻辑创建Invoker，而有一些子类则没有。

例如，下面这些类重载了该方法：
+ DubboProtocol
+ GrpcProtocol
+ InjvmProtocol
+ MemcachedProtocol
+ RedisProtocol
+ ThriftProtocol

而下面这些类没有对该方法进行重载：

+ HessianProtocol
+ HttpProtocol

根据我自己的测试，在使用Dubbo和Injvm协议时调用EchoService的$echo方法不会抛出异常。而使用Hessian或者Http协议会抛出NoSuchMethodException异常。

**Comment by beiwei30** [comment]
For all impls of org.apache.dubbo.rpc.protocol.AbstractProxyProtocol, the priority of supporting 'echo' is low. I also spent time today to look into how it's possible to support it for HessianProtocol and HttpProtocol, and I realize the efforts may be large, and it is unnecessary. After all, our major protocol is dubbo2 and in the future it is dubbo3.

My conclusion is: All AbstractProxyProtocol's impls don't support 'echo' today, and we don't have plan to support it.

**Comment by iochenlei** [comment]
Currently, can the end users get some notes about what you said in the documentation?
