### ISSUE TITLE
关于测试用例的建议

### ISSUE THREAD

**Issue by smipo** [apache/dubbo#6562]
最近在学习dubbo注册中心，想从测试用例开始，但是发现一个问题，大佬们修复的bug，很少有建立起对应的测试用例，比如 #5930（没有冒犯的意思），修复完成之后，无法从测试用例获取验证是否修复成功 。希望大佬们能多多补充测试用例。

**Comment by chickenlj** [comment]
That's an important part that we should do better in the futre. It would be appreciated if you can help to improve them.
