### ISSUE TITLE
dubbo + nacos slow start, cache Nacos registry instance failure, create a large number of threads

### ISSUE THREAD

**Issue by lijiaxing3045354** [apache/dubbo#6568]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Java version: 1.8

### Steps to reproduce this issue

In the process of switching Zookeeper to Nacos, we found that the startup speed of the application became slower, and a large number of Nacos threads were created. Looking at the source code, we found that every service registered in the application startup process would create a **NamingService**. We started to think that was the design. After a thorough review, we found that Dubbo had a static cache for the Nacos registry, and the cache key contained a dynamic parameter timestamp , every time a new service is registered, the latest value will be retrieved, and eventually the registry static cache will be invalid.
![image](https://user-images.githubusercontent.com/39329138/89625727-ea0dfc80-d8ca-11ea-8474-2fc24b0f6c47.png)

请大佬帮忙看看，多谢！

```
Just put your stack trace here!
```

**Comment by lijiaxing3045354** [comment]
I found the problem，NacosRegistryFactory override the method createRegistryCacheKey,return full url.
`public class NacosRegistryFactory extends AbstractRegistryFactory {

    @Override
    protected String createRegistryCacheKey(URL url) {
        return url.toFullString();
    }

    @Override
    protected Registry createRegistry(URL url) {
        return new NacosRegistry(url, createNamingService(url));
    }
}`

**Comment by JasonMing** [comment]
Too many threads may hang up the register/subscribe operations.
I found 3000+ nacos threads in my process, and the service list can never refresh again.
