### ISSUE TITLE
why consumer url not register and unregister to consul?

### ISSUE THREAD

**Issue by gaoxinge** [apache/dubbo#6569]
I wonder why consumer url not register and unregister to consul:

https://github.com/apache/dubbo/blob/afbf7d5171736dafba56bad7dcb664f1f2ce480e/dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java#L102-L104

https://github.com/apache/dubbo/blob/afbf7d5171736dafba56bad7dcb664f1f2ce480e/dubbo-registry/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/ConsulRegistry.java#L120-L122

And this issue is duplicated to https://github.com/apache/dubbo/issues/6147.

**Comment by chickenlj** [comment]
I think it's by design.  The Consul console has provided the statistics of the listening consumer instances?
