### ISSUE TITLE
Dubbo can only support one timeout in an application

### ISSUE THREAD

**Issue by qixiaobo** [apache/dubbo#6580]
### Environment

* Dubbo version: 2.6.X
* Operating System version: *nix
* Java version: 1.8+
### Feature Required

A very usual scene is that the consumer would call the provider with different timeout or retry or other settings.
But as far as  I know, dubbo put this param in the url in the register center. So an application can only has one timeout or other settings.
For example, I call a method  which will do a batch job , I can only set a very large timeout .(I see I can make a lot of method to spilt to different size)
In my scene,I will explode a service  named GenericApi which has one method callInnerService. I will call genericService to call my inner dubbo service.
But I faced a problem, even if I can get a reference ,but I can only set one timeout . A lot of front end apps will pass different timeouts in the same method.(I don't want to make different reference instances)
How to deal with this scene?

**Comment by Jaskey** [comment]
This is a good question

**Comment by CrazyHZM** [comment]
The new version already supports method-level timeout configuration.
