### ISSUE TITLE
Does dubbo cannot register mutli versions with same  interface in one service(application)?

### ISSUE THREAD

**Issue by chutian52** [apache/dubbo#6585]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: linux
* Java version: 8

### Steps to reproduce this issue

1. define a interface `com.demo.api.DemoService`
2. implements `com.demo.api.DemoService` with version (1.0) 
3. implements `com.demo.api.DemoService` with versiono (1.1)

### Expected Result

version 1.0 and 1.1 can be found .

### Actual Result

only 1.0 can be found.

Does Dubbo means application level registry?

**Comment by zhvqee** [comment]
see org.apache.dubbo.config.context.ConfigManager#addIfAbsent() method 。
 it get key by getId(config);.Different versions of the interface return the same interface name as key.
i think it's bug

**Comment by chutian52** [comment]
@zhvqee I know. but I see dubbo will register as application-level(like microservices). Is that reason ?

**Comment by AlbumenJ** [comment]
It works on 2.7.8 version. You can try upgrade to 2.7.8.

**Comment by chutian52** [comment]
@AlbumenJ It seems dubbo rewrite method implement for fix this.I'll try later, thanks.
@zhvqee Thanks
