### ISSUE TITLE
Dubbo多虚拟网卡情况下 怎么配置消费者指定真实ip

### ISSUE THREAD

**Issue by wxywizard** [apache/dubbo#6588]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: v2.7.6
* Operating System version: window10
* Java version: 1.8

### Steps to reproduce this issue

1. 本机存在多个虚拟网卡
2. 采用nacos注册中心，服务提供者配置dubbo.protocol.host之后可以注册本地真实ip但是服务消费者一直找不到这个提供者
3. 禁用虚拟网卡后一切都会好
尝试启动参数也无效
-DDUBBO_IP_TO_BIND和DDUBBO_IP_TO_REGISTRY在idea中vm options 配置都没有效果

**Comment by mercyblitz** [comment]
Please use `-Ddubbo.network.interface.preferred=${your-network-interface-name}` to filter network interface what you want.

**Comment by 598572** [comment]
如果确实就想在application.ymal文件中配 那么在启动时 拦截到ymal文件中的配置 然后通过 
 System.setProperty(DUBBO_PREFERRED_NETWORK_INTERFACE_CONSTANT, preferredInterface);
System.setProperty(DUBBO_NETWORK_IGNORED_INTERFACE_CONSTANT, ignoredInterface);
设置到系统变量中去，也是一个可行的方法，亲测有效，这里给出代码：

public class DubboNetworkInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

    private static final String DUBBO_PREFERRED_NETWORK_INTERFACE_CONSTANT = "dubbo.network.interface.preferred";
    private static final String DUBBO_NETWORK_IGNORED_INTERFACE_CONSTANT = "dubbo.network.interface.ignored";

    @Override
    public void initialize(ConfigurableApplicationContext applicationContext) {
        String preferredInterface = applicationContext.getEnvironment().getProperty(DUBBO_PREFERRED_NETWORK_INTERFACE_CONSTANT);
        String ignoredInterface = applicationContext.getEnvironment().getProperty(DUBBO_NETWORK_IGNORED_INTERFACE_CONSTANT);

        if (StringUtils.isNotBlank(preferredInterface)) {
            System.setProperty(DUBBO_PREFERRED_NETWORK_INTERFACE_CONSTANT, preferredInterface);
        }
        if (StringUtils.isNotBlank(ignoredInterface)) {
            System.setProperty(DUBBO_NETWORK_IGNORED_INTERFACE_CONSTANT, ignoredInterface);
        }
    }
}


启动类上：

public static void main(String[] args) {
        SpringApplication application = new SpringApplication(IMConnectServiceApplication.class);
        application.addInitializers(new DubboNetworkInitializer());
        application.run(args);
    }
