### ISSUE TITLE
maven-remote-resources-plugin:1.7.0 miss ExtendedProperties

### ISSUE THREAD

**Issue by WeifengFan** [apache/dubbo#6596]
Mac jdk:1.8

mvn clean install

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:process (process-resource-bundles) on project dubbo-common: Execution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:process failed: A required class was missing while executing org.apache.maven.plugins:maven-remote-resources-plugin:1.7.0:process: org/apache/commons/collections/ExtendedProperties

**Comment by WeifengFan** [comment]
in master branch

**Comment by 85668869** [comment]
Did you solve it? I also encountered this problem

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
