### ISSUE TITLE
ApplicationModel.getConfigManager().getReferences().size()永远为0，getServices()正常

### ISSUE THREAD

**Issue by 15168326318** [apache/dubbo#6600]
我想知道项目中有多少消费端和服务端，
ApplicationModel.getConfigManager().getReferences().size()这个永远为0

ApplicationModel.getConfigManager().getServices().size()这个是正常的服务端个数。

**Comment by zhvqee** [comment]
ApplicationModel.getConfigManager().getReferences(), 其实是从缓存拿到，key为"reference",是通过 addConfig方法添加，但是在dubbo启动的时候就没有去添加服务的引用。ApplicationModel.getConfigManager() 能拿到的内容如下：
"registry" 
"protocol"  
"application"  
"provider" 
"service"  
"module"  
"monitor" 
"metrics"  
"metadata-report" - 
"ssl"  
"consumer" - 
"config-center"

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
