### ISSUE TITLE
2.7.8，服务自省, 服务端重启后，消费端不能自动连接。

### ISSUE THREAD

**Issue by 15168326318** [apache/dubbo#6601]
* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: 1.8

((BackgroundPathable)this.curatorFramework.getChildren().usingWatcher(watcher)).forPath(path);

感觉这样增加的监听器只会执行一次，应该用PathChildrenCache这个对象吧。

**Comment by manzhizhen** [comment]
Can you give me which class？ I can find this code

**Comment by LYDXY** [comment]
我也遇到了 , 我只有一个服务 , 一个消费, 每次 服务重启, 消费者 就无法 找到服务了

**Comment by LYDXY** [comment]
难道是版本问题, 我的也是 2..7.8

**Comment by 15168326318** [comment]
有发现是什么问题吗 ？2.7.9版本是不是已经修改好了

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
