### ISSUE TITLE
客户端无法切换集群容错策略

### ISSUE THREAD

**Issue by tfwx** [apache/dubbo#6602]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: xxx
* Java version: 1.8

dubbo 2.7.6 版本和之后的版本，当使用 @Reference 注解修改 cluster 属性切换集群容错策略时，发现始终不生效，一直使用默认的 failover 策略。当使用 2.7.5 版本时，修改生效。

看了一下 RegistryDirectory.getUrl 方法的代码，发现从 2.7.6 版本开始，getUrl 返回的 url 为 RegistryDirectory 构造函数中传入的 url，在 2.7.5 版本中 getUrl 方法返回的是 overrideDirectoryUrl。overrideDirectoryUrl 中包含了用户设置的参数，而 url 中没有，导致无法切换集群容错策略。

**Comment by tianshuang** [comment]
Same problem.

**Comment by qiuzhihui1990** [comment]
遇到了同样的问题！！

**Comment by qiuzhihui1990** [comment]
> 遇到了同样的问题！！

升级到2.7.8版本，就ok了，感谢 @tfwx

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
