### ISSUE TITLE
源码中感到疑惑的地方

### ISSUE THREAD

**Issue by zhongxiongzeng** [apache/dubbo#6634]
- [✔ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ✔] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3
* Operating System version: win10
* Java version: 12.0.2

### Steps to reproduce this issue

1. 我在阅读ReferenceBean这一部分代码的时候，我注意到这个类实现了FactoryBean，ApplicationContextAware，InitializingBean，DisposableBean方法，这些都是Sping IOC对Bean功能增强提供的接口，期初我以为ReferenceBean也属于Spring IOC管理，然而我在Beanfactory中并没有找到任何ReferenceBean的痕迹。
2. 后来我发现这些功能增强的接口并不是有IOC调用了，而是由dubbo代码对其调用。
3. 我觉得这个地方迷惑性很大，请问这里刻意这么设计的原因是希望读者像理解Spring Bean一样理解ReferenceBean吗？还是有其他原因？希望管理员能从想法，设计方面给予回答，谢谢。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
设计时的想法与初衷

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by moonlight035** [comment]
xml配置是走的spring吧
