### ISSUE TITLE
Dubbo协议下如何关闭Telnet

### ISSUE THREAD

**Issue by jianpeng957** [apache/dubbo#6646]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Centos7
* Java version: openjdk1.8+

### Steps to reproduce this issue

看了以前18年的提及的issue，但是没看到很好的解决方法，官网提供的解决方案是通过telnet参数限制命令数量，但是还是希望能够做到直接关闭telnet功能，不知道还有什么方式能够做到

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by puzeyu** [comment]
可以考虑直接把telnet的包删掉

**Comment by AlbumenJ** [comment]
Already removed
