### ISSUE TITLE
junit: org.apache.dubbo.rpc.RpcException: No servlet context found. If you are using server='servlet', make sure that you've configured org.apache.dubbo.remoting.http.servlet.BootstrapListener in web.xml

### ISSUE THREAD

**Issue by abelli85** [apache/dubbo#6647]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: Ubuntu 20.04
* Java version: openjdk 1.8.0_265

### Steps to reproduce this issue

1. create a rest service
2. configure dubbo service as rest via servlet
3. create junit test with annotation
4. run junit tests, the first junit test will fail but the following tests run fine.

Pls. provide [GitHub address] to reproduce this issue.
https://github.com/abelli85/meterEff/blob/master/meff/src/test/kotlin/com/abel/bigwater/impl/CodeServiceImplTest.kt

### Expected Result
configuration for dubbo-rest via servlet:
```
<dubbo:protocol name="rest" port="8080" threads="500" contextpath="meff" server="servlet" accepts="500"
...
```

here's junit test class:
```
// create junit test class with annotation
@ContextConfiguration(locations = ["classpath:/spring/rest-provider.xml", "classpath:/spring-mybatis.xml"])
@RunWith(SpringJUnit4ClassRunner::class)
class CodeServiceImplTest {
  @Test
  fun test1() {
    // ...
  }
  
  @Test
  fun test2() {
    //...
  }
...
```

What do you expected from the above steps？
all junit tests including the first SHOULD run fine.

### Actual Result

What actually happens?
the first junit test in the list always FAILS.

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
Caused by: org.apache.dubbo.rpc.RpcException: No servlet context found. If you are using server='servlet', make sure that you've configured org.apache.dubbo.remoting.http.servlet.BootstrapListener in web.xml
	at org.apache.dubbo.rpc.protocol.rest.DubboHttpProtocolServer.doStart(DubboHttpProtocolServer.java:62)
```
### Comments:
seems that **web.xml** is loaded lazily during junit tests, so first junit test fails.

**Comment by yuxiao97** [comment]
You can add webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT on @SpringBootTest annotation try again.

**Comment by yuxiao97** [comment]
> You can add webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT on @SpringBootTest annotation try again.

If not worked yet, use JavaConfig and application config but xml.

**Comment by abelli85** [comment]
emmm, seems the above solutions do not work. so i just preload mock servlet context without intruding dubbo sources (maybe looks some ugly):
```
        @BeforeClass
        @JvmStatic
        fun addServletContext() {
            ServletManager.getInstance().addServletContext(ServletManager.EXTERNAL_SERVER_PORT, MockServletContext())
        }
```
