### ISSUE TITLE
invoker为啥不删除？

### ISSUE THREAD

**Issue by huanghuaquan** [apache/dubbo#6658]
我们项目用了dubbo+nacos，部署用了k8s。因为用k8s重新发布服务的时候会生成新的IP地址，旧的IP服务就没有了。dubbo检测到有新的服务，在invokers里面就会添加，但是不会去删除旧的invoker，导致刚开始启动的时候还会去调旧的服务，会报错。还有就是netty会去心跳检测，会报一堆timeout的错误。为啥这个invokers不删除呢？

**Comment by lapple06** [comment]
应该是会删除的。RegistryDirectory实现了NotifyListener类，当收到服务变更通知的时候会触发。
具体的清除逻辑见方法com.alibaba.dubbo.registry.integration.RegistryDirectory#refreshInvoker，里面调用了
destroyUnusedInvokers方法销毁无用的Invoker
