### ISSUE TITLE
dubbo是否存在自动注册服务功能？

### ISSUE THREAD

**Issue by 1076572358** [apache/dubbo#6663]
假设以下场景
zookeeper挂掉了，服务消费者还能通过本地缓存消费服务生产者。将zookeeper里面的节点缓存文件删除掉，重新启动zookeeper，里面的服务提供者节点全部没有了，这个时候好像只能重新启动服务提供者才行。所以想问下是否存在服务在zookeeper挂了后会定时检测和注册上去的功能。

**Comment by CrazyHZM** [comment]
Already supported.
