### ISSUE TITLE
[dubbo元数据dataId]dubbo元数据dataId如何指定格式

### ISSUE THREAD

**Issue by tttmmiao** [apache/dubbo#6664]
dubbo配置中心, dataId默认是应用名. 
通过哪项配置, 可以将dataId设置为 com.cz.reverse.api.facade.TestFacade:1.0.0.DEV:dubbo:provider:xx-reverse 这种格式

**Comment by AlbumenJ** [comment]
元数据是 Dubbo 自己配置的，无法进行修改的

**Comment by tttmmiao** [comment]
dataId的确是dubbo自己配置的, 当dataId不正确时, 去debug上传数据的接口. 
该问题的原因是: nacos bug, 导致上传数据异常, 上传到配置中心的数据也不正确.
