### ISSUE TITLE
dubbo 升级到2.7.8 报 dto must implement Serializable 

### ISSUE THREAD

**Issue by yangxuqiang1111** [apache/dubbo#6672]
dubbo 升级到2.7.8 报 dto must implement Serializable，在2.7.7及以前版本 我们通过  Hessian2SerializerFactory.SERIALIZER_FACTORY.setAllowNonSerializable(true);这样解决的，在最新版本应该如何？

**Comment by DIscord010** [comment]
`SERIALIZER_FACTORY` is moved to `AbstractHessian2FactoryInitializer`.

**Comment by chickenlj** [comment]
Please try `Hessian2FactoryInitializer.getInstance().getSerializerFactory()`

The compatibility of inner implementations is not guaranteed.

**Comment by yangxuqiang1111** [comment]
> Please try `Hessian2FactoryInitializer.getInstance().getSerializerFactory()`
> 
> The compatibility of inner implementations is not guaranteed.

有通用的解决方法吗？
