### ISSUE TITLE
dubbo泛化调用完成时，调用reference.destroy()后，com.alibaba.dubbo.common.URL依然没有回收

### ISSUE THREAD

**Issue by robin977** [apache/dubbo#6676]
测试场景：
public  void  run(String addr,String targetMethod,String className,String version) {  
           GenericService object=null;
           ApplicationConfig applicationConfig=new ApplicationConfig("job-consumer-application");
         RegistryConfig registryConfig=new RegistryConfig();
         registryConfig.setAddress(addr);
         registryConfig.setProtocol("zookeeper");
         applicationConfig.setRegistry(registryConfig);
         ReferenceConfig<GenericService> reference = new ReferenceConfig();
         reference.setApplication(applicationConfig);
         reference.setRegistry(registryConfig);
          reference.setGeneric(true);
          reference.setInterface(targetObject);
          reference.setVersion(version);
          reference.setCheck(false);
          object=reference.get();
          Object result=null;
        try {
             result=  object.$invoke(targetMethod, parameterTypes, args);
        } catch (Throwable e) {
           e.printStackTrace();
        }finally {
            reference.destroy();
        }
}
此方法调用后，com.alibaba.dubbo.common.URL依然没有回收
AbstractRegistry的ConcurrentMap<URL, Map<String, List<URL>>> notified，这个集合没有remove操作，所以它一直在涨
![image](https://user-images.githubusercontent.com/8486672/91825786-4fa59c80-ec6f-11ea-9705-e9e5d554c3a2.png)

**Comment by manzhizhen** [comment]
let me see
