### ISSUE TITLE
Dubbo qos command not work to  offline provider 

### ISSUE THREAD

**Issue by qixiaobo** [apache/dubbo#6680]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.X
* Operating System version: *nix
* Java version: 1.8

### Steps to reproduce this issue

1. use provider to provide dubbo group
2. not set dubbo group for specify service
3. enable qos port
4. connect to qos port execute offline command
5. the specify service not offline

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

the specify service should offline

### Actual Result

the specify service not offline

**Comment by qixiaobo** [comment]
I found this code below
```java
public String getUniqueServiceName() {
        StringBuilder buf = new StringBuilder();
        if (group != null && group.length() > 0) {
            buf.append(group).append("/");
        }
        buf.append(interfaceName);
        if (version != null && version.length() > 0) {
            buf.append(":").append(version);
        }
        return buf.toString();
    }
```
But in fact if we use a default group (in provider) , so we get a group null here

In offline command
```java
private boolean isReg(String serviceUniqueName) {
        Set<ProviderInvokerWrapper> providerInvokerWrapperSet = ProviderConsumerRegTable.getProviderInvoker(serviceUniqueName);
        for (ProviderInvokerWrapper providerInvokerWrapper : providerInvokerWrapperSet) {
            if (providerInvokerWrapper.isReg()) {
                return true;
            }
        }

        return false;
    }
```
```java
public static void registerProvider(Invoker invoker, URL registryUrl, URL providerUrl) {
        ProviderInvokerWrapper wrapperInvoker = new ProviderInvokerWrapper(invoker, registryUrl, providerUrl);
        String serviceUniqueName = providerUrl.getServiceKey();
        Set<ProviderInvokerWrapper> invokers = providerInvokers.get(serviceUniqueName);
        if (invokers == null) {
            providerInvokers.putIfAbsent(serviceUniqueName, new ConcurrentHashSet<ProviderInvokerWrapper>());
            invokers = providerInvokers.get(serviceUniqueName);
        }
        invokers.add(wrapperInvoker);
    }
```
So the serviceUniqueName just use url to build 
```java
public String getServiceKey() {
        String inf = getServiceInterface();
        if (inf == null) return null;
        StringBuilder buf = new StringBuilder();
        String group = getParameter(Constants.GROUP_KEY);
        if (group != null && group.length() > 0) {
            buf.append(group).append("/");
        }
        buf.append(inf);
        String version = getParameter(Constants.VERSION_KEY);
        if (version != null && version.length() > 0) {
            buf.append(":").append(version);
        }
        return buf.toString();
    }
```
It's in different way .So this command may fail to work

**Comment by puzeyu** [comment]
Is the QoS of an offline provider always 0?

**Comment by qixiaobo** [comment]
> Is the QoS of an offline provider always 0?

Yeah  because of the default group

**Comment by ppzzyy11** [comment]
> > Is the QoS of an offline provider always 0?
> 
> Yeah because of the default group

There may be no such need to get the QoS of an offline provider,

**Comment by qixiaobo** [comment]
> > > Is the QoS of an offline provider always 0?
> > 
> > 
> > Yeah because of the default group
> 
> There may be no such need to get the QoS of an offline provider,

You may misUnderstand. We need offline an online provider . So the dubbo code gives no providers to offline. It's just a bug to fix

**Comment by AlbumenJ** [comment]
close #6680 via #6683
