### ISSUE TITLE
Dubbo脚手架内部服务器错误

### ISSUE THREAD

**Issue by LiuShuKu** [apache/dubbo#6682]
http://start.dubbo.io/  无法正常访问

**Comment by htynkn** [comment]
same issue reported by another issue：https://github.com/apache/dubbo-website/issues/603

@beiwei30

**Comment by hengyunabc** [comment]
因为上游spring的api返回了新版本号，以前的 https://github.com/thubbo/initializr 代码解析出错了。

---

可以先用这个网站生成工程： https://start.aliyun.com/bootstrap.html

**Comment by hengyunabc** [comment]
网站提示已更新，网站代码也更新了： https://github.com/thubbo/initializr
