### ISSUE TITLE
No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config

### ISSUE THREAD

**Issue by dengchanglu** [apache/dubbo#6687]
https://gitee.com/psplp/market
代码工程
运行时候报错：
No application config found or it's not a valid config! Please add <dubbo:application name="..." /> to your spring config
jdk1.8
windows10
idea2020

**Comment by dengchanglu** [comment]
dubbo 版本 2.7.5 2.7.6 2.7.7 都试过

**Comment by dengchanglu** [comment]
第三方 mybatis封装的包 有问题

**Comment by yuxiao97** [comment]
> 第三方 mybatis封装的包 有问题

什么问题，说说看

**Comment by Uniman-Su** [comment]
mybatis-spring-boot-autoconfigure引入后就有这个问题，我用得2.7.6同样有这个问题。

**Comment by dengchanglu** [comment]
我同事引用了一个自动创建mapp文件的mybatis包;记不清楚了,你要检查一下,去除那些并不是官方的mybatis包

**Comment by dengchanglu** [comment]
> mybatis-spring-boot-autoconfigure引入后就有这个问题，我用得2.7.6同样有这个问题。

我同事引用了一个自动创建mapp文件的mybatis包;记不清楚了,你要检查一下,去除那些并不是官方的mybatis包

**Comment by c2ch** [comment]
你怎么解决的。还还有这个问题。

**Comment by dengchanglu** [comment]
> 你怎么解决的。我还有这个问题。

配置文件读取的问题,你得看看还有什么包会去创建去读配置文件,把这些去除后看看能否正常

**Comment by c2ch** [comment]
> > 你怎么解决的。我还有这个问题。
> 
> 配置文件读取的问题,你得看看还有什么包会去创建去读配置文件,把这些去除后看看能否正常

![image](https://user-images.githubusercontent.com/35028011/101870284-43a96f00-3bbc-11eb-8f6b-b1a7ee26ca77.png)
我的配置是这样的，只要把消费者配置注释了，就没有这个问题了。

**Comment by weixq709** [comment]
@dengchanglu 请问这个问题怎么解决的
