### ISSUE TITLE
dubbo 线程池的 其他属性都可以直接配置但是alive 属性没有配置入口  必须使用parameters 配置 建议放出来和其他属性一样可以配置

### ISSUE THREAD

**Issue by hbzhangwenjie** [apache/dubbo#6708]
### Environment

* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

ProtocolConfig和privoderConfig都没有alive 
![image](https://user-images.githubusercontent.com/13030314/92466105-30c08080-f202-11ea-831b-90c0b92dcfb3.png)

![image](https://user-images.githubusercontent.com/13030314/92465995-ffe04b80-f201-11ea-914f-40bfee6310d3.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by manzhizhen** [comment]
let me have a look
