### ISSUE TITLE
[suggestion]CacheFilter$ValueWrapper needs to add default constructor

### ISSUE THREAD

**Issue by lvchangqi** [apache/dubbo#6710]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: macOS 10.15.3
* Java version: 1.8.0_11

![image](https://user-images.githubusercontent.com/15379292/92544700-1d082f00-f281-11ea-8cc0-f45862fafbfe.png)

It is recommended to add a default constructor, otherwise some serialization tools like `kryo` cannot work well

**Comment by CrazyHZM** [comment]
Has been resolved.
