### ISSUE TITLE
同一服务不停的报 [DUBBO] Notify urls for subscribe url是什么原因？怎么处理？

### ISSUE THREAD

**Issue by sxqem** [apache/dubbo#6714]
同一服务不停的报 [DUBBO] Notify urls for subscribe url是什么原因？怎么处理？

**Comment by horizonzy** [comment]
provider的zk节点在抖动，检查下服务提供者是否和zk的通信存在问题

**Comment by pipiguai11** [comment]
你是debug启动的吗？看看你是不是在方法名上打了个断点

**Comment by sxqem** [comment]
是服务器发布的版本，没有断点的问题，用的也是nacos，也没有zk的问题，不过更换到1.4.0版本后没再出现过该问题。

**Comment by yclxiao** [comment]
是不是在nacos  1.4版本以下，nacos-server重启的时候，服务消费者会出现[DUBBO] Notify urls for subscribe url的问题？
具体是什么原因，有大佬知道吗？

**Comment by yclxiao** [comment]
更换到nacos 1.4版本，是不是就可以解决以上问题？

**Comment by AlbumenJ** [comment]
> 是不是在nacos 1.4版本以下，nacos-server重启的时候，服务消费者会出现[DUBBO] Notify urls for subscribe url的问题？ 具体是什么原因，有大佬知道吗？

nacos-server 重启是会触发服务变动的，所以有 Notify 是符合预期的
