### ISSUE TITLE
Dubbo 2.7.6 breaks the generic invocation behavior

### ISSUE THREAD

**Issue by JasonMing** [apache/dubbo#6728]
### Environment

* Dubbo version: 2.7.6 +

### Steps to reproduce this issue

```java
GenericService genericService = ...;
genericService.$invoke("method", null /* parameterTypes */, new Object[] { /* args */ });
```

Before 2.7.6, the `parameterType` parameter supports null value, means use the method without overloads.

However, since 2.7.6, see: https://github.com/apache/dubbo/commit/ad2d30ba90eaea6074fbe4c2497789e0545e915c#diff-d799d91b73870eef3c22b89216a3554fR74, a check `args.length != types.length` was added. An NPE will be thrown when `types` is null.

### Expected Result

Support nullable `parameterTypes`.

### Actual Result

A guard check `args.length != types.length` in https://github.com/apache/dubbo/commit/ad2d30ba90eaea6074fbe4c2497789e0545e915c#diff-d799d91b73870eef3c22b89216a3554fR74 causes NPE when `types` is null.

**Comment by JasonMing** [comment]
@sunchuanleihit could you please check this issue?

**Comment by manzhizhen** [comment]
Let me have a look
