### ISSUE TITLE
能否增加dubbo事件接口

### ISSUE THREAD

**Issue by linuke** [apache/dubbo#674]
实际使用中消费kafka消息，然后调用dubbo服务；重启时dubbo销毁了，kafka 消费线程池还在进行消费导致服务调用异常。能否参考spring增加dubbo事件（启动完成 ，dubbo关闭等事件）

**Comment by chickenlj** [comment]
关闭事件提供接口同步给上层应该也是合理的。在你这个场景下，利用消息的ack机制也能保证可靠通知

**Comment by chickenlj** [comment]
see event mechanism introduced in 2.7.5
