### ISSUE TITLE
dubbo disconnected from

### ISSUE THREAD

**Issue by hudongdong129** [apache/dubbo#6740]
一直报disconnected  重启后也一直报错

**Comment by manzhizhen** [comment]
Can you tell me more about it?

**Comment by hudongdong129** [comment]
provider is disconnected ,After restarting the service, the service is still unavailable, resulting in the consumer not being able to get the corresponding Dubbo connection

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues
