### ISSUE TITLE
官网上框架设计页面调用链与当前版本不符

### ISSUE THREAD

**Issue by Miemiemiemieqiang** [apache/dubbo#6743]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9-SNAPSHOT
* Operating System version: Mac OS X
* Java version: jdk1.8.0_211

### Steps to reproduce this issue

1. http://dubbo.apache.org/zh-cn/docs/dev/design.html
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/39361661/93200956-1565f000-f783-11ea-8899-fb87ab879b85.png">

### Expected Result

Consumer 调用经过的第一个 filter 未处理缓存相关的 filter.在调试中发现在 loadBalance 之后才进行 cacheFilter 的过滤.

### Actual Result

猜测是未更新文档.

```
Just put your stack trace here!
```
![截屏2020-09-15 下午3 13 33](https://user-images.githubusercontent.com/39361661/93201288-90c7a180-f783-11ea-9e6c-7fd062408664.png)

**Comment by ppzzyy11** [comment]
的确是没更新，缺人力

**Comment by manzhizhen** [comment]
要不我有空来画个新的吧。。。

**Comment by CrazyHZM** [comment]
Issues have been created in the dubbo-website project
