### ISSUE TITLE
Application service level registration dubbo.tag invalid

### ISSUE THREAD

**Issue by cai-ti** [apache/dubbo#6745]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: deepin
* Java version: 1.8.0_261

### Steps to reproduce this issue

org.apache.dubbo.rpc.cluster.router.tag.TagRouter#route In the list of provider URLs obtained, parameters dubbo.tag The value of the tag route is the same, which causes the tag routing not to work normally

**Comment by manzhizhen** [comment]
Can you describe it in detail?

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
