### ISSUE TITLE
The Metadata module cannot disable writing files

### ISSUE THREAD

**Issue by zonghaishang** [apache/dubbo#6747]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: >= 2.7.9
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

![image](https://user-images.githubusercontent.com/15549777/93314519-71407f80-f83c-11ea-816a-b273c56d610d.png)

Should you decide that file=N/A means disabled?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by GeorgeSheridan** [comment]
Should this issue be labeled as Good First Issue?

We are doing research about how to help newcomers onboarding in an open source project and how to accelerate the issue resolving process.
We have developed a tool to automatically label the Good First Issue (GFI), i.e., the issue which is good for newcomers. 
We first extract 72 features from different dimensions of issue reports, such as readability, semantic meaning, associated code snippets, etc, and experimentally investigate to what extent these features correlate with GFI. Results turn out that a large portion of these features do have a medium to large correlation with GFI. 
We then build a machine learning model based on these features to predict GFI. The experiments on a dataset of 12k issues from Github show that 0.90 AUC can be achieved. 

Our tool shows that this issue has a very large possibility to be a GFI. 
Could you please tell us whether it should be labeled as a GFI?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by icankeep** [comment]
It already supports not writing files when file = N/A

![image](https://user-images.githubusercontent.com/39434627/146498638-44382344-618a-4933-83ae-6588fd2f4dd6.png)



![image](https://user-images.githubusercontent.com/39434627/146498669-cb67a345-0663-4398-ad6c-86c1b04ab5f7.png)
