### ISSUE TITLE
Upgrade Zookeeper version to 3.5.x  to prevent UnresolvedAddressException in Java14

### ISSUE THREAD

**Issue by MrYangxf** [apache/dubbo#6755]
An `UnresolvedAddressException` is thrown if the Zookeeper registry  is used under the enviroment of Java14. 
Because the lower version of Zookeeper is not compatible with the Java14 unresolved address format.
The problem is fixed in version 3.5.x of Zookeeper, **I suggest upgrade the Zookeeper version of Dubbo to 3.5.x**

-  the lower version of `getHostString()` method for zk
https://github.com/apache/zookeeper/blob/2d71af4dbe22557fda74f9a9b4309b15a7487f03/src/java/main/org/apache/zookeeper/client/StaticHostProvider.java#L135-L138

- jdk rewrite unresolved address format
https://github.com/openjdk/jdk/blob/9a7dcdcdbad34e061a8988287fe691abfd4df305/src/java.base/share/classes/java/net/InetSocketAddress.java#L107-L116

- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8 release 
* Operating System version: macOS 10.13.6
* Java version: jdk14.0.1

### Steps to reproduce this issue

[run the demo](https://github.com/apache/dubbo/blob/master/dubbo-demo/dubbo-demo-api/dubbo-demo-api-provider/src/main/java/org/apache/dubbo/demo/provider/Application.java)

### Expected Result

the normal run

### Actual Result

throw `java.nio.channels.UnresolvedAddressException`

If there is an exception, please attach the exception trace:

```
[17/09/20 10:30:53:424 CST] main-SendThread(127.0.0.1:2181)  WARN zookeeper.ClientCnxn: Session 0x0 for server 127.0.0.1/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
```

**Comment by kylixs** [comment]
3.4.x and 3.5.x mixing may cause incompatibility issues：

https://stackoverflow.com/a/61630617
> 3.4.x clients compatible with 3.5.x server
> 3.4.x and 3.5.x clients can be mixed on 3.5 server
> 3.5.x clients incompatible with 3.4 server

**Comment by kevinten10** [comment]
I encountered the same problem on the dubbo 3.0 branch.
Given that zookeeper 3.4.x has stopped updating, It makes sense to upgrade to 3.5.x

**Comment by liaozan** [comment]
Any progress?

**Comment by AlbumenJ** [comment]
Dubbo already suuport zookeeper with curator 5. You can directly add curator5 dependencies to your project and Dubbo will use curator 5 first.
