### ISSUE TITLE
nacos 1.3.2 + dubbo 2.7.8 ，nacos cluster mode high cpu

### ISSUE THREAD

**Issue by lijiaxing3045354** [apache/dubbo#6762]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: centos6.9
* Java version: 1.8

org.apache.dubbo.registry.nacos.NacosRegistry.getServiceNames0，line271
This method returns two serviceNames in order to be compatible with the old subscription serviceName. If the compatible service name cannot be found on the Nacos server, it will go to the Nacos server every other second (normally 10 seconds). Because the frequency is too high, the CPU of the Nacos server will remain high.

This is the detailed process of my feedback in the Nacos community
[https://github.com/alibaba/nacos/issues/3806](url)

### Expected Result
Remove compatible code？

thank you !

**Comment by horizonzy** [comment]
it should be compatible. in the nacos, the newest code in branch/develop already optimize this situation
