### ISSUE TITLE
Service not found: com.aaa.bbb.ccc2,test. 

### ISSUE THREAD

**Issue by success110** [apache/dubbo#6767]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: centos6.9
* Java version: jdk1.8

### Steps to reproduce this issue

生产者maven依赖
```
<dependency>
	<groupId>org.apache.dubbo</groupId>
	<artifactId>dubbo</artifactId>
	<version>2.7.7</version>
</dependency>
<dependency>
	<groupId>org.apache.curator</groupId>
	<artifactId>curator-client</artifactId>
	<version>4.2.0</version>
</dependency>
```

消费者maven依赖
```
<dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>dubbo</artifactId>
	<version>2.5.3</version>
</dependency>
```
 提供多版本服务

```
  <dubbo:service interface="com.aaa.bbb.ccc" ref="xxx1" version="1.0.0"   />
  <dubbo:service interface="com.aaa.bbb.ccc" ref="xxx2" version="2.0.0"   />
```
    
消费者调用3.0.0
  <dubbo:reference id="idxxx" interface="com.aaa.bbb.ccc" version="2.0.0"/>
   
低版本2.5.3调用高本版2.7.7报错信息：
Service not found: com.aaa.bbb.ccc2,test. 

断点观察：
![image](https://user-images.githubusercontent.com/18319674/93572278-366b5280-f9c8-11ea-92bf-ff83fdfc8e8c.png)

这个方法的传入path 是com.aaa.bbb.ccc2
而serviceDescriptor中this.services的服务中的key只有两种：
com.aaa.bbb.ccc
com.aaa.bbb.ccc2:2.0.0

初步判断是duboo版本不兼容 消费者也升级为2.7.7
发现调用成功了 
低版本调用高版本怎么可以兼容

**Comment by xiaoheng1** [comment]
Hello, the 2.5.x version of the community is currently not maintained, please upgrade the version.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
