### ISSUE TITLE
关于服务引用源码的疑惑

### ISSUE THREAD

**Issue by shihuaguo** [apache/dubbo#6770]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.6
* Operating System version: windows、ubuntu
* Java version: 11
* Spring Boot version：2.2.6.RELEASE
* Spring Cloud version：Hoxton.RELEASE
* Spring Cloud Alibaba version：2.2.1.RELEASE

### Steps to reproduce this issue

1. 如果现在有2个consumer，2个provider，如图：
![image](https://user-images.githubusercontent.com/7941760/93584757-54d94a00-f9d8-11ea-9b2b-0171c4259998.png)

2. 现打算对部分接口进行不兼容升级：
![image](https://user-images.githubusercontent.com/7941760/93584947-a5e93e00-f9d8-11ea-932a-c0c244ab9a27.png)

3.升级之后，根据版本号匹配的原则，consumer1应该只会refer到provider1，原来的consumer2只会refer到provider2。

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
consumer1应该只会refer到provider1，原来的consumer2只会refer到provider2。

### Actual Result

What actually happens?

从源码来看，服务引入的过程似乎和版本没有关系。
1、在AbstractSpringCloudRegistry.subscribeDubboServiceURL方法中，有这样一段：
```
List<URL> exportedURLs = getExportedURLs(dubboMetadataService, url);
		for (URL exportedURL : exportedURLs) {
			String protocol = exportedURL.getProtocol();
			List<URL> subscribedURLs = new LinkedList<>();
			serviceInstances.forEach(serviceInstance -> {
				Integer port = repository.getDubboProtocolPort(serviceInstance, protocol);
				String host = serviceInstance.getHost();
				if (port == null) {
					if (logger.isWarnEnabled()) {
						logger.warn(
								"The protocol[{}] port of Dubbo  service instance[host : {}] "
										+ "can't be resolved",
								protocol, host);
					}
				}
				else {
					URL subscribedURL = new URL(protocol, host, port,
							exportedURL.getParameters());
					subscribedURLs.add(subscribedURL);
				}
			});

			allSubscribedURLs.addAll(subscribedURLs);
		}
```
可以看出，该段代码从dubboMetadataService获取exportedURLs，然后遍历所有的provider serviceInstance，生成最终的allSubscribedURLs。
然后跟踪dubboMetadataService的代码，在DubboServiceMetadataRepository.initSubscribedDubboMetadataService中有这样一段：
```
Optional<ServiceInstance> optionalServiceInstance = metadataServiceInstanceSelector
				.choose(discoveryClient.getInstances(serviceName));
		if (!((Optional) optionalServiceInstance).isPresent()) {
			return false;
		}
		ServiceInstance serviceInstance = optionalServiceInstance.get();
		if (null == serviceInstance) {
			return false;
		}
```
这里仅仅是从discoveryClient.getInstances(serviceName)返回的provider实例中随机选取了一个（stream.findAny()）实例，然后用来作为获取dubboMetadataServiceURL的实例。这样看的话，consumer要根据版本号调用匹配版本号的provider似乎并不能实现，而在实际使用中也发现，在以下场景下：
![image](https://user-images.githubusercontent.com/7941760/93586439-e5b12500-f9da-11ea-8822-0c2ac4d21941.png)
如果consumer1在服务引用时，选择的dubboMetadataService是provider1时，最终consumer1引用的invokers会包含provider1和provider2，导致调用会有50%的几率成功。
如果consumer1在服务引用时，选择的dubboMetadataService是provider2时，最终consumer1引用的invokers是空的，导致调用会100%失败。

**Comment by wujincheng2333** [comment]
这应该是springcloud alibaba的问题

**Comment by shihuaguo** [comment]
是的。
