### ISSUE TITLE
http://start.dubbo.io/ is not accessible

### ISSUE THREAD

**Issue by Xunzhuo** [apache/dubbo#6771]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

http://start.dubbo.io/ 无法正常访问

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by qixiaobo** [comment]
> Sorry, the site is out of date. If you still want to create a dubbo project, try to visit https://start.aliyun.com/bootstrap.html .


Why not 302 ？？？ @Xunzhuo
