### ISSUE TITLE
Nacos 注册中心在地址从有到无时，不会触发地址变更，导致客户端一直请求到下线的地址。

### ISSUE THREAD

**Issue by lexburner** [apache/dubbo#6774]
### 环境

* Dubbo version: 2.7.x

### 重现该 issue 的方式

1. 启动一个 consumer
2. 启动一台 provider，consumer 收到地址推送
3. 下线 provider，consumer 收不到地址推送，于是一个下线的地址一直存在于 consumer 端

### 预期结果

使用 Nacos 注册中心时，provider 地址在从有到无时，可以正常刷新地址

### 实际的结果

使用 Nacos 注册中心时，provider 地址在从有到无时，不会触发 notify 方法

### 问题影响面

在没有地址时，consumer 应当提示无可用 provider。但受该 bug 的影响，会导致 consumer 一直调用已经下线的 provider，影响问题排查的难度

### 问题分析

在 `org.apache.dubbo.registry.nacos.NacosRegistry#notifySubscriber` 方法和`org.apache.dubbo.registry.integration.RegistryDirectory#notify` 方法上同时打断点，前者是 nacos 实际监听的入口，后者是dubbo 地址 notify 的入口，发现 nacos 实际地址收到了监听，但是没有传递给 `RegistryDirectory#notify`。

根因是 `NacosRegistry` 在处理空地址列表时，没有遵循 dubbo 的规范，实际应当构造一个 empty 协议的 url 向下传递，才不会被 `org.apache.dubbo.registry.support.AbstractRegistry#notify` 的逻辑过滤。

### 修改建议

`NacosRegistry` 应当参考 `ZookeeperRegistry` 的实现，在收到空地址列表时，按照 `toUrlsWithEmpty` 方法，构造一个 empty 协议的 URL 向下传递。

**Comment by victoyzz** [comment]
good ，大佬修复下

**Comment by lexburner** [comment]
发现在 274 已经修复了
