### ISSUE TITLE
When the Ci of PR is successful, codecov does not issue coverage report comments

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo#6795]
_Bow-_ [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: `2.7.9-SNAPSHOT`
* Operating System version:  travis ci 
* Java version:  1.8
### Steps to reproduce this issue

 Add a pr ，and is is built successful
 

### Expected Result

We can see the  coverage report commented by  codecov

### Actual Result

Now codecov doesn't comment

**Comment by htynkn** [comment]
there is no codecov change recently and also I can confirm codecov data is updated, for example:
https://codecov.io/gh/apache/dubbo/pulls

I also double check some of apache project:
https://github.com/apache/shardingsphere-elasticjob/pull/1542

codecov comment not showing too. so I guess it maybe some infra issue from codecov.
will follow up.

**Comment by htynkn** [comment]
works now without any change in dubbo repo
