### ISSUE TITLE
dubbo客户端和服务端的强耦合性问题

### ISSUE THREAD

**Issue by GithubRyze** [apache/dubbo#6799]
在dubbo的使用过程中，我们发现客户端和服务端有着很强的依赖性， 并不想HTTP那样只要暴露一个URL客户端就可以找到服务。大部分在追赶项目进度的情况下，存在代码组织混乱，dubbo接口不合理的发布在一个class中，当后期有时间优化的时候，发现这些不合理的发布下，想把接口从A class放到B class中去的时候，发现客户端也同样需要修改代码。这样的情况下，我们想是不是客户端和服务端的耦合性太强了，我们认为理想的情况，是不是客户端不用管我们dubbo接口发布在哪个class中，当我们把接口从A class换到B class的时候，客户端不需要做任何修改。  请问下：dubbo可以这样用吗？因为存在多团队协作的情况下，这种效率会更高点？如dubbo不能这样做，请问下大家 是否有RPC框架可以像上面描述那样做到。  谢谢

**Comment by johnsonin** [comment]
泛化调用

**Comment by manzhizhen** [comment]
> 泛化调用

泛化调用也是要写类名的

**Comment by johnsonin** [comment]
> > 泛化调用
> 
> 泛化调用也是要写类名的
类名可以做成配置，客户端改配置就好啦

**Comment by GithubRyze** [comment]
> > > 泛化调用
> > 
> > 
> > 泛化调用也是要写类名的
> > 类名可以做成配置，客户端改配置就好啦

这样就需要修改代码配置，或者是修改配置中心的配置，都是需要客户端那边重新发布，一样需要修改。我们的理想是客户端不需要做任何处理 在我们调整代码的情况下。

**Comment by qixiaobo** [comment]
> > > > 泛化调用
> > > 
> > > 
> > > 泛化调用也是要写类名的
> > > 类名可以做成配置，客户端改配置就好啦
> 
> 这样就需要修改代码配置，或者是修改配置中心的配置，都是需要客户端那边重新发布，一样需要修改。我们的理想是客户端不需要做任何处理 在我们调整代码的情况下。

你这个问题很奇怪 你的说法同样适应于你的http接口暴露不规范 那么你迁移http接口不一样要求客户端修改吗？

**Comment by GithubRyze** [comment]
> > > > > 泛化调用
> > > > 
> > > > 
> > > > 泛化调用也是要写类名的
> > > > 类名可以做成配置，客户端改配置就好啦
> > 
> > 
> > 这样就需要修改代码配置，或者是修改配置中心的配置，都是需要客户端那边重新发布，一样需要修改。我们的理想是客户端不需要做任何处理 在我们调整代码的情况下。
> 
> 你这个问题很奇怪 你的说法同样适应于你的http接口暴露不规范 那么你迁移http接口不一样要求客户端修改吗？

你说的对，如果需要实现我们这个想法，可能泛化调用 + 配置就可以了

**Comment by mail6562** [comment]
springcloud 支持这样的方式。

**Comment by wujincheng2333** [comment]
如果你自己有思路可以自己fork下来自己改，远程调用本身就需要唯一标识，java里面唯一标识就是全类名，如果想客户端不动，那就要改成每次都要遍历所有暴露接口的方法，找到方法时再拼接类吗和包名，但是这样会引来很多问题，很多东西变得不规范，效率也会存在问题。

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
