### ISSUE TITLE
after import dubbo to my project ,and seperate project into multi modules ,each module takes even ten times memory than before( 引入dubbo后,每个单独的项目占用的内存都升高很多,并且其中一个不断升高)

### ISSUE THREAD

**Issue by raydl007** [apache/dubbo#6808]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: windows 10
* Java version: 1.8
* registry: redis

### Steps to reproduce this issue

并不清楚如何重现该问题,也不知道是否是普遍存在的问题。但是即便系统零负载内存仍然不断升高，直到fullGC

### Expected Result

即便由于启动了一个netty服务,以及一些其他的东西,但是内存应该处于相对稳定的状态下，也不应该出现10倍以上的内存占用升高

### Actual Result

![image](https://user-images.githubusercontent.com/10443318/96087076-e2378d80-0ef5-11eb-8bb8-710aa6f27304.png)
![image](https://user-images.githubusercontent.com/10443318/96086625-2e360280-0ef5-11eb-8dcd-22c235415434.png)
![image](https://user-images.githubusercontent.com/10443318/96086936-a3093c80-0ef5-11eb-93de-11d62d6d4724.png)

**Comment by raydl007** [comment]
![image](https://user-images.githubusercontent.com/10443318/96090956-88d25d00-0efb-11eb-8059-84e69fc9f85d.png)
there is a thread named "dubbo-future-timeout-thread-1" keep eating my memory

**Comment by manzhizhen** [comment]
mark

**Comment by raydl007** [comment]
I hava two modules A and B:
* B module provides a service named UserRpcService implements org.springframework.security.core.userdetails.UserDetailsService to provide a UserDetailsService to spring-security framework,
* A module reference this UserRpcService for login purpose,when invoke loadUserByUsername method ,the memory increase 10mb per seconds,and gc became more frequently than before.
## before invoke loadUserByUsername
![before invoke loadUserByUsername ](https://user-images.githubusercontent.com/10443318/96208890-0d2aeb80-0fa1-11eb-9bb6-e8d1ed92141d.png)
## after invoke loadUserByUsername
![after invoke loadUserByUsername ](https://user-images.githubusercontent.com/10443318/96208894-10be7280-0fa1-11eb-8552-46c420256bc3.png)

![image](https://user-images.githubusercontent.com/10443318/96209213-a78b2f00-0fa1-11eb-995f-352f9290df33.png)

**Comment by zx844174097** [comment]
[https://github.com/apache/dubbo/issues/6820](url)
