### ISSUE TITLE
Dubbo application will loss subscribe when  zookeeper  repeatedly switches between down and start

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#6810]
### Environment

* Dubbo version: 2.7.2 
* Operating System version: linux
* Java version: jdk8

### Steps to reproduce this issue

1. start consumer and provider when zookeeper cluster is avalable
2. stop zookeeper cluster
3. start zookeeper cluster
4. stop zookeeper cluster (make sure execute this step before FailedSubscribedTask execute)

### Expected Result
Just report it. maybe can help other people who meet this case.
At step 3. The recover event will trigger. the FailedSubscribeTask will execute. The FailedSubscribeTask will retry 3 times(default) when execute failed. Before FailedSubscribeTask execute, the zookeeper cluster is stop. So the retry task will failed 3 times. When fourth time, the task over the max retry time, it will return directly, the failed task will stop forever.
Even the zookeeper cluster restart. the failedSubscribed map already contails the old FailedSubscribeTask, so consumer loss subscribe.

Now we change the retry times to Integer.MAX to solve this case.

**Comment by zlm0125** [comment]
need update to 2.7.4.1+

**Comment by horizonzy** [comment]
> need update to 2.7.4.1+

Hi. Which pr fix it, can you refer it? Thanks very much.

**Comment by zlm0125** [comment]
> > need update to 2.7.4.1+
> 
> Hi. Which pr fix it, can you refer it? Thanks very much.

you can take a look at #5135 and it`s related.

**Comment by zlm0125** [comment]
> > need update to 2.7.4.1+
> 
> Hi. Which pr fix it, can you refer it? Thanks very much.
Because the session is not current.

**Comment by horizonzy** [comment]
Thank you, I think the pr is to solve another problem. this issue is about the AbstractRetryTask.
