### ISSUE TITLE
dubbo-spring-boot-starter2.7.8集成apollo，dubbo要求必须在apollo里面配置一个和应用名同名的namespace吗？

### ISSUE THREAD

**Issue by github-xuwj** [apache/dubbo#6824]
app.id=demo-provider
dubbo.application.name=provider-of-demo
启动的过程中， 会有一个namespace加载失败的日志
18:10:43.821 WARN [main] c.c.f.a.i.RemoteConfigRepository - Load config failed, will retry in 1 SECONDS. appId: demo-provider, cluster: default, namespaces: provider-of-demo.properties
看了dubbo源码 String appGroup = getApplication().getName();这里好像默认使用应用名作为一个namespace。

    private DynamicConfiguration prepareEnvironment(ConfigCenterConfig configCenter) {
        if (configCenter.isValid()) {
            if (!configCenter.checkOrUpdateInited()) {
                return null;
            }
            DynamicConfiguration dynamicConfiguration = getDynamicConfiguration(configCenter.toUrl());
            String configContent = dynamicConfiguration.getProperties(configCenter.getConfigFile(), configCenter.getGroup());

            String appGroup = getApplication().getName();
            String appConfigContent = null;
            if (isNotEmpty(appGroup)) {
                appConfigContent = dynamicConfiguration.getProperties
                        (isNotEmpty(configCenter.getAppConfigFile()) ? configCenter.getAppConfigFile() : configCenter.getConfigFile(),
                                appGroup
                        );
            }
            try {
                environment.setConfigCenterFirst(configCenter.isHighestPriority());
                environment.updateExternalConfigurationMap(parseProperties(configContent));
                environment.updateAppExternalConfigurationMap(parseProperties(appConfigContent));
            } catch (IOException e) {
                throw new IllegalStateException("Failed to parse configurations from Config Center.", e);
            }
            return dynamicConfiguration;
        }
        return null;
    }

**Comment by JohnYWN** [comment]
请问您这个问题怎么解决的，我也碰到了同样的情况。
