### ISSUE TITLE
泛化调用无参提供者方法时, parameterTypes 和 args 传null出现空指针异常

### ISSUE THREAD

**Issue by KeRan213539** [apache/dubbo#6840]
### Environment

* Dubbo version: 2.7.8
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue
当通过泛化调用无参提供者方法时, genericService.$invoke(methodName, null, null) 会报空指针异常
之前2.7.5 没问题, 2.7.8 出现(2.7.5~2.7.8中间的版本没测,所以也不确定到底是哪个版本出现的)
具体出现在 org.apache.dubbo.rpc.filter.GenericFilter#invoke 中:
![image](https://user-images.githubusercontent.com/1195743/97387097-4869da80-1910-11eb-85c0-36b8b19dff6e.png)
对 args 为 null 时做了处理,但是没有对 types 为null 做处理

**Comment by tswstarplanet** [comment]
Can you submit a pr to fix it ?

**Comment by KeRan213539** [comment]
> Can you submit a pr to fix it ?

ok，i will do it

**Comment by KeRan213539** [comment]
看了新代码,该问题已经修复, 该issue关闭
