### ISSUE TITLE
dubbo rest模块内置的swagger会改变spring boot默认行为

### ISSUE THREAD

**Issue by klzami** [apache/dubbo#6841]
- [ x ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ x ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: Mac Catalina 10.15.7 (19H2)
* Java version: 1.8.0_231
* SpringBoot: 1.5.9.RELEASE

### Steps to reproduce this issue

1. 基于spring boot 1.5.x搭建demo项目并编写测试controller
2. 访问该测试controller，默认返回json格式的response
3. 引用以下包：
```xml
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>2.7.7</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>2.9.2</version>
        </dependency>
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.5.9</version>
        </dependency>
```

4. 重启demo项目并再次访问测试controller，这时会返回xml格式的response

### Expected Result

引用swagger不改变spring boot的默认http message converter组织方式，不影响各接口的response格式。

### Actual Result

引用swagger后改变了spring boot的默认http message converter组织方式，进而改变了各接口的response格式。

### Trouble Shooting

1. dubbo rest集成了swagger，用到了相关的类，比如：``io.swagger.jaxrs.listing.BaseApiListingResource``。
2. 因此必须引用 ``swagger-jersey2-jaxrs`` 包。
3. ``swagger-jersey2-jaxrs`` 包引用了 ``jackson-dataformat-xml``包。
4. ``jackson-dataformat-xml``内部的 ``XmlMapper``类会改变SpringBoot的HttpMessageConverter组装过程，从而改变默认response格式。

**Comment by blindarcheology** [comment]
can you provide a recurring case for this issue. Thanks!

**Comment by CrazyHZM** [comment]
I think this is not a problem that dubbo needs to solve. You can try to specify `application/json` in the header and specify the http message in json format.
