### ISSUE TITLE
maven打包Could not transfer metadata以及code.alibabatech.com无法访问

### ISSUE THREAD

**Issue by whatbeg** [apache/dubbo#6861]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: linux centos 7
* Java version: 1.8

### Steps to reproduce this issue

[INFO] --------------------------------[ jar ]---------------------------------
Downloading from alibaba-opensource-releases: http://code.alibabatech.com/mvn/releases/com/alibaba/platform/shared/dubbo.rpc/maven-metadata.xml
^@[WARNING] Could not transfer metadata com.alibaba.platform.shared:dubbo.rpc/maven-metadata.xml from/to alibaba-opensource-releases (http://code.alibabatech.com/mvn/releases): Transfer failed for http://code.alibabatech.com/mvn/releases/com/alibaba/platform/shared/dubbo.rpc/maven-metadata.xml
Downloading from alibaba-opensource-releases: http://code.alibabatech.com/mvn/releases/com/alibaba/platform/shared/dubbo.remoting/maven-metadata.xml
^@^@[WARNING] Could not transfer metadata com.alibaba.platform.shared:dubbo.remoting/maven-metadata.xml from/to alibaba-opensource-releases (http://code.alibabatech.com/mvn/releases): Transfer failed for http://code.alibabatech.com/mvn/releases/com/alibaba/platform/shared/dubbo.remoting/maven-metadata.xml
Downloading from alibaba-opensource-releases: http://code.alibabatech.com/mvn/releases/com/alibaba/platform/shared/dubbo/maven-metadata.xml
^@^@[WARNING] Could not transfer metadata com.alibaba.platform.shared:dubbo/maven-metadata.xml from/to alibaba-opensource-releases (http://code.alibabatech.com/mvn/releases): Transfer failed for http://code.alibabatech.com/mvn/releases/com/alibaba/platform/shared/dubbo/maven-metadata.xml

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by htynkn** [comment]
CI is green at this moment, and auto snapshot works too.
alibaba-opensource-releases is a third party maven mirror which out of apache's control. please try to use apache repo or ask help from the admin for alibaba-opensource-releases
