### ISSUE TITLE
WebSite URL 404

### ISSUE THREAD

**Issue by minioreo** [apache/dubbo#6863]
many urls return 404 since 2020-11-02.

http://dubbo.apache.org/zh-cn/docs/user/references/telnet.html
http://dubbo.apache.org/zh-cn/docs/user/demos/thread-model.html
http://dubbo.apache.org/zh-cn/docs/user/demos/dump.html

etc。

These urls is returned by google search。

**Comment by AvengerEug** [comment]
You can try to access
[http://dubbo.apache.org/zh-cn/docs/2.7/user/references/telnet](http://dubbo.apache.org/zh-cn/docs/2.7/user/references/telnet).

Dubbo's official website has been updated.

**Comment by minioreo** [comment]
> Dubbo's official website has been updated.
> You can try to access http://dubbo.apache.org/zh-cn/docs/2.7/user/references/telnet.

ok  thanks。So we have to wait for google updating indicies.

**Comment by kentkwan** [comment]
动态配置页面缺失

**Comment by fsx379** [comment]
是啊，开发手册 下面的文章链接也全部失效...

**Comment by htynkn** [comment]
maybe apache config can do redirect for us.

**Comment by htynkn** [comment]
a new apache config for old style url has been applied. 
above links should work now

**Comment by kentkwan** [comment]
中文页面 2.7版本 “动态配置中心”页面连接依然错误跳转到“注解配置”页面

**Comment by htynkn** [comment]
> 中文页面 2.7版本 “动态配置中心”页面连接依然错误跳转到“注解配置”页面

thanks, done.
https://dubbo.apache.org/zh-cn/docs/2.7/user/configuration/config-center/

**Comment by kentkwan** [comment]
> > 中文页面 2.7版本 “动态配置中心”页面连接依然错误跳转到“注解配置”页面
> 
> thanks, done.
> https://dubbo.apache.org/zh-cn/docs/2.7/user/configuration/config-center/

感谢开发组

**Comment by kentkwan** [comment]
中文页面 2.7版本 “开发手册”页面所有连接均跳转失败

**Comment by htynkn** [comment]
> 中文页面 2.7版本 “开发手册”页面所有连接均跳转失败

Thanks for reporting. above issues are fixed by https://github.com/apache/dubbo-website/commit/b5e9e9eb9d03e19785e7266de1998e0428ee5361

**Comment by CrazyHZM** [comment]
Already resolved.
