### ISSUE TITLE
【java-consumer & dubbo-go-provider】org.apache.dubbo.remoting.RemotingException: message can not send, because channel is closed

### ISSUE THREAD

**Issue by Xstarfct** [apache/dubbo#6865]
泛化调用GO服务的时候，不确定时机的报错
![image](https://user-images.githubusercontent.com/9083689/97960244-0945f880-1dec-11eb-9e2d-3bd86f239d57.png)

**Comment by Xstarfct** [comment]
![image](https://user-images.githubusercontent.com/9083689/97960561-a739c300-1dec-11eb-8e38-4233b3714548.png)
@Override
    public void send(Object message, boolean sent) throws RemotingException {
        if (needReconnect && !isConnected()) {
            connect();
        }
        Channel channel = getChannel();
        //TODO Can the value returned by getChannel() be null? need improvement.
        if (channel == null || !channel.isConnected()) {
            throw new RemotingException(this, "message can not send, because channel is closed . url:" + getUrl());
        }
        channel.send(message, sent);
    }


这个地方有修改吗？

**Comment by Xstarfct** [comment]
目前个人的解决方案：
在服务注册的时候加上：send.reconnect=true

because :
if (needReconnect && !isConnected()) {
connect();
}
![image](https://user-images.githubusercontent.com/9083689/97986913-67d39c80-1e15-11eb-8f8e-1b40fd945180.png)

**Comment by mercyblitz** [comment]
Please Pull your request~

**Comment by kgrace52** [comment]
> 目前个人的解决方案： 在服务注册的时候加上：send.reconnect=true
> 
> because : if (needReconnect && !isConnected()) { connect(); } ![image](https://user-images.githubusercontent.com/9083689/97986913-67d39c80-1e15-11eb-8f8e-1b40fd945180.png)

麻烦问下，这个怎么加呢？

**Comment by Xstarfct** [comment]
> > 目前个人的解决方案： 在服务注册的时候加上：send.reconnect=true
> > because : if (needReconnect && !isConnected()) { connect(); } ![image](https://user-images.githubusercontent.com/9083689/97986913-67d39c80-1e15-11eb-8f8e-1b40fd945180.png)
> 
> 麻烦问下，这个怎么加呢？
please see https://dubbo.apache.org/zh/docs/v2.7/user/references/xml/dubbo-parameter/
