### ISSUE TITLE
Memory leak of  InternalThreadLocalMap

### ISSUE THREAD

**Issue by liusf1993** [apache/dubbo#6866]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: Linux  4.15.0-122-generic #124~16.04.1-Ubuntu SMP Thu Oct 15 16:08:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Java version: 1.8.0_201

### Steps to reproduce this issue

1. Provide a method in service-side and return a large data( for example 4M).
2. Create a fixed threadpool(fox example,with 100 threads), and invoke the remote method in a loop.
3. After the loop finished, the memory about 400M was always kept by `InternalThreadLocalMap`.

### Expected Result

After all finished, memory kept by `InternalThreadLocalMap`  will be revoked by GC.

### Actual Result

The memory about 400M was always kept by `InternalThreadLocalMap`.  

### More
The [demo](https://github.com/liusf1993/dubbo-test) can reproduce this issue.    
Other information I can  provided:  
The leak memory was created by `FutureContext#futureTL`, and data in threadlocal can be traced by `InternalThreadLocal#VARIABLES_TO_REMOVE_INDEX`,  invoke method `InternalThreadLocal#removeAll` in consumer filter can free the memory, but I can't  find any usages of this method. Now I add `InternalThreadLocal#removeAll` in an extended  filter to solve this problem in my program.  
If this is configuration error, thanks for your correction.

**Comment by xiaoheng1** [comment]
Are you sure it is ThreadLocalMap? I looked at the code you wrote and found that ThreadLocalMap was not used.

**Comment by xiaoheng1** [comment]
I think the FutureContext should indeed be recycled after the call ends.

**Comment by liusf1993** [comment]
> Are you sure it is ThreadLocalMap? I looked at the code you wrote and found that ThreadLocalMap was not used.
It's  `org.apache.dubbo.common.threadlocal.InternalThreadLocalMap` used, 
We can use `jcmd <pid> GC.class_histogram|grep "InternalThreadLocalMap"` to see the instances.  
And you can add 
````
                InternalThreadLocalMap.getIfSet().indexedVariable(0);
                InternalThreadLocalMap.getIfSet().indexedVariable(1);
                InternalThreadLocalMap.getIfSet().indexedVariable(2);
                InternalThreadLocalMap.getIfSet().indexedVariable(3);
````
at line 24 to see the value in threadlocal

**Comment by xiaoheng1** [comment]
I understand what you mean, I think the FutureContext object should be recycled after the call is over. you are right.

**Comment by xishian** [comment]
dubbo 2.7.7, org.apache.dubbo.remoting.exchange.support.DefaultFuture中有一个静态对象FUTURES（ConcurrentHashMap），consumer发起请求后会创建一个DefaultFuture的实例放到这个Map中，然后请求完成后会从FUTURES中删除这个实例（通过receive或者cancel方法）

我的程序（Consumer）中出现了一种情况，DefaultFuture实例并没有被成功删除，导致了内存泄漏

我的场景：Provider处理能力非常有限，Consumer端会出现大量超时，以及服务端线程池满等问题，另外发起dubbo请求的线程可能被中断

**Comment by xiaoheng1** [comment]
@xishian 能提供一个 demo 稳定重现你这种场景不？

**Comment by xishian** [comment]
https://github.com/apache/dubbo/issues/7100
已经解决了

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Comment by dinghal** [comment]
@xishian 请问是怎么解决的？我也遇到了同样的问题

**Comment by xiaoheng1** [comment]
The master branch has been fixed. please see #7100
