### ISSUE TITLE
官网的源码导读没了

### ISSUE THREAD

**Issue by fanxiaopeng** [apache/dubbo#6871]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Steps to reproduce this issue

http://dubbo.apache.org/zh-cn/docs/2.7/user/preface/architecture/
1. 源码导读章节没了
2. 左侧目录中，2.7 -> 开发手册 下的其他章节均跳转到首页

**Comment by htynkn** [comment]
感谢反馈
2.已经修复

1.正在排查

**Comment by htynkn** [comment]
fixed via: https://github.com/apache/dubbo-website/pull/642
