### ISSUE TITLE
"dubbo.service.shutdown.wait" does not be loaded to override the default value

### ISSUE THREAD

**Issue by wanghuigithub** [apache/dubbo#6872]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. use the "dubbo-samples-zookeeper" project
2. add "dubbo.properties" in the spring directory
![image](https://user-images.githubusercontent.com/11936135/97993800-82ab0e80-1e1f-11eb-81cf-5e5bf609fbfe.png)
3. add dubbo.service.shutdown.wait in the dubbo.properties
![image](https://user-images.githubusercontent.com/11936135/97993831-8f2f6700-1e1f-11eb-96ed-b3e34fdae938.png)
![image](https://user-images.githubusercontent.com/11936135/97993872-9ce4ec80-1e1f-11eb-8d43-1d741a100253.png)
4、kill -15 the project's process
5、the log print "Waiting 10000ms for registry to notify all consumers before unexport"。
always use the default value

**Comment by wanghuigithub** [comment]
是我提问方式不对么，怎么没人答复额

**Comment by Leishunyu** [comment]
The path of dubbo.properties is wrong. The default path is under the resource path. The dubbo.properties in spring will not be automatically scanned by the system, and SPI needs to be customized

**Comment by Leishunyu** [comment]
![image](https://user-images.githubusercontent.com/29188508/98330890-5c12f080-2036-11eb-9d7d-f2f60e654ad3.png)
org.apache.dubbo.common.utils.ConfigUtils#getProperties

**Comment by wanghuigithub** [comment]
ok thanks
