### ISSUE TITLE
有没有熔断策略 或 在consumer获取provider状态

### ISSUE THREAD

**Issue by zyiLoong** [apache/dubbo#6877]
dubbo 2.7.7
spring

1. 有没有可用的熔断策略，可以让provider在自身出现异常时自动下线，待恢复后再上线。
2. 或者是有没有什么办法可以在consumer获取到provider的可用状态（由provider维护的一个状态，比如provider在本地磁盘将满时将状态设置为"不可用"），这样我可以在负载均衡里面来根据状态筛选可用的provider节点。
看了官网2.7的文档，只找到了个StatusChecker，但是这个好像是只在启动时check？

thanks

**Comment by zhangzhonghua** [comment]
可以通过监控发现异常时变更注册中心中接口状态为不可用，或者provider端发现异常时服务自动下线。

**Comment by zyiLoong** [comment]
@zhangzhonghua 
有相应的文档吗？我没找到

**Comment by dkisser** [comment]
当服务不可用时会自动下线，当服务可用时会通过注册中心通知（这些是Dubbo的特性）。但consumer无法感知到provider的状态，即使provider可能已经满载，consumer最多返回超时。或按上面的同学说的使用monitor去手动下线。若是想实现智能熔断和降级的逻辑需要集成其他框架

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it.
