### ISSUE TITLE
the wiki should Be more simple and practical

### ISSUE THREAD

**Issue by libinglong** [apache/dubbo#6884]
for example,the icon on wiki page
![image](https://user-images.githubusercontent.com/38123153/98333959-ce86cf00-203c-11eb-87a0-5f70c8154faf.png)
there is no need to change the icon for Chinese.
And the wiki's quick start is Not following the common sense.You can provide a maven or gradle start guidence step by step.

**Comment by CrazyHZM** [comment]
Issues have been created in the dubbo-website project
