### ISSUE TITLE
Dubbo-thread-xxx threads that should not appear on the consumer side

### ISSUE THREAD

**Issue by tongxiao0622** [apache/dubbo#6887]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: mac os
* Java version: 1.8

### Steps to reproduce this issue

1. Start multiple provider nodes
(中文：启动多个提供方节点)

2. Start consumer node
(中文：启动消费方节点)

3. Frequently shutdown and restart provider nodes or Frequently enable and disable provider nodes
(中文：频繁关闭、重启提供方节点或者频繁启用、禁用提供方节点)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

Only the thread of DubboClientHandler-xxx will appear
(中文：应该只会出现DubboClientHandler-xxx的线程用于网络连接、断连，因为获取响应结果用的是主线程)

### Actual Result

What actually happens?

There are many threads named with Dubbo-thread-xxx on the consumer side，these threads will not be recycled.
(中文：消费方出现了很多以Dubbo-thread-xxx命名的线程，这些线程不会被回收)

**Comment by CrazyHZM** [comment]
Resolved in https://github.com/apache/dubbo/pull/7109
