### ISSUE TITLE
monitor在哪里下载安装啊，找了半天没找到

### ISSUE THREAD

**Issue by zhanglinlu** [apache/dubbo#6895]
2.7.8里面没有了啊

**Comment by LiHuaYang** [comment]
现在貌似单独维护在 dubbo-admin 项目下面了，master 分支

https://github.com/apache/dubbo-admin/tree/master

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it.
