### ISSUE TITLE
dubbo HeaderExchangeChannel close method logic error

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo#6902]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: MacOS
* Java version: 1.8

dubbo HeaderExchangeChannel source code.

```
public void close() {
        try {
            // graceful close
            DefaultFuture.closeChannel(channel);
            channel.close();
        } catch (Throwable e) {
            logger.warn(e.getMessage(), e);
        }
    }
```

I understand that if closed field is added to this class as the state control of the channel, it should be added to each of its methods. For example, the close method should be modified to

public void close() {
        if (closed) {
            return;
        }
        closed = true;
        try {
            // graceful close
            DefaultFuture.closeChannel(channel);
            channel.close();
        } catch (Throwable e) {
            logger.warn(e.getMessage(), e);
        }
    }

But if you don't do state control in the class, why not directly let HeaderExchangeChannel inherit the AbstractPeer class?

**Comment by dkisser** [comment]
In my opinion , although Channel may have closed ,but Dubbo must tell the invoke result to Client 。In `DefaultFuture.closeChannel(channel);`  it will return an error msg to Client.

**Comment by xiaoheng1** [comment]
@dkisser I don’t think so. If closed is true, the notification must have been sent to client.
 At this time, I think it can return immediately.

**Comment by dkisser** [comment]
Sure . But , Client don't know the result of invoke ,by this time.Client just know one of the channel closed

**Comment by xiaoheng1** [comment]
@dkisser I think it is enough to receive the channel closed, the client is not waiting for the return from the server. Do you think so?

**Comment by dkisser** [comment]
Not yet, Client will blocking util timeout in that way.Pay your attention to  `DubboInvoker` .
![image](https://user-images.githubusercontent.com/24600271/100449231-85331800-30ee-11eb-92cf-45dabe2d9e0b.png)

**Comment by xiaoheng1** [comment]
1.In the DefaultFuture.closeChannel method, the failure result is quickly obtained. When the pipeline is closed, a response will be generated immediately for notification.
2.DubboInvoker2.7.8

protected Result doInvoke(final Invocation invocation) throws Throwable {
        RpcInvocation inv = (RpcInvocation) invocation;
        final String methodName = RpcUtils.getMethodName(invocation);
        inv.setAttachment(PATH_KEY, getUrl().getPath());
        inv.setAttachment(VERSION_KEY, version);

        ExchangeClient currentClient;
        if (clients.length == 1) {
            currentClient = clients[0];
        } else {
            currentClient = clients[index.getAndIncrement() % clients.length];
        }
        try {
            boolean isOneway = RpcUtils.isOneway(getUrl(), invocation);
            int timeout = calculateTimeout(invocation, methodName);
            invocation.put(TIMEOUT_KEY, timeout);
            if (isOneway) {
                boolean isSent = getUrl().getMethodParameter(methodName, Constants.SENT_KEY, false);
                currentClient.send(inv, isSent);
                return AsyncRpcResult.newDefaultAsyncResult(invocation);
            } else {
                ExecutorService executor = getCallbackExecutor(getUrl(), inv);
                CompletableFuture<AppResponse> appResponseFuture =
                        currentClient.request(inv, timeout, executor).thenApply(obj -> (AppResponse) obj);
                // save for 2.6.x compatibility, for example, TraceFilter in Zipkin uses com.alibaba.xxx.FutureAdapter
                FutureContext.getContext().setCompatibleFuture(appResponseFuture);
                AsyncRpcResult result = new AsyncRpcResult(appResponseFuture, inv);
                result.setExecutor(executor);
                return result;
            }
        } catch (TimeoutException e) {
            throw new RpcException(RpcException.TIMEOUT_EXCEPTION, "Invoke remote method timeout. method: " + invocation.getMethodName() + ", provider: " + getUrl() + ", cause: " + e.getMessage(), e);
        } catch (RemotingException e) {
            throw new RpcException(RpcException.NETWORK_EXCEPTION, "Failed to invoke remote method: " + invocation.getMethodName() + ", provider: " + getUrl() + ", cause: " + e.getMessage(), e);
        }
    }

**Comment by xiaoheng1** [comment]
pr https://github.com/apache/dubbo/pull/7410

**Comment by AlbumenJ** [comment]
Close #6902 via #7410

**Comment by owen200008** [comment]
i think it make a bug，when destroy 
call HeaderExchangeChannel.close(timeout) it set 
this.closed = true;
and when call HeaderExchangeChannel.close() it do nothing
