### ISSUE TITLE
存在多个@Active扩展点，同时存在扩展点的wapper实现，多个@Active扩展点排序时，由于没有在wapper上指定@Active注解存在NPE

### ISSUE THREAD

**Issue by luojinbai** [apache/dubbo#6907]
Environment
Dubbo version: 2.7.9
Operating System version: windows
Java version: jdk. 1.8

**Comment by xiaoheng1** [comment]
see https://github.com/apache/dubbo/issues/7176
&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
This issue is the same with #7176 and is planing to fix in the next release.

Please feel free to reopen if you have any question.
