### ISSUE TITLE
dubbo中可以实现请求调用时，使用AOP拦截获取ProceedingJoinPoint吗？

### ISSUE THREAD

**Issue by develpoerX** [apache/dubbo#6918]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by horizonzy** [comment]
你的目的是什么，这个AOP是基于Bean的吧，如果要基于Rpc做拦截的话，推荐使用SPI去加载自定义的Filter

**Comment by develpoerX** [comment]
是的，我看到springboot里面基于bean的AOP可以使用ProceedingJoinPoint参数。我想将dubbo做类似的功能，我注意到了您说的dubbo中提供的Filter，我自己继承Filter实现了RPC拦截的一个过滤器，但是在我的新模块中它并没有生效，我把它放在之前的旧的代码模块里面，它就可以生效。请问这是为什么？（我已经配置了META-INF.dubbo文件）
2.顺便请教一下，您有将dubbo和resilience4j进行结合的案例吗？希望能找一个参考

>

**Comment by develpoerX** [comment]
> 你的目的是什么，这个AOP是基于Bean的吧，如果要基于Rpc做拦截的话，推荐使用SPI去加载自定义的Filter

是的，我看到springboot里面基于bean的AOP可以使用ProceedingJoinPoint参数。我想将dubbo做类似的功能，我注意到了您说的dubbo中提供的Filter，我自己继承Filter实现了RPC拦截的一个过滤器，但是在我的新模块中它并没有生效，我把它放在之前的旧的代码模块里面，它就可以生效。请问这是为什么？（我已经配置了META-INF.dubbo文件）
2.顺便请教一下，您有将dubbo和resilience4j进行结合的案例吗？希望能找一个参考

**Comment by horizonzy** [comment]
1.新模块和旧模块是什么意思
2.没有使用过

**Comment by dkisser** [comment]
想要集成熔断框架可以参考 #6877

**Comment by dkisser** [comment]
#6877

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it.
