### ISSUE TITLE
Waiting server-side response timeout by scan timer. start time: 2020-11-17 19:09:55.808, end time: 2020-11-17 19:09:56.820, client elapsed: 0 ms, server elapsed: 1012 ms, timeout: 1000 ms,

### ISSUE THREAD

**Issue by phpisfuture** [apache/dubbo#6919]
dubbo 2.7.8

有时候会出问题下面的问题，等一会自己又好了，Waiting server-side response timeout by scan timer具体是做什么呢，什么情况下及为什么会出现这个问题呢，求权威大佬帮忙科普一下，十分感谢。

`Waiting server-side response timeout by scan timer. start time: 2020-11-17 19:09:55.808, end time: 2020-11-17 19:09:56.820, client elapsed: 0 ms, server elapsed: 1012 ms, timeout: 1000 ms,`

**Comment by phpisfuture** [comment]
> 这个是consuemer这边的一个超时检测定时器。consumer这边发出了rpc，在timeout时间内如果没有返回值的话，就会自动报错。

dubbo的 consumer 发出 rpc 请求的超时处理是通过 超时检测定时器 扫描 实现的吗？

**Comment by horizonzy** [comment]
嗯。Consumer这边有一个定时扫描器去检查发起的RPC，`org.apache.dubbo.remoting.exchange.support.DefaultFuture.TimeoutCheckTask`, 见这个类

**Comment by phpisfuture** [comment]
> 嗯。Consumer这边有一个定时扫描器去检查发起的RPC，`org.apache.dubbo.remoting.exchange.support.DefaultFuture.TimeoutCheckTask`, 见这个类

好的，谢谢大佬的解答，十分感谢，我去看下源码。

**Comment by wangwanchao** [comment]
> 这个是consuemer这边的一个超时检测定时器。consumer这边发出了rpc，在timeout时间内如果没有返回值的话，就会自动报错。

这个超时和consumer.xml中设置的超时有关系吗？xml设置全局超时5s，调用1s就报超时了

**Comment by horizonzy** [comment]
有关系，如何配置查阅dubbo文档

**Comment by youngbird1** [comment]
> 嗯。Consumer这边有一个定时扫描器去检查发起的RPC，`org.apache.dubbo.remoting.exchange.support.DefaultFuture.TimeoutCheckTask`, 见这个类

consumer首次调用下游接口必出现该错误,后续的调用又都是正常的。  查看gc日志排除gc造成的影响, 请教大佬首次调用时有哪些 原因可能导致耗时变长呢？

**Comment by horizonzy** [comment]
> consumer首次调用下游接口必出现该错误,后续的调用又都是正常的。 查看gc日志排除gc造成的影响, 请教大佬首次调用时有哪些 原因可能导致耗时变长呢？

需要确定一下耗时在哪一部分。先明确是服务端还是客户端，可以通过arthas跟踪一下。
