### ISSUE TITLE
[Discuss] RegistryDirectory.refreshInvoker maybe have concurrency problems

### ISSUE THREAD

**Issue by qupingyao** [apache/dubbo#6923]
**Environment**

- Dubbo version: 2.7.x
- Operating System version: macOs
- Java version: jdk8

**### Steps to reproduce this issue**

1. new provider regist and  app-config change at the same time

since version 2.7.0  , register-center and  config-center is separated from zookeeper node
they can notify consumer at the same time in two thread with no lock
for example in class RegistryDirectory(urlInvokerMap : [invoker-a])
thread1 - new provider regist  , invoke method RegistryDirectory.refreshInvoker([invoker-a,invoker-b,invoker-c])
thread2 - just notify config change  , invoke method RegistryDirectory.refreshInvoker([])

this issue may similar to #6763 

### Expected Result

two thread can not invoke RegistryDirectory.refreshInvoker at the same time

### Actual Result

- step1. thread1 start invoke RegistryDirectory.refreshInvoker([invoker-a,invoker-b,invoker-c]) , urlInvokerMap  : [invoker-a]
- step2. thread2 start invoke RegistryDirectory.refreshInvoker([]) , urlInvokerMap  :  [invoker-a]
- step3. thread1 invoke into RegistryDirectory.toInvokers([invoker-a,invoker-b,invoker-c]) , urlInvokerMap  :  [invoker-a]
- step4. thread2 invoke into RegistryDirectory.toInvokers([invoker-a])  , urlInvokerMap  :  [invoker-a]
- step5. thread1 end invoke RegistryDirectory.refreshInvoker([invoker-a,invoker-b,invoker-c]) , urlInvokerMap  : [invoker-a,invoker-b,invoker-c]
- step6. thread2 end invoke RegistryDirectory.refreshInvoker([]) , urlInvokerMap  :  [invoker-a]

after step6 , invoker-b , invoker-c lost  after provider regist

P.S : the java keyword synchronized on method RegistryDirectory.notify is invalid at this situatation

**Comment by xiaoheng1** [comment]
similar to  https://github.com/apache/dubbo/issues/7125

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
related with #7125
