### ISSUE TITLE
关于2.7.8服务治理问题

### ISSUE THREAD

**Issue by houwen0** [apache/dubbo#6926]
我使用2.7.8做服务治理，发现不生效。我与2.7.0做了对比，具体如下：
![image](https://user-images.githubusercontent.com/19197938/99645075-b5910b80-2a89-11eb-928f-6819ebd57015.png)

![image](https://user-images.githubusercontent.com/19197938/99645104-c0e43700-2a89-11eb-8b4f-e4697096789b.png)

请问这是版本bug，还是可以通过配置解决此问题？

**Comment by manzhizhen** [comment]
具体是哪里不一样呢？

**Comment by houwen0** [comment]
dubbo-admin设置如下：









AbstractDirectory类中public URL getConsumerUrl()方法2.7.0、2.7.5版本中获取地址为：


但是在2.7.8中，获取的是这个地址。导致我服务治理时，黑名单不生效

















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 中午1:15
收件人:&nbsp;"apache/dubbo"<dubbo@noreply.github.com&gt;;
抄送:&nbsp;"Stuart"<116584273@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo] 关于2.7.8服务治理问题 (#6926)





 
具体是哪里不一样呢？

**Comment by manzhizhen** [comment]
你好，这个问题在即将发布的2.7.9版本会修复，参见：611be166cbd2cac263410f079e43894ec4dfe6eb （fix #6426, replace unnecessary directoryUrl with consumerUrl (#6666)）

**Comment by houwen0** [comment]
好的&nbsp; &nbsp;多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 上午9:31
收件人:&nbsp;"apache/dubbo"<dubbo@noreply.github.com&gt;;
抄送:&nbsp;"Stuart"<116584273@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/dubbo] 关于2.7.8服务治理问题 (#6926)





 
你好，这个问题在即将发布的2.7.9版本会修复，参见：611be166cbd2cac263410f079e43894ec4dfe6eb （fix #6426, replace unnecessary directoryUrl with consumerUrl (#6666)）
