### ISSUE TITLE
AbstractConfig.toString will print password in plain text

### ISSUE THREAD

**Issue by FavorMylikes** [apache/dubbo#6930]
https://github.com/apache/dubbo/blob/4df7e2fc1a8e6a2680d7554ac80ae5857c454229/dubbo-common/src/main/java/org/apache/dubbo/config/AbstractConfig.java#L522

`Logger` will call toString() in format process.

https://github.com/apache/dubbo/blob/12c18f6bb0d03f5ad1990d092a53b10cb7afbb72/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L768

We should hide the important information to up to Huawei's technical standards.

**Comment by AlbumenJ** [comment]
close #6930 via #6931
