### ISSUE TITLE
dubbo升级到2.7.8后启动失败

### ISSUE THREAD

**Issue by RongXiong2016** [apache/dubbo#6938]
jdk1.8+spring boot2.0.6 +nacos1.3.3+dubbo2.7.8

从dubbo2.7.1&nacos1.0.0升级到上述版本后，启动失败。原来该版本能正常启动

1.以main方法启动没有报错信息，启动后直接tomcat停止
2.以tomcat启动 报错堆栈如下
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'orderPrepackConfirmServiceImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'xxx' available: expected single matching bean but found 2: getOrderPrePackService,@Reference(version=1.0.0) com.leqee.wms.server.api.processor.inside.OrderPrePackService`

**Comment by horizonzy** [comment]
bean重复了。OrderPrePackService检查一下这个bean的注入方式，是否在不同地方生成了多个
