### ISSUE TITLE
@Wrapper 注解定义时缺少 @Retention(RetentionPolicy.RUNTIME) 导致实际无法生效

### ISSUE THREAD

**Issue by soft641400589** [apache/dubbo#6946]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9-SNAPSHOT
* Operating System version: Mac OS 10.15.7
* Java version: 1.8.0_261

### Steps to reproduce this issue

1. I Attempt to test extension @Wrapper's matches() and  mismatches()，but I Seems to fount a bug，The @Wrapper can not fetch in Class ExtensionLoader around line 652 when I invoke the code “ Wrapper wrapper = wrapperClass.getAnnotation(Wrapper.class);”

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

1. I can use @Wrapper's matches() and  mismatches() correct

### Actual Result

What actually happens?

1.I can not get Class Annotation when  I Already declared @Wrapper

If there is an exception, please attach the exception trace:

![image](https://user-images.githubusercontent.com/24708234/100401605-ed551000-3094-11eb-89ff-4468f272ae55.png)

![image](https://user-images.githubusercontent.com/24708234/100347425-4cc50880-3020-11eb-8737-cb6b47bbfa43.png)

**Comment by AlbumenJ** [comment]
close #6946 via #6947
