### ISSUE TITLE
dubbo2.7.8 windows下面打包失败

### ISSUE THREAD

**Issue by pmz0320** [apache/dubbo#6951]
- 进入admin目录下 执行命令：
> mvn package -Dmaven.test.skip=true
- 泛型报错：
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project dubbo-registry-api: Compilation failure
[ERROR] D:\app\dubbo-dubbo-2.7.8\dubbo-registry\dubbo-registry-api\src\main\java\org\apache\dubbo\registry\client\ServiceDiscoveryRegistry.java:[753,28] 错误: 不兼容的类型: 推断类型不符合上限
[ERROR]     推断: List<? extends Object>
[ERROR]     上限: List<URL>,Object

**Comment by huibinliupush** [comment]
今天也遇到这个问题  你最后是怎么解决的？

**Comment by AlbumenJ** [comment]
@huibinliupush 

> 今天也遇到这个问题 你最后是怎么解决的？

请问是否可以提供具体的报错信息（包括环境版本信息，编译的 commit 信息，编译报错的具体报错信息）？

你也可以开启一个新 issue 来反馈，我们会尽快回复的~
