### ISSUE TITLE
dubbo最新版线程模型还是用的 netty 吗

### ISSUE THREAD

**Issue by tsing-dong** [apache/dubbo#6952]
最新版本的Dubbo线程模型还是基于netty做的吗 如果是 文档什么时候能出来啊

**Comment by xiaoheng1** [comment]
我理解的新线程模型还是基于 netty 的，只是在同步调用的时候，阻塞是在业务线程上。
从网上盗了一张图，希望对你有帮助。


![image](https://user-images.githubusercontent.com/12539730/100689757-11c82980-33c0-11eb-88c4-63934effa13b.png)

**Comment by tsing-dong** [comment]
谢谢
