### ISSUE TITLE
simplified="true" 的问题

### ISSUE THREAD

**Issue by zzzzzmh** [apache/dubbo#6956]
2.7.8 版本

<dubbo:registry address="zookeeper://localhost:2181" simplified="true"/>
<dubbo:metadata-report address="redis://127.0.0.1:6379" sync-report="true"/>

zk里的url并没有简化，还需要怎么配置吗？

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues.
