### ISSUE TITLE
Nacos 注册中心不支持内部接口 serviceName 含有$

### ISSUE THREAD

**Issue by ShenFeng312** [apache/dubbo#6971]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version:2.7.8
* Operating System version: Mac
* Java version: 1.8

### Steps to reproduce this issue
```java
public interface Provider {
    String get(String args);
    interface In{
        String get(String args);
    }
}

```
目前nacos 不支持Provider$In 接口注册。因为nacos 不能携带$

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by ShenFeng312** [comment]
我在获取到ServiceName 后用'.'替换了'$'  不知道这样改会不会造成其他影响

**Comment by ShenFeng312** [comment]
@chickenlj

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
