### ISSUE TITLE
registry twice consumer service use @DubboReference annotation

### ISSUE THREAD

**Issue by JstCoding** [apache/dubbo#7003]
* Dubbo version: 2.7.8
* Operating System version: window
* Java version: 1.8
* Registry center: zookeeper 

example:

class A:
@DubboReference
ExampleService exampleSerivce

class B:
@DubboReference(check =false)
ExampleService exampleService;

where project start up, get a warm level log about zookeeper registry consumer fail, consumer exampleService registry twice to zookeeper
such as:

 org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dubbo/net.xxxx.service,ExampleService/consumers/xxxxx

**Comment by yuxiao97** [comment]
Maybe you use JavaConfig reference dubbo service, like this:
```
@Configuration
public class DubboServiceReferenceConfig {

    @DubboReference(version = "${dubbo.application.version}", check = false)
    private UserInfoService userInfoService;

    @Bean
    public UserInfoService userInfoService() {
        return userInfoService;
    }
    
}
```
Then use @Autowired annotation on your consumer service.

**Comment by kylixs** [comment]
This bug has been fixed: https://github.com/apache/dubbo/pull/7383

**Comment by kylixs** [comment]
> Maybe you can use JavaConfig reference dubbo service, like this:
> 
> ```
> @Configuration
> public class DubboServiceReferenceConfig {
> 
>     @DubboReference(version = "${dubbo.application.version}", check = false)
>     private UserInfoService userInfoService;
> 
>     @Bean
>     public UserInfoService userInfoService() {
>         return userInfoService;
>     }
>     
> }
> ```
> 
> Then use @Autowired annotation on your consumer service.

Only need to use @DubboReference to declare and register the reference bean, other places can be injected with `@Autowired`.
 
```java
@Configuration
public class DubboReferenceConfig {

    @DubboReference(version = "${dubbo.application.version}")
    private UserInfoService userInfoService;

    @DubboReference(version = "${dubbo.application.version}")
    private FooService fooService;
    ...
}
```

```java
@Service
public class MyService {
     @Autowired
     private UserInfoService userInfoService;
}
```

**Comment by kylixs** [comment]
This can work in Dubbo 3: https://github.com/apache/dubbo/pull/7383 
This kind of reference annotation configuration is very clear and can be recommended to everyone.
