### ISSUE TITLE
No clear plan for dubbo 3.0 ?

### ISSUE THREAD

**Issue by wangyjx** [apache/dubbo#7006]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

There is never a clear release date disclosed for Dubbo 3.0.

From 2018, you started to talk about "dubbo 3.0 is coming, blablabla", but at the end of 2020,  where is it?  what is the status now? No clear plan, no clear milestone?

This is the way you manage a project ?    Maybe it is  less important 11.11, 12.12 in Alibaba ?  If so, please don’t PUA the users, stop barking how good the 3.0 is.

**Comment by pangshuqiang** [comment]
up up up ~~~

**Comment by AlbumenJ** [comment]
![image](https://user-images.githubusercontent.com/9292748/103358074-b76dd600-4aef-11eb-9c3f-2dc686589119.png)

Currently, the development of 3.0 version is in progress. You can also view these changes in `3.0` branch.

**Comment by clovedin** [comment]
no KPI

**Comment by CrazyHZM** [comment]
3.0 has been released, you can follow the recent released note.
