### ISSUE TITLE
2.7版本负载均衡还是按照方法负载吗

### ISSUE THREAD

**Issue by shangwq** [apache/dubbo#7017]
假如现在有同一个提供者部署了两台服务器A和B，A中多出了一个方法，消费者调用多出的那个方法的时候 2.6 和 2.7 版本的调用逻辑不太一致
2.6版本是总能找到有那个方法的服务；
2.7版本是随机找两台服务中的一个，所以会出现有时候调用正常，有时候调用失败的情况。

经看源码，这部分逻辑2.7版本重写了，请问要怎么处理这种情况

**Comment by kimmking** [comment]
服务上加版本，或者用tag

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
