### ISSUE TITLE
消费者dubbo2.7.7 , 生产者2.7.3, zk 上 生产者的consumers下注册了消费者多个相同的节点

### ISSUE THREAD

**Issue by lydong09** [apache/dubbo#7030]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Java version: 1.8

消费者使用
@DubboReference(protocol = "dubbo",registry = "refundDubboCenter")
    private BoRefundInfoService boRefundInfoService;

引用dubbo服务，一共在不同类里引用四次，在生产者的consumers下注册了四个相同的节点

**Comment by lydong09** [comment]
消费者dubbo2.7.7 , 生产者2.7.3, zk 上 生产者的consumers下注册了消费者多个相同的节点

**Comment by xiaoheng1** [comment]
can you provider a demo ?

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
