### ISSUE TITLE
ThreadPoolStatusChecker get wrong pool size message

### ISSUE THREAD

**Issue by YoungHu** [apache/dubbo#7033]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.x
* Operating System version: all
* Java version: all

### Steps to reproduce this issue

1. set dubbo thread pool to be 100 `<dubbo:protocol port="-1" dispatcher="all" threadpool="fixed" threads="100"/>` and enable dubbo monitor `<dubbo:monitor protocol="registry" interval="10000"/>`
2. start dubbo provider application
3. run `telnet localhost 20880` when show dubbo flag then run `status -l` will get pool size is 100
![image](https://user-images.githubusercontent.com/7418602/102473212-2b40c500-4092-11eb-9a5c-790ab97b76f2.png)

4. start a dubbo consumer applicaiton
5. do step 3 again, pool size change to 0
![image](https://user-images.githubusercontent.com/7418602/102473317-4a3f5700-4092-11eb-9ee1-1cb7e523cd50.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

step 5 should show pool size is 100

### Actual Result

step 5 show pool size is 0

### Troubleshooting

![image](https://user-images.githubusercontent.com/7418602/102474473-a6ef4180-4093-11eb-9612-b26902900bbe.png)
![image](https://user-images.githubusercontent.com/7418602/102475722-334e3400-4095-11eb-933b-ee33a569fc90.png)
![image](https://user-images.githubusercontent.com/7418602/102476965-b623be80-4096-11eb-9c35-ded4de40b3a5.png)
![image](https://user-images.githubusercontent.com/7418602/102477318-28949e80-4097-11eb-8a11-03b7e36d2bb2.png)
Then the executor changed to MonitorService executor with no pool.

### solution
best:
> add `map.put(Constants.SIDE_KEY, Constants.CONSUMER_SIDE);` into `AbstractInterfaceConfig.loadMonitor` method

temporary fix:
> dubbo monitor config like this
![image](https://user-images.githubusercontent.com/7418602/102570788-17916f00-4123-11eb-8d8b-5233d026b117.png)

**Comment by chickenlj** [comment]
I am a bit confused here.  Most of the time `status -l` should be used to monitor the status of the Dubbo provider threadpool. What's the meaning of showing the pool of the Consumer consuming MonitorService?

**Comment by YoungHu** [comment]
yes, `status -l` is use to monitor the status of the dubbo provider thread pool. but dubbo monitor haven't mark it self as consumer, so it override the provider thread pool data. finally, we got the wrong data.
