### ISSUE TITLE
Payload的数据可以配置成不受限制吗？我看默认是8M，怎样配置？

### ISSUE THREAD

**Issue by Scan-jha** [apache/dubbo#7042]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by jha042120** [comment]
我不想要每次超出之后，就去修改payload的大小。

**Comment by xiaoheng1** [comment]
自己配置一个很大的数就好了，在服务端可以配置。

**Comment by wujincheng2333** [comment]
dubbo使用的是单链接，数据过大会阻塞其他请求

**Comment by xiaoheng1** [comment]
这个确实，但是如果需要传输大量数据，有好的建议没？

**Comment by wujincheng2333** [comment]
> 这个确实，但是如果需要传输大量数据，有好的建议没？

rmi协议，rmi是短链接的

**Comment by xiaoheng1** [comment]
> > 这个确实，但是如果需要传输大量数据，有好的建议没？
> 
> rmi协议，rmi是短链接的

学习了。

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
