### ISSUE TITLE
AppResponse recreate only throw provider's exception stack

### ISSUE THREAD

**Issue by ldkjdk** [apache/dubbo#7043]
consumer only throw provider's exception stack,no have inclued consumer's call stack when provider's occured buz exception
consumer don't know where is call .
issue coce：
@Override
    public Object recreate() throws Throwable {
        if (exception != null) {
            // fix issue#619
            try {
                // get Throwable class
                Class clazz = exception.getClass();
                while (!clazz.getName().equals(Throwable.class.getName())) {
                    clazz = clazz.getSuperclass();
                }
                // get stackTrace value
                Field stackTraceField = clazz.getDeclaredField("stackTrace");
                stackTraceField.setAccessible(true);
                Object stackTrace = stackTraceField.get(exception);
                if (stackTrace == null) {
                    exception.setStackTrace(new StackTraceElement[0]);
                }
            } catch (Exception e) {
                // ignore
            }
            throw exception;
            // to new exception stack include providers stack for consumer 
            //throw new Exception(exception); 
        }
        return result;
    }

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
