### ISSUE TITLE
dubbo 2.7.8 Invalid token! 

### ISSUE THREAD

**Issue by WanT0011** [apache/dubbo#7050]
复现样例地址：[https://github.com/WanT0011/dubbo-Invalid-token.git](https://github.com/WanT0011/dubbo-Invalid-token.git) ，
问题出现存在偶发性，一旦启动出现，后续服务执行则会一直出现

### Environment
* Dubbo version: 2.7.8
* Operating System version: win 10；centos 6、7
* Java version: 1.8.0

环境说明：
        外部环境仅依赖nacos
    复现说明：
        本地快速启动nacos即可
        启动两个服务者
        启动消费者，会出现调用其中一个出现Invalid token!的异常，如果调用正常请重新启动消费者多试几次。
        出现的概率还是比较大的
        
    bug原因：
        调用到了服务端，url上的token发生了变化，导致token校验失败

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues.

**Comment by Hulk904** [comment]
为什么关闭了，2.7.12 还是偶发 invalid token,  ... consumer incorrect token is null
