### ISSUE TITLE
使用 dubbo:config-center namespace="devenv" 设置的namespace不生效，还是访问的默认dubbo命名空间

### ISSUE THREAD

**Issue by lidaoyang** [apache/dubbo#7052]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: 1.8
* dubbo-dependencies-zookeeper:2.7.8

### Steps to reproduce this issue
使用 dubbo:config-center namespace="devenv" 设置的namespace不生效，还是访问的默认dubbo命名空间

    <dubbo:config-center namespace="devenv" protocol="zookeeper" address="mse-xxxxxxx.zk.mse.aliyuncs.com:2181" check="true" group="DUBBO_GROUP" />

**Comment by kevinw66** [comment]
与这个ISSUE是一样的原因 [ISSUE-#6606](https://github.com/apache/dubbo/issues/6606) 
同时已经有了对应的PR [#6717](https://github.com/apache/dubbo/pull/6717)

**Comment by AlbumenJ** [comment]
close #7052 via #6717
