### ISSUE TITLE
RegistryConfig 注释似乎不全

### ISSUE THREAD

**Issue by super9du** [apache/dubbo#7057]
https://github.com/apache/dubbo/blob/d98d48914b139d6abb2139ea36e51e536713edfe/dubbo-common/src/main/java/org/apache/dubbo/config/RegistryConfig.java#L76-L80

只列举了 1，没有列举其他

**Comment by CrazyHZM** [comment]
Thank you for your feedback, the community will continue to improve the code comments, and you are also welcome to participate in and improve together.
