### ISSUE TITLE
Dubbo framework code generation and usage problems

### ISSUE THREAD

**Issue by seedscoder** [apache/dubbo#7058]
- 如果使用Maven作为构建工具，加上官方提供的插件可以直接生成dubbo + grpc代码
   - ```xml
      <plugin>
          <groupId>org.xolstice.maven.plugins</groupId>
          <artifactId>protobuf-maven-plugin</artifactId>
          <version>0.5.1</version>
          <configuration>
              <protocArtifact>com.google.protobuf:protoc:3.7.1:exe:${os.detected.classifier}</protocArtifact>
              <pluginId>grpc-java</pluginId>
              <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
              <outputDirectory>build/generated/source/proto/main/java</outputDirectory>
              <clearOutputDirectory>false</clearOutputDirectory>
              <protocPlugins>
                  <protocPlugin>
                      <id>dubbo-grpc</id>
                      <groupId>org.apache.dubbo</groupId>
                      <artifactId>dubbo-compiler</artifactId>
                      <version>${dubbo.compiler.version}</version>
                      <mainClass>org.apache.dubbo.gen.grpc.DubboGrpcGenerator</mainClass>
                  </protocPlugin>
              </protocPlugins>
          </configuration>
          <executions>
              <execution>
                  <goals>
                      <goal>compile</goal>
                      <goal>compile-custom</goal>
                      <goal>test-compile</goal>
                      <goal>test-compile-custom</goal>
                  </goals>
              </execution>
          </executions>
      </plugin>
        ```
- 如果采用Gradle作为项目构建工具，官方支持生成dubbo + grpc组合的代码？如果可以，应该怎样配置？（Using Gradle as a project building tool, officially supports generating dubbo + grpc combination code? If so, how to configure）

**Comment by zhangj20122753** [comment]
any somebody know this question?
