### ISSUE TITLE
AccessLogFilter中为什么不在响应后将响应结果打印出来？

### ISSUE THREAD

**Issue by tastypinenut** [apache/dubbo#7063]
AccessLogFilter中详细的实现了请求参数的日志打印，但响应结果完全没有打印，也没有见到其他Filter进行日志打印，这是有特殊考虑吗？能否官方提供一个响应结果日志打印的功能

**Comment by wujincheng2333** [comment]
拿不到返回类型，请求类型可以拿到，有些还是void类型，你可以自己写个不为空的时候调用toString方法。但是toString自己重写。要考虑java基本数据类型和引用类型，集合类型，Map类型

**Comment by wujincheng2333** [comment]
还有个方法，直接转json字符串，就不用考虑类型了

**Comment by CrazyHZM** [comment]
Some response bodies are very large, and each response outputs logs, which will cause the log file to increase and the local disk occupies too large problems.
