### ISSUE TITLE
请教关于Dubbo源码阅读过程中的疑惑

### ISSUE THREAD

**Issue by JavaYZJ** [apache/dubbo#7064]
```java
public class ServiceAnnotationBeanPostProcessor implements BeanDefinitionRegistryPostProcessor, EnvironmentAware,
        ResourceLoaderAware, BeanClassLoaderAware {
private void registerServiceBeans(Set<String> packagesToScan, BeanDefinitionRegistry registry) {
        DubboClassPathBeanDefinitionScanner scanner =
                new DubboClassPathBeanDefinitionScanner(registry, environment, resourceLoader);
      // 省略部分代码
        for (String packageToScan : packagesToScan) {
            scanner.scan(packageToScan);
            Set<BeanDefinitionHolder> beanDefinitionHolders =
                    findServiceBeanDefinitionHolders(scanner, packageToScan, registry, beanNameGenerator);
            if (!CollectionUtils.isEmpty(beanDefinitionHolders)) {
                for (BeanDefinitionHolder beanDefinitionHolder : beanDefinitionHolders) {
                    registerServiceBean(beanDefinitionHolder, registry, scanner);
                }
       // 省略部分代码
            } 
        }
    }
}
```
源码中scanner.scan(packageToScan)底层会执行doScan,也是会返回关于@service的BeanDefinitionHolder的set集合，况且DubboClassPathBeanDefinitionScanner 继承了ClassPathBeanDefinitionScanner，重写的doScan方法是直接调用父类的doScan；
然而，源码中还有一步 findServiceBeanDefinitionHolders(scanner, packageToScan, registry, beanNameGenerator)，拿到的也是关于@service的BeanDefinitionHolder的set集合.我的理解是既然目的是拿到BeanDefinitionHolders, 那要么可以直接scanner.doSacn或者findServiceBeanDefinitionHolders就行，为何要重复两个步骤呢？请大家为我答疑解惑，谢谢

**Comment by wanghongenpin** [comment]
doScan是protected修饰的，没法直接调用；
看代码是scanner.scan(packageToScan)调用doScan多了注册@Service  bean流程，但是scan方法不返回注册的bean集合。
scanner.findCandidateComponents(packageToScan)会返回扫描到符合的bean集合，但是不会注册到Spring容器里。

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it.
