### ISSUE TITLE
dubbo2.7.7泛化调用配置

### ISSUE THREAD

**Issue by Daibhid666** [apache/dubbo#7084]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by Daibhid666** [comment]
dubbo2.7.7泛化调用具体是怎么配置的

**Comment by dkisser** [comment]
http://dubbo.apache.org/docs/v2.7/user/examples/generic-service/

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
