### ISSUE TITLE
从Dubbo2.7.3升级到Dubbo2.7.6之后，应用启动后的内存占用暴增

### ISSUE THREAD

**Issue by herist** [apache/dubbo#7088]
由于使用SpringAlibabaCloud 在从2.1.1.RELEASE 升级到 2.1.3.RELEASE之后，发现内存暴增了约4倍。
经过JProfile跟踪发现，占用内存的原因是Dubbo的相关类，
SpringAlibabaCloud 2.1.1.RELEASE 默认Dubbo2.7.3 （应用占内存大概是 0.5到2个G）
SpringAlibabaCloud 2.1.3.RELEASE 默认Dubbo2.7.6 （应用占内存大概是 2到8个G）
最后，经过调整版本配置，验证了确实如此：
在我把Dubbo版本配置到2.7.3之后，内存占用也降下来了（使用SpringAlibabaCloud 2.1.3.RELEASE + Dubbo2.7.3）
不知道Dubbo团队是升级了什么组件，导致了这个内存暴增的问题。

或者有什么配置选项，可以避免这种情况的发生？

![微信图片_20210108160302](https://user-images.githubusercontent.com/3771334/103989696-0f30cf00-51cb-11eb-92e7-ead5d5331a42.png)

**Comment by herist** [comment]
由于内存暴增，导致无法升级，只能退回来了

**Comment by chickenlj** [comment]
方便私下给我一份 dump 吗，InMemoryMetadataService 占了有多少空间
