### ISSUE TITLE
little bug

### ISSUE THREAD

**Issue by little-circle-circle** [apache/dubbo#7091]
org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient#calculateLeastDuration

    /**
     * Each interval cannot be less than 1000ms.
     */
    private long calculateLeastDuration(int time) {
        if (time / HEARTBEAT_CHECK_TICK <= 0) {
            return LEAST_HEARTBEAT_DURATION;
        } else {
            return time / HEARTBEAT_CHECK_TICK;
        }
    }

should be 

    /**
     * Each interval cannot be less than 1000ms.
     */
    private long calculateLeastDuration(int time) {
        if (time / HEARTBEAT_CHECK_TICK <= LEAST_HEARTBEAT_DURATION) {
            return LEAST_HEARTBEAT_DURATION;
        } else {
            return time / HEARTBEAT_CHECK_TICK;
        }
    }

write this function to org.apache.dubbo.remoting.utils.UrlUtils#getHeartbeat, maybe more appropriate

**Comment by vio-lin** [comment]
我也看到这个，建议楼主加下版本信息。会更瞩目一点

**Comment by little-circle-circle** [comment]
> 我也看到这个，建议楼主加下版本信息。会更瞩目一点
