### ISSUE TITLE
集群环境中使用直连提供者

### ISSUE THREAD

**Issue by rxxy** [apache/dubbo#7096]
http://dubbo.apache.org/zh/docs/v2.7/user/examples/explicit-target/
看到文档中有提到尽量不要在线上使用直连，但是如果线上环境使用k8s/swarm这样的集群时，他们已经有提供服务发现/负载均衡的功能，是否可以不使用注册中心直接使用直连去连接一个service的 vip。
不知会有其他的副作用吗?

**Comment by dkisser** [comment]
还是不建议这样使用。虽然服务端有负载均衡的功能，但是最终还是某个特定的容器节点和dubbo建立了连接。由于使用的是长连接，不会重新建立连接（除非连接断开），所以请求只会跑到你直连的那个容器中，这样负载均衡便会失效。

**Comment by rxxy** [comment]
感谢回复

这样看来和容器集群结合的最好方式还是得dubbo原生使用集群的注册中心，我看到有3.0-k8s分支。

除此之外还是需要在集群中部署好注册中心。

**Comment by gcdd1993** [comment]
@dkisser ，使用Dubbo的注册中心，例如`Redis Registry`，是否也是**只有在连接断开才会重新建立连接**？
