### ISSUE TITLE
fastJson序列化，泛型返回值导致内存不释放

### ISSUE THREAD

**Issue by nie312122330** [apache/dubbo#7098]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.x,2.7.x
* Operating System version: centos7.x
* Java version: jdk1.8

### Steps to reproduce this issue

1. 使用fastJson序列化
2. 接口返回值为泛型：如 RespVo<?, ?> add(SysGuestAddValid valid);
3. 持续调用该接口，导致内存一直不释放

问题应该发生在：
<T> T org.apache.dubbo.common.serialize.fastjson.FastJsonObjectInput.readObject(Class<T> cls, Type type) throws IOException, ClassNotFoundException

附临时解决方案：

   // 采用无锁方案，并发的时候即使不存在也没关系,顶多同一个签名的Type被写入两次，无伤大雅
    private final static Map<String, Type> typeList = Maps.newHashMapWithExpectedSize(8192);
    
    @Override
    @SuppressWarnings("unchecked")
    public <T> T readObject(Class<T> cls, Type type) throws IOException, ClassNotFoundException {
        String json = readLine();
        // 这里会导致 com.alibaba.fastjson.parser.ParserConfig.deserializers 缓存很多对象，只要序列化一次就会增加一个
        // --------------以下为临时解决方案，等待官方修复----------------
        String typeSigner = type.toString();
        Type existType = typeList.get(typeSigner);
        if (null != existType) {
            return (T)JSON.parseObject(json, existType);
        }
        typeList.put(typeSigner, type);
        // -------------------------------------
        return (T)JSON.parseObject(json, type);
    }

**Comment by dkisser** [comment]
参考fastjson内存泄露问题：[https://www.cnblogs.com/liqipeng/p/11665889.html](url)。本地测试，并不是一个实例就会新增一个缓存，而是当你的泛型有多少个就会有多少个缓存，例如：返回RespVo<User> 、RespVo<Product>，这才会有两个缓存。你内存泄露应该是泛型类太多，直接返回数据对象就好没必要用泛型类做返回值
