### ISSUE TITLE
dubbo使用nacos作为注册中心，服务却在nacos的配置列表下展示

### ISSUE THREAD

**Issue by mameng1992** [apache/dubbo#7116]
### Environment

* Dubbo version: 2.7.8
* Java version: 1.8

dubbo服务的配置文件内容如下：
![image](https://user-images.githubusercontent.com/37826586/105169810-0939d700-5b57-11eb-95eb-70b9b2664fef.png)

dubbo服务启动后，去nacos上查看，服务却在nacos的配置列表下：
![image](https://user-images.githubusercontent.com/37826586/105170017-5158f980-5b57-11eb-8461-7b0ee7b7d98e.png)
而服务列表下空空如也。。。。。。。。。。

**Comment by ZhuoSir** [comment]
解决了吗 ？我也出现这个问题

**Comment by mameng1992** [comment]
> 解决了吗 ？我也出现这个问题

没有，这个问题是nacos-server开启了权限认证后出现的。我debug后发现：this.nacosRestTemplate.exchangeForm(url, header, params, body, method, String.class)这个方法去注册到nacos-server返回的是403的状态码，具体日志如下：
{"timestamp":"2021-01-27T09:06:18.824+0000","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/ns/instance/list"}
，但日志没在控制台打印出来。
我继续排查后发现：SecurityProxy这个类读取properties中的用户名、密码都为空；所以就出现了上面的异常。

**Comment by AlbumenJ** [comment]
配置列表中的信息应该是应用级服务发现的服务名映射信息

**Comment by KeRan213539** [comment]
截图中配制列表中的是元数据信息, 服务没注册上应该是因为nacos开启了鉴权. 请检查配制是否正确. 如果能确定是BUG,请提供更多信息以便复现

**Comment by nickwongwong** [comment]
> > 解决了吗 ？我也出现这个问题
> 
> 没有，这个问题是nacos-server开启了权限认证后出现的。我debug后发现：this.nacosRestTemplate.exchangeForm(url, header, params, body, method, String.class)这个方法去注册到nacos-server返回的是403的状态码，具体日志如下：
> {"timestamp":"2021-01-27T09:06:18.824+0000","status":403,"error":"Forbidden","message":"unknown user!","path":"/nacos/v1/ns/instance/list"}
> ，但日志没在控制台打印出来。
> 我继续排查后发现：SecurityProxy这个类读取properties中的用户名、密码都为空；所以就出现了上面的异常。

跟这个问题有点像
#7075 
不过确实配置太多有一定迷惑性，403就是权限问题了
尝试下上显式带上用户名
`dubbo.registry.address=nacos://dnacos.now.com:80?username=nacos&password=nacos&namespace=XXX`

**Comment by ConnorLH** [comment]
> 尝试下上显式带上用户名
> `dubbo.registry.address=nacos://dnacos.now.com:80?username=nacos&password=nacos&namespace=XXX`

解决了问题

**Comment by jgswp** [comment]
问题解决了吗？我也发现了这个问题，这么不严谨的吗

**Comment by qinyi8888** [comment]
https://github.com/apache/dubbo/issues/7598#issuecomment-838133590
可以试试这个看
nacos版本：1.4.1
dubbo版本：2.7.8
配置如下：
dubbo:
   registry:
      address: nacos://127.0.0.1:8848?username=nacos&password=nacos
      use-as-metadata-center: false
      use-as-config-center: false
  
  添加上可以去掉，后续再测添加上之后是否会有其他影响。
