### ISSUE TITLE
如何在 dubbo 2.7.8  rest consumer端 自定义增加 header

### ISSUE THREAD

**Issue by ywww** [apache/dubbo#7123]
如何在 dubbo 2.7.8  rest consumer端 自定义增加 header

**Comment by sourirer** [comment]
目前根据梳理的代码来看，即使在2.7.9-SNAPSHOT中也是没有这个功能的。
目前我打算按以下两种方案来进行处理：

1，可以在reference标签或注解中，直接设定不变header值，增加对应的属性的处理逻辑；

2，在调用的时候，在RpcContext中，设置rest-request-headers这样的key对应的attachement，然后在新增filter进行处理。

麻烦 @AlbumenJ 看一下这样处理可否？可以的话我这两天弄一下提个pr。

**Comment by AlbumenJ** [comment]
@sourirer 个人觉得第二种会好一些。

不过第二种需要考虑的问题有：
1. 添加的 header 应该是类似 Map 的结构，要考虑下这些参数怎么传
2. 添加的 header 的有效周期，是只有一次请求有效还是永久有效，还是说分成两种 key 来做

另外的一些建议：
1. 添加后的对应文档要及时更新到官网
2. 对应单侧需要完善，最好是也提交相关实例 samples 到 dubbo-samples

**Comment by sourirer** [comment]
> @sourirer 个人觉得第二种会好一些。
> 
> 不过第二种需要考虑的问题有：
> 
> 1. 添加的 header 应该是类似 Map 的结构，要考虑下这些参数怎么传
> 2. 添加的 header 的有效周期，是只有一次请求有效还是永久有效，还是说分成两种 key 来做
> 
> 另外的一些建议：
> 
> 1. 添加后的对应文档要及时更新到官网
> 2. 对应单侧需要完善，最好是也提交相关实例 samples 到 dubbo-samples

我表达错误了，不是两种方案，是两个都需要做，然后第一个用来传递不变的header。第二个用来传递每次请求所需的定制化header。
然后，header都是一次请求生效，不进行永久保存，每次请求filter再次处理，结构我会参考metrics用逗号分隔的字符串来做，这样和原生header也比较像。

不过有个问题是，我不是很懂如何在这个场景下写单测， @ywww 能描述一下你们的使用场景么？设置之后如何使用。

**Comment by sourirer** [comment]
> 如何在 dubbo 2.7.8 rest consumer端 自定义增加 header

hello，通过沟通和本人测试，在rest中，使用dubbo的context的attachement来进行header传递，在header中格式为：
key=value  的方式，在提供者端可以通过  context的attachement获得，demo代码如下：

Consumer：
        RpcContext.getContext().setAttachment("clientName", "demo");
        RpcContext.getContext().setAttachment("clientImpl", "dubbo");

Provider:
        RpcContext.getContext().getAttachment("clientName");
        RpcContext.getContext().getAttachment("clientImpl");

如对整体流程感兴趣，可以关注
       org.apache.dubbo.rpc.protocol.rest.RpcContextFilter 中的两个filter方法。

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it
