### ISSUE TITLE
[Bug] Subscribe concurrency problem when zookeeper recover.

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#7125]
### Environment

* Dubbo version: 2.7.2-SNAPSHOT
* Java version: jdk8

### Steps to reproduce this issue

1. stop zookeeper, wait 60s.
2. start zookeeper.
3. FailedSubscribedTask.doSubscribe() and ChildListener will trigger concurrently.
![image](https://user-images.githubusercontent.com/22524871/105461444-322da980-5cc8-11eb-9473-163655b22e36.png)

![image](https://user-images.githubusercontent.com/22524871/105461485-407bc580-5cc8-11eb-9097-41727d2877fd.png)

There is the reason.  
FailedSubscribedTask.doSubscribe() will get three category nodes `providers, consumers, configurators` and notify.
When get `providers` nodes, the providers nodes not registerd yet.  because it will get consumers and configurators nodes, then notify. So this situation notify the registryDirectory refreshInvoker will after below situation. So the invokers will be clear.

org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.CuratorWatcherImpl#process will get `providers` and notify. When get `providers` node, the providers nodes already register. But this situation to refresh invokers before above situation, the the invokers will be created and clear.

 The log info will show this situation.

```
[INFO ] 2021-01-21 20:35:43.156 [localhost-startStop-1-EventThread] [org.apache.dubbo.registry.support.AbstractRegistry] [] -  [DUBBO] Notify urls for subscribe url consumer://1.1.1.1/com.horizonzy.xxxx.common.dubbo.TaskOpsDubboSer
vice?application=dmc-web&category=providers,configurators,routers&check=false&dubbo=2.0.2flag=blue&interface=com.horizonzy.xxxx.common.dubbo.TaskO
psDubboService&lazy=false&methods=hello&owner=horizon&pid=1&release=2.7.2-SNAPSHOT&revision=1.0.0-20201118.023858-6&shared=true&side
=consumer&sticky=false&timeout=30000&timestamp=1611230130482, urls: [dubbo://2.2.2.2:20885/com.horizonzy.xxxx.c
ommon.dubbo.TaskOpsDubboService?acl=false&anyhost=true&app_code=ddc-operator&application=ddc-operator&bean.name=com.horizonzy.xxxx.common.dubbo.TaskOpsDubboService&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.horizonzy.xxxx.common.dubbo.TaskOpsDubboService&methods=enableTask,updateTask,updateTaskQuartz,disableTask,executeTask,deleteTask,createTask&owner=xueyu.zhang&pid=25146&pro_code=DDC&release=2.7.2-SNAPSHOT&sdk_version=2.7.2&side=provider&t
imestamp=1610417681594], dubbo version: 2.7.2-SNAPSHOT, current host: 1.1.1.1



[INFO ] 2021-01-21 20:35:43.157 [DubboRegistryRetryTimer-thread-1] [org.apache.dubbo.registry.support.AbstractRegistry] [] -  [DUBBO] Notify urls for subscribe url consumer://1.1.1.1/com.horizonzy.xxxx.common.dubbo.TaskOpsDubboServ
ice?application=dmc-web&category=providers,configurators,routers&check=false&dubbo=2.0.2&flag=blue&interface=com.horizonzy.xxxx.common.dubbo.TaskOp
sDubboService&lazy=false&methods=hello&owner=horizon&pid=1&release=2.7.2-SNAPSHOT&revision=1.0.0-20201118.023858-6&shared=true&side=
consumer&sticky=false&timeout=30000&timestamp=1611230130482, urls: [empty://1.1.1.1/com.horizonzy.xxxx.common.du
bbo.TaskOpsDubboService?application=dmc-web&category=providers&check=false&dubbo=2.0.2&flag=blue&interface=com.horizonzy.xxxx.common.dubbo.TaskOpsD
ubboService&lazy=false&methods=hello&owner=horizon&pid=1&release=2.7.2-SNAPSHOT&revision=1.0.0-20201118.023858-6&shared=true&side=co
nsumer&sticky=false&timeout=30000&timestamp=1611230130482, empty://1.1.1.1/com.horizonzy.xxxx.common.dubbo.TaskO
psDubboService?application=dmc-web&category=configurators&check=false&dubbo=2.0.2&&flag=blue&interface=com.horizonzy.xxxx.common.dubbo.TaskOpsDubboS
ervice&lazy=false&methods=hello&owner=horizon&pid=1&release=2.7.2-SNAPSHOT&revision=1.0.0-20201118.023858-6&shared=true&side=consume
r&sticky=false&timeout=30000&timestamp=1611230130482, empty://1.1.1.1/com.horizonzy.xxxx.common.dubbo.TaskOpsDub
boService?application=dmc-web&category=routers&check=false&dubbo=2.0.2&flag=blue&interface=com.horizonzy.xxxx.common.dubbo.TaskOpsDubboService&lazy
=false&methods=hello&owner=horizon&pid=1&release=2.7.2-SNAPSHOT&revision=1.0.0-20201118.023858-6&shared=true&side=consumer&sticky=fa
lse&timeout=30000&timestamp=1611230130482], dubbo version: 2.7.2-SNAPSHOT, current host: 1.1.1.1
```

**Comment by horizonzy** [comment]
@AlbumenJ

**Comment by xiaoheng1** [comment]
@horizonzy Lock lock = notifyLocks.computeIfAbsent(url.getServiceInterface(), k -> new ReentrantLock());
建议这里以 url 为维度进行加锁。存在这么两种场景：
1.服务端提供不同版本的服务
2.服务端多机部署
这两种场景下，都将被阻塞。

**Comment by horizonzy** [comment]
> @horizonzy Lock lock = notifyLocks.computeIfAbsent(url.getServiceInterface(), k -> new ReentrantLock());
> 建议这里以 url 为维度进行加锁。存在这么两种场景：
> 1.服务端提供不同版本的服务
> 2.服务端多机部署
> 这两种场景下，都将被阻塞。

这个探讨一下呢。我的理解是去订阅时都是订阅的是某个service下的节点，至于版本，只是节点的一个属性值。服务端多机器部署，也只是多一些节点而已。这些应该是service之下的一个层面，加锁的目的应该是上面的一个层面，获取某个service下的`providers, router, configuators` 的节点去进行通知而已。所以我这里使用的是service级别

**Comment by xiaoheng1** [comment]
> > @horizonzy Lock lock = notifyLocks.computeIfAbsent(url.getServiceInterface(), k -> new ReentrantLock());
> > 建议这里以 url 为维度进行加锁。存在这么两种场景：
> > 1.服务端提供不同版本的服务
> > 2.服务端多机部署
> > 这两种场景下，都将被阻塞。
> 
> 这个探讨一下呢。我的理解是去订阅时都是订阅的是某个service下的节点，至于版本，只是节点的一个属性值。服务端多机器部署，也只是多一些节点而已。这些应该是service之下的一个层面，加锁的目的应该是上面的一个层面，获取某个service下的`providers, router, configuators` 的节点去进行通知而已。所以我这里使用的是service级别

我理解的是订阅的 providers 节点，比如说现在 providers 下存在一个 ip 为 192.168.0.1 的节点，此时会调用 notify. 如果突然新增了一个 192.168.0.2 的节点，此时也会调用 notify 方法，这时候，我理解的这两个通过同时进行刷新，不需要基于 service 维度进行阻塞。

**Comment by horizonzy** [comment]
我理解你的意思了。正常的通知通过org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.CuratorWatcherImpl#process进行通知，只会存在一个订阅者，线程都是同一个，这里的lock可以重入，不会进行阻塞。

互斥的是FailedSubscribeTask的doSubscibe()和org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.CuratorWatcherImpl#process。

**Comment by horizonzy** [comment]
> > > @horizonzy Lock lock = notifyLocks.computeIfAbsent(url.getServiceInterface(), k -> new ReentrantLock());
> > > 建议这里以 url 为维度进行加锁。存在这么两种场景：
> > > 1.服务端提供不同版本的服务
> > > 2.服务端多机部署
> > > 这两种场景下，都将被阻塞。
> > 
> > 
> > 这个探讨一下呢。我的理解是去订阅时都是订阅的是某个service下的节点，至于版本，只是节点的一个属性值。服务端多机器部署，也只是多一些节点而已。这些应该是service之下的一个层面，加锁的目的应该是上面的一个层面，获取某个service下的`providers, router, configuators` 的节点去进行通知而已。所以我这里使用的是service级别
> 
> 我理解的是订阅的 providers 节点，比如说现在 providers 下存在一个 ip 为 192.168.0.1 的节点，此时会调用 notify. 如果突然新增了一个 192.168.0.2 的节点，此时也会调用 notify 方法，这时候，我理解的这两个可以同时进行刷新，不需要基于 service 维度进行阻塞。

重新确认了一下，process那里可能不是同一个线程，这块是Zookeeper的EventThread线程，会有你说的那个问题。同一个service的两次通知需要同步阻塞。
不过现在对RegistryDirectory的notify那里已经是同步的了。

**Comment by xiaoheng1** [comment]
> > > > @horizonzy Lock lock = notifyLocks.computeIfAbsent(url.getServiceInterface(), k -> new ReentrantLock());
> > > > 建议这里以 url 为维度进行加锁。存在这么两种场景：
> > > > 1.服务端提供不同版本的服务
> > > > 2.服务端多机部署
> > > > 这两种场景下，都将被阻塞。
> > > 
> > > 
> > > 这个探讨一下呢。我的理解是去订阅时都是订阅的是某个service下的节点，至于版本，只是节点的一个属性值。服务端多机器部署，也只是多一些节点而已。这些应该是service之下的一个层面，加锁的目的应该是上面的一个层面，获取某个service下的`providers, router, configuators` 的节点去进行通知而已。所以我这里使用的是service级别
> > 
> > 
> > 我理解的是订阅的 providers 节点，比如说现在 providers 下存在一个 ip 为 192.168.0.1 的节点，此时会调用 notify. 如果突然新增了一个 192.168.0.2 的节点，此时也会调用 notify 方法，这时候，我理解的这两个可以同时进行刷新，不需要基于 service 维度进行阻塞。
> 
> 重新确认了一下，process那里可能不是同一个线程，这块是Zookeeper的EventThread线程，会有你说的那个问题。同一个service的两次通知需要同步阻塞。
> 不过现在对RegistryDirectory的notify那里已经是同步的了。

嗯嗯，我刚看了下，确实是，那就没啥问题了。

**Comment by xiaoheng1** [comment]
顺便在提一个，zk 的通知顺序 dubbo 中保证吗？比如我先创建了一个节点，会触发一次通知，再创建一个节点，又会触发一次通知，此时如何保证第一次的通知先于第二次的通知？

**Comment by horizonzy** [comment]
> 顺便在提一个，zk 的通知顺序 dubbo 中有保证吗？比如我先创建了一个节点，会触发一次通知，再创建一个节点，又会触发一次通知，此时如何保证第一次的通知先于第二次的通知？

先通知变更，再查询。再拿查询的结果进行通知。

**Comment by xiaoheng1** [comment]
明白了，感谢。

**Comment by kevinw66** [comment]
不是很理解这块改动，既然RegistryDirectory的notify已经是同步了，还需要这锁吗？并且Zookeeper的通知是会被client的watcher阻塞的，如果你在notify里加个Thread.sleep(60)，你会发现zookeeper的第二个通知会等到第一个执行完成后才到来，这个ReentrantLock还需要吗？

**Comment by horizonzy** [comment]
RegistryDirectory的同步是refreshinvokers流程中比较靠后的了。这里的同步是为了同步FailedSubscribeTask中的doSubscribe和CuratorWatcher的process。 

FailedSubscribeTask主动去拉的zk时，还没有节点。 CuratorWatcher通知到来去拉的时候，有zk节点。但是CuratorWatcher的notify先于FailedSubscribeTask的notify执行了。导致最终的invokers被清空。

**Comment by xiaoheng1** [comment]
我的理解是要保证在多线程环境下，获取变化集合和通知是原子操作。
比如现在 zk 挂掉了，那么会有定时任务重新注册和订阅。假设注册还没有完成，获取到的集合为空，在执行 notify 之前，记为A，provider 注册到了zk，这时候也会获取到变化的集合，然后执行通知(有节点信息)，这时候会创建 invoker。再回到A，接着执行 notify，会将创建 invoker 销毁掉。

**Comment by kevinw66** [comment]
我测了一下zk挂掉重启，并没有走ZookeeperRegistry的notify，只走了FailedSubscribeTask的doSubscribe唉？

**Comment by horizonzy** [comment]
多试几次呢。provivder节点在zk重新连接后，会重新注册的，这个时候在consumer的zk重连订阅后，会收到通知

**Comment by kevinw66** [comment]
好的 感谢，我仔细看看
