### ISSUE TITLE
dubbo result结果输出时  返回了未定义的属性

### ISSUE THREAD

**Issue by akangah** [apache/dubbo#7128]
* Dubbo version: 2.7.8
* Operating System version: linux 
* Java version: java 11 

### Steps to reproduce this issue

1. dubbo result结果输出时  返回了未定义的属性
举例如下：
这是我的bean定义
 @Setter
 private List<T> result;
 private Integer pageNum;
现在输出为
{
  result:"",
  pageNum:"",
  class:"",
  success:""
}
请问class和success为什么会出现
2. 我只是定义了一个success的方法
public booleab isSuccess(){}
3. 我定义的isSuccess方法也要输出吗

**Comment by xiaoheng1** [comment]
我理解的是这个和 dubbo 没有关系，这个和最终的对象结果输出有关。

**Comment by AlbumenJ** [comment]
麻烦可以提供一个具体示例吗

**Comment by xiaoheng1** [comment]
就以你这个例子，定义 javabean
@Setter
private List result;
private Integer pageNum;
现在输出为
{
result:"",
pageNum:"",
class:"",
success:""
}

然后用 json 将 javabean 装成字符串输出

**Comment by sourirer** [comment]
这个我记得如果在泛化调用里面返回结果的时候会长这样。
另外，isSuccess这个方法名已经符合获取boolean的get方法格式了。
看起来应该是泛化调用返回的结果。通过反射获取属性。

**Comment by CrazyHZM** [comment]
There is no feedback for a long time, temporarily close this issue.
