### ISSUE TITLE
dubbox 协议 不兼容 的问题 官方能不能辛苦搞个方案啊 卡在 dubbox 里 出不来了呀

### ISSUE THREAD

**Issue by limingwei** [apache/dubbo#7140]
还有：
这种问题 适合在 issue 里聊么？
不然的话，该在哪里聊？
有群啥的么？

**Comment by huyunhaode** [comment]
The official of dubbo seems not to support dubbox and dubbo2.5.x

**Comment by huyunhaode** [comment]
&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
Currently dubbo and dubbo 2.5.x are no longer supported. Please try upgrade to 2.7.x or 2.6.x.
