### ISSUE TITLE
利用 dubbo 服务异步化能力完成应用异步调用改造讨论

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo#7142]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macos
* Java version: jdk1.8

### Steps to reproduce this issue

对于分层应用而言：

比如在 infrastructure 层做 dubbo 远程调用
在 service 层调用 infrastructure 层
在 controller 层调用 service 层

这种结构的应用如何利用 dubbo 的异步化能力完成改造？

我想达到的效果是在不大改代码的情况下，在 service 层完成异步改造。

**Comment by AlbumenJ** [comment]
请问是否可以提供更详细的信息，比如 service 层或 infrastructure 层的实现实例吗

**Comment by xiaoheng1** [comment]
比如在 infrastructure 层：

```
@Component
@Slf4j
public class ProviderIntegration {

    @Reference(check = false, timeout = 3000)
    private HelloService helloService;

    public String sayHello() {
        return helloService.sayHello();
    }
}
```

Service 层：

```
@Component
@Slf4j
public class ProviderServiceImpl {
    @Autowired
    private ProviderIntegration providerIntergration;

    public ApiResponse<String> doSomeThings(){
        String result = providerIntergration.sayHello();
        return ApiResponse.success(result);
    }
}

```
Controller 层：

```
@RestController
public class ProviderController {

    @Autowired
    private ProviderServiceImpl providerServiceImpl;

    @PostMapping("v1/xxx")
    public ApiResponse<String> doSomeThings() {
        return providerServiceImpl.doSomeThings();
    }
}
```

infrastructure 层是 rpc 调用，可能被 service 层的多个服务复用，在 service 层组装成相应的功能暴露给 controller 层。

但是按照现有的 dubbo 异步化，我的理解是需要在 infrastructure 层和 service 层同时做改造，工作量较大。我想达到的效果是只在 service 层做改造，利用 dubbo 提供的异步化，将现有的接口修改为异步调用。

**Comment by AlbumenJ** [comment]
> 但是按照现有的 dubbo 异步化，我的理解是需要在 infrastructure 层和 service 层同时做改造，工作量较大。我想达到的效果是只在 service 层做改造，利用 dubbo 提供的异步化，将现有的接口修改为异步调用。

由于 Dubbo 提供的 proxy 代理在业务中只能触及到 infrastructure 层，如果 infrastructure 层使用的是同步的方式，我的理解是 service 层的能力 Dubbo 是无法更改的。如果实在想要 service 层进行异步可以考虑对 infrastructure 层的同步接口先进行异步转换，然后后期再改造 infrastructure 层了

**Comment by xiaoheng1** [comment]
明白了，感谢。

我现在改造的方式是在 service 层使用 CompletedFuture 来进行的.例如：

```
CompletableFuture.supplyAsync(new Supplier<String>() {
    @Override
    public String get() {
        providerIntergration.sayHello();
    }
});
```
但是这种方式不太优雅。后面我这边还是对 intergration 层进行改造。
