### ISSUE TITLE
Filter不执行问题

### ISSUE THREAD

**Issue by cjx-object** [apache/dubbo#7151]
@Reference(version = "1.0.0",group = "XXX",owner = "XXX",filter = "rpcSendFilter")
使用注解配置Filter在多个类中引用, 其中某个类不设置filter, 会导致其他类中引用该接口 的filter失效

**Comment by xiaoheng1** [comment]
能提供一个 demo 不？

**Comment by CrazyHZM** [comment]
There is no feedback for a long time, temporarily close this issue.
