### ISSUE TITLE
dubbo广播模式调用有bug

### ISSUE THREAD

**Issue by mobile664042** [apache/dubbo#7173]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: win7
* Java version: jdk8

### Steps to reproduce this issue

consumer c1, 广播调用下面三个接dubbo接口方法：

 productor p1 执行结果p11

 productor p2 执行结果抛出异常RemoteAccessException

 productor p3 执行结果抛出异常IllegalArgumentException
 
消费者c1广播调用后，最终的取值是p1, p2, p3 的结果？ 
**很有可能取得是生产者p1的结果**

Pls. provide [GitHub address] to reproduce this issue.

生产者p2或者p3的结果
![image](https://user-images.githubusercontent.com/1433479/106897634-27463080-672e-11eb-81a7-802cf009abc8.png)

What do you expected from the above steps？

### Actual Result

很有可能取得是生产者p1的结果

```
Just put your stack trace here!
```

**Comment by mobile664042** [comment]
我试着通过修改下面的方法，修改了这个bug

![image](https://user-images.githubusercontent.com/1433479/106914958-7a28e380-6740-11eb-8f8d-6ae697f4fccb.png)

**Comment by xiaoheng1** [comment]
我觉得可以提前抛出异常，没有必要等到最后抛出异常

**Comment by dkisser** [comment]
https://github.com/apache/dubbo/issues/7173#issuecomment-773759592
我觉得还是要最后抛异常，若是某个服务报错就直接抛异常，后续服务就收不到广播通知，失去了广播的意义了。我理解的广播是并不关心结果的，主要是要通知各个服务。

**Comment by xiaoheng1** [comment]
Let’s discuss this issue:

In the broadcast mode, when a node has a problem, do you need to continue to notify other nodes in the future?

When a node is abnormal, then notify other nodes, such as broadcast notification to update the cache. In this case, this notification is not guaranteed for consistency. Assuming that there are n nodes, n-1 have been notified, and there is no node left Update, so on the whole, this notification is problematic. Therefore, throwing exceptions in advance and throwing exceptions at the end are both unreliable in terms of results. It is better to report errors in advance to reduce resource occupation.

**Comment by dkisser** [comment]
consumer通知所有provider全部失败，这种极端情况下仍采用全部通知后再抛异常这种策略，确实会导致consumer资源浪费的问题。但是考虑到另外一种场景，provider处理能力不一样可能部分调用存在超时情况，亦或是网络原因导致部分失败部分成功。这样都不能单纯的说是consumer端的这个通知有问题。
        所以我觉的应给这个广播模式添加策略选择，一是出错就结束，二是不管报错与否都要全部通知，三是使用一个阈值来控制，超过阈值就不再通知。
        我觉得使用阈值比较合理，通过阈值我们也可以设置-1让它出错就不再继续调用，设置任意0~100的数表示报错百分比到达这个值就不再继续调用

**Comment by xiaoheng1** [comment]
@dkisser 这个确实是一个问题，可能由于网络状况导致调用失败，但是 provider 端已处理成功。加阈值控制我觉得可行。@AlbumenJ 你的意见了？

**Comment by AlbumenJ** [comment]
I think it is reasonable to add a threshold for broadcast cluster. 

There are still some issues to consider:
- We need to ensure forward adaptability, so that users no need to worry about inconsistent behaviors due to upgrading to the new version.
- Is the threshold corresponding to a percentage or an absolute value. Such as 20 is means 20 percent of all providers or just 20 providers.
- Shall we notify users when an error occurs if they already specify a threshold

**Comment by xiaoheng1** [comment]
I agree with you.

there is another issue that needs to be considered:

it is more reasonable to add this threshold to that position. Because for other modes, such as failover, this parameter is not needed, it is only required in broadcast mode.

**Comment by dkisser** [comment]
Threshold represent for a percentage, For example, 20  stand for 20 percent of all providers.Compatibility issues is easy to solve, wo can use 0 for the default threshold , in this way if exception occured ,it will throws it as the old version did.

**Comment by xiaoheng1** [comment]
By the way, is it appropriate to put this threshold parameter on the reference? After all, this parameter is only used by broadcast cluster. Are there other more suitable places?

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
close #7173 via #7174
