### ISSUE TITLE
GenericService调用，返回Optional类型，无法得到Optional中value

### ISSUE THREAD

**Issue by shuiuigee** [apache/dubbo#7183]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: windows 10
* Java version: 8

### Steps to reproduce this issue

1. 泛化调用的服务，返回类型为Optional
2. 调用成功后，返回的结果Map是{present=true，class=java.util.Optional}，无法得到Optional中value
3. 看了泛化调用的相关源码，发现PojoUtils没有对Optional类型做特殊处理，有没有什么好的办法得到Optional种value

**Comment by sourirer** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 2.7.8
> * Operating System version: windows 10
> * Java version: 8
> 
> ### Steps to reproduce this issue
> 1. 泛化调用的服务，返回类型为Optional
> 2. 调用成功后，返回的结果Map是{present=true，class=java.util.Optional}，无法得到Optional中value
> 3. 看了泛化调用的相关源码，发现PojoUtils没有对Optional类型做特殊处理，有没有什么好的办法得到Optional种value

你好，这里是可以针对Optional进行特殊处理，但是有个问题是，Optional本身就没有实现序列化接口，所以从接口规范来说，是不允许声明Optional为返回值的。

说到这个，个人考虑，后续增加一个判断，即使在泛化调用中，未实现序列化接口的值依然不允许传递。

**Comment by sourirer** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> ### Environment
> * Dubbo version: 2.7.8
> * Operating System version: windows 10
> * Java version: 8
> 
> ### Steps to reproduce this issue
> 1. 泛化调用的服务，返回类型为Optional
> 2. 调用成功后，返回的结果Map是{present=true，class=java.util.Optional}，无法得到Optional中value
> 3. 看了泛化调用的相关源码，发现PojoUtils没有对Optional类型做特殊处理，有没有什么好的办法得到Optional种value

我们讨论了一下，暂时不针对这种场景进行处理，建议按照正常规范，在返回值和参数都考虑采用实现serializable的类。

**Comment by chickenlj** [comment]
同意 @sourirer 的观点，尽量避免 Optional 类型作为 rpc 方法值传递。目前官方暂无支持 Optional 计划
