### ISSUE TITLE
dubbo2.6.* consumer配置lazy模式，connections 不配置也会有多个连接

### ISSUE THREAD

**Issue by fsx379** [apache/dubbo#7186]
问题：dubbo2.6.9 在consumer未配置connections 的前提下，按官方说法，与一台provider默认是1个连接。
但如果consumer 配置 lazy=true后，发现连接个数=应用的服务个数，即如果provider上有3个服务，那么会与一台provider 建立3个连接（3个服务都有访问的情况下，每个服务调用时是建立一个新连接），而不是默认1个连接。
求大佬帮忙验证~

**Comment by xiaoheng1** [comment]
这个是正常的。
我的理解是：
1.lazy 只会影响连接的创建时间，lazy 在发送数据的时候建立连接
2.共享连接解决的是当一个节点中多个服务共享同一个连接，而不是多个节点共用一个连接

**Comment by fsx379** [comment]
> 这个是正常的。
> 我的理解是：
> 1.lazy 只会影响连接的创建时间，lazy 在发送数据的时候建立连接
> 2.共享连接解决的是当一个节点中多个服务共享同一个连接，而不是多个节点共用一个连接

是的，现在主要问题是在lazy模式下，“共享连接”失效了。
一个provider节点 上暴露 AService、BService、CService三个服务。lazy模式下，cosumer在调用AService创建一个连接，调用BService、CService又分别新建2个连接，最后cosumer上开了三个端口，用三个连接，同时连接同一个provider节点 。

**Comment by xiaoheng1** [comment]
你的意思是说，一个服务提供者，提供了三个服务(也就是三个接口)，然后 lazy 模式下，consumer 端建立了三个连接？

**Comment by fsx379** [comment]
> 你的意思是说，一个服务提供者，提供了三个服务(也就是三个接口)，然后 lazy 模式下，consumer 端建立了三个连接？还是说一个节点上部署了三个服务(这三个服务分别使用不同的端口号)？

是前者：lazy 模式下，consumer 端建立了三个连接

**Comment by xiaoheng1** [comment]
can you provider a demo ?

**Comment by fsx379** [comment]
> can you provider a demo ?

代码地址
https://github.com/fsx379/dubbo-samples-lazymodel
测试方法详见 readme

**Comment by fsx379** [comment]
我的理解，未配置connections 参数情况下，在服务暴露过程中，会走到DubboProtocol#getSharedClient() 中，但每次都是新建一个ReferenceCountExchangeClient/LazyConnectExchangeClient，所以在 DubboInvoker#doInvoke 调用  currentClient.send()时，都会进行client 初始化（因为他们是不同的对象）。

**Comment by xiaoheng1** [comment]
There is a problem with dubbo2.6.9, which has been fixed in the new version.

**Comment by fsx379** [comment]
> There is a problem with dubbo2.6.9, which has been fixed in the new version.

好的，了解了，3q~

**Comment by xiaoheng1** [comment]
Please upgrade dubbo version to 2.7.8 and try.

**Comment by chickenlj** [comment]
Please feel free to reopen.

**Comment by AlbumenJ** [comment]
we will also fix it in 2.6.10

**Comment by AlbumenJ** [comment]
#7245 has been merged into 2.6.x branch, and this bug will be fix in 2.6.10. 
Also 2.7.8 has fix this bug in 2.7.x.
