### ISSUE TITLE
Doc fix at EnableDubboConfig

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#7241]
The properties parse way is take over by EnableConfigurationBeanBinding.

But at EnableDubboConfig, the doc is still EnableDubboConfigBinding.

https://github.com/apache/dubbo/blob/860a3f7d2f10ca92de73b427ebb7e1c006000c79/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/annotation/EnableDubboConfig.java#L36-L80

**Comment by AlbumenJ** [comment]
close #7241 via #7242
