### ISSUE TITLE
[Code Clean] The method startMetadataCenter() called twice when DubboBootstrap.initialize()

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#7256]
first: line_536.
https://github.com/apache/dubbo/blob/15fc5b473bbeb73b0a6c9ac02f2c8d7e0f6fbe82/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L522-L545

second: line_872
https://github.com/apache/dubbo/blob/15fc5b473bbeb73b0a6c9ac02f2c8d7e0f6fbe82/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L871-L875

**Comment by AlbumenJ** [comment]
close #7256 via #7257
