### ISSUE TITLE
Remove logger which is already defined in superclass.

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#7261]
Some class already define logger at superclass such as AbstractMetadataReport.

https://github.com/apache/dubbo/blob/15fc5b473bbeb73b0a6c9ac02f2c8d7e0f6fbe82/dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java#L87

The subclass needn't define logger again. But some class do as it, such as NacosMetadataReport.

https://github.com/apache/dubbo/blob/15fc5b473bbeb73b0a6c9ac02f2c8d7e0f6fbe82/dubbo-metadata/dubbo-metadata-report-nacos/src/main/java/org/apache/dubbo/metadata/store/nacos/NacosMetadataReport.java#L70

Remove the logger which is define at subclass.

**Comment by AlbumenJ** [comment]
close #7261 via #7262
