### ISSUE TITLE
AbstractRegistryFactory#getRegistry和destroyAll方法在多线程下共同争抢锁的问题

### ISSUE THREAD

**Issue by 1015773611** [apache/dubbo#7265]
问题 描述：比如两个线程A、B。线程A要调用destroyAll，线程B调用getRegistry(url)，此时线程B快一步，通过destory.get()状态的判定，要访问容器了，假设此时线程A先抢到了锁，B挂起，线程A清空容器，释放锁，回到B，B获得锁，B此时会给还会给容器添加元素，然后释放锁，这里其实有点问题，虽然外界无法访问了(destroyed为true)，但是REGISTRIES还是有值的。

解决方法：可以在在线程B获得锁之后再检查了一遍destoryed状态。

**Comment by xiaoheng1** [comment]
There may indeed be a problem

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
close #7265 via #7273
