### ISSUE TITLE
When using Telnet in QoS, the idle connect may not be closed in time, despite using the idle check.

### ISSUE THREAD

**Issue by Spongecaptain** [apache/dubbo#7281]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

## Bug Specification

When using Telnet in QoS, the idle connect may not be closed in time, despite using the idle check.

When using `IdleStateHandler` with `TelnetProcessHandler` in the `QosProcessHandler`, the timeout is set to  5*60 seconds, but **NO** handler deals with the `IdleStateEvent`. Maybe the `TelnetProcessHandler` should override the `userEventTriggered` method to handle this Event, and close the idle connect.

**Comment by AlbumenJ** [comment]
close #7281 via #7282
