### ISSUE TITLE
dubbo2.7.8中在接口上添加jetcache的@Cached注解不生效

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#7288]
`provider-dubbo`项目分为两个module,其中一个是`xxx-api`里面都是实体类和接口interface,另外一个是`xxx-service`里面是interface的实现类。

`consumer-dubbo`项目为dubbo调用方，引入了`xxx-api`的jar包，通过interface调用dubbo服务。

目前我想在xxx-api的方法上加上`jetcache`的`@Cached(expire = 30, cacheType = CacheType.LOCAL)`注解，然后consumer-dubbo调用的时候如果发现本地就缓存就不用去走dubbo协议去provider-dubbo调用了，减少dubbo间的调用。

但是上述方法不行，依然会走dubbo协议去请求。

当然我知道我可以在`consumer-dubbo`可以定义service类然后在service层定义一个方法调用`provider-dubbo`方法,然后在此service的方法上加上`@Cached`注解，这样确实可以。但是我就是想通过第一个方法实现。请问可以实现不。

**Comment by xiaoheng1** [comment]
Dubbo does not support Cached annotations now.

**Comment by chickenlj** [comment]
请参考使用方式 https://dubbo.apache.org/zh/docs/v2.7/user/examples/result-cache/
