### ISSUE TITLE
Some problem about ServiceDiscoverty.

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#7289]
problems.

1. Not all serviceDiscoveryRegistry will set localInstance, just like ServiceDiscoveryRegistry, it didn't  maintain localInstance, it will cause NPE at BubboBootstrap.registerServiceInstance();
https://github.com/apache/dubbo/blob/51d5a88a067876abf9d9a8ba40a1426c4f805909/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L1173-L1177

https://github.com/apache/dubbo/blob/51d5a88a067876abf9d9a8ba40a1426c4f805909/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java#L263-L272

2. The key which is used to judge instance is update, it should be reset after update process.
https://github.com/apache/dubbo/blob/51d5a88a067876abf9d9a8ba40a1426c4f805909/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/client/metadata/ServiceInstanceMetadataUtils.java#L253

3. The subclass of ServiceDiscoverty is messed, unify the subclass process about register and update in AbstractServiceDiscovery.

**Comment by AlbumenJ** [comment]
close #7289 via #7290
