### ISSUE TITLE
扩展的Cluster在没有任何配置下自动适配

### ISSUE THREAD

**Issue by JayeShen** [apache/dubbo#7312]
### Environment

* Dubbo version: 2.7.6
* Operating System version: windos10
* Java version: 1.8

### Steps to reproduce this issue

自己对Cluster扩展的RpcClusterWrapper在没有任何配置下声明过cluster=RpcClusterWrapper的情况下，被自动加载了join方法
按照@SPI和@Adaptive不是应该在声明cluster=RpcClusterWrapper的情况下，才会自动适配RpcClusterWrapper负载均衡策略吗？是否Cluster的扩展存在问题？
![image](https://user-images.githubusercontent.com/53166168/109775411-70f63e00-7c3c-11eb-930f-9a4adcef084c.png)

![image](https://user-images.githubusercontent.com/53166168/109775363-60de5e80-7c3c-11eb-9725-d436db4b2198.png)
![image](https://user-images.githubusercontent.com/53166168/109775748-d8ac8900-7c3c-11eb-825d-4ae26e2d6614.png)

**Comment by xiaoheng1** [comment]
can you provider a demo?

**Comment by xiaoheng1** [comment]
Wrapper will be automatically loaded by SPI in dubbo.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
