### ISSUE TITLE
Redundant box for boolean

### ISSUE THREAD

**Issue by 24kpure** [apache/dubbo#7315]
- [ √] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ √] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macos 10.14.6
* Java version: oracle 1.8.0_211

### Steps to reproduce this issue
1. method info 
org.apache.dubbo.rpc.cluster.router.tag.TagRouter#isForceUseTag
2. a boolean value is boxed  while a unboxed value is expected

### Expected Result

none box for boolean

### Actual Result

Redundant box for boolean

### others
Is the method graceful enough? org.apache.dubbo.rpc.cluster.router.tag.TagRouter#filterInvoker

**Comment by AlbumenJ** [comment]
close #7315 via #7316
