### ISSUE TITLE
Why dubbo scan twice by basePackages?

### ISSUE THREAD

**Issue by FisherLea** [apache/dubbo#7318]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: MacOS
* Java version: 1.8.0_211

### Steps to reproduce this issue

1.In line#166 of the ServiceClassPostProcessor class, the object named scanner extends ClassPathBeanDefinitionScanner, firstly after calling scanner.scan(packageToScan),the beanDefinitionMap already contains the scanned component annotated by @DubboService/@Service, however, secondly, call findServiceBeanDefinitionHolders() method, this will result in calling findCandidateComponents() again, actually there is no need at all. It should be called by scanner.doScan(packageToScan) here, and can obtain the return value(Set<BeanDefinitionHolder>) directly.   

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

scanner.scan(packageToScan);
->>
Set<BeanDefinitionHolder> beanDefinitionHolders = scanner.doScan(packageToScan);

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
