### ISSUE TITLE
Remove fast-json dependency on dubbo

### ISSUE THREAD

**Issue by yuxiao97** [apache/dubbo#7328]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: All
* Java version: jdk8

### Steps to reproduce this issue

1. telnet 
2. invoke 
3. return "Invalid json argument, cause: com.alibaba.fastjson.JSON"

InvokeTelnetHandler.jave

![image](https://user-images.githubusercontent.com/27430795/110265529-b75deb00-7ff6-11eb-8d06-11a3425bf3ee.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by horizonzy** [comment]
nedd more info.

**Comment by yuxiao97** [comment]
> nedd more info.

Sorry, Updated title and content.

**Comment by CrazyHZM** [comment]
Try it with the new version, if you still have problems, you can reopen the issues.
