### ISSUE TITLE
use QOS command to check if target service is ready

### ISSUE THREAD

**Issue by nickwongwong** [apache/dubbo#7331]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: macOS 
* Java version: 8

### Expected Result
希望检查指定的服务是否启动成功，然后再把服务流量切换上线
QOS功能提供了非常友好的http接口，但是缺少想要的功能
简单期望：QOS传入命令“Ready MyDubboService”，返回"true"或者"false"

### Actual Result
现有的QOS功能，“Ready”命令，只能提供查询整个dubbo是否初始化成功
[dubbo QOS文档](https://dubbo.apache.org/zh/docs/v2.7/user/references/qos/)
#5873
![image](https://user-images.githubusercontent.com/16626084/110137428-d0ef0f00-7e0b-11eb-9d25-cb6fc96f1c77.png)

**Comment by AlbumenJ** [comment]
@nickwongwong hi, would you please try to fix it ?

**Comment by CrazyHZM** [comment]
Resolved in https://github.com/apache/dubbo/pull/7370
