### ISSUE TITLE
QOS Ready command return OK when DubboBootstrap is not ready

### ISSUE THREAD

**Issue by nickwongwong** [apache/dubbo#7332]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: MacOS
* Java version: 8
* Service register: nacos
* spring-cloud-starter-dubbo 2.2.2.RELEASE

### Steps to reproduce this issue

1. Change dubbo register server into a bad address(like incorrect port) 
2. Start dubbo application
3. Check QOS ready command, return `true`(as OK). `curl "localhost:22222/ready"`。
![image](https://user-images.githubusercontent.com/16626084/110200412-de9ea600-7e98-11eb-95c0-f177cb97835c.png)
![image](https://user-images.githubusercontent.com/16626084/110200514-61bffc00-7e99-11eb-85dd-5fc680334883.png)

### Expected Result

QOS ready command return "false", when DubboBootstrap is not ready or start failed.

### Actual Result

return "true" as OK

### relative PR
#5873

**Comment by nickwongwong** [comment]
This command is very useful to check application is ready to visit when booting.

**Comment by AlbumenJ** [comment]
close #7332 via #7333

**Comment by horizonzy** [comment]
Hi, I can't reply your mail, you can communite with my wechat zhao1995yan.
