### ISSUE TITLE
dubbo filter中可否获取Method 对象

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#7336]
请问dubbo filter中可否获取提供者的Method对象？看了看invocation和invoker感觉都没有提供方法获取。

**Comment by xiaoheng1** [comment]
What problem are you trying to solve?

**Comment by luger1990** [comment]
> solve

I want to get the annotation of the method.

**Comment by xiaoheng1** [comment]
Can you provide a detailed scenario?

**Comment by AlbumenJ** [comment]
> 请问dubbo filter中可否获取提供者的Method对象？看了看invocation和invoker感觉都没有提供方法获取。

可以通过 Invocation 获取到方法名和参数信息，基于反射再去获取

**Comment by AvengerEug** [comment]
> > 请问dubbo filter中可否获取提供者的Method对象？看了看invocation和invoker感觉都没有提供方法获取。
> 
> 可以通过 Invocation 获取到方法名和参数信息，基于反射再去获取

使用Spring的工具类来获取指定的方法，类似这样：
```java
        String methodName = invocation.getMethodName();
        Class<?>[] parameterTypes = invocation.getParameterTypes();

        return ReflectionUtils.findMethod(invoker.getInterface(), methodName, parameterTypes);
```
Spring的反射工具类内部有缓存机制，可以减少反射带来的消耗。

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it.
