### ISSUE TITLE
Dubbo 2.7.8 在properties文件中指定service的registry不生效

### ISSUE THREAD

**Issue by panrd** [apache/dubbo#7348]
### Environment

* Dubbo version: 2.7.8
* Operating System version: Win10
* Java version: 1.8

### Steps to reproduce this issue
1. 引入dubbo依赖
           <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>2.7.8</version>
            </dependency>
2. 参照官网给出的属性配置格式，在application.properties做如下配置
官网给出的属性配置格式：
# 应用级别
dubbo.{config-type}[.{config-id}].{config-item}={config-item-value}
# 服务级别
dubbo.service.{interface-name}[.{method-name}].{config-item}={config-item-value}
dubbo.reference.{interface-name}[.{method-name}].{config-item}={config-item-value}
# 多配置项
dubbo.{config-type}s.{config-id}.{config-item}={config-item-value}

在项目中application.properties文件中，做了如下配置：
dubbo.registries.unit1.address=zookeeper://127.0.0.1:2181
dubbo.registries.unit2.address=zookeeper://127.0.0.1:2182

dubbo.service.org.example.service.api.EchoService.registry=unit1
dubbo.service.org.example.service.api.EchoService.group=echoServiceGroup2
dubbo.service.org.example.service.api.EchoService.version=2.0.1

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result
期望EchoService服务注册到unit1
### Actual Result
运行时，EchoService会被注册到unit1，unit2两个中心，不知是否是项目中peoeprties的配置的不正确

**Comment by kevinw66** [comment]
```java
@DubboService(registry = "unit1")
```
Service的配置直接写注解上即可

**Comment by panrd** [comment]
> ```java
> @DubboService(registry = "unit1")
> ```
> 
> Service的配置直接写注解上即可
dubbo.service.org.example.service.api.EchoService.registry=unit1
用以上的配置不能指定么，项目中基本都是xml的配置，期望是只更改properties文件就可以，尽量不用改代码

**Comment by panrd** [comment]
> > ```java
> > @DubboService(registry = "unit1")
> > ```
> > 
> > 
> > Service的配置直接写注解上即可
> > dubbo.service.org.example.service.api.EchoService.registry=unit1
> > 用以上的配置不能指定么，项目中基本都是xml的配置，期望是只更改properties文件就可以，尽量不用改代码

目前想到的一种方式是用一个后置处理器来修改ReferenceBean或ServiceBean的BeanDefinition中的注册中心相关的属性

**Comment by kevinw66** [comment]
> > ```java
> > @DubboService(registry = "unit1")
> > ```
> > 
> > 
> > Service的配置直接写注解上即可
> > dubbo.service.org.example.service.api.EchoService.registry=unit1
> > 用以上的配置不能指定么，项目中基本都是xml的配置，期望是只更改properties文件就可以，尽量不用改代码

用xml和注解我记得都是可以指定的，但是properties好像是没有dubbo.service这种配置的

**Comment by kevinw66** [comment]
> > > ```java
> > > @DubboService(registry = "unit1")
> > > ```
> > > 
> > > 
> > > Service的配置直接写注解上即可
> > > dubbo.service.org.example.service.api.EchoService.registry=unit1
> > > 用以上的配置不能指定么，项目中基本都是xml的配置，期望是只更改properties文件就可以，尽量不用改代码
> 
> 目前想到的一种方式是用一个后置处理器来修改ReferenceBean或ServiceBean的BeanDefinition中的注册中心相关的属性

可以试一试哦

**Comment by zhangyz-hd** [comment]
我也发现参照社区文档【https://dubbo.apache.org/zh/docs/v2.7/user/configuration/configuration-load-process/】设置timeout也不行。
```
dubbo.service.org.apache.dubbo.samples.api.DemoService.timeout=5000
dubbo.reference.org.apache.dubbo.samples.api.DemoService.timeout=6000
dubbo.reference.org.apache.dubbo.samples.api.DemoService.sayHello.timeout=7000
```
目前看来，社区版本未支持服务级别、服务方法级别的properties文件配置。

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issues.
