### ISSUE TITLE
Dubbo framework support for ARM architecture discussion

### ISSUE THREAD

**Issue by wbazmy** [apache/dubbo#7349]
In recent years, ARM architecture server has been more and more widely used in microservice development, some microservice frameworks have also provided support for ARM architecture, so now does Dubbo framework provide support for ARM architecture, if not, will there be any future migration plan?

**Comment by huyunhaode** [comment]
dubbo framework is based on java,the features of java is cross platform.Generally speaking,dubbo may support arm architecture because of the support to arm of java.Have you tried to use dubbo on the arm architecture?Did you have any problems using dubbo on the machine of ARM architecture.

**Comment by wbazmy** [comment]
> dubbo framework is based on java,the features of java is cross platform.Generally speaking,dubbo may support arm architecture because of the support to arm of java.Have you tried to use dubbo on the arm architecture?Did you have any problems using dubbo on the machine of ARM architecture.
I see. I haven't tried using the Dubbo framework on an ARM machine yet, but I think I will.
So is the Dubbo framework entirely Java based?

**Comment by wbazmy** [comment]
> dubbo framework is based on java,the features of java is cross platform.Generally speaking,dubbo may support arm architecture because of the support to arm of java.Have you tried to use dubbo on the arm architecture?Did you have any problems using dubbo on the machine of ARM architecture.

I see. I haven't tried using the Dubbo framework on an ARM machine yet, but I think I will.
So is the Dubbo framework entirely Java based?

**Comment by wbazmy** [comment]
> dubbo framework is based on java,the features of java is cross platform.Generally speaking,dubbo may support arm architecture because of the support to arm of java.Have you tried to use dubbo on the arm architecture?Did you have any problems using dubbo on the machine of ARM architecture.

Okay, I get it.  I haven't tried using the Dubbo framework on an ARM machine yet, but I think I will.
So is the Dubbo framework entirely Java based?

**Comment by huyunhaode** [comment]
> > dubbo framework is based on java,the features of java is cross platform.Generally speaking,dubbo may support arm architecture because of the support to arm of java.Have you tried to use dubbo on the arm architecture?Did you have any problems using dubbo on the machine of ARM architecture.
> 
> Okay, I get it. I haven't tried using the Dubbo framework on an ARM machine yet, but I think I will.
> So is the Dubbo framework entirely Java based?

yes,this project is entirely Java based.Dubbo also have other language support such as dubbo-go.And dubbo3.0 plans to support  cross-language based on cross-language Protocol.

**Comment by wbazmy** [comment]
> > > dubbo framework is based on java,the features of java is cross platform.Generally speaking,dubbo may support arm architecture because of the support to arm of java.Have you tried to use dubbo on the arm architecture?Did you have any problems using dubbo on the machine of ARM architecture.
> > 
> > 
> > Okay, I get it. I haven't tried using the Dubbo framework on an ARM machine yet, but I think I will.
> > So is the Dubbo framework entirely Java based?
> 
> yes,this project is entirely Java based.Dubbo also have other language support such as dubbo-go.And dubbo3.0 plans to support cross-language based on cross-language Protocol.

OK. Thank you for your answer.

**Comment by martin-g** [comment]
Dubbo does not build on ARM64 due to dependencies which use native binaries, like embedded-redis and embedded-consul.
I am going to send a Pull Request with updated versions of those dependencies!

**Comment by wbazmy** [comment]
> Dubbo does not build on ARM64 due to dependencies which use native binaries, like embedded-redis and embedded-consul.
> I am going to send a Pull Request with updated versions of those dependencies!

Ok, thank you for your reply, it will be very helpful.

**Comment by CrazyHZM** [comment]
Resolved in #7408
