### ISSUE TITLE
registry两种配置方式最终结果不一致（backup）

### ISSUE THREAD

**Issue by lkxiaolou** [apache/dubbo#7356]
### Environment

* Dubbo version: 2.7.x

### Steps to reproduce this issue

- 配置1：
```
  <dubbo:registry  address="zookeeper://127.0.0.1:2181,127.0.0.1:2182"/>
```
- 配置2：
```
  <dubbo:registry protocol="zookeeper"  address="127.0.0.1:2181,127.0.0.1:2182"/>
```

一直以为这两种配置是等价的，但它却不是

配置1生成的registry url是
```
zookeeper://127.0.0.1:2181,127.0.0.1:2182/org.apache.dubbo.registry.RegistryService?application=ddog-consumer&dubbo=2.0.2&file=/Users/didi/meta/.dubbo/dubbo-registry-ddog-consumer-10.96.238.17:9557.cache&interface=org.apache.dubbo.registry.RegistryService&owner=roshilikang&pid=65787&qos.enable=true&qos.port=33333&release=2.7.6&timestamp=1615358911768
```

配置2生成的registry url是
```
zookeeper://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=ddog-consumer&backup=127.0.0.1:2182&dubbo=2.0.2&file=/Users/didi/meta/.dubbo/dubbo-registry-ddog-consumer-10.96.238.17:9557.cache&interface=org.apache.dubbo.registry.RegistryService&owner=roshilikang&pid=65787&qos.enable=true&qos.port=33333&release=2.7.6&timestamp=1615358911768
```

重点关注address和backup

源码中
![image](https://user-images.githubusercontent.com/6935924/110590587-f173ec00-81b2-11eb-85e6-55b19ed58c4a.png)

也就是说当配置address中存在`://`时，多个地址用逗号隔开，而当address中不存在`://`时，配置多个地址，从第二个地址开始的地址都会被当做是backup。

不知道这样设计的目的是什么？是不是bug？有人能解释下么

**Comment by horizonzy** [comment]
使用方式不一样。
第一种方式配置是带了协议的，对协议的解析需要符合URL的格式，zk backup 地址的配置需要通过?key=value的形式保存。
第二种方式的配置是按照dubbo中的规则进行解析，会自动把address中的逗号隔开，第一个地址当成首选连接zk的地址，后面的当成backup保存在url的param中
