### ISSUE TITLE
to fix something wrong with MergeableClusterInvoker

### ISSUE THREAD

**Issue by zhangxin1932** [apache/dubbo#7359]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: win10
* Java version: 1.8.0_151

### Steps to reproduce this issue

1. I just started one dubbo-provider and one dubbo-consumer
2. the rpc interface is like: 
public interface IDubboService { List<DubboRespDTO> hello(DubboReqDTO dubboReqDTO); }
3. the dubbo-consumer's config is: 
4. @DubboReference(cluster = "mergeable", methods = {@Method(name = "hello", merger = "list")})
private IDubboService iDubboService;

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

the expected result is a List.

### Actual Result
the Actual Result is some exception is thrown like:
java.lang.UnsupportedOperationException: AppResponse represents an concrete business response, there will be no status changes, you should get internal values directly.
	at org.apache.dubbo.rpc.AppResponse.whenCompleteWithContext(AppResponse.java:217) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:103) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:88) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74) ~[dubbo-2.7.8.jar:2.7.8]
...

**Comment by horizonzy** [comment]
Can you pull request this case to the  [dubbo/samples](https://github.com/apache/dubbo-samples)

**Comment by zhangxin1932** [comment]
1.the problems had been commited at:
https://github.com/apache/dubbo-samples/pull/283

2.the issue's resolution at:
https://github.com/apache/dubbo/pull/7360

**Comment by horizonzy** [comment]
It can be close.

**Comment by AlbumenJ** [comment]
close #7359 via #7360
