### ISSUE TITLE
使用2.7.9的TagRouter，没有持续传递tag标签的疑惑

### ISSUE THREAD

**Issue by ericren** [apache/dubbo#7373]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version: Windows10
* Java version: 1.8

### Steps to reproduce this issue
想利用TagRouter实现在一次完整的远程调用中持续传递tag标签。
我一共有三个应用，分别是A、B、C, 每个应用起两个节点(A1,A2,B1,B2,C1,C2)，其中A应用会调用B应用的testB方法，在B应用的testB方法中，又会同步调用C应用的testC方法。
调用关系如下：
`A->B.testB()->C.testC()`

为了最终实现A1->B1->C1的精准走向，分别做如下配置：
1）在dubbo admin中，分别对应用B和C 新建了两条动态路由配置
其中B应用的配置如下：
enabled: true
force: false
runtime: false
tags:
  - name: tagGray
    addresses:
      - '192.168.XXX.XXX:20880'（B1节点）
	  
C应用的配置如下：
enabled: true
force: false
runtime: false
tags:
  - name: tagGray
    addresses:
      - '192.168.XXX.XXX:20880'（C1节点）
	 
	 
2）在A应用调用B应用的testB方法前，设置RpcContext.getContext().setAttachment("dubbo.tag","tagGray")

### Expected Result
通过在A应用设置RpcContext.getContext().setAttachment("dubbo.tag","tagGray")实现A1->B1->C1精准的走向。

### Actual Result
**实际情况是流量变成了：A1->B1->C2的走向**
排查后发现：
在B应用调用C应用的时候，并没有把dubbo.tag往下传，最后导致B1的RpcContext中是没有dubbo.tag标识的
不知道是不是我使用姿势不对，请各位大佬指教。

调试源代码后发现：
B应用在接收到A应用请求的时候，还是有dubbo.tag=tagGray的标识的，但随后在ContextFilter的invoke方法中，对attach做了重新赋值，newAttach中，不包含原先key在UNLOADING_KEYS中里的值，所以dubbo.tag在这个时候也就没有了，最后也就没办法把这个tag标签继续往C应用传递了。想请教一下这样做的目的，我是否能改变这个设置？改变这个设置会不会带来什么影响？
**以下为源代码截图：**
![image](https://user-images.githubusercontent.com/790395/111137691-0fc65700-85ba-11eb-8f2c-6ad7acc11be4.png)

**Comment by huyunhaode** [comment]
It's true that dubbo can't dubbo can not pass the tag in the default case.Maybe you can add an interceptor to change this behaviour before selecting the address to C.

**Comment by ericren** [comment]
> It's true that dubbo can't dubbo can not pass the tag in the default case.Maybe you can add an interceptor to change this behaviour before selecting the address to C.

Thank you, but the documentation said:
`The scope of the request.tag is for each invocation, using the attachment to pass the request tag. Note that the value stored in the attachment will be passed continuously in a complete remote invocation, thanks to this feature, we only need to set the tag at the beginning of a invocation.`
So I'm a little confused...

**Comment by huyunhaode** [comment]
Maybe the document has an inaccurate description.

**Comment by xiongmaonihao** [comment]
@huyunhaode @
你好，我应该如何将dubbo.tag加入到attachment中啊？是增加一个filter吗？

**Comment by xiongmaonihao** [comment]
@ericren @huyunhaode

**Comment by JayeShen** [comment]
> @huyunhaode @ 你好，我应该如何将dubbo.tag加入到attachment中啊？是增加一个filter吗？

可以扩展route之前的阶段，例如cluster

**Comment by AlbumenJ** [comment]
> > @huyunhaode @ 你好，我应该如何将dubbo.tag加入到attachment中啊？是增加一个filter吗？
> 
> 可以扩展route之前的阶段，例如cluster

Dubbo 3.0 中可以使用 ClusterFilter，在 2.7 中对应是 ClusteInterceptor（建议直接升级 3.0，此扩展点后续不在维护）
