### ISSUE TITLE
URL被重复添加没有正确修复

### ISSUE THREAD

**Issue by brucelwl** [apache/dubbo#7375]
这个issue https://github.com/apache/dubbo/issues/4587  对应的修复https://github.com/apache/dubbo/pull/6706/files 不正确，仍然会导致URL被重复添加，
原因是重写hashCode方法将``parameters`` 全部计算了, 没有剔除``timestamp``
 https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/URL.java#L1663

**Comment by kevinw66** [comment]
看看这样解决是不是能行 https://github.com/apache/dubbo/pull/7376

**Comment by brucelwl** [comment]
> 看看这样解决是不是能行 #7376

可以,但是遍历方式不是很好,建议换成这样

```java

private int parametersHashCode() {
        int h = 0;
        for (Map.Entry<String, String> next : parameters.entrySet()) {
            if (Constants.TIMESTAMP_KEY.equals(next.getKey())) {
                continue;
            }
            h += next.hashCode();
        }
        return h;
    }
```

**Comment by kevinw66** [comment]
> > 看看这样解决是不是能行 #7376
> 
> 可以,但是遍历方式不是很好,建议换成这样
> 
> ```java
> private int parametersHashCode() {
>         int h = 0;
>         for (Map.Entry<String, String> next : parameters.entrySet()) {
>             if (Constants.TIMESTAMP_KEY.equals(next.getKey())) {
>                 continue;
>             }
>             h += next.hashCode();
>         }
>         return h;
>     }
> ```

已改
