### ISSUE TITLE
ServiceCheckUtils.isRegistered not check all registries

### ISSUE THREAD

**Issue by nickwongwong** [apache/dubbo#7406]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

Dubbo version: 2.7.8
Operating System version: MacOS
Java version: 8
Service register: nacos

### Steps to reproduce this issue

https://github.com/apache/dubbo/blob/2d9583adf26a2d8bd6fb646243a9fe80a77e65d5/dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java#L33-L35
就如TODO注释所言：
判断服务是否注册时候，只判断了一个Registry，会导致判断服务一直未注册。

![image](https://user-images.githubusercontent.com/16626084/111600515-75aa1d00-880c-11eb-9218-59327ce13ffb.png)

### Scope of influence
影响范围：QOS和Telent中ls命令
https://dubbo.apache.org/zh/docs/v2.7/user/references/qos/
https://dubbo.apache.org/zh/docs/v2.7/user/references/telnet/

### Expected Result

判断多个registries

**Comment by nickwongwong** [comment]
已经有一个初步的代码，稍后测试后尝试提交个PR

**Comment by CrazyHZM** [comment]
Already resolved in #9133
