### ISSUE TITLE
FAQ link is broken

### ISSUE THREAD

**Issue by rhmangmang** [apache/dubbo#7409]
Hi, https://dubbo.apache.org/en-us/docs/developers/user-guide/faq_dev.html is broken.

**Comment by AlbumenJ** [comment]
Could you pls create a pr to fix this

**Comment by CrazyHZM** [comment]
Issues have been created in the dubbo-website project

**Comment by danielamorais** [comment]
Just a heads up: I created a PR https://github.com/apache/dubbo-website/pull/1008 and after that it's necessary to update the link in the Github wiki.
