### ISSUE TITLE
How to @Autowired @DubboReference bean（怎样注入一个@DubboReference声明过的bean）

### ISSUE THREAD

**Issue by linxiaobai** [apache/dubbo#7413]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: Mac OS MoJave 10.14.2
* Java version: 1.8.0_151

### Steps to reproduce this issue

1. config
```java
@Configuration
public class DubboServiceReferences {

    @DubboReference(version = "${serverside.userservice.version}")
    UserService userService;

    @DubboReference(version = "${serverside.greetservice.version}")
    GreetingServerService greetingServerService;

}
```
2.
```java
@RestController
@RequestMapping(Constants.WEB_API_PREFIX + "/web")
public class WebController {

    @Autowired
    private GreetingServerService greetingServerService;

    @Autowired
    private UserService userService;
}
```
3. error 
```java
Description:

Field greetingServerService in com.xxx.clientside.web.controller.WebController required a bean of type 'com.xxx.serverside.facade.service.GreetingServerService' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


```

### Expected Result

I want to centrally manage all @DubboReferences into one class, so that the maintenance of the version number and the configuration of some parameters are more intuitive.It seems that the bean declared by @DubboReference cannot be injected through @Autowried.

我想集中管理所有的DubboReference到一个类里，这样版本号的维护以及一些参数配置比较直观。
目前看来@DubboReference声明的bean并不能通过@Autowried进行注入。

### Actual Result

```java
Description:

Field greetingServerService in com.xxx.clientside.web.controller.WebController required a bean of type 'com.xxx.serverside.facade.service.GreetingServerService' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)


```

**Comment by kylixs** [comment]
This can work in Dubbo 3: https://github.com/apache/dubbo/pull/7383 
This kind of reference annotation configuration is very clear and can be recommended to everyone.

**Comment by daocr** [comment]
结合  xml 配置文件，可以解决你这样的需求

**Comment by wu560130911** [comment]
如果一定要使用注解，可以这样来解决；
`@Bean(ReferenceAnnotationBeanPostProcessor.BEAN_NAME)
	public ReferenceAnnotationBeanPostProcessor processor()
	{
		ReferenceAnnotationBeanPostProcessor processor = new ReferenceAnnotationBeanPostProcessor();
		processor.setOrder(Ordered.HIGHEST_PRECEDENCE);
		return processor;
	}`

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it.
