### ISSUE TITLE
服务消费者运行时，动态修改消费者超时时间，重试次数不生效

### ISSUE THREAD

**Issue by opver** [apache/dubbo#7424]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. 服务提供者启动
2. dubbo控制台修改服务消费者超时和重试参数
3. 消费者启动调用服务接口，超时次数和配置参数还是本地默认数字

![image](https://user-images.githubusercontent.com/9124753/111953374-7a7b1380-8b21-11eb-94db-989ac17e486f.png)

getUrl()获取的是本地启动时服务消费者的url，2.7.8返回的是overrideDirectoryUrl

**Comment by xiaoheng1** [comment]
OverrideDirectoryUrl will refresh every time the configuration changes, right?

**Comment by opver** [comment]
2.7.8版本getUrl()获取的是overrideDirectoryUrl，每次配置发生改变会刷新overrideDirectoryUrl，但是2.7.9getUrl()获取的是consumerUrl，动态配置发生改变不会刷新consumerUrl，导致消费者获取重试次数和超时时间获取的是最原始的数据
你可以通过xml本地配置重试次数为0，然后动态配置随意改成什么值，后续调用重试次数都是0
<dubbo:reference id="service" interface="org.apache.dubbo.Service" retries="0"/>

**Comment by xiaoheng1** [comment]
dubbo2.7.9 consumerUrl is overrideDirectoryUrl

![image](https://user-images.githubusercontent.com/12539730/112142202-3b2bf000-8c11-11eb-99d7-49544b0e6d3d.png)

**Comment by horizonzy** [comment]
> ### Steps to reproduce this issue
> 1. 服务提供者启动
> 2. dubbo控制台修改服务消费者超时和重试参数
> 3. 消费者启动调用服务接口，超时次数和配置参数还是本地默认数字


控制台改的动态配置走的是override协议，还是走的是configcenter.

**Comment by opver** [comment]
> dubbo2.7.9 consumerUrl is overrideDirectoryUrl
> 
> ![image](https://user-images.githubusercontent.com/12539730/112142202-3b2bf000-8c11-11eb-99d7-49544b0e6d3d.png)

https://github.com/apache/dubbo/blob/dubbo-2.7.9/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryDirectory.java

难道我看的是假的2.7.9代码，你看下上面链接中的RegistryDirectory有getConsumer方法吗？

**Comment by opver** [comment]
> configcenter

通过configcenter

**Comment by horizonzy** [comment]
2.7.9的确有这个问题。该问题在master分支已经被fix，最近2.7.10会发布。

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Comment by xiaoheng1** [comment]
see #6773 for more detail.
