### ISSUE TITLE
Dubbo has a warning on jdk11

### ISSUE THREAD

**Issue by lingsuzhi** [apache/dubbo#7425]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.ClassPool (file:/D:/common-soft/apache-maven-3.3.9/repo/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.ClassPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by AlbumenJ** [comment]
maybe we can upgrade javassist version to prevent this

**Comment by htynkn** [comment]
this warning will not break anything, and according to release notes, it requires at least version `3.23.1-GA` for javassist to prevent this.
