### ISSUE TITLE
关于DubboProtocol#initClient() 中 client type校验问题

### ISSUE THREAD

**Issue by fsx379** [apache/dubbo#7430]
dubbo中用到了SPI技术，比如在Transporter 中，可以分别自定义server和client；
但在DubboProtocol#initClient() 有这样一段校验：
```
 // client type setting.
        String str = url.getParameter(CLIENT_KEY, url.getParameter(SERVER_KEY, DEFAULT_REMOTING_CLIENT));

// BIO is not allowed since it has severe performance issue.
if (str != null && str.length() > 0 && !ExtensionLoader.getExtensionLoader(Transporter.class).hasExtension(str)) {
	throw new RpcException("Unsupported client type: " + str + "," +
                    " supported client type is " + StringUtils.join(ExtensionLoader.getExtensionLoader(Transporter.class).getSupportedExtensions(), " "));
}
```

即client端如果没有配置，会默认使用server的配置。

这样会导致一个问题，即在生产环境中，如果有多个consumer业务方，如果provider先上线，会导致client端报"Unsupported client type: " ，只能等consumer端所有业务都上线后，才能上线provider端。

Transporter 分别配置了client 和server，目的就是可以分别配置，例如mynetty，如果有了上述检查，无法做到平滑上线。

此处检查，是否可以删除？删除后会导致什么后果？或者有什么平滑上线方案？

**Comment by xiaoheng1** [comment]
let me have a look.

**Comment by xiaoheng1** [comment]
@fsx379  Under what scenario is the transmission protocol of the provider and the consumer inconsistent?

**Comment by xiaoheng1** [comment]
Can you configure the client parameters on the consumer side to solve this problem?

**Comment by fsx379** [comment]
> Can you configure the client parameters on the consumer side to solve this problem?

consumer 和provider 都配置了，但是面对复杂的生产环境，无法要求consumer全部升级上线后，才能让provider升级上线。所以核心问题还是在于无法平滑上线。在生产过程投产过程中，如果任意节点上线，对上下游都是兼容和无感的，那是最好的，否则成本极大，极易造成在线故障。

**Comment by xiaoheng1** [comment]
> > Can you configure the client parameters on the consumer side to solve this problem?
> 
> consumer 和provider 都配置了，但是面对复杂的生产环境，无法要求consumer全部升级上线后，才能让provider升级上线。所以核心问题还是在于无法平滑上线。在生产过程投产过程中，如果任意节点上线，对上下游都是兼容和无感的，那是最好的，否则成本极大，极易造成在线故障。

Why does the configuration of the client on the consumer side cause Unsupported client type errro? In my opinion, if the client is configured on the consumer side, the configuration on the consumer side will be used

**Comment by fsx379** [comment]
> > > Can you configure the client parameters on the consumer side to solve this problem?
> > 
> > 
> > consumer 和provider 都配置了，但是面对复杂的生产环境，无法要求consumer全部升级上线后，才能让provider升级上线。所以核心问题还是在于无法平滑上线。在生产过程投产过程中，如果任意节点上线，对上下游都是兼容和无感的，那是最好的，否则成本极大，极易造成在线故障。
> 
> Why does the configuration of the client on the consumer side cause Unsupported client type errro? In my opinion, if the client is configured on the consumer side, the configuration on the consumer side will be used

根本原因，还是因为在复杂的生产环境里面，无法保证所有consumer的改造上线，一定在provider之前

**Comment by huibinliupush** [comment]
不是有Default remote tpye作为默认值么？为什么会报unsupported client type？

**Comment by xiaoheng1** [comment]
> > > > Can you configure the client parameters on the consumer side to solve this problem?
> > > 
> > > 
> > > consumer 和provider 都配置了，但是面对复杂的生产环境，无法要求consumer全部升级上线后，才能让provider升级上线。所以核心问题还是在于无法平滑上线。在生产过程投产过程中，如果任意节点上线，对上下游都是兼容和无感的，那是最好的，否则成本极大，极易造成在线故障。
> > 
> > 
> > Why does the configuration of the client on the consumer side cause Unsupported client type errro? In my opinion, if the client is configured on the consumer side, the configuration on the consumer side will be used
> 
> 根本原因，还是因为在复杂的生产环境里面，无法保证所有consumer的改造上线，一定在provider之前

@AlbumenJ What is your opinion?

**Comment by fsx379** [comment]
最后，我们通过在resources/META-INF/dubbo/internal下放置com.alibab.dubbo.remoting.Transporter，并将netty4 指到自定义的实现上，才避免provider上线时，consumer还没有上线，导致consumer找不到 自定义的Transporter的问题。

**Comment by AlbumenJ** [comment]
> 此处检查，是否可以删除？删除后会导致什么后果？或者有什么平滑上线方案？

@fsx379 这里如果删除后，Invoker 正常构造，会导致在 RPC 调用过程中发现无法找到 SPI，导致 RPC 流量调用失败。这里是个尽早报错的操作。如果升级版本需要切换 Transport 这种的建议使用 version 标记接口，避免低版本的 consumer 使用这部分地址。
