### ISSUE TITLE
可否将dubbo.registry.parameters配置的所有参数全部传给NacosNamingService的构造方法

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#7431]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9及以下
采用Nacos注册中心

### Steps to reproduce this issue
应用application.yml里配置nacos注册中心增加的参数（namingPushEmptyProtection、namingRequestDomainMaxRetryCount这些参数是nacos1.4.1增加的，当前dubbo最新版本2.7.9引用的nacos还是1.3.1）：
```
dubbo:
    registry:
        parameters: {"namingPushEmptyProtection": true, "namingRequestDomainMaxRetryCount": 3}
```
dubbo的ReferenceConfig构建注册中心url时，把dubbo.registry.parameters配置的各个参数作为了url的parameters；
但是dubbo的NacosNamingServiceUtils类的buildNacosProperties方法构建nacosNamingService的properties时，并没有从注册中心的url取出这些参数。

### Expected Result
dubbo的NacosNamingServiceUtils类的buildNacosProperties方法构建nacosNamingService的properties时，把url所有的参数都取出来放入properties。

### nacos社区的关联issue
https://github.com/alibaba/nacos/issues/5163

**Comment by zrlw** [comment]
修改应用pom文件，排除dubbo自己引用的nacos-client版本可以解决这个问题。
只是这样做不如dubbo直接把dubbo.registry.parameters的内容透传给nacos优雅，这些东西本来也不是dubbo需要关注的内容。

**Comment by horizonzy** [comment]
Ok。我把这个fix了。

**Comment by horizonzy** [comment]
目前dubbo已经支持了，只需要把nacos-client升级到1.4.1即可。

**Comment by zrlw** [comment]
嗯，只是探讨一下，dubbo有没有必要解析parameters这个参数，假设以后nacos再增参数，有没有必要更新pom依赖。
有没有可能把parameters作为一个完整的参数放入url，透传给nacos呢？这样不用再解析里面的内容了吧。

**Comment by horizonzy** [comment]
现在已经实现了。现在是通过反射获取PropertyKeyConst中对应的字段。只要后续nacos中的参数在PropertyKeyConst中增加，dubbo这边不用改代码都能支持

**Comment by zrlw** [comment]
nacos增加参数升级了版本之后，应用的pom文件除了修改nacos的版本号之外，还要注意exclude排除dubbo里的nacos版本号，如果引用先后顺序写反了，dubbo还是读不到新增的参数的。
我想说的是，如果把parameters整体作为一个map参数作为url的一个参数，在构建nacosNamingService属性时，把这个map的key和value直接放入Properties是不是简洁一些？dubbo没有必要引用nacos的PropertyKeyConst类吧，无非就是解析一下放入Properties而已。

**Comment by horizonzy** [comment]
嗯。了解你的意思了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zrlw ***@***.***&gt;
发送时间: 2021年3月26日 00:24
收件人: apache/dubbo ***@***.***&gt;
抄送: 赵延 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[apache/dubbo] 可否将dubbo.registry.parameters配置的所有参数全部传给NacosNamingService的构造方法 (#7431)





 
nacos增加参数升级了版本之后，应用的pom文件除了修改nacos的版本号之外，还要注意exclude排除dubbo里的nacos版本号，如果引用先后顺序写反了，dubbo还是读不到新增的参数的。
 我想说的是，如果把parameters整体作为一个map参数作为url的一个参数，在构建nacosNamingService属性时，把这个map的key和value直接放入Properties是不是简洁一些？dubbo没有必要引用nacos的PropertyKeyConst类吧，无非就是解析一下放入Properties而已。

**Comment by horizonzy** [comment]
> nacos增加参数升级了版本之后，应用的pom文件除了修改nacos的版本号之外，还要注意exclude排除dubbo里的nacos版本号，如果引用先后顺序写反了，dubbo还是读不到新增的参数的。

这一点其实不算问题，如果对应的nacos-client的包还是是老的话，就算peoperties有相关的配置，也是无法应用到NacosNamingServce中的。

**Comment by horizonzy** [comment]
我认为这没有必要去改动，当前的代码已经能够满足适配nacos-client中的参数，后续nacos-client新增也能满足。

**Comment by horizonzy** [comment]
READY-TO-CLOSE
