### ISSUE TITLE
AbstractConfigurator#configureIfMatch重复添加元素到conditionKeys集合的问题

### ISSUE THREAD

**Issue by BurningCN** [apache/dubbo#7453]
这是一个小小的建议点，如下图所示，conditionKeys.add(key);只有在key.startsWith("~")才需要add，另两个key已经在上面填充过了。不过conditionKeys是set集合，影响不大

![image](https://user-images.githubusercontent.com/43363120/112635194-78dd8280-8e76-11eb-8100-c16025af5540.png)

**Comment by ttttangzhen** [comment]
我fix一下这个吧

**Comment by xiaoheng1** [comment]
let me have a look.
