### ISSUE TITLE
Consumer no listening ConditionRouter application configuration

### ISSUE THREAD

**Issue by haoyann** [apache/dubbo#7455]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version: mac OS
* Java version: 1.8

### Steps to reproduce this issue
1. admin create application scope condition router
![image](https://user-images.githubusercontent.com/43994656/112717106-640bf800-8f25-11eb-87d0-dd3db17fae1e.png)
2. consumer no listening application scope condition router
![image](https://user-images.githubusercontent.com/43994656/112717151-b4835580-8f25-11eb-9602-9466dbee59a1.png)
![image](https://user-images.githubusercontent.com/43994656/112717159-bfd68100-8f25-11eb-840d-d09c664e1c72.png)
 

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

Consumer listening application scope condition router, conditional routing takes effect.

### Actual Result

What actually happens?

Consumerno  listening application scope condition router.

```
Just put your stack trace here!
```

**Comment by BurningCN** [comment]
Hello, big brother, I verified this problem

This is indeed a problem. When the consumer side goes through the `AppRouter` flow, the consumer side listens to a structure similar to this:` /dubbo/config/dubbo/{consumerAppName}.condition-router,` from your screenshot, The application name value you specify is the provider's application name (dubbo-provider), and the correct operation is that what we fill in the console should be the consumer's application name.

But I tried to fill in the consumer's application name, it will prompt `there is no service for application:demo-consumer`, this is a bug, I will try to modify it

**Comment by BurningCN** [comment]
Hello, big brother, I verified this problem

This is indeed a problem. When the consumer side goes through the `AppRouter` flow, the consumer side listens to a structure similar to this:` /dubbo/config/dubbo/{consumerAppName}.condition-router,` from your screenshot, The application name value you specify is the provider's application name (dubbo-provider), and the correct operation is that what we fill in the console should be the consumer's application name.

But I tried to fill in the consumer's application name, it will prompt `there is no service for application:demo-consumer`, this is a bug, I will try to modify it

**Comment by BurningCN** [comment]
https://github.com/apache/dubbo-admin/issues/754

**Comment by haoyann** [comment]
Close by https://github.com/apache/dubbo-admin/pull/764.
