### ISSUE TITLE
more than one BeanDefinition  generated for one ServiceBean

### ISSUE THREAD

**Issue by spilledyear** [apache/dubbo#7478]
### Environment

* Dubbo version: 2.7.8
* Java version: 1.8

### Steps to reproduce this issue
1. 通过xml的方式定义dubbo服务，
2. 只有一个接口，但是针对这个接口定义多个 <dubbo:service > ， 如下图
![image](https://user-images.githubusercontent.com/24663965/112942012-0f08f580-9162-11eb-9eee-823fe09d1f43.png)

### 解决方式
1. DubboBeanDefinitionParser的parse方法中，针对这种重复接口 serviceBean的情况，会追加1，2，3 ， 然后以这个作为ID，例如：com.xxService, com.xxService2, com.xxService3, com.xxService4
2. 有一个疑，为什么不以 grouop/service:version 作为ID呢？ 是因为service上可以使用指定注册中心吗？那这时候对应的是两个bean， 那能不能吧 protocol也加上？ 如 protocol-grouop/service:version ？

**Comment by zhongxiongzeng** [comment]
确实如此，配置文件在解析时就被解析成了两个，这确实不河狸

**Comment by zhongxiongzeng** [comment]
If you think this is a problem, this pr can be solved
https://github.com/apache/dubbo/pull/7494

**Comment by spilledyear** [comment]
> If you think this is a problem, this pr can be solved
> #7494

不能这样改：
1. 有没有考虑  一个服务可以指定不同version和group的情况， 改了之后就变成同一个bean了

**Comment by zhongxiongzeng** [comment]
> > If you think this is a problem, this pr can be solved
> > #7494
> 
> 不能这样改：
> 
> 1. 有没有考虑  一个服务可以指定不同version和group的情况， 改了之后就变成同一个bean了

不会变成同一个bean，会报错
