### ISSUE TITLE
The same method in different application works differently.

### ISSUE THREAD

**Issue by KevinClair** [apache/dubbo#7481]
- [] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue
1. Create the same method in different application A and B;
```java
public String test() {
    return "hello";
}
```
2. Stress test the method
3. The QPS of A is 18000, and the QPS of B is 160;

### Expected Result
Method in different application A and B should have the same QPS；
### Actual Result
The two applications are deployed on the same machine.
The difference between application a and application B is that application a contains many Dubbo services, about 30, but application B has only a few.When I was testing stress, neither a nor B applications reached CPU bottlenecks.

Please give me some advice, this problem has tracked me a long time.

**Comment by xiaoheng1** [comment]
Can you provide a demo to reproduce this problem?

**Comment by pinxiong** [comment]
@KevinClair This issue will be closed. If necessary, we can reopen it.

**Comment by KevinClair** [comment]
> @KevinClair This issue will be closed. If necessary, we can reopen it.

Thanks a lot, please close it.
