### ISSUE TITLE
nacos作为注册中心的时候, 如果nacosURL中的namespace 值为dubbo, 会删除掉  

### ISSUE THREAD

**Issue by blanexie** [apache/dubbo#7499]
### Environment

* Dubbo version: 2.7.9
* Operating System version: win10
* Java version: openjdk11

### Steps to reproduce this issue
 
Pls. provide [GitHub address] to reproduce this issue.
![image](https://user-images.githubusercontent.com/15071350/113320224-da08c880-9344-11eb-9f73-1c5311c3df56.png)

 
问题代码位置:  org.apache.dubbo.configcenter.support.nacos.NacosDynamicConfigurationFactory
 
![image](https://user-images.githubusercontent.com/15071350/113320299-f3aa1000-9344-11eb-89f6-10faa449f848.png)

这段代码猜测应该是为了兼容dubbo的namespace,  但是这个和dubbo的namespace并不是一回事,   这里只是nacos注册中心的命名空间不应该如此处理

**Comment by kevinw66** [comment]
注册中心应该是没什么问题的，这块代码是配置中心的

**Comment by kevinw66** [comment]
针对这个问题，提了一个具体的ISSUE [#7514](https://github.com/apache/dubbo/issues/7514)
