### ISSUE TITLE
nacos + dubbo 在实例注册成功后会有几秒的时间调用不到提供者

### ISSUE THREAD

**Issue by ZhangShaoWu** [apache/dubbo#7504]
我们这边用的是spring-cloud-alibaba ，在项目上线的时候服务在启动的过程中发现服务启动了，nacos也注册上去了，会有消费者还是没有办法调用到提供者的情况。

1，这个时间点是实例注册到nacos中的时间

![3d3f638c32f73ea7bbce80cc0d3c12e7](https://user-images.githubusercontent.com/19930444/113406188-a29a2a80-93dd-11eb-892c-472e660759f3.png)

2，这个时间是dubbo初始化完成的时间
![图二](https://user-images.githubusercontent.com/19930444/113406199-a75ede80-93dd-11eb-9753-e51532d49550.png)

在图一的这个时间nacos已经注册了，那么nacos会将用户的流量分配到注册的机器，但是这个时候dubbo的初始化还没有完成，消费者调用这个提供者的时候就会出现找不到提供者异常，只有在dubbo初始化完成之后才能调用成功，请问下这个问题有成熟的解决方案吗？

**Comment by horizonzy** [comment]
能提供一个复现的demo到你的github仓库吗，我会跟踪一下。

**Comment by XiaoweiM** [comment]
建议先使用延迟暴露功能满足你的需求，参考下文档 [延迟暴露](https://dubbo.apache.org/zh/docs/v2.7/user/examples/delay-publish/)

**Comment by pinxiong** [comment]
@ZhangShaoWu We will close this issue. You can reopen it, if necessary
