### ISSUE TITLE
dubbo +nacos nacos网络故障恢复后，应用不会自动重新注册吗？

### ISSUE THREAD

**Issue by bestpayAmes** [apache/dubbo#7511]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by horizonzy** [comment]
这里的网络故障指的是什么，能具体描述下场景吗

**Comment by bestpayAmes** [comment]
应该是应用到nacos心跳超时，服务注册的临时节点都自动删除了，然后网络恢复了，应用不会自动重新注册服务吗？必须要重启？之前用zk好像有这个功能；

**Comment by bestpayAmes** [comment]
@horizonzy

**Comment by horizonzy** [comment]
应用和nacos网络恢复后，服务会自动重新注册



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bestpayAmes ***@***.***&gt;
发送时间: 2021年4月7日 09:13
收件人: apache/dubbo ***@***.***&gt;
抄送: 赵延 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[apache/dubbo] dubbo +nacos nacos网络故障恢复后，应用不会自动重新注册吗？ (#7511)





 
应该是应用到nacos心跳超时，服务注册的临时节点都自动删除了，然后网络恢复了，应用不会自动重新注册服务吗？必须要重启？之前用zk好像有这个功能；

**Comment by bestpayAmes** [comment]
请问下自动注册代码在哪？

**Comment by bestpayAmes** [comment]
DubboRegistry的构造器里的定时任务？

**Comment by horizonzy** [comment]
```
com.alibaba.nacos.client.naming.NacosNamingService#registerInstance(java.lang.String, java.lang.String, com.alibaba.nacos.api.naming.pojo.Instance)
```
这个方法中，有个beatReactor.addBeatInfo();会定时给nacos-server发心跳。如果服务端没有实例的话，会重新注册该实例。

**Comment by XiaoweiM** [comment]
nacos 通过心跳续约，网络恢复后通过心跳会重新注册服务

**Comment by bestpayAmes** [comment]
thanks
