### ISSUE TITLE
no provider exception

### ISSUE THREAD

**Issue by renkchina** [apache/dubbo#7513]
### Environment

* Dubbo version: 2.7.8
* Operating System version: nacos1.4.1+k8s+docker
* Java version: 1.8

### Steps to reproduce this issue

1. 在服务启动后，可以正常使用，通过telnet 查看如下
![2021-04-07](https://user-images.githubusercontent.com/17176354/113834284-3e9cab00-97bd-11eb-901c-48d0c850c6ee.png)
2.当过一段时间后，使用telnet 就连不上了。但是nacos上显示服务在线可用状态，日志出现如下
![_2021-04-07](https://user-images.githubusercontent.com/17176354/113834921-f3cf6300-97bd-11eb-87f0-d53d93f0bca8.png)
3. 然后重启该服务又好了。

4.过段时间又重复发生。
能否帮助排查一下问题所在。谢谢

**Comment by CrazyHZM** [comment]
Confirm whether the service port is still listening. If it is not listening, there may be a problem with the service.
Temporarily close the issues first, if there are still problems, you can open the issues at any time.

**Comment by xiaobing1** [comment]
Environment
Dubbo version: 2.7.8
Operating System version: nacos+k8s+docker
Java version: 1.8
spring.cloud.alibaba.version: 2.2.6.RELEASE

也出现类似的问题， nacos上可以看到注册列表, 重新部署后调用出现No provider， 比较长一段时间才恢复正常

能否帮助排查一下问题
