### ISSUE TITLE
Nacos对应的注册中心、元数据中心、配置中心的namespace行为不一致

### ISSUE THREAD

**Issue by kevinw66** [apache/dubbo#7514]
```java
public class NacosDynamicConfigurationFactory extends AbstractDynamicConfigurationFactory {

    @Override
    protected DynamicConfiguration createDynamicConfiguration(URL url) {
        URL nacosURL = url;
        if (CommonConstants.DUBBO.equals(url.getParameter(PropertyKeyConst.NAMESPACE))) {
            // Nacos use empty string as default name space, replace default namespace "dubbo" to ""
            nacosURL = url.removeParameter(PropertyKeyConst.NAMESPACE);
        }
        return new NacosDynamicConfiguration(nacosURL);
    }
}
```
Dubbo在创建Nacos配置中心的时候，默认过滤了名为dubbo的namespace。但是在注册中心和元数据中心里却没有主动过滤，就导致用户手动指定命名空间为`dubbo`时行为不一致。了解了代码之后发现是configcenter默认使用`dubbo`作为命名空间，而Nacos没有提供namespace的api并且默认namespace为空字符串所以新增的这段代码。

目前的认为可以这样处理
1、如果nacos-client后续提供namespace操作的api，Dubbo这边就手动check并创建dubbo namespace
2、如果nacos-client后续不提供的话，三个地方都主动过滤dubbo namespace
3、和`NacosDynamicConfiguration`类似，直接使用HttpAgent调用rest接口check并创建dubbo namespace

又或者说依旧保持这样，没必要改？

**Comment by xiaoheng1** [comment]
In dubbo, you can set namespace in properties.
such as nacosProperties.put("namespace", "dubbo") if we need.
com.alibaba.nacos.api.NacosFactory#createConfigService(java.util.Properties)

**Comment by kevinw66** [comment]
> In dubbo, you can set namespace in properties.
> such as nacosProperties.put("namespace", "dubbo") if we need.
> com.alibaba.nacos.api.NacosFactory#createConfigService(java.util.Properties)

This is a bug belongs to nacos and will be fixed in the future.
see more details in [#4134](https://github.com/alibaba/nacos/issues/4134)

**Comment by xiaoheng1** [comment]
i get it，thanks
