### ISSUE TITLE
NullPointException on method referenceConfig.get called

### ISSUE THREAD

**Issue by zhaopengchengg** [apache/dubbo#7515]
![image](https://user-images.githubusercontent.com/25955609/113846968-97724080-97c9-11eb-9513-e30a8587416d.png)
![image](https://user-images.githubusercontent.com/25955609/113847054-a953e380-97c9-11eb-9da4-994cca1f096b.png)
this getTarget() return null
![image](https://user-images.githubusercontent.com/25955609/113847209-d0121a00-97c9-11eb-84df-1ee9b747ed89.png)
Repetition steps:
1.just start a provider service
2.invoke a dubbo api ,init a ReferenceConfig instance ,it will throw no such provider exception
3.start the provider
4.invoke this dubbo api agin ,init a ReferenceConfig instance ,it will throw a npt exception
this problem is found in dubbo 2.7.7 then i update to 2.7.9 ,the npt exception is gone

**Comment by horizonzy** [comment]
I will trace it.

**Comment by xiaoheng1** [comment]
This problem has been fixed in the latest version.

&READY-TO-CLOSE&

**Comment by zhaopengchengg** [comment]
sorry i write a wrong word in the Repetition steps:
the correct step 1 :   just start a consumer service
and others step is correct.

i have try 2.7.0 version, i have not get this exception;maybe it just appear in 2.7.7

**Comment by AlbumenJ** [comment]
Please upgrade to 2.7.9 or later. Bugfix just fix in the future version.
