### ISSUE TITLE
Potential OOM risks

### ISSUE THREAD

**Issue by liudaolunboluo** [apache/dubbo#7521]
`com.alibaba.dubbo.common.threadpool.support.fixed.FixedThreadPool `

```java
return new ThreadPoolExecutor(threads, threads, 0, TimeUnit.MILLISECONDS,
              queues == 0 ? new SynchronousQueue<Runnable>() :
                      (queues < 0 ? new LinkedBlockingQueue<Runnable>()
                              : new LinkedBlockingQueue<Runnable>(queues)),
              new NamedThreadFactory(name, true), new AbortPolicyWithReport(name, url));
```

```java
new LinkedBlockingQueue<Runnable>()；
```

If the queues is less than 0, then the workqueue is an unbounded queue, and oom may be triggered here

**Comment by skyguard1** [comment]
@chickenlj When the queue parameter is less than 0, how about throwing an exception directly, or setting a default queue size

**Comment by liudaolunboluo** [comment]
> @chickenlj When the queue parameter is less than 0, how about throwing an exception directly, or setting a default queue size

Or use synchronous queue

**Comment by kevinw66** [comment]
I don't think this is a problem. 
You can find similar code in `Executors.newFixedThreadPool()`, also we'll set queue default to 0 and use SynchronousQueue if user is not specify the parameter. 
You should set queue to a positive number if you want a bounded queue. And if you set this parameter to a negative number, you should know exactly what you are doing.

**Comment by liudaolunboluo** [comment]
@kevinw66  Alibaba java development manual clearly points out that the reason why the thread pool provided by JDK can not be used is that it may cause oom. I think it should also be observed here. There is an old Chinese saying that "a gentleman does not stand under a dangerous wall". If I do not give a default size, the online environment may receive requests unlimited until oom

**Comment by kevinw66** [comment]
> Alibaba java development manual clearly points out that the reason why the thread pool provided by JDK can not be used is that it may cause oom.

Agreed, and that's why we add `queue` parameter here to let user to choose which way they want to use, and set it default to 0 to use SynchronousQueue to prevent this situation if the user did not set value or didn't know the meaning of this parameter.
But we also keep the unbounded queue to let user choose if they do want to use, to meets all requirements.

**Comment by liudaolunboluo** [comment]
@kevinw66  If it's to meet all the requirements, why can't workqueue be created by users themselves?

**Comment by liudaolunboluo** [comment]
@kevinw66   Sorry, I just reviewed the source code carefully. You can use Dubo's extensionloader to extend and implement the ThreadPool interface to define the thread pool. However, I still think that there should be no oom risk in the default implementation here. Even if the user has different requirements, he can implement the ThreadPool interface to define the thread pool himself

**Comment by AlbumenJ** [comment]
In my opinion, if users define `queues` is less than 0, he should know what this means. As for framework, we make it default a safe value (0).

**Comment by CrazyHZM** [comment]
I will close the issues temporarily. If there are any problems, I can open the issues at any time.
