### ISSUE TITLE
 dubbo 2.7.10 与 nacos 1.4.1 不兼容

### ISSUE THREAD

**Issue by Johnson-Jia** [apache/dubbo#7524]
dubbo 2.7.10 版本 与 nacos-client 1.4.1 版本不兼容

NacosDynamicConfiguration.java
```
  HttpSimpleClient.HttpResult result = httpAgent.httpGet(GET_CONFIG_KEYS_PATH, emptyList(), paramsValues, encoding, 5 * 1000);
            Stream<String> keysStream = toKeysStream(result.content);
```

**Comment by AlbumenJ** [comment]
could you please provide a demo or your configuration?

**Comment by Johnson-Jia** [comment]
nacos-client 1.4.1 移除了这个类 HttpSimpleClient.java 

nacos-client 1.3.2    1.3.3   1.4.0    HttpAgent.httpGet  方法参数与 dubbo 2.7.10 使用的不兼容。

不兼容代码如下： NacosDynamicConfiguration.java  271 行
```
HttpSimpleClient.HttpResult result = httpAgent.httpGet(GET_CONFIG_KEYS_PATH, emptyList(), paramsValues, encoding, 5 * 1000);
            Stream<String> keysStream = toKeysStream(result.content);
```

**Comment by kevinw66** [comment]
确实，这个是因为agent用了nacos-client的`HttpAgent`类，nacos不同版本这个接口返回值类型也不同，贸然升级版本的话有些用低版本的nacos-client的工程也会出问题。这边你先试试使用dubbo引入的1.3.1版本的nacos-client看看是否会出问题呢？

**Comment by horizonzy** [comment]
we should disscuss how to solve it.

**Comment by Johnson-Jia** [comment]
2.7.8 版本依赖  nacos-client 1.4.1 没问题，应该是2.7.8 没有启用动态配置 ？  2.7.10 默认启动了，所以项目初始化的时候 执行就报错了。

**Comment by AlbumenJ** [comment]
HttpAgent 在最新的 nacos-client 2.0.0 （版本向前兼容）已经临时加回去了，未来在 3.x 版本中将重构掉这一块 

nacos-client 2.0.0 信息：https://search.maven.org/artifact/com.alibaba.nacos/nacos-client/2.0.0/jar

nacos 相关 PR https://github.com/alibaba/nacos/issues/4976

**Comment by Johnson-Jia** [comment]
> HttpAgent 在最新的 nacos-client 2.0.0 （版本向前兼容）已经临时加回去了，未来在 3.x 版本中将重构掉这一块
> 
> nacos-client 2.0.0 信息：https://search.maven.org/artifact/com.alibaba.nacos/nacos-client/2.0.0/jar
> 
> nacos： [alibaba/nacos#4976](https://github.com/alibaba/nacos/issues/4976) [alibaba/nacos#4977](https://github.com/alibaba/nacos/pull/4977)

@AlbumenJ  这个解决的不是上面提到的问题。

**Comment by ChinaJeckXu** [comment]
🐞 2.7.8 升 2.7.10 同款问题

**Comment by AlbumenJ** [comment]
This has been fix in 2.7.11. #7676
