### ISSUE TITLE
Kryo serialization only used from provider to consumer

### ISSUE THREAD

**Issue by schneebuzz** [apache/dubbo#7527]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate (not reachable).

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: Windows 8.1
* Java version: 1.8

### Steps to reproduce this issue

I want to use kryo serializer but when I configure protocol=dubbo and serializer=kryo it seems to only use kryo when serializing on the provider side.

1. Setup provider with `dubbo-serialization-kryo` using API configuration with `protocolConfig.setSerialization("kryo")`
2. Setup consumer with `dubbo-serialization-kryo` on CP
3. Launch
4. Request data from the provider using consumer, data is custom type -> OK
5. Send other data from consumer to provider, data is same type -> Error (see below)

### Expected Result

I expect that kryo is used for serialization in both directions.

### Actual Result
What actually happens?
Serialization for consumer -> provider is using hessian which leads to the following error

```
org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: setSetting, provider: [...], cause: org.apache.dubbo.remoting.RemotingException: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Serialized class com.example.CustomType must implement java.io.Serializable
```

Is this a bug when negotiating the serializer or do I have the wrong configuration?
How do I tell the consumer to use kyro for serialization?

**Comment by xiaoheng1** [comment]
Can you provide a demo to reproduce this problem?

**Comment by schneebuzz** [comment]
Please see this simple example project: https://github.com/schneebuzz/dubbo_reprod_serialization_example

When removing `protocol.setSerialization("kryo");` in ProviderConfig.java and adding `implements Serializable` in Data.java, it works in both directions.

**Comment by xiaoheng1** [comment]
If it is a direct connection, there are two solutions:
1. The data implements serialization interface. Although the serialization type of provider and consumer are inconsistent, it does not affect data transmission.
2. The consumer side uses parameter to set the serialization type.

**Comment by schneebuzz** [comment]
@xiaoheng1 Yes it is a direct connection currently.
How can the serialization type parameter be set on the consumer side? Is there a way to use the API configuration?

**Comment by xiaoheng1** [comment]
you can use parameter to set the serialization type in consumer side.

like this: 

HashMap<String, String> parameter = new HashMap<>();
parameter.put("serialization", "kryo");
referenceConfig.setParameters(parameter);

**Comment by schneebuzz** [comment]
Oh.. Right, this does the trick of course.

So I think this is ok for the serialization type to only be exchanged when using a registry. In case of a direct connection, the consumer can be explicitly set to use a specific serialization type.
