### ISSUE TITLE
RegistryProtocol registerStatedUrl NPE.

### ISSUE THREAD

**Issue by harvies** [apache/dubbo#7529]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

RegistryProtocol registerStatedUrl NPE.

![image](https://user-images.githubusercontent.com/16585330/114278557-fd2d2980-9a62-11eb-92e7-24754bd26e01.png)

**Comment by horizonzy** [comment]
Hi, how did this issue occur.

**Comment by harvies** [comment]
> Hi, how did this issue occur.

The problem can be reproduced by running RegistryProtocolTest on the master branch.

**Comment by horizonzy** [comment]
I execute the test unit, but it works well, did you make sure your code is newest.

**Comment by xiaoheng1** [comment]
I also execute the test unit, but it works well.

**Comment by harvies** [comment]
> I execute the test unit, but it works well, did you make sure your code is newest.



> I also execute the test unit, but it works well.

Sorry, you should run org.apache.dubbo.registry.dubbo.RegistryProtocolTest#testExport separately.

**Comment by xiaoheng1** [comment]
> testExport

I think this is a test case problem, just modify the corresponding test case.

**Comment by FritzFeng** [comment]
![image](https://user-images.githubusercontent.com/33932843/115005146-270aa400-9eda-11eb-862b-40b60663e19c.png)
![image](https://user-images.githubusercontent.com/33932843/115005454-73ee7a80-9eda-11eb-88ec-9c112c076082.png)
@xiaoheng1

**Comment by harvies** [comment]
The application-level version configuration does not take effect.

**Comment by xiaoheng1** [comment]
@FritzFeng Can you provide a demo to reproduce ？

**Comment by zjutbang** [comment]
Hi, when use dubbo group feature, the problem will be occur.  When I debug the code, I found may be the code is not correct. 
org.apache.dubbo.config.ServiceConfigBase#getUniqueServiceName。I find the method in 2.7.7 version, the group maybe from provider group configuration. but in 2.7.10 not.

**Comment by zjutbang** [comment]
![企业微信截图_16188164385495](https://user-images.githubusercontent.com/1459934/115195889-e00eef80-a121-11eb-8ec1-cf0811e70d9d.png)

**Comment by wuwen5** [comment]
+1
maybe introduced  a bug ?  #6179
