### ISSUE TITLE
Suggestion：Constantize some configurations

### ISSUE THREAD

**Issue by rockit-ba** [apache/dubbo#7531]
For example, cluster and loadbalance ... strategies can be constant，string or enum.

**Comment by horizonzy** [comment]
can you explain it detaily.

**Comment by rockit-ba** [comment]
> can you explain it detaily.


this source code:
```
   /**
     * Load balance strategy, legal values include: random, roundrobin, leastactive
     */
    String loadbalance() default DEFAULT_LOADBALANCE;
```
when we use,we do this:
`@DubboService(loadbalance = "roundrobin")`

better, strategies can be designed as constant, for exemple:
```
public class LoadbalanceStrategy {
    public final static String ROUNDROBIN = "roundrobin";
}

@DubboService(loadbalance = LoadbalanceStrategy.ROUNDROBIN)
```
Similarly，cluster can also be designed like this。this can prevent users from writing mistakes.

**Comment by horizonzy** [comment]
Looks good, can you submit a pr to support it.

**Comment by rockit-ba** [comment]
> Looks good, can you submit a pr to support it.

ok , no problem .
