### ISSUE TITLE
Dubbo版本（2.7.8）无法消费Dubbo（2.5.10）服务，报错 no provider

### ISSUE THREAD

**Issue by fxbyun** [apache/dubbo#7538]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. Dubbo版本（2.7.8）无法消费Dubbo（2.5.10）服务，报错 no provider，如图：
![image](https://user-images.githubusercontent.com/18391971/114558105-eb36cb00-9c9c-11eb-9d16-de3aea90bb74.png)

<img width="918" alt="企业微信截图_16182239077086" src="https://user-images.githubusercontent.com/18391971/114558233-0b668a00-9c9d-11eb-8d50-3d69d9c63331.png">

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by xiaoheng1** [comment]
Please upgrade the server dubbo version.

**Comment by fxbyun** [comment]
> Please upgrade the server dubbo version.

yes，use 2.7.10，Solved the problem

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
