### ISSUE TITLE
MulticastRegistryTest#testUrlError failed

### ISSUE THREAD

**Issue by pinxiong** [apache/dubbo#7566]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: `2.7.11-SNAPSHOT`
* Operating System version: Mac OS
* Java version: 1.8

### Steps to reproduce this issue

run `org.apache.dubbo.registry.multicast.MulticastRegistryTest#testUrlError` and then throw `java.lang.IllegalArgumentException`

### Expected Result

It should throw `java.lang.IllegalStateException`

### Actual Result
![MulticastRegistryTest#testUrlError failed](https://user-images.githubusercontent.com/7067417/114860636-d2562300-9e1e-11eb-9ee6-fd2828368d27.png)

**Comment by xiaoheng1** [comment]
do you modify the host file? 

such as add 127.0.0.1 mullticast.

**Comment by pinxiong** [comment]
I'm sure I didn't do that. My hosts are as follows

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

In some companies, there are short domains to simplify the full domain. So, the OPS team will set some rules to convert the short domain to IP address(if the domain doesn't exist, it will convert to the default IP address). Sometimes, the short domains is a string without separating with dots.

So, we’d better let the domain name contain dots as an example. You can see the tests in #7567

**Comment by xiaoheng1** [comment]
Thank you very much, I understand it.

**Comment by pinxiong** [comment]
close #7566
