### ISSUE TITLE
Dubbo 配置梳理优化

### ISSUE THREAD

**Issue by kylixs** [apache/dubbo#7574]
**现状：**
dubbo 2.7.9 及之前，在使用dubbo-spring-boot 组件时会将spring environment配置属性注入到dubbo environment propertiesConfiguration 中。如果不使用dubbo-spring-boot 组件，则不会注入spring配置属性。这种不一致的行为给dubbo 属性配置覆盖带来了困难。

**优化目标：**
1、如果应用使用了Spring框架，不管是否使用dubbo-spring-boot，dubbo environment 配置都会引入spring environment的property sources。目的是打通配置，然后在AbstractConfig.refresh() 的属性覆盖处理时可以使用到spring的配置属性。

配置优先级查找顺序为（前面的比后面的优先级高）：
system props > java environment > config-center app config > config-center global config  > spring environment > dubbo.properties in classpath 

**Dubbo 3 属性配置说明** (https://github.com/apache/dubbo/issues/7890)

2、统一梳理配置属性，并移除configCenterFirst / include-spring-env 这两个参数。
  注： include-spring-env 参数保持不变，用于从Spring Environment中提取dubbo.properties等配置的内容，并将内容解析为properties，作为Dubbo 外部配置。

3、支持service/reference 方法属性配置覆盖，包括API/xml/注解三种不同的场景都支持
Dubbo 2.7.8 在properties文件中指定service的registry不生效 (https://github.com/apache/dubbo/issues/7348)

**Comment by kylixs** [comment]
似乎存在属性配置矛盾： 强制覆盖 or 默认配置  不清晰？
1、Dubbo 2.7 > 用户文档 > 用法示例 >  启动时检查
https://dubbo.apache.org/zh/docs/v2.7/user/examples/preflight-check/

> dubbo.reference.check=false，强制改变所有 reference 的 check 值，就算配置中有声明，也会被覆盖。
> 
> dubbo.consumer.check=false，是设置 check 的缺省值，如果配置中有显式的声明，如：<dubbo:reference check="true"/>，不会受影响。

2、Dubbo 2.7 > 用户文档 > 配置 > 属性配置
https://dubbo.apache.org/zh/docs/v2.7/user/configuration/properties/

> 优先级从高到低：
> 
> JVM -D 参数：当你部署或者启动应用时，它可以轻易地重写配置，比如，改变 dubbo 协议端口；
> XML：XML 中的当前配置会重写 dubbo.properties 中的；
> Properties：默认配置，仅仅作用于以上两者没有配置时。


3、Dubbo 2.7 > 用户文档 > 配置 > 配置加载流程
https://dubbo.apache.org/zh/docs/v2.7/user/configuration/configuration-load-process/


**例子1：**
**1、Spring XML 定义**
```
 <dubbo:registry address="zookeeper://localhost:2181"  />
 <dubbo:reference interface="a.b.DemoService"  check="true" />
```

**2、dubbo.properties**
```
dubbo.registry.address=zookeeper://192.168.1.10:2181
dubbo.registry.check=false
dubbo.reference.check=false
```
疑问： 
1)dubbo.reference.check配置是否覆盖XML定义的Reference check属性？
   
2)dubbo.registry.address 是否可以覆盖？

3)dubbo.registry.check 是否有效？

**3、Spring application.properties**
```
dubbo.registry.address=zookeeper://192.168.1.10:2181
dubbo.registry.check=false
dubbo.reference.check=false
```
疑问：同上

4、System properties
```
-Ddubbo.registry.address=zookeeper://192.168.1.10:2181
-Ddubbo.registry.check=false
-Ddubbo.reference.check=false
```
疑问：同上

**Comment by zhangyz-hd** [comment]
我的一点观点

1，优化目标1非常赞同，不管是否使用了dubbo-spring-boot，dubbo environment的行为应该是一致的。1的优先级也赞同。

2，语法上，不应该存在dubbo.reference.check=false，因为这也不符合XML配置时的语义传统（dubbo.consumer）。

3，关于properties与xml的覆盖关系，个人认为properties应该覆盖xml，对企业应用来说，propertis的key=value形式的文本才适合线上参数化管理，xml因为还记录依赖关系，过于复杂容易出错。

4，而dubbo.registry.check和reference.check关系上，是不是应该坚持“个性>共性”的原则，个性参数覆盖共性参数。

5，在属性覆盖上，我还有一点疑问，消费者端当配置属性=默认值时，无法覆盖消费者的属性（如提供者端async=true，消费者端asycn=false）

**Comment by pinxiong** [comment]
> 我的一点观点
> 
> 1，优化目标1非常赞同，不管是否使用了dubbo-spring-boot，dubbo environment的行为应该是一致的。1的优先级也赞同。
> 
> 2，语法上，不应该存在dubbo.reference.check=false，因为这也不符合XML配置时的语义传统（dubbo.consumer）。
> 
> 3，关于properties与xml的覆盖关系，个人认为properties应该覆盖xml，对企业应用来说，propertis的key=value形式的文本才适合线上参数化管理，xml因为还记录依赖关系，过于复杂容易出错。
> 
> 4，而dubbo.registry.check和reference.check关系上，是不是应该坚持“个性>共性”的原则，个性参数覆盖共性参数。
> 
> 5，在属性覆盖上，我还有一点疑问，消费者端当配置属性=默认值时，无法覆盖消费者的属性（如提供者端async=true，消费者端asycn=false）

@zhangyz-hd 非常赞同你提到的1、2、3和4点。对于你提到的第5点，个人认为consumer和provider的配置本身应该是相互隔离的，互不干扰，不应该存在覆盖的问题

**Comment by zhangyz-hd** [comment]
> > 我的一点观点
> > 1，优化目标1非常赞同，不管是否使用了dubbo-spring-boot，dubbo environment的行为应该是一致的。1的优先级也赞同。
> > 2，语法上，不应该存在dubbo.reference.check=false，因为这也不符合XML配置时的语义传统（dubbo.consumer）。
> > 3，关于properties与xml的覆盖关系，个人认为properties应该覆盖xml，对企业应用来说，propertis的key=value形式的文本才适合线上参数化管理，xml因为还记录依赖关系，过于复杂容易出错。
> > 4，而dubbo.registry.check和reference.check关系上，是不是应该坚持“个性>共性”的原则，个性参数覆盖共性参数。
> > 5，在属性覆盖上，我还有一点疑问，消费者端当配置属性=默认值时，无法覆盖消费者的属性（如提供者端async=true，消费者端asycn=false）
> 
> @zhangyz-hd 非常赞同你提到的1、2、3和4点。对于你提到的第5点，个人认为consumer和provider的配置本身应该是相互隔离的，互不干扰，不应该存在覆盖的问题

dubbo默认的有部分consumer和provider都可以配置但作用在consumer的属性，是可以由consumer覆盖的（如timeout、retries、loadbalance、actives），但async一直不能（从2.5开始），这也是我的不解。

**Comment by kylixs** [comment]
> dubbo默认的有部分consumer和provider都可以配置但作用在consumer的属性，是可以由consumer覆盖的（如timeout、retries、loadbalance、actives），但async一直不能（从2.5开始），这也是我的不解。

consumer的文档：https://dubbo.apache.org/zh/docs/v2.7/user/references/xml/dubbo-consumer/
> 服务消费者缺省值配置。配置类： org.apache.dubbo.config.ConsumerConfig 。同时该标签为 <dubbo:reference> 标签的缺省值设置。

按照设计文档描述，可以通过consumer 设置reference的缺省属性，即如果reference的某个属性没设置，应该去检查consumer的对应属性。 这个逻辑是在代码中实现的，某些后来加上去的属性可能就不支持这个规则。
类似的，provider 上设置service的缺省属性，也是在代码逻辑中实现的。这些功能没有太好的办法，只能通过增加测试案例来保证稳定性，欢迎提交改进PR。

**Comment by kylixs** [comment]
其中ReferenceConfig使用consumer属性的代码，原理是先添加consumer的属性，然后覆盖reference的属性，如果存在同一个属性则会覆盖consumer的对应属性：
```
public synchronized void init() {
        ....
        AbstractConfig.appendParameters(map, getApplication());
        AbstractConfig.appendParameters(map, getModule());
        AbstractConfig.appendParameters(map, consumer);
        AbstractConfig.appendParameters(map, this);
        ....
```

**Comment by pinxiong** [comment]
> > dubbo默认的有部分consumer和provider都可以配置但作用在consumer的属性，是可以由consumer覆盖的（如timeout、retries、loadbalance、actives），但async一直不能（从2.5开始），这也是我的不解。
> 
> consumer的文档：https://dubbo.apache.org/zh/docs/v2.7/user/references/xml/dubbo-consumer/
> 
> > 服务消费者缺省值配置。配置类： org.apache.dubbo.config.ConsumerConfig 。同时该标签为 dubbo:reference 标签的缺省值设置。
> 
> 按照设计文档描述，可以通过consumer 设置reference的缺省属性，即如果reference的某个属性没设置，应该去检查consumer的对应属性。 这个逻辑是在代码中实现的，某些后来加上去的属性可能就不支持这个规则。
> 类似的，provider 上设置service的缺省属性，也是在代码逻辑中实现的。这些功能没有太好的办法，只能通过增加测试案例来保证稳定性，欢迎提交改进PR。

> 其中ReferenceConfig使用consumer属性的代码，原理是先添加consumer的属性，然后覆盖reference的属性，如果存在同一个属性则会覆盖consumer的对应属性：
```java
public synchronized void init() {
        ....
        AbstractConfig.appendParameters(map, getApplication());
        AbstractConfig.appendParameters(map, getModule());
        AbstractConfig.appendParameters(map, consumer);
        AbstractConfig.appendParameters(map, this);
        ....
        serviceMetadata.getAttachments().putAll(map);
        ref = createProxy(map);
        ....
}
```

对于你提到的问题，我第一感觉是逻辑太复杂了。如果要想很好的解决这个问题可以从以下几个方面着手：

1. 将复杂逻辑简化（感觉可能性不是很大，因为要考虑兼容性问题），但一定要建立这样的思想，否则后面会越假越复杂。
2. 将复杂逻辑固定下来形成标准（目前应该已经有文档了，但是并不是每个维护的人都会看）。
3. 将`AbstractConfig.appendParameters()`方法的使用收口在一个地方，内部维护一个完成的复杂的覆盖流程，支持以任何顺序传入配置都会得到相同的覆盖结果。这样一来，不管在哪里调用，都不用关心覆盖结果不正确的问题。
4. 加强test cases的覆盖程度

目前看下来，第3、4点是比较靠谱
