### ISSUE TITLE
Use double-check to get elements from the cache

### ISSUE THREAD

**Issue by BurningCN** [apache/dubbo#7584]
Before we` LOCK.lock()`, we can try to fetch it from the `SERVICE_STORE_MAP` and return it (if non-null), eliminating an unnecessary lock, just like we do with double-check elsewhere.

The screenshot below:
![image](https://user-images.githubusercontent.com/43363120/115175186-230a9c00-a0fd-11eb-8362-aceddb52d926.png)

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Comment by AlbumenJ** [comment]
close #7584 via #7583
