### ISSUE TITLE
Issue that could lead to multiple init in MetadataReportInstance#init

### ISSUE THREAD

**Issue by BurningCN** [apache/dubbo#7585]
In `MetadataReportInstance#init` , if multiple threads come in at the same time and determine that `init.get()` is false, then the following steps will be taken, resulting in multiple initialization-related code logic. Here we should use `CAS` to update the value of `init`. This ensures that it will only be initialized once

![image](https://user-images.githubusercontent.com/43363120/115179145-3cafe180-a105-11eb-826c-5618dce99599.png)

**Comment by ZuoQiwen** [comment]
MetadataReportInstance.init method only be used  when DubboBootstrap. call the initialize, normally we will not be multiple threads to initialize the object

**Comment by BurningCN** [comment]
> MetadataReportInstance.init method only be used when DubboBootstrap. call the initialize, normally we will not be multiple threads to initialize the object

In your opinion, there is no need to use an `AtomicBoolean` type

**Comment by ZuoQiwen** [comment]
yes ,the current version MetadataReportInstance#init AtomicBoolean  boolean is the same, bescause  AtomicBoolean does not take effect now

**Comment by AlbumenJ** [comment]
close #7585 via #7586
