### ISSUE TITLE
dubbo supports duplicate filters which are defined by user，can be optimized?

### ISSUE THREAD

**Issue by tongweitao** [apache/dubbo#7587]
In dubbo ,it supports  duplicate filters which are defined by user，this situation is normal or can be optimized?
and then i found there is no priority concept in some dubbo configurations 。
It's my opinion above,  can you help me out with any queries?
thanks!

**Comment by tongweitao** [comment]
duplicate filters situation：for example , define a log filter both in <dubbo:provider> and <dubbo:service>

**Comment by cnlin** [comment]
make the filter as an SPI impl may be work

**Comment by xiaoheng1** [comment]
I think this may need to be de-duplicated.

**Comment by ZuoQiwen** [comment]
定义一个Filter日志实现类@Activate(group = {CommonConstants.PROVIDER,CommonConstants.CONSUMER），group支持提供者和消费者即可

**Comment by tongweitao** [comment]
> I think this may need to be de-duplicated.

thanks for reply。i replenish a sense i have meeted in my work : In a project, if a developer-A  define a filter called "logFilter" and configure in <dubbo:provider ... filter="logFilter"> , after some days , another developer-B configure this filter in <dubbo:serviceA ... filter="logFilter">  ,  so when the serviceA is be asked, it will exec the logFilter twice。 the biggest reason is the two developers  is not coded rightly , but i think can dubbo-framework supports  filter de-duplicated mechanism,  otherwise the filter chain is builded  through  <List>  by URL-Parameter：

`public List<T> getActivateExtension(URL url, String[] values, String group) {
        List<T> activateExtensions = new ArrayList<>();
        // solve the bug of using @SPI's wrapper method to report a null pointer exception.
        TreeMap<Class, T> activateExtensionsMap = new TreeMap<>(ActivateComparator.COMPARATOR);
        List<String> names = values == null ? new ArrayList<>(0) : asList(values);
.....}`

how about the other SPI with @activate defined by user?

**Comment by ZuoQiwen** [comment]
yes getActivateExtension method return as a list and not de-duplicated

**Comment by xiaoheng1** [comment]
@tongweitao This issue will be fixed in the next version.
