### ISSUE TITLE
nacos 配置列表中出现很多以接口名为dataid 的dubbo的配置文件，如何关闭呢？

### ISSUE THREAD

**Issue by lomodays207** [apache/dubbo#7598]
**Describe the bug**
组件版本信息：

dubbo 2.7.8 + nacos client 1.3.1  + spring boot 2.3.2.RELEASE  

只使用到了dubbo的服务注册功能，但是在nacos 配置列表中也有 配置列表自动出现很多以接口为group的配置文件

![image](https://user-images.githubusercontent.com/16081650/115500787-9a2e6480-a2a4-11eb-8c63-513e3a21474d.png)

**Expected behavior**
只想用服务注册功能，去掉配置列表自动出现很多以接口为group的配置文件

1. 参考了大家的配置，加了 **use-as-config-center: false** 也不生效。
2. #4491  dubbo 参照这个升级到 2.7.9 依然是同样的问题；

nacos:
  service-address: 192.168.150.111
  port: 8848

dubbo:
  registry:
    use-as-config-center: false
    address: nacos://${nacos.service-address}:${nacos.port}/?username=nacos&password=nacos
    parameters:
      namespace: 6dc0bc70-49c5-4202-ae4f-95558c81f837
  protocol:
    name: dubbo
    port: 20881

**Comment by kevinw66** [comment]
Dubbo启动的时候默认会把注册中心作为配置中心和元数据中心使用，这部分信息应该是元数据的配置，如果要去掉的话试试在配置文件里加上`dubbo.registry.use-as-metadata-center=false`这个配置看看行不行

**Comment by qinyi8888** [comment]
> Dubbo启动的时候有时会把注册中心作为配置中心和元数据中心使用，这部分信息应该是元数据的配置，如果要去掉的话试试在配置文件里加上`dubbo.registry.use-as-metadata-center=false`这个配置看看行不行

添加上可以去掉，后续再测添加上之后是否会有其他影响，感谢！
nacos版本：1.4.1
dubbo版本：2.7.8
配置如下：
dubbo:
   registry:
      address: nacos://127.0.0.1:8848?username=nacos&password=nacos
      use-as-metadata-center: false
      use-as-config-center: false

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
