### ISSUE TITLE
Method may be null, and NullPointerException will be thrown in MethodUtils

### ISSUE THREAD

**Issue by skyguard1** [apache/dubbo#7605]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10
* Operating System version: macos
* Java version: java8

### Steps to reproduce this issue

Method may be null, and NullPointerException will be thrown in MethodUtils

### Expected Result

NullPointerException will not be thrown

**Comment by AlbumenJ** [comment]
close #7605 via #7606
