### ISSUE TITLE
dubbo使用nacos作为注册中心，服务却在nacos的配置列表下展示

### ISSUE THREAD

**Issue by jgswp** [apache/dubbo#7612]
spring-cloud-starter-dubbo 2.2.5

<img width="522" alt="图片" src="https://user-images.githubusercontent.com/35256326/115943166-f5e53180-a4e0-11eb-9bf6-5df6858bd8c9.png">
注册的服务到了配置中心的列表
<img width="1302" alt="图片" src="https://user-images.githubusercontent.com/35256326/115943181-0eede280-a4e1-11eb-8a77-74f1dd0c3eca.png">

**Comment by kevinw66** [comment]
Dubbo启动的时候默认会把注册中心作为配置中心和元数据中心使用，若不希望有这些数据出现在配置列表里，则在项目配置文件上加上以下两行
```
dubbo.registry.use-as-metadata-center=false
dubbo.registry.use-as-config-center=false
```

**Comment by pinxiong** [comment]
@jgswp Can this issue be closed? If necessary, we can open it again.

**Comment by zuonidelaowang** [comment]
> Dubbo启动的时候默认会把注册中心作为配置中心和元数据中心使用，若不希望有这些数据出现在配置列表里，则在项目配置文件上加上以下两行
> 
> ```
> dubbo.registry.use-as-metadata-center=false
> dubbo.registry.use-as-config-center=false
> ```

加上这两个配置，consumer 调用的时候  就找不到 provider

这个问题你遇到过吗？

**Comment by jgswp** [comment]
没有遇到这个情况，可以检查一下端口是否打开



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月18日(星期四) 中午1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dubbo] dubbo使用nacos作为注册中心，服务却在nacos的配置列表下展示 (#7612)





  
Dubbo启动的时候默认会把注册中心作为配置中心和元数据中心使用，若不希望有这些数据出现在配置列表里，则在项目配置文件上加上以下两行
 dubbo.registry.use-as-metadata-center=false dubbo.registry.use-as-config-center=false   
加上这两个配置，consumer 调用的时候  就找不到 provider
 
这个问题你遇到过吗？
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
