### ISSUE TITLE
The Consumer will not work when id is null in <dubbo:reference>

### ISSUE THREAD

**Issue by spilledyear** [apache/dubbo#7614]
1. I define a consumer in xml， eg:
<dubbo:reference interface="com.tuya.seata.service.seata.StorageService"/>

2. Then I start the Application，debug and found that there never create a BeenDefine for <dubbo:reference> in DubboBeanDefinitionParser#parse， source code like that：
![image](https://user-images.githubusercontent.com/24663965/115953978-02897a00-a521-11eb-8f1b-8059a2183266.png)

is this a bug？ thanks for help

**Comment by xiaoheng1** [comment]
@spilledyear In my opinion, this should be a bug.
