### ISSUE TITLE
Field may be null, and NullPointerException will be thrown in FieldUtils

### ISSUE THREAD

**Issue by skyguard1** [apache/dubbo#7619]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

Dubbo version: 2.7.10
Operating System version: macos
Java version: java8

### Steps to reproduce this issue

Field may be null, and NullPointerException will be thrown in FieldUtils

### Expected Result

NullPointerException will not be thrown

**Comment by AlbumenJ** [comment]
close #7619 via #7620
