### ISSUE TITLE
注解模式和API模式telnet无法使用invoke

### ISSUE THREAD

**Issue by icankeep** [apache/dubbo#7646]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10
* Operating System version: MacOS
* Java version: 1.8.0_281

### Steps to reproduce this issue

1. clone代码
```bash
git clone git@github.com:apache/dubbo.git
git checkout -b 2.7.10 7b39089f
```
2. 分别运行dubbo-demo-annotation, dubbo-demo-api, dubbo-demo-xml的provider Application

**dubbo-demo-annotation**
![image](https://user-images.githubusercontent.com/39434627/116267824-54473400-a7af-11eb-8bf2-f61763e91b59.png)

**dubbo-demo-api**
![image](https://user-images.githubusercontent.com/39434627/116268040-8193e200-a7af-11eb-8910-31019057e453.png)

**dubbo-demo-xml**
![image](https://user-images.githubusercontent.com/39434627/116268168-a4be9180-a7af-11eb-9a6c-504e0e275817.png)

xml方式的telnet可以invoke，其他两种不行

请问一下是我使用的方式不对吗？还是说2.7.10版本的Dubbo 注解和api方式不支持telnet的invoke的那些参数？

**Comment by xiaoheng1** [comment]
This is caused by the introduction of the qos module in the xml project. I will mention a pr to adjust the package dependency of the xml demo to be consistent with the annotation module.

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
