### ISSUE TITLE
Dubbo升级到2.7.10，报错：compatible version of org.apache.curator.framework.api.CreateBuilder

### ISSUE THREAD

**Issue by fxbyun** [apache/dubbo#7658]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue
各种版本：
dubbo-spring-boot-starter：2.7.10
zookeeper：3.4.9
curator-recipes：2.12.0

报错信息：
![image](https://user-images.githubusercontent.com/18391971/116530723-ee72bd80-a910-11eb-9302-5373c9691220.png)

已经尝试将curator-recipes：2.12.0 升级到 4.0.1或者4.1.0，然后排除掉Zookeper依赖，依然报错，不过是NoClassDefFoundError错误

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by JayeShen** [comment]
我也遇到同样的错误，不过我解决了依赖冲突，你可以试一下 
<dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo</artifactId>
        <version>2.7.10</version>
    </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.4.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-x-discovery</artifactId>
            <version>4.0.1</version>
        </dependency>

**Comment by JayeShen** [comment]
<dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo</artifactId>
        <version>2.7.10</version>
    </dependency>
        <dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.4.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-x-discovery</artifactId>
            <version>4.0.1</version>
        </dependency>

**Comment by fxbyun** [comment]
> 我也遇到同样的错误，不过我解决了依赖冲突，你可以试一下
> 
> org.apache.dubbo
> dubbo
> 2.7.10
> 
> 
> org.apache.zookeeper
> zookeeper
> 3.4.6
> 
> 
> org.apache.curator
> curator-framework
> 4.2.0
> 
> 
> org.apache.curator
> curator-recipes
> 4.2.0
> 
> 
> org.apache.curator
> curator-x-discovery
> 4.0.1

可以用，非常感谢，但是产生了另一个问题，当配置多个zk的时候，会启动失败：
![image](https://user-images.githubusercontent.com/18391971/116540541-e1f46200-a91c-11eb-8772-e04ac1a1480e.png)
![image](https://user-images.githubusercontent.com/18391971/116540589-ee78ba80-a91c-11eb-9ded-3959bf7194c2.png)

报错信息：
A component required a bean named 'zk1' that could not be found.

**Comment by xiaoheng1** [comment]
@fxbyun can you provider a demo ?

**Comment by fxbyun** [comment]
> @fxbyun can you provider a demo ?



> 我也遇到同样的错误，不过我解决了依赖冲突，你可以试一下
> 
> org.apache.dubbo
> dubbo
> 2.7.10
> 
> 
> org.apache.zookeeper
> zookeeper
> 3.4.6
> 
> 
> org.apache.curator
> curator-framework
> 4.2.0
> 
> 
> org.apache.curator
> curator-recipes
> 4.2.0
> 
> 
> org.apache.curator
> curator-x-discovery
> 4.0.1

可以了，“A component required a bean named 'zk1' that could not be found.”这个问题是测试环境的问题，按照你方式可以完美解决

**Comment by fxbyun** [comment]
> @fxbyun can you provider a demo ?

已经解决了，谢谢！

**Comment by JayeShen** [comment]
> @fxbyun can you provider a demo ?

想问一下，dubbo2.7.10之后是准备都使用curator4.x.x的包了吗？
