### ISSUE TITLE
调用服务在consumer端和provider端记录不一致

### ISSUE THREAD

**Issue by xingcici** [apache/dubbo#7663]
dubbo 版本 2.7.4.1
jdk 1.8.0_121
前几天公司预发环境网关突然出现不在期望内的dubbo调用。
网关是用泛化调用调实际的服务。
看了下trace
![image](https://user-images.githubusercontent.com/38656144/116644279-7f937400-a9a5-11eb-8da0-b53717602009.png)

第一行是consumer记录的exitSpan，也就是网关。
第二行是provider记录的entrySpan，也就是实际服务。
可以看到网关记录的调用的是 wdshop，但是provider这边记录的是post。
想问下泛化调用难道会出现调用某个provider，结果会调用到另一个provider的情况吗？

**Comment by web1992** [comment]
1. 理论是不会出现的，我也用泛型调用，没有遇到类型的问题。
2.可以把其中的 provider 的一个 Service  停了，再次调用，正常应该出现 `No provider xxx` 的错误。如果没有出现，则说明是调错服务了

**Comment by gentryhuang** [comment]
> dubbo 版本 2.7.4.1
> jdk 1.8.0_121
> 前几天公司预发环境网关突然出现不在期望内的dubbo调用。
> 网关是用泛化调用调实际的服务。
> 看了下trace
> ![image](https://user-images.githubusercontent.com/38656144/116644279-7f937400-a9a5-11eb-8da0-b53717602009.png)
> 
> 第一行是consumer记录的exitSpan，也就是网关。
> 第二行是provider记录的entrySpan，也就是实际服务。
> 可以看到网关记录的调用的是 wdshop，但是provider这边记录的是post。
> 想问下泛化调用难道会出现调用某个provider，结果会调用到另一个provider的情况吗？

看着截图是泛化实现，可以检查下消费端引用的服务在服务提供方暴露的具体是哪个。

**Comment by xingcici** [comment]
找到原因了，二开的时候为了解决泛化调用 URL 过多导致内存泄露问题时修改了 URL 类的 equal 方法，导致 zkRegister 中 listener 混乱，在 zk 连接抖动 refresh 的时候就会触发referenceConfig 中 invoker 被刷新成不正确的。
