### ISSUE TITLE
Dubbo zookeeper registry failed to re-subscribe

### ISSUE THREAD

**Issue by willmao** [apache/dubbo#7665]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: Ubuntu 16.04
* Java version: jdk-1.8

### Steps to reproduce this issue

1. zookeeper cluster hang because of backend storage issue(aliyun nas in our case)
2. dubbo registry received a state change of RECONNECTED event and invoke fetchLatestAddresses method, but the zookeeper server has not recovered yet, so the 3 times re-subscribe all failed and the failed retry task exist in failedSubscribed hashmap
3. zookeeper server finally recovered, dubbo registry received a state change of NEW_SESSION_CREATED event, it triggered the recover process, but the FailedSubscribedTask will not be created since there was a previous failed task, see
https://github.com/apache/dubbo/blob/6a6eb0b85c428e9def9bd36bcc5a6dd0b3a955ab/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/FailbackRegistry.java#L133-L145
4. when the provider re-deployed in k8s cluster and changed the provider ip, the consumer would broken

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

dubbo zookeeper registry re-subscribe the provider successfully after the zookeeper server recovered

### Actual Result

dubbo zookeeper registry did not trigger a fresh recover process due to a previous failed re-subscribe

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by xiaoheng1** [comment]
let me have a look
