### ISSUE TITLE
dubbo支持服务提供方的mock吗？

### ISSUE THREAD

**Issue by moayi** [apache/dubbo#7678]
dubbo支持服务提供方的mock吗？这样可以做统一的服务降级处理

**Comment by moayi** [comment]
服务提供方出现异常（即提供方可用，但是提供方接口方法内部出现异常），会定义一个降级方法，统一走回退方法。因为消费者很多，想提供统一的回退方法，有点类似于springcloud->fallbackFactory = TOSaleOrderApiFallbackFactory.class,

**Comment by xiaoheng1** [comment]
Sorry, now the service downgrade is done on the consumer side. You can use the override protocol to configure the downgrade strategy to try, so that the consumer will rewrite the url after listening.

**Comment by pinxiong** [comment]
@moayi Can this issue be close? If necessary, we can open it again.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
