### ISSUE TITLE
delayed init of the registry

### ISSUE THREAD

**Issue by wangxw666** [apache/dubbo#7703]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue
RegistryProtocol
```
public <T> Invoker<T> refer(Class<T> type, URL url) throws RpcException {
        // 取 registry 参数值，并将其设置为协议头
        url = getRegistryUrl(url);
        // 获取注册中心实例
        Registry registry = registryFactory.getRegistry(url);
        if (RegistryService.class.equals(type)) {
            return proxyFactory.getInvoker((T) registry, type, url);
        }
}
```
InterfaceCompatibleRegistryProtocol
```
@Override
    public <T> ClusterInvoker<T> getInvoker(Cluster cluster, Registry registry, Class<T> type, URL url) {
        // TODO 延迟到这里初始化注册中心
        DynamicDirectory<T> directory = new RegistryDirectory<>(type, url);
        return doCreateInvoker(directory, cluster, registry, type);
    }

@Override
    public <T> ClusterInvoker<T> getServiceDiscoveryInvoker(Cluster cluster, Registry registry, Class<T> type, URL url) {
        // 新模型
        registry = registryFactory.getRegistry(super.getRegistryUrl(url));
        DynamicDirectory<T> directory = new ServiceDiscoveryRegistryDirectory<>(type, url);
        return doCreateInvoker(directory, cluster, registry, type);
    }
```

### Expected Result

 延迟到getInvoker初始化注册中心
### Actual Result

What actually happens?

RegistryProtocol 中初始化了一次注册中心，InterfaceCompatibleRegistryProtocol升级为ServiceDiscoveryRegistry初始化了两次，只用到了ServiceDiscoveryRegistry。

**Comment by xiaoheng1** [comment]
let me have a look.

**Comment by xiaoheng1** [comment]
I think we can decide whether to use service introspection based on the value of registry-type or interface-granularity service discovery to solve this problem may be a good choice. E.g:
In the method org.apache.dubbo.registry.client.migration.MigrationRuleHandler#doMigrate, the rawRule is no longer read, but based on the URL protocol to determine which service discovery to go.

**Comment by wangxw666** [comment]
org.apache.dubbo.registry.client.migration.MigrationRuleHandler#doMigrate? can u describe it in more detail?
