### ISSUE TITLE
The issue about consumer call DefaultExecutorRepository#getExecutor method

### ISSUE THREAD

**Issue by BurningCN** [apache/dubbo#7732]
In consumer side.

// ====================================================================
**phenomenon**
1. When the client connect to the server,  `channelActive` event triggered, and method `DefaultExecutorRepository#getExecutor` is triggered .When I use `registry:// `pattern, it can fetch the executor cached by the previous consumer; but `service-discovery-registry://` pattern get null from cache(Because the `side` parameter retrieved from the URL is null), This leads to the use `SHARED_EXECUTOR`

2. When I make the RPC call, method `DefaultExecutorRepository#getExecutor` is triggered, `registry://` and  `service-discovery-registry://` can both fetch the executor cached by the previous consumer.

// ====================================================================
**conclusion**
So, when we use registry:// pattern, Both RPC calls and network events such as `channelActive` use cached executor, while the phenomenon of  `service-discovery-registry://` pattern is RPC calls use cached executor and network events use `SHARED_EXECUTOR`.

The reason for this phenomenon in `service-discovery-registry://` pattern is that, 
In `registry:// `pattern, trigger `RegistryDirectory#toInvokers  --> mergeUrl` populates the `queryMap` directly into the `URL#parameters`. So in `DefaultExecutorRepository#getExecutor`  method in either case can get to the `side` parameter values.
In 'service-discovery-registry://' pattern, trigger `ServiceDiscoveryRegistryDirectory# toInvokers - > instanceAddressURL.addConsumerParams(getConsumerUrl().getProtocolServiceKey(), queryMap)` will also populate the `queryMap` into `instanceAddressURL`, but when it is retrieved `side` parameter will call `instanceAddressURL#getParameter,` which requires `protocolServiceKey`, which is only called on RPC and trigger `InvokerInvocationHandler#invoke -> RpcContext.setRpcContext(invoker.getUrl());`  will finally get the `side` value.

// ====================================================================
**question**
Which one should be the final criterion? (in #7717 , Some changes have been made so that the `service-discovery-registry://` mode uses the cached executor for both RPC calls and network events)

// ====================================================================
**Test case**
- `registry:// ` pattern use `dubbo-demo-xml` test case  in `dubbo` project

- `service-discovery-registry:// `pattern use `dubbo-samples/dubbo-samples-cloud-native/dubbo-demo-servicediscovery-xml/ `test case in `dubbo-samples` project

**Comment by horizonzy** [comment]
The pr #7717 can solve this problem. `InstanceAddressURL` just used at consumer side.
Althought it solve the problem, but it's a little wired. To ensure this pr won't cause problem in the fusture, `InstanceAddressURL` class shouldn't use at provuder side.

**Comment by BurningCN** [comment]
> The pr #7717 can solve this problem. `InstanceAddressURL` just used at consumer side.
> Althought it solve the problem, but it's a little wired. To ensure this pr won't cause problem in the fusture, `InstanceAddressURL` class shouldn't use at provuder side.

I am grateful for your help, I will keep an eye on the problem in the future
