### ISSUE TITLE
code designer is bad

### ISSUE THREAD

**Issue by chrishyc** [apache/dubbo#7739]
dubbo 2.7.8
org.apache.dubbo.common.URLBuilder
```
public URL build() {
        if (StringUtils.isEmpty(username) && StringUtils.isNotEmpty(password)) {
            throw new IllegalArgumentException("Invalid url, password without username!");
        }
        port = port < 0 ? 0 : port;
        // trim the leading "/"
        int firstNonSlash = 0;
        if (path != null) {
            while (firstNonSlash < path.length() && path.charAt(firstNonSlash) == '/') {
                firstNonSlash++;
            }
            if (firstNonSlash >= path.length()) {
                path = "";
            } else if (firstNonSlash > 0) {
                path = path.substring(firstNonSlash);
            }
        }
        if (CollectionUtils.isEmptyMap(methodParameters)) {
            return new URL(protocol, username, password, host, port, path, parameters);
        } else {
            return new URL(protocol, username, password, host, port, path, parameters, methodParameters);
        }
    }
```
why use new URL(protocol, username, password, host, port, path, parameters, methodParameters); not use 
new URL(this);
i think it is bad code, if use builder pattern, why still use raw param to pass?

**Comment by icankeep** [comment]
maybe org.apache.dubbo.common.URL add a constructor be better
```
  public URL(URLBuilder builder) {
      ...
  }
```

But I think it's not a problem

**Comment by AlbumenJ** [comment]
According to [Single Responsibility](https://en.wikipedia.org/wiki/Single-responsibility_principle) and Object Oriented Principle, `URLBuilder` is a tool to strengthen `URL`. That is `URLBuilder` is depends on `URL`. So, it is not a good idea for `URL` to perceive or depends on `URLBuilder`. Also, `URLBuilder` is tool to create such `protocol, username, password, host, port, path, parameters, methodParameters`. I don't think it is a bad smell.

**Comment by zhongxiongzeng** [comment]
agree with @AlbumenJ

**Comment by CrazyHZM** [comment]
I haven’t received feedback for a long time, temporarily close the issues, if there is any problem, you can reopen it.
