### ISSUE TITLE
RpcInvocation adds returnType assignment in initParameterDesc

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo#7745]
movitation:

RpcInvocation adds returnType assignment in initParameterDesc.

In many scenarios, we directly pass in the serviceName and then parse the Method, but need to manually set the returnType. Now add the returnType processing in org.apache.dubbo.rpc.RpcInvocation#initParameterDesc to simplify the operation.

**Comment by BurningCN** [comment]
Can this line be deleted?

![image](https://user-images.githubusercontent.com/43363120/118070923-60e7a100-b3d9-11eb-87e5-927dcf2d3796.png)
