### ISSUE TITLE
service discovery registry has bug

### ISSUE THREAD

**Issue by wangxw666** [apache/dubbo#7755]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 27.x
* Operating System version: *
* Java version: 1.8

### Actual Result

provider 在进行服务自省注册的时候，会通过url判断是否需要注册，但是开启了简化注册中心url之后，side=provider被移除了，导致不能导出url。我觉得这里需要重新梳理

```
    protected boolean shouldRegister(URL providerURL) {

        String side = providerURL.getParameter(SIDE_KEY);

        boolean should = PROVIDER_SIDE.equals(side); // Only register the Provider.

        if (!should) {
            if (logger.isDebugEnabled()) {
                logger.debug(String.format("The URL[%s] should not be registered.", providerURL.toString()));
            }
        }

        return should;
    }
```

**Comment by wangxw666** [comment]
I think it could be like `DynamicDirectory`

```

        this.shouldRegister = !ANY_VALUE.equals(url.getServiceInterface()) && url.getParameter(REGISTER_KEY, true);
        this.shouldSimplified = url.getParameter(SIMPLIFIED_KEY, false);
```

**Comment by xiaoheng1** [comment]
let me have a look.

**Comment by xiaoheng1** [comment]
> I think it could be like `DynamicDirectory`
> 
> ```
> 
>         this.shouldRegister = !ANY_VALUE.equals(url.getServiceInterface()) && url.getParameter(REGISTER_KEY, true);
>         this.shouldSimplified = url.getParameter(SIMPLIFIED_KEY, false);
> ```

i think you are right. i will do a pr to solve it.

**Comment by xiaoheng1** [comment]
But I think it might be a good idea to add side_key to the streamlined url

**Comment by wangxw666** [comment]
ok，这里有没有必要再进行判断是值得思考的，因为服务端都需要注册，而消费端的判断逻辑是在directory 里的。可以考虑下掉这里的判断


发自我的iPhone

------------------ Original ------------------
From: xiaoheng1 ***@***.***&gt;
Date: 周四,5月 13,2021 7:40 下午
To: apache/dubbo ***@***.***&gt;
Cc: wangxw666 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] service discovery registry has bug (#7755)





  
I think it could be like DynamicDirectory
          this.shouldRegister = !ANY_VALUE.equals(url.getServiceInterface()) &amp;&amp; url.getParameter(REGISTER_KEY, true);         this.shouldSimplified = url.getParameter(SIMPLIFIED_KEY, false);   
i think you are right. i will do a pr to solve it.

**Comment by wangxw666** [comment]
这样比较简单，但是我感觉这样做是不是不符合设计的原则那？是在注册的时候保留side_key还是判断以后再移除那


发自我的iPhone

------------------ Original ------------------
From: xiaoheng1 ***@***.***&gt;
Date: 周四,5月 13,2021 7:55 下午
To: apache/dubbo ***@***.***&gt;
Cc: wangxw666 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] service discovery registry has bug (#7755)





 
But I think it might be a good idea to add side_key to the streamlined url

**Comment by xiaoheng1** [comment]
> 这样比较简单，但是我感觉这样做是不是不符合设计的原则那？是在注册的时候保留side_key还是判断以后再移除那 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: xiaoheng1 ***@***.***&gt; Date: 周四,5月 13,2021 7:55 下午 To: apache/dubbo ***@***.***&gt; Cc: wangxw666 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [apache/dubbo] service discovery registry has bug (#7755) But I think it might be a good idea to add side_key to the streamlined url — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

If we use this.shouldRegister = !ANY_VALUE.equals(url.getServiceInterface()) && url.getParameter(REGISTER_KEY, true); This judgment will cause the service to fail to subscribe in the streamlined url scenario

**Comment by xiaoheng1** [comment]
becase shouldRegister is always true by default. and shouldSubscribe always is false.

**Comment by wangxw666** [comment]
这样的话，如果使用接口级别注册，相当于注册中心又增加了冗余数据。


发自我的iPhone

------------------ Original ------------------
From: xiaoheng1 ***@***.***&gt;
Date: 周四,5月 13,2021 8:00 下午
To: apache/dubbo ***@***.***&gt;
Cc: wangxw666 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] service discovery registry has bug (#7755)





  
这样比较简单，但是我感觉这样做是不是不符合设计的原则那？是在注册的时候保留side_key还是判断以后再移除那 发自我的iPhone
 …
 ------------------ Original ------------------ From: xiaoheng1 @.&gt; Date: 周四,5月 13,2021 7:55 下午 To: apache/dubbo @.&gt; Cc: wangxw666 @.&gt;, Author @.&gt; Subject: Re: [apache/dubbo] service discovery registry has bug (#7755) But I think it might be a good idea to add side_key to the streamlined url — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
If we use this.shouldRegister = !ANY_VALUE.equals(url.getServiceInterface()) &amp;&amp; url.getParameter(REGISTER_KEY, true); This judgment will cause the service to fail to subscribe in the streamlined url scenario

**Comment by wangxw666** [comment]
shouldRegister 和shouldSubscribe对提供者和消费者是相反的行为


发自我的iPhone

------------------ Original ------------------
From: xiaoheng1 ***@***.***&gt;
Date: 周四,5月 13,2021 8:02 下午
To: apache/dubbo ***@***.***&gt;
Cc: wangxw666 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] service discovery registry has bug (#7755)





 
becase shouldRegister is always true by default. and shouldSubscribe always is false.

**Comment by xiaoheng1** [comment]
When the consumer is subscribing, the url is also streamlined, then the side information is lost, whether registration will return true, which will cause the consumer to not subscribe

**Comment by wangxw666** [comment]
ok，所以我认为不应该使用sidekey判断，保留意见 ٩(❛ัᴗ❛ั⁎)


发自我的iPhone

------------------ Original ------------------
From: xiaoheng1 ***@***.***&gt;
Date: 周四,5月 13,2021 8:09 下午
To: apache/dubbo ***@***.***&gt;
Cc: wangxw666 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] service discovery registry has bug (#7755)





 
When the consumer is subscribing, the url is also streamlined, then the side information is lost, whether registration will return true, which will cause the consumer to not subscribe

**Comment by xiaoheng1** [comment]
Well, but after simplifying the url, there is really no way to judge whether it should be registered. 
Do you have any good suggestions?

**Comment by wangxw666** [comment]
Let me think for a moment
