### ISSUE TITLE
求解：messageOnlyChannelHandler中receivd()方法异常处理增加线程池满快速应答的原理是什么？

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#7776]
### Environment

* Dubbo version: 2.7.5
* Operating System version: centos7
* Java version: 1.8

项目压测Dubbo服务提供方线程池满后，偶发服务消费方接收不到SERVER_THREADPOOL_EXHAUSTED_ERROR应答，一直等到超时的现象，项目中Dubbo服务提供方使用的派发策略是message、ThreadPool类型是fixed。
看到issue#5256中提到messageOnlyChannelHandler中receivd()方法的异常处理应增加线程池满后快速应答的代码，如果不加这段快速响应SERVER_THREADPOOL_EXHAUSTED_ERROR应答的代码，是什么原因导致服务提供方没有返回应答？不加这段代码后面的代码好像也有处理，求解释。

**Comment by xiaoheng1** [comment]
1. The server uses a fixed thread pool. When there are too many tasks, the thread pool full exception will be triggered.
Not adding this code does not mean that the server will not return data to the client, but that it requires meaningless waiting, which is equivalent to fast failure.
2. Which part of the code that you mentioned later refers to, can you take a screenshot?

**Comment by zrlw** [comment]
1. 我们压测时遇到的情况是服务线程池满了，consumer超时了也没有收到应答，超时时间设置是3秒。服务端派发策略改成All时，线程池满的时候，consumer马上就能收到失败应答，没有再白等3秒。
2.  我指的是fix #5256的代码，这段代码和All策略基本一样，加了这个就能立即返回，不加这个3秒也返回不了，为啥meaningless waiting会耗时那么久？
public class MessageOnlyChannelHandler extends WrappedChannelHandler {

@@ -39,6 +41,10 @@ public void received(Channel channel, Object message) throws RemotingException {
        try {
            executor.execute(new ChannelEventRunnable(channel, handler, ChannelState.RECEIVED, message));
        } catch (Throwable t) {
            if(message instanceof Request && t instanceof RejectedExecutionException){
                sendFeedback(channel, (Request) message, t);
                return;
            }
            throw new ExecutionException(message, channel, getClass() + " error when process received event .", t);
        }
    }

**Comment by xiaoheng1** [comment]
If this code is not added, if the timeout period set by the client is exceeded, the consumer will automatically construct a timeout response. Please check the relevant situation on the consumer side, look at the load of the machine, etc.

**Comment by zrlw** [comment]
```
    public void received(Channel channel, Object message) throws RemotingException {
        ExecutorService executor = getPreferredExecutorService(message);

        if (message instanceof Request) {
            try {
                executor.execute(new ChannelEventRunnable(channel, handler, ChannelState.RECEIVED, message));
            } catch (Throwable t) {
                // FIXME: when the thread pool is full, SERVER_THREADPOOL_EXHAUSTED_ERROR cannot return properly,
                // therefore the consumer side has to wait until gets timeout. This is a temporary solution to prevent
                // this scenario from happening, but a better solution should be considered later.
                if (t instanceof RejectedExecutionException) {
                    sendFeedback(channel, (Request) message, t);
                }
                throw new ExecutionException(message, channel, getClass() + " error when process received event.", t);
            }
        } else if (executor instanceof ThreadlessExecutor) {
            executor.execute(new ChannelEventRunnable(channel, handler, ChannelState.RECEIVED, message));
        } else {
            handler.received(channel, message);
        }
    }
```
when the thread pool is full, SERVER_THREADPOOL_EXHAUSTED_ERROR cannot return properly, therefore the consumer side has to wait until gets timeout， 我们想问的是为什么不能正常返回？为什么不加这些代码，客户端一直要等到超时？

**Comment by xiaoheng1** [comment]
When the server thread pool is full, it can no longer accept requests from the client, so the data package sent to the client cannot be constructed. Therefore, if the above code is not added, the client can only wait for the timeout and construct a timeout packet by itself.

**Comment by wangxw666** [comment]
因为原来的这里异常返回响应也是通过业务线程池返回的，但是业务线程池被打满后就没有办法处理了，所以需要在io线程直接处理。你可以参考下这篇文章 [dubbo message](https://www.iteye.com/blog/manzhizhen-2391177)。这个问题本质上还是理解IO线程和业务线程分离的思想，以及fast-fail机制.

**Comment by zrlw** [comment]
线程派发策略是all的情况下加sendFeedback()这段逻辑可以解决业务线程池满无法正确响应的问题，但线程派发策略是message或者execution情况下，线程池满的异常本来已经在io线程中执行了(HeaderExchangeHandler#caught)，还加上sendFeedback()这段逻辑仅是为了快速失败？

**Comment by zrlw** [comment]
最新版本的dubbo无论是AllChannelHandler还是MessageOnlyChannelHandler，received方法都有捕获Throwable时直接sendFeedback处理。
我们的疑问是dubbo 2.7.5只有AllChannelHandler的received方法有这个快速sendFeedback，MessageOnlyChannelHandler的received方法并没有异常快速feedback异常处理，我们当初选择MessageOnlyChannelHandler，正是看过 wangxw666 提到的https://www.iteye.com/blog/manzhizhen-2391177 这篇帖子，但是我们实际压测结果和这篇文章说的结论刚好相反，我们用dubbo 2.7.5的AllChannelHandler没有出现过客户端等到超时的情况，反而用MessageOnlyChannelHandler才会出现客户端等待超时收不到应答的情况，这篇帖子所说的AllChannelHandler存在的缺陷已经在2.7.5版本修复了，但是帖子提出选择MessageOnlyChannelHandler能够避免客户端超时的说法在我们的实测中并不是真的，我们不明白的是为什么不成立。

**Comment by xiaoheng1** [comment]
@zrlw I probably understand what you mean, let me think about it

**Comment by xiaoheng1** [comment]
@zrlw Theoretically speaking, if dubbo 2.7.5 uses the message thread pool, the consumer can fail quickly, and my local test is also ok. Can you provide your stress test demo?

**Comment by zrlw** [comment]
提供不了demo，我们压测的是准生产环境，压测目标是单个dubbo服务达到目标tps后客户端能及时收到服务端线程池耗尽的响应，发现有客户端一直等待超时的情况，并且一旦出现会持续一段时间，服务端抓包wireshark能找到这些超时无应答的dubbo请求，根据这些请求dubbo报文头部的64bit请求唯一id检索不到应答报文，netty日志设为debug级别也没有找到和这些请求相关的应答日志。

**Comment by xiaoheng1** [comment]
1. Have you reproduced this problem only in the quasi-production environment? Have the same problem occurred in the local test
2. Can you provide information on how the consumer performs stress testing? Called by generalization? Or the consumer provides the http interface, and then the http interface is tested by pressure
3. Can the relevant configuration be provided?

**Comment by zrlw** [comment]
1. 本地搞不出来我们需要达到的tps；
2. 客户端集群提供http接口，压力机经过负载均衡设施向客户端http接口发压；
3. 每台客户端4c8g，提供http的undertow容器 io线程数8、工作线程64、buffer-size1024、direct-buffer为true、max-http-post-size为100万字节；dubbo reference配置的timeout为3000毫秒，方法retries次数为0。每台服务端也是4c8g，dubbo provider配置的timeout是15000毫秒，retries次数为0，dispatcher配置message，dubbo线程池fixed、200个工作线程、40个io线程。

**Comment by wangxw666** [comment]
理论上使用MessageOnly应该是没有问题的，因为最后线程池被打满后，异常会被NettyServerHandler捕获，最终由NioEventLoop在HeaderExchangeHandler中处理。

```
  public void caught(Channel channel, Throwable exception) throws RemotingException {
        if (exception instanceof ExecutionException) {
            ExecutionException e = (ExecutionException) exception;
            Object msg = e.getRequest();
            if (msg instanceof Request) {
                Request req = (Request) msg;
                if (req.isTwoWay() && !req.isHeartbeat()) {
                    Response res = new Response(req.getId(), req.getVersion());
                    res.setStatus(Response.SERVER_ERROR);
                    res.setErrorMessage(StringUtils.toString(e));
                    channel.send(res);
                    return;
                }
            }
        }
        ExchangeChannel exchangeChannel = HeaderExchangeChannel.getOrAddChannel(channel);
        try {
            handler.caught(exchangeChannel, exception);
        } finally {
            HeaderExchangeChannel.removeChannelIfDisconnected(channel);
        }
    }
```

如果有问题，就是中间的某个链路比较耗时导致的（也有可能是NioEventLoop比较繁忙，处理不及时）。你可以把业务线程池调小一点，让他在本地出发拒绝策略。看看

**Comment by zrlw** [comment]
从wireshark分析看，无应答的请求报文接收时间到抓包结束有4分钟时间，即便NioEventLoop再繁忙，理论上4分钟也应该返回这笔 应答了，但是我们从pcap抓包文件中没有检索到和dubbo请求报文唯一id相同的dubbo应答报文，这4分钟这个客户端还在继续压测，绝大多数请求都有对应的应答报文。
本地我们做过模拟测试，将工作线程池数设置成了1，但是没有复现出来这种问题，但是这种问题在准生产压测环境下却能稳定复现。

**Comment by goodjava** [comment]
我手里没有2.7.5 的代码.我参考2.7.4的代码给出我的一些建议 @zrlw 
1.大胆的用all ,这个选择没有问题,2.7.4 版本是没有那篇文章所描述的那个问题的
2.message的还是要慎重使用,我不认为那个适用所有场景,毕竟异常的处理你放到 netty work 线程池去处理,有点怪的(唯一不怪的地方是,你业务线程池抛出了拒绝异常
<img width="1372" alt="dubbo1" src="https://user-images.githubusercontent.com/869986/119070556-cdd2ea80-ba1a-11eb-876e-5ada29e621fc.png">
<img width="1289" alt="dubbo2" src="https://user-images.githubusercontent.com/869986/119070588-e216e780-ba1a-11eb-86f7-68a58ba12078.png">
<img width="1237" alt="6" src="https://user-images.githubusercontent.com/869986/119070628-f78c1180-ba1a-11eb-87e9-2382a8585899.png">
<img width="1415" alt="3" src="https://user-images.githubusercontent.com/869986/119070796-4174f780-ba1b-11eb-88d2-436b00cc0192.png">

**Comment by zrlw** [comment]
@goodjava 多谢！

**Comment by xiaoheng1** [comment]
@zrlw in dubbo2.7.5，Why can't the client fail quickly when the server thread pool is full ? 
Because in dubbo, there is an object that is MultiMessage. When Dubbo is processing in MultiMessageHandler, assuming that there are 100 elements in MultiMessage, if the first one is added to the server thread pool and the thread pool is full, it will be caught , Go to org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#caught for processing. It will cause the remaining 99 element data to be lost, which is why in dubbo2.7.5, there will be a timeout problem .

**Comment by zrlw** [comment]
> @zrlw in dubbo2.7.5，Why can't the client fail quickly when the server thread pool is full ?
> Because in dubbo, there is an object that is MultiMessage. When Dubbo is processing in MultiMessageHandler, assuming that there are 100 elements in MultiMessage, if the first one is added to the server thread pool and the thread pool is full, it will be caught , Go to org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler#caught for processing. It will cause the remaining 99 element data to be lost, which is why in dubbo2.7.5, there will be a timeout problem .

Fabulous！
