### ISSUE TITLE
suggest duboo > 2.7.11 is support to curator 5.1.0

### ISSUE THREAD

**Issue by NickZhang1024** [apache/dubbo#7785]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: >=2.7.11
* Operating System version: all
* Java version: all

**Comment by icankeep** [comment]
Dependencies conflicts

Related issue: #7772

**Comment by CrazyHZM** [comment]
Resolved in #8264
