### ISSUE TITLE
Dubbo 2.7.5, 2.7.9, 2.7.11, 2.7.12 are incompatiable with nacos-spring-context 1.1.0

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#7797]
### Environment

* Dubbo version: 2.7.5 or 2.7.9 or 2.7.11 or 2.7.12
* Operating System version: centos7
* Java version: 1.8
* nacos-spring-context 1.1.0

### Steps to reproduce this issue
create a maven spring-boot test application which pom.xml has dubbo first and nacos-spring-context 1.1.0 later,  
with dubbo which depend on spring-context-support 1.0.10:
a ClassCastException - com.sun.proxy.$Proxy...NNN... cannot be cast to java.util.Map - will be throwed at AnnotationNacosInjectedBeanPostProcessor.java line 145.
with dubbo which depend on spring-context-support 1.0.8 or less:
An attempt was made to call a method that does not exist (com.alibaba.spring.util.BeanUtils.getBeanNames)

The reason is nacos-spring-context 1.1.0 depends  on spring-context-support 1.0.11 which isn't compliant with that dubbo depends now.

**Comment by zrlw** [comment]
if exclude spring-context-support of dubbo in pom.xml, ClassCastException - java.lang.String cannot be cast to java.lang.Class - will be throwed at DubboAnnotationUtils.java line 95.

**Comment by AlbumenJ** [comment]
I think we can remove the dependency of spring-context-support in the future.

**Comment by zrlw** [comment]
the root cause is alibaba spring-context-support 1.0.11 set default value of two new added elements classValuesAsString and nestedAnnotationsAsMap to true, which destroys dubbo ReferenceAnnotationBeanPostProcessor findFieldAnnotationMetadata and findAnnotatedMethodMetadata functions.

**Comment by zrlw** [comment]
we make dubbo 2.7.12 and nacos 1.4.2 working well with each other by #8217 :
1. change alibaba spring-context-support version of dubbo pom.xml to 1.0.11
2. set classValuesAsString and nestedAnnotationsAsMap attributes of ReferenceAnnotationBeanPostProcessor to false
@horizonzy   @AlbumenJ

**Comment by AlbumenJ** [comment]
@kylixs PTAL

**Comment by zrlw** [comment]
related issues:
#7115 
#7385

**Comment by kylixs** [comment]
@zrlw  Since dubbo 3.0.0, the `AbstractAnnotationBeanPostProcessor` of alibaba `spring-context-support` is no longer used, and this problem should not occur, please check it again. 
Furthermore, dubbo 3 will gradually remove alibaba spring-context-support.

**Comment by kylixs** [comment]
dubbo 2.7.x has merge pull request: https://github.com/apache/dubbo/pull/8217

**Comment by kylixs** [comment]
@zrlw Please add a sample for regression testing: 
https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos

**Comment by zrlw** [comment]
> @zrlw Since dubbo 3.0.0, the `AbstractAnnotationBeanPostProcessor` of alibaba `spring-context-support` is no longer used, and this problem should not occur, please check it again.
> Furthermore, dubbo 3 will gradually remove alibaba spring-context-support.

you're right，i didn't notice that dubbo 3.x had used its own AbstractAnnotationBeanPostProcessor.

**Comment by zrlw** [comment]
> @zrlw Please add a sample for regression testing:
> https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos

I  tried to run Junit Test of dubbo-samples-nacos-configcenter, only got IllegalStateException:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.dubbo.samples.configcenter.DemoServiceIT': Unsatisfied dependency expressed through field 'demoService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry />
what else should i prepared?
```
i want to change these codes in NacosUtils.java from
```
String serverAddr = System.getProperty("nacos.address", "localhost");
Properties properties = new Properties();
properties.put(PropertyKeyConst.SERVER_ADDR, serverAddr);
ConfigService configService = NacosFactory.createConfigService(properties);
```
to
```
@NacosInjected(properties = @NacosProperties(serverAddr = "${nacos.address:localhost}"))
private ConfigService configService;
```

**Comment by kylixs** [comment]
> I tried to run Junit Test of dubbo-samples-nacos-configcenter, only got IllegalStateException:
> 
> ```
> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.apache.dubbo.samples.configcenter.DemoServiceIT': Unsatisfied dependency expressed through field 'demoService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoService': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: No registry config found or it's not a valid config! The registry config is: <dubbo:registry />
> ```
> 
> what else should i prepare?


Please start nacos server first

**Comment by zrlw** [comment]
modified dubbo-samples-nacos-configcenter:  apache/dubbo-samples#352
