### ISSUE TITLE
dubbo 2.7.9 使用  redis作为注册中心，发现不了服务

### ISSUE THREAD

**Issue by lwx314781** [apache/dubbo#7800]
dubbo 2.7.9 使用redis 做注册中心 ，消费方发现不了提供方的服务，跟踪源码发现redis作为注册中心，未实现ServiceDiscovery接口，请问这个需要自己实现还是说，我哪里配置错误了

**Comment by xiaoheng1** [comment]
Redis does not support service introspection in dubbo 2.7.9. If you want to use service introspection, you can consider zk or use interface granular service introspection.
