### ISSUE TITLE
Lack of Junit test case for MetricsConfig in package org.apache.dubbo.config

### ISSUE THREAD

**Issue by hadley0828** [apache/dubbo#7808]
- [*] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [*] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.12
* Operating System version: Mac OS 10.12.1
* Java version: 1.8

### Steps to reproduce this issue

There are Junit test cases for the other subclasses of AbstractConfig like ConsumerConfig or ProviderConfig, but there are no test cases for MetricsConfig.

**Comment by wangchengming666** [comment]
I'll fix it
