### ISSUE TITLE
dubbo2.7.8使用nacos注册中心指定version不生效

### ISSUE THREAD

**Issue by leyou240** [apache/dubbo#7817]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: xxx
* Java version: 8

### Steps to reproduce this issue

1. 指定服务版本
@DubboService(
        version = "1.0.1",
        interfaceClass = RewardService.class,
        cluster = "failfast",
        loadbalance = "roundrobin"
)
2. 通过nacos ui查看版本号，依然是1.0.0
dubbo.metadata-service.urls=[ "dubbo://192.xxx.xxx.154:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=xxx-reward&bind.ip=192.xxx.1.154&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=xxx-reward&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=10164&qos.enable=false&release=2.7.8&revision=2021.1&side=provider&timestamp=1621593564014&version=**1.0.0**" ]
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
希望支持版本号，方便滚动升级
### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by plusmancn** [comment]
@leyou240  Please provide the version of nacos.

**Comment by leyou240** [comment]
> @leyou240 Please provide the version of nacos.

nacos-server-2.0.1

**Comment by xiaoheng1** [comment]
I use dubbo 2.7.8, nacos 2.0.1 but there is no such problem as you mentioned, the version number has changed. 
Can you provide a demo?

**Comment by leyou240** [comment]
新版本使用元信息替代了原来的接口信息展示。经过源码调试，发现不同版本号的服务都能正常注册与消费。
