### ISSUE TITLE
AbstractMetadataReport里的Local disk cache properties对象能否用于本地自定义metadata-report

### ISSUE THREAD

**Issue by jackjoesh** [apache/dubbo#7831]
### Environment

* Dubbo version: 2.7.10
* Operating System version: xxx
* Java version: jdk11

1 AbstractMetadataReport里的Local disk cache properties对象我看只做了保存操作，并没有读取使用的操作，这是为什么？
就是这个对象：
    // Local disk cache, where the special key value.registries records the list of metadata centers, and the others are the list of notified service providers
    final Properties properties = new Properties();

2 我能否借用这个properties去实现自己定义的metadata-report读取，因为我不想依赖zk或redis等远程服务，希望把元数据放在本地保存和读取

谢谢！

**Comment by xiaoheng1** [comment]
In this scenario, I understand that you can extend a MetadataReport implementation class.

**Comment by jackjoesh** [comment]
是的我可以继承MetadataReport，但是我想问的是final Properties properties = new Properties();这个对象我能否用来做读取查询呢？  因为我看它在AbstractMetadataReport里已经被保存了，但却没有被使用过

**Comment by xiaoheng1** [comment]
properties are used, and will be loaded in the AbstractMetadataReport constructor. see loadProperties method please.

**Comment by xiaoheng1** [comment]
If you use this for query, I think it is possible.

**Comment by xiaoheng1** [comment]
Please take a look at the getExportedURLs method, it's just that no data is read from the cache file now, it should be implemented in the future.

**Comment by jackjoesh** [comment]
thank you for help！

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
