### ISSUE TITLE
项目a，消费项目b和c, b,c项目实现的是同一接口，如何指定？

### ISSUE THREAD

**Issue by HuShao96** [apache/dubbo#7848]
项目a，消费项目b和c； b和c项目实现的是同一接口，如何指定？
本来想根据应用名称指定，但是好像没有这样的方法，ProvidedBy属性好像也没用。求解

**Comment by kongwu-** [comment]
Dubbo group 啊，group 就是专门你这个场景的

Service:
```xml
<dubbo:service group="feedback" interface="com.xxx.IndexService" />
<dubbo:service group="member" interface="com.xxx.IndexService" />
```

Reference:
```xml
<dubbo:reference id="feedbackIndexService" group="feedback" interface="com.xxx.IndexService" />
<dubbo:reference id="memberIndexService" group="member" interface="com.xxx.IndexService" />
```

https://dubbo.apache.org/zh/docs/v2.7/user/examples/service-group/

**Comment by HuShao96** [comment]
> 杜博集团，团体古人
> 
> 服务：
> 
> ```
> <dubbo:service group="feedback" interface="com.xxx.IndexService" />
> <dubbo:service group="member" interface="com.xxx.IndexService" />
> ```
> 
> 参考：
> 
> ```
> <dubbo:reference id="feedbackIndexService" group="feedback" interface="com.xxx.IndexService" />
> <dubbo:reference id="memberIndexService" group="member" interface="com.xxx.IndexService" />
> ```
> 
> https://dubbo.apache.org/zh/docs/v2.7/user/examples/service-group/

我试过分组了。。没有用。用的是2.7.8版本，nacos2.0.1；打个比方，b项目，是分组group_b;实现FlowTestService接口
c项目是分组group_c实现FlowTestService ;a打代码如下：
```
 ReferenceConfigBase<FlowTestService> ref = new ReferenceConfig<>();
        ref.setInterface(FlowTestService.class);
        ref.setGroup("group_c");
        final FlowTestService iGreeter = ref.get();//下一步，访问接口
```
但b,c还是会轮询调用。只不过b会报错而已；

**Comment by zhongxiongzeng** [comment]
一个是可以使用group, 另一个是可以使用version

**Comment by AlbumenJ** [comment]
可以指定不同的 group，consumer 侧调用的时候指定为 groupA,groupB 的形式。如果需要结果聚合可以参考 apache/dubbo-samples/dubbo-samples-merger

**Comment by HuShao96** [comment]
谢谢大家
