### ISSUE TITLE
Lack of unit tests for AvailableClusterInvoker 

### ISSUE THREAD

**Issue by hadley0828** [apache/dubbo#7882]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.12
* Operating System version: Mac OS 10.12.1
* Java version: 1.8

### Steps to reproduce this issue

There are Junit test cases for the other subclasses of AbstractClusterInvoker like ForkingClusterInvoker or FailbackClusterInvoker, but there are no test cases for AvailableClusterInvoker.

**Comment by BurningCN** [comment]
3.0 has been added by @wangchengming666
