### ISSUE TITLE
dubbo服务自省问题

### ISSUE THREAD

**Issue by chumendeshijie** [apache/dubbo#7886]
环境
spring.cloud.alibaba.version 2.2.3.RELEASE
dubbo 2.7.8
nacos 1.3.3
jdk 1.8 

有两个模块
order模块 服务提供者
admin模块 订阅了order服务

问题 在order模块实例重启的时候
admin模块根据nacos相应事件要去更新相应服务信息
此时 order模块实例在nacos服务端已经是个健康的实例
但是admin模块在更新的过程中，会拿到dubbo元数据信息与该实例进行tcp通信
在通信的过程中 admin模块日志中有概率出现如下错误
![image](https://user-images.githubusercontent.com/42691757/119801116-f887dc00-bf0f-11eb-8a55-64f0a875a818.png)
通过接口单独去调用order模块中的接口是好的

**Comment by xiaoheng1** [comment]
This may be caused by the provider's failure to gracefully stop.
Can you provide a demo to reproduce this problem?

**Comment by chumendeshijie** [comment]
我用的是idea里面的启动/停止, 我是等到nacos服务端order实例完全消失了再重新启动的order实例  明天我提供一下 代码在项目里面 需要一点时间

**Comment by chumendeshijie** [comment]
> This may be caused by the provider's failure to gracefully stop.
> Can you provide a demo to reproduce this problem?
我用的是idea里面的启动/停止, 我是等到nacos服务端order实例完全消失了再重新启动的order实例 明天我提供一下 代码在项目里面 需要一点时间

**Comment by chumendeshijie** [comment]
> reproduce

thank you!  我把dubbo.service.shutdown.wait 这个参数调大, 没有复现这个问题了, 可能是我的订单服务里需要释放的资源有点多,导致超过了dubbo优雅关闭的时间

**Comment by chumendeshijie** [comment]
> This may be caused by the provider's failure to gracefully stop.
> Can you provide a demo to reproduce this problem?
thank you! 我把dubbo.service.shutdown.wait 这个参数调大, 没有复现这个问题了, 可能是我的订单服务里需要释放的资源有点多,导致超过了dubbo优雅关闭的时间

**Comment by xiaoheng1** [comment]
> > This may be caused by the provider's failure to gracefully stop.
> > Can you provide a demo to reproduce this problem?
> > thank you! 我把dubbo.service.shutdown.wait 这个参数调大, 没有复现这个问题了, 可能是我的订单服务里需要释放的资源有点多,导致超过了dubbo优雅关闭的时间

ok, if there are no other problems, we will close this issue.

**Comment by chumendeshijie** [comment]
ok thank you!

**Comment by chumendeshijie** [comment]
> > > This may be caused by the provider's failure to gracefully stop.
> > > Can you provide a demo to reproduce this problem?
> > > thank you! 我把dubbo.service.shutdown.wait 这个参数调大, 没有复现这个问题了, 可能是我的订单服务里需要释放的资源有点多,导致超过了dubbo优雅关闭的时间
> 
> ok, if there are no other problems, we will close this issue.

ok, thank you!

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
