### ISSUE TITLE
dubbo服务自省问题

### ISSUE THREAD

**Issue by chumendeshijie** [apache/dubbo#7904]
环境
spring.cloud.alibaba.version 2.2.3.RELEASE
dubbo 2.7.8
nacos 1.3.3
jdk 1.8

有两个模块
order模块 服务提供者
admin模块 订阅了order服务

问题 在order模块实例重启的时候
admin模块根据nacos相应事件要去更新相应服务信息
此时 order模块实例在nacos服务端已经是个健康的实例
但是admin模块在更新的过程中，会拿到dubbo元数据信息与该实例进行tcp通信
在通信的过程中 admin模块日志中有概率出现如下错误
![image](https://user-images.githubusercontent.com/42691757/119799523-bb6f1a00-bf0e-11eb-9e3c-65455fc78934.png)

**Comment by justein** [comment]
admin应该读取的还是本机缓存的order的信息，可以看下Cache部分，自己实现一下缓存清理。

**Comment by CrazyHZM** [comment]
Try to solve it with the above answer, if it has not been solved, you can reopen the issues.
