### ISSUE TITLE
Consumer can not get server attachment info with using explicit-target

### ISSUE THREAD

**Issue by mr3** [apache/dubbo#7937]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.x
* Operating System version: Windows 10
* Java version: [8,)

### Steps to reproduce this issue

1. Refer to this article: [Explicit Target-Specify explicit target in dubbo](https://dubbo.apache.org/en/docs/v2.7/user/examples/explicit-target/), we use consumer directly connected to provider, but consumer can not get server attachment info  through method RpcContext.getServerContext().getAttachment(). The reason is that ConsumerContextClusterInterceptor.onMeesage will not be executed when calling directly.
```java
public void onMessage(Result appResponse, AbstractClusterInvoker<?> invoker, Invocation invocation) {
    RpcContext.getServerContext().setObjectAttachments(appResponse.getObjectAttachments());
}
```
  I checked the history of the class ConsumerContextListener and found that the method onResponse was removed in this [commit](https://github.com/apache/dubbo/commit/2dd3d1a0c25b6414316c5577928b4ba207c0b310#diff-485e8c8c5707a33d551821a70cd294230f0bfdb4d59527a0ca8fd81190b05760)
```java
static class ConsumerContextListener implements Listener {
    @Override
    public void onResponse(Result appResponse, Invoker<?> invoker, Invocation invocation) {
        RpcContext.getServerContext().setAttachments(appResponse.getAttachments());
    }
}
```

  I think we still need these codes, pls give some ideas ASAP.

  If yes, I would submit the fix commit for your guys review.

2. I have wrote a demo to reproduce the problem, [demo address](https://github.com/mr3/dubbo-samples-direct). 
- org.apache.dubbo.samples.direct.DirectServiceIT#testApiGetAttachment
- org.apache.dubbo.samples.direct.DirectServiceIT#testGenericGetAttachment

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

Consumer can get server attachment info with using explicit-target.

### Actual Result

Consumer can not get server attachment info with using explicit-target.

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
I think we should check why `ClusterInterceptor` not work when `Explicit Target`.

**Comment by mr3** [comment]
Cuz protocol is dubbo not registry when direct connect prodiver, it will not set up cluster, `ClusterInterceptor` will not be adtivated.

https://dubbo.apache.org/en/docs/v2.7/user/examples/explicit-target/#configure-with-xml

> You can configure the specified provider url at <dubbo:reference>.it will bypass the registry.

https://dubbo.apache.org/en/docs/v2.7/dev/implementation/#1-direct-connect-service

> Direct connect provider when have not Registry, the URL format which parsing by ReferenceConfig: dubbo://service-host/com.foo.FooService?version=1.0.0.

> Based on extension point adaptive mechanism, call refer() method of DubboProtocol by identifying dubbo:// protocol header of URL, and return provider reference.

**Comment by vio-lin** [comment]
mark.

**Comment by CrazyHZM** [comment]
It is recommended to use 3.0 to solve the problem in direct connection mode.
