### ISSUE TITLE
【BUG】2.7.9 Consumer无法获取到Provider的默认配置

### ISSUE THREAD

**Issue by shenyanming95** [apache/dubbo#7942]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version: macOS 10.15.7
* Java version: 1.8.0_231

### Steps to reproduce this issue

1. 准备 consumer 和 provider 各一个服务
2. provider的服务类，使用注解@DubboService(retyies=0)标注，方法睡眠2s
```java
@Component
@DubboService(retries = 0)
public class DemoImpl implements Demo {
    public int sleepNSeconds() {
        System.out.println("==========before sleep==========");
        try {
            TimeUnit.SECONDS.sleep(2);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
3. Consumer直接使用注解@DubboReference，不指定其它参数
```java
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {ConsumerApplication.class})
public class DemoIT {

    @DubboReference
    private Demo demo;

    @Test
    public void testSleep() throws InterruptedException {
        demo.sleepNSeconds();
    }
}
```

### Expected Result

consumer 调用超时后重试一次

### Actual Result

实际上consumer重试调用了3次，也就是说没有读取到 provider 默认的配置。接着我们debug了源码，发现：
在org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker#doInvoke中它会获取 Directory的consumer url
```java
@Override
  public URL getUrl() {
      return directory.getConsumerUrl();
  }
```
但是这个 consumer url，并没有合并 provider url 的配置，导致consumer url里面的参数配置都是dubbo默认的

**Comment by xiaoheng1** [comment]
Does the latest version also have this problem? I remember it seems that the new version fixes this problem.
Please upgrade the most recently released version and try.

**Comment by shenyanming95** [comment]
Hi, I see that the latest version is 2.7.11, but it has no effect

**Comment by xiaoheng1** [comment]
> Hi, I see that the latest version is 2.7.11, but it has no effect. `org.apache.dubbo.registry.integration.RegistryDirectory#getConsumerUrl` still can't get the parameters from the provider url

ok, I will check the code later to see what the reason is.

**Comment by cnjxzhao** [comment]
If the providers in the cluster expose different retries values for the same method, which one does the consumer rely on?

Because of the characteristics of Failover Cluster, we can only rely on the current consumer. Is this correct?

**Comment by xiaoheng1** [comment]
> If the providers in the cluster expose different retries values for the same method, which one does the consumer rely on?
> 
> Because of the characteristics of Failover Cluster, we can only rely on the current consumer. Is this correct?

This is also a problem.

**Comment by xiaoheng1** [comment]
@shenyanming95 In FailoverClusterInvoker, the retries are obtained before the provider is called, so the value can only be obtained from the consumer. However, if the retries are obtained based on the url of the invoker during the call, it may be because the configuration of each provider is different , The number of retries in the call is uncertain. So I agree with cnjxzhao's point of view.

**Comment by xiaoheng1** [comment]
@shenyanming95 In FailoverClusterInvoker, the retries are obtained before the provider is called, so the value can only be obtained from the consumer. However, if the retries are obtained based on the url of the invoker during the call, it may be because the configuration of each provider is different , The number of retries in the call is uncertain. So I agree with cnjxzhao's point of view.

**Comment by shenyanming95** [comment]
all right, It may be our use error

**Comment by caichy** [comment]
有解决方法吗？确实有这样的需求怎么办呢，在哪种模式下才能把Provider的配置传到Cousumer???  
@xiaoheng1 @cnjxzhao

**Comment by xiaoheng1** [comment]
@caichy Personally, it’s better for the consumer to decide the number of retries.
