### ISSUE TITLE
[Code Clean] Unify the process of nacos illegal character 

### ISSUE THREAD

**Issue by horizonzy** [apache/dubbo#7943]
https://github.com/apache/dubbo/blob/c52835a8bf0c7f88abe73e3b70dd881daa9a07f8/dubbo-configcenter/dubbo-configcenter-nacos/src/main/java/org/apache/dubbo/configcenter/support/nacos/NacosDynamicConfiguration.java#L357-L359

https://github.com/apache/dubbo/blob/c52835a8bf0c7f88abe73e3b70dd881daa9a07f8/dubbo-registry/dubbo-registry-nacos/src/main/java/org/apache/dubbo/registry/nacos/NacosNamingServiceWrapper.java#L81-L85

The illegal chracter process can be hadle in NacosNamingServiceWrapper uniformly.

**Comment by horizonzy** [comment]
Anyone wants to fix it?

**Comment by haoyann** [comment]
Please assign to me.
