### ISSUE TITLE
dubbo-spring-boot-starter依赖dubbo-spring-boot-autoconfigure版本声明出现${revision}变量导致下载包版本错误

### ISSUE THREAD

**Issue by cngdlcl** [apache/dubbo#7944]
- [Y ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ Y] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.11
* Operating System version: linux
* Java version: 8

### Steps to reproduce this issue

1. 创建一个Demo工程的POM.xml如下：
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>dubbo-demo</artifactId>
  <version>${revision}</version>

  <properties>
    <revision>1.0-SNAPSHOT</revision>
    <maven.compiler.source>8</maven.compiler.source>
    <maven.compiler.target>8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
      <version>2.7.11</version>
    </dependency>
  </dependencies>

</project> 
2. 使用Maven 命令进行构建：
mvn -Drevision=1.0-RELEASE clean install 

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

dubbo-spring-boot-autoconfigure的下载版本应该还是2.7.11版本。

### Actual Result

dubbo-spring-boot-autoconfigure的下载版本1.0-RELEASE，导致在Spring仓库无法找到对应的包，403错误。

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by icankeep** [comment]
try to use other environment variable

![image](https://user-images.githubusercontent.com/39434627/120486422-9cc5c300-c3e7-11eb-9935-17997c826276.png)

**Comment by cngdlcl** [comment]
[按这个文档指引](https://maven.apache.org/maven-ci-friendly.html)，只有${revision}, ${sha1} and/or ${changelist}可以使用，但是用其他两个变量会到IDEA打包编译问题。

**Comment by icankeep** [comment]
`${revision}` can be replaced with any version you want. 
e.g.  `1.0.0-SNAPSHOT`

and you can try to learn more about using Maven

**Comment by icankeep** [comment]
READY_TO_CLOSE

**Comment by lduffy69** [comment]
如果外部应用属于多module组织，使用mvn -Drevision全局指定版本很正常，而且是Maven CI Friendly Versions插件标准功能，dubbo-spring-boot-starter发行版应内部替换成真实版本号，不应该影响外部应用打包机制
