### ISSUE TITLE
provider重启后，由于host、port没有变化，refreshInvoker无效，HeaderExchangeClient连接错误

### ISSUE THREAD

**Issue by Holmesus** [apache/dubbo#7966]
### Environment

* Dubbo version: 2.7.6
* Operating System version: MacOS
* Java version: 1.8

### Steps to reproduce this issue

1. provider重启
2. consumer端请求provider的接口
3. 出现异常
dubbo.remoting.RemotingException: message can not send, because channel is closed

### Expected Result

同一个host、port的provider重启后，invoker能够得到刷新或者是HeaderExchangeClient能够重连，此时消费者请求成功

### Actual Result

抛出异常 dubbo.remoting.RemotingException: message can not send, because channel is closed

只能等待reconnectTimerTask重新连接

dubbo默认服务重启后ip或端口会变吗，缓存都是用host:port作为key?

org.apache.dubbo.registry.integration.RegistryDirectory#refreshInvoker执行时会用url作为key判断urlInvokerMap是否存在invoker的缓存，重启provider，url是不变的，所以每次取的都是缓存。
通过AddressListener修改url后，会调用nvokerorg.apache.dubbo.rpc.protocol.dubbo.DubboProtocol#protocolBindingRefer生成新的invoker，但是invoker内的HeaderExchangeClient是根据address缓存的，这个address也是固定的。。

**Comment by xiaoheng1** [comment]
Under normal circumstances, the ip and port will not change when dubbo restarts. Are you a container deployment?

**Comment by Holmesus** [comment]
> Under normal circumstances, the ip and port will not change when dubbo restarts. Are you a container deployment?

org.apache.dubbo.registry.integration.RegistryDirectory#toInvokers刷新

**Comment by Holmesus** [comment]
> > Under normal circumstances, the ip and port will not change when dubbo restarts. Are you a container deployment?
> 
> org.apache.dubbo.registry.integration.RegistryDirectory#toInvokers刷新

**Comment by Holmesus** [comment]
> Under normal circumstances, the ip and port will not change when dubbo restarts. Are you a container deployment?

更新了描述，问题的现象是provider重启，consumer端报错，只能等待reconnectTimerTask重连

**Comment by xiaoheng1** [comment]
> > 抛出异常 dubbo.remoting.RemotingException: message can not send, because channel is closed

this high probability feels that there is no graceful shutdown.

**Comment by Holmesus** [comment]
> > > 抛出异常 dubbo.remoting.RemotingException: message can not send, because channel is closed
> 
> this high probability feels that there is no graceful shutdown.

通过ctrl + c结束了provider进程，从日志看provider端是正常关闭了。但是consumer端的HeaderExchangeClient并没有。
org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol#checkClientCanUse的这行代码
if (referenceCountExchangeClient == null || referenceCountExchangeClient.isClosed()) {
                return false;
 }
为什么不用!referenceCountExchangeClient.isConnected()判断呢，实际上这个channel已经disconnect了，但是没有close。
现在我用AddressListener给每个consumer的url都加上了send.reconnect=true这个参数，可以解决这个问题。
有其他可以配置send.reconnect=true的地方吗，对性能因该没有损失吧？

**Comment by xiaoheng1** [comment]
1. You can try to increase the waiting time of graceful shutdown.
2. When the consumer is calling, the referenceCountExchangeClient method will only affect the method to get the client. The actual call will use org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker#isAvailable to check the availability.

**Comment by CrazyHZM** [comment]
Try to solve it with the above answer, if it has not been solved, you can reopen the issues.
