### ISSUE TITLE
Add unit test for ConsumerContextClusterInterceptor

### ISSUE THREAD

**Issue by icankeep** [apache/dubbo#7971]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

## Detail
Add unit test for ConsumerContextClusterInterceptor

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&
