### ISSUE TITLE
Incorrect behavior on providing GenericService!

### ISSUE THREAD

**Issue by JasonMing** [apache/dubbo#7983]
According to ["Generic Service"](https://dubbo.apache.org/en/docs/v2.7/user/examples/generic-service/) guide.

>  The implementation of the generic interface is mainly used when there is **_no API interface and model class on the server side_**.

![image](https://user-images.githubusercontent.com/1220848/120766058-6ce40000-c54c-11eb-8a22-a9e231614cf2.png)

I built a generic service follow the steps in the guide. But when I call the generic service from a non generic reference, the process will be failed in early phase(decode the request) , not even touch the GenericFilter.
The error will be thrown when calling `ReflectUtils.desc2classArray(desc)` at [DecodeableRpcInvocation.java:136](https://github.com/apache/dubbo/blob/dubbo-2.7.8/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java#L136), because `desc`(parameter's type) is missing in classpath of server side.

I don't known should I add addtional config to enable generic service feature, or it just a bug?

**Comment by icankeep** [comment]
Parameter types only support Map, List, String etc.

**Comment by icankeep** [comment]
For other special types, refer to this wiki: https://dubbo.apache.org/zh/docs/v2.7/user/examples/generic-reference/#%E6%9C%89%E5%85%B3%E6%B3%9B%E5%8C%96%E7%B1%BB%E5%9E%8B%E7%9A%84%E8%BF%9B%E4%B8%80%E6%AD%A5%E8%A7%A3%E9%87%8A

**Comment by icankeep** [comment]
READY_TO_CLOSE

**Comment by JasonMing** [comment]
@icankeep  Why this issue is closed?

As you described:
> Parameter types only support Map, List, String etc.
But documents are:
> when there is no API interface and model class on the server side
> 泛接口实现方式主要用于服务器端没有 API 接口及模型类元的情况

If consumer side requires sending Map/List/String (i.e., jdk types), what's the worth to implement GenericService on server side?

Just like the consumer side **using** GenericService, there is no limitation on **implementation** to server side.
Why  **implementing** server side GenericServer, there is such a limit on **using**?

**Comment by icankeep** [comment]
![image](https://user-images.githubusercontent.com/39434627/121626245-a9ad7b00-caa7-11eb-96c1-6a4cb15603bf.png)

For other special types, you need to use map to save data, refer to this wiki: https://dubbo.apache.org/zh/docs/v2.7/user/examples/generic-reference/#%E6%9C%89%E5%85%B3%E6%B3%9B%E5%8C%96%E7%B1%BB%E5%9E%8B%E7%9A%84%E8%BF%9B%E4%B8%80%E6%AD%A5%E8%A7%A3%E9%87%8A

**Comment by JasonMing** [comment]
@icankeep your are talking about **generic reference**, that is the consumer side generic.
I'm talking about the **generic service**, that is the provider side generic.

Technically, server side can decode the hessian stream to Map/List structure, this can let server side handle the unknown types.
