### ISSUE TITLE
Dos dubbo-2.6.x support adding specific parameter to the provider url in registry except regsitry spi method？

### ISSUE THREAD

**Issue by jeffchanjunwei** [apache/dubbo#8030]
### Environment

* Dubbo version:  2.6.x
* Operating System version: centos 7
* Java version: 1.8

问下是否有方式，可以支持dubbo-2.6.x版本在registry的url上动态舔加参数？目前想到通过registry spi扩展的方式，不知道是否还有其它方式呢？

**Comment by CrazyHZM** [comment]
You can modify it through the override protocol.
