### ISSUE TITLE
WARN org.apache.dubbo.common.config.ConfigurationUtils [DUBBO] You specified the config center, but there's not even one single config item in it., dubbo version: 2.7.10

### ISSUE THREAD

**Issue by NickZhang1024** [apache/dubbo#8053]
log WARN org.apache.dubbo.common.config.ConfigurationUtils [DUBBO] You specified the config center, but there's not even one single config item in it., dubbo version: 2.7.10

how to resolve ?

**Comment by CrazyHZM** [comment]
Confirm whether it is because there is no configuration item in the configuration center, this is just an alarm that there is no configuration item in the configuration center.
