### ISSUE TITLE
Dubbo 3.0 cannot find service provider in k8s

### ISSUE THREAD

**Issue by m1ngyuan** [apache/dubbo#8056]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0-snapshot
* Operating System version: linux
* Java version: jdk 8

### Steps to reproduce this issue

Did you try to deploy Dubbo 3 on k8s? I have deployed it now, but I can't consume the service. Now I provide the server log. When I read the source code, I found that I didn't look for the pod annotated with 'io. Dubbo/metadata' when the consumer started

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

No provider available for the service com.m1ngyuan.api.service.HelloService

If there is an exception, please attach the exception trace:

```
The server startup log is as follows: https://github.com/apache/dubbo/files/6652524/logs.11.txt
```

**Comment by m1ngyuan** [comment]
Any update?

**Comment by AlbumenJ** [comment]
https://github.com/apache/dubbo-samples/blob/master/dubbo-samples-kubernetes/README.md
Please try follow this

**Comment by CrazyHZM** [comment]
Try it with the latest version and follow the example above.
