### ISSUE TITLE
使用 dubbo2.7.9 版本 consumer使用注解@DubboReference报错

### ISSUE THREAD

**Issue by caofei88** [apache/dubbo#8075]
2021-06-16 19:13:13.767  WARN [dubbo-spring-cloud-consumer,,,] 19012 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [com.alibaba.nacos.client.naming.updater] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name spring-cloud
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:623) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:630) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:429) ~[dubbo-2.7.9.jar:2.7.9]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:413) ~[dubbo-2.7.9.jar:2.7.9]

**Comment by caofei88** [comment]
spring-cloud-starter-alibaba-nacos-discovery 版本2.2.5.RELEASE  
nacos-client版本 1.4.1
org.apache.dubbo版本 2.7.9

**Comment by xiaoheng1** [comment]
Hello, did you manually enable service discovery?

**Comment by caofei88** [comment]
nacos都配置了，如果我consumer不使用注解@DubboReference 能正常注册上去

**Comment by xiaoheng1** [comment]
Hello, I still don't understand too much. Can you provide a demo to reproduce this problem?

**Comment by caofei88** [comment]
> Hello, I still don't understand too much. Can you provide a demo to reproduce this problem?

demo地址git@github.com:caofei88/dubbo-spring-cloud-demo.git  ，我在test.xml.bak用的是dubbo版本2.7.8，因为看到一个issue：https://github.com/apache/dubbo/issues/6426，我想升级dubbo到2.7.9 使用一些灰度路由功能

**Comment by xiaoheng1** [comment]
> > Hello, I still don't understand too much. Can you provide a demo to reproduce this problem?
> 
> demo地址[git@github.com](mailto:git@github.com):caofei88/dubbo-spring-cloud-demo.git ，我在test.xml.bak用的是dubbo版本2.7.8，因为看到一个issue：[https://github.com/apache/dubbo/issues/6426，我想升级dubbo到2.7.9](https://github.com/apache/dubbo/issues/6426%EF%BC%8C%E6%88%91%E6%83%B3%E5%8D%87%E7%BA%A7dubbo%E5%88%B02.7.9) 使用一些灰度路由功能

Hello, I will try this demo later

**Comment by caofei88** [comment]
> > > Hello, I still don't understand too much. Can you provide a demo to reproduce this problem?
> > 
> > 
> > demo地址[git@github.com](mailto:git@github.com):caofei88/dubbo-spring-cloud-demo.git ，我在test.xml.bak用的是dubbo版本2.7.8，因为看到一个issue：[https://github.com/apache/dubbo/issues/6426，我想升级dubbo到2.7.9](https://github.com/apache/dubbo/issues/6426%EF%BC%8C%E6%88%91%E6%83%B3%E5%8D%87%E7%BA%A7dubbo%E5%88%B02.7.9) 使用一些灰度路由功能
> 
> Hello, I will try this demo later

ok  If you have any questions, please contact me

**Comment by xiaoheng1** [comment]
This problem can be solved by upgrading dubbo to 2.7.11, please try again.

**Comment by yclxiao** [comment]
这个问题如何解决的？我们目前使用2.7.9的版本，消费者启动不了。报错：No such extension org.apache.dubbo.registry.client.ServiceDiscovery by name spring-cloud
