### ISSUE TITLE
[3.0] 支持以etcd作为注册中心、配置中心、元数据中心

### ISSUE THREAD

**Issue by klzami** [apache/dubbo#8081]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.0
* Operating System version: *
* Java version: *

### Steps to reproduce this issue

打开 https://github.com/apache/dubbo/tree/3.0/dubbo-registry 可以看到，3.0尚不支持etcd。

### Expected Result

将2.7的etcd代码逻辑迁移过来，同时增加对应用级注册的支持。

**Comment by horizonzy** [comment]
I will do it recently.

**Comment by CrazyHZM** [comment]
Migrate to dubbo-spi-extension or this warehouse, you can initiate a round of discussion.

**Comment by CrazyHZM** [comment]
Has been migrated to this project：
https://github.com/apache/dubbo-spi-extensions
