### ISSUE TITLE
dubbo version:2.7.7 , Failed to notify for subscribe;j仅在多台服务器上,其中几台出现问题

### ISSUE THREAD

**Issue by springcloud-boot** [apache/dubbo#8087]
### dubbo version:2.7.7
Failed to notify for subscribe
waiting for retry, cause: null, dubbo version: 2.7.7, current host: 192.168.0.17
java.lang.NullPointerException: null
每次在项目启动的时候,多台服务器会有其中几台报错.实际上retry的时候,还是可以成功,但是想知道为什么,因为一场抛出的是Null

**Comment by springcloud-boot** [comment]
ExporterChangeableWrapper<T> exporter = (ExporterChangeableWrapper<T>) bounds.get(key);
        URL registeredUrl = exporter.getRegisterUrl();
这里发现. 这个 registeredUrl  最终得到的为null;导致concurrentMap.get时出现空指针异常

**Comment by xiaoheng1** [comment]
can you provider a demo to reproduce this problem?

**Comment by CrazyHZM** [comment]
If you haven’t waited for feedback for a long time, please close the issue temporarily. If the issue still exists, you can reopen the issue.
