### ISSUE TITLE
注解方式 merger 不起作用

### ISSUE THREAD

**Issue by frlzk** [apache/dubbo#8088]
### Environment

* Dubbo version: 2.7.11
* Operating System version: Ubuntu 20
* Java version: 1.8

### Steps to reproduce this issue

1. 注解服务
   @DubboReference(methods= {@Method(name="hellos",merger=".addAll")},cluster="mergeable")
   HelloService` service;
2. org.apache.dubbo.rpc.cluster.support.MergeableClusterInvoker 方法　doInvoke　中无法获取merger值
  String merger = getUrl().getMethodParameter(invocation.getMethodName(), MERGER_KEY); 
3. System.out.println(getUrl().toFullString())　的输出是
    dubbo://192.168.31.160/org.example.api.HelloService?application=consumer&check=false&cluster=mergeable&dubbo=2.0.2&hellos.merger=.addAll&hellos.return=true&init=false&interface=org.example.api.HelloService&metadata-type=remote&methods=hellos,hello&pid=7855&qos.enable=false&register.ip=192.168.31.160&release=2.7.11&side=consumer&sticky=false&timestamp=1623929890380
4. 单独创建测试代码可以获取到值的
    URL url=URL.valueOf("dubbo://10.2.78.152/org.example.api.HelloService?application=consumer&check=false&cluster=mergeable&dubbo=2.0.2&hellos.merger=.addAll&hellos.return=true&init=false&interface=org.example.api.HelloService&metadata-type=remote&methods=hellos,hello&pid=11430&qos.enable=false&register.ip=10.2.78.152&release=2.7.11&side=consumer&sticky=false&timestamp=1623919516689");
String merger = url.getMethodParameter("hellos", MERGER_KEY);

**Comment by xiaoheng1** [comment]
can you provider a demo to reproduce this problem?

**Comment by CrazyHZM** [comment]
If you haven’t waited for feedback for a long time, please close the issue temporarily. If the issue still exists, you can reopen the issue.
@frlzk
