### ISSUE TITLE
schema dubbo.xsd 不支持 tag标签属性 

### ISSUE THREAD

**Issue by ldkjdk** [apache/dubbo#8094]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: all

### Steps to reproduce this issue

1. 在线文档 https://dubbo.apache.org/schema/dubbo/dubbo.xsd 不支持tag 标签属性
 
![image](https://user-images.githubusercontent.com/12707336/122521540-85254600-d047-11eb-8c3f-eff721bcd951.png)

希望dubbo.jar 本地包含的dubbo.xsd 和 在线提供的schema 内容一致，保持行为规范一致性，避免出现 Caused by: org.xml.sax.SAXParseException; lineNumber: 33; columnNumber: 127; cvc-complex-type.3.2.2: 元素 'dubbo:reference' 中不允许出现属性 'tag'。

**Comment by AlbumenJ** [comment]
@kylixs PTAL

**Comment by kylixs** [comment]
I tested the tag attribute of `dubbo:reference `on the master and the 3.0 branch, and both of them loaded successfully. **Please provide a test case to reproduce the problem.**  
In addition, please check the `xmlns` and the `schemaLocation` in the xml file header  for the dubbo url address.

```xml
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.3.xsd
    http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd
    ">

    <!-- current application configuration -->
    <dubbo:application name="demo-consumer"/>

    <!-- service configuration -->
    <dubbo:reference id="demoService" interface="org.apache.dubbo.config.spring.api.DemoService"
                     url="dubbo://127.0.0.1:20813" init="true" scope="remote" tag="demo"/>

</beans>
```

**Comment by ldkjdk** [comment]
test case
dubbo version: 2.7x
1. open dubbo-demo-xml-consumer project with eclipse  .
2. add tag for consumer.xml  , can see a  validation error in eclipse, and error  prompt content is "cvc-complex-type.3.2.2: Attribute 'tag' is not allowed to appear in element 'dubbo:reference'".
![image](https://user-images.githubusercontent.com/12707336/124252975-20471100-db5a-11eb-9d92-0dad35602f25.png)

![image](https://user-images.githubusercontent.com/12707336/124252594-b2024e80-db59-11eb-8b6e-7114aafb9663.png)

3. delete dubbo.xsd file from local dubbo.jar
4. start consumer app 
![image](https://user-images.githubusercontent.com/12707336/124253448-9cd9ef80-db5a-11eb-8e2b-6bbd6c149a08.png)

**Comment by ldkjdk** [comment]
have no found  element "tag " in  https://dubbo.apache.org/schema/dubbo/dubbo.xsd 


![image](https://user-images.githubusercontent.com/12707336/124255945-5043e380-db5d-11eb-9586-3ef59d2f59b7.png)

**Comment by AlbumenJ** [comment]
> have no found element "tag " in https://dubbo.apache.org/schema/dubbo/dubbo.xsd
> 
> ![image](https://user-images.githubusercontent.com/12707336/124255945-5043e380-db5d-11eb-9586-3ef59d2f59b7.png)

Updated in https://github.com/apache/dubbo-website/pull/857

**Comment by CrazyHZM** [comment]
This issue should have been resolved, please close this issue for now.
