### ISSUE TITLE
DubboBootstrap 的 ready/startup 默认值为什么是 true?

### ISSUE THREAD

**Issue by abel533** [apache/dubbo#8099]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8+
* Operating System version:  Windows10
* Java version: Jdk11

### Code

最近在解决 spring cloud alibaba 和 nacos 的问题。

实现了一个和 https://github.com/alibaba/spring-cloud-alibaba/issues/1805 不一样的方案，在 nacos 注册时先判断 `DubboBootstrap.isReady()`，只有等 `ready` 后才去注册服务。

现在看了源码发现一个是字段名和方法都改了。。另一个就是默认值还是 `true`。

https://github.com/apache/dubbo/blob/2bca144bfb4312f3e414c5551c233c4f93645fe6/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/bootstrap/DubboBootstrap.java#L172

### 问题

1. 从改动来看这个类是不是不希望在 dubbo 第三方扩展中使用？（接口改动随意）
2. 这个默认值为什么不设置为 `false`？（这样在使用的时候可以直接判断是否已经启动）

**Comment by abel533** [comment]
目前使用的 2.7.8 版本，如果能升级到 2.7.9，就能直接使用下面事件更方便的解决。
https://github.com/apache/dubbo/blob/2bca144bfb4312f3e414c5551c233c4f93645fe6/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/context/event/DubboBootstrapStatedEvent.java#L31

**Comment by AlbumenJ** [comment]
默认 true 是为了兼容 API 方式使用，直接使用 API 方式的不会触发 DubboBootstrap 初始化。
