### ISSUE TITLE
InternalThread  memory was never freed

### ISSUE THREAD

**Issue by gentryhuang** [apache/dubbo#8102]
### Environment

* Dubbo version: 2.7.7
* Java version: 1.8

###   issue
![20210620103512](https://user-images.githubusercontent.com/26839782/122660536-e28ad580-d1b4-11eb-91d2-1f77aa0a03e1.jpg)

### instructions
I found that related issues have been discussed in [Memory leak due to hessian2、FutureContext、RpcContext #7770](https://github.com/apache/dubbo/issues/7770)， I would like to confirm in which version this problem has been fixed. Or is it not a bug?

**Comment by AlbumenJ** [comment]
This is not a bug. InternalThread should cache Hessian2Input for the whole time, and save resources in creation.

**Comment by gentryhuang** [comment]
ok,thanks!
