### ISSUE TITLE
use dubbo 3.0.0 show me address already in use  but use 2.7.8 is success

### ISSUE THREAD

**Issue by dnlixiaoxin** [apache/dubbo#8117]
* Dubbo version: 3.0.0
* Operating System version: mac
* Java version: 1.8

in use 3.0.0
![image](https://user-images.githubusercontent.com/32609939/122923671-8207be00-d397-11eb-8630-60b36d869cf5.png)

**Comment by CrazyHZM** [comment]
When starting with 3.0.0, check which process is the local listening port 20880.

**Comment by dnlixiaoxin** [comment]
Thanks for ur reply, I check the 20880 port is not in use, but dubbo show me in use




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 晚上8:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] use dubbo 3.0.0 show me address already in use  but use 2.7.8 is success (#8117)





 
When starting with 3.0.0, check which process is the local listening port 20880.

**Comment by xiaohuige99** [comment]
Has it been solved

**Comment by xiaohuige99** [comment]
In the case of multiple network cards
You can try the configuration 
dubbo:
  protocol:
    name: dubbo
    port: -1
    host: 10.8.0.6 # 多网卡启动时设置IP

**Comment by YeautyYE** [comment]
+1

**Comment by CrazyHZM** [comment]
@dnlixiaoxin 
Try it with the latest version to see if the problem still exists.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
