### ISSUE TITLE
Dubbo2.7.12 TagRouter能否让tag标签在一次远程调用后继续传递

### ISSUE THREAD

**Issue by ericren** [apache/dubbo#8121]
### Environment

* Dubbo version: 2.7.12
* Operating System version: windows10
* Java version: 1.8

### Steps to reproduce this issue
1. 准备 consumer 和 provider 各一个服务，consumer 为A应用，provider 为B应用。
2. 应用A有方法 test  应用B有两个方法 b1、b2
3.  A应用的test()方法中，远程调用B应用的b1和b2方法，调用B.b1()前设置tag路由标签

测试代码如下：
```
 public void test() {
      RpcContext.getContext().setAttachment(CommonConstants.TAG_KEY,"tag1");
      B.b1();
      B.b2();
 }
```
### Expected Result
 使用dubbo2.7.12的TagRouter，在程序中多次串行的远程调用后，还能进行tag标签传递，
 比如：调用B.b1()后，能把tag标签继续传递下去，使得B.b2()执行时，也能拿到tag标签，使得TagRouter可以按照tag去路由指定的节点。

### Actual Result
远程调用B.b1()时，通过debug，发现RpcContext.getContext().getAttachment(CommonConstants.TAG_KEY) 能正常拿到tag1的标签，但当B.b2()的时候，RpcContext.getContext().getAttachment(CommonConstants.TAG_KEY)就为null了

目前的尝试：当第一次调用时，把tag存起来（使用ThreadLocal等），当第二次远程调用b2方法的时候，使用自定义Filter，把tag标签再set到Attachment里。但是尝试中发现，目前的dubbo版本中，Router在Filter前先执行了，所以即使自定义Filter，也没法在以在Router执行前塞入tag。导致无法正确路由。

### Help
**除了自定义一个TagRouter外，是否有个方案，可以把当前tag标签在Router执行前塞到Attachment里**

如果可以，是否能在2.7.13的版本里能作为一个enhancement，支持这样的策略。

**Comment by 24kpure** [comment]
Tag route has two implements, flow tag and  service tag.
Sticking tag in sevice slove this problem ，for example， add vm params -Ddubbo.tag=yourTag.

**Comment by CrazyHZM** [comment]
Try to use the above answer to solve the problem, temporarily close it, if there are other problems, you can reopen the issue.
@ericren

**Comment by JayeShen** [comment]
正如你说的：Router在Filter前先执行了，所以即使自定义Filter，也没法在以在Router执行前塞入tag。导致无法正确路由。
所以你可以扩展一个cluster，在这个阶段讲tag塞入，或者扩展一个其他的阶段，我目前是这样实现的。

**Comment by AlbumenJ** [comment]
> 正如你说的：Router在Filter前先执行了，所以即使自定义Filter，也没法在以在Router执行前塞入tag。导致无法正确路由。 所以你可以扩展一个cluster，在这个阶段讲tag塞入，或者扩展一个其他的阶段，我目前是这样实现的。

Dubbo 3.0 中可以使用 ClusterFilter
