### ISSUE TITLE
Fix the problem that in the Triple protocol, an error will be reported immediately when the service is exposed

### ISSUE THREAD

**Issue by xiaoheng1** [apache/dubbo#8124]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0
* Operating System version: macos
* Java version: 1.8

When using the Triple protocol, calling the refer method will generate a connection instance. But connection#isAvailable takes effect when channelActive is called back. But actually in the ConnectionListener, if the future is successful, the channel is already available. So I think it should be in the org.apache.dubbo.remoting.api.Connection.ConnectionListener#operationComplete method, for example:

```
public void operationComplete(ChannelFuture future) {
            if (future.isSuccess()) {
                onConnected(future.channel());
                return;
            }
          .......
}
```

**Comment by guohao** [comment]
For HTTP/2, a connection is availabel only after settings have been handled , so `opertaionComplete` is not a sufficient condition for `connectionActive`.

**Comment by xiaoheng1** [comment]
If this is the case, then I suggest blocking in TripleInvoker until the connection is available. Because the call of channelActive and org.apache.dubbo.rpc.protocol.tri.TripleInvoker#doInvoke are not in the same thread, if the service is immediately exposed and then referenced, a connection error will be reported.

**Comment by xiaoheng1** [comment]
such as:

```
public void connectSync() {
        this.initPromise.awaitUninterruptibly(this.connectTimeout);
        long start = System.currentTimeMillis();
        while (!isAvailable()) {
            if(System.currentTimeMillis() - start <= connectTimeout) {
                Thread.yield();
            }
        }
    }
```

**Comment by guohao** [comment]
> such as:
> 
> ```
> public void connectSync() {
>         this.initPromise.awaitUninterruptibly(this.connectTimeout);
>         long start = System.currentTimeMillis();
>         while (!isAvailable()) {
>             if(System.currentTimeMillis() - start <= connectTimeout) {
>                 Thread.yield();
>             }
>         }
>     }
> ```

All threads will wait as long as `connecTimeout` when the downstream service is unavailable.

A passthrough `Promise` will be better in some negotiation scenarios such as H/2, ,the `Connection` will be available  when the promise  has been done  @xiaoheng1

**Comment by xiaoheng1** [comment]
But if we only use initPromise to determine whether the connection is completed, there will be a Connect to %s failed error with a high probability. Because the thread where connection.onConnected is called and org.apache.dubbo.rpc.protocol.tri.TripleInvoker #doInvoke is not in the same thread. So my initial idea is to block the connectTimeout time to ensure that the connection must be available or unavailable.

**Comment by xiaoheng1** [comment]
The following test case can reproduce this problem：

```
public class TripleProtocolTest {
    private Protocol protocol = ExtensionLoader.getExtensionLoader(Protocol.class).getAdaptiveExtension();
    private ProxyFactory proxy = ExtensionLoader.getExtensionLoader(ProxyFactory.class).getAdaptiveExtension();

    @Test
    public void testDemoProtocol() throws Exception {
        IGreeter serviceImpl = new IGreeterImpl();

        int availablePort = NetUtils.getAvailablePort();

        URL url = URL.valueOf("tri://127.0.0.1:" + availablePort + "/" + IGreeter.class.getName());

        ServiceDescriptor serviceDescriptor = ApplicationModel.getServiceRepository().registerService(IGreeter.class);
        ApplicationModel.getServiceRepository().registerProvider(
            url.getServiceKey(),
            serviceImpl,
            serviceDescriptor,
            null,
            new ServiceMetadata()
        );

        protocol.export(proxy.getInvoker(serviceImpl, IGreeter.class, url));
        serviceImpl = proxy.getProxy(protocol.refer(IGreeter.class, url));
        Assertions.assertEquals("hello world", serviceImpl.echo("hello world"));

        // resource recycle.
        ApplicationModel.getServiceRepository().destroy();
    }
}
```

**Comment by guohao** [comment]
> But if we only use initPromise to determine whether the connection is completed, there will be a Connect to %s failed error with a high probability. Because the thread where connection.onConnected is called and org.apache.dubbo.rpc.protocol.tri.TripleInvoker #doInvoke is not in the same thread. So my initial idea is to block the connectTimeout time to ensure that the connection must be available or unavailable.

That is why `A passthrough Promise` is needed, set the Connection when is available and block the `connectSync` method.
