### ISSUE TITLE
dubbo2.7.8 之后没有监听spring的ContextClosedEvent 事件了？

### ISSUE THREAD

**Issue by thedownup** [apache/dubbo#8133]

**Comment by thedownup** [comment]
springboot 关闭后 dubbo的executorService 没有关闭

**Comment by xiaoheng1** [comment]
can you provider a demo to reproduce this problem ? 
In my impression, ContextClosedEvent is used.

**Comment by thedownup** [comment]
> can you provider a demo to reproduce this problem ?
> In my impression, ContextClosedEvent is used.

AwaitingNonWebApplicationListener.java
 protected void onApplicationReadyEvent(ApplicationReadyEvent event) {

        final ConfigurableApplicationContext applicationContext = event.getApplicationContext();

        if (!isRootApplicationContext(applicationContext) || isWebApplication(applicationContext)) {
            return;
        }

        if (applicationContextId.compareAndSet(UNDEFINED_ID, applicationContext.hashCode())) {
            await();
            releaseOnExit();
        }
    }

  好像引入 devtools 时候 这个isWebApplication方法 会返回false 实际上是web环境 就导致执行了 await()  开启了线程 但是没有监听springboot的关闭事件 没关掉release()  项目报错后进程会一直在 2.7.8之前 这个类有onContextClosedEvent 没问题

**Comment by candyaaa** [comment]
@i will solve it@

**Comment by candyaaa** [comment]
org.apache.dubbo.config.spring.context.DubboDeployApplicationListener
```java
@Override
public void onApplicationEvent(ApplicationContextEvent event) {
    if (event instanceof ContextRefreshedEvent) {
        onContextRefreshedEvent((ContextRefreshedEvent) event);
    } else if (event instanceof ContextClosedEvent) {
        onContextClosedEvent((ContextClosedEvent) event);
    }
}
```
调用了release()
