### ISSUE TITLE
dubbo MetricsFilter 获取不到线程池统计数据

### ISSUE THREAD

**Issue by welcc** [apache/dubbo#8140]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version: mac os
* Java version: 1.8.0_281

### Steps to reproduce this issue

1. 部署新版dubo-admin
2. 在dubbo provider开启metric filter 
dubbo:  
  provider:
    filter: metrics
  metrics:
    protocol: dubbo
    port: 20880
3. 在dubbo-admin服务统计能够获取服务调用统计数据，但是获取不到线程池统计数据

问题原因排查：
 1.查看dubbo源码(org.apache.dubbo.monitor.dubbo.MetricsFilter)发现获取线程池统计数据实现过程是这样的，从DataStore中获取线程池，然后获取线程池数据：
 private List<MetricObject> getThreadPoolMessage() {
        DataStore dataStore = ExtensionLoader.getExtensionLoader(DataStore.class).getDefaultExtension();
        Map<String, Object> executors = dataStore.get(EXECUTOR_SERVICE_COMPONENT_KEY);
    ...
}
 2.但是在 https://github.com/apache/dubbo/commit/2484877189c89e12c0ff67504838b702153aa016#diff-45baf3c442a606b31ed84241935cf0cbc571a532cad96bf9b27b4365fb1f0db6 
（Reduce context switching cost by optimizing thread model on consumer …）这次commit中去掉了将创建的线程池放入DataStore中的代码：
![image](https://user-images.githubusercontent.com/26807957/123364607-522f0500-d5a7-11eb-97da-4fca5c1b21f9.png)

![image](https://user-images.githubusercontent.com/26807957/123365331-ab4b6880-d5a8-11eb-84f6-2cf245d3bd03.png)

 3.改为用org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository存储线程池：
![image](https://user-images.githubusercontent.com/26807957/123364748-94f0dd00-d5a7-11eb-9d04-b0671a83045d.png)

这样导致MetricsFilter中获取线程池监控数据的逻辑失效。

 4.并且DefaultExecutorRepository中存储线程池的容器为private，没有提供外部获取方式，只能通过getExecutor(URL url) 获取
![image](https://user-images.githubusercontent.com/26807957/123364854-bc47aa00-d5a7-11eb-8de7-e6b6972c0684.png)
但是这个根据url获取线程池的方式在MetricsFilter无法使用

**Comment by ilaotan** [comment]
这货都开始标识过期了,也没写替代的类,哎

**Comment by chickenlj** [comment]
Observability under construction in 3.1.x version, progresses will be updated there.
