### ISSUE TITLE
GenericService 泛化调用抛出的异常类是com.alibaba.dubbo.rpc.service.GenericException

### ISSUE THREAD

**Issue by panyox** [apache/dubbo#8143]
不应该是org.apache.dubbo.rpc.service.GenericException吗？

dubbo 版本
```xml
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo</artifactId>
    <version>2.7.12</version>
</dependency>
```

**Comment by xiaoheng1** [comment]
Now there are two GenericServices in dubbo, one is compatible with 2.6.x and throws com.alibaba.dubbo.rpc.service.GenericService, and the other is 2.7.x, throws org.apache.dubbo. rpc.service.GenericException

**Comment by xiaoheng1** [comment]
If com.alibaba.dubbo.rpc.service.GenericException is thrown, please provide an example
