### ISSUE TITLE
`ThreadlessExecutor.waitAndDrain()`方法中的`queue.take()`语句如果抛出异常会导致后续级联拿不到正常结果吗？

### ISSUE THREAD

**Issue by dslztx** [apache/dubbo#8171]
消费者在请求Dubbo服务的过程中，可能出现以下情形吗？

1. 第一次请求调用，`ThreadlessExecutor.waitAndDrain()`方法中的`queue.take()`抛出异常，该次请求不能拿到结果
1. 第二次请求时，设置第一次请求结果的任务被放入queue中，然后该次请求的结果仍然没有拿到
1. 第三次请求时，设置第二次请求结果的任务被放入queue中，然后该次请求的结果仍然没有拿到
1. 以此类推

我主要是不太清楚ThreadlessExecutor类实例和其中BlockingQueue<Runnable> queue实例在多次请求之间的共享形式，还是每次请求独享的？

请大拿解惑，谢谢！

**Comment by jiangxch** [comment]
![image](https://user-images.githubusercontent.com/61080164/123804758-11751a00-d920-11eb-9651-884448297a12.png)
![image](https://user-images.githubusercontent.com/61080164/123804867-2c478e80-d920-11eb-8437-ddeddf08ec6a.png)
![image](https://user-images.githubusercontent.com/61080164/123804991-497c5d00-d920-11eb-88d8-f65146061766.png)

**Comment by dslztx** [comment]
明白了，谢谢！ @jiangxch
