### ISSUE TITLE
Are some properties of DubboService useless？

### ISSUE THREAD

**Issue by 24kpure** [apache/dubbo#8185]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.9
* Operating System version:  macos 10.14.6
* Java version: oracle 1.8.0_211

### Steps to reproduce this issue

1.Adding config with cluster = failfast to provider Api.
2.None extra operation in consumer.
3.Failover works which ignore provider config.

### Expected Result
It seems that cluster cannot be changed after merge provider properties.I know little of the design of  this part, Removing cluster config in DubboService which doesn't work maybe a choice so that developer make less mistakes in this case.By the way,retries in provider  doesn't work  which is overridden by consumer' default value.Could you give me some advice if the problem does exist?

**Comment by 24kpure** [comment]
I’m desiring for answer，thanks for your help.

**Comment by AlbumenJ** [comment]
Cluster is not a proper property in provider side, and it will not override consumer's operation.

**Comment by 24kpure** [comment]
> Cluster is not a proper property in provider side, and it will not override consumer's operation.

How about removing cluster properties in  annotation DubboService&Service ?

**Comment by 24kpure** [comment]
I have to close this issue  for none suitable answer.
