### ISSUE TITLE
One NPE in ConfigValidationUtils.java

### ISSUE THREAD

**Issue by containerAnalyzer** [apache/dubbo#8197]
Hello,
Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.
This issue has a similar bug trace as the one in #8194 

1. Return **null** to caller 
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java#L69

2. Function **parseURL** executes and returns
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java#L174

3. Function **add** executes and **registries** can contains **null** value
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java#L174

4. Program reaches the return point, and **registries** is the return value, which contains **null** value
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-common/src/main/java/org/apache/dubbo/common/utils/UrlUtils.java#L176

5. Function **parseURLs** executes and returns
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java#L206

6. Function **next** executes and returns **null** value
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java#L208

7. The return value of function **next** is passed as the this pointer to function **getProtocol** (the return value of function **next** can be **null**), which will leak to null pointer dereference
https://github.com/apache/dubbo/blob/f26ba91b67f642148a10d3b197502e29928b77bf/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java#L211

Commit: f26ba91b67f642148a10d3b197502e29928b77bf

ContainerAnalyzer

**Comment by horizonzy** [comment]
I will fix it.

**Comment by fangliji** [comment]
I will fix it

**Comment by chickenlj** [comment]
Is there any progresss on this issue? @fangliji

**Comment by horizonzy** [comment]
it fixed by #8208
