### ISSUE TITLE
重复注册 DubboBootstrapApplicationListener

### ISSUE THREAD

**Issue by liyong1028826685** [apache/dubbo#8201]
### Environment

* Dubbo version: 2.7.8
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. 在应用启动过程中使用@DubboComponentScan注解
2. @DubboComponentScan注解中@Import(DubboComponentScanRegistrar.class)
3. org.apache.dubbo.config.spring.context.annotation.DubboComponentScanRegistrar#registerBeanDefinitions注册BeanDefinition
4. 在org.apache.dubbo.config.spring.context.annotation.DubboComponentScanRegistrar#registerServiceAnnotationBeanPostProcessor中注册DubboBootstrapApplicationListener
5. 紧接着在org.apache.dubbo.config.spring.util.DubboBeanUtils#registerCommonBeans中也注册了DubboBootstrapApplicationListener

### Expected Result

这里应该只去注册一次 DubboBootstrapApplicationListener

### Actual Result

注册了两次

**Comment by horizonzy** [comment]
Hi, for xml config and annotation config, we need both config to invoke it.

**Comment by kylixs** [comment]
Calling DubboBeanUtils#registerCommonBeans() multiple times will not register beans repeatedly, and do nothing if it has already been registered.
```java
    static boolean registerInfrastructureBean(BeanDefinitionRegistry beanDefinitionRegistry,
                                                     String beanName,
                                                     Class<?> beanType) {

        boolean registered = false;

        if (!beanDefinitionRegistry.containsBeanDefinition(beanName)) {
            RootBeanDefinition beanDefinition = new RootBeanDefinition(beanType);
            beanDefinition.setRole(BeanDefinition.ROLE_INFRASTRUCTURE);
            beanDefinitionRegistry.registerBeanDefinition(beanName, beanDefinition);
            registered = true;

            if (log.isDebugEnabled()) {
                log.debug("The Infrastructure bean definition [" + beanDefinition
                        + "with name [" + beanName + "] has been registered.");
            }
        }

        return registered;
    }
```

**Comment by CrazyHZM** [comment]
There should be nothing wrong with the reply, please close the issue temporarily, and reopen the issue if there are other issues.
