### ISSUE TITLE
不使用CompletableFuture#get()

### ISSUE THREAD

**Issue by jimgreat** [apache/dubbo#8202]
### Environment

* Dubbo version: 3.0

AbstractInvoker中有注释 
         /*
             * NOTICE!
             * must call {@link java.util.concurrent.CompletableFuture#get(long, TimeUnit)} because
             * {@link java.util.concurrent.CompletableFuture#get()} was proved to have serious performance drop.
             */
要使用get(long, TimeUnit)

MergeableClusterInvoker中的
Result r = asyncResult.get()
也要改一下吧

**Comment by horizonzy** [comment]
Sure, can you pull request to fix it?

**Comment by MentosL** [comment]
> Sure, can you pull request to fix it?

I can fix it and have submitted PR

**Comment by horizonzy** [comment]
fix by #8223
