### ISSUE TITLE
same issue 2.7.8?

### ISSUE THREAD

**Issue by helong2048** [apache/dubbo#8203]
?

_Originally posted by @yanchunhuo in https://github.com/apache/dubbo/issues/6509#issuecomment-663980841_

**Comment by kevinw66** [comment]
本地无法复现，能否提供一个demo呢？
或者试试给package-private的class加上public修饰符看看是否可以？

**Comment by CrazyHZM** [comment]
@helong2048 
Are you still paying attention to the issue?

**Comment by CrazyHZM** [comment]
If you don’t get feedback for a long time, please close the issues temporarily. If there are any problems, you can open the issues at any time.
