### ISSUE TITLE
Dubbo3.0 Metadata 泄漏

### ISSUE THREAD

**Issue by spilledyear** [apache/dubbo#8249]
每次应用重启，都会在 /dubbo/metadata/${appName} 下生成一个版本号。经过调试，发现在每次计算 revison， 会连同  pid 和 timestamp 一起计算。这样是不是有问题呢？

![image](https://user-images.githubusercontent.com/24663965/125059185-a1178700-e0dd-11eb-8271-0243d59d30b6.png)

**Comment by AlbumenJ** [comment]
I will fix it in the next release
