### ISSUE TITLE
最新版dubbo monitor

### ISSUE THREAD

**Issue by gaohuanjie** [apache/dubbo#8254]
最新版dubbo monitor在哪儿下载，如何打包运行，有文档吗？

**Comment by AlbumenJ** [comment]
Please check https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-monitor

**Comment by gaohuanjie** [comment]
> 
> 
> Please check https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-monitor

如何打包使用？
