### ISSUE TITLE
dubbo.registry.check为false无效

### ISSUE THREAD

**Issue by gaohuanjie** [apache/dubbo#8255]
环境：JDK 14、ZooKeeper 3.6.3、Dubbo 3.0.0
问题：Spring boot项目中提供者或消费者配置配置dubbo.registry.check=false后，关闭ZooKeeper，启动服务，发现服务依然无法启动，这个dubbo官网描述不一致
代码：
[consumer.zip](https://github.com/apache/dubbo/files/6794698/consumer.zip)

**Comment by zrlw** [comment]
Whether to check if register center is available when boot up: dubbo.registry.check
Check if service provider exists, if not exists, it will be fast fail: dubbo.consumer.check

**Comment by CrazyHZM** [comment]
In the latest version, this problem has been resolved.
