### ISSUE TITLE
dubbo 2.7.3 mulitple regestries error， consumer defined in xml，registries in property

### ISSUE THREAD

**Issue by zziawan** [apache/dubbo#8279]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: linux
* Java version: jdk8

### Steps to reproduce this issue

1. create a spring boot dubbo project, use xml to define consumer bean, set zookeeper address in bootstrap.property. use single regestry is ok,but when use mulitple regestries, the project error when starting . but if there is only provider in xml, it can start.
2. error is:
[dubboerror.txt](https://github.com/apache/dubbo/files/6805451/dubboerror.txt)

3.registry config
dubbo:
  application:
    name: applicationname
  service:
    group: group
  protocol:
    name: dubbo
    port: -1
  registries:
    a1: 
      register: true
      address: zookeeper://10.125.31.185:32545
    a2: 
      register: true
      address: zookeeper://10.125.31.185:30195
  metadata-report:
    a1:
     address: zookeeper://10.125.31.185:32545
    a2: 
     address: zookeeper://10.125.31.185:30195

can someone help?

**Comment by ouyangnengda** [comment]
https://github.com/apache/dubbo/issues/419#issue-218162094

**Comment by ouyangnengda** [comment]
https://github.com/apache/dubbo/issues/419#issue-218162094

**Comment by ouyangnengda** [comment]
https://github.com/apache/dubbo/issues/419#issue-218162094
楼主看一下issue对你是否有帮助

**Comment by zziawan** [comment]
registries configuration in property file not work, error when staring， in xml inside jar do work, but it lost flexibility，can not use spring boot external config or config center.

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
