### ISSUE TITLE
dubbo2.6.2版本oneWay调用造成线程上下文污染传递

### ISSUE THREAD

**Issue by likefang** [apache/dubbo#8281]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: linux
* Java version: java8

### Steps to reproduce this issue

1. 调用链为serviceA调用serviceB调用serviceC，整个调用链均为dubbo方式调用
2. serviceA调用serviceB为oneWay方式调用不关注返回结果，serviceB调用serviceC为正常的dubbo同步调用，但是serviceB获取到serviceC的返回结果为null，而不是包装过的response，造成解析结果时报NPE异常
3. 验证一：修改serviceA调用servoceB的调用方式为同步调用，问题解决，整个调用链路正常
4. 验证二：忽略第三步，换另外一种方式验证，在serviceB中添加fitter，清除掉oneWay方式调用的key，整个调用也正常进行
5. 结论：在dubbo-rpc module中的org.apache.dubbo.rpc.filter.ContextFilter类中清除的Key列表中不包含oneWay方式调用使用的Key（RETURN_KEY）造成oneWay方式的调用一直向下游调用链传递

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by masteryourself** [comment]
https://github.com/apache/dubbo/issues/3848

**Comment by likefang** [comment]
thinks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上7:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] dubbo2.6.2版本oneWay调用造成线程上下文污染传递 (#8281)





 
#3848

**Comment by CrazyHZM** [comment]
The above question should have answered your question, please close this issue for now.
