### ISSUE TITLE
Dubbo3.0使用nacos2.0注册时parameters: namespace无效

### ISSUE THREAD

**Issue by xiaohuige99** [apache/dubbo#8303]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.1
* Operating System version: mac os
* Java version: 1.8

### Steps to reproduce this issue

配置信息
  registry:
    address: nacos://192.168.88.90:8848?namespace=dubbo-test # 这样是可以的
    parameters:
      namespace: dubbo-test #这种不行
    group: TEST_GROUP

**Comment by xiaoheng1** [comment]
let me have a look

**Comment by CrazyHZM** [comment]
Resolved in #8308
