### ISSUE TITLE
dubbo3.0启动服务会自动注册一个DEFAULT_GROUP的服务，如何调整这个默认分组

### ISSUE THREAD

**Issue by xiaohuige99** [apache/dubbo#8317]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.1
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. dubbo启动服务会自动注册一个DEFAULT_GROUP的服务

![image](https://user-images.githubusercontent.com/47840704/126137144-539e6d64-21ee-456d-b549-69bab18be721.png)

**Comment by xiaoheng1** [comment]
you can try to set namespace in the url. DEFAULT_GROUP is a default group in nacos when namespace is null.

**Comment by xiaohuige99** [comment]
My configuration
dubbo:
  application:
    name: dubbo-service
  scan:
    base-packages: com.jeepf.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.88.90:8848?namespace=dubbo-test 
    group: TEST_GROUP
  provider:
    group: DEV # 服务名group后缀
  consumer:
    group: DEV # 消费者group后缀
    check: false

**Comment by xiaohuige99** [comment]
> you can try to set namespace in the url. DEFAULT_GROUP is a default group in nacos when namespace is null.

Please take a look at my configuration

**Comment by xiaoheng1** [comment]
sorry, The above description is wrong. The default value of namespace is public, and the default value of group is DEFAULT_GROUP

**Comment by xiaoheng1** [comment]
i will check the configuration that you provider now.

**Comment by xiaoheng1** [comment]
dubbo-service is registered for service discovery. You can first use the nacos.group parameter to set the value of this group, I will submit a pr later to adjust nacos.group to group

**Comment by xiaohuige99** [comment]
> dubbo-service is registered for service discovery. You can first use the nacos.group parameter to set the value of this group, I will submit a pr later to adjust nacos.group to group

If i use nacos ,Then the phenomenon is the picture，There will be two service 
![image](https://user-images.githubusercontent.com/47840704/126246137-f3be6220-f820-442d-bef7-548ca0c93378.png)

**Comment by xiaoheng1** [comment]
i will check it later.

**Comment by xiaohuige99** [comment]
> i will check it later.

Thank you

**Comment by xiaoheng1** [comment]
This problem did not reproduce in my local test. 
Can you provider a demo ?
![image](https://user-images.githubusercontent.com/12539730/126346727-fd42daae-e614-4fe7-ba6d-54cddf279876.png)

**Comment by xiaohuige99** [comment]
> This problem did not reproduce in my local test.
> Can you provider a demo ?
> ![image](https://user-images.githubusercontent.com/12539730/126346727-fd42daae-e614-4fe7-ba6d-54cddf279876.png)


        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-autoconfigure</artifactId>
            <version>3.0.1</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>3.0.1</version>
        </dependency>

**Comment by xiaohuige99** [comment]
[dubbo-service.zip](https://github.com/apache/dubbo/files/6854474/dubbo-service.zip)
@ @xiaoheng1

**Comment by xiaoheng1** [comment]
@xiaohuige99 i will try it later.

**Comment by xiaoheng1** [comment]
The problem you mentioned still doesn't appear when i use the demo you provider.

config:

server:
  port: 8086
  address: 127.0.0.1
spring:
  application:
    name: dubbo-service
  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.88.250:8848
#        auto-register: true
#        group: TEST_GROUP
#        namespace: dubbo-test
#        ip: 10.8.0.10
    compatibility-verifier:
      enabled: false
############################# dubbo 配置 start #############################
dubbo:
#  application:
#    name: dubbo-service
  scan:
    base-packages: com.jeepf.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://127.0.0.1:8848?namespace=dubbo-test & nacos.group=TEST_GROUP # 这样是可以的
    parameters:
      namespace: dubbo-test #这种不行
    group: TEST_GROUP
  provider:
    group: DEV # 服务名group后缀
  consumer:
    group: DEV # 消费者group后缀
    check: false
#dubbo:
#  registry:
#    address: nacos://192.168.88.250:8848?namespace=dubbo-test
#    group: TEST_GROUP
#  consumer:
#    check: false
#    group: DEV
############################# dubbo 配置 end #############################

![image](https://user-images.githubusercontent.com/12539730/126639292-0d98fd7f-286d-4caa-8a73-6b668aa56b59.png)

**Comment by xiaohuige99** [comment]
> 当我使用您提供的演示时，您提到的问题仍然没有出现。
> 
> 配置：
> 
> ```
> server:
>   port: 8086
>   address: 127.0.0.1
> spring:
>   application:
>     name: dubbo-service
>   cloud:
> #    nacos:
> #      discovery:
> #        server-addr: 192.168.88.250:8848
> #        auto-register: true
> #        group: TEST_GROUP
> #        namespace: dubbo-test
> #        ip: 10.8.0.10
>     compatibility-verifier:
>       enabled: false
> ############################# dubbo 配置 start #############################
> dubbo:
> #  application:
> #    name: dubbo-service
>   scan:
>     base-packages: com.jeepf.service
>   protocol:
>     name: dubbo
>     port: 20880
>   registry:
>     address: nacos://127.0.0.1:8848?namespace=dubbo-test & nacos.group=TEST_GROUP # 这样是可以的
>     parameters:
>       namespace: dubbo-test #这种不行
>     group: TEST_GROUP
>   provider:
>     group: DEV # 服务名group后缀
>   consumer:
>     group: DEV # 消费者group后缀
>     check: false
> #dubbo:
> #  registry:
> #    address: nacos://192.168.88.250:8848?namespace=dubbo-test
> #    group: TEST_GROUP
> #  consumer:
> #    check: false
> #    group: DEV
> ############################# dubbo 配置 end #############################
> ```
> 
> ![图像](https://user-images.githubusercontent.com/12539730/126639292-0d98fd7f-286d-4caa-8a73-6b668aa56b59.png)

Nacos service version is 2.0.2 ？

**Comment by xiaoheng1** [comment]
I am using the code of nacos develop branch.

**Comment by CrazyHZM** [comment]
Close this issue temporarily, if there are other issues, you can open this issue at any time.
@xiaohuige99
