### ISSUE TITLE
是否有注解可以配置一个service中单个方法的retry次数.?

### ISSUE THREAD

**Issue by Likenttt** [apache/dubbo#8333]
是否有注解可以配置一个service中单个方法的retry次数(默认为2).我注意到有两个solution,
- 通过xml方式, 但是现在的dubbo已经大量使用注解了, 使用xml有开历史倒车的味道; 
- 通过 `@Service`注解里面的parameter参数, 但是我浏览了一些issue,说是一个比较hack的做法,并不推荐. 
所以是否有其他更优雅的途径?

**Comment by AlbumenJ** [comment]
可以通过配置 
```java
    /**
     * methods support
     *
     * @return
     */
    Method[] methods() default {};
```

**Comment by Likenttt** [comment]
> 可以通过配置
> 
> ```java
>     /**
>      * methods support
>      *
>      * @return
>      */
>     Method[] methods() default {};
> ```

当前我使用的版本是2.7,没有这个参数 :(

**Comment by caichy** [comment]
`@DubboService(methods = {
    @Method(name = "getById", timeout = 3000, retries = 1)})`

**Comment by Likenttt** [comment]
> `@DubboService(methods = { @Method(name = "getById", timeout = 3000, retries = 1)})`

方法很好, 可是我们还没用上dubbo 3.0. 感谢.
