### ISSUE TITLE
triple 支持调用纯grpc服务吗，比如一个使用grpc-spring-boot-starter 的服务

### ISSUE THREAD

**Issue by Cczzzz** [apache/dubbo#8335]
grpc的服务提供者只会上报自己的grpc端口，这样的情况也能兼容吗。
还有 dubbo-spring-boot-starter 与spring-cloud-starter-alibaba-nacos-discovery 支持3.0吗

**Comment by AlbumenJ** [comment]
支持调用，需要手动指定目标，具体文档后续会补齐
