### ISSUE TITLE
Optimize thread overhead of ExpiringCache.

### ISSUE THREAD

**Issue by hengyoush** [apache/dubbo#8338]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.x
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

I read the code about ExpiringCache. Currently, every method call starts a cleanup thread. Can we use a global thread pool (like JDK ScheduledExecutorService) for cleanup?

Every time we create a ExpiringCache,  submit a scheduled task

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by BurningCN** [comment]
AbstractCacheFactory internally caches Cache instances (such as ExpiringCache). Why do you miss the cache? Because I understand that only every time the createCache method is called will a new cleaning thread be started (for ExpiringCache)

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
