### ISSUE TITLE
关于启动脚本的一些问题

### ISSUE THREAD

**Issue by DeadLion** [apache/dubbo#835]
在启动脚本中  start.sh  经常检测不到已经在运行的服务，ps 参数需要加上 e  ，显示所有进程才行，如下。stop.sh 中也有同样的问题。
```
PIDS=`ps -ef | grep java | grep "$CONF_DIR" |awk '{print $2}'`
if [ -n "$PIDS" ]; then
    echo "ERROR: The $SERVER_NAME already started!"
    echo "PID: $PIDS"
    exit 1
fi
```

还有个问题就是 stop.sh 的脚本默认会执行 dump.sh ，之前碰到过 dump 时卡死整个应用的情况，尤其是在程序正在处理大量请求的时候。建议 stop.sh 里剔除执行 dump 的逻辑，如果真需要 dump 的时候，应该自己手动执行吧。

**Comment by DayuZhu** [comment]
我想知道能否将start.sh中 jvm 参数优化一下，调成 G1收集器

**Comment by chickenlj** [comment]
目前工程中的脚本尚没有跟随工程更新，都是几年前写的了，大家如果有需求的话还请暂且自己修改一下。

我们近期如果有精力的话安排把这些脚本再优化一下

**Comment by lovepoem** [comment]
Will fixed in https://github.com/apache/dubbo/issues/5668

**Comment by kimmking** [comment]
@lovepoem 

> Will be fixed in #5668

实际测试和线上来看，jdk8下，吞吐量最好的还是ParallelGC > CMS > G1
延迟平均最低的是CMS > G1 > ParallelGC 

G1的优势是延迟可控可预期，但是在JDK11和13的ZGC、Shenandoah面前，也被秒杀。

建议
- 默认做个判断：jdk8使用CMS，9-10使用G1,11-12使用ZGC，13+ Shenandoah
- 允许用户通过OPTS或者GC_OPTS环境变量自行修改GC策略
