### ISSUE TITLE
dubbo observability construction

### ISSUE THREAD

**Issue by complone** [apache/dubbo#8356]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.0
* Operating System version: ubantu16.04
* Java version: 1.8.0

### Steps to reproduce this issue

doc: https://www.yuque.com/apache-dubbo/dubbo3/gd5unt

1. There are currently two ways to report promthues indicators. One is service discovery through Prometheus, and the other is service discovery through pushgateway. In order to solve the single point problem of pushgateway, the following SDK is developed
https://github.com/complone/custom-metrics-sdk
2. In order to be compatible with the service registration discovery of zk/eurekua/nacos, the DisCoverClient in spring Cloud is used for implementation
https://spring.io/guides/gs/service-registration-and-discovery/

3.Another way, based on dubbo's registration center management factory ```AbstractRegisteryFactory``` to further expand

### Expected Result

Welcome to participate in the discussion of observability construction

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by complone** [comment]
@lexburner Can you help me take a look？

**Comment by chickenlj** [comment]
see https://github.com/orgs/apache/projects/121
