### ISSUE TITLE
dubbo2.7.8版本本地服务启动后会影响正常服务 

### ISSUE THREAD

**Issue by 985177520** [apache/dubbo#8360]
![image](https://user-images.githubusercontent.com/43394661/127124355-e3205fb3-126b-458e-bdb5-dfb174b79d48.png)
问题1：本地启动实例注册到nacos后，会影响到服务器上正常的服务，并且会使其健康状态变成false，但是将整个服务点击删除后，又会将服务器上正常的服务注册到nacos。
问题2：本地服务下线后，会一直注册在nacos但是建康状态为false，然后线上服务调用时会调用健康状态为false的已经关闭的错误服务
报错如下
![image](https://user-images.githubusercontent.com/43394661/127127610-3d5b1c36-302e-41d8-b341-4ce4a96663f1.png)
![image](https://user-images.githubusercontent.com/43394661/127127770-5903de1c-be84-42d4-bdbe-88005e206761.png)

**Comment by AlbumenJ** [comment]
请检查网络环境和注册使用的网卡信息

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
