### ISSUE TITLE
3.0.1 整合nacos 命名空间不起作用

### ISSUE THREAD

**Issue by cslcool** [apache/dubbo#8367]
version：3.0.1

![image](https://user-images.githubusercontent.com/34473354/127444339-ec6d59b5-2d04-4398-925e-f77627b99c3b.png)

同样的配置，2.7.12是可以注册到指定namaspace中的，3.0.1注册不进去

**Comment by kevinw66** [comment]
related to #8303

**Comment by CrazyHZM** [comment]
Resolved in #8308
