### ISSUE TITLE
dubbo 3.0 KubernetesServiceDiscovery question

### ISSUE THREAD

**Issue by shoyu666** [apache/dubbo#8374]
https://github.com/apache/dubbo/blob/3.0/dubbo-registry/dubbo-registry-kubernetes/src/main/java/org/apache/dubbo/registry/kubernetes/KubernetesServiceDiscovery.java
现状：
```
         当前是将metadata写入pod的Annotation,获取的时候是先获取Endpoints,再找到对应的pod的metadata。
```
Question：
```
         1:是否可以监听Endpoints并直接写入metadata到Endpoints更为直接。
         2:开发环境下，本地开发电脑跑A服务，会和服务器的其它服务(通过zk注册中心)互相访问(网络基于阿里云sag打通)，
            但基于k8s的实现如何打通？
            如果直接基于Endpoints,将本地开发电脑以Endpoints加入到k8s集群是否ok?

apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    io.dubbo/metadata:...
  name: ${serviceName}
subsets:
  - addresses:
      - ip: ${本地开发机器ip,基于sag}
    ports:
      - port: xxxx
```

**Comment by AlbumenJ** [comment]
>          1:是否可以监听Endpoints并直接写入metadata到Endpoints更为直接。

Dubbo 的 metadata 属性是属于实例本身的，而如果写入 Endpoints 的话需要和 Service 绑定在一起，而 Endpoints 的生命周期和 Service 是对齐的。也即是 Service 的存在与否不会影响 Pod 的创建，如果 Dubbo 写入的是 Service 相关的会加大运维成本。

**Comment by shoyu666** [comment]
thanks
