### ISSUE TITLE
Could not resolve placeholder 'xx' in value "${xx}"

### ISSUE THREAD

**Issue by yipixiaofeiyang** [apache/dubbo#8375]
ref-> https://github.com/apache/dubbo/issues/8359
@kevinw66 @kylixs 我今天在继续探索3.0的升级过程中, 又发现了个问题. 也和PropertySourcesPropertyResolver相关, 在原有的简易demo上引入了三方sdk, 比如aliyun-oss, 其中也有变量引入${aaa}, 如果采用
`<bean id="propertiesUtil" class="org.springframework.context.support.PropertySourcesPlaceholderConfigurer"></bena>`
的方式不会报错, 但是采用自定义类集成PropertySourcesPlaceholderConfigurer,如:
`<bean id="propertiesUtil" class="com.wqh.demo.dobbo3.PropertiesUtil">`
 又会引发上面的(Could not resolve placeholder)问题, 
 同样, 我把版本回到2.7.8  程序又能正常运行! 请原谅我三番五次的对比和折磨!  因为这对我的项目很重要!
 详情可以参考下面改进后的demo
[dobbo3-1.zip](https://github.com/apache/dubbo/files/6905569/dobbo3-1.zip)

_Originally posted by @yipixiaofeiyang in https://github.com/apache/dubbo/issues/8359#issuecomment-889669426_

**Comment by yipixiaofeiyang** [comment]
感觉和id已经没啥关系了

**Comment by kevinw66** [comment]
用了最新的代码测了一下好像是没问题了

**Comment by yipixiaofeiyang** [comment]
> 用了最新的代码测了一下好像是没问题了
好的
