### ISSUE TITLE
@DubboReference in Configuration but IDEA warning: Could not autowire. No beans of 'xxx' type found

### ISSUE THREAD

**Issue by mrrao** [apache/dubbo#8377]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.1
* Dubbo spring boot starer: 3.0.1
* Operating System version: Mac Os
* Java version: 1.8
* IntelliJ IDEA 2019.1.3

### Steps to reproduce this issue

1. Config dubbo reference in Configuration.java use @DubboReference and @Bean
2. Autowire reference in other Service
3. **IDEA warning: Could not autowire. No beans of 'xxx' type found**
4. Compile and run success

Code just like javadoc in org.apache.dubbo.config.spring.ReferenceBean.java:
```
   @Configuration
   public class ReferenceConfiguration {
       @Bean
       @DubboReference
       public ReferenceBean<HelloService> helloService() {
           return new ReferenceBean<>();
       }
   }
   
   @Controller
   public class FooController {
       
       private final HelloService helloService;
       
       @Autowired
       public FooController(HelloService helloService) {  <--- IDEA warning: Could not autowire. No beans of 'HelloService' type found
           this.helloService = helloService;
       }
   }
```

### Expected Result

No IDEA warning

### Suggest
org.apache.dubbo.config.spring.ReferenceBean.java:
```
public class ReferenceBean<T> implements FactoryBean
==>
public class ReferenceBean<T> implements FactoryBean<T>
```

Maybe solve the problem

**Comment by kevinw66** [comment]
Great suggestion!

**Comment by mrrao** [comment]
Thanks!
