### ISSUE TITLE
以前用zookeeper时也不往注册中心添加接口信息，现在nacos为什么添加了呢?

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8380]
就是启动一个普通的服务提供者，nacos服务列表中就出现2项：
（1）providers:com.ghy.www.api.IService1::
（2）my-nacos-provider

第2个可以理解，是服务提供者，但第1个为什么要注册进来呢?不理解，感谢。

**Comment by xiaoheng1** [comment]
What version are you using?

**Comment by startjava** [comment]
@xiaoheng1    有人说，这是正常的现象，，，，我用的是dubbo3.0.1和nacos2.0.3。

**Comment by xiaoheng1** [comment]
In some 2.7 versions, there will also be two registered services.

**Comment by startjava** [comment]
感谢
