### ISSUE TITLE
请问有关check不受影响的理解？

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8397]
https://dubbo.apache.org/zh/docs/advanced/preflight-check/

dubbo.consumer.check=false，是设置 check 的缺省值，如果配置中有显式的声明，如：<dubbo:reference check="true"/>，不会受影响。
----------------------------------------------------------
以上文字是官方文档上的内容，不太懂这个意思。
是不是说明如果使用dubbo.consumer.check=false配置对所有的服务都不进行检查，但是可以使用<dubbo:reference check="true"/>对部分服务进行检查 。

感谢

**Comment by BazookaW** [comment]
@startjava 我说一下我的理解哈，其实这个两个东西做的都是一件事情：`启动时检查提供者是否存在，true报错，false忽略`。当`<dubbo:reference check="true"/>`没有配置时会默认使用`<dubbo:consumer check="true"/>`。

**Comment by CrazyHZM** [comment]
Already resolved.
