### ISSUE TITLE
注册中心问题：如何定义注册到的注册中心上的dubbo server 名称

### ISSUE THREAD

**Issue by sephiroka** [apache/dubbo#8408]
因为有些原因，没有办法使用公用的api模块暴露接口给consumer，只能在consumer内部自定义一个包路径和类名称一摸一样的接口，有没有办法自定义这个名称，因为我看注册到nacos上的名称都是 （包路径+类名+版本号）这种形式。

**Comment by AlbumenJ** [comment]
可以尝试自己实现一个注册中心以自定义写入格式

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there are other problems, you can open the issue at any time
@sephiroka
