### ISSUE TITLE
dubbo 2.6.x版本兼容存在问题

### ISSUE THREAD

**Issue by gudegg** [apache/dubbo#8424]
提供者版本：2.6.10   
消费端：2.6.2
### 复现
1. 提供者配置
```xml

    <dubbo:application name="hello-world-app"  />

   
    <dubbo:registry address="zookeeper://127.0.0.1:2181" />

   //客户端选择netty3  不选择客户端没问题
    <dubbo:protocol name="dubbo" port="20880"  client="netty3"/>

   
    <dubbo:service interface="com.xxx.DemoService" ref="demoService" />

   
    <bean id="demoService" class="com.xxx.impl.DemoServiceImpl" />
```
2. 消费端配置
```xml
    <dubbo:application name="consumer-of-helloworld-app"  />

    <dubbo:registry address="zookeeper://127.0.0.1:2181" />

    <dubbo:reference id="demoService" interface="com.xxx.DemoService" />
```
3. 会导致消费端无法发现提供者

### 几个问题：
1. 按理说提供者的传输客户端选择不应该影响到消费端的，这里做了耦合，要是提供者选择mina呢，那消费端默认情况下没依赖这个架包就会全部会挂掉
2. 现在dubbo高版本依赖也有问题，默认客户端是netty4，默认依赖还是3
![image](https://user-images.githubusercontent.com/13344666/128330143-977638da-4df9-429f-8a33-4f73ba2fc9df.png)
3. 排除上面说的，我这个问题的原因就是dubbo对默认客户端做了一次变更，没有做好兼容，老版本spi机制里面根本没有netty3只有默认的netty和netty4

**Comment by fsx379** [comment]
和我之前遇到的问题类似 #7430

**Comment by CrazyHZM** [comment]
2.6.x only focuses on security issues for the time being, you can consider upgrading to 2.7.x first to see if the problem is resolved.
