### ISSUE TITLE
当tries重试次数的数量小于提供者的数据时，会发生什么?

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8425]
有没有可能，，提供者是10个，有4个提供者宕机了，，重试次数是3，，3次+1次重试巧合都是针对4个宕机的提供者执行了重试1次，总共是4次，然后就出现异常了，，其实另外6个提供者是正常的状态。。

如果这样是不是tries次数尽量要大于提供者个数？感谢 。

**Comment by noissues** [comment]
可以看下源码 `com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker#doInvoke` 的逻辑。在重试前是会重新 list 出提供者实例的，如果提供者 A 宕机，那么 A 就不会被 list 出来，所以不会出现针对宕机的提供者执行了重试的情况。

**Comment by startjava** [comment]
感谢
