### ISSUE TITLE
标签路由降级问题[官网文档对不上以及配置咨询]

### ISSUE THREAD

**Issue by lwsbox** [apache/dubbo#8427]
dubbo版本: 2.7.9

![image](https://user-images.githubusercontent.com/5414568/128332078-ce573f45-96d4-40bd-b33f-85786a297be9.png)
官网的标签路由文档可否更新下,里面一些参数都对不上
RpcContext.getContext().setAttachment("dubbo.force.tag", "true");
这个才是设置为不降级的key   文档写的是 request.tag.force   其实key对应的也是dubbo.tag而不是request.tag
Constants.REQUEST_TAG_KEY  也应该是  CommonConstants.TAG_KEY

同时问下 我们可以通过启动参数设置-Ddubbo.consumer.tag=blue3 来作为全局的消费tag
那么是否可以通过设置启动参数来设置全局的dubbo.force.tag 参数？

**Comment by BurningCN** [comment]
第一个问题的确是这样，方便的话，你可以在dubbo-website([  ](https://github.com/apache/dubbo-website))工程中提交个pr修改一下。第二个问题我不太清楚是否可以这样做，@AlbumenJ 大佬可以抽空看下

**Comment by CrazyHZM** [comment]
@lwsbox 
也可以用启动参数来设置dubbo.force.tag的
