### ISSUE TITLE
请问负载均衡中的配置<dubbo:service interface="..." loadbalance="roundrobin" />是不是可以应用在@DubboService注解中？

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8436]
<dubbo:service interface="..." loadbalance="roundrobin" />中的loadbalance属性应用在@DubboService注解中是否有效？

也就是<dubbo:service>和@DubboService是不是等同的关系，感谢 。

**Comment by BurningCN** [comment]
是的

**Comment by mercyblitz** [comment]
You are right.
