### ISSUE TITLE
在一个项目中针对同一个接口使用不同的容错策略，到底使用哪一个？

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8437]
@DubboReference(cluster = ClusterRules.FORKING)
    private IService1 service1;

    @DubboReference(cluster = ClusterRules.FAIL_OVER)
    private IService1 service2;

比如上面代码，是每个对象有自己的策略，还是两者使用最先声明的，或是两者使用最后声明的，感谢。

**Comment by tanoak10** [comment]
run demo ，Get the answer

**Comment by BazookaW** [comment]
@startjava 我觉得还是要按照业务场景来选择不同的容错策略，这是我之前整理的表格，希望可以帮到你。

![image](https://user-images.githubusercontent.com/17539174/129333219-371d40ea-bce7-4f22-9ea0-4efd4e5fb24b.png)

**Comment by startjava** [comment]
@tanoak10 我用注解@Bean解决的，，，比较标准，，，，，感谢。
@BazookaW 非常感谢，保存了。
