### ISSUE TITLE
entity中含有EnumMap属性，有时候反序列化之后解析，会报 Class [Ljava.util.HashMap$Node; does not implement the requested interface java.util.Set

### ISSUE THREAD

**Issue by jack-baitao** [apache/dubbo#8450]
entity中含有EnumMap属性，有时候反序列化之后解析，会报 Class [Ljava.util.HashMap$Node; does not implement the requested interface java.util.Set

**Comment by AlbumenJ** [comment]
could you please describe more about this?

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
