### ISSUE TITLE
2.7.13 ZoneAwareClusterInvoker doesn't work with zone configuration

### ISSUE THREAD

**Issue by MilkSDF** [apache/dubbo#8451]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

The property PREFER_REGISTRY_WITH_ZONE_KEY in ZoneAwareClusterInvoker should be  just ZONE_KEY, this issue is fixed in dubbo 2.7.9. but in the version 2.7.10+，the bug is also exists。

https://github.com/apache/dubbo/issues/6022

![image](https://user-images.githubusercontent.com/7495090/128657953-4e5a33ee-5b36-4f84-bccc-64bd4decb948.png)

### Actual Result
The registry url is like this

nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=dubbo-3&dubbo=2.0.2&pid=193320&qos.enable=false&release=2.7.7-SNAPSHOT&timestamp=1586922659951&zone=rega

In the url, the key of zone is zone but getParameter(REGISTRY_KEY + "." + ZONE_KEY) use registry.zone.

**Comment by CrazyHZM** [comment]
Resolved in #8521
