### ISSUE TITLE
Clean shared state pollution to avoid flaky tests in module dubbo-common

### ISSUE THREAD

**Issue by LALAYANG** [apache/dubbo#8453]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate. This is similar to #8390 and #7107, but for different tests.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.2-SNAPSHOT
* Operating System version: Linux ubuntu 5.11.0-25-generic
* Java version: 1.8.0_292

### Steps to reproduce this issue

1.Run unit test `org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension_Adaptive` and `org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension_NoExtend` twice in the same JVM.

### Expected Result

The 2 tests should run successfully without any failures.

### Actual Result

Failure after `org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension_Adaptive` runs:
```
java.lang.IllegalStateException: Adaptive Extension already exists (Extension interface org.apache.dubbo.common.extension.ext8_add.AddExt2)!
	at org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension_Adaptive(ExtensionLoaderTest.java:298)
```
Failure after `org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension_NoExtend` runs:
```
java.lang.IllegalStateException: Extension name ext9 already exists (Extension interface org.apache.dubbo.common.extension.ext9_empty.Ext9Empty)!
	at org.apache.dubbo.common.extension.ExtensionLoaderTest.test_AddExtension_NoExtend(ExtensionLoaderTest.java:276)
```

**Comment by CrazyHZM** [comment]
Resolved in #8467
