### ISSUE TITLE
org.apache.dubbo.common.serialize.protobuf.support.ProtobufUtils is not found in dubbo 3.0.x

### ISSUE THREAD

**Issue by Janrin** [apache/dubbo#8461]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.x
* Operating System version: windows 10
* Java version: 11

### Steps to reproduce this issue

1. use protobuf-maven-plugin to generate java code with protoc plugin dubbo-compiler 0.0.2
2. mainClass is org.apache.dubbo.gen.dubbo.Dubbo3Generator

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

org.apache.dubbo.common.serialize.protobuf.support.ProtobufUtils  should exist in dubbo 3.0.x.

### Actual Result

What actually happens?

org.apache.dubbo.common.serialize.protobuf.support.ProtobufUtils is not found in dubbo 3.0.x.

```
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ dubbo-spring-boot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 25 source files to D:\Workspace\medlinker\java\demo\dubbo-spring-boot\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteGuideDubbo.java:[14,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteGuideDubbo.java:[16,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteGuideDubbo.java:[18,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteGuideDubbo.java:[20,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/routeguide/RouteGuideDubbo.java:[22,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/helloworld/GreeterDubbo.java:[14,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[ERROR] /D:/Workspace/medlinker/java/demo/dubbo-spring-boot/build/generated/source/proto/main/java/io/grpc/examples/helloworld/GreeterDubbo.java:[16,63] 程序包org.apache.dubbo.common.serialize.protobuf.support不存在
[INFO] 7 errors 
[INFO] -------------------------------------------------------------

```

**Comment by EarthChen** [comment]
you can use `org.apache.dubbo:dubbo-serialization-protobuf` latest version  https://mvnrepository.com/artifact/org.apache.dubbo/dubbo-serialization-protobuf

**Comment by CrazyHZM** [comment]
@Janrin 
The above answer should solve your problem, temporarily close the issue, if there are other problems, you can open the issue at any time

**Comment by lmm1990** [comment]
@EarthChen
dubbo 3.0.4 with dubbo-serialization-protobuf 2.7.14 is not working

pom.xml setting

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <version>3.0.4</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-protobuf</artifactId>
            <version>2.7.14</version>
        </dependency>

error msg
java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.common.extension.ExtensionInjector, cause: No such extension org.apache.dubbo.common.extension.ExtensionInjector by name spi, possible causes: 
(1) spi=org.apache.dubbo.common.extension.factory.SpiExtensionFactory:
java.lang.IllegalStateException: Failed to load extension class (interface: interface org.apache.dubbo.common.extension.ExtensionInjector, class line: spi=org.apache.dubbo.common.extension.factory.SpiExtensionFactory) in jar:file:/C:/Users/DataXgroup/.m2/repository/org/apache/dubbo/dubbo-common/2.7.14/dubbo-common-2.7.14.jar!/META-INF/dubbo/internal/org.apache.dubbo.common.extension.ExtensionFactory, cause: Duplicate extension org.apache.dubbo.common.extension.ExtensionInjector name spi on org.apache.dubbo.common.extension.inject.SpiExtensionInjector and org.apache.dubbo.common.extension.factory.SpiExtensionFactory
java.lang.IllegalStateException: Failed to load extension class (interface: interface org.apache.dubbo.common.extension.ExtensionInjector, class line: spi=org.apache.dubbo.common.extension.factory.SpiExtensionFactory) in jar:file:/C:/Users/DataXgroup/.m2/repository/org/apache/dubbo/dubbo-common/2.7.14/dubbo-common-2.7.14.jar!/META-INF/dubbo/internal/org.apache.dubbo.common.extension.ExtensionFactory, cause: Duplicate extension org.apache.dubbo.common.extension.ExtensionInjector name spi on org.apache.dubbo.common.extension.inject.SpiExtensionInjector and org.apache.dubbo.common.extension.factory.SpiExtensionFactory
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:998)


update pom.xml

        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.6.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java-util</artifactId>
            <version>3.6.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-api</artifactId>
            <version>3.0.4</version>
        </dependency>

DemoServiceDubbo.java
@javax.annotation.Generated(
value = "by Dubbo generator",
comments = "Source: DemoService.proto")
public final class DemoServiceDubbo {
private static final AtomicBoolean registered = new AtomicBoolean();

public static boolean init() {
    if (registered.compareAndSet(false, true)) {
//            org.apache.dubbo.common.serialize.protobuf.support.ProtobufUtils.marshaller(
//            com.dataxgroup.nex.recommend.idl.HelloReply.getDefaultInstance());
//            org.apache.dubbo.common.serialize.protobuf.support.ProtobufUtils.marshaller(
//            com.dataxgroup.nex.recommend.idl.HelloRequest.getDefaultInstance());
    }
    return true;
}

private DemoServiceDubbo() {}

}

**No error reporting**

### Please upgrade Dubbo serialization protobuf dependency

**Comment by EarthChen** [comment]
@lmm1990 
`dubbo-serialization-protobuf` will no longer be required if dubbo versions after 3.0.3 use the Triple protocol

**Comment by lmm1990** [comment]
@EarthChen 
Thank you. It works normally after modification
