### ISSUE TITLE
我如何重现dubbo.registry.check=true或false的区别？感谢

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8463]
我测试了一下，，在nacos服务没有启动或已经启动，，我的provider使用false或true的效果都是一样的：启动时出现异常，进程销毁了。

所以我想知道我如何重现dubbo.registry.check=true或false的区别？感谢。

**Comment by startjava** [comment]
[check=true.txt](https://github.com/apache/dubbo/files/6958435/check.true.txt)
[check=false.txt](https://github.com/apache/dubbo/files/6958436/check.false.txt)

这是设置true和false的启动日志。

**Comment by startjava** [comment]
[check=false (2).txt](https://github.com/apache/dubbo/files/6958529/check.false.2.txt)
[check=true (2).txt](https://github.com/apache/dubbo/files/6958530/check.true.2.txt)

这是设置true和false的启动日志。nacos呈未启动的状态。

**Comment by startjava** [comment]
不管nacos启动还是未启动，不管check值是true还是false，最终启动的项目都会销毁！行为根本没有任何区别。

这么分析下来，dubbo.registry.check在dubbo3.0.1版本中有bug!!!!

**Comment by mercyblitz** [comment]
You can try the zookeeper register to validate `dubbo.registry.check`, nacos client does not support this feature.

**Comment by startjava** [comment]
好的，我试试ZK的效果。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mercy ***@***.***&gt;; 
发送时间: 2021年8月10日(星期二) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dubbo] 我如何重现dubbo.registry.check=true或false的区别？感谢 (#8463)





 
You can try the zookeeper register to validate dubbo.registry.check, nacos client does not support this feature.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
