### ISSUE TITLE
AwaitingNonWebApplicationListener blocks the application exit

### ISSUE THREAD

**Issue by wangbin77** [apache/dubbo#8469]
Since some bean is not initialized successfully,  spring boot application failed to start. Because the ExecutorService in AwaitingNonWebApplicationListener didn't shutdown, it blocked the application to exist, but the Spring boot application has stopped.

Solution suggestion：
Let AwaitingNonWebApplicationListener listen to ApplicationFailedEvent and release the resource(shutdown ExecutorService) when it receive ApplicationFailedEvent 。

======Below is Chinese description============== 

因为某个bean没有初始化成功， spring boot application启动失败。 但是因为AwaitingNonWebApplicationListener 里面的ExecutorService没有shutdown， 造成应用程序的进程没有退出，但是 Spring boot application 已经stop了。

解决方案：
让 AwaitingNonWebApplicationListener 支持 ApplicationFailedEvent， 在应用收到该事件后，release 资源。

另外好奇的问一下： 之前有监听 ContextClosedEvent， 并且在收到该事件后 release 资源，但是该事件在 2.7.8 版本里面被去掉了，不 知道是什么原因。

**Comment by wangbin77** [comment]
Is anyone handling this issue?

**Comment by wangbin77** [comment]
@AlbumenJ  Can you take a look at this issue. I've translated it into English.

**Comment by CrazyHZM** [comment]
@wangbin77 Please provide the dubbo version, and confirm whether the latest version has this problem.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
