### ISSUE TITLE
Dubbo服务联动业务层实现健康检查，自动上下线注册中心的实现方式咨询

### ISSUE THREAD

**Issue by onethin** [apache/dubbo#8502]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4.1
* Operating System version: CentOS 7.X
* Java version: 1.8.0

需求是想给业务层提供一个健康检查接口，服务框架定时调用该接口，业务层实现一个健康检查逻辑返回当前服务是否正常（比如检查数据库），如返回服务状态不正常，则服务框架操作Dubbo动态下线注册的接口，若返回状态正常则上线注册的接口。想咨询的是操作接口上下线注册中心，通过哪个层面的接口比较好？

**Comment by AlbumenJ** [comment]
可以参考下 dubbo-qos 模块中的操作

**Comment by CrazyHZM** [comment]
Close this issue temporarily, if there are other issues, you can open this issue at any time.
@onethin
