### ISSUE TITLE
Dubbo2.6.10在对无参构造函数的Java基础类进行kryo序列化时报错

### ISSUE THREAD

**Issue by ximingren** [apache/dubbo#8507]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.10
* Operating System version: windows 10
* Java version: 1.6
* kryo-shaded version:4.0.0
* kryo-serializers version:0.45

### Steps to reproduce this issue

1. provider端使用kryo序列化，provider端返回Exception对象，且该对象调用了getStackTrace方法，使得Exception的stackTrace变量值不为空
2. consumer消费，在进行序列化Exception对象时报错，报错信息：java.io.IOException: com.esotericsoftware.kryo.KryoException: Class cannot be created missing no-arg constructor): java.lang.StackTraceElement  Serialization trace:stackTrace 

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
consumer能正常接收到返回结果
### Actual Result

What actually happens?
在consumer端发生序列化报错
If there is an exception, please attach the exception trace:
java.io.IOException: com.esotericsoftware.kryo.KryoException: Class cannot be created missing no-arg constructor): java.lang.StackTraceElement  Serialization trace:stackTrace 
```
Just put your stack trace here!
```

**Comment by ximingren** [comment]
补充说明：
#2220的改动是导致本issue出现的原因。改动点在CompatibleKryo 类，去掉了以下功能：当为java基础类且有无参构造函数时，使用JavaSerializer进行序列化。改动之后直接使用调用getDefaultSerializer获取默认的serializer进行序列化。

**Comment by ximingren** [comment]
补充说明：
#2220的改动是导致本issue出现的原因。改动点在CompatibleKryo 类，

此改动导致Java基础类中带有无参构造函数的类在序列化时使用默认serializer进行，而不是使用JavaSerializer进行。

**Comment by CrazyHZM** [comment]
2.6.x is no longer maintained, it is recommended to upgrade to the latest version.
