### ISSUE TITLE
Question about TagStaticStateRouter#notify method

### ISSUE THREAD

**Issue by BurningCN** [apache/dubbo#8518]
The call here is meaningless, and so is TagDynamicStateRouter#notify

https://github.com/apache/dubbo/blob/0809a168db5fd71a58dd3f87b0bce00bd5ed8916/dubbo-cluster/src/main/java/org/apache/dubbo/rpc/cluster/router/tag/TagStaticStateRouter.java#L152

**Comment by wangchengming666** [comment]
I'll fix it.
