### ISSUE TITLE
etcd作为注册中心，如何支持https

### ISSUE THREAD

**Issue by visionarywind** [apache/dubbo#8528]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: centos7
* Java version: 1.8

使用etcd作为dubbo的注册中心，etcd已经开启https支持，
dubbo该如何适配呢？

感谢

**Comment by chickenlj** [comment]
目前的对接是不支持etcd https的，请参考以下现有对接代码，如有必要可进行相应适配

https://github.com/apache/dubbo/blob/master/dubbo-remoting/dubbo-remoting-etcd3/src/main/java/org/apache/dubbo/remoting/etcd/jetcd/JEtcdClientWrapper.java#L143

**Comment by visionarywind** [comment]
感谢，目前通过再注册个etcd的扩展，实现了基本功能
可以的话，希望新版本能够支持tls
