### ISSUE TITLE
consumer消费不到新增的provider

### ISSUE THREAD

**Issue by caijixmx** [apache/dubbo#8529]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?
当一次启动多个provider，然后再启动consumer，设置consumer负载均衡策略为random，consumer可以访问这多个provider，但consumer的请求发送不到consumer启动之后启动的provider
If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by caijixmx** [comment]
采用的是nacos注册中心，应用级服务发现，使用的dubbo版本是3.0.2

**Comment by horizonzy** [comment]
3.0.1有这个问题，3.0.2应该是解决了。我跟一下

**Comment by caijixmx** [comment]
> 3.0.1有这个问题，3.0.2应该是解决了。我跟一下

请问有结果了么？我自己使用3.0.2时没成功，不知道是不是需要什么配置等其他操作

**Comment by horizonzy** [comment]
不好意思，这几天有点忙，我现在看一下这个问题

**Comment by horizonzy** [comment]
我在本地测试，3.0.2版本在我本地不能复现。你能提供一个demo能浮现的demo放在你的仓库吗？

**Comment by caijixmx** [comment]
> 我在本地测试，3.0.2版本在我本地不能复现。你能提供一个能浮现的demo放在你的仓库吗？
这个问题我咨询过 #8345 issue的作者，他回复说3.0.2确实有这个问题，并验证了最新的代码说是解决了---最新的尚未发的代码，他自己打包测试的

**Comment by horizonzy** [comment]
这个修复在3.0.2是包含的，3.0.1存在这个问题。确认一下你的代码使用的是哪个版本呢。

**Comment by caijixmx** [comment]
> 这个修复在3.0.2是包含的，3.0.1存在这个问题。确认一下你的代码使用的是哪个版本呢。

我用3.0.1和3.0.2都测了，问题都存在，而且那个issue的代码提交者也测了3.0.2，说确实存在问题，但他验证了最新的代码说已经解决了。

**Comment by horizonzy** [comment]
@haoyann 能帮忙阐述一下吗。我使用3.0.2确实没有遇到这个问题。

**Comment by AlbumenJ** [comment]
@caijixmx 应用级推送有延时，同时 nacos 注册中心也会有偶尔较大延时

**Comment by caijixmx** [comment]
> @caijixmx 应用级推送有延时，同时 nacos 注册中心也会有偶尔较大延时

请问这个使用与nacos-client的版本有关系么？我使用的nacos-client是1.4.1版本

**Comment by AlbumenJ** [comment]
> > @caijixmx 应用级推送有延时，同时 nacos 注册中心也会有偶尔较大延时
> 
> 请问这个使用与nacos-client的版本有关系么？我使用的nacos-client是1.4.1版本

dubbo 3 需要使用 nacos 2

**Comment by caijixmx** [comment]
> > > @caijixmx 应用级推送有延时，同时 nacos 注册中心也会有偶尔较大延时
> > 
> > 
> > 请问这个使用与nacos-client的版本有关系么？我使用的nacos-client是1.4.1版本
> 
> dubbo 3 需要使用 nacos 2

我升级了nacos-client的版本到2.0.2，但在所有逻辑代码及配置未修改的情况下，consumer无法发现provider了，我把客户端版本降回1.4.1，又可以发现了，我理解的是nacos-client只是底层与nacos注册中心交互的客户端，在使用层面应该不需要修改什么的吧？

**Comment by horizonzy** [comment]
请问一下你的nacos-server是什么版本呢。dubbo3使用nacos-client的2.x版本，nacos-client 2.x版本需要nacos-server的2.x版本

**Comment by caijixmx** [comment]
> 请问一下你的nacos-server是什么版本呢。dubbo3使用nacos-client的2.x版本，nacos-client 2.x版本需要nacos-server的2.x版本

nacos-server使用的是 2.0.3，nacos-client是1.4.1

**Comment by horizonzy** [comment]
把nacos-cleint版本升级2.0.2，跑几次看看。2.x 版本nacos-server需要2.x版本的nacos-client.

**Comment by caijixmx** [comment]
> 把nacos-cleint版本升级2.0.2，跑几次看看。2.x 版本nacos-server需要2.x版本的nacos-client.

我直接升级的nacos-client 2.0.2，但consumer发现不了服务了，把版本改回来就可以发现了；我看后面提个demo到我的仓库里；还有个问题请教一下，关于dubbo 3.x版本，nacos必须使用2.x版本的nacos-server么？我用nacos-server的1.4.1也是能发现应用级服务的，是不是使用1.4.1版本会有什么问题啊？

**Comment by caijixmx** [comment]
> 把nacos-cleint版本升级2.0.2，跑几次看看。2.x 版本nacos-server需要2.x版本的nacos-client.

我升级了nacos-client到2.0.2版本，其他未修改，启动consumer无法发现provider了，启动会报错服务找不到；然后我把dubbo的版本升级到了3.0.2.1版本，都正常了，使用nacos-client 2.0.2也可以发现provider，后启动的服务consumer也可以感知到了。使用3.0.2.1版本，目前没有问题；  另外：请问，dubbo 3.x版本必须使用 nacos-server、nacos-client 2.x版本么？使用1.4版本会有问题么？（我简单测试过nacos-server 1.4 版本，也是可以发现服务的）

**Comment by caijixmx** [comment]
> > > 把nacos-cleint版本升级2.0.2，跑几次看看。2.x 版本nacos-server需要2.x版本的nacos-client.
> > 
> > 
> > 我升级了nacos-client到2.0.2版本，其他未修改，启动consumer无法发现provider了，启动会报错服务找不到；然后我把dubbo的版本升级到了3.0.2.1版本，都正常了，使用nacos-client 2.0.2也可以发现provider，后启动的服务consumer也可以感知到了。使用3.0.2.1版本，目前没有问题； 另外：请问，dubbo 3.x版本必须使用 nacos-server、nacos-client 2.x版本么？使用1.4版本会有问题么？（我简单测试过nacos-server 1.4 版本，也是可以发现服务的）
> 
> 提供者那边的nacos-client升级了吗

都升级了的；     后面 那个问题您晓得么？使用1.4可以不？因为nacos要使用1.4版本的，所以想咨询一下注意事项

**Comment by horizonzy** [comment]
现在的 nacos-server 2.x 版本兼容了 1.4.1的客户端。还是可以使用的。

**Comment by caijixmx** [comment]
> 现在的 nacos-server 2.x 版本兼容了 1.4.1的客户端。还是可以使用的。

请问nacos-server可以使用1.4.1么？

**Comment by AlbumenJ** [comment]
如果要使用完整 Dubbo 3.0 的能力，nacos-server 和 nacos-client **必须** 都升级到 2.0.x 版本以上。Dubbo 3.0 默认传递依赖 2.0.x 版本的 nacos-client，如果强制指定低版本的 nacos-client 会丢失应用级服务发现的功能。

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
