### ISSUE TITLE
【dubbo 2.7.8】 负载均衡逻辑无法获取provider端timestamp ,导致warmup 策略失效。

### ISSUE THREAD

**Issue by yuanhe3** [apache/dubbo#8541]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version:  2.7.8
* Java version: 1.8

负载均衡逻辑无法获取provider端timestamp是Dubbo 2.5.5一开始有问题，后面 Dubbo 2.5.6 又修复了，然后Dubbo 2.7.2代码调整完，又出问题了。最后文章说Dubbo 2.7.4 后完全修复了，但我看代码，在Dubbo 2.7.4  之后提交代码又有那个删provider 的 timestamp操作。应该是这个导致的
![image](https://user-images.githubusercontent.com/10695531/129997403-46c10178-7203-47f1-95ae-5ec29eb9541c.png)
![image](https://user-images.githubusercontent.com/10695531/129997941-9de92fb3-a819-40ec-a24e-1623b6039f5f.png)

**Comment by BazookaW** [comment]
Dubbo 3.0 also has this problem，I'll try to fix it.

**Comment by xiaoheng1** [comment]
@yuanhe3 Are you using application-level registration discovery or interface-level discovery?

**Comment by BazookaW** [comment]
@xiaoheng1 大佬，我尝试解决了这个问题，麻烦帮忙review一下哈，感谢！

**Comment by BazookaW** [comment]
@yuanhe3 你好，方便提供一个demo吗？谢谢！

**Comment by yuanhe3** [comment]
> @yuanhe3 你好，方便提供一个demo吗？谢谢！

demo 可能不太好提供给你，我可以描述一下，就是我在测试环境部署了两个同样的服务端的 docker 实例，然后在nacos上就能看到对应的服务端注册的两个ip了，之后我通过一个consumer实例去调用对应服务端提供的接口，就发现warmup 策略不生效，之后打日记看了原因，发现如上的问题，就是consumer端获取不到provider端的timestamp.

**Comment by yuanhe3** [comment]
> using application-level registration discovery

using application-level registration discovery

**Comment by xiaoheng1** [comment]
> using application-level registration discovery

I tried it on this machine, and the application-level service discovery can get the timestrap field on the instance.

Can you describe how it is used? It would be better if you could provide a demo.

**Comment by yuanhe3** [comment]
> > using application-level registration discovery
> 
> I tried it on this machine, and the application-level service discovery can get the timestrap field on the instance.
> 
> Can you describe how it is used? It would be better if you could provide a demo.

![image](https://user-images.githubusercontent.com/10695531/130543588-56739949-eea4-4400-aa4e-c38aad316871.png)

**Comment by xiaoheng1** [comment]
您这个信息太模糊了，能否提供比如 provider 端和 consumer 端的配置信息

**Comment by yuanhe3** [comment]
> 您这个信息太模糊了，能否提供比如 provider 端和 consumer 端的配置信息

经过我排查，发现不是dubbo的问题，是我使用了spring-cloud-starter-dubbo 了。 不同provider的实例除了host port 不同，参数默认是只使用其中一个url的参数。见如下代码：
![image](https://user-images.githubusercontent.com/10695531/130765311-6dff578c-8956-42dd-828b-3659130f20d3.png)

**Comment by yuanhe3** [comment]
> 如果这个没有其他问题的话，我这边关闭这个 issue 了

嗯。好的

**Comment by xieqiao2019** [comment]
问题没解
