### ISSUE TITLE
如何在consumer端获取调用的provider的application name

### ISSUE THREAD

**Issue by shensi199312** [apache/dubbo#8559]
如题：
想在Filter或者Router中，获取服务提供方的application name,有什么办法吗,
https://github.com/apache/dubbo/issues/3472
这个issue应该也没解决问题

### Environment

* Dubbo version: 2.7.12
* Operating System version: macos10.15.7
* Java version: 1.8

**Comment by 24kpure** [comment]
`invoker.getUrl().getParameter(REMOTE_APPLICATION_KEY)`
It works for me. Maybe you can get the answer from `org.apache.dubbo.rpc.filter.ConsumerContextFilter#invoke`.
