### ISSUE TITLE
dubbo.registry.default属性配置无法读取到

### ISSUE THREAD

**Issue by caijixmx** [apache/dubbo#8565]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.1、3.0.2
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. 配置dubbo.registry.default=false
2. 运行读取到的RegistryConfig中的isDefault属性为null
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
当配置了该配置项，其对应配置类中的属性为对应的值false或是true，而不是null

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
需要提供一个可以复现的示例，或者具体描述下如何配置的

**Comment by caijixmx** [comment]
> 需要提供一个可以复现的示例，或者具体描述下如何配置的

在application.properties文件中配置了dubbo.registry.default=true   然后debug启动到解析完配置属性后，发现其他配置的字段均有值，但就这个配置的 isDefault属性是null；                                     
我想验证的是DubboBootstrap类中的
         useRegistryAsMetadataCenterIfNecessary 方法中的：
                  List<RegistryConfig> defaultRegistries = configManager.getDefaultRegistries();
          这一行，我获取到的RegistryConfig的属性中 “isDefault” 是null

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
