### ISSUE TITLE
dubbo.provider.parameters无法注册到nacos 上面

### ISSUE THREAD

**Issue by tdwmarlboro** [apache/dubbo#8570]
dubbo 2.7.10版本，nacos 1.4.2
使用xml 方式
    <dubbo:provider>
        <dubbo:parameter key="test" value="123"/>
    </dubbo:provider>
可以在nacos 服务中心的provider 元数据中看到这个数据。
但使用properties dubbo.provider.parameters.test=123 无法注册到nacos 上面，请问是什么原因？

**Comment by chickenlj** [comment]
尝试使用 `dubbo.provider.parameters=[{test:123},{key:value}]`

**Comment by tdwmarlboro** [comment]
@chickenlj 可以了
