### ISSUE TITLE
[2.7.13] org.apache.dubbo.common.utils.NetUtils的ignoreNetworkInterface方法处理不了网卡名包含圆括号的环境

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#8581]
### Environment

* Dubbo version: 2.7.13

### Steps to reproduce this issue
NetUtils.ignoreNetworkInterface方法使用matches判断是否是要忽略的网卡，
当网卡名称包含圆括号时，如INTEL(R) XXX
即使完全相同，结果也是false： ”INTEL(R) XXX".matches("INTEL(R) XXX" 结果为false！

比较了3.0的代码，该方法已经删除了DUBBO_NETWORK_IGNORED_INTERFACE相关的处理，建议2.7系列做一下同步修订。

**Comment by zrlw** [comment]
实际上不止圆括号，网卡名称包含其他正则表达式元字符时，这条语句也会失败的。

**Comment by BazookaW** [comment]
@zrlw 请问`DUBBO_NETWORK_IGNORED_INTERFACE = "dubbo.network.interface.ignored"`这个参数你是在哪里设置的呢？

> NetUtils.ignoreNetworkInterface方法使用matches判断是否是要忽略的网卡，当网卡名称包含圆括号时，如INTEL(R) XXX
> 即使完全相同，结果也是false： ”INTEL(R) XXX".matches("INTEL(R) XXX" 结果为false！

![image](https://user-images.githubusercontent.com/17539174/130558080-46d99e38-9710-4431-b66d-4d70e041617a.png)
我验证了一下，确实是返回false

**Comment by zrlw** [comment]
```
String ignoredInterfaces = “Intel(R) wireless XXX";
System.setProperty(DUBBO_NETWORK_IGNORED_INTERFACE,ignoredInterfaces);
```
详细可参考NetUtilsTest.java测试类里的testIgnoreGivenPrefixInterfaceName方法。
PS:
可能dubbo不止这一处缺陷，无线网卡物理名称里面通常都有个(R)，在windows下控制面板把其他网卡全disable掉，只留下一个物理名称带(R)的无线网卡，然后跑dubbo整个工程的mvn clean install，不止dubbo-common工程单元测试过不去的。

**Comment by BazookaW** [comment]
@AlbumenJ 我看3.0分支没有ignore network Interface的代码了，请问是出于什么考虑呢？

**Comment by zrlw** [comment]
> 这个问题是不是给 dubbo.network.interface.ignored 加一下转义就好了

dubbo.network.interface.ignored这个配置内容需要用户自己去做转义，只有用户清楚里面的哪些特殊字符需要做转义处理，哪些不需要转。
dubbo可以做的是在配置指南上指出如果需要屏蔽的网卡名称里面包含特殊字符，则在不需要转义的内容前后加上\Q和\E就好了就像Pattern.quote方法做的那样，比如过滤掉Intel(R)开头的所有网卡，那么用户就需要配置为```\QIntel(R)\E.*``` 或者 ```Intel\Q(R\E).*```，或者反斜杠转义这种： ```Intel\\(R\\).*```

**Comment by zrlw** [comment]
考虑再三还是在提交的PR里还加进去了全等比较条件，作为正则匹配的补充。
配置dubbo.network.interface.ignored参数时，还要查一下配置的网卡名称里面有没有需要转义的元字符，可能这个要求对于大多数人而言都有点离谱了。

**Comment by zrlw** [comment]
debug测试发现网卡名包含某些元字符时，matches直接抛异常，需要做一下捕获处理。
顺便修订了一下原来测试案例的一处手误（匹配所有应该用```.*```，不能省略```.```字符），新增了一个网卡名称包含常见元字符的测试案例。
