### ISSUE TITLE
how to inject  dubbo reference  to spring boot autoconfiguratoin (如何在spring boot autoconfiguration 中注入 dubbo 服务)

### ISSUE THREAD

**Issue by youngerier** [apache/dubbo#8595]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: win10
* Java version: jdk1.8

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/10486543/130786861-6bf05aee-ed00-44f1-84d9-31b4bd43497f.png)
 
注入的服务为null 没能注入成功
Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

能够注入dubbo服务

### Actual Result

 注入的服务为null

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
