### ISSUE TITLE
Provider server restart with new Serialization config can not pass to consumer

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo#8596]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: Win10
* Java version: java 8

### Steps to reproduce this issue

1. start serve with serialization  "hessian2"
2. use client to invoke service 
3. restart service with serialization  "native-hessian"
4. use client to invoke service 

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

the second service invoke will through serialization `native-hessian`.

### Actual Result

the second service invoke will through serialization `hessian2`.  
when I use an serialization type which depeancy on specific POJO. such as buidler mode in protobuf or
some pojo without Serializable interface. Serailzation will failed.

[someTestLinke](https://github.com/vio-lin/dubbo-samples/tree/master)
1.  start  `org.apache.dubbo.samples.serialization.DubboProvider`
2.  use client to invoke `org.apache.dubbo.samples.serialization.DubboConsumer`
3.  edit serialization in provider.xm `src/main/resources/spring/dubbo-demo-provider.xml`
4.  restarted `org.apache.dubbo.samples.serialization.DubboProvider`
5.  use client to invoke `org.apache.dubbo.samples.serialization.DubboConsumer`
6.  see log in consumer console. which log the current used serialization

**Comment by CrazyHZM** [comment]
Temporarily close this issue, if you still have problems upgrading to the latest version, you can reopen this issue.
