### ISSUE TITLE
Packet len is out of range when starting

### ISSUE THREAD

**Issue by szd1993** [apache/dubbo#8622]
when consumer starting , it will get all dubbo node from zookeeper, then "Packet len is out of range"

why not only get  node that with @DubboReference 

just for less request ? 

```java
    void readLength() throws IOException {
        int len = this.incomingBuffer.getInt();
        if (len >= 0 && len < this.packetLen) {
            this.incomingBuffer = ByteBuffer.allocate(len);
        } else {
            throw new IOException("Packet len" + len + " is out of range!");
        }
    }
```

### Environment

* Dubbo version:  2.7.8
* Operating System version: xxx
* Java version: 8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by xiaoheng1** [comment]
There are two solutions:
1. You can increase the jute.maxbuffe parameter and try it
2. Use application-level service registration and discovery

**Comment by CrazyHZM** [comment]
@szd1993 You can refer to the above answer, temporarily close the issues, if there are other issues, you can reopen the issues.
