### ISSUE TITLE
建议增加MetadataReportConfig的client属性，使用application.yml配置DUBBO属性时无法自定义metadataReport的client

### ISSUE THREAD

**Issue by LnManch** [apache/dubbo#8627]
按照yml文件定义写成
dubbo:
  metadata-report:
    parameters:
      client: XXXX
也无法通过MAP的定义注入进去

**Comment by fangliji** [comment]
i will fixed it

**Comment by horizonzy** [comment]
Hi, which version do you use? I found that MetadataReportConfig can support custom parameters.

**Comment by fangliji** [comment]
![image](https://user-images.githubusercontent.com/86839680/132099154-c43538f4-e9f4-4191-99cf-b696e3b4dda7.png)
 之前确实有这个问题，最新的版本已经修复了，你拉下来再看看，我之前也是用的老版本，确实有问题，更新了，确实阔以了

**Comment by fangliji** [comment]
@LnManch
