### ISSUE TITLE
dubbo2.84版本 aop代理无效

### ISSUE THREAD

**Issue by hylyLLL** [apache/dubbo#8634]
IOrderService与IGoodServicee形成循环依赖，dubbo在生成对象时
![image](https://user-images.githubusercontent.com/46893979/131244779-50e1caa4-2cf7-4668-83dc-f55689f03744.png)
![image](https://user-images.githubusercontent.com/46893979/131244697-e75068a0-a972-4b99-adb9-3ce12e2b13b7.png)
为什么一个能够生成代理切面对象，一个不能呢，有什么方式能够让IGoodService把带有AOP增强的代理提前暴露出去呢？

**Comment by RuoBingCoder** [comment]
你能描述清楚你的问题吗？我的理解是例如：你的两个service加了事务spring对这两个接口生成代理，而Dubbo的注入是通过对ServiceBean构造器注入接口实例，这是spring所管理的就算循环依赖也都会注入proxy！你看看你的哪块配置出了问题！

**Comment by hylyLLL** [comment]
***@***.***注解去解决，也不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月30日(星期一) 下午2:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] dubbo2.84版本 aop代理无效 (#8634)





 
你能描述清楚你的问题吗？我的理解是例如：你的两个service加了事务spring对这两个接口生成代理，而Dubbo的注入是通过对ServiceBean构造器注入接口实例，这是spring所管理的就算循环依赖也都会注入proxy！你看看你的哪块配置出了问题！
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlbumenJ** [comment]
Apache Dubbo 没有发布 2.8.4 版本，第三方版本这里不进行处理

**Comment by hylyLLL** [comment]
抱歉，我这里版本是以前alibaba的版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Albumen ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dubbo] dubbo2.84版本 aop代理无效 (#8634)





 
Apache Dubbo 没有发布 2.8.4 版本，第三方版本这里不进行处理
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
