### ISSUE TITLE
3.0 为什么要删除etcd相关的注册

### ISSUE THREAD

**Issue by xiaokunliu** [apache/dubbo#8647]
3.0要如何兼容etcd3的注册,需要自己实现SPI么

**Comment by xiaoheng1** [comment]
这个会移到 dubbo-spi-extensions 仓库中

see https://github.com/apache/dubbo/issues/7784

**Comment by CrazyHZM** [comment]
See the project for the extension of etcd.
https://github.com/apache/dubbo-spi-extensions
