### ISSUE TITLE
Some questions about service.

### ISSUE THREAD

**Issue by KevinClair** [apache/dubbo#8656]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: Windows 10
* Java version: 1.8

### Steps to reproduce this issue
Hello guys, I have some question about dubbo when i use it.

How can I get the list of all providers when I use generic service in dubbo and how can I perceive when a provider goes online or offline.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by 24kpure** [comment]
You can have a clear view of all providers in Dubbo admin. Provider will remove it's info that consumers subscribe  registry when it go offline,so does offline.  How about  taking a look at architecture description like this?
![image](https://user-images.githubusercontent.com/14272651/131978741-aae6b716-8f84-43ee-8da7-6044eaeecd88.png)

**Comment by KevinClair** [comment]
> You can have a clear view of all providers in Dubbo admin. Provider will remove it's info that consumers subscribe registry when it go offline,so does offline. How about taking a look at architecture description like this?
> ![image](https://user-images.githubusercontent.com/14272651/131978741-aae6b716-8f84-43ee-8da7-6044eaeecd88.png)

Thanks for your reply,but i wanna know the way to get it.Not by `admin`.

**Comment by 24kpure** [comment]
Just read info from registry. For instance , the default path is /dubbo in zk.

**Comment by KevinClair** [comment]
If i user nacos or other registery,can it work too?

**Comment by 24kpure** [comment]
Of course,it's a duty of the registry.
