### ISSUE TITLE
[3.0-Triple] TripleRpcException should be removed and support dubbo status to triple status mapping

### ISSUE THREAD

**Issue by guohao** [apache/dubbo#8659]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

Dubbo's `RpcException` contains a `code` field and it is enough for exceptions occured in invocation chain. Therefore is no need to add complexity for user coding and framework processing.

What we need to do:
1.  Replace `TripleRpcException` with `RpcException`
2. Add dubbo code to grpc status mapping in `org.apache.dubbo.rpc.protocol.tri.GrpcStatus`
3. Add UT for above modifications.

**Comment by dockerXieShouYu** [comment]
> * [x]  I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
> * [x]  I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.
> 
> Dubbo's `RpcException` contains a `code` field and it is enough for exceptions occured in invocation chain. Therefore is no need to add complexity for user coding and framework processing.
> 
> What we need to do:
> 
> 1. Replace `TripleRpcException` with `RpcException`
> 2. Add dubbo code to grpc status mapping in `org.apache.dubbo.rpc.protocol.tri.GrpcStatus`
> 3. Add UT for above modifications.

I will finish this task
