### ISSUE TITLE
[3.0]  The problem collection of Triple with ApplicationDiscovery

### ISSUE THREAD

**Issue by plusmancn** [apache/dubbo#8666]
We have found these issues which are related to Triple with ApplicationDiscovery:
- [x] https://github.com/apache/dubbo/issues/8599
- [x] https://github.com/apache/dubbo/issues/8462
- [x] https://github.com/apache/dubbo/issues/8657
- [x] https://github.com/apache/dubbo/issues/8696

What we should do  for further popularization: 
- [x] Complete the docs: [Triple协议迁移指南](https://dubbo.apache.org/zh/docs/migration/migration-triple/) as soon as possible
- [x] The logic of preferredProtocol was not user-friendly, we maybe should optimize it.
- [x] #9229
- [x] Give a demo about SpringBoot integrate with Dubbo 3.0 which cover ApplicationDiscovery, Triple Protocol

**Comment by guohao** [comment]
Agreed on triple doc construction, I will start this task ASAP

**Comment by EarthChen** [comment]
I will also assist in these tasks

**Comment by plusmancn** [comment]
## The logic of preferredProtocol was not user-friendly, we maybe should optimize it.

### What's the problem?
When we only use the `triple` protocol in dubbo with setting provider's register-mode as `instance`, the consumer can't find the service.


The source is in `org.apache.dubbo.config.metadata.ServiceInstanceHostPortCustomizer`, let's have a look:


```java
@Override
public void customize(ServiceInstance serviceInstance) {
    String host = null;
    int port = -1;
    // ......
    Set<URL> urls = writableMetadataService.getExportedServiceURLs();
    if (CollectionUtils.isNotEmpty(urls)) {
        ApplicationModel applicationModel = serviceInstance.getApplicationModel();
        String preferredProtocol = applicationModel.getCurrentConfig().getProtocol();
        //  The default value of preferredProtocol is dubbo.
        if (preferredProtocol != null) {
            for (URL exportedURL : urls) {
                // The protocol of exportedURL is tri
                // because of tri != dubbo, the host and port will not be assigned values.
                if (preferredProtocol.equals(exportedURL.getProtocol())) {
                    host = exportedURL.getHost();
                    port = exportedURL.getPort();
                    break;
                }
            }
        } else {
            URL url = urls.iterator().next();
            host = url.getHost();
            port = url.getPort();
        }
        // If not the port of instace > 0, the application instance will not be registered to RegistryCenter(like Nacos, Zookeeper).
        // As a result, the consumer can't find the avaliabe providers when our settging is registry-mode=instance
        if (serviceInstance instanceof DefaultServiceInstance) {
            DefaultServiceInstance instance = (DefaultServiceInstance) serviceInstance;
            instance.setHost(host);
            instance.setPort(port);
        }
    }
}
```


For the moment, if you want both consumer and provider to force using `Application Discovery` in tri protocol, just change one line config of provider as follows:


```yaml
dubbo:
  application:
    metadata-type: remote
    register-mode: instance
    protocol: tri  <==== HERE, set preferredProtocol as tri
```




### The possible solution
change the default `application-protocol` as `TRIPLE` in the future
> Why not now? Because most users are still trying to migrate from 2.0 to 3.0

```java
// => org.apache.dubbo.config.ApplicationConfig#checkDefault
protected void checkDefault() {
    super.checkDefault();
    if (protocol == null) {
        protocol = DUBBO;   // <======= HERE
    }
    // ......
}
```
In `ServiceInstanceHostPortCustomizer`, If the default protocol not exists, just try to get the first protocol and log an error log.

**Comment by guohao** [comment]
Doc of migration to triple is constructing in https://github.com/apache/dubbo-website/pull/941/files
