### ISSUE TITLE
注解方式如何定义负载方式

### ISSUE THREAD

**Issue by ywzou** [apache/dubbo#8672]
@DubboService(methods = { @Method(name = "bind1thCardNew", loadbalance = "consistenthash") })
只用注解的方式如何正对某个方法定义参数位置和节点 hash.nodes  hash.arguments
只能定义在类这一级别吗？

**Comment by 24kpure** [comment]
`org.apache.dubbo.config.annotation.DubboService#parameters`  works
```
@DubboService(methods = { @method(name = "bind1thCardNew", loadbalance = "consistenthash") },parameters = {"bind1thCardNew.hash.arguments", "0"})
```
