### ISSUE TITLE
   服务注册时，动态追加参数

### ISSUE THREAD

**Issue by neocrm** [apache/dubbo#8678]
同一个服务提供者；向zk注册三个实例；怎么在每个实例的URL中追加一个参数；便于后续区分三个实例，路由；
例如，服务提供者统一用如下xml暴露服务：
<dubbo:service interface="com.lance.service.HelloService" ref="helloService"/>

那我想在zk上得到三个实例：
dubbo：//host:port/xxx?param=1
dubbo：//host:port/xxx?param=2
dubbo：//host:port/xxx?param=3
这个怎么实现？

**Comment by zrlw** [comment]
区分provider可以设置version、group或者tag，
可能tag最适合你，provider静态设置tag，consumer动态设置tag调用不同的provider

**Comment by neocrm** [comment]
> 区分provider可以设置version、group或者tag，
> 可能tag最适合你，provider静态设置tag，consumer动态设置tag调用不同的provider

我理解你说的version，group，或者tag，都是 provider.xml 里面的一些静态的配置项；
那么三个实例用的是同一份xml配置；那么它们注册的服务，group，version，tag都是一样的；就起不到区分的作用了；

**Comment by AlbumenJ** [comment]
目前原生不支持这样的行为，可以用 placeholder 的方式进行注入

**Comment by CrazyHZM** [comment]
I don’t know if the above answers can solve your problem, please close the issue temporarily, if you have other questions, you can reopen the issue.
