### ISSUE TITLE
官方人员帮忙看一下啊mvn install -Dmaven.test.skip=true安装3.0.3-snapshot版本出现异常

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8688]
[INFO] Building protoc plugin: dubbo
Downloading from mynexus: http://localhost:8081/repository/maven-group/org/apache/dubbo/dubbo-compiler/0.0.3-SNAPSHOT/maven-metadata.xml
Downloading from mynexus: http://localhost:8081/repository/maven-group/org/apache/dubbo/dubbo-compiler/0.0.3-SNAPSHOT/dubbo-compiler-0.0.3-SNAPSHOT.pom
[WARNING] Missing POM for org.apache.dubbo:dubbo-compiler:jar:0.0.3-SNAPSHOT
Downloading from mynexus: http://localhost:8081/repository/maven-group/org/apache/dubbo/dubbo-compiler/0.0.3-SNAPSHOT/dubbo-compiler-0.0.3-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] dubbo-build-tools 1.0.0 ............................ SUCCESS [  1.303 s]
[INFO] dubbo-parent 3.0.3-SNAPSHOT ........................ SUCCESS [  2.089 s]
[INFO] dubbo-common 3.0.3-SNAPSHOT ........................ SUCCESS [  9.053 s]
[INFO] dubbo-container 3.0.3-SNAPSHOT ..................... SUCCESS [  0.454 s]
[INFO] dubbo-container-api 3.0.3-SNAPSHOT ................. SUCCESS [  2.730 s]
[INFO] dubbo-container-spring 3.0.3-SNAPSHOT .............. SUCCESS [  2.743 s]
[INFO] dubbo-serialization 3.0.3-SNAPSHOT ................. SUCCESS [  0.458 s]
[INFO] dubbo-serialization-api 3.0.3-SNAPSHOT ............. SUCCESS [  2.707 s]
[INFO] dubbo-serialization-hessian2 3.0.3-SNAPSHOT ........ SUCCESS [  2.672 s]
[INFO] dubbo-remoting 3.0.3-SNAPSHOT ...................... SUCCESS [  0.455 s]
[INFO] dubbo-remoting-api 3.0.3-SNAPSHOT .................. SUCCESS [  3.201 s]
[INFO] dubbo-remoting-http 3.0.3-SNAPSHOT ................. SUCCESS [  2.861 s]
[INFO] dubbo-remoting-netty 3.0.3-SNAPSHOT ................ SUCCESS [  2.703 s]
[INFO] dubbo-remoting-zookeeper 3.0.3-SNAPSHOT ............ SUCCESS [  2.752 s]
[INFO] dubbo-remoting-zookeeper-curator5 3.0.3-SNAPSHOT ... SUCCESS [  2.955 s]
[INFO] dubbo-remoting-netty4 3.0.3-SNAPSHOT ............... SUCCESS [  2.682 s]
[INFO] dubbo-rpc 3.0.3-SNAPSHOT ........................... SUCCESS [  0.398 s]
[INFO] dubbo-rpc-api 3.0.3-SNAPSHOT ....................... SUCCESS [  5.946 s]
[INFO] dubbo-cluster 3.0.3-SNAPSHOT ....................... SUCCESS [  3.516 s]
[INFO] dubbo-serialization-jdk 3.0.3-SNAPSHOT ............. SUCCESS [  2.739 s]
[INFO] dubbo-rpc-dubbo 3.0.3-SNAPSHOT ..................... SUCCESS [  2.794 s]
[INFO] dubbo-rpc-injvm 3.0.3-SNAPSHOT ..................... SUCCESS [  2.703 s]
[INFO] dubbo-rpc-rest 3.0.3-SNAPSHOT ...................... SUCCESS [  3.306 s]
[INFO] dubbo-rpc-grpc 3.0.3-SNAPSHOT ...................... SUCCESS [  4.196 s]
[INFO] dubbo-rpc-triple 3.0.3-SNAPSHOT .................... FAILURE [  0.945 s]
[INFO] dubbo-configcenter 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-configcenter-zookeeper 3.0.3-SNAPSHOT ........ SKIPPED
[INFO] dubbo-metadata 3.0.3-SNAPSHOT ...................... SKIPPED
[INFO] dubbo-metadata-api 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-registry 3.0.3-SNAPSHOT ...................... SKIPPED
[INFO] dubbo-registry-api 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-registry-multicast 3.0.3-SNAPSHOT ............ SKIPPED
[INFO] dubbo-registry-zookeeper 3.0.3-SNAPSHOT ............ SKIPPED
[INFO] dubbo-registry-nacos 3.0.3-SNAPSHOT ................ SKIPPED
[INFO] dubbo-registry-multiple 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-registry-kubernetes 3.0.3-SNAPSHOT ........... SKIPPED
[INFO] dubbo-monitor 3.0.3-SNAPSHOT ....................... SKIPPED
[INFO] dubbo-monitor-api 3.0.3-SNAPSHOT ................... SKIPPED
[INFO] dubbo-metadata-report-zookeeper 3.0.3-SNAPSHOT ..... SKIPPED
[INFO] dubbo-metadata-report-redis 3.0.3-SNAPSHOT ......... SKIPPED
[INFO] dubbo-configcenter-nacos 3.0.3-SNAPSHOT ............ SKIPPED
[INFO] dubbo-filter 3.0.3-SNAPSHOT ........................ SKIPPED
[INFO] dubbo-filter-cache 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-filter-validation 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-config 3.0.3-SNAPSHOT ........................ SKIPPED
[INFO] dubbo-config-api 3.0.3-SNAPSHOT .................... SKIPPED
[INFO] dubbo-registry-dns 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-registry-xds 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-monitor-default 3.0.3-SNAPSHOT ............... SKIPPED
[INFO] dubbo-config-spring 3.0.3-SNAPSHOT ................. SKIPPED
[INFO] dubbo-demo 3.0.3-SNAPSHOT .......................... SKIPPED
[INFO] dubbo-demo-interface 3.0.3-SNAPSHOT ................ SKIPPED
[INFO] dubbo-metadata-report-nacos 3.0.3-SNAPSHOT ......... SKIPPED
[INFO] dubbo-demo-xml 3.0.3-SNAPSHOT ...................... SKIPPED
[INFO] dubbo-demo-xml-provider 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-demo-xml-consumer 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-demo-annotation 3.0.3-SNAPSHOT ............... SKIPPED
[INFO] dubbo-demo-annotation-provider 3.0.3-SNAPSHOT ...... SKIPPED
[INFO] dubbo-demo-annotation-consumer 3.0.3-SNAPSHOT ...... SKIPPED
[INFO] dubbo-demo-api 3.0.3-SNAPSHOT ...................... SKIPPED
[INFO] dubbo-demo-api-provider 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-demo-api-consumer 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-demo-generic-call 3.0.3-SNAPSHOT ............. SKIPPED
[INFO] dubbo-demo-triple 3.0.3-SNAPSHOT ................... SKIPPED
[INFO] dubbo-demo-native 3.0.3-SNAPSHOT ................... SKIPPED
[INFO] dubbo-demo-native-interface 3.0.3-SNAPSHOT ......... SKIPPED
[INFO] dubbo-native 3.0.3-SNAPSHOT ........................ SKIPPED
[INFO] dubbo-demo-native-consumer 3.0.3-SNAPSHOT .......... SKIPPED
[INFO] dubbo-demo-native-provider 3.0.3-SNAPSHOT .......... SKIPPED
[INFO] dubbo-plugin 3.0.3-SNAPSHOT ........................ SKIPPED
[INFO] dubbo-qos 3.0.3-SNAPSHOT ........................... SKIPPED
[INFO] dubbo-auth 3.0.3-SNAPSHOT .......................... SKIPPED
[INFO] dubbo-compatible 3.0.3-SNAPSHOT .................... SKIPPED
[INFO] dubbo-dependencies-bom 3.0.3-SNAPSHOT .............. SKIPPED
[INFO] dubbo-configcenter-apollo 3.0.3-SNAPSHOT ........... SKIPPED
[INFO] dubbo 3.0.3-SNAPSHOT ............................... SKIPPED
[INFO] dubbo-bom 3.0.3-SNAPSHOT ........................... SKIPPED
[INFO] dubbo-distribution 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-dependencies-zookeeper 3.0.3-SNAPSHOT ........ SKIPPED
[INFO] dubbo-dependencies 3.0.3-SNAPSHOT .................. SKIPPED
[INFO] dubbo-metadata-definition-protobuf 3.0.3-SNAPSHOT .. SKIPPED
[INFO] dubbo-metadata-processor 3.0.3-SNAPSHOT ............ SKIPPED
[INFO] dubbo-spring-boot 3.0.3-SNAPSHOT ................... SKIPPED
[INFO] dubbo-spring-boot-compatible 3.0.3-SNAPSHOT ........ SKIPPED
[INFO] dubbo-spring-boot-autoconfigure-compatible 3.0.3-SNAPSHOT SKIPPED
[INFO] dubbo-spring-boot-actuator-compatible 3.0.3-SNAPSHOT SKIPPED
[INFO] dubbo-spring-boot-autoconfigure 3.0.3-SNAPSHOT ..... SKIPPED
[INFO] dubbo-spring-boot-actuator 3.0.3-SNAPSHOT .......... SKIPPED
[INFO] dubbo-spring-boot-starter 3.0.3-SNAPSHOT ........... SKIPPED
[INFO] dubbo-test 3.0.3-SNAPSHOT .......................... SKIPPED
[INFO] dubbo-test-common 3.0.3-SNAPSHOT ................... SKIPPED
[INFO] dubbo-test-spring 3.0.3-SNAPSHOT ................... SKIPPED
[INFO] dubbo-test-spring3.2 3.0.3-SNAPSHOT ................ SKIPPED
[INFO] dubbo-test-spring4.1 3.0.3-SNAPSHOT ................ SKIPPED
[INFO] dubbo-test-spring4.2 3.0.3-SNAPSHOT ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:11 min
[INFO] Finished at: 2021-09-06T11:14:58+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile (default) on project dubbo-rpc-triple: Unable to resolve plugin artifact: Missing:
[ERROR] ----------
[ERROR] 1) org.apache.dubbo:dubbo-compiler:jar:0.0.3-SNAPSHOT
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=org.apache.dubbo -DartifactId=dubbo-compiler -Dversion=0.0.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=org.apache.dubbo -DartifactId=dubbo-compiler -Dversion=0.0.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]         1) org.apache.dubbo:dubbo-rpc-triple:jar:3.0.3-SNAPSHOT
[ERROR]         2) org.apache.dubbo:dubbo-compiler:jar:0.0.3-SNAPSHOT
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR]   org.apache.dubbo:dubbo-rpc-triple:jar:3.0.3-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   mynexus (http://localhost:8081/repository/maven-group/, releases=true, snapshots=true)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :dubbo-rpc-triple

**Comment by startjava** [comment]
我应该如何做才能install正常，最好官方改一下相关内容，不要让我们dubbo使用者改东西，感谢哈。

**Comment by zrlw** [comment]
dubbo-compiler这个需要你先自己mvn install，社区正在对dubbo3.0做重构，文档可能会脱节一段时间

**Comment by guohao** [comment]
This issue should have be resovled with https://github.com/apache/dubbo/pull/8687
