### ISSUE TITLE
如何在https://github.com/apache中找到dubbo+springboot的pom.xml配置标准代码啊？

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8696]
百度上面的一个BLOG一个样

想找官方标准的，

而https://github.com/apache/dubbo-spring-boot-project项目又废弃了，我在https://github.com/apache中没有找到。

求助！

**Comment by startjava** [comment]
我现在的parent项目使用：
```
    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Apache Dubbo  -->
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-dependencies-bom</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>

        <!-- Dubbo Spring Boot Starter -->
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo.version}</version>
        </dependency>
    </dependencies>
```

子模块使用：
```
    <parent>
        <artifactId>my-parent</artifactId>
        <groupId>com.ghy.www</groupId>
        <version>1.0-RELEASE</version>
        <relativePath>../my-parent/pom.xml</relativePath>
    </parent>

    <dependencies>
        <!-- Spring Boot dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>${dubbo.version}</version>
        </dependency>

        <!-- Zookeeper dependencies -->
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-dependencies-zookeeper</artifactId>
            <version>${dubbo.version}</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>com.ghy.www</groupId>
            <artifactId>my-api</artifactId>
            <version>1.0-RELEASE</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
```

我这种写法不知道是不是最佳实践。有什么需要改进的地方。

**Comment by felayman** [comment]
可以参考dubbo官方提供的工程样例，https://github.com/apache/dubbo-samples

**Comment by plusmancn** [comment]
@plusmancn mark

**Comment by wangchengming666** [comment]
兄弟这个可能是你需要的 https://github.com/apache/dubbo-spring-boot-project

**Comment by plusmancn** [comment]
> 兄弟这个可能是你需要的 https://github.com/apache/dubbo-spring-boot-project

@wangchengming666  This project is deprecated.

**Comment by startjava** [comment]
是的，这个项目 已经作废了 ，官方没有基于spring-boot的最新版dubbo3.0.3依赖pom.xml配置标准模板代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月7日(星期二) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dubbo] 如何在https://github.com/apache中找到dubbo+springboot的pom.xml配置标准代码啊？ (#8696)





  
兄弟这个可能是你需要的 https://github.com/apache/dubbo-spring-boot-project
  
@wangchengming666  This project is deprecated.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by plusmancn** [comment]
@startjava We have planned to provide a `starter-template` for spring-boot, you can track the progress in  issue #8666

**Comment by startjava** [comment]
@plusmancn 我还是没有找到模板代码，在8666中，如何找到呢。感谢。

**Comment by CrazyHZM** [comment]
https://github.com/apache/dubbo-spring-boot-project 
This project has been migrated to the current dubbo warehouse. The posture is the same as the previous posture. The version can depend on the version of dubbo, such as the latest 3.0.2.1.
`        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <version>3.0.2.1</version>
        </dependency>`
