### ISSUE TITLE
FAIL_OVER和FAIL_BACK 区别

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8710]
有没有大佬介绍一下DUBBO中FAIL_OVER和FAIL_BACK 区别

就是在运行效率上的区别，而不是单纯文字上的，百度搜了一些，没有一个说的比较具体的。

感谢

**Comment by dkisser** [comment]
`/**
 * When invoke fails, log the initial error and retry other invokers (retry n times, which means at most n different invokers will be invoked)
 * Note that retry causes latency.
 * <p>
 * <a href="http://en.wikipedia.org/wiki/Failover">Failover</a>
 *
 */
public class FailoverClusterInvoker<T> extends AbstractClusterInvoker<T> {
......
`
`/**
 * When fails, record failure requests and schedule for retry on a regular interval.
 * Especially useful for services of notification.
 *
 * <a href="http://en.wikipedia.org/wiki/Failback">Failback</a>
 */
public class FailbackClusterInvoker<T> extends AbstractClusterInvoker<T> {
......
`

**Comment by wangchengming666** [comment]
FAIL_OVER我的理解是，当我们的应用是集群模式，请求当出现失败的时候，会尝试集群中其他节点。用户可以通过retries="2"设置重试次数。这是Dubbo的默认容错机制，会对请求做负载均衡。通常使用在读操作或者幂等性写操作上，但是重试操作会导致接口的延迟增大，在下游机器负载已经到达极限的情况下，重试会增加下游机器的负载。

FAIL_BACK我的理解是请求失败之后，会自动记录失败的请求，并由RetryTimerTask定时重试，适用一些异步或者最终以执行的请求，官方也在javaDoc中写道：Especially useful for services of notification.适合消息通知的场景

**Comment by changfubai** [comment]
原来这里还有一场讨论啊  哈哈

**Comment by CrazyHZM** [comment]
@startjava 
Does the above answer answer you? I will temporarily close the issues, if you still have any questions, you can reopen it.
