### ISSUE TITLE
[3.0-compiler] Consider separating the Protobuf utils from the compiler plug-in

### ISSUE THREAD

**Issue by EarthChen** [apache/dubbo#8727]
## Background

Dubbo-Compiler currently init some data when generating apis using proto files (Protobuf objects registered in the serialization utility class to speed up subsequent serialization)

- 0.0.2 depend `dubbo-serialization-protobuf`
- 0.0.3+  depend `dubbo`

## The problem

If the path of these utility classes changes in the future, it will cause problems with the dependency of services that rely on API modules

## opinion

Separate utility classes from API modules

## plan

I came up with two solutions to this problem。

### plan1

Spi is used to separate the serialization utility classes, but the problem is that the TRI protocol relies heavily on the Protobuf utility class

### plan2

Compiled plug-ins do not rely on utility classes and simply provide a way to expose protobuf objects, delaying registration logic processing.

Which brings up another question, how late is the delay？

I think it falls into two categories：
- Any time before the RPC send
- In the process of RPC (Register whenever serialization is required)

**Comment by guohao** [comment]
Great, hope to see soon !

**Comment by EarthChen** [comment]
Close by https://github.com/apache/dubbo/pull/9853
