### ISSUE TITLE
[3.0] Attachment is lost when calling  without registry 

### ISSUE THREAD

**Issue by EarthChen** [apache/dubbo#8738]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.3-SNAPSHOT
* Operating System version: macos
* Java version: 1.8

#### code

1. server
```java
 @Override
    public GreeterReply greetWithAttachment(GreeterRequest request) {
        final String key = "user-attachment";
        final String value = RpcContext.getServerAttachment().getAttachment(key);
        RpcContext.getServerContext().setObjectAttachment(key, value);
        return GreeterReply.newBuilder().setMessage("hello," + request.getName()).build();
    }
```

2. client
```java
@Test
public void attachmentTest() {
    final String key = "user-attachment";
    final String value = "attachment-value";
    RpcContext.removeClientAttachment();
    RpcContext.getClientAttachment().setAttachment(key, value);
    GreeterReply reply = delegate.greetWithAttachment(GreeterRequest.newBuilder().setName("meta").build());
    Assert.assertEquals("hello,meta",reply.getMessage());
    final String returned = (String) RpcContext.getServerContext().getObjectAttachment(key);
    Assert.assertEquals("hello," + value, returned);
}
```

#### steps

1. start provider
2. start consumer with Url directly connect
3. start consumer with zk registry

Pls. provide [GitHub address] to reproduce this issue.

https://github.com/apache/dubbo-samples/pull/356

### Expected Result

consumer test is ok

### Actual Result

The consumer test using the URL direct connection failed.

The consumer test using Zookeper success.

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by icankeep** [comment]
![image](https://user-images.githubusercontent.com/39434627/132783707-45ba27b1-0c93-4025-9438-bd60dc4bb7d0.png)


@AlbumenJ  这两段代码有些矛盾，3.0将RpcContext分成ServerContext、ServerAttachment、ClientAttachment、ServiceContext，有点不太清楚他们分别的应用场景，ServerAttachment和ServerContext的差异是？ServiceContext的定位是？看代码注解没太看明白，大佬有空帮忙解答下

**Comment by EarthChen** [comment]
> ![image](https://user-images.githubusercontent.com/39434627/132783707-45ba27b1-0c93-4025-9438-bd60dc4bb7d0.png)
> 
> @AlbumenJ 这两段代码有些矛盾，finally已经将context清空了，onResponse再设置也没啥意义
> 
> 3.0将RpcContext分成ServerContext、ServerAttachment、ClientAttachment、ServiceContext，有点不太清楚他们分别的应用场景，ServerAttachment和ServerContext的差异是？ServiceContext的定位是？看代码注解没太看明白，大佬有空帮忙解答下

可能是我的环境问题，后来的测试场景都是直连不能放入ServerContext

原因是 filter 变为了 clusterfilter 而当使用 url 直连的时候 StaticDirectory会直接跳过 clusterfilter 的链的包装，如果只有一个 url ，都不会包装成 clusterinvoker

**Comment by EarthChen** [comment]
> ![image](https://user-images.githubusercontent.com/39434627/132783707-45ba27b1-0c93-4025-9438-bd60dc4bb7d0.png)
> 
> @AlbumenJ 这两段代码有些矛盾，finally已经将context清空了，onResponse再设置也没啥意义
> 
> 3.0将RpcContext分成ServerContext、ServerAttachment、ClientAttachment、ServiceContext，有点不太清楚他们分别的应用场景，ServerAttachment和ServerContext的差异是？ServiceContext的定位是？看代码注解没太看明白，大佬有空帮忙解答下

consumer 端需要看ConsumerContextFilter  
provider 端是 ContextFilter

**Comment by fengcunhan** [comment]
你使用错了API，如果要获取服务器端带来的参数，应该使用RpcContext.getServerContext()

`public void attachmentTest() {
        final String key = "user-attachment";
        final String value = "attachment-value";
        RpcContext.removeClientAttachment();
        RpcContext.getClientAttachment().setAttachment(key, value);
        delegate.greetWithAttachment(GreeterRequest.newBuilder().setName("meta").build());
        final String returned = (String) RpcContext.**getServerContext**().getObjectAttachment(key);
        Assert.assertEquals(value, returned);
    }`

**Comment by fengcunhan** [comment]
如果要看Triple协议下的结果如何传递给client端的，client端如何解析，可以查看代码：
 org.apache.dubbo.rpc.protocol.tri.UnaryServerStream.invoke()方法，在方法里面会执行方法 final Result result = getInvoker().invoke(invocation); 调用，拿到结果以后，先传递CONTENT_TYPE，然后data，最后结束帧传递attachments。

client解析部分可以看：org.apache.dubbo.rpc.protocol.tri.AbstractStream.AbstractTransportObserver.onMetadata()方法，这部分恰好对应上述服务器端传输部分

**Comment by EarthChen** [comment]
tri协议部分已经拿到了attach  。
问题在consumercontextfilter。。
