### ISSUE TITLE
Spring 5.2.8 +Dubbo 3.0 如何使用 Nacos 2.0 作为配置中心？

### ISSUE THREAD

**Issue by momoco530** [apache/dubbo#8740]
从 Dubbo 2.6 升级到 3.0，之前采用大量 xml 形式配置，其中包含 MySQL 连接配置、自定义 Listener、MyBatis 映射之类的
现改成 Nacos 作为配置中心，大部分都是采用 SpringBoot +Dubbo 形式的，有没有仅使用 Spring +Dubbo 的配置示例??

**Comment by EarthChen** [comment]
You can get some help with this module

**Comment by threeMonthee** [comment]
我正在用springboot 4.6.2+dubbo3+nacos2.0.2
