### ISSUE TITLE
About specifying the invoker to call the provider

### ISSUE THREAD

**Issue by KevinClair** [apache/dubbo#8773]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.5
* Operating System version: windows10
* Java version: 1.8

### Steps to reproduce this issue

Excuse me, how to call the specified provider on the consumer side through ip+port.
By the way, I am using generalized calls.

**Comment by 24kpure** [comment]
Set the url of referenceconfig before start.

```
reference.setUrl("dubbo://localhost:20890");
```

**Comment by KevinClair** [comment]
Thanks for your answer.I had figured it out with `LoadBalance`.
