### ISSUE TITLE
dubbo consumer 在注入spring bean时,无法注入相关的service

### ISSUE THREAD

**Issue by FelixLiuSheng** [apache/dubbo#8792]
### Environment

* Dubbo version: 3.0.2/3.0.2.1
* Operating System version: macos big sur 11.5
* Java version: 1.8

### Steps to reproduce this issue

1. 定义一个XXXFilter implements org.apache.dubbo.rpc.Filter
2. 在XXXFilter 里定义一个 属性 xxService(需要有一个实现xxService 并增加spring 的@Service注解)
3. 增加一个属性的set方法xxService
4. 启动消费者后,会发现XXXFilter中的xxService并未被实例化,还是null（同理提供者是正常的）

### 问题原因
最开始设置上下文的地方在DubboInfraBeanRegisterPostProcessor#setApplicationContex中，这里将上下文设置进SpringExtensionFactory。后面调用SpringExtensionFactory#initialize()就会清掉，而consumer端后面没有地方再设置（configCenter没配的情况下）
```

**Comment by CrazyHZM** [comment]
Suspected of the same issues：#8793
