### ISSUE TITLE
Dubbo 3.0.2 + Nacos 2.0 + Spring 5.2.8 如何配置应用级服务发现?

### ISSUE THREAD

**Issue by momoco530** [apache/dubbo#8797]

**Comment by EarthChen** [comment]
https://dubbo.apache.org/zh/docs/migration/migration-service-discovery/

**Comment by startjava** [comment]
请问为什么要配置应用级？有什么优势呢？

**Comment by CrazyHZM** [comment]
> 请问为什么要配置应用级？有什么优势呢？

https://dubbo.apache.org/zh/docs/new-in-dubbo3/
