### ISSUE TITLE
[3.0] dubbo MetadataService is exposed by default,That's right?

### ISSUE THREAD

**Issue by EarthChen** [apache/dubbo#8804]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.3-SNAPSHOT
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. start provider
2. start consumer

Pls. provide [GitHub address] to reproduce this issue.

### Actual Result

When local tests are launched on a machine, the consumer's port is occupied due to MetadataService exposure

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
MetadataService is a builtin service in Dubbo, which will be exposed when there is at least one service by default.

**Comment by EarthChen** [comment]
but is always expose dubbo protocol and 20880 port by default.
if run multi dubbo Server on one machine,The port will conflict.

**Comment by EarthChen** [comment]
I think it would be better to use one port because these built-in services should be consistent with the configured protocol.

**Comment by AlbumenJ** [comment]
> I think it would be better to use one port because these built-in services should be consistent with the configured protocol.

processing in https://github.com/apache/dubbo/pull/8796
