### ISSUE TITLE
LeastActive和ShortReponse负载均衡策略算法是不是自带“转移”功能

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8827]
消费者执行3000次操作，发现3个服务提供者有重复消费的现象，

不知道从这2个算法内部是不是就是自带具有这种效果？

感谢

**Comment by startjava** [comment]
如果这样做，执行insert操作，会插入多个数据，这是不对的！

**Comment by CrazyHZM** [comment]
1.What is the insert operation here? 
2.What does it mean that the three services have repeated consumption?
Can you give a specific example？

**Comment by startjava** [comment]
华大，这个“转移”的效果是因为超时导致重试，这个问题我解决了。
三个提供者是为了集群
：） close了，感谢大家！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] LeastActive和ShortReponse负载均衡策略算法是不是自带“转移”功能 (#8827)





 
1.What is the insert operation here?
 2.What does it mean that the three services have repeated consumption?
 Can you give a specific example？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
