### ISSUE TITLE
3.0.3 snapshot版本的Token好像无效啊！

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#8830]
3.0.3 snapshot版本的Token好像无效啊！

**Comment by haoyann** [comment]
我用最新代码测试，没有复现。token 的使用可以参考[文档](https://dubbo.apache.org/zh/docs/advanced/token-authorization/),和 https://github.com/apache/dubbo-samples 的示例。或者可以把你的 demo 上传一下。

**Comment by startjava** [comment]
https://gitee.com/gaohongyan/dubbo3_demo
仓库中有2个token测试，一个是provider，一个是consumer，代码大体帮我看看，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/dubbo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 中午11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/dubbo] 3.0.3 snapshot版本的Token好像无效啊！ (#8830)





 
我用最新代码测试，没有复现。token 的使用可以参考文档,和 https://github.com/apache/dubbo-samples 的示例。或者可以把你的 demo 上传一下。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by startjava** [comment]
解决了，我消费者马虎写成直连接了！麻烦了！感谢！
