### ISSUE TITLE
dubbo使用nacos做多注册中心，重启服务会导致provider被覆盖

### ISSUE THREAD

**Issue by zjutbang** [apache/dubbo#8839]
### Environment

* Dubbo version: 2.7.12
* Java version: 1.8

### Steps to reproduce this issue

1. 配置多个nacos注册中心
2. 启动provider和consumer服务
3. 重启某个注册中心的provider服务，会导致另一个注册中心的provider也变成这个重启的provider

### 源码解读发现逻辑问题
1. com.alibaba.nacos.client.naming.core.HostReactor#processServiceJson里会发布InstancesChangeEvent，这个事件会通知所有naocs注册中心的服务。
2. 会触发这个方法org.apache.dubbo.registry.nacos.NacosRegistry#subscribeEventListener里定义的eventListener。
3. 之后org.apache.dubbo.registry.integration.RegistryDirectory#refreshOverrideAndInvoker 会更新routerChain.setInvokers(newInvokers)。
4. 这里的newInvokers代表重启后的服务provider
5. 最后的结果就导致不同nacos注册中心的对应的RegistryDirectory对象，invokers都被更新成了一个

**Comment by CrazyHZM** [comment]
repeat：https://github.com/apache/dubbo/issues/8838
