### ISSUE TITLE
When subscribing, the check configuration section is unavailable

### ISSUE THREAD

**Issue by CrazyHZM** [apache/dubbo#8841]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0

When the subscription is initiated, check is forcibly set to false, which should be determined by the upper-level configuration
For example：
Mandatory set the check value to false in ZookeeperRegistry

Expectation: If check is an interface-level service discovery, it can be configured for different interfaces. If it is an application-level service discovery, it can be configured for an application.

**Comment by candyaaa** [comment]
I want to give it a try

**Comment by candyaaa** [comment]
@CrazyHZM 我看了dubbo-admin的应用级服务发现，RegistryServerSync依托org.apache.dubbo.registry.Registry进行订阅，订阅的时候传入的URL参数设置了check=false，那么要达到**应用级服务发现，可以进行配置**，是否把硬编码check=false改为从URL中进行获取就可以实现呢？

**Comment by CrazyHZM** [comment]
> RegistryServerSync

是的，不应该硬编码，应该由于配置决定，dubbo-admin如果有订阅全部接口的需求，应该在订阅时就配置check=false

**Comment by CrazyHZM** [comment]
> I want to give it a try

Go a head！
