### ISSUE TITLE
关于引入dubbo 2.7.13版本 启动失败 ReferenceAnnotationBeanPostProcessor  setClassValuesAsString() 方法不存在

### ISSUE THREAD

**Issue by zhaodelin** [apache/dubbo#8911]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.13
* SpringBoot version: 2.2.13.RELEASE
* Operating System version: xxx
* Java version: 1.8.0

### Steps to reproduce this issue
![20210924163953](https://user-images.githubusercontent.com/29915555/134645431-4c1967c6-afb4-4d5f-b1b8-1078dfa72f27.png)
![20210924164047](https://user-images.githubusercontent.com/29915555/134645568-baac452e-c15a-4edb-8e32-d6f58bdb0eb0.png)

**Comment by zrlw** [comment]
pom.xml有版本冲突，把dubbo2.7.13应该使用的spring-context-support 1.0.11覆盖了

**Comment by haihaiya** [comment]
请问下您是怎么解决的，我也遇到了同样的问题
