### ISSUE TITLE
跟换ExceptionFilter失败, 求助

### ISSUE THREAD

**Issue by zhyusgethup** [apache/dubbo#8950]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) 页面404

### Environment dubbo version:2.6.2
* Operating System version: win10
* Java version: 8

在spring-cloud-gateway使用dubbo调用认证服务, 认证服务返回异常时是RpcException. 我希望能处理自定义异常.不断百度, 尝试, 花了不少时间还是失败. issues里面有接近的例子, 可惜具体链接404了. 求助. 谢谢.

**Comment by CrazyHZM** [comment]
在Dubbo内是支持自定义异常的，只是用RpcException包裹了，可以尝试从中获取自定义的异常。
如果要更换ExceptionFilter，你可以尝试自定义filter，然后调整Filter。或者升级到新版本，新版本支持自定义构建Filter链，可以扩展FilterChainBuilder来完成。

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
