### ISSUE TITLE
3.0.2.1启动报错，但是能启动成功

### ISSUE THREAD

**Issue by cslcool** [apache/dubbo#8964]
dubbo配置
![image](https://user-images.githubusercontent.com/34473354/135376661-26d652c2-56a4-4b4a-86d0-e591197c536b.png)
报错信息
![image](https://user-images.githubusercontent.com/34473354/135376711-1dae69f4-049d-454b-9e92-30378bcaeaa6.png)
nacos依赖
![image](https://user-images.githubusercontent.com/34473354/135376768-4aa1e503-f509-4ce0-90be-3bcb20933af0.png)

更换成2.7 能正常启动，不会出现这个错误

### Environment

* Dubbo version: 3.0.2.1
* Operating System version: win10
* Java version: 8

**Comment by cslcool** [comment]
更换版本2.7 能正常启动，不会出现这个错误信息

**Comment by CrazyHZM** [comment]
This seems to be that you have introduced multiple nacos versions in your project, dubbo introduced nacos 2.x in 3.x, try to clean up the nacos version to solve the problem.

**Comment by AlbumenJ** [comment]
Dubbo 3.0 及更高版本需要升级 nacos 到 2.0 版本以上（client 和 server 都需要升级）

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
