### ISSUE TITLE
triple协议消费者报找不到服务提供者

### ISSUE THREAD

**Issue by zzps** [apache/dubbo#8987]
* Dubbo version: 3.0.3
* Operating System version: Windows10
* Java version: 11
重要！！！使用注解方式配置报错，使用api方式正常，注解方式会在nacos上自动添加元数据配置信息，这个很不厌恶
服务提供者：dubbo.protocol.name=tri
服务消费者报错： No provider available for the service 。。。。Please check if the providers have been started and registered

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.

**Comment by feng996** [comment]
> 
Dubbo version: 3.0.4
Operating System version: Ubuntu 18.04.5 LTS
Java version: 11
[dubbo-samples-feedback.tar.gz](https://github.com/apache/dubbo/files/7600561/dubbo-samples-feedback.tar.gz)

nacos version: 2.0.3

tri协议，FORCE_INTERFACE，provider注册，从nacos上能看到。consumer调用报 No provider available for the service

**Comment by feng996** [comment]
使用注解引用时，再次指定protocol=tri，解决
@DubboReference(providedBy = "feedback-provider", check = false, protocol = "tri")
    private HelloService helloService;

看起来是provider配置里services key 为`interface:protocol`的原因（"com.example.feedback.api.service.HelloService:tri"）。
但是不知道为什么在注解引用时，并没有把dubbo.protocol.name=tri这个信息加到后面，需要在reference里再次指定
