### ISSUE TITLE
程序启动成功后，绝大数环境是可以调用dubbo接口是成功的，只有一个环境调用dubbo失败，异常信息No such extension org.apache.dubbo.rpc.cluster.LoadBalance by name random

### ISSUE THREAD

**Issue by skl2226800347** [apache/dubbo#8992]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by skl2226800347** [comment]
这是什么原因导致的？

**Comment by 24kpure** [comment]
Can you find org.apache.dubbo.rpc.cluster.loadbalance.RandomLoadBalance in your project?RandomLoadBalance is the default implementation of LoadBalance.
## Reference
org.apache.dubbo.rpc.cluster.LoadBalance

**Comment by skl2226800347** [comment]
项目解压后，依赖的是dubbo-2.7.7.jar 再解压：1、里面是有org.apache.dubbo.rpc.cluster.loadbalance.RandomLoadBalance  class文件；2、META-INF/dubbo/internal路径下也org.apache.dubbo.rpc.cluster.LoadBalance文件。
