### ISSUE TITLE
Dubbo 3.0.2.1 使用TRI协议 反向序列号失败问题

### ISSUE THREAD

**Issue by q2186609** [apache/dubbo#9063]
### Environment

* Dubbo version: 3.0.2.1
* Operating System version: window11
* Java version: 1.8

### Steps to reproduce this issue
提供者代码如下：  使用了各种序列化实现，都是同一个错误
![image](https://user-images.githubusercontent.com/78395988/137701253-ee871b96-188e-4382-8429-1cfe79a653ac.png)
消费者代码如下
![image](https://user-images.githubusercontent.com/78395988/137701371-d86c9ca5-1041-473b-b276-56bccfa06fbc.png)

错误过程
 消费者调用了 test   提供者中的test 代码执行结束后。没有返回值
消费者端报错 提示  Failed to deserialize response
![image](https://user-images.githubusercontent.com/78395988/137701528-eb6a1a8b-308d-467a-b658-9c2b5471fa81.png)

但是实际上 提供者中的test代码已经被执行了。

如果把提供者协议替换成dubbo协议 就是正常的    请问是否是缺少了什么配置或者依赖？还是Tri 协议并不支持 void 和null 返回呢

**Comment by guohao** [comment]
@q2186609 @paopaoshimeng It is a bug in `3.0.2.1` version , plz try `3.0.3`
