### ISSUE TITLE
yml配置scan时无法set多个扫描类

### ISSUE THREAD

**Issue by liuJunOrGit** [apache/dubbo#9099]
scan:
    base-packages: 
        - com.qike.dubbo.springbootprovider.service.impl
        - com.qike.dubbo.springbootprovider.service.impl2
 或者以 [] 的形式都无法扫描到

  scan:
    base-packages: com.qike.dubbo.springbootprovider.service.impl  这样扫描单个可以

**Comment by CrazyHZM** [comment]
Repeat：https://github.com/apache/dubbo/issues/7268

**Comment by haoyann** [comment]
Please assign to me.

**Comment by haoyann** [comment]
请使用 `,`分割，配置如下
Yaml:
```
dubbo: 
  scan:
    basePackages: package1,package2
```
Properties:
```
dubbo.scan.basePackages=package1,package2
```

**Comment by CrazyHZM** [comment]
The above answer should solve your problem, temporarily close the issue, if there is still a problem, you can reopen it
