### ISSUE TITLE
Version update in pom configuration version inconsistencies error: org/springframework/core/metrics/ApplicationStartup There is also yML in the set to write address is not recognized

### ISSUE THREAD

**Issue by XLtoyyds** [apache/dubbo#9100]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
@XLtoyyds 
Provide more detailed information, such as dubbo version, etc.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
