### ISSUE TITLE
Flaky test: org.apache.dubbo.common.utils.AnnotationUtilsTest#testGetAllDeclaredAnnotations

### ISSUE THREAD

**Issue by HildoYe** [apache/dubbo#9121]
- [Y] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0
* Operating System version: Ubuntu 18.04.6 LTS
* Java version: java 17

### Steps to reproduce this issue

1. run the following command. It's a flaky-detector
`mvn -pl dubbo-common edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.dubbo.common.utils.AnnotationUtilsTest#testGetAllDeclaredAnnotations`

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

The command is to use different random seeds to initialize a test and run it multiple times .
Ideally the test should pass everytime.

### Actual Behavior

It sometime fails with a conversion error.

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
I did not reproduce your problem, please provide the error message.
@HildoYe
