### ISSUE TITLE
Already register the same consumer

### ISSUE THREAD

**Issue by JoyJeck** [apache/dubbo#9124]
**Environment**
Dubbo version: 2.7.4.1
Operating System version: linux
Java version: jdk8
warning：
[DUBBO] Already register the same consumer:xxx, dubbo version: 2.7.4.1
STACKTRACE(most recent call first)
Raw
    at org.apache.dubbo.rpc.model.ApplicationModel.initConsumerModel(ApplicationModel.java:68)

**thanks！**

**Comment by CrazyHZM** [comment]
Try it with the latest version, if you still have problems, you can reopen the issue
