### ISSUE TITLE
多个微服务调用时共用一个超时时间？

### ISSUE THREAD

**Issue by Crispinli** [apache/dubbo#9128]
对外提供服务时，我们服务整体的超时时间为100ms。
服务内部是3个微服务之间的调用，假设3个微服务的名称分别为A、B、C，具体的调用方式为：A调用B并等待B的结果，拿到B的结果后，A调用C并等待C的结果，拿到C的结果后返回。
我们诉求是，让上边描述的调用过程共用这100ms的超时时间，这样就能动态的去使用这100ms而不是为B和C单独设置超时时间。

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
