### ISSUE TITLE
Nacos注册中心发生故障不可用后，dubbo 服务不可用

### ISSUE THREAD

**Issue by chengj1** [apache/dubbo#9134]
我们使用的Dubbo版本为 2.7.8 、Nacos[client\server] 1.4.1。在一次偶发Nacos集群宕机完全不可用后，所有的微服务都无法消费服务

[错误信息一](https://pcsdata.baidu.com/thumbnail/6844e7771k5abb56cba99abfed6f23c6?fid=1829058389-16051585-948759121939408&rt=pr&sign=FDTAER-yUdy3dSFZ0SVxtzShv1zcMqd-ANrLOfKNGgEWOe7iXFFrChT1fAI%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=10186732616539384&dp-callid=0&time=1635235200&bus_no=26&size=c1600_u1600&quality=100&vuk=-&ft=video)
[错误信息二](https://pcsdata.baidu.com/thumbnail/8cff4559ai1ceb78b6035abbc5e6d7f5?fid=1829058389-16051585-586327106395421&rt=pr&sign=FDTAER-yUdy3dSFZ0SVxtzShv1zcMqd-E0CtQJFlvz065yhnxz2sL1%2BYtHQ%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=10251544162859618&dp-callid=0&time=1635235200&bus_no=26&size=c1600_u1600&quality=100&vuk=-&ft=video)
[错误信息三](https://pcsdata.baidu.com/thumbnail/2a8699d68g1aea650de119d9ff28e2c0?fid=1829058389-16051585-969469281831802&rt=pr&sign=FDTAER-yUdy3dSFZ0SVxtzShv1zcMqd-GKpDratnveSmeNYYMUcF%2BJwLZG0%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=10251544162859618&dp-callid=0&time=1635235200&bus_no=26&size=c1600_u1600&quality=100&vuk=-&ft=video)
[错误信息四](https://pcsdata.baidu.com/thumbnail/570b45256v8eb49eeea03c5a85cab5a2?fid=1829058389-16051585-2536561062733&rt=pr&sign=FDTAER-yUdy3dSFZ0SVxtzShv1zcMqd-H8oxnE9lsUouJlXIVMKwtc7%2B944%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=10251544162859618&dp-callid=0&time=1635235200&bus_no=26&size=c1600_u1600&quality=100&vuk=-&ft=video)

**Comment by HsiangCheng** [comment]
Nacos在1.4.1版本存在一个bug可能导致服务下线，你可以考虑升级Nacos解决这个问题。
附上两篇参考博客：
https://cloud.tencent.com/developer/article/1836305
https://onew.me/java/2021/10/19/nacos-net-bug.html

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
