### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by stone-98** [apache/dubbo#9148]
### Environment

* Dubbo version: 3.0.5-SNAPSHOT
* Operating System version: Windows 10
* Java version: JDK 8

### Steps to reproduce this issue

1. 启动org.apache.dubbo.demo.provider.Application
2. 启动org.apache.dubbo.demo.consumer.Application

### Expected Behavior

A successful invoke. 

### Actual Behavior

![image](https://user-images.githubusercontent.com/35629966/139102022-5148e97b-c303-41d2-ae1f-4379aeae7ade.png)

**Comment by LuckyDevin** [comment]
怎么解决的？

**Comment by zrlw** [comment]
maybe https://github.com/apache/dubbo/pull/9145

**Comment by CrazyHZM** [comment]
Will solve it together：https://github.com/apache/dubbo/issues/9182
