### ISSUE TITLE
Filter SPI Auto Load

### ISSUE THREAD

**Issue by wangzhenxyz1** [apache/dubbo#9150]
ExtensionLoader can not inject spring bean by type.
ex: when I customize Filter， I wanna inject spring boot Environment bean, then will delegate SpringExtensionFactory lookup with getOptionalBean,  but getOptionalBean only can inject by type when parameter beanName is null.

### Environment

* Dubbo version: 2.7.8
* Operating System version: MacOS 11.6
* Java version: 1.8

### Expected Behavior
ExtensionLoader can inject spring bean by type. 

Possible Solutions:
A: To annotate the setter method inject by type.
B: DubboBeanUtils#getOptionalBean by name, attempt to set null to beanName  if not found !

### Actual Behavior

ExtensionLoader can not inject spring bean by type.

**Comment by kylixs** [comment]
Pls try Dubbo 3.x

**Comment by wangzhenxyz1** [comment]
> Pls try Dubbo 3.x

Right Now, we can not upgrade to codebase v3.x..
2.8.x remains the majority users.

**Comment by wangzhenxyz1** [comment]
> Pls try Dubbo 3.x
Dubbo 3.x doesn't solve this bug!
`    private <T> T getOptionalBean(ListableBeanFactory beanFactory, String name, Class<T> type) {
        if (StringUtils.isEmpty(name)) {
            String[] beanNamesForType = beanFactory.getBeanNamesForType(type, true, false);
            if (beanNamesForType != null) {
                if (beanNamesForType.length == 1) {
                    return beanFactory.getBean(beanNamesForType[0], type);
                } else if (beanNamesForType.length > 1) {
                    throw new IllegalStateException("Expect single but found " + beanNamesForType.length + " beans in spring context: " +
                        Arrays.toString(beanNamesForType));
                }
            }
        } else {
            if (beanFactory.containsBean(name)) {
                return beanFactory.getBean(name, type);
            }
        }
        return null;
    }`
