### ISSUE TITLE
dubbo2.7.13版本容器化部署时如何满足注册端口和绑定端口需要不一致的问题

### ISSUE THREAD

**Issue by ilvey252** [apache/dubbo#9156]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

场景需求：
我在dubbo服务容器化时遇到一个问题。
**该容器化平台暂时只支持将宿主机的随机端口转发给容器的指定端口**。
比如dubbo provider进程在任意容器内启动后在容器内的端口需要是20880，而dubbo consumer访问容器内的dubbo provider需要通过宿主机的端口才能访问（容器拉起来的时候会随机分配一个端口，并将该端口映射容器的20880端口）。

问题：
我参考文档：https://github.com/apache/dubbo-samples/tree/b95ca08af9f207116ec70631559df4073fe4d75e/dubbo-samples-docker
使用DUBBO_PORT_TO_REGISTRY=宿主机的随机端口来实现，但是发现启动后容器内的dubbo provider的进程端口也变成了宿主机的随机端口，而非我指定的20880端口了。我当前使用的dubbo版本是2.7.13，查看源码里关于注册端口和绑定端口的逻辑（org.apache.dubbo.config.ServiceConfig.findConfigedPorts），发现从2.7.12开始注册端口和绑定端口被改成一致了，之前的版本允许注册端口和绑定端口不一致。
请问下2.7.12及以后的版本，如果需求上要求注册端口和绑定端口不一样，我该如果解决呢？

**Comment by AlbumenJ** [comment]
Dubbo 容器化内部署的最佳方案是 consumer 和 provider 均运行在容器内，容器间通信不依赖宿主机网络映射。需要外部网络访问是再通过网关或者 consumer 的端口映射进行访问。

**Comment by ilvey252** [comment]
> Dubbo 容器化内部署的最佳方案是 consumer 和 provider 均运行在容器内，容器间通信不依赖宿主机网络映射。需要外部网络访问是再通过网关或者 consumer 的端口映射进行访问。

-----
但是我们遇到的实际情况就是这样，容器化平台要求必须通过宿主机的ip+端口访问，且容器内dubbo provider的进程必须指定为某个固定的端口。

**Comment by monkeyWie** [comment]
很明显这是一个bug，不知道出于什么目的在2.7.12会把逻辑改成`DUBBO_PORT_TO_REGISTRY`作用于`DUBBO_PORT_TO_BIND `，这与官方文档里的描述明显也不相符：
![image](https://user-images.githubusercontent.com/13160176/141261475-6a3816c8-d26e-4fa4-b7ed-cc1aa1330711.png)

现在只能先回退到2.7.11来解决了。

**Comment by fl061157** [comment]
我现在开始用 DUBBO 3.0.4。也是完全没有办法， 只能搞一个 TransporterWrapper 在最终Bind时候，修改Port。

public class TransporterWrapper implements Transporter {

    private final Transporter transporter;

    public TransporterWrapper(Transporter transporter) {
        this.transporter = transporter;
    }

    @Override
    public RemotingServer bind(URL url, ChannelHandler handler) throws RemotingException {
        ServiceModel sm = url.getServiceModel();
        if (Objects.isNull(sm)) {
            return transporter.bind(url, handler);
        }
        AbstractInterfaceConfig config = sm.getConfig();
        if (Objects.isNull(config) || !(config instanceof ServiceConfig)) {
            return transporter.bind(url, handler);
        }
        ServiceConfig<?> sc = (ServiceConfig<?>) config;
        List<ProtocolConfig> pcs = sc.getProtocols();
        if (CollectionUtils.isEmpty(pcs)) {
            return transporter.bind(url, handler);
        }
        Map<String, ProtocolConfig> pcm = toMap(pcs);
        if (MapUtils.isEmpty(pcm)) {
            return transporter.bind(url, handler);
        }
        ProtocolConfig pc = pcm.get(url.getProtocol());
        if (Objects.isNull(pc)) {
            return transporter.bind(url, handler);
        }
        Integer port = findPort(pc, sc.getProvider(), url.getProtocol());
        URLAddress urlAddress = url.getUrlAddress();
        if (Objects.nonNull(port)) {
            urlAddress.setPort(port);
        }
        return transporter.bind(url, handler);
    }

    private Integer findPort(ProtocolConfig protocolConfig, ProviderConfig provider, String protocol) {
        Integer portToBind;
        String port = getValueFromConfig(protocolConfig, DUBBO_PORT_TO_BIND);
        portToBind = parsePort(port);
        if (Objects.isNull(portToBind)) {
            portToBind = protocolConfig.getPort();
            if (Objects.nonNull(provider) && (Objects.isNull(portToBind) || portToBind == 0)) {
                portToBind = provider.getPort();
            }
            final int defaultPort = ExtensionLoader.getExtensionLoader(Protocol.class).getExtension(protocol).getDefaultPort();
            if ((portToBind == null || portToBind == 0) && defaultPort != 0) {
                portToBind = defaultPort;
            }
        }
        return portToBind;
    }

    private String getValueFromConfig(ProtocolConfig protocolConfig, String key) {
        String protocolPrefix = protocolConfig.getName().toUpperCase() + "_";
        String value = ConfigUtils.getSystemProperty(protocolPrefix + key);
        if (org.apache.dubbo.common.utils.StringUtils.isEmpty(value)) {
            value = ConfigUtils.getSystemProperty(key);
        }
        return value;
    }

    private Integer parsePort(String configPort) {
        if (StringUtils.isBlank(configPort)) {
            return null;
        }
        try {
            int intPort = Integer.parseInt(configPort);
            return isInvalidPort(intPort) ? null : intPort;
        } catch (Throwable throwable) {
            return null;
        }
    }

    private Map<String, ProtocolConfig> toMap(List<ProtocolConfig> pcs) {
        Map<String, ProtocolConfig> map = new HashMap<>();
        for (ProtocolConfig pc : pcs) {
            if (Objects.nonNull(pc) && StringUtils.isNotBlank(pc.getName())) {
                map.put(pc.getName(), pc);
            }
        }
        return map;
    }


    @Override
    public Client connect(URL url, ChannelHandler handler) throws RemotingException {
        return transporter.connect(url, handler);
    }
}

**Comment by monkeyWie** [comment]
已经提了个PR修复：https://github.com/apache/dubbo/pull/9298
