### ISSUE TITLE
qos-server can not bind localhost:22222 配置错误

### ISSUE THREAD

**Issue by xiangyunup** [apache/dubbo#9158]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: mac
* Java version: 1.8

### Steps to reproduce this issue

1. 默认配置，启动2个互相依赖的服务，由于第一个暂用了 qos 默认端口 22222 ，所以第二个会报错
2. java.net.BindException: Address already in use: bind

### Expected Behavior
老版本没有遇到过，所以觉得不应该有此问题，百度查询结果，显示可以修改配置，但实际修改未生效
1 dubbo.application.qos.enable=true
2 dubbo.application.qos.port=33333
3 dubbo.application.qos.accept.foreign.ip=false

### Actual Behavior

通过查看源码，发现配置名称不一样，按照以下配置修改后正常
1 dubbo.application.qos-enable=true
2 dubbo.application.qos-port=33333
3 dubbo.application.qos-accept-foreign-ip=false

**Comment by wangchengming666** [comment]
I'll FIX it

**Comment by xiangzz159** [comment]
dubbo3.0.6使用的是dubbo.application.qos.enable，但是dubbo-spring-boot-starter是dubbo.application.qos-enable
