### ISSUE TITLE
Session 0x0 for server 127.0.0.1/<unresolved>:2181

### ISSUE THREAD

**Issue by hadesvip** [apache/dubbo#9167]
### Environment

* Dubbo version: 3.0.2.1
* Operating System version: win10
* Java version: openjdk 14

### Steps to reproduce this issue

1. 在openjdk14 版本上运行dubbo时候启动报错，提示如下

![image](https://user-images.githubusercontent.com/9640832/139537432-1817c3e5-0ada-408d-999f-f421b1d48b24.png)

2.  调试源码发现，openjdk14 修改了InetSocketAddress的toString方法，修改源码如下
![image](https://user-images.githubusercontent.com/9640832/139538155-be811b02-a07c-44f7-8381-da0e3879463c.png)

3.  调用InetSocketAddress.toString()获取IP地址的时候导致返回了`127.0.0.1/<unresolved>:2181`，获取IP地址触发了UnknownHostException运行时异常返回了默认的值
![image](https://user-images.githubusercontent.com/9640832/139537583-55feea8c-b1b7-4d7b-8f33-83e303b86bf8.png)

4. 后续对ip地址进行校验的时候，SocketAddress中的addr并没有设置值，直接触发了UnresolvedAddressException异常
![image](https://user-images.githubusercontent.com/9640832/139537823-45d46b21-3534-4ec2-99e6-59f5c12728a4.png)

Pls. provide [GitHub address] to reproduce this issue.
https://github.com/hadesvip/dubbo-samples/blob/master/dubbo-samples-echo/src/main/java/org/apache/dubbo/samples/echo/EchoProvider.java

**Comment by AlbumenJ** [comment]
Try upgrade zk version.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
