### ISSUE TITLE
dubbo2.6.*版本，provider重启导致consumer内存泄漏

### ISSUE THREAD

**Issue by heartarea** [apache/dubbo#9173]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.9
* Operating System version: xxx
* Java version: 1.8.0_111

### Steps to reproduce this issue

1. 注册中心使用zookeeper，启动一个provider和consumer，
2. 关停provider进程，等待40s（dubbo与zookeeper的会话超时时间）
3. 启动provider进程。
4. 重复步骤2和3

示例代码：https://github.com/heartarea/dubbo-memoryleak-demo

### Expected Behavior

每重启一次provider，内存中“com.alibaba.dubbo.remoting.transport.netty4.NettyClient”实例个数增加1。

### Actual Behavior

无论重启多少次provider，内存中“com.alibaba.dubbo.remoting.transport.netty4.NettyClient”实例个数始终为1

## 一个粗浅的源码分析 https://www.jianshu.com/p/8f4d33008c90。

**Comment by CrazyHZM** [comment]
2.6.x version is no longer maintained, it is recommended to upgrade to 2.7.x or 3.x version.
