### ISSUE TITLE
dubbo 3.X dubbo.application.register-mode 默认值是interface还是all？

### ISSUE THREAD

**Issue by syshenyao** [apache/dubbo#9193]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo 3.X dubbo.application.register-mode 默认值是interface还是all？

**Comment by syshenyao** [comment]
实验发现默认值应该是all，文档写的默认值前后不一致

**Comment by wangchengming666** [comment]
缺省值应该是instance

**Comment by AlbumenJ** [comment]
缺省值接口级、应用级都注册

https://github.com/apache/dubbo/blob/04a983792ad479efdc404bdcb600fddbd072820e/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/utils/ConfigValidationUtils.java#L250
