### ISSUE TITLE
游戏中使用dubbo的一些疑问

### ISSUE THREAD

**Issue by l42111996** [apache/dubbo#9206]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
我们想在游戏中使用dubbo，有个需求是要根据参数决定这个请求在指定的线程执行，比如同一个接口某些参数在固定的串行线程，某些在另一个，这种需求有什么好的解决方式吗？
dubbo线程的Dispatcher在协议decode之前执行了这样在Dispatcher的时候取不到对应的参数

**Comment by AlbumenJ** [comment]
建议自己实现一个 Dispatcher

**Comment by l42111996** [comment]
> 建议自己实现一个 Dispatcher

感谢大佬提供的思想，我定义了一个dispatcher在里面提前decode了协议体也实现了对应的线程调用，但是配置了
dubbo.provider.dispatcher=gameThreadPool 后provider启动没问题，对应的consumer端出现了找不到对应的dispatcher的exception，为什么会出现这个，这个应该怎么解决？

No such extension org.apache.dubbo.remoting.Dispatcher by name gameThreadPool, no related exception was found, please check whether related SPI module is missing.

**Comment by AlbumenJ** [comment]
目前 dispatcher 这个参数确实有这个问题，消费端要独立重新指定下

**Comment by l42111996** [comment]
> 目前 dispatcher 这个参数确实有这个问题，消费端要独立重新指定下

我只能在consumer端配置一个SPI文件指定 gameThreadPool=org.apache.dubbo.remoting.transport.dispatcher.message.MessageOnlyDispatcher
绕过这个问题了，谢谢大佬
