### ISSUE TITLE
项目升级dubbo3.0.4版本遇到的问题

### ISSUE THREAD

**Issue by liu6d1** [apache/dubbo#9209]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
将自己公司的项目升级到dubbo3.0.4版，dubbo-admin里面的注册来源只有接口级的，没有应用级的

**Comment by haoyann** [comment]
dubbo-admin 使用 develop 的代码试一下呢？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
