### ISSUE TITLE
Add ability for protection of empty provider list.

### ISSUE THREAD

**Issue by KomachiSion** [apache/dubbo#9213]
## Describe the feature

Currently Dubbo can support various registration centers including Nacos, Zookeeper and so on. And Dubbo can find the address list of the service provider from the registration center, so as to make RPC request.

However, many kinds of exceptions may occur in the registration centers. For example, sometimes the list of new services obtained is empty, but in fact it is not an empty list. Some registration centers, such as Nacos, can ignore the empty list by switching on in some versions, but other registries may not provide such capabilities, resulting in a sudden `No provider` problem during runtime.

For RPC, there should be no empty service provider list in most correct situations. Therefore, I hope to add an ability to ignore the empty provider list when this happens. And I think it is a common feature, which is not depended registration centers type.

**Comment by AlbumenJ** [comment]
Supported in 3.0
