### ISSUE TITLE
Whats the difference between dubbo.provider.payload and dubbo.protocol.payload?

### ISSUE THREAD

**Issue by einverne** [apache/dubbo#9250]
Recently, I met the `org.apache.dubbo.remoting.RemotingException: Data length too large: 21196226, max payload: 8388608, channel: NettyChannel ` error, I find two ways to set payload.

```
dubbo.provider.payload=33554432
dubbo.protocol.payload=33554432
```
What's the difference between these two.

**Comment by BurningCN** [comment]
protocolConfig has a higher priority
