### ISSUE TITLE
dubbo 2.7.12 @DubboReference @motehod 方法上的retries失效

### ISSUE THREAD

**Issue by softwarebb** [apache/dubbo#9256]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.12
* Operating System version: win10
* Java version: jdk8
*  配置中心:  nacos

### Steps to reproduce this issue

1. 下面是我的配置:
 客户端配置：
![企业微信截图_16366339068375](https://user-images.githubusercontent.com/18391433/141298512-2455c372-1563-4837-9246-9f61206d313c.png)
服务配置
![企业微信截图_1636633970555](https://user-images.githubusercontent.com/18391433/141298642-d9b6aec9-9e35-4d71-acde-d641add00e8d.png)
配置文件
![image](https://user-images.githubusercontent.com/18391433/141400484-b0be8d03-11b0-46b4-992d-9334798e14e2.png)

maven依赖：
![企业微信截图_1636634290942](https://user-images.githubusercontent.com/18391433/141299407-f49fe539-122e-477c-a4bf-4939d57da0b7.png)

发现在@Method中配置的retries不生效，但是timeout生效，经过debug发现获取方法上的retries属性时，url对象a和获取其他属性（例如timeout）的url对象b不同，url对象a中的methodParameters不包含@method上的属性，并且url中host是本机的以太网适配器 VMware Network Adapter VMnet1的Ipv4地址，而url对象b的methodParameters包含@method上的属性，并且其url中host是本机的以太网适配器 vEthernet (默认开关)对象的Ipv4地址

麻烦看一下是否是配置问题？

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
@softwarebb 
2.7.14 Should there be a problem?

**Comment by wangchengming666** [comment]
@softwarebb try last version

**Comment by softwarebb** [comment]
@wangchengming666 thanks, last version does work well
