### ISSUE TITLE
[3.0] provider开启MetricsFilter，但是在dubbo-admin获取不到线程池的统计数据

### ISSUE THREAD

**Issue by wangchengming666** [apache/dubbo#9272]
provider开启MetricsFilter，但是在dubbo-admin获取不到线程池的统计数据

原因如下
`    
private List<MetricObject> getThreadPoolMessage() {
        DataStore dataStore = extensionAccessor.getExtensionLoader(DataStore.class).getDefaultExtension();
        Map<String, Object> executors = dataStore.get(EXECUTOR_SERVICE_COMPONENT_KEY);
`

解决方案：在创建的时候将线程池信息放到`DataStore`中

**Comment by CrazyHZM** [comment]
Repeat：https://github.com/apache/dubbo/issues/8140
