### ISSUE TITLE
多注册中心，服务覆盖问题

### ISSUE THREAD

**Issue by feng996** [apache/dubbo#9285]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: ubuntu 18
* Java version: 11
* nacos version: 2.0.3
* protocol: tri
* spring boot version: 2.4.9

### Steps to reproduce this issue

引用多注册中心，第一次切换访问可以成功，后面的请求全部都打到上次请求的服务上去了。

配置如下

`@DubboReference(providedBy = "data-mysql", registry = "ali-sgp", id = "intlAuditLabelService", stub = "intlAuditLabelService", check = false)`
` private AuditLabelService intlAuditLabelService;`

   ` @DubboReference(providedBy = "data-mysql", registry = "aws-mb", id = "indAuditLabelService", stub = "indAuditLabelService", check = false)`
`    private AuditLabelService indAuditLabelService;`

dubbo:
  registries:
    aws-mb:
      address: nacos://${nacos.aws-mb.host}:${nacos.aws-mb.port}?namingLoadCacheAtStart=false&username=${nacos.aws-mb.username}&password=${nacos.aws-mb.password}&namespace=${nacos.aws-mb.namespace}
      id: aws-mb
      timeout: 1100
      preferred: true
    ali-sgp:
      address: nacos://${nacos.ali-sgp.host}:${nacos.ali-sgp.port}?namingLoadCacheAtStart=false&username=${nacos.ali-sgp.username}&password=${nacos.ali-sgp.password}&namespace=${nacos.ali-sgp.namespace}
      id: ali-sgp
      timeout: 1300

**Comment by chickenlj** [comment]
> 第一次切换访问可以成功，后面的请求全部都打到上次请求的服务上去了。

@feng996 劳烦把这部分问题详细描述一下：服务部署情况，怎么操作的切换，最终问题现象等

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/9427
