### ISSUE TITLE
dubbo对void类型的方法 的返回值解析失败

### ISSUE THREAD

**Issue by luky116** [apache/dubbo#9305]
我用 java-client 调用 java-server 的方法，方法返回值为 void，client收到后还是会将 void 反射弄成对象导致解析失败。想问问为啥void类型返回值，还要进行反射实例化呢？
dubbo版本是 3.0.2
![lQLPDhrkJNnUabDNA9zNBFOwBLRV3JoX6KEBowiplQBFAA_1107_988 png_720x720g](https://user-images.githubusercontent.com/38887641/142819904-eb19b747-3940-40bf-9bc6-a2c8d36581bd.jpg)

**复现方法：**
启动java-server的main方法，用java-client的main执行` complexProvider.invokeWithEmptyReq()`，即可复现问题：
https://github.com/luky116/dubbo-go-samples/tree/fix-tpcTripleHessian2/rpc/triple/hessian2

**Comment by guohao** [comment]
Has been fixed in 3.0.3 https://github.com/apache/dubbo/pull/8608
