### ISSUE TITLE
系统OOM, dump文件里显示threadLocal 存在大量数据 

### ISSUE THREAD

**Issue by bootstrap2025** [apache/dubbo#9335]
![screenshot-20211130-210614](https://user-images.githubusercontent.com/9637974/144052824-4d22c91b-d4c1-40f4-8bed-b4c596dba25d.png)
dubbo 版本```2.5.3```
我这边发现一次内存泄漏引起的oom，然后我把dump 文件打出来看了下，dubbo 的200个线程里每个线程都存了 150k（图片打码部分是Eclipse memory analyzer 的线程分析的截图）的数据，怀疑是因为这个导致引起的内存泄漏，然后这个数据是我们程序请求接口加载的大文本数据，数据是正常的，但是有些奇怪的是，不同接口的返回数据出现在一个threadLocal 里，导致threadLocal 值很大，于是我想问几个问题：
1. 为什么线程threadLocal里会有这么多不同接口的数据？ 这边线程不会remove掉数据吗？
2. 我本地接口里没有调用threadLocal ,想咨询下什么情况下会把数据缓存到threadLocal里？

**Comment by AlbumenJ** [comment]
Dubbo 2.5.x is no longer maintained. Please try upgrade to the latest version.
