### ISSUE TITLE
duplicate of  #7659

### ISSUE THREAD

**Issue by rottenmu** [apache/dubbo#9336]
duplicate of  #7659

_Originally posted by @chickenlj in https://github.com/apache/dubbo/issues/7655#issuecomment-856914417_

Injection of @DubboReference dependencies is failed; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Class

**Comment by rottenmu** [comment]
@ulinkwo help! help! help!

**Comment by haoyann** [comment]
这个异常是什么意思，需要怎么才能复现？

**Comment by rottenmu** [comment]
> 这个异常是什么意思，需要怎么才能复现？
启动 dubbo服务的时候出现的这个问题，找到了 issue
https://github.com/apache/dubbo/issues/7115，但是依旧有问题

**Comment by rottenmu** [comment]
环境 dubbo2.710,nacos1.1.1,springboot2.3.1.RELEASE，nacos-discovery-spring-boot-starter0.27

**Comment by haoyann** [comment]
看相关修复的PR 升级 `alibaba_spring_context_support_version` 到了 1.0.11 版本，然后 dubbo 版本建议使用 2.7.x 的最新版本试试。

**Comment by rottenmu** [comment]
> `alibaba_spring_context_support_version`
nacos-spring-context-support?

**Comment by haoyann** [comment]
> nacos-spring-context-support?

嗯，`spring-context-support` 升级到 1.0.11 和 dubbo 版本升级到 2.7.x 最新版本试一下.
