### ISSUE TITLE
MetricsFilter 没有将MetricsService注册到ApplicationModel的ServiceRepository

### ISSUE THREAD

**Issue by aaa489** [apache/dubbo#9338]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: windows
* Java version: 1.8

### Steps to reproduce this issue

1. 使用dubbo admin服务统计功能的时候发现报错，大概是service not found
![image](https://user-images.githubusercontent.com/23420362/144187737-b87872f0-d8a5-4c21-b9a3-c7e1326779e9.png)
2. 查看源码发现调的是的MetricsService的getMetricsByGroup接口
![image](https://user-images.githubusercontent.com/23420362/144187830-3ae3450f-a124-4e57-b8a3-53a173374a5b.png)
3. 该接口是带参数的，所以请求的时候会有参数类型，而对于有参数类型的请求，在做decode的时候会去ApplicationModel的ServiceRepository中判断是否存在，不存在则抛service not found异常
![image](https://user-images.githubusercontent.com/23420362/144188061-a03a6fe9-2b54-4b52-95e2-98e98ac7cd72.png)
4. 正常暴露服务的时候会服务注册到ApplicationModel的ServiceRepository
![image](https://user-images.githubusercontent.com/23420362/144188330-a271facb-1010-4bdd-b0ba-eb5f1bd798ec.png)
5. 而MetricsService确并没有这个逻辑

### Expected Behavior

MetricsService应该注册到ApplicationModel的ServiceRepository

### Actual Behavior

ApplicationModel的ServiceRepository没有MetricsService，导致处理该接口请求抛异常

**Comment by wangchengming666** [comment]
I'll try fix it

**Comment by aaa489** [comment]
> @aaa489 可以尝试一下最新版本

最新版本里被弃用了，感谢支持

**Comment by habertzk** [comment]
> > @aaa489 可以尝试一下最新版本
> 
> 最新版本里被弃用了，感谢支持

 最新版本不支持了吗，如果不支持了，服务统计该如何使用呢？

**Comment by habertzk** [comment]
> > @aaa489 可以尝试一下最新版本
> 
> 最新版本里被弃用了，感谢支持

你现在是怎么解决的呢？
