### ISSUE TITLE
hessian 序列化如何不支持非Serializable 对象

### ISSUE THREAD

**Issue by hillwater** [apache/dubbo#9339]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
hessian 序列化如何不支持非Serializable 对象

**Comment by lexang** [comment]
Add system properties to support allow non-serializable  之后 报错:[Serialization Security] Serialized class * has not implement Serializable interface. Current mode is strict check, will disallow to deserialize it by default.

**Comment by AlbumenJ** [comment]
> Add system properties to support allow non-serializable 之后 报错:[Serialization Security] Serialized class * has not implement Serializable interface. Current mode is strict check, will disallow to deserialize it by default.

Please test on the latest version
