### ISSUE TITLE
版本2.7.5  zookeeper客户端读取配置中心的单个服务的配置的路径有问题

### ISSUE THREAD

**Issue by LazyMonkey1992** [apache/dubbo#9350]
类org.apache.dubbo.config.AbstractInterfaceConfig中的   

方法 private void prepareEnvironment() 中的  

`  if (StringUtils.isNotEmpty(appGroup)) {
                // 这里获取的是/dubbo/config/dubbo-demo-consumer/dubbo.properties节点中的内容
                // todo 这里有bug
                appConfigContent = dynamicConfiguration.getProperties
                        (StringUtils.isNotEmpty(configCenter.getAppConfigFile()) ? configCenter.getAppConfigFile() : configCenter.getConfigFile(),
                         appGroup
                        );
            }`

注释的地方的方法作用是获取我们在配置中心配置的单个实例的配置内容，正确路径应该为
/dubbo/config/dubbo/dubbo-demo-consumer/dubbo.properties
实际上为
/dubbo/config/dubbo-demo-consumer/dubbo.properties
导致获取不到配置的内容

**Comment by CrazyHZM** [comment]
@LazyMonkey1992 
Try to use the latest version.

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
