### ISSUE TITLE
dubbo注册服务到nacos注册中心，注册地址是https域名

### ISSUE THREAD

**Issue by lixiuyang** [apache/dubbo#9376]
我加上http或者不加都不行
dubbo.registry.address:=nacos://https://xxx.xiaoming.cn:443
或 dubbo.registry.address:=nacos://xxx.xiaoming.cn:443
如果是https域名，应该怎么配置？谢谢

**Comment by AlbumenJ** [comment]
nacos 注册中心通过私有端口进行通信，不支持加 TLS。具体端口配置信息请参考 nacos 相关文档
