### ISSUE TITLE
使用应用级别注册后 消费端无法获取信息

### ISSUE THREAD

**Issue by kentkwan** [apache/dubbo#9405]
使用外置配置中心

dubbo.application.name=test
dubbo.application.register-mode=instance
dubbo.protocol.name=tri
dubbo.metadata-report.address=nacos://127.0.0.1:8848
dubbo.registry.address=nacos://127.0.0.1:8848

消费端启动报错
Directory already destroyed .url: nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?application=test&dubbo=2.0.2&pid=48179&qos.enable=false&release=3.0.4&timestamp=1639469279628

**Comment by paopaoshimeng** [comment]
这个问题和我遇到的[9374](https://github.com/apache/dubbo/issues/9374)，有点像

**Comment by chickenlj** [comment]
duplication
