### ISSUE TITLE
dubbo:metadata-report配置参数retry-times不生效

### ISSUE THREAD

**Issue by SheepNo2** [apache/dubbo#9410]
xml配置
<dubbo:metadata-report address="zookeeper://127.0.0.1:2181" retry-times="3" retry-period="10000" cycle-report="false" />
调试了几次retry-times ，retry-period等参数不生效，
后来发现key不一样
org.apache.dubbo.metadata.support.Constants     定义的key是String RETRY_TIMES_KEY = "retry.times";
而map取的key是retry-times，所以每次都是用的默认值100，大家是怎么处理的？
![image](https://user-images.githubusercontent.com/19886737/146121722-d05678a7-925d-4b44-932e-5d8a38ba73b5.png)

**Comment by BurningCN** [comment]
看了下，这是一个bug  两边的key不一致
![image](https://user-images.githubusercontent.com/43363120/146144259-7b176ab8-2f38-42bd-8b13-bda8ff894213.png)
![image](https://user-images.githubusercontent.com/43363120/146144367-150248cc-076c-495b-b790-5e2c30c0a117.png)

**Comment by SheepNo2** [comment]
> 看了下，这是一个bug 两边的key不一致 ![image](https://user-images.githubusercontent.com/43363120/146144259-7b176ab8-2f38-42bd-8b13-bda8ff894213.png) ![image](https://user-images.githubusercontent.com/43363120/146144367-150248cc-076c-495b-b790-5e2c30c0a117.png)

对，你们有遇到吗，怎么处理的？

**Comment by BurningCN** [comment]
我会尝试修复这个问题

**Comment by CrazyHZM** [comment]
Resolved in #9429
