### ISSUE TITLE
[3.0] Unify usage of group in registry, metadata and configcenter

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#9427]
As titled, check group usage of Nacos, Zookeeper

**Comment by haoyann** [comment]
This issue #9188 is same reason , configcenter use group is fixed dubbo.

**Comment by JavaLionLi** [comment]
应用级服务注册发现 dubbo.register.group 无效 注册的服务 group 并没有变化

**Comment by chickenlj** [comment]
> 应用级服务注册发现 dubbo.register.group 无效 注册的服务 group 并没有变化

感谢上报。我们之前也已经注意到这个问题了，正在修复中

**Comment by GTaurus** [comment]
> 

请问会在3.0.8版本中修复吗？

**Comment by JavaLionLi** [comment]
> > 应用级服务注册发现 dubbo.register.group 无效 注册的服务 group 并没有变化
> 
> 感谢上报。我们之前也已经注意到这个问题了，正在修复中

请问大概在哪个版本会修复此问题

**Comment by cycle2zhou** [comment]
3.0.10并没有修复

**Comment by AlbumenJ** [comment]
3.1.0 中将会修复 nacos group 错误的问题，由于存在兼容性问题此变更不会合并进入 3.0 版本

**Comment by chickenlj** [comment]
应用级服务发现中，几个主流注册中心（涵盖zookeeper、nacos）的 group (`dubbo.registry.group` )属性方式已经对齐。

3.0.10 版本之前的 group 属性是不生效的，而 3.1 版本之后，您可以配置 group 属性并实现注册数据软隔离。

如果您之前您的项目没使用过 group 则不用担心兼容性，如果项目中有配置 group，在升级 3.1 之前请注意兼容性问题：
https://dubbo.apache.org/zh/docs3-v2/java-sdk/upgrades-and-compatibility/3.0-to-3.1-compatibility-guide/
