### ISSUE TITLE
Apache Dubbo 社区贡献者回馈计划

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#9432]
近日，阿里巴巴发起了一项开源贡献者回馈活动，意在奖励为开源做出贡献的社区与个人，很荣幸 Apache Dubbo 社区也受邀参与其中，能有机会为各位社区贡献者带来一些物质回馈。请各位曾为 Dubbo 社区做出代码、文档、生态等的贡献者在填写必要的个人信息，以便活动主办方能将奖品发放给各位。

请填写以下表单：
http://ssrafysdv3u5tv1v.mikecrm.com/jytF4a0

在此，非常感谢过去一年大家对 Apache Dubbo 社区的关注与支持，在社区的共同努力下，Dubbo 在 6 月份发布了 3.0 的首个正式版本，随后阿里巴巴各条业务线包括淘宝、考拉、饿了么、钉钉、达摩院等业务线都已陆续上线 3.0 版本，其他公司如小米、工商银行等也引入了 3.0 版本的新特性。Dubbo3 仍在持续演进之中，未来一段时间在持续推进稳定性、支持社区用户的同时，我们将继续加强规划功能、生态、文档等建设，让 Dubbo3 继续成为引领云原生时代的服务框架。

> 据主办方反馈，如贡献者数量过多（如 100+）会有限额，还请大家如实填写贡献信息，如出现名额超限情况社区会根据贡献排名进行筛选，还请见谅。

> 您对 Apache Dubbo 有过任何形式的贡献都可以在此报名。

Recently, Alibaba launched an open source contributor feedback activity, which is intended to reward communities and individuals who contribute to open source. It is a great honor that Apache Dubbo community is also invited to participate in it, and can have the opportunity to bring some material feedback to community contributors. Please fill in your personal information in the following form for contributors who have made codes, documents and ecology for Dubbo community, so that the event organizer can distribute the prizes to you. 

Please fill in the following form:
http://ssrafysdv3u5tv1v.mikecrm.com/jytF4a0

Here, thank you very much for your attention and support to Apache Dubbo community in the past year. With the joint efforts of the community, Dubbo released the first official version of 3.0 in June. Subsequently, Alibaba's business lines including Taobao, koala, hungry, nailing, Dharma hall and other business lines have successively launched version 3.0, and other companies such as Xiaomi ICBC has also introduced the new features of version 3.0. Dubbo 3 is still evolving. In the future, while continuing to promote stability and support community users, we will continue to strengthen the construction of planning functions, ecology and documents, so that Dubbo 3 will continue to become a service framework leading the original era of cloud.

> According to the feedback from the organizer, if there are too many contributors (such as 100 +), there will be a limit. Please fill in the contribution information truthfully. If the quota exceeds the limit, the community will screen according to the contribution ranking. Please forgive me.

> You can sign up here if you have made any contribution to Apache Dubbo.

https://lists.apache.org/thread/1l7qd9k3q11q2g1vbx6vsy5tyv76m2b6

**Comment by icankeep** [comment]
Won't this cause personal information disclosure? It doesn't feel like a good way

**Comment by chickenlj** [comment]
> Won't this cause personal information disclosure? It doesn't feel like a good way

Sure, I will edit to guide contributors to send emails privately or by submitting private form.

**Comment by lkxiaolou** [comment]
需要提交哪些信息呢？怎么提交

**Comment by chickenlj** [comment]
> 

已经增加了表单链接了，直接填写表单即可

**Comment by guohao** [comment]
👍

**Comment by 24kpure** [comment]
Wow, I can't wait more!

**Comment by 5ME** [comment]
http://ssrafysdv3u5tv1v.mikecrm.com/jytF4a0

链接打开什么也没有啊

**Comment by u0x01** [comment]
👍👍👍

**Comment by complone** [comment]
👍

**Comment by chickenlj** [comment]
Thank you very much. Now I announce the end of this activity.
