### ISSUE TITLE
dubbo 3.0.4如何正确开启应用级服务注册与发现

### ISSUE THREAD

**Issue by childe-dragon** [apache/dubbo#9480]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
1.dubbo 3.0.4如何正确开启应用级服务注册与发现,有什么参数可以设置？

**Comment by haoyann** [comment]
可以参考官网文档 https://dubbo.apache.org/zh/docs/migration/migration-service-discovery/

**Comment by childe-dragon** [comment]
1.provider设置dubbo.application.register-mode=all,consumer设置dubbo.application.service-discovery.migration=FORCE_APPLICATION,consumer压根就找不到服务,提示No provider available for the service xxx
以上provider和consumer都是全新启的服务,provider注册信息在nacos服务列表接口级和应用级都是有的.但是consumer设置dubbo.application.service-discovery.migration=APPLICATION_FIRST就不会有问题,但个人猜测压根就没走应用级调用,应该走了接口级调用否则FORCE_APPLICATION参数应该必然会生效不至于找不到服务
2.如果dubbo.registry.simplified设置为true,那么nacos上根本就不会有应用级的注册信息[配置同1情况下],更头疼的是dubbo.application.parameters参数传参也是空的.
真不知道是我配置问题还是这本身就是个bug

**Comment by VirensCn** [comment]
你们使用3.0.4能启动？我使用3.0.3就没问题。。。特别诡异。。
![(7$88RR%E`5)SNRBJZUMY74](https://user-images.githubusercontent.com/9736815/147342279-3e933fae-f405-42a2-88d2-fa5320ef9336.png)
![@@~2F`F C0J~RY4WU@Z42ZT](https://user-images.githubusercontent.com/9736815/147342547-27efbfab-dabb-43ef-9afc-dc601d8bd902.png)

![VE ZP@22{ZY}UPZR{BTBMIF](https://user-images.githubusercontent.com/9736815/147342344-6b4d41bf-b631-4379-90c2-332280d52bdb.png)

![EZ9}@25GZ9 (Q4NT3G1I{NL](https://user-images.githubusercontent.com/9736815/147342424-ade7398f-c5a1-48af-a3b4-83f603633646.png)

**Comment by childe-dragon** [comment]
我的三大中心都是nacos,客户端和版本都保持一致.你可以看看你的zk是否也保持一致,很多时候都是版本兼容问题。
我是卡在了路由这儿,dubbo和dubbo-admin总是各种奇奇怪怪的问题.无论怎么设置dubbo-admin看不到应用级注册信息,mesh路由、tag路由无论怎么设置都无法生效,完全在摸索特别耗人

**Comment by haoyann** [comment]
@childe-dragon 配置不生效看这个 #9239，可以用最新版本试一下。

**Comment by childe-dragon** [comment]
已经解决了,比较无奈，服务提供方、消费方以及mesh的规则配置都没什么问题.翻了3.0.4 cluster里route里的源码,发现从配置中心拉取数据时候nacos的group硬编码为dubbo,而dubbo-admin配置的group是DEFAULT_GROUP导致写入nacos的规则group自然是DEFAULT_GROUP,进而在消费端拉取规则配置是拉取不到的.
个人建议这个group最好能与项目中dubbo配置中心的group保持一致[dubbo.config-center.group],这样无论是dubbo的配置还是路由、限流等group都一致,会避免很多的麻烦。

**Comment by chickenlj** [comment]
> 个人建议这个group最好能与项目中dubbo配置中心的group保持一致[dubbo.config-center.group],这样无论是dubbo的配置还是路由、限流等group都一致,会避免很多的麻烦。

这个建议我们将会在下个 3.0.6 版本中重点关注 https://github.com/apache/dubbo/issues/9427
