### ISSUE TITLE
Dubbo 3 版本中，不提供kryo这种序列化的maven坐标吗

### ISSUE THREAD

**Issue by jinshengyong** [apache/dubbo#9481]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by CrazyHZM** [comment]
kryo 序列化的扩展，可以关注https://github.com/apache/dubbo-spi-extensions

**Comment by lifeixiang027** [comment]
> kryo 序列化的扩展，可以关注https://github.com/apache/dubbo-spi-extensions

如何使用？ 找不到任何的说明
