### ISSUE TITLE
Dubbo's proxyless mesh

### ISSUE THREAD

**Issue by adalrsjr1** [apache/dubbo#9491]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## How to use Dubbo's proxyless mesh features?
I'm learning how deploy a proxyless mesh gRPC-xDS application using Dubbo, and I didn't found any documentation explicitly mentioning this feature.

1. How does Dubbo implement [xDS APIs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/dynamic_configuration)?
2. Is it correct assuming that Registration, Configuration, and Metadata centers are Dubbo's control plane like Istio's Pilot and Citadel?
3. Can I use Envoy for Dubbo's governance and cloud features, e.g., routing, load balancing, etc? Do I need to create extensions for using this tool it Dubbo has is built-in?
4. Looking at the [code repo](https://github.com/apache/dubbo/tree/7081b5d48185b045d5d548f21fe9faa0397e425d/dubbo-registry/dubbo-registry-xds/src/main/java/org/apache/dubbo/registry/xds) I learned that Dubbo relies on Istio for xDS registry, how exactly it works, Dubbo uses Istio Control Plane and it doesn't need Envoy for inter-services communication?

**Comment by adalrsjr1** [comment]
diving deep into the code base I got a new question. does this [history](https://github.com/apache/dubbo/pull/7112/commits) implements all features proposed in #6194?

**Comment by jungan21** [comment]
哪位Dubbo社区大佬能帮忙回复一下这个问题啊 ？我们和期望用上Dubbo的Proxless Mesh的能力

![image](https://user-images.githubusercontent.com/11303313/148103791-bb4c9058-bce3-43a9-9f10-0113f2da89e7.png)

**Comment by wenliumeng** [comment]
@jungan21 The proxyless mesh mentioned in the picture actually means that the proxy is placed in dubbosdk, so that dubbosdk can directly connect to the xds server. refer to

```
https://dubbo.apache.org/zh/docs/v3.0/introduction/#service-mesh
为了解决 Sidecar 引入的相关成本问题，Dubbo 引入了另一种变相的 Mesh 架构 - Proxyless Mesh，顾名思义，Proxyless Mesh 就是指没有 Sidecar 的部署，转而由 Dubbo SDK 直接与控制面交互，
```

[dubbo-registry-xds](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-registry-extensions/dubbo-registry-xds)

**Comment by wenliumeng** [comment]
> diving deep into the code base I got a new question. does this [history](https://github.com/apache/dubbo/pull/7112/commits) implements all features proposed in #6194?


I think it's the history you mentioned, now it's moved to [dubbo-registry-xds](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-registry-extensions/dubbo-registry-xds)
