### ISSUE TITLE
org.apache.dubbo.registry.integration.RegistryDirectory疑似内存泄漏

### ISSUE THREAD

**Issue by jxctx88** [apache/dubbo#9509]
**Environment**
Dubbo version: 2.7.12
Java version: 1.8

**Steps to reproduce this issue**
1.网关系统
2.通过泛化调用后台业务系统

**问题**
1、系统有FullGC告警，dump内存分析内存泄漏问题：发现有1万多个org.apache.dubbo.registry.integration.RegistryDirectory这个实例
2、分析是ConsumerConfigurationListener.listeners这个List数组持有的对象，通过分析对象发现这些有很多serviceKey(对应的是接口的类名全路径)重复的对象，其中url中的host有不同的值，ZK-1、ZK-2、ZK-3正好我们有3台zk集群，但是其他的重复发现每种不同的zk有20个重复对象，看不出里面的区别
![image](https://user-images.githubusercontent.com/15684827/147645390-cd904cb8-df4f-4512-9c1f-15eba579a987.png)
上图只是其中一个接口，每个接口的个数还不一样，不清楚这里的具体逻辑

**Comment by jxctx88** [comment]
问题已找到：
1、我们有调用ReferenceConfig.destroy()

**Comment by jgroups** [comment]
> 问题已找到： 1、我们有调用ReferenceConfig.destroy() [3295](https://github.com/apache/dubbo/pull/3295) 也是同样的问题，但是他在2.7.1修复了，我使用的版本是2.7.12还是有这个问题

升级到2.7.15

**Comment by jxctx88** [comment]
谢谢，忘记关闭了，我在 #9558 中已经关闭了该问题
