### ISSUE TITLE
dubbo-2.7.8 使用多版本 调用异常

### ISSUE THREAD

**Issue by 404988672** [apache/dubbo#9513]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: linux
* Java version: 1.8

### Steps to reproduce this issue

消费端配置信息
dubbo:
  cloud:
    subscribed-services:
  registry:
    address: nacos://127.0.0.1:8848
    group: prod
  scan:
    base-packages: ***
  registry:
    check: false
  provider:
    loadbalance: roundrobin
    version: release
  protocol:
    name: dubbo
    port: -1
    serialization: kryo

生产者有两个实例，配置分别为
1、
dubbo:
  cloud:
    subscribed-services:
  registry:
    address: nacos://127.0.0.1:8848
    group: prod
  provider:
    loadbalance: roundrobin
    version: 
  protocol:
    name: dubbo
    port: -1
    serialization: kryo

2、
dubbo:
  cloud:
    subscribed-services:
  registry:
    address: nacos://127.0.0.1:8848
    group: prod
  provider:
    loadbalance: roundrobin
    version: release
  protocol:
    name: dubbo
    port: -1
    serialization: kryo

当消费者连续的发请求，一个成功，一个会失败，失败信息为：
![image](https://user-images.githubusercontent.com/38349390/147739427-76b03032-2605-480d-960f-02126ccc3f5f.png)

**Comment by neighbor-uncleWang** [comment]
Can you provide demo？

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
