### ISSUE TITLE
Dubbo 名称的由来？ What's the name of dubbo stands for?

### ISSUE THREAD

**Issue by donaldjohn** [apache/dubbo#9514]
Nacos is the abbreviation of Naming and Configuration Server, 
Seata means Simple Extensible Autonomous Transaction Architecture, 
so what's is dubbo stands for? I am just a little curious!

Nacos 是 Naming and Configuration Server的缩写， Seata 是  Simple Extensible Autonomous Transaction Architecture 的缩写， 那 Dubbo是什么的缩写？ 或者有什么特殊的含义？好好奇啊，有人解释下么？

**Comment by zouyx** [comment]
Dubbo不是什么的缩写，也不是什么的简称，是澳大利亚的一个“沿海”城市名。

至于为什么是以这个城市来命名呢？据知情人士透露是因为当年的 code name 基本上都是沿着海岸线找的。其他系统也是按照这个规则，选这个也是按照名字顺序或者心情找的。（我还特意看了下聊天记录

所以，故事就是这样。

PS：Dubbo是个美丽而幽静的城市，有空可以去体验一下^-^

**Comment by donaldjohn** [comment]
了解了， 感谢大佬拨冗回复！
