### ISSUE TITLE
In the docker container environment, dubbo 2.7.14+ version use problem

### ISSUE THREAD

**Issue by ChinaJeckXu** [apache/dubbo#9516]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.14、2.7.15
* Operating System version: Linux Centos7.9 Docker 20.10.5
* Java version: 1.8.0_202

### Steps to reproduce this issue

1. docker container start command：docker run -d --name abc --net=host xxx:xxx 
2. In the previous version 2.7.9, the address that dubbo reported to the registry after the container was started was the host IP, such as: [192.168.1.100], this is correct, because the docker start command uses --net=host, However, in the latest version 2.7.14 and 2.7.15, the address reported by dubbo to the registry is the internal IP of the container, such as 172.17.0.1. In this case, in the development environment we usually use, the development machine used by the program developer is Unable to connect to the dubbo service started by the container.

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by juzi214032** [comment]
用的哪个 docker 镜像？

**Comment by juzi214032** [comment]
你用的 jdk 版本是多少，我用 1.8.0_181 测试是没问题的

**Comment by ChinaJeckXu** [comment]
> 你用的 jdk 版本是多少，我用 1.8.0_181 测试是没问题的

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by ChinaJeckXu** [comment]
> 你用的 jdk 版本是多少，我用 1.8.0_181 测试是没问题的

需要说明的是，我之前用的dubbo-2.7.9所在的JDK环境也是1.8.0_202

**Comment by iJIAJIA** [comment]
https://github.com/apache/dubbo/issues/9617
相似的问题。
使用arthas
// 获取NetUtils 实例hash
sc -d *NetUtils 
// 使用ognl调用org.apache.dubbo.common.utils.NetUtils#getValidNetworkInterfaces
ognl -c 7728643a -x 3 '@org.apache.dubbo.common.utils.NetUtils@getValidNetworkInterfaces()'
发现网卡列表里docker0网卡在我们的物理网卡之前
@LinkedList[
    ....
    @NetworkInterface[
        name=@String[docker0],
        displayName=@String[docker0],
    ],
    @NetworkInterface[
        name=@String[ens192],
        displayName=@String[ens192],
    ],
]
2.7.14之前用的break，这只是中断了while循环。2.7.14我猜测是为了修复这个逻辑bug，结果走到docker0之后就退出了。

**Comment by chickenlj** [comment]
related to [在docker环境下部署服务](https://dubbo.apache.org/zh/docs3-v2/java-sdk/advanced-features-and-usage/others/set-host/#%E5%9C%A8%E4%BD%BF%E7%94%A8-docker-%E6%97%B6%E6%9C%89%E6%97%B6%E9%9C%80%E8%A6%81%E8%AE%BE%E7%BD%AE%E7%AB%AF%E5%8F%A3%E6%98%A0%E5%B0%84%E6%AD%A4%E6%97%B6%E5%90%AF%E5%8A%A8-server-%E6%97%B6%E7%BB%91%E5%AE%9A%E7%9A%84-socket-%E5%92%8C%E5%90%91%E6%B3%A8%E5%86%8C%E4%B8%AD%E5%BF%83%E6%B3%A8%E5%86%8C%E7%9A%84-socket-%E4%BD%BF%E7%94%A8%E4%B8%8D%E5%90%8C%E7%9A%84%E7%AB%AF%E5%8F%A3%E5%8F%B7%E6%AD%A4%E6%97%B6%E5%8F%88%E8%AF%A5%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE)
