### ISSUE TITLE
设置retries 为0，测试后还是consumer还是继续重试。

### ISSUE THREAD

**Issue by 283883031** [apache/dubbo#9522]
### Environment

* Dubbo version: 2.7.14
* Operating System version: win10
* Java version: jdk1.8

### Steps to reproduce this issue

1.  <dubbo:consumer check="false" retries="0"/>
2. 服务端抛出异常。
3. 消费者继续请求

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

retries设置为0后，服务端抛出异常，消费端不继续请求

### Actual Behavior

retries设置为0后，服务端抛出异常，消费端仍然继续请求

review code:dubbo:2.7.14, 2.7.15

```
public FailbackClusterInvoker(Directory<T> directory) {
        super(directory);

        int retriesConfig = getUrl().getParameter(RETRIES_KEY, DEFAULT_FAILBACK_TIMES);
        if (retriesConfig <= 0) {
            retriesConfig = DEFAULT_FAILBACK_TIMES;
        }
        int failbackTasksConfig = getUrl().getParameter(FAIL_BACK_TASKS_KEY, DEFAULT_FAILBACK_TASKS);
        if (failbackTasksConfig <= 0) {
            failbackTasksConfig = DEFAULT_FAILBACK_TASKS;
        }
        retries = retriesConfig;
        failbackTasks = failbackTasksConfig;
    }
```
如果小于0，则设置为默认值？

**Comment by juzi214032** [comment]
没问题了吗

**Comment by 283883031** [comment]
刚刚重试了，又没有复现了。&nbsp;

Give you best wishes from your friends Mr.Jz!


&nbsp;

**Comment by juzi214032** [comment]
> 刚刚重试了，又没有复现了。&nbsp; Give you best wishes from your friends Mr.Jz! &nbsp;

我试了一下，确实是有问题的，当 retries 设置为 0 时，会被错误的重置为 3，导致依然会重试，这个我提个 pr 修复一下，你可以把 issue 重新打开一下

**Comment by juzi214032** [comment]
@CrazyHZM I will try to reproduce the whole problem, please assign him to me

**Comment by 283883031** [comment]
上次复现我记得是因为超时了，但是今天我还没复现出这个BUG。

**Comment by juzi214032** [comment]
> 上次复现我记得是因为超时了，但是今天我还没复现出这个BUG。

在 provider 中 Thread.sleep() 一下很容易复现

**Comment by codeimport** [comment]
failback模式下有问题，failover模式没问题。
