### ISSUE TITLE
dubbo 2.7.7 配置validation = "true" 参数校验未生效

### ISSUE THREAD

**Issue by itming001** [apache/dubbo#9544]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by juzi214032** [comment]
hibernate-validator 用的哪个版本

**Comment by juzi214032** [comment]
@CrazyHZM I will try to reproduce the whole problem, please assign him to me

**Comment by itming001** [comment]
> hibernate-validator 用的哪个版本，建议切换到 6.2.1.Final ，目前 dubbo 不支持 7.x 版本的 validator，后续我会提交一个 pr 来支持 7.x 版本的 hibernate-validator

现在用的是6.1.7.Final这一个版本，切换到6.2.1.Final，校验就可以了。

**Comment by juzi214032** [comment]
> > hibernate-validator 用的哪个版本，建议切换到 6.2.1.Final ，目前 dubbo 不支持 7.x 版本的 validator，后续我会提交一个 pr 来支持 7.x 版本的 hibernate-validator
> 
> 
> 
> 现在用的是6.1.7.Final这一个版本，切换到6.2.1.Final，校验就可以了。

我这边测试6.1.7是没问题的，建议看下是不是项目中有依赖传递把7给拉进来了，理论上小于等于6的版本都是没问题的

**Comment by itming001** [comment]
> > > hibernate-validator 用的哪个版本，建议切换到 6.2.1.Final ，目前 dubbo 不支持 7.x 版本的 validator，后续我会提交一个 pr 来支持 7.x 版本的 hibernate-validator
> > 
> > 
> > 现在用的是6.1.7.Final这一个版本，切换到6.2.1.Final，校验就可以了。
> 
> 我这边测试6.1.7是没问题的，建议看下是不是项目中有依赖传递把7给拉进来了，理论上小于等于6的版本都是没问题的

![image](https://user-images.githubusercontent.com/51200523/148671445-34b495e6-2ba8-4a2a-8b72-c0c8820531a0.png)
![image](https://user-images.githubusercontent.com/51200523/148671455-3e87de0e-a9ff-4dc1-b1a8-cc257089e389.png)
我也不知道我这样查的是否正确，但是我们项目中确实依赖的是6.2.1.Final这个版本

**Comment by itming001** [comment]
> > > hibernate-validator 用的哪个版本，建议切换到 6.2.1.Final ，目前 dubbo 不支持 7.x 版本的 validator，后续我会提交一个 pr 来支持 7.x 版本的 hibernate-validator
> > 
> > 
> > 现在用的是6.1.7.Final这一个版本，切换到6.2.1.Final，校验就可以了。
> 
> 我这边测试6.1.7是没问题的，建议看下是不是项目中有依赖传递把7给拉进来了，理论上小于等于6的版本都是没问题的



> > > > hibernate-validator 用的哪个版本，建议切换到 6.2.1.Final ，目前 dubbo 不支持 7.x 版本的 validator，后续我会提交一个 pr 来支持 7.x 版本的 hibernate-validator
> > > 
> > > 
> > > 现在用的是6.1.7.Final这一个版本，切换到6.2.1.Final，校验就可以了。
> > 
> > 
> > 我这边测试6.1.7是没问题的，建议看下是不是项目中有依赖传递把7给拉进来了，理论上小于等于6的版本都是没问题的
> 
> ![image](https://user-images.githubusercontent.com/51200523/148671445-34b495e6-2ba8-4a2a-8b72-c0c8820531a0.png) ![image](https://user-images.githubusercontent.com/51200523/148671455-3e87de0e-a9ff-4dc1-b1a8-cc257089e389.png) 我也不知道我这样查的是否正确，但是我们项目中确实依赖的是6.1.7.Final这个版本

<dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-validation</artifactId>
</dependency>
项目中的中直接是这样引用的，这样我试了下貌似不行。

**Comment by juzi214032** [comment]
你们的 springboot 版本是多少 @itming001

**Comment by itming001** [comment]
> 



> 你们的 springboot 版本是多少 @itming001

可以了兄弟，应该是没有问题的。 @juzi214032
