### ISSUE TITLE
default load policy can not correctly obtain the weights of registries

### ISSUE THREAD

**Issue by codeimport** [apache/dubbo#9546]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.15
* Operating System version: windows 10
* Java version: 8

### Steps to reproduce this issue
    Different registries are configured with different weights, but the weights are not effective. The reason is that the default load policy can not correctly obtain the weights of registries, and can only obtain the weights of ordinary providers.

     consumer config like that:     

    <dubbo:registry id = "main" address="zookeeper://${zookeeper.address:127.0.0.1}:2181" weight="1"/>

    <dubbo:registry id = "slave" address="zookeeper://${zookeeper.address:127.0.0.1}:2182" weight="100"/>

    <dubbo:reference id="demoService" check="false" interface="com.example.DemoService" registry="main,slave"/>

Pls. provide [GitHub address] to reproduce this issue.

### consumer use slave registry center

consumer use main registry center

```
Just put your stack trace here!
```

**Comment by codeimport** [comment]
i will fix it

**Comment by zrlw** [comment]
你这么改就把多注册中心用的dubbo.registries.xxx.weight配置搞废了，registries这种是多中心的一种配置形式，比registry多了一层。

**Comment by zrlw** [comment]
it seemed that ```RegistryConfig.getWeight()``` lost ```@Parameter(key =  "registry.weight") , see #7788
