### ISSUE TITLE
New contributor guide 404

### ISSUE THREAD

**Issue by lmm1990** [apache/dubbo#9554]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

Dubbo version: 3.0.5
Operating System version: windows 11
Java version: 1.8

### Steps to reproduce this issue

1. https://github.com/apache/dubbo/wiki/New-contributor-guide
2. click http://dubbo.apache.org/en-us/docs/developers/contributor-guide/new-contributor-guide_dev.html 404

**Comment by juzi214032** [comment]
this link is avaliable

https://github.com/apache/dubbo-website/blob/master/content/en/docs/contribution-guidelines/contributor/new-contributor-guide_dev.md

**Comment by juzi214032** [comment]
> This link is avaliable
> 
> https://dubbo.apache.org/en/docs/contribution-guidelines/

Can someone fix this link? @chickenlj  @AlbumenJ

**Comment by biyuhao** [comment]
Thanks for reporting this, it has been fixed.
