### ISSUE TITLE
3.x和2.6.3的group兼容问题

### ISSUE THREAD

**Issue by cadeeper** [apache/dubbo#9557]
### 问题描述
如果提供者是2.6.x，消费者是3.x，并且有提供分组和未分组两类提供者，那么会出现**Not found exported service**异常

### 可能的原因
UrlUtils.isMatch方法中，会通过验证consumer的group和provider的group是否一致，来匹配对应提供者。 如果提供者是2.6.3，他的url中的group会是null值，在3.x中，providerURL实现为：**ServiceAddressURL**，在ServiceAddressURL中获取group分组时，**_如果group为null，那么他会取 consumer的分组_**，这样会导致有分组的消费者会匹配到正常的分组提供者和没有分组的提供者。

#### 问题
1、 如果获取不到提供者分组，则获取消费者分组的原因是？
2、 3.x是否可以兼容低版本的dubbo？

**Comment by juzi214032** [comment]
Not found exported service 是服务端报的，还是消费端报的

**Comment by cadeeper** [comment]
> Not found exported service 是服务端报的，还是消费端报的

服务端，因为调到了未非组的服务端，没有对应的分组接口

**Comment by wangchengming666** [comment]
理论上上dubbo2和dubbo3是不能通信的吧，比如你的这种场景提供者是2.6.x，消费者是3.x

**Comment by cadeeper** [comment]
> 理论上上dubbo2和dubbo3是不能通信的吧，比如你的这种场景提供者是2.6.x，消费者是3.x

2和3是不兼容的吗？ 但是如果不是这样的分组情况的话，是可以正常调用的哦。

**Comment by wangchengming666** [comment]
> > 理论上上dubbo2和dubbo3是不能通信的吧，比如你的这种场景提供者是2.6.x，消费者是3.x
> 
> 2和3是不兼容的吗？ 但是如果不是这样的分组情况的话，是可以正常调用的哦。

抱歉，我理解错了

**Comment by codeimport** [comment]
建议consumer与provider都是用同一版本，3.0升级挺大的，应该不能完全保证兼容2的版本。

**Comment by cadeeper** [comment]
> 建议consumer与provider都是用同一版本，3.0升级挺大的，应该不能完全保证兼容2的版本。

3.0是作为一个新框架，和2.x的用户割裂嘛。 2.x如果想到升级到3.x，不可能一次性全部更换可以服务的版本的

**Comment by chickenlj** [comment]
> 在ServiceAddressURL中获取group分组时，如果group为null，那么他会取 consumer的分组，这样会导致有分组的消费者会匹配到正常的分组提供者和没有分组的提供者。

@cadeeper 感谢反馈，此问题已经定位；在3.x 版本的接口级地址模型中确实存在，我们将会在 3.0.7 版本中予以修复。
