### ISSUE TITLE
BigDecimal is converted to scientific notation when using Generic

### ISSUE THREAD

**Issue by kclizhiwei** [apache/dubbo#9562]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.13
* Operating System version: MacOS 12.1 
* Java version: 11

### Steps to reproduce this issue
consumer code :

```java
ReferenceConfig<GenericService> reference = new ReferenceConfig<>();
ApplicationConfig applicationConfig = new ApplicationConfig();
applicationConfig.setName("dubbo-provider");
RegistryConfig registryConfig = new RegistryConfig();
registryConfig.setAddress("zookeeper://127.0.1:2181");
reference.setApplication(applicationConfig);
reference.setRegistry(registryConfig);
reference.setProtocol("dubbo");
reference.setInterface("com.msnu.demo.provider.OrderService");
reference.setVersion("1.0.0");
reference.setTimeout(1000);
reference.setGeneric("true");
GenericService genericService = reference.get();
Order order = new Order("20220110172900001", new BigDecimal(10000000.00));
String orderJson = objectMapper.writeValueAsString(order);
// The  price attribute type is Long in linkedHashMap
LinkedHashMap linkedHashMap = objectMapper.readValue(orderJson, LinkedHashMap.class);
Object result = genericService.$invoke(
        "queryOrder",
        new String[]{"com.msnu.demo.provider.OrderDto"},
        new Object[]{linkedHashMap});
System.out.println(result);
```

provide code :

```java
public class OrderServiceImpl implements OrderService{
    @Override
    public OrderDto queryOrder(OrderDto orderDto) {
        System.out.println(orderDto);
        return orderDto;
    }
}
```
Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

result is {orderId=20220110172900001, price=10000000, class=com.msnu.demo.provider.OrderDto}
### Actual Behavior

If there is an exception, please attach the exception trace:
result is {orderId=20220110172900001, price=1.0E+7, class=com.msnu.demo.provider.OrderDto}

The analysis is as follows：
code:
```java
org.apache.dubbo.common.utils.CompatibleTypeUtils#compatibleTypeConvert
```
line : 173
```java
if (type == BigDecimal.class) {
     return BigDecimal.valueOf(number.doubleValue());
 }
```
  If I use <b>new BigDecimal(number.doubleValue())</b>, can fix this problem

**Comment by tanoak10** [comment]
This problem has been fixed: #9576

**Comment by tanoak10** [comment]
This problem has been fixed: #9692

**Comment by tanoak10** [comment]
@kclizhiwei  You can't use it like this BigDecimal.valueOf() method ,look https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#BigDecimal(double)

**Comment by gitchenjh** [comment]
It is not a bug of dubbo  
BigDecimal#toString() transefered to scientific notation while it's needed  
![image](https://user-images.githubusercontent.com/24949156/157832196-b2bf011f-0650-46c9-b4c0-4fb70ff611bb.png)  
![image](https://user-images.githubusercontent.com/24949156/157832363-a3a20727-80d6-4a3b-97f5-c34c341c1c86.png)
