### ISSUE TITLE
Dubbo支持多个重载方法调用吗？

### ISSUE THREAD

**Issue by daidai21** [apache/dubbo#9573]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by EarthChen** [comment]
理论上是支持的 有做处理，能给个复现的 demo嘛

**Comment by monkeycraps** [comment]
为啥日志最后显示：
... 当前dubbo版本[2.15.0.RELEASE]

**Comment by monkeycraps** [comment]
> ```shell
> com.alibaba.dubbo.remoting.RemotingException: java.lang.IllegalStateException: Not unique method for method name(searchUserInfo) in class(com.companyname.groupname.DemoService), find 2 methods.
> java.lang.IllegalStateException: Not unique method for method name(searchUserInfo) in class(com.companyname.groupname.DemoService), find 2 methods.
> 	at com.alibaba.dubbo.common.utils.ReflectUtils.findMethodByMethodSignature(ReflectUtils.java:808)
> 	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:62)
> 	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:108)
> 	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:39)
> 	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:108)
> 	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
> 	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:108)
> 	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:93)
> 	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:89)
> 	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received$original$NqbVQaNw(HeaderExchangeHandler.java:203)
> 	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received$original$NqbVQaNw$accessor$ThxnG4m7(HeaderExchangeHandler.java)
> 	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler$auxiliary$f7hylC38.call(Unknown Source)
> 	at com.pdd.service.ptracer.boot.api.injector.enhance.InstanceMethodEnhancer.enhance(InstanceMethodEnhancer.java:61)
> 	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java)
> 	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
> 	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
> 	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:52)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
>  结果: 调用远程方法未知异常. 方法名: $invoke,  调用接口: [com.alibaba.dubbo.rpc.service.GenericService]的方法: [$invoke]失败. 从注册中心: [st1-tdubbo-zk-a-1.host.xxxxx.net:2181]上的的消费者: [152.4.231.10]重试调用提供者[[152.4.231.10:45925](1/2)]1次, 当前dubbo版本[2.15.0.RELEASE]
> ```

为啥日志最后显示：
... 当前dubbo版本[2.15.0.RELEASE]

**Comment by EarthChen** [comment]
dubbo 2.15?  似乎没有这个版本阿？   看堆栈打印的是 alibaba 的包名，至少是2.7之前的版本，可能不支持，但目前2.7和3.0都是支持重载调用的

**Comment by monkeycraps** [comment]
只有参数为空，才会抛这个错误 
![image](https://user-images.githubusercontent.com/2322555/149617376-8e352f28-a0fe-4388-a186-152f5d1d30ef.png)

**Comment by daidai21** [comment]
明白了，公司用的看来版本有些老了，感谢 @EarthChen
