### ISSUE TITLE
很多调用URL.getMethodParameter方法的key都没有在Method定义

### ISSUE THREAD

**Issue by zrlw** [apache/dubbo#9574]
比如master分支下列调用使用的key都没有在Method里定义。
1. AbstractLoadBalance的WEIGHT_KEY：  
```
            weight = url.getMethodParameter(invocation.getMethodName(), WEIGHT_KEY, DEFAULT_WEIGHT);
```
2. ConsistentHashLoadBalance的HASH_NODES和HASH_ARGUMENTS：  
```
            this.replicaNumber = url.getMethodParameter(methodName, HASH_NODES, 160);
            String[] index = COMMA_SPLIT_PATTERN.split(url.getMethodParameter(methodName, HASH_ARGUMENTS, "0"));
```
3. MockClusterInvoker的MOCK_KEY:
```
        String value = getUrl().getMethodParameter(invocation.getMethodName(), MOCK_KEY, Boolean.FALSE.toString()).trim();
```
4. JCache的"cache.write.expire":
```
                MutableConfiguration config =
                        new MutableConfiguration<>()
                                .setTypes(Object.class, Object.class)
                                .setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(new Duration(TimeUnit.MILLISECONDS, url.getMethodParameter(method, "cache.write.expire", 60 * 1000))))
                                .setStoreByValue(false)
                                .setManagementEnabled(true)
                                .setStatisticsEnabled(true);

```
5. RpcUtils的AUTO_ATTACH_INVOCATIONID_KEY和RETURN_KEY:
```
        String value = url.getMethodParameter(invocation.getMethodName(), AUTO_ATTACH_INVOCATIONID_KEY);
          ...
            isOneway = !url.getMethodParameter(getMethodName(inv), RETURN_KEY, true);
```
这些key无法通过Method注解的方式进行配置，那么上述这些代码要怎么用？
比如第一个AbstractLoadBalance的这个WEIGHT_KEY，看起来是从URL获取method的权重，应用要怎么设置才能执行到这一行代码呢？

**Comment by monkeycraps** [comment]
我理解你说的是 registry 的配置 weight 
![image](https://user-images.githubusercontent.com/2322555/149617142-3cd7461e-1a45-471e-b421-630939636ecc.png)

看 getWeight 的测试类如下 
![image](https://user-images.githubusercontent.com/2322555/149617080-34537c01-1d46-45ec-85fe-995cbec1e707.png)

**Comment by zrlw** [comment]
getWeight这个测试类是直接mock加的参数，但是实际运行时要怎么给URL加这个参数?我搜了一下并没有找到给URL加这个参数的代码。
无论用xml配置```<dubbo:method name="xxx" weight="nn" />```还是用```@DubboReference(methods = {@Method(name = “xxx”,  weight=nn)})``注解设置weight都会提示weight参数不识别，那么这个参数要怎么才能用起来呢？

**Comment by zrlw** [comment]
#9546 这个问题也和AbstractLoadBalance的getWeight方法相关，这个方法的第一个入参invoker的类型难道不都是ClusterInvoker类型（我debug跟踪了几个测试类都是MigrationInvoker）？如果都是ClusterInvoker类型，那么这个方法从ClusterInvoker.getRegistryUrl返回的url直接取权重就好了，不用那么多分支判断了吧。

**Comment by codeimport** [comment]
There is such a problem

**Comment by chickenlj** [comment]
>这些key无法通过Method注解的方式进行配置，那么上述这些代码要怎么用？

注解是秉承最小易用原则。如果需要配置这些参数，请按照dubbo配置标准格式，通过在 properties 文件中进行配置
