### ISSUE TITLE
tag路由不生效

### ISSUE THREAD

**Issue by chenjian5** [apache/dubbo#9592]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Operating System version: macos
* Java version: 1.8

### Steps to reproduce this issue

1. 在生产者和消费者的yml里分别配置 dubbo:consumer/provider:tag = test，生产者再起一个服务配 tag = qa
2. 生产者配置
 dubbo:
  scan:
    base-packages: xxxxxx
  application:
    name: ${spring.application.name}
    parameters:
      machine-room: xxxxx
  protocol:
    name: tri
    port: 8090
    serialization: protobuf
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}
  provider:
    tag: nz
消费者配置
dubbo:
  application:
    name: ${spring.application.name}
    parameters:
      machine-room: xxxx
  consumer:
    timeout: 5000
    tag: nz
  registries:
    test:
      protocol: nacos
      address: xxxxxxx:8848

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

配置了 tag =test 的消费者只请求 tag= test的生产者

### Actual Behavior

配置了 tag =test 的消费者会轮循 tag= test\qa 两个生产者。
debug发现，在TagRouter.filterUsingStaticTag 中，163行的tag.equals(invoker.getUrl().getParameter(TAG_KEY))，invoker.getUrl().getParameter(TAG_KEY)底层获取的是conumerUrl的param，导致所有的生产者invoker.getUrl().getParameter(TAG_KEY)和tag变量一直是equals true，没有过滤掉

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by CrazyHZM** [comment]
Try it with 3.0.5, I tried it and found that it didn't reproduce.
@chenjian5

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily. If there is still a problem, you can reopen it.
