### ISSUE TITLE
@DubboReference  parameters  do not put into methodParameters correctly!

### ISSUE THREAD

**Issue by wangzhenxyz1** [apache/dubbo#9597]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.15
* Operating System version: Mac OS
* Java version: 1.8

### Steps to reproduce this issue

1. Add @DubboReference(parameters = {"xxx.mock", "force:return fake"}
2. Startup consumer without providers
3. xxx method's mock do not degrade

### Expected Behavior

xxx method's mock can degrade!

### Actual Behavior

xxx method's mock do not degrade

**Comment by CrazyHZM** [comment]
Fixed in https://github.com/apache/dubbo/pull/9599
