### ISSUE TITLE
dubbo IOC:SpringExtensionInjector context is null

### ISSUE THREAD

**Issue by wuyongCloud** [apache/dubbo#9602]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master;  last commitId:65bd70b54c87539ccc843b938479f0b7c2ea8d20 
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

使用的是 dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer
1. 自定义Bean(MyServiceImpl)。xml注入spring容器
2. 自定义Myfilter实现 Filter；META-INF/debbo com.alibaba.dubbo.rpc.Filter(myfilter=org.apache.dubbo.demo.filter.Myfilter)
3. Myfilter 引用 MyServiceImpl，有set和get方法
4. dubbo-consumer.xml  : <dubbo:reference id="demoService" check="false" interface="org.apache.dubbo.demo.DemoService" filter="myfilter"/>

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

加载Myfilter，调用injectExtension(instance) -> SpringExtensionInjector 内的context 是null 无法完成IOC 注入 

If there is an exception, please attach the exception trace:

```
![image](https://user-images.githubusercontent.com/41030862/150333739-62be4fad-dd09-4d8f-a7b7-34b9a8716fcd.png)
```

**Comment by juzi214032** [comment]
可以给一个可复现 demo 吗

**Comment by rainwolf01** [comment]
应该是一样的问题 https://github.com/apache/dubbo/issues/8793

**Comment by wuyongCloud** [comment]
> 可以给一个可复现 demo 吗

用的官方的Demo dubbo-demo/dubbo-demo-xml/dubbo-demo-xml-consumer
MyServiceImpl 注入spring，里面什么内容也没有
Myfilter 里是空实现，注入MyServiceImpl 
还有需要提供的细节吗

**Comment by CrazyHZM** [comment]
Fixed in https://github.com/apache/dubbo/pull/9636
