### ISSUE TITLE
Triple 协议线程模型与 Dubbo 协议线程模型不一样

### ISSUE THREAD

**Issue by Cuihongsen** [apache/dubbo#9606]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here

dubbo version: 3.0.5

Triple 实际使用中发现，与文档中[线程模型](https://dubbo.apache.org/zh/docs/advanced/thread-model/)不一致，配置了 fixed 线程池，但是无论怎么压测线程池均无活跃线程，后来排查的 Triple 协议下均在 io 线程上执行的逻辑，与 Dispatcher 和 ThreadPool 的配置无关。
请问这是出于什么考虑设计成这样？

**Comment by Cuihongsen** [comment]
Found in the actual use of the Triple protocol，The actual phenomenon is inconsistent with the threading model in the documentation，Fixed thread pool configured，But no matter how the stress test thread pool has no active threads。
It was later found that，Logic executed on the io thread under the Triple protocol，Regardless of the configuration of Dispatcher and ThreadPool.
May I ask why this is designed in this way?

**Comment by wuwangben** [comment]
+1

**Comment by ilaotan** [comment]
+1

**Comment by ilaotan** [comment]
另外也不走SPI模式了.哎

**Comment by ilaotan** [comment]
关联问题 #10018  ,好像是由于metadata-service-protocol 走的dubbo. 导致了dubbo协议占用了线程池.  tri协议就没拿到.

**Comment by wangchengming666** [comment]
fixed by https://github.com/apache/dubbo/pull/10019
