### ISSUE TITLE
dubbo 3.0.4 + nacos 2.0.3 registry group 配置对服务隔离不生效

### ISSUE THREAD

**Issue by lijiaxing3045354** [apache/dubbo#9621]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.4
* Java version: 1.8

### Steps to reproduce this issue

服务端配置<dubbo:registry protocol="nacos" address="nacos url" group="test" register="true"/>
消费端配置<dubbo:registry protocol="nacos" address="nacos url" group="local" register="true"/>
其他地方未设置group，分组为local的消费端调用到了 test分组的服务，2.7.X版本的dubbo没有遇到此问题。
nacos的元数据配置都有正常显示group
请帮忙看看次问题，多谢！

**Comment by CrazyHZM** [comment]
@lijiaxing3045354 Does 3.0.5 have the same problem?

**Comment by lijiaxing3045354** [comment]
@CrazyHZM consumer version 3.0.5，provider version 3.0.4，can be reproduced this problem

**Comment by neighbor-uncleWang** [comment]
> 3.0.

为什么会出现消费者和生产者版本不一致呢？

**Comment by neighbor-uncleWang** [comment]
> @CrazyHZM消费者版本3.0.5，提供者版本3.0.4，可以重现这个问题

为什么会出现消费者和生产者版本不一致呢？

**Comment by lijiaxing3045354** [comment]
因为修改生产者版本麻烦一些，所以只改了消费者的dubbo版本，个人猜测这个问题是消费者端产生的，因为在nacos能看到包含group的正确注册信息

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/9621
