### ISSUE TITLE
dubbo消费端启动报错-在线急

### ISSUE THREAD

**Issue by linkintest** [apache/dubbo#9635]
![image](https://user-images.githubusercontent.com/83860035/151304642-58165981-d929-4227-83a8-1c5366e58813.png)

**Comment by linkintest** [comment]
![image](https://user-images.githubusercontent.com/83860035/151305005-b49552af-423b-4bc9-9dbc-b4b952801418.png)

**Comment by linkintest** [comment]
![image](https://user-images.githubusercontent.com/83860035/151305352-db870c94-4c51-4885-a945-10254d7bd886.png)

**Comment by linkintest** [comment]
consumers一直启动不成功

**Comment by juzi214032** [comment]
consumer 里面 check设置成false吧

**Comment by CrazyHZM** [comment]
@linkintest 
主要原因是从注册中心中没有发现可用的服务节点。尝试在reference的配置中添加check=false来解决。或者先启动Provider，进行服务注册，再启动consumer。
