### ISSUE TITLE
引入Dubbo后，项目启动失败

### ISSUE THREAD

**Issue by 7rikka** [apache/dubbo#9648]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
搭建spring cloud项目，引入dubbo之后项目启动失败
完整错误日志：[https://github.com/7rikka/dubbo-demo/blob/master/error.log](url)
demo：[https://github.com/7rikka/dubbo-demo](url)

**Comment by monkeycraps** [comment]
mvn -v 输出信息确认下，看看使用的 jdk 版本，maven 版本 
如果是 idea 开启的，检查对应版本，试试换版本

**Comment by 7rikka** [comment]
更换jdk为jdk15，问题解决
