### ISSUE TITLE
某一个长连接偶发 Invoke remote method timeout

### ISSUE THREAD

**Issue by CantosSong** [apache/dubbo#9654]
### Environment

* Dubbo version: 2.7.12
* Operating System version: CentOS Linux release 7.9.2009 (Core)
* Java version: 1.8.0_232

### Steps to reproduce this issue
偶发现象：线上运行过程中，某一个长连接出现调用超时，Server端200ms，Client端6000ms(超时时间6000ms)

已知情况
1. Server端升级到2.7.12之后出现的问题
2. Client端有2.5.x和2.7.12在调用Server端都出现了此问题
3. 偶发性问题，长连接存在就会偶发出现，例如3小时中共请求了1000次，其中100次左右超时
![image](https://user-images.githubusercontent.com/15994261/152730795-2361d4a2-8da5-41bc-a43c-7fe04bec79f6.png)

### Expected Behavior

预期不出现超时的情况

### Actual Behavior
此问题为偶发性问题

Failed to invoke the method * in the service *. Tried 1 times of the providers [10.7.49.41:20883] (1/3) from the registry zk1:2181 on the consumer ip1 using the dubbo version 2.7.12. Last error is: Invoke remote method timeout.

**Comment by chency147** [comment]
您好，请问一下这个问题后来您是如何解决的？我这边也遇到了类似的问题。

**Comment by CantosSong** [comment]
> 您好，请问一下这个问题后来您是如何解决的？我这边也遇到了类似的问题。

client 升级到新版本就没问题了
