### ISSUE TITLE
自定义Filter中通过 setXX 的方式注入 bean 失败

### ISSUE THREAD

**Issue by lj-example** [apache/dubbo#9656]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.8
* Operating System version: mac
* Java version: jdk8

### Steps to reproduce this issue

1. dubbo-spring-boot-starter 集成 spring-boot 2.4.13
2. 自定义 Filter 中通过 set 的方式注入 springBean 会出现注入失败的情况
``` java
@Slf4j
@Configuration
@RequiredArgsConstructor
@Activate(order = Ordered.LOWEST_PRECEDENCE)
public class ProviderLogFilter implements Filter {


    private CrmProviderConfig providerConfig;

    public void setProviderConfig(CrmProviderConfig providerConfig) {
        this.providerConfig = providerConfig;
    }

}
```
3. 在 2.7.3 版本没有问题，经过查阅代码发现在 BeanFactoryUtils 中

```
        // Issue : https://github.com/alibaba/spring-context-support/issues/20
        String[] allBeanNames = beanNamesForTypeIncludingAncestors(beanFactory, beanType, true, false);
       // 此处的返回的 beanNames 与实际的 beanName 不一致，导致 containsElement 判断失败，不会执行 set方法。
      // 实际的beanName 为 `providerConfig` ，通过如上方式获取的 beanName 为`spring.dubbo.provider-xxx.xxx.config.CrmProviderConfig`     

        List<T> beans = new ArrayList<T>(beanNames.length);

        for (String beanName : beanNames) {
            if (containsElement(allBeanNames, beanName)) {
                beans.add(beanFactory.getBean(beanName, beanType));
            }
        }
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior
不是很理解 `  if (containsElement(allBeanNames, beanName)) ` 判断的原因

**Comment by lj-example** [comment]
还有在 2.7.8 的版本如何关闭 系统自动注入的那个 `ApplicationConfig` 啊 自定义了之后，启动项目就会出现 Expected single matching of application, but found 2 instances, will randomly pick the first one.

**Comment by dy-only** [comment]
我这里使用最新版本 3.0.5 同样注入不进去。3.0.2可以，不知道是不是同一个原因。

**Comment by lj-example** [comment]
> 

可以考虑追踪下 如上的代码位置，在 2.7.3版本是直接 Application.getBean 来获取的，后面就换了种方式，如上的代码会导致判断Bean 失败。你看看是不是也是同样的问题。

**Comment by chickenlj** [comment]
在最新的 3.0.6 版本开始，修复了类似注入问题，请确认是否已修复：https://github.com/apache/dubbo/pull/9636
