### ISSUE TITLE
Dubbo消费者无法使用registry_zone主动选择指定注册中心的服务

### ISSUE THREAD

**Issue by 18205097282** [apache/dubbo#9668]
本地有两个nacos机房，zone各自设置为A和B。

消费者启动两个接口想要分别调用机房A的服务1，和机房B的服务1。（这里服务1的端口号不同）
接口1：
RpcContext.getContext().setAttachment("registry_zone", "A");
接口2：
RpcContext.getContext().setAttachment("registry_zone", "B");

实验发现每次启动消费者  会随机出现以下三种情况：
只去A机房找服务
只去B机房找服务
按照setAttachment("registry_zone", "B")  setAttachment("registry_zone", "A")指定的机房找服务，也就是正常工做。

这种随机是按消费者启动随机的，启动后，随机到哪一种情况就永恒不变了。

**Comment by neighbor-uncleWang** [comment]
你好，Dubbo和Nacos的版本多少呢？是否方便提供一个demo用于演示呢？

**Comment by 18205097282** [comment]
> 你好，Dubbo和Nacos的版本多少呢？是否方便提供一个demo用于演示呢？

Dubbo2.7.14 nacos1.3.2 Demo在公司内网，我们debug走ZoneAwareClusterInvoker的代码
`       String zone = invocation.getAttachment(REGISTRY_ZONE);
        if (StringUtils.isNotEmpty(zone)) {
            for (Invoker<T> invoker : invokers) {
                ClusterInvoker<T> clusterInvoker = (ClusterInvoker<T>) invoker;
                if (clusterInvoker.isAvailable() && zone.equals(clusterInvoker.getRegistryUrl().getParameter(ZONE_KEY))) {
                    return clusterInvoker.invoke(invocation);
                }
            }`
这段代码都正确选择到了对的注册中心

**Comment by 18205097282** [comment]
> 你好，Dubbo和Nacos的版本多少呢？是否方便提供一个demo用于演示呢？

而且，除了不能指定去哪个注册中心之外，其他功能都正常的，比如消费者只找A注册中心的服务1，A的服务1下线了，它就会去B注册中心找服务1了。
