### ISSUE TITLE
graceful shutdown从3.0.3开始有问题. 3.0.2.1没事.

### ISSUE THREAD

**Issue by ilaotan** [apache/dubbo#9670]
dubbo3.0.5有问题.
dubbo3.0.5降级到2.7.15. 测试没问题.
dubbo3.0.5降级到3.0.2.1 测试没问题.
从3.0.2.1升级到3.0.3 复现问题了. 是3.0.3改过什么东西影响了?

我看阿里的人已经注意到这个问题了.  #9422

**Comment by chickenlj** [comment]
Thanks for the report. I will continue to check this issue within 3.0.7

**Comment by chickenlj** [comment]
Please follow https://github.com/apache/dubbo/issues/9422 for further updates
