### ISSUE TITLE
dubbo 2.7.15配置文件中的dubbo.scan.base-packages失效

### ISSUE THREAD

**Issue by dongmaxiang** [apache/dubbo#9672]
### Environment

* Dubbo version: 2.7.15
* Operating System version: mac os
* Java version: 1.8

### Steps to reproduce this issue

1. 2.7.15
2. 配置文件yml配置dubbo扫描的的包路径：dubbo.scan.base-packages
3. man方法所在的启动类上添加@EnableDubbo

### Expected Behavior
可以扫描yml配置文件中的packages

### Actual Behavior
实际上扫描不到

### 问题我也找到了，就是不知道直接提交代码修复还是提Issue。
2.7.8是可以存在多个ServiceClassPostProcessor的，也就是说配置文件中的base-packages可以扫描
@EnableDubbo(scanBasePackages="your packages")注解上的也可以扫描。
但是2.7.15就只允许注册一个，不知道设计的目的是什么？

```java
@ConditionalOnProperty(prefix = DUBBO_PREFIX, name = "enabled", matchIfMissing = true)
@Configuration
@AutoConfigureAfter(DubboRelaxedBindingAutoConfiguration.class)
@EnableConfigurationProperties(DubboConfigurationProperties.class)
@EnableDubboConfig
public class DubboAutoConfiguration implements ApplicationContextAware, BeanDefinitionRegistryPostProcessor {

    @ConditionalOnProperty(prefix = DUBBO_SCAN_PREFIX, name = BASE_PACKAGES_PROPERTY_NAME)
    @ConditionalOnBean(name = BASE_PACKAGES_BEAN_NAME)
    @ConditionalOnMissingBean// 就是在这里，2.7.8没有这个条件，2.7.15就有了，这是出于什么目的呢？
    @Bean
    public ServiceClassPostProcessor serviceClassPostProcessor(@Qualifier(BASE_PACKAGES_BEAN_NAME)
                                                                       Set<String> packagesToScan) {
        return new ServiceClassPostProcessor(packagesToScan);
    }
```

**Comment by 24kpure** [comment]
In most case,this bean init in `DubboRelaxedBindingAutoConfiguration`.Btw, can you provide  provide a demo to reproduce i?
```
    @ConditionalOnMissingBean(name = BASE_PACKAGES_BEAN_NAME)
    @Bean(name = BASE_PACKAGES_BEAN_NAME)
    public Set<String> dubboBasePackages(Environment environment) {
        PropertyResolver propertyResolver = dubboScanBasePackagesPropertyResolver(environment);
        return propertyResolver.getProperty(BASE_PACKAGES_PROPERTY_NAME, Set.class, emptySet());
    }
```

**Comment by dongmaxiang** [comment]
> In most case,this bean init in `DubboRelaxedBindingAutoConfiguration`.Btw, can you provide provide a demo to reproduce i?
> 
> ```
>     @ConditionalOnMissingBean(name = BASE_PACKAGES_BEAN_NAME)
>     @Bean(name = BASE_PACKAGES_BEAN_NAME)
>     public Set<String> dubboBasePackages(Environment environment) {
>         PropertyResolver propertyResolver = dubboScanBasePackagesPropertyResolver(environment);
>         return propertyResolver.getProperty(BASE_PACKAGES_PROPERTY_NAME, Set.class, emptySet());
>     }
> ```

Sorry, I posted the wrong code, it should be @conditionalonmissingBean, I hava corrected issues

**Comment by chickenlj** [comment]
Please submit a pull request directly to here

**Comment by dongmaxiang** [comment]
> 

哦哦，3.0版本我看已经被别人修复了。[修复commit](https://github.com/apache/dubbo/commit/f07640fc7455726c841b009492dc5edf5f11c6d1#diff-b56fc01a35ad220796094b6fde449b1120b243d20fcbbe6f7878d2b21bf4909cL74)
