### ISSUE TITLE
dubbo 2.7.14 指定zone的功能不起作用

### ISSUE THREAD

**Issue by elvislou** [apache/dubbo#9673]
使用Dubbo的多注册中心和Zone 功能，想通过zone机制跨机房部署dubbo服务。

假设有机房A和机房B，分别部署了nacos注册中心，我们叫nacosA和nacosB
![dubbo_nacos](https://user-images.githubusercontent.com/51158416/153413259-61a00b4f-3fb4-4ccc-91df-e331da3ad411.png)

现在在机房A部署一个dubbo服务，注册到nacosA
在机房B部署同一个dubbo服务，注册到nacosB

现在想要做到的效果是：部署在机房A的消费者，需要优先调用机房A的dubbo服务，只有当机房A没有服务的时候，
再调用机房B的服务

根据网上资料和dubbo源码，我们是通过调用前设置
RpcContext.getContext().setAttachment("registry_zone", "A");
来实现的（provider配置文件声明registry的时候，nacosA指定了zone参数为“A”，nacosB指定了zone参数为“B”）。

另外consumer的配置文件中同时声明了两个注册中心nacosA和nacosB

但结果是，不起作用，有时候会调用机房A的服务，有时候会调用到机房B的服务，

dubbo版本是2.7.14

demo见附件
[dubbo_zone_demo.zip](https://github.com/apache/dubbo/files/8040826/dubbo_zone_demo.zip)
。

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/9679

能否按照这个issue给的方式看一下执行情况

**Comment by acmday** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/61953741/161893413-4fe2ce7c-aa16-4095-90b2-41db03b14546.png">

**Comment by acmday** [comment]
I will fix it

**Comment by acmday** [comment]
![image](https://user-images.githubusercontent.com/61953741/163305725-026fb3b2-d91b-4138-8137-5f388fcae277.png)

用你的demo debug复现看了下，导致你这个问题的原因是你没有配置cluster="failsafe" 。你需要在你的配置文件中暴露和发现服务的时候，加上cluster="failsafe" 这个配置，否则会因为isAvailable=false，导致你说的这个问题。修复后的demo链接：https://github.com/acmday/dubbo_zone_demo，感兴趣可以clone验证下。

**Comment by acmday** [comment]
![image](https://user-images.githubusercontent.com/61953741/163309066-db81a1ba-48d2-4593-a1c7-d57c83fd3762.png)

用你的demo debug复现看了下，导致你这个问题的原因是你没有配置cluster="failsafe" 。你需要在你的配置文件中暴露和发现服务的时候，加上cluster="failsafe" 这个配置，否则会因为isAvailable=false，导致你说的这个问题。修复后的demo链接：https://github.com/acmday/dubbo_zone_demo，
感兴趣的朋友可以clone验证下。

**Comment by elvislou** [comment]
@acmday 
我们后来调试出来，是因为这个bug导致的。
https://github.com/apache/dubbo/issues/8838

目前官方应该还没有修复。

**Comment by acmday** [comment]
#8838是在provider重启后才会有问题并且已经修复，你这个issue和#8838没关系。如果没在配置文件中配置cluster="failsafe"，就走不到同区域调用的逻辑（走不到截图中第85行的逻辑），截图中的debug结果已经能给出答案了。你可以clone[修复后的dubbo_zone_demo](https://github.com/acmday/dubbo_zone_demo%EF%BC%8C) 验证下。

**Comment by chickenlj** [comment]
Check this issue https://github.com/apache/dubbo/issues/7822

**Comment by elvislou** [comment]
@acmday 
cluster="failsafe"参数 ，如何会影响到zone的选择？什么原理？
#8838的问题，我们测试下来，包括跟贴主沟通的结果，在2.7.14里面是没有修复的 。
如果方便的话可以加我微信 elvislou，沟通一下。

**Comment by acmday** [comment]
> @acmday cluster="failsafe"参数 ，如何会影响到zone的选择？什么原理？ 
可以看下上面截图中的第84行代码

**Comment by acmday** [comment]
> @acmday cluster="failsafe"参数 ，如何会影响到zone的选择？什么原理？ 
------------
可以看下上面截图中第84行代码。
如果没有配置cluster="failsafe"，就走不到第85行的代码，从而导致指定zone的功能不起作用。

**Comment by acmday** [comment]
> @acmday cluster="failsafe"参数 ，如何会影响到zone的选择？什么原理？ 
------------
可以看下上面截图中第84行代码。
如果没有配置cluster="failsafe"，clusterInvoker.isAvailable结果为false，走不到第85行的代码，从而导致指定zone的功能不起作用。

**Comment by Meedly** [comment]
cluster="failsafe"也不生效，AbstractClusterInvoker.doSelect，2选1，无法进入ZoneAwareClusterInvoker
dubbo 2.7.22 + nacos 2.1.0

**Comment by Meedly** [comment]
> > @acmday cluster="failsafe"参数 ，如何会影响到zone的选择？什么原理？
> 
> 可以看下上面截图中第84行代码。 如果没有配置cluster="failsafe"，clusterInvoker.isAvailable结果为false，走不到第85行的代码，从而导致指定zone的功能不起作用。

cluster="failsafe"也不生效，AbstractClusterInvoker.doSelect，2选1，无法进入ZoneAwareClusterInvoker
dubbo 2.7.22 + nacos 2.1.0

**Comment by Meedly** [comment]
> > @acmday cluster="failsafe"参数 ，如何会影响到zone的选择？什么原理？
> 
> 可以看下上面截图中第84行代码。 如果没有配置cluster="failsafe"，clusterInvoker.isAvailable结果为false，走不到第85行的代码，从而导致指定zone的功能不起作用。

failsafe配置在多注册中心中，没有生效，这个有什么办法吗？必须每个接口都要配置一下？
