### ISSUE TITLE
[3.0] Can't get timestamp cause loadbalance warm-up invalid

### ISSUE THREAD

**Issue by haoyann** [apache/dubbo#9675]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce this issue
`org.apache.dubbo.rpc.cluster.loadbalance.RandomLoadBalance#needWeightLoadBalance` get URL `timestamp` property is null, As a result, the weight cannot be calculated based on service start time.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/43994656/153420882-1fe41afd-b844-40ea-8d95-58a0406cf50d.png">

**Comment by neighbor-uncleWang** [comment]
Can you provide demo？ zip or Github address

**Comment by haoyann** [comment]
> Can you provide demo？ zip or Github address

1. Use Dubbo 3.0.5 version, start two provider.
2. Start consumer and invoke interface.

**Comment by chickenlj** [comment]
Try add extra key `timestamp` to registry through `dubbo.registry.extraKeys=timestamp`

**Comment by chickenlj** [comment]
If you are using Service Discovery model, aka application-level registry, please also extend `org.apache.dubbo.metadata.MetadataParamsFilter` to customize the keys adding to instance URL

```java
@Activate
public class CustomizedParamsFilter implements MetadataParamsFilter {

    @Override
    public String[] serviceParamsIncluded() {
        return new String[]{"timestamp"};
    }

    /**
     * Not included in this test
     */
    @Override
    public String[] instanceParamsIncluded() {
        return new String[0];
    }
}
```

**Comment by chickenlj** [comment]
This feature is disabled by default starting from 3.0

**Comment by zhengkaifor** [comment]
> This feature is disabled by default starting from 3.0

why disabled this feature
