### ISSUE TITLE
dubbo2.7.14部分功能 zookeeper支持 而nacos不支持

### ISSUE THREAD

**Issue by 18205097282** [apache/dubbo#9679]
在多个注册中心的情况下

用以下代码主动选择对应zone的注册中心 
`RpcContext.getContext().setAttachment("registry_zone", "A");`

和用dubbo.registry.default选择默认注册中心
```
<dubbo:registry address="nacos://192.168.43.152:8840" zone="A"/>
<dubbo:registry address="nacos://192.168.43.152:8848" zone="B" default="false"/>
```

以上两个主动选择注册中心的功能在 注册中心为Zookeeper时正常工作，当注册中心为nacos时不起作用。
Dubbo版本为2.7.14
nacos版本为1.4.3

**Comment by chickenlj** [comment]
在 ZoneAwareClusterInvoker#invoke() 方法中确认一下，该执行过程中 `clusterInvoker.getRegistryUrl()` 的返回值中是否有 zone 标识

**Comment by chickenlj** [comment]
Reopen if necessary

**Comment by chickenlj** [comment]
Check this issue https://github.com/apache/dubbo/issues/7822
