### ISSUE TITLE
why use registry config's group as config center's namespace

### ISSUE THREAD

**Issue by iJIAJIA** [apache/dubbo#9681]
in dubbo version less than 2.7.15
org.apache.dubbo.config.bootstrap.DubboBootstrap#registryAsConfigCenter
```java
private ConfigCenterConfig registryAsConfigCenter(RegistryConfig registryConfig) {
    ...
    // is it possible a misset?
    cc.setNamespace(registryConfig.getGroup());
    ...
}
```
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by BurningCN** [comment]
When `ConfigCenterConfig` is not configured, the configuration information of `RegistryConfig` will be used as the default configuration of `ConfigCenterConfig`. The `group` attribute of `RegistryConfig` and the `namespace` attribute of `ConfigCenterConfig` are at the same level. For example, in the zk node, they are all first-level nodes, such as `/dubbo`

**Comment by chickenlj** [comment]
> private ConfigCenterConfig registryAsConfigCenter(RegistryConfig registryConfig) {
    ...
    // is it possible a misset?
    cc.setNamespace(registryConfig.getGroup());
    ...
}


Actually, it's a legacy issue and we do this mainly for compatibility purposes. `group` was designed in Registry to work for almost the same purpose as `namespace` in most config center products, for example, Nacos. Nacos has both `namespace` and `group`,  with `namespace` being used as a concept to isolate two totally different users or environments while `group` being used as a method to further group configuration items within the same `namespace`.

**Comment by XXMY** [comment]
> > private ConfigCenterConfig registryAsConfigCenter(RegistryConfig registryConfig) {
> > ...
> > // is it possible a misset?
> > cc.setNamespace(registryConfig.getGroup());
> > ...
> > }
> 
> Actually, it's a legacy issue and we do this mainly for compatibility purposes. `group` was designed in Registry to work for almost the same purpose as `namespace` in most config center products, for example, Nacos. Nacos has both `namespace` and `group`, with `namespace` being used as a concept to isolate two totally different users or environments while `group` being used as a method to further group configuration items within the same `namespace`.

the problem is we have to set nacos's namespace id equals to namespace, otherwise, nacos's auth will be failed, cause it only use namespace id in authentication.
