### ISSUE TITLE
consumer can set default protocol for global, such as `dubbo.consumer.protocol=tri`

### ISSUE THREAD

**Issue by rainwolf01** [apache/dubbo#9682]
消费者可否增加默认的protocol配置, 现在每次调用`provider-service`都要配置`protocol = "tri"`：
```
@DubboReference(providedBy = "provider-service", protocol = "tri")
```

## Describe the proposal

期望通过如下配置指定consumer的默认协议：
```
dubbo.consumer.protocol=tri
```
消费者仍使用以下方式调用即可
```
@DubboReference(providedBy = "provider-service")
```

**Comment by BurningCN** [comment]
这样配置即可
dubbo.protocol.name=tri

**Comment by rainwolf01** [comment]
使用版本：dubbo 3.0.5/nacos 2.0.4

### 调用方式一：
这种方式是可以正常调用provider-service并返回预期结果
```
@DubboReference(providedBy = "provider-service", protocol = "tri")
```

### 调用方式二：
使用这种方式配置后，会报异常, 
```
@DubboReference(providedBy = "provider-service")

//配置
dubbo.protocol.name=tri
```

异常信息：
```
2022-02-14 12:53:22.920  WARN [consumer-service,ebfeb5e99cd16341,ebfeb5e99cd16341] 10184 --- [nio-8001-exec-2] o.a.d.r.c.directory.AbstractDirectory    :  [DUBBO] No provider available after connectivity filter for the service com.example.demo.xxxxService all validInvokers' size: 0/ all routed invokers' size: 0/ all invokers' size: 0 from registry 192.168.1.212:8848 on the consumer 192.168.1.98 using the dubbo version 3.0.5., dubbo version: 3.0.5, current host: 192.168.1.98
```

报no provider异常应该是consumer查找时使用了默认的`dubbo`协议，而provider仅支持`tri`协议导致的。

@BurningCN 麻烦看一下，这是bug吗？

**Comment by BurningCN** [comment]
看了下，这的确是一个bug。

背景：单独在`应用级`服务发现模式下（非双注册），提供方以`tri`协议注册。

现象：消费端任何引用方式（比如上面的`@DubboReference`方式）没有指定特定的协议，直接配置`dubbo.protocol.name=tri`。按理说会使用这里配置的`tri`作为默认消费方协议，并能成功发现提供者列表并发起调用。但是实际情况确使用了`dubbo`协议，配置`tri`协议未生效，从而导致找不到提供者列表，导致调用失败。

调试：`addListenerAndNotify->getAddresses` ，消费方提供的`com.example.demo.xxxxService:dubbo` 和 服务发现的 `com.example.demo.xxxxService:tri`无法匹配，从而导致上处错误`No provider available after`

原因：`dubbo.propertis`的配置`dubbo.protocol.name=tri`，没有将值传递到`ReferenceConfig#init`方法里面的`map`对象(`referenceParameters`)中，（前面`@DubboReference`方式能传递成功是因为`ReferenceConfig#appendConfig`方法中这行 `AbstractConfig.appendParameters(map, this)`，会将this即ReferenceConfig的Protocol写到这个map中）。而订阅流程走到`RegistryConfig#doCreateInvoker`方法中 执行`parameters.get(PROTOCOL_KEY) == null ? DUBBO : parameters.get(PROTOCOL_KEY)`会发现`parameters`没有`protocol`参数，导致使用默认的`dubbo`作为缺省值。

// ====================================================================================

我会尝试修复下这个问题

**Comment by rainwolf01** [comment]
@BurningCN   非常感谢，分析的一目了然，向您看齐。
这个修复可以在 `3.0.6` 里发布吗？

**Comment by BurningCN** [comment]
> @BurningCN 非常感谢，分析的一目了然，向您看齐。 这个修复可以在 `3.0.6` 里发布吗？

是否发布这个要看committer的

**Comment by chickenlj** [comment]
我认为当前修改是能通过设置默认protocol解决地址调用问题的，但这里有另外一个 issue 尝试修复了相同的问题：https://github.com/apache/dubbo/pull/9684

考虑到消费端支持消费多个地址的可能性，通过在地址订阅上自动识别 protocol有更好的通用性，参见 https://github.com/apache/dubbo/pull/9684/files#diff-19a0ac3942e6915bb7f34816216ddaa3a8a14ddc604697c338f4a9fa82f7faa1R206  
因此，我认为我们需要 revert 当前修改转而依赖 #9684
