### ISSUE TITLE
Dubbo-compile 编译grpc bug

### ISSUE THREAD

**Issue by melin** [apache/dubbo#9687]
@EarthChen 

dubbo-compiler 0.0.2 0.0.3 有bug，0.0.1 不支持v3的protobuf，需要jprotoc升级到比较新的版本。
https://github.com/quarkusio/quarkus/issues/16451

https://github.com/vert-x3/vertx-grpc/issues/96

**Comment by EarthChen** [comment]
标准的 proto3 似乎就是不支持 optional，在不填的时候就是会填充默认值

**Comment by melin** [comment]
3.15 之后是支持的
https://stackoverflow.com/questions/42622015/how-to-define-an-optional-field-in-protobuf-3/62566052#62566052
[image: image.png]

earthchen ***@***.***> 于2022年2月16日周三 10:23写道：

**Comment by melin** [comment]
我用的是dubbo 2.7.15 版本，如果用compiler 0.0.3 版本，编译报错，能够快速修复支持一下
![image](https://user-images.githubusercontent.com/1145830/154189139-2b7adcda-fc97-4209-a58f-d596a02841ea.png)

**Comment by melin** [comment]
@EarthChen 大概什么时候开发提交到仓库？ 现在有一个项目需要optional，能够快速支持一下？

**Comment by EarthChen** [comment]
拉下pr  本地编译暂时用一下把

**Comment by chickenlj** [comment]
@EarthChen 请一同看一下这个问题是否需要在 3.0 中修复

https://github.com/apache/dubbo/issues/9715
