### ISSUE TITLE
接口级自定义元数据暴露不生效问题

### ISSUE THREAD

**Issue by icodening** [apache/dubbo#9690]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master最新版本
* Operating System version: mac os 10.15.7
* Java version: 1.8

### Steps to reproduce this issue
````java
ServiceConfig<DemoServiceImpl> service = new ServiceConfig<>();
ProtocolConfig protocolConfig = new ProtocolConfig();
protocolConfig.setPort(20880);
protocolConfig.setName("dubbo");
service.setInterface(DemoService.class);
service.setRef(new DemoServiceImpl());
service.setGroup("group");
service.setVersion("1.0");
service.setProtocol(protocolConfig);
//这里我需要添加自定义元数据，但暴露的时候并没有该元数据
service.getServiceMetadata().addAttachment("my-metadata", "99999");

DubboBootstrap bootstrap = DubboBootstrap.getInstance();
bootstrap.application(new ApplicationConfig("dubbo-demo-api-provider"))
        .registry(new RegistryConfig("nacos://127.0.0.1:8848"))
        .service(service)
        .start()
        .await();
````

### Expected Behavior
可以正常注册用户自定义的元数据

### Actual Behavior
如图所示，没有将我配置的元数据注册上，并且查看注释也说该attachments字段的元数据是会被传送至远程的.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/42876375/154305156-85669c3e-6edf-4fde-8687-e7b23a6b2b89.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/42876375/154305617-ce234481-5e22-4647-9b06-97e6c20fe8b0.png">

**Comment by chickenlj** [comment]
> //这里我需要添加自定义元数据，但暴露的时候并没有该元数据
service.getServiceMetadata().addAttachment("my-metadata", "99999")

请尝试使用 `service.getParameters().put("my-metadata", "99999")`

**Comment by chickenlj** [comment]
Reopen if necessary
