### ISSUE TITLE
找不到符号方法 emptyLongList

### ISSUE THREAD

**Issue by kingduxia** [apache/dubbo#9715]
### Environment

* Dubbo version: 2.7.13
* Operating System version: macos 10.14.6
* Java version: 1.8.0_271

### Steps to reproduce this issue

1. 定义好protobuf rpc协议
2. 编译的时候报错，提示找不到符号方法 emptyLongList等

私有项目，暂时没有上传github，已上传rpc描述文件

### Expected Behavior

期望能正常生成stub代码

### Actual Behavior

build时报错

[ERROR]   找不到符号:   方法 emptyLongList()

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```
[RTM.txt](https://github.com/apache/dubbo/files/8131206/RTM.txt)

**Comment by kingduxia** [comment]
已明确发现问题，repeated int64 xx字段类型声明会触发这个问题，调整成repeated string xx可以通过，希望可以修复

**Comment by chickenlj** [comment]
具体报错能否贴一下

**Comment by kingduxia** [comment]
![82e3041a2a54d9ab59e56d43359e8c6](https://user-images.githubusercontent.com/14851589/155968891-c122af9a-6d61-445c-a490-32d0ce3e277d.png)
可以看下这个

**Comment by EarthChen** [comment]
compiler 版本多少？

**Comment by kingduxia** [comment]
![9799ea98d6051365d7c80c32bcc3e62](https://user-images.githubusercontent.com/14851589/155969579-c924e000-aa7d-4315-9de1-a17b20706715.png)
compiler版本是3.7.0

**Comment by EarthChen** [comment]
dubbo.compiler.version

**Comment by kingduxia** [comment]
<dubbo.compiler.version>0.0.2</dubbo.compiler.version>

**Comment by kingduxia** [comment]
是基于最新的dubbo samples 项目，只是替换了protobuf子项目的proto做的测试，测试过程中发现了这个问题

**Comment by kingduxia** [comment]
好的，我再试下看看，稍等，晚点回复

**Comment by kingduxia** [comment]
![image](https://user-images.githubusercontent.com/14851589/155975592-679a84eb-9fec-4f41-b455-ceb1f325e14a.png)
![image](https://user-images.githubusercontent.com/14851589/155975619-4839a471-b00a-4e45-a0d2-902969f4d9d5.png)
我就是在这个项目里增加了RTM.proto，编译就各种报错啊，还有其他的配置项吗，太奇怪了

**Comment by kingduxia** [comment]
![image](https://user-images.githubusercontent.com/14851589/155978185-4df20203-7798-432c-8b5e-5d2c15bd8222.png)

**Comment by kingduxia** [comment]
往上看这个问题像是protobuf版本的问题，但是看pom用的是3.7.1版本的pb，应该已经没这个问题了，我让其他同事尝试，与我的现象是一样的，确定编译过程是正常的吗？不仅仅是生成桩代码

**Comment by EarthChen** [comment]
> 往上看这个问题像是protobuf版本的问题，但是看pom用的是3.7.1版本的pb，应该已经没这个问题了，我让其他同事尝试，与我的现象是一样的，确定编译过程是正常的吗？不仅仅是生成桩代码

确实有问题，我确认了一下问题的原因 就是 protobuf 版本的问题 
`com.google.protobuf.GeneratedMessageV3` 不同版本中的实现类不完全一致
在 protobuf 模块中是3.6.0，缺少`emptyLongList()`方法
本地自测使用3.19.4是ok的
<img width="652" alt="image" src="https://user-images.githubusercontent.com/20179425/156091906-e4c120a5-6c6a-4b94-8146-d000fd6a050c.png">

**Comment by kingduxia** [comment]
![image](https://user-images.githubusercontent.com/14851589/156092192-6b5c7435-3e9e-424a-b2ff-8fc733385943.png)
请问是调整这里的protoc版本吗？

**Comment by EarthChen** [comment]
原有的 protobuf 依赖来自于`dubbo-serialization-protobuf`,直接在项目dependencies中添加 protobuf 依赖覆盖即可

```
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>3.19.4</version>
</dependency>
```

**Comment by kingduxia** [comment]
明白了，我在maven库中搜索发现dubbo-serialization-protobuf依赖的是3.6.0，不过看protoc依赖的又是3.7.1，我还以为这个问题已经修复了，增加依赖之后就可以了，非常感谢，不过还是希望能在dubbo-serialization-protobuf更新pb依赖

**Comment by EarthChen** [comment]
> 明白了，我在maven库中搜索发现dubbo-serialization-protobuf依赖的是3.6.0，不过看protoc依赖的又是3.7.1，我还以为这个问题已经修复了，增加依赖之后就可以了，非常感谢，不过还是希望能在dubbo-serialization-protobuf更新pb依赖

`dubbo-serialization-protobuf` 在3.0分支已经不使用，可能不会进行更新了

**Comment by CrazyHZM** [comment]
dubbo-serialization-protobuf  模块已经被移动到 https://github.com/apache/dubbo-spi-extensions，版本升级可以在该项目下做升级
