### ISSUE TITLE
启动服务消费者出现异常java.nio.channels.OverlappingFileLockException: null

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#9716]
https://github.com/apache/dubbo-admin/issues/875

**Comment by startjava** [comment]
[消费者启动出错.txt](https://github.com/apache/dubbo/files/8139021/default.txt)
@CrazyHZM 华大帮忙看看啊

**Comment by chickenlj** [comment]
报错暂不影响正常功能。只是容灾用的注册中心缓存文件问题

**Comment by startjava** [comment]
有计划修复吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ken.lj ***@***.***&gt;
发送时间: 2022年2月28日 12:19
收件人: apache/dubbo ***@***.***&gt;
抄送: startjava ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [apache/dubbo] 启动服务消费者出现异常java.nio.channels.OverlappingFileLockException: null (Issue #9716)





 
报错暂不影响正常功能。只是容灾用的注册中心缓存文件问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
