### ISSUE TITLE
python 怎么调用dubbo接口（protubuf协议）

### ISSUE THREAD

**Issue by jierongjian** [apache/dubbo#9718]
- 如题
- 当dubbo接口使用的是protobuf协议时，可以使用python传参吗
- 以下是具体场景
- .proto文件已转.py
- url = 'http://127.0.0.1:25271/'
- service = 'com.service.common.api.service'
- interface= 'TestHessianService'
- method = 'testHessian'
- 求求各位大大指导

**Comment by EarthChen** [comment]
建议使用 dubbo 3.0的 triple 协议，python 端直接使用 grpc client 即可

**Comment by zcbbpo** [comment]
要不试试telnet，我们测试也是用python的，他们说用Telnet会很简单。

**Comment by jierongjian** [comment]
> 要不试试telnet，我们测试也是用python的，他们说用Telnet会很简单。

哒咩哟，如果是json，是OK的，但是PB，不行的呢
