### ISSUE TITLE
请问什么场景会出现 Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:com.xxx.MyAsyncService, query？

### ISSUE THREAD

**Issue by itxingfeichen** [apache/dubbo#9730]
https://github.com/apache/dubbo/blob/e8eeddbf42952e7dd4ba4428548f91006900ea5c/dubbo-rpc/dubbo-rpc-dubbo/src/main/java/org/apache/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java#L146

我这边在重启provider的时候在消费端遇到了这个异常，接口本身没有修改。再次重启provider又重新恢复正常，请问这个是什么原因呢？异常信息如下：
org.apache.dubbo.remoting.RemotingException: Fail to decode request due to: java.lang.IllegalArgumentException: Service not found:com.xxx.MyAsyncService, query；

接口为CompletableFuture<xxDto> query(xxRequestDTO name);

**Comment by Tooi6** [comment]
+1
