### ISSUE TITLE
LoadbalanceRules.CONSISTENT_HASH会执行不同的服务提供者

### ISSUE THREAD

**Issue by startjava** [apache/dubbo#9731]
请问，为什么LoadbalanceRules.CONSISTENT_HASH负载均衡策略，我参数传一个a，会执行不同的服务提供者呢，这是什么原理，按理说a的hash值是确定的，不应该出现这样的情况啊。

这是我测试的打印结果：
public String test5() hello5 a port=8086
public String test5() hello5 A port=8085
public String test5() hello5 我 port=8086
public String test5() hello5 是 port=8085
public String test5() hello5 中 port=8086
public String test5() hello5 国 port=8085
public String test5() hello5 人 port=8085
test5_provider1_runtime=4
test5_provider2_runtime=3
test5_provider3_runtime=0

public String test5() hello5 a port=8086
public String test5() hello5 A port=8085
public String test5() hello5 我 port=8086
public String test5() hello5 是 port=8085
public String test5() hello5 中 port=8086
public String test5() hello5 国 port=8086
public String test5() hello5 人 port=8085
test5_provider1_runtime=3
test5_provider2_runtime=4
test5_provider3_runtime=0

发现2次运行时，都是倒数第2个“国”字，有时落到8085上，有时落到8086上，奇怪了。

**Comment by chickenlj** [comment]
consistent hash 的实现目前并不是强制要求落到同一个节点
