### ISSUE TITLE
triple生成的客户端，访问grpc服务

### ISSUE THREAD

**Issue by leyou240** [apache/dubbo#9739]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
背景是这样的，我们有一个其他语言的grpc服务。
然后我们java这边想使用triple协议生成的客户端来访问这个服务。
通过相关文档的阅读，我认为triple也是兼容grpc的

**Comment by EarthChen** [comment]
所以，你的问题是什么

**Comment by leyou240** [comment]
有例子吗？请问

**Comment by EarthChen** [comment]
https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-triple

**Comment by leyou240** [comment]
https://github.com/leyou240/triple-consumer
@EarthChen 请看这个代码，readme中有详细描述。我用go写的grpc服务，用triple生成的客户端，无法访问。

**Comment by EarthChen** [comment]
@leyou240  

我这边已经发现了问题  这是个已知问题，等待我们修改 compiler 插件即可

此时生成的 client 调用的是如下接口
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/20179425/158609240-cfb45201-06fb-4e3c-afcf-d0f28dc0411a.png">

但是实际 grpc 暴露的 url 为如下
<img width="732" alt="image" src="https://user-images.githubusercontent.com/20179425/158609448-bb0072ad-9370-4ee7-800f-138bb8fff87e.png">


造成问题的原因来源于 dubbo 是通过反射生成请求 path，这个在未来版本会跟 stub 的支持一起发布。

## 临时解决方案:

将如下两者保持一致

<img width="785" alt="image" src="https://user-images.githubusercontent.com/20179425/158609984-0914d970-d263-4bd4-9bf8-5e1caf1c404d.png">

**Comment by leyou240** [comment]
目前按照建议，将两者保持一致依然有问题。unknown method sayHello for service helloworld.v1.Greeter
期待新版本的修复~

**Comment by EarthChen** [comment]
@leyou240 

问题是这样的，客户端的方法描述是通过反射获取 class name 和 method name，根据 java 规范，方法名首字母应该小写，但是你的 proto 中方法首字母是大写。

目前 triple 的 client 请求的 url 为 `helloword.v1.Greeter/sayHello`

但你的 grpc server 暴露的method 为 `helloword.v1.Greeter/SayHello`

所以会报上述错误

---

该问题目前只能等待我们在新版本修复。


ps: 如果你用 grpc 的 client 调用 triple 的 server 目前这样是可以的，目前服务端有做兼容处理

**Comment by leyou240** [comment]
是的，我们目前的解决方案确实是用的grpc的client。
麻烦你们修复了，及时通知

**Comment by EarthChen** [comment]
> 是的，我们目前的解决方案确实是用的grpc的client。 麻烦你们修复了，及时通知

如果你的 proto 文件中将方法名改为小写开头目前就是可以的  `SayHello` --> `sayHello`

**Comment by guohao** [comment]
@leyou240 3.0.7 版本已经发布，可以尝试下 stub 方式 https://github.com/apache/dubbo-samples/blob/master/dubbo-samples-triple/pom.xml

**Comment by leyou240** [comment]
@guohao 
<dubbo.compiler.version>0.0.4.1-SNAPSHOT</dubbo.compiler.version>
dubbo-compiler还是SNAPSHOT的，非正式版

**Comment by guohao** [comment]
> 

会在本月发布 3.0.8 的时候同时发布正式版 compiler
