### ISSUE TITLE
使用group作为环境隔离，正常环境访问问题

### ISSUE THREAD

**Issue by IceNiro** [apache/dubbo#9748]
目前使用group做环境隔离
需求：
当迭代环境中未部署对应的服务是，需要去调用稳定环境；若有部署对应服务，则调用迭代环境的提供者。
方案：
1 稳定环境提供者和消费者都没有group标记
2 迭代环境对应提供者的group标记；消费使用通配符 * 
问题：
因为 消费者 使用 通配符 会触发 toMergeInvokerList；但是只存在一个稳定环境的提供者，会默认使用 MergeableClusterInvoker 调用且无法拓展；然后 会出现 ：Not found exported service: */com.xxxx.xxxx.ucenter

可以如何解决这个问题？

**Comment by chickenlj** [comment]
请按照 issue 格式描述下版本与相关环境，方便社区同学跟进

**Comment by IceNiro** [comment]
Environment
Dubbo version: 2.7.7
Operating System version: Linux centos 6.7
Java version: 1.8

使用group做环境隔离
需求：
当迭代环境中未部署对应的服务是，需要去调用稳定环境；若有部署对应服务，则调用迭代环境的提供者。
方案：
1 稳定环境提供者和消费者都没有group标记
2 迭代环境对应提供者的group标记；消费使用通配符 *
问题：
因为 消费者 使用 通配符 会触发 toMergeInvokerList；但是只存在一个稳定环境的提供者，会默认使用 MergeableClusterInvoker 调用且无法拓展；然后 会出现 ：Not found exported service: */com.xxxx.xxxx.ucenter

可以如何解决这个问题？

**Comment by AlbumenJ** [comment]
> 但是只存在一个稳定环境的提供者，会默认使用 MergeableClusterInvoker 调用且无法拓展；然后 会出现 ：Not found exported service: */com.xxxx.xxxx.ucenter

这个可以提供下复现用例吗

**Comment by yswdqz** [comment]
我在dubbo3.04版本成功复现出了这个bug，但是替换成3.07版本之后就已经可以正常使用了。如果是*的话，3.04版本服务端获取的时候也会获得*，而3.07版本会获得一个空字符串。这样就不会出现这个错误。
