### ISSUE TITLE
改为triple协议后，如何验证是走的triple协议呢？日志里看不出来。

### ISSUE THREAD

**Issue by gang0713** [apache/dubbo#9751]
dubbo版本3.0.6
nacos 版本2.0.3

**Comment by rainwolf01** [comment]
用wireshark抓包可以看出来

**Comment by zhaoqf-cq** [comment]
dubbo-admin 直接看就行了吧....

**Comment by gang0713** [comment]
> 用wireshark抓包可以看出来

这样太麻烦，如果日志或启动的时候能看到是用的什么协议最好

**Comment by EarthChen** [comment]
我们考虑一下是否在启动 server 时进行打印

**Comment by gang0713** [comment]
最好是启动的时候就能打印一下使用的什么协议，序列化方式等基本信息。

**Comment by guohao** [comment]
> 我们考虑一下是否在启动 server 时进行打印

可以在 TripleProtocol export 的时候增加一条日志

**Comment by EarthChen** [comment]
> > 我们考虑一下是否在启动 server 时进行打印
> 
> 可以在 TripleProtocol export 的时候增加一条日志

在 `ServiceConfig` 已经进行过打印。这边应该不用再添加了

```java
// org.apache.dubbo.config.ServiceConfig#exportRemote

if (logger.isInfoEnabled()) {
      if (url.getParameter(REGISTER_KEY, true)) {
          logger.info("Register dubbo service " + interfaceClass.getName() + " url " + url + " to registry " + registryURL.getAddress());
      } else {
          logger.info("Export dubbo service " + interfaceClass.getName() + " to url " + url);
      }
  }

```

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/20179425/158538787-1a49c162-f35b-4de2-af36-e525b8788814.png">
