### ISSUE TITLE
Aboot DubboShutdownHook Bug.优雅下线问题！

### ISSUE THREAD

**Issue by kuaile-zc** [apache/dubbo#9760]
* Dubbo version: 2.7.15
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

所以dubbo框架本身是这个逻辑还是有问题
1.服务A->B
当A调用B的时候调用过程中停止A那么JVM退出之前使用hook保证A的请求完成在结束默认时间10s（优雅下线成功）

2.服务A->B
不具备：A调用B的过程中关闭B这个时候A会调用失败。

请问情况2是否是预期的

代码如下DubboShutdownHook中的destroyAll()

![图片](https://user-images.githubusercontent.com/37325510/157612529-3dbc4d08-ad9c-404f-9d19-41d135e4da81.png)

![图片](https://user-images.githubusercontent.com/37325510/157612544-ea3d75c1-706a-43e4-a379-9ca2446e2784.png)

![图片](https://user-images.githubusercontent.com/37325510/157612559-c3d5a190-5ac3-4ca8-9804-b006e6275194.png)

![图片](https://user-images.githubusercontent.com/37325510/157612338-bc97ae11-eebc-42a6-8ad5-576d3535aa23.png)
是先关闭provider，再关闭consumer源码是不是这个流程

So the Dubbo framework itself is the logic of the problem  
1. The service A - > B  
When A calls B, stop A during the call. Then use hook to ensure that A's request completes at the end time of 10 seconds before JVM exits.  
 
2. Service A - > B  
None: If B is closed when A calls B, A fails to call B.

**Comment by chickenlj** [comment]
> 2.服务A->B
不具备：A调用B的过程中关闭B这个时候A会调用失败

从上面的分析来看，一次关闭 registry -> server -> reference 的顺序并没有明显问题

**Comment by chickenlj** [comment]
Reopen if necessary.

**Comment by kuaile-zc** [comment]
> 一次关闭 registry

意思就是
2.服务A->B
不具备：A调用B的过程中关闭B这个时候A会调用失败
这种情况是预期中的？
正常来说B在关闭的时候应该需要检测是否有请求没有执行完成呢。
