### ISSUE TITLE
dubbo 3.0 how to appoint ip and port

### ISSUE THREAD

**Issue by dnlixiaoxin** [apache/dubbo#9761]
当我使用2.7.15的时候 使用  RpcContext.getContext().setObjectAttachment("address", new Address(ip, port)); 进行动态的ip 和 port指定，但是我更新到3.0.5后，这个方法已过期，请问有其他替代方法么

**Comment by dnlixiaoxin** [comment]
社区这么不活跃么 TvT

**Comment by AlbumenJ** [comment]
指定 IP 调用的功能对应到 3.0 的版本正在发布中 https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-cluster-extensions/dubbo-cluster-specify-address-dubbo3 预计本周末可以正式 release

3.0 版本相较 2.7 版本的指定 ip 提供了更全面的能力，文档我们也会在后续补充

**Comment by dnlixiaoxin** [comment]
好的 那我就可以升级到最新的dubbo3了 期待最新的dubbo3的使用文档

**Comment by chickenlj** [comment]
> 好的 那我就可以升级到最新的dubbo3了 期待最新的dubbo3的使用文档

https://github.com/apache/dubbo/issues/9436
请在此issue登记 3.0 用户信息，帮助社区提高版本质量，也方便我们后续更好的提供支持

**Comment by dnlixiaoxin** [comment]
请问这个release了么 文档更新了么

**Comment by xykjlcx** [comment]
> 请问这个release了么 文档更新了么

你好，请问您解决了么

**Comment by dnlixiaoxin** [comment]
> > 请问这个release了么 文档更新了么
> 
> 你好，请问您解决了么
没有 等待官方更新文档中 我现在用的还是2.7    3.0还没文档可以用

**Comment by xykjlcx** [comment]
> > > 请问这个release了么 文档更新了么
> > 
> > 
> > 你好，请问您解决了么
> > 没有 等待官方更新文档中 我现在用的还是2.7    3.0还没文档可以用

我的2.7.8没有Address类了，你用的是2.7.x啊?

**Comment by dnlixiaoxin** [comment]
得 2.7.12版本以上才有&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午3:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/dubbo] dubbo 3.0 how to appoint ip and port (Issue #9761)





    
请问这个release了么 文档更新了么
  
你好，请问您解决了么
 没有 等待官方更新文档中 我现在用的还是2.7    3.0还没文档可以用
   
我的2.7.8没有Address类了，你用的是2.7.x啊?

**Comment by dnlixiaoxin** [comment]
@AlbumenJ  请问文档有么 没有指定实例的调用 3.0一直无法使用
