### ISSUE TITLE
Dubbo3.0.6版本 SPI机制源码： ExtensionLoader loadDirectory（）为啥要重复loadDirectory？

### ISSUE THREAD

**Issue by xjjva520** [apache/dubbo#9766]
private void loadDirectory(Map<String, Class<?>> extensionClasses, LoadingStrategy strategy, String type) {
        loadDirectory(extensionClasses, strategy.directory(), type, strategy.preferExtensionClassLoader(),
            strategy.overridden(), strategy.includedPackages(), strategy.excludedPackages(), strategy.onlyExtensionClassLoaderPackages());
        //以前的路径用从com
        String oldType = type.replace("org.apache", "com.alibaba");

        loadDirectory(extensionClasses, strategy.directory(), oldType, strategy.preferExtensionClassLoader(),
            strategy.overridden(), strategy.includedPackagesInCompatibleType(), strategy.excludedPackages(), strategy.onlyExtensionClassLoaderPackages());
    }
上述代码oldType 和type一致的情况下，loadDirectory会执行两遍，且没有任何意义，为啥要这样做？

**Comment by AlbumenJ** [comment]
type 对应的是 SPI 扩展点，目前全部都是 org.apache.dubbo 的包名的，所以不会有重复加载。

**Comment by xjjva520** [comment]
自定义的SPI扩展点应该就会这样吧

**Comment by xjjva520** [comment]
自定义的SPI扩展点应该就会这样吧

**Comment by chickenlj** [comment]
自定义扩展点报名也会遵循
