### ISSUE TITLE
3.0.5 to 3.0.6 api change cause project using it suffer compile failure, thus CAN cause dependency hell. 

### ISSUE THREAD

**Issue by XenoAmess** [apache/dubbo#9771]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: migrating from 3.0.5 to 3.0.6

### Steps to reproduce this issue

https://github.com/XenoAmess/metasploit-java-external-module/runs/5522599197?check_suite_focus=true

https://github.com/XenoAmess/metasploit-java-external-module/pull/65

### Expected Behavior

DO NOT DELETE EXISTED API WITHIN SAME MAJOR VERSION

PLEASE JUST FOLLOW SEMVER

### Actual Behavior

compile failure.

**Comment by XenoAmess** [comment]
Stronglly suggest you add a BC aware maven plugin like other normal apache project.
An aimed to be widely used library should have sense of responsibility for not causing dependencyn hell.

If you have techniquelly trouble I can offer help.

**Comment by XenoAmess** [comment]
https://garygregory.wordpress.com/2020/06/14/how-we-handle-binary-compatibility-at-apache-commons/

**Comment by AlbumenJ** [comment]
`AbstractCompiler.doCompile(Class<?>,ClassLoader,String,String)` is changed for jdk17 compatible purpose.
I will add it back later.

For such API breaking changes cases, I think we can try to move out those API to a single module which expose to users.

**Comment by XenoAmess** [comment]
> `AbstractCompiler.doCompile(Class<?>,ClassLoader,String,String)`为兼容 jdk17 的目的而更改。 我稍后会添加回来。
> 
> 对于此类 API 重大更改案例，我认为我们可以尝试将这些 API 移出到向用户公开的单个模块中。



> `AbstractCompiler.doCompile(Class<?>,ClassLoader,String,String)` is changed for jdk17 compatible purpose. I will add it back later.
> 
> For such API breaking changes cases, I think we can try to move out those API to a single module which expose to users.

you can move it to some package named 'inner' or something, and add annotations to aware anybody outside this repo do not use it, like what hotspot kids do in jdk.
