### ISSUE TITLE
Dubbo 3.0.5 SPI SpringBean注入问题

### ISSUE THREAD

**Issue by dengcb179** [apache/dubbo#9772]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.5
* Operating System version: Mac
* Java version: 1.8

### Steps to reproduce this issue

1. 自定义Filter中获取SpringBean，代码如下，setTestBean函数没有调用，通过跟踪发现SpringExtensionInjector中的context属性为空
@Activate(group = "consumer")
public class TestFilter implements Filter {

    private TestBean testBean;

    public void setTestBean(TestBean testBean) {
        this.testBean = testBean;
    }

    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) {
        Result result = invoker.invoke(invocation);
        return result;
    }
}

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/8793

**Comment by chickenlj** [comment]
Please check the above issue that has been fixed in 3.0.6 is the same issue as the one that your encountered.

**Comment by chickenlj** [comment]
Reopen if necessary
