### ISSUE TITLE
Dubbo 2.7.7 when i start  10 reference，it cause overflow.

### ISSUE THREAD

**Issue by vio-lin** [apache/dubbo#9781]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: windows
* Java version: jdk8

### Steps to reproduce this issue

1. find  10 server
2.  create 10 client in XML:DubboReference 
3. start client Applicaion

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behaviort
The Client will be started and run will.

### Actual Behavior
It take too much time to start application.

```java
private void prepareDubboConfigBeans() {
        beansOfTypeIncludingAncestors(applicationContext, ApplicationConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, ModuleConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, RegistryConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, ProtocolConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, MonitorConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, ProviderConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, ConsumerConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, ConfigCenterBean.class);
        beansOfTypeIncludingAncestors(applicationContext, MetadataReportConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, MetricsConfig.class);
        beansOfTypeIncludingAncestors(applicationContext, SslConfig.class);
    }
```
`org.apache.dubbo.config.spring.ReferenceBean#prepareDubboConfigBeans`

every ReferenceBean is a factoryBean，before It start it will  
find all ApplicationConfig in SpringContext ，wich will init all factoryBean  
then other ReferenceBean will be init and try to get applicationConfig again.
the application just stop

**Comment by vio-lin** [comment]
我们生产环境上有个用户的应用里面大概有30多个客户端。
升级版本之后直接会有个应用动不了。实际测试中大概大概在
10个客户端左右就会出现超长时间的加载时间。

**Comment by chickenlj** [comment]
请先分析堆栈或内存情况，排查可能的阻塞点

**Comment by chickenlj** [comment]
同时建议尝试升级到最近的2.7.x或3.x版本
