### ISSUE TITLE
upgrade log4jv2 to 2.17.2

### ISSUE THREAD

**Issue by pjfanning** [apache/dubbo#9792]
- [X] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

* https://logging.apache.org/log4j/2.x/security.html
* https://logback.qos.ch/news.html

**Comment by CrazyHZM** [comment]
@pjfanning 
Can commit a patch to the 3.0 branch ？

**Comment by pjfanning** [comment]
@chickenlj I created https://github.com/apache/dubbo/pull/9796
