### ISSUE TITLE
想请教个问题，dubbo是客户端负载均衡，但是可以在服务端进行配置，这个需要怎么理解呢？

### ISSUE THREAD

**Issue by yinwenjian** [apache/dubbo#9803]
我理解客户端负载均衡是在调用方进行的逻辑，来得到需要对哪一台节点进行调用，但是在服务提供者这端的配置有什么作用呢？并且如果服务端多个节点配置的策略不同，这又会怎么处理？

doc：https://dubbo.apache.org/zh/docs/advanced/loadbalance/
![image](https://user-images.githubusercontent.com/41369584/158788091-ae018337-9a93-49bc-83ff-afdd963ec6e3.png)

**Comment by MaiSR9527** [comment]
> 

有配置的优先级的，低优先级的会被覆盖

**Comment by yinwenjian** [comment]
> 

那多个服务端配置的规则不一样，会选择哪种策略呢

**Comment by MaiSR9527** [comment]
> > 
> 
> 那多个服务端配置的规则不一样，会选择哪种策略呢

有篇博客可以看一下 https://www.cnblogs.com/twoheads/p/10131656.html
