### ISSUE TITLE
dubbo 3.0.6 instance bug

### ISSUE THREAD

**Issue by yeatsinheart** [apache/dubbo#9804]
dubbo.registry.simplified=true
dubbo.application.register-consumer=false
应用级服务注册与发现，这两个配置只要存在一个，就无法正常消费服务了

**Comment by wangchengming666** [comment]
@yeatsinheart 可以帮忙提供一个案例方便社区排查吗

**Comment by yeatsinheart** [comment]
> 查

dubbo.registry.simplified=true
dubbo.application.register-consumer=false

**Comment by chickenlj** [comment]
I will try to see why it's the situation

> dubbo.registry.simplified=true
> dubbo.application.register-consumer=false

**Comment by chickenlj** [comment]
I cannot reproduce this issue with the above configurations. Please provide more information and reopen this issue later.

**Comment by chickenlj** [comment]
> dubbo.application.register-consumer=false

对于provider应用不要配置这个配置项
