### ISSUE TITLE
dubbo3 使用grpc协议+[register-mode: instance] 消费者检查生产者失败

### ISSUE THREAD

**Issue by luger1990** [apache/dubbo#9815]
dubbo3 使用grpc协议改为 应用级发现之后，消费者启动失败提示“No provider available for the service”
详见:https://gitee.com/luger/spring-boot-dubbo-grpc/tree/feature_grpc/

nacos版本 2.0.4

**Comment by chickenlj** [comment]
用的什么版本？3.0.6 版本已解决消费端应用级协议地址自动发现和识别的问题。

**Comment by luger1990** [comment]
> 用的什么版本？3.0.6 版本已解决消费端应用级协议地址自动发现和识别的问题。

用的就是3.0.6版本的  我上面的git上有代码

**Comment by chickenlj** [comment]
是 grpc 协议吗？ 目前 grpc 协议不在默认的支持协议列表中，需要在消费端自行配置：
```yaml
dubbo:
   consumer:
      protocol: grpc
```
