### ISSUE TITLE
Directly return the unFinished（注册启动成功但是consumer无法调用provider的方法）

### ISSUE THREAD

**Issue by 631876058** [apache/dubbo#9823]
dubbo version 2.7.15
dubbo.registry.address=nacos://127.0.0.1:8848

consumer 启动的时候也设置了 check=true 启动成功啦，provider和consumer都注册到了nacos上。

但是consumer调用provider方法的时候，报错了

org.apache.dubbo.remoting.RemotingException: Channel NettyChannel [channel=[id: 0x0de7496a, L:/127.0.0.1:53965 ! R:/127.0.0.1:7890]] is inactive. Directly return the unFinished request : Request [id=5, version=2.0.2, twoway=true, event=false, broken=false, data=null]] with root cause

没有找到原因，可以帮忙看下嘛？

**Comment by 631876058** [comment]
开了全局代理的缘故。。。

**Comment by CarsonYue** [comment]
> 开了全局代理的缘故。。。

请问，具体是什么配置？如何解决的~

**Comment by 7471ma** [comment]
请问是网络的全局代理吗
