### ISSUE TITLE
@DubboService配置的timeout未生效

### ISSUE THREAD

**Issue by galfordliu** [apache/dubbo#9832]
### Environment

* Dubbo version: 3.0.6
* Operating System version: centos 7
* Java version: 11.0.2

### Steps to reproduce this issue

1. 启动一个服务，timeout设置为-1，永不超时
2. 调用这个服务中的测试方法，超过1秒再返回
3. 系统会打印超过1000ms的告警信息，timeout未生效。不影响程序使用，但是会打印告警日志。

服务注解配置为
<code>
@DubboService(interfaceClass = IAnalysisADBService.class,
        executes = 200,
        retries = 0,
        cluster = "failfast",
        timeout = -1
)
</code>

在dubbo 2.7.x 版本时一切正常。但是升级到dubbo 3.0.6之后，每次执行一个超过1秒的调用，都会打印告警信息

22-03-23 16:49:47.080 [WARN ] [DubboServerHandler-172.28.53.72:25051-thread-10] o.a.d.r.f.ProfilerServerFilter                     :   [DUBBO] [Dubbo-Provider] execute service com.syyx.tpf.common.bigdata.analysis.facade.IAnalysisADBService:0.0.0#analysisTask cost 1830.049551 ms, this invocation almost (maybe already) timeout. Timeout: 1000ms
client: xxxxxxxxxxxx
invocation context:
input=599;
path=com.syyx.tpf.common.bigdata.analysis.facade.IAnalysisADBService;
remote.application=tpf-bigdata-analysis-cmd-task;
dubbo=2.0.2;
id=6;
interface=com.syyx.tpf.common.bigdata.analysis.facade.IAnalysisADBService;
version=0.0.0;
thread info: 
Start time: 14102589299377092
+-[ Offset: 0.000000ms; Usage: 1830.049551ms, 100% ] Receive request. Server invoke begin.
  +-[ Offset: 0.111898ms; Usage: 1829.823148ms, 99% ] Receive request. Server biz impl invoke begin., dubbo version: 3.0.6, current 

查看了ProfilerServerFilter的代码：
<code>   timeout = invoker.getUrl().getMethodPositiveParameter(invocation.getMethodName(), TIMEOUT_KEY, DEFAULT_TIMEOUT);</code>
判断获取的timeout是默认值DEFAULT_TIMEOUT。但是我在@DubboService上配置的是-1，应该永不超时才对。是3.x版本有什么变化我需要跟着修复吗？还是这是一个bug?

**Comment by wangchengming666** [comment]
I'll FIX it

**Comment by CrazyHZM** [comment]
@galfordliu 
It will be fixed in version 3.0.7.

**Comment by JavaHello** [comment]
还是有问题，我设置了 `@DubboService(timeout = 90000)` 得到异常信息
```log
o.a.d.r.p.InvokerInvocationHandler       [] :  [DUBBO] [Dubbo-Consumer] execute service 120/com.xxx:1.1#xxx cost 60018.808477 ms, this invocation almost (maybe already) timeout. Timeout: 60000ms
invocation context:
path=com.xxx;
remote.application=xxx;
sw8-x=0- ;
sw8-correlation=;
interface=com.xxx;
version=1.1;
timeout=60000;
group=120;
thread info:
Start time: 17548786889708564
+-[ Offset: 0.000000ms; Usage: 60018.808477ms, 100% ] Receive request. Client invoke begin. ServiceKey: 120/com.xxx:1.1 MethodName:xxx
  +-[ Offset: 0.577623ms; Usage: 60015.538807ms, 99% ] Invoker invoke. Target Address: xxx:20888, dubbo version: 3.1.4, current host: xxx, error code: 3-4. This may be ca
```

**Comment by AlbumenJ** [comment]
> 还是有问题，我设置了 `@DubboService(timeout = 90000)` 得到异常信息
> 
> ```
> o.a.d.r.p.InvokerInvocationHandler       [] :  [DUBBO] [Dubbo-Consumer] execute service 120/com.xxx:1.1#xxx cost 60018.808477 ms, this invocation almost (maybe already) timeout. Timeout: 60000ms
> invocation context:
> path=com.xxx;
> remote.application=xxx;
> sw8-x=0- ;
> sw8-correlation=;
> interface=com.xxx;
> version=1.1;
> timeout=60000;
> group=120;
> thread info:
> Start time: 17548786889708564
> +-[ Offset: 0.000000ms; Usage: 60018.808477ms, 100% ] Receive request. Client invoke begin. ServiceKey: 120/com.xxx:1.1 MethodName:xxx
>   +-[ Offset: 0.577623ms; Usage: 60015.538807ms, 99% ] Invoker invoke. Target Address: xxx:20888, dubbo version: 3.1.4, current host: xxx, error code: 3-4. This may be ca
> ```

consumer 侧配置的超时是多少。consumer 侧的配置是优先于 provider 侧的

**Comment by JavaHello** [comment]
> > 还是有问题，我设置了 `@DubboService(timeout = 90000)` 得到异常信息
> > ```
> > o.a.d.r.p.InvokerInvocationHandler       [] :  [DUBBO] [Dubbo-Consumer] execute service 120/com.xxx:1.1#xxx cost 60018.808477 ms, this invocation almost (maybe already) timeout. Timeout: 60000ms
> > invocation context:
> > path=com.xxx;
> > remote.application=xxx;
> > sw8-x=0- ;
> > sw8-correlation=;
> > interface=com.xxx;
> > version=1.1;
> > timeout=60000;
> > group=120;
> > thread info:
> > Start time: 17548786889708564
> > +-[ Offset: 0.000000ms; Usage: 60018.808477ms, 100% ] Receive request. Client invoke begin. ServiceKey: 120/com.xxx:1.1 MethodName:xxx
> >   +-[ Offset: 0.577623ms; Usage: 60015.538807ms, 99% ] Invoker invoke. Target Address: xxx:20888, dubbo version: 3.1.4, current host: xxx, error code: 3-4. This may be ca
> > ```
> 
> consumer 侧配置的超时是多少。consumer 侧的配置是优先于 provider 侧的

```java
        ReferenceBuilder<T> builder = ReferenceBuilder.newBuilder();
        ReferenceConfig<T> reference = builder
                .interfaceName(interfaceName)
                .interfaceClass(interfaceClass)
                .group(group)
                .version(version)
                .generic(generic)
                .retries(retries)
                .timeout(timeout)
                .build();
        String key = SimpleReferenceCache.DEFAULT_KEY_GENERATOR.generateKey(reference);
        SimpleReferenceCache cache = SimpleReferenceCache.getCache();
        T t = cache.get(key, interfaceClass);
```
动态获取的，传入的 timeout 是 90000

**Comment by AlbumenJ** [comment]
> > > 还是有问题，我设置了 `@DubboService(timeout = 90000)` 得到异常信息
> > > ```
> > > o.a.d.r.p.InvokerInvocationHandler       [] :  [DUBBO] [Dubbo-Consumer] execute service 120/com.xxx:1.1#xxx cost 60018.808477 ms, this invocation almost (maybe already) timeout. Timeout: 60000ms
> > > invocation context:
> > > path=com.xxx;
> > > remote.application=xxx;
> > > sw8-x=0- ;
> > > sw8-correlation=;
> > > interface=com.xxx;
> > > version=1.1;
> > > timeout=60000;
> > > group=120;
> > > thread info:
> > > Start time: 17548786889708564
> > > +-[ Offset: 0.000000ms; Usage: 60018.808477ms, 100% ] Receive request. Client invoke begin. ServiceKey: 120/com.xxx:1.1 MethodName:xxx
> > >   +-[ Offset: 0.577623ms; Usage: 60015.538807ms, 99% ] Invoker invoke. Target Address: xxx:20888, dubbo version: 3.1.4, current host: xxx, error code: 3-4. This may be ca
> > > ```
> > 
> > 
> > consumer 侧配置的超时是多少。consumer 侧的配置是优先于 provider 侧的
> 
> ```java
>         ReferenceBuilder<T> builder = ReferenceBuilder.newBuilder();
>         ReferenceConfig<T> reference = builder
>                 .interfaceName(interfaceName)
>                 .interfaceClass(interfaceClass)
>                 .group(group)
>                 .version(version)
>                 .generic(generic)
>                 .retries(retries)
>                 .timeout(timeout)
>                 .build();
>         String key = SimpleReferenceCache.DEFAULT_KEY_GENERATOR.generateKey(reference);
>         SimpleReferenceCache cache = SimpleReferenceCache.getCache();
>         T t = cache.get(key, interfaceClass);
>         if (t == null) {
>             t = cache.get(reference);
>         }
> ```
> 
> 动态获取的，传入的 timeout 是 90000

从上面的日志看就是 ReferenceConfig 里面传人的 timeout 就是 60000 导致的

**Comment by JavaHello** [comment]
谢谢，这个是正确的。在其他地方调用传入了 60000, 另一个地方传入了 90000 获取到了之前的缓存。

**Comment by JavaHello** [comment]
> > > > 还是有问题，我设置了 `@DubboService(timeout = 90000)` 得到异常信息
> > > > ```
> > > > o.a.d.r.p.InvokerInvocationHandler       [] :  [DUBBO] [Dubbo-Consumer] execute service 120/com.xxx:1.1#xxx cost 60018.808477 ms, this invocation almost (maybe already) timeout. Timeout: 60000ms
> > > > invocation context:
> > > > path=com.xxx;
> > > > remote.application=xxx;
> > > > sw8-x=0- ;
> > > > sw8-correlation=;
> > > > interface=com.xxx;
> > > > version=1.1;
> > > > timeout=60000;
> > > > group=120;
> > > > thread info:
> > > > Start time: 17548786889708564
> > > > +-[ Offset: 0.000000ms; Usage: 60018.808477ms, 100% ] Receive request. Client invoke begin. ServiceKey: 120/com.xxx:1.1 MethodName:xxx
> > > >   +-[ Offset: 0.577623ms; Usage: 60015.538807ms, 99% ] Invoker invoke. Target Address: xxx:20888, dubbo version: 3.1.4, current host: xxx, error code: 3-4. This may be ca
> > > > ```
> > > 
> > > 
> > > consumer 侧配置的超时是多少。consumer 侧的配置是优先于 provider 侧的
> > 
> > 
> > ```java
> >         ReferenceBuilder<T> builder = ReferenceBuilder.newBuilder();
> >         ReferenceConfig<T> reference = builder
> >                 .interfaceName(interfaceName)
> >                 .interfaceClass(interfaceClass)
> >                 .group(group)
> >                 .version(version)
> >                 .generic(generic)
> >                 .retries(retries)
> >                 .timeout(timeout)
> >                 .build();
> >         String key = SimpleReferenceCache.DEFAULT_KEY_GENERATOR.generateKey(reference);
> >         SimpleReferenceCache cache = SimpleReferenceCache.getCache();
> >         T t = cache.get(key, interfaceClass);
> >         if (t == null) {
> >             t = cache.get(reference);
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 动态获取的，传入的 timeout 是 90000
> 
> 从上面的日志看就是 ReferenceConfig 里面传人的 timeout 就是 60000 导致的
谢谢，这个是正确的。在其他地方调用传入了 60000, 另一个地方传入了 90000 获取到了之前的缓存。
