### ISSUE TITLE
dubbo 注册中心 group 不生效

### ISSUE THREAD

**Issue by JavaLionLi** [apache/dubbo#9838]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.6
* Java version: 1.8

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/31852897/159896987-a0484def-d643-4fd4-8177-2e817da72883.png)
dubbo配置了与nacos一样的group用于隔离

![image](https://user-images.githubusercontent.com/31852897/159897234-38412200-932b-4b67-8fd9-efc2bd84e63d.png)
nacos注册组正常

![image](https://user-images.githubusercontent.com/31852897/159897151-4b3e8fcf-d72c-4198-8eb0-6cb229c79286.png)
dubbo注册组异常

使用的是应用级注册 注册的应用服务分组无效

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by wangchengming666** [comment]
@JavaLionLi  请问是和 #9557 一样的问题吗？

**Comment by chickenlj** [comment]
> @JavaLionLi 请问是和 #9557 一样的问题吗？

No, it's not the same issue as 9557.

It's the same as https://github.com/apache/dubbo/issues/9427. Please follow updates from here
