### ISSUE TITLE
发布预热、负载均衡权重调整失效

### ISSUE THREAD

**Issue by YsoulM** [apache/dubbo#9841]
环境如下：

* Dubbo version: 3.0.6
* Operating System version: centos 7.5
* Java version: 1.8

具体问题描述：

使用dubbo3.0.3+，请求rpc接口时，拿不到实例的启动时间以及修改后的权重，导致预热和加权失效。

如图：
<img width="908" alt="image" src="https://user-images.githubusercontent.com/13176005/160091149-016939ab-5cfc-40fc-ac3f-53c96f407212.png">

项目启动时间参数获取不到，是因为增加了org.apache.dubbo.registry.ProviderFirstParams，导致获取启动时间参数失败，继而导致发布预热失效。

通过dubbo-admin修改权重后，在这个截图的代码里也拿不到，具体原因没有进行详细测试。

**Comment by haoyann** [comment]
same as this #9675

**Comment by YsoulM** [comment]
>

**Comment by YsoulM** [comment]
> same as this #9675

Thanks♪(･ω･)ﾉ
