### ISSUE TITLE
dubbo3 真的有人上了生产环境吗，怎么测试的时候好多问题,版本dubbo3.0.6

### ISSUE THREAD

**Issue by wujincheng2333** [apache/dubbo#9855]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
Stream模式服务掉线没有抛异常，还能往里面写数据，但是无法接收（服务下线或者调用了complete）
应用级服务发现一直有问题，无法只使用应用级注册，启动参数和配置都无效（nacos注册中心）
偶尔出现 dubbo自动下线，自己调用 shutdown。比较大的几率是服务刚启动的时候调用接口出现的。springboot 2.3.12。springboot的问题？
....

**Comment by guohao** [comment]
@wujincheng2333 这个问题我们会尽快修复

**Comment by chickenlj** [comment]
这是一个triple协议特有问题，并不影响dubbo3运行在其他协议如dubbo2。

请在 https://github.com/apache/dubbo/pull/9858 继续跟进问题进度，感谢反馈。

**Comment by wujincheng2333** [comment]
> 这是一个triple协议特有问题，并不影响dubbo3运行在其他协议如dubbo2。
> 
> 请在 #9858 继续跟进问题进度，感谢反馈。

tri作为dubbo3主推协议，架构升级偏向用新特征，如果不是新特征，感觉还是 2.7.x好
