### ISSUE TITLE
java.lang.NoClassDefFoundError: com/alibaba/com/caucho/hessian/io/ThrowableSerializer

### ISSUE THREAD

**Issue by gaostrong** [apache/dubbo#9860]
Dubbo2.7.14版本
RedHat6.8
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/12680146/160662867-cd6179e4-c8e1-4bfa-b750-746b972f3fb6.png">

**Comment by gaostrong** [comment]
应用启动一段时间内会有这种错误

**Comment by AlbumenJ** [comment]
在出现报错的时候可以尝试用 Arthas 看下这个类是不是存在，同时与其他正常的节点比对下信息
