### ISSUE TITLE
Google Summer of Code 2022 (Idea List)

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#9862]
## Abstract
We are pleased to announce that Apache Dubbo has been accepted as an independent project to attend GSoC 2022, aka Google Summer of Code 2022. Notice that this year's event is open to both college students and graduates who have been working already, you can attend as long as you are interested in Open Source and Coding.

We are still working on the Idea List that we want contributors from GSoC to work on now and they are expected to be available very soon and will be posted to this issue page. Please keep tuned. We hope to provide ideas of as many levels and kinds as possible so contributors of different levels can find a suitable one to participate.

## Idea Lists:
* [Proxyless Mesh](https://github.com/apache/dubbo/issues/9884)  
* [Thin SDK for Proxy Mesh](https://github.com/apache/dubbo/issues/9885)  
* [Observability](https://github.com/apache/dubbo/issues/9886)  
* [Tasks Demo Design and Implementation](https://github.com/apache/dubbo/issues/9887)  
* [Rust language implementation](https://github.com/apache/dubbo-rust/issues/1)

## Notices on Applications.
* Application instruction from Apache：https://community.apache.org/gsoc.html#prospective-asf-mentors-read-this
* Please make sure you leave comments below the Github Issue you are interested in before applying。
* Official website to apply: https//summerofcode.withgoogle.com/

## Other GSoC projects of Dubbo side projects
Click [here](https://github.com/apache/dubbo-awesome/blob/master/summerofcode/gsoc/2022-idea-list.md) to learn about more GSoC projects from some other side projects of Dubbo.

## 基本说明
我们很高兴地宣布 Apache Dubbo 将正式作为独立项目参加 GSoC 2022，既2022 谷歌编程夏令营。需要注意的是，今年的活动同时对在校大学生、毕业生开放，也就是说，只要你对开源和编码感兴趣就可以报名参加。

我们仍在制作 Ideas List，我们希望提供尽可能多的不同程度的 Idea，以便不同层次的贡献者能够找到合适的项目参与其中。请持续关注此 issue，我们将随时在此更新进展。

## 题目列表
* [Proxyless Mesh](https://github.com/apache/dubbo/issues/9884)  
* [Thin SDK for Proxy Mesh](https://github.com/apache/dubbo/issues/9885)  
* [可观测性](https://github.com/apache/dubbo/issues/9886)  
* [服务治理用例设计与实现](https://github.com/apache/dubbo/issues/9887)  
* [Rust 语言实现](https://github.com/apache/dubbo-rust/issues/1)

## 报名须知
* 请务必详细阅读指引：https://community.apache.org/gsoc.html#prospective-asf-mentors-read-this
* 请务必在感兴趣的项目 Github Issue 下方留言。
* Google 官方报名地址：https://summerofcode.withgoogle.com/

## 其他生态项目 GSoC 题目
要了解 Dubbo 生态更多议题，请点[击此查看](https://github.com/apache/dubbo-awesome/blob/master/summerofcode/gsoc/2022-idea-list.md)

> FYI, [Google Summer of Code](https://summerofcode.withgoogle.com/) is a global, online program focused on bringing new contributors into open source software development. GSoC Contributors work with an open-source organization on a 12+ week programming project under the guidance of mentors.

**Comment by chickenlj** [comment]
Please notice that the application phase has ended and we are now working on the evaluation of all the proposals.

**Comment by xhnhill** [comment]
Hi, I found that I missed the application phase. Is there any other way to join this event?
