### ISSUE TITLE
Dubbo 3 还没有适配consul注册中心吗？

### ISSUE THREAD

**Issue by goto456** [apache/dubbo#9901]
使用dubbo 3.0.4时，用consul作为注册中心，发现dubbo-registry-consul的maven依赖包的最新版本是2.7.15，目前还没有3.0版本以上的，使用dubbo-registry-consul 2.7.15时会报错，所以想请问一下是不是dubbo 3 还没有适配consul注册中心？

看到之前有相关的计划 （https://github.com/apache/dubbo/issues/7782）
好像还没有落地是吧？

**Comment by chickenlj** [comment]
这部分工作正在 apache/dubbo-spi-extensions 中开展

**Comment by imgoby** [comment]
现在dubbo-spi-extensions 对consul支持情况如何？
