### ISSUE TITLE
Dubbo 3.0 在启动时，偶尔会出现failed to connect to zookeeper server

### ISSUE THREAD

**Issue by wangbolin** [apache/dubbo#9906]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.5
* Operating System version: window 11
* Java version: 1.8

### Steps to reproduce this issue

1. 升级dubbo3.0
2. 启动应用程序
3. 启动失败，failed to connect to zookeeper server
问题
    BLOCK_UNTIL_CONNECTED_WAIT("blockUntilConnectedWait", 10, Integer::valueOf)
临时解决，在zookeepor地址上附上更大值
&init.timeout=60000&timeout=60000&blockUntilConnectedWait=30

**Comment by AlbumenJ** [comment]
这个应该是 zk SDK 相关的问题，需要检查下 zk 集群的健康度

**Comment by Ruffianjiang** [comment]
相同的问题。同样的几套环境，纯内网虚拟机的环境只能url加参数，其他环境默认配置就能连。从2.6升级到3.0.9。

感谢大佬的方案。
```
zookeeper://localhost:2181?init.timeout=60000&timeout=60000&blockUntilConnectedWait=30
```

**Comment by yangkai9546** [comment]
> 相同的问题。同样的几套环境，纯内网虚拟机的环境只能url加参数，其他环境默认配置就能连。从2.6升级到3.0.9。
> 
> 感谢大佬的方案。
> 
> ```
> zookeeper://localhost:2181?init.timeout=60000&timeout=60000&blockUntilConnectedWait=30
> ```

有效!

**Comment by ilaotan** [comment]
有效，nnd 本地localhost的能连，别的机器就连不上，加大超时时间后，连zk初始化会卡20秒

**Comment by seqwait** [comment]
我这边是改了 服务器的DNS 和 hostname /etc/hosts 就完全没问题了
