### ISSUE TITLE
RMI协议同一个服务提供者中,分组和版本不起作用

### ISSUE THREAD

**Issue by 12482** [apache/dubbo#9913]
### 系统版本

* Dubbo version: 2.7.15
* Java version: 1.8

### 问题出现的步骤
1. dubbo客户端和服务端采用RMI协议交互
2. 在服务端某个接口有两个实现类,他们版本相同,标记成不同的组: g1, g2
3. 在客户端,无论调用哪个组,最终都会调用到g2这个一个组的接口
4. 同样的,服务端两个某一接口两个实现类标记成不同的版本,在客户端分别调用不同版本的接口,最终也会定位到服务端的同一个版本

**Comment by xielongfei** [comment]
i will solve it

**Comment by xielongfei** [comment]
我看了相关代码，存在你说的版本、分组无效问题。

原因在于RMI 绑定到Registry注册表时name（远程引用对象关联的名称）不能重复，如果重复会报AlreadyBoundException异常。dubbo-rpc-rmi模块中用的RmiServiceExporter对象完成绑定操作，其replaceExistingBinding属性默认为true，所以会调用rebind方法进行重绑定，name相同会覆盖。

目前dubbo中绑定的name值是接口全限定名，未包含分组和版本标识。
例如：rebind(org.apache.dubbo.demo.DemoService, obj);
如果加上分组和版本值：rebind(g1/org.apache.dubbo.demo.DemoService:v1，obj)，则name唯一，Consumer远程调用时会找到指定的存根对象进行调用。

本地已测可行。我在RmiProtocol类中调整了doRefer()、createExporter()代码后，版本和分组已生效。

但我切换3.0.7分支后，发现dubbo-rpc-rmi相关模块已移除。所以我不清楚这是不是bug。

**Comment by 12482** [comment]
> 我看了相关代码，存在你说的版本、分组无效问题。
> 
> 原因在于RMI 绑定到Registry注册表时name（远程引用对象关联的名称）不能重复，如果重复会报AlreadyBoundException异常。dubbo-rpc-rmi模块中用的RmiServiceExporter对象完成绑定操作，其replaceExistingBinding属性默认为true，所以会调用rebind方法进行重绑定，name相同会覆盖。
> 
> 目前dubbo中绑定的name值是接口全限定名，未包含分组和版本标识。 例如：rebind(org.apache.dubbo.demo.DemoService, obj); 如果加上分组和版本值：rebind(g1/org.apache.dubbo.demo.DemoService:v1，obj)，则name唯一，Consumer远程调用时会找到指定的存根对象进行调用。
> 
> 本地已测可行。我在RmiProtocol类中调整了doRefer()、createExporter()代码后，版本和分组已生效。
> 
> 但我切换3.0.7分支后，发现dubbo-rpc-rmi相关模块已移除。所以我不清楚这是不是bug。

调整doRefer()、createExporter()我在本地也尝试过，基本功能没问题，但是不确定是否会带来其他影响，dubbo2.7 是否还会有相关的补丁发布呢，dubbo3的rmi协议应该是要重新适配 https://github.com/apache/dubbo/issues/7781，

**Comment by CrazyHZM** [comment]
Thanks for your feedback.
The 2.7.x version can still be patched in the master branch in this repository, and the latest version 3.x has moved the rmi protocol to the following projects:
https://github.com/apache/dubbo-spi-extensions
You can patch this project in this project.

**Comment by xielongfei** [comment]
> Thanks for your feedback. The 2.7.x version can still be patched in the master branch in this repository, and the latest version 3.x has moved the rmi protocol to the following projects: https://github.com/apache/dubbo-spi-extensions You can patch this project in this project.

sorry, my first commit missed a class.

**Comment by xielongfei** [comment]
> Thanks for your feedback. The 2.7.x version can still be patched in the master branch in this repository, and the latest version 3.x has moved the rmi protocol to the following projects: https://github.com/apache/dubbo-spi-extensions You can patch this project in this project.

I submitted a pr, please check, thanks.
