### ISSUE TITLE
dubbo 2.7.15 org.apache.dubbo.registry.integration.RegistryDirectory#mergeUrl 

### ISSUE THREAD

**Issue by skipper-sj** [apache/dubbo#9922]
系统版本
- Dubbo version: 2.7.15
- Java version: 1.8

问题描述：
org.apache.dubbo.registry.integration.RegistryDirectory#mergeUrl
```java
// The combination of directoryUrl and override is at the end of notify, which can't be handled here
        this.overrideDirectoryUrl = this.overrideDirectoryUrl.addParametersIfAbsent(providerUrl.getParameters()); // Merge the provider side parameters
```
在2.7.15版本中，此处代码如果存在dubbo.tag时，如：provider-A1 tag为null  ，provider-A2 tag为grey时，consumer tag为null时，仍然路由到tag为grey的服务。
在最新的代码中，此处已排除dubbo.tag的参数，希望2.7.15中，也做该处理。

**Comment by wangchengming666** [comment]
pls try latest version

**Comment by skipper-sj** [comment]
> pls try latest version

最新版本已经为3.0，2.7.15版本已经是最新的2.x版本，也是去年年底刚更新的，希望还是能在最新的2.x版本中间进行更新。

**Comment by baymax55** [comment]
请问删除dubbo.tag后,替代tag的解决方案有吗

**Comment by chickenlj** [comment]
Already fixed in 2.7.16
