### ISSUE TITLE
Broken KEYS link on download page

### ISSUE THREAD

**Issue by sebbASF** [apache/dubbo#9924]
The page https://dubbo.apache.org/en/blog/2020/05/18/past-releases/ which is linked from the download button on the front page
has the following URL for KEYS:

https://downloads.apache.org/PROJECT/KEYS

Please fix the URL.

(The corresponding Chinese page appears to have the correct KEYS link)

**Comment by wangchengming666** [comment]
fix by https://github.com/apache/dubbo-website/pull/1068
