### ISSUE TITLE
关于dubbo3.0.6应用级注册发现问题,若消费者配置 dubbo.application.service-discovery.migration=APPLICATION_FORCE ,且服务端配置  dubbo.application.register-mode=instance   会出现  No provider

### ISSUE THREAD

**Issue by rottenmu** [apache/dubbo#9930]
server.port=17722
spring.application.name=dubbo3-service-provider
dubbo.application.name=dubbo3-service-provider
dubbo.registry.parameters.namespace=ns-38n9xvnd
dubbo.registry.address=nacos://ip:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
dubbo.metadata-report.sync.report=true
dubbo.application.register-mode=all
dubbo.application.logger=slf4j

server.port=17723
spring.application.name=dubbo3-service-pconsumer
dubbo.application.name=dubbo3-service-consumer
dubbo.registry.parameters.namespace=ns-38n9xvnd
dubbo.registry.address=nacos://ip:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=-1
dubbo.application.register-mode=instance
dubbo.application.service-discovery.migration=APPLICATION_FIRST
dubbo.application.logger=slf4j
dubbo.application.enable-file-cache=false
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

**Comment by AlbumenJ** [comment]
检查下是不是元数据中心有问题，强制走应用级找不到地址的需要考虑是否为应用级地址注册/获取失败或者元数据注册/获取失败。

**Comment by rottenmu** [comment]
是要加上这些配置吗  
dubbo.config-center.address=nacos://ip:8848
dubbo.metadata-report.address=nacos://ip:8848

**Comment by iwangjie** [comment]
> 是要加上这些配置吗 dubbo.config-center.address=nacos://ip:8848 dubbo.metadata-report.address=nacos://ip:8848

请问是吗？
