### ISSUE TITLE
Will provide distributed config service? Something like spring cloud config service

### ISSUE THREAD

**Issue by zhuxiujia** [apache/dubbo#994]
dubbo 是否提供了 类似spring cloud 的 config service服务？
spring cloud config service 可以 从git仓库提取.properties 文件，用注解@Value读取。毕竟配置应该独立为一个服务，而不是分布于每个服务中。

我这边做了一个 曲线救国的思路，使用dubbo 协议定义一个config service ，读取配置application.properties后把 整个配置文件转换为byte[] 再转换为ISO-8859-1的文本压缩并且加密后，返回给 消费服务，消费服务再把文本转换为对应的文件名application.properties
这样可以做到 .

**Comment by Spring8848** [comment]
用个第三方的来解决吧，比如apollo或disconf

**Comment by chickenlj** [comment]
We are considering adapt to some open-source config solutions. But only aimed to meet the dynamic config requirement relating with dubbo, like routing rules, dynamic service governance,  rate limit policies, etc.. 
The application level configuration solution is not what we concerned, like the spring cloud config service you mentioned above. This also reflects that this two frameworks are focusing on different areas, Spring Cloud are trying to provide a complete solution for microservice architecture (including RPC and Service Govermance), while dubbo only focus on RPC and Service Govermance.
