### ISSUE TITLE
V2.7.8 分组聚合 指定group用逗号分割

### ISSUE THREAD

**Issue by kingxjs** [apache/dubbo#9947]
难道不可以这样？所以我应该怎么写？

```
No provider available for the service sms,answer/com.test.service.SmsSendService
```
consumer：
![image](https://user-images.githubusercontent.com/17718227/164187578-76fea94d-5484-4337-b7ee-2c2a95e80a1d.png)

provider：
![image](https://user-images.githubusercontent.com/17718227/164187365-0506b77a-8227-4b20-9f5f-ca25cec6db8d.png)
![image](https://user-images.githubusercontent.com/17718227/164187408-5b267ec1-ef4d-4027-89a8-a9b9a9364fc6.png)

nacos:
```
providers:com.test.service.SmsSendService::sms
providers:com.test.service.SmsSendService::answer
```
另外，group="*" 也是相似的错误

**Comment by AlbumenJ** [comment]
单个分组订阅是正常的吗

**Comment by lizhichao999** [comment]
dubbo.service.group = sit
dubbo.reference.group = sit

**Comment by chickenlj** [comment]
I reproduced this issue with the latest 3.0.11 release and I will try to fix it.

**Comment by chickenlj** [comment]
Consumer side wildcar group match has been supported in 3.1.x and newer releases.
