### ISSUE TITLE
> @hongyu-zxj Does it still exist in the latest version 2.7.15

### ISSUE THREAD

**Issue by hongyu-zxj** [apache/dubbo#9961]
> @hongyu-zxj Does it still exist in the latest version 2.7.15
@CrazyHZM 能说一下之前的版本具体的问题是什么吗？在哪里做了修复？

_Originally posted by @hongyu-zxj in https://github.com/apache/dubbo/issues/7554#issuecomment-1107680109_

**Comment by CrazyHZM** [comment]
You can discuss it under the original issue.
