### ISSUE TITLE
Dubbo3 以上版本是否支持metrics

### ISSUE THREAD

**Issue by habertzk** [apache/dubbo#9971]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
我最近使用dubbo3.0.5版本的metrics功能，在dubbo admin后台服务访问服务统计功能是遇到了和[#9338](https://github.com/apache/dubbo/issues/9338)一样的问题，如果新版本已弃用，那新版本该如何使用类似的监控功能？

**Comment by chickenlj** [comment]
3.x 版本会继续支持 Metrics 功能，当前可能是和 dubbo-admin 适配有问题，我们将在 3.0.9 版本中继续跟进

**Comment by chickenlj** [comment]
project in progress https://github.com/orgs/apache/projects/121
