### ISSUE TITLE
网关应用泛化调用dubbo性能差

### ISSUE THREAD

**Issue by ppj19891020** [apache/dubbo#9973]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
dubbo版本：2.7.8 至 3.0.7
场景：网关应用泛化调用dubbo每次都会走到ClassUtils.forName，由于是泛化调用，每次都是找不到method

压测火焰图：
![](https://cdn.jsdelivr.net/gh/ppj19891020/picgo-images/202204261746676.png)

备注：
dubbo在2.7.1版本中发现也有这个代码，但是没有走这个ClassUtils.forName，还未找到原因

建议：
目前你们新版本是provider方增加了CommonConstants.GENERIC_WITH_CLZ_KEY启动参数来设置这个class属性，但是消费者还是通过获取class去找到class，只要能获取到class就需要走ClassUtils.forName。
建议能不能消费侧也可以增加一个启动参数来设置需不需要通过ClassUtils.forName

**Comment by chickenlj** [comment]
> 建议能不能消费侧也可以增加一个启动参数来设置需不需要通过ClassUtils.forName

将在。3.0.9 版本中予以支持
