### ISSUE TITLE
Dubbo Telnet Unsupported command: ls

### ISSUE THREAD

**Issue by egalee** [apache/dubbo#9983]
### Environment

* Dubbo version: 3.0.7
* Operating System version: windows10
* Java version: jdk1.8

### 复现方法

1. telnet 127.0.0.1 20880
2. dubbo>ls
Dubbo Telnet Unsupported command: ls

**Comment by chickenlj** [comment]
Please use the specific QOS port for QOS commands, by default is `22222`
