### ISSUE TITLE
过滤器中获取到的sidekey参数总是provider

### ISSUE THREAD

**Issue by songxiaosheng** [apache/dubbo#9985]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: windows10+Linux
* Java version: 1.8

### Steps to reproduce this issue

1. 自定义过滤器从invoke对象中获取sidekey
2. 无论是消费者还是提供者获取到的sidekey都是provider

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

自定义过滤器中消费者从invoke中获取到的sidekey参数应该是consumer,这个在低版本时候是正常的

### Actual Behavior

1. 自定义过滤器从invoke对象中获取sidekey
2. 无论是消费者还是提供者获取到的sidekey都是provider

**Comment by chickenlj** [comment]
你好，我这边没能复现此问题，请提供更多的问题及如何复现的细节。

`getParameter("side")` and `getSide()` 都没问题，你是用的 `getParameters()` 么?

**Comment by chickenlj** [comment]
在 3.0 中 `getParameters()` 是完整的返回了 provider 侧的原始数据，因此 side=provider，这点在设计上是和 2.7 有明显差异的。
 
如是在 `getParameters` 上遇到的问题，建议调整为 `getSide()`，受限于 3.0 的设计理念，getParameters 的行为很难调整。

**Comment by songxiaosheng** [comment]
我来贴一下我测试的代码: 如下代码是我做测试的过滤器不论消费者还是提供者拿到的都是provider

`package link.elastic.dubbo.spi;

import org.apache.dubbo.common.constants.CommonConstants;
import org.apache.dubbo.common.extension.Activate;
import org.apache.dubbo.rpc.*;

@Activate(group = {CommonConstants.PROVIDER,CommonConstants.CONSUMER})
public class MyFilter implements Filter {
    @Override
    public Result invoke(Invoker<?> invoker, Invocation invocation) throws RpcException {
        String sideKey = invoker.getUrl().getParameter("side");

        return invoker.invoke(invocation);
    }
}
`
再贴个图证明下我的Debug过程

![Uploading image.png…]()

**Comment by chickenlj** [comment]
请注意忽略 Dubbo 内置的 “MetadataService”。
