### ISSUE TITLE
How to unregister provider with QOS command in dubbo 3.x?

### ISSUE THREAD

**Issue by YoungHu** [apache/dubbo#9986]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

## Ask your question here
As we know, `offline` command can unregister provider from register center. it work fine in `interface` mode, but when I setting register-mode to `instance`, i can see provider application name register to nacos as service name, but `offline` command dose not work(is work when register-mode is `interface`). is also no work with `offlineApp` command. so below is my two questions:
1. what offlineApp command means and what function does it provide?
2. which QOS command can unregister provider with `instance` register-mode?

PS: I made a extension name `offlineMetadata` which like `publishMetadata` command, just change `ServiceInstanceMetadataUtils.refreshMetadataAndInstance(applicationModel)` to `ServiceInstanceMetadataUtils.unregisterMetadataAndInstance(applicationModel)` , and find it work to unregister application from register center.

**Comment by chickenlj** [comment]
Please check the following log on the Consumer side to see if the address notification was blocked by the default 'empty address notification protection'  policy.

`Ignore empty notify urls for subscribe url` 
or 
`received empty address list with no EMPTY protocol set,`

**Comment by chickenlj** [comment]
Basically, offline, offlineInterface and offlineApp works as blow:
* offline can be used to offline both interface level and instance level address from the registry center
* offlineInterface will only offline interface level address from the registry center
* offlineApp will only offline interface level address from the registry center

Distinguishing offlineInterface and offlineApp can be useful in multiple registration scenario.

**Comment by YoungHu** [comment]
> Please check the following log on the Consumer side to see if the address notification was blocked by the default 'empty address notification protection' policy.
> 
> `Ignore empty notify urls for subscribe url` or `received empty address list with no EMPTY protocol set,`

already check nacos and consumer side. after invoke `offline` cmd, instance not unregister from registry center, and consumer side haven't get any notify.

**Comment by chickenlj** [comment]
Is it working now with 3.0.8 version?

**Comment by YoungHu** [comment]
> Is it working now with 3.0.8 version?

it's not work with 3.0.8
