### ISSUE TITLE
@DubboService注解为什么不支持serialization

### ISSUE THREAD

**Issue by wuhaoqiang1** [apache/dubbo#9989]
### Environment

* Dubbo version: 3.0.6
* Operating System version: window10
* Java version: 1.8

### Steps to reproduce this issue

官方案例，设置序列化使用的是xml
    <dubbo:service serialization="protobuf" interface="org.apache.dubbo.demo.DemoService"
                   ref="demoServiceImpl"/>

我的项目使用的是注解，然而在DubboService注解中没有找到serialization参数，难道是不支持吗？

**Comment by chickenlj** [comment]
注解目前遵循的是最小化可用原则，如果需要配置更多的配置项，请配合 dubbo.properties 使用。

**Comment by chickenlj** [comment]
比如，如果配置接口级别的 serialization 则在 dubbo.properties 文件中增加以下配置：
```properties
dubbo.service.{your-full-package-service-name}.serialization=xxx
```

**Comment by wuhaoqiang1** [comment]
> 比如，如果配置接口级别的 serialization 则在 dubbo.properties 文件中增加以下配置：
> 
> ```ini
> dubbo.service.{your-full-package-service-name}.serialization=xxx
> ```

注解和xml应该只是配置方式的不同吧，<dubbo:service>配置和@DubboService注解应该对应起来才合理吧，xml支持而注解不支持很容易让人误解

**Comment by chickenlj** [comment]
> 注解目前遵循的是最小化可用原则，如果需要配置更多的配置项，请配合 dubbo.properties 使用。

请参考我们这里的设计原则。注解从可用性和易于管理的角度，不会提供所有属性的支持。

对于序列化这个参数，建议是通过 `dubbo.provider.serialization=xxx` 设置全局默认值。

**Comment by wuhaoqiang1** [comment]
> > 注解目前遵循的是最小化可用原则，如果需要配置更多的配置项，请配合 dubbo.properties 使用。
> 
> 请参考我们这里的设计原则。注解从可用性和易于管理的角度，不会提供所有属性的支持。
> 
> 对于序列化这个参数，建议是通过 `dubbo.provider.serialization=xxx` 设置全局默认值。

懂了，感谢回答，谢谢

**Comment by wuhaoqiang1** [comment]
官方提供了其他解决方案

**Comment by yang101yang20230912** [comment]
dubbo.service.{your-full-package-service-name}.serialization=xxx 这个配置项只支持rpc接口请求参数的序列化吗？如何配置单个接口的请求参数和响应报文的序列化方式？
