### ISSUE TITLE
[3.0] warm-up feature don't work at instance register-mode

### ISSUE THREAD

**Issue by YoungHu** [apache/dubbo#9990]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.0.7
* Operating System version: mac os
* Java version: JDK8

### Steps to reproduce this issue

1. set both provider and consumer side as `register-mode=instance` and ` service-discovery.migration=FORCE_APPLICATION`
2. debug at `AbstractLoadBalance.getWeight` method
3. start 2 providers and start 1 consumer to invoke.
4. `AbstractLoadBalance.getWeight` always return 100.

### Expected Behavior
new start node weight should less than 100

### Actual Behavior
got weight value=100

### What Reason
if want warn up feature work correct, the key parameter is `timestamp` which in `urlParam`.  `DubboServiceAddressURL` fill urlParam but 'InstanceAddressURL' not, so when dubbo register with instance mode, warn up can't work.

![image](https://user-images.githubusercontent.com/7418602/166858211-47224b65-9021-4fd3-9128-1438f59b036a.png)
![image](https://user-images.githubusercontent.com/7418602/166858350-6459156d-bfbc-4873-a0ce-cf0ec49a14ee.png)
![image](https://user-images.githubusercontent.com/7418602/166858399-df6354b2-3d6a-40c9-ab6b-1d2cf741f190.png)

**Comment by chickenlj** [comment]
This is a known issue. `timestamp` key has currently been removed from previous 3.0 releases for performance seeking. We are considering keep `timestamp` as disabled by default and give users the way to enable it if necessary.

**Comment by YoungHu** [comment]
> This is a known issue. `timestamp` key has currently been removed from previous 3.0 releases for performance seeking. We are considering keep `timestamp` as disabled by default and give users the way to enable it if necessary.

`timestamp` key how to effect performance?

**Comment by chickenlj** [comment]
> > This is a known issue. `timestamp` key has currently been removed from previous 3.0 releases for performance seeking. We are considering keep `timestamp` as disabled by default and give users the way to enable it if necessary.
> 
> `timestamp` key how to effect performance?

The timestamp value will change every time one instance restarts.

**Comment by chickenlj** [comment]
One way to do that is by extending `MetadataParamsFilter` SPI as below;
```java
@Activate
public class CustomizedParamsFilter implements MetadataParamsFilter {
    @Override
    public String[] instanceParamsIncluded() {
        return new String[]{"timestamp"};
    }
}
```
