### ISSUE TITLE
Why use /ConfigCenterConfig as default config center PATH_KEY？

### ISSUE THREAD

**Issue by YidanWang** [apache/dubbo#9991]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

为什么默认设置动态配置中心的path为`ConfigCenterConfig.class.getName()`（149行，dubbo 2.7.15和3.0+）？我的注册中心和配置中心是同一个zk地址，应该如何设置呢？
https://github.com/apache/dubbo/blob/431f2a7e77a2bd5decea67575bb288533157c5a0/dubbo-common/src/main/java/org/apache/dubbo/config/ConfigCenterConfig.java#L143-L155

**Comment by chickenlj** [comment]
> 我的注册中心和配置中心是同一个zk地址，应该如何设置呢？

一般不用关心 path，直接设置好配置中心的地址就好了。
